### ISSUE TITLE
Total uptime counter wraps

### ISSUE THREAD

**Issue by mattbuford** [BiglySoftware/BiglyBT#1]
On the statistics page, under the transfers tab, there is a counter for total uptime.  This counter wraps after 10+ years.  285291010 is a working value, while 322032610 wraps.  Somewhere in-between those two values is the cutoff where the counter wraps.  Both values are 29 bits long so it isn't an obvious bit length issue:

10001000000010011001000000010
10011001100011101001111100010

Also oddly, the counter wraps back to 1m0s instead of 0.

To reproduce, edit your BiglyBT.statistics file, find the number after "uptimei", change it to 322032610, then start BiglyBT.  Go to stats and transfers, then watch the total uptime and session uptime.  Total uptime will be 10y77d until session uptime hits exactly 1m, and at that time total uptime will wrap to 1m.

System details:

ava 1.8.0_131 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4757, win32
Windows 10 v10.0, amd64 (64 bit)
B1.0.0.0/4 az3

**Comment by TuxPaper** [comment]
heh, there was code from 2004 explicitly zeroing out values over 10 years.
Fix will be in B02.  Assuming Github works the way I think it does, you can mark it closed once B02 is out and you can determine it's fixed :)

As for why it's an additional 77 days, it's most likely the mark_time value for you is 77 days.

**Comment by mattbuford** [comment]
I can confirm that this is working as expected in 1.0.2.0.  My total uptime is now "10y 362d".  Thanks!
