### ISSUE TITLE
Embedded Media Player - Doesn't display some non-english characters on non-utf8 subtitle

### ISSUE THREAD

**Issue by ghost** [BiglySoftware/BiglyBT#10]
*(Screenshot Removed by Admin)*

> "Summer, bir dahaki sefere bir Colorkiya
> eko yuvasında saklandığımızda..."

Missing 
"ı,ğ"

*(Screenshot Removed by Admin)*

> - Ne demek olduğunu bilmiyorsun bile!
> - Çünkü ezikler gidip araştırır...

"ş,ı"

**EDIT: If i change subtitle encode to "UTF -8" it shows non-english characters**

2. Can we seek video duration while streaming torrent? I mean i want to download and start half on torrent
(7:00-14:00) not (0:00 - 14:00)

3-) I can't open vlc with streaming button.
![3](https://user-images.githubusercontent.com/26485077/29003961-0bf92fe4-7ac9-11e7-884d-ba23fc7c2a36.JPG)

**Comment by TuxPaper** [comment]
Glad you figured out the encode issue.

Can you explain what happens (or doesn't happen) when you switch to VLC for playback?
