### ISSUE TITLE
Blurry systray icon on linux running KDE Plasma desktop environment

### ISSUE THREAD

**Issue by glaubersm** [BiglySoftware/BiglyBT#1000]
* OS and version linux, Arch Linux
* For *nix: Desktop Environment KDE Plasma 5.15.4

Java 10.0.2 (64 bit)
  Oracle Corporation
/usr/lib/jvm/java-10-openjdk

SWT v4922, gtk/3.24.8, zoom=100, dpi=96
Linux v5.0.7-arch1-1-ARCH, amd64 (64 bit)
B1.9.0.0/4 az3

As we can see in the screenshot belo, biglybt icon in systray looks blurry.

![biglybt](https://user-images.githubusercontent.com/15967631/56141409-23528880-5f73-11e9-9846-27bf43358734.png)

**Comment by TuxPaper** [comment]
I mentioned a couple of things to try in #1001.  One of them might make the icon clearer.  There's one linux distro where 50% of the time it'll show only 1/4 of the icon, so I guess you have the full icon going for you :)

**Comment by glaubersm** [comment]
This bug persists with BiglyBT 2.0.

**Comment by glaubersm** [comment]
Why was this issue closed? Tray icon of BiglyBT 2.3.0.0 is still blurry on Arch + Plasma 5.18.3.

**Comment by parg** [comment]
mass close due to inactivity perhaps

**Comment by o0nd7ots** [comment]
This still persists on 3.5.0.0. I think this might be the icon's fault

**Comment by glaubersm** [comment]
This bug persists with version 3.5. Could anyone reopen please?

**Comment by parg** [comment]
I've changed the icon in 3501_B26 - can you try that out?

No doubt this will cause outrage amongst the users that were happy with the old one...

**Comment by glaubersm** [comment]
Can you tell me how to install 3501_B26  please?

**Comment by glaubersm** [comment]
The new icon is better.

![trayicon](https://github.com/BiglySoftware/BiglyBT/assets/15967631/e5d2852b-f724-42d1-8186-89778f4150eb)

**Comment by parg** [comment]
That'll do then
