### ISSUE TITLE
Dialog to confirm content deletion is cut off on Gnome 3.32

### ISSUE THREAD

**Issue by glaubersm** [BiglySoftware/BiglyBT#1003]
OS and version linux, Arch Linux
For *nix: Desktop Environment Gnome 3.32

Java 10.0.2 (64 bit)
Oracle Corporation
/usr/lib/jvm/java-10-openjdk

SWT v4922, gtk/3.24.8, zoom=100, dpi=96
Linux v5.0.7-arch1-1-ARCH, amd64 (64 bit)
B1.9.0.0/4 az3

Select a torrent., press delete key.

![bitlybt4](https://user-images.githubusercontent.com/15967631/56149065-112c1680-5f82-11e9-875d-7daefeaa8d30.png)

**Comment by lislei** [comment]
I see the same on Windows, so this might not be OS spesific.

```
SWT v4922, win32, zoom=100, dpi=144
Windows 10 v10.0, amd64 (64 bit)
B1.9.0.1_B11/4 az3
```
![bilde](https://user-images.githubusercontent.com/13136714/56423547-de00c480-62ac-11e9-8d01-abe2e1c7d29e.png)
