### ISSUE TITLE
"Files" tab show files from an already deleted torrent

### ISSUE THREAD

**Issue by glaubersm** [BiglySoftware/BiglyBT#1004]
OS and version linux, Arch Linux
For *nix: Desktop Environment KDE Plasma 5.15.4
Java 10.0.2 (64 bit)
Oracle Corporation
/usr/lib/jvm/java-10-openjdk

SWT v4922, gtk/3.24.8, zoom=100, dpi=96
Linux v5.0.7-arch1-1-ARCH, amd64 (64 bit)
B1.9.0.0/4 az3

Steps to reproduce:
select a torrent that is being downloaded
press delete key (a dialog to confirm content deletion shows up)
click "Delete from computer" button
click "Files" tab
Result: "Files" tab shows the files from the just deleted torrent

**Comment by glaubersm** [comment]
This behavior is still reproducible with BiglyBT v2.3.0.0.
Why was this issue closed?

**Comment by parg** [comment]
mass close due to inactivity perhaps
