### ISSUE TITLE
Disabled Socks Proxy is Still Checked

### ISSUE THREAD

**Issue by dbareis** [BiglySoftware/BiglyBT#1007]
The following picture shows the disabled proxy host being checked and the reported error.  I enabled the proxy, added "disabled." to the front of the hostname and disabled it again before closing and reopening the app and taking this picture.  In case it's not obvious I don't expect disabled entries to be checked and warning reported.

_I can't see how to add a picture, since pictures are mentioned will try to add via comment on this issue..._

I'm on Windows 10 64 bit and BiglyBT:

```
Java 1.8.0_201 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_201

SWT v4922, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B1.9.0.0/4 az2
```

**Comment by dbareis** [comment]
![Disabled Socks Proxy is Still Checked](https://user-images.githubusercontent.com/295230/56182450-a2b88880-6055-11e9-98b5-1602b9e44f25.png)

**Comment by parg** [comment]
Fixed in next beta, thanks!

**Comment by Taurean75** [comment]
In my case, I get a warning that says "Socks server is requesting authentication..." It's not enabled however.
