### ISSUE TITLE
FileNotFoundException For PIA settings.json

### ISSUE THREAD

**Issue by Poorman65** [BiglySoftware/BiglyBT#1012]
* Windows 10 Pro 1803 - 17134.320
* BiglyBT Version Number: 1.9.0.0
* PIA: v1.1.1 (build 02545)

Getting many errors logged where BiglyBT is looking for the PIA settings.json file at location "C:\Program Files\pia_manager\data\settings.json".
The file is actually at "C:\Program Files\Private Internet Access\data\settings.json"

PIA did a significant update recently and may have changed the folder name. Not sure if this is something I need to manually update somewhere in the options or in some other manner.
[debug_1.log](https://github.com/BiglySoftware/BiglyBT/files/3098867/debug_1.log)

**Comment by Swampgirl** [comment]
Dear Poorman65,
If you have not already, check out the exchange under issue labelled:
PIA Manager, Where is it After PIA Upgrade? ".PIA_Manager.app now considered legacy software" 

I am not sure it will help your json notification. If not, Try manually upgrading PIA, BBT, and Java. You may have to do uninstall Java, perform a manual update/upgrade of BBT and PIA, then download latest Java version.
