### ISSUE TITLE
Feature Request - Enable Clipboard in Panels

### ISSUE THREAD

**Issue by Poorman65** [BiglySoftware/BiglyBT#1014]
* Windows 10 Pro 1803 - 17134.320
* BiglyBT Version Number: 1.9.0.0
I often have the need to copy information from panels, such as a file path or name. It would be nice if this were enabled. Right now, you cannot select text.

**Comment by parg** [comment]
tried right-clicking on them and 'copy to clipboard' ?

**Comment by Poorman65** [comment]
Ahh! That does work. Thanks! It's an unusual behavior though.
