### ISSUE TITLE
Failed to install DNS manager...

### ISSUE THREAD

**Issue by WishedGit** [BiglySoftware/BiglyBT#1017]
Hello.

Since around B09 or B10 (not sure, not that long) I've been getting the following warning whenever I start BiglyBT:

"Failed to install DNS manager
This will impact functions such as forced DNS resolution prevention with SOCKS
Error: DNS SPI not loaded"

I've been through the settings and I can't remember changing anything. Doesn't appear to be impacting torrent functionality or performance though.

* Windows 10 Home 1809 17763.437
* Java 12 (64 bit)
* B1.9.0.1_B11/4 az3

**Comment by parg** [comment]
That's related to https://bugs.openjdk.java.net/browse/JDK-8192780

**Comment by WishedGit** [comment]
Thanks parg; didn't realise this was a Java error.

Downgraded (upgraded?) from Java 12 to latest Java 8 (u211 x64) and this fixed it.

**Comment by parg** [comment]
Yup, we obviously want to move up from 8, and almost everything works fine with 12..., but we have limited resources and would rather Java brought the ability to intercept DNS calls!

**Comment by Gatak** [comment]
Hi @parg Is there any downside to use Java 12, other than the DNS error? I use my own DNS server and don't use SOCKS.
Java 8 is rather old too, and afaik on my system, BiglyBT is the only that requires it.

Thanks :)

**Comment by parg** [comment]
I don't know of any issues apart from that DNS one - it is more for trapping attempts to use the 'virtual' .i2p / .onion suffixes than SOCKS itself

**Comment by Gatak** [comment]
OK great. Thank you. The Java bug is still open, I wonder if Oracle intends to fix it :/

**Comment by sergiomb2** [comment]
AFAIK also we can't compile BiglyBT with Java 9 or 11[1]  . we have multiple examples on internet  ( error: package sun.net.spi.nameservice does not exist)  [2] . 

[1]
[ERROR] Failed to execute goal io.takari.maven.plugins:takari-lifecycle-plugin:2.0.0:compile (default-compile) on project biglybt-core: 16 error(s) encountered:
[ERROR] /builddir/build/BUILD/BiglyBT-2.7.0.2/core/src/com/biglybt/core/util/spi/AENameServiceDescriptor.java:[39:31] package sun.net.spi.nameservice does not exist
[ERROR] /builddir/build/BUILD/BiglyBT-2.7.0.2/core/src/com/biglybt/core/util/spi/AENameServiceDescriptor.java:[40:31] package sun.net.spi.nameservice does not exist
[ERROR] /builddir/build/BUILD/BiglyBT-2.7.0.2/core/src/com/biglybt/core/util/spi/AENameServiceDescriptor.java:[41:35] package sun.net.spi.nameservice.dns does not exist
[ERROR] /builddir/build/BUILD/BiglyBT-2.7.0.2/core/src/com/biglybt/core/util/spi/AENameServiceDescriptor.java:[60:20] cannot find symbol
[ERROR]   symbol: class NameServiceDescriptor


[2]
https://community.jitsi.org/t/jitsi-dev-building-jitsi/13197 
https://github.com/beeLin/beeLin-java/issues/5

**Comment by parg** [comment]
Just exclude the file from the build

**Comment by SteelRodent** [comment]
I had to up Java to 17 to run Minecraft, so now I'm getting this error too. It does appear to prevent I2P from working. Otherwise Bigly's still fully functional.

Since Java is now up to 18 and Oracle plan to seize support for Java 8 from next month, I wonder if there is a workaround to get I2P working until you're able to come up with a permanent solution?

**Comment by parg** [comment]
Java 8 is supported until at least 2030

https://www.oracle.com/java/technologies/java-se-support-roadmap.html

Where did you see that support was ending from next month?

Install a separate Java 8 runtime and use that for BiglyBT?

I2P shouldn't be prevented from working with the DNS manager issue, what errors are you seeing?

**Comment by sergiomb2** [comment]
> Java 8 is supported until at least 2030

by this article [1] openjdk 1.8 is "only" supported until Nov 2026 

[1]
https://access.redhat.com/articles/1299013
