### ISSUE TITLE
Subscription stop/pause size

### ISSUE THREAD

**Issue by Macronot** [BiglySoftware/BiglyBT#1018]
With auto download enabled. Is is possible to add a subscription in a stopped/paused state >= (x)MB. I would like to be able to approve downloads of large sizes before they can be downloaded. 

I have tried setting "Only start if <= MB" in Options - subscriptions to 5120 but files larger that this still continue to download.

**Comment by parg** [comment]
You should be able to do this with tags.

Create a Tag (call it 'Subs' for example) and then right-click on it in the sidebar and select 'execute-on-assign' and select 'Stop' or 'Pause'

Right-click on your subscription(s) and assign this tag to them.

This should automatically assign all downloads from the subscription(s) to the tag and stop them.

Then create a second tag, say 'SubsGo', and set its execute-on-assign to 'Start'

Go to the tag settings for this tag and set its tag constraint to be

hasTag( "Subs") && sizemb < x

This second tag should then cause all subscription downloads < x MB to start and leave the others stopped/paused

**Comment by parg** [comment]
I created the tags with a 100MB limit - unzip and open the .biglybt file in BiglyBT.

[substags.zip](https://github.com/BiglySoftware/BiglyBT/files/3100069/substags.zip)

You would still need to set the subscription(s) to assign to tag 'Subs' yourself though.

**Comment by Macronot** [comment]
Thanks parg, 
That worked perfectly.
