### ISSUE TITLE
Bithub is not downloading torrents after clicking download file.

### ISSUE THREAD

**Issue by ImUrDaddi** [BiglySoftware/BiglyBT#1019]
Bithub is not downloading torrents after clicking download file.

* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment

**Comment by parg** [comment]
Can't comment on specific sites but you can always manually download the .torrent file and then open it in BiglyBT (likewise copy magnet links and paste them into the search area or open-torrent window). Obviously not as smooth as things working automatically but sometimes sites have 'smart' stuff that prevents BiglyBT from downloading things internally (e.g. CloudFlare fronting)
