### ISSUE TITLE
Edit HTTP seeds not working

### ISSUE THREAD

**Issue by trancephorm** [BiglySoftware/BiglyBT#1024]
When adding HTTP seed manually to torrent in getright of webseed section, it's just not accepted: in Sources tab of a torrent, under HTTP seeds sections, it still is unavailable, but it's added.

**Comment by parg** [comment]
Thanks, fixed in next beta

**Comment by parg** [comment]
B13 has been released, please close the issue if your problem is resolved

**Comment by trancephorm** [comment]
Please tell me from where can I download beta version? Also, I think I saw an option in BiglyBT to do self-updates to beta version but I can't find it right now.

**Comment by parg** [comment]
Go to the Help menu and join the Beta Program
