### ISSUE TITLE
PIA Manager, Where is it After PIA Upgrade? ".PIA_Manager.app now considered legacy software" 

### ISSUE THREAD

**Issue by Swampgirl** [BiglySoftware/BiglyBT#1031]
I am posting this again because PIA has undergone a huge update. I do not believe the .pia_manager.app exists anymore. The new files available are (that I can find): pia-daemon, pia-openvpn, pia-openvpn-helper, pia-support-tool, and Private Internet Access. Please update the directions for connecting to PIA within BiglyBT. 
.pia_manager.app is now considered legacy software according to the PIA site:
"Locate the "pia_manager" folder  (*this is the file folder for the legacy application and may not exist anymore)"

Thanks!

* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment

**Comment by TuxPaper** [comment]
Just downloaded the new PIA Manager on OSX.  Bah, humbug.

Thanks for creating a new bug report.

Manually entering your username and password in Tools->Options->Plugins->VPN Helper->"Private Internet Access" should give it access to the open port.  If you are using the latest beta, there's a bug that will prevent that from working.. the next beta will allow it again.

**Comment by Swampgirl** [comment]
Thank you TuxPaper! So I do not have to browse for the PIA manager.app file for PIA to work properly, once the bug is fixed?

**Comment by TuxPaper** [comment]
Next version I'll probably remove that field.  It doesn't do much good.  I found a way to get the username with the new app, but I may not have a way to grab the password anymore (which means users will have to enter it if they want the port forwarding linked)

**Comment by Swampgirl** [comment]
I have always entered my username and password, for the record. Thank you for your help!

**Comment by Swampgirl** [comment]
Hi TuxPaper!
By next version, do you mean 21? Just wondering b/c I would like to use my subscription and BBT, otherwise I cannot use the BBT software.  Just wanted to know if I should buy another VPN subscription, despite already having paid PIA for another 200+ days.

**Comment by Swampgirl** [comment]
Dear Tux,
I just reread this, and it may come off as snotty; it is not meant to.  I am just trying to figure out what I need to do.
Thank you for your help,
Warm Regards

**Comment by TuxPaper** [comment]
Sorry, I don't know what BBT stands for. :/

Are you on the BiglyBT beta? If you are, you should have received a VPN Helper plugin update (v5.8) in the last couple of days that may have fixed the PIA issues.  If not, join the beta :)
