### ISSUE TITLE
Transport encryption/obfuscation links to an empty page

### ISSUE THREAD

**Issue by WPFilmmaker** [BiglySoftware/BiglyBT#1038]
Fiddling with the countless Bigly options I clicked on 'Please visit here for details' under 'Transport encryption/obfuscation' which opens this link in the browser:

https://wiki.biglybt.com/wiki.php?q=Avoid_traffic_shaping

However the page says "BiglyBT does not have a wiki page for this topic yet"

Can this be fixed?

Lubuntu 16.04.3
Java 1.8.0_191 (64 bit)
1.8.0.0
LXDE

**Comment by parg** [comment]
You can always refer to the first hit returned by Google (for me anyway) - the link to the Vuze wiki
