### ISSUE TITLE
Tag Overview - When Exceeded - Stop, not working

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#1040]
![BiglyBT Tag Settings](https://user-images.githubusercontent.com/37715552/56997467-ddeaa980-6b75-11e9-8852-1ed0945ae9ef.jpg)

In the above, the 'When exceeded' is set to Stop. It is not working for torrents that are set to _'Forced Seeding'_.  I have the 'Execute of Assign' set to Forced Seeding as I want them to keep seeding to keep the Ratio UP.  See the last 2 torrents below for items that exceed the 10:1 ratio I have set as the Target Share Ratio.

![BiglyBT Tag Settings Torrents](https://user-images.githubusercontent.com/37715552/56997603-58b3c480-6b76-11e9-85ed-73b44d97d88b.jpg)

I would like to see the 'When Exceeds' work for all states. But would also like to see the actions expanded from the current 'Queue, Pause, Stop' to include the additional options of 'Archive', 'Remove from Library' and 'Delete from Computer'.  While I only want the Delete choice for my needs, I see the others as valid choices for other users.

- Windows 10 1809
- Biglybt Beta 1.9.0.1_B14
- Java 1.8.0_211 (64 bit)

**Comment by parg** [comment]
Use the 'first priority seeding' on the Tag and an appropriately high 'max active torrents' under Tools->Options->Queue instead of 'force start'. The 'force start' option it almost always a manual indication that the download should run until you manually stop it.

I'll look at the other request.

**Comment by parg** [comment]
B15 has additional 'when exceeds' options
