### ISSUE TITLE
Multitracker Torrent Issue

### ISSUE THREAD

**Issue by egortech** [BiglySoftware/BiglyBT#1041]
**System Info**
Oracle Corporation
c:\program files\biglybt\jre
SWT v4922, win32, zoom=100, dpi=144
Windows 10 v10.0, amd64 (64 bit)
B1.9.0.0/4 az3

There are some problems with torrent with have more that one tracker. When application restart these torrents have tracker with queued status and don't become active unless they have been activated manually. 

Another bugs related with such torrent occurs when you add additional trackers for torrent via different file with same hash, then added trackers also have queued status and they can't be activate manually without restart torrent downloads.

Also sometimes applications stop send information to tracker. Next update interval in tracker list in detail panel frozen on some value like 0:00:20 and you need to update tracker manually to send data there.

**Comment by parg** [comment]
BiglyBT follows http://www.bittornado.com/docs/multitracker-spec.txt mainly and tries to respect the 'min interval' reported by trackers. Trackers will remain 'queued' if you are connected to sufficient peers and therefore there is no need to hit a new tracker.

**Comment by egortech** [comment]
As I said sometimes timer to refresh tracker stick on some value and don't countdown, so refreshing process stopping.

Is there some option to change this behaviors? Mainly in important for announce (general) tracker, that tracking stats.

**Comment by parg** [comment]
In my experience the only trackers that attempt to track stats are those belonging to private torrents and these tend to have a single tracker - if they have multiple trackers for load balancing then it is up to the private tracker to manage things internally. 

There is no way to change the behaviour from that that is currently implemented.
