### ISSUE TITLE
Beta Update Failure?

### ISSUE THREAD

**Issue by LuvBiglyBT** [BiglySoftware/BiglyBT#1046]
Java 1.8.0_181 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4922, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B1.9.0.1_B10/4 az3

Since Beta10 checking for Updates, even with all IP filtering disabled, comes back with "No updates available to you.)  Until now, disabling PeerBlock resolved tghis rpoblem.  It no longer does so and disabling IP filter in Bigly also changes nothing.  Any thoughts?

**Comment by PrototypeZero** [comment]
Try turning off the "Update Anonymously" if its selected under Interface>Start.  Worked for me in the past on both non-beta and beta updates.

**Comment by LuvBiglyBT** [comment]
Thanks PrototypeZero.  I actually had it switched off already due to a previous encounter with the same issue.  Figured I would try turning it on and voila...was able to download.  Over the years I have found this needs to be turned on sometimes and off other times.  Have no idea why, but thanks for bringing it back to my memory.

**Comment by JBitte** [comment]
yes, I followed "Update Anonymously" uncheck and worked. Probably points to a rights issue in the online repository
