### ISSUE TITLE
"Not Authorized" for remote access

### ISSUE THREAD

**Issue by rigadoog** [BiglySoftware/BiglyBT#1047]
I'm getting an error on the TV I want to control remotely during pairing, saying:
"**Error Connecting**
Not Authorized. It's possible that the remote client is in View-Only mode."

I verified that none of my firewalls are blocking my laptop or my router. I have a Deco M9 Plus router, and I couldn't find a uPNP-specific setting but it seems like that's enabled - it's a very new router. Both the TV and my laptop are connected to my same home Wi-Fi. I typed in the pairing access code correctly, and I'm fairly sure the laptop is not in view-only mode, I definitely didn't enable it.

* Windows 10 connecting to latest Android TV
* Latest BiglyBT

**Comment by TuxPaper** [comment]
If I'm reading this correctly, you are trying to connect to your Win10 machine from Android TV?

Make sure these two checkboxes are checked 
![image](https://user-images.githubusercontent.com/725353/57184015-da06a200-6e69-11e9-92d9-6ece3a2ffa12.png)

The two test links on that screen only check Internet access to BiglyBT (ie.  Access from outside your LAN).  A LAN only test URL to try on your Win10 machine would be:

http://127.0.0.1:9091

Enter vuze/<Paring Code> and see if you can connect properly locally.  If you can, try again on Android.

**Comment by rigadoog** [comment]
I got it to work from my phone to the TV since it only gave me a QR code, which is fine, I was trying to do it backwards before.

Now my issue is that my external HDD connected to the TV - which is where I want to download to - is Read-Only to BiglyBT, and I don't see anywhere to allow it to write in the permission settings. Frustrating.
