### ISSUE TITLE
Program not picking up seeds/peers

### ISSUE THREAD

**Issue by intelligentfox** [BiglySoftware/BiglyBT#1048]
<!--
Hi. A lot of times I need to restart the program to refresh the seeds/peers when downloading a file. I tried force download, stopping and starting download but its not working. For example the download picks up no seed/peers and after restarting the program it picks up a lot. 

Are there any settings available to fix this. It did not happen with the Vuze version.

* OS and version Windows7 64 bit Service Pack 1
* BiglyBT Version Number: B1.9.0.0/4 az3
* For *nix: Desktop Environment

**Comment by parg** [comment]
You need to specify your issue in detail - this doesn't give anything to go on.
