### ISSUE TITLE
Someone help me with this error - Linux installation of BiglyBT, something related to Internal Browser.

### ISSUE THREAD

**Issue by trancephorm** [BiglySoftware/BiglyBT#1049]
https://i.imgur.com/WXUpoWT.png

Thanks!

**Comment by parg** [comment]
Did you ensure that WebKit is installed, as per the message?

**Comment by trancephorm** [comment]
Was surfing a bit but I can't find how to install that. Seems like it's some component of browsers, and I even have Konqueror installer already. Can it be installed from Ubuntu packages?

**Comment by parg** [comment]
Use the package manager to install 

libwebkitgtk-3.0

(Muon package manager on Kubuntu for example)

**Comment by trancephorm** [comment]
Works. Thanks! For Ubuntu 18.04 with KDE Plasma it was enough to install libwebkitgtk-3.0-0, that's the exact package name, if you type without -0, it woudl install libwebkitgtk-3.0-common and libwebkitgtk-3.0-dev also, but it seems they are not needed.
