### ISSUE TITLE
I2P or not I2P

### ISSUE THREAD

**Issue by csylvain** [BiglySoftware/BiglyBT#105]
I have the I2P Helper. In the BiglyBT options (Tools -> Options -> Connection), I2P network is checked/enabled.
But when I load a magnet link (maybe also if I loaded a torrent file?), in the subsequent "Open Torrent Options" window, down in the "Tracker, Peer & Connection Options" section, I2P network **is not checked/enabled**.
Is I2P on or is it not?
ps: B1.0.2.1_B18

**Comment by parg** [comment]
The networks shown in the open-torrent-options dialog are derived from what is in the torrent - if it has public trackers then the public network will be enabled etc. For magnets, if the magnet has the (non-standard) &net=I2P (for example) magnet argument then I2P will be used to download the magnet. There is a default setting for magnets under Tools->Options->Plugins->Magnet  Plugin

The defaults under Tools->Options->Connection are used when no hints are available (as far as I can remember anyway...)

**Comment by csylvain** [comment]
yup, I2P also already enabled in the Magnet Handler plugin.  ok then, didn't know a magnet link or torrent could do network selection(s)/deselection(s).
