### ISSUE TITLE
Outbound Connection to 213.152.162.89

### ISSUE THREAD

**Issue by Taurean75** [BiglySoftware/BiglyBT#1050]
Occasionally on start, it tries to connect to 213.152.162.89 which Malwarebytes reports as Trojan.

Are you guys from Netherlands?

Please elaborate.

**Comment by parg** [comment]
We're not based in NL, our servers (e.g. version.biglybt.com) run on Amazon Web Services in the US. The 'Mainline DHT' plugin has a few bootstrap servers configured but from what I can tell they don't resolve to that address.

Do you have a port number the connection is being made to?

**Comment by Taurean75** [comment]
The port number is 2122.

**Comment by parg** [comment]
Another possibility is the Tor plugin - it is used to attempt connections via the Tor network when failures to connect via the public IP network occur.

**Comment by Taurean75** [comment]
Ah, that makes sense.

**Comment by Taurean75** [comment]
Now it tried to connect to 91.192.100.3 through the port I've assigned even though Tor is disabled. Again, Malwarebytes reports it to be Trojan / malware.

**Comment by Taurean75** [comment]
213.152.162.165 through the internal port. See https://www.abuseipdb.com/check/213.152.162.165

I don't think it's Tor.

**Comment by parg** [comment]
There are a lot of things that cause BiglyBT to make external connections - Tor, I2P, DHT, MLDHT, Trackers,  Peer Exchange, Web Seeds... and we can't account for these or whether they will be flagged as bad addresses.

If you think that BiglyBT contains malware then by all means go over the source - https://github.com/BiglySoftware/BiglyBT - and built it yourself.

**Comment by Taurean75** [comment]
I was just asking a question. I wasn't saying it's a malware.

The thing is that one of the reported actually belongs to a website tagged as deceptive by Google.

**Comment by uzerus** [comment]
The main problem of abuseipdb like services is false-positives. If my opinion about malvare detection software matters, i'll recommend the same using eset software (nod32 - trial f.e.). You shouldn't have many problems as in other.

Tell if it helps, maybe malwarebytes are not torrent-friendly :smile:

**Comment by Taurean75** [comment]
@uzerus --
Damn, I paid for 2 years already. Oh, well.

Anyway, try going to http://91.192.100.3/ which apparently is a deceptive website. It's blocked by Google.
It's odd that BiglyBT tried to connect to that site.
