### ISSUE TITLE
Ctrl+left mouse click doesn't deselect a torrent's details sub-tab

### ISSUE THREAD

**Issue by Xemnarth** [BiglySoftware/BiglyBT#1053]
Ctrl+left mouse click stopped deselecting any torrent other than in Library view. IIRC, this was possible under all views.

**Comment by parg** [comment]
Which view isn't it working it? Works for me in Tag and Category views

**Comment by Xemnarth** [comment]
I mean it doesn't deselect the torrent's details in the sub-tabs

**Comment by Xemnarth** [comment]
any update? this thing is really annoying me

**Comment by Xemnarth** [comment]
Cool, it's better now. I noticed there is a new: deselecting a torrent in this fashion doesn't remove the number indicator from some tabs (see below snip for better understanding)
![Annotation 2019-10-01 205836](https://user-images.githubusercontent.com/6406869/65983699-31e41c00-e48f-11e9-805b-fbf260c9cd1f.png)

**Comment by TuxPaper** [comment]
Indicator not being removed will be fixed in next beta, although the other views with indicators (Files) might have similar issue which I will eventually look into

**Comment by Xemnarth** [comment]
Very nice, thank you
