### ISSUE TITLE
[Feature Request] Removal Folder Based on Tag

### ISSUE THREAD

**Issue by PrototypeZero** [BiglySoftware/BiglyBT#1064]
Would be useful if there was an option to set a directory for each tag for when you remove a torrent from the library (not delete it completely).

Just like when a torrent completes you can set a folder to move the torrents to based on its tag, instead of placing everything in one folder as it is now (if you have the option set of course).

So for example, an torrent with an Audio tag the contents could for example be in 
"C:\P2P\Incomplete\Audio" (when downloading)
"C:\P2P\Library\Audio" (when complete and seeding)
"C:\P2P\Removed\Audio" (when removed from library)

and a Video torrent contents could be set to be in 

"C:\P2P\Incomplete\Video" (when downloading)
"C:\P2P\Library\Video" (when complete and seeding)
"C:\P2P\Removed\Video" (when removed from library)

Instead of the current situation where all removed files are placed for example in
"C:\P2P\Removed"
and have to be be manually moved if you want to sort them (breaking the link in the library history to the files location in the process).

**Comment by parg** [comment]
It'll be in the next beta, thanks

**Comment by PrototypeZero** [comment]
Thanks a lot! 👍
