### ISSUE TITLE
[BiglyBT Tray Icon]->Tray Options->More Doesn't Work

### ISSUE THREAD

**Issue by dbareis** [BiglySoftware/BiglyBT#1065]
Clicking "more" doesn't do anything, I'd expect BiglyBT to be restored and/or the relevant options to be shown.

Windows: 10 64 Bit 
Bigly About: Java 1.8.0_201 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_201

SWT v4922, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B1.9.0.0/4 az2

![BiglyBT-Tray Options-More Doesn't work](https://user-images.githubusercontent.com/295230/57825462-58f0c880-77e2-11e9-869c-ba814a32e66f.png)

**Comment by parg** [comment]
It opens the Tools->Options->Interface view within BiglyBT - this has the additional tray options in it. It doesn't bring BiglyBT into an active state though, I'll look into that.

**Comment by dbareis** [comment]
I've just checked and it does open the settings but doesn't restore the app.  Apart from fixing that it could be improved by adding a text filter "tray" to highlight the entries.

**Comment by parg** [comment]
will do - check B22 when published
