### ISSUE TITLE
Keep Metadata

### ISSUE THREAD

**Issue by mppdidi** [BiglySoftware/BiglyBT#107]
Is it possible to keep Metadata after a restart / crash ?

Thanx

**Comment by parg** [comment]
you mean a magnet download that hasn't completed?

**Comment by mppdidi** [comment]
Yes

**Comment by parg** [comment]
check next beta

**Comment by mppdidi** [comment]
seems it creates a more 'nested' file metadata download of metadata download ....
Doesn't seem right ?

**Comment by parg** [comment]
hmm, explain in more detail please!

**Comment by mppdidi** [comment]
I was unable to reproduce this - so I'm closing this for now.
