### ISSUE TITLE
Seems like BiglyBT is occasionally changing big files when they're seeded from 2 different torrents.

### ISSUE THREAD

**Issue by trancephorm** [BiglySoftware/BiglyBT#1070]
For some time now, I'm trying to catch the cause of big files changed (corrupted pieces in log). I setuped auditing in Linux with and here's the entry from the log. Right now I don't have time to analyze this entry, but it seems that biglybt binary executable is involved. I didn't ever analyze this type of log, maybe it is some other thing that changed file. 

Here to supply any information that would be of help solving this potential BiglyBT bug, I'm fighting with corrupted file pieces for pretty long now, btw I'm pretty sure my hard disk is ok - SMART monitoring fully healthy, and such errors are not being made on smaller files, just on big files (this one is around 50 GB) which are seeded from 2 torrent files which are reading from same seed data. I suppose this shouldn't be the problem because the file should be opened just for reading.

Filename of corrupted filed is pyc_-_personal_relief_(darkpsy_mix)_[4k_48fps_h264].mp4, piece 988 is corrupted (from BiglyBT log)

```
$ sudo ausearch -f pyc
[sudo] password for pyc: 
----
time->Sat May 18 02:49:50 2019
type=PROCTITLE msg=audit(1558140590.814:721575): proctitle=6A617661002D586D783235366D002D6370002E2F4269676C7942542E6A61723A2E2F636F6D6D6F6E732D636C692E6A61723A2E2F646F726B626F782D73797374656D747261792E6A61723A2E2F6C6F67346A2E6A61723A7377742F7377742D7838365F36342E6A6172002D446A6176612E6C6962726172792E706174683D2F75
type=PATH msg=audit(1558140590.814:721575): item=1 name="/xxxx/video/spotovi/pyc_-_personal_relief_(darkpsy_mix)_[4k_48fps_h264].mp4" inode=94830826 dev=08:11 mode=0100777 ouid=1000 ogid=1000 rdev=00:00 nametype=NORMAL cap_fp=0000000000000000 cap_fi=0000000000000000 cap_fe=0 cap_fver=0
type=PATH msg=audit(1558140590.814:721575): item=0 name="/xxxx/video/spotovi/" inode=94830599 dev=08:11 mode=040777 ouid=1000 ogid=1000 rdev=00:00 nametype=PARENT cap_fp=0000000000000000 cap_fi=0000000000000000 cap_fe=0 cap_fver=0
type=CWD msg=audit(1558140590.814:721575): cwd="/usr/local/biglybt"
type=SYSCALL msg=audit(1558140590.814:721575): arch=c000003e syscall=257 success=yes exit=158 a0=ffffff9c a1=7f33fc002ad0 a2=42 a3=1b6 items=2 ppid=18542 pid=18620 auid=1000 uid=1000 gid=1000 euid=1000 suid=1000 fsuid=1000 egid=1000 sgid=1000 fsgid=1000 tty=(none) ses=3 comm="AEThread2:parke" exe="/usr/lib/jvm/java-11-openjdk-amd64/bin/java" key=(null)
```

**Comment by trancephorm** [comment]
Concluded file is actually not corrupted really, it's just some bug that makes it look corrupted. Loaded the same .torrent into Transamission and it fully checked.

**Comment by trancephorm** [comment]
...which is not the case with some other big file that also got corrupted today, but it doesn't check out in Transmission its change is logged by Audit :))) WTF is happening here........!?

**Comment by parg** [comment]
WTF indeed!
