### ISSUE TITLE
Rename praise & tweek request

### ISSUE THREAD

**Issue by SteveBresson** [BiglySoftware/BiglyBT#1071]
Appreciate the change in 1.9 that automatically highlighted the file name.
Makes the perlTk script I wrote work easier by skipping the text selection.
    My only problem is that when the (directory) name ends with the author,
something like:    Blah blah - Joe K. Blow
It highlights up to the period instead of the whole string. 
    The change (as I see it) would be to not allow the trailer to be treated as a suffix
if it includes a Space character.
Thanks for a great product!
Kubuntu 18.4
BiglyBT 1.9

**Comment by parg** [comment]
Just double checking this is the text selection in the 'Rename Download' window (the one with the options to rename display name, save path and torrent)

**Comment by SteveBresson** [comment]
You are correct.  I use it on everything.
I was surprised when it started doing the highlighting after the update.
Very quickly grew to like it when there was a ".suffix".
But based on what I perceive as the intent behind it, it shouldn't allow a
space as part of a suffix.

{{{ --- Steve ---- c:443.676.5396 --- }}}
http://www.stevebresson.smugmug.com

"That ain't gonna work," Roy said. "Get another option."
"We've already tried twelve."
"So you shouldn't have all that much trouble coming up with another twelve.
Your momma didn't raise an unimaginative engineer, did she?"

*--"Kris Longknife 03 - Defiant", Mike Shepherd*

**Comment by parg** [comment]
fixed in next beta, thanks!

**Comment by SteveBresson** [comment]
Much Gratis!!
I don't use most of the features you've provided in the s/w
but the rename and the ability to auto-archive files when I remove them
makes things much easier.

{{{ --- Steve ---- c:443.676.5396 --- }}}
http://www.stevebresson.smugmug.com

"That ain't gonna work," Roy said. "Get another option."
"We've already tried twelve."
"So you shouldn't have all that much trouble coming up with another twelve.
Your momma didn't raise an unimaginative engineer, did she?"

*--"Kris Longknife 03 - Defiant", Mike Shepherd*
