### ISSUE TITLE
ETA in Title & Transfers Bar frequently Wrong

### ISSUE THREAD

**Issue by dbareis** [BiglySoftware/BiglyBT#1073]
See the attached "Transfers Bar" picture, the same ETA is in the app's title bar, I'm not sure if its ever correct and certainly doesn't match the ETA of the next to complete torrent as displayed in the app.  Although the figure does seem to update frequently in the transfers bar it seems like its perhaps 30+ seconds behind?

![BiglyBt, incorrect ETA in TitleBar and Transfer Bar](https://user-images.githubusercontent.com/295230/57994235-82ba3000-7aff-11e9-87df-5f83cbca7967.png)

Windows: 10 64 Bit
Bigly About: Java 1.8.0_201 (64 bit)
Oracle Corporation
c:\program files\java\jre1.8.0_201

SWT v4922, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B1.9.0.0/4 az2

**Comment by parg** [comment]
There are two ETA values calculated, a raw one and a smoothed one. The one shown in the title bar is the smoothed one. The one shown in the ETA column is the raw one. There is an alternative column for the smoothed one.

The smoothed one is often preferable but was introduced later than the ETA column so the ETA column retained the raw one for backwards compatibility.

**Comment by dbareis** [comment]
Is there an option as to which displays on title/transfers bar?

**Comment by parg** [comment]
no
