### ISSUE TITLE
[Bug] Trackers aren't queried properly after reconnection

### ISSUE THREAD

**Issue by PrototypeZero** [BiglySoftware/BiglyBT#1074]
It seems BiglyBT isn't quering the trackers properly after a connection is lost and re-established.

For example if my VPN goes down (either on its own or if I swap server) then BiglyBT fails to _ever (I've waited well over 2 hours)_ re-establish a connection to **all trackers**, it will just alternate between "Querying" and "Error: Offline - No data received from tracker".  

The only way to fix this is to restart Bigly completely, the torrent will resume and connect to all the trackers without any problem at all in seconds.  But this is both annoying and inconvenient when you think your making progress on torrents only to find Bigly failed to reconnect for no good reason.

It seem Bigly is failing to "say" something to all the trackers that it only does correctly on the 1st connection to the tracker (maybe because its expecting something which it never receives).  Or maybe simply Bigly is simply not taking into account IP address changes at all.

NAT is fine, and Bigly is bound to the correct VPN interface.

**Comment by parg** [comment]
I'll check it out!

**Comment by parg** [comment]
For me everything gets working again after a VPN disconnect and reconnect with a different IP address bound to the same adapter. You can see the bind address that BiglyBT currently believes it should be using by hovering over the routing icon in the status bar. Took a minute or so.

**Comment by PrototypeZero** [comment]
It definitely binding to the correct address/port.

It seems to happen about 90% of the time when server/ip is changed.  As its a new VPN to me (and still within my possible refund time) I'll try to investigate further whether its something to do with certain areas/servers or VPN options that seems to be causing this or not.
I have used other (crappy, free) VPNs in the long distant past with Vuze and don't recall any similar problems occurring so it may be something to do with this VPN provider. :(

If theres any log files that may be useful or things to try just say and I'll provide them when I can.

**Comment by parg** [comment]
hopefully fixed in next beta (B25)
