### ISSUE TITLE
TCP not binding Error when first starting

### ISSUE THREAD

**Issue by HayamaSB** [BiglySoftware/BiglyBT#1077]
Whenever I load BiglyBT, I get the error in the screenshot.

I also get a "NAT Error - Connection to [IP ADDRESS] (your computer) refused." when I run the NAT TCP port test, which might be caused by the same thing?  The UDP port test works fine.

BiglyBT is version 1.9 & I updated my Java to the current version (build 1.8.0_211-b12), but that didn't solve my problem.

![BiglyBT Error](https://user-images.githubusercontent.com/50892841/58139102-4f62c880-7c07-11e9-8f0c-839c41558a4d.JPG)

**Comment by parg** [comment]
Something is already using the TCP port you have selected in BiglyBT - try selecting a different one. If it continues to fail, regardless of port choice, then perhaps your anti-virus/firewall isn't configured to allow BiglyBT to act as a 'server'

**Comment by HayamaSB** [comment]
found a port that stopped giving me the bind error on startup, but I'm still getting the "NAT Error - Connection to [IP ADDRESS] (your computer) refused." when I run the NAT TCP port test.  Could this be from the VPN service?  I'm using PIA on an open port server.
