### ISSUE TITLE
Disabling TCP Reliably

### ISSUE THREAD

**Issue by CrafterLaughter** [BiglySoftware/BiglyBT#1078]
* Win10 x64 17763.745
* BiglyBT Version Number 1.9

Phenomenal app you guys have developed here!

I'm seeking a means of disabling TCP reliably.  I came across the "Start in low resource usage mode" that has the checkbox to de-select TCP.

My observation is that a few times I'll start Bigly and launch the GUI via the sysTray icon right away to make a needed change and doing so shows me that TCP connections are still being made.

However, if I launch Bigly and leave the try icon for a number of minutes and then launch the GUI that it's working as intended with only uTP peers.

I considered disabling TCP for Bigly's Windows firewall entry but I thought that might inhibit app updates or other useful functions.  LMK.  Thanks.

**Comment by parg** [comment]
I'll look into an explicit option to disable TCP peers

**Comment by CrafterLaughter** [comment]
Top notch.  Just made a small PP donation 4Y828830Y6673745S  Have a great week!

**Comment by parg** [comment]
B26 has options to disable tcp/udp peers under Options->Connection - please test!

**Comment by CrafterLaughter** [comment]
Will do.  Have a great weekend.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
why want to disable tcp compatibility? You won't be able to connect my seedboxes with udp firewalled.
