### ISSUE TITLE
uTP Target Delay Before Throttle?

### ISSUE THREAD

**Issue by CrafterLaughter** [BiglySoftware/BiglyBT#1079]
Win10 x64 17763.745
BiglyBT Version Number 1.9

uTorrent has a setting "uTP Target Delay" controlling the threshold detected connection receive delay in ms that, if surpassed, causes µTorrent to throttle back on bandwidth usage. Receive delay is detected by tracking the changes in the deltas between uTP packet timestamps and packet receive times.

I'm hosting a tracker for people 20 hops and about 350ms away and I'd like to avoid unnecessary throttling of the connection.  Are settings for this kind of thing available somewhere in Bigly?

**Comment by parg** [comment]
No, those type of connection statistics are not currently available from the uTP subsystem - no throttling is performed at the application level.

**Comment by CrafterLaughter** [comment]
Sweet.  Even better then.

**Comment by parg** [comment]
I saw your post - https://www.reddit.com/r/torrents/comments/bsazkb/utp_speed_tests_of_various_torrent_clients_with/ - interesting stuff!

Not sure if you're interested but if you might be able to reduce BiglyBT's working set by fiddling with the JVM heap allocation. The default for BiglyBT is around 250MB (configured under Tools->Options->Startup and Closedown (set your 'mode' to Advanced if not already to see this). Actually I'll write a wiki article :) https://github.com/BiglySoftware/BiglyBT/wiki/Performance-Tweaks

**Comment by CrafterLaughter** [comment]
Fantastic.  When it comes to Windows my experience has been Bigly is notch above the others in terms of performance and features.  Your searchable options menu is brilliant.  I don't mind using a teeny bit more resources for all it's benefits at all.  The only reason I didn't just come out and say that is folks can be very political about this stuff, so I thought it best to just let the speed results speak for themselves.   Stellar job with the wiki article.  I'll go ahead and tag it in my post.  I'm only going to load up hundreds of torrents in the coming weeks, even so, I'll give a look at what it looks like with java garbage collection and adjusting the JVM memory limit if it were to save a few gigs of memory use on my setup.  

Just a heads up…When I just looked for the Java options this is what I ran into.

 



 

There was an error access the JVM options: Only Sun/Orade JVMs are supported (current vendor=AdoptOpenJDK)

 

Myself and many of my buddies have switched over to this OpenJDK stuff because we use this thing https://ninite.com/ to make batch install apps much faster.  Apparently Sun has changed their licensing?

 

Is it possible to have Bigly recognize and manage JVM from OpenJDK?

**Comment by CrafterLaughter** [comment]
A heads up to other 64 bit users like myself.  If you load up lots of torrents and Bigly warns of running out of memory which cannot be adjusted under OpenJDK....Once you uninstall OpenJDK, don't just go to Java.com and install as it will auto install 32 bit which will make Bigly launch to an error dialogue asking for 64 bit.  You have to uniquely search for java 64 bit which will bring you here
https://java.com/en/download/faq/java_win64bit.xml#Java%20for%2064-bit

Once installed you'll successfully launch Bigly and be able to increase your Java memory heap.

**Comment by parg** [comment]
Sorry for the delay in replying. I've extended the supported vendors to include AdoptOpenJDK - as this is an OpenJDK build it should support the usual JVM extensions for heap size etc.

It'll be in 2.0.0.1_B01
