### ISSUE TITLE
Update via I2P only not working

### ISSUE THREAD

**Issue by ghost** [BiglySoftware/BiglyBT#108]
As the update url's are not available the update via I2P only fails.
Is there a way around this besides manually fetching and patching ?

**Comment by mppdidi** [comment]
Maybe it's a good idea to make the update url's and trackers user configurable - so we could setup our own I2P mirror.
The software is digitally signed after all - so this should be no issue.

Thanx

**Comment by TuxPaper** [comment]
Closing issue do to age and OP's account being deleted. If anyone still has this issue, please file a new one.  Thanks!
