### ISSUE TITLE
Do not restart torrents with error due no space left on device

### ISSUE THREAD

**Issue by d00rsfan** [BiglySoftware/BiglyBT#1080]
Do not restart torrents with error due no space left on device
Never used that feature before - always restarted manually.

Java 11.0.3 (64 bit)
  Ubuntu
/usr/lib/jvm/java-11-openjdk-amd64

SWT v4922, gtk/3.24.8, zoom=100, dpi=102
Linux v5.1.3-050103-generic, amd64 (64 bit)
B1.9.0.1_B24/4 az2

States are
 Error: Resume data save fails: flush fails, write fails, No space left on device;
 Error: Disk write error - flush fails, write fails, No space left on device
 Error: Disk read error - flush fails, write fails, No space left on device

![image](https://user-images.githubusercontent.com/22635889/58233585-2ea08d00-7d45-11e9-8228-85d47a875453.png)

Set periodically restart downloads that has failed due to insufficient disk space to check if space has become available with Restart downloads every 120 min.
![image](https://user-images.githubusercontent.com/22635889/58233705-72939200-7d45-11e9-89c5-7bc82233b1ef.png)

For last 2.5+ hours free space is enough not only to finish downloading mostly all those torrents, but the size of any those torrent multiple to 2..3

**Comment by parg** [comment]
Most likely it isn't detecting the specific error type, I'll extend the logic.

**Comment by d00rsfan** [comment]
> I'll extend the logic.
After manual restart some of them began to recheck (i didn't remember witch of them), just for info, so it should be not a force set Downloading state, but similar behavior as by GUI
Unfortunately i haven't skill to fix and pull request :(

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
its desirable. May space got freed up until last try!

**Comment by d00rsfan** [comment]
Hi, parg!
I want to help you to create the best client, that's why i report about issues...
B2.0.0.1_B03/4 az2
Check box and 120 min is still present. Bug present too. 4 hours after space got freed up and:
![image](https://user-images.githubusercontent.com/22635889/58870558-162b5d80-86c9-11e9-8590-acee2804a040.png)
I'll not stop-start manually these torrents, will wait for auto-restart after updates, if You interesting to fix that issue

**Comment by parg** [comment]
hmm, I'll take another look, thanks

**Comment by parg** [comment]
OK, try B04 when it is built! The existing code picked up 'out of space' during file allocation but not later during actual downloading...

**Comment by d00rsfan** [comment]
> OK, try B04 when it is built! The existing code picked up 'out of space' during file allocation but not later during actual downloading...

Hi, Parg!
B2.0.0.1_B04/4 az2
 Space got freed up, now much better, 2 from 6 self-restarted, but these 4 still red:
![image](https://user-images.githubusercontent.com/22635889/58943393-4be34b80-8788-11e9-9904-74b913c6417d.png)

**Comment by parg** [comment]
Did you wait a while? It will only attempt to restart one at a time

**Comment by d00rsfan** [comment]
sure!
waited >3 hours (with 120min in config).
State changed to stop after restart client (no sense to wait more), and after manual change to download was without rechecking.

**Comment by parg** [comment]
ok, time to take another look, thanks!

**Comment by parg** [comment]
try B05 when available, thanks!

**Comment by parg** [comment]
B05's out!

**Comment by d00rsfan** [comment]
During day 5 torrents was bit by bit started successfully! Thank You!

**Comment by parg** [comment]
yay :)
