### ISSUE TITLE
[Feature Request] Pop-Up to relocate went missing files

### ISSUE THREAD

**Issue by ahnono** [BiglySoftware/BiglyBT#1085]
Sometimes I have to rename my files, so that they fully work with software like Kodi. Unluckily BiglyBT thinks that the files which went missing are deleted and starts to automatically redownload them in the background. 
Instead of that behaviour, it would be awesome if an error message pops up which tells the user about the missing files pops-up, while also giving him the option to relocate the renamed/removed files. Also an option to deactivate the auto-redownload would be great too :)

**Comment by parg** [comment]
If you rename the files via BiglyBT you won't have this problem - right-click on the file and select 'rename/retarget'

Alternatively, if you have already renamed the file, the same menu can be used to point the file to the correct location.

**Comment by ahnono** [comment]
@parg Please read the title, I am not having a problem here. Thats a feature request.
1. Nope, I am batch renaming my files.
2. Thats not what Im talking about.
