### ISSUE TITLE
[question] Tag constraint

### ISSUE THREAD

**Issue by nin0bb** [BiglySoftware/BiglyBT#1088]
Been trying to wrap my head around how tag constraints work but as the wiki is of no use whatsoever to me not showing any examples and only useful for anyone with knowledge of the code, I am in need of some assistance.

I'm wanting to auto tag magnet/torrent downloads added by sonarr/radarr so that only these downloads are affected by the tagging, maybe through the save path? They each download to separate folders with respective names inside the main biglybt download folder.
If possible, it tags it on download complete so I can set execute on assign but this is not a necessity to me

**Tagging by fileext is pointless to me as it'll affect other downloads.**
_I am currently using auto import via several folders assigned to their own tags which I want to not be affected by this._

Any help would be appreciated

**Comment by parg** [comment]
I don't know sonarr/radarr - how exactly are you adding the magnet/torrents to BiglyBT from sonarr/radarr ?

**Comment by nin0bb** [comment]
Sonarr and radarr is connected through BiglyBT web remote, and the magnet link or torrent file is automatically injected there.
Sonarr adds download with a "category" 'sonarr' which creates a subfolder called sonarr and the same for radarr.
The category as far as I can tell isn't detected by bigly as an actual category there, it is just creating the subfolder for it's downloads under \download\.

**Comment by parg** [comment]
So Sonarr is setting the download location based on the category you select but it doesn't explicitly convey that category to BiglyBT. It could as BiglyBT has added tagging features to the BiglyBT Web Remote protocol and client but that would require a change to Sonarr and I don't have the time at the moment to look into creating a pull request for that.

Best quick solution would be for me to add 'save path matching' to the BiglyBT constraints language - I'll look into this for the next beta (available later today or tomorrow, I'll tell you when)

**Comment by parg** [comment]
Actually you can already do it - set the tag constraint to be

contains( save_path, "\sonarr" )

for example, to select downloads that have "sonarr" in it

**Comment by nin0bb** [comment]
It was that simple huh. This works great! Thank you very much
I've been trying to combine this with the isComplete() function but I'm failing to find the correct variable to input

**Comment by parg** [comment]
is
contains( save_path, "\sonarr" ) && isComplete()

what you're looking for?

**Comment by nin0bb** [comment]
Wonderful, I shall attempt at learning myself how to put these things together and what I can do with it.
Thank you for taking time to help me out, very much appreciated!

Been using Azereus/Vuze almost since it's release and never looked back and BiglyBT seems to be better so far, now to just get these difficult private tracker admins to accept BBT 2.0 in their whitelist (yet for some reason some of them allow 1.9 spoofed as vuze still but refuse to allow BBT 2.0 until the top trackers whitelist apparently)

I shall send thee a donation for sticking up with the development and swift help!

**Comment by parg** [comment]
No problem - just shout if you need any help with anything else!
