### ISSUE TITLE
Frequent crashes

### ISSUE THREAD

**Issue by ghost** [BiglySoftware/BiglyBT#109]
Not to complain, but it crashes a lot - esapecially after the start.
What info can I provide to debug this ?
Looks exactly like this here https://forum.vuze.com/Thread-Vuze-shutting-down-at-start-up

**Comment by mppdidi** [comment]
Trying with the internal browser disabled - probably the fetch via socks/tor/i2p doesn't work or is slow.
I'm doing some testing and let you know.

**Comment by mppdidi** [comment]
No more crashes with internal browser disabled.

**Comment by parg** [comment]
hmm, annoying :( the 'internal browser' is used for showing the 'web' search results (not the meta-search ones) and a few pages like the beta sidebar entry - are you using any of these when it crashes?

**Comment by mppdidi** [comment]
Yes indeed - the beta sidebar loads on startup - don't know how to disable it.

**Comment by parg** [comment]
You can remove it by clicking on the little x - or does it keep coming back?

**Comment by Havokdan** [comment]
> You can remove it by clicking on the little x - or does it keep coming back?

Always comeback for me

**Comment by mppdidi** [comment]
Dito

**Comment by mppdidi** [comment]
Still crashing - especially directly after startup.
Still no clue...

**Comment by mppdidi** [comment]
What is the difference between the 32bit and 64bit application - maybe the java 64bit is problematic ?

**Comment by parg** [comment]
Doesn't make a difference really - if you have a problem with this then it won't run at all.

When you say 'crash' does it startup and then vanish or does it start up and hang and you have to kill it?

**Comment by mppdidi** [comment]
It starts and then crashes after a few seconds

**Comment by parg** [comment]
any JVM dump files hanging about? Names are of the form 

hs_err_pidxxxx.log

**Comment by mppdidi** [comment]
Yes a lot of them - but what about scrubbing them before sending them over ?

**Comment by mppdidi** [comment]
From what I observe / conclude - file checking is enabled and indeed while the file check is running after a crashed restart, a simple klick on the gui is enough to crash it again...

**Comment by TuxPaper** [comment]
Closing issue do to age and OP's account being deleted. If anyone still has this issue, please file a new one.  Thanks!
