### ISSUE TITLE
Every thing has slowed down

### ISSUE THREAD

**Issue by ebobtron** [BiglySoftware/BiglyBT#1090]
2.0.0.0 auto downloaded today and asked to be installed.  Things are know crawling with Bigly running.  Very high CPU usage compared with what I have become accustom to.  Wish I could tell you more.  Mouse hover over piece map slower than this morning.   Selecting torrent is slow to react and highlight the torrent clicked.

Windows 10 Pro 1809 with the latest crash-ware.
2.0.0.0

Thanks for this.

**Comment by ebobtron** [comment]
self induced problem  "driver verifier"

**Comment by parg** [comment]
yay ;)
