### ISSUE TITLE
[Bug/Feature Request] Search for Existing Data Files

### ISSUE THREAD

**Issue by PrototypeZero** [BiglySoftware/BiglyBT#1092]
[Bug] There seem to be a problem with the "Search for Existing Data Files" feature if a torrent has not allocated files yet (ie the torrent was added in a Stopped or Paused state).  If you attempt to Search (in copy mode atleast), the files will be found and checked yet will always result in a "copy failed" error (file not found exception in console pointing to the non existent destination file).  I've only noticed this with the Copy function, but have not used the Move function yet.
Maybe either stop the user and warn them when the files aren't allocated yet, or do the allocation there and then when the files are to be copied?

[Feature Request] When files in a torrent are "linked" and you click "Revert File Location(s)" it always seem to move the linked files, thus possibly damaging other torrents (by effectively deleting the file) if file linked is part of another torrent.

Now I know you should really use the search with the copy function instead of link if you have the space and want to retain the "old" source files.  But why not have a "Revert File Location(s) - Copy File(s)" option that Reverts the location and copies the linked file(s) there for times when you may have been short of space originally but now aren't?

**Comment by parg** [comment]
Ah, it is because the parent-folders haven't been created. I'll fix that! 

I'll think about the revert thing.

thanks!

**Comment by parg** [comment]
B03 with the fix is now available.

I added a revert (copy) but the menu item only appears if the existing revert item would be enabled (don't like to fill up menus and sub-menus get a bit annoying)

**Comment by PrototypeZero** [comment]
Thanks.

**Comment by MHMae001** [comment]
i have a question is it possible to add the copy instead of making a link a '' by default option'' i dont have a space problem'' so id like it to always copy the the files 
and i have some torrents that have over 200 links how do i make it so the files gets unlinked and copied since from what ive read theres a copy function already implemented ?? and from the options i see its unclear how to do that ? 
is it the move option ?

**Comment by parg** [comment]
The "search for existing data files" dialog remembers the last mode used - if you set it to "copy" there then it will be "copy" next time you use it.

If you right-click on a download in the Library and select the "Advanced" menu under the "Control" tab then there is a "Clear links" option to remove all links.

You would then need to use "search for existing data files" again to copy the missing files in.

If you decide to do this I would test it out on a file with one or two links first to make sure things are working as expected.
