### ISSUE TITLE
Teredo is ignored as public bindIP

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [BiglySoftware/BiglyBT#1093]
* OS and version 
Windows 10 1903
* BiglyBT Version Number
2.0.0.

If no IPv6 is available, one might want extend connectivity to other IPv6 peers.

Mainline DHT does work fine if forced to. 
Vuze DHT does not even recognize it. The IPv6 Tab is missing from stats completely.

Is there a way to manually make it use? I found in source code that the teredo prefix is punished. Shouldn't it be prioritized lower instead Of not using it at all? Could solve RED Nat for some users.

i have explicitly bound it to teredo interface but it still says:

```
Test starting
Default public address is ...
Bindable addresses: 127.0.0.1, 0:0:0:0:0:0:0:1, 2001:0:XXXX:,..
0 NAT devices found
No HTTP proxy found
Testing HTTP outbound
    Test successful
Testing TCP outbound
    Test successful
Testing UDP outbound
    Test failed: Outbound test failed
2 public/external addresses found
...
IPv6 test
```
    **No default public IPv6 address found**
`Test complete
`

**Comment by gh338** [comment]
It seems private ipv6 ranges are completely ignored - is this really necessary ?

**Comment by rindeal** [comment]
Private, _Teredo_ and _6to4_ are explicitly disabled in code https://github.com/BiglySoftware/BiglyBT/blob/701fd18a8ceb3e1a1319da40948e263236e90042/core/src/com/biglybt/core/networkmanager/admin/impl/NetworkAdminImpl.java#L3754

**Comment by parg** [comment]
Get yourself a proper IPv6 address if you want to torrent over it

**Comment by parg** [comment]
If you want to consider some ULA as a 'public' address then the latest beta has that option
