### ISSUE TITLE
[Feature Request] Peer Transport Encryption AES

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [BiglySoftware/BiglyBT#1094]
I found the Peer Encryption can have more options than selectable by dropdown:

1. None
2. Plain
3. RC4
===
4. AES

Can this be implemented? If not set to minimum required cryoto For backward compatibility, AES should be fine To configure. Even if only for very few other BiglyBT at beginning this will be used.

* BiglyBT Version Number
2.0.0

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
it is just hidden inside? 

https://github.com/BiglySoftware/BiglyBT/blob/243fd50431e52a9b6f37c0fefa9204c71f6cf26d/core/src/com/biglybt/core/networkmanager/impl/ProtocolDecoderPHE.java#L281

**Comment by parg** [comment]
https://en.wikipedia.org/wiki/BitTorrent_protocol_encryption - search for AES. It was implemented but then not used so there is no point in enabling it within BiglyBT as no other clients support it.
