### ISSUE TITLE
Use HTTPS for ipdiscovery services

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [BiglySoftware/BiglyBT#1097]
One valid example: biglybt - [2607:f1c0:100f:f000::2f3]:80 Enforce HTTPS for ip.discoveryvip.com

* BiglyBT Version Number
2.0.0

**Comment by parg** [comment]
http://ip.discoveryvip.com/ip.asp doesn't work anymore - I'll remove it.

The other existing one (DynDNS) is https already.
