### ISSUE TITLE
Regression (old): Start Options disappear if chosen more than one torrent

### ISSUE THREAD

**Issue by d00rsfan** [BiglySoftware/BiglyBT#1099]
Hi!
Version, OS don't matter, 
Regression happened since Vuze times. Window Open Torrent Options. That menu is disappear if was chosen more than 1 torrent:
![image](https://user-images.githubusercontent.com/22635889/58759599-4f32c900-8535-11e9-9a6d-ea37a4870ed9.png)
 In Azureus it was possible to select Stop mode for selected torrents.

**Comment by parg** [comment]
Fixed in next beta (2001_B03)

**Comment by parg** [comment]
B03 with the fix is now available, see the Help menu -> Join Beta Program to obtain beta releases.

**Comment by d00rsfan** [comment]
Have tested: fixed, Thank You!
