### ISSUE TITLE
[REQ] Selection by Mouse or Keyboard Shortcut 

### ISSUE THREAD

**Issue by Taurean75** [BiglySoftware/BiglyBT#11]
Hey --

From Azureus, it was never possible to select multiple items by dragging the mouse or even using CTRL-A shortcut.  

Is this possible in Java environment?

Thanks.

**Comment by TuxPaper** [comment]
What OS (and desktop environment, if you are on *nix) are you using?

All the tables/lists that I know of support CTRL-click, SHIFT-click, as well as CTRL-A, CTRL-SHIFT-UP/DOWN/PGUP/PGDN.  You do have to have the table as the focus for these keys to work though :)

**Comment by Taurean75** [comment]
Windows 10 x64.

All those work except CTRL-A.  Weird.

It'd be nice if it supports selection by mouse drag.
