### ISSUE TITLE
No automatic use of Tor and i2P on magnet links

### ISSUE THREAD

**Issue by rex4539** [BiglySoftware/BiglyBT#1100]
When opening a magnet link it only uses the Public IP network but not Tor and I2P (you need to add them manually for each file).

.torrent files use them automatically.

**Comment by parg** [comment]
You need to either add &net=I2P to the magnet link or go to Tools->Options->Plugins->Magnet URI Handler and set the 'default networks'

**Comment by rex4539** [comment]
![Screen Shot 2019-06-02 at 15 56 48](https://user-images.githubusercontent.com/227442/58761616-169fe900-854f-11e9-871d-0fd92a59b1b9.png)

These options were already preselected but not applying to magnet links.

Please, test before you close a bug report.

I'm happy to provide any other information.

**Comment by parg** [comment]
Why have you got all three default networks enabled? You would need to deselect the 'public network' if you wanted that to be deselected for magnet links by default.

**Comment by rex4539** [comment]
Actually I want to have all 3 selected by default :)

Am I doing something wrong?

**Comment by parg** [comment]
Hmm, is your issue with the magnet links themselves or the downloads that result from the use of magnet links? 

I assumed the former from your issue title.

If you mean the latter then the initial download networks are inherited from the ones that were used to download the magnet link - if the magnet link download occurs over the public network then the download will have that enabled.

**Comment by parg** [comment]
Just to clarify...

The magnet link download process (i.e. the download of the .torrent file using the information in the magnet link) uses the 'default networks' defined under the magnet uri handler plugin's settings, or the explicit networks provided in the magnet link (via &net=Public/I2P/Tor uri parameters) if they are present.

Once the .torrent has been downloaded the actual networks used to download the .torrent are then passed on to the open-torrent-options dialog and become the networks enabled for the download when added.

When you open a .torrent file directly then the default networks defined under Tools->Options->Connection are used by the open-torrent-options dialog (as there is no other network information available).

It would be possible to add another option to the magnet URI handler plugin to say 'don't propagate network selection' I suppose (leaving the download to use the default networks under Options->Connection) Is that the behaviour you are after?

**Comment by rex4539** [comment]
I basically want the magnet link to use all the networks, same as the .torrent file, and not just clearnet.

It looks like a bug that it uses all networks for .torrent files and not for magnet links.

**Comment by parg** [comment]
It isn't a bug, it is working as designed. 

However, 'as designed' doesn't coincide with your view of how you expect things to work - nothing wrong with that. So I offered to add an option to make it work how you want.
