### ISSUE TITLE
No UDP Connections if Peer Data proxy set

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [BiglySoftware/BiglyBT#1101]
https://github.com/BiglySoftware/BiglyBT/blob/651be803c0871e20bbe3896483a893c56c3ebce2/core/src/com/biglybt/core/networkmanager/impl/udp/UDPTransport.java#L155
https://github.com/BiglySoftware/BiglyBT/blob/651be803c0871e20bbe3896483a893c56c3ebce2/core/src/com/biglybt/core/networkmanager/impl/udp/UDPTransport.java#L157

BiglyBT supports SOCKS proxies of type 4, 4a and 5. But It does not support SOCKS 5 UDP associations for peer connections. Why disable UDP with socks enabled? if Vuze may bound to udp capable interface or VPN while using socks for tcp. 

This is only expected behaviour together with this:
https://github.com/BiglySoftware/BiglyBT/blob/651be803c0871e20bbe3896483a893c56c3ebce2/core/src/com/biglybt/core/networkmanager/impl/udp/UDPTransport.java#L134

**Comment by parg** [comment]
Not going to support UDP over SOCKS
