### ISSUE TITLE
2.0.0.0 regression: active seeding torrent rows in the classic table no longer have a blue font

### ISSUE THREAD

**Issue by bughit** [BiglySoftware/BiglyBT#1102]
* OS and version: win7 sp1 x64
* BiglyBT Version Number: 2.0.0.0

I don't remember if downloading torrents were ever blue, but if the goal is consistency, it would make sense for all active to be blue because it's helpful to be able to tell them apart at a glance, rather than the current state where all are black.

**Comment by parg** [comment]
Same issue as https://github.com/BiglySoftware/BiglyBT/issues/1091#issuecomment-498082633

**Comment by parg** [comment]
B03 with the fix is now available, see the Help menu -> Join Beta Program to obtain beta releases.

**Comment by bughit** [comment]
Thanks. It would be helpful if you released minor bugfix releases more often. To do that you'd need to use branches (e.g 2-0-x) which would receive backported fixes from master and from which bugfix releases could be made.

**Comment by parg** [comment]
I'll get our development manager to allocate a resource or two on to that right away.

**Comment by bughit** [comment]
Using branches in git does not require development mangers and teams of people, you just need to know how to do it and it's not as overwhelming as your sarcasm implies you believe.

Here's an example of another open source bittorrent client that does that: https://github.com/qbittorrent/qBittorrent/tree/v4_1_x

I guess their corporate sponsors enabled them to hire a branching team.

**Comment by parg** [comment]
Funnily enough, after having worked in the software development industry for 33 years, I know how branching works.

**Comment by bughit** [comment]
> 
> 
> Funnily enough, after having worked in the software development industry for 33 years, I know how branching works.

Then your reaction makes even less sense

> I'll get our development manager to allocate a resource or two on to that right away.

It's like I suggested you port the whole project to C#.

Doing bugfix releases off stable branches is a reasonable and common, bordering on universal, practice. The reason is self evident, it allows the product to stabilize, the stable branch only receives fixes and never new regressions.

**Comment by parg** [comment]
And so you plough on.

Let's go back to your post and fix it for you.

> Thanks. It would be helpful if you released minor bugfix releases more often. To do that you'd need to use branches (e.g 2-0-x) which would receive backported fixes from master and from which bugfix releases could be made.

This is constructed in such a way as to imply that I am ignorant of branching, backporting and bugfix releases.  

I would suggest something more along the lines of

> Thanks. Do you guys ever do bugfix releases to get things out to users between main releases or should I stick to the beta channel/wait until the next main release?

This then permits the conversation to go one or two (or maybe more) ways

1.  We look at the severity of issues and if they are significant enough we will branch. Sometimes fixes can be piggy-backed on plugin updates as well, for example an issue with the multi-tracker editor in 1,8 was fixed this way. Bugfix releases can be disruptive with private trackers that whitelist client versions as they now have another version to validate. Also users unaffected by the issue being addressed are confronted with another update - it can be hard enough to get users to update anyway. Your issue hasn't been reported by many people (you have to have gone into Advanced mode and deselected 'start UI before Core Initialisation' to trigger it) so it has been left as a beta fix for the moment. If a more significant issue is discovered that requires a bugfix release then your issue would most likely be included in it.

or

2. Wow, I've never thought of using branches as a means of managing interim releases, I'll take a look into it. Thanks!

**Comment by parg** [comment]
There is a work-around for the seeding row colour (but not other issues) - you can set up a Tag to colour the foreground/background however you want.

Use a constraint of something like

hasTag( "Seeding") && setColors( 0x0000d0 )

as well as enabling the 'TagColors' column in the Library view and right-clicking on the Status column header and de-selecting the 'Vary row foreground color' option.

See https://github.com/BiglySoftware/BiglyBT/wiki/Tags#Change_downloads_row_color_when_it_contains_certain_file_types
