### ISSUE TITLE
Problems with AVISTAZ.TO

### ISSUE THREAD

**Issue by bekam11** [BiglySoftware/BiglyBT#1104]
I installed the latest version of BIGLYBT and I have noticed that I can't download torrents from AVISTAZ.TO
For example, this magnet: 
magnet:?xt=urn:btih:c0f1271411b1462a08af77d46e5df2b350c9edec&dn=REAL_ONIGOKKO_3-d1k

Any solution?.

**Comment by parg** [comment]
Can't comment on specific sites/downloads. 

Magnet downloads will fail if there are no peers available to download the .torrent from or if the .torrent files are private and the magnet relies on the DHT.

Check to see if there are direct links for downloading the torrent rather than a magnet link.

**Comment by bekam11** [comment]
> Can't comment on specific sites/downloads.
> 
> Magnet downloads will fail if there are no peers available to download the .torrent from or if the .torrent files are private and the magnet relies on the DHT.
> 
> Check to see if there are direct links for downloading the torrent rather than a magnet link.


I think this software supports "private".... bad thing.

**Comment by parg** [comment]
BiglyBT fully supports private torrents.

By design (not just BiglyBT design, it is a BitTorrent standard) a private torrent can't be downloaded via the DHT and therefore can't be downloaded via a magnet link such as the one you posted.
