### ISSUE TITLE
Regression(old) - Force Re-check button is disabled in most cases

### ISSUE THREAD

**Issue by d00rsfan** [BiglySoftware/BiglyBT#1107]
Hi, Parg!
Thank You for the best clients, I use for 15 years (jumped from reference Python official shit)
Regression since last Azureus or early Vuze versions,
OS and Version doesn't matter.
Force Re-check is active on Paused or Stopped torrents, while i remember  there was possible to recheck downloading and seeding torrents.
and i see such combined states are possible and present:
![forced_checking;_seeding](https://user-images.githubusercontent.com/22635889/58871434-a322e680-86ca-11e9-94bc-e603fbdbd39c.png)
![Checking;Seeding](https://user-images.githubusercontent.com/22635889/58871435-a3bb7d00-86ca-11e9-9f06-50130702013f.png)

Please, fix, sometimes it's really important.
P.S. today checked https://github.com/BiglySoftware/BiglyBT/issues/1080 and problem is still present

**Comment by parg** [comment]
The 'checking and seeding' case is a low-resource recheck on download completion, it is different from an explicit force-recheck which, as you say, is only available for downloads in a stopped/paused state.

If you want to force-recheck just stop the torrent and do it?
