### ISSUE TITLE
unable to update biglybt

### ISSUE THREAD

**Issue by asinkwrongus** [BiglySoftware/BiglyBT#1108]
I am not able to install updates and am receiving this notification:

**Verification of 'Core BiglyBT Version' failed: Signature missing from file**

* OS and version Windows 8.1
* BiglyBT Version Number B1.9.0.1_B26/4 az3
*
thanks

**Comment by parg** [comment]
hmm, the latest beta version is 2.0.0.1_B04 - so the associated download will be

core_BiglyBT2001-B04-signed.jar

See if you can find this in your download list, delete it and then try checking for updates again.

**Comment by asinkwrongus** [comment]
Yeah, I had not been able to update since that version.  I was able to get the update to complete by going into settings and changing to anonymous update then adding public network at download time. Weird. Thanks for responding, I'll let you know if the next update is ok.
