### ISSUE TITLE
[Linux] [GTK3] Advanced Statistics plugin: Activity graphs are empty

### ISSUE THREAD

**Issue by axredneck** [BiglySoftware/BiglyBT#1111]
![2019-06-07-033123_1920x1080_scrot](https://user-images.githubusercontent.com/20617900/59074796-d38aa080-88d5-11e9-89ef-d54ab815e49a.png)

Before, when GTK2 worked (BiglyBT 1.5.0.0, Vuze, earlier OpenJDK versions, can't remember exactly), this graph also worked, it doesn't work exactly with GTK3.
Related issue: #753 

Arch Linux
Java 11.0.3 (64 bit)
  Oracle Corporation
/usr/lib/jvm/java-11-openjdk

SWT v4922, gtk/3.24.8, zoom=100, dpi=305 (actual dpi of my LCD panel is not 305 but much much less)
Linux v5.1.6-zen1-1-zen, amd64 (64 bit)
B2.0.0.0/4 az3

p.s. Don't blame my GTK theme, with default GTK theme it doesn't work too.

**Comment by parg** [comment]
Try version 2.3 (available via auto-update) - hopefully fixed that and a few other UI issues as well.

**Comment by axredneck** [comment]
Fixed, thanks!

**Comment by parg** [comment]
No problem!
