### ISSUE TITLE
User-defined keyboard shortcuts

### ISSUE THREAD

**Issue by trancephorm** [BiglySoftware/BiglyBT#1113]
User-defined keyboard shortcuts for whatever action. No need for defaults, just to be able to define would be neat, like for example I do use "update tracker" function pretty frequently.

Bigly's really the best out there!

Thanks!

**Comment by TuxPaper** [comment]
This is a technical comment for an implementation idea.  You don't have to understand it, it's mainly for myself, or anyone wanting to code this up.

 Our plugin interface is accessible from javascript snippets.  Extending this so a javascript function is run on keypress might be a good way to implement this feature (passing along context, like the download object currently selected in the UI, so one could do a `download.requestTrackerScrape()` when focused on a torrent in My Library).
