### ISSUE TITLE
"Test SOCKS" button doesn't provide the Popup that previ

### ISSUE THREAD

**Issue by Resef8604** [BiglySoftware/BiglyBT#1114]
Java 1.8.0_211 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_211

SWT v4922, win32, zoom=100, dpi=96
Windows 7 v6.1, amd64 (64 bit)
B2.0.0.0/4 az3

When I go to Tools > Options > Connection > Proxy there is a SOCKS setup that I have used for years between Vuze and this platform.  Previously I could click the Test SOCKS button to verify the connection was ok and running correctly.  Now when I try click the Test SOCKS button nothing happens.  No Pop up and no confirmation that the connection is working.

**Comment by parg** [comment]
Fixed in the beta program - see the Help menu to join it
