### ISSUE TITLE
Install fails on Win10 - cannot retrieve JRE from vuze.com

### ISSUE THREAD

**Issue by Limos** [BiglySoftware/BiglyBT#1115]
Windows 10 1903
BiglyBT v 2.0.0 (latest download from public website)

i4j_nlog.log shows:

[0:630] ERROR: No JVM found
[0:640] Download location: https://www.biglybt.com/jre/win64
[0:649] Downloading JRE
[1:486] ERROR: InternetOpenUrl failed with error code 12045
[2:496] ERROR: Retry JRE download

Attempting to go to the URL above (in Chrome on Windows) redirects to:

https://cf1.vuze.com/files/java/jres/windows-amd64-1.8.0_202.tar.gz

Chrome shows an SSL error due to a self-signed certificate.

I'm assuming Win10 is preventing the installer from downloading the JRE from a website with an untrusted (self-signed) cert.

**Comment by Limos** [comment]
Whoops.   Never mind....      It appears this issue is being caused by our corporate web content filter.   Access to the Vuze.com domain is blocked from my corporate network.  

Might want to host the JRE on the same server that the BiglyBT installer was downloaded from.   Or bundle it into the installer package.

**Comment by TuxPaper** [comment]
Thanks for finding the cause of your issue.  I've added an installer with Java to the GitHub Release page, and will put one there in future releases.
