### ISSUE TITLE
Tools>Options>Files>Ignore>File names to auto-skip when adding a torrent

### ISSUE THREAD

**Issue by nofnway** [BiglySoftware/BiglyBT#1116]
Hi Parg,
I was excited when I saw you had added this setting, but I cannot get this to work, and cannot find any resource in the wiki to guide/tell me if I am doing something incorrectly. I am reporting this in case it is a bug.

I am attempting to use the setting:
Tools>Options>Files>Ignore>File names to auto-skip when adding a torrent
to skip files with the word "sample" or "padding"in the filename. Have tried: 
sample
*sample
sample;padding
*sample;padding
sample; padding
*sample; padding
.sample;
-sample
sample.mkv

All of these were tried with and without the Regular Expression box checked. However, each time I click a magnet link, and the Open Torrent Options UI is displayed, the files with sample in the name are checked. Please advise.
Thanks!

OS: Windows 10 Pro version 1903 build 18362.175
BiglyBT version: B2.0.0.1_B07

System from About:
Java 1.8.0_211 (64 bit)
Oracle Corporation
c:\program files\java\jre1.8.0_211

SWT v4922, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.0.0.1_B07/4 az3

**Comment by parg** [comment]
Ah, the joy of regular expressions :) Matching is either by exact name or regular expression. You want the latter so make sure you have checked the 'regular expression' box to the right.

Here's a link to Java regular expressions:

https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html

To match against <something> appearing anywhere in a file name you need to use

`.*<something>.*`

For example

`.*sample.*`

The .* matches against 'zero or more occurrences of any single character'

**Comment by nofnway** [comment]
That did the trick. Thank you so much for explaining how to use this feature! Have a great day!

**Comment by parg** [comment]
No Problem!
