### ISSUE TITLE
BiglyBT Launcher

### ISSUE THREAD

**Issue by Hollowlog** [BiglySoftware/BiglyBT#1118]
* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment

**Comment by Hollowlog** [comment]
How do you change the BiglyBT launcher settings from save to open?

**Comment by o0nd7ots** [comment]
@parg Please help or close this

**Comment by parg** [comment]
Closing as nothing's going to happen here, re-open if so desired.
