### ISSUE TITLE
UI Display bug

### ISSUE THREAD

**Issue by hadam9** [BiglySoftware/BiglyBT#1119]
I want to remove sidebar sections like Devices but I can't. Tools->Options->Interface->Display then I delete the number header order, saving, but the settings doesn't save, tried install beta, stable release but doesn't work, this settings doesn't change no matter what I do, tried everything from save and restart to reinstall.

* OS and version: MacOS 10.13.6 (High Sierra)
* BiglyBT Version Number: 2.0.01 (Doesn't work on Stable too)

**Comment by parg** [comment]
I think you failed to hit the 'save' button before restarting. Normally when you tab out of a field the focus-lost event causes the option you have changed to be persisted automatically (without an explicit save). However, if you go straight from an amended field to the File menu and select 'restart' unfortunately the system doesn't deliver a focus-lost event and the change isn't saved.

Not that I am saying this is great behaviour but I believe that is the cause.

**Comment by parg** [comment]
I'll add something in to pick this situation up

**Comment by hadam9** [comment]
Thanks for the reply, but doesn't work on macOS, I tried fullscreen mode, hit save multiple times, restarted from the macOS menu, quit application etc, doesn't save. 
I tried this on the windows version, the windows version works fine, no problem, only macOS.

**Comment by parg** [comment]
hmm, I tested on Mac and it worked ok - there must be something else going on preventing your configuration from being saved. I think in chat you said that changing something else (e.g. gap between header rows) caused the sidebar changes to also be picked up - just verifying that is the case?

**Comment by hadam9** [comment]
Yes, I changed header rows to 4 and the settings saved, but it's worked only one time sadly.

**Comment by parg** [comment]
Can you go to the Help menu and select the last option (generate debug info) - this will create a .zip file containing diagnostics. Attach this to an email and send it to paul@biglybt.com

Thanks!

**Comment by hadam9** [comment]
Sent, thank you for the support!

**Comment by parg** [comment]
Thanks for that - there were a few unrelated issues that I fixed but nothing obvious. I just tested again and realize that on the Mac hitting the 'save' button also isn't drawing focus away from the text field and therefore the change isn't be picked up :( Can you try changing the header options and click on another text field to ensure that the cursor has moved out of the header options box, then hit 'save' and restart?

**Comment by hadam9** [comment]
The settings is saved with header gaps 4, but only works with the last 3 header order.
If I'm trying to delete the 3, which is biglybt the settings is reseting.
If I changing header gaps from 4 to 1 the settings is saving with the deleted header gaps.
