### ISSUE TITLE
RSS Error 

### ISSUE THREAD

**Issue by Taurean75** [BiglySoftware/BiglyBT#1120]
Hello --

I'm getting  "Fail TorrentManager createFromBEncodedFile fails" with ETTV RSS in RSSFeed Scanner.

What does this mean?

Thanks.

**Comment by parg** [comment]
Sounds like whatever the RSS feed thinks represents the .torrent file download link is, it isn't. Check out the RSS feed contents by hand and see if the download link refers to a valid .torrent.

**Comment by Taurean75** [comment]
Torrents from etorrent.click seem to be malformed. However, I don't understand how every one of them could be malformed.

I tried to open one in the browser, and BT stated "unable to display the data."

Could you try it?

**Comment by parg** [comment]
I'm afraid I can't look into specific site issues, you'd need to try downloading one of the malformed torrents and look at the content. If it is a valid torrent file then it'll look something like

`d8:announce51:http://tracker.documentfoundation.org:6969/announce13:announce-listll51:http://tracker.documentfoundation.org:6969/announcee7:comment29:LibreOffice_6.2.4_Win_x64.msi10:created by18:MirrorBrain/2.19.013:creation datei1558296051e4:infod6:lengthi295682048e6:md5sum32:855e7b1a30c30612af4ef48e98ada2784:name29:LibreOffice_6.2.4_Win_x64.msi12:piece lengthi262144e6:pieces22560:<....>e8:url-listl113:http://mirrors.coreix.net/thedocumentfoundation/libreoffice/stable/6.2.4/win/x86_64/LibreOffice_6.2.4_Win_x64.msi137:https://www.mirrorservice.org/sites/download.documentfoundation.org/tdf/libreoffice/stable/6.2.4/win/x86_64/LibreOffice_6.2.4_Win_x64.msi127:https://mirrors.ukfast.co.uk/sites/documentfoundation.org/tdf/libreoffice/stable/6.2.4/win/x86_64/LibreOffice_6.2.4_Win_x64.msiee`

**Comment by Taurean75** [comment]
Its RSS seems to be malformed... https://www.ettv.to/rss.php?cat=5,7,41,50
