### ISSUE TITLE
Can't prevent BiglyBT from stealing focus

### ISSUE THREAD

**Issue by ZioFeda** [BiglySoftware/BiglyBT#1121]
BiglyBT steals focus from my main window every time I add a torrent from my browser. 
If the window is minimized, it will get maximized and steal focus every time I add a magnet link, but I can stop that from happening by selecting the "suppress file download popup dialog". On the other hand, if the window is unfocused but NOT minimized, that particular dialog will not steal focus; however, the main window will always steal focus as soon as the related torrent is added to the list. 

I tried trifling with some options, to no avail; I've already tried "reduce situations where main window is shown". 

I've also tried to compare my settings with the ones I used to have in Vuze (which, for some reason, BiglyBT DID NOT ask me to import, to my great disappointment), but it all seems pretty much the same to me. Vuze, of course, did not behave like this.  
Any suggestions?

**Comment by parg** [comment]
Hmm, it definitely shouldn't have offered to import settings, not sure why that didn't happen :(

Did you use the Help menu's Advanced->Show Configuration Changes... dialog to compare settings?

Meantime I'll have a play

**Comment by parg** [comment]
Did you uncheck

show the main windopw when a download is added by another application

under Alerts?

**Comment by ZioFeda** [comment]
I did! 
I think the reason it didn't ask me to import the config is that I used to keep my Vuze config files in a customized folder, on a drive different from C. I might try to put them back in their default folder and see what happens, if you think it'll help with my issue. 

Meanwhile, I'll do what you said in your first post, I didn't even know that log existed :)

**Comment by parg** [comment]
OK, think I reproduced it, don't message things up by moving your old config :)

**Comment by ZioFeda** [comment]
Perfect, thanks :) I'll just leave everything as it is then. After checking that log, I didn't see major discrepancies and\or options I might have forgotten to deal with.

**Comment by parg** [comment]
Hmm, actually for me it was a donation window that was attempting to be shown (and failing for another reason) that was causing BiglyBT to be shown :(

**Comment by parg** [comment]
So, just to recap, I have 

Options->Alerts:

Show the main window when a download is added by another application - UNCHECKED
Reduce situations where the main window is automatically shown - CHECKED

Options->Files:

When opening a torrent, show options dialog: NEVER AGAIN

Options->Interface->Display:

Suppress File Download popup dialog - CHECKED

With these settings adding a magnet via a browser doesn't cause BiglyBT to be shown/moved above other windows regardless of whether it is minimised to task bar, minimised to system tray or just obscured.

**Comment by ZioFeda** [comment]
> 
> 
> So, just to recap, I have
> 
> Options->Alerts:
> 
> Show the main window when a download is added by another application - UNCHECKED
> Reduce situations where the main window is automatically shown - CHECKED
> 
> Options->Files:
> 
> When opening a torrent, show options dialog: NEVER AGAIN
> 
> Options->Interface->Display:
> 
> Suppress File Download popup dialog - CHECKED
> 
> With these settings adding a magnet via a browser doesn't cause BiglyBT to be shown/moved above other windows regardless of whether it is minimised to task bar, minimised to system tray or just obscured.

Yeah, that seems right...now at least. Yesterday I tested it with those exact settings, but it would sometimes steal focus when the torrent was added to the list (after the "metadata download"). Now apparently that configuration works fine, and I'm not entirely sure what caused the difference in behaviour. I'll test it a bit more.
I would still love to find a way to have the popup not suppressed and not stealing focus, like it was in Vuze, but I can settle for this solution if it keeps working.

**Comment by parg** [comment]
Next beta should allow you to leave the 'suppress file download popup dialog' UNCHECKED as long as you have the 'reduce situations where...' CHECKED
