### ISSUE TITLE
Search expression changes not reflected when creating a subscription based on a Swarm search

### ISSUE THREAD

**Issue by WolfInABowl** [BiglySoftware/BiglyBT#1123]
OS: Windows 10
BiglyBT ver: 2.0.0.0

Sorry if this has been discussed before

It appears that creating a subscription from a Swarm search only uses the original expression - any modifications are not reflected in the subscription.
E.g. If I were to create a search of 'Foo', change it to 'Bar', and then create a subscription from it; the subscription would be of 'Foo'.

**Comment by parg** [comment]
Should be fixed in version 0.7.1 available to beta users (see Help menu for option to join beta program)

Thanks!
