### ISSUE TITLE
Stuck at 99.9% 

### ISSUE THREAD

**Issue by almozayaf** [BiglySoftware/BiglyBT#1124]
I didn't had these problem before , but few days ago Bigly start to take 100% Torrents and make them into 99.9% and I have no idea why

* Window 10
* BiglyBT Version 2.0.0.0

**Comment by parg** [comment]
Make sure your 'mode' is set to Advanced (Tools->Options->Mode) then stop the 99.9% torrents, right-click on them and select the 'force-recheck' icon. If after doing that they still show as incomplete then it is likely that either something has modified the files you downloaded or you have a hard-disk issue.
