### ISSUE TITLE
ToolBar Disappears (toggle VIEW->ToolBar to fix)

### ISSUE THREAD

**Issue by dbareis** [BiglySoftware/BiglyBT#1125]
I don't know what causes it but sometimes the toolbar disappears ("VIEW->ToolBar" is still ticked), click it twice to restore it.

---
Java 1.8.0_201 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_201

SWT v4922, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.0.0.0/4 az2

**Comment by parg** [comment]
Is it missing on startup or does it vanish during use? When it vanishes is there space left where it should be or does it look the same as if you had unchecked the menu option?

**Comment by dbareis** [comment]
I will take more notice next time however I believe it is OK on startup as I use it a lot and that it's just not there at all (if it's partial, it is subtle).

**Comment by dbareis** [comment]
I've left the app running a few days now, occasionally minimizing, maximising and trying other things, so far nothing out of the ordinary.  Is there a hotkey to toggle the toolbar that could be getting invoked accidentally?

**Comment by parg** [comment]
There's no hotkey for that - the fact that the menu still shows as checked means that BiglyBT still thinks it should be visible.

**Comment by Blackbagz** [comment]
it's 2020 and the toolbar still disappears. I minimise it and come back to it at irregular intervals and the toolbar is gone. i have to go view\toolbar to remove the tick, then repeat to re add the toolbar again. this is still happening,

**Comment by Thanny0ther** [comment]
This still happens with the latest version.  The toolbar area is still allocated, but none of the buttons are drawn.  Every time I've had it happen, it's after the window has been invisible for an extended period of time (i.e. "minimized" to the system tray).  I know of no way to deliberately reproduce it.
