### ISSUE TITLE
[Feature Request] Dark Mode 

### ISSUE THREAD

**Issue by hadam9** [BiglySoftware/BiglyBT#1127]
Hello
I see B11 added dark theme alpha support, but I can't find how/where to activate dark theme manually without having Mojave.
If this not available please can you add it to the settings? 
Dark mode for MAC, Windows, etc too..
Thanks.

2001_B11
...
"OSX dark theme alpha support"

 OS and version: Mac OS High Sierra
 BiglyBT Version Number: B11 Beta

**Comment by parg** [comment]
It requires native OSX support and thus Mojave+ I'm afraid, There is no Windows or Linux support in the UI library BiglyBT uses (SWT)

**Comment by parg** [comment]
oh, and to activate it you need OSX to be in dark mode and then go to Tools->Options->Interface->Color and select the native theme support + restart.

There are lots of issues (e.g. sidebar font invisible) which is why it is alpha...

**Comment by hadam9** [comment]
Please add dark mode without Mojave and for other platforms.

**Comment by Asgardsurfer** [comment]
Thanks parg et al, I'm liking the "Dark Mode" even if it's not finished yet! Thanks!
I'm on Mojave 10.14.5.

**Comment by parg** [comment]
B13 should show a few improvements

**Comment by Asgardsurfer** [comment]
Sidebar looking good now, great!
![Screen Shot 2019-07-03 at 6 56 58 AM](https://user-images.githubusercontent.com/10076020/60587142-b5438380-9d61-11e9-92d0-a4570f77a1fc.png)

**Comment by hadam9** [comment]
Please add dark mode for older Mac like High Sierra, and for other os

**Comment by tiotrom** [comment]
It looks a bit brokwen on Manjaro Gnome - using QT Vimix theme + Kvantum
![image](https://user-images.githubusercontent.com/34804533/61331241-d906cf00-a821-11e9-9e58-d06bb9f41ec9.png)

**Comment by ArtexJay** [comment]
Add support for dark mode in Windows, you don't need to make it OS tied.

**Comment by vomindoraan** [comment]
I'd like to see dark mode supported on Windows 10 as well.

**Comment by ballo** [comment]
Thank you for Dark Mode!

**Comment by RebBlumstein** [comment]
While Windows 10 users wait for a simple "Dark Mode" implementation, is there a way to leverage the "JavaScript Provider" plugin (azjscripter) to change the colors quasi-manually in a few lines of JavaScript?

**Comment by parg** [comment]
Unfortunately not.

**Comment by iansebryk** [comment]
any word on when this will be available on Win10?  my eyes are bleeding...

**Comment by lucknaumann** [comment]
@iansebryk Your answer, or at least a temporary one, may lie [here](https://github.com/BiglySoftware/BiglyBT/issues/1841#issuecomment-718206381), my friend. Or [here](https://github.com/BiglySoftware/BiglyBT/issues/1841#issuecomment-718500141).

**Comment by iansebryk** [comment]
thanks @lucknaumann!  appreciate the pointers.  😃
