### ISSUE TITLE
Your tracker bloats with external torrents

### ISSUE THREAD

**Issue by mppdidi** [BiglySoftware/BiglyBT#113]
Your tracker http://jcgok7sfv2ycwdluzjr6s5bdca4ps6beaogilp72dzl6mopp46ya.b32.i2p:6968/ bloats with external torrents making it really slow - unless this is intentional behaviour.

**Comment by parg** [comment]
It is probably slow because it is actually running on my main test BiglyBT instance which gets rebooted a lot...

**Comment by mppdidi** [comment]
That maybe true but a couple of days ago there where dozens of external torrents with only dht hashes - that's what I was referring to.

**Comment by parg** [comment]
dozens of entries won't trouble performance ;)
