### ISSUE TITLE
Conversion from VUZE to BiglyBT

### ISSUE THREAD

**Issue by VeeJai123** [BiglySoftware/BiglyBT#1134]
I don't know if this is the right place for this help request or not. If it is not if someone could direct me to the proper venue I would greatly appreciate it. If I am in the right place any help or suggestions would be appreciated as well.

**My issue:**
I cannot get BiglyBT to update any tracker (private or otherwise). I Closed/Stopped VUZE and verified such in task manager. Then installed BiglyBT 64bit downloaded from BiglyBT site. It installed correctly and duplicated/imported all the setting from VUZE correctly (including ports #s etc.)  and I see all my torrents in BiglyBT now.
I think the problem is: BiglyBT not updating any of the trackers for my torrents so all my existing torrents although there and active, show 0 Seeds and 0 Peers even though they are active.
Added a new torrent with 12 seeders to see if it was just a problem with the existing torrents and have the exact same problem. It shows downloading and 0 Seeds and 0 Peers.

* OS and version: Windows Server 2016 Standard X5560 2.80GHz [rpcesspr. 40 GB Memory
Java 1.8.0_202 (64 bit)   Oracle Corporation c:\program files\biglybt\jre
SWT v4922, win32, zoom=100, dpi=96

Windows Server 2016 v10.0, amd64 (64 bit)
B2.0.0.0/4 az3
* BiglyBT Version Number: 2.0.0.0

* For *nix: Desktop Environment

Thanks Vee Jai

**Comment by parg** [comment]
Is there any error message displayed against the trackers in the 'sources' view (sub-tab)?

You could also check the logs for any errors - go to the Help menu and select the last option to generate diagnostic information. This produces a .zip file containing various logs. Check out the debug_1.log (and debug_2.,log file if it exists) for any errors.

You could also try with this torrent:

https://download.documentfoundation.org/libreoffice/stable/6.2.4/win/x86_64/LibreOffice_6.2.4_Win_x64.msi.torrent

**Comment by o0nd7ots** [comment]
@parg Can we close this?

**Comment by parg** [comment]
Closing as nothing's going to happen here, re-open if so desired.
