### ISSUE TITLE
Remove button becomes greyed-out and disabled for all completed downloads

### ISSUE THREAD

**Issue by dmorchard** [BiglySoftware/BiglyBT#1137]
To elaborate on the title, once torrents are seeding they can no longer be removed from the "Advanced List" view via the red X button at the right end of the toolbar.  When I mouse-over it I see the tool tip, but it is greyed out and doesn't respond to any mouse click.  Resorting to the delete key or the remove button in the context menu does work.

If I switch to "Simple List" the toolbar button behaves as expected.

**"System" section of the Help->About window...**
   Java 1.8.0_201 (64 bit)
   Oracle Corporation
   c:\program files\java\jre1.8.0_201

   SWT v4922, win32, zoom=100, dpi=96
   Windows 10 v10.0, amd64 (64 bit)
   B2.0.0.1_B14/4 az3

While downloading the button appears normal...
![image](https://user-images.githubusercontent.com/30359271/60677210-79ceb500-9e46-11e9-8547-85868971bf2e.png)

While seeding in "Advanced List" view it goes grey and won't work...
![image](https://user-images.githubusercontent.com/30359271/60677271-ada9da80-9e46-11e9-922e-736161b6452b.png)

It's sibling in the context menu functions as expected...
![image](https://user-images.githubusercontent.com/30359271/60677657-bbac2b00-9e47-11e9-8e97-dff42dc8dd1b.png)

While seeding in "Simple List" view it works as expected...
![image](https://user-images.githubusercontent.com/30359271/60677929-7d633b80-9e48-11e9-9b5a-fe7ace6bf7a5.png)

**Comment by parg** [comment]
Very peculiar! I can't reproduce this with a pretty similar setup, does the problem still occur after a restart of BiglyBT? How about if you ctrl+click on it in the Library to deselect it and then reselect it?

**Comment by dmorchard** [comment]
It is persistent after a restart, and has been an annoyance for weeks now, if not months.  I dunno how many beta updates it has survived.

CTRL + click on a seeding torrent in "Advanced List" view does toggle selection of the torrent on/off, and correspondingly other buttons on that same toolbar toggle from regular to greyed-out.  The remove button remains grey however.

I suppose I should try a complete reinstallation if you've got no other ideas.  I've just been avoiding that hassle :)

**Comment by parg** [comment]
re-installing is most unlikely to make any difference :( Can you generate a debug.zip file (Help menu, last item) after reproducing the problem a few times and then send it over to parg@users.sf.net? Thanks!

**Comment by dmorchard** [comment]
In the process of generating several debug.zips for you I've discovered more worth reporting.  I've decided to delete an incomplete download and in "advanced list" view the "Remove" button appears normal.  However, when I click on it nothing happens.  After a few clicks the button goes grey.  Toggling selection of the download (which I've now paused) resets the "Remove" button's appearance but it still doesn't function.  I've got to resort to one of the alternatives previously mentioned to get rid of it.

**Comment by parg** [comment]
Thanks, think I've fixed it, please test next beta when available!

**Comment by dmorchard** [comment]
Will do.  Thanks a bunch :D

**Comment by dmorchard** [comment]
Fixed! 👍
