### ISSUE TITLE
Tag Move On Complete ignoring Move Torrent setting

### ISSUE THREAD

**Issue by dizzyMongoose** [BiglySoftware/BiglyBT#1142]
Java 1.8.0_181 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4922, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.0.0.0/4 az3

When using the **Move On Complete** functionality of tags from the Tags Overview, I have a folder assigned with **Move data** checked but not **Move torrent**. However, after my torrent is done downloading, BiglyBT is moving both my data and the torrent file into the new folder. My testing of Move On Assign and Copy On Complete resulted in the torrent file staying in its original location as expected, so Move On Complete specifically is doing it wrong.

I've included a screenshot of the tag settings from Tags Overview.

![image](https://user-images.githubusercontent.com/26749854/60760386-e803ab00-9ff1-11e9-8428-f9c35b7bcb07.png)

**Comment by PrototypeZero** [comment]
You any other tags assigned to the torrent (with or without move torrent selected?).  Or the default option set to move torrents?

Bigly does *very* occasionally in my experience get confused on which tag options to use, tag options always override defaults (as it should) but tag vs tag sometimes works strangely, sometimes the 1st tag to be applied "wins" other times the last tag "wins".

Sometimes the only way i found to fix it was delete the tag, restart Bigly and recreate the tag.

**Comment by dizzyMongoose** [comment]
I only have the one tag assigned to the torrents, and by default torrents stay where they are. I've tried this with both my existing tag and the Test tag I created for that screenshot, and in both cases the torrent moves on complete to the same folder as the data despite not being flagged to do so.

**Comment by parg** [comment]
When multiple move/copy on whatever tags apply BiglyBT is supposed to use a deterministic means of selecting which tag to use - currently it is based on a 'unique id' assigned when the tag is created. You can't directly control this but when confronted with a set of such tags it should always select the same one.

**Comment by parg** [comment]
The incorrect torrent moving will be fixed in the next beta, thanks! 

If you want to fix it manually then go to Tools->Options->Files->Completion Moving, enable 'Move completed files (after download)', deselect the 'Move .torrent' associated with this, then deselect the 'Move completed files (after download)'.
