### ISSUE TITLE
Move on completion error

### ISSUE THREAD

**Issue by JustCallBen** [BiglySoftware/BiglyBT#1143]
* Windows 8
* BiglyBT Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4922, win32, zoom=100, dpi=120
Windows 8 v6.2, amd64 (64 bit)
B2.0.0.0/4 az3

When files have completed d/l they are to be moved from the temporary directory (...\Downloads) to the final destination (\...Watched).  This worked fine in Vuze. 

Now it seems the .torrent files, in full size, are being saved in the destination directory and the data file is being saved in the Downloads directory.  I didn't change any settings yet since migrating from Vuze today.

I used a magnet link to start the files.

![biglybt screenshot 3](https://user-images.githubusercontent.com/37347074/60761325-d2df4a00-9ffa-11e9-8bdf-6f7510c4e23b.jpg)
![biglybt screenshot 2](https://user-images.githubusercontent.com/37347074/60761326-d2df4a00-9ffa-11e9-9199-02d7f9a72b63.jpg)
![biglybt screenshot](https://user-images.githubusercontent.com/37347074/60761327-d2df4a00-9ffa-11e9-9299-32db87696387.jpg)

**Comment by parg** [comment]
Are you saying that the actual download files are being named <hash>.torrent in the 'move to' location, as opposed to the .torrent files themselves? 

Perhaps you could go to the Help menu, generate a debug.zip from the last option there and then email it to parg@users.sf.net? Thanks

**Comment by JustCallBen** [comment]
I've emailed you the file.  I also noticed today that moving data files (I have "To Be Watched" and "Watched" folders) takes a very long time.  Something like what Azureus used to do way back when.  I have the "copy then delete" option unchecked.

**Comment by JustCallBen** [comment]
I've emailed you the file. Edit: I tried but the email was bounced on error "550 Blacklisted file extension detected ".

 I also noticed today that moving data files (I have "To Be Watched" and "Watched" folders) takes a very long time.  Something like what Azureus used to do way back when.  I have the "copy then delete" option unchecked.

**Comment by parg** [comment]
try renaming the debug.zip to just debug and see if that gets through
