### ISSUE TITLE
Auto move to "tag" path when finished & many other questions.

### ISSUE THREAD

**Issue by fusk-l** [BiglySoftware/BiglyBT#1149]
In "files/torrents" you can set watch folders and auto assign tags/labels to torrents added from those folders. 

What i can't figure out is how i assign a default save path for created tags. So a torrent loaded from X:\gdrive or dropbox\dir1 gets a dir1 tag, and when finished is moved from scratch disk to default save location for tag "dir1" at X:\dir1. Watch folder dir2 get's the same treatment with a user defined tag and save path, and is saved to X:\dir2 when moved from scratch disk.

**Comment by parg** [comment]
You need to set the 'initial save location' for the Tag under Tag Settings - likewise 'move on complete' location

**Comment by fusk-l** [comment]
And where are those tag settings located?
I've expanded every setting and can find no such options.

**Comment by parg** [comment]
View menu -> Tags Overview (or if you are using the default UI with the sidebar then right-click on the Tag there and select settings.

**Comment by fusk-l** [comment]
Ohhh, it's not in settings, but view/tags overview, now i see what you mean.
Can i ask another question, or should i create a new topic so others might pitch in?

**Comment by parg** [comment]
Ask another one here, probably easiest!

**Comment by fusk-l** [comment]
I've been through all the settings, but there's many i have not seen before, some which are worded in a way that i'm not entirely sure how to interpret. Like settings/connection "enable public tcp peers", does that mean tcp peers from outside the tracker reported peers, or is it tcp peers from your wan.

So basically i want to disable or remove anything that's related to "public", that is any discovery function, dht, pex etc. etc.

**Comment by parg** [comment]
The only downloads that get added to BiglyBT automatically are component updates - the .zip files have names like "plugins_xxxx.zip" and "swt_yyy.zip". If you join the beta program then the beta updates are also distributed by torrent (named "core_zzz.zip").

Often the word 'public' refers to the public internet (as opposed to I2P/Tor connections).

The difference sources of peers are under 'Peer Sources', there are defaults and also per-torrent settings if needed:

From a tracker - returned directly by a tracker
Decentralized tracking - DHT peers
Supplied by another peer - PEX
Added by a plugin - like it says
Incoming - incoming connection from another client

If you don't like DHT then you can disable it entirely under plujgins->Distributed DB

**Comment by fusk-l** [comment]
By "related to "public"" i mean anything that isn't reported from tracker, or any feature that could leak/share data with outside peers.
I'm coming from qbittorrent, but libtorrent has some issues with write performance at gbit speeds and raid arrays. Hoping biglybt is the solution as what i read is positive.

Do you have any suggestions to memory configuration for faster connections with fast storage?

**Comment by parg** [comment]
If the torrents you have are marked as 'private' then that automatically disables DHT/PEX - if not then it sounds as if you want to disable those peer sources in the defaults and perhaps check in the 'all peers view' (see Tools menu; right-click on a column header and select 'column setup' to enable the 'peer source' column) to see what connections you are getting.

If you're really worried about peers coming from the tracker then I suppose you could also disable 'incoming' connections but that'd generally impact connectivity.

Memory usage is mainly related to the number of concurrently running torrents. BiglyBT does have a file cache (under Files->Performance options), you could play with the size but don't make it enormous.

You may also want to experiment with the advanced networking options under Connection - dropping the read/write selector timeouts a bit might improve speeds at the cost of increasing CPU.

**Comment by fusk-l** [comment]
Thanks.
"If you're really worried about peers coming from the tracker" I only want peers from the tracker and from nowhere else. Most private trackers have those things disabled, but i'd like to do it client side as well.
I have 200/300 torrents running.

**Comment by parg** [comment]
If you can let the seeding rules (Options->Queue) manage your completed torrents so not too many are actually active at a given time - definitely don't 'force start' downloads unless you really want them to be permanently active.

**Comment by parg** [comment]
There's a bit of discussion on memory in https://github.com/BiglySoftware/BiglyBT/issues/92

**Comment by fusk-l** [comment]
All remains actively seeding after completion, but not very many ~10/12 has active traffic at the same time, most of those are sub 500kb/s. I have max downloads at 3, but that's also not very often that happens.
I'll have to look into that read/write selector thing, not entirely sure what that is yet.

**Comment by fusk-l** [comment]
Found a potential problem, when creating a tag. Max upload speed 0 = unlimited. But when entering a 0 it turns red and defaults to 1 next time you click the tag.

**Comment by fusk-l** [comment]
What are the two choices for encryption, any compatibility issues with other clients?

**Comment by parg** [comment]
There's a bug in 2.0.0.0 regarding Tag upload speed - either right-click on the Tag in the sidebar to set the speed or join the beta program to get a fix.

Transport encryption of plain/RC4 is supposed to be supported by all clients - https://wiki.vuze.com/w/Message_Stream_Encryption

**Comment by fusk-l** [comment]
Alright, just havn't seen the option to pick between encryptions. Are there performance differences between the two?
I just set upload speed to 1500, then that's not gonna be an issue. I was looking at statistics, and couldn't find any I/O overload indicator, is there such a thing?

I set cache size to 100mb, i don't know if that's a bit on the low side for gbit. Maybe biglybt just works a bit differently than what i'm used too.

**Comment by fusk-l** [comment]
Can the dashboard be removed?
In settings/transfers there is a max upload timer setting, it's defaulted at 30 secs and i have no idea what that's for.
In tag overview, there's several tags like "all", they don't show up in the side panel when enabled.
Can the columns be set to a standard so you don't have to do it manually for every window?

**Comment by parg** [comment]
'All' might be a category, ignore it unless you're interested in using the deprecated category feature

max upload timer - can't remember, ignore it :)

dashboard - Options->Interface->Display: Sidebar - Header order - remove '1' from it and restart.

Are the bind errors on BiglyBT startup or when starting a torrent? Do you have two copies of BiglyBT running on the same machine?

**Comment by fusk-l** [comment]
Just one copy, the other port was used with qbittorrent. It's when torrent starts, they start downloading, then stalls for ~30secs and then continue. This was with debian dvd's, and maybe not the best way to test.

**Comment by mighelch** [comment]
> If you're really worried about peers coming from the tracker then I suppose you could also disable 'incoming' connections but that'd generally impact connectivity.

Is it necessary? Aren't peers still coming from a tracker (obtained from another peer on this tracker)?

> Added by a plugin - like it says

What are the plugins that can add peers? I would guess dht, which is disabled anyway. Aren't they ingored if torrent have "private" flag?

**Comment by fusk-l** [comment]
> 
> 
> > If you're really worried about peers coming from the tracker then I suppose you could also disable 'incoming' connections but that'd generally impact connectivity.
> 
> Is it necessary? Aren't peers still coming from a tracker (obtained from another peer on this tracker)?
> 
> > Added by a plugin - like it says
> 
> What are the plugins that can add peers? I would guess dht, which is disabled anyway. Aren't they ingored if torrent have "private" flag?

**Comment by fusk-l** [comment]
Ops.

**Comment by fusk-l** [comment]
Getting a memory allocation failure. Says something about command line to fix.

**Comment by parg** [comment]
make your cache smaller or follow the instructions to increase JVM heap (under Startup&Shutdown options, near the bottom)

**Comment by fusk-l** [comment]
But why the error when there's a limit and the cache descriptions says it needs to only be 32mb smaller than, isn't that created to avoid that?

**Comment by parg** [comment]
Try Heap

**Comment by fusk-l** [comment]
The stalling seems to have something to do with bigly doing something on the disk. After adding torrent it runs for ~15 secs, then stalls. But in task manager i can see there's a lot of disk activity, how do i get it to stop doing that and just continue download?
It looks like it's allocation space.

**Comment by parg** [comment]
enable sparse files under Files?

**Comment by fusk-l** [comment]
I just did, i sort of remember what sparse files do. But don't know if having it off would cause such behaviour.

**Comment by fusk-l** [comment]
I am also getting some unable to bind port to server and listen server socket errors. And i don't understand those as server socket refers to 127.0.0.1 and bind is set up correctly with lan ip, port forwarding is fully functional.

**Comment by parg** [comment]
Generate a debug.zip file (Help menu, last option) and then look at the debug_1.log (and debug_2.log) files to see if there is any context around the bind fails

**Comment by fusk-l** [comment]
Well, it says "java.net.BindException: Address already in use: bind" and then a long list of components. Debug2 has a lot of these "Table Cell Plugin for Column #r10c5:this plugin is crazy. tried to refresh 10 times in 68ms"
and these where it either increases or decreases "Network interface enumeration took 392: increased refresh frequency to 120000ms"

**Comment by parg** [comment]
that long list of components - that'd be useful

**Comment by fusk-l** [comment]
java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Unknown Source)
	at sun.nio.ch.Net.bind(Unknown Source)
	at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
	at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
	at com.biglybt.core.networkmanager.impl.tcp.VirtualBlockingServerChannelSelector.startProcessing(VirtualBlockingServerChannelSelector.java:86)
	at com.biglybt.core.networkmanager.impl.tcp.IncomingSocketChannelManager.startProcessing(IncomingSocketChannelManager.java:429)
	at com.biglybt.core.networkmanager.impl.tcp.IncomingSocketChannelManager.<init>(IncomingSocketChannelManager.java:147)
	at com.biglybt.core.networkmanager.impl.tcp.TCPNetworkManager.<init>(TCPNetworkManager.java:130)
	at com.biglybt.core.networkmanager.impl.tcp.TCPNetworkManager.<clinit>(TCPNetworkManager.java:50)
	at com.biglybt.core.networkmanager.NetworkManager.getMinMssSize(NetworkManager.java:319)
	at com.biglybt.core.networkmanager.impl.ByteBucketST.ensureByteBucketMinBurstRate(ByteBucketST.java:172)
	at com.biglybt.core.networkmanager.impl.ByteBucketST.<init>(ByteBucketST.java:58)
	at com.biglybt.core.networkmanager.impl.ByteBucketST.<init>(ByteBucketST.java:44)
	at com.biglybt.core.networkmanager.impl.TransferProcessor.createBucket(TransferProcessor.java:669)
	at com.biglybt.core.networkmanager.impl.TransferProcessor.<init>(TransferProcessor.java:99)
	at com.biglybt.core.networkmanager.NetworkManager.<init>(NetworkManager.java:206)
	at com.biglybt.core.networkmanager.NetworkManager.<clinit>(NetworkManager.java:54)
	at com.biglybt.core.impl.CoreImpl.<init>(CoreImpl.java:337)
	at com.biglybt.core.impl.CoreImpl.create(CoreImpl.java:170)
	at com.biglybt.core.CoreFactory.create(CoreFactory.java:43)
	at com.biglybt.ui.Main.main(Main.java:192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.biglybt.launcher.MainExecutor$1.run(MainExecutor.java:37)
	at java.lang.Thread.run(Unknown Source)

**Comment by parg** [comment]
Whatever bind/port you have set up under 

Options->Connection: Incoming TCP listen port

is already in use by something else.

**Comment by fusk-l** [comment]
That's what it says, but that port is not in use by anything. But regardless i can change it.

**Comment by parg** [comment]
Maybe antivirus or something preventing binding

**Comment by fusk-l** [comment]
No, bigly has the exact same rights as qbittorrent has in the OS, only difference is the port they use. The port forwarding are identical besides the port number.

**Comment by fusk-l** [comment]
What exactly does "read/write selector timeouts" do and when you said lower it a bit, how much did you mean. From 25 to 23, or 25 to 15?

**Comment by parg** [comment]
try 10, see if that improves speeds without excessive CPU

**Comment by parg** [comment]
netstat -a -b will show you what process is using a given port

**Comment by fusk-l** [comment]
If i run the network status, it says success on both in and out tcp, only udp out, but that's disabled any ways. Also, the error is not constant, seems like it mostly appears when the app is restarted.

**Comment by fusk-l** [comment]
netstat -a -b doesn't show that port being used by anything else than bigly.

**Comment by fusk-l** [comment]
The listen socket error writes 127.0.0.1 and not lan ip, not sure. But could it be trying to bind to the wrong interface maybe?

**Comment by fusk-l** [comment]
Tried adding adapter, but did not notice a difference.
Bind to. lan ip;eth6[0]
eth6	(Hyper-V Virtual Ethernet Adapter #2)
		eth6[0]	lan ip
		eth6[1]	fe80:0:0:0:796b:a116:2ec2:74cb%eth6

**Comment by parg** [comment]
remove all bind settings under Advanced Network Settings:

Bind to local IP - blank
Bind to local Port - 0 [disabled]

see if the problem occurs then

**Comment by fusk-l** [comment]
Ok.
These are the present settings, anything you notice that could adjusted for higher performance?
https://pastebin.com/cUBxr8EH

**Comment by parg** [comment]
Looks reasonable - maybe not have unlimited active torrents but see how it goes

**Comment by fusk-l** [comment]
Unlimited is fine, it's limited by the mechanical storage array. I don't remember it ever going above 300 torrents.
Btw, in the tags next to upload, there's a "upload priority" tick box, what does that do?

**Comment by parg** [comment]
Tries to give bandwidth upload priority to the associated downloads

**Comment by fusk-l** [comment]
> 
> 
> Tries to give bandwidth upload priority to the associated downloads

So without that ticked, it will actively try to prioritize download even tho bandwidth is available for upload?

**Comment by parg** [comment]
Without it ticked then all peers get the same upload priority (at the network level, when scheduling bytes to be delivered to peer connections)

With it ticked, peers connected to the downloads with 'upload priority' will get preferential scheduling.

**Comment by fusk-l** [comment]
I tried ticking it a few hours ago, and believe i noticed significantly increased upload, but thought that might've been a coincidence.

**Comment by fusk-l** [comment]
Know what this is: scrape error, server returned http 403?
I have not seen that error before.

**Comment by parg** [comment]
https://www.google.com/search?q=http+403

**Comment by fusk-l** [comment]
Wouldn't it then be the same for all torrents using the same tracker, and not just some of them?

**Comment by parg** [comment]
no idea

**Comment by fusk-l** [comment]
Tracker says online and the same torrent where there's a scrape error.

**Comment by parg** [comment]
tracker error

**Comment by fusk-l** [comment]
Could it have something to do with idle torrents?

**Comment by fusk-l** [comment]
I don't think there's any sensitive info in there i didn't remove.

**Comment by fusk-l** [comment]
I've noticed the torrent sometimes starter later than other peers, like. It'll start the torrent, but when it actually starts downloading, other peers are already at 70%. Is there a setting for refreshing tracker when either there is no seeders/peers yet on newly added torrents or torrent is unregistered more aggressively?
And afterwards going back to normal refreshing to avoid hammering tracker.

**Comment by fusk-l** [comment]
![Udklip](https://user-images.githubusercontent.com/6765298/61184702-444d7700-a651-11e9-8a8c-a6774486e253.PNG)

Looking at this, is 400mb cache reasonable or overkill as mentioned in the settings that 32mb is probably enough for anyone?

Besides that, everything appears to be running smoothly.

**Comment by parg** [comment]
The cache mainly helps with saving writes and the read required to hash check a piece - the blocks that make up each piece are generally downloaded in order ending up in the cache. Once the piece is complete it is read for hash checking - if it is already in cache then it is read from there. The piece is then written as a single write (if things work out). Other peers are then informed that you have the piece, this  may result in them requesting it from you and if it happens to be in cache then the read will be saved.

Anyway, the most savings are obtained from having a cache sized roughly to 'number-of-active-pieces * piece-size' across all active torrents.  Take a look at the pieces view. maybe you have 10 active? If each piece is 1MB then a 10MB cache would cover this (well, add some slack, say 20MB)

**Comment by fusk-l** [comment]
I was looking at the piece view, and thinking if a piece is 16mb, then having 15 incomplete pieces would require up to 240mb to make sure pieces are written as one write. 1mb is minimum, piece sizes ranges from 1 to 16 but most are somewhere in between.
But in this scenario there's not a lot of space for cached reads, so making the cache bigger to be able to house both large incomplete pieces and cached reads to increase hit% to cache and alleviate the disk activity a bit. Maybe i'm just going at it wrong.

**Comment by parg** [comment]
16MB pieces are insane

**Comment by fusk-l** [comment]
~15% out of 86 torrents are 16mb. But 4mb is the most common.

**Comment by parg** [comment]
Check the pieces view on an active torrent - if the piece size is 16mb then there shouldn't be that many active. The '32mb' advice is probably a bit old from when torrents didn't tend to be so large. I know that the advice used to be to try and keep the number of pieces in a download around 2000. The issue with very large pieces is that the hash-check process works at the piece level. If there is any corruption within the piece then the whole thing needs to be re-downloaded.

**Comment by fusk-l** [comment]
One of them is 16mb at 2295 pieces.

Someone on libtorrents did a piece iops test over gbit lan and found that pieces below 2mb would cause disk iops, solved by increasing to 4mb to utilized the max potential of the disk.
I believe utorrent torrent creator tries to keep number of pieces around 2000 and auto scale pieces up to 16mb.

**Comment by fusk-l** [comment]
Sorting by date added, how do flip dates so they display correctly?

**Comment by parg** [comment]
right-click column header and set the date format you want (whatever you mean by 'correctly')

**Comment by fusk-l** [comment]
I tried doing that, but i have no idea what the output, tried it yesterday and output was 195, time went missing.

**Comment by parg** [comment]
https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html

**Comment by fusk-l** [comment]
The "max files open for read/write" is that open pieces or the entire file. Is there a statistic somewhere which shows how many are in use?

**Comment by parg** [comment]
No stats available - it is the maximum open files, nothing to do with pieces. When the limit is exceeded files are closed and re-opened as required.

**Comment by fusk-l** [comment]
Alright, 50 seems resolvable then.
I am having a hard time figuring out the memory. I have max heap set to 1gb, and cache to 700mb which ran into memory errors, so lowered it to 650mb.
But, does it use more memory for every torrent added, so even if has the difference of ~350mb available, that will eventually run out as more torrents are added?

Cache does state "keep this value at least 32mb below your max VM" where VM is max heap. But this does not appear to be true if you get memory errors when it had 300mb.
Would it be better if i set max heap to just default and then instead set direct memory to ~650mb?

**Comment by parg** [comment]
There are two main types of Java memory:

Heap memory - used for the various 'normal' objects created by BiglyBT to maintain state, UI etc.
Direct memory - mapped directly to physical memory and efficient at passing data between Java and the IO subsystems (networking, disk IO).

Without the use of direct memory data would be copied between heap memory and network buffers all the time, impacting performance.,

Direct memory is used by BiglyBT to the disk cache and also for network buffers (packets are assembled into direct memory and then handed directly to the networking system). The amount of memory required for networking is linked to the amount of queued/inflight network traffic so can be many MB. Direct memory is also used internally by the JVM but I don't think that much. 

The number of torrents you have loaded within BiglyBT mainly impacts the heap memory. The number active will also impact direct memory for networking. The cache will fill on use and then generally stay pretty full so you should assume that the minimum amount of direct memory needed is 'cache size' + 'in flight network data' + X.

In early versions of Java the direct memory was explicitly set to some number of MB. At some point the default became 'same as heap memory'.

**Comment by fusk-l** [comment]
Have 109 torrents, ~10 active.
It sounds like it would be better to set a lower heap, and then use direct which is presently empty/default in the settings. Is 50mb enough for network IO or how much difference should there be between direct and cache?

**Comment by fusk-l** [comment]
Oh, heap has to be larger than direct. If heap is 600 and direct 400, does that take 1gb of memory or is the 400 used from the 600?

**Comment by parg** [comment]
1GB

**Comment by fusk-l** [comment]
Alright, so if you wanted to have ~650mb cache, what values would you use and where would you enter them?

**Comment by parg** [comment]
750mb max direct memory, 256mb max heap (Options->Startup & Shutdown: Java Options) perhaps

**Comment by fusk-l** [comment]
But if heap is 256, then you can't enter 650 in the cache settings.

**Comment by parg** [comment]
meh, make the heap 650 then

**Comment by fusk-l** [comment]
So 750 in direct, 650 in heap and 650 in cache?

**Comment by fusk-l** [comment]
650 heap will only allow me to put 546 in cache.

**Comment by parg** [comment]
heh, who wrote this stuff! you can figure it out :)

**Comment by fusk-l** [comment]
It makes no sense to me, at all.

**Comment by fusk-l** [comment]
It would be easier if heap & direct memory auto adjusted after what your cache setting is.

**Comment by fusk-l** [comment]
Still getting "disk error: direct buffer memory" I set heap to 1gb, direct to 850 and cache to 750. I don't understand what the problem is.

**Comment by parg** [comment]
Set your cache to 400mb see what happens

**Comment by fusk-l** [comment]
Also got the error at 700, now lowered to 600.

**Comment by fusk-l** [comment]
Listening errors appears to be because when starting bigly, it errors before nat = ok. The socket error to localhost i haven't figured out yet. But doesn't seem to do anything relevant.
