### ISSUE TITLE
Groups - Tags - Collapse All Not Working

### ISSUE THREAD

**Issue by ms52538** [BiglySoftware/BiglyBT#1157]
The "Collapse All" function, when right-clicked on the Tag, which is nested within a Group, is not working.

This would be the Client View, left-hand area where Categories and Tags appear within the "My Torrents" area.

Windows 10
BiglyBT Windows Beta Version B2.0.0.1_B-18/4 az3
Java 1.8.0_181 (64-Bit)

**Comment by parg** [comment]
The 'collapse all' menu item applies to those downloads in the right-hand torrent view area that have multiple files and have been expanded by clicking on the arrow in the 'name' column - not the left-hand tree view itself. Are you seeing an issue with this or are you expecting the left-hand tree items to be collapsed?

**Comment by ms52538** [comment]
The Dashboard has a split screen and on the left hand side of my screen is the entire view of My Torrents, Default Tags (i.e. Active, Complete, Downloading, Error, inactive, etc.), and what not. Then the other2/3rd's of my screen (center to far right hand side) is there all my torrents appear. So when I click a Tag (or View if that's what they are called", I get the corresponding lot of torrents appearing in the rest of my screen area. Click another one, and those corresponding torrents appear in the screen. 

So let's take the default "Complete", and select it. The corresponding torrents across the screen appear, and some of expandable/collapsable twisties that reflect the multiple files contained within the torrent. So expand 4 or 5 of those. Ok? Now, back over in the Complete Tag/View on the left hand side, right click and select "collapse all", and now the torrents, that had been expanded, are now collapsed back to their singular form (retracted vs. expanded).

Ok, hopefully we are on the same page.

Now, I create a few of my own Tags and those appears on the left hand side of the screen as where the COMPLETE tag/view is located, just below it actually. 

Create 3 different tags (and they each appear on the left hand side of the screen in the same section as the others referenced).  Now go up to the COMPLETE Tag/View and select a  handful  of torrents that contain multiple files, and assign your newly created tags you just made.

Now go and click back on the tags you had just made and test/validate the collapse all feature works. It does for me.

Now take those same tags/views (the new ones you had created for testing purposes and just validated had worked, and now add them into a GROUP. Ok, the names of those tags/views disappear and are replaced with the new GROUP you just created. Click on the group's twistie and expand it, and now you see the newly created tabs/views you had validated earlier that worked. Now expand those tabs/views once again and validate that work within the group. For me, they do not. Is that normal, or a bug. My apologies if it's normal, It's just that the "Collapse" trigger is present within them still, so I expected them to work, and they are not. Sorry, I'm butchering this as usual - but hopefully I got you to the right place.

**Comment by ms52538** [comment]
Sorry, you call that left hand side of the screen the Side Bar.

**Comment by ms52538** [comment]
And I'm using "Simple List" as the default torrent screen.

**Comment by parg** [comment]
thanks, fixed next beta

**Comment by ms52538** [comment]
Nice work! :)  Thank you, Captain.   I have a couple of other issues I've encountered which I'll post separately. ALSO, just an FYI --> On the windows client, when I select the Beta Program page, the page that renders, has a paragraph on the far right side of the page. The last sentence with a link: See the latest commits on GitHub. The "GitHub" link does not launch a browser to open the site. Minor, but just fyi.

Thanks again, as always!

**Comment by parg** [comment]
fixed, thanks!
