### ISSUE TITLE
biglybt update set fedora ask for admin password (possibily)

### ISSUE THREAD

**Issue by legacychimera247** [BiglySoftware/BiglyBT#116]
so, maybe i am completely wrong but i thought to report it just to be sure biglybt is not the culprit...
i don't know if you are familiar with fedora linux but i have set my pc to never ask me any password, unless i input "su" on the terminal for gaining root access...the other morning i have installed biglybt and tried updating to beta (i said "tried" because beta updates weren't working, as i have already reported, biglybt cannot update itself because it requires root access to the folder) and to my surprise the app rebooted and asked my for my root password to finish the update, the opened again. unfortunately the update failed and from that moment on, fedora started asking me for my admin pass for everything like installing/removing software or entering my user account settings...is this just a coincidence or has biglybt something to do with it?

**Comment by TuxPaper** [comment]
It depends on how you originally installed it.  If you installed it using 'su', then it will need (and try) su for updates to the core.  If you installed it without su, it shouldn't.  Where is BiglyBT installed?  If it's in `~/biglybt` then it's installed locally and should never need perms, but if it got installed in `/opt/*` or similar dir, it'll need permissions.

**Comment by TuxPaper** [comment]
Closing issue do to age and lack of update. If anyone still has this issue, please file a new one.  Thanks!
