### ISSUE TITLE
Cannot install on debian 10 (buster)

### ISSUE THREAD

**Issue by tenzap** [BiglySoftware/BiglyBT#1160]
* OS and version : linux debian 10 buster on amd64
* BiglyBT Version Number 2.0
* For *nix: KDE

When running the installer "sh BiglyBT_Installer.sh"
I get the following error

> No suitable Java Virtual Machine could be found on your system.
> The version of the JVM must be at least 1.8 and at most 1.12.
> Please define INSTALL4J_JAVA_HOME to point to a suitable JVM.

I user the default java version of buster : ie 

> openjdk version "11.0.3" 2019-04-16
> OpenJDK Runtime Environment (build 11.0.3+7-post-Debian-5)
> OpenJDK 64-Bit Server VM (build 11.0.3+7-post-Debian-5, mixed mode, sharing)

However, when running biglybt from the unix .tar.gz version, everything is fine

**Comment by Sanyy** [comment]
Same error on Mint 19.

echo $JAVA_HOME
/usr/lib/jvm/openjdk-11

**Comment by parg** [comment]
Try installing from the Unix .tar.gz ?

**Comment by Sanyy** [comment]
From .tar.gz it runs with some error:

Starting BiglyBT...
Suitable java version found [java = openjdk 11.0.4 2019-07-16]
Using swt/swt-x86_64.jar v4.924
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.biglybt.core.util.spi.AENameServiceJava9 (file:/home/user/Downloads/biglybt/BiglyBT.jar) to field java.net.InetAddress.impl
WARNING: Please consider reporting this to the maintainers of com.biglybt.core.util.spi.AENameServiceJava9
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

The installer script does not work.

**Comment by parg** [comment]
Those errors aren't generally that significant, please ignore them

**Comment by TuxPaper** [comment]
The installer at https://github.com/BiglySoftware/BiglyBT/releases has been updated to fix the "No suitable Java Virtual Machine".  www.biglybt.com's installer will be updated within 3-4 hours depending on aws magic.

**Comment by tenzap** [comment]
Thanks. I just tested it and installer loads fine now.
