### ISSUE TITLE
How to turn off the auto peer cat function?

### ISSUE THREAD

**Issue by PrototypeZero** [BiglySoftware/BiglyBT#1162]
Just trying out the auto-peer cat option in B19, turned it on, found it to be completely useless to me, but now can't find any way to turn the auto option off and it survives restarts

Right clicking on any of the cats or peers themselves shows no option that I can see anyway (using classic interface).

**Comment by parg** [comment]
The menu item you used to enable it is replaced by one to edit the peer-set config. Select that then delete the peer_set Auto line
