### ISSUE TITLE
Tag Icons

### ISSUE THREAD

**Issue by PrototypeZero** [BiglySoftware/BiglyBT#1163]
There doesn't seem to be anyway of removing Tag icons once they are set (other than setting it to a deleted/non existent file and restarting which works but leaves the icon space blank instead of "-"). 

Also, is there no way of showing icons for download states in the "Tag Icons" column (it only seems to show manual tag icons)?

**Comment by parg** [comment]
Go to Tag Settings, right-click on the Icon button and select 'reset'
I'll fix the Tag Icons column, thanks
