### ISSUE TITLE
Side List: Sort Categories Alphabetically?

### ISSUE THREAD

**Issue by ms52538** [BiglySoftware/BiglyBT#1165]
Just read you tweaked Tags in the Side List. I realize Categories is a plug-in. Is there a limitation in the ability to have user-created categories appear alphabetically in the side list, as tags do? It seems to be limited to the side view, as when the pop-up window appears to assign a category, that list appears in alphabetical order, just not in the side list (left side of the windows gui).

**Comment by parg** [comment]
sure!

**Comment by ms52538** [comment]
So much better and looks great! Thank you so much! The communities I am part of, I share with them my thoughts and praise for BiglyBT and development behind it - it does, really, make a difference. And when the topic comes up in forum discussions about torrent clients - I jump in and refer people to using BiglyBT, every time.  :) That includes noting there is a responsive development team who are actively engaged with beta testers and open to receiving suggestions and feedback. Nice work :)

**Comment by parg** [comment]
much appreciated!
