### ISSUE TITLE
WebTorrent doesn't seem to work

### ISSUE THREAD

**Issue by tiotrom** [BiglySoftware/BiglyBT#1167]
* OS and version: Manjaro Gnome
* BiglyBT Version Number: biglybt  2.0.0.0-1

I have several torrents created with Webtorrent for our trade-free.org website. Add them to Bigly. Enable Webtorrent plugin and add Webtorrent tracker with the following settings:
![image](https://user-images.githubusercontent.com/34804533/61596490-b94a1f00-ac04-11e9-8bb5-96905dcf64fd.png)

I am behind a VPN with port forwarding. I am downloading and uploading torrents for many eyars now. In Webtorrent the same torrent files work without a problems.

So, in BiglyBT I cannot make it work with the Webtorrent technology. The "caveats" (chromium window open) is not even opening - clicking LAUNCH does nothing. I Tested with Chromium and Ungoogle Chromium. 

What am I doing wrong?

Thank you!

**Comment by TuxPaper** [comment]
parg will know more about webtorrent, but in the meantime, check if the Help->Getting Started page shows.  If it doesn't, try installing `libwebkitgtk-3.0` or similar package on your OS.  This should get that page working, and maybe webtorrent.

**Comment by tiotrom** [comment]
That page works

**Comment by Flingafu** [comment]
I am also encountering the same issue, no window pops up when I click launch, my help->getting started page works

**Comment by parg** [comment]
The plugin comes with a bundled chromium browser. Go to 

~/.biglybt/plugins/azwebtorrent/browser_71.0.3578.92.2

and try to launch ./chrome

**Comment by tiotrom** [comment]
Ok I get this error:
```

[tio@tio-pc browser_71.0.3578.98.2]$ ./chrome
[2998:2998:0729/175717.665327:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see https://chromium.9oo91esource.qjz9zk/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
Trace/breakpoint trap (core dumped)

```

**Comment by parg** [comment]
how about if you rename chrome to chrome.app (for example) and then create a new file called chrome with the contents

./chrome.app --no-sandbox

and chmod+x the new file?

**Comment by tiotrom** [comment]
I am not that knowledgeable about this I'm sorry. If you can please give me more detailed instructions so that I don't break anything with bigly.
I understand to rename this one:
![image](https://user-images.githubusercontent.com/34804533/62080223-80d3c200-b250-11e9-8bd1-cbb0128da8a7.png)
to chrome.app for example. 

Then create a new file or a folder? Then what to copy more exactly?

By the way it works with 

`[tio@tio-pc browser_71.0.3578.98.2]$ ./chrome --no-sandbox`

It opens the chrome window. But I am not sure if that affects bigly in any way?

**Comment by parg** [comment]
No problem, try the following in a terminal window in the same folder as the you tried the ./chrome --no-sandbox

rename chrome to chrome.app:

`mv chrome chrome.app`

create a new file to launch the renamed chrome.app with the no-sandbox parameter:

`echo "./chrome.app --no-sandbox" > chrome`

make the new file executable

`chmod +x chrome`

Hopefully the chromium browser will now launch when you type

`./chrome`

If this is the case then launch BiglyBT and see if the webtorrent integration is now working

**Comment by tiotrom** [comment]
Now it worked. Thanks! My follow up questions are:
1. How do I properly check if it works? We this trade-free.org website that streams videos via webtorrent. Generally I am testing by opening it and I'll see my Webtorrent application making upload. But BiglyBT does not. It doesn't seem to connect via BiglyBT.
2. When Bigly works, does it open a new Chrome instance for each webtorrent instance?

**Comment by parg** [comment]
There should only be a single chromium browser opened by BiglyBT to handle all webtorrent network traffic. When running BiglyBT with a download that has a webtorrent tracker the chromium window should automatically open and you should see any connected webtorrent peers within the browser window.

**Comment by tiotrom** [comment]
I see this window being opened automatically
![image](https://user-images.githubusercontent.com/34804533/62084254-268b2f00-b259-11e9-9cc0-6138749f0edf.png)
Now I don't understand which torrent opened it and where can I see the connected peers and/or speed.

**Comment by tiotrom** [comment]
As an update: I currently have 2 chrome windows opened by biglybt....same as above (is a simple window). Does not show the peers or anything.

**Comment by tiotrom** [comment]
I woke up to this this morning
![image](https://user-images.githubusercontent.com/34804533/62123121-83253300-b2c7-11e9-8dab-20e114202ced.png)
So many chrome instances opened...

**Comment by parg** [comment]
Try performing the following command in the same place as before but with the additional $*

`echo "./chrome.app --no-sandbox $*" > chrome`

**Comment by tiotrom** [comment]
Done it. Restarted bigly. Same behavior...

**Comment by parg** [comment]
Does the chrome window that opens at least have the title 'BiglyBT WebTorrent Protocol Proxy' rather than the default start page? If not then please execute the following in 

~/.biglybt/plugins/azwebtorrent/browser_71.0.3578.92.2

`cat chrome`

and tell me what the result is

**Comment by tiotrom** [comment]
No. It is the default Chrome homepage.

cat chrome outputs:
```
[tio@tio-pc browser_71.0.3578.98.2]$ cat chrome
./chrome.app --no-sandbox 

```

**Comment by parg** [comment]
You didn't make the change correctly / in the right place - the command

`echo "./chrome.app --no-sandbox $*" > chrome`

should have resulted in the 'chrome' file containing an additional $* after the --no-sandbox

**Comment by tiotrom** [comment]
I am outputting the same command
`[tio@tio-pc browser_71.0.3578.98.2]$ echo "./chrome.app --no-sandbox $*" > chrome`
In the ~/.biglybt/plugins/azwebtorrent/browser_71.0.3578.92.2

Is that what I should do?

**Comment by parg** [comment]
yup - try doing it again and see if the 'cat' command shows the change. You could try deleting 'chrome' before applying the command to see if that helps

**Comment by tiotrom** [comment]
Ok, so. I did this again:
```
[tio@tio-pc browser_71.0.3578.98.2]$ echo "./chrome.app --no-sandbox $*" > chrome
[tio@tio-pc browser_71.0.3578.98.2]$ cat chrome
./chrome.app --no-sandbox 

```
Then deleted "chrome" file and did it again:
```
[tio@tio-pc browser_71.0.3578.98.2]$ echo "./chrome.app --no-sandbox $*" > chrome
[tio@tio-pc browser_71.0.3578.98.2]$ cat chrome
./chrome.app --no-sandbox 

```
Seems like no change.

**Comment by parg** [comment]
argh, my mistake, you need to escape the $* to prevent expansion. Use the command 

`echo "./chrome.app --no-sandbox \$*" > chrome`

**Comment by tiotrom** [comment]
Yup :)
There we go: 
```
[tio@tio-pc browser_71.0.3578.98.2]$ echo "./chrome.app --no-sandbox \$*" > chrome
[tio@tio-pc browser_71.0.3578.98.2]$ cat chrome
./chrome.app --no-sandbox $*
```
Now in bigly when I try to "launch" 
![image](https://user-images.githubusercontent.com/34804533/62128020-c9808f00-b2d3-11e9-9622-db626e57b6fc.png)

I get nothing. So you know...

**Comment by parg** [comment]
ah, redo the 'chmod +x chrome' command as well

**Comment by tiotrom** [comment]
Ok thanks now it seems to work! :) - I still have to make sure it seeds via webtorrent technology. We are seeding these videos trade-free.org via webtorrent desktop app and as a simple test whenever I visit the website, the webtorrent app starts to upload - meaning it connects to my webtorrent client. In BiglyBT this does not happen it seems. I see no upload despite the chrome windows opening.
![image](https://user-images.githubusercontent.com/34804533/62131078-bfae5a00-b2da-11e9-8fab-310bd8d0f67c.png)
We want to replace webtorrent desktop app with BiglyBT because Bigly is far superior on all aspects, however so far it seems we cannot do any sort of upload via Bigly for our webtorrent-based videos.

**Comment by parg** [comment]
Not sure of the implications of using the --no-sandbox flag - hopefully things will work but if not we can try and figure things out.

**Comment by parg** [comment]
I've created a new version of the plugin, 1.3.4, for BETA users (i.e. you need to join the beta program to get it). It has an updated chromium browser along with a config option to do the '--no-sandbox' stuff. So all you need to do is update to this version and then go to the plugin config (Tools->Options->Plugins->WebTorrent Support) and check the new 'Run the web browser without a sandbox' option

**Comment by tiotrom** [comment]
How do I join the beta program?

**Comment by parg** [comment]
Help menu

**Comment by tiotrom** [comment]
Ok. Done it. Now I get this window all the time
![image](https://user-images.githubusercontent.com/34804533/62147149-3b1e0480-b2f7-11e9-9839-4f5e6bff1ebc.png)
If I go to options I see this
![image](https://user-images.githubusercontent.com/34804533/62147190-4c671100-b2f7-11e9-9304-a0a51b0e341c.png)

**Comment by parg** [comment]
So if you restart you keep getting the software update window? Might need to restart a few times to pick up new stuff. If the update is failing you will get a warning triangle bottom right after restarting - clicking on that will give you more info

**Comment by tiotrom** [comment]
I kept restarting. I see these errors:
![image](https://user-images.githubusercontent.com/34804533/62148505-1f682d80-b2fa-11e9-9efb-225e4c49379e.png)

and
![image](https://user-images.githubusercontent.com/34804533/62148516-268f3b80-b2fa-11e9-9b97-5ca2147414a8.png)

**Comment by parg** [comment]
meh, permissions issue? There's a file called 'update.log' in ~/.biglybt - maybe that contains a clue

**Comment by tiotrom** [comment]
I can only see these
![image](https://user-images.githubusercontent.com/34804533/62160397-3287f700-b314-11e9-9f50-2a8938cb92d0.png)

Any of them that I should check?

**Comment by parg** [comment]
How did you install BiglyBT? I setup Manjaro in VirtualBox, downloaded the Unix tar.gz, unzipped into a local~/Apps and joining the beta program works just fine

**Comment by tiotrom** [comment]
Via AUR - pacman. 
![image](https://user-images.githubusercontent.com/34804533/62167678-0e341680-b324-11e9-8b31-f61db2188557.png)

**Comment by tiotrom** [comment]
https://aur.archlinux.org/packages/biglybt/

**Comment by as-muncher** [comment]
Was the webtorrent plugin removed?  I'm looking for it....  I'd love to use it because I need it.

**Comment by parg** [comment]
No but it requires Java 11+

**Comment by as-muncher** [comment]
@parg, so instead of letting BiglyBT install the java version it requires, I need to go to Java's website and install it manually?  Even so, I didn't see it in the list of plugins available, so perhaps you could change that to have it, but greyed out, with a tooltip saying that java 11+ is required.

**Comment by as-muncher** [comment]
Perhaps, when I get that error message from Biglybt, that it requires Java 1.11 or higher, is there something you can do on Biglybt's end, so that I don't have to try and figure out how to solve this problem?  Maybe BiglyBT could offer to install a higher version?  Or give me some suggestions as to what to do?

**Comment by as-muncher** [comment]
and when I tried to install azwebtorrent, and installation failed, now I don't know if I have to try to download the plugin again off the biglybt plugins page, or if, after I install java 11+, that when Biglybt starts up, that it will see that I have the needed version and install it again for me.

**Comment by as-muncher** [comment]
I went here:
https://www.oracle.com/java/technologies/downloads/
and downloaded a later version.  The webtorrent plugin didn't need to download anymore but installed.
