### ISSUE TITLE
Backup Config

### ISSUE THREAD

**Issue by ChrsKt** [BiglySoftware/BiglyBT#117]
I ran Advanced System Care, after that my BiglyBT was screwed. All torrents, settings, tags, plugins are gone, but I still have the files. I dont know why though. 
Now I think it would be nice to have a backup config available.

So to formulate this as a feature request: 
BiglyBT creates once a day a backup config with all torrents.

**Comment by parg** [comment]
How about the existing backup/restore under Tools->Options->Backup & Restore?

**Comment by 2635599** [comment]
there is a backup feature in biglybt but it copies all files to a folder instead of to say a .backup file. i've already requested that we get a single file instead of multiple files placed in a folder.
