### ISSUE TITLE
Private IP4 IPV6 Range

### ISSUE THREAD

**Issue by gh338** [BiglySoftware/BiglyBT#1175]
* Uubntu 18.04
* BiglyBT 2.0.0.1_B20
* KDE 

Private IPv4 ranges from https://tools.ietf.org/html/rfc1918 for binding and listening work fine.
Private IPv6 ranges from https://tools.ietf.org/html/rfc4193 on the other hand do not work - they are not recognized or used even if we configure / force them explicitly.
Could you please allow those IPv6 ranges as well ?

Thank you

**Comment by parg** [comment]
Are you just talking about FC00::/7 or any other address ranges? Unfortunately I don't have a setup that contains such addresses to test with - are you getting any explicit errors?

**Comment by gh338** [comment]
Yes the fc00::/7 range. There is no error but BBT refuses to detect or accept those addresses as interface or bind interfaces with that address range.
You can just fire up openvpn or onioncat to have such a tunnel interface configured to test.

**Comment by parg** [comment]
I started onioncat and I can see and bind to the tunnel address - nothing seems to route through it even though I setup tor hidden service as required so dunno about that

**Comment by gh338** [comment]
That's fine as it is an isolated network and has no exit by default
The question is does BBT list it as a listening interface on your machine ?

**Comment by parg** [comment]
yup:

xample: 192.168.1.5;eth0;eth1[2] will bind the specified IP, to all IPs of the 1st interface and the 3rd IP of the 2nd interface.
The 1st IP will be used for all services, all others are only used for load balancing.
The following interfaces are available:
	enp0s3	(enp0s3)
		...
		enp0s3[5]	192.168.1.12
	lo	(lo)
		lo[0]	0:0:0:0:0:0:0:1%lo
		lo[1]	127.0.0.1
	tun0	(tun0)
		tun0[0]	fe80:0:0:0:dfcd:13b8:5d4:1437%tun0
		tun0[1]	fd87:d87e:eb43:5b8:5630:8ea8:cdc8:8521%tun0
