### ISSUE TITLE
Completely disable seeding and or have no upload speed, other than what's required to download?

### ISSUE THREAD

**Issue by DumbJoe** [BiglySoftware/BiglyBT#1176]
* Windows 10 Pro
* 2.0.0.0
* For windows: Desktop Environment

I notice that there's isn't a way to disable this completely but reduce it and 0 = unlimited, not disabled...and there's no post on an issue here either so I must be the first to complain.... I remember being able to do this with other clients, why not with this one too? Vuze had one at one point I think, and isn't this based off Vuze? Why was this removed?

Also on another note, why is the dashboard using Internet Explorer?

**Comment by parg** [comment]
Vuze and BiglyBT never had a global 'disable upload' option - you can do this with Tag speed limits though - create a Tag and assign all downloads to it (set its Tag Constraint to 'true'). There is a bug in 2.0.0.0 though regarding setting speed limits via Tag Settings - right-click on the Tag in the sidebar and set the speed limit that way.

**Comment by DumbJoe** [comment]
Oh?  I guess it must have been some other torrent clients then that I had tried in the past....hmmm....

How do I create a tag and set it global by default? In the Tags Overview, there's no option to "create tag".....

On another note, is this file related to BiglyBT in any way shape or form?
`C:\Users\GROWLI~1\AppData\Local\Temp\i4jdel0.exe`

I've notice it sometimes run and sometimes doesn't and blocking execution of it doesn't seem to affect the client at all....so far.....

**Comment by DumbJoe** [comment]
Hmmm, according to [this](https://www.wakfu.com/en/forum/36-technical-issues/25341-i4jdel0-exe-trojan-virus-not?poid=117143)

> The abbreviation i4j stands for "Install4J", which is a Multi-platform Java installer and builder, the same builder that the engine for Wakfu utilizes.

>The files of the type "i4jdel*.exe" or "i4j***.tmp" are created upon an instance of Wakfu being launched.
Please note that the Java builder does have a bug that prevents these files from being removed after the application using the Java builder is closed. You can manually delete these files after you shut down Wakfu.

>Please also note that these files may return a false-positive with certain brands of antivirus software. As long as these are located in your 'User/Temp' folder (for Windows), they are harmless, if you have played a java game recently. If they appear elsewhere however, please run a full system check, as this may be a trojan masquerading as an i4jdel executable application.

So I guess it must be a bug that it failed to remove itself upon successful installation....

**Comment by parg** [comment]
In Tags Overview there's an 'Add Tag' button top right

**Comment by DumbJoe** [comment]
Hm, so far so good, thanks!
