### ISSUE TITLE
Stopping BiglyBT while a file is checked causes it to re-donwload all of it

### ISSUE THREAD

**Issue by Gatak** [BiglySoftware/BiglyBT#1177]
Hi!

I have a very big torrent loaded in BiglyBT. It is 100% downloaded and it is beeing seeded fine. 

However there is a problem that causes Bigly to re-download it. It can be triggered easilly:

1) The torrent is being seeded as normal.
2) Stop and start (or restart) BiglyBT.
3) While BiglyBT is checking allocation of the file choose to restart BiglyBT (menu option)
4) When BiglyBT now starts it doesn't check the file, but immediately starts re-downloading the whole file from 0%

To fix the problem:
1) Stop the torrent
2) Force a re-check.
3) See that all data is OK.
4) Force start.

You can see from the screenshot that this has happened a few times before. Once I did not notice, so it downloaded another 100GB before I stopped it. :-(

![biglybt](https://user-images.githubusercontent.com/1469150/62039133-5efa2100-b1f7-11e9-97f6-87b470db4bb2.PNG)

Rechecking shows all data is there.
![biglybt2_png](https://user-images.githubusercontent.com/1469150/62039386-e47dd100-b1f7-11e9-9301-ff4354d466f4.PNG)

I'm using BiglyBT v2.0.0.0 on Windows 10. The torrent file is stored on a NAS (Samba network share)
```
Java 12.0.1 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4922, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.0.0.0/4 az3
```

**Comment by parg** [comment]
I created an 8GB torrent on a NAS share but when I stop/start it (or stop/start BiglyBT) it passes through the 'allocating' phase very quickly. Have you changed any settings that might be causing it to take a while in your setup? (can't think of any off the top of my head)

**Comment by Gatak** [comment]
As you see the file is 363GB. It contains about 2500 individual files. During startup, the allocation phase can take several minutes. It also is depending on if other torrents are also being loaded/started at the same time. This is on a gbit/s attached nas, but with spinning hdd, so random access isn't all that great.

**Comment by PrototypeZero** [comment]
While I can't recreate Bigly restarting files using the conditions quoted by the OP.

However (possible related) there are times that Bigly will for no reason out of the blue _**on startup only**_, suddenly decide at random any usually random, large torrent (60-400GB+) I've been seeding for 2+ months has nothing downloaded.  It doesn't even seem to check properly as the status column flips though allocating, etc so quick.  There is definitely NO checking of the torrents actual content, as doing a manual re-check ALWAYS confirms the content is 100% complete/correct.  It also has zero to do with the tracker, as this can occur when a binded & forced interface is not available (ie when my VPN isn't connected).

This occurs so randomly its impossible to recreate at will (sometimes going months without any, other times happening 4 times in a week).  It is slightly annoying on some private trackers that keep track of seeding times when suddenly you start downloading again and BAM, months of seeding is reset to 0 minutes.

**Comment by parg** [comment]
yay, managed to reproduce it :) I'll look into a fix. In the meantime, there is an option to cause BiglyBT to skip rechecking and assume everything is correct - right click on the download in the library, select the advanced menu and then 'Set resume data complete (skip recheck)'

**Comment by mighelch** [comment]
"File>Re-check ... when done" is this the same thing?
I have this unchecked, and I never had this issue.

**Comment by parg** [comment]
B21 should have fixed things, with a bit of luck :)

**Comment by Gatak** [comment]
Great. I will check. Thank you!

**Comment by Gatak** [comment]
> "File>Re-check ... when done" is this the same thing?
> I have this unchecked, and I never had this issue.

Good question. I have it enabled, though only once or twice it actually found something. Usually after a crash or so.

**Comment by d00rsfan** [comment]
Thanks to @Gatak about describing bug, sometimes it was happen with me too...
Friends, don't forget to close issues after testing the fix!

**Comment by PrototypeZero** [comment]
Might of fixed the OP's problem but I'm still getting random complete restarting of completed torrents at startup (just now) :( with B21 so I guess it may be a similar but unrelated issue.

**Comment by parg** [comment]
check the logs, see if anything is there relating to the issue

**Comment by PrototypeZero** [comment]
Not seeing anything obvious (to me) related in the logs to the problem.  

Is there a particular log file and/or category most likely to catch this in future?

**Comment by parg** [comment]
debug_1/2.log would be the most likely ones

**Comment by Gatak** [comment]
Seems as the fix works. I have not had any issues so far with the big torrents. :)

**Comment by parg** [comment]
Please close the issue when you're happy, cheers!
