### ISSUE TITLE
Unix Launcher Duplicate JAVA_ARGS

### ISSUE THREAD

**Issue by DigitalDJ** [BiglySoftware/BiglyBT#119]
Hi,

Would submit a pull request, but can't seem to find the "biglybt" launcher script script that is packaged in the Unix tar.gz in the repo.

At the end of the script, where it launches BiglyBT, the variable JAVA_ARGS is duplicated:

`${JAVA_PROGRAM_DIR}java -Xmx256m ${JAVA_ARGS} \
        -cp "${CLASSPATH}" \
        "-Djava.library.path=${PROGRAM_DIR}" \
        "-Dazureus.install.path=${PROGRAM_DIR}" \
        "-Dazureus.script=$0" \
        ${JAVA_ARGS} \
        ${JAVA_PROPS} \
        ${START_CLASS} \
        ${OTHER_PARAMS} \
        "$@"
`

For some Java arguments, the JVM will refuse to start if you duplicate arguments. In Java 9 for example, --patch-module is only allowed once.

Thanks!

**Comment by TuxPaper** [comment]
Well spotted!  I've removed the duplicate JAVA_ARGS for the next release.  For reference, the launcher script is in git at https://github.com/BiglySoftware/BiglyBT/blob/master/core/src/com/biglybt/platform/unix/startupScript
