### ISSUE TITLE
Min Seeds filter

### ISSUE THREAD

**Issue by gh338** [BiglySoftware/BiglyBT#1191]
* Ubuntu 18.04
* BiglyBT 2.0.0.1_B22
* KDE

Can you add Min Seeds as a subscription filter ?

**Comment by parg** [comment]
Done in next beta, thanks

**Comment by gh338** [comment]
Looking good
Can we also have age filtered - should open up a separate issue for this ?

Thanks

**Comment by gh338** [comment]
Maybe i missed something - the filter is purely visual and does not apply to the (auto)download ?
At least in my case Subscriptions filter seem to be only visual and not 'functional'

**Comment by parg** [comment]
ah, messed that bit up, try next beta

**Comment by parg** [comment]
max-age filter will be in the next beta (B25)

**Comment by gh338** [comment]
Thank you so much !!!
