### ISSUE TITLE
Column width not saved

### ISSUE THREAD

**Issue by larsm17** [BiglySoftware/BiglyBT#1195]
B2.0.0.1_B22, Win10, Classical Mode, Mainline DHT (IPv4) tab.

The columns in the lower window (Type, Stat.., Key, Active Re..., Messages, Info are too narrow and when I expand them fo readability then it is not saved for the next session.

**Comment by parg** [comment]
Unfortunately that's a plugin view, not a core one (core ones automatically remember settings). Although the plugin is supported in terms of core functionality there isn't anyone with the time to fiddle with the UI - sorry
