### ISSUE TITLE
[Question] Can I control a remote BiglyBT Daemon from my local BiglyBT client?

### ISSUE THREAD

**Issue by flatline-studios** [BiglySoftware/BiglyBT#1196]
I'm looking for a good solution for my seedbox, and am really struggling to find the ideal option.

I use BiglyBT on my main machine, but would love to be able to connect from my local client to my remote daemon, and control it just as if it was on my local machine.

Is this at all possible? Or will it ever be?

**Comment by TuxPaper** [comment]
It's unlikely the Client UI will ever be able to do this.  However, there are three alternatives:

1) Try a Transmission client to connect to BiglyBT's remote server.  For example, [TransGUI](https://github.com/transmission-remote-gui/transgui) boasts a uTorrent style GUI and probably works with BiglyBT.

2) You can use the existing Web UI, or install a different transmission compatible Web UI, like [Transmission Web Control](https://github.com/ronggang/transmission-web-control)

3) If you have an android device, you can use our BiglyBT app to remote control your server, or you can use any of the transmission compatible apps out there.

3rd Party apps/clients/webui's all have the caveat that BiglyBT specific features (like Swarm Discoveries, and Search) will not be available (unless the devs of these apps add support for them).

**Comment by flatline-studios** [comment]
Ahh okay. It's just that using the BiglyBT options menu there are sooooooo many options. Altering them through a config file would be nigh-on impossible for me to do. I guess it was too much to hope for that the GUI could simply switch which daemon it was talking to.

It's not so much about controlling BiglyBT through a web UI or anything, but more about having the huge amount of control the desktop GUI offers you.

**Comment by parg** [comment]
Actually you can connect BiglyBTs together using the View->BiglyBT Remote panel although features are limited! Could be improved a little but obviously nothing like a full UI

**Comment by flatline-studios** [comment]
The main features I'm looking for are:

- Ability to control per-torrent upload/download speed.
- Torrents of different trackers respect different share ratios, then stop.
- Torrents added with a specific label/tag have specific upload/download rates.
- Torrents added with a specific label/tag have respect different share ratios, then stop.

ruTorrent comes close to handling all of these, apart from the first point (which seems weird, as it seems the most basic).

BiglyBT desktop GUI on my Windows client can do all of these things... But trying to find something that can do all of that through the web interface seems an impossible dream. 👎

**Comment by parg** [comment]
How do you currently access your remote BiglyBT? Are you running it headless with the console UI? If you have remote-desktop style access then aren't some of those things you want to configure one-off things rather than stuff you'd be regularly tweaking?

**Comment by flatline-studios** [comment]
Headless through the console UI on a [thin client](https://www.parkytowers.me.uk/thin/wyse/d/dx0q/) I've re-purposed as a server (it's actually quite good, and was a steal at £24).

I guess they wouldn't be tweaked that much, at least points 2-4... Is there a command line options/config file documentation somewhere? If I could just have these options in a `.conf` file somewhere that I rarely have to touch, that could work. 👍

**Comment by parg** [comment]
Did you try the View->BiglyBT Web Remote on your local machine and connect using that to the remote one? I know the commands there are currently limited ('status', 'torrents', 'close', 'restart', 'update-check', 'update-apply' ) but that could be extended. For example, commands could be added to mirror a Tag from your local BiglyBT to the remote one.

**Comment by radumamy** [comment]
Hi @flatline-studios. If you're using an Android phone, you can use the official BiglyBT App. Thanks.
