### ISSUE TITLE
"Adjustment Interval" Missing from Auto Speed (beta) Configuration

### ISSUE THREAD

**Issue by dbareis** [BiglySoftware/BiglyBT#1198]
The "**Adjustment Interval**" option is missing in BiglyBT as per this page: "https://wiki.vuze.com/w/Auto_Speed_Beta"

<Java 1.8.0_201 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_201

SWT v4922, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.0.0.0/4 az2

**Comment by parg** [comment]
The option was removed at some point - the Vuze wiki isn't maintained at all...

**Comment by dbareis** [comment]
But in that case the REMAINING option doesn't make any sense at all?:  **Skip AFTER adjustment**

**Comment by parg** [comment]
Actually, now I look (yeah, should have before...) the option was accidentally removed - I'll re-add it. Thanks!
