### ISSUE TITLE
Issue reported while testing internet connection using the client

### ISSUE THREAD

**Issue by Xemnarth** [BiglySoftware/BiglyBT#1203]
`Contact import for 5E050B08... failed: import of '/2600:1f18:2b8:c403:8a4f:baea:25ea:c547:47612' failed`

I keep getting this error message (it's the only one). My WAN is set up as DMZ so can someone translate this code for me to understand its source? Thanks!

Using 2001_B25 on Win 10 Pro

**Comment by parg** [comment]
Ah, that's some debug stuff from when I was working on getting IPv6 working better with the tester. Removed in next beta!
