### ISSUE TITLE
Name column doesn't respect "Show program icon..." setting for torrent contents (when expanded)

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#1204]
The "Name" column in the Library view has a context menu checkbox, "Show program icon in name column", which controls the display of an associated-application icon next to the torrent names in the column.

That works fine for the _torrent_ level, but when a torrent's contents are expanded using the disclosure triangle to the left of the name, program icons are always shown next to each file in the torrent regardless of the state of that checkbox.

#### "System" details:
```
Java 1.8.0_222 (64 bit)
  Oracle Corporation
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.222.b10-0.fc30.x86_64/jre

SWT v4924, gtk/3.24.10, zoom=100, dpi=96
Linux v5.2.9-200.fc30.x86_64, amd64 (64 bit)
B2.0.0.1_B26/4 az3
```

**Comment by parg** [comment]
fixed next beta,, thanks!
