### ISSUE TITLE
Blanking "Min Heap" or "Max Heap" setting results in unpopulated error dialog

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#1205]
Blanking the "Min Heap memory size" setting in Options -> Startup & Shutdown (with "Max Heap memory size" set to `580 MB`), then tabbing out of the field, netted me this super-informative error dialog:

![image](https://user-images.githubusercontent.com/538020/63718483-b1d7f000-c818-11e9-84c9-f093b1565916.png)

Additional observations:
1. It's weird that the field apparently can't be blank anymore, but I notice that when I fill in Max Heap it automatically fills in Min Heap.
    1. Originally I thought Min Heap was always filled in with a copy of Max Heap (which really wouldn't make sense), but just now I restored the `580 MB` setting to Max Heap (after blanking both), and Min Heap was auto-filled to `550 MB`, the value I'd last set it to before I blanked it.
2. Blanking Max Heap results in the same enlightening dialog, the _first_ time you tab out of the field after blanking it. After that, it's happy to let you leave the field blank, without complaint.

#### System details:
```
Java 1.8.0_222 (64 bit)
  Oracle Corporation
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.222.b10-0.fc30.x86_64/jre

SWT v4924, gtk/3.24.10, zoom=100, dpi=96
Linux v5.2.9-200.fc30.x86_64, amd64 (64 bit)
B2.0.0.1_B26/4 az3
```

**Comment by parg** [comment]
will be improved a bit in next beta, thanks

**Comment by ferdnyc** [comment]
I'm just going to assume this is fixed, two years later, and close it. 😉
