### ISSUE TITLE
(question) Transfer and Queue options

### ISSUE THREAD

**Issue by newgithubuser2019** [BiglySoftware/BiglyBT#1206]
Hi

Is there a recommended guide/calculator for setting those?

I'm aware of the following:
https://wiki.vuze.com/w/Good_settings
http://infinite-source.de/az/az-calc.html

However, if you paste upload speed from Good Settings page into azureus calculator suggested settings in the calculator would differ from those on Good Settings page for a corresponding upload speed.

**Comment by parg** [comment]
There's no hard-and-fast rule - Transfer settings has an 'auto' mode for upload slots etc, you just need to configure your maximum global upload limit to be around 80% of your network's capacity to avoid saturating it.
