### ISSUE TITLE
(question) Max Heap and Max Direct memory size

### ISSUE THREAD

**Issue by newgithubuser2019** [BiglySoftware/BiglyBT#1207]
Hi

Is it best to leave them at default values or is there a "reasonable" amount those values can be raised to in order to minimize the chance of encountering memory issues in case i start significantly more torrents than usual? My laptop has 8gb of ram.

**Comment by parg** [comment]
The default value is sufficient for most users - you will get warnings if the JVM heap starts to become exhausted and CPU usage will increase as it attempts to garbage collect more frequently. If you were planning on having 100s of active torrents then perhaps an increase would be in order.
