### ISSUE TITLE
(question) I2P Helper plugin bandwidth settings

### ISSUE THREAD

**Issue by newgithubuser2019** [BiglySoftware/BiglyBT#1208]
Hi

Could someone explain these settings to me please?

1) Are max upload and download speed settings a part of those under Options -> Transfer section? Or would i have to lower limits in Options -> Transfer if i enabled I2P Helper so that BiglyBT doesn't use more than 80% of my bandwidth?

2) What does "Share Percentage" mean?

3) In what case is it best to enable "Treat I2P peer traffic as LAN traffic for rate limiting purposes"?

**Comment by parg** [comment]
1. independent I2P network usage configuration 
2. how much of the permitted bandwidth is used for third party tunnels as opposed to your own
3. if you want to apply the LAN rate limits to I2P peers instead of the non-LAN ones
