### ISSUE TITLE
(question) Network Status plugin

### ISSUE THREAD

**Issue by newgithubuser2019** [BiglySoftware/BiglyBT#1210]
Hi

UPNP is enabled in both my wifi router settings and in BiglyBT settings. Ports are forwarded in router settings. In the status bar it says "NAT OK". 

However whenever i run Network Status tests i get this:
-Testing TCP port *** inbound
Test failed: NAT test failed: Connect attempt to *** (your computer) timed out after 20 seconds. This means your port is probably closed
Check your port forwarding for TCP ***

-Testing UDP port *** inbound
Test failed: Inbound test failed
Check your port forwarding for UDP ***

-failed to lookup AS: Query failed for ...

-(LL 1) Outbound connection fail: Connection attempt to *** aborted: timed out after 15sec

-No incoming connections received, likely NAT problems

Does it mean there is something wrong with my setup?

**Comment by parg** [comment]
It means you have a NAT problem - UPnP isn't working or something else is blocking inbound connections (e,g, firewall)
