### ISSUE TITLE
Mystery Folders Reappearing

### ISSUE THREAD

**Issue by ms52538** [BiglySoftware/BiglyBT#1215]
For the past few months now, I've noticed situations where I move an existing torrents and it's sub-directory contents from one drive location to another drive location. The client facilitates the move nicely.  But in a handful of situations, about 12 thus far, I'm noticing the BiglyBT client will recreate the folder structure of the torrent's original location, albeit empty. They seem to be 'ghosts' or remnants in code somewhere.  In some cases it is not obvious which torrents are associated with the mystery folders, in other cases they are easily identifiable. But try as I may; either checking the torrent, moving the data files, nothing seems to prevent the folders from being recreated in their spots before they were moved. The only thing the solves the problem is going through an arduous process of starting, stopping, torrents to widdle down which ones are the problem, exporting them, deleting them, then re-adding them as new torrents.

**Comment by parg** [comment]
Could it be that the ones that cause this issue have some files within them linked to another location? Such links are established when you rename or retarget physical files within a download.
