### ISSUE TITLE
New results from RSS feeds don't auto-download

### ISSUE THREAD

**Issue by newgithubuser2019** [BiglySoftware/BiglyBT#1218]
Hi

I've added an rss feed -> i right-click on the feed, mark all results as read, tick "post updates to notifications" and "auto-download new results". Updates get posted to notifications, but don't get auto-downloaded.

**Comment by parg** [comment]
You could check the Subscription_1/2.log files in the logs folder to see if there are any clues. Do the new results get marked as 'read' or do they remain 'unread'?

**Comment by newgithubuser2019** [comment]
Logging wasn't enabled, so i can try that only next week when new updates become available. 

Once new results become available they get posted to notifications, don't get auto-downloaded and remain "unread". If i right-click on a feed and mark all results as read, then they will become "read".

RSS feed url was copied from Jackett if that matters.

**Comment by parg** [comment]
Manually downloading the results from the feed works fine though?

I don't think logging needs to be enabled with Tools->Options->Logging for those logs to contain useful info - might have  been overwritten though as they cycle when full.

**Comment by newgithubuser2019** [comment]
Yes, manual downloading works.

I've looked into logs folder but couldn't find any Subscription_1/2.log files.

**Comment by parg** [comment]
Hmm, ok, might be when you join the beta program - please go ahead and do this (Help menu has an option to do so)

**Comment by newgithubuser2019** [comment]
Updated to 2.0.01_B29

Should I attach "Subscriptions_1" log here?

**Comment by parg** [comment]
Once you have reproduced the problem (and therefore hopefully captured some logs) could you send it over to paul@biglybt.com ? Thanks

**Comment by newgithubuser2019** [comment]
I'm on version 2.0.0.1_B29 and this week's new results have auto-downloaded. The only other change i've made is checking options->subscriptions->automatically start downloads when added (as opposed to putting them in a stopped state).

**Comment by newgithubuser2019** [comment]
A bit off-topic: I've switched to BiglyBT from Tixati and in Tixati the situation was the same with regards to that feed - it couldn't be auto-downloaded, but manual download worked fine.

So now that updates have auto-downloaded on 2.0.0.1_B29, what gives? Some issues on the side of the tracker? Related to uploads from that one particular category? idk

**Comment by parg** [comment]
You'd need to find some failing ones and investigate the logs to find out why they weren't downloading... Of course, once you start looking at these things they work, its only when you're not that they fail :)

**Comment by newgithubuser2019** [comment]
The problematic rss feed strikes again. Three new results - only one got auto-downloaded. I wanted to email you "Subscriptions_1" and "Subscriptions_2", but their "Date modified" is 09.09.2019. Do i need to manually download new results to create new logs?

**Comment by parg** [comment]
MetaSearch_1/2.log might have something in it

**Comment by parg** [comment]
Also, if you stop BiglyBT the date modified for Subscriptions_1/2.log might change?

**Comment by newgithubuser2019** [comment]
There is no MetaSearch_2 in my logs folder, only MetaSearch_1. Date modified for MetaSearch_1 is also 09.09.2019. Restarting BiglyBt hasn't changed date modified for any of them.

**Comment by parg** [comment]
hmm, well please send em over anyway - subscriptions+metasearch - send to paul@biglybt.com please

**Comment by newgithubuser2019** [comment]
Sent. Subject line is "logs for issue #1218".

**Comment by parg** [comment]
Thanks for sending the logs, nothing of interest there unfortunately (as you pointed out, the mod dates were old).

You could try peeking in the debug_1/2.log files, there's a small chance that an error has been logged there.

**Comment by newgithubuser2019** [comment]
If memory serves me right last week new results were successfully auto-downloaded. Week before that new results didn't get auto-downloaded, but i was able to manually download them by pressing "download". This week's new results that didn't get auto-downloaded can't be downloaded manually either - it says no sources found. However if i click "details" and go to a webpage i can see that there are hundreds of seeds. 

For comparison I've opened Tixati and new results got successfully auto-downloaded. Now, if i think about it, i remember having issues with magnet links in BiglyBT found on some other trackers as well and not just for this particular rss feed.

**Comment by parg** [comment]
Do you have the 'mainline DHT plugin' installed?

**Comment by newgithubuser2019** [comment]
yep

**Comment by parg** [comment]
Try making magnet downloads live for longer by going to 

Tools->Options->Plugins->Magnet URI Handler 

and setting 'Overall lookup timeout' to 0

At least that way you should be able to see outstanding magnet downloads for the RSS items that are failing

**Comment by newgithubuser2019** [comment]
It's already set to zero. Something isn't right though, cause in Tixati the download is instantaneous.

**Comment by newgithubuser2019** [comment]
For the magnets that won't download in BiglyBT, but will download in Tixati - there is a lock icon next to a torrent name in Tixati. From what i've read It means that a torrent is private.

**Comment by parg** [comment]
hmm, well if the torrent is marked as private then the DHT should be disabled (by all clients) and if a magnet URI doesn't have explicit trackers encoded in it then the download should fail. Check the magnets for &tr or other parameters that mention an explicit download source

**Comment by newgithubuser2019** [comment]
Links have trackers listed after "&tr="

**Comment by parg** [comment]
Find one of the magnets that denotes a failed download from the RSS feed, click on it and look at the Sources tab to see what the trackers are returning in terms of seeds/peers or perhaps whether they have errors

**Comment by newgithubuser2019** [comment]
I had "enable download-based metadata transfer" unchecked in magnet url handler options. I've re-enabled it and all magnets download fine now.
