### ISSUE TITLE
Tweak Request: Move re: Tags

### ISSUE THREAD

**Issue by ms52538** [BiglySoftware/BiglyBT#1219]
Windows client
When right-clicking a torrent file in the library, then selecting "organize", please move "Assign Category" above "Tags" in the column window. Seems more natural to select a category first, then a tag - at least for me.

Additionally, 
When right-clicking a torrent file in the library, then selecting "organize" and then "tags",
a pop-out column expands open; in that column window, please move the "Tagging View" and "Add Tag" to the top of the column, ABOVE "Auto" so they reside at the top of that column and not the bottom.

I use "tagging view" the most as it presents my template of what tags I am assigning the torrent,  

The "Tagging View" is a great feature/template/tool - and I really like the tweaks/changes that have been being made these past few weeks. Great work. :)

I think these changes will be in line with other 'flow' in the client regarding the order in which Categories and Tags are presented.

It's a tad confusing, I suppose, to place Categories inside the "Tags View" in the client, if one wants to look at the global picture assigning meta to the torrents, but even in that window you do present Categories above / before Tags.

Just a thought. Please disregard if you don't think it's in line with your perspective/vision for the tool. I feel I might be stepping out on a limb for this request, as I am just one user/tester.

As always, thanks for all you do!

Thanks!

**Comment by parg** [comment]
I'll make your requested changes and then wait for people to ask for them to be switched back :)

Regarding categories, they are implemented as a type of tag which is why they sometime make guest appearances along with other tag types (auto, manual, peer-sets)

**Comment by ms52538** [comment]
I just brought it down and have to say - I LOVE IT. Hopefully others will as well. It just seems a more natural flow (at least for me, hopefully for others as well!). Thank you! :)

**Comment by parg** [comment]
No problemo!

**Comment by ms52538** [comment]
It's a holiday weekend. Step away from the computer. :)  That is, if you are States-side. Enjoy

**Comment by parg** [comment]
Heh, in the UK these days - I have to code to get away from Brexit :)

**Comment by ms52538** [comment]
Hell I don't blame you M8. I don't blame you at all. Quick note: On the Category, if you move "Add Category" to the top, like it is for "Add Tag", things will be consistent. Minor. I know. Enjoy your weekend then! And thank you, as always. I continue to push the client in the channels which I associate. :)
