### ISSUE TITLE
This is rather a feature / usability request

### ISSUE THREAD

**Issue by ghost** [BiglySoftware/BiglyBT#122]
I would love to have 2 things in BBT:

1) an XML / REST interface for the various counters / logs
2) filtered views - for example:
All Peers -> filtered by Network -> sorted by upload -> filtered by file name.

Maybe these 2 go along together ?
Anyways with 1) I could implement an external statistics / view of my own with reporting tools or something similar
It's even possible that 1) is already part of BBT - but I'am no Java expert ... :-)

Thanx a lot !!!!

**Comment by parg** [comment]
I did write a plugin that used 'highcharts' to show stats once...

**Comment by parg** [comment]
You can enable the XML stats file under Tools->Options->Statistics, dunno if that would help

**Comment by parg** [comment]
FYI I ported my Highcharts plugin - biglybt://install-plugin/azhighchartsstats

If you install it and then go to View->Highcharts Statistics you'll get an internal webbrowser pointed at

http://127.0.0.1:9092/charts/updown.html

Plugin is here for info: https://github.com/BiglySoftware/BiglyBT-plugin-azhighchartsstats/blob/master/com/azureus/plugins/highchartsstats/HighchartsStatsPlugin.java
