### ISSUE TITLE
2.0.0.1_B30 doesn't start up on Mac Catalina 19A546d

### ISSUE THREAD

**Issue by ackerthehacker2** [BiglySoftware/BiglyBT#1222]
Mac 10.15 beta 19A546d
2.0.0.0 release works just fine .... as well as 2.0.0.1_B28 ...but B30 will not start up

**Comment by parg** [comment]
Yup, there is an issue with B30 on OSX - please manually download the B29 jar from

https://biglybt-files.s3.amazonaws.com/core/BiglyBT2001-B29-signed.jar

then rename it to BiglyBT.jar and replace the one in the App folder with this.

Or edit the info.plist to remove 

-Djava.system.class.loader=com.biglybt.launcher.classloading.PrimaryClassloader

**Comment by parg** [comment]
B31 should be OK
