### ISSUE TITLE
(BUG) B30 Doesn't shutdown correctly

### ISSUE THREAD

**Issue by PrototypeZero** [BiglySoftware/BiglyBT#1223]
Since the B30 update, the program fails to terminate properly (but with no error messages) leaving an active BiglyBT process but no GUI running, the next time you run it you get a "Another copy of BiglyBT is running: failed to lock file" referring to the ".azlock" file.

However after this error message, the rogue process is actually terminated and if you try to launch Bigly it works fine.

**Comment by Asgardsurfer** [comment]
parg, had some serious issues yesterday with B30 or B31 not sure (had to use QB)...It just would not startup.
Had to revert to a backup, the backup would update itself and then would not start. B32 fixed it for me, Thanks!

**Comment by parg** [comment]
sorry about that, there was an issue with the B30 update :( glad things are working!

**Comment by Havokdan** [comment]
Now the problem occurs with me in the Java 1.8.0_221 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4922, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B2.0.0.1_B32/4 az3

**Comment by Asgardsurfer** [comment]
No problems here:

Java 1.8.0_221 (64 bit)
  Oracle Corporation
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home

SWT v4926, cocoa, zoom=100, dpi=72
Mac OS X v10.14.6, x86_64 (64 bit)
B2.0.0.1_B32/4 az3

**Comment by parg** [comment]
Working on it, its a Windows 10 only issue

**Comment by parg** [comment]
try B33

**Comment by Havokdan** [comment]
> try B33

Ok now, thanks
