### ISSUE TITLE
Tags in 'Open Torrent Options' window

### ISSUE THREAD

**Issue by newgithubuser2019** [BiglySoftware/BiglyBT#1224]
This happens from time to time - can't pick tags in 'open torrent options' window (pls see attached screenshot). Have to press arrow button in top right corner to close/reopen this section of the window so that it's displayed properly.
___________________________________________________________________________________________________
![Untitled](https://user-images.githubusercontent.com/54177868/64120026-dba68f00-cda3-11e9-88ae-fe4759c9809c.png)

**Comment by parg** [comment]
yup, I've seen that and never been able to figure out how to fix it :(

**Comment by newgithubuser2019** [comment]
It seems to happen only when the number of files in a torrent is greater than the number of files that fits into file selection section of "open torrent options" window. If the number of files is such that the scroll bar shows up, then the aforementioned glitch with tags happens.

**Comment by newgithubuser2019** [comment]
> It seems to happen only when the number of files in a torrent is greater than the number of files that fits into file selection section of "open torrent options" window. If the number of files is such that the scroll bar shows up, then the aforementioned glitch with tags happens.

That was a premature conclusion on my part

**Comment by parg** [comment]
I fiddled a bit with B36 - give that a go please

**Comment by newgithubuser2019** [comment]
Updated to 2.0.0.1_B36. Will see how it goes

**Comment by newgithubuser2019** [comment]
I've tried opening several of my latest torrents (and this glitch was definitely manifesting for at least some of them) and so far it hasn't reoccurred.
