### ISSUE TITLE
Subscriptions sorting

### ISSUE THREAD

**Issue by newgithubuser2019** [BiglySoftware/BiglyBT#1228]
I have a minor gripe: when i go to 'Subscriptions' i click subscriptions column so that my subscriptions are sorted a-z. However after every restart sort order changes from a-z to z-a.

**Comment by parg** [comment]
fixed next beta (B37)

**Comment by newgithubuser2019** [comment]
It still happens on B38

**Comment by parg** [comment]
works for me

**Comment by newgithubuser2019** [comment]
There seem to be inconsistencies depending on whether you exit or restart and, perhaps, switch to a different sidebar node after changing sort order for 'Subscriptions' (I've tried switching to 'Library', for example). 

So it's somewhere in one or more of these variations:
1. change sort order -> exit and start again
2. change sort order -> restart
3. change sort order -> switch to a different sidebar node -> exit and start again
4. change sort order -> switch to a different sidebar node -> restart

**Comment by newgithubuser2019** [comment]
After re-creating that subscription (from issue #1253) sorting order seems to be remembered.
