### ISSUE TITLE
Windows 10, 64b - Crashes when shutdown/exit

### ISSUE THREAD

**Issue by eurobank** [BiglySoftware/BiglyBT#123]
I'm having constant crashing reports when (almost everytime) i exit the application. I run Windows 10 Pro, 64 bit.

The problem seems to be with 

C:\WINDOWS\System32\MSCTF.dll

dll.

Thanks

**Comment by parg** [comment]
Are you running 32 or 64 bit Java? Also, have you tried checking your system via

https://support.microsoft.com/en-us/help/929833/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system

?

**Comment by eurobank** [comment]
I have no missing files or anything (sfc /scannow). All is intact. 

As for Java, i don't see anything installed in my applications in Control Panel.

Your about says: 

Java 1.8.0_131 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4757, win32
Windows 10 v10.0, amd64 (64 bit)
B1.0.2.0/4 az3

**Comment by parg** [comment]
The latest Java is 1.8.0_152 - you would need to install a system-wide one and probably delete the one in c:\program files\biglybt\jre

**Comment by eurobank** [comment]
I did and work nice now. Thanks.

**Comment by eurobank** [comment]
It seems that it not solved, half of the times when shuting down  or restarting i have the crash i initialy described.

**Comment by parg** [comment]
Please update to 1.2.0.1_B02 (See Help menu for Beta Program option).

**Comment by eurobank** [comment]
The download doesn't seem to fully work, Displays "downloading etc etc" and stays there for a long time doing nothing. Tried a second time, same results.

**Comment by eurobank** [comment]
After installing the beta you provided, for several hours i see no crash when exiting/restarting. 

I'm almost sure things are better now. 

Thanks, closing this issue.

**Comment by parg** [comment]
cool - we have a work-around for the actual bug that is seemingly in an external library. Hopefully they'll fix the root cause sometime!
