### ISSUE TITLE
'My Torrents' in the sidebar

### ISSUE THREAD

**Issue by newgithubuser2019** [BiglySoftware/BiglyBT#1230]
Should it be possible to minimize/close 'My Torrents' node in the sidebar like every other node? Whenever i click on the little triangle to the left of 'My Torrents' it seems to refresh it but not minimize/close - ie it disappears for a split second and then appears again.

**Comment by parg** [comment]
You can't collapse it if something inside it has focus - click on a sidebar node outside of My Torrents and then collapse it
