### ISSUE TITLE
While you are doing work on the "Add Torrent pop-up window"...

### ISSUE THREAD

**Issue by ms52538** [BiglySoftware/BiglyBT#1231]
These are questions/concepts for discussing;

A feature of one of the other bt clients I used a few years back was the ability to add several new torrents into a similar window, but the layout of that window would allow me to apply the same 'elements' to all of the added files at one time. I would describe Bigly more as a per-torrent design, even though I can add multiple downloads into a single pop-up window (if enabling that in the options area of the client). It was a time-saving step to be able to do all torrents added into the pop-up window all in one fell swoop (adding new torrents to the client). 

Being able to change the torrents name while adding it to the pop-up window; if a torrent contains a single file, then I can change the name while in the pop-up window view, however, if the torrent contains multiple files (say the contents of a Blue Ray) - I can change those file's names but I cannot change the torrent's name in that view. It is not until I 'ok' the add (usually in "stop" mode" can I then click on the newly added torrent in the library view and change the torrent name. Is that correct or is there a feature that I'm not seeing?

Staying on the topic of the pop-up window when adding a new torrent; I like that all the tags that I have created are available in that frame for me to apply to the newly added torrent. However, I do not see something similar for those categories I have already created, in that window. Am I missing something?

Finally, transparency of the product. It's open-source, but you seem to be the owner of most effort (perhaps not all) that goes into the product. Stepping away from the daily details and nitty-gritty of code; what is the future for the client most likely to be - can you set a milestone for what you want it to be or achieve in the next few years? Or perhaps a mini roadmap of intended goals. I really do love this client. I heard the other day "there's no documentation", how do I find stuff?" and I asked what they were trying to do, and they said a copy of template view over to a different view and apply it, but they had to recreate it. I looked, did not have an answer, looked at the documentation, and realized they had a point. I chuckled and said, "donate some money to the coffee fund, it's a free client". 

Once again - thanks for all you do with this client!!

**Comment by parg** [comment]
When you enable the 'multi torrent' window some options can be applied to multiple ones by multi-selecting them in the left hand panel. A few more could be added I suppose but things like Tags are a bit more of an issue as they can be auto-selected based on torrent file types and this breaks in the multi-torrent case.

You can change the name of a multi-file torrent by right-clicking an entry in the Files view section and selecting 'rename top level folder'.

I'll think about the category thing - keep trying to kill categories but people like them too much!

You can copy a table-view setup from one to another by selecting the 'export' button on the 'column setup window' for the source and then hitting the 'import' button on the setup window for the other, if that's what was wanted.

TuxPaper and myself are the main developers of the client, TuxPaper historically has spent a lot more of his time on the Android client while I've done more on the desktop. Ideally in the long term we would get to the point where donations covered both the AWS server expenses and our basic living expenses but unfortunately we're a long long way from there! We don't really have a roadmap - things come along like bittorrent v2 and the cryptocurrency BTT extensions and we track them to see if there's opportunities for the client but other than that we mainly respond to user requests and whatever takes our fancy. We don't have the resources to embark on any long term projects although if there was a killer feature then I'm sure we'd find the time. We obviously welcome contributions to the project but can't afford a lot of time overseeing them. If you look at the BiglyBT pull requests you'll see some from 'lislei' - I fear I stopped him from contributing with my feedback on his changes. Unfortunately he wanted to make seemingly minor changes in a lot of places and it took me absolutely ages to review them and find some problems.

**Comment by ms52538** [comment]
Sorry - has been a busy day. From what is being reported, you all have had a busy week in Politics there in the UK!
Thanks for the quick and detailed reply. One of the things that strike me, so positively for the client, is the professional association it has to your efforts in communication and coordination in making bug fixes and changes. You always come across professional, unemotional, and respectful in your dialogue. The client is a quality product, the development/support team is quality in their support of it. The quality is high overall. Thank you for that. Aside from this - do you prefer a different means of communicating suggestions or asking questions? Fixing things is obviously a high priority - and my suggestions and questions are certainly nowhere of the level of importance. I appreciate the responses to the questions and will pass along your instruction for copying views. Thanks again!

**Comment by parg** [comment]
Ah, UK politics, don't get me started! 

I've spent almost 15 years working on Azureus/Vuze/BiglyBT (in various capacities) and before that 20 years working for Fujitsu, so I've been around the block a bit. So I manage to bite my tongue mostly, as long as I haven't had one too many beers.

GitHub issues are fine for reporting problems, requesting features or asking questions. We used to run our own forums but they were more hassle than they were worth - spent so much time fighting spam and inappropriate users. You can always email me at paul@biglybt.com if needed.

Thanks for all the support and feedback!
