### ISSUE TITLE
Plugin 'seedingcolumns1' ported (ETA, remaining). What next?

### ISSUE THREAD

**Issue by MichaelKing1832** [BiglySoftware/BiglyBT#1235]
Can someone write the classes to implement an upload data remaining column for completed torrents?

It would simply display the torrent data size * the share ratio limit - uploaded data.

Use case: Prioritizing torrents with the least amount of data remaining to hit their upload ratios.

**Comment by TuxPaper** [comment]
We used to have http://plugins.vuze.com/details/seedingcolumns1 that had a `Remaining - bytes left uploading till a given share ratio is reached` column but it never got ported over.  We also had a cool threshold markers for share ratio limits,  http://plugins.vuze.com/details/ColumnExample2 , but it also never got ported over.

Might be time to drag those back into the daylight.

**Comment by MichaelKing1832** [comment]
I tried manually installing the seedingcolumns1 (which was the exact plugin I was thinking of) from the source zip file. BiglyBT refused since it only had the Azureus signature in it. I removed the signature file and manually overrode installing it. The plugins log shows it was found and loaded, but there are no extra columns showing up.

I haven't coded Java in years, but any pointers on what to look at to port it over would be appreciated. The documentation on writing and testing a plugin seems to be a bit sparse.

**Comment by MichaelKing1832** [comment]
I've pulled the original seedingcolumns1 plugin.
The main class KazgorColumn.ExtraColumns, is attributed to "omschaub for kazgor" from 2004.
The only "license" I could find is "Free. Use however you see fit".

So I built it and tweaked it for BiglyBT and I've got the extra columns showing up!
There are still some non-fatal errors on loading that I still need to track down, but so far, it works.

I have no idea how to package up the plugin as a fork here, so help with that would be appreciated.

**Comment by MichaelKing1832** [comment]
Well, the errors were mine in the properties file. So, how do I get the updated/migrated plugin up on the BiglyBT plugin site?
I can attach src (pretty much simple package renaming from Azureus to BiglyBT) and a compiled jar.

Next steps?

**Comment by MichaelKing1832** [comment]
@TuxPaper How can I upload or send in the patch/changes to add this plugin?
It turned out to be just translating the azureus class names/packages to the BiglyBT equivalents.
It's been working and rock solid for me.

**Comment by MichaelKing1832** [comment]
@TuxPaper @parg bump. 
Any help? How can I upload or send in the patch/changes to add this plugin to the ported plugins?

**Comment by parg** [comment]
Do you have it in a Git repository? If so point me at it, I'll build it and get in on the plugins page.

I already do this for

https://github.com/Shusshu/biglybt-plugin-timedautostart

for example.
