### ISSUE TITLE
Offline Downloader plugin update?

### ISSUE THREAD

**Issue by graycatgrayhat** [BiglySoftware/BiglyBT#124]
Any chance of getting the plugin Offline Downloader updated to work with BiglyBT?  The code base looks old so maybe its not able to be migrated.

https://plugins.vuze.com/details/azofflinedownloader

**Comment by parg** [comment]
yup, that's pretty dead - what are you trying to achieve?

**Comment by graycatgrayhat** [comment]
Ah well my use case is a bit more of a hack, and I had never used it with Vuze so only working in theory.  I was hoping to set up two BiglyBT clients slave/master.  With the slave taking torrents added to the local client, not downloading the content at all but just syncing the torrent info to the master.

**Comment by parg** [comment]
You can achieve that in a few ways. For example, create a Tag in the source BiglyBT that contains the torrents you want to share with the slave, generate an internal RSS feed for it, use the RSSToChat plugin to automatically feed the torrents to a chat channel. The in the slave BiglyBT generate an RSS feed from the chat channel and set it to auto-download

**Comment by graycatgrayhat** [comment]
Just finished setting that up, it works for the time thanks again.

**Comment by parg** [comment]
nice! You can of course use the RSS feed directly from client A -> client B, however that needs a staticish public IP and port forwarding, so the chat is in some ways simpler. Also a chat can be many->many if needed
