### ISSUE TITLE
Question/Request: Files "Tree view" collapse/expand all (or recursive) feature?

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#1241]
Now that @TuxPaper has kindly fixed the SWT lockups that were plaguing me in the Files view, and I can actually use that interface safely, I find myself wishing the tree view, specifically, was a bit... "more".<sup>**1**</sup> Or, at least, wondering if I'm using it to its full potential.

Working with really BIG torrents — on the order of hundreds, or even thousands, of files — the tree view can be an invaluable tool for exploring the contents in an organized fashion. In fact, there are times when I really want to see just a list of the directories directly below the top-level folder, and then drill down into certain subfolders from there.

AFAICT, the only way to get such a view is to manually collapse each of the directories at the level I want to view, to hide their contents and subfolders — a pretty tedious process. The quickest method I've come up with is to take advantage of the keyboard navigation (<kbd>←</kbd> to collapse, <kbd>→</kbd> to expand, <kbd>↑</kbd> and <kbd>↓</kbd> to move between rows) to quickly collapse the tree — I can repeatedly hit <kbd>←</kbd><kbd>↓</kbd>, <kbd>←</kbd><kbd>↓</kbd>, <kbd>←</kbd><kbd>↓</kbd>... to collapse every directory at a certain level, until the list is just the contents of that one level. 

But it's still pretty tedious, and since lots of things (closing the Torrent Details view, turning on/off "Hide files not selected...", using/clearing the filter input field) will reset the tree to fully-expanded, I end up having to do it over again pretty frequently.

So, I'm wondering if there's possibly a way to do a "collapse all" on the tree, to fold up everything (or everything below a certain level) all at once? Or, if not, would it be possible to add that function? 

Ideally it would be recursive, so that if I "collapse all" the top-level folder, then expand that folder, its contents are still collapsed (thus getting me to my initial goal of seeing just a single level of the tree). And, if it _does_ operate recursively, then a recursive **expand** feature would be handy for quickly exposing a given subtree in its entirety.

#### Things I've tried, unsuccessfully
1. Right-clicking on a row — none of the context menu selections have anything to do with expanding/collapsing the tree.
1. All manner of <kbd>Shift</kbd>/<kbd>Ctrl</kbd>/<kbd>Alt</kbd>/<kbd>Super</kbd>-clicking the expansion twisties
1. Collapsing a row with <kbd>Shift</kbd>+<kbd>←</kbd>

#### System details 
(Though the request is really non-version-specific, it's worked the same in every version I can recall since Tree view was introduced.)
```
Java 1.8.0_222 (64 bit)
  Oracle Corporation
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.222.b10-0.fc30.x86_64/jre

SWT v4924, gtk/3.24.10, zoom=100, dpi=96
Linux v5.2.9-200.fc30.x86_64, amd64 (64 bit)
B2.1.0.1_B01/4 az3
```

#### Notes
1. (This request thus serves as a handy demonstration of the principle that "No Good Deed Goes Unpunished".)

**Comment by parg** [comment]
I'll take a look!

**Comment by ferdnyc** [comment]
Finally got a chance to try this out. (Hey, it's not every day you work with thousand-file torrents! ...Well, ***I*** don't, anyway,)

It's great! Works perfectly, and what a time saver. Thanks, Parg!

**Comment by parg** [comment]
Glad it helps!
