### ISSUE TITLE
[Bug] Swarm Merge Tooltip

### ISSUE THREAD

**Issue by PrototypeZero** [BiglySoftware/BiglyBT#1242]
Hovering over a torrent in the "Swarm Merge" tooltip column results in the tooltip popup only briefly appearing for a fraction of a second (ie of no use at all).

**Comment by parg** [comment]
odd, works fine for me on Windows

**Comment by PrototypeZero** [comment]
Strange, it appears happen on about 50% torrents from a certain seeder on a certain site, nearly all of these torrents Bigly identifies as swarm merge candidates when the contents clearly aren't (all mp3 and all *very* different songs).

Maybe it just happening when there is too much info to fit in the tooltip/popup?

**Comment by DonnyDDEV** [comment]
Confirmed, when the file list is "long", you get this behavior.

**Comment by DonnyDDEV** [comment]
Confirmed, when the file list is "long", you get this behavior.

> 
> 
> Confirmed, when the file list is "long", you get this behavior.

Java 1.8.0_231 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_231

SWT v4930r7, win32, zoom=100, dpi=96
Windows 7 v6.1, amd64 (64 bit)
B2.4.0.0/4 az3

**Comment by parg** [comment]
I'll limit it to, say, 20 lines

**Comment by parg** [comment]
Also added a menu option to view all the info if needed
