### ISSUE TITLE
Beta After Update Reset

### ISSUE THREAD

**Issue by brazenvoid** [BiglySoftware/BiglyBT#1243]
So I have this issue with Beta versions. Any random update can reset all my settings or even remove all the torrents like a factory reset. This state is irrecoverable through backups.

Is this intended?

**Comment by parg** [comment]
No, obviously not. Why can't you recover from a backup?

**Comment by brazenvoid** [comment]
I don't know really. The restore process succeeds but after the restart everything is the same. I tried it 3-4 times before I just abandoned the practice. 

The torrent removal has only occurred twice only. Off-topic but I have experienced the torrent removal after a forced computer restart as well. 

Good to know its not intentional, the last torrent removal really inconvenienced me as I seed a lot and had a long list of them. 

Sorry to not be very helpful, I will update the issue if it happens again.

**Comment by parg** [comment]
Very odd - something must be trashing your config folder. On Windows this is %appdata%\BiglyBT - your general config is stored in 'biglybt.config' and download details in 'downloads.config' and the 'active' folder. Normally restoring the contents of the BiglyBT folder is sufficient to recover from most issues.

**Comment by PrototypeZero** [comment]
Similar thing happened to me a few betas back after an update, about half the configuration files got corrupted and even the backups couldn't be restored.  Bigly renamed the extensions of the affected config files to ".corrupt" or something like that (I don't quite remember).  All the the affected files seemed to have got zeroed (looking in a hex editor);  it was mostly the "basic" settings and the state of the current torrents which got corrupted.

Its only happened once to myself and was an extreme annoyance more than anything (having to manually recheck TB's of torrents was slow and a PITA) but I didn't lose any data.

**Comment by brazenvoid** [comment]
After exploring my BiglyBT folder, I have found numerous *.bad{count} files;
21x biglybt.config.bad
12x biglybt.config.bak.bad
2x downloads.config.bad
1x downloads.config.bak.bad
2x pm_23674.dat.bad

**Comment by parg** [comment]
Do they have anything in them or are they all 0 length files or full of nulls?

**Comment by brazenvoid** [comment]
Filled with nulls.
