### ISSUE TITLE
Avoid banning seeder

### ISSUE THREAD

**Issue by afsharsafavi** [BiglySoftware/BiglyBT#1244]
Hello
I used BigLyBT 2.1 in Centos (CLI mode), and I have a problem.
I need to download a big torrent that has only one seed.
Download starts successfully, but after some progress, downloading will be stopped. I checked log and config folders for finding the reason, but I couldn't find anything.
Finally, I found seeder IP in "banips.config" file:
d3:ipsld4:desc11:<torrent name>:ip14:<seeder IP>:timei1568231085963eeee
But I can't find out the reason for this event. 
(I have the same problem for this torrent with the latest version of transmission)
Can you help me to find out why this happens and fix it?
Best Regards

**Comment by parg** [comment]
Peers are banned for sending bad (incorrect) data. You can disable this with the command

set "Ip Filter Enable Banning" false boolean

However, if the seed is sending you garbage you might not be able to complete the download.
