### ISSUE TITLE
Preferences Window appears to be missing lots of stuff

### ISSUE THREAD

**Issue by albchong** [BiglySoftware/BiglyBT#1246]
* OS and version
Mac OS Catalina Beta (19A558d)
* BiglyBT Version Number
2.1.0.0
* For *nix: Desktop Environment

Selecting Preferences from the menu reveals a window with only Subscriptions, where as if I do the same with Vuze I see more options. Screenshots of both attached.

![Screenshot 2019-09-13 at 05 09 01](https://user-images.githubusercontent.com/6863434/64837318-d0463580-d5e5-11e9-935f-e7b56827d2f1.png)
![Screenshot 2019-09-13 at 05 10 48](https://user-images.githubusercontent.com/6863434/64837319-d0463580-d5e5-11e9-967f-9490bd1ae539.png)

**Comment by parg** [comment]
Perhaps something to do with Catalina? Please generate a 'debug.zip' from the Help menu and send it over to paul@biglybt.com - I'll take a look.

Thanks

**Comment by parg** [comment]
aha! So the options are scrolled for some reason. If you select the 'Subscriptions' entry and hit up-arrow then the rest will scroll into view.

**Comment by albchong** [comment]
Thanks Paul,

That is sooooo strange. I would never have guessed.

Have a great weekend,

Best,

Albert

**Comment by parg** [comment]
You too, I'll see if I can figure out a fix!
