### ISSUE TITLE
annoying Certificate Trust Pop-up

### ISSUE THREAD

**Issue by JBitte** [BiglySoftware/BiglyBT#1247]
Popups appear to notify of an untrusted Certificate from various issuers "Internet Widgets".
I searched for any trust complaints online and there were no specific references.

This all started as I reset my security biglybt certificate store. I had migrated from vuze earlier this year and I thought I didn't want to carry over any possible badly configured certs. 

Since, I've noticed this in versions 19.x , 2.0.x and now 2.1.x betas
While there is a checkbox for "automatically install unknown SSL certs without prompting", it would be a good feature to also include the opposite option - Never prompt for unknown SSL Certs. Or, if that is not possible move the alert box to the lower right corner warning as the current alert box mid-screen is annoying.

![certificate-popup1-nul](https://user-images.githubusercontent.com/6049555/64905999-a45baa80-d6e0-11e9-9e2c-f6fe6d4735d1.png)

I'm running Windows 10, 64-bit install BiglyBT B2.1.0.1B02 My Java is current at 1.8.0 221 64-bit

**Comment by parg** [comment]
So you would like an option to turn off any attempt to handle an unknown certificate and silently fail the attempt to use it?

**Comment by JBitte** [comment]
Yes, but I can see it being controversial among your user base. The benefit is negating erroneous human behaviour in clicking Yes instead of No by mistake when multiple pop-ups cascade with large and small re-sized windows appearing moving the Yes and No box locations.

Another possibility is to have a queued list of Cert prompt attempts where the user can decide which to trust without taking the client operational focus. In effect, just changing today's pop-up activity to a non-disruptive list.

Cheers!

**Comment by parg** [comment]
I'll add an option to automatically decline unknown certs. Simplest fix for hopefully a fairly rare problem,  creating a list etc would be quite a bit of work...
