### ISSUE TITLE
failed

### ISSUE THREAD

**Issue by ResidentBody** [BiglySoftware/BiglyBT#1248]
![c3ed441260f871544873ab3d258a7bd5](https://user-images.githubusercontent.com/55314704/64906450-2cdd4980-d6e7-11e9-9435-8888d71711c9.png)
what is wrong by me on my biglybt is this a bug or not is some one to help me what to do. 

thank you friendly regards

**Comment by parg** [comment]
Your download location looks pretty weird... Go to Tools->Options->Files and make sure the 'default directory' is somewhere sensible. Also check Tools->Options->Files->Torrents for the torrent save location.

**Comment by ResidentBody** [comment]
thank you Parg ... for your adivice its working agian thank you.

**Comment by parg** [comment]
\o/
