### ISSUE TITLE
improve UI for removing dead trackers

### ISSUE THREAD

**Issue by JBitte** [BiglySoftware/BiglyBT#1249]
I've been using azureus/Vuze/BiglyBT for almost 15 years and have had my fair share of bad torrent and dead trackers. I've been a fan of the Edit Tracker URLs Together feature to add trackers but sometimes my AV scanner actively pops up messages for Threat Blocked due to URL Blacklist (i.e. peersteers.org, ...). My normal action is to remove the tracker record from my client so no pop-ups appear whether false-positive or threat.

 With Tracker sites going offline, I've tried to manage trackers for specific torrents I'm downloading. This has resulted in some 100% downloads and some unsuccessful. 

The core of my issue is that the vuze wiki offers little information on removing a trackers from a downloading torrent. If your torrent is showing red health status, you can show Torrent / Details / Sources and see offline or erroneous trackers. I normally select them, then hit the X to delete. The torrent download may be revived moving to a green health status to download further.
 I have the feeling these tracker records do not really go away.  On Biglybt restart, they appear again so it seems a bit futile. 
![BT-tracker-delete-Untitled](https://user-images.githubusercontent.com/6049555/64906318-454c6480-d6e5-11e9-84f7-a6ad41b495be.png)

As a second Part of the same UI or user intuitive issue of trying to rid the biglybt client of dead trackers, one can go to View / All Trackers and see a list of the trackers used by all loaded torrents.
I can see the list of torrents associated with trackers here, with an option for Create Action.
![AllTrackers](https://user-images.githubusercontent.com/6049555/64906552-65c9ee00-d6e8-11e9-8620-24e0faf4dd92.png)

 My expectation is this Action would be to create a filter for a set of trackers and delete whenever it is found associated with any torrent. In reality it seems to group this tracker with an existing or new Tag only.
One can see the list of torrents associated with trackers here.
![biglybt-alltrackersaction-Untitled](https://user-images.githubusercontent.com/6049555/64906559-737f7380-d6e8-11e9-95d7-6c812b1c7181.png)
  Possibly I'm missing the knowledge for the next step to run the delete tracker URL process?
It would be great to have an Edit Tracker URLs Together feature which can remove all records of selected trackers!
Maybe there's an underlying process or plugin needed for this request to run.

I'm running Windows 10, 64-bit install BiglyBT B2.1.0.1B02 My Java is current at 1.8.0 221 64-bit

**Comment by parg** [comment]
There's some information on the All Trackers view on the (limited) Wiki - https://github.com/BiglySoftware/BiglyBT/wiki/All-Trackers-View

The right-c;lick 'remove from current [and future]' option is a shortcut for creating a Tag that has associated with it a 'Tracker Template' that removes a set of trackers from the torrents assigned to the Tag (and the Tag is setup to auto-assign all torrents). 

Perhaps you can play with this?
