### ISSUE TITLE
Windows 10.64 bit: Adding a new torrent "stall" all downloads 

### ISSUE THREAD

**Issue by eurobank** [BiglySoftware/BiglyBT#125]
Adding a new torrent (8-10 giga) all downloads seems to stall for some time, showing "downloading" (not actually downloading).

After a while (2-3 minutes) everything is back to normal.

Any ideas ? Maybe this "pause" is during creating the new torrent file ?

**Comment by parg** [comment]
Probably allocating the file storage. You could try enabling

Tools->Options->Files: Append data to files as downloaded and reorder pieces as the download progresses

Also check you haven't enabled 'allocate and zero new files on creation'

**Comment by eurobank** [comment]
No, i have not enabled Allocate and zero ...

Enabling your suggestion (append data ...) seems to resolve this.

**Comment by parg** [comment]
Some filesystems pre-allocate even when the zero-option isn't specified.
The drawback with the append-mode is that BiglyBT has to reorder the file as it downloads so you get some increased disk IO
