### ISSUE TITLE
Convert Magents to torrents or Save torrent list as torrent files

### ISSUE THREAD

**Issue by dropitlikecross** [BiglySoftware/BiglyBT#1250]
* OS and version Windows 10
* BiglyBT Version Number 2.0.0.0

Aside from backing up everything, is there a way to export the torrents from the list I want and export them as torrent files?

**Comment by parg** [comment]
Right-click on them, select the 'Social' menu tab and then 'Export torrent...'

**Comment by llewlem888** [comment]
I'm trying to do this on the mobile client, and there's no option to export I can find. Also, there doesn't appear to be a filesystem location I can find to get the metadata, even to just copy and paste the *title* of the torrent, or export **the magnet link**. There are other apps to generate torrent files, as long as I have the **magnet**.
WTF? Idc that BiglyBt Android is a minimalist app, but YOU'VE GOT TO BE ABLE TO EXPORT AT LEAST THE TITLE! And the magnet PLEASE! The rest can be left to other apps like Libretorrent.

**Comment by TuxPaper** [comment]
@llewlem888 
File a Feature Request on the [BiglyBT Android Project](https://github.com/BiglySoftware/BiglyBT-Android/issues) for a Share Torrent feature.  Copying to clipboard would be the easiest. Saving to file(s) would take a bit more work, but would be better for multi-torrent selecting.  We have a QR code generator ready and waiting too, so we could show that for easy sharing with another person's phone.  But without a issue filed, I'll forget about it until I want it personally :/

As a sort of workaround, you can set where BiglyBT stores torrent files in the latest versions.  By default it writes them to a private dir, but you can change it to a folder within Downloads or some public dir, and any new torrents added would be written there.  May not be very easy to figure out which .torrent file is which, but workarounds rarely are fun.
