### ISSUE TITLE
Memory usage grows when the Statistics tab/window is open

### ISSUE THREAD

**Issue by detelosk** [BiglySoftware/BiglyBT#1251]
On macOS Mojave 10.14.6, starting with BiglyBT 2.1.0.0, when leaving the Statistics window open (showing the Transfers tab, for example) the memory column of Activity Monitor shows a slow seemingly unbound growth (I closed the program when it reached 40 GB) somewhat countered by the memory being compressed. Closing the Statistics tab/window seems to stop the growth but does not free the memory.

About window System information:

> Java 1.8.0_202 (64 bit)
>   Oracle Corporation
> /Applications/BiglyBT/.install4j/jre.bundle/Contents/Home/jre
> 
> SWT v4926, cocoa, zoom=200, dpi=72
> Mac OS X v10.14.6, x86_64 (64 bit)
> B2.1.0.0/4 az3

(Offtopic: Are there plans to bundle a more up to date Java, or am I missing it for some reason?)

**Comment by parg** [comment]
Leak confirmed, thanks. Appears to be in the most recent SWT we pushed to support Dark Mode - testing shows that a more recent SWT (4.13RC2) doesn't exhibit the leak - https://download.eclipse.org/eclipse/downloads/drops4/S-4.13RC2-201909071130/download.php?dropFile=swt-4.13RC2-cocoa-macosx-x86_64.zip

**Comment by NaPurHab** [comment]
To your Java Question.  Offical Java Site has the current version listed as Version 8 Update 221.
You can get it from   [Get Java](https://www.java.com/en/)

**Comment by detelosk** [comment]
It seems that the B2.1.0.1_B03 beta release does not show the reported issues. Thanks for the fix!

**Comment by parg** [comment]
Thanks for reporting!
