### ISSUE TITLE
Last sidebar tree position

### ISSUE THREAD

**Issue by newgithubuser2019** [BiglySoftware/BiglyBT#1253]
On startup the focus is always on one particular subscription for some reason. Is there a way to make BiglyBT remember last tree position?
__________________________________________________________________________________________________
Java 1.8.0_221 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_221

SWT v4922, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.1.0.0/4 az3

**Comment by parg** [comment]
Do you have 'force focus to subscriptions when they are updated' set under Options->Subscriptions?

**Comment by newgithubuser2019** [comment]
No, it's not checked. All results are marked as read also.

**Comment by newgithubuser2019** [comment]
Nevermind, I've deleted and re-created that subscription and it's back to normal now.

**Comment by parg** [comment]
There is a bug there somewhere - the last tree position is supposed to be remembered but it doesn't always work.

**Comment by newgithubuser2019** [comment]
Now the focus seems to be always on My Torrents->Library

**Comment by parg** [comment]
might have improved in B04
