### ISSUE TITLE
Fix legacy bug i4jdel0.exe for your next release please!

### ISSUE THREAD

**Issue by DumbJoe** [BiglySoftware/BiglyBT#1254]
As per this post here: https://github.com/BiglySoftware/BiglyBT/issues/1176#issuecomment-516356389 this appears to be legacy code that fails to remove itself and hence starts itself up every time BigBT starts. 

![pic](https://i.imgur.com/6VpH6vQ.png)

* OS and version: Windows 10
* BiglyBT Version Number: 2.1

**Comment by o0nd7ots** [comment]
@parg can we close this?

**Comment by parg** [comment]
Closing as nothing's going to happen here, re-open if so desired.
