### ISSUE TITLE
Install update manually seems to be borked or just me?

### ISSUE THREAD

**Issue by DumbJoe** [BiglySoftware/BiglyBT#1255]
Just would like to point out updating manually through the program using the downloaded zip file seems to be broken.....

![pic](https://i.imgur.com/jotQ2XV.png)

This is the error I get upon restarting: 
![pic](https://i.imgur.com/k9asB8F.png)

2.1 installs fine using the usual exe file method from the releases section....

* OS and version Windows 10
* BiglyBT Version Number: 2.0

**Comment by parg** [comment]
Hmm, which .zip file are you using here? If it is the full update zip (e.g. BiglyBT_Update_2.1.0.0_win64.zip) then yes, this won't work as the 'install update manually' currently is only designed to work with incremental updates (plugins, swt, beta .jars)

Obviously it shouldn't accept the full-update zips

**Comment by DumbJoe** [comment]
The file that was automatically torrented....

I see, perhaps have a checker to checks the file to see if it's a full update or incremental update and if it's full update, alert an error saying this is a full update and won't work?

**Comment by parg** [comment]
The auto-torrented update file should have triggered a message to apply the update automatically. I've done as you suggested regarding the error etc. Cheers

**Comment by DumbJoe** [comment]
....thanks...
