### ISSUE TITLE
Is there a way to add/append trackers from another torrent to an existing one?

### ISSUE THREAD

**Issue by DumbJoe** [BiglySoftware/BiglyBT#1257]
Like steal trackers from a new torrent and add it to a dead torrent that have no seeders but this new torrent does have seeders. Adding that new torrent file with the new trackers doesn't work because the program would complain that a pre-existing torrent already exists and cancels the download. I'm guessing the below screenshot is it?

![pic](https://i.imgur.com/Rad7x8q.png)

But that doesn't work on magnet links....since you would first need to download the torrent file in question.....and if the server hosting the torrent file is dead....you can't exactly download it....now can you...?

* OS and version: Windows 10
* BiglyBT Version Number: 2.1

**Comment by parg** [comment]
If you open a second .torrent file for the same download and the trackers differ you should get automatically prompted to merge the trackers from the second one into the first.

If this doesn't work then use the 'sources' tab for the download, right-click on a tracker and select 'edit tracker URL(s)' - you can then copy/paste trackers around (if you select the 'edit as text' button)

**Comment by DumbJoe** [comment]
I see, thanks.....

**Comment by parg** [comment]
If you have any other issues with this please re-open!

**Comment by DumbJoe** [comment]
> If you have any other issues with this please re-open!

How would you do this on console or the web ui? They don't seem to have an option to append or add trackers onto pre-existing torrents.

**Comment by parg** [comment]
No, they don't, so you can't!
