### ISSUE TITLE
Erorr: file not found (Torrent file *** doesn't exist)

### ISSUE THREAD

**Issue by newgithubuser2019** [BiglySoftware/BiglyBT#1258]
So far it has happened two times after clicking on a magnet link in a browser and pressing OK in "Open Torrent Options" window. I have checked "Save .torrent files" under Options->Files->Torrents and whenever this error occurs the torrent file is not created in the specified save directory. I have to remove the transfer which gives the error from library and re-add it. Upon re-adding the error doesn't re-occur or at least it hasn't so far.
__________________________________________________________________________________________________
Java 1.8.0_221 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_221

SWT v4922, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.1.0.0/4 az3

**Comment by dbareis** [comment]
I can't remember this happening before the last update and its probably happened 8 or so times since then.

If I try to recover from this by stopping and restarting the torrent it shows the same message then changes to "**Error: Failed to read torrent**"

After typing the above (a few minutes later), I deleted the failed entry and it worked the second time.

**Comment by bigo93** [comment]
After the last update this happened every single time when I click a magnet link!
I have to remove from seeding list, where it displays the error, and click magnet link a second time before it actually adds the download.

**Comment by parg** [comment]
Weird one this - can't reproduce it :( Can you try joining the beta program (Help menu option) and see if the problem is still occurring? Thanks!

**Comment by bigo93** [comment]
K done that.
Now got an Open Error message claiming the torrent **could not be opened: not a File**

**Comment by parg** [comment]
Can you general a debug.zip (last option on the Help menu) and send it over to paul@biglybt.com ? Thanks!

**Comment by dbareis** [comment]
I just sent a debug log as requested (on beta version)

**Comment by bigo93** [comment]
Now on beta version torrents are opening normally without any errors. Must have need a restart.

**Comment by bigo93** [comment]
Strange
Just did a clean reinstall of windows.
Installed biglybt, and getting the same error.
guess I'll have to use beta version until you figure out the issue

**Comment by dbareis** [comment]
I haven't seen this on the latest beta's, EXCEPT possibly in one unusual scenario.

BiglyBT doesn't detect if you have accidentally downloaded a magnet multiple times.
