### ISSUE TITLE
Bug: when transcoding "Remember this setting" doesn't work

### ISSUE THREAD

**Issue by dmorchard** [BiglySoftware/BiglyBT#126]
Java 1.8.0_151 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_151

SWT v4757, win32
Windows 10 v10.0, amd64 (64 bit)
B1.0.2.0/4 az3

I'm trying to force BiglyBT to always transcode but despite checking "Remember this setting" for my selected device BiglyBT always defaults back to "when required" on subsequent transcodings.

**Comment by parg** [comment]
If you right-click on the device in the sidebar what does it say under 'default profile' ?

**Comment by dmorchard** [comment]
Long answer: In order to force it to transcode I need it set to "Always ask", but when I've tried to have it remember my settings, i.e. clicking on XBox 360 SD on this screen...
![image](https://user-images.githubusercontent.com/30359271/32379944-e02178c8-c07c-11e7-9124-cdd6b51331f8.png)
...then subsequently, the default profile is "XBox 360 SD", but it never transcodes.

**Comment by parg** [comment]
Is it possible that the files are already compatible with XBox 360SD? I know there's some detection logic that tries to avoid transcoding if it isn't required

**Comment by dmorchard** [comment]
It is possible, but from time to time I have playback issues regardless of what *should* be compatible... Windows Media Player (in Win10) is streaming to XBox's "system video player" app.  I had Vuze set to always transcode because of these troubles.  I just switched to BiglyBT this past week and was expecting the same functionality, but it won't "remember this setting" when I set it to "always transcode".

**Comment by parg** [comment]
I'll take a look!

**Comment by parg** [comment]
Can you check out the latest beta - 1201_B01 (join the Beta program to get it - see the Help menu)

**Comment by dmorchard** [comment]
Problem solved!  Thanks Parg!
