### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by biggles702** [BiglySoftware/BiglyBT#1262]
MacOS 10.14.6

BiglyBT 2.0 was working.  Attempted to upgrade to 2.1.  Installer shows this window:

![image](https://user-images.githubusercontent.com/55608845/65366011-980eaa80-dc16-11e9-81cd-2015fc295d89.png)

Mouse turns into spinning beachball, unable to click anything.

CPU usage goes to 100%

RAM usage increases until it reaches 12 GB, then drops (JVM doing GC?), then goes back to 12 GB, etc.

Is there a reason the buggy installer is even necessary?  Couldn't I just download the .app bundle from somewhere and drag into Applications like every other MacOS app?

**Comment by parg** [comment]
I just ran the update on Mojave and it went OK - does the same happen if you grab the installer from https://www.biglybt.com/ ?

Also, when updating you generally don't get pushed through the terms-and-conditions screen again as you've done it before, so I'm not sure why you're even seeing that screen,

**Comment by parg** [comment]
Worst case don't upgrade but join the beta program (Help menu option) - that will effectively update you without needing the full installer.

**Comment by biggles702** [comment]
I am using the installer from the website.  The in-app upgrade didn't work, so I downloaded the full installer.  That didn't work, so I deleted the app.  So I no longer have any version installed.  But the installer still doesn't work.  I also tried the installer for 2.0, which doesn't work either.  I also tried deleting every file in the home directory with BigltBT in the name.

**Comment by TuxPaper** [comment]
Beta program option would have probably worked.  Without any diagnosis or hints to why the installer didn't work, we unfortunately can't help much.  If you can remember anything that changed on your system between when the successful 2.0.0.0 install and the unsuccessful 2.1.0.0 upgrade, please let us know.  Did you perhaps upgrade to 10.14.6 between those two events, or change any system settings?

As for a drag-and-drop installer, that isn't a bad idea.  We can't do a direct .app drag-and-drop, but we could probably make a "drag this BiglyBT folder to Applications", which would essentially be the same thing.  I'll try to remember to look into it the next time we are building installers.

**Comment by biggles702** [comment]
I eventually got it to install by creating a new user and running the installer as that user.  So it's something about the user environment rather the system environment.  But what environmental things could be persisting after deleting all the config files I don't know.

**Comment by biggles702** [comment]
I figured it out.  The installer won't run if https://magnet.crowdcafe.com is running.  I don't know if this is the fault of Magnet or the fault of Install4j.

**Comment by anonymous4argus** [comment]
Hi,
I am currently investigating this issue with my diagnosis tool.  My tool figured out the spinning cursor is from the java process. It is busy testing accessibility of the installer window with the API below, and therefore its main thread becomes unresponsive.
```
[JavaComponentAccessibility accessibilityHitTest:withEnv:]  from /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/libawt_lwawt
```
Our tool reports the actions are triggered by applications like Magnet when it is enabled to control your computer in  System Preference->Security & Privacy->Accessibility. 

Inside the function, 
```
[JavaComponentAccessibility accessibilityParentAttribute]
```
and 
```
NSAccessibilityUnignoredAncestor
```
are invoked frequently. Optimizing the Accessibility hierarchy(https://developer.apple.com/documentation/appkit/accessibility_for_macos/nsaccessibility) may help solve the issue, and I hope to hear from you soon on this issue.

**Comment by eburggraaf** [comment]
Hi,

This may be affecting me as I am an apple voiceover screen reader user.  I am having this exact issue installing on mac.  I was interested to read about the fixes people discovered here and may try reading up soon.  But I have to have voiceover read the screen to complete the install.  So, this will be a deal breaker for me if something in the installer code just won't work with apple's accessibility framework.  Ultimately, mac apps work best when they are self contained any how.  Very few really need to mess with core componants or system files to do what they do, and this should be no exception.  I'd prefer to just drag and drop from downloads to applications and call it done.  Thanks,
