### ISSUE TITLE
[SUGGESTION] Search to Search Setting *Values* (not just Descriptive text)

### ISSUE THREAD

**Issue by dbareis** [BiglySoftware/BiglyBT#1263]
Currently, BiglyBT options->Search does a good job of searching for descriptive text, for example, one of the items matching the text "**directory**" is "Torrents->**Save Directory**", but knowing that item's value I can't search for it ("_D:\BiglyBT\torrents_").  If it was an optional search parameter then the options should be:

1. Description Only
2. Value Only
3. Both

String and integer values are definite candidates, booleans should probably be ignored.

**Comment by parg** [comment]
I'll just make it search Text and integer values along with descriptions
