### ISSUE TITLE
Idea:  Improve VPN detection.

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#1264]
Was poking around and noticed the VPN Helpers in the Get Plugins. It gave me an idea.

In Connection: Advanced Network Settings   there are the following:

![image](https://user-images.githubusercontent.com/37715552/65380029-9c7fa580-dca0-11e9-930e-f99e5ed80ec1.png)
![image](https://user-images.githubusercontent.com/37715552/65380037-b9b47400-dca0-11e9-8621-cb5ebf2b914a.png)
![image](https://user-images.githubusercontent.com/37715552/65380041-ca64ea00-dca0-11e9-9605-fe3e6389c912.png)

I'm wondering if it would be possible to change the Bind to to read:
_Bind to local IP address or interface or VPN_
then in the entry box the name of the VPN can be used as the target interface. For me that would be PureVPN instead of ppp1.

The other place the VPN name could be used is as a TEXT Box addon to the _Automatically try and detect the presence of VPNs and prompt to configure their bindings._

Or it could be as simple as searching for the string 'VPN' in the list of interfaces.

This idea was because on occasion when my VPN client starts it switches from ppp1 to ppp0. Then the next time it switches back.  Which means I have to change it. But if it could be tied to the Label for the interface, BiglyBT could adapt, as it would follow the VPN name.

So I will leave this for discussion and see where it goes.

* Java 1.8.0_221 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_221

SWT v4922r17, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.1.0.1_B05/4 az3

**Comment by parg** [comment]
I can add support for regular expression matching against network interface display name using (...) to indicate this. For example

(.*I219-LM$)[0]

matches against my ethernet connection named

Intel(R) Ethernet Connection (2) I219-LM

and selects the first address (using [0])

**Comment by NaPurHab** [comment]
Just tested this is B06

Since my whole string is PureVPN, I used:  **(PureVPN)[0]** though **(PureVPN)** by itself also works.

So Simple straight forward VPN names like PureVPN, NordVPN, and others should not be difficult. In your example I don't understand the . before the * or the $ as there is nothing after the LM. 

Perhaps a Link after the 'Bind to local address' that points to a wiki article on RegExp.   As well as the example text being updated to mention this new way. 

Or perhaps, remove the Example Text and put a Link to a Wiki Article that covers the Example and the new RegExp entry method.  A lot more room to be clear in a Wiki. Even if Documentation is the bane of every programmer. Though needed for Novices.

But for simple entries like (PureVPN)[0]  or (NordVPN)[0] or (AirVPN)[0] or (Mullvad)[0], it should work a charm.  And now if my PureVPN wanders from ppp1 to ppp0 when starting, it doesn't matter.

At the top of the Connnection: Advanced Settings   is the BLUE Text 'Please visit here for details.' 
It goes to a page that says:  **BiglyBT does not have a wiki page for this topic yet**

![image](https://user-images.githubusercontent.com/37715552/65395048-9dc5d680-dd63-11e9-8046-28687549835a.png)

Anyway, it works as intended, just need to be Documented so people will know its there.
