### ISSUE TITLE
Torrent "search library" field clear button bound to double click

### ISSUE THREAD

**Issue by detelosk** [BiglySoftware/BiglyBT#1265]
When the “Search library” field on the top right of the torrents views has text on it, a round button with a cross appears on its right to allow clearing it. I believe that in BiglyBT versions prior to 2.1 a single click would activate it, but it now requires a double click. The current behaviour does not seem in line with the rest of the interface. Is it a bug or is there a reason for it?

“About BiglyBT” system information:

```
Java 1.8.0_202 (64 bit)
  Oracle Corporation
/Applications/BiglyBT/.install4j/jre.bundle/Contents/Home/jre

SWT v4928r15, cocoa, zoom=200, dpi=72
Mac OS X v10.14.6, x86_64 (64 bit)
B2.1.0.1_B06/4 az3
```

**Comment by parg** [comment]
Seems like an issue with the latest SWT version (4928r15) (the one that fixes the memory leak introduced by the previous SWT version...)

**Comment by detelosk** [comment]
Ah, the joys of version upgrade roulette! Thank you for confirming the behaviour as an issue. Here's to the next release providing a painless match.

**Comment by parg** [comment]
I created https://bugs.eclipse.org/bugs/show_bug.cgi?id=551405 - hopefully they'll take a look sometime.

**Comment by detelosk** [comment]
For me, it is back to working as expected: since the regular expression toggle (“.*”) was added to the search field (starting with BiglyBT 2.7?), a single click on the cross is enough to clear the search field. If I am not the exception in seeing this, I think that this issue can be closed. Thanks!

**Comment by esabol** [comment]
> For me, it is back to working as expected: since the regular expression toggle (“.*”) was added to the search field (starting with BiglyBT 2.7?), a single click on the cross is enough to clear the search field. If I am not the exception in seeing this, I think that this issue can be closed. Thanks!

Yesssss! I just upgraded to 2.7.0.2, and it’s fixed for me also. I agree that this issue can be closed now. You’d be surprised at how much this bug was bothering me on a daily basis. Thank you! I also love the regular expression support.
