### ISSUE TITLE
BUG?   B6 freezing

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#1266]
B6 has been freezing on me. No idea why. Perhaps we need a WIKI explaining how to collect information to attach.

Going back to B5, I noticed the following issue: ![image](https://user-images.githubusercontent.com/37715552/65406773-8a8c2880-ddae-11e9-83f0-2be5f80e8bff.png)

I had thought the issue of multiple checking/allocating/etc. had been resolved a while back. But seems it still happens.

* Java 1.8.0_221 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_221

SWT v4922r17, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.1.0.1_B06/4 az3 Freezing
B2.1.0.1_B05/4 az3 now back to B5

**Comment by parg** [comment]
Permanent freeze or does it unfreeze after a bit? 

You could try removing the (...) bind IP setting and see if is somehow associated with that change.

**Comment by NaPurHab** [comment]
Starts fine. And as I said in the other issue. The new VPN string change works.

I just went to check on a transfer. And the interface was not responding. Window slightly dimmed and the header show the 'Not Responding' message.   I forced it closed and restarted after a while it happed again. Tried a system reboot, still happened.

When I reinstalled B05 its been running with no problems for several hours now.  Definitely something in B06 that is the issue.

**Comment by parg** [comment]
Can you try B07, see if that fixes the issue?

**Comment by NaPurHab** [comment]
Ok, I've tested it for 12 hours and no sign of it reoccurring. Looks like you got it.

One suggestion, for the new RegExp in Bind To.  Change the words regular expression in the example to a Link to the Wiki on RegExp.  Would be useful to newbies.
