### ISSUE TITLE
any chance to run it on headless NAS over a web interface

### ISSUE THREAD

**Issue by nephaste** [BiglySoftware/BiglyBT#127]
Hi 

i am develloper for Qnap (and QnapClub Community)

I am looking for a way to run it on headless Linux and control it over a Web Interface

is it feasible ?

Thanks for all ...

**Comment by parg** [comment]
Simplest way is to use the console ui. You can test this by simply installing BiglyBT and running it via

`./biglybt --ui=console`

That will spew a load of SWT related errors though so we could really do with a separate script.

The in the console UI enter

`plugin install xmwebui`

Then enable pairing via

`pair enable`

and go to  http://remote.vuze.com to login

**Comment by TuxPaper** [comment]
As you can see from parg's comment, it should very very similar to the Vuze at http://wiki.vuze.com/w/Setup_WebUI_without_GUI#Run_Vuze_and_install_web_ui  (Starting at *Run Vuze and install web ui*)

https://www.biglybt.com/download/ has a tar.gz that would need to be extracted to the Qnap.  Assuming Qnap  has JRE installed, `java -jar BiglyBT.jar --ui=console` should start it.  As the wiki mentions, you can also go to `http://qnap.ip.address:9091/` and login as `vuze` with the password as what `pair enable` returned.

Let us know if you run into any issues, or if there's anything we can do on our side to make it easier for you and other users to get it up and running

**Comment by TuxPaper** [comment]
hmm, java -jar doesn't work :(  This does:

```
java -cp BiglyBT.jar:log4j.jar:commons-cli.jar com.biglybt.ui.Main --ui=console
```

**Comment by TuxPaper** [comment]
I did some testing, and while the steps work (extract tar.gz, run biglybt, install xmwebui, enable pair), sometimes `pair enable` returns the wrong pairing code the first time around.  Calling `pair` right after `pair enable` should give you the correct pairing code (which is hopefully the same as the first one)

**Comment by nephaste** [comment]
thanks i ll give a try

**Comment by nephaste** [comment]
seems half working

credential  vuze / EP8HE78U (tried Vuze as well in user)

EP8HE78U is paring generated bring me localy on error 404 page and http://remote.vuze.com  (nothing, white page)

using Oracle JDK8 152 ... all seems ok on stdout

https://pastebin.com/dbAuhBrb

need also to find a Way to report the pairing key to user... is there a way to write it in plain text somewhere in a txt file ?

**Comment by TuxPaper** [comment]
I modified your comment to remove your access code;  It's something you wouldn't want to share with the world.

Did you try http://qnap's-ip:9091 from a device on the network to see if anything loads (or prompts for creds)?
Locally, running `wget 127.0.0.1:9091` should also return "Authentication Failed" if the webui is up and running (and a html file if you pass ins `--user vuze --password xxx`


also, check to see if the Access Code is the same with `pair` after you run 'pair enable'

---

If BiglyBT is already running, you can get the pairing code with the following command:
```
java -cp BiglyBT.jar:log4j.jar:commons-cli.jar com.biglybt.ui.Main --ui=console -c pair
```

if you grep it correctly, you can get just the access code

**Comment by diizzyy** [comment]
I can confirm that the xmwebui works however it does have some quirks/bugs?
https://github.com/BiglySoftware/BiglyBT-plugin-xmwebui/issues/2

**Comment by tassadar81** [comment]
I followed the instruction for a ui-console, xmwebui and pair enable but as i try to access with vuze/<the code returned by pair enable> the login fails. It keep asking me for user and password. Someone can help me?
I'm running it from a synology nas with openjdk 1.8.0_151

**Comment by iav** [comment]
Trying the same on no-gui, ssh only raspbian 
```
$ uname -a
Linux hel 4.14.96-mvebu #32 SMP Tue Jan 29 06:24:23 CET 2019 armv7l GNU/Linux
```
set with BiglyBT_Installer.sh

start from ssh
```
:~/biglybt$ ./biglybt --ui=console -c pair
Starting BiglyBT...
Suitable java version found [java = openjdk 1.8.0_181]
Using swt/swt-x86.jar vUnknown
SWT check failed with: org.eclipse.swt.SWTError: No more handles [gtk_init_check() failed]
Loading BiglyBT:
changeLocale: *Default Language* != English (United States). Searching without country..
changeLocale: Searching for language English in *any* country..
changeLocale: no message properties for Locale 'English (United States)' (en_US), using 'English (default)'
DEBUG::Sun Feb 10 03:32:40 EET 2019::com.biglybt.core.proxy.impl.AEPluginProxyHandler::installTor::631:
  UIFunctions unavailable - can't install plugin
    AEPluginProxyHandler::checkPluginInstallation::571, AEPluginProxyHandler::getPluginServerProxy::498, AEProxyFactory::getPluginServerProxy::173, WebPlugin$16::runSupport::1483, AsyncDispatcher$1::run::161, AEThread2$threadWrapper::run::304

Attempting to load aliases from: /home/iav/.biglybt/console.aliases.properties
Running BiglyBT 1.8.0.0...
Using configuration settings from:
  /home/xxx/.biglybt/
> -----
Available console commands (use help <command> for more details):

  [] xml   [#] hack   [a] add   [] create   [c] check   [q] queue
  [r] remove   [tar] torrent_archive   [s] start   [h] stop   [] host
  [] publish   [] forcestart   [tl] tlog   [l] log   [m] move
  [rs] runstate   [] share   [+] set   [sh] show   [u] ui   [] logout
  [] quit   [?] help   [] alias   [] prio   [] plugin   [pair] pairing
  [ar] archive   [subs] subscriptions   [tag] tag
> -----
pair
Current pairing state:
        Status:      Update successful (2/10/19 3:32 AM)
        Access code: xxxxxxx
pair
```

I try to open from laptop in same LAN in browser http://192.168.1.x:9091/, then enter login vuze and access code from log as password — but password form appears again.
I try to enter code on http://remote.vuze.com/ — and get "Please make sure Vuze is running and accessible." status.

How to take control on vuze in this box?
Maybe, it can run in kind of VNC session, and then I can connect and disconnect to bbt delicious GUI from other computer?

**Comment by parg** [comment]
works fine for me following the same instructions that you did  - you could with the latest beta to see if anything has been fixed since the 1.8.0.0 release - download this from

magnet:?xt=urn:btih:BCBU7BDEERMF3IFXUTD7EJZGDHM4PO2P&dn=core_BiglyBT1801-B15-signed.jar&net=Public&net=I2P&tr=http%3A%2F%2Ftracker.amazonaws.com%3A6969%2Fannounce&tr=http%3A%2F%2Fs5ikrdyjwbcgxmqetxb3nyheizftms7euacuub2hic7defkh3xhq.b32.i2p%2Fa&tr=http%3A%2F%2Fjcgok7sfv2ycwdluzjr6s5bdca4ps6beaogilp72dzl6mopp46ya.b32.i2p%3A6968%2Fannounce&fl=http%3A%2F%2F127.0.0.1%3A6905%2Ftags%2FGetTorrent%3Fhash%3DBCBU7BDEERMF3IFXUTD7EJZGDHM4PO2P&xl=19211570&_s=6&_l=2&_d=1549725934000

and replace the BiglyBT.jar with that.

**Comment by iav** [comment]
all the same.
Any logs for debug?
Looks like auth failure - some criteria not met. login, password, network filter, browser headers?

**Comment by parg** [comment]
You should change your access code as you included it in the post...

Did you attempt to change any of the other settings regarding authentication? You can check config changes by typing 

set -export

**Comment by iav** [comment]
No, I am new with text BBT interface and change nothing after installation.
set -export shows a lot of info... I don't know what to look for.
example:
```
set "Plugin.xmwebui.Config Migrated" 1 int
set "Plugin.xmwebui.Pairing Auto Auth" 0 int
set "Plugin.xmwebui.Pairing Migrated" 1 int
set "Plugin.xmwebui.Pairing Session Key" xxx string
set "Plugin.xmwebui.Password Enable" 1 int
set Plugin.default.pairing.accesscode LQS98GU9 string
set Plugin.default.pairing.enable 1 int
set Plugin.default.pairing.last.error  string
set Plugin.default.pairing.status.info "Update successful (2/10/19 7:02 PM)" string
set Plugin.xmwebui.Password [B@b12ecc unknown
```
My bbt now sit inside home LAN, no external access, clean just generated host, and all configuration will be cleaned again before start of real usage, so all keys and paroles leaks seems acceptable risk level.

**Comment by parg** [comment]
hmm, pairing auto-auth isn't set for some reason - that means that the vuze+access-code won't work.
try

set "Plugin.xmwebui.Pairing Auto Auth" 1 boolean

in the console UI

**Comment by iav** [comment]
And now it works - I see generic gui for torrent add/del/start/stop at http://192.168.1.22:9091/#

**Comment by petcol** [comment]
Hi I seem to be having a remote authentication issue.
I can see the login screen from <http://mylocalIP>:9091  I assume vuxe to be the user and I also assume that
pair enable

from the consule should have returned the code but I get this?
</--------------- start cut ----------/>
Apply these updates with the 'plugin update' command
pair enable
Current pairing state:
        Status:      No remote services enabled
Failed to get access code: create failed, Field 'group_id' doesn't have a default value
</--------------- end cut ----------/>

Suggestions
Raspberry Pi

**Comment by petcol** [comment]
> Hi I seem to be having a remote authentication issue. I can see the login screen from http://mylocalIP:9091 I assume vuze to be the user and I also assume that pair enable
> 
> from the consule should have returned the code but I get this? </--------------- start cut ----------/> Apply these updates with the 'plugin update' command pair enable Current pairing state: Status: No remote services enabled Failed to get access code: create failed, Field 'group_id' doesn't have a default value </--------------- end cut ----------/>
> 
> Local LAN not trying to get to it from outside.
> 
> I also have a version running happily on Windows, should I be shutting it down first?
> 
> Suggestions Raspberry Pi

I tried this
set "Plugin.xmwebui.Pairing Auto Auth" 1 boolean

I got this back
> Parameter 'Plugin.xmwebui.Pairing Auto Auth' set to '1'. [boolean]
╒══════════════════════════════════════╕
│ plugins.xmwebui │ BiglyBT Web Remote │
╘══════════════════════════════════════╛
Boolean     │ "Plugin.xmwebui.Pairing Auto Auth"                 │ true
            │ Enable default password protection: username=vuze, password=<pairing access code>

I used vuze as the user and blank field for the password and I believe it's opened from the Web GUI 
That's a very new interface for me so I'll work my way through it.
But appears to access O.K.

**Comment by petcol** [comment]
O.K. successfully downloading, now a questions I use a proxy but can not seem to find Option Connection Proxy etc.  

Could you point me where to look for the instruction's ?

**Comment by parg** [comment]
Thanks for reporting the "group_id" issue, there was a bug there!

Not sure what proxy you are referring to?

**Comment by petcol** [comment]
> Thanks for reporting the "group_id" issue, there was a bug there!
> 
> Not sure what proxy you are referring to?

O.K. now I'm getting the pair code response as i would expect and once copied into the password field it all worked O.K.

PROXY connections
Allows the client to connect to an external proxy server
TOOLS > OPTIONS > Connection > Proxy

![BiglyBT - Proxy Connections](https://github.com/BiglySoftware/BiglyBT/assets/61083722/d2a35e0d-004e-4bda-bc4e-8a1dc3c6848a)

**Comment by petcol** [comment]
> > Thanks for reporting the "group_id" issue, there was a bug there!
> > Not sure what proxy you are referring to?
> 
> O.K. now I'm getting the pair code response as i would expect and once copied into the password field it all worked O.K.
> 
> PROXY connections Allows the client to connect to an external proxy server TOOLS > OPTIONS > Connection > Proxy
> 
> ![BiglyBT - Proxy Connections](https://private-user-images.githubusercontent.com/61083722/334626680-d2a35e0d-004e-4bda-bc4e-8a1dc3c6848a.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NjAwMjMsIm5iZiI6MTcxNjk1OTcyMywicGF0aCI6Ii82MTA4MzcyMi8zMzQ2MjY2ODAtZDJhMzVlMGQtMDA0ZS00YmRhLWJjNGUtOGExZGMzYzY4NDhhLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDA1MTUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1OWRkZmY3OGRlMGRjODUzY2UyNjkxN2M1NzRmYmVhNzg3NzEzM2JkYWIxYTIwZTMwOGJiMmE3ZjM4NzkxMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lIjzN6Ged1nMGG8Q86dMT3IJyYCMdWHRyoApC-W1zck)

Also it keeps stopping?  

I think the could be something on the Pi that's stopping the terminal connection also, is there a way for the BighlyBT to run as a service ?

**Comment by parg** [comment]
No, can't run as a service. You're on your own regarding Pi support I'm afraid.
