### ISSUE TITLE
Torrent (from magnet) which fails to load silently disappears

### ISSUE THREAD

**Issue by david-bakin** [BiglySoftware/BiglyBT#1271]
(BiglyBT Beta (2.1.0.1_B)7), Windows 2012 R2)

Have seen this for a few days now: When you add a torrent and you get the standard "Operation in Progress" dialog - when it fails (I guess) to find the torrent and after the usual time out the "Operation in Progress" dialog just disappears.  Not always - most of the time you get the usual failure (with retry button, and expanded details).  But sometimes.

**Comment by david-bakin** [comment]
(These are torrents added via the clipboard - via the "monitor clipboard for torrent links" option - in case that matters.)

**Comment by gh338** [comment]
Magnet URI Handler defines a overall lookup timeout for torrent retrieval. If it is exceeded the torrent/magnet get's deleted. To avoid this set to 0->infinite.

**Comment by david-bakin** [comment]
OK, I finally got back to this issue and tried timeout = infinite.  But this is not the behavior I want.  Now the "operation in progress" just sits around forever _and doesn't have the "recycle/restart" icon_!.  So the only thing you can do is close it and restart the torrent by copying the magnet url to the clipboard again.

The behavior I want - which used to be there - is that when the torrent failed - timed out - you'd see a recycle/restart icon as well as the close icon (red slashed circle) and if I'm remembering correctly there was some textual indication that the torrent had failed as well - the message in the dialog changed?  The dialog text box opened up and scrolled to a failure line?  Something or other to indicate it had failed in addition to the recycle/restart icon appearing.

**Comment by parg** [comment]
Hmm, for me the 'Operation In Progress' window has a red 'no entry' icon at the right (don't ask me why that's the icon) and when you hit it it gets replaced with a 'delete' or 'retry' icon. Just make sure that the magnet download has been removed before you hit 'download' otherwise you might get an annoying 'media already added' popup (not sure if I fixed that...)
