### ISSUE TITLE
"Monitor clipboard for torrent links" - where does it show up?

### ISSUE THREAD

**Issue by david-bakin** [BiglySoftware/BiglyBT#1272]
(BiglyBT Beta (2.1.0.1_B07), Windows Server 2012 R2)

So by accident I right-clicked the "Open Torrents" button and discovered it had a right-click menu!

Which includes the very useful "Monitor Clipboard for Torrent Links" option!  Which works great!

My question is: Why have I never spotted this before elsewhere (where it might be more discoverable).  Doesn't appear to be in the normal menus, and a quick look at Options didn't find.

**Comment by parg** [comment]
It is a good point, that's what makes BiglyBT so exciting, all those secret options :) I guess it could be added as a more normal option, I'll take a look.
