### ISSUE TITLE
My harddisk crashed so downloaded data is missing. How to solve "Error: Data missing "<path on crashed harddrive>?

### ISSUE THREAD

**Issue by C-Denninger** [BiglySoftware/BiglyBT#1275]
Hello I thought this would be a simple question but apparently it isn't.

My external harddisk crashed so a part of the already downloaded data is missing. That is also what BiglyBT concludes but instead of offering me to restart (part) of the data I only get "ERROR: DATA MISSING "<path on crashed harddrive> or (Dutch) "FOUT: DATA FILE MISSING "<path on crashed harddrive>.

Since I cannot find a way to fix this on this forum or in the help-files I posted the issue here.

* OS and version: Windows 10 Home, 64 bits including the Microsoft updates until today.
* BiglyBT Version Number: 2.1.0.0
  Java 1.8.0_202 (64 bit)
  Oracle Corporation
  c:\program files\biglybt\jre
  SWT v4922, win32, zoom=100, dpi=96
  Windows 10 v10.0, amd64 (64 bit)
  B2.1.0.0/4 az3
* For *nix: Desktop Environment: Non-LINUX system

**Comment by parg** [comment]
Make sure you mode is set to advanced under Tools->Options->Mode then right-click on the downloads that are in an error state and select the 'force recheck' icon

**Comment by C-Denninger** [comment]
Thanks Parg,
You mean the button with the two yellow arrows I guess. I tried that already, but since the files are nonexistent (or damaged for what I could recover). The error returns with no result.

**Comment by C-Denninger** [comment]
In short: What I want in short is BiglyBT to restart downloading the missing files (like they were new) as they are lost or unrecoverable.

**Comment by parg** [comment]
If you perform the 'force recheck' then the downloads should be placed into a state whereby they re-download the missing bits - is there an issue with where the missing files should be on the hard-disk? Perhaps BiglyBT can't recreate the missing files.

**Comment by C-Denninger** [comment]
Exactly my point, the download goes into a "ERROR: DATA MISSING "path and filename on crashed harddisk (I tried to reset it to a new location) and a STOPPED state. No restart what's however.
Do you think this is a bug in BiglyBT?

**Comment by parg** [comment]
How did you try to reset it to a new location? If you right-click on it then you should get a 'change data directory' option - set this to somewhere on a good disk and then hit the 'force recheck' button if it is still complaining. If that doesn't work then

**Comment by C-Denninger** [comment]
Ah yes that is the solution!
As I recovered part of the old harddisk to the new one and kept the old drive-letter that combination wasn't understood by the program. Changing the data directory to a _new_ location even on the same drive solved the issue.

So the full workaround is:
1. Right-click ⇾ 'Change Data Directory' (Dutch: 'Verander Data Map' / 'Nieuwe doelstelling') to a different (sub)directory
2. Right-click ⇾ 'force recheck' (Dutch: 'Forceer hercontrole'), the two-yellow-arrows-in-a-circle-button.
3. Finally; restart the torrent(s).

Did the trick,

Thanks Parg!

**Comment by parg** [comment]
Glad you figured it out, cheers!
