### ISSUE TITLE
Checkboxes in Files view render weird

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#1277]
I feel like I read something recently about a change to the checkbox styling? Anyway, the checkboxes in Options definitely look different, and a lot better IMHO:

![image](https://user-images.githubusercontent.com/538020/65889557-711b4b80-e36f-11e9-8a3c-b425c9a17ed8.png)

Buuuut, the ones above the Torrent Details "Files" list are rendering as white-on-gray when checked now (shades of the `setBackgroundMode(INHERIT_FORCE)` thing from #1002).

![image](https://user-images.githubusercontent.com/538020/65890111-6319fa80-e370-11e9-9f26-503cf6ba600b.png)

("Hide..." is unchecked, in that screenshot, while "Tree View" is checked. Not that you can tell. ...TBH this looks _exactly_ like `INHERIT_FORCE` rearing its shading-ey head again.)

#### "System" block
```
Java 1.8.0_222 (64 bit)
  Oracle Corporation
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.222.b10-0.fc30.x86_64/jre

SWT v4924r25, gtk/3.24.11, zoom=100, dpi=96
Linux v5.2.13-200.fc30.x86_64, amd64 (64 bit)
B2.1.0.1_B08/4 az3
```

**Comment by ferdnyc** [comment]
Same thing is happening to the checkboxes in the "Options" tab of Torrent details. Not the "Privacy" tab, though. Yes, the "Console" tab. Urgh, OK, lemme catalog these in order:

#### Mis-rendered checkboxes
* Torrent Details: Files
* Torrent Details: Options
* Torrent Details: Console (and Tools: Console)

#### Properly rendered checkboxes
* Torrent Details: Privacy
* RSS Feed Scanner: Options
* BiglyBT application menus
* Tags Overview: Settings
* Open Torrent Options
* Make a torrent (File > New Torrent... dialog)

..Those were all the places I could think of offhand with checkboxes, rest are N/A (no checkboxes) or I didn't think to check, and of course there are plenty of plugins I don't have installed.

**Comment by ferdnyc** [comment]
Added "BiglyBT Web remote configuration" to problem rendering list, and "Uninstall Plugins dialog" to properly-rendered list.

**Comment by TuxPaper** [comment]
hmm, there is still one rogue `parent.setBackgroundMode(SWT.INHERIT_NONE);` in TabbedEntry that might be doing it.  I'll disable it for linux, but not for another beta or two, since there's some major restructuring coming out in the next beta.  I'll comment here when I do.

**Comment by ferdnyc** [comment]
> #### Mis-rendered checkboxes
> * Torrent Details: Options

Weirdly, this one is fixed in B09.

Not any of the others. _Just_ that tab. :laughing:

**Comment by TuxPaper** [comment]
Try B11 and let me know if anything changed

**Comment by ferdnyc** [comment]
Installing now...

Hmm. Well, first weird (but unrelated) thing: A lot of settings reset.
* All of my tags reset to non-Visible (the box was actually unchecked
* The tag buttons disappeared from the Library view, even though the option is still checked — to get them to reappear, I had to first make the tags visible, _then_ uncheck and re-check the Tag Buttons setting.
* My RSS Feed Scanner sidebar entry (which is normally always there) disappeared, I had to reopen it from the menus.

But as far as checkboxes go:
* Torrent Details: Files — not fixed
* Torrent Details: Options — (still) fixed
* Console - not fixed
* Web Remote settings — not fixed

So, nope, zero changes from B10 in terms of the checkboxes, I'm afraid.

**Comment by TuxPaper** [comment]
B13 for sure, it's the lucky one

**Comment by ferdnyc** [comment]
Aww, that trick never works, Bullwinkle!

...But this time it did:
> * Torrent Details: Files — **fixed**
> * Torrent Details: Options — (still) fixed
> * Console - **fixed**
> * Web Remote settings — **fixed**

Since even the web remote plugin is fixed (and without updating), I figure it's safe to assume that it's fixed everywhere. Thanks!

**Comment by TuxPaper** [comment]
Everywhere might be an overstatement, but let's just say all :P If you happen to cross any that aren't, at least we know the reason now -- that the one of the widgets the checkbox is on has a background color or image set explicitly.

**Comment by ferdnyc** [comment]
> Everywhere might be an overstatement,

I am comfortable in my hyperbole!

But, root cause noted. I'm sure it'll come up _eventually_. If not for this exact problem, then some other (related) issue.
