### ISSUE TITLE
Files view not rendering any data

### ISSUE THREAD

**Issue by ms52538** [BiglySoftware/BiglyBT#1279]
Windows 10
Beta 2101_B10

My Torrents - Library view
Select torrent with multiple files contained within
In the column "Files" that appears within the Library view, click on the # of files in the torrent
Normally a window pops open with rendered data of all the files within the torrent, but the new functionality is the window pop open but remains blank and no data is rendered within it.

**Comment by TuxPaper** [comment]
Should be fixed in the next beta.  Thanks for reporting, and I'm glad someone knows about the secret popup dialog on file count :fireworks:

**Comment by ms52538** [comment]
Not so secret any longer - but I do love it, use it often.

Thanks!, and resolved :)
