### ISSUE TITLE
[Feature request] No option to manually recheck a file?

### ISSUE THREAD

**Issue by mr-rubbish** [BiglySoftware/BiglyBT#128]
In Vuze there was a menu option to force the client to recheck a file against the torrent file.
This feature was present even in Azureus but seems to be strangely missing in BiglyBT.

Please add it back in! 
Thank you!

![untitled](https://user-images.githubusercontent.com/33392379/32414658-feb572d2-c223-11e7-9f1b-730a58bc6dcb.png)

**Comment by parg** [comment]
Set your Mode to intermediate/advanced (this hasn't changed...)
