### ISSUE TITLE
Remote Pairing Issue

### ISSUE THREAD

**Issue by srialmaster** [BiglySoftware/BiglyBT#1281]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4922, win32, zoom=100, dpi=144
Windows 10 v10.0, amd64 (64 bit)
B2.1.0.0/4 az3

* OS and version Windows 10.0.18362.329 
* BiglyBT Version Number 2.1.0.0

I am trying to use the remote pairing tool version 1.0 and it isn't working. I keep getting access denied when trying to pair with the access code.

Enable pairing of BiglyBT and remote applications/interfaces is checked.
Enable secure pairing is NOT checked.
Enable registration of non-public network service addresses is checked.
Explicit Attributes is NOT checked.
Show BiglyBT Remote remote icon in status bar is checked.

When I try to pair my cell phone that is using the BiglyBT mobile application on my Samsung Galaxy S10, it is getting an error that it isn't authorized when using the access code supplied by the BiglyBT client on my windows computer. Also, when I look at the remote access icon at the bottom, it states that my phone's IP address was Access denied.

**Comment by Asgardsurfer** [comment]
I was getting that too early on so I stopped using the pairing feature. Instead now, I am using the BiglyBT remote plugin (LAN only). Works really well!

**Comment by srialmaster** [comment]
I figured out the issue. You have to use the Pairing and the Web Remote together. Also, you have to make sure the "enable default password protection: username=vuze, password=<pairing access code>" is set. This solved my issue!

**Comment by parg** [comment]
Thanks for fixing it yourself, we were getting to the ticket, honest!
