### ISSUE TITLE
Piece map doesn't show

### ISSUE THREAD

**Issue by larsm17** [BiglySoftware/BiglyBT#1282]
B2.1.0.1_B10, Win10

Piece Tab/Piece Map is empty. 
Can get it to show if I put mouse cursor on a piece being downloaded in the upper part of the window. 
Would be nice to see a piece map also for torrents where there is no download activity..

**Comment by larsm17** [comment]
I use a good hex editor to do manual merges of files where BiglyBT for certain reasons (skew, offsets) can't merge them. It is essential for me that I can see my own piece map, see the missing piece number and calculate its address in the file. Previously I just had to make sure that the torrent was running in order to see my piece map. 
From Beta 10 this possibility is not there anymore, the torrent need to have a download in order to show the piece map and I furthermore have to click on a piece being downloaded to get the piece map to appear.

**Comment by parg** [comment]
Out of interest what calculations are you doing? Perhaps some info could be added to the header section to make things easier

**Comment by larsm17** [comment]
I'm calculating a piece starting position in a file where piece number x piece size +offset gives the address within the file.
A simple calculation and I've now found that the piece map in Files view works equally well, I don't need to see the whole torrent piece map from Pieces view.
Still think it is awkward that you should have to wait for an active download in order to see the map in Pieces view.

**Comment by parg** [comment]
Tux has done some work on making it visible for inactive downloads. I'll look into adding 'piece offset in file' to the header information on hover

**Comment by parg** [comment]
B12 has these changes in, please test

**Comment by larsm17** [comment]
The piece map in Pieces view is now (after B12) by default visible again, thanks!!
I also noticed the file offset being displayed when hovering over a piece.
