### ISSUE TITLE
Min Seeds value range

### ISSUE THREAD

**Issue by gh338** [BiglySoftware/BiglyBT#1283]
Could we have Min Seeds value range up to 9999 ?

* Ubuntu 18.10
* BiglyBT 2.1.0.1_B10
* KDE

**Comment by parg** [comment]
where is this setting?

**Comment by parg** [comment]
ah, subscription results? Done in next beta if so!

**Comment by gh338** [comment]
Sorry for the late reply - and YES in subscriptions but also in Swarm Discoveries if that makes any difference...
Thanks a lot !

**Comment by parg** [comment]
Ah, the Swarm Discoveries one will require a plugin release to fix - might not be immediate unless you desperately need it

**Comment by gh338** [comment]
Subscriptions is fine if it is the easier one.

Cheers

**Comment by gh338** [comment]
Swarm plugin also working ;-)

Cudos !
