### ISSUE TITLE
Download Path search in "Open Torrent Options" window - enhancement

### ISSUE THREAD

**Issue by akidburn** [BiglySoftware/BiglyBT#1284]
Hi all,

I am using the current beta and as it is I had the idea for a small enhancement, would it be possible to include a search form similar to the

"Search Library" search 

in the "Open Torrent Options" windows when creating a new download and selecting the 

"Save Location"

It would be much more efficient to choose the Path for a large Torrent beforehand, than move the files after Downloading. And if the Target Directory has been used before, it would be simple to enter part of the name of the save location and simply have the desired location selected from the history.
The Color grading right now is rather useful already, but a small search window next to the "Available Space On Drive Display" would be even better.

Please add

Thanks
akidburn

**Comment by parg** [comment]
The 'Save Location' is a drop-down list that remembers previous save locations. You can also hit CTRL+space after typing a prefix of a previous location to get a popup window with matches. Is this enough?

**Comment by akidburn** [comment]
@parg That works. Is this an option available on all drop down lists of this type?
Thx by the way

**Comment by parg** [comment]
It is a special case for the save-location one only :(

**Comment by akidburn** [comment]
biglybt is essentially built with java swing right?

because you could probably adapt this one for this case:

https://www.algosome.com/articles/java-jcombobox-autocomplete.html

**Comment by parg** [comment]
No problem :)
