### ISSUE TITLE
Docker build image

### ISSUE THREAD

**Issue by gh338** [BiglySoftware/BiglyBT#1285]
Would it be possible to have a docker image for automated compiling of BT along with its dependencies and plugins as the 'official' way is somewhat out of my league ?

Much appreciated !

**Comment by parg** [comment]
Sounds good, who's going to do it?

**Comment by gh338** [comment]
I can do the docker part.
What platform do you build on ? (Ubuntu/SuSE/RedHat)
What packages did you install for building ?
We could build all this on OBS to make things easier.

Cheers

**Comment by parg** [comment]
Currently everything is pretty much done by hand. For example, the BiglyBT.jar is built (by me) within Eclipse using .jar export

https://github.com/BiglySoftware/BiglyBT/blob/master/core/BiglyBT_parg.jardesc

**Comment by parg** [comment]
There is Maven/Travis stuff in https://github.com/BiglySoftware/BiglyBT but it isn't something I use
