### ISSUE TITLE
<existing_tag>_old 

### ISSUE THREAD

**Issue by gh338** [BiglySoftware/BiglyBT#1288]
I have some tag logic going on. 
Tags in the form of 

<existing_tag>_old 

keep appearing.
I probably missed something about tag mechanics in BiglyBT... but what is it ?

* Ubuntu 18.10
* 2.1.0.1_B11
* KDE

**Comment by parg** [comment]
Those tags most likely come from setting up a Tag with 'Limit Settings' having a 'removal policy' of 'Move to _old'

**Comment by gh338** [comment]
Thanks for the hint - found it in the removal policy as you described.
