### ISSUE TITLE
Subscriptions -> Max Age calculation error

### ISSUE THREAD

**Issue by gh338** [BiglySoftware/BiglyBT#1289]
In Supcriptions -> Max Age setting it to 

1 hour ->outputs 119 min
1 day -> outputs 47 hr
1 week ->outputs 13 day
1 month ->outputs 59 day
1 year  -> outputs 24 mo

Not sure if it is a display or calculation error

* Ubuntu 18.10
* BiglyBT 2.1.0.1_B11
* KDE 5.5

**Comment by parg** [comment]
That's how it works - 1 hour actually gives you < 2 hours etc
