### ISSUE TITLE
Double options in MacOS menubar.

### ISSUE THREAD

**Issue by erg12** [BiglySoftware/BiglyBT#129]
Hi, I have a problem with double (and sometimes triple) options in MacOS menubar.
Any way to fix it? 
Mac 10.13.1
BigBt 1.2.0.0

![32323](https://user-images.githubusercontent.com/33417663/32438075-9263ac4a-c2e9-11e7-883c-64ee11f8f3b7.png)

**Comment by parg** [comment]
Maybe that's part of the 'Extreme Mod' - Extreme Menus

**Comment by erg12** [comment]
When I changing something in preferences or going to plugin deinstallation options in menu bar are growing.
![1](https://user-images.githubusercontent.com/33417663/32438423-b2129ea6-c2ea-11e7-80fb-dc6707b802e4.png)
![2](https://user-images.githubusercontent.com/33417663/32438425-b22ef114-c2ea-11e7-8a9e-4ef7b4ad6175.png)

Clean client - seme problem with new macos user.

**Comment by erg12** [comment]
The problem only occurs in "Classic Interface".

**Comment by parg** [comment]
Should be fixed in 1.2.0.1_B03 - join the Beta Program to get it (See Help menu). Thanks

**Comment by TuxPaper** [comment]
Closing issue do to age and lack of update. If anyone still has this issue, please file a new one.  Thanks!
