### ISSUE TITLE
Option to disable tag discoveries

### ISSUE THREAD

**Issue by Xemnarth** [BiglySoftware/BiglyBT#1290]
![Annotation 2019-10-07 110527](https://user-images.githubusercontent.com/6406869/66291303-8570c280-e8f2-11e9-8efd-8acb870c343a.png)

**Comment by Xemnarth** [comment]
Also suggested as my client keeps getting a lot of unwanted Swarm Tags under Tags Overview

**Comment by parg** [comment]
There is Options->Interface->Tags: Show Swarm Tags in Overview
