### ISSUE TITLE
Feature Request: Cancel/Close Multiple Dialogue Boxes

### ISSUE THREAD

**Issue by ms52538** [BiglySoftware/BiglyBT#1291]
You might have received this before - and perhaps already thought of it and there is no quick solution. Thought I'd toss it out there for you just to see.

When I select multiple torrents and then perform an action on them (i.e. rename), I get the corresponding number of torrent dialogue pop-up boxes appear on the screen. This is probably my least favorite feature of the client. And say, you had copied incorrectly some information that you want to append to said torrents in the rename process. There is no simple way to cancel/close all of the open dialogue pop-up boxes that are on the screen. I have to individually click on every single box and make it disappear to see the next box below it, and so on. And let's say that I was working with a TAGS view that had 200 torrents which I had selected to rename all, so now I have 200 open dialogue boxes on my screen that need to be individually closed. UGH. Any more I find it easier just close my client down and restart it than to deal with those boxes.

So, two streams of thought on this, working backward: (1) can a kill switch be built-in someplace that when selected will automatically cancel/close any open dialogue boxes? (2) can the client open a single frame pop-up box and have all the torrents I am applying said action to (i.e. rename) all appear in individuals lines (much like the pop-up box that appears when I am adding multiple new torrents into the client) and in that then give me an option to rename each of the files in that single frame pop-up box) - that way if I want to cancel/close the pending action, I just close one window? 

Just trying to think of different approaches to achieve my request, with the unfortunate disposition of not know code or java. 

Ultra-low priority, it looks like you guys have your hands full and are busy with other stuff that's been popping up.

Thanks, as always!

**Comment by parg** [comment]
Hmm, how about a long-press on the cancel button causing all outstanding dialogs with a 'cancel' to be cancelled? Not sure it could be added magically to all such dialogs in BiglyBT but if you enumerated the ones in particular where that might work I could take a look. I'm assuming that your reference to 'rename' above is the one shown when you select Organize->Rename... from the right-click torrent menu?

**Comment by ms52538** [comment]
Hola! Correct on how I'm performing the rename. For example, one of things I do is append the end of my torrent file names with an indication if it is active on the tracker site or if it has been removed. The name change corresponds then down to the O/S file system level (for single filed-torrents, else I have more work when there is multiple files contained within a torrent that must all be renamed). Needing to cancel a transaction of renaming a large amount of torrent tiles happens for me here.  So your thought of a "long cancel click to close all" is a good fit for the situation. 

Beyond that, there are times where I may accidentally drag a bunch of highlighted files into a column when I actually trying to click up above in a menu function, and that causes 'mass panic' as files begin to move and in that case there is nothing I can do to stop it except to emergency task/close the client. lol. Hey, we all fat-finger once in a blue moon, don't we? haha

Thanks for the quick reply, always appreciate it M8. 

PS - does it come across as fake/unauthentic when an American says "mate" to an Englishman? haha

Ok, how about "Cheers!"

**Comment by parg** [comment]
hah, mate works although to me at least it has a tinge of Australian to it :)

**Comment by TuxPaper** [comment]
Realistically, all those sorts of prompts should just be converted to "show one dialog a time, with a button that says 'no to all' or 'cancel to all'".  I've done a few in the past year, but obviously there's still some out there.

As a workaround, doesn't pressing ESC close the dialogs.  That's how I usually close them all

**Comment by ms52538** [comment]
To your question, no, not directly. Pressing escape is the equivalent of mouse click. Two issues: A) each dialogue box is not focused, so I have to click on each box (UGH), and then click on Cancel or press Escape (double UGH).  If you have 200 dialogue boxes open, well, you get my point.

**Comment by parg** [comment]
long-press on cancel will be in next beta, Tux can make things more beautiful if he gets the time!

**Comment by parg** [comment]
or not!

**Comment by ms52538** [comment]
Awesome. As I had stated, this is very low low low priority as you both seem quite busy of late with lots of other changes taking place. This was just a convenience request. So ... as always, Thank you! :)

**Comment by TuxPaper** [comment]
Things that also annoy us get higher priority ;)

Beta after next beta will show one dialog at a time, ESC to cancel them all.  I kept the long press on cancel in there too.

**Comment by ms52538** [comment]
Awesome, and thank you! LOL, are you saying I'm annoying? ;)

**Comment by TuxPaper** [comment]
haha, no, having 100 dialog pop up is annoying :P

**Comment by ms52538** [comment]
It's like .... Christmas, with all the trimmings, in October. :) Thank you so much. Looks fantastic.
