### ISSUE TITLE
How to stop a site creating new tags?

### ISSUE THREAD

**Issue by PrototypeZero** [BiglySoftware/BiglyBT#1294]
Recently started downloading torrents from a new site and for nearly every torrent it creates a new tag with its website name (if its not already there).  I can delete the tag but next torrent from there it usually created again.
Doing such things without user permission or any kind of prompting is IMO potentially dangerous to the configuration of BBT and completely uncalled for.

Its not the auto cat feature (that is disabled) and it only happens to this one new site.

How the hell is it doing this and more importantly how to stop it?

**Comment by parg** [comment]
What is it with people having to be so aggressive? Do you think it makes me want to spend time replying? Let me rewrite that for you

Recently started downloading torrents from a new site and for nearly every torrent it creates a new tag with its website name (if its not already there). I can delete the tag but next torrent from there it usually created again.
~~Doing such things without user permission or any kind of prompting is IMO potentially dangerous to the configuration of BBT and completely uncalled for.~~

Its not the auto cat feature (that is disabled) and it only happens to this one new site.

How ~~the hell~~ is it doing this and more importantly how to stop it?

**Comment by parg** [comment]
Next beta will have an option at the bottom of Options->Interface->Tag to disable it

**Comment by PrototypeZero** [comment]
Sorry if I caused any offence.
But I was annoyed at the torrent site (not yourself or the project) and just thought someone here might point out a reason for this behaviour I had never seen before.
