### ISSUE TITLE
Error Message I've never seen before.

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#1298]
![image](https://user-images.githubusercontent.com/37715552/66723556-54a7f600-ede8-11e9-8bd3-9f2b19edda3e.png)
What is this?  How do I correct for it?  This is new, and I have not changed anything on my system since around Beta 7.  No Ports given, so difficult to forward specifically. Currently I only open ports 49001 for MLDHT, and 49876-49880 for BBT.

Java 1.8.0_221 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_221

SWT v4922r17, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.1.0.1_B14/4 az3

**Comment by parg** [comment]
Any chance you have a firewall/AV product that has kicked in and started blocking BiglyBT from listening on a server socket?

**Comment by NaPurHab** [comment]
Only Norton Security/AV. And nothing has changed. Purevpn I have the Port Forwarding Option, so the listed ports are setup in the VPN. And I've made no changes to any of them.  Rebooted and now over 6 hours uptime in BBT. No sign of the error.
But if it is saying something is Firewalled, could it list the port?

**Comment by parg** [comment]
A selector isn't associated with any particular port - it is a general mechanism for dealing with multiple 'file descriptors'. They do have a 'purpose' though, I can add that to the message.

**Comment by NaPurHab** [comment]
I  just thought if it is talking about Firewall, that a port is involved. But added info in the error message is never a bad thing.
