### ISSUE TITLE
Feature Request: Another indicator for the piece map.

### ISSUE THREAD

**Issue by larsm17** [BiglySoftware/BiglyBT#1299]
The latest indicator addition was Merge Read and Merge Write indicators and I would very much like to have an indicator for Forced Piece.
When you have a merge between 2 torrents then both of them will request forced priority from each other and for a multi file torrent there will be lots of forced flags set in both torrents and it will really become a mess when you have a 3 or 4 file merge going..  :-) 
I'm not asking for an improvement of the very complex priority system but being able to directly see which pieces are on priority would be helpful especially when you want to to manually prioritize a certain file in a multi file torrent by removing forced flag from the other files.

**Comment by parg** [comment]
sure, check next beta

**Comment by larsm17** [comment]
Works like a charm, thanks!
(My choice of color is black which makes a very visible black frame around a piece in the map.)
