### ISSUE TITLE
Maven/Gradle?

### ISSUE THREAD

**Issue by ava1ar** [BiglySoftware/BiglyBT#13]
Hi, guys!

Do you use Maven or Gradle for managing the dependencies and build process? It is really strange to see modern Java application, which doesn't use one of them.

**Comment by Shusshu** [comment]
I'm in the process of adding support for Maven but I saw code is missing from the repo...

They are including a bunch of plugins in the jar directly which I guess is not right

**Comment by Shusshu** [comment]
This can be closed :)
