### ISSUE TITLE
Import new .magnet automatically

### ISSUE THREAD

**Issue by Dingmatt** [BiglySoftware/BiglyBT#130]
Hi,

Similar to the "Import new .torrent automatically" feature (options/files/torrents) is it possible to create the same functionality for .magnet files (i.e. import directories, tags, etc).

Regards,

**Comment by parg** [comment]
Magnets are links rather than files, so you wouldn't find them in directories - perhaps you could give a scenario where this feature would apply?

**Comment by Dingmatt** [comment]
True. Though a few 3rd party applications that provide a 'blackhole' option (saving a torrent to a folder, to then be picked up by BiglyBT) have the option of saving the magnet link as a physical .magnet file if no torrent is found.

BiglyBT already has ability to open these files (and treats them like magnet links) but this is a manual process which would benefit from the same automation .torrent files are privilege to.

**Comment by parg** [comment]
ah! I never knew that :) How about simply extending the existing 'import' logic to handle both .torrent and .magnet files?

**Comment by Dingmatt** [comment]
That would certainly cover my usage scenario, I can't imagine anyone would need to treat the two types differently.

**Comment by parg** [comment]
OK, I'll do that - it'll be in the next beta (1201_B02), probably today or tomorrow

**Comment by Dingmatt** [comment]
Many Thanks

**Comment by parg** [comment]
B02 is out, please test!

**Comment by Dingmatt** [comment]
@parg Looks like its working. 
It seemed to first resolve the magnet file into a torrent and then went on with the auto process as normal, tags all look correct.
