### ISSUE TITLE
Feature Request: Swarm merge indicator in "Simple List" Progress column

### ISSUE THREAD

**Issue by actricom** [BiglySoftware/BiglyBT#1302]
When swarm merging files, the Progress column shows "DOWNLOADING + SWARM MERGE". However, I like to have the ETA showing, which makes this disappear. There looks to be plenty of room to have both in some form, "ETA: 1h 26m (Swarm DL)" or the "ETA 1h 26m followed by an icon". While we're here, what would also be nice would be some indication on each as to which one they are linked to. So for example while trying to download three individual files using 9 links, instead of 9 lines saying SWARM MERGE you might have 3 lines saying MERGE A, 2 lines saying MERGE B and 4 lines saying MERGE C.

**Comment by parg** [comment]
Use a separate ETA column? The tooltip on the Swarm Merge column should give some info.

**Comment by actricom** [comment]
An additional separate ETA column requires a horizontal scroll bar on my screen. I also don't show the Swarm Merge column for the same reason. Interestingly, I did just turn on the ETA column at the same time as showing ETA in the Progress column and the results are quite different - the Progress column varying around 5-10 minutes longer for a 50 minute download (oh it's just changed to 3 minutes shorter)!

**Comment by parg** [comment]
There are two kinds of eta, a relatively raw one and a smoothed one - there are two separate ETA columns for each type, can't remember what the progress column uses
