### ISSUE TITLE
VPN Helper for AirVPN stays in ?? status

### ISSUE THREAD

**Issue by Slowrider1969** [BiglySoftware/BiglyBT#1307]
After last update, the VPN helper will not go to OK mode.  Tried manually entering UN and PW for AirVPN, saving, and does not clear the issue.  Am I missing something.  It had worked fine until this last update.  
![image](https://user-images.githubusercontent.com/48262625/67234103-1aeb7680-f40a-11e9-93c5-1d9e233ec405.png)

![image](https://user-images.githubusercontent.com/48262625/67234144-33f42780-f40a-11e9-9461-61b9d0be2289.png)

* OS and version  Windows 10 PRO  ver 18362
* BiglyBT Version Number   B2.1.0.0/4 az3

**Comment by omzig10** [comment]
Agreed. This seems to happen reasonably regularly when AirVPN makes changes to their Login page. It has happened before, and was fixed within a few months by the VPN Helper developers. I am guessing it's a fairly quick fix...
