### ISSUE TITLE
BiglyBT no longer transcodes to iTunes/.mp4

### ISSUE THREAD

**Issue by carvermon** [BiglySoftware/BiglyBT#1308]
For some time my BiglyBT app (2.1.0.0) on a Mac OS 10.11.6 has sometimes refused to transcode .mkv files, and now it will not transcode any .mkv or .avi files to .mp4 using the built-in iTunes converter. The files will go into the iTunes device window, but just sit at 0% progress (though previously I would get a failed notice).
Any idea as to the issue?

Thanks much. System info below.

Java 1.8.0_221 (64 bit)
  Oracle Corporation
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home

SWT v4928, cocoa, zoom=100, dpi=72
Mac OS X v10.11.6, x86_64 (64 bit)
B2.1.0.0/4 az3

**Comment by parg** [comment]
please join the beta program (see the help menu) and let BiglyBT update to the latest version of the transcoer plugin - tell me if that fixes the issue (and if not what error messages are in the log)

**Comment by carvermon** [comment]
Hello parg,

Thanks so much for the response. I have now joined the beta program. Not sure when I'll have the opportunity to test the transcoder, but will report when I do. Cheers.

**Comment by carvermon** [comment]
Hello again,

Just now sent an .mkv file to the iTunes transcoder and it started converting right away! Thank you much, sir. Guess I'll be back here with a log if trouble reappears, but this seems to have done the trick.

**Comment by parg** [comment]
excellento!
