### ISSUE TITLE
Add peer via javascript

### ISSUE THREAD

**Issue by gh338** [BiglySoftware/BiglyBT#1310]
Is there a way to add peers ( with fixed ip / .b32.i2p ) via javascript action (and automate via tag) ?

* Ubuntu 18.10
* BiglyBT 2.1.0.1_B16
* KDE

**Comment by parg** [comment]
What are you trying to achieve?

**Comment by gh338** [comment]
i just want to know if it is possible - certainly not crucial.
Thanks.
