### ISSUE TITLE
Fails at magnet links

### ISSUE THREAD

**Issue by nayots** [BiglySoftware/BiglyBT#1311]
When you open and start torrenting a magnet link for example it fails for some random reason.
![image](https://user-images.githubusercontent.com/10439945/67509364-7ed89e00-f69b-11e9-9f37-66b5745b8bee.png)
Saying that the file does not exist ???

* Windows 10
* 2.1.0

**Comment by parg** [comment]
If you open the torrent file in BiglyBT once it is running does it work OK?

**Comment by nayots** [comment]
Yes once it is running it does not have this problem. Only when i use the link and the application was turned off before that.

**Comment by parg** [comment]
Some other users have reported the same problem but I can't reproduce it - can you try joining the beta program (See the Help menu for an option) and see if the problem still occurs? Thanks!

**Comment by nayots** [comment]
> Some other users have reported the same problem but I can't reproduce it - can you try joining the beta program (See the Help menu for an option) and see if the problem still occurs? Thanks!

I just joined. Will update soon.
