### ISSUE TITLE
Alter privacy settings for multiple torrents simultaneously

### ISSUE THREAD

**Issue by BPDunbar** [BiglySoftware/BiglyBT#1312]
Currently if you select multiple torrents and open the privacy tab the settings (privacy slider and networks tick boxes) within it are ghosted and cannot be selected. This makes it extremely time consuming if you want to change the privacy settings on multiple torrents.

The only way appears to be to individually select the torrent and change the settings. I do not seem to be able to either select a number of torrents and change them all at once or filter the list according to which networks are enabled or disabled (say to filter to show only those torrents with ip2 enabled) which would make individually updating easier.

**Comment by parg** [comment]
You can multi-select and then right-click to get the context menu that will update multiple networks in one operation (although you can only update one network at a time)

You can also use Tags with constraint expressions to group downloads based on their current network setting (hasNet( "I2P") for example))
