### ISSUE TITLE
Not showing at system tray, and torrents added not showing temporarily

### ISSUE THREAD

**Issue by adolfovalle** [BiglySoftware/BiglyBT#1313]
Windows 10 v10.0, amd64 (64 bit)
B2.1.0.0/4 az3

After minimizing BiglyBT (having the minimize to system tray option on), it will often disappear and not show even at the system tray, making it impossible to find and having to ctrl+alt+del and force-close the process and reopen it as the only option.

Also this happened just now for the first time, i added a torrent via magnet link and after it correctly asked me the files, it didn't show up on my torrent list, but whenever i would click again on the magnet link it would say that the torrent was already added, after that i would re-check and it still wouldn't show as downloading. This went away only after restarting the process.

**Comment by parg** [comment]
When BiglyBT vanishes from the tray does re-launching it cause it to become visible? If not it sounds as if BiglyBT is crashing - perhaps you could generate a 'debug.zip' file (Help menu, last option) and send it over to paul@biglybt.com ?

Regarding your second issue - some users have reported a problem whereby after adding the magnet the downloads gets added to the 'seeding' area of the Library with an error state ('torrent file missing'). Is it possible that this is what you are seeing?

**Comment by freMea** [comment]
Related to issue #390 and I think it is mostly related to explorer.exe restart described here #1565. Of course, all tray icon are set to be shown. BBT tray icon really disappear and it is the only one affected by an explorer.exe restart.

**Comment by as-muncher** [comment]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B2.7.0.2/4 az3

Even though I have "Enable System Tray" checked, plus "Minimize to system tray" checked, when I minimize BiglyBT, it doesn't even show up in the taskbar, and it doesn't show in the system tray either.  To see it again, I have to double-click on the biglybt icon to bring it up.

**Comment by parg** [comment]
works for me on Windows 10H2 - it wouldn't show up in the taskbar but it should show up in the tray unless it is configured in the windows settings to be hidden

**Comment by as-muncher** [comment]
I'll see after I install the 2021-03 Cumulative Update for 20H2.
