### ISSUE TITLE
Feature Request: OPTION-Files-Ignore didn't work when torrents were added by OPTION-Files-Torrents-Import new...automatically.

### ISSUE THREAD

**Issue by a67878813** [BiglySoftware/BiglyBT#1316]
OPTION-Files-Ignore didn't work when the torrent is added by OPTION-Files-Torrents-Import new...automatically.

Regular expression is selected. It's important for some user.
------------------------
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4922, win32, zoom=100, dpi=96
Windows Server 2016 v10.0, amd64 (64 bit)
B2.1.0.0/4 az3

**Comment by parg** [comment]
true that, I'll take a look
