### ISSUE TITLE
Transcoding to new Mac OS TV App

### ISSUE THREAD

**Issue by d1n077** [BiglySoftware/BiglyBT#1318]
How do I transcode now iTunes has been replaced by the TV App in the new Mac OS?
It just says I need to install iTunes.
Please help!

* Mac OS Catalina
* BiglyBT 2.1.0.1_B17
* For *nix: Desktop Environment

**Comment by d1n077** [comment]
*UPDATE*
So I've just read a closed post where someone had the same problem, now that is fixed.

Is there any way where once the transcode is finished it will be automatically copied to the TV App or does it have to be done manually?

**Comment by parg** [comment]
You'd have to do that manually probably

**Comment by d1n077** [comment]
Thanks Parg, thought so. 
I’ve downloaded the iTunes app that on here and it won’t even do it automatically to that. Oh well, was just me being lazy tbh lol

**Comment by parg** [comment]
It took quite a bit of work to integrate with iTunes and it was always a bit dodgy, so unless there was some really easy way of integrating with the App it'd be too much effort

**Comment by parg** [comment]
BTW for anyone else reading this you can still 'install iTunes support' to get the various apple decide transcode profiles.
