### ISSUE TITLE
Duplicate "Details" menu

### ISSUE THREAD

**Issue by LordSky00** [BiglySoftware/BiglyBT#132]
Java 1.8.0_152 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4757, win32
Windows 7 v6.1, amd64 (64 bit)
B1.2.0.0/4 az3
------------------------------------

Step to repo:

1. open the details of a torrent.
2. Go to the library menu.
3. From the library, right-click and open the details menu of the torrent again.
4. In the sidebar, right-click on the torrent. See issue in screenshot below.

![dup_menu](https://user-images.githubusercontent.com/32420902/32514000-59ddba72-c3c1-11e7-8285-7978f0f39ef5.png)

**Comment by gr88** [comment]
I don't see the issue, don't know what to look for.  I noticed in biglyBt and the previous client that the menu would repeat but I thought that was by design.  What issue are you not happy with?

**Comment by parg** [comment]
hah, I can see it - you have to open the details view from the Library twice (or more...)

**Comment by parg** [comment]
fixed in next beta (B18) - thanks
