### ISSUE TITLE
External I2P router bug

### ISSUE THREAD

**Issue by gh338** [BiglySoftware/BiglyBT#1321]
When the external i2p router is down or restarted while BBT is still runing it hangs or crashes.

* Kubuntu 18.10
* BiglyBT 2.1.0.1_B18
* KDE

**Comment by parg** [comment]
I know there are issues around this - however I have never seed BiglyBT crash or hang - do you have any debug logs from this? If BiglyBT is hung you can get some diagnostics as per https://github.com/BiglySoftware/BiglyBT/issues/930

Look for the bit about

http://127.0.0.1:45100/setinfo?name=AZMSG&value=AZMSG;0;config;log-diags;;

**Comment by gh338** [comment]
I see - thank you very much.

**Comment by parg** [comment]
I'll have a look at improving the reconnection to the external router

**Comment by parg** [comment]
Version 0.9.42.1.3 has "Improved reconnection to external router" - I'd be interested in feedback, in particular if you encounter hangs/crashes

**Comment by gh338** [comment]
Much better now - no hangs/crashes so far.

**Comment by gh338** [comment]
After the external router is restarted there are duplicate destinations 
Mixed+ and Pure+ - are started twice on the router.

**Comment by parg** [comment]
please check this still occurs with 0.9.43.1.1

**Comment by gh338** [comment]
No it does not - however bbt is not able to build tunnels until it's restarted.

**Comment by gh338** [comment]
Seems locked on exit / restart.

**Comment by parg** [comment]
Please see earlier post on providing diagnostics on hang.
