### ISSUE TITLE
Error: Table View Import in Column Setup window

### ISSUE THREAD

**Issue by ms52538** [BiglySoftware/BiglyBT#1323]
Windows - latest Beta Build 2.1.01_B18

Table View Import Error

When performing the function of Table View import in the Column Setup area (after successfully performing an export to clipboard) an error is being thrown: Operation Failed - Incorrect table configuration.data (My.Library.big/MySeeders) when applying to a different category and/or tag view.  

FYI.

**Comment by parg** [comment]
The import/export only works between compatible views (as the available columns can vary between them) - can you check that you're importing into the same view type? For the Library views there are three main view types:

MyLibrary.big = simple view (as selected by the simple/detailed view buttons in the toolbar)
MyTorrents  = incomplete (top by default) detailed view
MySeeders = complete (bottom by default) detailed view
