### ISSUE TITLE
media server sharing all media by default

### ISSUE THREAD

**Issue by digimbyte** [BiglySoftware/BiglyBT#1326]
Windows 10 64bit
2.1.0.0
For what ever reason, I am unable to manually choose what content is available for my devices, and instead publishes all media by default, despite it not being selected in the Media Server plugin
I don't wish to share my library with my whole house hold.
(found solution, "show only transcoded" was unselected)

potential secondary bug, if you have a password and username set in Media server, it is still in effect even if you uninstall the media plugin while keeping the Upnp service (after restart)

**Comment by parg** [comment]
I have a clean install (therefore with the 'publish all media by default' not selected), downloaded some content and it isn't visible to other users via UPnP.  Or is it just for specific devices that you are seeing this? Ah, just saw your edit - I guess it was. 'Only show transcoded files' is selected by default, I assume you deselected it?

**Comment by parg** [comment]
Regarding your second point, the parameters used to control authentication are only used within the 'Media Server' plugin so I'm not sure how they can still be effective if the plugin is uninstalled and BiglyBT restarted. How are you triggering the authentication to occur?

**Comment by digimbyte** [comment]
with the credentials defined, it prompted the user credentials inside
bigly, I assume for the internal media player.
this dialog only showed on the desktop with credentials required via Media
Server and this still displayed after I removed Media Server for a clean
install regarding my original issue

**Comment by parg** [comment]
Did the media player plugin reinstall? If so, and you haven't explicitly deleted the configuration data in biglybt.config (and the other config files), then it will pick up the previous configuration data.

**Comment by digimbyte** [comment]
It did re-install. but im saying it still asked for login details when it
was uninstalled at the time.
