### ISSUE TITLE
First torrent to load always errors

### ISSUE THREAD

**Issue by Mdage** [BiglySoftware/BiglyBT#1327]
Hi, I'm having a weird problem that I am unable to find reference to others experiencing.

It's more of an annoyance that a huge problem, but I always DL via magnet links from chrome, which forces biglybt to open. Unfortunately the first file that clears the hashing conversion always fails, with the error: File is not a torrent.
Not sure what is going on, this issue doesn't happen if I open bigly first, however if I attempt to open multiple magnet files it doesn't matter which one I click first, it will always fail the first to load into the torrent section. 
Really hoping someone has heard of this issue!

* OS and version: Win10 Pro x64
* BiglyBT Version Number 2.1.0.0

**Comment by parg** [comment]
Like https://github.com/BiglySoftware/BiglyBT/issues/1258 and https://github.com/BiglySoftware/BiglyBT/issues/1311 ?

I'm having problems reproducing this, there are a few comments in those issues about it., 

Does it fail almost immediately or does it take a while trying to download the magnet and fail like this later?

**Comment by Mdage** [comment]
It takes a while trying, has the pop-up like it is loading, loads the 64mb odd first file, but once it trys to convert to a torrent thats when it fails

**Comment by Mdage** [comment]
So it finishes the metadata dl then errors.
The strangest thing is that it is only the first file after I restart that has this issue. I can close bigly and try to reproduce and it works fine. Looks like I have to fully restart the computer for this to happen again

**Comment by Mdage** [comment]
Yep looked at those other issues and seems the same

**Comment by parg** [comment]
Can you follow the instructions to join the beta program and see if that resolves the problem?

**Comment by Brokklu** [comment]
Mdage I've been experiencing the same darn issue for over a month although when I close Bigly it actually does reproduce the error in my case. First file gives same File is not a torrent crap. Please let me know if and how you manage to resolve this by posting it here on the forum. Many thanks.

**Comment by parg** [comment]
Hey Brokklu, perhaps you could also try joining the beta program to see if the problem has been resolved? Go to the Help menu, select the 'Join Beta Program' option and then change the setting in the next dialog to the second one to join the program. When you then close the dialog BiglyBT will update to the latest version.

**Comment by Brokklu** [comment]
Beta versions are not my thing I avoid them like the plague. I love modding but I've not time to waste on experimental stuff when it comes to torrenting I want stable. Uturrent and bittorrent bit off more than they could chew and smart people are giving them a wide berth nowadays. If bigly wants to follow the way of the dodo then it's up to them. Until then I can handle a simple error. thanks

**Comment by parg** [comment]
I am them.

**Comment by Brokklu** [comment]
done. Thanks for caring about  your product. You actually made my day :)

Currently using 2.1.0.1 B24

**Comment by parg** [comment]
great :)

**Comment by Brokklu** [comment]
and... lo and behold it stopped the error! yay certainly time to rethink my opinions about beta testing ;)

**Comment by parg** [comment]
Thanks for testing - I couldn't reproduce the problem myself so had to guess at potential solutions, hopefully the problem is fixed, but if not I'm sure I'll hear from you!

**Comment by Brokklu** [comment]
No actually I will keep you updated - I have logged in/out restarted my system several times and the error has not yet occurred. I will give you another update next week. Thanks again.

**Comment by Brokklu** [comment]
Still doing ok the error has not recurred since ;)

**Comment by parg** [comment]
Thanks for the update, I can almost rest easy :)

**Comment by Gazza1956** [comment]
Hi I have this exact issue of first torrent errors MacOS B27

**Comment by parg** [comment]
Please generate a debug.zip (Help menu, last option) and send it over to paul@biglybt.com. Thanks!

**Comment by Brokklu** [comment]
After updating to stable version B27 the problem has reoccurred :( please note I have sent the zip to you. Hope it helps.

**Comment by parg** [comment]
Darn it :( I can't see how that was associated with any changes in B27 thought, more likely the bug was still there but just didn't happen to occur for a bit.

Are you manually accepting the torrent in the 'open torrent options' dialog after the download completes or is it automatically being placed straight into the error library state?

**Comment by parg** [comment]
I've added some more attempted work arounds / logging in B28 - please give it a try when you get a chance. If it is still failing a new debug.zip would much be appreciated, thanks!

**Comment by Brokklu** [comment]
Hi sorry to keep you waiting. I've tested it and shutdown and testing it again after installing B28 and all is fine again so something you changed must have affected it.  Basically I have no auto open options selected and it only stops to ask me where I would like to place the temporary file (see attached screenshot).  It could be just a coincidence as I didn't test it repeatedly after the B27 update. Still I've sent the B28 debug as you requested. If you need any screenshots of options just let me know.  Regards

![open torrent options screenshot](https://user-images.githubusercontent.com/57442113/69203998-153a9b00-0b46-11ea-8bb3-c2415e033cc9.JPG)

**Comment by Gazza1956** [comment]
Hi,
 B28 for MacOS Catalina seems to have resolved this issue . First torrent is loading without error

**Comment by parg** [comment]
We've been here before, let's hope it stays that way!

Brokklu - that save destination is where the actual download is saved (not temporary files), if you're moving them somewhere once completed then great, otherwise make sure they don't accidentally get deleted :)

**Comment by Brokklu** [comment]
Hi Parg, Sorry haven't been in touch last week. Yes I move the completed files once completed as the temporary storage cannot hold what I required it to but still thanks for pointing it out. Mind you I don't know 90% of all the functions biglyBT has to offer so my hats off to you and others of your profession.
