### ISSUE TITLE
Ability to combine downloading and seeding panels

### ISSUE THREAD

**Issue by silverbacknet** [BiglySoftware/BiglyBT#1329]
I've always appreciated the way uTorrent has a single list for all torrents, and they can be sorted by completion status if you need to split them that way. I never got used to Vuze splitting them up into completed and incomplete. Is making it possible to combine them all into one master list feasible?

**Comment by parg** [comment]
There is the 'master list' under the 'simple view' (see toolbar buttons to switch between them). Then again, you must have seen this as it is the default view? It is different from the split pane view in that each torrent takes up move vertical space though.

**Comment by parg** [comment]
Ah, are you using the 'classic UI'? If so maybe try the regular UI

**Comment by parg** [comment]
I added a feature to the latest beta (B21) that allows the split view to be merged as per your request via 

Tools->Options->Interface->Tables: My Torrents: Advanced View download split mode - Combined

**Comment by silverbacknet** [comment]
Ah, thank you! I'll give that a shot when it's out, and in the meantime I'll use simple view. It took a bit to find the UI selector, but it looks like I am using the Bigly one.
