### ISSUE TITLE
Moving Stopped Torrents forces Copy-Delete

### ISSUE THREAD

**Issue by akidburn** [BiglySoftware/BiglyBT#133]
Hi,
new problem since a few days.

After the Update to 1.2 Moving Torrent Data Files ( of a seeding torrent) from Contextmenu while the torrent is in a stopped state forces the use of the Copy-Delete Method instead of just Move even if not the Copy-Delete Method is not selected. While the torrent is seeding the Move method is used. 

The problem being I use the automatic seed stop plugin which means i move the files once the seeding has finished, but with this bug moving the files to their destination folders takes significantly longer.

Please fix

akidburn

**Comment by parg** [comment]
Are you moving across file systems? The 'bug' was due to people wanting to get a progress report on the move operation, the only way to do this in Java is to explicitly copy the file.  However, we do attempt to detect if the file system is the same for source+destination.

**Comment by akidburn** [comment]
No, I am moving files from one folder to another on the same partition,
though it is a mounted veracrypt partition. But the copy delete only
happens if the torrents are stopped. If they are still seeding, the move
method is used.

akidburn

Am 08.11.2017 23:52 schrieb "parg" <notifications@github.com>:

**Comment by parg** [comment]
yah, there's a bug - thanks, will be fixed in 1201_B05 hopefully

**Comment by akidburn** [comment]
1201_B05 Fixed It

thx

**Comment by parg** [comment]
thanks!
