### ISSUE TITLE
No 2.1.0 update found 

### ISSUE THREAD

**Issue by WPFilmmaker** [BiglySoftware/BiglyBT#1330]
I still have the 2.0.0 version despite several attempts to check for updates. No update is found.

* OS and version Lubuntu 18.04
* BiglyBT Version Number 2.0.0
* For *nix: Desktop Environment LXDE

Java 11.0.4 (64 bit)
  Ubuntu
/usr/lib/jvm/java-11-openjdk-amd64

SWT v4924, gtk/3.22.30, zoom=100, dpi=142
Linux v5.0.0-32-generic, amd64 (64 bit)
B2.0.0.0/4 az3

**Comment by parg** [comment]
Please check to see if you have enabled 'anonymous updates' in the config - this can sometimes cause issues

**Comment by WPFilmmaker** [comment]
@parg thanks! It worked! Is it a bug that is already known right?

**Comment by parg** [comment]
Yup - enabling that option is supposed to push all the update requests through Tor and downloads over I2P but for some reason it isn't reliable :(

**Comment by WPFilmmaker** [comment]
thanks! Closing.

**Comment by WPFilmmaker** [comment]
@parg just to clarify I did not have any tor or i2p plugin installed, I just thought that 'anonymous' was about some sort of obfuscation, not about tor or i2p. Could it be the case for other reports? I suggest you add "(requires I2p or tor)" next to it for clarification

**Comment by parg** [comment]
Hmm, it should (haha) prompt you to install the 'TorHelper' and 'I2PHelper' plugins during the process to support this - I'll take a look when I get a chance, Cheers!
