### ISSUE TITLE
Scoop and Chocolatey install

### ISSUE THREAD

**Issue by Restia666Ashdoll** [BiglySoftware/BiglyBT#1336]
* OS and version - Windows 10
* BiglyBT Version Number
* For *nix: Desktop Environment
Are there any plans to make BiglyBT available for those who use Scoop or Chocolatey like other torrent clients like qBittorrent and your predecessor Vuze ?

**Comment by parg** [comment]
Vuze never did any work for Scoop/Chocolatey so that must have been done by a third-party - perhaps they could do it for BiglyBT as well?

**Comment by Restia666Ashdoll** [comment]
Yeah I know. But someone added Vuze to Chocolatey. And most popular clients like qbittorrent and deluge are available on Scoop/Chocolatey. I don't think BiglyBT should be left out.

**Comment by parg** [comment]
Maybe you could do it?

**Comment by Restia666Ashdoll** [comment]
I am actually now creating a scoop json in gist for BiglyBT. I will try asking the opening of @oltolm opinion before making a pull request to scoop-nonportable.
Are the github and site release links same or are there any difference ?

**Comment by Restia666Ashdoll** [comment]
Also, are the installer hash checks available anywhere online ?

**Comment by parg** [comment]
I'll ask the guy who does the releases

**Comment by Restia666Ashdoll** [comment]
I guess they are same, since they have the same SHA-256 string.

**Comment by TuxPaper** [comment]
Yes, they are the same.  The Github installers are renamed with a "GitHub_" prefix, because that sounded like a cool thing to do that the time :P

**Comment by Restia666Ashdoll** [comment]
https://github.com/oltolm/scoop-nonportable/issues/78
https://gist.github.com/Restia666Ashdoll/d2bf171f275c9061d7797b4010c09021

**Comment by Restia666Ashdoll** [comment]
Its already available in Homebrew, Pacman and apt-get.

**Comment by Restia666Ashdoll** [comment]
Finally is it possible to uninstall from the command line.

**Comment by Restia666Ashdoll** [comment]
Its merged
https://github.com/oltolm/scoop-nonportable/blob/master/biglybt.json
```
scoop bucket add nonportable
scoop install biglybt
```

**Comment by parg** [comment]
Nice one, cheers!

**Comment by Restia666Ashdoll** [comment]
So, apparently its now also on AppGet
`appget install biglybt`
https://appget.net/packages/i/biglybt
https://github.com/appget/appget.packages/blob/master/manifests/biglybt/biglybt.yaml
