### ISSUE TITLE
Odd allocating issue.

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#1338]
![image](https://user-images.githubusercontent.com/37715552/68537129-44266500-032d-11ea-92cd-5ac0a87f6f86.png)

Your guess is as good as mine.  I had selected for download only the first file in a torrent.  After checking the quality of the finished first file. I decided to get the rest of the files in the torrent.  The above is what happened when it was allocating the remaining files.

Java 1.8.0_231 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_231

SWT v4922r17, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.1.0.1_B23/4 az3

**Comment by parg** [comment]
weird - do you have 'zero fill' set for allocation strategy?

**Comment by NaPurHab** [comment]
![image](https://user-images.githubusercontent.com/37715552/68542351-d8b6b480-0379-11ea-83a3-9cd55414639c.png)

Do you mean this?

**Comment by parg** [comment]
yup
