### ISSUE TITLE
Tag Issue:  Untagged not applying

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#1339]
![image](https://user-images.githubusercontent.com/37715552/68537383-97e67d80-0330-11ea-9f98-4e24f72ccd88.png)

Normally when I finish processing a video file. I remove the Specific Tag (PLEX in the above), and allow it to be untagged.   The 2 that are highlighted in Blue are showing BLANK entries.  And when I check the Untagged they are not included.  They have NO Tag, instead of Untagged.

I just installed B23 and did not see this issue in B22.

I use the Untagged as a Trash Can. Untagged torrents are allowed to seed to 10:1, then get deleted.  The 2 entries in the image don't show in Untagged. And I can only find them in the Library entry, and other system tags.  They don't show in any of my user Tags.

Torrents that I had removed the Tag from prior to B23 all have the Tag as Untagged.

Java 1.8.0_231 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_231

SWT v4922r17, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.1.0.1_B23/4 az3

**Comment by parg** [comment]
Nothing changed between B22 and B23 that could have caused this... If you click on one of the downloads that have no tags and check the Tag sub-view does it also no assigned tags? You can actually have multiple untagged tags, you could try creating another one and see if that exhibits the same behaviour. Create a tag, right-click on it and select Properties->Untagged

**Comment by NaPurHab** [comment]
Yes right click, Organise->tags shows no tags.   Trying to drag to Untagged on the horizontal Tag Labels, gets a DO NOT symbol.

I tried turning off the Properties->Untagged, then back on. **That fixed it.** But it happened. So a glitch to keep in mind.

**Comment by parg** [comment]
I'll take a look, thanks!
