### ISSUE TITLE
Fix a url in your beta window

### ISSUE THREAD

**Issue by eurobank** [BiglySoftware/BiglyBT#134]
Hi fix this:

> There are no new updates available for you.
> 
> You are running the latest stable beta release (B05)
> 
> Visit the <a href="http://dev.biglyt.com/">Beta Program site</a> for further information on both stable and unstable releases.
> 

The beta url "dev.biglyt.com" is missing a "b".

cheers !

**Comment by parg** [comment]
oops :) thanks!
