### ISSUE TITLE
REQUEST: Add "Forced Seeding" in Add Mode Drop-down list

### ISSUE THREAD

**Issue by ms52538** [BiglySoftware/BiglyBT#1342]
Hola, 

Quick request:
Windows 10 - latest beta build out

When adding a new torrent, a pop-out window appears to select various things to tag and assign the new torrent. In this window you have things such as Add Mode, Initial Tags, Tracker Peer & Connection Options, etc.. Under the "Add Mode" there is a drop down list of things to select, including: Queued, Stopped, Seeding, etc.. I'd like to request that "Forced Seeding" be added to the drop down list. This prevents me from having to take the extra step of going back and looking for the torrent and changing its status after I've added it. Just seems like a logical thing - but then again, that's just me.  Thanks gents!!! :)

**Comment by ms52538** [comment]
I'm losing it. I swear. LMAO. Please delete. Sorry.

**Comment by parg** [comment]
:P
