### ISSUE TITLE
Torrent with mutliple files, expeanded - Shift L-Click not selecting all

### ISSUE THREAD

**Issue by ms52538** [BiglySoftware/BiglyBT#1343]
Hola!

New issue:
WIndows 10
1201_B23

When looking at a torrent in any view, one that has multiple files contained, I select the twistie to expand and see all said files. If I Shift+L-Click on the first file on the top, and then Shift+L-Click on the last file, I expect all files to be selected. Instead it randomly selects some files but not all. This appeared within the last few betas. I thought it might be my computer but after a few reboots and continuing to see it, I suspect it is an issue. HOWEVER, if I perform a Control+L-Click and select each file within the torrent, that does work correctly and I can select all of the files that way then perform a function such as "revert all files".  In some cases when I perform the Shift+L-Click on the files, my client will lock up and goes into "not responding" mode and does not recover - forcing me to kill it under Task Manager.

FYI. Hopefully it's not just my PC.

Thanks gents!!!

**Comment by parg** [comment]
To begin with I thought you were having another 'moment' :) However I can reproduce it so you can breath easy. It is some side effect of the fact that sorting is now applied to the files when sort is by another column (e.g. sort a Library view by 'size' and the files within a torrent will also be sorted by 'size', Obviously this re-ordering is confusing the selection process...

**Comment by parg** [comment]
Should be working on B24...

**Comment by ms52538** [comment]
I'm a BIG fan :)
Nice work. Resolved. ... and closed.
Thank you, Sir.
