### ISSUE TITLE
Issue with Catalina? 

### ISSUE THREAD

**Issue by DanielWFisher** [BiglySoftware/BiglyBT#1344]
I'm on the latest version of BiglyBT and it had been running most excellently for the past many months. I then upgraded to macOS Catalina and BiglyBT no longer downloads certain things on its own. It can "consume" a torrent file but then fails to make a connection to the remote server, apparently, as no files at all will download. I also cannot download plugin updates. In the BiglyBT Component/Plugin Installer, it just sits trying to download but never gets anywhere. At the bottom I see 34 users max listed, whereas there are usually several hundred thousand.  Sometimes it's just 3 or 5 users. My internet connection works just fine with other applications. 

Any ideas on what is blocking BigltBT from getting connected? 

Here are the results of the internet connection test from BiglyBT. There are definitely some errors going on there: (I got rid of certain ip and bindable address info

> Test starting
> Default public address is xxx.xxx.xxx.xxx
> Bindable addresses: 2601:<snip>, 
> 0 NAT devices found
> No SOCKS proxy found
> No HTTP proxy found
> 1 bind addresses
>     fe80:0:0:0:<snip>
> Testing HTTP outbound
>     Test successful
> Testing TCP outbound
>     Test successful
> Testing UDP outbound
>     Test failed: Outbound test failed
> Testing TCP port 58585 inbound
>     Test failed: NAT test failed: Error: Read timed out
>     Check your port forwarding for TCP 58585
> Testing UDP port 58585 inbound
>     Sending outbound packet and waiting for reply probe (timeout=5000)
>     Sending outbound packet and waiting for reply probe (timeout=10000)
>     Sending outbound packet and waiting for reply probe (timeout=15000)
>     Sending completion event
>     Test failed: Inbound test failed
>     Check your port forwarding for UDP 58585
> Testing HTTP port 8080 inbound
>     Test failed: NAT check failed: Error: Read timed out
>     Check your port forwarding for HTTP 8080
> 1 public/external addresses found
>     185.<snip>
>     AS details: as=9009,asn=M247, GB, bgp_prefx=<snip>
> BiglyBT Services test
>     BiglyBT Website - www.biglybt.com
>         Certificate: CN=biglybt.com
>         Connection result: 200/OK
>     Version Server - version.biglybt.com
>         Connection result: 200/OK
>     Plugins Website - plugins.biglybt.com
>         Certificate: CN=biglybt.com
>         Connection result: 200/OK
> Indirect Connect test
>     Connecting to https://www.biglybt.com/
>     Certificate: CN=biglybt.com
>     Connection result: 200/OK
> Distributed protocol test
>   Incoming routing established for 5F373552....<snip>
>   Searching 0 contacts for 0 test targets
>   Searching complete, 0 targets found
>   Results
>       insufficient outbound connects for analysis
>   Incoming routing destroyed for 5F3735....<snip>
> IPv6 test
>     No default public IPv6 address found
> Test complete
> 

Thank you!

**Comment by DanielWFisher** [comment]
As well, when I run the NAT / Server Port Test, I get the result:

> Testing port TCP 58585 ... 
> Unable to test: Invalid port given, or test service failed.
> Another application may already be using this port.. 
> (Error: Read timed out).
> 
> Testing port TCP 58585 IPv6 ... 
> Unable to test: Invalid port given, or test service failed.
> Another application may already be using this port.. 
> (Error: Read timed out).

So what I do is either restart the BigltBT app ( to get another random port) and then re-test (with the same result) and/or restart my computer and only open my VPN and BiglyBT, with the same result occuring.

**Comment by DanielWFisher** [comment]
Oh I figured it out. The little code representing my VPN connection (BigltBT settings, Connection: Advanced Settings: Bind to local IP address or interface) had changed from utun1 to utun2. After changing that, everything now works splendidly. 

Keep up the excellent work!

**Comment by parg** [comment]
Thanks for working it out, I was just about to start worrying :)

**Comment by DanielWFisher** [comment]
My pleasure. I figured if I started “loosening” some of my settings a clue
might shake loose. :)
