### ISSUE TITLE
Retro beta version numbers

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#1345]
Hey, uh, that's two beta releases in a row now that have been announced in the long-dead 1.2.0.1 series.  Would the gentlemen care to rearrange their digits? :wink:

![image](https://user-images.githubusercontent.com/538020/68641066-b0dd6300-04d7-11ea-9378-263e4eed4235.png)

**Comment by parg** [comment]
Such confusion!
