### ISSUE TITLE
Duplicating an existing torrent

### ISSUE THREAD

**Issue by ms52538** [BiglySoftware/BiglyBT#1349]
Hola,

I've recently found myself having to re-download torrents from a tracker, of which I have about 2,800 torrents. The re-download element is that the old torrents are no longer registered with the tracker under my profile user key which was tagged to them. Having been assigned a new profile user key, I can redownload the torrents and activate them once more by identifying the existing files on my hard drives.

When I re-download a torrent from the tracker, Bigly recognizes that the torrent already exists and offers me a prompt to download and apply a new torrent in addition to the existing one. Love that it does. However, that is where the convenience of technology stops; I have to go through and completely reassign the torrent its category, tags, comments, and location/placement of the subdirectories and files. Considering that I use Plex, my challenge is to always have to clean-up torrent names, file names, file locations, etc. - and over the past year, I've done extensive work on the 2,800 torrents I have within Bigly. Unfortunately when I re-download a torrent - it will not recognize the existence of file placements or file renames from the initial torrent already in Bigly (i.e. - torrent with 720 files; torrent renamed, all the files within the torrent renamed and many of those files individually moved to different drives and sub-directories. In order to re-download and 'match' my existing content I find it much easier to first 'revert file locations' which moves the files back to the original sub-directory AND it renames the files back to their original names - but in the process of doing that I essentially wipe out hundreds of hours of work that I performed on the initial download torrent. 

So, a thought; can Bigly identify not only the torrent already exists, but offer to duplicate the identified existing torrent, including file name changes and file location placements that already exist? And/Or - can Bigly simply take the re-downloaded torrent and switch out the assigned user profile key with the nex one into the existing torrent?

A bit random, I know. I had surgery on my arm last week and the meds have been making me loopy. Hence a couple of prematurely submitted issues. Sorry about those. 

Thanks gents!

**Comment by parg** [comment]
I assume these are 'private' torrents? The difference between old + new is simply the announce-URL within the torrent I assume (as that is where profiles/passkeys are usually encoded). Unfortunately for private torrents the ability to edit tracker URLs is disabled (to prevent users from adding public trackers and getting around the private tracker's desires to try and manage things. 

If this is the case I could perhaps think about allowing the replacement of a privat torrent's announce URL with that of another private torrent on addition...

**Comment by ms52538** [comment]
It is, you nailed it. While probably obscure in feature need, I can envision it as a feature. I really do wish that I could learn code. It just has never been my strength in IT. But I have enough vision that I am a pain in the ass when it comes to asking questions and humbling myself to the developer(s) (who are upstanding gents in this case).

**Comment by parg** [comment]
So it currently asks you if you want to add it as a separate download. I'll make it so that if you decline that then it prompts you if you want replace the old url with the new one - making a combined dialog is a bit of a pain.

**Comment by parg** [comment]
Check out B25 - see if that works for you!

**Comment by ms52538** [comment]
Amazing! You are nothing short of a miracle worker. Please accept my gratitude and appreciation for the quick turnaround on this. Thank you, Sir.

**Comment by parg** [comment]
hah, I wish, more like an old hack! Cheers
