### ISSUE TITLE
Upload speed 0 after downloads

### ISSUE THREAD

**Issue by Xuchilbara** [BiglySoftware/BiglyBT#135]
There's apparently a problem, or at least an annoyance, that's been around in BiglyBT for some years (yes, also Vuze).

I noticed when one downloads some torrents with no leechers, Bigly keeps dedicating all the resources, or slots, or whatever is called, to those torrents apparently forever, or until some parcticular change is made (forcing seeding, stopping/deleting those torrents, being able to upload at last and least some data from them...).

That results in upload speed being 0 B/s or close for days, weeks or even months.

I don't know what this can be happening, but it would be great is something could be made to change/fix this Bigly behaviour. It isn't nice having hundreds of torrents and 1 MB/s of upload speed and not being able to seed and share anything from all the other torrents...

Windows 7 Ultimate x64 SP1.
BiglyBT 1.2.0.0.

**Comment by parg** [comment]
looking into it!

**Comment by parg** [comment]
1201_B12 is out - please test and see if anything has improved - it is currently a work-in-progress so if not please report back!
