### ISSUE TITLE
can't add new torrent from open torrent link

### ISSUE THREAD

**Issue by amber4389** [BiglySoftware/BiglyBT#1350]
When I try to add torrent files I've made with bigly by clicking open torrents on top left, a screen pops up that is labeled open torrent but has text from clipboard in it and if I try to add file it says the webpage is not valid?
I can drag the torrent to bigly and open that way but it doesnt see that it has the files already in place for seeding so I have to manually stop the "download" and have it look for data files.
It's weird because it started happening today with every other one. any ideas?

windows 7 ultimate 64
Bigly 2.1.0.0

* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment

![Screenshot_1](https://user-images.githubusercontent.com/57728310/68798885-391d4e80-0625-11ea-8b09-5bc95c185d6e.png)

**Comment by parg** [comment]
Why not check the 'open for seeding' checkbox on the last panel of the create-torrent wizard?

**Comment by amber4389** [comment]
That would work if it would not copy everything from clipboard first and not allow me to add any torrents.  I can try it next time I make a torrent but why is it copying clipboard stuff to begin with

**Comment by parg** [comment]
Not sure but I think it copies from the clipboard if it thinks it might be a torrent link. You can just hit the delete key (to remove the stuff copied from clipboard) and then select the 'add files' button to select the torrent file.

**Comment by amber4389** [comment]
> Not sure but I think it copies from the clipboard if it thinks it might be a torrent link. You can just hit the delete key (to remove the stuff copied from clipboard) and then select the 'add files' button to select the torrent file.

tried that did not work

**Comment by parg** [comment]
Make sure you entirely delete everything in the text area before hitting 'add files'

**Comment by parg** [comment]
if you're getting 'open torrent failed' with 'cold not open http://blah/dsad' then it is because your clipboard contained a URL, BiglyBT thought the URL referred to a .torrent file and auto-pasted that into the open-torrent dialog, you didn't remove it completely and then BiglyBT downloaded whatever was at that URL and found it wasn't a torrent.

**Comment by amber4389** [comment]
> if you're getting 'open torrent failed' with 'cold not open http://blah/dsad' then it is because your clipboard contained a URL, BiglyBT thought the URL referred to a .torrent file and auto-pasted that into the open-torrent dialog, you didn't remove it completely and then BiglyBT downloaded whatever was at that URL and found it wasn't a torrent.<

I removed the text 5 times.  there was no url that I could see in the text as I copied and pasted it to a txt file to see what was in it.  I finally had to clear clipboard via cmd and did not happen when I tried to add another torrent. But I did not use copy and paste prior either. this never happened with vuze at all and may be a glitch?

**Comment by parg** [comment]
Weird, I'll add a 'clear' button to ensure that things are completely cleared.

**Comment by amber4389** [comment]
I thought it was weird also that's why I opened a thread.  Let me know when new version is up and I'll give it a try.  But my OCD says a button should not be needed LOL

**Comment by parg** [comment]
B26 is up :)

**Comment by Brokklu** [comment]
Hi Parg,

I've met with this issue before and generally searched appdata for local files related the download in question. Where have you located this clear button and does it clear files and cache?

Regards,
