### ISSUE TITLE
Portable Version

### ISSUE THREAD

**Issue by Restia666Ashdoll** [BiglySoftware/BiglyBT#1351]
* OS and version Windows 10
* BiglyBT Version Number 2.1.0.0
Are there no plans for a proper portable version ever ?

**Comment by parg** [comment]
What do you mean by 'proper'?  There are some instructions here

https://github.com/BiglySoftware/BiglyBT/wiki/Command-Line-Options

about running BiglyBT from a single folder.

On Windows there is also a command line option 'azureus.portable.enable' (see https://wiki.vuze.com/w/Portable_Vuze, it works the same) that should give you some portability if running things from a drive that can change name across mounts.
