### ISSUE TITLE
Paul, please, please! 

### ISSUE THREAD

**Issue by hatewesterncivilization** [BiglySoftware/BiglyBT#1353]
Paul, hi, I didn't know what I can do now, yesterday I was waiting the whole day and night for updating my stats at few torrent sites like rutracker and kinozal, and nothing. Stats just stopping at some numbers, amount of uploaded without true change, but I was uploaded tons of gigabytes in fact. 

I just saw Bigly increase the time of doing announce to 51 min - 1 hr, and then, fanstastic, it disappear to do the announce. 

Can you please provide alternate config to not do this, do not change the announce time and announce all tracker simultaneously!? 

I just trying getting back up to Bigly from Tixati and this thing interferes to do that. 

Tixati by the way doing this things correct. Taking the announce time reported by tracker and announcing all tracker URL in torrent simultaneously. But I want come back to Bigly, because I have thousands torrents in it, which I cannot make-in to Tixati due to big number of it. 

This would be a revolution if you guys make up those things at least like a alternate config item. Give us an choice to do all the things.

**Comment by parg** [comment]
If you have a torrent with three trackers, A, B and C, they will most likely all have their own, different, 'min_announce' times.

There is no 'The Tracker' in this torrent, so your statement "Taking the announce time reported by tracker and announcing all tracker URL in torrent simultaneously" doesn't make sense. 

Also stats will eventually be reported to trackers if they are active in a torrent, the frequency at which a tracker is announced to doesn't affect the overall totals reported.

Also it doesn't make sense to have multiple trackers in a torrent where stats reporting is a concern - there should be a single tracker only.

**Comment by parg** [comment]
Check out https://github.com/bittorrent/bittorrent.org/issues/82 and http://www.bittorrent.org/beps/bep_0012.html

**Comment by parg** [comment]
BiglyBT follows this specification with the addition that if there are insufficient peers available from, say, the first tier's responding tracker, then it will move on to tier 2 to attempt to get more peers (and so on)

**Comment by parg** [comment]
Now it appears that the 'defacto standard' deviates from this (because it is 'more useful'). I could consider adding an option to do this (hit all tiers in parallel, rather than taking the current more considered approach of 'don't hit a tracker unless there's a reason for doing so'). This won't affect tracker update times though - they need to be respected on a per-tracker basis.

**Comment by hatewesterncivilization** [comment]
Absolutely, just an option. Many thanks for that. Why I am adding well-known public announcers like this list https://github.com/ngosang/trackerslist? Just for sharing torrents with whole community around the world, if torrent not private, and of course there are sharing effect by DHT itself. 

Just curious, looks like Tixati actively pushing through announcing time while announce time really between 50 min-1 hr in rutracker, kinozal cases. Should Bigly support option for that?

**Comment by parg** [comment]
In my experience (over many, many years) the min-announce interval is a very touchy subject with trackers and not obeying it is likely to bring on the wrath of the tracker admins. If Tixati wants to flirt with that then fine but it isn't something I am about to do.

**Comment by parg** [comment]
B27 will have an option under Tools->Options->Tracker->Client: Overrides

    Manage tracker activation to reduce load

If you disable this then the 'defacto standard' approach of querying tiers in parallel will be enabled

**Comment by hatewesterncivilization** [comment]
Dear Paul, incredible, just for information, sounds like I've fixed things about disappearing from stats of rutracker/kinozal sites. Now all torrents I've seeding stable in place. What I've made, moving client into RAM-disk like I'd maded lots time before. 

I think client itself now work super-rocket and then very reflect to internal things. For example, speeds of operations of the RAM-disk something like 10 GB/s reading and 21 GB/s and more writing. Client now super-slim in great self-selfing.

**Comment by hatewesterncivilization** [comment]
Client running now 2 h 52 min about and all fine, I've full list of torrents seeding in fact. Soft I've using for RAM-disk - Primo Ramdisk.

**Comment by as-muncher** [comment]
> 
> 
> Client running now 2 h 52 min about and all fine, I've full list of torrents seeding in fact. Soft I've using for RAM-disk - Primo Ramdisk.

Which software specifically are you using for creating a RAMdisk?  I'd like to use that.
