### ISSUE TITLE
Bigly BT wont' start on windows.

### ISSUE THREAD

**Issue by ioweb-gr** [BiglySoftware/BiglyBT#1355]
* Windows 10  19025 x64
* 2.1.0.0

I'm trying to start bigly bt but nothing is happening. The executable never shows on the task manager. 
I've turned off all antivirus / firewall etc and the issue persists.

**Comment by parg** [comment]
You could try starting via command line - see

https://github.com/BiglySoftware/BiglyBT/wiki/Command-Line-Options

Hopefully that will either work or produce an error we can look into.

**Comment by ioweb-gr** [comment]
Hi,

yes it produces the following error

> 
> C:\Program Files\BiglyBT>java -cp "BiglyBT.jar;commons-cli.jar;swt.jar" com.biglybt.ui.Main
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by com.biglybt.core.util.spi.AENameServiceJava9 (file:/C:/Program%20Files/BiglyBT/BiglyBT.jar) to field java.net.InetAddress.impl
> WARNING: Please consider reporting this to the maintainers of com.biglybt.core.util.spi.AENameServiceJava9
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> There appears to be another process already listening on socket [127.0.0.1:6880].
> 
> Locate and terminate the other program or change the control port - <a href="https://wiki.biglybt.com/w/Commandline_options#Changing_the_Control_Port">see the wiki for details</a>.


However after using powershell I see that no process is binding it. 

> PS C:\WINDOWS\system32> Get-Process -Id (Get-NetTCPConnection -LocalPort 6880).OwningProcess;
> Get-NetTCPConnection : No MSFT_NetTCPConnection objects found with property 'LocalPort' equal to '6880'.  Verify the va
> lue of the property and retry.
> At line:1 char:18
> + Get-Process -Id (Get-NetTCPConnection -LocalPort 6880).OwningProcess;
> +                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (6880:UInt16) [Get-NetTCPConnection], CimJobException
>     + FullyQualifiedErrorId : CmdletizationQuery_NotFound_LocalPort,Get-NetTCPConnection
> 
> Get-Process : Cannot bind argument to parameter 'Id' because it is null.
> At line:1 char:17
> + Get-Process -Id (Get-NetTCPConnection -LocalPort 6880).OwningProcess;
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidData: (:) [Get-Process], ParameterBindingValidationException
>     + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.GetProcessC
>    ommand



And 

netstat -n -a |Select-String "6880" 
yields nothing

**Comment by parg** [comment]
Hmm, well something is preventing it from binding to that port :(

You can use a different port by adding a setting to the command line, that same wiki page has details of it, use `-Dazureus.instance.port=nnnn` as per the other -D flags at the bottom of the page.

Worst case you can use the `-DMULTI_INSTANCE=true` to prevent it from failing if the binding fails. The downside of this is that you won't be able to click on magnets in your browser and have them automatically open in BiglyBT.

**Comment by ioweb-gr** [comment]
OK let's see. First of all following the guide i try to change port but receive an error. I've tried lots of variations with quotes without quotes and the name `biglybt` `bigly` `azureus`, with a space between D and the option and without a space but to no avail. So I must be typing it wrong but I'm just copying and pasting the wiki example and changing the option. 

I receive this following error

java -cp "BiglyBT.jar;commons-cli.jar;swt.jar" -D biglybt.instance.port=17000 com.biglybt.ui.Main
Error: Could not find or load main class biglybt.instance.port=17000
Caused by: java.lang.ClassNotFoundException: biglybt.instance.port=17000

Any idea what I'm typing wrong?

Secondly how do I store this configuration? 

With -DMULTI_INSTANCE=true I was able to start the client but I would like to make these settings permanent if I could at worst case.

**Comment by parg** [comment]
There's no space between the -D and the <property_name>=<property_value>

I added a section to that wiki page on making them permanent.

**Comment by ioweb-gr** [comment]
I see thank you. I managed to start it using another port. I'll test the permanent config

Regarding the Wiki it mentions that 

System Properties are set by using the -D<name>=<value> JVM command line parameters. You can use 'biglybt.' in place of 'azureus.' in property names.

However for future reference this is not accurate  for the instance.port it needs to be `azureus.instance.port` 

`java -cp "BiglyBT.jar;commons-cli.jar;swt.jar" -Dazureus.instance.port=17002 com.biglybt.ui.Main`

worked now for me :)

Much appreciated

**Comment by parg** [comment]
You're right, I'll look into that!

cheers

**Comment by benedictleejh** [comment]
Hi, sorry to bump a closed issue, but I just faced this issue recently as well. Would it be possible to throw an error dialog when BiglyBT can't bind to the port it's trying to? It's quite frustrating for it to fail silently, and I had to do a lot of searching to figure out what the error was to even try to work around it.

**Comment by parg** [comment]
done in next beta!
