### ISSUE TITLE
VPN Helper Plugin: PIA Port Forwarding Not Working

### ISSUE THREAD

**Issue by nofnway** [BiglySoftware/BiglyBT#136]
Hi,
I don't know if this belongs here, and I don't know if this is even a BiglyBT issue, but I can't find any info searching Google on how to fix this, so reporting it. I'd normally ask this in a forum, but I don't know that one is setup yet, so asking here:

Port Forwarding used to work fine. I don't know when it broke, but now, NAT tests fail and uploads are slow or don't connect to available peers. From what I can tell, the IP and the port shown in the PIA manager is not the same being reported by the VPN helper, so I can understand why port forwarding isn't working, but not what is causing this to occur or how to solve the issue. Perhaps this is a bug with the Plugin? Perhaps it is a PIA issue, but as you are probably aware, getting them to address anything in what normal people would call a timely manner is an exercise in futility. Anyhow, if you could fix this if it is a bug, or if you could point me in the right direction if it is not, I'd surely appreciate it.
Thanks!

BiglyBT 1.2.0.1_B05
VPN Helper Plugin v 5.5
Win 10 Pro 17035,rs_prerelease
PIA Manager v75

**Comment by TuxPaper** [comment]
If you are still seeing incoming connections, and the plugin is still reporting that it's getting a port, then the port forwarding is still working.  The port reported by PIA Manager can be different than the one BiglyBT uses.  In theory, we could open a bunch of ports, but I haven't experimented enough to find out what their limit is.

**Comment by nofnway** [comment]
Hi,
Thanks for responding. No, I do not believe I am getting incoming connections, only outgoing. NAT test fails. Does this help? If you need any further info, just let me know.
Thanks!

**Comment by TuxPaper** [comment]
Go to Tools->All Peers and look at the "T" column (I think it's there by default, but you may have to add the column).  If there are rows that say "R", then you are getting incoming connections from the PIA's open port

**Comment by nofnway** [comment]
Hi,
I checked All Peers and there are some marked R. There are not many, but they are there, I guess this is just a PIA UI issue since it what is reporting the incorrect IP and port. I still don't understand why the NAT test is failing then, but as it appears you do not believe this is an issue, I'll close this ticket. Feel free to re-open it if you'd like to keep investigating or think there is more to it. Thank you very much for your help!
