### ISSUE TITLE
Visual Bug in Order

### ISSUE THREAD

**Issue by eurobank** [BiglySoftware/BiglyBT#1363]
Bigly latest BETA version, Windows 10 / 64 PRO.

There is some visual issue as you can see. The two (1) (1) in the queue. The second (1) should be (2) and no (7) is missing.

The Order is fixed only if a click on the Order sorting arrows. Meaning it is a visual only issue.

![2019-11-25 22_04_52-Window](https://user-images.githubusercontent.com/4467158/69574247-5ad8e700-0fd0-11ea-959a-ee518f1e24c0.png)

**Comment by parg** [comment]
Hmm, that's a weird one! Are you saying that when you clicked on the Order sort column header then the number '7' appeared (and one of the '1's went away)? Or that the items were put into the 'correct' order (with one of the '1's appearing between 6 and 8?

**Comment by eurobank** [comment]
yes when i clicked the sort arrows, everything showed well again. One to Ten. In order.

I must say here that i use Downloading in Reverse Seed Count, meaning the order auto-changes frequently. Apparently some change got mixed up. I have seen that several times, and it is not a major problem.

**Comment by parg** [comment]
Next beta (32) should be a bit better behaved - please report if you see the issue after it is released!

**Comment by eurobank** [comment]
While i don't see that anymore, now i see this:

![2019-11-27 17_29_45-Window](https://user-images.githubusercontent.com/4467158/69736928-1f5b2b80-113c-11ea-89a3-6f77e2aae643.png)

And i think it is wrong, UNLESS it takes a long time to queue the Number 3.

**Comment by parg** [comment]
All I changed was the logic that updated the Queue column when positions changed, so not sure.

**Comment by eurobank** [comment]
Ok, meaning this is a different issue. I will open a new issue if i see it again.

**Comment by parg** [comment]
If you do see it then wait a while to see if it resolves. 

Also you could try right-clicking on the 'My Torrents' tab heading and selecting 'pop out' to see if a separately built view exhibits the same behaviour.

**Comment by eurobank** [comment]
Well the thing is i can wait but in Reverse seed mode the queue changes all the time, and after a while (2-3 minutes) the middle queued (2) starts again by its own. So it is hard to tell.

**Comment by parg** [comment]
Also enable the 'downloading rank' column in the downloading view and also Tools->Options->Queue:  Log debug information.

If you then hover over the 'downloading rank' entry for a download you will get a tooltip with some clues about what's going on

**Comment by eurobank** [comment]
Will do so.
