### ISSUE TITLE
[Bug] Missing half digit on large numbers

### ISSUE THREAD

**Issue by Technetium1** [BiglySoftware/BiglyBT#1364]
The last digit of "Reachable" is consistently cut off with any number bigger than 3 digits:
![image](https://user-images.githubusercontent.com/9877150/69576087-9a381100-0f99-11ea-8485-4ebc71ea4e7a.png)
* OS and version
Windows 10 1909
* BiglyBT Version Number
2.1.0.0

**Comment by parg** [comment]
thanks ;)
