### ISSUE TITLE
[bug] faq.legal.url not found

### ISSUE THREAD

**Issue by Technetium1** [BiglySoftware/BiglyBT#1365]
I clicked where the cursor is in the screenshot and the error pops up rather than opening a browser window:
![image](https://user-images.githubusercontent.com/9877150/69591294-56a4cd80-0fc0-11ea-91ad-7f7a7c4b2d68.png)
* OS and version
Windows 10 1909
* BiglyBT Version Number
2.1.0.0

**Comment by parg** [comment]
thanks!
