### ISSUE TITLE
swarm merge fails to merge the last piece (sometimes)

### ISSUE THREAD

**Issue by whiteloader** [BiglySoftware/BiglyBT#1368]
OS and version: Windows 10 1903
BiglyBT Version Number: 2.1.0.0
Java 1.8.0_202 (64 bit)
Oracle Corporation
c:\program files\biglybt\jre
SWT v4922, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B2.1.0.0/4 az3

Suppose I have a dead (no seeders) private linux torrent containing a big iso file "A" and a tiny info File "B" (smaller then on piece). Since the torrent is dead I won't get any data from the swarm. 

However swarm discovery finds me similar torrents with the same Files A and B and an additional tiny File C. If I start Downloading torrent 2 and eventually complete it, it is working as expected gradually completing also the first torrent by merging, but unfortunately **only until 99.9%**. The last piece is often not completed and therefore the torrent 1 not revived/usable.

![image](https://user-images.githubusercontent.com/57460132/69709674-23685880-10fe-11ea-9de4-65f9dc52a0d7.png)

Even if I force a recheck it stays at 99.9%

HOWEVER: If I take the files from torrent 2 and copy them manually over the files from torrent 1, and then recheck it suddenly works and shows the torrent 100% complete (so all the necessary data was available in the first place)

**Comment by parg** [comment]
Unfortunately merging is piece oriented and only considered for files with at least 5 pieces to reduce attempts to merge incompatible files. 

In particular the merging can only guage whether or not things are working based on piece hash checks within the file and if the file is smaller than a piece (well, < 2 pieces considering alignment) then it may not contain an entire piece to be used for verification. Consider that a piece can in theory contain thousands of small files you can perhaps see the complexity (and the reason for the 5 piece limit!)

I could make the piece limit a config option to allow you to experiment but I'm not sure exactly how well things would work.

**Comment by parg** [comment]
Option will be there in B33

**Comment by whiteloader** [comment]
I don't have such a deep understanding as you, but what about this one?

If Download of Torrent 1 finishes, the Client looks at nearly completed files of the torrent 1, and tries to calculate the hashes of torrent 1 using the equivalent files from torrent 2. If they match they will be copied over the files from torrent 1.

**Comment by whiteloader** [comment]
How is the connection made between the two swarm merge torrents? Or does the client by default try to match each and every torrent with every other one?

**Comment by whiteloader** [comment]
I think there is another problem at play here. While it sometimes work, it sometimes doesn't

I have another linux torrent duo that contains exactly the same files (all >500 MB), but still at has problems merging the borders. I noticed that the piece size is different and also the **order of the files differs** – I think that is the main Problem. do you think it would be possible to consider the merging logic I proposed earlier? Or do you have another idea? I really appreciate the merging feature, but it is unfortunate, that it sometimes can't merge the borders.


Example:
Merge source:
![image](https://user-images.githubusercontent.com/57460132/69970891-4f7d4280-151f-11ea-88a0-150f6f99f8f8.png)
![image](https://user-images.githubusercontent.com/57460132/69970923-5f952200-151f-11ea-9991-ca9822136c16.png)

Merge Target:
![image](https://user-images.githubusercontent.com/57460132/69971059-9ec37300-151f-11ea-8281-0416675e740c.png)
![image](https://user-images.githubusercontent.com/57460132/69971027-9408de00-151f-11ea-9ef9-3c2c45eba23f.png)

![image](https://user-images.githubusercontent.com/57460132/69971360-0ed1f900-1520-11ea-8b28-decc087b8d4d.png)

**Comment by parg** [comment]
I'm doing some rework on swarm merging although it won't make the next release.

**Comment by whiteloader** [comment]
That's good news. Let me know if I can help you with more examples.

**Comment by parg** [comment]
I'll need help testing, I'll let you know :)

**Comment by parg** [comment]
I just built B35 with the changes in, please test. Note that to merge small files you will need to set the new 'min-pieces' option to 0.

**Comment by whiteloader** [comment]
sorry I don't know how to do that. Where do I find this version?

**Comment by parg** [comment]
Join the beta program - Help menu, 'join beta program' and select the second option to join. It'll update automatically after doing that.

**Comment by parg** [comment]
might want to hold off for B36, I found an issue :)

**Comment by parg** [comment]
OK, B36 is now live - hopefully things should be working well now!

**Comment by parg** [comment]
B37's out with a further fix
