### ISSUE TITLE
BBT ignoring any changes to folder location on adding torrent

### ISSUE THREAD

**Issue by PrototypeZero** [BiglySoftware/BiglyBT#1369]
For a few versions now BBT will only initially write the torrent data to the initial save position (ie global default or tag default) when adding torrents.  This is regardless of making changes on the add torrent dialog box and then starting the torrent.

You have to manually after the torrent has started,  stop and move the data file location.  Also most of the time it wont even move the data to the specified folder on completion (if set in the tag) like it used to.

**Comment by parg** [comment]
Changing the default save location in the open-torrent-options dialog seems to work reliably for me. 

Note that if you do have a tag assigned and it has an initial-save-location set then this value will always be used regardless of whether you change the explicit save location in that dialog.

If you have two or more tags assigned that have initial-save-locations then one of them will be selected (based on lowest unique ID allocated to the tag when created)

Are you sure that what I've described above isn't working?

**Comment by PrototypeZero** [comment]
Ok, found some torrents were automatically getting assigned a none visible tag with their own folders, so changes weren't being used as you described, so that accounts for them.  

But others definitely without any tags are still getting forced to the default folders despite being changed in the add dialog box.  I'll have to investigate further if there's anything differentiating those that get forced and those that don't (I don't see anything obvious at first glance).

Perhaps when folders are being assigned by tags (or otherwise are going to be ignored like the mystery ones I'm getting) the ability to select a new destination in the add dialog box should be disabled to stop possible confusion as it effectively becomes useless?

**Comment by parg** [comment]
I was thinking of disabling the destination box, I'll take a look.
