### ISSUE TITLE
BBT not able to "Set options back to their default values" - not working

### ISSUE THREAD

**Issue by nickjacobs999** [BiglySoftware/BiglyBT#1372]
Hi BBT peeps,
This feature stopped working some time ago now... I trust this is enuf info. to resolve the issue... :)
Cheers, Nick
- - -
System section details are:
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre
SWT v4922, win32, zoom=100, dpi=96
Windows 7 v6.1, amd64 (64 bit)
B2.1.0.0/4 az2

**Comment by parg** [comment]
Actually it has been working, it just hasn't been updating the view :) Switch to a different tab and back again to see...

**Comment by parg** [comment]
Fixed next beta, thanks.

**Comment by nickjacobs999** [comment]
Oh yer - so it does! Thx!
