### ISSUE TITLE
Inconsistent subscription deletion

### ISSUE THREAD

**Issue by Technetium1** [BiglySoftware/BiglyBT#1373]
When you click the 'X' to the right of a subscription it deletes with no warning, however when you right click and choose 'delete' it asks if you really want to. For the sake of consistency and preventing accidental subscription removals, can we get the same warning when we click the 'X'?

https://github.com/BiglySoftware/BiglyBT/blob/6fb3ea12e38ffe1f6c413017738fb64ae0d06ef2/core/src/com/biglybt/internat/MessagesBundle.properties#L2577

* OS and version
Windows 10 1909
* BiglyBT Version Number
2.1.0.0

**Comment by parg** [comment]
The 'x' in the sidebar doesn't delete it, it just removed it from view. Click on the Subscriptions header, find the subscription you want to view on the right and double-click it to bring it back into the sidebar
