### ISSUE TITLE
What's the opposite of "Add To Sidebar"?

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#1374]
Say I experimentally clicked **Add To >** **Sidebar** in the context-menu for the Console sidebar entry, and now I've got a splitter in my sidebar with a weird, unusable sliver of console showing underneath it... how would I _undo_ that, and make it go away again?

I can't find any controls, menu options, icons, etc. that would seem to have the opposite effect of **Remove From >** **Sidebar**.

I managed to drag the splitter all the way to the bottom of the sidebar, so it's effectively invisible, but **_I know_** it's still there... :eyes: 

#### System block
```
Java 1.8.0_232 (64 bit)
  Oracle Corporation
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.232.b09-0.fc31.x86_64/jre

SWT v4924r25, gtk/3.24.12, zoom=100, dpi=96
Linux v5.3.12-300.fc31.x86_64, amd64 (64 bit)
B2.1.0.1_B33/4 az3
```

**Comment by parg** [comment]
hah - right-click on the 'Console' tab as shown in the sidebar and select 'remove'. I have seen an issue where the tab header isn't drawn, if that is the case then try adding something else to the sidebar in the same way and then headers should appear to allow removal.

**Comment by ferdnyc** [comment]
Thanks! That worked.

> I have seen an issue where the tab header isn't drawn,

Yeah, initially there was no header. I figured it might be something like that, but I was understandably reluctant to experiment further, and possibly end up with ''two'' unremovable sections in the sidebar if I was wrong.

**Comment by iansebryk** [comment]
this might want to be a sticky since, on fresh install, this is the initial behaviour: no tab.  once a second tab is added, tabs DO show and subsequent removals/additions all have proper tabs.  it's adding that first one that's a stumper.  :smiley:
