### ISSUE TITLE
Torrents

### ISSUE THREAD

**Issue by anderdea** [BiglySoftware/BiglyBT#1375]
OK it will be obvious that I’m new to this group. But I’ll give my question a shot anyway.

I have been using Vuze and over the last couple of years BiglyBT. I have noticed over the last few months that many of my torrents don’t seem to be working any longer although they still show up. When I first started using BiglyBT I imported all my Vuze torrents and now I’m finding that I need to find updated torrents to bring into Bigly. Also had used “Torfeat” which worked great for importing torrent locations. Can I get some help in locating working torrents and or the magnetic link? I use a VPN when ever I’m in Bigly.  I’d also like to learn more about adding files to help support the sharing process. 
Windows 7 V6.1 and 64 bit
BiglyBT Version NumberB2.1.0.0/4 az3

Any posts or screenshots displaying torrent names, search results, subscription names, will be removed without notification, unless they are linux distros.
For bugs, please include the "System" section of the Help->About window, or if you don't have access to the window, include: -->

* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment

**Comment by parg** [comment]
We can only provide support for techincal problems with BiglyBT. Generally if you want to help other downloaders then you simply need to keep things you've downloaded seeding within BiglyBT for as long as possible. This doesn't generally require you to do anything except not remove completed downloads. You may want to consider increasing your target 'share-ratio' under Tools->Options->Queue->Seeding->First Priority to keep things running for longer before they are considered for queueing.
