### ISSUE TITLE
Feature Request: Revert File Location / but Keep New Name Option

### ISSUE THREAD

**Issue by ms52538** [BiglySoftware/BiglyBT#1376]
Hola gents! Hope all is well. This has been a long beta cycle on this release - but you've made some great strides in improving the client, in my opinion. Just keeps getting better! 

Based upon my usage I do have an area that causes some consternation for me in reverting files so I thought I'd send in a feature request and see what you might think. 

Is there a possibility to code the functions of "revert file location" and "revert file location/with copy" to provide an option of retaining a file(s) newly assigned name(s) (that I have changed from the original name) instead of just reverting the name back to the original name within a torrent?

Low priority - I see you have a handful of items in the queue at the moment.

Thanks!
M

**Comment by parg** [comment]
I suppose that would end up being a separate dialog with two check boxes (copy, keep name) - or I suppose a Revert menu with 4 options... How I hate UI work!

**Comment by ms52538** [comment]
LOL, I understand that you do. More features/functions = a more popular and sought-after client (I certainly hope, how anyone can use something else besides this is beyond me). Did you get an invite to the Nato summit?  You all have been hosting a lot of events over there this year. :)

**Comment by parg** [comment]
Haha, gotta cram everything in before we become irrelevant!

B38 has a revert dialog with a 'retain name' option - please test to death as we're close to a release!

**Comment by ms52538** [comment]
Awesome! (and nothing / no one in / from GREAT BRITTAIN is or can become irrelevant!  :)  )
Downloading now. 
Couple of quick things: 
1) You remember that pop-up dialogue box that appears when you are performing multiple rename functions, and you incorporated the "long click hold" on the cancel or ok buttons to stop the process from continuing? I'm noticing when I am attempting to rename multiple WITHIN a torrent (i.e. the Files tab on the lower screen area [General, Tags, Torrent Options/Info, Sources, Peers tabs are all located - the FILES TAB in this case to view files I am mentioning here) and want to stop, that pressing a long click hold on the cancel button is not working some times. I'll focus on where it's happening a bit this afternoon.
2) Question on memory allocation settings for my environment.
I have about 33,000 files associated with about 2,800 torrents that I "FORCE SEED". 
At any given time I am uploading about 8 torrents, on avg, as active to my tracker(2) total.
The files are spread across the disk drives dedicated to collection types. 2 are fast, 1 is slow in  spin.
I have a 16GB PC that I'm running BiglyBT on in Windows 10.
I'm running with a java config of on the Max/Min Heap sizes as both being 4gb,
Max Directory memory size is 256MB (I've tried to set that to 512 in the Java config doc used for emergency recovery but it never sticks, 256MB seems to always work).
Under my performance options I have Enabled disk cache, 64MB of cache applied, not doing anything below 1024. Checkboxes are Perform read-ahead, Cache download data o reduce disk, & Write complete pieces immediately.
Do you have any recommendations that I should potentially change/tweak to improve performance?

**Comment by parg** [comment]
That dialog with the long-press is the one that applies to downloads as a whole (and you get the three options to rename display name, save-path and torrent). Tux also implemented 'hitting escape cancels all subsequent dialogs' (i.e. does the same as the long-press on cancel)

As for the FilesView, the 'quick rename' does suffer from a multitude of dialogs - is this the one you mean?

**Comment by parg** [comment]
Regarding performance, you'll be getting a lot of load from having a lot of force-seeding torrents. In general how active are they? You can enable the 'up idle' column to see when they have last actually uploaded. You could use a Tag to remove the 'force' from seeds that haven't uploaded in a long time automatically. If a peer comes along in the future the queue rules should pick it up and schedule the torrent to seed.

**Comment by ms52538** [comment]
Yes, that is the one I mean. I do my bulk renaming in that area, and often will just do a "Quick Rename" if I'm making only a change to 2-10 files, and that's where I can close 10 dialogue pop up boxes with the long-press on Cancel. 

Testing the Revert File Location with the checkboxes. Looks great thus far - will hammer it in next 24 hours.
You may want to consider changing the text of each so they are a bit simpler to understand:
Box 1 - "Revert File Location and RESTORE Original File Name(s)"
Box 2 - "Revert File Location and RETAIN Current/Existing File Name(s)"

:)  Thank you, by the way, for the fast response on this request!

M

**Comment by hatewesterncivilization** [comment]
Hello, brothers, I'm seeding >3900 torrents in active state. I'm using by the way early-access 14.0 Java beta builds. Having also 16 GB spec PC, and there are 4.7 GB system memory free about. For client grant up kind of >2500 GB memory amount. And client works just fine with those free system memory gap. Have antivirus F-Secure in system. But I've placed Bigly to Ram-disk with backing up and syncing to alternate folder. 

Also having trying standart Java version available for download and it works much worst than early-access one. 

Using .vmoptions file for configure of -xmx setting, so on, max, min granted amount of memory.

**Comment by ms52538** [comment]
I love this new feature. Thank you again! I've used it repeatedly over the past few days on 30 large torrents and have not seen any issues in its function.

**Comment by parg** [comment]
Good to hear!
