### ISSUE TITLE
CPU usage high

### ISSUE THREAD

**Issue by Xuchilbara** [BiglySoftware/BiglyBT#138]
I noticed Bigly uses a lot of CPU when the plugin/network I2P is enabled. The process takes around 4-8 % of CPU (and I have an i7 7700K!) when it is enabled, compared to 0-3 % when it's not.

It wouldn't matter if I wouldn't notice the impact on the OS. Everything gets noticeable slower. In addition, ehen I2P is working, sometimes my system even freezes for some seconds...

This has been like this for a long time. Back then, when I noticed the issues I2P creates, I disabled it. Yesterday I reenabled it to see if it was perfected, better optimized. It behaves all the same.

Bigly also takes **a lot** more time to close when I2P is enabled. It can even cause to close incorrectly if one shuts down the OS right when the GUI closes...

Windows 7 Ultimate x64 SP1.
BiglyBT 1.2.0.0.

**Comment by mppdidi** [comment]
Xuchilbara,
your diagnosis is partially correct. 
Most of the time Antivirus / Security software causes these hangups.
So one thing you could try is to exclude bbt from traffic scanning and / or antivirus scanning.
Of course this is not ideal so ultimately you'll have decide for yourself if you pursue this path.
Regarding the cpu load - i2p does some heavylifting crypto- and network processing all the time, so you cannot lower this any further.
Regarding the closing procedure - please update to the latest version or even better switch to the beta.
