### ISSUE TITLE
Characters not allowed causing initialization error.

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#1399]
Was renaming a file in the download dialog before proceeding.  I usually try to ensure episode titles are added to files.  Example:

ShowName.S01E01.1080p.mp4   Would become
ShowName.S01E01.EpisodeTitle.1080p.mp4

The problem I found was when pasting in the Title from another source.
Example:
"Book 1: Chapter 1: Title" - pasted into the file name creates:
ShowName.S01E01.Book 1: Chapter 1: Title.1080p.mp4
in Biglybt.  And an initialization error when it tries to allocate.

Windows and Mac handle this differently.  [See this page](http://xahlee.info/mswin/allowed_chars_in_file_names.html).  If I try to do that rename in windows file explorer, it shows an error message:
![image](https://user-images.githubusercontent.com/37715552/70671255-66bbde80-1c49-11ea-80bc-9865a2bd94da.png)
and strips the offending characters.  And the rules are probably different for Linux or Mac.

At the moment, when I click OK, Biglybt accepts the file name with the colons. What I would like to see is a message says there are invalid characters and allow the user to correct it.  Or, Strip the characters like windows.

Java 1.8.0_231 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_231

SWT v4922r17, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.2.0.1_B01/4 az3

**Comment by parg** [comment]
BiglyBT makes an effort to substitute illegal characters in filenames in general - see 

https://github.com/BiglySoftware/BiglyBT/blob/master/core/src/com/biglybt/core/util/FileUtil.java

method convertOSSpecificChars

On Windows ':' is supposed to be substituted with an "_" - looks like you might have found a way to avoid this conversion occurring - I'll take a look.

**Comment by parg** [comment]
Just to be clear, exactly where are you performing the renaming?

**Comment by NaPurHab** [comment]
Open Torrent from Edge Browser. Then the Open Torrent Options dialog.  The list of files in the torrent.  If given a file like:
ShowName.S01E01.1080p.mp4

And I had an Episode Title of "Book 1: Chapter 1: Title"
I would either click on the file then the rename button, or press F2. Then edit the filename as follows:
ShowName.S01E01.Book 1: Chapter 1: Title.1080p.mp4

In the SNIP I included above, you can see that Windows File Explorer has removed the colons, while showing the message about them not being allowed.  BiglyBT is allowing them in the Open Torrent dialog. But once I click OK on the Rename it allows it. Then I click the OK to finish the Open Torrent dialog and when it tries to Allocate the file, the error is shown in the status column.

**Comment by parg** [comment]
I'll make it do the same as elsewhere in BiglyBT, rename as required them when added
