### ISSUE TITLE
I'm missing the frog

### ISSUE THREAD

**Issue by ViperCode7** [BiglySoftware/BiglyBT#14]
Was wondering if a better icon would be available in the future.?.. I'm already missing the blue frog on my desktop.

**Comment by TuxPaper** [comment]
haha, we don't want to get into any trademark issues, so anything frog related is out of the question.  Icons and branding are a huge pain in general.

Maybe it will *grow* on you after a few months?  Until then, I'm going to close this issue.

(On the plus side, at least people can pronounce this name ;) )

**Comment by csylvain** [comment]
so avoid using an amphibian as a mascot, that's easy.

but please do adopt a mascot. there is a world of critters out there on the land, in the air, and in the seas. maybe even one worthy of a modest annual donation for conservation efforts. 

it would be better than a bulging waistline with a belt buckle at the last perforation.
