### ISSUE TITLE
Global Max Up/Down Speeds Reset to Defaults After Every App Restart

### ISSUE THREAD

**Issue by Michael-CJ** [BiglySoftware/BiglyBT#1400]
I've been fighting this issue for the past week. I will change the global max up/down to fit my connection and I hit save. The changes will hold until the next time the app starts and those two settings reset to default (125KB down/0 up). No other settings I change will reset to defaults AFAIK, just the global transfer speeds. I have attempted to disable any plugins that might affect this including: Focus, Measurement Lab, Speed Scheduler, uTP Plugin. I do not see any plugin or way to disable "auto-speed" beyond leaving the enabled setting unchecked next to the classic and beta options and setting upload and download limits to fixed under "network details."

java 11.0.5-ea (64 bit)
Ubuntu: 19.10 XFCE (bare metal)
/usr/lib/jvm/java-11-openjdk-amd64
SWT v4924r25, gtk3.24.12, zoom=100, dpi=89
Linux v5.3.0-24-generic, amd64 (64 bit)
B2.2.0.0/4 az3

**Comment by parg** [comment]
Check Tools->Speed Limits->Schedule and Settings to make sure something hadn't become enabled in there.

Not sure where those default values of 125/0 can be coming from.

You could try generating a 'debug.zip' (see help menu) and sending it over to paul@biglybt.com if you want me to take a look

**Comment by Michael-CJ** [comment]
> Check Tools->Speed Limits->Schedule and Settings to make sure something hadn't become enabled in there.
> 
> Not sure where those default values of 125/0 can be coming from.
> 
> You could try generating a 'debug.zip' (see help menu) and sending it over to [paul@biglybt.com](mailto:paul@biglybt.com) if you want me to take a look

Oh that was it actually. I thought having the speed scheduler plugin disabled, those settings would not be in effect. Seems confusing that they are effective with the plugin disabled.

**Comment by parg** [comment]
It is an entirely separate, built in scheduler.
