### ISSUE TITLE
Search wtihin a Tag's View

### ISSUE THREAD

**Issue by ms52538** [BiglySoftware/BiglyBT#1401]
This is more a question:
I've certainly created a lot of TAGs and interact with the views of those tags from my dashboard. One thing I've wondered is specific to the search feature within the tag views: if I enter a search term, then switch to a different tab view, then later return to the tab view where I had performed a search, the search field is still populated from I had used it last. I often forget to clear the value from the search before I leave and switch to a different tab view, and upon return to the initial view - wonder why I'm not seeing what I expect, it is because the old search value is still present. Is this functionality by design with an intent?

**Comment by parg** [comment]
In general I'd say people expect a tab's content to stay the same when they switch away and then back to it, so keeping the search makes sense to me.

**Comment by ms52538** [comment]
- How do you fix deadlock? You hold new elections (or roll out a beta fix). 
- Over here, we have Mariah Carey telling us what she wants for Christmas. Over there you have voters telling you they want a Merry Brexit before Christmas. 
- I think the Scotts Family will be telling the DNA kit makers to ensure they are listed independently from the UK on all future results.  Bah Humbug!

As for the search; here's a thought - I understand your vision for its function. Yet, I also will return to a Tag View and stare at it in confusion for 3-8 seconds wondering why I'm not seeing what I expect to see - hence why I asked. Thinking about this for a bit, I think there can be a win/win for both but you'd have to consider my first suggestion below. Search, to me, is one of the best damn capabilities in the client, especially with RegEx. And when using RegEx the search field turns to a light canary yellow color. 

So a couple of suggestions to improve Search. 1) When Search is not in use, continue to remain the color white that it is. As with RegEx "turned on" (Cntrl + X), the shade of the field changes from white to a light canary yellow as a visual indicator that RegEx is activated and remains such until turned off - perform something similar for when a normal Search is in use and populated; i.e. have it turn a light shade of blue (or some color you choose to code) so it to can be a a "visual' indicator that it is in use or is retaining an active search when the Tag View is left and returned to, just like what RegEx's canary yellow does. Turning the Search field to a shaded color when in use enables a visual indicator that Search is in use. So in short, my suggestion would be to enable a visual indicator that can be caught by the eye that Search is in use in the view. This allows you to cotinue to have the functionality you want - and enables a visual indicator that catches and draws the eye's attention as a reminder to folks like me.  That's my first suggestion.

My second suggestion would be to enable Search to retain a history of most recently used test/words/phrases that have been used (i.e. like 10 or 15, with the most recent at the top closest to the filed, where the user can simply click on an item in the history dropdown. Those items in the list should include RegEx entries that were used in the list of 10 or 15, maybe preceded with an indicator RgE or something OR create colored backgrounds of the terms using light canary yellow for RegEx and light blue for normal queries used in the 10-15 list [think of an excel spreadsheet, column, cell (and each cell has a colored background as to illustrate the colored background suggestion). Or something like this that you may think of that I'm not. 

Let me know what though thinkest :)

**Comment by parg** [comment]
Thanks for the festive chortles, I think :)

2203_B01 has some colour in the search box when active and also I hacked in an existing 'search with history' widget I had hanging around - it doesn't differentiate between regex + plain history but I guess you can just hit ctrl+x again after selecting it. Whadyathink?

**Comment by ms52538** [comment]
I think you just made the holidays a little brighter. Literally! :)
That light blue is a bit weak.  Maybe a dark blue with white lettering? I don't know - but what I do know is that it is in the general target area. :)  I'll tinkering a bith with the history component in the next couple of days and give it a better shake down. Thanks, as always, my friend!

**Comment by parg** [comment]
B02 has a few fixes in the search history, check it out! 

Colour selection is of course possible but I'm currently not feeling enthusiastic enough to get off my arse and look into it :)

**Comment by ms52538** [comment]
Will do. I've had little time with it today but will be on it tonight and tomorrow.
And that is TOTALLY understandable! You do soooo much already - making this a better client day after day.  :)

**Comment by ms52538** [comment]
In regards to accessing the history; walk me through how to facilitate that when you have time, please. I'm hitting Cntrl X and see the field switch to yellow indicating RegEx mode but a subsequent Cntrl X is bringing back to the nromal field and no history. I'm likely doing something wrong?

**Comment by parg** [comment]
History is accumulated when you perform a search and leave the field (e.g. you type in a search of 'mp3' and then leave the field). It is matched against next time you do a search - type in 'm' and a drop down list of previous searches starting with 'm' will appear, keep typing and it will refine. Once the drop down list appears you can use down-arrow to select and entry and hit 'enter' to select it. At this time, if you wanted to make it a 'regex' you would just hit CTRL+x to switch mode.

When in the search field you can hit down arrow to show the history explicitly. You can click on an entry to select it but currently down-arrow doesn't work to navigate the list as focus is grabbed by the table.

**Comment by ms52538** [comment]
Awesome sauce! Oh I like this :)

**Comment by parg** [comment]
B03 has the option to set the active colour - right-click in the table header area (where it shows number of items etc) and select 'Filter' from the context menu

**Comment by ms52538** [comment]
Well.... LOOK at THAT!  Color me IMPRESSED :)   Looks FANTASTIC! 

Thank you, Good Sir.
