### ISSUE TITLE
Question: Filter by path?

### ISSUE THREAD

**Issue by Gatak** [BiglySoftware/BiglyBT#1408]
Is there a way to filter torrent list based on storage path, rather than just file names? For example `D:\Download` or `E:\Other Path\`
![bigybt](https://user-images.githubusercontent.com/1469150/70848957-f98e9000-1e78-11ea-87d2-7b3a06feff8d.png)

```
Java 12.0.1 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4922r17, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.2.0.1_B03/4 az3
```

**Comment by parg** [comment]
No, but you can use the 'save path' column to sort and then at least they will be grouped by save-path

**Comment by TuxPaper** [comment]
Alternatively, you could make a tag with the following constraint:

```
matches(save_path, "^D:\\Download\\.*")
```

**Comment by Gatak** [comment]
Thanks!
