### ISSUE TITLE
Please add a "share ratio" option in the Column strip

### ISSUE THREAD

**Issue by Nikita11790** [BiglySoftware/BiglyBT#1410]

**Comment by parg** [comment]
There is a 'Share Ratio' column - unless you are referring to something else?

**Comment by parg** [comment]
(intermediate mode, either change your Mode under Tools->Options->Mode or open the 'Filters' in the Column Setup dialog (at the bottom) and change your mode there)

**Comment by Nikita11790** [comment]
thanks, sorry I was in default mode not intermediate
