### ISSUE TITLE
Moving file during download breaks playing locally

### ISSUE THREAD

**Issue by tankorsmash** [BiglySoftware/BiglyBT#1413]
```
Java 1.8.0_181 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4757, win32
Windows 10 v10.0, amd64 (64 bit)
B1.6.0.0/4 az3
```

Steps to reproduce:

1. Right click downloading torrent (mine was a folder containing a video file)
2. Content > Move Data Files... > move the file whereever
3. Content > Media Server > Media Server: Play locally
4. VLC Output: `Unidentified codec: VLC could not identify the audio or video codec`

But if you go and view the moved file in explorer, the moved video plays as expected.

Workaround is just opening the file manually, instead of doing it via dropdown.

**Comment by parg** [comment]
Seems to work for me. You're on an old version of BiglyBT, might as well update to 2.2.0.2 and see if thast helps.

**Comment by tankorsmash** [comment]
I'll try that and reopen if it comes up again. Thank you!
