### ISSUE TITLE
Slow to check Trackers

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#1419]
I was using the Availability Button in Open Torrent Dialog. And it stalls on the Trackers.
![image](https://user-images.githubusercontent.com/37715552/71301266-f90b6300-236a-11ea-8018-058d6cc381f5.png)
I timed it and it took 23 minutes to finally check the trackers:
![image](https://user-images.githubusercontent.com/37715552/71301279-18a28b80-236b-11ea-8603-bb2c19895a7e.png)
As you can see the DHT has 0 seeds, but it take a long time to check the trackers.

I have also noticed the same when adding torrents and they take a long time to start.  Even if I Right Click on a tracker in Sources and choose Update Tracker, it does nothing. It used to react quickly, but now no matter how many times I click Update Tracker it doesn't happen.  Eventually it tries the trackers, but it can often take hours.  I would have reported it earlier, but thought it was obvious and would be caught.

See what you make of it.

Java 1.8.0_231 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_231

SWT v4922r17, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.2.0.3_B05/4 az3

**Comment by parg** [comment]
Try unchecking 'manage tracker activation to reduce load' under Tools->Options->Tracker->Client
