### ISSUE TITLE
Feature Request: Add option to keep simple GUI but allow advanced options on right click of torrent 

### ISSUE THREAD

**Issue by Nikita11790** [BiglySoftware/BiglyBT#1422]
If I load up BiglyBT in simple mode but then go to settings and enable advanced mode I can keep the simple Gui but have advanced features(like if I right click on a torrent I can enable super seeding), if I go to advanced mode then restart client I get advanced GUI, is there a way to keep simple Gui? :(

**Comment by parg** [comment]
If by 'advanced mode' you mean the single list of torrents as opposed to the split view then you can switch between them whenever you want by using the icons on the toolbar. Unless you mean something else.

**Comment by Nikita11790** [comment]
Yes but is there a way to unspilt them in advanced mode

**Comment by parg** [comment]
Search for the word 'split' in the options
