### ISSUE TITLE
Error plug-in CountryLocator

### ISSUE THREAD

**Issue by Bavarello** [BiglySoftware/BiglyBT#1423]
![Annotazione 2019-12-21 102415](https://user-images.githubusercontent.com/22433856/71319413-65d34a00-249e-11ea-8367-17fb008a0a1b.png)
<!--
Hello,

**Comment by Bavarello** [comment]
![Annotazione 2019-12-22 094109](https://user-images.githubusercontent.com/22433856/71319482-47218300-249f-11ea-8884-203c52f04b76.png)

**Comment by parg** [comment]
You can't install Vuze plugins directly into BiglyBT - they need to be ported. The supported list is here:

https://plugins.biglybt.com/

**Comment by parg** [comment]
I should mention the features of that plugin are built into BiglyBT via the 'Location Provider' plugin

**Comment by parg** [comment]
Although there's no map :(
