### ISSUE TITLE
Issue with starting/stalling torrents

### ISSUE THREAD

**Issue by ghost** [BiglySoftware/BiglyBT#1424]
* Win 7 & 10
* BiglyBT 2.2.0.2

After metadata is created/downloaded, torrents starts downloading for few seconds ( disc cache? ) then stops, afterwards BiglyBT starts to write torrents to hdd like if Allocate and zero ... option was enabled but its not, with very big files 50GB+ and hdd write speed around 80MB/s it takes 10+ minutes before downloading starts, I never had this problem before neither with vuze or BiglyBT - I recently upgraded connection from 30mb to 150+, other clients doesn't have this behaviour. I want to reduce hdd IO writes as much as possible but, now it looks like it write whole torrent size to hdd before it starts to download or something like that. Append-mode is workaround but I prefer to avoid using it. Its impossible to create whole torrent size 50+ GB on HDD on the fly and immediately starting to download like before?

**Comment by parg** [comment]
Tried enabling sparse mode?

**Comment by stapi23** [comment]
It looks like its similar to append data, at least in both cases it somehow works, are there any disadvantages or issues using any of them or even better any recommended settings that should be turn on or off?
