### ISSUE TITLE
VPN causes 50%+ consistent cpu usage even when no torrents are active

### ISSUE THREAD

**Issue by AlexVores** [BiglySoftware/BiglyBT#1425]
OS version: Microsoft Windows 10 Pro 10.0.17134
BiglyBT version: 2.2.0.2

Consistently high CPU usage (50%+) while running together with Windscribe VPN client (VPN itself keeps low CPU usage) even with 0 active torrents. Disabling VPN drops CPU usage back to normal (but then forced binding stops all connections of course). 
![image](https://user-images.githubusercontent.com/59181763/71381848-55f15e00-25a3-11ea-9bc4-30b8e721868c.png)

Upgraded from Vuze, haven't changed any settings except binding it to VPN socket:
![image](https://user-images.githubusercontent.com/59181763/71381622-3ad21e80-25a2-11ea-9481-0196e3d7a8a5.png)

**Comment by parg** [comment]
Take a look at https://github.com/BiglySoftware/BiglyBT/wiki/Diagnostics
