### ISSUE TITLE
binding IPv6 problem

### ISSUE THREAD

**Issue by afsharsafavi** [BiglySoftware/BiglyBT#1426]
Hello
I have both valid ipv4 and ipv6 on my server (they've been bind directly into server without any NAT or somethings else)
I bind ip in console with this command:
set "Bind IP" "2aXX:XXX::50;4x.x.x.x5" string
set "Plugin.default.pairing.ipv6" "2aXX:XXX::50" string
set "Plugin.default.pairing.local.ipv6" "2aXX:XXX::50" string
But it seems biglybt can't use IPV6. when I run "show nat" commands and "show dht", I can see only my ipv4 and there is no sign of ipv6
How can I add ipv6 to biglybt?

**Comment by parg** [comment]
Enable IPv6 support via 

set "IPV6 Enable Support" true boolean

**Comment by afsharsafavi** [comment]
So there is a problem in "set" or "show option" commands.
When I run those commands, I see default value is 0,int
I run before 
set "IPV6 Enable Support" 1 int
But nothing changed.
Also problem didn't solve with  
set "IPV6 Enable Support" true boolean
with boolean, I see my ipv6 in startup 
BiglyBT started at 24-Dec-20---
Bind IPs not resolved: 1:2:3:4::5
I found and run this command
set "Enforce Bind IP" true boolean (boolean :D instead of int)
but nothing change, there is no sign of ipv6 in "show nat", "show dht"

**Comment by parg** [comment]
I have IPv6 - after 

set "IPV6 Enable Support" true boolean

and a restart I see an IPv6 DHT when I 'show d'

so I'm not sure what your problem is

**Comment by afsharsafavi** [comment]
Hello
I think that I explained everything clearly.
A new problem has been made after your first comment, and my main problem didn't solve.
I try to explain them with more detail:
The new problem is:
Before opening this ticket, I executed this command:
`set "IPV6 Enable Support" 1 int`
And you said you should run this command:
`set "Enforce Bind IP" true boolean`
Means: 1 int => true boolean
And it seems they are different. Your choice (true boolean) is correct and (1 int) doesn't any effect. and it seems Biglybt have different behaviour with "1 int" and "true boolean"
But in comments of Biglybt commands as I see them in "show options" and "set" commands, I see wrong type description for boolean properties. You wrote all of them like this:
Enforce Bind IP is not set. [int, default: 0]

The second problem (the main problem of this thread) that didn't solve completely:
I used your first reply command (with true boolean).
Regardless of before (with 1 int), Now I can see my IPv6 in Biglybt startup message (in the console)
(And that is only changed that happened)
I saw this notice in the startup process of Biglybt:

```
BiglyBT started at 24-Dec-20---
Bind IPs not resolved: 1:2:3:4::5

See Tools->Options->Connection->Advanced Network Settings
(I changed my IPv6 real address for privacy with 1:2:3:4::5)

```
And the result (No ipv6 in Biglybt) is the same as before.
With "1 int" I didn't even get that error.
"show nat" and "show dht" commands output are include only my ipv4.
Additionally, I added my IPv6 to "/etc/hosts" with a random hostname (myip.host) like this:1:2:3:4::5 ( myip.host)
That ipv6 is assigned directly into one of my network interface (Linux), and it's pingable and reachable from other places. 
Also, I checked whether to use or bind it with other programs, and it was OK, but there is a problem with Biglybt.

**Comment by afsharsafavi** [comment]
Also I got this error for some torrents:
Tracker returned an error: Failed - No bind address for IPv6

**Comment by parg** [comment]
what is listed if you type

cfg connection.advanced

for the interfaces available?

**Comment by afsharsafavi** [comment]
The output is included only my IPV4 address:

```
tun1	(tun1)
  tun1[0]	10.0.1.1
lo	(lo)
  lo[0]	127.0.0.1
bond0	(bond0)
  bond0[0]	x.x.x.x1
  bond0[1]	x.x.x.x2
  ...
  bond0[n]	x.x.x.xn
tun0	(tun0)
  tun0[0]	10.0.0.1

```
I assigned my IPv6 addresses on bond0 interface
In this file:
`/etc/sysconfig/network-scripts/ifcfg-bond0`

That included:
`
DEVICE=bond0
  USERCTL=no
  BOOTPROTO=none
  ONBOOT=yes
  IPADDR=x.x.x.x1
  NETMASK=255.255.255.0
  GATEWAY=gateway_ip
  DNS1=dns1_ip
  DNS2=dns1_ip
  BONDING_OPTS="miimon=100 mode=4 xmit_hash_policy=1"
  TYPE=Uknown
  IPV6INIT=yes
  IPV6ADDR=first_IPV6_address
  IPV6_DEFAULTGW=IPV6_gateway
  IPV6ADDR_SECONDARIES="second_IPV6_address/64 \
  third_IPV6_address/64 \
  last_IPV6_address/64"
`

**Comment by afsharsafavi** [comment]
`
│ Boolean     │ "IPV6 Enable Support"                              │ true
│             │ Enable IPv6 support
│ 
│ Boolean     │ "IPV6 Enable Multiple Address Checks"              │ true
│             │ Check for firewall issues when there are multiple global IPv6 addresses
│ 
│ Boolean     │ "IPV6 Prefer Addresses"                            │ true
│             │ Prefer IPv6 addresses when both IPv6 and IPv4 are available

`

**Comment by afsharsafavi** [comment]
I switched Java from openjdk1.8 to openjdk 13.0.1
Now I have these warnings on Biglybt startup that maybe are related to my problem:

`Starting BiglyBT...
Suitable java version found [java = openjdk 13.0.1 2019-10-15]
Using swt/swt-x86_64.jar v4.924
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.biglybt.core.util.spi.AENameServiceJava12 (file:/opt/biglybt/BiglyBT.jar) to field java.net.InetAddress.nameService
WARNING: Please consider reporting this to the maintainers of com.biglybt.core.util.spi.AENameServiceJava12
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
`

**Comment by parg** [comment]
The JDK people are breaking things - nothing to do with IPv6 though.

**Comment by afsharsafavi** [comment]
It is possible to make a fix for detecting IPv6?

**Comment by parg** [comment]
It works fine for me - for some reason Java isn't detecting the IPv6 interface at all, perhaps it is something to do with the way you configured it
