### ISSUE TITLE
question: auto assign to category

### ISSUE THREAD

**Issue by magicmana** [BiglySoftware/BiglyBT#1427]
hello  i'm  would want to know  if is possible to  put a  new torrent  in  a category when i add a   torrent ;  based of the title .
for sample  when i   add a torrent with  "xxx" in title  , the torrent   are added in the "xxx" category , using something like  regex
thanks

**Comment by parg** [comment]
You can set up tags so that they are auto-assigned based on title by using a tag constraint of, say,

matches( name, "xxx" )

What you can't do is set things up to dynamically create tags based on title
