### ISSUE TITLE
Memory uses

### ISSUE THREAD

**Issue by adagsn** [BiglySoftware/BiglyBT#1428]
Since last update on december 2019 the biglybt are using too many RAM and freezing my PC

* OS and version - windows 10
* BiglyBT Version Number 2.0.2.2

**Comment by parg** [comment]
Please see https://github.com/BiglySoftware/BiglyBT/wiki/Performance-Tweaks and  https://github.com/BiglySoftware/BiglyBT/wiki/Diagnostics to try and get some diagnostics

**Comment by adagsn** [comment]
> Please see https://github.com/BiglySoftware/BiglyBT/wiki/Performance-Tweaks and https://github.com/BiglySoftware/BiglyBT/wiki/Diagnostics to try and get some diagnostics

I did that as you said. But doesn't work. And as I said first, the problem starts after last biglybt update. My internet and my PC are both the same.

**Comment by parg** [comment]
What doesn't work? Perhaps you could generate a 'debug.zip' (Help menu, last option) and email it to paul@biglybt.com ?

**Comment by adagsn** [comment]
Sending the debug.

I said doesn’t work change the Max heap memory

De: parg <notifications@github.com>
Enviada em: sexta-feira, 27 de dezembro de 2019 11:16
Para: BiglySoftware/BiglyBT <BiglyBT@noreply.github.com>
Cc: adagsn <adagsn@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [BiglySoftware/BiglyBT] Memory uses (#1428)


What doesn't work? Perhaps you could generate a 'debug.zip' (Help menu, last option) and email it to paul@biglybt.com<mailto:paul@biglybt.com> ?

**Comment by parg** [comment]
Thanks! Could you try this to see if it makes any difference? Go to

Tools->Options->Files

and find the entry named "Attempt to merge incomplete files that are the same size"

This option is selected by default - de-select (uncheck) it and see if things improve - you shouldn't need to restart BiglyBT, just changing the option should be enough to see if it helps.
