### ISSUE TITLE
BiglyBT sending and receiving massive amounts of data in background with no active torrents

### ISSUE THREAD

**Issue by Stepcraft** [BiglySoftware/BiglyBT#1429]
I hope someone can help!

I've been using Vuze for years (don't hate me, I didn't know about BiglyBT). I recently switched to BiglyBT. :) The reason I switched was because Vuze was sending & receiving massive amounts of data in the background even when I had no active torrents. It would start out small (around 3k/sec sent and 10k/sec received) and would slowly increase. After an hour is was at 170k/sec sent and 180k/sec received. It progressively got worse and after 5 hours it would be up to 1.40MB/sec sent and 1.50MB/sec received and it had sent a total of 2.96 GB and received 3.05 GB. It was totally crazy. After 24 hours it had sent and received 100's GB. I found BiglyBT and installed it. I thought the problem was fixed, but unfortunately, it's not. I'm still having the same problem with BiglyBT, but much less data is being sent & received when there are no active torrents. And when I say "no active torrents" I mean there are no torrents even listed in the window. Nothing at all.

I ran a test for 24 hours with BiglyBT and after about 5 hours it had sent 287.8 MB and received 323.8 MB (much better than Vuze which sent 2.96 GB and received 3.05 GB in 5 hours). After 24 hours BiglyBT had sent 26.16 GB and received 27.04 GB. It shouldn't be doing this, right?

FYI: When I installed BiglyBT I had it import my settings from Vuze. I also tested Transmission with no active torrents and after 24 hour it had only sent 44.5 MB (not GB) and received 19.6 MB (not GB).

Can anyone tell me what's going on?

My specs:
iMac 27" / 24 GB / 3.4 GHz Intel i7 / macOS 10.13.6 (64 bit)
Java 1.8.0_231 (64 bit) / BiglyBT B2.2.0.2/4 az3

1st picture below is the starting point after BiglyBT has been run. The 2nd picture is at the 5 hour mark and the 3rd picture is at the 24 hour mark.

Thank you so much!!!

![Avtivity-Monitor-2019-12-22-at-1 25 28-PM](https://user-images.githubusercontent.com/59187451/71498239-66f2d700-2810-11ea-9ec6-d6e596fdd070.jpg)
![Avtivity-Monitor-2019-12-22-at-6 57 54-PM](https://user-images.githubusercontent.com/59187451/71498252-6eb27b80-2810-11ea-9835-48b42f1a8fc0.jpg)
![Avtivity-Monitor-2019-12-23-at-1 15 37-PM](https://user-images.githubusercontent.com/59187451/71498258-72de9900-2810-11ea-8fa3-aef59c0cb7b2.jpg)

**Comment by silverbacknet** [comment]
With in/out being so symmetrical, I wonder if it's just round-tripping through openvpn, without actually going out to your router, or alternately into your router and right back to your system -- if there's a mismatch between one service using the openvpn ip, and another using the clear ip, this could happen. Are you able to see the router egress/ingress stats? Can you further look into the actual packets sent out, such as with Wireshark on the physical interface (not the virtual vpn interface)?

If it actually is real outside traffic, maybe your node is a particularly hot DHT node, or maybe the tracker is turned on and is somehow being heavily used.

**Comment by parg** [comment]
Do you have the I2P Helper plugin installed? If so, uninstall it or disable it and see how that helps

**Comment by Stepcraft** [comment]
Hi Parg,

It looks like removing I2P Helper did the trick. I just ran a test for 31 hours with no active torrents (no torrents at all listed in the window). My total sent was 358.4MB with my total received 568.4MB (my previous similar test was 26.16GB sent and 27.04GB received). Does this new test of 358.4MB sent & 568.4MB received seem normal? It's still quite a bit higher than my Transmission (24 hour test), which was only 44.5MB sent with 19.6MB received.

What exactly is being sent and received when there are no active torrents?

Thank you so much for your help!

![Avtivity Monitor Removed IP2 Test4 (31 hours) 2020-01-05 at 4 30 33 PM (358 4MBs:568 4MBr)](https://user-images.githubusercontent.com/59187451/71839063-2d6f6680-306f-11ea-8a92-db8c6f0d31f0.jpg)

**Comment by parg** [comment]
The I2P plugin does 'what I2P does' - act as a node in the I2P overlay network. With I2P all traffic is routed over tunnels that comprise a number of computers (for anonymity purposes) - this requires participants to forward data on behalf of other nodes. Hence the constant network traffic. You can control how much bandwidth is made available to for such tunnels via the I2P Helper plugin config (share percentage)

**Comment by parg** [comment]
(without I2P there is more DHT activity within BiglyBT than other clients as it runs both the BiglyBT DHT, the mainline DHT (if you have the mlDHT plugin installed) and more DHT features such as swarm discoveries, decentralised chat, subscriptions). If you want to disable all this activity then

1) Disable the DHT (plugins->Distributed DB)
2) Disable the mlDHT plugin if you have it installed

**Comment by Stepcraft** [comment]
Hi Parg,

Does disabling DHT and/or disabling mlDHT effect BiglyBT from connecting to users sharing torrents? Do I need both running? Basically, I don't want to disable anything that would decrease download speed or decrease the number of users I can connect to. I have no problem sharing extra bandwidth with the torrent community if running DHT and/or mlDHT helps the community. 

I greatly appreciate all your help. Your recommendation of removing I2P made a massive difference. 

Thanks again!

**Comment by parg** [comment]
Disabling the DHT/mlDHT prevents decentralised tracking from finding peers for you (and other peers from finding you) so if you can afford the bandwidth they consume it is better to leave them enabled.

cheers!

**Comment by Stepcraft** [comment]
I just realized I never closed out this issue from a year and a half ago. Removing I2P Helper solved my problem. Thanks again!

**Comment by ceresBakalite** [comment]
All of the above was very helpful
