### ISSUE TITLE
BiglyBT does not download in portable mode

### ISSUE THREAD

**Issue by Qwest8K** [BiglySoftware/BiglyBT#1430]
* Windows 7 SP1
* BiglyBT 2.2.0.2

I make a clean installation of the program. Then I add a line **"-Dazureus.portable.enable=true"** to the file **"BiglyBT.exe.vmoptions"** for enable portable mode. And after that, the program stop downloading files - it connects to the trackers and finds seeds, but they status is forever **"Waiting for handshake"** and then they gradually disconnect and I do not receive ever a byte from them.

**Comment by parg** [comment]
Unlikely to be anything to do with that flag.
