### ISSUE TITLE
Tag buttons in library disappeared

### ISSUE THREAD

**Issue by PrototypeZero** [BiglySoftware/BiglyBT#1431]
In latest beta the tag button in the library have disappeared, despite toggling on/off in options or right click/show no tags appear in the library area as they used to.

p.s. Seems its something to do with the "is filter" flag, if "show only tags marked as filters" option is enabled then the expected (marked as filter) tag buttons are shown.  If however you deselect the option then no tag buttons are shown regardless of tag settings.

**Comment by parg** [comment]
Tools->Options->Interface->Tags->Library->Only show Tags marked as filters
