### ISSUE TITLE
Can no longer transcode

### ISSUE THREAD

**Issue by orfeocookie** [BiglySoftware/BiglyBT#1437]
I recently upgraded BiglyBT to version 2.2.0.2.

I've just discovered that I cannot transcode any more. Either for iTunes or for my LG television. In both cases the operation aborts after a few seconds. The error message is "Transcode failed. Operation aborted."

It says to read the transcode log for further details. My first problem is that I have no idea where the transcode log even is. 

Any advice gratefully received as the transcoding function is a fantastic feature that makes my life much easier.

**Comment by orfeocookie** [comment]
Apologies, I've spoken too soon.

It turns out I can in fact still transcode some files that I know I've previously transcoded. They still work. So it is not a general issue but a file-specific one. I seem to have stumbled across files that refuse to transcode.

But I've no idea why. Perhaps this transcode log I can't find would help explain why some .mkv files are perfectly happy and others are not.

**Comment by parg** [comment]
Take a look in the 'logs' folder for BiglyBTTranscoder_1.log (and .._2.log)

**Comment by orfeocookie** [comment]
> 
> 
> Take a look in the 'logs' folder for BiglyBTTranscoder_1.log (and .._2.log)

Um, I can't find a logs folder. I can go Tools - Plugins - Log views - BiglyBTTranscoder, but all that got me was some logging from the last 2 minutes since I opened up BiglyBT.

I then went into the Options menu and logging was not enabled, so presumably that is why I don't have a logs folder?

Anyway, when I tried to transcode one of the questionable files again, the in-program log spat out a huge amount of material.

The first part of the failure message was:

[12:04:58] Transcode failed: Operation aborted, Failed 
(matched at least once : false,final line seen : false, exit code : 1,partial file : false)

Another line that stood out:

[matroska @ 00388f70]Unknown/unsupported CodecID V_MPEGH/ISO/HEVC.

Towards the end there was also this, suggesting the mkv file has a picture packaged inside it?

Stream #0.3: Attachment: mjpeg
    Metadata:
      filename        : cover.jpg
swScaler: Unknown format is not supported as input pixel format
Cannot get resampling context

**Comment by parg** [comment]
What OS are you on and also exactly what transcode profiles are you using? Some things were updated to support 'newer' codecs (such as hevc) but only for a limited set of profiles - the intent is to update others but as there are a lot I would prefer to only do so for those actively being used.

**Comment by orfeocookie** [comment]
I'm on Windows 7. The main/preferred profile I'm trying to use is for iTunes, and for playing on an Apple TV. I'm actually using a profile labelled "Apple TV 3" because that appears to be the most recent one, but in fact I have an Apple TV 4K.

I was previously using a different profile but if the Apple TV one works then for me personally that would be the most convenient one in any case. It has better controls for viewing the results than my LG television does.

**Comment by parg** [comment]
That profile has been updated - however I think I can see an issue with the updating of the transcoder plugin - I'll take a look

**Comment by parg** [comment]
Please restart and update to the 'BiglyBT Transcoder Plugin' version 2.0 - see if that helps.

**Comment by orfeocookie** [comment]
The updated version didn't work on the file I just tried. I did get different errors in the log though. Here's the part that seems most relevant:

x264 [error]: main profile doesn't support a bit depth of 10
[libx264 @ 0060fc40] Error setting profile main.
[libx264 @ 0060fc40] Possible profiles: baseline main high high10 high422 high444
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
[aac @ 005c2d80] Qavg: 65536.000
[aac @ 005c2d80] 2 frames left in the queue on closing
Conversion failed!

**Comment by parg** [comment]
I've tried a few h265 10-bit encodes and can't manage to reproduce your error - any chance you could send me a link to something I can test with? If so please email to paul@biglybt.com - thanks!

**Comment by orfeocookie** [comment]
Okay.

I've discovered a workaround. There's a version of the VLC player for Apple TV, and it has a very nice system for transmitting files from the PC to the Apple TV device which so far has worked perfectly for the files I was having trouble transcoding.

So rather than taking up more of your time I might just use whichever of the methods works. I'll come back if there's anything I get COMPLETELY stuck with!

Thanks very much for your time and effort.

**Comment by parg** [comment]
Glad you found a workaround - it'd still be nice to figure out the issue so other users don't encounter it but no problem!
