### ISSUE TITLE
2.2.0.2 "Progress" column has font that is too small

### ISSUE THREAD

**Issue by TheBUCH** [BiglySoftware/BiglyBT#1438]
The font is barely readable, very unusable.
![image](https://user-images.githubusercontent.com/27789215/71648029-a38a6b00-2d07-11ea-836b-b26d12013437.png)

**Comment by o0nd7ots** [comment]
@parg It is still small but I think we can close this

**Comment by parg** [comment]
Closing as nothing's going to happen here, re-open if so desired.
