### ISSUE TITLE
Rename changed to worse

### ISSUE THREAD

**Issue by Xuchilbara** [BiglySoftware/BiglyBT#144]
I noticed a recent change I find unnecessary and inconvenient.

Before, renaming a torrent (all the files, not only the *.torrent) was instant because only the name in the filesystem was changed, as it should be when we are talking about the same device (HDD in this case).

Now everytime I try to rename, it says “Moving 0%”, and it takes a while to finish depending on the size. I noticed it creates a copy, then deletes the original.

This, besides having to wait for it to finish minutes or even hours (for really big files), which is annoying and a waste of time (and seeding time), creates severe fragmentation, of course. I checked with Defraggler.

Perhaps the change was made to make the renaming safer or something, but I really find it to be a regression. It isn't even safer, as any changes in the original files or Bigly while moving can cause severe undesired effects. Not to talk about possible bad sectors or other flaws the device could have on the new location...

Windows 7 Ultimate x64 SP1.
BiglyBT 1.2.0.0.

**Comment by parg** [comment]
Join the beta program please - Help menu, Beta Program - a fix in this area should help

**Comment by TuxPaper** [comment]
Closing, over a year old and probably fixed
