### ISSUE TITLE
Torrents will not open in Bigly

### ISSUE THREAD

**Issue by carvermon** [BiglySoftware/BiglyBT#1440]
After a forced Beta update tonight (that is another, ongoing issue - Bigly will shut down on its own apparently to install Beta updates but does not automatically restart), once I have downloaded a torrent it will not open/appear in the Bigly app. 

Edit: Just found that I CAN add a torrent/file by using the "Open Torrents" button at the top left of Bigly and using the Add Files button (which I had never before used), but still not as I usually do which is to download a torrent, which then (and still does) open a Firefox dialog window asking what to do with the torrent, but the Bigly options window which usually pops up next does not appear.

Java 1.8.0_231 (64 bit)
  Oracle Corporation
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home

SWT v4928r15, cocoa, zoom=100, dpi=72
Mac OS X v10.11.6, x86_64 (64 bit)
B2.2.0.3_B08/4 az3

**Comment by parg** [comment]
Does Firefox still give you an option to 'open it in BiglyBT'? Maybe it was a Firefox update that broke things, not a BiglyBT one - nothing has changed in this area in recent betas.

**Comment by carvermon** [comment]
Thanks for the response. Yes, the Firefox popup asks if I should open with Bigly (my default), but after choosing that I do not get the usual Bigly options popup, it just brings the app window to the front but the torrent is not added. This started right after the app quit and installed 2.2.0.3_B08 tonight. I had chosen to update later, but as mentioned, Bigly has been quitting on its own recently and failing to restart on its own.

**Comment by carvermon** [comment]
My Firefox is 71.0, but I believe it has been a few weeks since it updated.

**Comment by parg** [comment]
I just installed 71.0 on Catalina 10.15.2 and things worked fine. Is it possible that your BiglyBT installation doesn't have access to the 'Downloads' directory that Firefox is using? Catalina introduced a level of privacy controls that have caused me issues regarding folder access.

**Comment by carvermon** [comment]
I am still on os 10.11.6
Don't know how to check Bigly's access to directory. Just looked in Bigly preferences (intermediate mode) and did not find a setting for that. All I know is that is was working as it should until the 2.2.0.3_B08 update.

**Comment by parg** [comment]
All I know is that the changes in B08 are listed here - https://www.tumblr.com/blog/biglybt and consist of the changes linked from that blog entry - none of these have anything to do with how Firefox passes torrent file information to BiglyBT.

**Comment by carvermon** [comment]
Well, thanks for looking into this. Guess I'll continue to use the Add Files feature for now, and maybe the issue will eventually disappear as mysteriously as it appeared.

All the best for your new year!

**Comment by parg** [comment]
We can hope, and thanks! :)

**Comment by carvermon** [comment]
Just updated to B09 and the download options window has reappeared! Also after clicking restart to install the update, Bigly actually restarted (which it had not been doing recently - it would quit but I would have to manually open it again). :)

**Comment by parg** [comment]
No idea why, let's hope it stays that way!

**Comment by MarkJeronimus** [comment]
I started using biglybt (2.2.0.2), and the exact issue as described is plaguing me, but only sometimes.

I traced the cause being spaces in the torrent filename.

I see this if I run biglybt in a console:
```
[alert] Alert:3:Failed to access torrent file '[pyroneko]'. Ensure sufficient temporary file space available (check browser cache usage).
[alert] Alert:3:Failed to access torrent file 'Darling'. Ensure sufficient temporary file space available (check browser cache usage).
[alert] Alert:3:Failed to access torrent file 'in'. Ensure sufficient temporary file space available (check browser cache usage).
[alert] Alert:3:Failed to access torrent file 'the'. Ensure sufficient temporary file space available (check browser cache usage).
[alert] Alert:3:Failed to access torrent file 'FranXX'. Ensure sufficient temporary file space available (check browser cache usage).
[alert] Alert:3:Failed to access torrent file '(BD'. Ensure sufficient temporary file space available (check browser cache usage).
[alert] Alert:3:Failed to access torrent file '810p)-8.torrent'. Ensure sufficient temporary file space available (check browser cache usage).
```

This is a double bug as I expect (as a user) to see error messages for "incorrect" use.
