### ISSUE TITLE
set specific settings via "set" commands

### ISSUE THREAD

**Issue by EnorMOZ** [BiglySoftware/BiglyBT#1441]
How do you set "idle-seeding-limit-enabled", "SeedRatioLimited", and "idle-seeding-limit" via the set command ?

**Comment by parg** [comment]
Did you figure it out? Not sure what exactly what the config values you want to set are but a good place to start is 

https://github.com/BiglySoftware/BiglyBT/blob/master/core/src/com/biglybt/core/config/ConfigKeys.java
