### ISSUE TITLE
Magnet link not working

### ISSUE THREAD

**Issue by iorinoe** [BiglySoftware/BiglyBT#1442]
magnet link can't download the .torrnet information in BiglyBT,but magnet link can work good and fast in other clients, like qbittorrent.
I tested different links,most of them are not available, a few popular magnet link can be downloaded but very slow, wait about 5 minutes.
The way I have tried:
Magnet URI Handler set Public IP network as 'default networks' ,DHT enabled, firewall disable,updated tracker list.

Or which option allows me to use a proxy to download the Magnet link?

* OS windows 10
* BiglyBT Version 2.1
* For *nix: Desktop Environment

**Comment by parg** [comment]
Update to BiglyBT 2.2 - it has the mlDHT plugin bundled by default which might help

**Comment by iorinoe** [comment]
> Update to BiglyBT 2.2 - it has the mlDHT plugin bundled by default which might help

great!updated 2.2 and updated plugin,It's solved.

**Comment by parg** [comment]
Great!
