### ISSUE TITLE
Memory leak - BiglyBT taking up all my RAM

### ISSUE THREAD

**Issue by j03bj03** [BiglySoftware/BiglyBT#1443]
Hello!

Windows 7 Ultimate, 8GB RAM
BiglyBT 2.2.0.2
Java 1.8.0_202 (64 bit)

I switched to BiglyBT 2 weeks ago because of qbittorrent crashing too often. I have to say that I like that it looks fast, robust and stable... Well at least it did until 3 days ago.

THE PROBLEM:

While running, BiglyBT will, after a while, for an unknown reason, start taking up all the available RAM on the system EVEN THOUGH the process only shows around 500MB RAM usage. If I go to the performance tab of the task manager, I'll see all my 8GB are full.

This seems to happen after a while that the program is running. If I close / logoff, then start again, it will eat the RAM right away even though the torrents are not transfering, like if there was a ghost process still running from the last session. The only solution is to reboot, and then after a variable while (depending on how much transfer happens), it will start eating up all the RAM again.

A point worth noting is that I get error messages from BiglyBT telling me that the memory will soon be full and that the program will stop working once the memory is full.

I love the program, and I don't care "tweaking down" some settings to get rid of this problem. Is there a way I can just put an upper bound on memory usage (TOTAL memory usage, not the actual memory the process is using, which is very decent, around 400-600MB).

Thanks a lot!

**Comment by parg** [comment]
If the BIglyBT process is only showing 500MB then it isn't BiglyBT that is directly grabbing memory - are you sure it isn't just file system cache?

Take a look at 

https://github.com/BiglySoftware/BiglyBT/wiki/Performance-Tweaks

and check out the bit about the thread_1.log (and thread_2.log) that shows some more details about memory usage.

**Comment by parg** [comment]
(you need to join the Beta program to get the thread logs, see the Help menu for an option to do so)

**Comment by j03bj03** [comment]
Thank you very much for fast answer!

Will read the link when I have a bit of time and will post back here after. Thanks1

**Comment by j03bj03** [comment]
Hello!

It was indeed a file system cache issue. After a bit of research, I found that we can download a software to control the min / max file system cache size in Windows 7 (and maybe for other versions). Even from Windows website, they say this is not built-in the OS and suggest this method.

Following link is the first post I read from another person having the exact same issue with detailed solution. The link to software doesn't seem to work anymore, but I'll post it below.

[https://forum.vuze.com/Thread-VUZE-eating-all-RAM-slowing-the-PC-fixing-a-memory-leak-or-incorrect-settings](https://forum.vuze.com/Thread-VUZE-eating-all-RAM-slowing-the-PC-fixing-a-memory-leak-or-incorrect-settings)

Link from where to download the software (even suggested by Microsoft themselves): 

[https://www.softpedia.com/get/System/System-Miscellaneous/SetSystemFileCacheSize.shtml](https://www.softpedia.com/get/System/System-Miscellaneous/SetSystemFileCacheSize.shtml)
(If for some reason, you are redirected to the website's home page, just do a search for "setsystemfilecachesize")

Two links on Microsoft's website discussing this issue:

[https://support.microsoft.com/en-ca/help/976618/you-experience-performance-issues-in-applications-and-services-when-th](https://support.microsoft.com/en-ca/help/976618/you-experience-performance-issues-in-applications-and-services-when-th)
[https://social.technet.microsoft.com/wiki/contents/articles/6925.how-to-prevent-filecache-from-eating-up-all-the-ram.aspx?Sort=MostUseful&PageIndex=1](https://social.technet.microsoft.com/wiki/contents/articles/6925.how-to-prevent-filecache-from-eating-up-all-the-ram.aspx?Sort=MostUseful&PageIndex=1)

Thanks for fast help. So far, I really like the client.

**Comment by parg** [comment]
Nice, thanks for the research!

**Comment by Xyrio** [comment]
fyi: i have this problem too and i notices that: when the torrent is queued, paused or stopped then the memory goes down immediately.

a new setting could be added, that does whatever queuing does internally at certain intervals to prevent it from building up too much.

**Comment by rafi-d** [comment]
Definitely a workaround, to cover for Windows bad caching- clearing.

I propose to leave the client "alone" and take care of Windows directly, by periodically (by task scheduler) using some ram cleaning app - would be much better and "cleaner". No one likes his P2P connections to be randomly & intentionally disconnecting... :)

**Comment by Xyrio** [comment]
nice. 
with that i found more:
- currently total cached amount can be seen in windows task manager called "in Cache" or "Cached"..
- sysinternals RAMMap can view mapped file standby size and manually reset from menu: Empty -> Empty Standby List
- EmptyStanbyList.exe (console): frees almost as much as with RAMMap
- sysinternals sync (console): does only empty a little not as much as with RAMMap

https://superuser.com/questions/1362024/how-to-programmatically-clear-buffers-and-caches-in-windows
source code c#: https://stackoverflow.com/questions/12841845/clear-the-windows-7-standby-memory-programmatically

**Comment by jmakov** [comment]
Had just 16GB of RAM being cleared after a Week of use. This is becoming ridiculous.

**Comment by rafi-d** [comment]
> 
> 
> Had just 16GB of RAM being cleared after a Week of use. This is becoming ridiculous.

It's a Windows cache management related side-effect ... 
Try with this (reducing memory priority, so to clean the cache more often):

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\<exe name>]
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\<exe name>\PerfOptions]"PagePriority"=dword:00000001

**Comment by jmakov** [comment]
> > Had just 16GB of RAM being cleared after a Week of use. This is becoming ridiculous.
> 
> It's a Windows cache management related side-effect ...
> Try with this (reducing memory priority, so to remove from the cache more often):
> 
> [HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options<exe name>]
> [HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options<exe name>\PerfOptions]"PagePriority"=dword:00000001

Thanks for the quick reply! The problem occurs on Ubuntu 21.04 with latest BiglyBT (2.8.0.0). Tried disabling I2P plugin, no difference.
