### ISSUE TITLE
Question & Possible Bug on Rename

### ISSUE THREAD

**Issue by ms52538** [BiglySoftware/BiglyBT#1446]
Hey gents! Hope the New Year is off to a good start for you.

Question:
Pertaining to Tag Groups; I have tag groups that I had used and then decided to delete the tags associated with the Tag Group. When all tags within the group are deleted, the group disappears. Not to be seen again in that area. However, the group names still appear in the Column Setup Pop-Out Window in the drop down list for all possible columns to be placed into a view. How do I get rid of the Groups permanently so they no longer appear anywhere, including the Column Setup Pop-Out Window?

Possible Bug:
When I have two separate torrents that have a common file, I will link one torrent to the other's existing file so that it is shared (I have that option turned on in the Options area). Ok, so when I go to perform a bulk rename of files on the first torrent that shares one of those file with another active torrent, the application seems to bugger out and will not perform the rename. No errors appear - but it's clear the rename process stopped and said file(s) do not get renamed. With that said, the gui then gets really buggy and I cannot perform a rename on the TORRENT name. The pop-out box does appear but when i attempt to select text or hit the tab key on my keyboard the gui jumps all over the place and wont let me select text. The only way to overcome this is to either restart the client or to perform a bulk-batch rename instead - but the quick rename pop up box wont work due to the bug. FYI.  

Low priority! :)

**Comment by parg** [comment]
Not such a bad year so far, hope you're enjoying it!

Regarding your question, a reboot of the client will remove those tag columns associated with deleted tag groups - are you seeing them persisted anywhere else?

As for the bug, that sounds really weird! When you say you 'perform a bulk rename of the files on the first torrent' how exactly are you doing this? Just so I can try and reproduce it!

cheers

**Comment by ms52538** [comment]
I meant "Batch Rename", not Bulk, sorry for the confusion on that.  So I'm opening the batch rename process on a torrent's files (lower 3rd screen section of the client in advanced mode). When I'm experiencing is that if a file within the torrent is shared in its location to another torrent in my collection, I would not know that simply by looking at the screen. But I'm attempting to clean up file names and extensions, so I use the batch rename process. The process fails, it seems, when it attempts to rename the file which is shared to another torrent elsewhere in my collection. And at the same time, the gui bug starts. Now what is odd is, (and this is new info for you), If I restrart the client, I can repeart the bug process and the batch rename fail. If I restart the client again, and go to that specific file, and attempt to perform a quick rename of it, the rename works. The bug is associated to the batch rename process specifically, it seems, in this scenario. Let me know if you need more info and I'll trace my steps and detail them to help out.

In regards to those tag groups, no, they do not disappear after a client reboot, they are remaining persistent specifically in the Colums Setup Pop-Out Box Drop down list on the left hand side where I can scrol and select which columns I would like added to my view. I raise this simply because it junks things up a bit in there with them remaining persistent.  On this as well, let me know if you need more info and I'll detail my steps.

Thanks Compadre'!

**Comment by parg** [comment]
Hmm! I tested with the tag group thing and they vanished on restart! Are you sure the tag groups are completely empty and don't have non-visible members? Easy way to check is to go to View->Tags Overview and enable the 'Group' column.

**Comment by ms52538** [comment]
Ah, ok, just checked, deleted, and correctly they are not appearing any longer in the Colummn pop out window. :)  Groovy!!  Thank you!

**Comment by parg** [comment]
So I tried to reproduce your batch-rename bug

Torrent 1:
    f1
    f2
    f3

Torrent 2:
    f4
    f5
    f6 -> f1

If they are both active (seeding) and I try to rename f1 (or f6) then the process fails with an error saying 'failed to rename/retarget'  and things are left as they are.

If one of them isn't running (queued/stopped) and I do the batch rename then the process works but next time I start the other torrent it goes into an error state (data file missing) - as expected.

:(
