### ISSUE TITLE
Deleted files Can't be controlled?

### ISSUE THREAD

**Issue by wernerbw** [BiglySoftware/BiglyBT#1453]
When deleting a file from 'Progress' column, can't control where this 'garbage data will go'...It still downloads (need to be able to at least control where it will be downloaded to...

![Progress](https://user-images.githubusercontent.com/14228128/72451656-43c1a480-378a-11ea-846c-1fe13b9d06c5.png)

How can I control where this 'garbage/deleted data goes?'  WOULD REALLY LIKE THE FILE TAB RETURNED TO THE DETAILS PAGE...WITH ALL CONTROLS IT HAD. Thanks.

Thanks.
Bill

Using latest version BiglyBT (2.2.0.2) on Win 7 x64.

**Comment by parg** [comment]
The File tab still exists in the detailed view - perhaps you removed it? Right-click on the right of the tab header area (to the right of 'general', 'tags', 'options' etc and a context menu will appear to show removed tabs.

Not sure what you mean when you say that the garbage/deleted file still downloads. It will be necessary to download any initial and final parts of the file that share data with pieces of other files but that will be a maximum of 2*piece-size of the download. As for the location, that is in the same place as other files in the download.

**Comment by wernerbw** [comment]
Yeah, just figured out how to restore files tab; fixed issue... Thanks.  Great software.

Bill

**Comment by parg** [comment]
Thanks!
