### ISSUE TITLE
The latest beta removed my tags

### ISSUE THREAD

**Issue by brazenvoid** [BiglySoftware/BiglyBT#1454]
Well the new update has clean slated my tags. They can't be restored even from the backups. Just informing, I know I will have to remake the db nonetheless.

* W10 x64 1909
* v2.2.0.3 Beta 12

**Comment by parg** [comment]
So they have vanished from the Tags Overview, not just the sidebar? The Tag setup is completely stored in 'tag.config' - nothing changed regarding Tags in B12 so you really should just be able to replace that file from a backup to get them back (although their visibility in the sidebar might not recover - you'd have to do that bit by hand)

**Comment by brazenvoid** [comment]
Its fine, fortunately I had few torrents this time around so redefining them wasn't a big hassle.
