### ISSUE TITLE
Show my torrent download pieces status on "peers" page

### ISSUE THREAD

**Issue by david-bakin** [BiglySoftware/BiglyBT#1455]
v2.2.0.3.B12

Feature idea:  You can see your torrent's pieces-downloaded graphically on the general tab for the torrent - but not on the peers tab.  Why not?  I'd frequently like to see it right there at the top of the list of peers  or, maybe, since I always keep the peers list sorted in '%' order - right at the proper location sort-wise ...

**Comment by parg** [comment]
B13 has an option to show the 'local peer' in the PeersView (checkbox in the area at the top of the view) - tell me how that looks

**Comment by david-bakin** [comment]
Excellent! Only suggestion I could make - and it's really low priority - would be to highlight the local peer somehow (because in my case it is displayed using the external ip which I couldn't care less about).  Anything at all - different color for the graphical pieces displayed, asterisk after the IP ... anything.  But nothing to do unless you're at a loose end.  Thanks for the quick update!

**Comment by parg** [comment]
The 'Client Name' starts with 'Local' - also, if you enable the 'LAN' column then the row will be shown in blue as it is marked as 'LAN local'

**Comment by parg** [comment]
(and it has a 'Source' of 'Local')

**Comment by parg** [comment]
Actually I'll make it faded green as long as you have the 'Client' column enabled (row colours are driven by columns in case you wonder why)

**Comment by david-bakin** [comment]
BTW I'm totally happy with this, thanks! 

Don't know the etiquette of closing resolved issues in this repo.  Do you do it or do I?

**Comment by parg** [comment]
I tend to leave them open and let the raiser close when happy, feel free!

**Comment by david-bakin** [comment]
Satisfied!
