### ISSUE TITLE
BiglyBT 2.2.0.2 hangs/freezes intermittently when uTorrent is also running

### ISSUE THREAD

**Issue by SUCM** [BiglySoftware/BiglyBT#1457]
not sure why, but when there is a uTorrent running in parallel (using its own separate ports and HDD) to Bigly, Bigly GUI hangs/freezes quite often for 3-10 second. this happens when I try to witch to Bigly Windows, clicking anywhere on Bigly GUI, just mouse scrolling or right click on a torrent

at this point I have no idea what could have triggered/caused it except that UT running is required to see this issue, but UT is consuming very little system resources ex. 3% cpu and less than 400MB RAM, while Bigly consumes way more resource (9% cpu and ~1.8GB RAM). both have active torrents, but haven't been downloading/uploading except for the (Tor&I2P) overhead for hours

Java 1.8.0_181 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_181

SWT v4922r17, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.2.0.2/4 az3

**Comment by parg** [comment]
Disable I2P then (seeing as you seem to be comparing uTorrent and BiglyBT)

**Comment by SUCM** [comment]
curious as to why you had suspected I2P causing Bigly GUI to hang/freeze?

**Comment by SUCM** [comment]
in any case, restarted Bigly after disabled I2P and hang/freeze still happens when UT and Bigly are both running

**Comment by parg** [comment]
My point was that you are compairing apples and oranges

**Comment by SUCM** [comment]
I was saying if I have both running, then Bigly would freeze then unfreeze frequently. not sure about the comparing apples and oranges part. was suspecting some conflict or contention between Bigly and UT.

anyways, this seems to be something with disk cache or DNS. issue hasn't show up after tuned disk cache on both and changed to CF DNS+wipe existing DNS cache. wonder if there is any value to do DNS over secure connection if this was due to DNS

**Comment by SUCM** [comment]
this may have something to do with 2.2.0.2 itself. despite having JAVA11 installed and detected with current running Bigly. running 2.2.0.2 installer always forcefully downloads a copy of jre from Vuze website and put that in Bigly's installation directory :\Program Files\BiglyBT\jre to use, then this freezing nightmare starts whenever uTorrent is also running. might be DNS or network resource fighting or something related to network behaviour introduced when both are running

after I delete that crappy jre @ :Program Files\BiglyBT\jre to force Bigly use the installed JAVA11, random freeze issue went away and never show up for more than 2 weeks so far. this also seems to be causing some of the freeze issues mentioned in #1436 for some corner cases torrent

perhaps the default Bigly forced/preferred JRE doesn't play well with Windows 10

**Comment by SUCM** [comment]
forgot to mention that today I tried to run 2.2.0.2 installer again to get that Bigly preferred jre and random freeze issue started showing up in less than 30 seconds when uTorrent is also running. I re-launch Bigly after delete Bigly's jre and this random freeze went away again
