### ISSUE TITLE
Time to moving to Ai auto-repair system within of Bigly

### ISSUE THREAD

**Issue by hatewesterncivilization** [BiglySoftware/BiglyBT#1459]
I mean in-place automatic repair any torrent become broken in the list. 

I often facing with those situations. So, every time I got manually do of re-adding torrent to client. 

I think, absolutely must-have thing. Now only devs can or can't support this innovation in forward movements of Bigly developing.

**Comment by o0nd7ots** [comment]
@parg maybe close?

**Comment by parg** [comment]
Closing as nothing's going to happen here, re-open if so desired.
