### ISSUE TITLE
Feature Request:  on Mac if there is a java version newer then 8 in path use the java version in  path

### ISSUE THREAD

**Issue by ghost** [BiglySoftware/BiglyBT#1460]
im on Mac OS latest. I have java 13 in path but biglybt start up with java 8

**Comment by TuxPaper** [comment]
install4j handles the logic of which Java to choose.  If you want to fiddle around, there's a suspicious file at `/Applications/BiglyBT/.install4j/pref_jre.cfg` which contains the JRE it's going to use.  I'm not sure if it supports a list of paths, or how it really works.  In the past, we were able to erase the whole jre in `.install4j` and have it use the System one, but I'm not sure if that works nowadays (ie. removing jre.bundle might cause it to use system).  There's also other config files in there that might be worth playing with.  Let us know if you get anywhere with them :)
