### ISSUE TITLE
Start magnet -> find and load torrent file -> stuck on "Metadata download" forever

### ISSUE THREAD

**Issue by silverbacknet** [BiglySoftware/BiglyBT#1462]
Resolving an unresolved magnet link with a torrent file doesn't work, in fact it hangs indefinitely until the entry is deleted. Only then can the torrent be added properly.

For some reason it also says it's seeding and counting up seeing time.

![Screenshot](https://user-images.githubusercontent.com/1977016/72715952-4889ae00-3b26-11ea-8945-ae9f4d04e00b.png)

**Comment by parg** [comment]
It'll be fixed next beta, thanks
