### ISSUE TITLE
Math overflow in Share Ratio display, and possibly calculation itself

### ISSUE THREAD

**Issue by DonnyDDEV** [BiglySoftware/BiglyBT#1464]
It appears there is a math overflow in that when the calculated Share Ratio gets to some relativity large value, it reverts to what is displayed as an ever increasing negative number (moving towards zero).

Could be critical if this is more than just a display issue, like its in the calculation and is used elsewhere to drive actions. I have not confirmed this to be the case.

sample:

![Capture](https://user-images.githubusercontent.com/51059973/72752480-22402e80-3b77-11ea-9952-6adcbcaf432c.JPG)

Java 1.8.0_231 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_231

SWT v4922r17, win32, zoom=100, dpi=96
Windows 7 v6.1, amd64 (64 bit)
B2.2.0.2/4 az3

Thank you
Donny

**Comment by parg** [comment]
Oops :) It will cause issues if you have, say, a target share ratio to stop a download at. Having said that, if you did then the download would have been stopped long before the overflow occurred...

**Comment by parg** [comment]
Fixed next beta, please keep a look out for any similar issues!
