### ISSUE TITLE
The I2P Helper plugin is not installable except by pasting an I2P hostname in the search box

### ISSUE THREAD

**Issue by interfect** [BiglySoftware/BiglyBT#1465]
Java 11.0.5 (64 bit)
  Private Build
/usr/lib/jvm/java-11-openjdk-amd64

SWT v4924r25, gtk/3.22.30, zoom=100, dpi=96
Linux v4.15.0-74-generic, amd64 (64 bit)
B2.2.0.2/4 az3

I'm not able to easily find the I2P Helper plugin or get it to install. I can turn on "I2P network" in the "Networks" submenu for a torrent, but there's no "I2P Helper Plugin" in the uninstallation wizard, and there's no entry for it on https://plugins.biglybt.com/. I was under the impression that if I turned on the I2P network for a torrent, the plugin would be automatically downloaded, but that doesn't seem to be happening.

Meanwhile, Vuze appears to have a page for their I2P plugin: https://plugins.vuze.com/details/azneti2phelper

The way I finally got it to install was to paste Vuze's I2P test torrent URL, `http://xdwlfjmvtw7awr6n5y3cxx64abid23pibyol3kd5hrjia64vpfba.b32.i2p/torrents/Azureus5.7.5.0.jar.torrent?38BAAB3B884A477EF6203C5C2374EDA6F4233780`, into the "Find Torrents" box.

**Comment by interfect** [comment]
No, I don't see the plugin on that page. What is it supposed to be between?

January 21, 2020 3:47 AM, "parg" <notifications@github.com (mailto:notifications@github.com?to=%22parg%22%20<notifications@github.com>)> wrote:
	Hmm, 'I2P Helper' is listed on https://plugins.biglybt.com/ (https://plugins.biglybt.com/), is it not showing for you?

**Comment by parg** [comment]
Ah, you're right, issues on OS detection are hiding things - we'll look into it!

**Comment by parg** [comment]
should be fixed

**Comment by LiftedStarfish** [comment]
I am running into this problem. I typically use Brave Browser, and even after I turned off Brave Shield and ublock origin, and did a CTRL+F5, I _still_ could not see it. I _was_ able to see it when I went to the website in Firefox, so this might be a chromium issue.

**Comment by parg** [comment]
Just FYI you can install the I2P Helper plugin from the "Privacy" sub-tab in the Library views
