### ISSUE TITLE
RSSFeed Scanner torrents don't start, stay paused

### ISSUE THREAD

**Issue by j03bj03** [BiglySoftware/BiglyBT#1468]
Windows 7 Ultimate x64
BiglyBT 2.2.0.2
Java 1.8.0_202 (64bit)

Problem with plugin RSSFeed Scanner.

Sorry in advance if this is not the right place to post, I was not sure about posting here... Plugin RSSFeedScanner used to work fine when I selected "Set state to > Force download". However, sometimes when fetching too many downloads, because "Force download" starts them all at the same time ignoring download queue, sometimes the program would freeze or crash because of too many downloads at the same time. So, I selected "Set state to > Queued". The problem is that they won't start with status "Queued". They start with status "Paused". I have to manually start them, defeating the purpose of RSS.

Thanks!

* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment

**Comment by parg** [comment]
The RSSFeed Scanner doesn't appear to have any references to pausing downloads - are you sure it isn't something within BiglyBT that is pausing it? I know there are settings to automatically stop and pause torrents under Tools->Options->Files->Torrents for example. Or Tags can be configured to pause downloads on assignment.

**Comment by j03bj03** [comment]
Wow, awesome!

I was 99.99% sure it was some checkbox somewhere, but there are so many settings in BiglyBT!

I unchecked Tools->Options->Files->Torrents->"By default add new torrents in a stopped state" and now everything works as I want.

It is me who had checked that box, before I was using the RSS feed. Normally, when I open a few torrents at the same time, I don't like it when they all start right away, because sometimes I want to set the download folders or do other stuff and "usually" prefer to start them myself. But with the RSS functionality, I definitely want them to start right away.

Thanks a lot and thank you for the fast support :)

**Comment by parg** [comment]
Anytime :)
