### ISSUE TITLE
Magnet link loading failing after Win10 upgrade

### ISSUE THREAD

**Issue by squasheds** [BiglySoftware/BiglyBT#1469]
Loading torrents with magnet link has started failing 100% of the time after upgrading from Win7 to Win10. As usual, after clicking on the link, BiglyBT opens and the "Operation in progress" window appears. However, after a while without progress, it simply disappears and the "Metadata download" item from the downloads list disappears as well; however, when opening the .torrent file directly, everything loads without problem and the torrent is downloaded. As mentioned, this started happening after I upgraded my OS from Windows 7 to Windows 10 Pro. I already tried to reinstall Bigly and made sure the Magnet URI Handler Overall lookup timeout was set to 0.

Java 1.8.0_231 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_231

SWT v4922r17, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.2.0.2/4 az2

**Comment by parg** [comment]
In the status bar there is a 'show the progress reporting window' icon (usually leftmost) - if you click on this after one of these failures it should give some info on how the magnet download went. Perhaps there is an issue with BiglyBT being able to write the .torrent file to storage after downloading it?

**Comment by parg** [comment]
I just reproduce it by setting the 'save torrents' folder under Tools->Options->Files->Torrents to a folder that exists but to which BiglyBT doesn't have write access...

**Comment by parg** [comment]
Next beta will at least report the error!

**Comment by squasheds** [comment]
I checked the "show progress reporting window" icon right after another such malfunction happened and all it said was "There are no progress reports to display at this time".

I don't know about the folder you mention not being accessible to Bigly; unless the update to Win10 changed the permissions to that particular folder, I don't see how that could've happened, as the permissions to the folder were actual downloads are stored seem to be the same, files were downloaded there when I used the .torrent file.

**Comment by parg** [comment]
Join the beta program (Help menu option), update to beta build 2203_B18 and see if that fixes things

**Comment by gemosley** [comment]
Not sure what's going on. As of very recently, all torrents are failing including plugins_azlocprov_0.4.5.zip. Seeds stay at 0 (even though torrent source may have shown hundreds). The plugins line is now showing Tracker Status "OK (DHT backup only)", as are other entries that have been there for a while. Just joined the beta program but doesn't seem to have made much of a difference. The BiglyBT app on my Chromebook seems to be working just fine.

**Comment by parg** [comment]
Perhaps you could create a 'debug.zip' file (Help menu, last option) and email it over to paul@biglybt.com ? You might need to rename it to (say) debug_zip to avoid issues with email attachments.

**Comment by squasheds** [comment]
I just tried the beta version option and worked perfectly. I still never knew what was wrong, though I assume it was more related to changes made by windows when upgrading to 10.

**Comment by gemosley** [comment]
Working fine for me, now, although I've stayed on Beta. Incidentally, my experience had nothing to do with upgrading Windows 7 to Windows 10.
