### ISSUE TITLE
SwarmMerge

### ISSUE THREAD

**Issue by strange-antiquark** [BiglySoftware/BiglyBT#1477]
Why do I keep seeing the following in the list of IPs that have sent bad data:

[30.01.2020 20:08:35]	SwarmMerge-xfer from 4VZRWMRGSNSKTKVH66MEJLINM525B4LQ/19[1025/9/11166] has sent bad data: occurrences = 1
This has only started showing up in the past day or two; the only change to BiglyBT I have made since last summer is an upgrade to the current version in December.

* openSUSE Leap 15.1
* BiglyBT 2.2.0.2
* KDE

**Comment by parg** [comment]
It is part of the swarm merge process - if BiglyBT attempts to merge two files that appear to be the same but actually contain differences then this will result in the merge of a block from file A into file B causing a hash-fail in B and the knock on effect of that log you are seeing. When sufficient hash fails have occurred merging will be abandoned. Ignore it
