### ISSUE TITLE
Current User Count

### ISSUE THREAD

**Issue by flyeboy** [BiglySoftware/BiglyBT#1481]
I just closed Vuse and installed BiglyBT and i see the user count went from 1.8mil to just 200k. How can i increase the users online again?

* OS and version - Win10
* BiglyBT Version Number Java 1.8.0_202 (64 bit)
* For *nix: Desktop Environment

**Comment by parg** [comment]
The user number is an estimate of the size of the DHT which is shared between BiglyBT and Vuze - the number of users hasn't changed but the estimate can be influenced by such things as your network setup. Check you don't have NAT issues by using the NAT tester via the Help menu,

**Comment by flyeboy** [comment]
> 
> 
> The user number is an estimate of the size of the DHT which is shared between BiglyBT and Vuze - the number of users hasn't changed but the estimate can be influenced by such things as your network setup. Check you don't have NAT issues by using the NAT tester via the Help menu,

Ok done the test and seems failed but i have enabled it to go through the firewall.

![Capture](https://user-images.githubusercontent.com/60537990/73589849-3de6f580-44e4-11ea-90e9-09f5a9f76bc7.JPG)

**Comment by parg** [comment]
Make sure that
1) Your windows firewall is configured to allow BiglyBT / BiglyBT Launcher through on both private and public networks
2) If you have installed any other AV products on Windows that they aren't blocking BiglyBT from actiing a 'server'
3) That your router is either being auto-configured to allow traffic though via UPnP (check the status of the UPnP plugin). Or, if you don't have UPnP support or have it disabled, that you have manually added a port forwarding rule in the router for your chosen port
4) You don't have any warnings (bottom right of BiglyBT status bar) about 'failed to bind to port'

**Comment by flyeboy** [comment]
> 
> 
> Make sure that
> 
>     1. Your windows firewall is configured to allow BiglyBT / BiglyBT Launcher through on both private and public networks
> 
>     2. If you have installed any other AV products on Windows that they aren't blocking BiglyBT from actiing a 'server'
> 
>     3. That your router is either being auto-configured to allow traffic though via UPnP (check the status of the UPnP plugin). Or, if you don't have UPnP support or have it disabled, that you have manually added a port forwarding rule in the router for your chosen port
> 
>     4. You don't have any warnings (bottom right of BiglyBT status bar) about 'failed to bind to port'

Thank you so much for your assistance. I have taken steps as mentioned above and configured a few things. Will restart and see if there is progress. I checked all step by step and no more errors.

Thanks
