### ISSUE TITLE
IPv6 ULA interfaces

### ISSUE THREAD

**Issue by gh338** [BiglySoftware/BiglyBT#1484]
* Kubuntu 18.04 / 18.10 / 19.04 / 19.10
* 2.2.0.3_B25
* KDE

IPv6 networks like onioncat (FD87:D87E:EB43::/48), cjdns (fc00::/7) or yggdrasil (200::/7) do not work with BBT because they are ULA.
Could you allow those to be accepted as IPv6 interfaces in BBT ?

Thank you

**Comment by parg** [comment]
I've released B27 - it has a new option under Advanced Network Settings (near the bottom) to explicitly define additional network ranges as 'global' - I don't have the means at the moment to test this myself so if you could try it and see how it works that'd be good. I'm not 100% sure I have made sufficient changes to make everything work but it should be a start...

**Comment by gh338** [comment]
I adjusted the configuration but the ipv6 ist still being reported as missing.
lsof + netstat do not report any kind of ipv6 bindings.

**Comment by gh338** [comment]
I am sure this is working on your machine - but so far no other user has reported ipv6 working with bbt if i am not mistaken ?

**Comment by gh338** [comment]
With Windows 10 it works without problems.
The real issue seems to be that under linux ipv6 is not used/detected at all.

**Comment by parg** [comment]
IPv6 works just fine on my AWS Ubuntu instances

**Comment by parg** [comment]
and it works fine on my Kubuntu running under VirtualBox

**Comment by parg** [comment]
In installed CJDNS on Kubuntu - in the Advanced Network Settings I now see

he following interfaces are available:
	enp0s3	(enp0s3)
		enp0s3[0]	fe80:....%enp0s3
		enp0s3[3]	2a00:....%enp0s3
		enp0s3[4]	192.168.1.12
	lo	(lo)
		lo[0]	0:0:0:0:0:0:0:1%lo
		lo[1]	127.0.0.1
	tun0	(tun0)
		tun0[0]	fc00:.....%tun0
		tun0[1]	fe80:......%tun0

I can bind to it (tun0[0]) and have set fc00::/8 as an extra global address range but can't go further than that as I'm not part of the CJDNS thang...

**Comment by parg** [comment]
And onioncat

The following interfaces are available:
	tun1	(tun1)
		tun1[0]	fe80:0:0:0:...%tun1
		tun1[1]	fd87:d87e:eb43:5b8:5630:8ea8:cdc8:8521%tun1

**Comment by gh338** [comment]
I will try and reproduce this as i am not sure why exactly my BBT is not showing ipv6 interfaces at all.
What java version do you run @parg ?

**Comment by parg** [comment]
Java 11.0.6 (64 bit)
  Ubuntu
/usr/lib/jvm/java-11-openjdk-amd64

SWT v4922r17, gtk/3.22.30, zoom=100, dpi=96
Linux v4.15.0-76-generic, amd64 (64 bit)
B2.2.0.3_B27/4 az3

**Comment by gh338** [comment]
Thanx @parg . 
Can't reproduce why my identical ubuntu runs without BBT ipv6 detection.
Closing this.
Cheers

**Comment by gh338** [comment]
Can i raise the logging level somehow ?
The log states
nwman NetworkAdmin: ipv4 supprted: true; ipv6: false; probing v6+nio functionality

**Comment by gh338** [comment]
In the biglybt script changed this line:
JAVA_PROPS="-Djava.net.preferIPv4Stack=true"

into this one:
JAVA_PROPS="-Djava.net.preferIPv6Stack=true"

Now ipv4+ipv6 are working.
The corresponding button in the gui does not work.

Cheers :-)
