### ISSUE TITLE
Cannot update to beta

### ISSUE THREAD

**Issue by hatewesterncivilization** [BiglySoftware/BiglyBT#1485]
You, guys, should provide outside downloading of beta builds jar. 

I completely stuck on current version and cannot updating.

**Comment by parg** [comment]
https://github.com/BiglySoftware/BiglyBT/wiki/Updating-BiglyBT

**Comment by hatewesterncivilization** [comment]
I am not sure, when I was write there about moving forward, then this brokage happens. Some paranoid was hacked Bigly on my pc? Because all just works before. 

I was trying gettting beta update from release build, not works. And few other things. I closed to that stuck, I guess.
