### ISSUE TITLE
quick rename dialog too short

### ISSUE THREAD

**Issue by david-bakin** [BiglySoftware/BiglyBT#1488]
BiglyBT Beta 2.2.0.3_B27 on Windows 2016 Datacenter.

Ok, this is super low priority.  But!  The little dialog you get for quick rename is too short.  At least for the files I'm renaming which tend to have really long names - like >100 chars.  Can it be longer ... or resizable?  (If resizable it should remember the last size I set it to!)

Did I mention: low priority?  But thanks!

**Comment by parg** [comment]
Done :)

**Comment by Sauron3019** [comment]
![2020-07-01 172432](https://user-images.githubusercontent.com/66399617/86255605-f7471580-bbbf-11ea-91e6-d2b53e1cb092.png)

**Comment by parg** [comment]
hmm, that's a weird one, I'll take a look

**Comment by parg** [comment]
fixed next beta

**Comment by Sauron3019** [comment]
Can you do the same for batch renaming? Thanks!

**Comment by parg** [comment]
sure, be in B27
