### ISSUE TITLE
raspberry pi better stability? 

### ISSUE THREAD

**Issue by droopified** [BiglySoftware/BiglyBT#1491]
using a raspberry pi and i am in LOVE with this client! its probably the best torrent client i have seen since the old school utorrent days. the features are amazing! the only issue im having is extremely laggy on my raspberry pi 4 4gb. i even wake up to a crashed client. the gui gets unresponsive quick but i can see activity of uploads/downloads. have to pkill it. is there any tweaks i can do on my pi?

**Comment by parg** [comment]
Check out https://github.com/BiglySoftware/BiglyBT/wiki/Performance-Tweaks and see if that helps - if you're not running many active downloads then you should be able to trim the memory usage back which might help.

**Comment by o0nd7ots** [comment]
@parg I think this is closeable

**Comment by parg** [comment]
Closing as nothing's going to happen here, re-open if so desired.
