### ISSUE TITLE
I'll be waiting outside beta download possibility

### ISSUE THREAD

**Issue by hatewesterncivilization** [BiglySoftware/BiglyBT#1492]
Then those situation like I am got planted to going be just impossible. 

Very, very elementary thing, but I am cannot update the betas. Weird one.

**Comment by parg** [comment]
Have you selected 'update anonymously'?

**Comment by hatewesterncivilization** [comment]
Paul, sorry, men, looks like I have fixed things. Just start-up client with default config pathes, before with installing of major release, also replaced some files from it like .certs, so on. Then start-up client with config pathes on the Ram-disk, and now all fine. 

Immediately update syb-system is got working and updated uTP plugin.

**Comment by parg** [comment]
coolio :)
