### ISSUE TITLE
question about Last Update column for trackers

### ISSUE THREAD

**Issue by SUCM** [BiglySoftware/BiglyBT#1494]
since trackers are updated/pulled/checked quite often (every 20-30 minutes), not sure if it make sense to display only the date, but not time (including seconds) for the Last Update column? I know there is the Next Tracker Access column for torrents, so just wondering

also similar question for Full Copy Seen and Last Active columns for torrents, which may not always be the same as Down/Up Idle column's time

just general inquiry. not necessarily seeing these as issue

**Comment by parg** [comment]
For me it shows the date and time - have you changed the date/time format setting in Tools->Options->Interface->Tabled: General ?

You can set whatever format you want at a column level too by right-clicking on the header and selecting from the menu.

**Comment by SUCM** [comment]
ah, I see. I didn't change it. it may have been from migration of Vuze
