### ISSUE TITLE
Organizing (Sorting) Archived Files. Please add the category column.

### ISSUE THREAD

**Issue by MisterFixIt1952** [BiglySoftware/BiglyBT#1499]
I have a rather extensive collection of downloaded files/torrents (40TB+) movies, anime, audiobooks, etc. I have something like 16,000+ items in my BT library. I like to "give back to the community" by keeping these torrents & files seeded. The problem is with so many files, my computer becomes unstable and blue screens out about twice a day if I leave BT live. I have windows 7 64pro with 16GB of ram and an Intel 7 CPU. To solve the problem I finally took my movie collection offline and added it to the archive. Most of the movies are well seeded through other sources. BT now quite crashing but is still sluggish, probably the fault of Chrome with too many pages open (it's a memory hog).

Getting to the point. **With so many items in Archive, I need to sort them by categories, not tags.** There is a column for tags but not one for catagories. Since tags sort alphabetically, it is no good for general sorting unless I delete all of the descriptive tags and keep it general, like categories. Sorting using categories allows me to keep track of movies on drives WXY&Z, which are stored alphabetically across the drives. If I sort by category it shows me all my movies alphabetically. If I sort using tags, it sorts all over the place depending on the first tag. Either that or don't remove the archived files from the library, just mark them archived.

Having archived so many files, I am having trouble keeping track of things since I now have two libraries. Actually, it's more like 4 libraries. Files I have, files I've archived, files I'm downloading and files that I would like to download (or finish) if they would ever become available. With 16,000+ files to track it gets confusing, sometimes (frequently). If I didn't care about seeding and sharing (just being a leach) all of this would be a lot easier but what's the fun in that.

Thanks, guys, you do a great job and make my life a happier place. It's not easy being an obsessive-compulsive file collector (for the last 30 or so years). Oh, the stacks of by-gone hard drives.

**Comment by parg** [comment]
Hi,
You can enable a 'Category' column by right-clicking in the table header area, selecting 'Column Setup' and adding the 'Category' column, You can then click on this to sort by category and, since version 2.2 (I think) you can use multi-column sort by then ctrl+clicking on the 'Name' column to make the sort first by Category and then by Name (within category).

Does that do what you need or did I miss something?
cheers

**Comment by parg** [comment]
ooooo, archived files! I'll take a look!

**Comment by MisterFixIt1952** [comment]
Yes, I was surprised that archived files do not have categories available in the column setup. There are very few columns available, compared to the library, download and other lists. That is why I posted this request.

**Comment by parg** [comment]
Beta B32 has a category column in archived files - unfortunately you will need to unarchive+re-archive everything in order to populate it :( 

The idea of the archive view is to use less memory to manage the downloads, that's why it has a restricted set of columns.

**Comment by MisterFixIt1952** [comment]
Thanks for the tip. Does it really take that much more memory to add 1 more
column? Isn't the Archive view just a spreadsheet or DB view? If that is
the case I would much prefer the Category over the Tag column, at least for
sorting purposes. Will I save memory by turning off unneeded columns in the
Archive view? How about in the Library and Download views? I have become
very memory conscious since BiglyBT had started crashing my machine. I
realize that it's not the program's fault but mine since I have so many
programs, either queued for downloading or saved in the library. Archiving
seems to have alleviated the problem for now.

As a control freak, I tend to have almost all of the informational columns
turned on in most views so I can see what I have, if or when it finished or
if I still need to download or catalog a file. Eventually, all files are
stored on individual data drives according to their category. I need to be
able to quickly lookup the status of a file or rely on Bigly to reject
duplicate torrents. If I take a file out of the library into the archive,
will Bigly no longer recognize a duplicate torrent?

One reason I have so many active downloads queued up is that I have a lot
of partially finished files that I refuse to give up on. At some point, I
plan on deleting the really old ones as I figure that after several years
my chances of finishing them are slim. Every once in a while one completes,
making it hard to delete the possibles. I'm a born optimist.

As it is, I frequently have BiglyGT redownload a file that is already
finished, or at least I think it's finished. Occasionally I try to play a
file marked finished only to find out its a fake file with zero content but
marked as having data. Having Bigly reserve disk space for a file that
doesn't yet exist is the worst "feature" I have ever seen. I have waded
through hundreds of fake files trying to discern if they are really
complete or not. I have the reserve space feature turned off (now) in
setup, preferring to use the az! extension to identify unfinished files.
Since I have quite a few old torrents still active with the optimists hope
that they might get finished one day, I don't know how many old, partially
finished downloads have fake files if the az! feature was not turned on at
the time.

Thanks again for the help. I plan on upping my memory to 32GB in the near
future so memory won't be such a  problem. Better yet, I'm thinking of
converting over to a Linux machine, since I really don't want to upgrade(?)
my Windows 7 to Windows 10. I keep telling myself that 67 years old is not
too late to try something different (or learn new tricks, Woof). Losing
Windows has never been the problem but replacing all of my favorite
programs with a Linux equivalent is. Now I find myself using enough
open-source programs to justify the changeover. I just can't make myself
acquiesce to being forced into Windows 10 bloatware by decommissioning my
trusty Windows 7.

MisterFixIt1952

**Comment by parg** [comment]
BiglyBT won't allocate space for a file if you deselect it for download when adding it (or right-click on it and set its priority to 'delete' (not do-not-download). Sometimes you will get partial files allocated when pieces span file boundaries between those selected and not selected. Also make sure under Tools->Options->File that you select 'spare allocation' if available.

**Comment by parg** [comment]
BiglyBT will recognize duplicate files across library + archived downloads

**Comment by parg** [comment]
It isn't just a spreadsheet/database view - every download has an associated .torrent file that can be many KB in size. When a download is in the Library view its .torrent is loaded into memory (as it contains lots of metadata around file names, trackers...). The .torrent file is also used to store BiglyBT-specific metadata such as category assignments.

The archive view doesn't load the .torrent file and has a restricted set of metadata denormalized into another file to support the view's columns. In B32 I added the Category to this set of data, but to populate it you need to re-archive the downloads as it is at that point denormalization occurs.

**Comment by parg** [comment]
In general the really expensive thing memory wise in BiglyBT is the number of active (downloading or seeding) torrents - each has memory, cpu and network resource usage. Try to avoid force-starting large numbers of downloads in the hope that they will seed and instead rely on BiglyBT's 'seeding rules' that will rotate downloads into/out of an active state to limit resource usage.
