### ISSUE TITLE
Fast Move Broken

### ISSUE THREAD

**Issue by akidburn** [BiglySoftware/BiglyBT#1502]
The latest Beta Broke Fast File Move when on the same drive/partition

please fix

akidburn

Java 13.0.2 (64 bit)
  AdoptOpenJDK
c:\program files\adoptopenjdk\jre-13.0.2.8-hotspot

SWT v4930r7, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.2.0.3_B32/4 az3

**Comment by parg** [comment]
Nothing changed...

**Comment by akidburn** [comment]
switching to V2.2.0.2 fixed it though. 

????

**Comment by parg** [comment]
And switching back to the beta re-breaks it?

**Comment by parg** [comment]
Any update on this? Perhaps you can give some more info on the issue so I can see if I can reproduce it? Thanks :)
