### ISSUE TITLE
Where is the "Sources" file tab?

### ISSUE THREAD

**Issue by Swampgirl** [BiglySoftware/BiglyBT#1503]
Mac OS Sierra 10.12.6
Bigly BT 2.2.0.2

About a week or so ago, the "Sources" tab disappeared from the Torrent view. Now when I double click on an individual torrent, I can no longer see what trackers it has. The tabs remaining are: General, Files, Tags, Options, Swarm, Pieces, Speed, Info, Privacy, Console, and Discoveries. How do I get it back?  Is the absence of the "Sources" tab something I did, or something I can fix? I did try re-downloading Bigly - but I did not clear my old configuration (I do not know how to keep my resources in the side panel when I download a new configuration).
Thank you for all the work you do!

**Comment by parg** [comment]
:P
