### ISSUE TITLE
Swarm Discovery by file size is disabled if file is completely downloaded

### ISSUE THREAD

**Issue by TheBestPessimist** [BiglySoftware/BiglyBT#1506]
![image](https://user-images.githubusercontent.com/4482210/75150802-d8b2a880-570d-11ea-9a7a-78b94eb3b109.png)

I wonder if it makes sense to make this option available even if i have everything. Maybe i could help someone who has a different torrent by seeding my own copy. 

Does that make sense, or do i missunderstand how to use Swarm Discovery/Swarm Merge?

**Comment by parg** [comment]
There is a minimum supported file size (50MB) for such lookups, is this why it is disabled?

**Comment by TheBestPessimist** [comment]
Yes, it seems that for small files (less than 50M) it is disabled, and for larger ones (>1gb) it appears.

Is there a way to inform the user about this?

**Comment by parg** [comment]
I'll add something to https://github.com/BiglySoftware/BiglyBT/wiki/Swarm-Discoveries
