### ISSUE TITLE
Cache is not used at all for reads/seeding

### ISSUE THREAD

**Issue by TheBestPessimist** [BiglySoftware/BiglyBT#1510]
Java 13.0.2 (64 bit)
AdoptOpenJDK
c:\program files\biglybt\jre

SWT v4922r17, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.2.0.2/4 az3

Not sure why, as yesterday during testing, before i tried some downloads the cache was 100% utilised. During the downloads, cache usage kept dropping (i downloaded multiple torrents, canceled some, then downloaded some more; in total more than 5GB).

After leaving it overnight, in the morning the cache usage was 0% (debug 1).
After leaving it today, it seems the cache usage is still 0%.

Here are some logs:
[1 debug morning.zip](https://github.com/BiglySoftware/BiglyBT/files/4251664/1.debug.morning.zip)
[2 debug evening.zip](https://github.com/BiglySoftware/BiglyBT/files/4251665/2.debug.evening.zip)
![cache is not usedd after dowloading](https://user-images.githubusercontent.com/4482210/75278315-52cc5580-5812-11ea-99b0-73528653576b.png)

**Comment by parg** [comment]
If you expect the cache to be used when purely uploading then you'd need to enable 'perform read aheads...'

**Comment by TheBestPessimist** [comment]
Thanks for pointing that out.

Could the wording of that feature be changed only a little, to make this clearer:
`Perform read-aheads to cache to reduce disk usage when uploading.` ?

**Comment by parg** [comment]
sure, thanks!
