### ISSUE TITLE
[question] is there any change on focus of panel in library view between 1.9 and 2.2?

### ISSUE THREAD

**Issue by SUCM** [BiglySoftware/BiglyBT#1512]
on many versions  of Vuze and Bigly 1.x, I'm used to having focus default to seeding panel in library view when
1. nothing is selected in the downloading panel
2. the latest selected torrent is a seeding torrent

where, I usually just use CTRL+A and hotkey to stop/pause seeding torrents for recheck/hash

However, the focus behaviour changed after I updated straight from Bigly 1.x to Bigly 2.2. now if I don't explicitly select a seeding torrent and wait for selection to draw, CTRL+A can select all downloading torrents and stopped all download torrents to re-check/hash on these incomplete torrents because I usually quickly press the hotkeys

this has been quite inconvenient, so I'm just wondering if it's a known/intentional code change or side effect of something else

**Comment by parg** [comment]
Looks like a bug, thanks :)

**Comment by SUCM** [comment]
would like to confirm if fix is not in 2.3.0.0 or fix is not complete in 2.3.0.0

**Comment by parg** [comment]
You saying it isn't fixed?

**Comment by SUCM** [comment]
on 2.3.0.0, not sure if it's just me. occurrence reduced, but still happens from time to time

reproducing steps is roughly like the following. hopefully no missing details/steps

1. CTRL+A select all on torrents in seeding panel (some stopped due to reach ratio or no downloader, some still active, some queued)
2. do whatever with the selected seeding torrents (right click recheck hash, hotkey to tag or stop...etc)
3. add new torrents where each has its own prompt
4. additional torrents finished download and jumped to seeding panel while doing step 3
5. add all of the new torrents from step3 to download panel by clicking their ok buttons one by one
6. after all new torrents prompt are handled, focus goes back to step1's selected torrents
7. press hotkey to remove seeding torrents and immediately press CTRL+A
8. I expect the newly seeding torrents from step4 to be selected since focus was on the torrents in seeding panel, but sometimes all downloading torrents become selected on 2.3.0.0

**Comment by parg** [comment]
Hmm, there may well still be a bug there :( Not high on my list though I'm afraid

**Comment by SUCM** [comment]
that's why I wanted to confirm if this issue was fixed in 2.3.0.0

**Comment by parg** [comment]
well partially it was, your original scenario should be fixed

**Comment by SUCM** [comment]
well, this is the original scenario where step7-8 cover the original scenario1&2. I generalized it into the original scenario1&2 since those were very common and I suspected some timing was in the play

anyways. was just interested to know if I should watch this issue or some other (existing?) issue for the more complete fix

**Comment by SUCM** [comment]
sometimes when I had already click on a seeding torrent and it's highlighted/selected, CTRL-A would still select all torrents in the download panel
