### ISSUE TITLE
Is there a way to add a rule to delete a torrent after X days of seeding?

### ISSUE THREAD

**Issue by brazenvoid** [BiglySoftware/BiglyBT#1514]
I guess the best way would be through a tag. I mean there is a function measuring seeding time. But is there a way? 

I actually use a private tracker which has a hit and run system in testing phase for its ecosystem of trackers. Meaning it does not penalize users yet though it does annoy them through its bells and whistles. I am keeping with it regardless. 

I was thinking of automating its two rules; 1:1 ratio or seed X days for Y sized torrents.

**Comment by parg** [comment]
Setup a Tag that will be assigned torrents when you want them to be deleted and in the settings scroll to the bottom to find 'Limit Settings' There you can define the removal policy when the number of torrents assigned to the Tag exceeds the limit. As you can see, a limit of 0 is already defined to mean 'unlimited' (unfortunately) so there is a hack if you want to actually have a limit of 0, set the value to 999999 (6 nines)

**Comment by brazenvoid** [comment]
Sorry, I don't seem to get your solution. Let me reword my request:

Lets say I start seeding a torrent which is 4GB in size, according to the rule, it will take 4 days for the HnR system to go green on it. Now I have a "Seed for 4d" tag which I assign to this torrent. 

What I would want for this tag is to delete any attached torrents when their seeding time exceeds 4 days or they reach a 1:1 ratio.

**Comment by parg** [comment]
Create Tag 1, call it "seed_4d_or_more" and assign it a Tag Constraint of
`seeding_for > daysToSeconds(4)`
Create Tag 2, call it "ratio_ok" and assign it a Tag Constraint of
`share_ratio >= 1`
Create Tag 3, call it "ok_to_delete" and assign it a Tag Contraint of
`hasTag( "seed_4d_or_more" ) || hasTag( "ratio_ok" )`
Also configure this third Tag to have a Limit Setting with 999999 for the maximum entries and the 'removal policy' of 'delete from computer' (or whatever you want it to do with those old torrents

I wou;d suggest you experiment with a non-destructive removal policy when setting things up in case you make a mistake and things get removed that you'd rather keep...

**Comment by parg** [comment]
Note I editted the above to include 'isComplete()' in the share-ratio test. You need this as during download the share-ratio can fluctuate...

**Comment by brazenvoid** [comment]
What are these tag constraints? Do they like auto tag torrents per set criteria?

**Comment by parg** [comment]
Exactly - see https://github.com/BiglySoftware/BiglyBT/wiki/Tags#Constraints

**Comment by brazenvoid** [comment]
Wow... Here one thinks of something and the app already has it. Sometimes I do wonder, how all this came to be. None of the other apps have even a fraction of possible customization.

**Comment by parg** [comment]
Heh, it came to be because TuxPaper and I wrote it :) 
If you have any feature requests (or bugs) then send them over, always happy to improve the client.
