### ISSUE TITLE
UPnP Not showing folder contents unless i use Classic UI Interface ?

### ISSUE THREAD

**Issue by Mccabe2001** [BiglySoftware/BiglyBT#1516]
I noticed a few nights back that when I select BiglyBT on my smart tv it doesn't show the folder contents, not sure how long its been like this as i'd only recently moved to Win10, older W7 machine was running older Vuze in Classic Interface and worked fine.  So from tv menu, select BiglyBT (Network Media Server), while in new modern view i can see the folders, Video, Music etc, but no content within, but change the Interface to Classic UI and everything is back ... currently some 138 video files ?
Same happens if viewing on my mobile phone through say, VLC Player

Why isn't the UPnP working correctly when in modern UI Interface ?

Any help much appreciated

**Comment by parg** [comment]
In the 'modern UI' your smart TV should appear as a device in the sidebar. You can then specifically make downloads available to it by dragging+dropping them onto the TV's sidebar entry or right-click on the sidebar entry and deselect 'Only show transcoded Files on Device'

**Comment by Mccabe2001** [comment]
Hi  Parg, yes in the Modern UI I can see all of my active LG TV's and other media players and yes i can drag and drop downloaded torrents on to the tv icon and they'll play on the appropriate tv ... but this means i have to start them from my pc (or i can set them off using the Bigly app for Android), but in Classic UI i'm able to select the Bigly app as a UPnP Media Server directly from the tv screen (eg, in the bedroom etc) and scroll down the list of movies held in the Bigly Library and play accordingly.  Any movies that i've downloaded but removed from the Bigly Library are not visible (and for them i use Nero MediaHome as the Media Server)

**Comment by parg** [comment]
And you tried right-clicking on the TV and deselecting 'Only show transcoded Files on the device' ?
