### ISSUE TITLE
Is there install instructions for linux version?

### ISSUE THREAD

**Issue by DumbJoe** [BiglySoftware/BiglyBT#1518]
* Debian
* Latest
* For *nix: Headless Environment

Or is it a simple `wget https://files.biglybt.com/installer/BiglyBT_Installer.sh` and then `./BiglyBT_Installer.sh` and that's it as the installer will take care of any dependencies such as GTK and java-headless that was mentioned on the download page and download and install them or install them if it comes prepackaged with the .sh file or is there more that we need to do to get the program running under terminal cli mode? I checked the wiki but there was no entry on linux installation and no one's asked this question before so I guess I must be the first noob here to attempt and have no idea what I'm doing....

Also, is it possible to install without root access?

**Comment by TuxPaper** [comment]
Answering just from memory, so this may not be 100% accurate:

Installer should install components you need, but will `sudo` to do it. If it can't get sudo, it'll write to stdout/stderr what package it wanted.

If you are installing in headless, the installer will use console to ask any questions.  It will still try to install the gui components of BiglyBT, but you can run BiglyBT in console mode and install the webui (See https://github.com/BiglySoftware/BiglyBT/issues/127#issuecomment-341786046 ). 

If you are more used to tar.gz files, you can also just get the GitHub_BiglyBT_unix.tar.gz on our Github releases page, and uncompress it into an app dir of your choice.  Most *nix environments include all the packages you need nowadays, and a 50/50 chance java is already installed.

**Comment by DumbJoe** [comment]
Thanks, I'm actually more used to the GUI installer but since my os is commandline only and that I don't have root access, I can't install the usual way... The tar.gz file method works, able to extract it using `tar -xvzf GitHub_BiglyBT_unix.tar.gz` and I'm guessing it created its own folder since the program was archived up in a folder prior. Does the extracted contents method include those two dependencies or would I need to download and install them separately as well? 

I get a 

> No binding available (Please activate pairing from Vuze)

When I try to login, error.

**Comment by DumbJoe** [comment]
Also, updating seems to fail, and I don't have an update log file, but can find the debug one: https://pastebin.com/tdsAcrid

**Comment by parg** [comment]
Have you turned on pairing? type 'help pair'

When you quit biglybt do you do it by typing 'quit' - updates should be installed on exit

**Comment by DumbJoe** [comment]
>Have you turned on pairing? type 'help pair'
shows up empty

>When you quit biglybt do you do it by typing 'quit' - updates should be installed on exit
i just press control + c to stop it...

**Comment by parg** [comment]
turn on pairing via (only required once)

`pairing enable`

and make sure you use you use

`quit`

to exit (this ensures configuration state is saved and also should apply any updates). You need to use

`plugin update`

to apply any updates prior to restart if prompted to do so.

**Comment by DumbJoe** [comment]
![11111111111111](https://user-images.githubusercontent.com/36319788/76041714-d19d5d00-5f8d-11ea-9d3c-dd46f8e08351.PNG)
![11111111111111](https://user-images.githubusercontent.com/36319788/76041842-33f65d80-5f8e-11ea-94e7-d58291514e6d.PNG)

Access code has been cleaned out as apparently that's not safe to share....according to you. Oh yeah, I suppose logically it wouldn't because if someone were to have your access code, they could then remote into your bigly bt and start torrenting random stuff.....using up your internet....

As for the updates, yeah they seem to be going cleanly now....thanks...

**Comment by parg** [comment]
Using an access code is just a shortcut for finding out your IP address, and doing as you did with port 9091 - if you're happy with that then do that. In the background BiglyBT contacts a 'pairing server' and maps your access code to your current IP address. When you log in with the access code your client contacts the pairing server, gets the IP address and then uses it to log in. It may be that BiglyBT isn't able to contact the pairing server, from your log it appears that it isn't going to do so until 01:33.

updates don't happen very often and you should be prompted when they are available so you would only need to enter 'plugin update' when you saw there was an update and you were ready to apply it.

**Comment by DumbJoe** [comment]
Does the update always happen? I had to restart biglybt because it stopped responding and when i typed in pair, it told me: 

> Status:      Update will be performed at 13/03/20 01:46

...which means the remote pairing won't work until that update is installed....and will have to use IP and port method instead...

**Comment by parg** [comment]
No, that means that an attempt will be made to inform the pairing server of your latest information at 01:46. Nothing to do with product updates.

If there was a previous error in doing this it might be held in a config variable - type

`set -export`

to show all changed config vars that have changed values and look for one starting with "pairing."

**Comment by DumbJoe** [comment]
Command 'status:' unknown (or . used without prior command)

**Comment by parg** [comment]
status?

**Comment by DumbJoe** [comment]
Samething...

**Comment by parg** [comment]
so you type

`set -export`

and you get the error message

`Command 'status:' unknown (or . used without prior command)`

???

**Comment by DumbJoe** [comment]
yes

**Comment by parg** [comment]
The only way you will get 

`Command 'status': unknown...`

is if you type in the word 'status' as a command

**Comment by DumbJoe** [comment]
Oh I see what I did, I accidentally copied `Status: Update will be performed at 13/03/20 01:46` into the mix before the `set` command for some reason... 🤦 I dumb.

Ok, it works now, here's all the changed variables:

![bb2](https://user-images.githubusercontent.com/36319788/76675028-75bb7f80-65f0-11ea-875a-16f550912786.PNG)

**Comment by parg** [comment]
Ah, look for

set Plugin.default.pairing.last.error

It shows some kind of error, I'll take a look...

**Comment by parg** [comment]
Can you update to 2301_B05 and see if that fixes it?

**Comment by DumbJoe** [comment]
Uhhh, am I doing something wrong?

```
Update available for 'Core Patch Checker', new version =
Apply these updates with the 'plugin update' command
Loaded /biglybt/plugins/azlocprov/GeoLite2-Country_0.4.5.mmdb
plugin update
Updating Core Patch Checker
plugin update
Updating Core Patch Checker
```

Nothing appears to be happening....or showing signs that it's been updated or in the process of being updated....unless it takes more than a few hours for it to happen for some reason...?

**Comment by parg** [comment]
I don't know how you manage to break so much!

There obviously isn't really an update as the 'new version' is blank.

What is output if you enter:

`plugin status azupdaterpatcher`

**Comment by parg** [comment]
By the way, to auto-update to beta versions you need to join the beta program via

`set "Beta Programme Enabled" true bool`

**Comment by DumbJoe** [comment]
...well had there been proper instructions on how to install and run this in a nix environment, headless or gui on the download site on here in the wiki, maybe I wouldn't have had these issues, now would I....? 😛 Perhaps no one uses this in linux environment and is more of a windows program than any other, and I am the first (or first newb attempting to and the others did it no problem because they know their way around a headless system...), mm? Might explain there's a bare minimum web interface compared to the full program app in windows....

I get

```
ID     : azupdaterpatcher
Name   : BiglyBT Updater Support Patcher
Version: 2.1
Running: true
Runs at startup: true
```
with the first command. I've also joined into the beta program now with that next command.

**Comment by TuxPaper** [comment]
We'd love to have proper instructions on installing on various linux distros.  Unfortunately, our time is limited to bug fixing and issue resolving.  We welcome any documentation or help any of our users can provide :)

Having said that, the steps you listed should have worked for you, so thanks for filing an issue about it :)

**Comment by DumbJoe** [comment]
Nope, doesn't seem to fix it, I get a *new* date for the next update that will apparently run before pairing is enabled: `Status:      Update will be performed at 19/03/20 01:07`

Anyhow, the program seems to be crashing on:
```
19-Mar-2020 01:07:32 CRIT  [r 1 shutdown] net.i2p.router.Router         : Shutting down the router...
19-Mar-2020 01:07:32 CRIT  [r 1 shutdown] net.i2p.router.Router         : Starting final shutdown(3)
19-Mar-2020 01:07:32 CRIT  [r 1 shutdown] net.i2p.router.Router         : Shutdown(3) complete
BiglyBT stopped at 19-Mar-2020 01:07:41
Exit from BiglyBT complete
No shutdown tasks to do
BiglyBT TERMINATED.
```

I'm guessing this is relating to the privacy slider thingy you would see in the tab that would switch between public, private/tor and tor only downloads/uploads in the privacy tab, of the windows program...

> We'd love to have proper instructions on installing on various linux distros. Unfortunately, our time is limited to bug fixing and issue resolving. We welcome any documentation or help any of our users can provide :)

Fair enough, how many people are working on this? Just you and Parg? Two man gang...

**Comment by parg** [comment]
So you managed to get the beta version running after joining the beta program? It would say something like

Running BiglyBT 2.3.0.1_B07...

on startup. 

If the beta hasn't managed to install you can do this manually by downloading 

https://biglybt-files.s3.amazonaws.com/core/BiglyBT2301-B07-signed.jar

renaming it to BiglyBT.jar and replacing the existing one in the installation directory with this (when BiglyBT isn't running of course).

And yes, we're a two man band.

**Comment by DumbJoe** [comment]
Yep, it's running the beta now. What else do you need me to do?

**Comment by parg** [comment]
Is pairing working now? If not what is the error shown when you do

`set Plugin.default.pairing.last.error`

**Comment by DumbJoe** [comment]
```
╒═══════════════════╕
│ Pairing │ Pairing │
╘═══════════════════╛
Info        │ Plugin.default.pairing.last.error                  │ "update failed, Data truncation: Data too long for column 'client_state' at row 1"
            │ Last error
```

**Comment by parg** [comment]
hmm, same problem it seems. Can you clear the error by entering

`set "Plugin.default.pairing.last.error" "" string`

triple check that it is reporting 

`Running BiglyBT 2.3.0.1_B09...`

on startup and then wait to see if that error gets logged again - just want to check that it isn't an old error.

**Comment by DumbJoe** [comment]
`Status:      Update will be performed at 24/03/20 16:00`

Apparently it's still adamant that it needs an update....and yes I checked, definitely says `Running BiglyBT 2.3.0.1_B09...` on the console window.

And checking last error using previous command and still the same issue:
`"update failed, Data truncation: Data too long for column 'client_state' at row 1"`

**Comment by parg** [comment]
OK, next beta (B10 when released) will log further diagnostics that should enable me to fix the bug. Please wait until it has installed (today or tomorrow) and then we can take a look. Thanks for your patience!

**Comment by parg** [comment]
B10 is out - please update to it, wait for the update error to occur and then grab the new debug I added by entering

`set -export`

and looking through the result for the entry for `Plugin.default.pairing.last.error.payload`

It should be a large block of text.

**Comment by DumbJoe** [comment]
Is there a way to save the screen into a file so I can view from there? The lines seem to cut off if you don't have a big enough height resolution to view it all.

**Comment by parg** [comment]
Send me over a debug.zip to paul@biglybt.com - that should include it

**Comment by parg** [comment]
hmm, sorry, you can't generate one :(

Close biglybt and send me the biglybt.config file please

**Comment by DumbJoe** [comment]
> Send me over a debug.zip to paul@biglybt.com - that should include it

Uhhhh, where's the debug zip?

I can send you the config file though, that's in the .biglybt folder.

**Comment by DumbJoe** [comment]
Hm, ok so that issue's now resolved. I've notice once torrents are finished downloading, they do not verify themselves to ensure they have 100% integrity before helping to seed the content back to others as that's what usually happens on the windows version. Is that an oversight?

**Comment by parg** [comment]
It's an option, on by default: Files: Re-check pieces when download is done

**Comment by DumbJoe** [comment]
It's on by default for the windows gui application, but not for the Linux cli app....how do I turn it on and leave it on by default so it affects future torrents?

**Comment by parg** [comment]
It is on by default in all versions of BiglyBT - you must have turned it off if it is indeed off.

Type in `set` and look for the current setting for this (default of 1 == true )

> Seeding Piece Check Recheck Enable is not set. [int, default: 1]

To change it

`set "Seeding Piece Check Recheck Enable" true boolean`

**Comment by DumbJoe** [comment]
Does not seem to do it: `> Seeding Piece Check Recheck Enable: 1 [int]` unless it happens whilst it's seeding as the parameter suggests? So keeping the greenbar still stating seeding, but in the background right after it's downloaded, it's actually verifying the pieces but doesn't outright say it is, just says seeding to us, whereas when you right click on the torrent and then go "verify local data" you get a blue bar, is that not the same? If it is, then it should maybe change colour to whatever colour blue and green mixes into...and have a status saying "verifying pieces/local data" for nice user feedback. Helps distinguish between seeding, downloading, and verification process.

And I'm guessing to change the username is:
`set "Plugin.xmwebui.User" <newusername> string`
and to change the accesscode or password is:
`set "Plugin.xmwebui.Password" <newpassword/accesscode> password`

Well the above seems to work anyways as the new username and password works so I guess I got it.

Hmm, found this line:
`> On Downloading Complete Do: Nothing [string]`
isn't that suppose to say something like:
`> On Downloading Complete Do: Recheck [string]` or something to that extent so rechecks the parts before doing nothing? Could be why it's not rechecking the pieces, assuming the checking procedure is not during the first part of seeding status...

**Comment by parg** [comment]
Status is 'seeding and checking' during the post-download recheck. It is different from a force recheck - force rechecking stops the download and verifies the data. It will be working, move on.
