### ISSUE TITLE
Plugin Installation Wizard Missing!???

### ISSUE THREAD

**Issue by res1492** [BiglySoftware/BiglyBT#152]
Hi 
First off I just wanted to say **THANK YOU** to everyone that has kept this amazing piece of software running, I mean it, Thank you!!!..........Back to the "issue" 
I had been running Azureus/Vuze since the very beginning and im very familiar with the software setting/layout and what not.
ATM Im running BiglyBT 1.2.0.0 on Win 10 and I have noticed that the "Plugins"->"Installation Wizard" is missing.
The Uninstallation Wizard is there but the aforementioned is not, was this just an oversite or does it serve a purpose?
The reason I'm asking is that I'm having trouble installing a plugin and be able to manually install it would solve the problem.
Thank again !!
_Res_

**Comment by parg** [comment]
There's a 'get plugins' link that takes you to https://plugins.biglybt.com/

From there you can install the plugins that have been converted.

If there is one you need that is missing then just ask and it can be looked into.

thanks!

**Comment by res1492** [comment]
[AutoPilot_0.5.2.zip](https://github.com/BiglySoftware/BiglyBT/files/1492953/AutoPilot_0.5.2.zip)

Thank for the reply, yep I know about the "Get plugins", but it's not there...I didn't realise it would need converting
 I'm trying to install  **Autopilot**, I have attached the plugin or you can find it on the Vuze plugins page.

Thank you again !!

**Comment by res1492** [comment]
[AutoPilot_0.5.2.zip](https://github.com/BiglySoftware/BiglyBT/files/1492967/AutoPilot_0.5.2.zip)

Thank for the reply, yep I know about the "Get plugins", but it's not there...I didn't realise it would need converting
I'm trying to install Autopilot, I have attached the plugin or you can find it on the Vuze plugins page.

Thank you again !!

**Comment by parg** [comment]
Check out the plugin page, it is there now - tell me if it works ok!

**Comment by res1492** [comment]
Wow, it's working perfectly....This is what I was talking about, its people like you that I was aiming my original thank you at.
Thanks again !!!

**Comment by parg** [comment]
no problem!
