### ISSUE TITLE
Feature Question: Force Start

### ISSUE THREAD

**Issue by Oldbot70** [BiglySoftware/BiglyBT#1520]
I use the autoimport and rename before starting a torrent.
Q: Should the FORCE START carry over to Force Start once the torrent completes?
I set everything that I want to run as F.S. once it finishes so that they
will start immediately whenever I do a BiglyBT restart.

**Comment by parg** [comment]
There's an option to carry-over the force-start under Tools->Options->Queue: Transition 'force start' downloads to 'force seeding' on completion

You could be more selective by using Tags with an 'execute on assign' of 'force start' if you wanted to (and using Tag Constraints to decide which downloads get assigned to them). 

You could also do things like make things transition to 'not force start' once their share-ratio met a given value.

**Comment by SteveBresson** [comment]
Thank You for the quick response!
S
