### ISSUE TITLE
Plugin Porting Request - Monitoring Plugin

### ISSUE THREAD

**Issue by deus0ww** [BiglySoftware/BiglyBT#1522]
Could you port the Monitoring Plugin from Vuze? https://plugins.vuze.com/details/monitoringplugin

I'm seeding many torrents and it would be nice to be able to monitor memory and gc usage.

**Comment by parg** [comment]
Just install the JDK and use jconsole ?

**Comment by parg** [comment]
Also since 2.3.0.0 there's a button you can hit on Tools->Options->Startup & Shutdown that gives the recent memory usage in terms of total/maximum and free

**Comment by deus0ww** [comment]
jconsole will do. Thank you. (It would be nice if there were a button to launch jconsole from BiglyBT or a display of the current pid somewhere...).
