### ISSUE TITLE
Opening multiple torrents in the same window

### ISSUE THREAD

**Issue by exuvo** [BiglySoftware/BiglyBT#1524]
Well i just ran into the 10 year uptime counting rollover bug in my old vuze 4.9.0.0 and upgraded to BiglyBT which worked well, everything migrated over.

But as soon as i started adding new torrents I remember why I still use that ancient version and that is the open torrent window that handles multiple torrents at the same time. It was removed in vuze 5. And I can't seem to find anything similar in BiglyBT either.

How much work do you think it would be to port back the old open torrent window? I don't need any of the tagging or categories stuff, just the same as the old window with multiple torrents at the same time.
I am a java developer so I am up for doing it myself in a fork but thought you might be able to give an estimate on feasibility and the work required. 

This is the window i am refering to:
![vuze 4 9 0 0](https://user-images.githubusercontent.com/2049338/76130865-95f5a800-600c-11ea-8a56-48fca21c93f8.png)

* Arch linux updated today, kernel 5.5.8
* BiglyBT 2.3.0.0
* For *nix: vncserver with OpenBox (nothing else)

**Comment by parg** [comment]
There's a couple of options under 

Tools->Options->Files: Default Dirctory Options

    When opening a torrent, show options dialog: every time (etc)
    Use a separate dialog per torrent

that affects when the window is shown and how it behaves with multiple torrents.

It doesn't give you the old style view but might help. You can multi-select the torrents in the left panel to set some of the settings on all of the torrents.

**Comment by exuvo** [comment]
Okay with that option off it works decently.

Any way to get the left panel to show save location as a column? Column setup only has Number, Size, TorrentName. Otherwise it is a bit tedious to go and check that everything is being saved in the correct location (best guess usually is correct but not always).

**Comment by parg** [comment]
I've added a new column - it'll be in 2301_B03 when built

**Comment by exuvo** [comment]
Wonderful.

A slightly unrelated question, the choose torrent file window used to remember my sorting by date in vuze but not in BiglyBT. Is that a gtk2 vs gtk3 thing or something in BiglyBT?

**Comment by parg** [comment]
You mean the system file selection dialog? If so then that is something BiglyBT doesn't have any control over AFAIK.

**Comment by exuvo** [comment]
Okay then, i'll see if i can find a setting in gtk for that then.
