### ISSUE TITLE
Failed to update + incorrect config directory path in message

### ISSUE THREAD

**Issue by RegProctor** [BiglySoftware/BiglyBT#1525]
I just got your latest update but it failed to update and each time I restarted it asked me to update again. 

When I clicked on the link from a notice (bottom right corner icon) and the notice says "BiglyBT did not shut down correctly... check for any diagnostics log files..." the link opens up a Dolphin window in KDE and Dolphin gives the following message:

The file or folder /home/me/biglybt/'/home/me/.biglybt/logs/save' does not exist.

Clearly this is not my actual configuration directory and I presume /home/me/.biglybt is the actual configuration directory as far as it is concerned - I have some log files dated today in that dir. so I'll take that as the case but the incorrect path in the message can throw a person for moment.

Could you tell me how I best perform the update since I'm probably going to have to do this one manually?

Currently it says I have version 2.2.0.2.

**Comment by TuxPaper** [comment]
hmm, not sure where that Dolphin window/message is coming from you can manually update to 2.3.0.0 by downloading the BiglyBT.jar in our releases section (
https://github.com/BiglySoftware/BiglyBT/releases/download/v2.3.0.0/GitHub_BiglyBT.jar ) and copying it over your existing BiglyBT.jar (probably in /home/me/biglybt).  Maybe make a backup of the original jar first ;)

**Comment by RegProctor** [comment]
You know in the status bar at the very bottom? The right-most icon is a little yellow triangle with a black exclamation mark in it. You can click on that and get messages. 

Right now, mine has a 2 to the right of it indicating there are 2 messages. If I click on the triangle a message box pops up along with arrows so I can scroll through the messages. The messages themselves have links. One of the links in one of the messages opens up the OS file manager, in my case since I am using KDE on OpenSUSE Linux, it opens up Dolphin which is the default file manager for my system. Obviously the link that the message has in it is incorrect since it is sending it to Dolphin and Dolphin is reporting: **The file or folder /home/me/biglybt/'/home/me/.biglybt/logs/save' does not exist.**

Hopefully this time I was at least a little clearer than mud. ;)
