### ISSUE TITLE
2.3.0.0 Update setup ends with reboot request

### ISSUE THREAD

**Issue by token0** [BiglySoftware/BiglyBT#1526]
2.2.0.2→2.3.0.0 update wants to reboot. Is it normal? Why?

![image](https://user-images.githubusercontent.com/4627595/76212740-d2462580-6211-11ea-8ed5-0c807667d90a.png)

**Comment by o0nd7ots** [comment]
@parg this is outdated. Can you close this please?

**Comment by parg** [comment]
Closing as nothing's going to happen here, re-open if so desired.
