### ISSUE TITLE
ui doesnt load when windows open

### ISSUE THREAD

**Issue by droopified** [BiglySoftware/BiglyBT#1527]
was talking to someone on the facebook page about it and they think its a swt issue. my device is a raspberry pi 4 with the latest version of os and biglybt. they said it seems that the system file selection dialog is hanging up. here is are links to screenshots of how it looks after countless killing the process because the whole program becomes unresponsive. 
![image](https://user-images.githubusercontent.com/10093946/76480584-218c8180-63dd-11ea-9f22-d14ce8fa5f2f.png)
here is what it should look like 
![image](https://user-images.githubusercontent.com/10093946/76480616-41bc4080-63dd-11ea-98bc-6f9e05b3b4f9.png)

my about is 
Java 11.0.6 (32 bit)
Raspbian
/usr/lib/jvm/java-11-openjdk-armhf
SWT v4922r32, gtk/3.24.5, zoom=100, dpi=96
Linux v4.19.97-v7l+, arm (32 bit)
B2.3.0.0/4 az3

i know the easiest way to fix it is to move my files manually but that would stop seeding since the files are no longer there but i believe in seeding and keeping files alive.

**Comment by parg** [comment]
Thanks for posting here, that was me on Facebook :) 

You can continue seeding the files by fixing them up after manually moving them (assuming the fixup process doesn't also hang the system). The downloads should go into an error state - data files missing. Right-click on it, select the 'Content' menu tab and then 'search for existing data files'. This will open a window where you can tell BiglyBT where to look for the files - you can manually type in the folder you move files to on the NAS and then hit 'add' to add it to the default locations that are search - this way you avoid having to call up the file dialog that might hang. Once the files are fixed up you can restart the download to seed it.

**Comment by parg** [comment]
(Unfortunately I'm on an older Pi 3 with everything working nicely so I don't want to risk the update to Debian Stretch that I assume would pull in the never kernel etc.)

**Comment by parg** [comment]
Here's the older version of SWT that works for me (although the issue might be with the GTK version you have rather than this) - if you want to try it then unzip the file to extract swt.jar and then replace the one in the BiglyBT directory with it.

[swt.zip](https://github.com/BiglySoftware/BiglyBT/files/4323882/swt.zip)

**Comment by droopified** [comment]
getting the following with that swt no swt-gtk-4623 in java.library.path
no swt-gtk in java.library.path
can't load library: /usr/lib/jni/libswt-gtk-4623.so
can't load library: /usr/lib/jni/libswt-gtk.so
can't load library: /home/pi/.swt/lib/linux/arm/libswt-gtk-4623.so
guess im missing those .so files dont know where to get them. downloaded libswt-gtk-4-jni_4.6.0-2_armhf.deb but that broke the /usr/lib/java directory and was missing libswt-cairo-gtk files.

**Comment by droopified** [comment]
this is hands down the best torrent client i have seen so far. with that ui fix when opening a new dialog box i was able to finish tasks within minutes that took me a week after retries. now i gotta figure out how to apply working trackers and delete dead trackers.

**Comment by parg** [comment]
yay :) The 'All Trackers' view might help regarding deleting dead trackers, it gives you an option to set up a Tag that automatically removes them. Similarly you can use a Tag to automatically add them.

See https://github.com/BiglySoftware/BiglyBT/wiki/All-Trackers-View
