### ISSUE TITLE
Feature request revisited: Search for existing files

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#1528]
I'd like, if you'll indulge me, to make a case for revisiting an aspect of how "Search for existing files..." (henceforth: SfEF) interacts with the elements of the torrent — in particular, _disabled_ members of the torrent — when it discovers matching files. On the grounds that the existing behavior both (IMHO) makes certain operations unnecessarily difficult for the user, and (in doing so) represents poor [DWIM](https://en.wikipedia.org/wiki/DWIM)ming on BiglyBT's part.

Back in #530, in response to a nasty data-loss bug involving SfEF on disabled torrent members, the decision was made to have the scan ignore any matches on files which were not selected for download. I understood that decision then, and I understand it now... but I can't escape the conclusion that it ultimately leads to BiglyBT doing the _opposite_ of what I mean, when I tell it to SfEF.

#### My use case

1. As I've mentioned previously, I often work with very large torrents, ones that contain literally thousands of files. These torrents are assembled as central repositories of the data they comprise, specifically because one of the strengths of BitTorrent is the ability to retrieve only the specific files required. So it is not necessarily the expectation (neither mine, nor the other swarm members', at least to the best of my understanding) that each swarm member will ever obtain all of the torrent's files.
1. I load such a torrent, usually, because I'm interested in obtaining files from it which I don't currently have.
1. I **will** often have _some_ of the torrent's files already available, though — either from a previous session, or from a different torrent entirely that happens to overlap with the current one. (Again, one of the strengths of BitTorrent, and BiglyBT's SfEF in particular, is the ability to match pieces by data checksum regardless of differences in file naming and other metadata.)
1. I'm a nice guy, so whichever of the torrent's files I already have, while I'm part of the swarm I'd like to share them. It's no real imposition on me, and to my mind represents better "swarm citizenry".
1. However, I don't really want to download a lot of files I have no use for (I'm not _that_ nice), so I'd prefer to enter the swarm with the only files enabled being the ones I either **have** or **want**.

#### How it works today

Because of how SfEF works now, my current process is:

1. I load the torrent in stopped state. Both because SfEF requires a stopped torrent, and because in my mind I'm "not ready" to join the swarm, yet.
1. Initially I set _all_ of the files disabled (unchecked). Because I typically  have a few hundred at most, and may want as few as a dozen more. So it's easier to work up from zero than down from thousands.
1. I go into the torrent's file list, looking for sections with files I might already have. When I find some, I have to enable them in order for SfEF to scan them.
1. This often has the side-effect of accidentally _Starting_ the torrent, since BiglyBT understandably interprets the act of enabling files on a stopped torrent to mean that you'd like to download them, even though (in this case) that's **not what I _mean_.** (Though it _should_ be, I'm not arguing here to change that aspect of things.)
1. I then run a SfEF on the newly-checked files, which — if it doesn't fail because the torrent is no longer stopped — matches up all, some, or none of the selected files to my existing ones.
1. If any checked files _weren't_ matched, I then have to go through and uncheck each individual file. This can be a _very_ tedious process. Because even though they were checked, **I don't _mean_ to download them**. (This is another reason I initially uncheck all of the files. Even if I did the SfEF scan with all files enabled, I'd have to go through later and uncheck all of the non-matches.)
1. Last but not least, I enable the files I _want_ to download and finally join the swarm.

#### How I'd _like_ it to work

I'd prefer the process look like this:

2. Steps 1 - 2, same as before.
2. I go into the torrent's list, find groups of _unchecked_ files that I might already have, and run SfEF on those files. (Or even run it on the entire torrent, if I think the match percentage will be high enough.)
2. If BiglyBT finds any matches, it automatically enables **_ONLY_ THE MATCHING FILES**, and leaves the rest disabled.
2. I check any additional files I _want_ to download, and done.

#### Why BiglyBT isn't Doing What I Mean

In #530, @parg expressed reluctance to have SfEF "amend the priority that you have set for the files" (by automatically enabling matched files). Like I said, I understood that reasoning then, and I understand it now — but I still think it's wrong.

If SfEF were any sort of _automated_ action, or if it didn't allow you to indicate _specifically_ which files you'd like it to consider, I'd completely agree. But it's **not** automatic, and it **does** allow fine-grained targeting.

SfEF can only occur when the user explicitly _chooses_ to run it. They have the ability to scan all of the files in a torrent, or just the specific files they want it to consider. So, the act of doing a SfEF _implies_ sharing the files with the swarm. I simply can't see any reason someone would do that and _not_ want the files to be enabled — by running SfEF, the implication is that **they _mean_ to share the matched files**.

**Comment by parg** [comment]
Heyup! Are you sure that the SfEF action sometimes starts the download? A quick look through the code doesn't reveal it doing that but I might have missed something?

**Comment by ferdnyc** [comment]
> Heyup! Are you sure that the SfEF action sometimes starts the download? A quick look through the code doesn't reveal it doing that but I might have missed something?

Oh, no, it definitely doesn't. But _checking_ files from the files list — switching them from Do not Download to Normal priority — can cause the torrent to go from Stopped to Queued after it finishes the Checking run that's often triggered by enabling new files.

**Comment by parg** [comment]
Oh, sorry, you're saying that enabling the files causes this, not the SfEF itself... It still shouldn't start the download though

**Comment by parg** [comment]
hah, beat me to it

**Comment by ferdnyc** [comment]
It seems to be the transition out of the recheck that does it — when BiglyBT finishes Checking a torrent, it doesn't always make it back to the same state it was in before the scan started.

**Comment by parg** [comment]
How about an additional option that does what you want:

'Check deselected files and enable if matched'

?

**Comment by ferdnyc** [comment]
I was actually going to (reluctantly) suggest that, it could even be a checkbox in the SfEF dialog. (Or an additional Mode, or something.)

**Comment by ferdnyc** [comment]
Hmm, probably not a Mode. It's really pretty orthogonal to the question of Link vs Copy, and would work with either.

**Comment by parg** [comment]
I think always scanning all the files might annoy people who aren't as generous as you seeding-wise :)

Can you come up with a reproducible way of triggering that download-starting-on-file-selection issue? I've randomly clicked around and can't reproduce it :(

**Comment by parg** [comment]
I've added an option for the next beta (B04) - please test when released!

**Comment by ferdnyc** [comment]
> Can you come up with a reproducible way of triggering that download-starting-on-file-selection issue? I've randomly clicked around and can't reproduce it :(

I'll give it a try, hopefully I can narrow it down to some concrete series of events.

**Comment by ferdnyc** [comment]
@parg 

Well, I can't reproduce it now. But I did make a related discovery that leads me to think that _maybe_ I was just confused.

As I mentioned, sometimes enabling new files on a stopped torrent will trigger an automatic recheck, if BiglyBT determines that it needs to re-sync its internal torrent state with the filesystem contents.

On torrents this large, that Checking run can take on the order of several minutes, depending how many actual disk bytes have to be scanned and checksummed. And it turns out, a torrent in Checking state counts as "not Stopped" for the purposes of SfEF.

So, for now let's just assume that I was confused, and the SfEF run failed not because the torrent had auto-started, but because it was in the middle of an auto-recheck run.

(I feel like there are times I've been working in the Files tab of a torrent, then switched to the General tab and been surprised to discover it started, totally unrelated to SfEF. But I can't reproduce it now. I'll keep an eye out for occurrences, but unless I can come up with some demonstrable proof, the "I was just confused" assumption seems reasonable.

**Comment by parg** [comment]
Thanks for trying, keep your eye on it! As you say, sometimes rechecking is required and this can take a while. Sometimes torrents are auto-stopped and restarted when fiddling with the skipped status but the code does try to get things back to their original state when complete.

**Comment by ferdnyc** [comment]
In a peripherally-related note, I feel like when the Files list is in tree mode, I used to be able to right-click on a folder line to run SfEF on all of the files in that folder. But I don't see that option now. Am I just misremembering?

(And even if I am, any chance of adding (or returning) that option to the tree-view folder-entry context menu?) :angel:

**Comment by parg** [comment]
heh, don't think it ever did that, but I can take a look :)

**Comment by parg** [comment]
B04 lives - I fiddled a bit with the log output format during SfEF, tell me if anything looks bad or if you can think of any improvements.

Peripherally-related note addressed as well.

**Comment by ferdnyc** [comment]
I did see all of the snazzy new options on folder nodes — an embarrassment of riches! Thanks for that.

I'm afraid all is not well in SfEF land, though. I did test out the new functionality, and in fact ran this test twice on two different directories to confirm. The results were unfortunately similar.

Here's what I did:
1. Copied a directory full of files I know I have, that match the ones in the torrent, to `/var/tmp/foo`
1. Right-clicked on the corresponding torrent folder node (unchecked, along with all its contents), and chose SfEF
1. Set the dialog up in Link mode, "Search for skipped..." enabled, and with the `/var/tmp/foo` dir chosen to scan
1. Hit Search and let it run.

Results:
```
    Matched=37, complete=0, ignored as not selected for download=0, no candidates=0,
 remaining=0 (total=2573)
    Changed 37 files from 'skipped' to 'normal'
3/14/20 10:12 AM: Complete, downloads updated=1
```

But in the torrent, the files ended up like this:
![image](https://user-images.githubusercontent.com/538020/76684151-e7d79880-65df-11ea-9e4f-fcdd720502d8.png)

Out of 37 matching files, somehow 23 weren't correctly preserved when linking them back to the torrent. The files that show 0% have, in fact, been zeroed in the `/var/tmp/foo` directory — the contents are gone.
```sh
# In the original source directory
$ du -sh .
1.2G         .

$ cd /var/tmp/foo
$ du -sh .
452M         .
```

**Comment by ferdnyc** [comment]
Here's the same list sorted by First Piece. It's not _quite_ every-other, but... the pattern does seem weirdly regular. It's odd that no two adjacent files survived.
![image](https://user-images.githubusercontent.com/538020/76684303-2de12c00-65e1-11ea-8d7b-74c4d1e685e5.png)

**Comment by parg** [comment]
Hmm, are they definitely zeroed? Does a manual force-recheck end up in the same state?

**Comment by ferdnyc** [comment]
Yeah, the disk files are 0 bytes in "true" length — the files still show their original size when `stat()`ed, but they're sparse and contain nothing but `0`. Manual re-checks had no effect. When I started the torrent, it proceeded to download all of those pieces back into the zeroed files.

**Comment by parg** [comment]
Just tried to repeat exactly what you outlined and it worked fine :(

I can't think what would be causing the files to be set to zero length - I assume that in the log prior to the

Matched=37, complete=0, ignored as not selected for download=0, no candidates=0,
 remaining=0 (total=2573)

you get entries for each file detailing number of candidates, file testing, matching and successful linking?

**Comment by parg** [comment]
I wonder if it is something weird to do with the way I coded it to switch the files to non-skipped at the end of the process (i.e. after the linking). I'll try switching that around in case it is related.

**Comment by ferdnyc** [comment]
> I assume that in the log prior to the
> 
> Matched=37, complete=0, ignored as not selected for download=0, no candidates=0,
> remaining=0 (total=2573)
> 
> you get entries for each file detailing number of candidates, file testing, matching and successful linking?

Correct, every file is reported as matched and linked, at its correct size.

Actually, I saved the entire log of the second run, here it is with filenames sanitized out.

<details>
<summary>Output of SfEF</summary>

<pre><code>
3/14/20 10:11 AM: Enumerating files in /var/tmp/foo
Found 38 files with 38 distinct sizes
Processing 'torrent', piece size=4.19 MB
    File 01 (size=57.67 MB) - 1 candidate(s)
        Testing /var/tmp/foo/File 001 - ..        Matched
            Linking to /var/tmp/foo/File 001
                Link successful
    File 019 (size=47.19 MB) - 1 candidate(s)
        Testing /var/tmp/foo/File 019 - ..        Matched
            Linking to /var/tmp/foo/File 019
                Link successful
    File 034 (size=43.62 MB) - 1 candidate(s)
        Testing /var/tmp/foo/File 034 - .        Matched
            Linking to /var/tmp/foo/File 034
                Link successful
    File 018 (size=41.66 MB) - 1 candidate(s)
        Testing /var/tmp/foo/File 018 - .        Matched
            Linking to /var/tmp/foo/File 018
                Link successful
    File 015 (size=40.59 MB) - 1 candidate(s)
        Testing /var/tmp/foo/File 015 - ..        Matched
            Linking to /var/tmp/foo/File 015
                Link successful
    File 035 (size=39.23 MB) - 1 candidate(s)
        Testing /var/tmp/foo/File 035 - .        Matched
            Linking to /var/tmp/foo/File 035
                Link successful
    File 017 (size=38.59 MB) - 1 candidate(s)
        Testing /var/tmp/foo/File 017 - ..        Matched
            Linking to /var/tmp/foo/File 017
                Link successful
    File 030 (size=37.86 MB) - 1 candidate(s)
        Testing /var/tmp/foo/File 030 - .        Matched
            Linking to /var/tmp/foo/File 030
                Link successful
    File 033 (size=37.50 MB) - 1 candidate(s)
        Testing /var/tmp/foo/File 033 - ..        Matched
            Linking to /var/tmp/foo/File 033
                Link successful
    File 022 (size=35.11 MB) - 1 candidate(s)
        Testing /var/tmp/foo/File 022 - .        Matched
            Linking to /var/tmp/foo/File 022
                Link successful
    File 026 (size=34.84 MB) - 1 candidate(s)
        Testing /var/tmp/foo/File 026 - .        Matched
            Linking to /var/tmp/foo/File 026
                Link successful
    File 024 (size=34.70 MB) - 1 candidate(s)
        Testing /var/tmp/foo/File 024 - .        Matched
            Linking to /var/tmp/foo/File 024
                Link successful
    File 1001 (size=34.50 MB) - 1 candidate(s)
        Testing /var/tmp/foo/File 1001 - .        Matched
            Linking to /var/tmp/foo/File 1001
                Link successful
    File 028 (size=34.34 MB) - 1 candidate(s)
        Testing /var/tmp/foo/File 028 - ..        Matched
            Linking to /var/tmp/foo/File 028
                Link successful
    File 027 (size=33.78 MB) - 1 candidate(s)
        Testing /var/tmp/foo/File 027 - .        Matched
            Linking to /var/tmp/foo/File 027
                Link successful
    File 032 (size=33.69 MB) - 1 candidate(s)
        Testing /var/tmp/foo/File 032 - .        Matched
            Linking to /var/tmp/foo/File 032
                Link successful
    File 025 (size=32.55 MB) - 1 candidate(s)
        Testing /var/tmp/foo/File 025 - .        Matched
            Linking to /var/tmp/foo/File 025
                Link successful
    File 020 (size=32.37 MB) - 1 candidate(s)
        Testing /var/tmp/foo/File 020 - .        Matched
            Linking to /var/tmp/foo/File 020
                Link successful
    File 029 (size=32.21 MB) - 1 candidate(s)
        Testing /var/tmp/foo/File 029 - .        Matched
            Linking to /var/tmp/foo/File 029
                Link successful
    File 031 (size=31.81 MB) - 1 candidate(s)
        Testing /var/tmp/foo/File 031 - .        Matched
            Linking to /var/tmp/foo/File 031
                Link successful
    File 021 (size=31.77 MB) - 1 candidate(s)
        Testing /var/tmp/foo/File 021 - .        Matched
            Linking to /var/tmp/foo/File 021
                Link successful
    File 016 (size=30.67 MB) - 1 candidate(s)
        Testing /var/tmp/foo/File 016 - .        Matched
            Linking to /var/tmp/foo/File 016
                Link successful
    File 023 (size=30.16 MB) - 1 candidate(s)
        Testing /var/tmp/foo/File 023 - .        Matched
            Linking to /var/tmp/foo/File 023
                Link successful
    File 003 (size=30.15 MB) - 1 candidate(s)
        Testing /var/tmp/foo/File 003 - .        Matched
            Linking to /var/tmp/foo/File 003
                Link successful
    File 007 (size=30.01 MB) - 1 candidate(s)
        Testing /var/tmp/foo/File 007 - .        Matched
            Linking to /var/tmp/foo/File 007
                Link successful
    File 004 (size=29.02 MB) - 1 candidate(s)
        Testing /var/tmp/foo/File 004 - .        Matched
            Linking to /var/tmp/foo/File 004
                Link successful
    File 005 (size=28.94 MB) - 1 candidate(s)
        Testing /var/tmp/foo/File 005 - .        Matched
            Linking to /var/tmp/foo/File 005
                Link successful
    File 011 (size=28.35 MB) - 1 candidate(s)
        Testing /var/tmp/foo/File 011 - .        Matched
            Linking to /var/tmp/foo/File 011
                Link successful
    File 014 (size=28.18 MB) - 1 candidate(s)
        Testing /var/tmp/foo/File 014 - .        Matched
            Linking to /var/tmp/foo/File 014
                Link successful
    File 002 (size=28.08 MB) - 1 candidate(s)
        Testing /var/tmp/foo/File 002 - .        Matched
            Linking to /var/tmp/foo/File 002
                Link successful
    File 010 (size=27.77 MB) - 1 candidate(s)
        Testing /var/tmp/foo/File 010 - .        Matched
            Linking to /var/tmp/foo/File 010
                Link successful
    File 001 (size=26.83 MB) - 1 candidate(s)
        Testing /var/tmp/foo/File 001 - .        Matched
            Linking to /var/tmp/foo/File 001
                Link successful
    File 008 (size=26.35 MB) - 1 candidate(s)
        Testing /var/tmp/foo/File 008 - .        Matched
            Linking to /var/tmp/foo/File 008
                Link successful
    File 009 (size=25.93 MB) - 1 candidate(s)
        Testing /var/tmp/foo/File 009 - .        Matched
            Linking to /var/tmp/foo/File 009
                Link successful
    File 013 (size=23.85 MB) - 1 candidate(s)
        Testing /var/tmp/foo/File 013 - .        Matched
            Linking to /var/tmp/foo/File 013
                Link successful
    File 006 (size=23.19 MB) - 1 candidate(s)
        Testing /var/tmp/foo/File 006 - .        Matched
            Linking to /var/tmp/foo/File 006
                Link successful
    File 012 (size=22.83 MB) - 1 candidate(s)
        Testing /var/tmp/foo/File 012 - .        Matched
            Linking to /var/tmp/foo/File 012
                Link successful
    Matched=37, complete=0, ignored as not selected for download=0, no candidates=0, remaining=0 (total=2573)
    Changed 37 files from 'skipped' to 'normal'
3/14/20 10:12 AM: Complete, downloads updated=1
</code></pre>
</details>

**Comment by ferdnyc** [comment]
> I wonder if it is something weird to do with the way I coded it to switch the files to non-skipped at the end of the process (i.e. after the linking).

That sounds like a strong possibility. If the files are linked _before_ they're enabled, then potentially it's the #530 case all over again. With torrents this big, plenty of time for the data in the disabled file to get deleted, between when it's linked and when it gets enabled.

**Comment by ferdnyc** [comment]
Hmm. I didn't think to check at the time, and without seconds precision in the SfEF log timestamps it's hard to be sure, but if I have a chance I'll reproduce the test, and then check the file modification times. If they show that the zeroed files were modified _before_ the SfEF run finished, then that'd be pretty strong confirmation.

**Comment by parg** [comment]
B06 is out with the changes - please see if it helps! Can't figure out why I can't reproduce the issue though, always annoying that.

**Comment by ferdnyc** [comment]
I'll repeat the test as soon as it finishes updating. And grab timestamps for the start/finish of the run, to check against the disk files (just in case).

**Comment by ferdnyc** [comment]
Ahh, there we go. :+1:  Just the two on the borders "incomplete", as one would expect.

![image](https://user-images.githubusercontent.com/538020/76701813-fd5dc880-669a-11ea-9ec4-0d3746989956.png)

Closing as implemented and fixed, thanks! :100:

**Comment by parg** [comment]
any time ;)

**Comment by ferdnyc** [comment]
I've been puzzling some more over _why_ the first attempt at this failed, and why you weren't able to reproduce it. I formed a half-baked theory.

I probably should've mentioned the specifics of my setup in running these tests, which was:
* 60GB torrent containing ~4000-5000 files of similar size (relatively small, as you can see in the screenshots)
* Torrent download directory on a spinning-platter HDD, ~6-7 years old, fast but not hypersonic
* Files being scannned copied to `/var/tmp` which put them on my 128GB boot SSD
* `$HOME/.biglybt` on a somewhat newer HDD, about 3-4 years old, and relatively quiescent compared to the busy, constantly-accessed torrent HDD

Could be something in the disk speed differences, especially the _latency_ differences, between the input files on the SSD and BiglyBT's working stores which were all on relatively glacial HDDs, that caused the race which ultimately resulted in data loss.

...Or, y'know, might not be that at all. 🤷‍♂️
