### ISSUE TITLE
Magnet "click duplicate" behaviour borked

### ISSUE THREAD

**Issue by actricom** [BiglySoftware/BiglyBT#1529]
If you click a magnet link in a web browser for a torrent with no or low availability, the result is a small window pops up (as it always has done). But if you click the magnet link again, BiglyBT no longer gives a "duplicate - do you wish to add trackers" message and furthermore it removes the popup window and seems to leave the line in the Advanced List, but with the timer removed so it stays there until manually removed. This behaviour is only since 2.3.0.0.

* OS and version: Windows 10
* BiglyBT Version Number: 2.3.0.0

**Comment by parg** [comment]
I'll take a look, thanks

**Comment by parg** [comment]
Should be fixed next beta (although you won't be getting a 'duplicate - add trackers' message as that wasn't right anyway)
