### ISSUE TITLE
EMAIL OVERLOAD

### ISSUE THREAD

**Issue by 2635599** [BiglySoftware/BiglyBT#153]
**since biglybt doesn't seem to have a forum i guess i have yo post here. i just opened outlook and i received 477 emails from you. yes 477. any way of limiting which feature request that i get replies to? thanks**

**Comment by parg** [comment]
What are the kind of emails that you would prefer not to receive?

**Comment by 2635599** [comment]
'd like to only get replies to tickets i created or tickets i commented on. it's a bit ridiculous to receive emails made on every ticket. i thought that was how this was set up.

**Comment by parg** [comment]
Hmm, not sure - have you checked out your settings under https://github.com/settings/notifications ?

Maybe you're watching the repository as well as things you're involved in?

**Comment by 2635599** [comment]
thanks but all looks well there. 

https://i.imgur.com/ScKchiJ.png

**Comment by oblomovx** [comment]
It’s mainly these hundreds of commits of translation files, can’t they be bundled or something?

**Comment by parg** [comment]
Agreed on the translation emails - Tux has been experimenting to set up the Crowdin stuff, hopefully these will reduce now things are 'live' (although he is now working on plugin resources so perhaps not for a bit). I have a filter set up for them anyway.

**Comment by 2635599** [comment]
yea when i saw that many i created a new folder in outlook, searched for bigly, and dragged them all there.

**Comment by 2635599** [comment]
here's an example. according to the setting nin my above image i should not be getting email for new threads, but sure enough

https://github.com/BiglySoftware/BiglyBT/issues/154

**Comment by parg** [comment]
No idea - we don't run GitHub...

**Comment by 2635599** [comment]
yea i think i need to contact their support and point them at this thread. thanks for the suggestions and help much appreciated.

**Comment by 2635599** [comment]
OMFG can you believe this?

"Hi there,
Thanks for reaching out! I'm sorry, but your concern is not clear to me even after reading that thread. Can you give me more detail about your unwanted notifications? Please me as specific as possible.
Regards,
Laura
@lecoursen
GitHub Support"

**Comment by TuxPaper** [comment]
Github emails still so annoying, but we can't fix it on our end, so closing :(
