### ISSUE TITLE
2.3.0.0

### ISSUE THREAD

**Issue by Padriag** [BiglySoftware/BiglyBT#1532]
Java 1.8.0_241 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_241

SWT v4930r7, win32, zoom=100, dpi=96
Windows 7 v6.1, amd64 (64 bit)
B2.3.0.0/4 az3

After update the program often freeses, i was use to it after some time it would get active....
But now when the program freeses it stay's inactive until a restart sometimes 3 or 4 on a row

**Comment by parg** [comment]
Take a look at https://github.com/BiglySoftware/BiglyBT/wiki/Diagnostics

**Comment by o0nd7ots** [comment]
@parg I think this is closeable

**Comment by parg** [comment]
Closing as nothing's going to happen here, re-open if so desired.
