### ISSUE TITLE
Sophos detects C2/Generic-B in BiglyBT\BiglyBT.exe

### ISSUE THREAD

**Issue by othacad** [BiglySoftware/BiglyBT#1533]
* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment

**Comment by hatewesterncivilization** [comment]
I use F-Secure SAFE in Windows, and it shows all alright and clean, no dangerous things.

**Comment by TuxPaper** [comment]
Did the notification pop up before you even ran BiglyBT, or after it was running?

From the description of C2/Generic-B ( https://www.sophos.com/en-us/threat-center/threat-analyses/viruses-and-spyware/C2~Generic-B.aspx ), I'd guess that maybe BiglyBT connected or tried to connect to a peer that Sophos considers a "C&C Server".

Our BiglyBT.exe hasn't changed in a very long time (the last change was to update it's certificate), but we'll keep an eye on it if we get some more user reports like this

**Comment by jzeggelaar** [comment]
I know this discussion is over a year old, but I'm experiencing the same thing. The machine where BiglyBT is running, tries to access 96.9.209.216 and 78.46.87.133 and ATP doesn't seem to like those addresses.

**Comment by parg** [comment]
BiglyBT gets IP addresses from lots of places - trackers, other peers, the DHT - it has no control over these and will, when required, send packets to them.

For example, when doing a DHT lookup for decentralized tracking (at location 'key'), the process is 

* contact a node near to the target key and ask for the list of peers that are closer to the key
* contact all closer nodes and do the same thing
* repeat until no closer nodes are found

At any point in this process a node can return 96.9.209.216, 78.46.87.133 etc and BiglyBT will "connect" to them - it doesn't imply BiglyBT is doing anything nefarious.
