### ISSUE TITLE
question, possibly feature request. how do you re-order tab?

### ISSUE THREAD

**Issue by SUCM** [BiglySoftware/BiglyBT#1534]
in Library view, the bottom panel has a bunch of tabs. accidentally click on x would remove the tab, but right click can bring it back. however, tabs are brought back to right most side. is it possible to drag the tab to somewhere in the middle or to the left most?

**Comment by parg** [comment]
You can drag+drop in the latest beta. Othewise you need to close all the tabs and then re-open them in the order you want.
