### ISSUE TITLE
[Linux] Unreadable texts when GTK3 GUI is used on KDE Plasma 

### ISSUE THREAD

**Issue by glaubersm** [BiglySoftware/BiglyBT#1535]
See the attached screenshots below.
"Use GTK2 instead of GTK3" option available in BiglyBT settings has no effect.
BiglyBT is still using gtk3 GUI.

Java 1.8.0_242 (64 bit)
  Oracle Corporation
/usr/lib/jvm/java-8-openjdk/jre

SWT v4924r25, gtk/3.24.14, zoom=100, dpi=96
Linux v5.4.24-1-lts, amd64 (64 bit)
B2.3.0.0/4 az3

* OS and version Arch Linux
* BiglyBT Version Number v2.3.0.0
* For *nix: Desktop Environment KDE Plasma 5.18.3

![1biglybt](https://user-images.githubusercontent.com/15967631/76686218-a8697600-65f8-11ea-8a0a-8f657191e668.png)
![2biglybt](https://user-images.githubusercontent.com/15967631/76686221-a9020c80-65f8-11ea-8775-6faefff4db79.png)
![3biglybt](https://user-images.githubusercontent.com/15967631/76686222-a99aa300-65f8-11ea-8797-485b923359de.png)
![4biglybt](https://user-images.githubusercontent.com/15967631/76686224-aa333980-65f8-11ea-9730-da4b20691e18.png)
![5biglybt](https://user-images.githubusercontent.com/15967631/76686225-aacbd000-65f8-11ea-8cfa-609e586c3f4d.png)
![6biglybt](https://user-images.githubusercontent.com/15967631/76686229-ab646680-65f8-11ea-8320-cea4c5f6a509.png)
![7biglybt](https://user-images.githubusercontent.com/15967631/76686230-abfcfd00-65f8-11ea-82d1-e745b2a2a4b6.png)
![8biglybt](https://user-images.githubusercontent.com/15967631/76686231-ac959380-65f8-11ea-8c69-6c8b3b8fc04a.png)
![9biglybt](https://user-images.githubusercontent.com/15967631/76686232-ad2e2a00-65f8-11ea-9e3f-aaf639dc1261.png)
![10biglybt](https://user-images.githubusercontent.com/15967631/76686236-adc6c080-65f8-11ea-996e-5a1b0975ddb2.png)
![11biglybt](https://user-images.githubusercontent.com/15967631/76686237-ae5f5700-65f8-11ea-9ad9-add0860d7954.png)
![12biglybt](https://user-images.githubusercontent.com/15967631/76686238-aef7ed80-65f8-11ea-8802-77e6a5534066.png)
![13biglybt](https://user-images.githubusercontent.com/15967631/76686239-af908400-65f8-11ea-9848-b3b87d56519a.png)

**Comment by TuxPaper** [comment]
What theme are you using?  The only built-in dark theme I see is "Breeze Dark" which does not show BiglyBT in black at all.

**Comment by glaubersm** [comment]
I use Breeze GTK3 theme, but BiglyBT is not respecting any GTK3 theme configured on my system. I have tested all themes pointed by a red arrow in the screenshot below but the appearance of BiglyBT is always the same. Transmission, for example, respects my theme settings.

![biglyBT](https://user-images.githubusercontent.com/15967631/76701052-3a768a80-669c-11ea-8471-8dd3a9f5c949.png)

![tested themes](https://user-images.githubusercontent.com/15967631/76701053-3d717b00-669c-11ea-97ea-31ca865cdcf8.png)

**Comment by TuxPaper** [comment]
Thanks! I was only changing the global theme.  Now that I've changed the GTK Application Style, I see what you are seeing (well, I only have 4 themes, but the Breeze-Dark looks as ugly as the pictures you posted, if not more ugly)

**Comment by TuxPaper** [comment]
Try downloading the latest SWT release candidate :+1: 

https://www.eclipse.org/downloads/download.php?file=/eclipse/downloads/drops4/S-4.15RC2-202003050155/swt-4.15RC2-gtk-linux-x86_64.zip

then extract the swt.jar as ~/biglybt/swt/swt-x86_64.jar (while BiglyBT isn't running!)  So, something similar to:

```
unzip ~/Downloads/swt-4.15RC2-gtk-linux-x86_64.zip swt.zip
mv swt.jar ~/biglybt/swt/swt-x86_64.jar
```

When you run BiglyBT, the Help->About should say SWT v4932r18, and hopefully your UI will be readable.

Let us know your results.  If they are positive, we'll roll out the new swt library.

**Comment by glaubersm** [comment]
\o/

![fixed biglybt](https://user-images.githubusercontent.com/15967631/76709452-a2999080-66dd-11ea-90d8-3a6eae2dd6a9.png)
