### ISSUE TITLE
Where are the torrents?

### ISSUE THREAD

**Issue by aleistergreynight** [BiglySoftware/BiglyBT#1537]
Where does bigly store torrent files?  I can't f***ing find them.

**Comment by parg** [comment]
%appdata%\BiglyBT\torrents on Windows

**Comment by librarianm** [comment]
I have an issue with my Torrents view since the last upgrade, no dashboard or options (most importanly no library options) so i cant see if a torrent is starting or not.  any suggestions? Windows7

**Comment by parg** [comment]
Tools->Options->Mode: reset options

and then restart?
