### ISSUE TITLE
Graphical Corruption with SWT 4.15RC2 and Retina Display

### ISSUE THREAD

**Issue by deus0ww** [BiglySoftware/BiglyBT#1539]
OS: macOS 10.13 + 10.14
BiglyBT: 2.3.0.1_B07

It seems like there's issue with scaling the alpha channel. This happens starting with SWT 4.15M3 (4.15M1 is fine).

macOS 10.14 + Non-Retina Display (Normal case):
![Mojave_NonRetina](https://user-images.githubusercontent.com/6702585/76927700-4d929000-6912-11ea-94d4-a4279f6ddff4.png)
macOS 10.13 + Retina Display (Problematic case):
<img width="878" alt="HighSierra_Retina" src="https://user-images.githubusercontent.com/6702585/76927722-5e430600-6912-11ea-9720-f8e240778197.png">

**Comment by parg** [comment]
You have zoom=200 on the corrupted one, any idea why?

**Comment by deus0ww** [comment]
It seems like 200% is the default for Retina/HiDPI display (the second screenshot). The first screenshot is from a non-Retina Mac.

The "Force-DPI" preference is unchecked in both screenshots.

**Comment by parg** [comment]
I think you're right - just cranked up my retina Mac and that's what it shows.

On the currently version we use on OSX (2928r15) I do actually see a little weirdness in the logo on the about dialog but obviously nothing like you're seeing on the newer version. Maybe the SWT guys will magically fix it. 

I'm on 10.15.3 by the way

**Comment by parg** [comment]
Hmm, they released 4.15 on March 5th...

**Comment by parg** [comment]
Yup, 4.15 has the issue :( Guess we'll never upgrade!

**Comment by deus0ww** [comment]
That's ok. I upgraded to test whether dark mode was better (it wasn't). I'll use 4.15M1. I have a feeling it's because of this commit:

https://git.eclipse.org/c/platform/eclipse.platform.swt.git/commit/?h=R4_15_maintenance&id=7afefd0a269900dca511e16bdb0f037877efc22c

**Comment by parg** [comment]
Dark-mode support is a work in progress sadly lacking in enthusiasm at the moment :( I got it to where it is at but I keep finding other things to work on.

**Comment by parg** [comment]
Think I fixed this for the next beta

**Comment by deus0ww** [comment]
Thank you! I saw your commit for the the About window.

One more thing: the toolbar icons are corrupted, too. They're all black.

**Comment by deus0ww** [comment]
By the way, if you're in a lib-updating mood, log4j 2 with the log4j 1.2 API jar, works perfectly for me. I've been using it for years.

**Comment by parg** [comment]
There's another commit for the toolbar... Not a great fix but seems to work :)

**Comment by deus0ww** [comment]
This is now working perfectly. Thank you!
