### ISSUE TITLE
Seeding priority not working properly

### ISSUE THREAD

**Issue by burfadel** [BiglySoftware/BiglyBT#154]
In B1.2.0.1_B11, the priority of uploads seems to be broken. I have a torrent that I created (and hence am the only seed), have set the upload priority to 1 in the torrent options, set force seeding, position 1. The seeding rank is 1st priority, the position is 1, uploaded to a private tracker. In previous versions it worked fine, torrents uploaded in such a manner were pretty much always the main uploader. In the latest version, a torrent that already has 12 seeds, a seeding ratio of (what is now approaching 1.000), is set to the lowest priority and it basically takes all the upload bandwidth, overriding the priority set on the one I'm most interested in seeding. The priority is that bad that basically the torrent I want seeded and set priority for gets shoved to the bottom of the list and ends up not being seeded.

I see changes were made to seeding in this version, it appears broken! Yes, seeding should be fair, but if you are the only seeder that should take precedence over other torrents automatically, and especially if high priority is set. The torrent was only just added today as well, everything appears to be high priority and it gets demoted below other torrents that should be low priority.

System:
Java 9.0.1.3 (64 bit)
Azul Systems, Inc.
c:\program files\zulu\zulu-9

SWT v4830, win32
Windows 10 v10.0, amd64 (64 bit)
B1.2.0.1_B11/4 az3

**Comment by parg** [comment]
ah, boo! Sorry, I was trying to fix an issue where the enabling of upload priority automatically for downloads (the default) was impacting overall upload rates - I'll mainly revert the change for B12 (there were some parts of it that I don't think will cause your problem to occur, but not 100% sure) - please tell me if that works for you

**Comment by burfadel** [comment]
Thankyou! I'll let you know how B12 works out when available.

**Comment by parg** [comment]
By the way, do you have a global upload rate configured or is it left 'unlimited' ?

**Comment by burfadel** [comment]
Global uprate is configured for around 600 Kbit/s, download 1.2 MB/s. Leaves plenty of bandwidth for online streaming, internet usage etc.

**Comment by parg** [comment]
ok, good, important to have a configured upload limit in general - thanks

**Comment by parg** [comment]
B12 is out - please report on whether things have improved, thanks!

**Comment by burfadel** [comment]
Seems to be much better! It's actually seeding now. Also the seeding order of the other torrents makes sense in terms of the upload ratio and seed/peer ratio.
