### ISSUE TITLE
magnets download .torrent file 

### ISSUE THREAD

**Issue by droopified** [BiglySoftware/BiglyBT#1541]
i have some magnets that seem to contain a .torrent file on biglybt but on other clients like deluge the magnets do download the content of the torrent. im not sure if its a torrent within a torrent but with bigly i cant even see the torrent in my library at all. the downloaded .torrent file does nothing in biglybt. on deluge i dont even see the .torrent file even tho i have it set to save .torrent files.

**Comment by parg** [comment]
There was a bug in the last release whereby if you tried to download a magnet twice in quick succession it left things in a weird state - is this happening on a beta version?

**Comment by droopified** [comment]
im on 2.3.0.0 not in the beta program. the download dialog that contains files only has a what i believe is HASH#.torrent but confirming that download doesnt really do anything. doesnt add to library and the downloaded file doesnt open.

**Comment by parg** [comment]
Join the beta program (help menu option) and see if that helps

**Comment by droopified** [comment]
the only problem is that im on a pi4 with 4gb of ram and for biglybt updates i have to manually run the installer. every time i get an update notification it does download it and tries to install it then asks me to relaunch biglybt but the update never installs. i am also not sure where the correct install is. when i first installed biglybt it defaulted to /opt/biglybt but required root. the update to 2.3.0.0 went to /home/ without asking for root. i reran the installer with root which did go to /opt/biglybt so im thinking i have 2 installs of biglybt lol but its working so i just left it. when i install stuff i usually do it to both locations just to make sure.

**Comment by parg** [comment]
I would assume the updates fail due to permissions issues if not installed in /home/ - that's where I have it and I don't have any issues

**Comment by droopified** [comment]
i was able to fix permissions seems to be working. i got 1 unrelated question tho, i move files to my server when im not using my server, it auto shuts down. when its off, biglybt seems to hang. downloads dont seem to start, adding torrents dont seem to download the metadata, and when browsing folders ie moving download location of files, it doesnt load folders at all even if they area local. as soon as i power on the server (not starting the array to share), biglybt works like normal. i have an unraid server so the array is started after manually. im assuming that the target ip becomes valid or online even tho the share paths are not yet mounted so biglybt i guess times out if the ip is down. on my pi i mount the network path to /home/pi/server and i tried to remount from the network path to a local path but it still hangs. not sure why.

**Comment by parg** [comment]
When it is in this weird state trying generating a debug.zip file (Help menu, last option), rename it to "debugzip" to avoid AV issues and email it over to paul@biglybt.com - might give a clue as to what is hanging things.
