### ISSUE TITLE
IRC Bot Plugin is not as good as one in Vuze, please make the one in BiglyBT as good as original!

### ISSUE THREAD

**Issue by roboirc** [BiglySoftware/BiglyBT#1544]

**Comment by parg** [comment]
What do you mean?

**Comment by roboirc** [comment]
The current IRC bot in BiglyBT seems different than the one in Azeurus: http://plugins.vuze.com/details/bdcc

Can we use Azeurus plugins with BiglyBT?

**Comment by parg** [comment]
Not sure what you mean by the 'current IRC bot' - there isn't one by default. There is decentralized chat though.

Compatible BiglyBT plugins can be found from Tools->Plugins->Get Plugins - look for "Tracker Web Templates and IRC plugin"

**Comment by roboirc** [comment]
So Azeurus plugins are not all compatible with BiglyBT?

**Comment by parg** [comment]
They have to be converted

**Comment by roboirc** [comment]
OK thanks
