### ISSUE TITLE
Windows security alerts about azneti2phelper

### ISSUE THREAD

**Issue by BPDunbar** [BiglySoftware/BiglyBT#1546]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4930r7, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.3.0.1_B08/4 az3

Windows security keeps flagging the azneti2phelper plugin as containing PUA:Win32/iBryteInstaller

Specifically in the files C:\Users\brett\AppData\Roaming\BiglyBT\plugins\azneti2phelper\jbigi.dll and  C:\Users\brett\AppData\Roaming\BiglyBT\plugins\azneti2phelper\jcpuid.dll

This is somewhat concerning. I have therefore attempted to uninstall said plugin using the plugin remover however it keeps silently downloading and reinstalling itself, which is annoying.

**Comment by parg** [comment]
Hmm, that file is part of I2P (geti2p.net) and hasn't changed in a long time - I would assume that it is a false positive but I'll ask them in case they have seen similar reports.

**Comment by parg** [comment]
(just disable the plugin under Tools->Options->Plugins->I2PHelper if you're not happy to run it - on beta builds the plugin is auto-installed)

**Comment by hatewesterncivilization** [comment]
Windows AntiMalware is garbage in fast work of system, they would be much better. Right today i was disabled it through gpedit.msc in administrative templates of it. 

F-Secure which i use before i install new system, slightly better than windows defender, but it's detection rate not bad and even fine.

**Comment by skofisk** [comment]
Just got the same warning from windows defender.

Looking into the dll files, they are digitally signed by Azureus Software Inc. Probably includes something "extra" that makes them trigger.
Installed the standalone I2P package, the dlls in there are not signed. And do not give a warning.

Copied/renamed the `jbigi.jar` from that I2P install, to the plugindir. Plugin works just fine, and no warnings :)

**Comment by parg** [comment]
meh, ridiculous

**Comment by parg** [comment]
guess I'll grab the latest DLLs and release them

**Comment by parg** [comment]
I've released version 0.9.46.1.2 for beta users with updated DLLs signed with our latest certificate - please tell me if that fixes the issue.

**Comment by skofisk** [comment]
Got jbigi-win_0.4.jar from the plugin page and deleted jbigi-win_0.3.jar. Windows defender did not complain when restarting BiglyBT.
Fixed for me.
