### ISSUE TITLE
Feature Request: Earlier rejection of SfEF on non-stopped torrents

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#1548]
Hiiiiiiiii, me again. :angel: _One_ more thought I had regarding Search for Existing Files, but I promise this one's no huge change.

As we know, SfEF can't be run on a torrent unless it's stopped. It will tell you that, in fact, if you try to start a scan on a torrent that's Started, Queued, Checking, or in any state other than stopped.

Cool and all, but any chance it could perform that check _first_, as soon as you select the menu option, and refuse to even open the SfEF dialog on a running torrent?

Rather than bringing up the dialog, letting you select paths and set all of the options, and only **_then_**, after you click Search, pointing out that the torrent's running so it can't actually search? (It was running **#ThisWholeTime**, after all.)

See? I can be easy, sometimes. Thanks!

##### System block
```
Java 1.8.0_242 (64 bit)
  Oracle Corporation
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.fc31.x86_64/jre

SWT v4930r7, gtk/3.24.13, zoom=100, dpi=96
Linux v5.5.9-200.fc31.x86_64, amd64 (64 bit)
B2.3.0.1_B08/4 az3
```

**Comment by parg** [comment]
Added something for next beta!

**Comment by ferdnyc** [comment]
Which is already waiting for me to press "Update", cool! Let's try this out...

**Comment by ferdnyc** [comment]
Neato! Works great, thanks.  The "stopped/error" wording makes it extra thrilling, too! :wink:
