### ISSUE TITLE
I2P clock skew error

### ISSUE THREAD

**Issue by user8446** [BiglySoftware/BiglyBT#1562]
BiglyBT v2.3.0.0
I2P helper v0.9.45.1.1
W10

I constant get the error:
I2P reported a clock skew of xxms. Correct your computer time setting if you want I2P to work correctly.

I am using cloudflare's NTP:  time.cloudflare.com and even after syncing the error appears.
Would this be an issue to report here or w/ I2P?

**Comment by amayra** [comment]
i have same problem no matter what how i change time skew error appears 

> I2P reported a clock skew of 1379576ms. Correct your computer time setting if you want I2P to work correctly.

**Comment by parg** [comment]
BiglyBT just reports the skew time reported by I2P which I believe is the average of the detected clock-skew between your computer and the connected I2P peers. If your computer is correctly synced I am at a loss as to why the error would be reported :( Does I2P actually work OK after the error is reported? If there really is a significant issue with your clock then I2P doesn't work well, if at all.
