### ISSUE TITLE
After install plugin 3DView in Linux Fedora 31, BiglyBT won't start 

### ISSUE THREAD

**Issue by sergiomb2** [BiglySoftware/BiglyBT#1563]
* OS and version 
   Linux Fedora 31 with  Java 1.8.0_242 
* BiglyBT Version Number  
   2.3.0.0
* For *nix: Desktop Environment 
   KDE 

after install and download plugins_3DView-linux_0.5.4.zip  a lots of java.lang.NoClassDefFoundError appears in logs and core modules won't load , and BiglyBT doesn't download one byte

**Comment by parg** [comment]
If it doesn't start then why do you say it 'doesn't download one byte', it doesn't do a lot of things if it won't even start... 

Can you post the errors please?

**Comment by sergiomb2** [comment]
doesn't star any download

**Comment by sergiomb2** [comment]
```
    Downloading: [http://version.biglybt.com/biglybt-files/plugins/3DView-linux_0.5.4.zip.torrent?i2p=1: torrent,https://files.biglybt.com/plugins/3DView-linux_0.5.4.zip,https://files.biglybt.com/plugins/3DView-linux_0.5.4.zip]
      Downloading: plugins_3DView-linux_0.5.4.zip
Torrent download complete
Installing plugin '3DView/3D View', version 0.5.4
    Data verification stage complete
Plugin initialising, please wait... 
... initialisation complete.
Version 0.5.4 of plugin '3DView/3D View' installed successfully
```

after restart 
[error.txt](https://github.com/BiglySoftware/BiglyBT/files/4399137/error.txt)

**Comment by parg** [comment]
No idea what's going on there - looks like a corrupted Java installation. How that could be related to the 3DView plugin I have no idea :(

**Comment by sergiomb2** [comment]
yeah java totally broken after install 3DView and after remove 3DView plugin , works without problems .
