### ISSUE TITLE
still loading blank and cant access menu options

### ISSUE THREAD

**Issue by petcol** [BiglySoftware/BiglyBT#1567]
![image](https://user-images.githubusercontent.com/61083722/78028311-2c19b580-73a2-11ea-8856-def4e9bc1065.png)

Once it opens no torrents are shown in the listing you can not access the menu options either,
you get this something like TOOLS > OTPIONS =
![image](https://user-images.githubusercontent.com/61083722/78028643-ad714800-73a2-11ea-8705-5973242db783.png)

I've tried restarting and rebooting and even did a new install, I haven't yet uninstalled and re-installed as I don't want to lose the library. (any suggesitons on how to manually copy it please)

* OS and version
Windows 10 64 bit
* BiglyBT Version Number
v2.3.0
* For *nix: Desktop Environment

**Comment by parg** [comment]
Something very unwell there. Go to %appdata%\BiglyBT\logs and upload the debug_1.log and debug_2.log files

**Comment by petcol** [comment]
[debug_1.log](https://github.com/BiglySoftware/BiglyBT/files/4409215/debug_1.log)
[debug_2.log](https://github.com/BiglySoftware/BiglyBT/files/4409216/debug_2.log)

**Comment by parg** [comment]
Thanks for that - the logs show a load of weird failures and not much in the way of clues. One example is

java.io.FileNotFoundException: C:\Users\...\AppData\Roaming\BiglyBT\devices.config.bak (The requested operation cannot be performed on a file with a user-mapped section open)

when saving config files - I've never seen that error message before about a "user-mapped section"

Can you try launching BiglyBT by using the executable called 

`BiglyBT-console.exe`

in the installation folder rather than the usual shortcut to BiglyBT.exe ? This will open a command window which might show some errors during startup that didn't make it into the debug logs. You can copy from that window by clicking on the BiglyBT icon top-left and then selecting Edit->Select All followed by Edit->Copy

**Comment by petcol** [comment]
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>cd D:\Program Files\BiglyBT

C:\WINDOWS\system32>d:

D:\Program Files\BiglyBT>BiglyBT-console.exe
There appears to be another process already listening on socket [127.0.0.1:6880].

Locate and terminate the other program or change the control port - <a href="https://wiki.biglybt.com/w/Commandline_options#Changing_the_Control_Port">see the wiki for details</a>.

D:\Program Files\BiglyBT>

----------------------------------------------

p.s.: I did close it using Task Manager.
I'll reboot and try again.

Check back later.

**Comment by petcol** [comment]
Oh joy :-(
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>cd D:\Program Files\BiglyBT

C:\WINDOWS\system32>d:

D:\Program Files\BiglyBT>BiglyBT-console.exe
changeLocale: *Default Language* != English (Australia). Searching without country..
changeLocale: Searching for language English in *any* country..
changeLocale: no message properties for Locale 'English (Australia)' (en_AU), using 'English (default)'
UIFunctions/ImageLoad took 86ms
DEBUG::Wed Apr 01 10:40:07 AEST 2020::com.biglybt.platform.win32.access.impl.AEWin32AccessImpl::getAllDrives::645:
  Not enumerating system drives as it crashed last time we tried
    Win32UIEnhancer$1::run::413, AEThread2$threadWrapper::run::317
new shell took 1731ms
new shell setup took 249ms
skin init took 352ms
MainMenu init took 756ms
pre skin widgets init took 124ms
skin widgets (1/2) init took 4663ms
skin widgets (2/2) init took 951ms
pre SWTInstance init took 3ms
Init Core Columns took 1732ms
SWTInstance init took 24ms
shell.layout took 182ms
---------SHOWN AT 1585701618030;16349ms
---------DONE DISPATCH AT 1585701619666;17987ms
---------READY AT 1585701620210;18531ms
shell.open took 2199ms
processStartupDMS took 2ms
postPluginSetup init took 0ms
Locale Initializing took 529ms

--------------------------------
Interesting, it was 
![image](https://user-images.githubusercontent.com/61083722/78087724-59e41600-7405-11ea-91f7-d38724004a12.png)

Clicking OK
-----------------------------
tick tick tick going to make a coffee......

**Comment by petcol** [comment]
![image](https://user-images.githubusercontent.com/61083722/78087825-a4fe2900-7405-11ea-9744-1bcd43a4450f.png)
 
-----------

Still waiting not much happening.

**Comment by petcol** [comment]
I guess what I really need to do is back up my library for this manually so if I have to uninstall and reinstall either this or the PC then I have it ready to go?  Suggestions on a command line or copy file how-to

**Comment by petcol** [comment]
Oh wow I just needed three bups of coffee not one, the library had opened now.

I'm going to back it up before I have any other problems.

**Comment by petcol** [comment]
Console or command prompt is getting loads of this error.
    MsgSyncHandler::sync::5064, MsgSyncHandler::access$35::4826, MsgSyncHandler$10::runSupport::3801, AERunnable::run::36, ThreadPool::runIt::328, ThreadPool$threadPoolWorker::run::739, AEThread2$threadWrapper::run::317
java.lang.OutOfMemoryError: GC overhead limit exceeded
DEBUG::Wed Apr 01 10:57:48 AEST 2020::com.vuze.plugins.azmsgsync.MsgSyncHandler::receiveMessages::4395:
 ---------------------------
that's just a piece copied out btw.

**Comment by petcol** [comment]
Oh I suppose it is Aprils Fools Day isn't it. :-(

**Comment by petcol** [comment]
I have just kicked off a manual backup crossing fingers.

**Comment by petcol** [comment]
<path to files>
Syncing current state
Backup Failed: GC overhead limit exceeded
-----------------------------------------
Should I just copy them or is there an command line method?

**Comment by petcol** [comment]
closed command line mode and opened normally OK too have yet to try back up.....

**Comment by petcol** [comment]
Writing to \\PERSONALCLOUD-2\colin_blunt\Vuze-Backup\2020-04-01\2020-04-01
Syncing current state
Reading configuration data from C:\Users\Colin\AppData\Roaming\BiglyBT
Copying '.certs' ...101.9 kB
Copying '.certs.bad' ...122.6 kB
Copying '.keystore' ...32 B
Copying 'active' ...17752 files, 589.71 MB
Copying 'alltrackers.config' ...20.7 kB
Copying 'alltrackers.config.bak' ...20.6 kB
Copying 'backup' ...3 files, 53.21 MB
Copying 'banips.config' ...265 B
Copying 'banips.config.bak' ...179 B
Copying 'biglybt.config' ...386.2 kB
Copying 'biglybt.config.bak' ...386.2 kB
Copying 'BiglyBT.statistics' ...315 B
Copying 'BiglyBT.statistics.bak' ...315 B
Copying 'categories.config' ...533 B
Copying 'cnetworks.config' ...191 B
Copying 'custom' ...89 B
Copying 'devices' ...5 files, 26.3 kB
Copying 'devices.config' ...144.4 kB
Copying 'devices.config.bak' ...144.4 kB
Copying 'dht' ...10 files, 26.7 kB
Copying 'dlarchive' ...0 B
Copying 'dlhistorya.config' ...1.79 MB
Copying 'dlhistorya.config.bak' ...1.79 MB
Copying 'dlhistoryd.config' ...1.2 kB
Copying 'dlhistoryd.config.bak' ...1.1 kB
Copying 'downloads.config' ...5.37 MB
Copying 'downloads.config.bak' ...5.37 MB
Copying 'exported_params.properties' ...399 B
Copying 'filters.config' ...12 B
Copying 'ipfilter.cache' ...0 B
Copying 'java.vmoptions' ...18 B
Copying 'java.vmoptions.bak' ...18 B
Copying 'java.vmoptions.lastgood' ...18 B
Copying 'metasearch.config' ...23.2 kB
Copying 'metasearch.config.bak' ...23.2 kB
Copying 'net' ...12 files, 209.2 kB
Copying 'plugins' ...513 files, 264.33 MB
Copying 'rcm.config' ...79.4 kB
Copying 'rcm.config.bak' ...79.4 kB
Copying 'rss' ...0 B
Copying 'shares' ...0 B
Copying 'sharing.config' ...15 B
Copying 'sidebarauto.config' ...4.1 kB
Copying 'sidebarauto.config.bak' ...4.1 kB
Copying 'stats' ...2515 files, 84.55 MB
Copying 'subs' ...199 files, 258.8 kB
Copying 'subscriptions.config' ...21.4 kB
Copying 'subscriptions.config.bak' ...21.0 kB
Copying 'tables.config' ...25.6 kB
Copying 'tables.config.bak' ...25.6 kB
Copying 'tag.config' ...429.9 kB
Copying 'tag.config.bak' ...429.9 kB
Copying 'torrents' ...12471 files, 306.44 MB
Copying 'trackers.config' ...92 B
Copying 'VuzeActivities.config' ...60 B
Copying 'VuzeActivities.config.bak' ...435 B
Backup Complete!

**Comment by parg** [comment]
Looks like something has kicked BiglyBT into an out-of-memory situation, from your backup log you seem to have a lot of torrents loaded in BiglyBT - 8000ish? When the Java virtual machine runs out of memory you can get very slow behaviour and errors as it tries to free memory in more and more of a panic...

Check https://github.com/BiglySoftware/BiglyBT/wiki/Performance-Tweaks

You can manually force BiglyBT to start with more memory, Take a look at

https://github.com/BiglySoftware/BiglyBT/wiki/Command-Line-Options

there's a bit about specifying Java options there. Try setting it to 1GB (-Xmx1g)
