### ISSUE TITLE
request much lower waits for ignoring " Torrents that do not upload..."

### ISSUE THREAD

**Issue by coyote3** [BiglySoftware/BiglyBT#1568]
Please provide much shorter time periods in
Settings|Queue|Seeding|First Priority|Ignore: Torrents that do not upload anything for:

Currently the minimum wait is "2 hours".  This is highly problematic for me on Dimeadozen where the number of torrents one can serve is limited.  My limit is often almost completely used by torrents who won't accept a bit due to being firewalled.  How about adding 5, 10, 15, etc minutes please?

BiglyBT 1.0.2.0

**Comment by parg** [comment]
Sure, it'll be in B16 - you'd need to upgrade from 1.0.2.0 though...

**Comment by coyote3** [comment]
OMG thank you very much, you're the man, parg!

Looking at the ChangeLog I see on 1.0.2.0 I'm way behind.  How does one update to betas?  (I enabled Join Beta Program and Checked for Updates but none were found, so I guess one manually updates by downloading the installer from [](https://github.com/BiglySoftware/BiglyBT/releases) ?

**Comment by parg** [comment]
Should auto-update, perhaps you've turned things off under Tools->Options->Interface->Start ? Also check that you haven't enabled  'anonymous updates' as that can cause issues.

Also check that you joined the beta program - the Help menu option should switch from 'Join the Beta Program...' to 'Leave the Beta Program' if that's been done successfully.

**Comment by coyote3** [comment]
Thanks, it does say 'Leave the Beta Program', and now I've disabled 'anonymous updates'.  Then I tried Check for Updates and voila! it offered me B16!

Sweet, thanks parg!
