### ISSUE TITLE
Unable to Install - 2k3

### ISSUE THREAD

**Issue by online-stuff** [BiglySoftware/BiglyBT#157]
* OS and version
Server 2003 Standard SP2
* BiglyBT Version Number
Installer

It says XP works but unsupported..  2003 should be the same?  I can not get it to install.

The Stub installer downloads BiglyBT_Installer32.exe..  Shortly after this launches the main window shows 
BiglyBT is downloading the Java(TM) Runtime Environment. Please Wait.

Then an Error box titled Error appears.
Error downloading the Java(TM) Runtime Environment.
Please check your internet connection and start setup again.

Log: C:\Documents and Settings\kevin\Local Settings\Temp\1\i4j_nlog_8.log

In the log file the part that jumps out is

`[0:234] ERROR: No JVM found
[0:234] Download location: https://www.biglybt.com/jre/win32
[0:234] Downloading JRE
[0:671] ERROR: InternetOpenUrl failed with error code 12157
[1:671] ERROR: Retry JRE download`

Each time I run it the nlog_ increases by 1 and the tmp directory e4j31.tmp_dir1511512668 in the same folder as the log file, the number at the end increases by a smaller but unknown (to me) value.

I tried copying a couple variations of the jre.tar.gz file it is looking for, but from the logs, I am not fast enough getting the new folder name any copying the files before it skips it.

Online searches for the error code 12157, lead me to one page asking if  SSL 2.0 and SSL 3.0 were enabled in Internet Options..  3.0 was, 2.0 was not.  After enabling 2.0 there was a delay before getting the error message and a different error shows in the log file 12029, but otherwise I don't see any change.

I am attaching a screen shot and the log files.

Are there any command line options for passing a local file instead of it fetching the JRE package from the internet?  An offline install for example.

I find it odd that the stub downloader can get the full install file but not the JRE file.
[i4j_nlog_10.log](https://github.com/BiglySoftware/BiglyBT/files/1501171/i4j_nlog_10.log)
[i4j_nlog_8.log](https://github.com/BiglySoftware/BiglyBT/files/1501172/i4j_nlog_8.log)
![biglybt](https://user-images.githubusercontent.com/28365718/33204396-a16e47ce-d0c0-11e7-9ee6-04b8677fec7b.jpg)

**Comment by TuxPaper** [comment]
For XP and possibly Win2k3, you will need to install Java 8 yourself from oracle.  If Java (JDK or JRE) 1.8.0_151 or higher is installed on your system, that should make our installer skip trying to download it itself (and failing).

**Comment by online-stuff** [comment]
That fixed it.  I had 144 installed.

Uninstalled and installed the newest (151) and then Bigly installed without issue.

Thank you.
