### ISSUE TITLE
does autobackup also backup the library?

### ISSUE THREAD

**Issue by droopified** [BiglySoftware/BiglyBT#1570]
my raspberry pi sdcard died and i had auto backup enabled on biglybt. nothing is in the library and it appears that the /torrent folder in the backup directories all are empty. it did backup all my categories but thats about it. not even my save locations are saved in the restore.

Edit: so I got a different card and set up my pi with the thinking that in case the SD card dies again I can simply write the data back from a .img backup of the whole card. in bigly, i had a fresh install without any configurations thinking the backup would restore everything. When backed up and restore the image, I ran bigly and restored. Only the categories got applied. No options got applied and not my library. I restored the .img back and tried this time to set up bigly as if how I liked it then backed up that .img again. I ran a restore just to see what would happen and it applied everything from the restore bigly did. Just to try and replicate it again, I re flashed the backup .img and it didn't take it again only the categories. I kept closing bigly and opening it and eventually it applied it again. Thinking it's just a bug so of it doesn't apply the restore keep trying! 1 key thing I noticed is when the restore didn't apply bigly didn't automatically reopen. I also want to point out that I tried to copy/paste the data from a backup folder bigly made but that also didn't wouldn't apply.

**Comment by droopified** [comment]
so to update, the either doesnt save complete or gets corrupted because my setting simply did not change, however, i setup biglybt again as best i could remember to my liking and noticed that the /torrent will be moved in the settings. since i my location to my external data drive, it did restore my library which is great! but yea i started with a fresh install and bigly didnt restore the config in the options.  do you know where the library data is saved? since i redid the config, i made a iso backup, i think i can just backup/restore my library and it should be good to go.

**Comment by parg** [comment]
It is supposed to backup most of the contents of the configuration folder, including ../torrents. You can check this by running a backup manually in BiglyBT and see what ends up in the backup folder.

It doesn't backup download data.

When the restore process runs you should get a window detailing what's going on - does that complete successfully?

**Comment by droopified** [comment]
well when u restore it gives you a process of the files and says it finishes then asks to restart. upon restarting, it doesnt actually apply. the it takes quite a few tries for it to actually apply.  i even tried to copy the content from the backup manually. 

but where is the library data stored? as in my incomplete/complete downloads? if i know which file it is i wouldnt mind just transfering that and manually setting up a config/plugings/etc.

**Comment by parg** [comment]
Download data config consists of two things

1) the downloads.config file
2) the 'active' folder (and any subfolders)

The 'torrents' folder is also a useful thing to copy.

All the backup process really does is copy (most of) the config directory and the restore process copies it back. There are some smarts around restoring to a different location from where the backup was made from (some config data has absolute paths in it and needs fixing up), but if you are backing up and restoring to the same place then manually copying will work. 

Obviously you need to restore the files when BiglyBT isn't running.

**Comment by parg** [comment]
And of course the other files do have purpose!

biglybt.config - overall configuration
tag.config - all Tag settings
categories.config - Category settings
subscriptions.config + the 'subs' folder - Subscriptions

**Comment by NewGuestUser** [comment]
> Download data config consists of two things
> 
> 1. the downloads.config file
> 2. the 'active' folder (and any subfolders)
> 
> The 'torrents' folder is also a useful thing to copy.
> 
> All the backup process really does is copy (most of) the config directory and the restore process copies it back. There are some smarts around restoring to a different location from where the backup was made from (some config data has absolute paths in it and needs fixing up), but if you are backing up and restoring to the same place then manually copying will work.
> 
> Obviously you need to restore the files when BiglyBT isn't running.

Hi parg!

Can pls give me instructions how can I do that manually on last 2.3.0.0 version? Is it possible to transfer just a library and download history from the older releases of BiglyBT (without other settings)?!

I tried to transfer file “downloads.config” and folder “active” several times but no way to make this 
 to work!

 Thx ;)

**Comment by parg** [comment]
Works fine for me - what is going wrong for you? Download History is stored in dlhistorya.config and dlhistoryd.config by the way.

**Comment by NewGuestUser** [comment]
Yes history works fine but library is not displayed in new version when I transfer mentioned file and folder :(

**Comment by NewGuestUser** [comment]
Can Tags be a Problem?

I used them in old realse of BiglyBT so I trensfare also a "tag.config" file!

**Comment by parg** [comment]
Tags are separate, not related to library.

**Comment by NewGuestUser** [comment]
Any idea then? pls!

**Comment by parg** [comment]
Perhaps the downloads.config file you are importing is corrupted. Copy everythign again and then, instead of starting Vuze by BiglyBT.exe use BiglytBT-console.exe (I assume you are on Windows, you didn't say). See what gets logged.

**Comment by NewGuestUser** [comment]
I get:
"[core] Error while loading downloads.  One download may not have been added to the list....."

???

**Comment by parg** [comment]
And what follows that? Check the debug_1.log and debug_2.log files too

**Comment by NewGuestUser** [comment]
I did that with TraceLog and same error few times!?

**Comment by NewGuestUser** [comment]
Can be a problem last JDK14??

**Comment by NewGuestUser** [comment]
I try to start old version of BiglyBT and everything works fine! Isn’t that strange?

**Comment by NewGuestUser** [comment]
The error I have was a problem of ipfilter location. I fix location of file “ipfilder.dat” and now I don’t have any errors in logs but I still have a problem with displaying the library!

**Comment by parg** [comment]
I can't help you if you don't give any more details. From earlier...

"And what follows that? Check the debug_1.log and debug_2.log files too"

**Comment by NewGuestUser** [comment]
[15:07:13] [core] Error while loading downloads.  One download may not have been added to the list.
[15:07:13] [stderr] DEBUG::Mon Apr 13 15:07:13 CEST 2020::com.biglybt.core.global.impl.GlobalManagerImpl::loadDownload::2907:
[15:07:13] [stderr]   java.lang.NullPointerException
	at com.biglybt.core.global.impl.GlobalManagerImpl.addDownloadManager(GlobalManagerImpl.java:1321)
	at com.biglybt.core.global.impl.GlobalManagerImpl.loadDownload(GlobalManagerImpl.java:2884)
	at com.biglybt.core.global.impl.GlobalManagerImpl.loadDownloads(GlobalManagerImpl.java:2571)
	at com.biglybt.core.global.impl.GlobalManagerImpl.<init>(GlobalManagerImpl.java:635)
	at com.biglybt.core.global.GlobalManagerFactory.create(GlobalManagerFactory.java:41)
	at com.biglybt.core.impl.CoreImpl.start(CoreImpl.java:1023)
	at com.biglybt.ui.swt.Initializer.run(Initializer.java:614)
	at com.biglybt.ui.swt.mainwindow.SWTThread$6.runSupport(SWTThread.java:353)
	at com.biglybt.core.util.AERunnable.run(AERunnable.java:36)
	at java.base/java.lang.Thread.run(Thread.java:832)
[15:07:13] [stderr]

**Comment by NewGuestUser** [comment]
...and then the error persists

**Comment by NewGuestUser** [comment]
Image from console:
![image](https://user-images.githubusercontent.com/63556875/79124156-02965c00-7d9c-11ea-9c66-cdc47971b172.png)

**Comment by NewGuestUser** [comment]
parg,

leave it I'm going back to more stable Vuze ;)

Thx & Br!

**Comment by parg** [comment]
lol
