### ISSUE TITLE
Set File Order Resets On Minimize/Maximize Cycle

### ISSUE THREAD

**Issue by brazenvoid** [BiglySoftware/BiglyBT#1573]
**Problem**

As The title says, its pretty easy to reproduce. Essentially whenever I set file order to whatever criteria for a torrent, on next minimize/maximize cycle that order is purged and default order is restored. 

The same thing happens when I switch torrents but well I can ignore that inconvenience.

**Use Case**

My use case is that I have few torrents with thousands of files and I am opening each file one by one so as to keep only a limited few of them. These torrents have slow seeds so many of the media are incomplete. 

Thus, I have to sort them by completion status. As a further filter I mark already seen files to low priority. So I first sort by priority and then by completion status. This kind of sort does not always returns the same order. 

While switching between the associated app and BiglyBT due to habit sometimes I minimize it regardless resulting in the reset.

* Windows 10 64-bit 1909
* BiglyBT v2.3 Release

**Comment by parg** [comment]
Can you clarify please as I can't reproduce it. This is how I read your problem

1. Standard UI (sidebar view, not classic UI)
2. Detailed list view in the Library (although this probably doesn't matter)
3. You selected a torrent and switched to the Files sub-tab view
4. Files sub-tab view is not the 'tree view' version (or is it?)
5. You select the priority column to sort by that and then ctrl+click on % to get secondary sort on that

Everything is fine, you then switch to another torrent in the Library view and then back again and this leaves the Files view in an incorrect sort state?

Note there can be a second or so delay on switching things as the sort isn't re-applied immediately on switch.

**Comment by brazenvoid** [comment]
I thought it was clear that there were two cases while the main one is related to Minimize and Maximize cycle. I didn't really care for the second one which is when switching torrents but a further observation is that it actually happens when switching to nothing and then back. 

There is no second delay (the UI redraw) which returns the settings to my settings rather it is the dreaded thing that when happens, it means a reset.

Sometimes it does not redraw but very rarely. 

**Your modified STR:**

1. Standard UI (sidebar view)
2. Detailed list view in the Library 
3. You selected a torrent and switched to the Files sub-tab view
4. Files sub-tab view is not the 'tree view' version 
5. You select the priority column to sort by that and then ctrl+click on % to get secondary sort on that
6a. Minimize and Maximize, the settings will be lost after a UI redraw
6b. Switch to no selection state and then the state with selected same torrent, the UI is redrawn and settings are gone.

**Comment by parg** [comment]
I didn't really care for the maximize/minimize case if it was possible to re-create the issue by switching torrents.

**Comment by parg** [comment]
For me, Windows 10 same as you, the issue does not occur. So there must be some other setting involved (well, actually I am on the latest Beta, I suppose it is possibly something to do with that)

Neither 6a or 6b causes the Files view to lose the primary and secondary sort.

**Comment by brazenvoid** [comment]
Alright. 

Another further observation is when it works, the sort is actually calculated again on Minimize/Maximize. Can this be disabled or the previous result cached and restored?

As I remarked earlier, this kind of sort returns different results on every iteration.

**Comment by parg** [comment]
Could it be you've turned off auto-resorting

Tools->Options->Interface->Library: Re ORder tabled every N GUI updates: [0: never]

?

**Comment by brazenvoid** [comment]
Don't have that option in release build. Should I use it?

**Comment by brazenvoid** [comment]
[Beta] Ah its under Interface->Table, yes it is somehow set to 4 though I have never known this setting. Perhaps a remnant of some old build...

**Comment by brazenvoid** [comment]
No changing it to 0 does not fix it. It still reorders...

**Comment by parg** [comment]
Next beta (B19) will have some changes to force a re-sort when the FilesView is rebuilt - let's see if that helps.

**Comment by brazenvoid** [comment]
Yes, it seems to working great and consistently bringing up same results. I will keep on using and will close this issue, if it persists.

Though just curious, why does it have to reorder anyways, whether to default or set order? Does the row order gets purged or something on UI refresh? I mean it inevitably still loses the selection and scroll position.

**Comment by parg** [comment]
Some views get disposed of when no longer visible to save resources.
