### ISSUE TITLE
Why is  Forced Seeding so much faster than normal seeding?

### ISSUE THREAD

**Issue by TheBestPessimist** [BiglySoftware/BiglyBT#1574]
Background: I'm trying to seed as much as possible. Target ratio: > 222. I have 1000/500 (100MBps/50MBps) internet.

I can download torrents with 100MBps without issues. Maximum upload speed I managed (using qBittorrent) is ~30 MBps while testing with some friends in the same city, same network provider, and 10-15 MBps normally.

My question is how to tune BBT to achieve better seeding/upload speed?

If I enable "Forced Seeding" mode, I get upload speeds of about 7-12 MBps.
![10  using forced seeding](https://user-images.githubusercontent.com/4482210/78381004-64f19e80-75dd-11ea-8d1d-44ecd8dc8594.png)

Why is "normal mode" so much slower to upload compared to Forced Seeding? The upload speed is smaller compared to forced mode, never reaching 10MBps, and very rarely reaching 8MBps. It seems scraping the trackers is also slower, even though I did not achieve my ratio. 
The `Scrape OK` message appeared 1-2 minutes before me takig the screenshot, even though BBT was running for more than 10 minutes.
![20  using normal seeding mode](https://user-images.githubusercontent.com/4482210/78381011-67ec8f00-75dd-11ea-8876-e87719d7befe.png)

Here are some of my settings (whatever else you might need, I will provide):
![100  Queue - Seeding - First Priority](https://user-images.githubusercontent.com/4482210/78381040-763aab00-75dd-11ea-80b9-375d1dab93aa.png)
![200  Queue - Seeding - Ignore Rules](https://user-images.githubusercontent.com/4482210/78381045-78046e80-75dd-11ea-81c8-cf4349f8bd99.png)

For example, for the highlighted torrent there (same in both pictures): i know there are a lot of peers to which i could seed (from forced mode), but it seems that in normal mode, BBT is not trying to seed to any of those.

If i start forced mode again, here's how it goes.

![30 normal - to forced](https://user-images.githubusercontent.com/4482210/78381797-8dc66380-75de-11ea-9586-17832cde8784.png)

Note about the pictures: i was using forced mode for screen1. Then i set all torrents to normal mode, and restart BBT and took screenshot2. After a while, I started forced mode again and took screenshot 3.

---

Java 14 (64 bit)
  AdoptOpenJDK
c:\program files\java

SWT v4930r7, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.3.0.0/4 az3

**Comment by hatewesterncivilization** [comment]
Maybe there are some logic for that by system of seeding rules? No matter of that, devs have seeing your request and will do things.
