### ISSUE TITLE
tag for force start after 50% downloaded

### ISSUE THREAD

**Issue by almanteka** [BiglySoftware/BiglyBT#1577]
* OS and version = Windows 10 Pro 1909 Build 18363.720
* BiglyBT Version Number = 2.3.0.0.

hi! i'm trying to create a tag to force start a downloading torrent after reaching 50% using constraint "isGE( percent, 50 )" and selected execute on assign "Force Start", but this apply the tag to already downloaded and seeding torrents too! anyway to apply to only downloading torrents? there is no "isDownloading() " constraint defined to use! also, will like to remove the tag after is completed, how i can use "isComplete()" in the same constraint argument to remove the tag? thanks in advance for any help and for the great client!

**Comment by almanteka** [comment]
after reading the wiki, i came with a constraint of "isGE( percent, 50 ) && !isComplete()"! now, i need to know how to auto-remove the tag after the download is completed

**Comment by parg** [comment]
Once the download is complete it will be auto-removed from the tag - I assume what you're asking for is the 'force start' to be removed once complete? You can do this by creating a separate tag with a constraint of

hasTag( "whatever-you-called-the-other-tag" ) && isComplete()

with an execute-on-assign of 'not force start'
 
BUT you'll need to set the 'scope' of the original constraint to be 'addition only' - this will prevent it from being removed once the download is complete and therefore allow the second tag to do its work.

probably :)

**Comment by almanteka** [comment]
> 
> 
> Once the download is complete it will be auto-removed from the tag - I assume what you're asking for is the 'force start' to be removed once complete? You can do this by creating a separate tag with a constraint of
> 
> hasTag( "whatever-you-called-the-other-tag" ) && isComplete()
> 
> with an execute-on-assign of 'not force start'
> 
> BUT you'll need to set the 'scope' of the original constraint to be 'addition only' - this will prevent it from being removed once the download is complete and therefore allow the second tag to do its work.
> 
> probably :)

thanks for your reply! indeed, i tested it out and the tag is removed after completion! i'm only using BiglyBT for 3 days and I love how i can manage my torrents with the tags! now, i'm trying for a tag to hold paused torrents with only one downloading, and after this one completed, a paused one start to download automatically within the ones paused in the tag! is that possible?

**Comment by parg** [comment]
You can control the number of active downloads at a global level via the rules under Tools->Options->Queue.  I can't think of a reliable way to do what you want with Tags - there is a constraint regarding number of things assigned to a Tag and you could set something up whereby downloads from one 'paused' tag were assigned to a 'run me' tag when the 'run me' tag had no other entries but I I'm not sure you could guarantee that only one was transferred at a time. You could experiment :) You'd need 2 Tags, call them "SchedTestQueue" and "SchedTest". The Tag constraint for SchedTestQueue would be 

`!isComplete()`

and the constraint for SchedTest would be

`countTag( "SchedTest" ) == 0 && hasTag( "SchedTestQueue" ) && !isComplete()`

SchedTest would have an execute-on-assign of 'Start' (or 'Resume')

**Comment by parg** [comment]
Oh, and 'SchedTest' has to have a scope of 'Addition Only'

**Comment by almanteka** [comment]
thanks! your suggestions are working as expected, just waiting for a download to finish to watch the behavior! i'll keep you informed!

**Comment by almanteka** [comment]
well, it worked! but i need to manually remove the tag "SchedTest" on the completed torrent for a paused one on "SchedTestQueue" to start downloading! not a problem at all! thanks for all your help! i'll test, maybe adding another tag just to remove the other tag!

**Comment by parg** [comment]
hmm, darn it, that's the disadvantage of the 'addition only' scope :( but you need that otherwise the counttag part will cause the download to be removed from the tag when assigned.

Maybe you can do it with a third tag with constraint

```
SchedTest - countTag( "SchedTestActive" ) == 0 && hasTag( "SchedTestQueue" )

SchedTestQueue - !isComplete()

SchedTestActive = hasTag( "SchedTest" ) && !isComplete()
```

**Comment by almanteka** [comment]
ok, i'll test your suggestion! just to be sure:

`SchedTest - countTag( "SchedTestActive" ) == 0 && hasTag( "SchedTestQueue" ) ---> execute-on-assign=START ---> scope=Addition Only

SchedTestQueue - !isComplete() ---> execute-on-assign=PAUSE --->scope=Addition Only (here are going to be assigned, the torrents we want paused?)

SchedTestActive = hasTag( "SchedTest" ) && !isComplete() ---> execute-on-assign=??NONE SELECTED?? ---> scope=??Removal Only??`

thanks for your help!

**Comment by parg** [comment]
The only one that needs a scope of anything other than the default (addition+removal) is the "SchedTest" - as before, scope = Addition Only.

**Comment by parg** [comment]
I should probably try these things out before suggesting them though :) How this is supposed to work is as follows.

Starts off with all your paused and incomplete downloads assigned to SchedTestQueue.

Nothing is assigned to SchedTestActive.

SchedTest is examined to see if a download should be assigned to it. SchedTestActive is empty so that passes for download D1, hasTag( "SchedTestQueue" ) is true for all the downloads assigned to SchedTestQueue so the first one gets assigned to SchedTest. When this happens it also gets assigned to SchedTestActive. Now the second paused download is checked. SchedTestActive is now non-empty so no other downloads are assigned to SchedTest and they sit in the queue paused.

Eventually D1 completes. This causes it to be removed from SchedTestQueue and SchedTestActive. SchedTestActive is now empty so download D2 gets assigned to SchedTest, repeat.

Theory sounds good.

**Comment by almanteka** [comment]
ok, i'll like to use this test with only torrents added to the tag SchedTestQueue. if i use the default scope of addition+removal, all of the other torrents already assigned to other tags, are added to SchedTestQueue! thanks!

**Comment by parg** [comment]
boo! Not really designed for this as you can tell! I'll think about it, see if I can come up with a new feature that might make it straight forward to do this kind of thing! Thanks for experimenting.

**Comment by almanteka** [comment]
thanks!!!

**Comment by parg** [comment]
Next beta will have a new constraint function, 'tagPosition( tagname )' that returns the download position (in terms of the 'Order' of the download within the tag). So you can use a constraint of 

`tagPosition( "SchedTestQueue" ) == 0 && !isComplete()`

to assign the first download from the queue to the SchedTest tag (and therefore start it). Once it completes it will be removed from the SchedTest and SchedTestQueue tags and therefore the next one from the queue will be assigned and started. 

You just need these two tags, both with scope of 'addition and removal' for this hopefully to work.

**Comment by parg** [comment]
B20's live if you want to try it

**Comment by almanteka** [comment]
thanks!!! any advice on how to install the beta version? just run the installer after backing up? i'm new with biglybt!

**Comment by almanteka** [comment]
ok! just made a backup, joined the beta program and installed the beta version! i'll test it out! thanks!

**Comment by almanteka** [comment]
worked perfectly! used these settings:
SchedTestQueue ---> execute-on-assign= Pause ---> constraint= !isComplete() ---> scope= Removal Only (i send all the torrents that i like to download one by one to this tag)
SchedTest ---> execute-on-assign= Start ---> constraint= tagPosition( "SchedTestQueue" ) == 0 && !isComplete() ---> scope= Addition & Removal
both tags are removed when complete and a new torrent is added to SchedTest to start downloading!  i used scope= Removal Only at SchedTestQueue because i like to use only the torrents assigned to this tag and not all the torrents from the library and/or other tags! thanks for the great work!!!

**Comment by almanteka** [comment]
sorry! forgot to ask! what means exclusive for tags groups? TIA!

**Comment by parg** [comment]
A download can only be a member of one tag in a group if that tag is 'exclusive'. If the group has tags T1, T2 and T3, if a download is assigned to T1 and subsequently assigned to, say, T2, then it will automatically be removed from T1.

Of course the tags should not have auto-assignments setup as this will cause problems...
