### ISSUE TITLE
Autohost downloaded torrents

### ISSUE THREAD

**Issue by gh338** [BiglySoftware/BiglyBT#1578]
* Kubuntu 18.04
* BiglyBT 2301_B19
* KDE

Would it be possible to auto host downloaded torrents (Right Mouse Click -> Social-> Host)? 
Maybe have a javascript action for that ?

Thank you.

**Comment by parg** [comment]
I'll add an 'execute-on-assign' Tag action to do this, you would need to associate the downloads that you want to host with that tag (e.g. via a constraint of 'isComplete')

Unfortunately the Java developers are removing the JavaScript engine from Java so I'm not actively going down that route :(

**Comment by gh338** [comment]
Much appreciated. So is there an alternative or is all the javascript related functionality going to die ?

Cheers.

**Comment by parg** [comment]
Not sure how much javascript Bigly stuff there is out there! They haven't actually removed it yet, just throw out warnings. Hopefully there'll be a drop-in replacement by the time it becomes an issue, assuming we want to continue supporting it.

**Comment by gh338** [comment]
Much appreciated.

Cheers :-)

**Comment by gh338** [comment]
Can we have an autopublish too ?

Cheers !

**Comment by parg** [comment]
sure
