### ISSUE TITLE
BBT web remote 0.9.3 crashing the client 

### ISSUE THREAD

**Issue by nin0bb** [BiglySoftware/BiglyBT#1580]
After the latest update any attempt at connecting through the web remote results in very high CPU usage and the client becomes partially to completely unresponsive until it crashes, it is enough to just press 'click to test pairing' to make this happen.

I use this function to inject torrents from Sonarr and Radarr dockers.
Trying to connect through these or just testing the connection from them results in a unresponsive BBT client instantly and I need to restart the program

**Comment by parg** [comment]
Weird, not seeing that with my testing. When BiglyBT is in an unresponsive state can you try the instructions here:

https://github.com/BiglySoftware/BiglyBT/wiki/Diagnostics

to try and grab some diagnostics?

**Comment by nin0bb** [comment]
Does this give you any pointers as to what's going on?
[debug_1.log](https://github.com/BiglySoftware/BiglyBT/files/4438875/debug_1.log)

**Comment by parg** [comment]
Yes, thanks - I'll work on a fix

**Comment by parg** [comment]
Try 0.9.3.1

The changes made in 0.9.3 to correctly calculate some download attributes were using a lot of resources so I reworked them to hopefully put things back how they were resource-wise.

**Comment by nin0bb** [comment]
That appears to have fixed it, testing connection is now instant as before. 
Mind you the machine this is running on is a 12 core 1.7Ghz system so it's not a powerhouse xD

Thank you for the help!

**Comment by parg** [comment]
No problem :)
