### ISSUE TITLE
BiglyBT keeps crashing

### ISSUE THREAD

**Issue by casnewydd** [BiglySoftware/BiglyBT#1582]
Started having issues with BiglyBT saying short on memory about 8 weeks ago and I still keep having problems no matter what I try.  Things have actually got worse and it is constantly crashing now and is almost unusable.  I've tried switching to Beta version, updated Java, changed memory settings, re-installed, but still no luck.

**Comment by parg** [comment]
Check out 

https://github.com/BiglySoftware/BiglyBT/wiki/Performance-Tweaks

for some clues around memory usage

**Comment by casnewydd** [comment]
Already tried that.  I tried copying the log to the clipboard but I couldn't get it to paste on here.  In baby steps can you tell me how to copy the errors in the log to here for you to have a look.  

I've been using BiglyBT since the very beginning and have never come across a problem that I haven't been able to solve..........until this.

Many thanks

**Comment by parg** [comment]
Go to the Help menu, generate a debug.zip (last option), rename it to debugzip and email it to paul@biglybt.com - I'll take a look

**Comment by casnewydd** [comment]
Sent at 19:27.  Let me know if not received or any problems.

Many thanks

**Comment by parg** [comment]
Received and replied! As I said in my email, your max heap is set to 120MB which is way too small for anything other than a very bare-bones BiglyBT with no extra plugins and very few downloads.

**Comment by casnewydd** [comment]
Replied
