### ISSUE TITLE
Incremental file creation not always working correctly

### ISSUE THREAD

**Issue by Qwest8K** [BiglySoftware/BiglyBT#1584]
* Windows 7 Enterprise SP1 
* BiglyBT 2.3.0.0

When a function "Enable incremental file creation..." is active, then it must create files with name and resolution as in torrent file, but with zero size. And after - increasing them sizes on the number of *bytes that was downloaded. However, often this function creates files with name and resolution as in torrent file, but with complete (and not zero) size and then just replaces them filler bytes with the correct ones.

It is very uncomfortable. Especially when very large files are downloaded and the space on the hard disk instantly disappears, because BiglyBT immediately fills it with "empty" files with size = ~100 gigabytes.

**Comment by parg** [comment]
Use the 'sparse file' option instead. The issue with incremental creation is that the file is extended as data is downloaded (as opposed to being pre-allocated). As bittorrent downloads tend to download random parts of the file as the download progresses it may download a piece a long way into the file and trigger the file to be extended to that point at any time.

Sparse files use the underlying OS's sparse file features to allocate disk blocks when needed. They may appear to be large but when you right-click on them to show properties their 'size on disk' should be incrementally allocated.

**Comment by Qwest8K** [comment]
Okay, this works as needed.
