### ISSUE TITLE
Tracker Web sort option

### ISSUE THREAD

**Issue by gh338** [BiglySoftware/BiglyBT#1585]
* Kubuntu 18.04.4
* BBT 2.3.0.1_B20
* KDE Plasma 5
* Tracker Web 2.3.1

Would it be possible to have the TW plugin to default to either alphabetical sorting and/or Added (=time the torrent was added) ?
This way the latest one could appear at the default page.

Cheers

**Comment by gh338** [comment]
The problem currently is also when pagination is enabled it only sorts in the page context and not global->paged.

**Comment by parg** [comment]
Unfortunately we don't have anyone working on that plugin - don't suppose you know enough to hack around with it?
