### ISSUE TITLE
BiglyBT Error 

### ISSUE THREAD

**Issue by Tazmaniac2** [BiglySoftware/BiglyBT#1587]
I was downloading a movie and it stopped at 99.0% and shower an error. The error was...
Error: Read Fails Data Error (Cyclic Redundancy Check)
What should I do now?

The system is: Java 1.8.0_202 (32 bit), Oracle Corporation

**Comment by parg** [comment]
Check your hard disk - that's a physical device error.

**Comment by Tazmaniac2** [comment]
> 
> 
> Check your hard disk - that's a physical device error.

Is there anything I should check out?
