### ISSUE TITLE
double-click row no longer launches Details tab

### ISSUE THREAD

**Issue by coyote3** [BiglySoftware/BiglyBT#1588]
When I upgraded from 1.0 to the Beta releases, I noticed that when I double-click a row it no longer launches that row's Details tab.  

I can't find this option in the Interface Settings; I loved that functionality, can one still enable it?

**Comment by parg** [comment]
Search for 'double' in the settings

**Comment by coyote3** [comment]
Thank you very much, parg!  
And I never even noticed that Settings had a search!

**Comment by parg** [comment]
I have to use it myself :)

**Comment by coyote3** [comment]
Hey, IIRC if I selected one or more rows then pressed Enter that also launched Details tab(s).

Now doing so for one row launched my file manager, and for multiple rows does nothing.  I can't find a setting to change this.

**Comment by parg** [comment]
Tools->Options->Interface->Tables: 'Return in torrent views'

Only works with a single selection though
