### ISSUE TITLE
Unable to set stop ratio in CLI 

### ISSUE THREAD

**Issue by diizzyy** [BiglySoftware/BiglyBT#159]
For some reason it's not possible to set stop ratio in CLI.

```
set "Stop Ratio"
> Stop Ratio: 0.0 [unknown]
set "Stop Ratio" 2.0
ERROR: invalid type given
```

FreeBSD 11.1 - OpenJDK 8 (openjdk8-jre-8.144.1)
BiglyBT 1.2.0.0

**Comment by parg** [comment]
Use

set "Stop Ratio" 2.0 float

**Comment by diizzyy** [comment]
Ahh, I see! Thanks :-)
