### ISSUE TITLE
it takes along time for biglybt to stop downloads. maybe half an hour sometimes.

### ISSUE THREAD

**Issue by Bzs123** [BiglySoftware/BiglyBT#1590]
* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment

**Comment by parg** [comment]
Try the beta, it gives closedown progress information (Help menu to join it)

**Comment by parg** [comment]
Is it possible the download has a lot of unwritten/cached data that has to be flushed to disk before it can stop?

**Comment by TuxPaper** [comment]
It's possible it's getting stalled on trying to write to a bad part of your drive. You could also try scanning your disk for bad blocks or errors.  If you have a utility that shows drive health, that might tell you if the drive has been seeing errors lately, too.

**Comment by Bzs123** [comment]
Drive is healthy, no bad sectors. It's possible that has cached data but halts for half an hour!
Maybe I should change the drive format, it's ExFAT under Catalina, I'm not sure of this is causing the issue but I never had this problem with AFPS.

**Comment by parg** [comment]
If you want generate a debug.zip file (help menu, last option), rename it to debugzip (sometimes .zip causes email issues) and send it over to paul@biglybt.com - I'll look to see if there are any errors in the logs.

**Comment by Bzs123** [comment]
Drive is healthy, no bad sectors. It's possible that has cached data but halts for half an hour!
Maybe I should change the drive format, it's ExFAT under Catalina, I'm not sure of this is causing the issue but I never had this problem with AFPS.
