### ISSUE TITLE
What this could be?

### ISSUE THREAD

**Issue by eurobank** [BiglySoftware/BiglyBT#1592]
Latest BiglyBT (not beta) and Windows 10/64 Pro.

What this area could be ?

![2020-04-11 21_11_00](https://user-images.githubusercontent.com/4467158/79052664-cdc1c200-7c40-11ea-8000-5fcf4ed6bb8a.png)

**Comment by parg** [comment]
No idea

**Comment by eurobank** [comment]
This is actually the upload area in the advanced list. If you switch back and forth, it shows. Also (it is related i think) in the advanced view, sometimes the upload area is gone (not shown) and you have to max resize the window to view it.

**Comment by parg** [comment]
Hmm, never seen that! You have the 'Downloading' view selected, it isn't even supposed to have an 'upload' area... Do you see this on other views (e.g. Library) or just 'Downloading' ?

**Comment by eurobank** [comment]
This is still an issue but after so much time, no reason to keep it open.
