### ISSUE TITLE
The context menu popup is broken on MATE on Debian Buster

### ISSUE THREAD

**Issue by dark-penguin** [BiglySoftware/BiglyBT#1593]
The context menu popup does not look right - at least on MATE on Debian Buster. All tabs of the popup are empty except for icons partly visible on the very right.
![screenshot](https://user-images.githubusercontent.com/16963337/79067891-8a606580-7ccb-11ea-97fd-5b7e94c09081.png)

This issue persists if I try:
- GTK2 or GTK3 interface
- "Classic" or "new" interface
- OpenJDK 11.0.6 or Oracle Java 1.8.0.231

BiglyBT v2.3.0.0
MATE on Debian Buster amd64
Java 11.0.6 (64 bit) - Debian - /usr/lib/jvm/java-11-openjdk-amd64
Java 1.8.0_231 (64 bit) - Oracle Corporation - /home/kami/.tlauncher/jre1.8.0_231
SWT v4924r25, gtk/3.24.5, zoom=100, dpi=94
Linux v5.5.0-7.1-liquorix-amd64, amd64 (64 bit)

**Comment by dark-penguin** [comment]
I've tried diagnosing this problem.

- On Debian LiveCD, the menus are displayed properly
- On Debian Buster in Docker, the problem exists
- In the same Docker container, if I run the whole MATE in Xephyr, it works correctly!

What could be the difference between a fresh installation and my machine? To narrow things down, it reproduces when running BiglyBT in Docker (I run Docker with "-v /tmp/.X11-unix:/tmp/.X11-unix"). So, everything is on the Docker side except only the X server. Is it a problem with the X server?.. o_O

**Comment by parg** [comment]
I know this is in no way a solution but if you double-right-click to show that menu then you get the older style, non-tabbed menu instead (you can change the default to always show this in the config somewhere too).

Diagnosing SWT library issues on particular OS configurations is always a massive pain :(

**Comment by dark-penguin** [comment]
This solution is good enough for me! If I can make this the default instead of double-right-clicking. (This is the first time I've seen double-right-clicking used somewhere, so at first I even misread it and tried to double-click until I've figured it out by myself.)

I'm trying all this on a fresh installation of BiglyBT in Docker (Debian Buster, OpenJDK 11) to avoid potential issues from migration from Azureus. I'm using "Advanced" mode for options. "Interface/Legacy - Use old style speed menus" did not help. (What is a "speed menu"? Maybe it's some other menu?) Also, I could not find out what does "use closeable tabs" mean - the tabs on details on the bottom are closeable either way, even on GTK2. "Interface/Tables" has options what to open on a double-click (which does not include "a menu"), but not on double-right-click.

Are you sure that setting is there? Maybe it is not, but should be?

**Comment by dark-penguin** [comment]
If I start BiglyBT in Docker without installing a desktop environment, then the menu displays with its items visible, but buttons on top of that menu disappear immediately after showing, and also the whole window looks like it's not raised. I assume most of that is expected, but the interesting part is that the original problem does not appear in this case.

**Comment by parg** [comment]
The double-right-click is a hack I put in just for this menu as sometimes I prefer the original one :)

The option isn't obvious unless you know that the 'new' menu is also known as the 'fancy menu' :) Look under Options->Interface->Tables for 'Show Fancy Menu'

**Comment by dark-penguin** [comment]
Oh! Thank you! This worked!
