### ISSUE TITLE
1 million users on Vuze's DHT and only 48 thousands on Bigly's DHT

### ISSUE THREAD

**Issue by hatewesterncivilization** [BiglySoftware/BiglyBT#1594]
Reported right now. But Bigly much better than Vuze at present time. 

People just didn't hear about good changes?

**Comment by parg** [comment]
shame isn't it

**Comment by NewGuestUser** [comment]
hatewesterncivilization I don't agree with you!

People rather see stability than changes ;) Did you look how many issues are opened for "Bigly"?

And parg -1 for your work. I suggest you not giving a answer if you don't know what are you doing! Just closing the threads is not solution for all the problems :)

**Comment by parg** [comment]
hatewesterncivilization - please don't feed the trolls

**Comment by hatewesterncivilization** [comment]
Ok, men, no problem, never thinking about those hostile trolls, but this topic pretty solution for the problem. Ok, parg.
