### ISSUE TITLE
Columns of torrents' status causes lags

### ISSUE THREAD

**Issue by Qwest8K** [BiglySoftware/BiglyBT#1598]
I noticed that with a very large number (3000+ for example) of active torrents, scrolling of table with torrents becomes extremely painful - BiglyBT freezes for several seconds any time when move more than a few lines at a time. Also, even more hellish freezing are obtained when trying to sort torrents by status - in this case, program almost dies, if do not switch the sorting to another column.

However, if disable any columns with the current status of the torrent - such as "Progress" and "Status" - then scrolling becomes problem-free: smooth and instant.

But I hope there is no need to say how inconvenient it is to monitoring torrents with the disabled column of status?

**Comment by hatewesterncivilization** [comment]
Try placing Bigly to ram-disk, I'm doing so. More faster mentioned issue.

**Comment by parg** [comment]
I've not got thousands in my library but around 700 doesn't cause me any issues. Perhaps you can recreate the problem for a minute or so and then grab the debug_1.log and debug_2.log files and upload them? They might give a clue as to where the issue is.

**Comment by Qwest8K** [comment]
This files?
[logs.zip](https://github.com/BiglySoftware/BiglyBT/files/4468872/logs.zip)

**Comment by parg** [comment]
Hmm, actually, sorry, I should have said thread_1.log and thread_2.log :(

**Comment by Qwest8K** [comment]
Okay, this ones?
[logs2.zip](https://github.com/BiglySoftware/BiglyBT/files/4469300/logs2.zip)

**Comment by hatewesterncivilization** [comment]
Another thing, yesterday I was granted to PrimoCache additional 1 GB of cache and had seen faster work right Bigly's GUI and system too.

**Comment by parg** [comment]
Qwest8K - thanks for those files, useful!

**Comment by parg** [comment]
Try Beta B23, should improve things

**Comment by parg** [comment]
Oh, sorry, you're running 'BiglyBT Extreme Mod', how can you try betas.

**Comment by Qwest8K** [comment]
I accidentally noticed that if check off "Attempt to merge incomplete files that are the same size", then lags, provided by status columns, disappears completely.

**Comment by parg** [comment]
It is fixed in beta
