### ISSUE TITLE
Update via TOR + I2P

### ISSUE THREAD

**Issue by gh338** [BiglySoftware/BiglyBT#1599]
* Kubuntu 18.04
* BiglyBT 2.3.0.1_B21
* KDE 5

Currently the automatic update when doing anonymously requires a working TOR + I2P plugin.
If i understand correctly some URL's are fetched to check for updates.
Would it be possible to update only via TOR or only via I2P ?

Cheers

**Comment by parg** [comment]
With work yes but it isn't high on my list. If you're that bothered I'd suggest that you monitor the anonymous update channels and download from that and manually install:

`chat:anon:?BiglyBT%3A%20Updates%5Bpk%3DARJPXVO5NRE3ZG4OBCWPA5I6ZXF6D2JSPDS23Q4GEPW7LRBVIC7EWLRVM2QS6ZAXR357L2B4ZPWAATQ%26ro%3D1%5D`

**Comment by o0nd7ots** [comment]
@parg I think it is already there?

**Comment by parg** [comment]
Closing as nothing's going to happen here, re-open if so desired.
