### ISSUE TITLE
Bad image scaling on Windows 10

### ISSUE THREAD

**Issue by DelScipio** [BiglySoftware/BiglyBT#16]
Interface is a mess right now. Mainly bad icon resize. Its and known issue or just my computer (Windows 10)?

**Comment by Clae224** [comment]
Are you talking about DPI scaling issues with high DPI displays? You might be able to fix that with the built in DPI settings, and some tweaking windows DPI handling for this program.

**Comment by TuxPaper** [comment]
Can you provide a screenshot, with any references to torrents blacked out? (Any posts or screenshots with torrent names, search results, subscription names, etc displaying, unless they are linux distros, will be removed)

**Comment by pmmsoares** [comment]
![snipaste_20170810_124601](https://user-images.githubusercontent.com/6597322/29167266-094d4ede-7dca-11e7-86ec-6d9e0fa2d93d.png)

Screen, I have a 15'' 1080p screen

**Comment by TuxPaper** [comment]
That's not good!

Can you try this launcher exe instead? 
https://s3.amazonaws.com/biglybt-files/installer/BiglyBT-DPIaware.exe

Save/Copy it to your BiglyBT program directory (Proabably `C:\Program Files\BiglyBT\`) and then run it.

I'm not sure if it will make a difference, so let me know if anything changes.

**Comment by pmmsoares** [comment]
No difference!
![snipaste_20170811_110221](https://user-images.githubusercontent.com/6597322/29206971-9316d4a4-7e84-11e7-8a71-dc59cdc5aaff.png)
Anything more i can help?

**Comment by RigmarRadio** [comment]
I am running BiglyBT on Windows 10 advanced Tabbed view with no problems at all.   Windows 10 is the latest Creator's version.   So far I have no bugs to report.

**Comment by Shusshu** [comment]
On a 4K display it's also very ugly

**Comment by RigmarRadio** [comment]
Ok on that.  Not a big problem and with good eyes and a good monitor I am
more than pleased that development is still going to happen on my favourite
Bit Torrent Client.   Thank you for the head up.

Malta Music Services - Rocking Malta since 2010
internationalmusicservices@gmail.com (Sales & Service)

+356 2703 0790 Office
+356 9901 1827 Mobile

HD Media/Playout system Lease to Bars, Clubs, Hotels, Receptions - anywhere
where the public will enjoy Music Video's

**Comment by parg** [comment]
If only Tux could afford a 4K monitor I'm sure the issue would be solved :)

**Comment by TuxPaper** [comment]
The biggest issue now is someone providing images 2x the size they are now.  Someday I'll dig around one of those free icon sites and try to makes sense of the usage rights.

**Comment by Clae224** [comment]
> someone providing images 2x the size they are now

I can contribute some fairly basic vector icons - I learned a bit of illustrator in my free time.

**Comment by TuxPaper** [comment]
I have added a [Desgin Graphic Assets](https://github.com/BiglySoftware/BiglyBT/blob/master/CONTRIBUTING.md#design-graphic-assets) section to our Contributing page
