### ISSUE TITLE
Jumping loads of CPU

### ISSUE THREAD

**Issue by Qwest8K** [BiglySoftware/BiglyBT#1602]
BiglyBT instantly loads CPU to 100%, holds it for literally a second or less, and then relieves the load to the value by which it constantly loads CPU.

During normal program working I can use a desctop without restrictions. But such split second loads up to 100% cause the all system to hag.

Similar loads occur several tens of times per hour. I don't think that I fully figure out their pattern, but I can say for sure that they occur, at least, when program begins to torrent (re)check and/or (re)check one of BIG files of torrent.

**Comment by parg** [comment]
Set the process priority lower? Change the hash check strategy under Files->Performance?

**Comment by hatewesterncivilization** [comment]
I had those situations before, when has having another old pc, when cpu been not so brilliant. Now with core-i5 8th's of generation cpu much colder to mentioned problem.

**Comment by Qwest8K** [comment]
@parg Changing of hash checking strategy does nothing, exept decrease\increase average CPU load. 

But lowering the priority of the process makes the situation much better. Why this function is not built into BiglyBT, and I should to do it through the task manager at every program start? Or I just did not notice it in the options?

**Comment by parg** [comment]
Unfortunately there's no built-in option for doing that :( However, you can use the 'start' command with a parameter of /low to probably do it (create a .bat file to launch BiglyBT with start /low BiglyBT.exe in it)

**Comment by Qwest8K** [comment]
Okay, but it still a crutch.

**Comment by parg** [comment]
How many active downloads do you have? 

Post the trace from Options->Startup & Shutdown: JVM memory usage history (at the bottom)

**Comment by Qwest8K** [comment]
[JMV memory usage history.txt](https://github.com/BiglySoftware/BiglyBT/files/4477978/JMV.memory.usage.history.txt)
