### ISSUE TITLE
How to migrate to BiglyBT from qBitTorrent

### ISSUE THREAD

**Issue by DXDHD** [BiglySoftware/BiglyBT#1603]
* OS Windows 10 / 8 / 7 
* BiglyBT Version 2.3.0.0
* For Windows

**Comment by hatewesterncivilization** [comment]
I think Paul or anyone else can take a look for conversion tool, qBittorent folks of course cannot do this.

**Comment by DumbJoe** [comment]
Isn't it as simple as just copying the files and folders over and then just create a new torrent for each? Or if if you still have the torrent files, then use them?

**Comment by as-muncher** [comment]
I'm transferring incomplete and complete files.
