### ISSUE TITLE
Torrents not accepted except after multipe restarts and/or multiple times downloading torrents

### ISSUE THREAD

**Issue by trapsterr** [BiglySoftware/BiglyBT#1604]
* OS and version windows 10 1909 
* BiglyBT Version Number 6.2013.0
* For *nix: Desktop Environment
[evidence.log](https://github.com/BiglySoftware/BiglyBT/files/4483025/evidence.log)
[usermessage.txt](https://github.com/BiglySoftware/BiglyBT/files/4483029/usermessage.txt)

**Comment by parg** [comment]
Download the .torrent file by hand to you hard drive and then use the File menu to open them?
