### ISSUE TITLE
Error when trying to stream a video to my LG webOS TV

### ISSUE THREAD

**Issue by amasciotta** [BiglySoftware/BiglyBT#1605]
Hello! I've bought a new LG Smart TV (coming from a Samsung Smart TV). With this new TV I can't stream any video file from BiglyBT to the TV anymore, using the integrated media streaming functionality.

If I right-click on a video file, then select the Content tab, Media Server and finally click on "Media Server: play on renderer [LG] webOS TV OLED55B9PLA", I get an error "402: Invalid Args". This was a very useful feature, especially with incomplete downloads! I was able to stream a video file while it was still downloading.

My "System" section of the Help->About window 

> Java 1.8.0_202 (64 bit)
>   Oracle Corporation
> c:\program files\biglybt\jre
> 
> SWT v4930r7, win32, zoom=100, dpi=96
> Windows 10 v10.0, amd64 (64 bit)
> B2.3.0.0/4 az3

**Comment by parg** [comment]
Can you do this the from the TV rather than from BiglyBT? 

Find the TV in the BiglyBT sidebar under Devices and then drag+drop the video from the BiglyBT library to the sidebar entry.

Then on the TV locate the BiglyBT 'source' and browse it to find the video.

Unfortunately it is hard to diagnose device specific errors like the one you are encountering without having access to them.

**Comment by parg** [comment]
Glad it works!

Perhaps you could reproduce the original problem and look in the log by going to 

Tools->Plugins->LogViews->Media Server

and see if there are any more clues there. 

It is possible that some kind of authorisation is required to allow something to play content on the TV and that is resulting in the error, but that's just a guess...

**Comment by amasciotta** [comment]
The log reports this message:

> [18:39:05] Renderer: Preparing for connection to '[LG] webOS TV OLED55B9PLA'
> [18:39:05] Renderer: Setting transport URI
> [18:39:05] [4] Streaming starts for <filename>  [complete file] - Neptune/1.1.3/192.168.1.145
> [18:39:05] [4] Streaming ends for <filename>: read 0 B, delivered 0 B
> [18:39:06] Renderer: Play operation failed: Invoke of 'urn:schemas-upnp-org:service:AVTransport:1#SetAVTransportURI' failed - fault reported: Invalid Args

Could the the debug.zip package (created from the Help menu) help?

**Comment by parg** [comment]
I don't think the debug.zip would include anything more that you pasted above :( The problem is that 'Invalid Args' could mean absolutely anything and is generated by the TV, so unless the TV itself has some form of logging it is hard to work on

**Comment by parg** [comment]
If you did want to try and diagnose the problem the best approach would be to find some other product that can successfully send a video to the TV to play it and then install an application like WireShark to capture the network traffic so that it can be compared against the failing BiglyBT traffic.

I found https://github.com/UniversalMediaServer/UniversalMediaServer/issues/758 while searching for similar issues but I don't think that applies in this case.

**Comment by parg** [comment]
Also https://stackoverflow.com/questions/28422609/how-to-send-setavtransporturi-using-upnp-c that mentions LG

**Comment by parg** [comment]
Also does it fail with different container types (.mkv, .avi, .mp4 etc)?

**Comment by amasciotta** [comment]
The problem occurs with mkv, avi and mp4 video file. Using WireShark, I've managed to capture the traffic between my PC and the TV. I've compared BiglyBT trying to stream with the Windows 10 built-in function (right click on a file and then "Stream to device").

BiglyBT sends much less messages than Windows, but the one that receives an non-OK response is the following one:

```
<?xml version="1.0" encoding="utf-8"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
  <s:Body>
    <u:SetAVTransportURI xmlns:u="urn:schemas-upnp-org:service:AVTransport:1">
      <InstanceID>0</InstanceID>
      <CurrentURI>http://192.168.1.151:58241/Content/FBFD9993E3BBD8DF58AF28E840207C7D90C73734-0.mkv</CurrentURI>
      <CurrentURIMetaData>&lt;DIDL-Lite xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot; xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot;&gt;&lt;item id=&quot;0&quot;&gt;&lt;dc:title&gt;filename.mkv&lt;/dc:title&gt;&lt;dc:creator&gt;Unknown&lt;/dc:creator&gt;&lt;dc:date&gt;2020-03-29&lt;/dc:date&gt;&lt;upnp:class&gt;object.item.videoItem.movie&lt;/upnp:class&gt;&lt;res protocolInfo="http-get:*:video/x-matroska:*" size="27653088306" resolution="640x480"&gt;http://192.168.1.151:58241/Content/FBFD9993E3BBD8DF58AF28E840207C7D90C73734-0.mkv&lt;/res&gt;&lt;res protocolInfo="http-get:*:video/x-mkv:*" size="27653088306" resolution="640x480"&gt;http://192.168.1.151:58241/Content/FBFD9993E3BBD8DF58AF28E840207C7D90C73734-0.mkv&lt;/res&gt;&lt;res protocolInfo="http-get:*:video/x-matroska:DLNA.ORG_PN=MATROSKA;DLNA.ORG_OP=01;DLNA.ORG_FLAGS=01500000000000000000000000000000" size="27653088306" resolution="640x480"&gt;http://192.168.1.151:58241/Content/FBFD9993E3BBD8DF58AF28E840207C7D90C73734-0.mkv&lt;/res&gt;&lt;res protocolInfo="http-get:*:video/x-mkv:DLNA.ORG_PN=MATROSKA;DLNA.ORG_OP=01;DLNA.ORG_FLAGS=01500000000000000000000000000000" size="27653088306" resolution="640x480"&gt;http://192.168.1.151:58241/Content/FBFD9993E3BBD8DF58AF28E840207C7D90C73734-0.mkv&lt;/res&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;</CurrentURIMetaData>
    </u:SetAVTransportURI>
  </s:Body>
</s:Envelope>
```

which gets this response from the TV:

```
<?xml version="1.0" encoding="UTF-8"?>
<s:Envelope s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns="urn:schemas-upnp-org:control-1-0"><errorCode>402</errorCode><errorDescription>Invalid Args</errorDescription></UPnPError></detail></s:Fault></s:Body></s:Envelope>
```

The corresponding message from Windows (the only one that contains the string `SetAVTransportURI`) is the following:

```
<?xml version="1.0"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><SOAP-ENV:Body><m:SetAVTransportURI xmlns:m="urn:schemas-upnp-org:service:AVTransport:1"><InstanceID xmlns:dt="urn:schemas-microsoft-com:datatypes" dt:dt="ui4">0</InstanceID><CurrentURI xmlns:dt="urn:schemas-microsoft-com:datatypes" dt:dt="string">http://192.168.1.151:10246/MDEServer/9CE96BC8-E3B0-4AE0-8C0C-2FFCF107A5F6/1000.mkv</CurrentURI><CurrentURIMetaData xmlns:dt="urn:schemas-microsoft-com:datatypes" dt:dt="string">&lt;DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/" xmlns:microsoft="urn:schemas-microsoft-com:WMPNSS-1-0/" xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/"&gt;&lt;item id="1000" restricted="1" parentID="0" microsoft:cpId="{93E11DF5-21AA-4B7A-B625-831578BDA4F7}" microsoft:trackId="1"&gt;&lt;dc:title&gt;filename&lt;/dc:title&gt;&lt;res size="24294418524" duration="2:37:05.625" bitrate="2577486" resolution="3840x2160" protocolInfo="http-get:*:video/x-matroska:DLNA.ORG_FLAGS=01700000000000000000000000000000" sampleFrequency="48000" bitsPerSample="16" nrAudioChannels="6" microsoft:codec="{43564548-0000-0010-8000-00AA00389B71}"&gt;http://192.168.1.151:10246/MDEServer/9CE96BC8-E3B0-4AE0-8C0C-2FFCF107A5F6/1000.mkv&lt;/res&gt;&lt;upnp:class&gt;object.item.videoItem&lt;/upnp:class&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;</CurrentURIMetaData></m:SetAVTransportURI></SOAP-ENV:Body></SOAP-ENV:Envelope>
```

which instead gets this response:

```
<?xml version="1.0" encoding="UTF-8"?>
<s:Envelope s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><u:SetAVTransportURIResponse xmlns:u="urn:schemas-upnp-org:service:AVTransport:1"/></s:Body></s:Envelope>
```


The content of both messages is unaltered, except for the filename which I've redacted.

**Comment by parg** [comment]
Hmm, interesting! There are quite a few differences, hard to know which is/are the significant ones. I'm guessing it is something to do with the embeded DIDL-Light fragment. BiglyBT has some escaped &quote; entries where MS doesn't. Also the DLNA.ORG_FLAGS are different. I'll look into making some changes and get you something to test with! Thanks

**Comment by parg** [comment]
I've attached an updated azupnpav.jar (had to rename it to .zip to upload it, simply rename it to 'azupnpav_0.6.7.jar' and replace the one in the azupnpav plugin directory (when Bigly isn't running!)

The changes I made were
1) don't escape " with &quote;
2) added two boiler place parameters to the DIDL-Lite item

I didn't fiddle with the ORG_FLAGS and other things yet, let's see if this helps!

[azupnpav.zip](https://github.com/BiglySoftware/BiglyBT/files/4496748/azupnpav.zip)

**Comment by amasciotta** [comment]
IT WORKS! I can now stream a file like before, by right-clicking on it and then hitting "Play on renderer..."! Thank you!

Another problem that I noticed is that there seems to be no way to move along the track. I've tried two ways, neither of them worked:
1. the pinpoint on the progress bar of the video can be moved back and forth with my TV remote, but when I click the OK button to confirm the new desired plyaback position, the TV displays a message saying that "This is feature is not available at the moment", and nothing happens;
2. the backward and fastforward buttons on the screen (the one like << and >>) seem to have no effect on the playback speed: when I press them, the screen show the 2x or 4x multipliers, but the playback speed is not modified. Sometimes those two buttons are even grayed out!

Do you think that this problem is related to the original one that I reported and that you brilliantly solved? Can I help again in some way with WireShark?

**Comment by parg** [comment]
I really don't know much about the seeking/speed aspects of DLNA - we have a very basic media server, for example it doesn't know anything about a video's actual metadata or container format etc - all it supports is byte-range operations on the video file. So I don't think there is much that can be done to addresses these shortfalls.
