### ISSUE TITLE
Re-Adding/Discovering a deleted device/renderer

### ISSUE THREAD

**Issue by DenverArmo** [BiglySoftware/BiglyBT#1606]
Hi Y'all... Newbie here...

I had just switched the Samsung TV from wireless to wired to see if it would help with the buffering issue I was experiencing. When the transcoded movies no longer showed, I deleted the resource/renderer. Then rebooted my PC and pulled power from the TV so that both were reset. how can I re-add it or force BiglyBT to rediscover it? I can not find that option in any of the menu's. Thank you in advance for your help.

**Comment by parg** [comment]
Must be a networking issue - BiglyBT and the device have to be able to discover each other, you can't manually make this happen, your network has to be configured so that UDP multicast messages are routed between them. Generally that means they have to be on the same network segment and firewalls/AV products have to permit communication.

**Comment by DenverArmo** [comment]
Parg... thanks for your quick reply... but, it is not a networking issue. BiglyBT see's other devices on the network as they are turned off and on... 

Any other idea's? Maybe reinstall BiglyBT to force it to rediscover deleted devices/renderers?

**Comment by DenverArmo** [comment]
A few more things I have tried so far...
-- turned off firewall and a/v on the machine that has BiglyBT(i know, not smart, but my network is behind a firewall and router) - No Change
-- reinstalled BiglyBT - No Change
-- uninstalled UPnP plug in
-- reinstalled UPnP plug in - No Change
-- went through all the setting and found a place to reset all removed devices - No Change

can not find anything else to check/change to get my Samsung TV listed in the devices/renders list again... sigh...

**Comment by parg** [comment]
Did you try switching the TV back to a wireless connection? Also right-click on the Devices entry in the sidebar and see if the 'show hidden devices' option is enabled - if so click it and see if that helps.

**Comment by DenverArmo** [comment]
Prag... you are the man... thank you... This time when I right clicked on Devices\Renderers, the app did give a menu that had 'show hidden devices' and viola, the device is there. 

Also figured out a way to connect to BiglyBT as an input and found the folder to put the movies in to view directly from the TV.

**Comment by parg** [comment]
\o/
