### ISSUE TITLE
Bug when max connection reached?

### ISSUE THREAD

**Issue by Makidb** [BiglySoftware/BiglyBT#1607]
Java 1.8.0_241 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_241

SWT v4930r7, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B2.3.0.0/4 az3

Hello
Maybe i'm wrong but it looks like as soon as the max connection numbers is reached (or exceed), some bug happens & everything stops

Some history
With my previous computer i had a lot of problems with biblyBT, always stuck at some point & took a lot of time to close
I was on windows 10 too
Now i have a new computer & everything was fine until today
But i kept the connection number pretty low & i may had some issues but i thought it was my ISP
Today same problem, everything stopped & impossible to close

I checked the logs & i found the max connection was reached just before everything goes wrong

I tried to lower the count in the settings to see
Same problem occured very fast, everything stops
I tried to add more connection allowed & then everything restarted

So i think there is some issue when the client reach the max connection

**Comment by parg** [comment]
Interesting - if you can reproduce the problem and then follow the instructions here:

https://github.com/BiglySoftware/BiglyBT/wiki/Diagnostics

(the top bit to get diagnostics when hung) that would help.

I just experimented with a global connection limit of 1 but things seemed to work ok

**Comment by Makidb** [comment]
I'll do that asap, so later today

**Comment by Makidb** [comment]
After some test i can't get the same issue
So it must be something else, i tried to increase a memory setting but i have to admit i understand nothing in those settings
If this happens again i'll check the logs
It's really strange how all stops sometimes
Thx & i guess you can close this

**Comment by parg** [comment]
Are you saving downloads to a USB or network drive? You seem to be encountering some slow disk writes that might be triggering that memory issue.  You could try increasing the Java memory available via Options->Startup & Shutdown - Java options

**Comment by Makidb** [comment]
Indeed, i use a usb disk
I increased the memory setting already & so far no problem
Thanks, i close this issue cause looks like the issue was me
