### ISSUE TITLE
Ubuntu 20.04 KDE Plasma 5.18.4, white fonts on white background in settings, and in context menus of torrents

### ISSUE THREAD

**Issue by trancephorm** [BiglySoftware/BiglyBT#1609]
Ubuntu 20.04
KDE Plasma 5.18.4
BiglyBT 2.3

Java 11.0.7-ea (64 bit)
/usr/lib/jvm/java-11-openjdk-amd64

SWT v4924r25, gtk/3.24.17, zoom=100, dpi=160
Linux v5.4.0-24-generic, amd64 (64 bit)
B2.3.0.0/4 az3

See the screenshot: https://imgur.com/a/tEM2Js1
Text is unreadable, any way to fix this?

**Comment by kevinlekiller** [comment]
Using breeze gtk should fix these issues: https://github.com/KDE/breeze-gtk

Once installed, in System Settings, go to Application Style, click Configure GTK/Gnome Application Style, select Breeze or Breeze Dark in the dropdown list.

**Comment by trancephorm** [comment]
That would be it, thanks!
