### ISSUE TITLE
Settings tab renders too wide in Tags Overview

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#1612]
The tag settings interface in the "Settings" tab of the Tags Overview display seems to be laying out based on the width of the entire window, rather than the available width.<sup>1</sup> Additionally, it seems there's no way to scroll that pane horizontally. (Unlike, say, the table in the Torrents tab, which will have a horizontal scrollbar if it's wider than the available space.) As a result, unless I'm missing something it seems the only way I can view the entire Tags Overview > Settings interface is by temporarily closing the sidebar. 

Interface with sidebar open:
![image](https://user-images.githubusercontent.com/538020/79642561-25de5400-816c-11ea-87f7-a38cdd11387e.png)

After hitting <kbd>F7</kbd>:
![image](https://user-images.githubusercontent.com/538020/79642577-3e4e6e80-816c-11ea-9008-6f3dcc565def.png)

It's weird, too, because as you can see the _pane_ itself is sized correctly — its minimize button is always visible on the right. It's just the contents of the Settings tab pushing out beyond that width.

#### System block
```
Java 1.8.0_242 (64 bit)
  Oracle Corporation
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.fc31.x86_64/jre

SWT v4930r7, gtk/3.24.13, zoom=100, dpi=96
Linux v5.5.16-200.fc31.x86_64, amd64 (64 bit)
B2.3.0.1_B24/4 az3
```

#### Notes
1. (Or it could just be coincidence, maybe that's its minimum width. "Transfer Settings" does seem awfully tight.<sup>2</sup> But I can't help but notice that the tab fits perfectly in the window if I close the sidebar, which doesn't _feel_ like a coincidence.)
2. Heh, I wrote that looking at it with the sidebar _open_, but as my second screenshot indicates, there's even unused width in "Transfer Settings". So, it's definitely not a space-constraint thing.

**Comment by parg** [comment]
Funny you should mention it, just today I was cursing at those settings. I'll take a look :)

**Comment by ferdnyc** [comment]
I guess not really surprising, now that I think about it, since we were probably both there for the same reason: something to do with the #209 convo. :laughing:

**Comment by ferdnyc** [comment]
Fixed a bunch of beta updates ago, thanks @parg !

The layout's still really wide (those darn max speed labels). And it's too bad the File Settings paths and the tag Name field expand horizontally, because everything on their right side gets pushed out into the overflow area.

But now I can scroll right to reach the parts that don't fit in the window, which is fine. Especially considering I rarely even look at these settings.
