### ISSUE TITLE
Initialize the Kern debian 10.3 (x86-64)

### ISSUE THREAD

**Issue by MrOnyx** [BiglySoftware/BiglyBT#1614]
I installed BiglyBT on debian on startup a message appears 
initialize the kern and it will also hang
and does not start

* OS and version debian 10.3 (x86-64)
* Linux-Kernel 4.19.0-8-amd64
* BiglyBT Version Number 2.3.0.0
* java version "14.0.1" 2020-04-14

**Comment by parg** [comment]
Extreme Mod? Go ask on their forums.
