### ISSUE TITLE
Auto shutdown when finished downloading does not work

### ISSUE THREAD

**Issue by joliett1234** [BiglySoftware/BiglyBT#1615]
* OS and version  Win10
* BiglyBT Version Number B2.3.0.0/4 az3

Hi...
Auto shutdown when downloading is complete does not work...it worked for months, but suddenly stopped working.  I deleted the BiglyBT working file in username, appdata, Roaming, and restarted BiglyBT but still no computer shutdown...

**Comment by parg** [comment]
Do you get any alert in BiglyBT saying that it is about to shut down the computer? It should be shown when downloading is complete and also logged to the alerts_1.log (or alerts_2.log) file in <roaming>\BiglyBT\logs

**Comment by parg** [comment]
Oh, and if there are *any* paused downloads then it won't trigger

**Comment by joliett1234** [comment]
No alerts..

**Comment by joliett1234** [comment]
No  paused downloads.

**Comment by parg** [comment]
Active metadata downloads?

**Comment by parg** [comment]
It has to have been actively downloading for over a minute or so before the action will be considered. I just did a test (with action=shutdown BiglyBT) and it worked fine

**Comment by joliett1234** [comment]
It worked fine for me for months. I actively download a large torrent file
and go to bed. In the morning, usually BiglyBT would be finished
downloading and the computer would be off. The last week, the computer has
been on and Bigly was finished downloading. Nothing else was downloading or
running.

**Comment by joliett1234** [comment]
Hi!
Well you were right about the downloading needing over a minute for the
auto shutdown action to be considered.  I was testing the program with my
forced torrent completions.
Last night I tried with a real running download and it worked fine.
Deleting the Biggly working file in appdata fixed it!

Thank you for your support...


*❤*

*Joel*

**Comment by parg** [comment]
Good to know!
