### ISSUE TITLE
beta upgrade restarts & Dime seeding limit issue

### ISSUE THREAD

**Issue by coyote3** [BiglySoftware/BiglyBT#1616]
When I switched to the betas I was intrigued by the shutdown popup.  I thought 'maybe this will help it pick up where it left off when seeding torrents?'

And maybe it has, but maybe that's causing an issue I didn't anticipate.

One of the best things about BiglyBT is it's ability to serve torrents as demand calls for because that allows me to live within the limit that dimeadozen.org has on simultaneously seeding torrents.  (I preach on Dime that this makes BiglyBT **the** client for Dime.)

But when the betas restart for an upgrade, I end up with tracker errors from a huge number of torrents saying that they're exceeding dime's limit.

So I guess BiglyBT isn't telling the Dime tracker that the torrents have disconnected, or something.  (As I understand it, it takes a while for the dime tracker to dime out torrents that don't let it know they've left.)

Any advice, please?

**Comment by parg** [comment]
Is the shutting-down-tracker time limit sufficient? The default is 5 seconds which isn't a massive amount of time, check Options->Tracker->Client for this setting. There's the new 'Trackers' tab under Statistics that shows tracker activity - if you open this view and then manually restart BiglyBT you can observe what's going on.

**Comment by coyote3** [comment]
In "Options->Tracker->Client" I see 
"Maximum time to wait for trackers on closedown (secs)" is set to the default 5 seconds.

Is this per torrent?  I have like 600 Dime torrents.

(Oh, on that screen I can't figure out if "But don't scrape torrents that have never been started" is enabled or disabled by default; I think I may have disabled it by an inadvertent click, but I didn't save and shut down and waited and started, but it's still disabled.)

On that Trackers tab it looked like the Dime torrents were "Update Rates" were all fast, all under 1/3 second maybe averaging a tenth of a second.

Here's a printscreen of a moment a Dime torrent was in the popup, near-ish the end of the Restart.
![BiglyBT-RestartStatisticsTab](https://user-images.githubusercontent.com/30500973/80285529-845e8180-86da-11ea-9abd-00fc6357101f.jpg)

**Comment by parg** [comment]
The time-to-wait is overall, not per-torrent. The 'Operation In Progress' window will first show the downloads being saved, then stopped, then it progresses onto 'waiting for tracker updates' before 'finalizing shutdown' and then exiting. The 'waiting for tracker updates' is the bit of interest - when it is doing this it is running all of the 'stopped' messages sent to you active download's trackers. The Trackers stats tab currently shows you with 47 scheduled private tracker updates. You would want that to go to zero before the 'waiting for tracker updates' phase of closedown completes. 

There are two ways to affect things. Firstly there is the tracker-update-concurrency, default value 32. Increasing this means you will hit more updates in parallel - thus decreasing the overall time taken to process the updates. Secondly by increasing the time BiglyBT waits for the updates to be processed. I would suggest you increase the 5 seconds to 30 seconds and see how that goes.

**Comment by coyote3** [comment]
Thanks parg, I tried a couple times and got printscreens each time of the Shutdown phase.  However upon restart the problem didn't occur either time.  So I'm very puzzled; I changed no settings; I guess my 'watched pot didn't boil' either time.  Should the issue ever occur again I'll know how to monitor it.

But for now, I just have these printscreeens of the private tracker updates quickly diving down to zero...which I guess means little since I couldn't replicate the issue.
![BiglyBT-Finalizing-Closedown](https://user-images.githubusercontent.com/30500973/80327291-726f0280-87f0-11ea-9fad-924a8468734b.jpg)
![BiglyBT-Finalizing-Closedown2](https://user-images.githubusercontent.com/30500973/80327298-77cc4d00-87f0-11ea-9a6a-b7b9ce841e0c.jpg)

**Comment by parg** [comment]
Often the way with them kettles :)

**Comment by nokti** [comment]
> One of the best things about BiglyBT is it's ability to serve torrents as demand calls for because that allows me to live within the limit that dimeadozen.org has on simultaneously seeding torrents. (I preach on Dime that this makes BiglyBT **the** client for Dime.)

Would you mind sharing your queuing settings for BiglyBT. I'm trying to set it up for use with Dime but can't seem to find the proper settings. Torrents either end up queued or "not authorized" (I have more than the 40 torrents limit).

**Comment by coyote3** [comment]
Here's printscreens of my relevant settings:
https://i.imgur.com/Bv1DdC4.jpg

**Comment by nokti** [comment]
> Here's printscreens of my relevant settings:
> https://i.imgur.com/Bv1DdC4.jpg

That didn't work for me, almost all torrents ended up in a queued state and I was not visible as a seeder on the tracker. So I tried tweaking those settings and I think I found something that's close to what I was aiming for:

- a maximum of 40 simultaneous seeding torrents
- a rotation between torrents so I can overcome the limit above
- no warning message from the tracker telling me I am over the 40 limit

![BiglyBT Queueing Settings](https://user-images.githubusercontent.com/58652818/81156672-7c2dfe00-8f86-11ea-8ae9-425e14a25d5b.png)

Out of 55 torrents loaded, 40 are active, 15 queued. And the seeding torrents are rotated, every 600 seconds if I understand correctly. What I still have to do is raise the Timed Rotation Option so I don't get disconnected while a peer is downloading from me. 600 sec (10 mn) seems too short, some people have a really slow download speed.

What I'd like to have is a first priority rule for torrents with a ratio **over** a certain limit, so popular torrents are seeded first. Atm it's the less popular (ratio **under** 0.5 is the minimum available) that get first priority.

**Comment by parg** [comment]
You can use Tags to set first-priority - https://github.com/BiglySoftware/BiglyBT/wiki/Tags

Use a tag constraint to assign the downloads you want to a Tag (based on ratio or whatever) and mark that Tag as 'first priority seeding'

**Comment by nokti** [comment]
> Use a tag constraint to assign the downloads you want to a Tag (based on ratio or whatever) and mark that Tag as 'first priority seeding'

This looks like what I'm looking for, thanks :) What would be the correct command? With `isGE( shareratio >= 1.0 )` I'm getting an invalid parameter warning.
(Sorry I have no idea what `isGE, isGT, isLE, isLT, isEQ, isNEQ` mean, this is way above my meager tech knowledge!)

**Comment by parg** [comment]
heh, yeah, the 'isGE(a,b)' was the old way of doing it before 'a >= 'b' was supported

**Comment by coyote3** [comment]
_"seeding torrents are rotated, every 600 seconds if I understand correctly. What I still have to do is raise the Timed Rotation Option so I don't get disconnected while a peer is downloading from me."_

Purely out of curiosity, nokti, why even select "Timed Rotation" (instead of Peers:Seed ratio as I do which sounds like it prioritizes swarm health)?

Incidentally, in an off-thread exchange nokti explained that the torrents which "ended up in a queued state" had no peers.  (Which is exactly what I want and what I think makes BiglyBT **The Client** for Dime.   Because I can enable "Ignore Torrents with 0 peers" and not have my Dime limit of seeding torrents taken up by torrents without any peers, and the limit can instead be fully utilized by only torrents with peers among my billion Dime torrents.)

**Comment by nokti** [comment]
> Purely out of curiosity, nokti, why even select "Timed Rotation" (instead of Peers:Seed ratio as I do which sounds like it prioritizes swarm health)?

Because I think that if I choose someting else than a time rotation some torrents will remain queued and never seeded. Timed rotation insures that all the torrents in the client get a chance to be seeded for some time regardless of whether they have peers or not. 

> What I still have to do is raise the Timed Rotation Option so I don't get disconnected while a peer is downloading from me.

In the end I didn't do that. Raising the Timed Rotation Option caused me to overshoot the 40 torrents limit. The priority tag explained by @parg above was a better solution.

> Because I can enable "Ignore Torrents with 0 peers" and not have my Dime limit of seeding torrents taken up by torrents without any peers,

I understand why you'd want to do that. But if I understand this correctly (I've only been using BiglyBT since yesterday so forgive me if I'm wrong), ignoring torrents without peer makes you invisible to the tracker for those torrents. Which also means invisible to someone trying to download. To be visible I think the client needs to announce to the tracker. Or is there a way for the client to know that there's suddenly a peer on a torrent that previously had none and take that torrent out of queued state and into seeding state? For me it's seems impossible without the client announcing to the tracker. But I may be wrong, I don't know how the client-tracker communication works.

**Comment by coyote3** [comment]
_"I understand this correctly (I've only been using BiglyBT since yesterday so forgive me if I'm wrong), ignoring torrents without peer makes you invisible to the tracker for those torrents."_

First, it's BiglyBT that needs to know when the peer appears on a torrent.  And I think the technical term for that is that the client 'scrapes' the tracker for this info.  Because somehow, BiglyBT knows how many peers there are on my billion queued Dime torrents too.

**Comment by parg** [comment]
Right, BiglyBT scrapes the tracker of inactive downloads periodically to see if there are peers. If a peer appears constraints such as 'zero peers' will no longer be true in the seeding rules and that download will be scheduled to start seeding. 

Obviously these scrapes don't occur very frequently so there will be a period when the peer is registered but not yet detected by BiglyBT.

**Comment by coyote3** [comment]
In our off-thread exchange I suggested (in the testing nokti is doing running a separate client) that nokti "Update Tracker" for the torrent the other client has started.  I just tested that on a Queued torrent; it remained Queued and I presume it scraped.

Anyway, nokti I'm confident it works because it has for me for most of two decades.  It's been so dependable I never bothered to test it with another client.

**Comment by nokti** [comment]
> Obviously these scrapes don't occur very frequently so there will be a period when the peer is registered but not yet detected by BiglyBT.

That would explain some of the interactions that I've observed on Dime, with a seeder suddenly appearing when the tracker previously said none. Is it possible to know how often BiglyBT scrape trackers? Is it at fixed times? Or does it depend on several variables?

Thank you @parg and @coyote3 for the clarifications. I will have plenty of spare time tomorrow morning to do more testing and report back.

**Comment by coyote3** [comment]
I wish everyone on Dime understood this functionality.  I bring it up every time someone asks me for a seed, and mention it when relevant on the Dime mailing list, because BiglyBT can do this without me ever being involved.
