### ISSUE TITLE
[enhancement] Register default magnet uri handler

### ISSUE THREAD

**Issue by Technetium1** [BiglySoftware/BiglyBT#1617]
When I click on a `magnet:` link I have no way to select BiglyBT. This can be fixed with registry keys.

These examples assume the install path is `C:\Program Files\BiglyBT\BiglyBT.exe`
* Always backup before making changes!
* To launch magnet uri with BiglyBT:
Set the default string key in: `[HKEY_CLASSES_ROOT\magnet\shell\open\command]`
to: `"C:\Program Files\BiglyBT\BiglyBT.exe" "%1"`
* To use the correct icon:
Set the default string key in `[HKEY_CLASSES_ROOT\magnet\DefaultIcon]`
to: `"C:\Program Files\BiglyBT\BiglyBT.exe",1`

**Comment by parg** [comment]
It already registers itself:

https://github.com/BiglySoftware/BiglyBT/blob/master/core/src/com/biglybt/platform/win32/PlatformManagerImpl.java#L1618

Perhaps this is failing for some reason - there is a button to press to re-register the association under Options->Interface (near the bottom)

**Comment by Technetium1** [comment]
@parg Thanks for the quick response. I looked for that button and somehow glossed over it. I can click and it will reset the defaults for _all_ types to Bigly as intended. I somewhat expected that option to be in Startup/Shutdown over interface; but as long as it works that's enough for me!

**Comment by parg** [comment]
No problem! It is supposed to prompt if the associations aren't there (unless disabled by the user) so not sure why that didn't work for you.
