### ISSUE TITLE
Ignoring failure reason?

### ISSUE THREAD

**Issue by proton-ab** [BiglySoftware/BiglyBT#162]
Simple but important thing - despite 'failure reason' being present in announce response, BiglyBT shows 'OK' status for tracker in question.

This causes users to be unaware of any messages coming from tracker or simply the fact that tracker is not working. Important for private trackers where 'failure reason' may include additional information like torrent deletion reason.

Example response:
`d14:failure reason27:Your client is not approved8:intervali3600e12:min intervali3600ee`

Do note that while strictly, including interval and min interval along with failure reason is against specs, it is useful as other clients use this and it can be used to minimize downtime.

**Comment by parg** [comment]
I'll change things to always respect a reported 'failure reason' even if interval/min interval is included
