### ISSUE TITLE
Request: Moving Subfolder line in Add Torrent window

### ISSUE THREAD

**Issue by almanteka** [BiglySoftware/BiglyBT#1621]
![subfolderbiglybt2](https://user-images.githubusercontent.com/42816936/80658055-19eb6f80-8a53-11ea-8a22-da0d1d74df4d.jpg)

* OS and version = Windows 10 Pro Version:1909 Build:18363.778 
* BiglyBT Version Number = 2.3.0.1_B29
 
is there is any way to resize the subfolder name area of the add torrent window? i like to edit the subfolder names because sometimes the names are too long, but even when I maximize the window, the subfolder area is too little to edit! photo included showing what i mean. maybe moving the subfolder line below the Save Location or the option to adjust the length between the Save Location line & Subfolder. thanks!

**Comment by parg** [comment]
I'll see what I can do, thanks

**Comment by almanteka** [comment]
WOW! you're FLASH! already on version 2301_B30 you've included a solution: "Make subfolder in open-torrent-options scale with window size"! thank you!!! i'm going to test it out with those torrents with large names!
