### ISSUE TITLE
Double clicking torrents opens wrong app

### ISSUE THREAD

**Issue by MarathonZephead** [BiglySoftware/BiglyBT#1622]
Hi

When I double click a torrent, it opens with FileMail Desktop instead of XYplorer (Windows replacement app).

Can you please advise how I associate it with the correct app?

Many thanks!

**Comment by parg** [comment]
You want it to open with XYplorer?

If you want a .torrent file to open BiglyBT then Options->Interface and hit the button near the bottom to reset file associations.

**Comment by MarathonZephead** [comment]
Hi parg, thanks for replying :-)

I want to view the containing folder in XYplorer (an alternative to Explorer) which it has done OK since I installed BiglyBT but ever since I installed FileMail Desktop double clicking a torrent runs that app instead!

**Comment by MarathonZephead** [comment]
Hi I just clicked 'reset' as you suggested and Save, closed and restarted but I have the same problem :-(

**Comment by parg** [comment]
Uninstall FileMail Desktop? Ask XYplorer for support regarding how their application associations work? It isn't something you can solve within BiglyBT unfortunately.

**Comment by parg** [comment]
Does right-clicking a download and selecting 'show in explorer' work?

**Comment by MarathonZephead** [comment]
Unfortunately I need to use FileMail Desktop for a different purpose else I would certainly do that.

I right clicked a torrent and selected 'Open Containing Folder' but it just did the same thing i.e. opened FileMail Desktop.

**Comment by MarathonZephead** [comment]
I just unchecked 'Use XYplorer as the default file manager' i.e. revert to Explorer and the torrents open fine in Windows - so this is a conflict between FileMail and XYplorer.

Thanks for your help!
