### ISSUE TITLE
Can we allow biglybt to use default java set on system?

### ISSUE THREAD

**Issue by a8underscore** [BiglySoftware/BiglyBT#1627]
I have java 14 as my default java, can I change biglybt to use that?

or at least java 11

I am on macOS 10.15.4

**Comment by parg** [comment]
BiglyBT runs fine on Java 11...14 on Windows at least (https://github.com/BiglySoftware/BiglyBT/wiki/Command-Line-Options). You would need to figure out a script to do the same on OSX (I can have a look later if I have time)

**Comment by a8underscore** [comment]
Thanks, I tried that but I couldn’t find where the jar was :/

**Comment by parg** [comment]
I updated https://github.com/BiglySoftware/BiglyBT/wiki/Command-Line-Options with details of how to do it.

Note the issue with restarts

**Comment by a8underscore** [comment]
Thank you! I will close this issue when I get to my computer or you can just close it.

**Comment by a8underscore** [comment]
it launched in some sort of dark mode? was it supposed to do that? 
![Screen Shot 2020-05-03 at 1 34 36 PM](https://user-images.githubusercontent.com/60801647/80925230-e8b8bb00-8d42-11ea-9c3f-7143426654d8.png) is this a new feature?

**Comment by parg** [comment]
Ah, yes. If you have your system set to dark mode then you'll end up with what you see (beta dark mode support). Normally BiglyBT has plist preferences set to not use dark mode as there's work to be done, but if you launch it manually then you'll get it anyway. Not sure off the top of my head how to force non-dark mode.

**Comment by a8underscore** [comment]
thanks
