### ISSUE TITLE
Old torrent .DS_Store suddenly modified, un-completed

### ISSUE THREAD

**Issue by g5ppc** [BiglySoftware/BiglyBT#1629]
On startup, some long term torrent Status showed their data was unavailable.  Investigation showed that these torrents included a .DS_Store file.  That file had been user writable.  Only now did something happen in BiglyBT that caused this .DS_Store to be touched, and truncated to zero.  I was able to correct this, and block writing to the .DS_Store files.

However, if this is a BiglyBT bug it should be fixed because of the potential to permanently '99%' old torrents.  If this isn't a BiglyBT bug, then I've corrected the underlying problem with writability for myself.

Java 8u251 in Win8.1 x64.
B2.3.0.0/4 az3

**Comment by parg** [comment]
BiglyBT doesn't do anything .DS_Store files, those are Mac/OSX hidden files updated by OSX. Did you share the torrent data location with a Mac at some point.

BiglyBT also doesn't mess with downloaded file's writeability - it's up to the user if they want to make things read-only.
