### ISSUE TITLE
Updates stuck at 1201-B13

### ISSUE THREAD

**Issue by kwloafman** [BiglySoftware/BiglyBT#163]
OK, so B14 is out and I have been updating solidly for a while.  Today it decided to stick and not do an update.  It will not update from B13 to B14.  I even did a manual update and got the new jar file.  It shows B14 on the GUI, but when I look at the updater log, it still thinks I'm on B13.

`Java 1.8.0_151 (64 bit)
  Oracle Corporation
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home

SWT v4528, cocoa
Mac OS X v10.13.1, x86_64 (64 bit)
B1.2.0.1_B14/4 az3`

`Checking for Updates - added
Checking for Updates
    BiglyBT Core -     Core: latest_version = '1.2.0.1_B13', file = 'http://version.biglybt.com/biglybt-files/core/BiglyBT1201-B13-signed.jar.torrent?i2p=1'
    BiglyBT Core - Finished
    SWT library -     SWT: current version = 4528, latest version = 4528
    SWT library - Finished
    Platform-specific support -     OSX: current = 1.12, latest = 1.12
    Platform-specific support - Finished
    Mandatory plugins -     Loading details for azupdater/BiglyBT Update Support
    Non-mandatory plugins -     Loading details for azitunes/BiglyBT iTunes Integration
    Mandatory plugins -         current=2.1_CVS, latest=2.1_CVS
    Mandatory plugins - Finished
    Non-mandatory plugins -         current=0.4_CVS, latest=0.4_CVS
    Non-mandatory plugins -     Loading details for azlocprov/Location Provider
    Non-mandatory plugins -         current=0.2.2_CVS, latest=0.2.2_CVS
    Non-mandatory plugins -     Loading details for azmsgsync/Message Sync Support
    Non-mandatory plugins -         current=0.8.3_CVS, latest=0.8.3_CVS
    Non-mandatory plugins -     Loading details for 3dview/3D View
    Non-mandatory plugins -         current=0.5.2_CVS, latest=0.5.2_CVS
    Non-mandatory plugins -     Loading details for azrating/Rating
    Non-mandatory plugins -         current=1.6.6_CVS, latest=1.6.6_CVS
    Non-mandatory plugins -     Loading details for azupnpav/UPnP Media Server
    Non-mandatory plugins -         current=0.6.5_CVS, latest=0.6.5_CVS
    Non-mandatory plugins -     Loading details for azutp/uTP Plugin
    Non-mandatory plugins -         current=0.6.2_CVS, latest=0.6.2_CVS
    Non-mandatory plugins -     Loading details for vuzexcode/BiglyBT Transcoder
    Non-mandatory plugins -         current=0.9.2_CVS, latest=0.9.2_CVS
    Non-mandatory plugins -     Loading details for aercm/Swarm Discoveries
    Non-mandatory plugins -         current=0.6.10_CVS, latest=0.6.10_CVS
    Non-mandatory plugins -     Loading details for mldht/mlDHT
    Non-mandatory plugins -         current=2.2.1_CVS, latest=2.2.1_CVS
    Non-mandatory plugins -     Loading details for azemp/Embedded Media Player
    Non-mandatory plugins -         current=4.2.3_CVS, latest=4.2.3_CVS
    Non-mandatory plugins -     Loading details for azneti2phelper/I2P Helper Plugin
    Non-mandatory plugins -         current=0.9.32.1.1_CVS, latest=0.9.32.1.1_CVS
    Non-mandatory plugins -     Loading details for mlab/Measurement Lab (M-Lab)
    Non-mandatory plugins -         current=0.3_CVS, latest=0.3_CVS
    Non-mandatory plugins -     Loading details for azplatform2/Platform-Specific Support
    Non-mandatory plugins -         current=1.12_CVS, latest=1.12_CVS
    Non-mandatory plugins -     Loading details for aznettor/Tor Helper Plugin
    Non-mandatory plugins -         current=1.2.2_CVS, latest=1.2.2_CVS
    Non-mandatory plugins - Finished
Finished
`

**Comment by parg** [comment]
Should be OK now - had a configuration error server-side - thanks!

**Comment by kwloafman** [comment]
Thanks!  Did not want to chase that one again!
