### ISSUE TITLE
I updated BiglyBT a few days ago.  Since then, I have not been able to download anything.  The infinity symbol is where the ETA is.  Forcing a download doesn't seem to work either.  

### ISSUE THREAD

**Issue by Ziggyinbr** [BiglySoftware/BiglyBT#1630]
* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment

**Comment by Ziggyinbr** [comment]
I am using Windows 10, 
BiglyBT version 2.3.0.0

Any help would be appreciated.

Thanks in advance.

**Comment by parg** [comment]
What status is showing for the tracker(s) under the Sources tab?

**Comment by parg** [comment]
Also test with https://download.documentfoundation.org/libreoffice/stable/6.4.3/win/x86_64/LibreOffice_6.4.3_Win_x64.msi.torrent
