### ISSUE TITLE
Issue with character sets in file names and directory names

### ISSUE THREAD

**Issue by trancephorm** [BiglySoftware/BiglyBT#1631]
Hello everyone...

BiglyBT is driving me nuts :( From time to time, it just can't find data (Error: data missing) for the torrents seeded, and it seems to be that is charset related. I know the filesystem is charset agnostic and I don't really know what should I do. It's like as if the .torrent files themselves are changed at some point, where all "unknown" chars are replaced with ?, but it just looks that way, I'm not really sure what can be the problem. Also, I've noticed sometimes data is doubled and one version is made with question marks in directories/file names. Right now I have 800 torrents for which data cannot be found, but it's there, the only solution is to delete the torrent from client (but not data), and re-download torrent from the tracker, then the data can be found when I load it again (with a warning that was already being loaded in past).

Can anyone shed some light onto this problem, I'm not really in the mood to download 800 torrents from site again and load them one by one. What can I do, does someone smell quick solution? Can I somehow export torrents in "Error" status and fix them somehow so the data can be found?

It's BiglyBT 2.3 on Ubuntu 20.04 / KDE Plasma

Thanks!

**Comment by parg** [comment]
Right-click on an error download and select 'search for existing data files' - that should fix things up.

**Comment by parg** [comment]
(obviously it doesn't explain the issue - I've had no other reports of this kind of problem)

**Comment by trancephorm** [comment]
Parg, problem is that I cannot do it for every file, because last time I tried, the computer was working for 48 hours because I have around 12000 torrents seeded and I don't know how much of it was done, but it didn't find data. Not to mention that function is is very bugged, that's my impression. If I could give that command for all 800 torrents and if it would last say for days - ok, but this way it's meaningless.. :(

**Comment by parg** [comment]
multiselect?

**Comment by trancephorm** [comment]
I tell you... there is some bug which is really hard to pinpoint. Maybe that's because I have 11k+ torrents in it, along with this one, I experienced file corruption here and there (and HDD is perfectly OK, and it occures on torrents which are seeded, and I'm not touching thim with any other program except Foobar2000.... I'm hopeless pretty much here and I need to rant a bit, never mind. Thanks for everything, seems like I'm really some special case.

**Comment by parg** [comment]
I blame Foobar2000. Did you try multi-selecting all your downloads and right-click 'search for existing' as one operation?

**Comment by trancephorm** [comment]
Yes I've tried that and it just can't find files, I think I will record video and post it... As for Foobar, I was suspicious too, but they on their forums that it's not changing files.

**Comment by parg** [comment]
Perhaps copy/paste from the 'search for files' window and email over to paul@biglybt.com ?

**Comment by trancephorm** [comment]
OK, so the problem definitely is that BiglyBT cannot read some files when they have unusual characters in them like ’, ø, Ì, — and many others. When such character is in directory name, it makes new directory with "?" instead of unusual characters and tries to download it all. When it's in the file name, then it makes new file again with "?" and tries to download it. That much I'm sure, but I'm mazed why that happens from time to time. Usually, it's able to read dirs/files with unusual characters, but once it gets broken it just can't be fixed easily. Once I managed to fix it with restoration of previous data, and then I manually was deleting new dirs/files with ? in their names, but it seems now that even that doesn't help, I tried it. And then I have the problem that the Search for Existing Data function is not working probably because of the same reason. So desperate here, I was always someone who deeply cared for data, backups, my seeding directory right now is a mess with duplicate data, and around 400 unfinished torrents, for which I actually have data... Something is very wrong in my setup or BiglyBT has some problem specially with my system. :(

**Comment by parg** [comment]
It is Java that handles encoding on BiglyBT's behalf. I just came across

https://dzone.com/articles/java-may-use-utf-8-as-its-default-charset

that discusses the 'sun.jnu.encoding' system property. 

On my Windows OS this is 'UTF-8'. You can check yours by running the 'generate debug info' from the Help menu, opening up the generated debug.zip file to get the 'evidence.log' file and then searching this for 'sun.jnu.encoding'

**Comment by trancephorm** [comment]
Seems that we're onto something. Says here it's sun.jnu.encoding=ANSI_X3.4-1968, which doesn't sound too good. Now I need to find a way to change this. Will report... Thanks!

**Comment by parg** [comment]
You can set the property by supplying a

`-Dsun.jnu.encoding=UTF-8`

to the java command line

**Comment by trancephorm** [comment]
Edited biglyby startup file, I changed
JAVA_PROPS="-Djava.net.preferIPv4Stack=true" to 
JAVA_PROPS="-Djava.net.preferIPv4Stack=true -Dsun.jnu.encoding=UTF-8"

But it didn't change encoding. Any idea where I can do that properly?

**Comment by parg** [comment]
https://stackoverflow.com/questions/10106161/encoding-of-file-names-in-java says 'utf8' as opposed to 'UTF-8'

Also mentions the LANG env var, might work?

**Comment by trancephorm** [comment]
Needed to insert this:

```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8

```
into my .bashrc file and logout and login.

Now it's OK. Still I saw somewhere that Java program might not be dependent on system setting as far as charsets are in question, so you may consider hard coding it to UTF8?

Thanks a lot fot your help!

**Comment by parg** [comment]
Its tempting to hard code it but there must be a reason that Java relies on the environment to select the encoding...
