### ISSUE TITLE
BiglyBT backups settings confusing

### ISSUE THREAD

**Issue by joliett1234** [BiglySoftware/BiglyBT#1632]
Windows 10
Desktop Environment

When I set Backup options:
BiglyBT Tools, Options, Setup & Setup, 
Backup frequency ... There is option for Days or Hours...

It's a bit confusing...I want to Backup once a day...

So Backup frequency (Days) = 1
or [hours] = ????  It defaults to 1??

Not sure what I should enter for hours???  Is it 24 hours?  I tried to put in zero...but not good.

Thanks!!!!

**Comment by parg** [comment]
Ah, when the config settings were reworked a while back it seems that bit got broken - it is supposed to be either days or hours (with hours being disabled unless you set days to 0).

I'll take a look but for the moment just set days to 1 and hours to 0

**Comment by joliett1234** [comment]
You can not set hours to 0...
I set days to 0
And hours to 24

Thank you.

**Comment by parg** [comment]
I can set hours to 0 - what prevents you?

**Comment by parg** [comment]
hopefully fixed the enable state for next beta
