### ISSUE TITLE
Wait for storage on launch

### ISSUE THREAD

**Issue by Orthodox-531** [BiglySoftware/BiglyBT#1635]
Since my DAS takes some time to start up (a lot longer than my computer), BiglyBT has launched and marked all torrents as having inaccessible files by the time the DAS containing the torrent data is ready to use.

It would be good if there was an option to specify a "grace period" on launch during which BiglyBT will quietly wait and retry if local data files are inaccessible.

* OS: Windows 10 Professional + Drobo 5D
* BiglyBT version: 2.3.0_B33

**Comment by parg** [comment]
There is an option to query for missing data files periodically

Files->Periodically restart downloads that appear to havbe missing files
