### ISSUE TITLE
v2.3.0 installer not compatible with MacOS 10.7.5

### ISSUE THREAD

**Issue by MarsArtis** [BiglySoftware/BiglyBT#1638]
Even if the home page states that client can be installed on OSX 10.7.3 and later it will not on Lion 10.7.5, the installer application will show up with a DENIAL symbol and if I try to open it it says that it requests OX 10.11 and up.

* OS and version = MacOS 10.7.5
* BiglyBT Version Number = 2.3.0

**Comment by parg** [comment]
Does the old installer from 

https://github.com/BiglySoftware/BiglyBT/releases/tag/v1.0.0.0

work?

**Comment by parg** [comment]
https://github.com/BiglySoftware/BiglyBT/releases/tag/v2.0.0.0 might work too - that was the last one before the installer software we use moved to supporting 10.11+

If you can  install then BiglyBT should auto-update from the version you install to the latest one.

**Comment by MarsArtis** [comment]
Hi,
installer v2.0.0.0 works but the app won't launch, it will bounce in the dock and nothing will happen.

the V1.0.0.0 installer works too and the app will launch. And it seems it's updating. I hope it'll update to suppoort HTTPS, SSL/TSL...

**Comment by MarsArtis** [comment]
So, V1.0.0.0 launched
made first update and restarted.
said It has a new second update to install, updated bit it will no more open.

**Comment by parg** [comment]
Hmm, annoying! Could you reinstall v1.0 (don't uninstall the broken version, just run the installer again) and while it still runs OK go to the Help menu and select the last option there to 'Generate Debug Info'. This will produce a debug.zip file with diagnostics in it. Please email that over to paul@biglybt.com (you might want to rename it to debugzip to avoid any email issues)

**Comment by MarsArtis** [comment]
thx Paul for solving the Lion issue. Really aprecciate.

**Comment by parg** [comment]
No problem - tell me if you notice other issues! For anyone else out there on 10.7

* Install the v1.0 installer linked above
* Wait for it to update to core version 2.4 and other dependencies
* Join the beta program as there is a fix in 2.4.0.1 required to fix UI issues

**Comment by MarsArtis** [comment]
I’m struggling. You know switching from Transmission ti BiglyBT is a great deal.
Just Consider that I’m still not able to understand how to globally set a seeding ratio to 3:1.
Will you address me please?

**Comment by parg** [comment]
Go to 

Options->Queue->Seeding->First Priority

"First priority" seeds will get first priority when it comes to scheduling them to run. 

In the First Priority section the second option there is called

'A share ratio under"

Anything with a share ratio less than this value will be considered 'first priority'

Set this to 3:1

You can control the number of actively seeding torrents under Options->Queue

'Max active torrents' is the overall control - the 'Max simultaneous downloads' option controls how many incomplete torrents will be scheduled to download. 

Say you have 'Max active torrents' set to 10 and 'Max simultaneous downloads' set to 3. If you have 3 downloads then 7 will be allowed to seed at any time.
