### ISSUE TITLE
Turn request throttling off by default

### ISSUE THREAD

**Issue by nokti** [BiglySoftware/BiglyBT#1642]
* Windows 10 x64
* BiglyBT 2.4.0.0

One thing I noticed when using BBT is that I was always downloading from one peer at a time. If I stopped then restarted the client it would be another peer but always just one. 

![BBT with](https://user-images.githubusercontent.com/58652818/82114202-8bb5ff80-975b-11ea-92ba-1b6474227cce.jpg)

So I started looking around in the options and I noticed that in the Transfer section "Use request throttling..." was checked (and the sub item as well). I'm guessing this is checked by default when installing BBT because I don't remember changing that setting. So I unchecked it:

![BBT transfer](https://user-images.githubusercontent.com/58652818/82114230-cc157d80-975b-11ea-8a42-0fe44bb56a9f.jpg)

I'm now downloading from several peers, as it should be:

![BBT without](https://user-images.githubusercontent.com/58652818/82114221-b7d18080-975b-11ea-983d-6de1764c0a57.jpg)

Wouldn't it be better and more ethical if this option came unchecked by default? Prioritizing only one peer seems unfair to the rest of the swarm, esp. on trackers where seeding ratio counts.

**Comment by parg** [comment]
Most (all?) bittorrent clients will preferrably allocate requests to the fastest peers when downloading. When you have set a download speed limit (as you have) and there is a peer that can satisfy your entire rate limit then you end up with what you are seeing. If you don't have a download limit set then requests will be sprayed around more as BiglyBT looks for the fastest peer(s).

**Comment by nokti** [comment]
Thanks for the quick reply and explanation :) I'm also running µTorrent 2.2.1 and qBittorrent 4.2.5 and neither display this behaviour. The download speed is also capped on those clients. So if there are 10 peers they will all upload to me at roughly the same speed, sending me roughly the same amount of data.

BBT's behaviour makes sense on public torrents. But on private torrents it results in rewarding (almost exclusively) people paying for fast seedboxes, which are not necessarily people bringing content.

Anyway, all is good now that I've found which setting to turn off.
