### ISSUE TITLE
Trackers update when all torrents are stopped.

### ISSUE THREAD

**Issue by yonk345** [BiglySoftware/BiglyBT#1643]
What BiglyBT is updating when I have all torrents stopped? I haven't even started any torrents since launching the aplication

![Clipboard01](https://user-images.githubusercontent.com/65455992/82122722-87a6d380-9795-11ea-914d-c921cef48729.jpg)

**Comment by BiglyBT** [comment]
Switch to the Tracker view in statistics - it shows the number of tasks if not the details. The All Trackers view will also give some hints regarding tracker access, check the last-ok/last failed column

**Comment by yonk345** [comment]
My bad, question should be why. In All Trackers view I can see that trackers get updated while all my torrent are still stopped after launching BiglyBT. Why?

**Comment by parg** [comment]
Scraping stopped torrents enabled?

**Comment by yonk345** [comment]
All torrents are stopped, scraping enabled by default. When I start BiglyBT without starting any of torrents I can see constatnt tracker update activity. I tought that scraping applies only to quened torrents.

**Comment by yonk345** [comment]
So, there is an option "Scrape torrent that aren't running" Aren't running means that it applies to quened or stopped torrents?

**Comment by parg** [comment]
Stopped and queued

**Comment by yonk345** [comment]
I don't get it. It looks like I was constantly seeding plugins_azneti2phelper-win32_0.9.45.1.2.zip file that could only be seen in All Trackers view after clicking on one of the updating trackers. In "Active" torrents tab there was nothing.

**Comment by parg** [comment]
Switch to detailed library view
