### ISSUE TITLE
a few hotkey not working anymore

### ISSUE THREAD

**Issue by SUCM** [BiglySoftware/BiglyBT#1645]
1. CTRL+R used to be able to resume/start a torrent, but don't know wince which version, this no longer works
2. is it possible to add a hotkey or how do I define hotkey for things like re-check hash on the selected torrents?

**Comment by parg** [comment]
ctrl+p/r pause and resume all torrents, not a specific one - seems to work for me
You can't define your own hotkeys

**Comment by SUCM** [comment]
I see. didn't know it had changed from Vuze https://wiki.vuze.com/w/Keyboard_shortcuts

**Comment by parg** [comment]
That documentation is out of date - BiglyBT hasn't changed the ctrl+p/r actions
