### ISSUE TITLE
ADD "starup on minimize"

### ISSUE THREAD

**Issue by rileyjoe** [BiglySoftware/BiglyBT#1648]
Can you add "starup on minimize"

**Comment by parg** [comment]
You mean Options->Interface->Start: Start minimized?

**Comment by rileyjoe** [comment]
Options->Interface->Start (Where Start? I can't see?)

**Comment by parg** [comment]
![image](https://user-images.githubusercontent.com/395293/82326239-6d0e6d80-99d4-11ea-90a0-124267ba2294.png)
