### ISSUE TITLE
How to make BiglyBT portable or at least change the installation folder

### ISSUE THREAD

**Issue by j03bj03** [BiglySoftware/BiglyBT#1649]
* OS and version: Windows 10 Pro 64-bit
* BiglyBT Version Number: 2.3.0.0

Hello,

This has probably already been answered somewhere, but I couldn't find anything.

I want, if possible, to have BiglyBT installed in a portable way, in a folder that I can move around without worrying about Windows paths, the registry and stuff like that.

If that is not possible, is it possible to at least install it on another disk, in a folder of my choice? The idea is to have BiglyBT installed on the same external HDD where my torrent data is located. This way, all my non-BiglyBT related stuff is on my C drive on my laptop, and all my BiglyBT related stuff is on my external HDD.

Thank you!

**Comment by parg** [comment]
There some stuff in https://github.com/BiglySoftware/BiglyBT/wiki/Command-Line-Options about selecting your own folder. If you google for 'portable vuze' you'll find a wiki entry - things are pretty much the same for BiglyBT

**Comment by j03bj03** [comment]
Hello and thanks for answering,

When I check the method at this link https://wiki.vuze.com/w/Portable_Vuze, it says to move everything in Program Files, but it does not talk about the files in ~AppData/local/roaming... There is a bunch of files there, including the torrent files. Is this method going to automatically move everything in AppData, or they will remain there?

Thanks!

**Comment by parg** [comment]
Ah, the discussion there is basically how to set up a fresh install to run from a portable location - if you have existing stuff then that is probably going to cause issues :(

**Comment by j03bj03** [comment]
Oh, I could live with a fresh install and manually restart the torrents. Do you think if I do a fresh install like in this tutorial, the AppData folder will be created at the new location, or it will be created at C:/.../AppData/Local/Roaming?

**Comment by parg** [comment]
I just tried it - everything gets put into the one folder BUT you need to slightly change the changes made to the .vmoptions file

1) Edit the BiglyBT.exe.vmoptions file to read
    -include-options java.vmoptions

2) Create a java.vmoptions file in the same folder with contents

    -Dazureus.portable.enable=true

**Comment by j03bj03** [comment]
Ok, thanks! I'll need to Google a few things about that java file, but I think I'll be fine!

I'll close this ticket and give this a try during the weekend. Thanks!

**Comment by j03bj03** [comment]
Hello!

Everything seems to be working as expected. A few things to note for anyone else who would like to do this:

- If you really want nothing related to BiglyBT on your C drive, don't change the location of the "install to" path during the install process (that's what I did on my first try). Really install it normally on your C, then copy-paste on the other drive like in the tutorial on Vuze's site, and then uninstall with Windows uninstaller and check the box saying "delete configuration files". This will cleanly remove all of BiglyBT on your C drive.

- If you had played with configuration a lot and don't want to configure everything again, or even if you want to transfer your torrents without having to re-add them all, before fully uninstalling BiglyBT from your C, do a backup of everything in ~AppData/Roaming/BiglyBT. Copy-paste everything that was in ~AppData/Roaming/BiglyBT into the new BiglyBT installation folder on the other drive, **except the java.vmoption file if there is one such file**.

- When starting my portable installation for the first time by running BiglyBT.exe, I got an error message saying _"No JVM could be found on your system. Please define EXE4J_JAVA_HOME to point to an installed 64-bit JDK or JRE or download a JRE from www.java.com"_. I tried installing Java from their website and I still had the same message. This is because the default Java download is the 32-bit version. On Java's website, click on "see all versions" and install the 64-bit version. Now everything should run as expected when running BiglyBT.exe.

- To set your new default download directory, go to Options>>Files, and enter a directory name of your choice, but without a drive letter, this will keep the downloads in a folder inside your new BiglyBT installation folder without having to worry about changing drive letters. If you keep a full folder path with a drive letter there, you will be able to download somewhere else than inside your BiglyBT install folder, but the drive that contains your default download directory will need to keep the same letter always.

@parg Do you think updating BiglyBT will be possible with portable mode and still remain fully portable after the update process?

**Comment by parg** [comment]
Glad you figured things out!

First check that restart works as expected from the File menu - after restarting go to Tools->Options->Plugins (click on the Plugins tree node to show overall plugin details on the right). This shows links to the 'user-specific and shared plugins folders. Both of these should refer to the same location in your portably install.

If the user-specific one has reverted to %appdata% then something went wrong (probably to do with the java.vmoptions file)

Assuming that is ok then everything apart from full-version updates should auto-update just fine. The full-version updates basically run a new installer and will stick stuff into 'program files' afaik. So you would need to run the installer and then manually grab the BiglyBT.jar file from the default installation location and replace the one in your portable install. I should make a change to switch to a .jar based update for portable installs, I'll take a look but obviously that would only apply to the next version. Alternatively you could join the 'beta program' as this generally updates via a .jar update which would work. Of course you would have to want to run beta versions.

**Comment by j03bj03** [comment]
Just double-checked, the restart works fine and the plugin paths are fine too. If there is a full version update, I'll do as you said. Anyway, now that I know how everything works and even how to transfer settings and everything, I shouldn't have any trouble doing this.

Thanks agains for all the help!

**Comment by BodySame** [comment]
How to change  java installed path   in config  or java.vmoptions to custom path ?
Where is this path string?
