### ISSUE TITLE
Normal internet connection used when SOCKS proxy fails

### ISSUE THREAD

**Issue by jpaddock** [BiglySoftware/BiglyBT#1650]
* OS and version - Windows 10 Pro 64 Bit
* BiglyBT Version Number - 2.4.0.0

I've been having some issues with my SOCKS proxy connection going down.  I noticed that when the SOCKS connection is down, torrents are still downloading/uploading.  I'm using a SOCKS proxy specifically so that I'm not using my normal internet connection.

Please ensure that when a SOCKS proxy is configured and enabled, that is the only method that can be used for an internet connection.  If/when the proxy goes down, all downloads/uploads should stop and wait for the proxy connection to resume.

**Comment by parg** [comment]
I would really advise you to switch to a proper VPN - SOCKS is pretty sucky.

When your proxy is down take a look at the peers you are connected to - perhaps they are I2P peers

**Comment by jpaddock** [comment]
Is there a way that I can have just this app go over the VPN and not the
entire internet connection for my server? My server that downloads runs my
media software too and I want my content served locally, not streaming
everything over the internet.

**Comment by TuxPaper** [comment]
> Is there a way that I can have just this app go over the VPN and not the entire internet connection for my server? My server that downloads runs my media software too and I want my content served locally, not streaming everything over the internet.

This is something the VPN software can do for you.  PIA (Private Internet Access) VPN has options to select apps to only use VPN or not use VPN.  I've used it and it works well.  Other VPNs might have similar features.

**Comment by jpaddock** [comment]
Just saw this feature in PIA.  Looks to work perfectly.  Thanks for the
help!

**Comment by ArtemGr** [comment]
I was looking for this as a feature: would be neat if a BiglyBT torrent could connect to both peers which are only available via socks5 and at the same time to peers which are only available via direct connection.

**Comment by parg** [comment]
What are peers that are "only available via socks5" ?

**Comment by ArtemGr** [comment]
Basically most of the Internet [in my case](https://en.wikipedia.org/wiki/Internet_censorship_in_Russia).

**Comment by parg** [comment]
OK, so what are these peers that are available via direct connection but not when a client uses socks5?

**Comment by ArtemGr** [comment]
socks5 itself is to a server in another country and is rather slow, so if everyone goes out via socks5, everyone is slow; some local in-country peers are available for direct connection obviously and it makes no sense really to connect to them via the socks5 reaching into the other country. Makes sense?
I've heard that BiglyBT supports direct incoming connections even when socks5 is enabled (Google search leads to this here issue), but so far I haven't seen any direct connections when socks5 is enabled (judging by the Protocol column, which always shows "TCP (SOCKS)").

**Comment by parg** [comment]
Your connection to trackers runs over SOCKS so I assume it is the SOCKS server IP that ends up registered with the tracker as your IP and incoming connections get bounced by the server.

If you want peers out there to connect directly to your public IP (do you?) then you would need to set an ip-override with your public IP and hope that the tracker honours it.

To be honest it all sounds like a privacy nightmare...

**Comment by ArtemGr** [comment]
It's mostly DHT and PEX and given a peer IP and port from these (or rather a list of prospective ip:port endpoints I imagine), the idea for the option would be to try and connect to the peer directly before falling back to the socks.
So the public IP might be left alone (to it's normal socks values).

**Comment by parg** [comment]
Maybe you could specify the IP ranges you want direct connections to as "LAN peers" 

    Options->Plugins->LAN Peer Finder: Local networks

I don't think SOCKS is considered when connecting to them

**Comment by ArtemGr** [comment]
Yes, this should work, thanks, will try to!
p.s. Doesn't seem to work: added the networks of most in-contry peers to the Local networks list, but no direct connections so far (and Sources says "LAN: 0 local clients discovered").

**Comment by parg** [comment]
In the latest Beta (4101_B19)  I added a new option:

Options->Connection->Proxy [Peer Communications]: Disable Data Proxies for members of this Peer Set

If you create a Peer Set that matches the peers you don't want to use the SOCKS proxy for and put its name here that should work.

https://github.com/BiglySoftware/BiglyBT/wiki/Speed-Limit-Scheduler#user-content-Peer_Sets

Tell me if that works or if you need help.

Beta program can be joined via the Help menu

**Comment by ArtemGr** [comment]
It works!

    peer_set ru=RU

<img width="1137" height="83" alt="Image" src="https://github.com/user-attachments/assets/60061130-17b8-48e3-be6b-45adcabac423" />
