### ISSUE TITLE
Additional listen ports

### ISSUE THREAD

**Issue by strange-antiquark** [BiglySoftware/BiglyBT#1654]
This isn't technically an issue, but I can't find any information on the subject anywhere, so here goes:

Quite by accident, I recently discovered the TCP.Listen.Additionalports parameter -- in my case, it is set to an old TCP port that I was using a few years ago.

I'm curious as to how this port value is chosen, and if there is any way for the user to configure it explicitly. In particular, would enabling "Randomize listen ports on startup" have any effect on the additional listen ports?

**Comment by parg** [comment]
BiglyBT has the ability to run more than one torrent with the same hash although obviously this is a rarely used feature. In this case additional TCP listen ports are allocated to permit the differentiation of incoming connections. Not something you can explicitly use. Hope that helps :)

**Comment by strange-antiquark** [comment]
Thanks for the note. I have just a quick followup.
As rarely used as this feature is, it does occur -- in my case, it was the third occurrence before I discovered what was happening.
At the very least, the existence of the additional listen ports is something users of advanced mode surely should know about, including how they are assigned. Ideally, advanced mode users should be able to select which ports will be used as additional TCP listen ports.
