### ISSUE TITLE
Feature request: Quick tag

### ISSUE THREAD

**Issue by FaffeF** [BiglySoftware/BiglyBT#1656]
I think it would be very helpful to have a quick way to assign tags. Like double-clicking the tab filter label, or even assigning a keyboard shortcut.

Since tags are a great way to automate actions, it's just a bit annoying that you currently have to right-click, navigate to another tab, then select the tag i a sub-menu.

**Comment by parg** [comment]
You can show tags in the sidebar and then drag a download onto it to add it (or remove it if already assigned)

Likewise if you show tag buttons in the library view you can drag a download and drop it on the button to add/remove

**Comment by parg** [comment]
Or there's the 'Tag' sub-tab in the Library view

**Comment by FaffeF** [comment]
Ok, thanks! That's a bit quicker than the right-click menu at least. Though I would still prefer a shortcut for the tags I use the most.
