### ISSUE TITLE
Nothing happens when I open a torrent file

### ISSUE THREAD

**Issue by quantitative-technologies** [BiglySoftware/BiglyBT#1659]
* OS and version
Ubuntu 20.04

Java 11.0.7 (64 bit)
  Ubuntu
/usr/lib/jvm/java-11-openjdk-amd64

SWT v3836, gtk/null, zoom=100, dpi=96
Linux v5.3.0-7648-generic, amd64 (64 bit)
B2.2.0.2/4 az3

**Comment by quantitative-technologies** [comment]
Also, when I try to download from a magnet nothing gets added to my library.

**Comment by parg** [comment]
Not sayng it'll fix your issue but please update to 2.4.0.0 and try again.

If it still doesn't work take a look at https://github.com/BiglySoftware/BiglyBT/wiki/Diagnostics

**Comment by quantitative-technologies** [comment]
Yes, upgrading did fix the issue.

Thanks.
