### ISSUE TITLE
issue connecting to seeds when enabled IPv6

### ISSUE THREAD

**Issue by SUCM** [BiglySoftware/BiglyBT#1662]
not sure how to debug this, but I have been noticing that sometimes Bigly would never connect to any seeds despite 5-10 of them reported from each tracker when IPv6 is enabled. if I disable IPv6 (uncheck enable IPv6 option) and restart Bigly, Bigly would happily connects to those seeds and starts downloading. However, I checked Bigly's setting/options and can confirm I only enable IPv6 support and its check firewall issue without disable/prefer either v4 or v6. this has been happening on multiple torrents for more than a year now.

just want to report this in case there is some bug or something else I should look for next time

also, is there any documentation on what exactly do "Prefer IPv* stack/address" option do or should I even enable them at all? currently not enabling any of them

**Comment by parg** [comment]
Don't change the prefer stack/address stuff unless https://docs.oracle.com/javase/7/docs/api/java/net/doc-files/net-properties.html makes you want to...

Enabling IPv6 really shouldn't interfere with IPv4 connections so I am at a loss to explain your observations. Perhaps you could enable it, turn on logging and see if there are any error messages being generated for attempted IPv4 connections.

**Comment by SUCM** [comment]
1. how do I turn on logging after a torrent seeing this issue is already running?
2. how do I re-trigger connection attempt just for the torrent seeing this issue?

the confusing part for me is that I can see active/connected IPv6 and IPv4 seeds/peers when looking at seed/peer list of other torrents, so I'm not sure why this happens from time to time

**Comment by parg** [comment]
1. Options->Logging
2. Stop and start the torrent

If you select the Log sub-tab for the torrent in question you should see (mainly) logs related just to that torrent.

Sounds more like you're just seeing random if other torrents are working

**Comment by SUCM** [comment]
somehow I'm not seeing log sub-tab anywhere (library, downloading...etc) for the torrent. is it in some special view?

**Comment by parg** [comment]
Actually it is called 'Console' and I think you need to enable logging under Options->Logging  (and restart) for it to be shown
