### ISSUE TITLE
Downloads Frozen

### ISSUE THREAD

**Issue by gemosley** [BiglySoftware/BiglyBT#1665]
<!--BiglyBT 2.4.0.0
![image](https://user-images.githubusercontent.com/51492765/83462665-a3aaa600-a420-11ea-8c9c-5817307a760b.png)
Sudden change in behaviour in Windows client. I've activated a number of torrents with several Seeds/Leeches but sitting in the BiglyBT Downloading queue, they all show 0/0 with ETA of infinity. I know the Seeds are not zero - I tried one on my Chromebook (my secondary device) and it worked just fine. The same exact torrent just sits there in my Windows BiglyBT queue showing 0/0.

Ran the BiglyBT Network Test and got a couple of failures that I don't understand:
Testing UDP outbound
    Test failed: Outbound test failed
Testing TCP port 14930 inbound
    Test failed: NAT test failed: Error: Unexpected end of file from server
    Check your port forwarding for TCP 14930
Testing UDP port 14930 inbound
    Sending outbound packet and waiting for reply probe (timeout=5000)
    Sending outbound packet and waiting for reply probe (timeout=10000)
    Sending outbound packet and waiting for reply probe (timeout=15000)
    Sending completion event
    Test failed: Inbound test failed
    Check your port forwarding for UDP 14930_

**Comment by gemosley** [comment]
Just saw that this was closed. Not sure why. My problem persists.

**Comment by parg** [comment]
Two word title with no description? What do you expect?

**Comment by gemosley** [comment]
I apologize for that but not sure what happened. I put "Downloads Frozen"
in the Title space and then entered a description of the problem in the
"Write" tab, including BiglyBT release info and an image clip of my system
info. I even edited the item shortly afterward to include a segment of the
report generated by performing the BiglyBT "Connection Test". There were
some failures related to UDP that I don't understand enough about to know
if they're relevant or not. In short, any torrent I add to the queue just
sits there with 0 seeds and 0 leeches. To confirm that the torrents were
valid I used one in a test download on my Chromebook and it downloaded just
fine while still showing an ETA of infinity on my Windows version.

**Comment by gemosley** [comment]
Yes. They seem to be related to UDP.

[image: image.png]

**Comment by parg** [comment]
Try testing with

https://download.documentfoundation.org/libreoffice/stable/6.4.4/win/x86_64/LibreOffice_6.4.4_Win_x64.msi.torrent

**Comment by gemosley** [comment]
OK. That one failed, too. I even turned off my VPN and did an "Update
tracker" on it. Here's the Source tab:

[image: image.png]

**Comment by parg** [comment]
You images aren't uploading for some reason

**Comment by parg** [comment]
Also check the status bar for a 'routing' icon - if it is present is it green or red?

**Comment by gemosley** [comment]
Yes, the Routing icon is red. When I hover, it indicates "Missing: eth3"

**Comment by parg** [comment]
So at some point BiglyBT was configured to only route traffic through the 'eth3' network interface - this would appear to now be invalid. Right-click on the red routing icon and select 'remove binding. Things should start working

**Comment by gemosley** [comment]
That seems to have done the trick. Your test torrent is now downloading.
Thanks so much for your help.
George

**Comment by parg** [comment]
no problem, glad we got there in the end :)
