### ISSUE TITLE
Blank text on some sidebar entries

### ISSUE THREAD

**Issue by detelosk** [BiglySoftware/BiglyBT#1666]
When launching BiglyBT using most newer Java environments (seemingly Java 11 onwards; Java 9 and 10 unknown), when items in the side bar that were out of view become visible by scrolling, some of them do not show their text until they are clicked on. After clicking on a different entry, some of the previously visible entries that went out of view by scrolling will show the same fate when they become visible again.

Steps to reproduce:
1. Start BiglyBT (tested with fresh settings through a temporary user profile) using an affected Java bundle.
2. Make sure that the sidebar is visible and is scrollable (for example by making tags and categories visible in the sidebar — through the Tags subsection of the Interface section of the preferences — and adding enough entries).
3. Scroll the sidebar.

Expected result: All entries that have come into view are fully shown, with their text visible.

Actual result: Some entries show their left-side icon, their right side icons (close button, count, etc.) but not their text.

System details:
* macOS Mojave 10.14.6 (18G5033)
* BiglyBT 2.4.0.0 (B2.4.0.0/4 az3, SWT v4928r15, cocoa, zoom=200, dpi=72) [This is not the first version where I have seen it.]
* BiglyBT launched via the terminal from `/Applications/BiglyBT/.biglybt` using `"$java_binary" -XstartOnFirstThread -cp BiglyBT.jar com.biglybt.ui.Main`

Observations:
* Tested Java bundles with this problem: Downloaded versions of AdoptOpenJDK packages (Java 11 and 14, both Hotspot and OpenJ9). Homebrew formulas and casks of OpenJDK (Java 11 and 13), Oracle JDK (Java 14), Sapmachine (Java 14).
* Tested Java bundles without this problem: Downloaded versions of AdoptOpenJDK packages (Java 8). Homebrew cask of Zulu (Java 14).

**Comment by parg** [comment]
Should be fixed next beta, thanks

**Comment by detelosk** [comment]
It does seem fixed. Thank you!

**Comment by detelosk** [comment]
After further usage, though the behaviour is now fixed when using the scrollbar or the mouse wheel (or equivalent trackpad gesture), I have found that other scrolling cases still trigger the issue in a noticeable way. In particular, I still experience the behaviour when focus is switched to a sidebar entry that is already open (not so for cold or unloaded entries) by the following means: keyboard shortcuts, the menu, and the status bar. (Note: This time I have only tested using my usual profile with the AdoptOpenJDK 14.0.1+7 HotSpot JRE.)

Since the missing entries are now repainted (mostly)[*] for the cases covered by the current fix, it is now less annoying to shoo away the issue, but it is still quite noticeable when it happens. Since I believe that the issue's description applies to what I have described, I am taking the liberty to reopen the case.

[*] In very rare occasions I am still experiencing at least one entry's text not loading (perhaps never more than one) when scrolling using the mouse, but it is not something that I have managed to reproduce.

**Comment by parg** [comment]
Might be fixed next beta (B12)

**Comment by detelosk** [comment]
It does seem fixed.

I have just stumbled on another issue-triggering situation which might be the one I wasn't able to reproduce: the text is not painted/refreshed when using the mouse wheel while the cursor is pointing to the scroll bar (however, clicking on the scroll bar or using the trackpad scrolling gesture works fine).

**Comment by detelosk** [comment]
I have tried replacing the `.install4j/jre.bundle`within the BiglyBT install directory (which hosts the Java 8u202 that the program's installer provides) with one of the JREs that was giving me trouble. With this change, BiglyBT.app — run either through the icon in the GUI or executing ` BiglyBT.app/Contents/MacOS/JavaApplicationStub` via the CLI — uses the new JRE (according to “About BiglyBT”) and the last issue-triggering procedure I mentioned causes no problems. The issue is still there when launching BiglyBT as initially specified.

**Comment by detelosk** [comment]
The issue no longer seems to appear when launching BiglyBT as initially specified (I hadn't checked it in a very long time).
