### ISSUE TITLE
Windows client locking up on multiple selections

### ISSUE THREAD

**Issue by ms52538** [BiglySoftware/BiglyBT#1668]
Windows 10 (latest build)
BT 2.4.0.1_B07/4 az3

The client seems to be locking up on this beta. If I type in a word in my search bar (either in the torrent section at the top, or file-specific search window at the bottom) and then I move to select multiple files within the returned items, my client locks up and only a CntlAltDel will resolve the issue. I've performed a warm reboot of the OS in between the lock-ups. Not sure if this is my environment or the beta client. Thoughts?

M

**Comment by parg** [comment]
The UI hangs up but other apps keep running? If that is the case then when it is hung you may be able to open a browser and open

http://127.0.0.1:45100/setinfo?name=AZMSG&value=AZMSG;0;config;log-diags;;

(see https://github.com/BiglySoftware/BiglyBT/wiki/Diagnostics )

to dump thread state into the logs/ folder

**Comment by ms52538** [comment]
Thank you. And of course, as I try to duplicate the issue at the moment, without luck. I'll double back on this if I see it again in the next few days.

:)

Thanks!
M
