### ISSUE TITLE
Increasing heap memory

### ISSUE THREAD

**Issue by j03bj03** [BiglySoftware/BiglyBT#1670]
OS: Windows 10 pro 64-bit
BiglyBT version: 2.4.0.0
Java: 1.8.0_251 (64 bit)

Hello,

Me again lol! I have installed a bigger disk, so I now have more active torrents at the same time. I am running into memory issues (memory is running low warning). Also, after too long, BiglyBT just stops transferring and says something about heap memory.

By reading a bit, I found the 2 following links that suggested to manually change heap memory:

https://wiki.vuze.com/w/Java_VM_memory_usage
https://github.com/BiglySoftware/BiglyBT/issues/92

The links say to go to Advanced Mode > Tools > Options > Startup & Shutdown and to change Java memory. However, in the Java section, I see this:

![Untitled](https://user-images.githubusercontent.com/39162841/83948622-5fd2ea80-a7ec-11ea-9931-9cbc02aea69b.png)

There does not seem to be a way to change heap memory.

Thanks!

**Comment by parg** [comment]
Did you set your mode to advanced under Options->Mode ?

**Comment by j03bj03** [comment]
Yeah, I did. The only thing I can click under Java Options is the "View" button to see the memory usage log.

**Comment by parg** [comment]
You must be running with some non-standard setup - if the Java config section is missing then I think this is because the .vmoptions file isn't where it should be or is set up incorrectly.

**Comment by j03bj03** [comment]
Oh, then it must be because I am running portable. If you remember, 2 weeks ago, you helped me setup to be portable here: https://github.com/BiglySoftware/BiglyBT/issues/1649

**Comment by parg** [comment]
Ah, LOL. You need to modify the vmoptions file to add a memory setting. Add a line

-Xmx512m

for example - this sets your max heap to 512MB.

**Comment by j03bj03** [comment]
Ok, will try that.

I just add the line under the portable line in the same file?

**Comment by j03bj03** [comment]
I think it's working alright, I don't have any memory warnings anymore. It still crashed, but I think that's because I allowed too much memory :D

Thanks for help!

**Comment by DumbJoe** [comment]
> Ah, LOL. You need to modify the vmoptions file to add a memory setting. Add a line
> 
> -Xmx512m
> 
> for example - this sets your max heap to 512MB.

In the linux version, do you edit that value here in the biglybt executable file in your install folder location, near the end of the file?

```
# Don't use "exec -a BiglyBT ..." here as exec quits this script after completion,
# preventing ScriptAfterShutdown from running, which installs updates and does
# restarts
${JAVA_PROGRAM_DIR}java -Xmx256m \
	-cp "${CLASSPATH}" \
	"-Djava.library.path=${PROGRAM_DIR}" \
	"-Dazureus.install.path=${PROGRAM_DIR}" \
	"-Dazureus.script=$0" \
	${JAVA_PROPS} \
	${JAVA_ARGS} \
	${START_CLASS} \
	${OTHER_PARAMS} \
	"$@"

echo $MSG_AZEXIT

runJavaOutput "com.biglybt.platform.unix.ScriptAfterShutdown" "$@";

echo $MSG_TERMINATED
```
to
```
# Don't use "exec -a BiglyBT ..." here as exec quits this script after completion,
# preventing ScriptAfterShutdown from running, which installs updates and does
# restarts
${JAVA_PROGRAM_DIR}java -Xmx4096m \
	-cp "${CLASSPATH}" \
	"-Djava.library.path=${PROGRAM_DIR}" \
	"-Dazureus.install.path=${PROGRAM_DIR}" \
	"-Dazureus.script=$0" \
	${JAVA_PROPS} \
	${JAVA_ARGS} \
	${START_CLASS} \
	${OTHER_PARAMS} \
	"$@"	

echo $MSG_AZEXIT

runJavaOutput "com.biglybt.platform.unix.ScriptAfterShutdown" "$@";

echo $MSG_TERMINATED
```
If you want to give it 4GB of heap memory?

**Comment by parg** [comment]
yup
