### ISSUE TITLE
Prioritize first and last piece of file(s)

### ISSUE THREAD

**Issue by Sauron3019** [BiglySoftware/BiglyBT#1672]
Last piece of files do not download when sequential download is enabled

![resim](https://user-images.githubusercontent.com/66399617/84331781-d0cf2500-ab93-11ea-8c88-d63481bd941c.png)

**Comment by Sauron3019** [comment]
Isn't there anyone who can fix this issue?
Thanks.

**Comment by parg** [comment]
Hmm, not seeing this issue - can you reliably reproduce it?

**Comment by Sauron3019** [comment]
"Prioritize first and last piece of file(s)" option enabled.
When adding the torrent, enabled the sequential download.
The last piece doesn't prioritize download and the preview doesn't work.

**Comment by parg** [comment]
Sequential overrides first/last piece prioritization - don't force it sequential if you want to preview it, BiglyBT will handle that automatically.

**Comment by Sauron3019** [comment]
I usually need to download sequentially because I'm watching it while downloading.

**Comment by parg** [comment]
If you watch via a stream URI from BiglyBT or using the embeded player then the sequential downloading etc is handled for you.

**Comment by Sauron3019** [comment]
I use an external player.

**Comment by parg** [comment]
So how does the 'external player' access the downloading file? Directly from disk?

**Comment by Sauron3019** [comment]
Yes.

**Comment by parg** [comment]
Can't the player take a URL as a source?

**Comment by Sauron3019** [comment]
Can take.

**Comment by parg** [comment]
If you right-click on a download/file and select Content->Media Server->Copy Stream URI to Clipboard (or variations thereof) then you will get a URL that when added to your player should work as you want.

**Comment by Sauron3019** [comment]
Thanks, but still troubled by some slow torrents.

**Comment by pokekrishna** [comment]
> Sequential overrides first/last piece prioritization - don't force it sequential if you want to preview it, BiglyBT will handle that automatically.

@parg, is there a way to have both of the options enabled when the user wants, like qbittorrent has. 
in that case the desired outcome would be, download the first and last pieces first and then carry on with the sequential downloads

**Comment by parg** [comment]
You can right-click on a piece in the piece map view and select 'force piece' - if you do this with the last piece of a file then that will override sequential download.

I can look into an option to make first-last piece prioritzation override sequential I suppose

**Comment by parg** [comment]
Beta B25 has a new option under the existing 'prioritize first/last piece' one to force this regardless of sequential settings
