### ISSUE TITLE
BiglyBT ignores download priority

### ISSUE THREAD

**Issue by Knocks** [BiglySoftware/BiglyBT#1673]
I often uncheck small files (text files, NFOs, etc) when downloading torrents with multiple files, but BiglyBT almost always downloads these small files anyway.  This is a problem, especially when BiglyBT downloads text files with very common names (e.g. Readme.txt), because if multiple torrents contain a file with that name, all of the torrents will error out.

When a file is unchecked prior to the download, that file should be the same as 'Delete' priority.  Those files should never be downloaded, and even dummies for them should not be generated.

* Windows 10
* BiglyBT Version 2.5.0

**Comment by parg** [comment]
Right-click on them and set their priority to 'delete' when you don't want them entirely.

**Comment by Knocks** [comment]
@parg That's an unnecessary step and bad UX when you've already presented with an option to uncheck the files you don't want.

**Comment by Knocks** [comment]
I have changed the title to reflect that @parg's comment does not address the issue and the issue should be reopened.

**Comment by parg** [comment]
Please don't tell me how to write my code - feel free to fork it and make it work how you want.

**Comment by Knocks** [comment]
What a bizarre response.  Do you write this software for your own use or for the public?  If it's the latter, do UI writing conventions mean anything to you?

**Comment by parg** [comment]
Oh, and in case you're wondering, 'Do Not Download' has the implication that you might want to download it in the future. You can switch a partially downloaded file into 'DND' and it won't forget how far it got with it, it will just mark it to be ignored, then when you switch it back to 'normal' it will continue. 'Delete' means you really don't want the file and if there happens to have been any of it downloaded at the point you switch it it will be deleted.

**Comment by parg** [comment]
Actually, I write the code for myself - nobody pays me to do it, nobody tells me what to do.

**Comment by Knocks** [comment]
Do you understand the difference between a checkmark and a no checkmark?  On what planet does a checkmark mean "download anyway"?

**Comment by parg** [comment]
LOL, move along now, no standing on top.

**Comment by Knocks** [comment]
Okay.  You might want to get off GitHub and move into a cave where no one bothers you with comments or reports bugs.

**Comment by parg** [comment]
Sure, see yah later
