### ISSUE TITLE
NAT OK on BiglyBT but Firewalled on Vuze

### ISSUE THREAD

**Issue by magus186** [BiglySoftware/BiglyBT#1674]
Hello parg, 
Not sure if you remember me, I'm the one who had a strange case last year of needing to use a newer version of Java to run Vuze/BBT. 

I now come to you with another issue I've tried hard to resolve but just can't figure it out and hoping you can perhaps help. 
First, the simple solution would be to use BBT, but since one of the trackers I use is still not allowing it, I'm still stuck on Vuze at the moment. 

I am Firewalled on Vuze, but not on Bigly. As such, I can't seed well. I have run through your guide here, and nothing has helped so far http://wiki.vuze.com/w/NAT_problem 

Vuze 5.7.6.0/4
OS: Windows 7 SP1
Java 13 64bit
Router ASUS AC-68U on AsusWRT-Merlin 384.17 latest firmware
Router supports UPnP and MAC binding 
Modem Comcast Technicolor CGM4140COM rev 2.1 (running on Bridge mode to the ASUS)
Firewall: Windows 7 Firewall (currently disabled for testing)
Anti-virus: Malwarebytes (currently disabled for testing, Windows defender has been disabled since day1)

I have so far
Set in windows static local IP 192.168.1.93 
MAC binding in ASUS router for 192.168.1.93 for this device
Ports: Tried using port 61286 for TCP and UDP after setting port forwarding in ASUS, tried 61286 for TCP and 61287 for UDP separately, both port forwarded in ASUS while UPnP was disabled. Tried random ports on startup with UPnP enabled in ASUS and Vuze. I tried the "bind to local IP address" option and it didn't work so I went back to leave it blank again. I've double checked that yes the port forwarding is ON in the router. I've tried changing various settings but nothing has worked...

I then checked with the PFportchecker from portforward and tested both of those ports on both TCP and UDP. 61286 seems to not be working at the moment on TCP but UDP was OK, and 61287 was open for both TCP and UDP. Yet, even if I change the settings in Vuze accordingly, I'm still firewalled. 

Out of curiosity, I tried BBT just to see what would happen, and I got the green light NAT OK and uploads started quickly for the trackers which are compatible. Meanwhile on Vuze which is still firewalled, I can't really connect to anybody during seeding. 

Also just to be clear, I'm not using any VPN on my connection as the private trackers don't allow it. 

I also use qbitorrent with a proxy for public trackers, and had the same issue with the connection being yellow. I was able to look that up though and saw someone mentioned enabling TCP and uTP connection helped, and it did for me too, it turned green after a few minutes of changing the setting. I had previously set up port forwarding on qbitorrent too and without the uTP setting I was still stuck on yellow. 

I then had the idea to check BBT 2.3.0's uTP plugin to see if it was newer than Vuze and it was, so I'm wondering if I just had a newer uTP plugin for Vuze would solve the problem. I tried just copying the files but of course that didn't work, so I'm guessing something has to be modified to make it work...if that is a possible solution at least. 

Final note...this issue has been going on for years, it's nothing new, just have some time off work now and time to tackle all these issues :-) 

Thank you

**Comment by parg** [comment]
Private trackers that ban VPNs? Wow, I thought they usually tried to sell you them.

I don't really have the time to debug Vuze issues, have you tried asking their support? lol

The 'green light' in the status bar is indicative of incoming connections being detected, i.e. a potential consequence of ports being open, but not always 100% accurate. Your go-to test is the NAT test wizard in BiglyBT, unfortunately the equivalent in Vuze has been broken for some time.

Have you tried running some of the torrents that work ok in BiglyBT in Vuze? Maybe those trackers that don't support BiglyBT have no leechers in their swarms.

The BiglyBT uTP plugin (well all plugins) is incompatible with Vuze - doubt it is changes to that though.

Enjoy experimenting!
