### ISSUE TITLE
Column "Pieces" in sub-tub "Files" causes strong lags of interface

### ISSUE THREAD

**Issue by Qwest8K** [BiglySoftware/BiglyBT#1681]
If this column enabled, then with a large number of files in torrent, loading of their list takes several seconds (and the whole program freezes during it), scrolling of this list becomes just impossible ('cause lag on lag with lag and lag) and the program itself works with strong lags when "Files" sub-tub is active.

Also, lags appear even in the "Column Setup" menu when this column, being disabled, appears on the screen.

**Comment by parg** [comment]
From my tracing only the visible rows are repainted and I don't see an issue. How many files are you talking about?

**Comment by Qwest8K** [comment]
About torrent with 7251 files.
