### ISSUE TITLE
Check for existing data doesn't always work? 

### ISSUE THREAD

**Issue by droopified** [BiglySoftware/BiglyBT#1683]
I'm on the latest version beta on a raspberry pi which is always on. If I have files on the network, I'm noticing that the checking exciting data doesn't always link the file. If I manually move the file to the local download directly and recheck it, it scans properly. I also have no clue what the tolerance% means. Maybe that might help me out? It's at 0% right now.

**Comment by parg** [comment]
Does the torrent contain the file more than once? A bug has been fixed in the beta series regarding that. Otherwise take a look at the log generated when searching to see if there are any clues. One other thing, is the missed file small (simialr to or smallher than the torrent's 'piece' size)?
