### ISSUE TITLE
BiglyBT hugs all the upload bandwidth without active upload

### ISSUE THREAD

**Issue by NEO701** [BiglySoftware/BiglyBT#1687]
Hello,

First of all, thanks for the great BiglyBT.
I have an issue that **while downloading**, BiglyBT hugs all the upload BW also I set **global upload limit about 10%** of the actual upload capacity and **current active torrent doesn't even do this much upload**.

So it seems this upload is done while downloading for some reason on the background and not related to the active torrents as shown in the attached SS.

And yes upload stops when I stop current active downloading torrent , and the shown value is my max upload capacity all utilized !

The situation below is on torrent downloading and many seeding without actively upload.
https://i.postimg.cc/5N0B1ZCy/SS.png

* System :
Java 14.0.1 (64 bit)
Oracle Corporation
c:\program files\biglybt\jre
SWT v4922, win32
Windows 10 v10.0, amd64 (64 bit)
B1.9.0.0/4 az3

* Win 10 2004 x64
* BiglyBT Version 1.9.0.0
* For *nix: Desktop Environment ?

**Comment by parg** [comment]
Wow, so you have a download limit of at least 3MB/sec but your upload limit is 130KB/sec? Never heard of such an attrocious network connection!

BiglyBT itself can generate a fair bit of background network traffic regardless of whether torrents are active (DHTs, I2P helper plugin especially). Also note that when downloading fast there is also a flow of protocol bytes in the other direction to make requests etc. There is an option under Options->Interface->Display to show the protocol statistics, under 'Display Units'

By the way, 1.9 is a rather old version of BiglyBT, the latest is 2.4

**Comment by NEO701** [comment]
No, this is not the usual line configuration, I have an issue and I should settle it with my ISP as upload should be 3MB/sec at least.

I have just enabled protocol statistics but still it does not show this utilization, actually it is so small values that it can be ignored.
Also I am not using either DHT or I2P helper plugin.

Need to add that I didn't have this issue when i was using the old versions before it became BiglyBT.

As for V2.4, I am aware and I will update soon but I am just little lazy to backup the current torrent list. :)
