### ISSUE TITLE
Transfer Limits Keep Resetting

### ISSUE THREAD

**Issue by Stildawn** [BiglySoftware/BiglyBT#1688]
HI All

I am trying to set my transfer limits so I can leave on Bigly on all the time.

However when I set it, it works for a minute but then goes back to unlimited which is not ideal.

Screenshot below:
![image](https://user-images.githubusercontent.com/2102261/85363167-5085c800-b574-11ea-8bf4-5a0e4e16251d.png)

Obviously not working as intended.

Thanks

**Comment by parg** [comment]
You have probably configured something to reset the limits.

Try Tools->Speed Limit s->View Current...

to see if anything is set.
