### ISSUE TITLE
IOException: Server returned HTTP response code: 400 for URL

### ISSUE THREAD

**Issue by Memfivosfey** [BiglySoftware/BiglyBT#1689]
When adding a file to the download, an error occurs and the download does not start. Downloading is only with DHT.

Torrent Tracker:
https://www.lostfilm.tv

Mistake:
IOException: Server returned HTTP response code: 400 for URL: http://bt.tracktor.in/tracker.php/xxxxxxx/announce?info_hash=%40%8C%DA%AF%DBE%8E%DB%DD%2C % 25% AB% 28% A6% 3F% BC% 10% CFv% E3 & peer_id = -BI2400-3TIsBath2xrR & supportcrypto = 1 & port = 56457 & azudp = 56457 & uploaded = 0 & downloaded = 0 & left = 2407230194 & corrupt = 0 & event = started & numwant = 1 & & = = & & = = & & = = & & = error = Bad Request400 Bad Request]

The admin says that the error is on the client side. With another client (uTorrent), such an error does not occur.

******* OS and version
Windows 7 x64
******* BiglyBT Version Number
Java 9 (64 bit)
  Oracle Corporation
c:\program files\java\jre-9

SWT v4930r7, win32, zoom=100, dpi=96
Windows 7 v6.1, amd64 (64 bit)
B2.4.0.0/4 az3
![Ошибка BiglyBT](https://user-images.githubusercontent.com/42377471/85432480-3a482e00-b5ad-11ea-8f85-e5120bb5b04f.jpg)

**Comment by parg** [comment]
There are some extra parameters added to the announce URL that the tracker should ignore (&azudp=) for example - is there any chance you could ask the tracker admin if that might be the case?

**Comment by Memfivosfey** [comment]
I can try.
