### ISSUE TITLE
Speed Scheduler not applying `resume_all` correctly

### ISSUE THREAD

**Issue by Mikewl** [BiglySoftware/BiglyBT#169]
```
Java 1.8.0_152 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4757, win32
Windows 10 v10.0, amd64 (64 bit)
B1.2.0.1_B14/4 az3
```
So, the logs are showing that `pause_all` is being successfully applied. Which is great!. However, when `resume_all` triggers as `pause_all rule no longer applies` the downloads are not resumed.

**Comment by Mikewl** [comment]
I managed to temporarily get it working by first using the manual `resume` button in the transfers bar. After resuming using that it works correctly until BiglyBT is restarted after which the broken behaviour continues.

**Comment by parg** [comment]
That is by design - the scheduler only resumes downloads that it has paused itself. The idea behind 'pause on exit' is (when not using the 'resume on start' feature) that it gives the user control over how things startup.
