### ISSUE TITLE
Can't set webui password from console

### ISSUE THREAD

**Issue by moham96** [BiglySoftware/BiglyBT#1693]
* OS and version: CentOS Linux 8
* BiglyBT Version Number: 2.4.0.0
* For *nix:  console, no desktop environment

How can i set the password for the xmwebui from the console interface ? i tried to use the set command but it fails with an invalid type error:
```
set Plugin.xmwebui.Password 09999
ERROR: invalid type given
```
putting quotes around the password doesn't help either

Regards

**Comment by parg** [comment]
`set "Plugin.xmwebui.Password "whatever your password is" password`

The last argument gives the type of the config var, in this case it is 'password' (as opposed to 'string', 'int' etc)
