### ISSUE TITLE
Feature Request: Swarm Discovery only track active

### ISSUE THREAD

**Issue by sharkbit** [BiglySoftware/BiglyBT#1694]
Would love to see a Checkbox to allow swarm discovery to only track active torrents,  I want to discard any torrent with out a seed or peer PLZ.

* OS and version: ANY
* BiglyBT Version Number: All
* For *nix: Desktop Environment: Meh

**Comment by parg** [comment]
There's the 'Filters' where you can remove 0/unknown seeds - this not what you want?

**Comment by sharkbit** [comment]
the filters are applied after the swarm limit.  So if your swarm limit is 100 you will probably still have torrents that are 0/0.  I only want to allow active torrents

**Comment by parg** [comment]
Might be possible to set a global minimum, I'll take a look

**Comment by parg** [comment]
I added an option in the Beta release - first you need to join the Beta Program (See the Help menu for an option) - this will update you to version 2.4.0.1_B13. Then you need to wait for the Swarm Discoveries plugin to update to version 0.8.5. This has a new option under Tools->Options->Plugins->Swarm Discoveries to ignore inactive results. You will need to enable this and then reset your current results by right-clicking on Swarm Discoveries in the Sidebar and selecting 'Reset to initial state'. Or alternatively explcitly delete any existing results you don't want - the option just affects newly added results.
