### ISSUE TITLE
MacOS: reset torrent(s) transfer statistics to zero will leave the share ratio as 'infinity'

### ISSUE THREAD

**Issue by Macie73** [BiglySoftware/BiglyBT#1695]
hi team,

this is something I had seen before but never cared to report on it.
When I open the Torrents right-click -> show details page and then go to 'Options' and click on the reset button at the bottom of that page, it resets all statistics alright but even when then later seeding it for several GBs the share ratio remains ∞ (infinity)

* OS and version: MacOS Catalina (10.15.5)
* BiglyBT Version Number: 2.4.0.0

how do i get it to start from 0, rather than not do anything?

the torrents are all fully downloaded and some have been seeding in the past, i just want the share ratio to start from 0 again and seed from there WITHOUT deleting and re-importing the torrents back in. 

thx

**Comment by parg** [comment]
If you enable the 'Share Ratio' colum in the library you can right-click on a download and select 'set share ratio' to set it explicitly. Not sure why the reset button is causing grief.

**Comment by Macie73** [comment]
thanks but I can't seem to find that option in the right-click menu, I have the 'Share Ratio' column enabled. both in Simple List and Advanced List library view. Is there something else i need to enable to see that option?

**Comment by Macie73** [comment]
![Screen Shot 2020-06-30 at 22 52 55](https://user-images.githubusercontent.com/34692047/86176000-97e7f780-bb24-11ea-9eb7-01cb5ea5eaaa.png)
![Screen Shot 2020-06-30 at 22 52 45](https://user-images.githubusercontent.com/34692047/86176002-98808e00-bb24-11ea-83ec-d9399202517a.png)
![Screen Shot 2020-06-30 at 22 52 34](https://user-images.githubusercontent.com/34692047/86176004-99192480-bb24-11ea-8603-7eb728aa4636.png)
![Screen Shot 2020-06-30 at 22 52 18](https://user-images.githubusercontent.com/34692047/86176005-99192480-bb24-11ea-865f-8c726f7d02f1.png)
just dropped some screenshot files, not sure if that worked

**Comment by parg** [comment]
Hmm, I have an 'Other' option to the right of 'Social' - make sure you are right-clicking in the 'Share Ratio' column

**Comment by parg** [comment]
(bit of an Easter Egg feature - I've got to get some sleep, back later!)

**Comment by Macie73** [comment]
yes! see it now. thx!
