### ISSUE TITLE
Botnet:Blacklist Questions

### ISSUE THREAD

**Issue by Iggy9730** [BiglySoftware/BiglyBT#1696]
The last couple of days my antivirus has been notifying me of a blocked connection, Botnet:Blacklist associated with Biglybt.exe.

The notifications cite specific udp:// addresses.

I've scoured the settings and options in Bigly to try see the udp addresses attempting to make connections with the hopes of being able to block connections from these addresses. Is it possible to see individual udp connections?

I've used BiglyBT for a while, and Vuze before it and never seen this kind of alert associated with the program. Any information is appreciated.

* Windows 10 Pro version 2004, build 19041.329
* BiglyBT Version Number: 2.4.0.0

**Comment by parg** [comment]
The DHT (Distributed Database) uses UDP packets - there is a continual exchange of information to maintain the DHT and perform DHT operations. If your AV is picking these up as (obviously incorrect) 'BotNet' connections then there's not much you can do apart from configuring your AV to exclude BiglyBT.exe or disabling the DHT.

**Comment by parg** [comment]
I'm told that Avast has put out an update that is supposed to fix this issue.
