### ISSUE TITLE
swarm dicovery 'delete all results' button does not work beginning 2.4.0.1_B13

### ISSUE THREAD

**Issue by hglecke** [BiglySoftware/BiglyBT#1697]
Win10-64
2.4.0.1_b13
* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment

**Comment by parg** [comment]
Something to do with the Swarm Discoveries plugin 0.8.4->0.8.5 update process - a restart of BiglyBT should fix it.

**Comment by parg** [comment]
I've fixed the bug that caused this (deregistration of menu resources not done on plugin unload in-process during the update) but the next plugin release will exhibit the same issue (as the bug is in the unloading of the old version)
