### ISSUE TITLE
Any chance for a uTorrent Import function?

### ISSUE THREAD

**Issue by DeathStalker77** [BiglySoftware/BiglyBT#17]
This would be *extremely* helpful. QBT toyed with it for a while, but I have not seen it implemented in any other client - being able to do that would definitely help to pull in more of the user base :)

**Comment by TuxPaper** [comment]
I briefly looked into it last month, but realized it would be a bigger project than just a day's work if we wanted to properly import labels and config settings (which we do!)

It's on my TODO list.  I'll check out QBT and see if they have anything I can scavenge.  They are GPL too, so that's a plus! :clinking_glasses:

**Comment by DeathStalker77** [comment]
If you guys can pull it off, you will be THE client.  I'm anxious to try out even 2.0 :)

**Comment by DeathStalker77** [comment]
Tried to send you a PM, but GitHub doesn't have that functionality :(  I'm not a programmer/coder, but I am a designer/developer/UX/data professional, so I'm happy to help wherever I can!

**Comment by DeathStalker77** [comment]
I am excited to see the 2nd release of this!  Any guesstimate eta on possible uT import function?  (I'm not especially thrilled with manually doing over 1300 entries :( )

Thanks!

**Comment by DeathStalker77** [comment]
Are we any closer to this functionality?

**Comment by parg** [comment]
no :(

**Comment by DeathStalker77** [comment]
As an update - the functionality that QBT uses is about 98% effective.  I have ~2100 torrents and cannot manually re-add them one by one.  So an import mechanism is an absolute MUST for me to even consider switching.

**Comment by parg** [comment]
Have you tried

1) Set torrents to be added 'stopped' - Tools->Options->Files->Torrents: By default add new torrents in a stopped state
2) Set Bigly to not show the add torrent dialog: Tools->Options->Files: When opening a torrent, show options dialog: Never
3) Drag and drop (or using whatever means) all your existing .torrent files onto BiglyBT
4) When they are all in the Library in a stopped state select them all, right-click and select 'Search For Existing Data Files...' from the 'Content' menu

?

**Comment by DeathStalker77** [comment]
I have not tried that - however, my original .torrent files are 1) across multiple drives & directories, and 2) not every one of them is currently in the client.  That is why the resume.dat data is so critically important.  Clearly this method sounds fine if we're just talking about a few torrents or those that are all in the same location.

**Comment by slrslr** [comment]
I have tried the steps @parg is showing, and among around thousand torrents, it not marked any torrent as competed or not modified its save path to match my existing file/folder structure. (took a few hours of maxed out CPU)

**Comment by TuxPaper** [comment]
I'll create a new github project in a week or so with the importer I've been working on.  Pretty straight forward so far, but I still want to add things like bringing over labels and other fun settings.

**Comment by TuxPaper** [comment]
Speaking of fun settings, we can use this issue to promote and discuss settings that you'd want brought over if you were importing.  Obviously the torrents and their piece completion info, and general max upload/download/queue size, but there's probably some other good-to-have things I might miss if no one advocates for it :)

**Comment by slrslr** [comment]
Preserving custom naming of the payload files/folders and tracker lists set in torrents. Maybe create categories/tags. I am not having utorrent, but qbittorrent (for which i created import feature request), so i am opting out of this thread.

**Comment by TuxPaper** [comment]
There's now a pre-release of a uTorrent migration plugin at https://github.com/BiglySoftware/BiglyBT-plugin-migratetorrentapp

Plugin (.biglybt file) can be downloaded at https://github.com/BiglySoftware/BiglyBT-plugin-migratetorrentapp/releases

I realize that everyone on this thread probably has already dealt with migration manually, however, if you would like to test it, we'd appreciate the help and feedback.

Any issues, feedback, or feature requests can be made using that GitHub projects Issue Tracker.
