### ISSUE TITLE
Windows: Inform the user a download has finished.

### ISSUE THREAD

**Issue by eurobank** [BiglySoftware/BiglyBT#170]
Is there a way to have Windows (10) to Notify the user that a torrent has finished ? 

If not, could that be included in some future update ?

Thanks !

**Comment by parg** [comment]
Can you join the beta program (Help menu option), allow BiglyBT to update to beta version B16 and go to Tools->Options->Interface->Alerts - there are some new 'Notify' options you can enable that might work.

**Comment by eurobank** [comment]
I did, and seems to work just fine. 

Thank you !

**Comment by eurobank** [comment]
Not sure if related but now i have TWO icons in Windows tools bottom line. The first can be clicked the second (to the right) not. 

See the capture:

![2017-11-29 08_04_00-](https://user-images.githubusercontent.com/4467158/33360413-45da9a28-d4dc-11e7-9b58-00107077f57d.png)

**Comment by parg** [comment]
Yes, that is unavoidable, sorry. One is the existing SWT tray icon, the other the native one that generates notifications. You should be able to hide one

**Comment by parg** [comment]
Hmm, maybe you can't hide one of them without hiding the other. It might be possible to remove the native one after some time period, not sure if that would result in the notification being removed too though

**Comment by eurobank** [comment]
Since it is a visual thing, not a problem.

**Comment by parg** [comment]
Yup, I tested auto-removal but unfortunately it also removes the message from the notification area. I have added a right-click menu to it to manually hide it in case it bothers you

**Comment by eurobank** [comment]
It doesn't bother me at all. I was afraid something wrong was happening, like two instances of the software etc etc.
