### ISSUE TITLE
BIglyBT User interface corrupted

### ISSUE THREAD

**Issue by BPDunbar** [BiglySoftware/BiglyBT#1700]
* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment

Java 1.8.0_251 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_251

SWT v4930r7, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.4.0.1_B13/4 az3

For some reason the UI in biglyBT has become corrupted. The fonts are incorrect and some are in totally unreadable sizes. I have tried uninstalling removing the configuration data and reinstalling, I tried reverting to the release version. Running sfc /scannow and dism None of the is worked. No other program seems to be affected. I have reset the fonts in Windows and cleared the font cache, it didn't work.

![BiglyBT 2020-07-04 112633](https://user-images.githubusercontent.com/18512971/86510738-2e990a80-bdea-11ea-90fd-6afb4022cd4b.png)

**Comment by parg** [comment]
Whoa, very odd and never before seen... Check the debug_1.log and debug_2.log files in the 'logs' directory in %appdata%\BiglyBT in case there are clues

**Comment by BPDunbar** [comment]
This is the debug_1.log from my reinstall of biglybt. I had deleted the existing configuration during uninstall and rebooted before reinstallation, this removed all existing logs. There was no debug_2.log.
[debug_1.log](https://github.com/BiglySoftware/BiglyBT/files/4873723/debug_1.log)

**Comment by parg** [comment]
Thanks - no clues there unfortunately :( I suppose you could try installing a newer version of Java although that's grasping at straws. 

Try https://adoptopenjdk.net/index.html 

Run BiglyBT and check the about window to see if it using the updated Java. If not you might have to delete c:\program files\java\jre1.8.0_251 to force it to pick up the newer one.

**Comment by aiorus** [comment]
I'm Having the same issue
[debug_1.log](https://github.com/BiglySoftware/BiglyBT/files/4875000/debug_1.log)
[debug_2.log](https://github.com/BiglySoftware/BiglyBT/files/4875001/debug_2.log)

Updated Java, installed AdoptOpenJDK, nothing.

Hope this helps...

**Comment by parg** [comment]
Nothing in those logs points to anything UI related :( You do have some weird permission errors writing to 

'C:\Users\Sergio\AppData\Roaming\BiglyBT\...

though

**Comment by aiorus** [comment]
Cleared the logs, restarted the app and the only thing that I see UI related is this line

[21:30:06] [stderr]     Win32UIEnhancer$1::run::413, AEThread2$threadWrapper::run::317

any clue?

**Comment by KiloWhiskeyDelta** [comment]
With Windows 10 ceasing Java support it may have updated a script that is corrupting the BiglyBT UI as I cleared the install and memory and although it works the UI is corrupted and you have to float the mouse over objects to read the highlight and click on the directory you are after.

**Comment by parg** [comment]
Windows 10 is not 'ceasing Java support' - where did you get that from?

I run multiple Windows 10 machines and haven't seen any issues like this - wonder what the difference is between your install and mine.

**Comment by chuchanpr** [comment]
I am also reporting the same issue.

[debug_1.log](https://github.com/BiglySoftware/BiglyBT/files/4878435/debug_1.log)

**Comment by rinkydinkyproject** [comment]
Same exact issue as OP. 
![image](https://user-images.githubusercontent.com/19210676/86642004-921d6680-bfa9-11ea-8ef4-3d7cc38fec20.png)

**Comment by rinkydinkyproject** [comment]
Same exact issue as OP. 

![image](https://user-images.githubusercontent.com/19210676/86642170-b37e5280-bfa9-11ea-8661-afda579f50ef.png)

**Comment by parg** [comment]
Anyone with this issue have any custom Win 10 UI settings?

**Comment by rinkydinkyproject** [comment]
> Anyone with this issue have any custom Win 10 UI settings?

I'm running the latest insider build (fast ring). The biggest change I made since this problem started.

**Comment by BPDunbar** [comment]
I'm also running the insider preview build of Windows 10 (build 20261.1000 to be exact).

**Comment by chuchanpr** [comment]
I'm also running the insider preview build of Windows 10

**Comment by KiloWhiskeyDelta** [comment]
Running on Microsoft Windows 10 Home Insider Preview Version 10.0.20161 Build 20161 with Edge Chromium Version 83.0.478.58 (Official build) (64-bit) as the browser, instead of IE and I have found Chrome to be memory hungry even though I am running Version 83.0.4103.116 (Official Build) (64-bit). I also have the latest Java 8 Update 251 (build 1.8.0_251-b08). 
So something with the general script in Vuze BiglyBT is not handling the screen layout and fonts - UI so hopefully a fix will be put in the next update of BiglyBT.

**Comment by parg** [comment]
I sense a common theme...

**Comment by parg** [comment]
I would expect Microsoft to fix the issue, not us.

**Comment by parg** [comment]
Just in case it has already been fixed by the SWT team can you please try the following? Download this .zip file and extract the 'swt.jar' from it. 
Stop BiglyBT and then replace the 'swt.jar' in the BiglyBT install folder with this updated one.  (keep a copy of the old one around if you want to revert after testing)

[swt-4.16-win32-win32-x86_64.zip](https://github.com/BiglySoftware/BiglyBT/files/4885972/swt-4.16-win32-win32-x86_64.zip)

**Comment by rinkydinkyproject** [comment]
No dice. Same problem with the new swt.jar. Is there a dev build of swt that could be pulled down perhaps? I recognize that could intro new bugs, but given I'm already running a beta build of BiglyBT, not overly concerned, I can just revert back and restore configs if needed. (I also had stable build of BiglyBT with the same problem as well) It is likely some interaction between Java and Windows in some way there. Im not well versed, but understand enough to know the newer windows build is the primary cause, but given it's Microsoft, they likely will not fix it.

**Comment by parg** [comment]
Latest dev build is here 

https://download.eclipse.org/eclipse/downloads/drops4/I20200707-0600/#SWT

**Comment by rinkydinkyproject** [comment]
Thanks. Installed it, same result :S

**Comment by parg** [comment]
Thanks for testing, I'll report it to the SWT team to see if they have any clues.

**Comment by parg** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=565029

**Comment by 74lobster** [comment]
Hi, I have the same problem too, tried to use the modified 'swt.jar' file but nothing changed.

There is a way to change the dpi settings of the interface program ?


I use Windows 10 Pro Insider Preview Build 20161.rs_prerelease.200627-1754

**Comment by aiorus** [comment]
Yeah, there def is a common thread of using latest insider build...time to use the feedback button.

Thanks for the help!

**Comment by Katmeat** [comment]
Same problem here on latest insider builds

**Comment by 74lobster** [comment]
> 
> 
> Yeah, there def is a common thread of using latest insider build...time to use the feedback button.
> 
> Thanks for the help!

I have the same issue also with the official release of BiglyBT.

Seems to be a problem related to the last Windows 10 Pro Insider Preview Build 20161.rs_prerelease.200627-1754 
that miss a font or has some corrupted fonts inside...

**Comment by KiloWhiskeyDelta** [comment]
> Windows 10 is not 'ceasing Java support' - where did you get that from?
> 
> I run multiple Windows 10 machines and haven't seen any issues like this - wonder what the difference is between your install and mine.



> Windows 10 is not 'ceasing Java support' - where did you get that from?
> 
> I run multiple Windows 10 machines and haven't seen any issues like this - wonder what the difference is between your install and mine.

Parg - perhaps you should have read this before commenting:

JULY 25, 2017 9:00 AM
The End of an Era – Next Steps for Adobe Flash
By Microsoft Edge Team
 SHARE  TWEET  SHARE  SHARE  SKYPE
[Update Aug 30 2019 – We have posted an update on our plans for the removal of Flash support from Microsoft browsers, including the new Chromium-based version of Microsoft Edge. – Ed.]

Today, Adobe announced that Flash will no longer be supported after 2020. Microsoft will phase out support for Flash in Microsoft Edge and Internet Explorer ahead of this date.

Flash led the way on the web for rich content, gaming, animations, and media of all kinds, and inspired many of the current web standards powering HTML5. Adobe has partnered with Microsoft, Google, Mozilla, Apple, and many others, to ensure that the open web could meet and exceed the experiences that Flash has traditionally provided. HTML5 standards, implemented across all modern browsers, provide these capabilities with improved performance, battery life, and increased security. We look forward to continuing to work with Adobe and our industry partners on enriching the open web without the need for plug-ins.

We will phase out Flash from Microsoft Edge and Internet Explorer, culminating in the removal of Flash from Windows entirely by the end of 2020. This process began already for Microsoft Edge with Click-to-Run for Flash in the Windows 10 Creators Update. The process will continue in the following phases:

Through the end of 2017 and into 2018, Microsoft Edge will continue to ask users for permission to run Flash on most sites the first time the site is visited, and will remember the user’s preference on subsequent visits. Internet Explorer will continue to allow Flash with no special permissions required during this time.
In mid to late 2018, we will update Microsoft Edge to require permission for Flash to be run each session. Internet Explorer will continue to allow Flash for all sites in 2018.
In mid to late 2019, we will disable Flash by default in both Microsoft Edge and Internet Explorer. Users will be able to re-enable Flash in both browsers. When re-enabled, Microsoft Edge will continue to require approval for Flash on a site-by-site basis.
By the end of 2020, we will remove the ability to run Adobe Flash in Microsoft Edge and Internet Explorer across all supported versions of Microsoft Windows. Users will no longer have any ability to enable or run Flash.
This timeline is consistent across browsers, including Google, Mozilla, and Apple. We look forward to continuing our close collaboration with Adobe, other browser vendors, and the publishing community, as we evolve the future of the web for everyone.

— John Hazen, Principal Program Manager Lead, Microsoft Edge

**Comment by parg** [comment]
Why would I read that? It doesn't mention Java anywhere.

**Comment by smcpoland** [comment]
LOL...totally agree with Parg, no mention of Java at all...

Anyway - I have the same problem Windows 10 (2004 edition) 20161.1000

That's the DEV ring as it's now called :)

**Comment by 74lobster** [comment]
> 
> 
> LOL...totally agree with Parg, no mention of Java at all...
> 
> Anyway - I have the same problem Windows 10 (2004 edition) 20161.1000
> 
> That's the DEV ring as it's now called :)
> 
> Note: I'm using the latest Beta version of BiglyBT 2.4.0.1-B16
> 
> Here are some GUI related issues from debug_1.log
> 
> `[14:50:08] [stderr] java.net.SocketException: Network is unreachable: connect
> [14:50:08] [stderr] at sun.nio.ch.Net.connect0(Native Method)
> [14:50:08] [stderr] at sun.nio.ch.Net.connect(Unknown Source)
> [14:50:08] [stderr] at sun.nio.ch.DatagramChannelImpl.connect(Unknown Source)
> [14:50:08] [stderr] at lbms.plugins.mldht.kad.utils.AddressUtils.getDefaultRoute(AddressUtils.java:221)
> [14:50:08] [stderr] at lbms.plugins.mldht.kad.DHT.start(DHT.java:734)
> [14:50:08] [stderr] at lbms.plugins.mldht.azureus.MlDHTPlugin$9.runSupport(MlDHTPlugin.java:670)
> [14:50:08] [stderr] at com.biglybt.core.util.AsyncDispatcher$1.run(AsyncDispatcher.java:161)
> [14:50:08] [stderr] at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:317)
> 
> [14:50:58] [GUI] Table Cell Plugin for Column #r0c2:this plugin is crazy. tried to refresh 10 times in 87ms
> getStackTrace (Debug.java:317), pluginError (TableCellSWTBase.java:660), refresh (TableCellSWTBase.java:733), run (TableViewImpl.java:1888), runForAllRows (TableViewImpl.java:535), columnInvalidate (TableViewImpl.java:1878), columnInvalidate (TableViewImpl.java:1901), columnInvalidate (TableStructureEventDispatcher.java:128), invalidateCells (TableColumnImpl.java:815), recalcWidth (ColumnDateSizer.java:338), access$2 (ColumnDateSizer.java:278), runSupport (ColumnDateSizer.java:245), AERunnable.run, execSWTThread (Utils.java:1053), execSWTThread (Utils.java:1219), refresh (ColumnDateSizer.java:224), refresh (ColumnDateSizer.java:181), refresh (ColumnDLHistoryCompleteDate.java:71), invokeCellRefreshListeners (TableColumnImpl.java:914), refresh (TableCellSWTBase.java:790), run (TableViewImpl.java:1888), runForAllRows (TableViewImpl.java:535), columnInvalidate (TableViewImpl.java:1878), columnInvalidate (TableViewImpl.java:1901), columnInvalidate (TableStructureEventDispatcher.java:128), invalidateCells (TableColumnImpl.java:815), recalcWidth (ColumnDateSizer.java:338), access$2 (ColumnDateSizer.java:278), runSupport (ColumnDateSizer.java:245), AERunnable.run, execSWTThread (Utils.java:1053), execSWTThread (Utils.java:1219), refresh (ColumnDateSizer.java:224), refresh (ColumnDateSizer.java:181), refresh (ColumnDLHistoryCompleteDate.java:71), invokeCellRefreshListeners (TableColumnImpl.java:914), refresh (TableCellSWTBase.java:790), run (TableViewImpl.java:1888), runForAllRows (TableViewImpl.java:535), columnInvalidate (TableViewImpl.java:1878), columnInvalidate (TableViewImpl.java:1901), columnInvalidate (TableStructureEventDispatcher.java:128), invalidateCells (TableColumnImpl.java:815), recalcWidth (ColumnDateSizer.java:338), access$2 (ColumnDateSizer.java:278), runSupport (ColumnDateSizer.java:245), AERunnable.run, run (RunnableLock.java:40), runAsyncMessages (Synchronizer.java:185), runAsyncMessages (Display.java:3963), readAndDispatch (Display.java:3590), (SWTThread.java:400), createInstance (SWTThread.java:58), Initializer
> [14:50:58] [GUI] Table Cell Plugin for Column #r1c2:this plugin is crazy. tried to refresh 10 times in 85ms
> getStackTrace (Debug.java:317), pluginError (TableCellSWTBase.java:660), refresh (TableCellSWTBase.java:733), run (TableViewImpl.java:1888), runForAllRows (TableViewImpl.java:535), columnInvalidate (TableViewImpl.java:1878), columnInvalidate (TableViewImpl.java:1901), columnInvalidate (TableStructureEventDispatcher.java:128), invalidateCells (TableColumnImpl.java:815), recalcWidth (ColumnDateSizer.java:338), access$2 (ColumnDateSizer.java:278), runSupport (ColumnDateSizer.java:245), AERunnable.run, execSWTThread (Utils.java:1053), execSWTThread (Utils.java:1219), refresh (ColumnDateSizer.java:224), refresh (ColumnDateSizer.java:181), refresh (ColumnDLHistoryCompleteDate.java:71), invokeCellRefreshListeners (TableColumnImpl.java:914), refresh (TableCellSWTBase.java:790), run (TableViewImpl.java:1888), runForAllRows (TableViewImpl.java:535), columnInvalidate (TableViewImpl.java:1878), columnInvalidate (TableViewImpl.java:1901), columnInvalidate (TableStructureEventDispatcher.java:128), invalidateCells (TableColumnImpl.java:815), recalcWidth (ColumnDateSizer.java:338), access$2 (ColumnDateSizer.java:278), runSupport (ColumnDateSizer.java:245), AERunnable.run, execSWTThread (Utils.java:1053), execSWTThread (Utils.java:1219), refresh (ColumnDateSizer.java:224), refresh (ColumnDateSizer.java:181), refresh (ColumnDLHistoryCompleteDate.java:71), invokeCellRefreshListeners (TableColumnImpl.java:914), refresh (TableCellSWTBase.java:790), run (TableViewImpl.java:1888), runForAllRows (TableViewImpl.java:535), columnInvalidate (TableViewImpl.java:1878), columnInvalidate (TableViewImpl.java:1901), columnInvalidate (TableStructureEventDispatcher.java:128), invalidateCells (TableColumnImpl.java:815), recalcWidth (ColumnDateSizer.java:338), access$2 (ColumnDateSizer.java:278), runSupport (ColumnDateSizer.java:245), AERunnable.run, run (RunnableLock.java:40), runAsyncMessages (Synchronizer.java:185), runAsyncMessages (Display.java:3963), readAndDispatch (Display.java:3590), (SWTThread.java:400), createInstance (SWTThread.java:58), Initializer
> [14:50:58] [GUI] Table Cell Plugin for Column #r2c2:this plugin is crazy. tried to refresh 10 times in 89ms
> getStackTrace (Debug.java:317), pluginError (TableCellSWTBase.java:660), refresh (TableCellSWTBase.java:733), run (TableViewImpl.java:1888), runForAllRows (TableViewImpl.java:535), columnInvalidate (TableViewImpl.java:1878), columnInvalidate (TableViewImpl.java:1901), columnInvalidate (TableStructureEventDispatcher.java:128), invalidateCells (TableColumnImpl.java:815), recalcWidth (ColumnDateSizer.java:338), access$2 (ColumnDateSizer.java:278), runSupport (ColumnDateSizer.java:245), AERunnable.run, execSWTThread (Utils.java:1053), execSWTThread (Utils.java:1219), refresh (ColumnDateSizer.java:224), refresh (ColumnDateSizer.java:181), refresh (ColumnDLHistoryCompleteDate.java:71), invokeCellRefreshListeners (TableColumnImpl.java:914), refresh (TableCellSWTBase.java:790), run (TableViewImpl.java:1888), runForAllRows (TableViewImpl.java:535), columnInvalidate (TableViewImpl.java:1878), columnInvalidate (TableViewImpl.java:1901), columnInvalidate (TableStructureEventDispatcher.java:128), invalidateCells (TableColumnImpl.java:815), recalcWidth (ColumnDateSizer.java:338), access$2 (ColumnDateSizer.java:278), runSupport (ColumnDateSizer.java:245), AERunnable.run, execSWTThread (Utils.java:1053), execSWTThread (Utils.java:1219), refresh (ColumnDateSizer.java:224), refresh (ColumnDateSizer.java:181), refresh (ColumnDLHistoryCompleteDate.java:71), invokeCellRefreshListeners (TableColumnImpl.java:914), refresh (TableCellSWTBase.java:790), run (TableViewImpl.java:1888), runForAllRows (TableViewImpl.java:535), columnInvalidate (TableViewImpl.java:1878), columnInvalidate (TableViewImpl.java:1901), columnInvalidate (TableStructureEventDispatcher.java:128), invalidateCells (TableColumnImpl.java:815), recalcWidth (ColumnDateSizer.java:338), access$2 (ColumnDateSizer.java:278), runSupport (ColumnDateSizer.java:245), AERunnable.run, run (RunnableLock.java:40), runAsyncMessages (Synchronizer.java:185), runAsyncMessages (Display.java:3963), readAndDispatch (Display.java:3590), (SWTThread.java:400), createInstance (SWTThread.java:58), Initializer
> [14:50:58] [GUI] Table Cell Plugin for Column #r3c2:this plugin is crazy. tried to refresh 10 times in 93ms
> getStackTrace (Debug.java:317), pluginError (TableCellSWTBase.java:660), refresh (TableCellSWTBase.java:733), run (TableViewImpl.java:1888), runForAllRows (TableViewImpl.java:535), columnInvalidate (TableViewImpl.java:1878), columnInvalidate (TableViewImpl.java:1901), columnInvalidate (TableStructureEventDispatcher.java:128), invalidateCells (TableColumnImpl.java:815), recalcWidth (ColumnDateSizer.java:338), access$2 (ColumnDateSizer.java:278), runSupport (ColumnDateSizer.java:245), AERunnable.run, execSWTThread (Utils.java:1053), execSWTThread (Utils.java:1219), refresh (ColumnDateSizer.java:224), refresh (ColumnDateSizer.java:181), refresh (ColumnDLHistoryCompleteDate.java:71), invokeCellRefreshListeners (TableColumnImpl.java:914), refresh (TableCellSWTBase.java:790), run (TableViewImpl.java:1888), runForAllRows (TableViewImpl.java:535), columnInvalidate (TableViewImpl.java:1878), columnInvalidate (TableViewImpl.java:1901), columnInvalidate (TableStructureEventDispatcher.java:128), invalidateCells (TableColumnImpl.java:815), recalcWidth (ColumnDateSizer.java:338), access$2 (ColumnDateSizer.java:278), runSupport (ColumnDateSizer.java:245), AERunnable.run, execSWTThread (Utils.java:1053), execSWTThread (Utils.java:1219), refresh (ColumnDateSizer.java:224), refresh (ColumnDateSizer.java:181), refresh (ColumnDLHistoryCompleteDate.java:71), invokeCellRefreshListeners (TableColumnImpl.java:914), refresh (TableCellSWTBase.java:790), run (TableViewImpl.java:1888), runForAllRows (TableViewImpl.java:535), columnInvalidate (TableViewImpl.java:1878), columnInvalidate (TableViewImpl.java:1901), columnInvalidate (TableStructureEventDispatcher.java:128), invalidateCells (TableColumnImpl.java:815), recalcWidth (ColumnDateSizer.java:338), access$2 (ColumnDateSizer.java:278), runSupport (ColumnDateSizer.java:245), AERunnable.run, run (RunnableLock.java:40), runAsyncMessages (Synchronizer.java:185), runAsyncMessages (Display.java:3963), readAndDispatch (Display.java:3590), (SWTThread.java:400), createInstance (SWTThread.java:58), Initializer
> [14:50:58] [GUI] Table Cell Plugin for Column #r4c2:this plugin is crazy. tried to refresh 10 times in 90ms`

Hi, did you find a solution to fix the visual issue ?

Thanks in advance.

**Comment by parg** [comment]
Nope, waiting on either Microsoft to fix whatever they've broken or Eclipse to fix whatever they need to to work with whatever Microsoft have changed.

**Comment by 74lobster** [comment]
> 
> 
> Nope, waiting on either Microsoft to fix whatever they've broken or Eclipse to fix whatever they need to to work with whatever Microsoft have changed.

Today I have installed the new Windows 10 Pro Insider Preview

Build 20170.rs_prerelease.200710-1419

Nothing changed, the issue persists...

**Comment by parg** [comment]
boo

**Comment by 74lobster** [comment]
> 
> 
> boo

so weird...

**Comment by Alontier** [comment]
Same issue, directly after upgrading to Windows Insider Dev Channel build: Windows 10 build 20170.1000

**Comment by 74lobster** [comment]
In the last version of Windows 10 Pro Insider Preview Build 20175.rs_prerelease.200717-1349 
the issue of the corrupted fonts in BiglyBt was solved !!!

**Comment by smcpoland** [comment]
Yea!!!

Downloading now 😊

**Comment by Ram-Benz** [comment]
Issue is resolved in 

Edition	Windows 10 Enterprise Insider Preview
Version	2004
OS build	20175.1000
Experience	Windows Feature Experience Pack 120.18201.0.0

**Comment by parg** [comment]
Thanks for the update!
