### ISSUE TITLE
Downloads stall.

### ISSUE THREAD

**Issue by hectorjroman** [BiglySoftware/BiglyBT#1701]
* OS and version: Windows 10 Pro 64 bits with JRE 8u251 
* BiglyBT Version Number: Beta 2.4.0.1_B13
* For *nix: Desktop Environment

Any download, specially big files, stalls after I while. When closing the program it keeps stopping the pending downloads for several minutes. Once it closes and is restarted the program says that it wasn't closed properly and starts to check all the pending downloads as if they where corrupted. I reverted to version 2.4.0.0 and the issue was solved.

**Comment by parg** [comment]
Anything in the debug_1.log and debug_2.log files in the 'logs' folder?

**Comment by hectorjroman** [comment]
> Anything in the debug_1.log and debug_2.log files in the 'logs' folder?

Cannot find that folder. Anyway, they already released the B14 so I guess they already fixed the situation. I will try it.

**Comment by parg** [comment]
%appdata%\BiglyBT\logs - if you reproduce the issue then you can generate a 'debug.zip' (Help menu, last option) and email it over to paul@biglybt.com (rename it to, say, debugzip, to avoid possible email issues)

**Comment by hectorjroman** [comment]
> %appdata%\BiglyBT\logs - if you reproduce the issue then you can generate a 'debug.zip' (Help menu, last option) and email it over to [paul@biglybt.com](mailto:paul@biglybt.com) (rename it to, say, debugzip, to avoid possible email issues)

I found the logs but they won't be necessary because the issue has been fixed with the B14. That was fast. By the way, the logs have sensitive information so it would have been necessary to clean them up before sending. Thanks anyway.
