### ISSUE TITLE
Text size change?

### ISSUE THREAD

**Issue by ExRobotGuy88** [BiglySoftware/BiglyBT#1705]
Concerning BiglyBT v.2.4 on iMac Mac OS 10.13.5

Is there a way to increase the font size on Library view?

Thanks

**Comment by DaniAngel** [comment]
Is there any further guidance here?  I would love to increase the font size of Bigly library view.

**Comment by ExRobotGuy88** [comment]
My God, 'DaniAngel' It's taken 3 years for anyone to comment and it's another question!! I don't think we will get an answer. Happy New Year1

**Comment by parg** [comment]
Well the answer is that BiglyBT doesn't have any built-in way to change the font size. 

If your OS has the ability to do so (e.g. as an "Accessibility" feature) then you could use that. For example, https://www.idownloadblog.com/2023/06/28/how-to-adjust-text-size-apps-mac/

However you may find that this doesn't uniformly do things within BiglyBT.

**Comment by ExRobotGuy88** [comment]
IT LIVES!! Thx., parg.
