### ISSUE TITLE
Allow typing in limits for speed

### ISSUE THREAD

**Issue by Krutonium** [BiglySoftware/BiglyBT#1711]
* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment

Arch Linux, 2.4.0.0, Budgie

Basically, when I'm in the main UI and want to limit the speed, it presents a list of arbitrary list of speeds I can limit it to, without an option to select what speed I actually want - IE Punching in a number. In some cases, I want to limit my download speed to slower than the slowest speed available, meaning I have to go into the settings proper.

Would it be possible to enable setting of a user defined speed in that dialog easily?

![Download](https://user-images.githubusercontent.com/3945538/87140782-0b4ddf80-c270-11ea-87e2-8796df6f1a71.png)

**Comment by parg** [comment]
You can just type into that dialog once it is visible, or isn't that working?

**Comment by parg** [comment]
typed value is pretty hard to see though, I'll fix that a bit

**Comment by Krutonium** [comment]
Oh, can you? Fair enough! I completely missed it, probably for the reason you mentioned.

**Comment by david-bakin** [comment]
Oh I gotta say that edit control is not obvious!  Thanks for this issue - now that I've learned you can type there I'll never forget it.

**Comment by parg** [comment]
\0/
