### ISSUE TITLE
Force BiglyBT "UDP is currently bound to..." use the same IP all the time?

### ISSUE THREAD

**Issue by tuffdadsf** [BiglySoftware/BiglyBT#1714]
Every time I start BiglyBT after a reboot...

VPN Helper for PIA

BiglyBT UDP is currently bound to /xxx.xxx.xxx.xxx 
changes to a new IP address

Can I force it to use the same one every time? I always have to reset the IP settings on my other programs to match the new IP that Bigly grabbed.

Thanks for the help!

**Comment by parg** [comment]
BiglyBT isn't allocating IP addresses, it is your VPN software (I assume the xxx.xxx.xxx.xxx is that allocated to the network interface of your VPN, often a 10.xxx.xxx.xxx address)

**Comment by tuffdadsf** [comment]
Thanks! I guess that's why I couldn't find any settings in Bigly to change that...
Now to search PIA to see what I can do. Thanks again!
