### ISSUE TITLE
Blocky font issue

### ISSUE THREAD

**Issue by actricom** [BiglySoftware/BiglyBT#1715]
The font used on the toolbar (between the Up/Down buttons and the "Search Library" box) is very blocky and pixelated and looks hideous compared to every other piece of text on the screen. The text says things such as "20 items: 16 active, 1 queued". Hardly major, I know, but it just triggers my OCD! This is not a new thing, it has always been like it on both my PC's.

* Windows 10 1909
* BiglyBT Version Number 2.4.0.0

**Comment by parg** [comment]
Here's mine:

![image](https://user-images.githubusercontent.com/395293/87572918-20899a80-c6c4-11ea-8204-08e5c06c3fa0.png)

What's your's like?

**Comment by actricom** [comment]
Here's mine:

Blocky

**Comment by parg** [comment]
hmm, that didn't work - try adding it directly here - https://github.com/BiglySoftware/BiglyBT/issues/1715

**Comment by actricom** [comment]
![Blocky](https://user-images.githubusercontent.com/36631004/87579656-2ab09680-c6ce-11ea-9d44-1f0349bdc1a0.png)

It actually doesn't look too bad in this example, but the zeroes show it up the best.

**Comment by parg** [comment]
Looks like text anti-aliasing isn't working, are there any other places in the UI with blocky stuff going on or just here?

**Comment by actricom** [comment]
No, it's that area only.

**Comment by parg** [comment]
I've added explicit anti-aliasing to beta B17 - if you're not in the Beta Program then please join it via the Help menu. When it updates to B17 and you've restarted there's a vague chance things might have improved.

**Comment by actricom** [comment]
Sorry I can't try now, but I'll have a go later tonight or tomorrow and let you know.

----- Reply message -----

**Comment by actricom** [comment]
Yes, B17 has fixed it. It may be my imagination, but all the other text that looked fine before seems to be even better too.

**Comment by actricom** [comment]
Just so that you can compare a before and after, here's the B17 fixed result:
![BlockyNoMore](https://user-images.githubusercontent.com/36631004/87667399-2a61db00-c762-11ea-8308-03d11f68a268.png)

**Comment by parg** [comment]
Still can't explain why you were blocky in the first case but a fix is a fix!
