### ISSUE TITLE
Feature Request: Check Move on complete location for seed files.

### ISSUE THREAD

**Issue by Napsterbater** [BiglySoftware/BiglyBT#1716]
When adding a torrent to seed existing files, if you select a tag that has an initial save location and a move on complete location.

If you add the torrent and select the Tag and select Seeding, BiglyBT only checks the initial save location for the files, which is now not changeable since it is forced by the tag, BiglyBT should also search the move on complete location if the items were not found in the initial save location.

Thanks.

**Comment by parg** [comment]
Implemented in the next beta (B19) - thanks

**Comment by Napsterbater** [comment]
This works perfectly.

Would it also be possible to have this work when Torrents/Magnets are added from a watched folder as well? Though you are obviously not selecting seeding, but some way to check to existing files in a similar manner?

**Comment by parg** [comment]
Is this in the context of having a Tag assigned to the watch folder and that Tag having a move-on-complete setup?

**Comment by Napsterbater** [comment]
Yes, at least how I'm using it. Though I could see it being useful for default non tagged? Though I do not use a watch folder that is not tagged.

**Comment by parg** [comment]
Might work already for the default case to be honest but I wanted to check.

**Comment by parg** [comment]
Should be working in B25 when released
