### ISSUE TITLE
Occasional AEThreadMonitor segfaulting

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#1717]
I'd been noticing that BiglyBT "seemed a bit crashy" over the past few beta builds (possibly going back 10, 15 at this point) — it always happened when I wasn't watching, and usually (AFAICT) when it was idle. I'd set some torrents running, they'd complete, I'd close the remote display window, and next time I opened it a few hours/days later, no BiglyBT!

So this last time, I started it from a terminal window so that I could capture the output, and this is what greeted me when I just connected to my fileserver, instead of BiglyBT's smiling UI:

(I also used the `time` command to launch it, so I can tell you that it was running for 9h 32m 40.46s before it died. Basically all of that after the first 10 minutes would've been unattended.)

```
....................................DEBUG::Fri Jul 17 01:44:49 EDT 2020::com.biglybt.core.networkmanager.impl.tcp.TCPConnectionManager::addNewRequest::601:
  java.net.BindException: Cannot assign requested address
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:454)
	at sun.nio.ch.Net.connect(Net.java:446)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:645)
	at com.biglybt.core.networkmanager.impl.tcp.TCPConnectionManager.addNewRequest(TCPConnectionManager.java:479)
	at com.biglybt.core.networkmanager.impl.tcp.TCPConnectionManager.runSelect(TCPConnectionManager.java:868)
	at com.biglybt.core.networkmanager.impl.tcp.TCPConnectionManager$7.run(TCPConnectionManager.java:293)
	at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:317)

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fd6d4c70ba4, pid=1241823, tid=0x00007fd6bcac9700
#
# JRE version: OpenJDK Runtime Environment (8.0_252-b09) (build 1.8.0_252-b09)
# Java VM: OpenJDK 64-Bit Server VM (25.252-b09 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libpthread.so.0+0x11ba4]  pthread_getcpuclockid+0x4
#
# Core dump written. Default location: /home/ferd/lib/biglybt/core or core.1241823
#
# An error report file with more information is saved as:
# /home/ferd/lib/biglybt/hs_err_pid1241823.log
Compiled method (nm) 34344630 7861     n 0       sun.management.ThreadImpl::getThreadTotalCpuTime0 (native)
 total in heap  [0x00007fd6bd6fdfd0,0x00007fd6bd6fe320] = 848
 relocation     [0x00007fd6bd6fe0f8,0x00007fd6bd6fe140] = 72
 main code      [0x00007fd6bd6fe140,0x00007fd6bd6fe320] = 480
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
/home/ferd/lib/biglybt/biglybt: line 253: 1241823 Aborted                 (core dumped) ${JAVA_PROGRAM_DIR}java -Xmx256m -cp "${CLASSPATH}" "-Djava.library.path=${PROGRAM_DIR}" "-Dazureus.install.path=${PROGRAM_DIR}" "-Dazureus.script=$0" ${JAVA_PROPS} ${JAVA_ARGS} ${START_CLASS} ${OTHER_PARAMS} "$@"
Exit from BiglyBT complete
No shutdown tasks to do
BiglyBT TERMINATED.
~/lib/biglybt/biglybt  6297.21s user 1356.15s system 22% cpu 9:32:40.46 total
```

Here's the full content of that error report file:
[hs_err_pid1241823.log](https://github.com/BiglySoftware/BiglyBT/files/4941888/hs_err_pid1241823.log)

I also saved as much of the console output as fit in my terminal window so I can provide that as well if it'd be useful, but everything above that `..........DEBUG` line is riddled with peer addresses, torrent hashes, and who knows what other PID, so I'd rather not do it publicly. (Especially if it's not even needed.)

#### System block
```
Java 1.8.0_252 (64 bit)
  Oracle Corporation
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.252.b09-1.fc32.x86_64/jre

SWT v4934r6, gtk/3.24.20, zoom=100, dpi=96
Linux v5.7.8-200.fc32.x86_64, amd64 (64 bit)
B2.4.0.1_B18/4 az3
```

**Comment by parg** [comment]
This is a known issue - see https://github.com/BiglySoftware/BiglyBT/issues/1641 - raised a bug on the JVM but had no feedback :( Check out the workaround involving

`-Dbiglybt.thread.monitor.enable=0`

**Comment by ferdnyc** [comment]
Thx, I'll take a look.

As a data point, this _may_ possibly have some sort of RSSFeed Scanner involvement, since I noticed after bringing everything back up that the most recent entry in one of my feeds was marked "Hist", but was _not_ actually in the queue, making me think the crash happened fairly soon after — if not during — the metadata download for that torrent. \*shrug\* May mean nothing, just happened to notice it.

**Comment by ferdnyc** [comment]
Ayup, that's definitely the same bug ­— though it surprises me a bit that I'm not seeing it as _often_ (or as quickly) on Fedora, for me BiglyBT usually runs for hours before it crashes.

Still, closing as duplicate of #1641.
