### ISSUE TITLE
Restore from backup methods? 

### ISSUE THREAD

**Issue by droopified** [BiglySoftware/BiglyBT#1718]
I'm on a raspberry pi 4 and haven't been able to restore. It says it will auto restart after I select the folder but it doesn't seem to apply the restore. Is manually copy and paste of the content from the backup to the default good enough?

Not sure if manually copying from the backup folder is the same as doing a restore from the options.

**Comment by parg** [comment]
Close BiglyBT, manual copy-paste and restart should do the trick
