### ISSUE TITLE
B19 - after 1-3 hours of operation UI starts failing to update when switching tabs

### ISSUE THREAD

**Issue by david-bakin** [BiglySoftware/BiglyBT#1719]
Windows Server 2016 (10.0.14393).  BiglyBT 2.4.0.1_B19

Soon after I upgraded to B19 and not before I started suffering large delays in UI updating.  Perhaps the entire app is stalled - can't tell.  But basically, seems to work fine for an hour or so downloading multiple torrents at my max rate then ... UI starts failing to update.  Click on a different sidebar tab (e.g., to to from "incomplete" to "seeding" and ... the update takes ... well over a minute, even longer.  Sometimes doesn't even finish refreshing.  Menu system seems to respond at normal speed - at least I can exit and restart.

Anyway - let me know if you want logs and if so which ones.

**Comment by david-bakin** [comment]
Actually, I'm not even sure now b19 is restarting correctly.  It seems to be hanging on restart for a very long time.  This is the second time today.  The first time killling it worked: it restarted ok.  This time not.  It's siting with the sidebar showing only "My Torrents/Library" and "BiglyBT/Beta Program" and "BiglyBT/Notificaitons".

**Comment by parg** [comment]
Hmm, not seeing any issues here - the thread_* and debug_* log files are probably the most useful if you can dig them out

**Comment by david-bakin** [comment]
Reverted to last official release.  Then forgot to turn off the beta enrollment so it automatically upgraded me back to B19.  And then ... all normal.  Working fine now, for several days.  NVM!

**Comment by parg** [comment]
long may it not recur!
