### ISSUE TITLE
Pieces tab empty when uploading only

### ISSUE THREAD

**Issue by Xyrio** [BiglySoftware/BiglyBT#1721]
problem: 
i have a seeding torrent where even when uploading with 30kbyte/sec the pieces tab shows nothing.

expectation:
i would expect the pieces tab to show at least currently uploading pieces. maybe even REQUEST and HAVE communications. messages that are instant or after being removed could still stay in the list for 60(configurable?)  seconds with a gray font color, for when things go very fast.

also the Peers/Piece column shows -1 for peers that have high (30kbyte/sec) upload

notes:
Java 1.8.0_181 (64 bit)
  Oracle Corporation
c:\progzre64\java\jre1.8.0_181

SWT v4930r7, win32, zoom=100, dpi=96
Windows 7 v6.1, amd64 (64 bit)
B2.4.0.0/4 az3

the pieces map tab does show uploading pieces as red triangles.

im not familiar with the internals but in the console tab i see these kind of messages:

<pre>
[03:42:52.884] {net} Received [BT_REQUEST piece #6918:393216->409599] message; 	| TorrentDLM: 'Buzz3d_Archive_Fixed'; Peer: L: 190.47.211.220:62898 [Transmission 2.94]
[03:42:52.921] {net} Sent [BT_PIECE data for piece #6918:393216->409599] message; 	| TorrentDLM: 'Buzz3d_Archive_Fixed'; Peer: L: 190.47.211.220:62898 [Transmission 2.94]
[03:42:56.008] {net} Received [BT_HAVE piece #25619] message; 	| TorrentDLM: 'Buzz3d_Archive_Fixed'; Peer: L: 190.199.37.7:34914 [µTorrent 3.5.5]
</pre>

**Comment by parg** [comment]
That's how it is designed to work - the pieces view shows incomplete active pieces. As you point out, you can see uploading in the piece map view.

**Comment by parg** [comment]
The Peers/Piece item shows the last piece you requested from the peer for download, not the last piece they requested from you.

I'm not sure a 'piece uploading' view would be very interesting (compared to the existing downloading piece view). Peers don't actually request pieces from you, they request 16kb blocks, although a well written client will attempt to source multiple blocks from the same piece from the same peer. 

If a good case could be made for such a view I might consider adding it.

**Comment by Xyrio** [comment]
it is just as interesting to see what pieces are uploaded as downloaded. especially for multifile torrents where the Pieces/Files column would then show what file(s) use that piece. basically seeing what files are uploaded since you dont have to download the whole torrent in the multifile case.

**Comment by parg** [comment]
The Piece Map view shows what files are associated with a piece - hover over the piece and the information at the top of the view will show the details.

Not sure I understand the bit about 'you don't have to download the whole torrent in the multi-file case' - you will only see a block (of a piece) uploading if you already have downloaded the (piece of the) file so you can't use that information to decide which files to download.

**Comment by Xyrio** [comment]
when a torrent is made of multiple files like zip files you dont need to download all pieces. only the pieces that contain data for the file you want can be downloaded. once you are done with downloading the torrent moves into the seeding only view. 

what i mean is that the information that is shown in the Piece Map view can also be shown in the Pieces view. the red tirangles marked pieces indicate what is currently being uploaded and hovering mouse over a piece will show within which file(s) that piece is located. therefore it should be trivial to add the same information to the Pieces tab so one does not have to look through the slower Pieces Map tab and scroll around to find what is currently uploaded. this is especially slow the bigger the torrent. in my case it is a 200gb+ torrent and i only downloaded around 70gb. in the Files tab one sees what is selected for download (Priority Tab: Normal) and Delete are parts not to be downloaded or kept.

**Comment by parg** [comment]
"therefore it should be trivial" - ok, you do it then

**Comment by Xyrio** [comment]
ok when i find the time ill try then :)

**Comment by parg** [comment]
Good luck, it isn't trivial.

**Comment by parg** [comment]
I'll add some form of uploading pieces to the next beta, I was bored

**Comment by Xyrio** [comment]
tried it. but doesnt work. pieces tab shows nothing while piece map tab shows red triangles for uploads

**Comment by parg** [comment]
You enabled the 'show uploads' option at the top of the pieces view?

**Comment by Xyrio** [comment]
ah didnt see that. yes it works. tnx.

**Comment by Xyrio** [comment]
hmm the upload speed limit per torrent doesnt seem to work. im testing locally with 127.0.0.1 tracker and another torrent client downloading from biglybt. am i missing something?

**Comment by parg** [comment]
Do you have separate LAN limits configured? Options->Transfer->LAN

**Comment by Xyrio** [comment]
yep that was enabled
