### ISSUE TITLE
"Options" does not work

### ISSUE THREAD

**Issue by ambiDave** [BiglySoftware/BiglyBT#1722]
The "Options" menu does not work. It is listed under the "Tools" menu but when clicked on the options page doesn't pop up and the display area goes blank

This is what BiglyBT normally looks like
![BiglyBT screen](https://user-images.githubusercontent.com/68652176/88209737-124ef780-cc4b-11ea-9c90-b328d423e853.jpg)

This is what BiglyBT looks like after selecting options from the tools menu. To get the screen back to normal,I hit the Library button on the sidebar
![BiglyBt options](https://user-images.githubusercontent.com/68652176/88209785-20047d00-cc4b-11ea-8bd9-e6c819b70882.jpg)

I've tried reinstalling BiglyBT, uninstalling and then re-installing BiglyBT - neither tactic worked

Any ideas?

**Comment by ambiDave** [comment]
The "Options" menu does not work. It is listed under the "Tools" menu but when clicked on the options page doesn't pop up and the display area goes blank

This is what BiglyBT normally looks like
![BiglyBT screen](https://user-images.githubusercontent.com/68652176/88209393-8e950b00-cc4a-11ea-9360-1a5fd2918541.jpg)

This is what BiglyBT looks like after selecting options from the tools menu
![BiglyBt options](https://user-images.githubusercontent.com/68652176/88209506-b8e6c880-cc4a-11ea-88ae-f42b47a2d034.jpg)

I've tried reinstalling BiglyBT, uninstalling and then re-installing BiglyBT - neither tactic worked

Any ideas?

**Comment by parg** [comment]
What OS? Perhaps you could go to the Help menu and select the last option there to generate a debug.zip and email it to paul@biglybt.com ?
