### ISSUE TITLE
Error checking if BiglyBt is updated to the last beta version or not...

### ISSUE THREAD

**Issue by 74lobster** [BiglySoftware/BiglyBT#1723]
Hi Paul, when I try to check if BiglyBt is updated to the last beta version, the following errors were reported:

Platform-specific support, Failed to load plugin details for the platform manager, Plugin list load failed, https://10.199.212.195/update/pluginlist3.php?type=&version=2.4.0.1_B19&app=BiglyBT&os=Windows+10&osv=10.0&arch=amd64&ui=az3&java=1.8.0_261&swt_platform=win32&swt_version=4936&pmv=1.27&epids=aercm%3Aazlocprov%3Aazitunes%3Aazmsgsync%3Aazneti2phelper%3Aazrating%3Aazupnpav%3Aazutp%3Amigratetorrentapp%3Amlab%3Amldht%3Avuzexcode%3Axmwebui%3Aaznettor%3A: I/O Exception while downloading 'https://plugins.biglybt.com/update/pluginlist3.php', Connect timed out

Non-mandatory plugins, Failed to load plugin details, Plugin list load failed, Tor helper plugin failed or not available

Mandatory plugins, Failed to load plugin details, Plugin list load failed, https://10.148.42.213/update/pluginlist3.php?type=&version=2.4.0.1_B19&app=BiglyBT&os=Windows+10&osv=10.0&arch=amd64&ui=az3&java=1.8.0_261&swt_platform=win32&swt_version=4936&pmv=1.27&epids=aercm%3Aazlocprov%3Aazitunes%3Aazmsgsync%3Aazneti2phelper%3Aazrating%3Aazupnpav%3Aazutp%3Amigratetorrentapp%3Amlab%3Amldht%3Avuzexcode%3Axmwebui%3Aaznettor%3A: I/O Exception while downloading 'https://plugins.biglybt.com/update/pluginlist3.php', Connect timed out

Have you got any idea to solve this issue ?

I attach also debug file...

[debug.zip](https://github.com/BiglySoftware/BiglyBT/files/4962098/debug.zip)

Thanks in advance !

**Comment by AzaleeBleue** [comment]
The root cause is "Caused by: java.net.SocketTimeoutException: Connect timed out" so it may be the same problem as #1842
