### ISSUE TITLE
Migrated my files from old MAC to new MAC with Catalina, now looks like BiglyBT is not pointing to the hard drive where they are located

### ISSUE THREAD

**Issue by blair500** [BiglySoftware/BiglyBT#1724]
I moved my BiglyBT files from an old MAC to a new MAC with Catalina operating system.  I had to stop and then start each of the files to get the "Error:data missing" status changed to either Seeding or Queued.  I was able to successfully download new files and share them, but the old files, although they show seeding or Queued and not sharing at all.  I ensured the transfer location was correctly identified as the hard drives where the programs are residing.  It seemed that an attempt to share a files was made and resulted in the "Error:data missing" code.  Have I missed a step - although I was able to get the torrents into my library on the new computer, is it not pointing to the hard drives where they are located and where a sharer would access them?  Thanks for any advice!

**Comment by blair500** [comment]
I'd like to add that I can see the torrents are showing the correct drive location.  I did try to "move data files" to the hard drive, but there was no response - because they were where I was trying to move them.  Obviously I am not a pro at this, but I'm trying!!

**Comment by parg** [comment]
Have you tried right-clicking on one of the 'error: data missing' torrents and selecting the 'search for existing data files...' option under the 'content' menu tab?

**Comment by blair500** [comment]
I tried that - and got this result:

Found 0 files with 0 distinct sizes
Processing 'To Serve Them All My Days (1980) [mp4]', piece size=1.04 MB
    Matched=0, complete=13, ignored as not selected for download=0, no candidates=1, remaining=0 (total=14)
7/23/20 8:10 AM: Complete, downloads updated=0

But I am able to play the program.

I did try to check files before I wrote to you, and on all the ones I tried it on, nothing happened.  I know the status changes to checking, but it didn’t.

Thank you for your help though.

**Comment by parg** [comment]
You need to configure the dialog you get when selecting 'search for existing data files...' with the locations to search - i.e. the folder where you have the data files. You can either enter the location explicitly or add various folders to the default locations to search multiple places at once/make it easy to do a search again in the future.

The fact it says 'found - files with 0 distinct sizes' means that it didn't find any files to check against.
