### ISSUE TITLE
Issue regarding uninstallation

### ISSUE THREAD

**Issue by nocdoggo** [BiglySoftware/BiglyBT#1727]
Hi there, I installed BiglyBT via the installer .sh. Per previous issues, I wasn't able to locate the /biglybt folder, never the less, the uninstallaion folder.

I wonder what would be the best way to remove biglybt, and I know that java related packages should not be uninstalled. Yet, I can't find any meaningful wiki instructions.

Can someone shine some lights on this?

Thanks a lot in advanced!

System: Ubuntu 20.04

**Comment by parg** [comment]
Doesn't the installer just put stuff into ~/biglybt ?
