### ISSUE TITLE
Display Issues

### ISSUE THREAD

**Issue by Ddraig64** [BiglySoftware/BiglyBT#1728]
Display is corrupted. You can't always see the displayed info. It seems like a font error.

![image](https://user-images.githubusercontent.com/68854345/88540779-de415100-d013-11ea-853f-5fd00c50712c.png)

* OS and version Windows 10 Home Insider Preview Build 20170.rs_prerelease.200710.1419
* BiglyBT Version Number 2.4.0.1_B22
* For *nix: Desktop Environment

**Comment by parg** [comment]
See https://github.com/BiglySoftware/BiglyBT/issues/1700
