### ISSUE TITLE
Add search engine Android?

### ISSUE THREAD

**Issue by Solace50** [BiglySoftware/BiglyBT#1729]
I cannot seem to figure out where in the UI we would be able to add our own custom list of search engines. Or where would the config that is hosting in json be located?

Android 9
Latest Stable Bigly

**Comment by fabriba** [comment]
Hi, 
did you ever find out? thanks!

**Comment by TuxPaper** [comment]
You can take any .biglybt or .vuze search template file, save it to your android device, and launch it with your file browser app.  It should list BiglyBT as an app that can open it.  Afterwards, BiglyBT should display a message that the Search Template has been added.

We don't provide search template files, but you can export them in the BiglyBT desktop client and might be able to find some on the internet.
