### ISSUE TITLE
Feature Request: Adding/Selecting multiple torrents, allow tagging.

### ISSUE THREAD

**Issue by Napsterbater** [BiglySoftware/BiglyBT#1730]
Currently when you add multiple torrents or a folder of torrents in the Add torrent screen on the right hand side if you multi-select multiple torrents some options disappear, such are tagging, tio me it seems like motui selecting torrents should not exclude tagging.

**Comment by parg** [comment]
Trouble is you can set up auto-tagging to cause Tags to be selected based on file extensions - with multiple torrents this can result in consistent situation (e.g. an auto-selected Tag can have a save location...)

Now you could argue that having auto-tagging could cause the multi-tag view to be disabled, but it all gets a bit confusing and I'm not sure I want to go there.
