### ISSUE TITLE
Torrents Now added to START of Queue (previously END, no options changed)

### ISSUE THREAD

**Issue by dbareis** [BiglySoftware/BiglyBT#1731]
Torrents are now being added to the START of the queue Queue (as #1)
I can't find any option to change this but I'd also not changed any options for ages.

---
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4930r7, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.4.0.1_B24/4 az2

**Comment by parg** [comment]
There's a parameter named "Add Torrent Queue Position". It is set in the 'add torrent options' dialog and will be remembered for the next time, perhaps you changed it there?

**Comment by dbareis** [comment]
Thanks, I eventually found that option, but I didn't change it.  I have restored it to "Last".

- There have been a few instances where the remembered dialog positions have been forgotten, I wonder if that is related?
- Is "First" the default option?

**Comment by parg** [comment]
The default is 'last', there are quite a lot of contextual options that aren't represented in the explicit Options dialog.
