### ISSUE TITLE
Revolutionary workaround about peers under VPN connection

### ISSUE THREAD

**Issue by hatewesterncivilization** [BiglySoftware/BiglyBT#1732]
Java 1.8.0_252 (64 bit)
  Eclipse OpenJ9
c:\opj

SWT v4930r7, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.4.0.1_B24/4 az3

Paul, hi, men! 

I know uTP basically fashioned for getting peers through VPNs NAT.

Lots of VPN services just do not provide port forwarding feature, so, we can do think about good workaround, if that possible? Some third-party, maybe?

Don't you, Paul, knows any? Within Bigly.

**Comment by parg** [comment]
BiglyBT will already use a third-party (another BiglyBT peer) to try and establish a connection to a BiglyBT peer - the third party 'rendezvous' peer publishes its availability in the DHT and the peers attempt to arrange UDP NAT punching via it. 

Not sure how well I2P handles things with VPNs, all connections are relayed via third party nodes so in theory stuff should work.

Nobody is going to run dedicated third party relays for bittorrent traffic.

**Comment by hatewesterncivilization** [comment]
Understood, thanks. Surprisingly, KeepSolid VPN Unlimited getting incoming connections, while on the KeepWise UDP type of connection. But no matter, It small amount of connections.

But I'd observed, uTorrent on VPNs sligthly better getting peers even behind VPN's NAT.

And it's bad that uTorrent still yet not supported us, Bigly's DHT. 

And, another thing, some of third-party Windows tools that can provide incoming listening any port, so, we just use-in this port In Bigly? Any thoughts?

**Comment by hatewesterncivilization** [comment]
I'm gonna once again check that tool and see, if helps. Will message here, if any good result.
