### ISSUE TITLE
pieces map does not show full relative path

### ISSUE THREAD

**Issue by Xyrio** [BiglySoftware/BiglyBT#1733]
* OS and version: win7
* BiglyBT Version Number: 2.4.0.1_B24

problem:
when torrent with multiple files with same name in different folders exist, than it is hard to tell what file it is when mouse-over a piece.

expected:
show the full relative path in pieces map tab on mouse over, similar to the pieces tab files column. since the text can be very long maybe also auto word wrap on multiple lines.

i dont remember in which torrent i saw this. so i cannot provide an example.

**Comment by parg** [comment]
I'll add the file(s) relative paths as a tooltip, there isn't enough space in the header area

**Comment by Xyrio** [comment]
ah yea, even better. maybe one file per line to be better readable too.
