### ISSUE TITLE
`Dead Trackers` Tracker Template does not autoapply after adding a new tracker

### ISSUE THREAD

**Issue by TheBestPessimist** [BiglySoftware/BiglyBT#1737]
#### 10. I have a bad tracker which belongs to 3 torrents
![10  I have a bad tracker which belongs to 3 torrents](https://user-images.githubusercontent.com/4482210/90233241-7d44b600-de26-11ea-87c5-7af339ab5bc1.png)

#### 20. Bad tracker is not associated with any Tracker Templates
![20  Bad tracker is not associated with any Tracker Templates](https://user-images.githubusercontent.com/4482210/90233235-7c138900-de26-11ea-8c5e-9841bf69583b.png)

#### 30. Add bad tracker to the dead trackers template
![30  Add bad tracker to the dead trackers template](https://user-images.githubusercontent.com/4482210/90233232-7ae25c00-de26-11ea-8df3-d298f3ead26d.png)

#### 40. We can see the tracker is associated to the tempalte
![40  We can see the tracker is associated to the tempalte](https://user-images.githubusercontent.com/4482210/90233229-79b12f00-de26-11ea-9a88-cb52007e739d.png)

#### 50. After adding the tracker to the tracker template, i expect no torrents have this tracker. but the tracker is not removed
![50  After adding the tracker to the tracker template, i expect no torrents have this tracker  but the tracker is not removed](https://user-images.githubusercontent.com/4482210/90233224-79189880-de26-11ea-9a1d-6b6b8d102018.png)

#### 60. I have to manually reaplly the tracker template, in order for my tracker to be removed
![60  I have to manually reaplly the tracker template, in order for my tracker to be removed](https://user-images.githubusercontent.com/4482210/90233223-77e76b80-de26-11ea-8374-2a34bfdc00b5.png)

#### 70. Finally the tracker is removed
![70  Finally the tracker is removed](https://user-images.githubusercontent.com/4482210/90233218-761da800-de26-11ea-99d5-7b082648ab94.png)

I believe Tracker Template should be auto-re-applied when i add a new tracker to the dead tracker list. (note: i'm not sure if for new torrents this is auto applied, but i think it is)

Possibly related: https://github.com/BiglySoftware/BiglyBT/issues/1249

------

Java 14 (64 bit)
  AdoptOpenJDK
c:\program files\java

SWT v4930r7, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.4.0.1_B26/4 az3

**Comment by parg** [comment]
There's that option 'Remove from current and future downloads' on the AllTrackers right-click menu. That automatically creates or adds to a tag with configured to remove trackers and should do what you want (as opposed to you manually arranging things as you have and therefore being responsible for re-applying when desired)

**Comment by TheBestPessimist** [comment]
Thanks for the suuuuper quick answer. 

The problem with the proposed solution is that the option `Remove from current and future downloads` always wants to create a new tag/tracker template (`Add to existing action` is not selectable). Adding new trackers to the tracker template created when using that option are not automatically applied, so i am still at my initial situation.

Example: 
torrent has: `bad-tracker2` and `bad-tracker3` which i want to remove.

1. In All Trackers right click on `bad-tracker2` and move mouse over `Remove from current and future downloads` and chose `Add to New Action`. give name to the action `dead trackers 2`
1.5 :white_check_mark: tracker is removed from all torrent currently existing
2. In All Trackers right click on `bad-tracker3` and move mouse over `Remove from current and future downloads`.
3. `Add to existing action` is not selectable => 
4.1 i'm forced to `create new action` which is not what i want as i dont want to create the third tag `dead trackers 3`
4.5 move mouse over `Add To Tracker Template`, chose `dead trackers 2`
5 :x: the tracker `bad-tracker3` is not removed from all the torrents unless i do the reapply dance.

**Comment by parg** [comment]
Hmm, there's something broken if it doesn't allow you to add it to the previous 'action' - I'll take a look

**Comment by parg** [comment]
Yup, bug that. Fixed in next beta - thanks :)
