### ISSUE TITLE
I2P ECIES-X25519-AEAD-Ratchet

### ISSUE THREAD

**Issue by gh338** [BiglySoftware/BiglyBT#1738]
* Ubuntu 20.04
* BBT 2.4.0.1_B26
* KDE

Does the BBT i2p plugin support the new encryption ?
https://geti2p.net/de/docs/protocol/i2cp # 
i2cp.leaseSetEncType="4,0" should be used to support fallback for versions prior to 0.9.38

Thanks

**Comment by parg** [comment]
I just go with whatever the I2P devs release and assume their defaults are what they recommend

**Comment by gh338** [comment]
It shows still 0.9.46.1.1

**Comment by gh338** [comment]
okay working now 
i2cp.leaseSetEncType=4,0
builds ECIES tunnels also

!!! Thank YOU !!!

**Comment by gh338** [comment]
As this is a custom patch - can I share it with other beta testers ?

**Comment by parg** [comment]
sure, the more the merrier

**Comment by gh338** [comment]
Tested also with 
**i2cp.leaseSetEncType=4**
works as expeted.

Cheers

**Comment by parg** [comment]
Good stuff, thanks for testing!

**Comment by gh338** [comment]
A few days in - ElGamal + ECIES tunnels work in parallel just fine.

Thank you !
