### ISSUE TITLE
Name clash in completion moving folder leads to overwrite

### ISSUE THREAD

**Issue by KZ-Erge** [BiglySoftware/BiglyBT#1739]
If a torrent is added, and a file with the same name exist in the directory where completed torrents are moved, the already completed one is overwritten silently. 

I tracked it to DiskManagerImpl.java line 540, 
but i don't know why that check is there, so i don't know how to fix it.

To reproduce completion moving have to be set.
You can reproduce either by downloading a torrent, and after it finished add a different torrent which contains a file that has the same name as the previously downloaded one, or simply before adding a torrent create a dummy file in the completed torrents folder with the same name as the one in the torrent.
Either way the file in the completed torrents folder is taken over by the new torrent, and is overwritten.

Linux 4.9.0-6-amd64
B2.4.0.1_B24/4 az2
KDE 5.8.6

**Comment by parg** [comment]
Well the intent is that it is trying to detect the situation where a download has already completed and been moved to the completed-folder. If you have the 'truncate existing files that are too large' option enabled then I suppose this increases the chance of what you're encountering,

**Comment by parg** [comment]
Actually scrub that, the current logic will treat short files as OK, I've changed it so that for the 'do files already exist?' check it requires an exact file size match.
