### ISSUE TITLE
Torrent downloads stop after reaching ~10MB

### ISSUE THREAD

**Issue by Karlovsky120** [BiglySoftware/BiglyBT#1742]
OS: Windows 10 2004
BiglyBT version:  2.4.0.0

Java data:
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\programs\biglybt\jre

Other data:
SWT v4930r7, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.4.0.0/4 az3

After installing Windows 10 2004 update, BiglyBT would stop downloading all torrents after hitting the 10MB mark. It would still show them in downloading state, with plenty of fully established connection, but no down (or up) traffic would occur. I downloaded qBitTorrent and it worked without issues. BiglyBT is also on the firewall exception list, so I'm really not sure what is going on here.
I have tried this with several torrents, they all stop after they reach 10MB.

It's possible to stop and start the torrent after which another 10MB will be downloaded and the issue would repeat.

I tried reinstalling BiglyBT with the latest version from the official site (2.4.0.0), but the issue is still here.

Stopping a torrent also takes a stupidly long amout of time (it's now been 5 minutes and the torrent still isn't stopped).

This is one of the only torrent clients that enables streaming, so I'd be really sad if I had to switch to something else.

PS: I just found the log folder, I've attached debug_1.log and debug_2.log
[debug_1.log](https://github.com/BiglySoftware/BiglyBT/files/5110448/debug_1.log)
[debug_2.log](https://github.com/BiglySoftware/BiglyBT/files/5110454/debug_2.log)

Other log files didn't look like they had anything particularly interesting in them, so I won't include the unless you request them explicitly.

EDIT: After pausing and starting the torrent three times, it now seems to work fine. But I'm guessing this will happen again, as it did before.

**Comment by Karlovsky120** [comment]
The disk indeed seems to be a problem, with active time spiking and staying at 100% while this occurs. However, the write speed during that time is consistently >60MB/s.

I've checked settings and "Allocate and zero new files on creation" is disabled. Write complete pieces to disk immediately is enabled. Maximum write and read request queued are set to 5MB.

I never did change any of the default settings anyway.

Anyway, it seems that BiglyBT is keeping the disk busy, but I don't know why and what for.

**Comment by Karlovsky120** [comment]
I can confirm the same behavior on a 3GB/s NVMe drive. The pauses are much shorter, but something must be wrong if it locks up at all when downloading at 1MB/s to a drive with 3000MB/s write capacity.

**Comment by parg** [comment]
Did you try the 'sparse file' option?

**Comment by Karlovsky120** [comment]
I'll try it next time and report back. One thing I forgot to note is that this happens only then the torrent initially starts up. Once it manages to download ~60MB or so, it starts working fine.

**Comment by parg** [comment]
My guess is that the OS is allocating file space during the pauses. BitTorrent downloads pieces of the file at random, If you have a 50GB file and the first piece that happens to download is located at, say, 40GB into the file, then the OS might be allocating all of the space prior to that piece in order to write it, causing a pause. After the download has been running a while it is likely that some random pieces near the end of the file have been downloaded and the file is fully allocated, hence no more pauses.

**Comment by Karlovsky120** [comment]
I think that we can conclude that Windows is at blame here then. It did start happening after the 2004 update.
