### ISSUE TITLE
Malicious Code Discovered in jbigi.dll !! - 2nd Time this week !!

### ISSUE THREAD

**Issue by 00PHATE00** [BiglySoftware/BiglyBT#1744]
Malicious Code Detected in :  **jbigi.dll**
the detection is described as **PUA:Win32/iBryteInstaller**

- I thought maybe you nice chaps at BiglyBT might like to know about that as it is now the 2nd time this week that Windows Defender has Detected it !! 

- I am sure you didn't put it there yourselves !? -  you might wanna get on to that...Don't you think ?

** Keep up the Good work - BiglyBT is my fave Torrent Client....wouldn't want to have to Uninstall it !!   :-)

![BIGLY-INFECTED](https://user-images.githubusercontent.com/70301864/91374369-f7564100-e80f-11ea-8897-8222d8eddd88.jpg)

Windows 10 v10.0, amd64 (64 bit)
SWT v4930r7
B2.4.0.0/4 az3
Java 1.8.0_202 (64 bit)

**Comment by parg** [comment]
It isn't "there", it is a false positive. We did recently re-sign the DLLs with a newer certificate, there will be a release soon that includes the update but in the meantime you can join the beta program to get it to see if that helps.

Thanks for reporting though!
