### ISSUE TITLE
macOS Mavericks 10.9.5 not installing

### ISSUE THREAD

**Issue by macOS-Mavericks** [BiglySoftware/BiglyBT#1745]
The BiglyBT download page indicates the requirement of macOS / OS X 10.7.3 or higher - https://www.biglybt.com/download/. Java Version 8 Update 261 (July 14, 2020) installs on Mavericks successfully and supposedly all the way down to OS X Lion 10.7.3 . The current BiglyBT installer will not work on Mavericks 10.9.5 and indicates through an error message that macOS 10.11 is required for the BiglyBT Installer. The problem seems to stem from install4j version 8. Version 7.0.12 of install4j works with macOS 10.7 through 10.14.

Any chance you can throw the masses a bone who are either stuck on Lion 10.7.5 or the other crowd that are on Mavericks 10.9.5 please? Perhaps a 'Classic BiglyBT for OS X' since OS X name was used up until El Capitan 10.11 .There's a lot of Lion and Mavericks users that rely on current 2020 versions of Classic Waterfox and Pale Moon to browse, but all of the other OS X bittorrent clients haven't been updated since last year or longer. 

* OS X Mavericks 10.9.5
* BiglyBT 2.4.0.0

**Comment by TuxPaper** [comment]
Thanks for the heads up.  I think I have install4j v7 still installed, so it hopefully shouldn't be too hard to build an older installer for pre-10.11.

Looks like the last version using install4j v7 is 2.2.0.2.  This installer is at https://github.com/BiglySoftware/BiglyBT/releases/tag/v2.2.0.2 .  There's a chance installing that version might result in a jar update to the latest version on first run, but I haven't checked.

**Comment by macOS-Mavericks** [comment]
I forgot to mention that previously, I successfully installed 2.2.0.2 with Java Version 8 Update 261 (July 14, 2020) _already_ installed. What happens is the icon bounces for a very _long_ duration in Mavericks dock and then just sits there. Right clicking BiglyBT's icon shows me Application Not Responding and Force Quit. I manually uninstalled Java through Oracle's instructions and then reinstalled BiglyBT which trigged a new Java download and install. The results were the same, the application tries to open, but fails. With Java being installed via BiglyBT, there is no Java preference pane in System Preferences.

**Comment by TuxPaper** [comment]
I put a GitHub_BiglyBT_Installer_Old_MacOS_10.7-10.11.dmg in https://github.com/BiglySoftware/BiglyBT/releases/tag/v2.4.0.0
I could only test it on 10.13, but it seemed to work ok.

**Comment by macOS-Mavericks** [comment]
Appreciate your prompt efforts. Well, we got one step forward. The new OS X legacy 2.4.0.0 build installs on Mavericks 10.9.5 perfectly. Unfortunately, the app displays the same behavior, the icon bounces in the dock for a long duration of time, but it won't open. I tried to install BiglyBT 2.4.0.0 with the new and old UIs (after proper uninstalls), to see if that would make a difference because of SWT. I tried to figure out what version of SWT is bundled with this installer, but couldn't determine it.  I read that old PPC versions of Vuze struggled with SWT - http://wiki.vuze.com/w/Known_Issues#OSX_10.5_PPC_Issues . Is there any other details you can think of that I can provide you? Do you have a virtual machine that you could install Mavericks on? Here's a means to download old versions of macOS - https://github.com/corpnewt/gibMacOS & https://gist.github.com/foxlet/f0ee0fecf3fd90e88ad228e051c1d0d1 . Thank you again and I'll donate to the cause.
