### ISSUE TITLE
NAT/UDP Problem

### ISSUE THREAD

**Issue by gemosley** [BiglySoftware/BiglyBT#1746]
* Windows 10 Home (64 bit) Ver 1909
* BiglyBT Version 2.4.0.0
 
Suddenly, while executing a torrent activates BiglyBT, nothing appears in the active library.
Running a network test produced this:

Testing port TCP 57804 ... 
NAT Error - Connection to 107.181.189.44:57804 (your computer) refused.

Testing port TCP 57804 IPv6 ... 
Unable to test: Invalid port given, or test service failed.
Another application may already be using this port.. 
(Error: Connection timed out: connect).

Testing port UDP 57804 ... 
    Sending outbound packet and waiting for reply probe (timeout=5000)
    Sending outbound packet and waiting for reply probe (timeout=10000)
    Sending outbound packet and waiting for reply probe (timeout=15000)
    Sending completion event
NAT Error. Inbound test failed, timed out.

Testing port UDP 57804 IPv6 ... 
    Sending outbound packet and waiting for reply probe (timeout=5000)
    Sending outbound packet and waiting for reply probe (timeout=10000)
    Sending outbound packet and waiting for reply probe (timeout=15000)
    Sending completion event
NAT Error. Inbound test failed,PRUDPPacketHandler:sendAndReceive failed, 
Network is unreachable: Datagram send failed.

What can I do?

**Comment by parg** [comment]
Your initial stated problem seems to be nothing to do with NAT, rather that torrents aren't appearing in your library?

Rather than clicking on a torrent to get it added to BiglyBT try using the 'Open Torrents' button top left and browse to the .torrent file that way - see if they get added then.

**Comment by gemosley** [comment]
My apologies. I should have tried a different torrent. When the one I was after failed, I tried the diagnostic tests and saw the errors highlighted and assumed that was the problem. I've just tried a magnet for the same torrent and it worked OK as did a completely different torrent.
Thanks for your patience.

**Comment by parg** [comment]
No problem!
