### ISSUE TITLE
BiglyBT NOT completing initialization

### ISSUE THREAD

**Issue by david-bakin** [BiglySoftware/BiglyBT#1748]
[It won't start so I'm not exactly sure which version I have but it is definitely the latest beta as of today's date.]

BiglyBT was acting "funny" - very very slow UI update - as in it wasn't updating, and clicking on sidebar tab/buttons would highlight multiple tabs and the tab would only change 3-5 minutes later.  So I killed it.

Now it won't start.  It is not yet in the state "completed installation" as see by the dialog below when trying to generate a debug log via the menu - see screen capture below.

I'm pretty sure there's just a file or two that need deleting to "reset" biglybt without losing any torrents in progress ... but what?

![image](https://user-images.githubusercontent.com/4162948/92032099-7cfd5380-ed1e-11ea-8ff5-6bed32133cda.png)

**Comment by parg** [comment]
Anything in the debug_1/2.log files in the logs folder (%appdata%/BiglyBT/logs on win) ?

**Comment by david-bakin** [comment]
Nothing stands out in there.  But: I just moved *.log away (into a subdir) and restarted BiglyBt to get fresh logs and it _started right up!_  Torrents being downloaded.  It did immediately want to upgrade to 2401_B30 though.

So:  Maybe I didn't wait long enough.  (There are 4370 torrents in the library, though only about 10 active.)  Or maybe the pending upgrade had something to do with it?  dunno.
