### ISSUE TITLE
Allocating running multiple times.

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#1749]
While testing B30, I noticed this:

![image](https://user-images.githubusercontent.com/37715552/92046551-cebed180-ed50-11ea-8b4d-7fbb8eba636e.png)
Is it supposed to do this?

I have seen similar things like allocating and checking at the same time.   Perhaps for Allocating, Checking, Moving, Copying and other disk heavy activity.  A window like with moving. But as a queue, with additional line items extending down, and they get processed in a FIFO fashion.   Effectively One at a time, get in line.

Java 14 (64 bit)   AdoptOpenJDK  c:\program files\adoptopenjdk\jre-14.0.0.36-openj9
SWT v4930r7, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.4.0.1_B30/4 az3

**Comment by NaPurHab** [comment]
There were a number waiting at 0% to allocate, and only the last of the 3 was moving at the time.  But the top 2 should have been waiting at 0%.    As to Allocating and Checking, I have seen those running at the same time and dragging down performance.

**Comment by parg** [comment]
Please tell me if you actually see > 1 actively allocating at the same time, Allocating + checking will occur in parallel (although checking should be limited to one at a time as well)

**Comment by NaPurHab** [comment]
I watched it after posting, and while there with 3 with >0, only the last 1 was moving.
Would be better if the Allocating, Checking, Moving were all FIFO. Allocating/Checking at the same time slow my transfers.

**Comment by hatewesterncivilization** [comment]
I have those behavior, if I use antiviris software. Without it things pretty rocket.
