### ISSUE TITLE
Remote shutdown needs confirmation

### ISSUE THREAD

**Issue by Heisenbergsbluestuff** [BiglySoftware/BiglyBT#1750]
When using the remote shutdown feature to activate at the completion of downloads a confirmation dialogue pops up instead. For me the whole point of setting auto shut down is that I won't be there when the downloads complete so how can I therefore confirm shutdown?  Very frustrating each time I return to my laptop to find it is still running although all downloads have finished'

**Comment by parg** [comment]
There's an option, enabled by default, 'prompt to allow action to be aboted' - disable that?
