### ISSUE TITLE
Problem seeding with vpn

### ISSUE THREAD

**Issue by moi15moi** [BiglySoftware/BiglyBT#1751]
* Nvidia Shield 8.2.0 (32.6.435.1)
* BiglyBT 1.2.6.6 (build 1020606)

Hi,

Since I am using a vpn, I can not seed properly torrent. I have contacted ipvanish support but the problem does not seems to be on the vpn side.

Is there any option I need to enabled to allow vpn? Or any other option?

Thank you

**Comment by parg** [comment]
Not sure what version of BiglyBT you have there, there isn't a 1.2.6.6 (latest is 2.4)

What do you mean when you say you can't seed properly? The usual issue with VPNs is they often don't support incoming connections - if this is the case then peers can't connect to you but you can still connect to them to seed. In a reasonable sized swam this generally doesn't cause problems.

**Comment by moi15moi** [comment]
I use bigly on the nvidia shield.

Here is a proof that I have the 1.2.6.6 version (sorry I do not know how to take screenshot on the nvidia shield)
![20200905_125824](https://user-images.githubusercontent.com/34408507/92309969-c8f70500-ef77-11ea-8ded-4d4bc8dbd5d8.jpg)

Ipvanish allow the port forwarding, so I think it should support incoming connections.

**Comment by moi15moi** [comment]
Oh, I realise that there is a git for bigly android (https://github.com/BiglySoftware/BiglyBT-Android/issues).

I close this post to open one in the correct place
