### ISSUE TITLE
[feature request] %-needed column in the "peers" panel (lower pane of "incomplete")

### ISSUE THREAD

**Issue by david-bakin** [BiglySoftware/BiglyBT#1753]
In the "peers" panel of the "incomplete" tab one of the columns you can see is "%" - which is the percent completion of the peer (in that row).  As a suggestion for another possible column that could be added to this panel I'd _also_ like to see "% needed" (or maybe "% available") which is the % of what _your_ torrent needs that this peer has available.  E.g., if you're at 10% complete and the peer is at 15% complete but half of that 15% it has are pieces you're missing then I'd like to see "7.5" as "% needed". 

[BiglyBT Beta 2.4.0.1_B30, Windows 10 Pro]

**Comment by parg** [comment]
Say torrent has 1000 pieces. I am 10% complete so there are 900 remaining pieces I need.

Peer is 15% complete (has 150 pieces) but 75 of them are pieces I still need.

The 'percent of what I still need that they have' would be (75*100)/900 = 8.3%. Or are you after something else?

**Comment by david-bakin** [comment]
Oh.  That arithmetic clarifies things.  I'm thinking more of "how much will my percentage go up if I get all his pieces". 

So in this case, I've got 10% = 100 pieces.  He has 75 I need.  If I get them I'll have 175 pieces, therefore I'll be at 17.5% complete.  So I'd like to see 7.5.  (I'm pretty sure.)

By the way, one reason this is useful is the case where I'm not downloading the entire torrent - I've selected certain files from it.  In this situation the % column - which is how much of the _entire_ torrent the peer has, doesn't really say how much he's got that I want.

**Comment by parg** [comment]
B31 has a new column, tell me if that works

**Comment by david-bakin** [comment]
I'm running B31 now [Windows 10 Professional] but I don't actually see a "haveweneed" column.  Just the same "%" column as before.  Do I need to do something special?  (Like uninstall/reinstall, not just upgrade...)

**Comment by parg** [comment]
set your mode to advanced?

**Comment by parg** [comment]
it is called Available

**Comment by david-bakin** [comment]
Got it!  And looks great!

Here's a nit:  If the peer is complete (% = 100) then the Available column shows 100 not the amount remaining.  It's a nit because it doesn't matter: If the peer is complete then there's no question about what he's got that I need.

Thanks for the feature!

![image](https://user-images.githubusercontent.com/4162948/92841108-be34d980-f396-11ea-8d30-912d972700df.png)

**Comment by parg** [comment]
try B32

**Comment by parg** [comment]
B33 I mean, B32 was missing changes

**Comment by david-bakin** [comment]
Looking good!  thanks again!

**Comment by parg** [comment]
no problemo!
