### ISSUE TITLE
Limit the "checking" to ONE file per time

### ISSUE THREAD

**Issue by eurobank** [BiglySoftware/BiglyBT#177]
If a finished download is (re)cheched AND a downloading file is ALSO checking, there is a huge delay and pause to everything.

I think ONE check per time should be applied and the rest should be queued for checking (or re-checking).

Thanks

**Comment by parg** [comment]
Try Tools->Options->Files->Performance Options: friendly hash checking

**Comment by eurobank** [comment]
Tried that, seems not to work for me.

See:

![2017-12-03 14_48_04-](https://user-images.githubusercontent.com/4467158/33525494-33eba374-d839-11e7-96df-2efb377ce136.png)

**Comment by parg** [comment]
did it make the load on the system less severe though?

**Comment by eurobank** [comment]
I think it did. Not a major problem. still i think one check at time should be performed.

**Comment by parg** [comment]
If you select a bunch of files and manually recheck them then only one will run at a time. The 'seeding and checking' process is handled separately though and should be done fairly slowly so as to not impact uploading too much
