### ISSUE TITLE
Hi All!  I cannot Exit or Restart, but biglyBt runs properly (mostly)

### ISSUE THREAD

**Issue by gr88** [BiglySoftware/BiglyBT#178]
I cannot exit or restart biglyBt.  When I use the menu item to exit, the command seems to be ignored.  I have closed all other programs and let biglyBt sit for an hour, but it won't close.  The torrents continue to upload and download correctly.  I have been able to close it with xkill, or task manager killing java.  

I will post a different (unrelated?) question asking about the correct java and 64 bit or 32 bit.

Thanks for any help... Take care... gr88

I do not know what JNA is.

I am on 
biglyBt 1202b17.  
Linux 4.7.9-64 (x86_64) debian.  running in 64 bit mode.
openjdk version "1.8.0_141"
OpenJDK Runtime Environment (build 1.8.0_141-8u141-b15-1~deb9u1-b15)
OpenJDK Server VM (build 25.141-b15, mixed mode)

2017.11.30th 13:04 central time

**Comment by gr88** [comment]
Next observation.  I am now on 1201b18 (not 18a as far as I can tell).  Changing the beta version did not change my problem.  I found a way to Shut Down.  If I pick (File, Transfers, Pause).  
Then:  (File, Exit, answer yes to exit prompt);   it seems to shut down properly.  
But if I go straight to Exit, then the Exit prompt pops up, I answer yes, but it will not exit.
I tried both ways, with and without the confirm exit prompt.  
(tools, options, interface, show confirmation dialog on exit).  
I have also experimented with 
(tools, options, startup & shutdown, pause downloads on exit).

now is 2017.12.03 15:35


I will try to restart a few times to see if I can get the b18 to change to b18a.

**Comment by parg** [comment]
B18 was borked so B18a was released to fix the update process. It shows as B18 though, just to be confusing :) You have a strange problem - something must be deadlocking the shutdown process for you but not others :( If you look in the logs folder (~/.biglybt/logs I think) and examine the debug_1.log (and debug_2.log) file, are there any errors logged during close that might give us a clue?

**Comment by gr88** [comment]
Thanks Parg.  I'll check that log file...

**Comment by gr88** [comment]
I need to change some of my observations.
And give more hardware software info.
Some of my system specs are listed above.
I have 24 gig of ram, but consistently only use about 7.5 to 9.5 gig.
Sometimes my system seems to show I am running a 32bit system and sometimes 64 bit.
I would like to run java and biglyBt in 64 bit mode.

Tools, options, startup & shutdown, java options, 
max heap memory size = 2gb
min heap memory size = 2gb
max direct memory size = 2gb
these options have greatly speeded up biglyBt for most functions & lowered cpu time.  The settings seem to not affect some hidden background tasks that still take a long time, such as shutdown.
Notice below what seems to be 3 million milliseconds to shut down.

 dumpThreads (AEJavaManagement.java:72), dumpThreads (AEDiagnostics.java:265), perform (CoreImpl.java:1640), runSupport (TimerEvent.java:133), AERunnable.run, ThreadPool.runIt
DEBUG::Mon Dec 04 21:29:20 EST 2017::com.biglybt.core.util.AEDiagnostics::markClean::393:
  Marking as clean
    stopSupport (CoreImpl.java:1810), runSupport (CoreImpl.java:1549), AERunnable.run, run (CoreImpl.java:1508), run (AEThread2.java:295)
DEBUG::Mon Dec 04 21:25:54 EST 2017::com.biglybt.core.util.ListenerManager::addListener::135:
  check this out: lots of listeners!
    addPeerListener (DownloadManagerImpl.java:3284), setRateLimit (TagDownloadWithState.java:611), access$6 (TagDownloadWithState.java:599), taggableAdded (TagDownloadWithState.java:259), dispatch (TagBase.java:100), dispatch (TagBase.java:1), doDispatch (ListenerManager.java:438), dispatchInternal (ListenerManager.java:496), dispatch (ListenerManager.java:301), dispatch (ListenerManager.java:232), addTaggable (TagBase.java:1132), addTaggable (TagWithState.java:256), addTaggable (TagDownloadWithState.java:406), stateChanged (GlobalManagerImpl.java:4311), dispatch (DownloadManagerImpl.java:154), dispatch (DownloadManagerImpl.java:1), doDispatch (ListenerManager.java:438), dispatchInternal (ListenerManager.java:520), dispatchLoop (ListenerManager.java:563), run (ListenerManager.java:366), run (AEThread2.java:295)
core.stop done in 3006077   (<<<<<< notice this giant number says gr88)
DEBUG::Mon Dec 04 21:23:28 EST 2017::com.biglybt.core.dht.transport.udp.impl.DHTTransportUDPImpl::setLocalContact::1326:
  DHTTransport: address changed to /123.456.789.01:12345 (changed by gr88)
    run (DHTTransportUDPImpl.java:1097), run (AEThread2.java:295)
DEBUG::Mon Dec 04 21:20:52 EST 2017::com.biglybt.core.networkmanager.impl.tcp.TCPConnectionManager::addNewRequest::534:
Exit from BiglyBT complete
No shutdown tasks to do
BiglyBT TERMINATED.


Java 1.8.0_141 (32 bit)
  Oracle Corporation
/usr/lib/jvm/java-8-openjdk-i386/jre

SWT v4757, gtk/3.22.0
Linux v4.7.9-64, i386 (32 bit)
B1.2.0.1_B19/4 az3

**Comment by parg** [comment]
To run in 64-bit mode you should just need to install the 64-bit version of the Java runtime environment - are you saying that sometimes it chooses 32 and sometimes 64?

So did it really take 3000 seconds (50 minutes) to shutdown or is that a weird log?

Out of interest, how many downloads do you have active (downloading/seeding) when you close BiglyBT?

**Comment by gr88** [comment]
Good morning (at least in my world) !  I spent a couple of days making backups, installing new drives, & moving files around.  I am running Linux Debian Knoppix 7.7.1 which boots as 64 bit. The knoppix people might mention "mixed mode" in the documentation.  I did apt-get update & apt-get install default-jre which automatically chooses 32 bit java.  Yes, it really did take 3000 seconds to shutdown.  But now I do not have the shutdown problem (SOLVED)!!!  In versions 1201b22(maybe), b23 & b24 I have been able to shutdown & restart correctly.

I have 566 total torrents running now. I plan on seeding several hundred more (there are many linux distributions out there).  551 torrents listed as "inactive" and about 14 "active" as listed in "My Torrents" in the left sidebar with the advanced library view.  At the moment there are 10 in the downloading area which usually just sit there because there are no seeds.  All the rest are in the seeding area.  I tend to run about 1megaByte per second up at all times.  I limit each ip address to 50kB up per second.  

By the way, I am very impressed and like so many of the old and new features you at biglyBt have added!  Some that come to mind are:  sequential file download, sequential up or down from a piece number, speed limits that are fine-tunable (such as my 50kB per ip address), the new file highlighting of pieces, media url, and heaps of other features.  Some of the features I am aware of, and lots which run smoothly in the background.  Thank you. ...gr88

Java 1.8.0_151 (32 bit)    Oracle Corporation  /usr/lib/jvm/java-8-openjdk-i386/jre
SWT v4757, gtk/3.22.0  Linux v4.7.9-64, i386 (32 bit)  B1.2.0.1_B24/4 az3

**Comment by parg** [comment]
gr8 news! Let's hope it keeps behaving :) Glad you're enjoying the news features - if you think of anything else that would help you then send it over. Happy holidays!
