### ISSUE TITLE
Embedded Media Player issues/clarity/launching default player

### ISSUE THREAD

**Issue by GregariousJB** [BiglySoftware/BiglyBT#1782]
```
Java 1.8.0_252 (64 bit)
  AdoptOpenJDK
c:\program files\adoptopenjdk\jre-8.0.252.09-hotspot

SWT v4930r7, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B2.4.0.0/4 az3
```

```
File names blurred to protect the innocent. 

![image1](https://i.imgur.com/5zvbDYM.png)

![image2](https://i.imgur.com/xbq7o3g.png)

Also:

1. Restarting the program multiple times does not help.
2. Completely disabling the embedded media player plugin (azemp) does not help, it only makes double-clicking media files do nothing.

I don't want to use an embedded media player. I have a much more advanced player that allows me to download subtitles and use
```

Alright, I figured out how to fix this myself while writing this issue and enclosed the problem in a code block above.

The fix: `Options > Interface > Tables > "Double click in torrent views" > Launch`

It was such an ordeal just being able to do this that I'm submitting this issue in the hopes that this process can be made more clear. It makes sense to have the program "Launch" files by default instead of using some crappy embedded player that immediately recommends the user install something else. No offense. 

This is much of a cry for help for future generations of BiglyBT users as it is a first-timer review. So take it with a grain of salt, or just close this issue if you disagree. In any case, thank you for a viable qBittorrent alternative with no ads.

**Comment by parg** [comment]
Or you can use the 'launch helpers' config there to specify what to launch based on file extension.

I suppose it isn't hugely clear, glad you figured things out!

**Comment by GregariousJB** [comment]
> Or you can use the 'launch helpers' config there to specify what to launch based on file extension.
> 
> I suppose it isn't hugely clear, glad you figured things out!

That's part of the problem that I show in those screenshots above. The table launch helpers do nothing.
