### ISSUE TITLE
Odd display glitch

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#1785]
I was experimenting with the settings in `Plugins:Friends` when I saw the following happen:

**Before**
![image](https://user-images.githubusercontent.com/37715552/93524295-4b7dae00-f902-11ea-8a68-11d885ce0ffd.png)

**After**
![image](https://user-images.githubusercontent.com/37715552/93524350-618b6e80-f902-11ea-80ef-190e4177fe07.png)

Just disappears. When I choose a different item from the categories on the left, then back to `Plugins:Friends` it returns.

![image](https://user-images.githubusercontent.com/37715552/93524733-f2624a00-f902-11ea-87c8-37e343484c4e.png)

![image](https://user-images.githubusercontent.com/37715552/93524564-b0390880-f902-11ea-9f63-8898eabc6b91.png)

**Comment by parg** [comment]
Fixed next beta, thanks!
