### ISSUE TITLE
Thank you very much for the program!

### ISSUE THREAD

**Issue by mrkaban** [BiglySoftware/BiglyBT#1789]
Thank you very much for such a cool program and a special thank you for distributing it under the GNU GPL version 2! It is the second version that guarantees that the product based on this program will also be free!

Added a program to a Russian-language site about free software, here's the [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D0%BD%D0%B5%D1%82/%D0%B7%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B8/biglybt-torrent.html)!

The program is very cool, please don't abandon the project!

PS: This is the best torrent client in my opinion!

**Comment by parg** [comment]
Thank you very much! 

Our Russian translation is around 60% complete, if you know anyone who wants to contribute to that then please send them our way.

https://crowdin.com/project/biglybt/ru#

:)

**Comment by mrkaban** [comment]
Thank! I will provide a link to the site for translation in the comments! I myself will try to help if possible!
