### ISSUE TITLE
Support for network drives

### ISSUE THREAD

**Issue by macdojoh** [BiglySoftware/BiglyBT#179]
My network drives do not appear in the selection dialog when select a place to save downloaded information to.

Also my imported Vuse config doesn't work because it was configured to save to my network drives. The drives are mapped to a letter.

Just wondering if there is more configuration I need to do, or is this not supported.

**Comment by parg** [comment]
The drive selection dialog is native, not a BiglyBT component, so if they are present in Windows then they should be selectable. For me things are working...

**Comment by macdojoh** [comment]
The file selection works, but the dialogs between Vuse and Bigly are different. Vuse has the full dialog with the links to short cuts and Bigly only has the smaller one to select a folder.

The big issue, is Bigly isn't working with the Vuse config I imported which uses mapped network drives to save downloaded information in. Wasn't sure if there was more config I needed to do or something with the JVM?

**Comment by shanevbg** [comment]
I was using Vuse for a long time, all my files are on network drives. For me, BiglyBt works much better than Vuse (which I just switched from this week) browsing my network drives.  I am using Windows 10 with Oracle's Java 8 Update 121.  My config from Vuse came over without any problems, including my library and addons.

**Comment by parg** [comment]
great :)

**Comment by macdojoh** [comment]
That maybe my issue, Vuse is Java 1.8.0_121 and Bigly is 1.8.0_152. What does your file dialog look like when you open it to select a folder, the simple one where you have to browse for a folder or the bigger one with your shortcuts and file listings?

**Comment by shanevbg** [comment]
I have the full file dialogue
That said, I went to the help-about in BiglyBt and this is what it reported.  
Java 1.8.0_152 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4757, win32
Windows 10 v10.0, amd64 (64 bit)
B1.2.0.0/4 az3
