### ISSUE TITLE
Regression Crash during close the app (~1 year ago)

### ISSUE THREAD

**Issue by d00rsfan** [BiglySoftware/BiglyBT#1797]
* OS and version Ubuntu 19.10, 20.04
* BiglyBT Version Number since 2.3.0.1_Beta_xx
* For *nix: Desktop Environment Gnome
~1 year ago one morning i found biglybt is not running (after attempt to autoupdate). No more successful restarts after that.
App crashes during closing, so restart doesn't work, update not applied.  syslog is (slightly anonymized). There is 3k+ lines log from app folder: [hs_err_pid504829.log](https://github.com/BiglySoftware/BiglyBT/files/5286270/hs_err_pid504829.log)
 `
Sep 25 19:08:19biglybt.desktop[504829]: core.stop
Sep 25 19:08:26biglybt.desktop[504829]: DEBUG::Fri Sep 25 19:08:26 2020  Skeleton builds: 4000
Sep 25 19:08:46java[504829]: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed
Sep 25 19:08:46biglybt.desktop[504829]: #
Sep 25 19:08:46biglybt.desktop[504829]: # A fatal error has been detected by the Java Runtime Environment:
Sep 25 19:08:46biglybt.desktop[504829]: #
Sep 25 19:08:46biglybt.desktop[504829]: #  SIGSEGV (0xb) at pc=0x00007f6accc9b14b, pid=504829, tid=504848
Sep 25 19:08:46biglybt.desktop[504829]: #
Sep 25 19:08:46biglybt.desktop[504829]: # JRE version: OpenJDK Runtime Environment (14.0.1+7) (build 14.0.1+7-Ubuntu-1ubuntu1)
Sep 25 19:08:46biglybt.desktop[504829]: # Java VM: OpenJDK 64-Bit Server VM (14.0.1+7-Ubuntu-1ubuntu1, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
Sep 25 19:08:46biglybt.desktop[504829]: # Problematic frame:
Sep 25 19:08:46biglybt.desktop[504829]: # C  [libswt-pi3-gtk-4934r5.so+0x4914b]  Java_org_eclipse_swt_internal_gtk_OS_G_1OBJECT_1TYPE+0x0
Sep 25 19:08:46biglybt.desktop[504829]: #
Sep 25 19:08:46biglybt.desktop[504829]: # Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /home/username/biglybt/core.504829)
Sep 25 19:08:46biglybt.desktop[504829]: #
Sep 25 19:08:46biglybt.desktop[504829]: # An error report file with more information is saved as:
Sep 25 19:08:46biglybt.desktop[504829]: # /home/username/biglybt/hs_err_pid504829.log
Sep 25 19:08:46biglybt.desktop[504829]: core.stop done in 27141
Sep 25 19:08:46biglybt.desktop[504829]: Compiled method (n/a)  547610 3834     n 0       org.eclipse.swt.internal.gtk.OS::G_OBJECT_TYPE (native)
Sep 25 19:08:46biglybt.desktop[504829]:  total in heap  [0x00007f6aeb9ce190,0x00007f6aeb9ce518] = 904
Sep 25 19:08:46biglybt.desktop[504829]:  relocation     [0x00007f6aeb9ce2e8,0x00007f6aeb9ce318] = 48
Sep 25 19:08:46biglybt.desktop[504829]:  main code      [0x00007f6aeb9ce320,0x00007f6aeb9ce510] = 496
Sep 25 19:08:46biglybt.desktop[504829]:  oops           [0x00007f6aeb9ce510,0x00007f6aeb9ce518] = 8
Sep 25 19:08:46biglybt.desktop[504829]: Compiled method (n/a)  547610 3834     n 0       org.eclipse.swt.internal.gtk.OS::G_OBJECT_TYPE (native)
Sep 25 19:08:46biglybt.desktop[504829]:  total in heap  [0x00007f6aeb9ce190,0x00007f6aeb9ce518] = 904
Sep 25 19:08:46biglybt.desktop[504829]:  relocation     [0x00007f6aeb9ce2e8,0x00007f6aeb9ce318] = 48
Sep 25 19:08:46biglybt.desktop[504829]:  main code      [0x00007f6aeb9ce320,0x00007f6aeb9ce510] = 496
Sep 25 19:08:46biglybt.desktop[504829]:  oops           [0x00007f6aeb9ce510,0x00007f6aeb9ce518] = 8
Sep 25 19:08:46biglybt.desktop[504829]: Compiled method (n/a)  547613 3834     n 0       org.eclipse.swt.internal.gtk.OS::G_OBJECT_TYPE (native)
Sep 25 19:08:46biglybt.desktop[504829]:  total in heap  [0x00007f6aeb9ce190,0x00007f6aeb9ce518] = 904
Sep 25 19:08:46biglybt.desktop[504829]:  relocation     [0x00007f6aeb9ce2e8,0x00007f6aeb9ce318] = 48
Sep 25 19:08:46biglybt.desktop[504829]:  main code      [0x00007f6aeb9ce320,0x00007f6aeb9ce510] = 496
Sep 25 19:08:46biglybt.desktop[504829]:  oops           [0x00007f6aeb9ce510,0x00007f6aeb9ce518] = 8
Sep 25 19:08:46biglybt.desktop[504829]: [thread 505103 also had an error]
Sep 25 19:08:46biglybt.desktop[504829]: #
Sep 25 19:08:46biglybt.desktop[504829]: # If you would like to submit a bug report, please visit:
Sep 25 19:08:46biglybt.desktop[504829]: #   Unknown
Sep 25 19:08:46biglybt.desktop[504829]: # The crash happened outside the Java Virtual Machine in native code.
Sep 25 19:08:46biglybt.desktop[504829]: # See problematic frame for where to report the bug.
Sep 25 19:08:46biglybt.desktop[504829]: #
Sep 25 19:08:47biglybt.desktop[504738]: /home/username/biglybt/biglybt: line 251: 504829 Aborted                 (core dumped) ${JAVA_PROGRAM_DIR}java -Xmx256m -cp "${CLASSPATH}" "-Djava.library.path=${PROGRAM_DIR}" "-Dazureus.install.path=${PROGRAM_DIR}" "-Dazureus.script=$0" ${JAVA_PROPS} ${JAVA_ARGS} ${START_CLASS} ${OTHER_PARAMS} "$@"
Sep 25 19:08:47biglybt.desktop[504738]: Exit from BiglyBT complete
Sep 25 19:08:47biglybt.desktop[505740]: WARNING: An illegal reflective access operation has occurred
Sep 25 19:08:47biglybt.desktop[505740]: WARNING: Illegal reflective access by com.biglybt.core.util.spi.AENameServiceJava12 (file:/home/username/biglybt/BiglyBT.jar) to field java.net.InetAddress.nameService
Sep 25 19:08:47biglybt.desktop[505740]: WARNING: Please consider reporting this to the maintainers of com.biglybt.core.util.spi.AENameServiceJava12
Sep 25 19:08:47biglybt.desktop[505740]: WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
Sep 25 19:08:47biglybt.desktop[505740]: WARNING: All illegal access operations will be denied in a future release
Sep 25 19:08:47biglybt.desktop[504738]: No shutdown tasks to do
Sep 25 19:08:47biglybt.desktop[504738]: BiglyBT TERMINATED.
Sep 25 19:08:47systemd[2581]: gnome-launched-biglybt.desktop-504738.scope: Succeeded.
`

**Comment by parg** [comment]
Crash in SWT for some reason (the graphics library we use)
