### ISSUE TITLE
Updates installing to %AppData%\Local\Biglybt

### ISSUE THREAD

**Issue by WolfSabian** [BiglySoftware/BiglyBT#1801]
This has been an issue for a while now. Despite configuring and installing to C:\Program Files\Biglybt updates install to %AppData%\Local\Biglybt and then run that installation.

Any way to prevent this?

**Comment by TuxPaper** [comment]
I've never heard of this issue happening before.  Did the installer ask to invoke Admin privileges, or maybe you are running as a different user than when you first installed? It feels like that maybe the installer couldn't write to C:\Program Files for whatever reason, and fell back to AppData :(

**Comment by WolfSabian** [comment]
It's been an issue for a while. I thought I resolved it. But apparently not. It did not ask for admin privileges. If I manually install it goes fine, but launching the update via biglybt does not. I will start program with admin privileges and do the update.

**Comment by WolfSabian** [comment]
Running BiglyBT with admin privileges results in the update process also doing so, allowing the updates to be installed to the correct location.

I think it's a good idea that if the current installation folder is not accessible/writable the client be notified, rather than an additional installation be the result.
