### ISSUE TITLE
2 "How to" questions, regarding forced adding a torrent with supposedly zero seeders.

### ISSUE THREAD

**Issue by Dragonsi2** [BiglySoftware/BiglyBT#1803]
Bigly version: 2.5.0.1_B04
Win 10.18363

Hello,

I'm an advanced bit torrent users, and have been using mostly Utorrent for  ~17 years now. I have Utorrent on my older computer, Deluge on my newer computer, and I just installed Bigly on my laptop yesterday. I have the Advanced, all settings showing. I have 2 questions on how to do something.

1.) I'm downloading on my normal site, and see a new 6 episode tv series, but apparently it wasn't popular, and is a reality show, with only a couple of seeders for each of the 6 episodes. But every episode says there is at least 1 seeder per torrent, some even 6-10 seeders.  5 of the 6 finished, but the 6th one refuses to find a seeder even though it says at least one on the webpage. It just sits there as a small window and I have hit the blue refresh button on it many times in the 8-10 hours since I started yesterday. Now I'm ready to reboot my computer and close Bigly. Is there something under advanced settings that I haven't noticed to allow me to force it to add it to the list, so it can find the seeder the next time on it's own, when I boot it up? Both Deluge and Utorrent automatically add magnets/torrents if there are seeders or not, so I thought this was strange. 

For my browser, I do keep "Remember all tabs and reopen on start from last session", and I would have to keep 2 specific torrent pages on my tabs so I don't forget about them since the program is refusing to allow me to add them even it says there are seeders. At least it's on my list. If, in the next week, it never finds a seeder, I can just delete it from the list myself.

2.)  On both Deluge and Utorrent, there is an option to set seeding level to "0", instead of "1", and the file immediately goes into finished mode instead of sharing mode.  My famous ISP company never said a word about my downloads for 6 years now, and had just temporarily suspended my internet last until I had a "talk" with them and was told about copyrights etc.  

How do I set it to NOT share, and go immediately into STOPPED mode?  I'm guessing it's this, which I just found as I was typing this up, I didn't see this option when I installed it yesterday.  "Allocate and zero new files on creation." Then below that: "Stop the download after files have been allocated."?  I just checkmarked those boxes as I'm typing this up to see.  I also had found under Downloading "Set amount uploaded to give a share ratio of 1.0 when adding partially completed downloads."  and wasn't sure if I should checkmark that box or not.

**Comment by parg** [comment]
Regarding (1) when adding a magnet link to BiglyBT initially you will get the small progress window regarding the metadata download. You will also get a 'metadata download' torrent added to the downloading section of the Library after a 20 seconds (configurable under Options->Plugins->Magnet URI Handler). This metadata download will be recovered across restarts and continue attempting to download the magnet. It will eventually time out and be removed though unless you fiddle with the config for this (same place)

2) I guess you are talking about a download going directly to a Stopped state on completion of downloading. Obviously this is not 'good P2P behaviour' as you are probably not giving back as much as you might to other downloaders. You can configure this behaviour though by setting up a Tag with a tag constraint of 'isComplete()' and setting its 'execute on assign' action to 'Stop'

**Comment by d00rsfan** [comment]
Nice question and answer (1) < set Overall lookup timeout to 0, hope magnets will not disappear if not peers found during short term.
