### ISSUE TITLE
Bigly BT update files issues

### ISSUE THREAD

**Issue by TheBestPessimist** [BiglySoftware/BiglyBT#1812]
I download to `C:/torrentz-temp` (ssd), then on completion the torrents are moved to `D:/torrentz`. 

All BBT updates + plugin updates are:
1. not moved to the final folder on completion, but are left in the temp directory - i guess this is a good thing
2. not cleaned up, and i have files left there since April 2020 (probably when i started using BBT) - this is not cool

![image](https://user-images.githubusercontent.com/4482210/94938312-570fce00-04d9-11eb-9bfd-c4284bb887f9.png)

May i suggest BBT creates its own folder `.BiglyBtUpdates` and downloads the files there instead of polluting the root of user's folders?
Example:
- temp download location: `C:/torrentz-temp/.BiglyBtUpdates/`
- completed torrent download location: `D:/torrentz/.BiglyBtUpdates/`

Also: i have 2 more requests here:
1. It would be nice if BBT update torrents would have their own tag, for easier management
2. If 1. is implemented, then an automatic cleanup rule could also be implemented, based on tags and date added/completed

------

Java 15 (64 bit)
  Oracle Corporation
c:\program files\java

SWT v4930r7, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.5.0.1_B09/4 az3

**Comment by NaPurHab** [comment]
All updates are Tagged as 'Untagged'.  The solution is to find them in 'Untagged' and MOVE them where you want them.  Then go to Tag Overview and set the 'Initial Save Location' for 'Untagged' to your preferred storage location.

**Comment by NaPurHab** [comment]
BTW, here is what my Tag settings are for 'Untagged'.
![image](https://user-images.githubusercontent.com/37715552/95145503-61380380-0749-11eb-964a-c3cedfa4dd88.png)

**Comment by TheBestPessimist** [comment]
Thanks for the input @NaPurHab , but that "untagged" tag does not really apply to me:
![image](https://user-images.githubusercontent.com/4482210/95160978-945eaf00-07aa-11eb-8c39-e32bd05eb975.png)

I guess, since i have 2 global tags which apply to all downloads, the updates are also moved out of untagged.

**Comment by NaPurHab** [comment]
It is much easier to just use the auto tagging found in 'interface/tags'.  You can tag the files by extension, and any that don't match fall through to a final tag.
![image](https://user-images.githubusercontent.com/37715552/95163971-0ddcaa00-0777-11eb-92f5-d1c71a93e033.png)
Another way to add tags is in `files/torrents` , you can import torrents from multiple paths. I use google drive to save torrents on my tablet or my laptop on the go, and my home machine imports them from google drive.  Each import path has a tag associated with it.  And in all these, I manage to allow the BBT updates/plugins to fall through the filters to Untagged.

If you rethink your settings, you can easily get it to filter so you can get the BBT files to fall into a final Tag.

**Comment by TheBestPessimist** [comment]
Pinging @parg about this.

![image](https://user-images.githubusercontent.com/4482210/101246569-dc537100-371c-11eb-9821-2cba7a3bf38f.png)
My "temp download" folder has 1GB of files only from BBT updates. 
Could we have some sort of autocleaning for these?
