### ISSUE TITLE
Disk View is empty - how do I set it up?

### ISSUE THREAD

**Issue by david-bakin** [BiglySoftware/BiglyBT#1819]
[Windows Server 2016 Datacenter, BiglyBT 2.5.1.1.B13]

Disk view seems to show a lot of nothing even when torrents are active and running nicely.  Do I need to do something to turn it on?  Maybe in the Options?  (Or maybe in the OS itself?)

![image](https://user-images.githubusercontent.com/4162948/95471535-e46a7c80-0936-11eb-83a8-c12cad737f5f.png)

**Comment by parg** [comment]
It shows major operations - allocation, checking, moving. For general IO there's the 'cache view' under statistics. I need to add some documentation to this effect!
