### ISSUE TITLE
VPN Helper showing Bad with PIA Next Generation network 

### ISSUE THREAD

**Issue by ggowins** [BiglySoftware/BiglyBT#1821]
* Ubuntu 20.04
* BiglyBT 2.5.0.0.
* VPN Helper 5.10

For v5.10 of the VPN Helper, I'm getting Bad reported when using PIA's Next Generation network.  It appears to be working ok, as I can run the NAT/Firewall test and it is using the forwarded port, but it appears that PIA changed the network settings for the tunnel with Next Generation.  Here's what I get when checking the Port Forwarding/IP Binding:

check - BiglyBT is currently bound to /10.27.17.3 aka tun0(tun0) 
X - Subnet Bitmask for /10.27.17.3 aka tun0 (tun0) is 24.  Minimum is 30
X - Non-BiglyBT probably routing through /10.27.17.3 aka tun0(tun0).  Subnet Bitmask is 24.  Minimum is 30
X - Can't determine VPN's local IP
X - Keep existing binding of tun0
check - PIA CLI is active.  Last open port status returned was '48586'

If I switch back to the PIA Current Network, it will show as Good.

**Comment by bennettbrad** [comment]
Confirming that I'm getting a similaar issue:
Debian 10
BiglyBT 2.5.0.0
VPN Helper 5.1.0

Messages are the same except:
check PIA CLI active. Last open port status returned was "Inactive"

**Comment by TuxPaper** [comment]
ggowins, do you know if the tun0 (10.27.17.3) listed was the actual PIA interface?  

If it is, then I should be able to loosen the subnet bitmask to 24, and maybe throw in a config option to override that value.

**Comment by ggowins** [comment]
Yep, `ip a` shows that the tun0 address matches what the VPN Helper is reporting

**Comment by TheScottMan** [comment]
I confirm same problem with PIA on "next gen" network. This was causing me such a headache and so I am grateful for the tip here. Something seriously wrong with PIA next gen since i got all kinds of other problems using that as well.

**Comment by ggowins** [comment]
Got the updated plugin.  Seems to be working as expected now!  I'll keep an eye on it over the next few days.

**Comment by ggowins** [comment]
Looks great.  Thanks for the fix!
