### ISSUE TITLE
Setting to immediately exit

### ISSUE THREAD

**Issue by hatewesterncivilization** [BiglySoftware/BiglyBT#1823]
Hello. It would be nice trick, so, exiting procedure gonna be very fast. 

About savings states, just do that before exit. 

Hope, Paul will be not against.

**Comment by parg** [comment]
There's an option to disable the progress indicator on close: Interface->Display: Various - Wait for BiglyBT to close...

**Comment by hatewesterncivilization** [comment]
I think that's not what I mean actually, ok, maybe you further give a try for that. Thanks.

But this is super-need trick, I think.

**Comment by parg** [comment]
Kill it using task manager then - of course everything will be in a mess on restart

**Comment by hatewesterncivilization** [comment]
Paul, point is a pre-made of savings.
