### ISSUE TITLE
Add monero donation address to website

### ISSUE THREAD

**Issue by t-900-a** [BiglySoftware/BiglyBT#1825]
You're missing [monero](https://getmonero.org)
https://www.biglybt.com/donation/donate.php

**Comment by TuxPaper** [comment]
Thanks for noticing! XMR/Monero address added to page.  For reference, our XMR address is 43pYoLDNKw4GdUxpJ8D2ETSdCxbSeFob1PiH1Jfg6Jgg2AHsY9URMBw8WGvL2ZS8ER4amP66RFVjtZXsY864BzaC5urU3ND
