### ISSUE TITLE
application freeze when selecting multiple torrents

### ISSUE THREAD

**Issue by Slayn5** [BiglySoftware/BiglyBT#1827]
The application often freeze when I  select multiple torrents.
It randomly freeze when I multi select torrents but it hangs 100% of the times when I select multiple incomplete torrents and click using the left or right mouse button anywhere.
The interface stop responding and the only way to close it is to terminate the application. I already tried to wait a few hours to check if interface would start responding again but it didn't.

When I start the application from a console, there is no error displaying when it start freezing.
Is there any way to get more verbose logging to see what's happening?

* OS and version
Debian GNU/Linux 10 (buster)
4.19.0-11-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17) x86_64 GNU/Linux

* BiglyBT Version Number
2.5.0.0

* For *nix: Desktop Environment
xcfe

* About System
ava 11.0.8 (64 bit)
  Debian
/usr/lib/jvm/java-11-openjdk-amd64

SWT v4934r5, gtk/3.24.5, zoom=100, dpi=96
Linux v4.19.0-11-amd64, amd64 (64 bit)
B2.5.0.0/4 az3

**Comment by parg** [comment]
If it is the interface that is freezing but other non-UI components are still working then you may be able to grab some diagnostics by following 

https://github.com/BiglySoftware/BiglyBT/wiki/Diagnostics

**Comment by Slayn5** [comment]
Thanks!
With the diagnostics URL I'm getting
```
[02:20:57] [stderr] DEBUG::Wed Oct 21 02:20:57 EDT 2020::com.biglybt.ui.swt.extlistener.StimulusRPC$MyExternalStimulusListener::receive::110:
[02:20:57] [stderr]   Warning: Bad JSON String: ;
[02:20:57] [stderr]     ExternalStimulusHandler$2::set::131, MagnetPlugin$4::set::684, MagnetURIHandlerImpl::process::1080, MagnetURIHandlerImpl$1$1::run::197, AEThread2$threadWrapper::run::317
[02:20:57] [stderr] java.lang.Error: Lexical Error: Unmatched Input.
[02:20:57] [stderr]     at org.json.simple.parser.Yylex.yylex(Yylex.java:295)
[02:20:57] [stderr]     at org.json.simple.parser.JSONParser.parse(JSONParser.java:41)
[02:20:57] [stderr]     at org.json.simple.JSONValue.parse(JSONValue.java:28)
[02:20:57] [stderr]     at org.json.simple.JSONValue.parse(JSONValue.java:37)
[02:20:57] [stderr]     at com.biglybt.util.JSONUtils.decodeJSON(JSONUtils.java:50)
[02:20:57] [stderr]     at com.biglybt.ui.swt.extlistener.StimulusRPC$MyExternalStimulusListener.receive(StimulusRPC.java:110)
[02:20:57] [stderr]     at com.biglybt.util.ExternalStimulusHandler$2.set(ExternalStimulusHandler.java:131)
[02:20:57] [stderr]     at com.biglybt.plugin.magnet.MagnetPlugin$4.set(MagnetPlugin.java:684)
[02:20:57] [stderr]     at com.biglybt.net.magneturi.impl.MagnetURIHandlerImpl.process(MagnetURIHandlerImpl.java:1080)
[02:20:57] [stderr]     at com.biglybt.net.magneturi.impl.MagnetURIHandlerImpl$1$1.run(MagnetURIHandlerImpl.java:197)
[02:20:57] [stderr]     at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:317)
[02:20:57] java.lang.Error: Lexical Error: Unmatched Input.
        at org.json.simple.parser.Yylex.yylex(Yylex.java:295)
        at org.json.simple.parser.JSONParser.parse(JSONParser.java:41)
        at org.json.simple.JSONValue.parse(JSONValue.java:28)
        at org.json.simple.JSONValue.parse(JSONValue.java:37)
        at com.biglybt.util.JSONUtils.decodeJSON(JSONUtils.java:50)
        at com.biglybt.ui.swt.extlistener.StimulusRPC$MyExternalStimulusListener.receive(StimulusRPC.java:110)
        at com.biglybt.util.ExternalStimulusHandler$2.set(ExternalStimulusHandler.java:131)
        at com.biglybt.plugin.magnet.MagnetPlugin$4.set(MagnetPlugin.java:684)
        at com.biglybt.net.magneturi.impl.MagnetURIHandlerImpl.process(MagnetURIHandlerImpl.java:1080)
        at com.biglybt.net.magneturi.impl.MagnetURIHandlerImpl$1$1.run(MagnetURIHandlerImpl.java:197)
        at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:317)
```

So I disable the magnet plugin and restart and now I'm getting:

```
[02:27:14] [stderr] java.lang.UnsupportedOperationException: IPv6 not available
[02:27:14] [stderr]     at java.base/sun.nio.ch.DatagramChannelImpl.<init>(DatagramChannelImpl.java:155)
[02:27:14] [stderr]     at java.base/sun.nio.ch.SelectorProviderImpl.openDatagramChannel(SelectorProviderImpl.java:46)
[02:27:14] [stderr]     at java.base/java.nio.channels.DatagramChannel.open(DatagramChannel.java:187)
[02:27:14] [stderr]     at lbms.plugins.mldht.kad.utils.AddressUtils.getDefaultRoute(AddressUtils.java:215)
[02:27:14] [stderr]     at lbms.plugins.mldht.kad.DHT.start(DHT.java:734)
[02:27:14] [stderr]     at lbms.plugins.mldht.azureus.MlDHTPlugin$9.runSupport(MlDHTPlugin.java:670)
[02:27:14] [stderr]     at com.biglybt.core.util.AsyncDispatcher$1.run(AsyncDispatcher.java:161)
[02:27:14] [stderr]     at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:317)
[02:27:18] DEBUG::Wed Oct 21 02:27:18 EDT 2020  Skeleton builds: 1000
[02:27:20] [GUI] Table Cell Plugin for Column #r1c2:this plugin is crazy. tried to refresh 10 times in 74ms
  Debug::getStackTrace::317, TableCellSWTBase::pluginError::660, TableCellSWTBase::refresh::733, TableViewImpl$6::run::1888, TableViewImpl::runForAllRows::535, TableViewImpl::columnInvalidate::1
878, TableViewImpl::columnInvalidate::1901, TableStructureEventDispatcher::columnInvalidate::128, TableColumnImpl::invalidateCells::815, ColumnDateSizer::recalcWidth::338, ColumnDateSizer::acces
s$2::278, ColumnDateSizer$4::runSupport::245, AERunnable::run::36, Utils::execSWTThread::1053, Utils::execSWTThread::1219, ColumnDateSizer::refresh::224, ColumnDateSizer::refresh::181, DateAdded
Item::refresh::100, ColumnDateSizer::refresh::176, TableColumnImpl::invokeCellRefreshListeners::914, TableCellSWTBase::refresh::790, TableViewImpl$6::run::1888, TableViewImpl::runForAllRows::535
, TableViewImpl::columnInvalidate::1878, TableViewImpl::columnInvalidate::1901, TableStructureEventDispatcher::columnInvalidate::128, TableColumnImpl::invalidateCells::815, ColumnDateSizer::reca
lcWidth::338, ColumnDateSizer::access$2::278, ColumnDateSizer$4::runSupport::245, AERunnable::run::36, Utils::execSWTThread::1053, Utils::execSWTThread::1219, ColumnDateSizer::refresh::224, Colu
mnDateSizer::refresh::181, DateAddedItem::refresh::100, ColumnDateSizer::refresh::176, TableColumnImpl::invokeCellRefreshListeners::914, TableCellSWTBase::refresh::790, TableViewImpl$6::run::188
8, TableViewImpl::runForAllRows::535, TableViewImpl::columnInvalidate::1878, TableViewImpl::columnInvalidate::1901, TableStructureEventDispatcher::columnInvalidate::128, TableColumnImpl::invalid
ateCells::815, ColumnDateSizer::recalcWidth::338, ColumnDateSizer::access$2::278, ColumnDateSizer$4::runSupport::245, AERunnable::run::36, Utils::execSWTThread::1053, Utils::execSWTThread::1219,
 ColumnDateSizer::refresh::224, ColumnDateSizer::refresh::181, DateAddedItem::refresh::100, ColumnDateSizer::refresh::176, TableColumnImpl::invokeCellRefreshListeners::914, TableCellSWTBase::ref
resh::790, TableViewImpl$6::run::1888, TableViewImpl::runForAllRows::535, TableViewImpl::columnInvalidate::1878, TableViewImpl::columnInvalidate::1901, TableStructureEventDispatcher::columnInval
idate::128, TableColumnImpl::invalidateCells::815, ColumnDateSizer::recalcWidth::338, ColumnDateSizer::access$2::278, ColumnDateSizer$4::runSupport::245, AERunnable::run::36, Utils::execSWTThrea
d::1053, Utils::execSWTThread::1219, ColumnDateSizer::refresh::224, ColumnDateSizer::refresh::181, DateAddedItem::refresh::100, ColumnDateSizer::refresh::176, TableColumnImpl::invokeCellRefreshL
isteners::914, TableCellSWTBase::refresh::790, TableViewImpl$6::run::1888, TableViewImpl::runForAllRows::535, TableViewImpl::columnInvalidate::1878, TableViewImpl::columnInvalidate::1901, TableS
tructureEventDispatcher::columnInvalidate::128, TableColumnImpl::invalidateCells::815, ColumnDateSizer::recalcWidth::338, ColumnDateSizer::access$2::278, ColumnDateSizer$4::runSupport::245, AERu
nnable::run::36, Utils::execSWTThread::1053, Utils::execSWTThread::1219, ColumnDateSizer::refresh::224, ColumnDateSizer::refresh::181, DateAddedItem::refresh::100, ColumnDateSizer::refresh::176,
 TableColumnImpl::invokeCellRefreshListeners::914, TableCellSWTBase::refresh::790, TableViewImpl$6::run::1888, TableViewImpl::runForAllRows::535, TableViewImpl::columnInvalidate::1878, TableView
Impl::columnInvalidate::1901, TableStructureEventDispatcher::columnInvalidate::128, TableColumnImpl::invalidateCells::815, ColumnDateSizer::recalcWidth::338, ColumnDateSizer::access$2::278, Colu
mnDateSizer$4::runSupport::245, AERunnable::run::36, Utils::execSWTThread::1053, Utils::execSWTThread::1219, ColumnDateSizer::refresh::224, ColumnDateSizer::refresh::181, DateAddedItem::refresh:
```

Interface is freeze will cpu usage of the process still use 35%.
What is "#r1c2:this" column? Can I disable it?

**Comment by parg** [comment]
Ignore the spew when you hit the diagnostics URL and re-enable the magnet plugin, that message just happens to come out when you grab diagnostics.

Go to the logs folder and locate the file called ThreadDump.log and upload the contents of it here please.

Also when you have high CPU usage to to Tools->Options->Startup & Shutdown, scroll to the bottom and hit the 'JVM memory usage history' 'View' button and copy/paste the results here.

You might have to set your 'mode' to 'advanced' under Options->Mode to see the memory usage button

**Comment by Slayn5** [comment]
I also notice that max heap memory size was set to 1 GB, so I set it blank to use the default memory value. But the issue still occur.

Here are the files you requested.

[debug_1.log](https://github.com/BiglySoftware/BiglyBT/files/5435323/debug_1.log)
[JVMMemoryUsageHistory.txt](https://github.com/BiglySoftware/BiglyBT/files/5435324/JVMMemoryUsageHistory.txt)
[ThreadDump.log](https://github.com/BiglySoftware/BiglyBT/files/5435325/ThreadDump.log)

Thanks!

**Comment by parg** [comment]
Thanks for that - I took a look and the thread dump shows that a thread is active enabling/disabling toolbar state but nothing more useful :(

I installed the latest Debian Buster and Xfce desktop, installed BiglyBT and added 10 downloads to the incomplete section and I don't see any issues with selecting multiple downloads and clicking around - this is running in VirtualBox VM.

**Comment by Slayn5** [comment]
Thanks for your time you took for testing on a VM.

Actually I have about 1000 torrents. I can't multi select for a while (maybe a year) so I can't easily do a cleanup and just accumulate torrents over time.

My guest is when I multi select torrents, it start computing something over all the torrents maybe.
I tried looking at the code to find what happen when a do a multi selection but it will take me a while to understand it.

But good news, I isolate the problem on my side. It seems that it doesn't occur as long as the "files" sub-tab is closed.
That's weird because my torrents doesn't have lots of files.

**Comment by parg** [comment]
Ah, ok, the FilesView thing gives a good clue. When you multi-select torrents the FilesView is built to show ALL the files in the selected torrents which I guess could be slow/use a lot of memory.

Perhaps there should be a limit to the number of torrents that it will do that for as most likely people don't often use that information anyway.

**Comment by parg** [comment]
Out of interest, how many files do you think you have in the multi-selection? I have a client with 1000 torrents but they are all single-file torrents - this builds the FilesView pretty rapidly.

**Comment by Slayn5** [comment]
When displaying the column "files" I can see that the smallest number of file is 1 and the biggest is 782.
I have test again selecting only torrents with 1 files when "files" sub-tab is opened and it still freezing the UI even if I only selected 2 or 3 torrents at a time.

**Comment by Slayn5** [comment]
I just copy paste the ~/biglybt/biglybt to ~/biglybt/biglybt-test
Modify the  -Dazureus.config.path to point to .biglybt-test.
Add some torrents (16 torrents). All stopped! Some was started and stopped by accidents.

At first the multi selection was working well. I tried various variations like opening the statistics Windows and modify torrent to select a file priority to "Do not download". But now even if I revert those variations a can still reproduce the multi selection bug that I have everytime. Still the only way to prevent this bug is to close the "files" sub-tab again.

I have tried on my Windows machine with the last version and I cannot reproduce the bug.

I think that next step (when I will have the time) will be to try on a VM like you did to see if I can still manage to reproduce the bug.

**Comment by Dingmatt** [comment]
I can confirm I'm seeing the same crash on v2.5.0.0 using Mint 20 inside a VM, the applications GUI seems to completely crash if you attempt to select multiple torrents via the library 'tab'.

**Comment by parg** [comment]
Which desktop?

**Comment by parg** [comment]
I installed Mint 20 with Cinamon Desktop - I have 20 torrents loaded with around 250 files between them - selecting them all doesn't cause me any issues.

**Comment by parg** [comment]
Having just said that it crashed for me :(

**Comment by Dingmatt** [comment]
I'm using Xfce and the size of the torrents doesn't seem to be a factor, even if it's only a few files per torrent it'll crash as soon as multiple torrents are selected

**Comment by Slayn5** [comment]
I have reproduce de problem on a VM machine. Debian Buster latest version with xfce.
The way I reproduce it:
- Add some torrents.
- Restart biglybt.
- Make sure the "files" sub-tab (FilesView) is selected.
- Play around using shift + left mouse button click and then the left mouse button anywhere to make a new selection.
- It doesn't always freeze the first time. But it shouldn't be too hard to reproduce after a few selections.

**Comment by Slayn5** [comment]
Actually it is not that easy on a fresh install. I have reproduce the bug two times. But now it seems it has become harder to reproduce.

**Comment by Slayn5** [comment]
I tried using gnome instead of xfce but still able to replicate the problem.
