### ISSUE TITLE
Unable to add trackers

### ISSUE THREAD

**Issue by DeathStalker77** [BiglySoftware/BiglyBT#183]
Ok, so you can REMOVE any existing Tracker, but you cannot ADD extra trackers the way you can with uTorrent - you can ONLY add after you REMOVE (and then add as text) - VERY inefficient!.  Unit this feature is implemented, BiglyBT is useless to me  :(

**Comment by parg** [comment]
Can you explain your problem? For me I can right-click on a torrent, select 'Tracker/Torrent' and then 'Edit tracker URLs' - in the editor window I can right-click on the tree structure to manipulate it or simply hit the 'edit as text' to manually add/remove/structure the trackers. Same can be done from the 'Sources' tab

**Comment by DeathStalker77** [comment]
Ok, maybe that is the issue - I was trying to select it in the TRACKER tab.  Let me try it the way you describe.

**Comment by DeathStalker77** [comment]
Ok, I am able to do that the way you describe - however, I can only do it once the client is started.  It would be MUCH more helpful to have the ability to edit trackers when you ADD the torrent or magnetic link, as you can with uT.  I will say that I was VERY impressed with the speed I got from BiglyBT by comparison!

**Comment by parg** [comment]
You can add edit trackers in the 'open torrent options' dialog (make sure you have this set to show when adding torrents - Tools->Options->Files - near the top the is a 'When opening a torrent, show options dialog:' parameter that you should have set to 'every time'.

Then when the dialog pops up expand the 'tracker, peers and connection options' panel near the bottom and hit the 'edit trackers' button

**Comment by DeathStalker77** [comment]
I have that enabled and I see the EDIT TRACKERS button, but it is grayed out.

**Comment by parg** [comment]
Perhaps it is a private torrent

**Comment by DeathStalker77** [comment]
Shouldn't matter - there are occasions I may want to add additional trackers.  If it can be done when it is already added, it should be able to be done here as well.  Design flaw.

**Comment by parg** [comment]
false

**Comment by DeathStalker77** [comment]
False?  WTF?  What kind of an answer is that?

**Comment by parg** [comment]
You can't add trackers to a private torrent - go read up on it
