### ISSUE TITLE
Display Issue: Transfer Bar: ETA does not match actual next ETA

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#1830]
![BBT ETA not matching](https://user-images.githubusercontent.com/37715552/96952809-b00dc900-14bd-11eb-8164-8665a7cd4374.png)

Transfer Bar does not match the actual next ETA.

_BTW, this shows a slowdown in UL Speed. Before starting the DLs, the speed was between 120-140 Mbits/s. After clipping the image, I paused all DLs.  The speed of ULs returned to around 120 Mbits/s. There is a definite proformance shift._

![image](https://user-images.githubusercontent.com/37715552/96953508-38409e00-14bf-11eb-91d3-efbeaf5708a1.png)

Java 1.8.0_271 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_271

SWT v4930r7, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.5.0.1_B16/4 az3

**Comment by parg** [comment]
What about if you enable the 'smoothed eta' column? does that match?

**Comment by NaPurHab** [comment]
Where? I did a search in options on 'smoothed eta', 'eta', 'smooth',  I can't find it.

**Comment by parg** [comment]
Column setup for Library - right-click on the Library header area and select 'Column Setup' - search for 'smooth'

**Comment by NaPurHab** [comment]
Thats why I could not find it. It was not a setting, but a duplicate column that is not where one would think to look.  But that only shows an alternate way to see ETA. Doesn't explain why the Transfer Bar is not following the 'ETA' Column, which is the default column. Not to mention the Label in the Transfer Bar is `Next ETA`, not `Smoothed ETA of all running DLs`.  

Anyway, I only noticed because the Transfer Bar is easier for me to Read.
![image](https://user-images.githubusercontent.com/37715552/97047813-86997f80-1547-11eb-9d5e-8804a2414a94.png)
The background Graph on the speed in the bottom right of the main window, causes a reduction of contrast that is hard for me to read. So, the use of the Transfer Bar, as it is simple B+W. Not to mention the entire Status Line is already on a Light Grey Background to start with. Would be nice if I could right click on the Speeds in the Status Bar, and be able to Turn Off/On the background graphic.

**Comment by parg** [comment]
Many things would be nice. It would be nice to be paid for the time I spend on BiglyBT.
