### ISSUE TITLE
bad

### ISSUE THREAD

**Issue by SP77** [BiglySoftware/BiglyBT#1831]
Hello all. I've been having an issue for the past few weeks any time I use the program and would love some help. Whenever I open Bigly, I blue screen a few minutes later. According to BlueScrenView the issue is as follows;

![image](https://user-images.githubusercontent.com/16098219/96954841-47751b00-14c2-11eb-8847-a3dda6adaa37.png)

I've tried to access the 127.0.0.1 diagnostics page but Edge Dev won't let me (I even added it to my antivirus Eset Endpoint), and I looked over the log file but don't know what I'm looking for.

I've googled the error and found results stating it's probably relating to the network driver. I had rolled back one version thinking it would work but it didn't. I've also uninstalled Bigly hoping a fresh install would fix the issue but no luck there either. Any help would be greatly appreciated. Let me know if I can update with any further info. Stay Corona free ya'll , unless it's the kind you celebrate with.

OS=Windows 10 Pro x64 Build 2004
BiglyBT Version=2.5.0.0<!--

**Comment by parg** [comment]
duplicate
