### ISSUE TITLE
BAD POOL CALLER

### ISSUE THREAD

**Issue by SP77** [BiglySoftware/BiglyBT#1832]
Hello all. I've been having an issue for the past few weeks any time I use the program and would love some help. Whenever I open Bigly, I blue screen a few minutes later. According to BlueScrenView the issue is as follows;

![image](https://user-images.githubusercontent.com/16098219/96954841-47751b00-14c2-11eb-8847-a3dda6adaa37.png)

I've tried to access the 127.0.0.1 diagnostics page but Edge Dev won't let me (I even added it to my antivirus Eset Endpoint), and I looked over the log file but don't know what I'm looking for.

I've googled the error and found results stating it's probably relating to the network driver. I had rolled back one version thinking it would work but it didn't. I've also uninstalled Bigly hoping a fresh install would fix the issue but no luck there either. Any help would be greatly appreciated. Let me know if I can update with any further info. Stay Corona free ya'll , unless it's the kind you celebrate with.

OS=Windows 10 Pro x64 Build 2004
BiglyBT Version=2.5.0.0

Update edit: I ran whocrashed and the issue it pointed to is Malwarebytes web protection (mwac.sys). Still working on it on my end.

Edit #2-Just noticed it double posted. My apologies, not sure how that happened.<!--

**Comment by parg** [comment]
Your crash details point to the error occurring in fwpkclnt.sys - you need to figure out what that file is part of? A google shows people with similar issues, e.g.

https://answers.microsoft.com/en-us/windows/forum/all/bsod-badpoolcaller-caused-by-fwpkclntsys/de2aa2cb-2c0e-4d7b-ba12-f3b8e01a56e5 ?

**Comment by SP77** [comment]
> Your crash details point to the error occurring in fwpkclnt.sys - you need to figure out what that file is part of? A google shows people with similar issues, e.g.
> 
> https://answers.microsoft.com/en-us/windows/forum/all/bsod-badpoolcaller-caused-by-fwpkclntsys/de2aa2cb-2c0e-4d7b-ba12-f3b8e01a56e5 ?

Thanks for the response. Thankfully, I seem to have sorted it out. It was malwarebytes' web control that was causing the issue. Was torrenting last night for a few hours and no issue. Bigly's running now too and so far so good. I'll post back with updates if changes occur. Fingers crossed...lol. Wanted to also say thanks for such a great program. Had been using Vuze since literally the moment I learned about torrenting. Probably 12 years ago (if that's possible. It seems that way anyway) and while I was hesitant to change, I have no regrets. I'm glad you guys decided to build on the goodness of Vuze.

**Comment by parg** [comment]
Thanks!
