### ISSUE TITLE
Deleting multiple torrents with pre-selected option "Apply action to all xx selected entries"

### ISSUE THREAD

**Issue by Stepcraft** [BiglySoftware/BiglyBT#1834]
When deleting multiple torrents, is there a way to have the option "Apply action to all xx selected entries" pre-selected with a check-mark? I have the option "Delete .torrent file as well" pre-selected (I found this option in settings), but I can't find a way to do the same for "Apply action to all xx selected entries".

Thank you!

My specs:
iMac 27" / 24 GB / 3.4 GHz Intel i7 / macOS 10.13.6 (64 bit)
Java 1.8.0_261 (64 bit) / BiglyBT B2.2.0.2/4 az3

![BiglyBT Delete Content](https://user-images.githubusercontent.com/59187451/97035758-a7e47680-151b-11eb-8ce8-51278bb01c4e.jpg)

**Comment by Stepcraft** [comment]
Is there no solution for this?

**Comment by parg** [comment]
It is a bit of a dangerous option to auto-select, that's why I believe it isn't remembered

**Comment by Stepcraft** [comment]
Hmm... But, for those of us that would like this option, it would save us a lot of time. I'm not suggesting for this option to be added and then be checked by default. A user would need to go into preferences to choose it. This new option would be perfect to add in Preferences/Files/ right below "By default, delete .torrent file when deleting content". :)

Big thanks to all your hard work on BiglyBT. It's an amazing piece of software!

**Comment by parg** [comment]
sigh, ok

**Comment by Stepcraft** [comment]
I just upgraded to version 3.0.0.0 and was very delighted to see that you implemented this option. I was still using version 2.8.x, so you may have implemented this option earlier than 3. I'm very happy to have this feature!

THANK YOU!!!
