### ISSUE TITLE
VPN binding broken

### ISSUE THREAD

**Issue by drogongod** [BiglySoftware/BiglyBT#1835]
It detected my vpn Surfshark and I ok Binding. it stopped downloading any and all Torrents and I see no way to unbind it.
I am assuming it Exists but it useless if there are no instructions to do so or reset default unbinded state.  

* windows 10
* BiglyBT 2.5.0.0
*  windows 10

**Comment by parg** [comment]
Look in the status bar. There is a 'routing icon'. Right click it to get an option to remove it.

**Comment by drogongod** [comment]
![status](https://user-images.githubusercontent.com/16511480/97095124-a903c980-1629-11eb-8ebe-e36e5dfb9333.png)
![status 2](https://user-images.githubusercontent.com/16511480/97095127-aa34f680-1629-11eb-9ed3-00111235c3d0.png)
 I do not see It.

**Comment by drogongod** [comment]
The Very Bottom line I got it lol

**Comment by parg** [comment]
:P
