### ISSUE TITLE
Copying magnet URL to clipboard on v2 only torrent adds v1 btih

### ISSUE THREAD

**Issue by Radtoo** [BiglySoftware/BiglyBT#1836]
Biglybt 2.5.0.0, Linux

I assume "v2 only" torrents should not add the v1 "btih" part when copying their magnet URL to clipboard.

While it appears to have no ill consequences on BiglyBT, it potentially fools a whole lot of v1-only clients into thinking they can handle the torrent.

**Comment by parg** [comment]
I like the idea that legacy clients will be able to download v2 torrents via the truncated v2 hash and then find that they can't handle them.

**Comment by Radtoo** [comment]
I don't think it works out well.

It doesn't seem obvious to most humans what is going on. And the v1 clients themselves just keep trying to connect and do something, wasting some bandwidth. Many don't seem to give up on their own.

Will it not be enough and more elegant for v1 only clients to realize that they have no handler for btmh, "as intended" with v2 only torrents?

**Comment by TuxPaper** [comment]
my understanding (correct me if I'm wrong, parg) is a client not supporting v2 will be able to get the torrent just fine -- but the client will throw an error saying the torrent is an invalid format (because it's missing the v1 keys).   Clients may even have a friendly message like "Sorry, we don't support v2 Torrents right now" or "v2 support coming soon", or "This is a v2 Torrent, you should download BiglyBT"

It shifts the blame from "why can't my client download magnet uri's from BiglyBT" to "Why does my client say a .torrent file retrieved from a magnet is invalid?"

**Comment by parg** [comment]
well I don't know exactly "what is intended" - the v2 BEP has no mention of btmh, I only found out about it via the libtorrent blog.

**Comment by Radtoo** [comment]
> well I don't know exactly "what is intended" - the v2 BEP has no mention of btmh, I only found out about it via the libtorrent blog.
I also only saw that there, and equally have no idea where they've got it from. But it does very specifically suggest that there is v1 sha1 (btih) and v2 sha256 (btmh).  I currently very much believe it'd be wise to just assign magnets that way (e.g v1 gets btih, v2 btmh, v1&v2 hybrid both of them). 

Or are there any positive effects of providing a sha-1 btih for v2 only torrents? I really currently only see negative effects.

> Clients may even have a friendly message like "Sorry, we don't support v2 Torrents right now" or "v2 support coming soon", or "This is a v2 Torrent, you should download BiglyBT"
I imagine the clients that update will just support v2 rather than advertising their friendly competition.

But consider how long the old clients that assume they'll get v1 torrents via btih are realistically going to be around and just waste bandwidth. Meanwhile if you just go with btmh for v2, I think users will realize they need to do something because these just won't work on the old clients.

**Comment by parg** [comment]
Thanks for your input!

**Comment by Radtoo** [comment]
Sure, thanks for listening and your hard work!
