### ISSUE TITLE
Do not create .pad files on v2 only torrents

### ISSUE THREAD

**Issue by Radtoo** [BiglySoftware/BiglyBT#1837]
BiglyBT 2.5.0.0

If I understand BEP 52 (the torrent v2 spec) correctly, I believe pure v2 torrents should not need to have any padding files, only hybrid v1&v2 torrents. But v2 only torrents created in BiglyBT generate a complete set of .pad files regardless.

**Comment by parg** [comment]
It doesn't create pad files, it is an implementation artifact

**Comment by as-muncher** [comment]
I'm finding that I can't change the download priority for the .pad folder in my torrent.  

Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.1.0.1_B11/4 az3
