### ISSUE TITLE
Doesn't always show full title of download

### ISSUE THREAD

**Issue by RegProctor** [BiglySoftware/BiglyBT#1839]
If I copy a magnet and paste it into the "Find Torrents" area the title is always correct. If I click on a magnet link in a browser then only up the to first space in the title will show so the title "The awesome thing" will just show as "The" when I click on a magnet in my browser.

* OpenSUSE Leap 15.2
* Browser: FireFox
* BiglyBT 2.5.0.0
* For KDE: Desktop Environment

**Comment by parg** [comment]
Is the magnet URI in the browser correctly escaped? Spaces should be represented by %20 or perhaps + signs.

**Comment by parg** [comment]
Here's an example that works fine when opened in Google Chrome for me:

magnet:?xt=urn:btih:IC6N4WEFUP4GZO7CP6OJEBAU3DNQB37S&dn=core_BiglyBT%20++2501-B16-signed.jar

The title shows as 'core_BiglyBT   2501-B16-signed.jar'
