### ISSUE TITLE
Why not have a simple forum for discussion?

### ISSUE THREAD

**Issue by DeathStalker77** [BiglySoftware/BiglyBT#184]
This would seem very easy to do, and VERY helpful.

**Comment by parg** [comment]
What would you suggest that is free to use (both in terms of software and hosting)?

**Comment by DeathStalker77** [comment]
Unfortunately not my area of expertise.

**Comment by parg** [comment]
But you said it would 'seem very easy to do'...

**Comment by DeathStalker77** [comment]
By that I mean that a lot of inexperienced people can set up forums or blog software that is open source.  This is not my area of expertise - mine is in design UI/UX.

**Comment by wangchung69** [comment]
get something thrown up on some $9 a month resold vps service somewhere or on a free azure account,  I know you can get phpbb servers for free if you turn over ad revenue its just been years since I bothered.    I would offer space but my vps is down for about a month

**Comment by user8446** [comment]
If you want to go the free route, you can use www.nabble.com . Then, just make it a subdomain such as forum.biglybt.com . I did just that in a few minutes: itus.accessinnov.com . You can also use google groups. I'm sure there are others out there.

**Comment by dbareis** [comment]
Google forums, Google+

**Comment by mblauser** [comment]
Google Groups sounded like a great idea. I have functionality questions but lack a place to address them. It was easy enough to create a discussion forum for BiglyBT. The group is set as public to join and requires joining before posting. Provide me details on who should be promoted as owners/moderators after joining.

Google Groups Forum:
[https://groups.google.com/d/forum/biglybt](https://groups.google.com/d/forum/biglybt)


Here is the code for embedding the discussion forum into biglybt.com's website:

`<iframe id="forum_embed" src="javascript:void(0)" scrolling="no" frameborder="0" width="900" height="700">`
`</iframe>`
`<script type="text/javascript">
  document.getElementById('forum_embed').src =
     'https://groups.google.com/forum/embed/?place=forum/biglybt'
     + '&showsearch=true&showpopout=true&showtabs=false'
     + '&parenturl=' + encodeURIComponent(window.location.href);`
`</script>`

**Comment by KonoromiHimaries** [comment]
i think a discord or reddit is a better solution for that

**Comment by TheBestPessimist** [comment]
If there's a forum software which i love, that would be: Discourse!

Here's the discourse meta forum (where discourse devs participate in the community): https://meta.discourse.org/.
For another example, here's a second forum, to which i am an admin of: https://forum.duplicacy.com/, for a specific software (so it fits the same category as BiglyBT). _(note to repository owners: if the second link is too much/should not belong, please edit my comment as appropriate)_.

As for costs: if you wanna self-host you can go with the cheapest VPS you want, as long as it has at least 2GB of ram. On the other hand, i think you may be eligible to have free hosting from discourse itself as per here: https://blog.discourse.org/2018/11/free-hosting-for-open-source-v2/.

**Comment by skycommand** [comment]
GitHub has recently added a forum feature that could be activated per-repo.

**Comment by parg** [comment]
My previous experience of running a forum is that the management of it was way too much effort.

**Comment by TexMcc** [comment]
Found this list with just a basic search, could do a bit more research if this is a real possibility. I would LOVE a dedicated forum    

    Forumotion – http://www.forumotion.com/
    Lefora – http://www.lefora.com/
    ProPhpBB – https://www.prophpbb.com/
    ProBoards – https://www.proboards.com/
    Nabble – https://nabble.com/
    Former – http://www.forumer.com/
    FreeForums – http://www.freeforums.org/
    BoardHost – http://boardhost.com/
    CreateAForum – http://www.createaforum.com/
    IcyBoards – http://icyboards.com/
    SMFNew – http://www.smfnew.com/ (This one is a bonus for people looking for SMF forum – if you unaware of what SMF is, its Simple Machines Forum open source forum software).

**Comment by jeffward01** [comment]
If the creators / maintainers @parg, @dbareis, @sallek0 (sorry for not tagging everyone), I can create a Discord server for this.

Currently I am active on a few Discord Servers for GitHub projects such as [MudBlazor (scroll down to the bottom to view the discord link)](https://mudblazor.com/)

Another option that I can create is a 'Self-Hosted' [Discourse Server](https://github.com/discourse/)

* Self Hosted: Server Costs, approx $50 - $200 per month (probably around the $50 - $100 mark)
- [Server Requirements](https://github.com/discourse/discourse/blob/main/docs/INSTALL.md#hardware-requirements)
- [Server Pricing (Vultr)](https://www.vultr.com/pricing/#:~:text=%C2%A0/hr-,Regular%20Performance,-Powered%20by%20previous) - I recommend at least 4 CPU, more is better

* Discourse Hosted: [$100 - $300](https://www.discourse.org/pricing) per month depending on userbase size (We'll probably be in the $100 - $200 range).

Of course the Discourse hosted is 'better' to fix problems, such as if the Self-Hosted server goes offline, a volunteer needs to fix that... and the community will be 'offline' during down-time. But its more expensive

**Comment by jeffward01** [comment]
> On the other hand, i think BiglyBT may be eligible to have free hosting from discourse itself as per here: https://blog.discourse.org/2018/11/free-hosting-for-open-source-v2/. This means no headache, no need for administration, free and automatic updates and support by those who make Discourse!

If BiglyBT qualifies for free 'Discourse Hosted' Forums, I vote for this.

For example, I have some questions such as this question that I just opened an issue for #2532 
- I have searched the Wiki and various websites and do not have an answer to my question
- I want to ask more knowledgeable community members a question, my current options are either asking on Reddit, or opening an issue on GitHub as I have done

**Comment by butter100** [comment]
Hey, I noticed r/BiglyBT on Reddit was inactive so I requested Reddit admins give it to me and eventually got it. 
Reddit is a hosted platform with many built in tools for moderation and automation so it works well out of the box and has easy optimization. Many open source project use it for community interaction too. 
If contributors or anyone want to help make it the project's forum please feel free to PM me on Reddit. If you're a contributor I can make you head of the subreddit (and remove my account) so you have full control.

**Comment by parg** [comment]
Thanks for grabbing it! I have answered some posts on r/BiglyBT and r/torrents when prodded but don't have a huge amount of time to devote to support. My worry would be that if we pushed users to r/BiglyBT and then couldn't put enough time into answering stuff it'd become less than useful. It would need a community of BiglyBT users willing to pitch in and help out and I'm not sure we have that.

**Comment by jeffward01** [comment]
Honestly this is the best Torrent Client out there for the active user. Yes, some things on it are rather Opiniated "this is the way we do things"  but at least you can do the things.

this is a much better built client than QBT, Deluge, and the others. Only thing I wish was that it was in C# 🙃

**Comment by parg** [comment]
Not sure C# was a popular programming choice in 2003!

**Comment by parg** [comment]
@butter100 I'll link to the reddit from a few places, see if we can drive some traffic there and see how it goes
