### ISSUE TITLE
Torrent Location not updating if torrent moved

### ISSUE THREAD

**Issue by attritionorg** [BiglySoftware/BiglyBT#1840]
Environment:
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4930r7, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.5.0.0/4 az2

For several versions of BiglyBT and as long as I can remember for that other software, the 'Torrent Location' in the UI does not update properly in my opinion. Steps to reproduce:

1. download torrent, save to e.g. c:\tmp\myarchive.torrent
2. complete download
3. use Control -> Tracker/Torrent -> Move Torrent File to move the .torrent to e.g. d:\newdir\myarchive.torrent

At this point, the UI will still show the file location in the c:\tmp directory rather than the new location. Even stopping/starting or upgrading BiglyBT will not trigger it to display the new torrent location, despite it clearly knowing where it is.

Thanks!

**Comment by parg** [comment]
Hmm, works for me (tm). Are you sure the torrent file is actually getting moved? Make sure that it actually exists where you think it is (C:\tmp\myarchive.torrent) before attempting the move - for me if the .torrent file doesn't actually exist you don't get an error when you attempt to move it but obviously it doesn't actually get moved.

**Comment by attritionorg** [comment]
@parg  I have a dozen+ .torrent files in f:\  (root dir), that I want to update to move to f:\torrent-files. So I know they exist, they are all actively seeded torrents. Two of the torrents that I tried to move the .torrent file from within BTT worked, but now the rest of them are failing to move. For the ones that do move, it isn't updating the 'Torrent Location' column and never has for me. This is the 2nd or 3rd time I have moved them and each one shows the original location the torrent file was written to.

**Comment by parg** [comment]
Check out the debug_1.log and debug_2.log files in the logs directory under %APPDATA%\BiglyBT - see if there are any clues there

**Comment by parg** [comment]
Also, FYI, when a download is in BiglyBT the original torrent file isn't used to run the download, rather a copy is made in the 'active' directory. So just because a download is actively seeding it doesn't mean the .torrent file exists in the indicated location.

**Comment by attritionorg** [comment]
@parg "Torrent Location" is where the torrent the .torrent file lives based on what I see, e.g. "D:\torrent\myfiles.torrent". But, that is not updating. So ~ 80% of my torrents show they live on D:\ despite being moved to F:\ months ago. Since then I have re-started BiglyBT a dozen times and it still shows the old location. It seems like that value is being registered upon creation of the torrent location but not updated subsequently.

I downloaded a new file today, it shows E:\torrent\newfiles.torrent in the location (correct). Moving the torrent file works for this, which is a small file (hundreds of megs) and downloaded today. But my 25 gig+ torrents hosted for years are the ones not reliably moving. I've gotten a few to move but most are not.

Following your log advice:
[15:39:05] [stderr] DEBUG::Fri Oct 30 15:39:05 MDT 2020::com.biglybt.core.download.impl.DownloadManagerImpl::setTorrentFile::5423:
[15:39:05] [stderr]   torrent file doesn't exist!
[15:39:05] [stderr]     DownloadManagerImpl::moveTorrentFile0::5414, DownloadManagerImpl::moveTorrentFile::5397, DownloadManagerImpl::moveTorrentFile::5384, TorrentUtil::moveTorrentFile::2641, TorrentUtil$60::run::2443, ListenerDMTask::go::89, ListenerDMTask::handleEvent::75, EventTable::sendEvent::89, Display::sendEvent::4175, Widget::sendEvent::1057, Display::runDeferredEvents::3988, Display::readAndDispatch::3587, SWTThread::<init>::400, SWTThread::createInstance::58, Initializer::<init>::180, UI::takeMainThread::136, Main::main::239, NativeMethodAccessorImpl::invoke0::-2, NativeMethodAccessorImpl::invoke::-1, DelegatingMethodAccessorImpl::invoke::-1, Method::invoke::-1, Launcher$1::run::48, Thread::run::-1

So this supports your comment about the original torrent file not being used to run the download but three issues:
1. The torrent lives in F:\ (root dir) where I moved it months ago (and can't move it from again)
2. There are no other torrent files with that name on the old or new drive
3. Regardless of where it actually lives, the BTT interface shows the .torrent lives in D:\torrent\ and that directory doesn't exist.

When you say "in the 'active' directory", what directory would that be exactly? Would it be a directory unrelated to the torrent files? I don't see one in %APPDATE% for example.

Thanks for your help on this!

**Comment by parg** [comment]
The active folder is %APPDATA%\BiglyBT\active

On my Windows machine this resolves to

C:\Users\Paul\AppData\Roaming\BiglyBT\active

The torrent files in there are named after the torrent hash. So my download 'LibreOffice_6.4.4_Win_x64.msi', with hash 1A9D12C430F199E05AC0484515EFDD266B84BF98, has its active torrent file copy in

C:\Users\Paul\AppData\Roaming\BiglyBT\active\1A9D12C430F199E05AC0484515EFDD266B84BF98.dat

Not sure how your save locations ended up incorrect as obviously it is supposed to update the remembered save location when the torrent is moved. There is a 'Switch torrent' option on the right-click menu that can be used to fix things up again but obviously a pain if you had a lot to do.

I suppose I could write a plugin to try and fix things up - if you're interested then you'd need to explain how you would want it to work

**Comment by parg** [comment]
Tell you what, if you attempt to move a torrent and it is found to be missing I'll change it to export the internal copy of the torrent instead

**Comment by attritionorg** [comment]
My active dir is then:
C:\Users\attri\AppData\Roaming\BiglyBT\active

It has a significant number of .dat and .bak so this is good to know! In that case, and maybe I was overthinking this along with not understanding that the active .torrent file is stored there... but can I just delete all the .torrent files in F:\ then?

And if so, then I guess the recommendation I would make is "Torrent Location" in the UI be updated to reflect either the 'Original Torrent Location' (i.e. where it was saved when downloaded) which doesn't seem that helpful to me, or have it show the active directory torrent.

Finally, I am curious why when I moved the torrent for two into F:\torrent-files\ it worked and it moved those files even if they were not the active ones?
