### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by Omni-Comp** [BiglySoftware/BiglyBT#1841]
Hi, Please magically add a dark mode to gui thanks

**Comment by parg** [comment]
It has it on OSX however other platforms don't have native support in the graphics library we use.

**Comment by Omni-Comp** [comment]
Haven’t coded in decades but cant you just change the background and text colors? Not sure why its hard…

 

Mark

**Comment by parg** [comment]
Sure, give it a go - https://github.com/BiglySoftware/BiglyBT

It's just Java, can't be that hard...

**Comment by Omni-Comp** [comment]
Haha, lmao NOOOOO – I like my pc – I don’t want to destroy it via coders rage 😉

**Comment by parg** [comment]
You can change a few things via Options->Interface->Colour Scheme

**Comment by Omni-Comp** [comment]
Sidebar works with black background – perhaps tweak the settings for full backround – dunno – don’t code anymore .

 

But logically – if white can be programmed any other color should be selectable by coders…

**Comment by parg** [comment]
Shoulda coulda woulda. The GUI library (SWT) is based on native widgets - the colours of these default to whatever the GUI library deems appropriate. On OSX the SWT devs have natively supported dark mode and the widgets change appropriately with no work from us. On Windows and Linux not.

**Comment by Omni-Comp** [comment]
Hows about starting the app from scratch again then – nice weekend project 😉

**Comment by parg** [comment]
How about No?

**Comment by parg** [comment]
Might be possible to hack something with the table views - that would cover most of the basic UI

**Comment by parg** [comment]
If you join the beta program (Help menu option) and update to B20 there's an option under Interface->Color Scheme to set the table views to use a dark scheme. So if you set

1) dark tables ->selected
2) sidebar background -> black
3) library header -> black

this gives a fairly dark scheme.

I'll probably look into making the tab headers in the sub-view go along with the 'library header' colouring as well.

Making everything dark is a big job but I'm happy to fiddle with major things.

**Comment by Omni-Comp** [comment]
Shall try today thanks

 

Mark

**Comment by parg** [comment]
The SWT team are working on (or at least thinking about) native Windows dark theme support:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=568112

However it looks like it'll be a while until something is available...

**Comment by Omni-Comp** [comment]
It’s the only way to go nowadays… Windows went full dark mode I think 2 updates back… Office has a dark theme but backgrounds still white tho… Cant wait for yours, not that I have it focussed much, but would be keeping up with the times…

 

Not sure if you guys use nicehash miner – their transform to dark mode totally remade the gui , looks much better…

 

Another suggestion, for a minimal display mode (basic info on active downloads and total throughput) that can be kept open in windowed mode (I have an ultrawide screen, hence loads of room to have open windows to monitor, but not doable if backgrounds are white… 😉 

 

 

Thanks

**Comment by parg** [comment]
There's an option to show transfer stats in the title bar (and hence task bar entry)

Options->Interface: Show current rates in title bar

Also there's

Tools menu -> Transfer Bar

Not dark though

**Comment by parg** [comment]
Or you can 'pop-out' the Library as a separate view (right-click on the Library sidebar entry to find the option)

**Comment by parg** [comment]
I'm not wasting more time looking at tabs, too much of a mess to work around. I have made the 'transfers bar' dark if you have a dark theme selected in the next beta (not built yet)

**Comment by Omni-Comp** [comment]
Hi, no, never a “waste” of time seeing that it is your product 😉.

 

Appreciate the assist, but dark mode needs priority at next major release… I don’t use other competitors products so not aware if they have that feature yet.

 

Enjoy

Mark

**Comment by Omni-Comp** [comment]
Much much better , thanks for the effort.

 

I do have progress and pieces pn downloading which still white, guess I can get used to that…

 

Regards

Mark
