### ISSUE TITLE
TCP connection is using ipv6 instead of ipv4

### ISSUE THREAD

**Issue by AzaleeBleue** [BiglySoftware/BiglyBT#1842]
* Windows 10 Pro 20H2 19042.608
* BiglyBT Version Number : B2.5.0.1_B19/4 az3
* Java version : Oracle JRE Java 1.8.0_202 (64 bit)

Help-About-> System : 
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre
SWT v4930r7, win32, zoom=200, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B2.5.0.1_B19/4 az3

I'm behind a VPN providing NAT on IPv4 and IPv6.
I have an opened incoming port.
This is my configuration :
![BiglyBT_Fk4VUM7jsO](https://user-images.githubusercontent.com/73590822/97432909-fe3b2600-191c-11eb-8c69-2fc5ec990a25.png)
![BiglyBT_LLYt3P6RkM](https://user-images.githubusercontent.com/73590822/97432946-08f5bb00-191d-11eb-8ac5-f5f6c65e8d9f.png)
![BiglyBT_cp56Tac9NM](https://user-images.githubusercontent.com/73590822/97432963-0dba6f00-191d-11eb-92b3-bb350409b747.png)
And the VPN Helper screen : 
![BiglyBT_lzvJ6tQ4ck](https://user-images.githubusercontent.com/73590822/97435879-5ffd8f00-1921-11eb-9241-7eea893b722c.png)

When I'm using the NAT / Firewall test tool : 
UDP results : 
Testing port UDP **XXXX** ... 
    Sending outbound packet and waiting for reply probe (timeout=5000)
    Sending completion event
OK ! (**VPN OUTSIDE IPv4 ADDRESS**)

Testing port UDP **XXXX** IPv6 ... 
    Sending outbound packet and waiting for reply probe (timeout=5000)
    Sending completion event
OK ! (**VPN OUTSIDE IPv6 ADDRESS**)

TCP results : 
Testing port TCP **XXXX** ... 
OK ! (**VPN OUTSIDE IPv6 ADDRESS**)

Testing port TCP **XXXX** IPv6 ... 
OK ! (**VPN OUTSIDE IPv6 ADDRESS**)

The updater is not working, I think because it's trying to connect to an HTTP over TCP IPv4 website while using the IPv6 address.

If I bind to the interface net1[0] (the VPN internal IPv4 address) instead of net1 in the Advanced Network Settings, when I use the NAT / Firewall test tool. For UDP it's using the IPv4 for the IPv4 and failling for the IPv6 part. For TCP, it's using and working the IPv4 even for the IPv6 test.

The updater is still failling : Read time out.

**Comment by bonze82** [comment]
I can confirm I have the same exact problem with ipvanish. Seems to be a vpn issue I use ipv4. I can also confirm updating while connected to the vpn does not work on debian using apt.
DEBUG::Mon Jul 04 21:10:44 CDT 2022  VersionCheckClient - java.net.SocketTimeoutException: Read timed out

debian 11.3 kernel 5.10.0-14
biglybt 3.0.0.0
openjdk 11.0.15
swt 4942r22
