### ISSUE TITLE
Error: disk read error: read - file is closed

### ISSUE THREAD

**Issue by TSellers2** [BiglySoftware/BiglyBT#1843]
Refers to a folder with 4 media files. Path is valid. All exist and play. I'm not sure what this means, or what action to take to rectify.

Regards, John

* Windows 7
* 2.3.0

**Comment by parg** [comment]
Me neither but you could update to 2.5 first

**Comment by TSellers2** [comment]
OK, will do, thanks.

**Comment by TSellers2** [comment]
Did the update. Only found the error once again, and it referred to a directory that no longer existed. Thanks for the suggestion.
