### ISSUE TITLE
Mullvad VPN and VPN Helper: cannot connect to Mullvad's site?

### ISSUE THREAD

**Issue by phourniner** [BiglySoftware/BiglyBT#1846]
I'm having an issue with using Mullvad and VPN Helper.
![Screenshot 2020-10-28 184342](https://user-images.githubusercontent.com/73620435/97509954-a4088800-1951-11eb-97e9-48d0e2b410df.png)

For some reason, it has warnings, apologies as I am unsure of how I would go about fixing this problem. Fresh install of Mullvad.

* OS and version: Windows 10 version 20H2
* BiglyBT Version Number: B2.5.0.0/4 az3
* For *nix: Desktop Environment

**Comment by AzaleeBleue** [comment]
May be the same problem as #1842 ?

**Comment by phourniner** [comment]
Dunno. It was working perfectly fine using Private Internet Access VPN before I switched. Not sure if it's on Mullvad's side either, figured I'd stop here first.

**Comment by TuxPaper** [comment]
I have a fix in the works.  They stopped using master.mullvad.net.

**Comment by phourniner** [comment]
> I have a fix in the works. They stopped using master.mullvad.net.

Oh, perfect! Thank you so much!

**Comment by TuxPaper** [comment]
Should be a new plugin (5.11) out.  Let me know if it works! :)

**Comment by phourniner** [comment]
> Should be a new plugin (5.11) out. Let me know if it works! :)

Yes, that fixed it! :D

**Comment by phourniner** [comment]
I'll go ahead and close this issue now, thank you.
