### ISSUE TITLE
Peers tab not showing country code or flag

### ISSUE THREAD

**Issue by thegreatestminer** [BiglySoftware/BiglyBT#1847]
Java 1.8.0_261 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_261

SWT v4930r7, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.5.0.0/4 az3

---
Loaded plugins: azupdater,azupdaterpatcher,xmwebui,azbpcorepatcher,azbpcoreupdater,azbpdht,azbpdhdtracker,azbpremovalrules,azextseed,azlocaltracker,azintrss,azlocprov,azbpmagnet,mldht,aznetstat,azplatform2,azbppluginupdate,azbpsharehoster,azbpstartstoprules,azbpupnp,azutp

![image](https://user-images.githubusercontent.com/19188146/97703980-ef24b700-1a87-11eb-86ec-f029a129d58f.png)

**Comment by parg** [comment]
Flags are provided by the azlocprov plugin - go to Options->Plugins and ensure that it is operational

**Comment by thegreatestminer** [comment]
@parg How do I tell? 
![image](https://user-images.githubusercontent.com/19188146/97708374-17fc7a80-1a8f-11eb-930d-ed5732707510.png)

I searched the log and this is the only thing that's mentioned about the plugin.

    Location Provider
        id:azlocprov,version:0.4.8
        type:per-user,enabled=true,load_at_start=true,operational=true

**Comment by parg** [comment]
Hmm, something is borked - I'll look into it, thanks!

**Comment by parg** [comment]
I've built a 0.4.9 - should update on restart or possibly if you do an explicit check-for-updates, thanks!

**Comment by thegreatestminer** [comment]
Works perfectly! Thank you!
![image](https://user-images.githubusercontent.com/19188146/97731241-438d5e00-1aab-11eb-9bc8-08ec71eb4b7d.png)
