### ISSUE TITLE
Add an option purely for disabling sliding animation for alert notifications

### ISSUE THREAD

**Issue by asdsadsaasd12312132** [BiglySoftware/BiglyBT#1848]
I enabled the "Disable sliding animation/on-top style" setting but this setting also moved the alert to the centre of my screen and and never auto closes. I want a setting that only disables the animation of the notification sliding to the right. The notification should just disappear after the auto close timer.

**Comment by parg** [comment]
Didn't your mother ever tell you "I want doesn't get" ?
