### ISSUE TITLE
New items not updating in sidebar

### ISSUE THREAD

**Issue by kwloafman** [BiglySoftware/BiglyBT#185]
You fixed the tabs to update, but for some reason the New items does not update as well.  I have to select it, then it updates to show how many new items have completed.

...Thanks,
...Ken

Java 1.8.0_151 (64 bit)
  Oracle Corporation
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home

SWT v4528, cocoa
Mac OS X v10.13.1, x86_64 (64 bit)
B1.2.0.1_B21/4 az3

**Comment by parg** [comment]
Thanks, be fixed in next beta
