### ISSUE TITLE
Unable to add unfinished/removed torrent

### ISSUE THREAD

**Issue by kwalker99** [BiglySoftware/BiglyBT#1850]
Hi Guys

I am trying to re add 100 torrents that were either not downloading/unfinished etc and removed from the queue. When adding, BiglyBT pops an error/message saying they were previously downloaded, which is not true, they were queued, but never completed and it refuses to allow me to re add them.

I have tried removing the torrent files in /home/$user/.biglybt/torrents/ and also removed the download history in the view menu, neither has resolved this problem.

* OS and version - Ubuntu Linux 18.04
* BiglyBT Version Number - 2.5.0.0
* For *nix: Desktop Environment - GNOME Shell 3.28.4

How do i remove this hidden download history and why is this even a feature? Users should be able to re-download whatever they want... This is likely something inherited from Vuze.

Kind regards

Kevin

**Comment by parg** [comment]
Did you figure it out? The 'previously downloaded' message is informative so if downloaded refuse to add that would be a different issue. 

Download history can be disabled by deselecting

Tools->Options->Files: Record download history
