### ISSUE TITLE
Using only I2P metadata will not download on clearnet magnet files, feature request/bug depending on how you look at it

### ISSUE THREAD

**Issue by SamtheTruck** [BiglySoftware/BiglyBT#1851]
Windows 7 v6.1, amd64 (64 bit)
Java 1.8.0_162 (64 bit)
B2.5.0.0/4 az3
I'm using I2P v.0.9.47 to run the I2P for BigglyBT, not BT internal

Using only I2P metadata will not download on clearnet magnet files log says
error:no sources found for torrent

Yes I get that since no I2P based tracker has the file then it will not be able to get the metadata and will eventually after trying give you an error. What I'm asking for is that it will save the magnet file and wait until possibly someone picks up the file in I2P

The action in I2Psnark is if you add a magnet file from a clearnet torrent it will add it to the que and keep searching the DHT until such time it shows up then move it to active and download. 

I'm going to explain simply the actions so there's no confusion(yes this is boring). No clearnet. Only I2P helper active. 

Go to a magnet file page on web. Right click open in new tab. Win7 requester comes up asking if you want to use (BT), you say yes and BT opens. BT opens a requester that says it's trying to download metadata. "IF" this is really popular and someone is downloading on I2P then it will download the metadata and then start the torrent. The problem is if it is not presently being downloaded on the I2P network. Then the requester is in the way and it eventually times out.

Another problem is if you copy the magnet with "copy link location" in Win 7 and then try to copy the magnet file into the "open torrents" > "file" requestor it will not accept it as a url. It will accept "copy from clipboard" but then we are back to it timing out.

What I would like.

Copy a url magnet link location from clearnet web page, click "open torrents" then add the magnet url in the open files requester box, (hit "open file" then paste in the magnet url) without it saying "error". Just accept it. Then have it que it up, whether it starts downloading metadata immediately or not. It should just check every so often if the file is in the DHT in I2P but not time out.

This is the only problem I see with using BigglyBT only. I use I2PSnark because you can que up obscure magnet files and frequently they eventually start themselves. Sometimes it takes months but...they do finish many times. The idea is that BigglyBT shouldn't demand that all files should be active immediately or it errors. That's sort of a bug but I guess could be classed as a feature.

I would add magnet files that directly show the action but...you can't do that here.

Thanks for the great work you guys are doing.

**Comment by SamtheTruck** [comment]
A idea popped up after I wrote this. Is it possible to get the metadata, and only the metadata, with Tor???

**Comment by parg** [comment]
Under Options->Plugins->Magnet URI Handler there are settings to control how long a magnet download will remain in BiglyBT before timing out. If you set 'overall lookup timeout' to 0 (infinite) and ensure you have 'recover magnet downloads across restarts' enabled then they should sit there forever attempting to download the metadata.

**Comment by SamtheTruck** [comment]
Thanks. My apologies for being picky but it still leaves the requester box open. I2PSnark's way of just accepting it does seem better.

Thanks for the help.

**Comment by parg** [comment]
you can just close that dialog, things will continue

**Comment by SamtheTruck** [comment]
Damn. Parg you have all the answers! THANKS! Much appreciation.

**Comment by parg** [comment]
No problem :)
