### ISSUE TITLE
Funky New Transfer Bar

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#1854]
Just updated to Beta 21 and the transfer bar is looking rather funky.

![image](https://user-images.githubusercontent.com/37715552/97852943-6dba6800-1cc5-11eb-9668-34e7e6772311.png)

Black background. Only change was installing B21.

Java 1.8.0_271 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_271

SWT v4930r7, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.5.0.1_B21/4 az3

**Comment by parg** [comment]
Dark theme isn't it

**Comment by NaPurHab** [comment]
Yes Windows is in Dark Theme, but the Transfer Bar had a light grey background in B20 and before.  I changed nothing in BBT, other that installing B21.  Just took a look you added a Dark Tables option. It looks like this.
![image](https://user-images.githubusercontent.com/37715552/97907142-d2e87a80-1d12-11eb-8f91-28045160bc6e.png)
The Dark likes are unreadable, while in the Transfer Bar all text is unreadable. Dark mode is more than just changing the background.

**Comment by parg** [comment]
Dark tables are a hack to work with the default colour scheme, if you've changed that already then whatever.

The transfer bar was explicitly black text on white background (generally), I changed it to do something more sensible if you selected 'application dark theme' in Windows, but obviously if you've messed with colours already then your mileage will vary.
