### ISSUE TITLE
Improve performance of mass adding of large torrents

### ISSUE THREAD

**Issue by Qwest8K** [BiglySoftware/BiglyBT#1857]
Typical situation: I have ~10,000 torrent-files (ranging with size from a couple of kilobytes to half a dozen megabytes) that I want to add to BiglyBT in one piece - by selecting them and dragging them into the program window.

But when I try to do this, BiglyBT stops responding, takes away all free CPU time and load CPU up to 100% and loads the system HDD as much as possible. And if the load on the system HDD passes over time, then 100% CPU load and the lack of a response from program just never end and it must be closed through the task manager.

It's possible to use crutch method by adding torrent-files in parts. But even in this case, BiglyBT may forever freeze with 100% CPU load (this happens if in one part there are too many torrent-files with a large number of files). However, adding by parts allows program to wake up and free CPU time, but nevertheless it is practically impossible to use PC while adding torrent-files, since system HDD and the CPU are loaded to the maximum (and lowering the priority of the process does not help much).

Actually the conclusion - is it possible to make adding a large number of torrent-files is not so painful?

**Comment by parg** [comment]
Not really, sorry but your use-case of adding 10,000 torrents in one case is not something I am going to spend days trying to optimize...

Write some script to gradually copy the files into a folder that is configured as a 'torrent watch folder' ?
