### ISSUE TITLE
uTorrent (v2.2.1) Still Faster With Magentic Links

### ISSUE THREAD

**Issue by DeathStalker77** [BiglySoftware/BiglyBT#186]
Tried the same link with BiglyBT and it just sat on the metadata - uT grabbed it fast and started downloading almost immediately.

**Comment by parg** [comment]
Do you have the mlDHT plugin installed?

**Comment by DeathStalker77** [comment]
I did not - it was not clear that it was needed.  I will try again and update.

**Comment by eurobank** [comment]
@parg do we need to install and enable mIDHT ?

**Comment by parg** [comment]
it helps to do so

**Comment by davisjackie321** [comment]
Very
