### ISSUE TITLE
Torrent displayed name no longer changes to match subfolder (if user changes it in the open torrent options dialog)

### ISSUE THREAD

**Issue by david-bakin** [BiglySoftware/BiglyBT#1865]
[BiglyBT Beta (2.5.0.1_B26); Windows 2016 Datacenter]

When you add a torrent and change the `subfolder` in the `open torrent options` dialog the _displayed name_ of the torrent changed to match (*).  This no longer happens.  Noticed it in B26 but it could have happened earlier, maybe B25.

(*) This itself was a recent _desirable_ change in the last couple of months.  It may have been inadvertent because it wasn't mentioned in any changelist (the stuff that gets displayed in the `beta program` page).  But I liked it quite a lot as it made things very convenient!  Please bring it back!

**Comment by parg** [comment]
If you right-click in the Files area of the open-torrent-options dialog there is a menu 'check' option called 'rename torrent on top level folder change'. Is this still checked? (it is by default)

**Comment by david-bakin** [comment]
Nope.  Must have clicked on it by accident.  Thanks!
