### ISSUE TITLE
Web UI Plugin isFinished false for completed torrents

### ISSUE THREAD

**Issue by elisionducoeur** [BiglySoftware/BiglyBT#1867]
* OS and version Ubuntu 18.04
* BiglyBT Version Number 2.5
* For *nix: Desktop Environment

xmwebui plugin
isFinished doesn't return true for completed torrents

**Comment by TuxPaper** [comment]
I fall into this trap every year or so!
isFinished is very annoying because it's not for completion at all according to the transmission javadocs :( 

https://github.com/transmission/transmission/blob/master/libtransmission/transmission.h#L1855

```
    /** A torrent is considered finished if it has met its seed ratio.
        As a result, only paused torrents can be finished. */
    bool finished;
```

Since BiglyBT doesn't have a required seed ratio to meet, isFinished is always false.

Personally, I use `percentDone == 1.0` for completion logic, although `leftUntilDone == 0` would probably also work.

**Comment by elisionducoeur** [comment]
Oh wow confusing. The problem is that radarr is the one doing the API calls and is expecting isFinished to be true. Any chance you know if/how someone got it working with radarr?

**Comment by TuxPaper** [comment]
hmm, well that's interesting.  raddar marks something as complete in two cases.  One using the isFinished (which always fails for BiglyBT), and one based on Status of Seeding or SeedingWait.

https://github.com/Radarr/Radarr/blob/master/src/NzbDrone.Core/Download/Clients/Transmission/TransmissionBase.cs#L90

```
                else if (torrent.Status == TransmissionTorrentStatus.Seeding ||
                         torrent.Status == TransmissionTorrentStatus.SeedingWait)
                {
                    item.Status = DownloadItemStatus.Completed;
                }
                else if (torrent.IsFinished && torrent.Status != TransmissionTorrentStatus.Check &&
                         torrent.Status != TransmissionTorrentStatus.CheckWait)
                {
                    item.Status = DownloadItemStatus.Completed;
                }
```

For the torrents you see as not complete, but actually are, what status is shown for them? If Radarr shows torrent status, that information would be helpful too.

**Comment by TuxPaper** [comment]
oh, there's an if statement just before that code chunk in Radarr that would set a torrent to a warning state if BiglyBT send an error string for the torrent.  Not sure if that matters in your case.

**Comment by elisionducoeur** [comment]
Yep was also looking at that file. json response wise everything looks like
it should work out. radarr folks are saying it's a vuze/biglybt problem
though, and since none of them use it they can't fix the issue. Also,
agreed on the error string, it's being passed as an empty string in the
json response. Radarr doesn't seem to even detect the torrent after it
sends it, I never get a warning, error, attempt to import, etc.

**Comment by TuxPaper** [comment]
I can't think of any negative side affects of making isFinished == isComplete, so I may change it.  I'll spend some time pondering whether I should put a config setting to turn on the logic, or just go full commando.

**Comment by elisionducoeur** [comment]
Ah also this is the line in radarr that doesn't seem to be triggering even
though the response fits the conditions (different branch than what you
posted earlier, more commonly used)
https://github.com/Radarr/Radarr/blob/develop/src/NzbDrone.Core/Download/Clients/Transmission/TransmissionBase.cs#L93
ᐧ

**Comment by TuxPaper** [comment]
> Ah also this is the line in radarr that doesn't seem to be triggering even though the response fits the conditions (different branch than what you posted earlier, more commonly used) https://github.com/Radarr/Radarr/blob/develop/src/NzbDrone.Core/Download/Clients/Transmission/TransmissionBase.cs#L93 ᐧ

If you have a json response for a torrent that you think should be completed, can you check what the leftUntilDone is (should be 0), and what the status value is (should be 0, 5 or 6).  In the latest xmwebui plugin, we also send a "status.biglybt" key.  If you have that one as well, it could be helpful for figuring this out (values of status.biglybt are same as STATE_XXX in [DownloadManager.java](https://github.com/BiglySoftware/BiglyBT/blob/master/core/src/com/biglybt/core/download/DownloadManager.java#L52))

**Comment by elisionducoeur** [comment]
Yep, leftUntilDone is 0 and status is 6. The radarr query doesn't include
status.biglybt but if I do it through the browser status.biglybt is 60,
which matches.
ᐧ

**Comment by TuxPaper** [comment]
@elisionducoeur 
Why did you close this issue?  Please tell me it was for good reasons :D 

Everything indicates that Radarr should be picking up the torrent and complete

**Comment by elisionducoeur** [comment]
Doesn't seem like an issue with biglybt since the isFinished is just following the transmission RPC
