### ISSUE TITLE
[Linux] Padding in the sidebar is too wide

### ISSUE THREAD

**Issue by txtsd** [BiglySoftware/BiglyBT#1868]
There is too much padding between the window border and the icon. I made a red arrow pointing to it.
Is there a way to reduce it?

Here's a screenshot:
![2020-11-18-131323_1920x1080_scrot](https://user-images.githubusercontent.com/768728/99501018-2e686880-29a1-11eb-8377-a433889edf7b.png)

* OS: Arch Linux
* BiglyBT Version Number: 2.5.0.0
* For *nix: Openbox, no DE
* System info:
```
Java 14.0.2 (64 bit)
  N/A
/usr/lib/jvm/java-14-openjdk

SWT v4934r5, gtk/3.24.23, zoom=100, dpi=96
Linux v5.9.6-1-ck-zen, amd64 (64 bit)
B2.5.0.0/4 az3
```

**Comment by parg** [comment]
Options->Interface->Display: Sidebar ?

**Comment by txtsd** [comment]
There is nothing there that adjusts horizontal padding.

**Comment by parg** [comment]
'indent expander controls'
'reduce width'

**Comment by txtsd** [comment]
It isn't there. And search for indent doesn't show any results.

![2020-11-18-151851_1144x1051_scrot](https://user-images.githubusercontent.com/768728/99514279-958e1900-29b1-11eb-917d-87e7b22203fd.png)

**Comment by parg** [comment]
Ah, sorry, no support for messing with sidebar widths on GTK as it is a native tree widget - those options are Windows/OSX only :(

**Comment by txtsd** [comment]
What are my options then? Am I stuck with the T H I C C padding?

**Comment by parg** [comment]
My Kubuntu looks pretty decent

![image](https://user-images.githubusercontent.com/395293/99521221-10443d80-298c-11eb-968f-0f1759fef416.png)

**Comment by TuxPaper** [comment]
Maybe there's an OS theme on Arch Linux with a tighter tree view?  I don't know how hard it is to edit existing themes, but maybe there's some resources online that tell you how to edit specific widgets -- I hear a lot of linux OSes these days use a form of CSS/HTML for their widget specs.

**Comment by txtsd** [comment]
> Maybe there's an OS theme on Arch Linux with a tighter tree view? I don't know how hard it is to edit existing themes, but maybe there's some resources online that tell you how to edit specific widgets -- I hear a lot of linux OSes these days use a form of CSS/HTML for their widget specs.

Tried a few different ones. It's the same.
Matcha:
![2020-11-19-102018_1142x1046_scrot](https://user-images.githubusercontent.com/768728/99623168-8363b780-2a51-11eb-84c1-8e4578a382c6.png)
Paper:
![2020-11-19-102204_1146x1048_scrot](https://user-images.githubusercontent.com/768728/99623171-85c61180-2a51-11eb-9d63-dff1e29ccf64.png)
Adwaita:
![2020-11-19-102328_1142x1044_scrot](https://user-images.githubusercontent.com/768728/99623175-878fd500-2a51-11eb-92ca-0b074c0ab2d9.png)
