### ISSUE TITLE
How to make torrent NOT auto start after being added? | Any option to disable "previously downloaded" popout?

### ISSUE THREAD

**Issue by waldens** [BiglySoftware/BiglyBT#1869]
* OS and version: Windows 7
* BiglyBT Version Number: BiglyBT 1.8.0.0

1. How to make the torrent NOT start downloading automatically once being new added? The option "When opening a torrent, show options dialog: [every time / etc...]" only gives the choice to select files user want to download, but the torrent still starts downloading as soon as added to the form, which is not being wanted here. Is there something similar to this option in uTorrent?
![](https://i.imgur.com/ByyNzSJ.png)

2. Any option to disable this popout of "previously downloaded" reminder?
![](https://i.imgur.com/O6aRFob.png)

**Comment by david-bakin** [comment]
The answer (I think) to your first question is in Options/Files/Torrents: "By default add new torrents in a stopped state".

(BTW, at the bottom of the options page is a search control - searches the options pages!  Terrific feature.  I knew this checkbox existed but didn't know where so I typed "stop" into the search and it highlighted (bold) the pages with the word "stop".)

**Comment by waldens** [comment]
@david-bakin Yes! This search feature makes it easier to find options. I did search for relevant keywords before asking (and googled), but for some reason missed this option, and just used, this's exactly what needed here, Thanks for such quick help! :_happy:
