### ISSUE TITLE
Default Theme

### ISSUE THREAD

**Issue by emkei-cz** [BiglySoftware/BiglyBT#187]
USE:
- LM 18.3 Mate 64bit
- BiglyBT 1_2_0_0

Hi,
Is there a possibility to set default theme?

I use taken over theme, and that's bad...
https://ctrlv.cz/shots/2017/12/09/HgCd.png
https://ctrlv.cz/shots/2017/12/09/VU2Z.png

**Comment by emkei-cz** [comment]
@parg

Can you help me ?

**Comment by parg** [comment]
Unfortunately not, otherwise I would have chipped in :(

**Comment by kevlarsefirot** [comment]
I have the same problem I recommend:
- Vuze
- qBittorrent
- Transmission
