### ISSUE TITLE
Automatically generate and seed V2 torrents when V1 are downloaded

### ISSUE THREAD

**Issue by TheBestPessimist** [BiglySoftware/BiglyBT#1872]
We have 2 torrent versions now, V1 and V2, but most torrents are and will probably be created in V1 for the foreseeable future.

Totally wild idea:
I was wondering if it makes sense for BBT to automatically create V2 torrents (not hybrid as we dont want any padding) for the V1 torrents that i have downloaded. This might help with swarm merging, as someone downloading a (different) V1 torrent containing the same files might use the V2 torrent for swarm merging, find the files that i have and download from me. (i have a totally different torrent, but we have common files).

This can be seen like automatic V2 creation/publishing.

Note 1: I'm not sure if what i proposed here is useful IRL, but it's just an idea i had.

Note 2: i'm not sure if, in order to create a V2 torrent we must have the torrent fully downloaded, or if we can create the torrent only from the V1 torrent. In any case, this might not matter: if at some point in the future someone will start downloading a V2 torrent which contains part of my files, the swarm merge will still be possible, so this can be seen as a free win.

**Comment by parg** [comment]
You'd have to have fully downloaded the v1 torrent in order to create the v2 torrent as it needs to re-hash the downloaded data to build the v1 hash trees and therefore the root hashes. 

It would be possible to do that automatically on v1 download completion although you probably wouldn't want the overhead of actually running a (decentralized) v2 swarm for every download you have just on the offchance that someone else would have created a hybrid/v2 torrent of exactly the same files.

Currently swarm-merging works based on file-size, I haven't got around to extending it to work on v2 root hashes as there appear to be very few non-v1 torrents out there so far. File-sized base merging will work across v1 and v2 swarms (obviously not as accurately as using root hashes would be).

If you think it useful I could add a manual mechanism for generating a hybrid/v2 torrent from a completed non-private v1 torrent but I'm not convinced...

**Comment by TheBestPessimist** [comment]
> s it needs to re-hash the downloaded data to build the v1 hash trees and therefore the root hashes.

do you mean V2 hash trees?


> although you probably wouldn't want the overhead of actually running a (decentralized) v2 swarm for every download you have

what's the difference between V1 and V2? isn't each V1 torrent a different swarm in itself? why does V2 have a bigger overheard? (i might be missing something obvious here, sorry if that's the case)

> If you think it useful I could add [...]

I'm not sure how useful it is now. This is why i'm asking for your and BBT's users opinion. I'm just thinking for the future.

**Comment by parg** [comment]
oops, yes, v2 hash trees.

By overhead I mean your client will need to run double the number of swarms, not that a v2 swarm has more overhead than a v1 swarm. Each swarm takes resources - DHT registration and lookup costs, memory for swarm state etc. If you only have 1 or 2 torrents loaded in your client then no biggie but if you have 100s or 1000s then effectively doubling this number could be quite significant.

As for the future, it might well be something to consider. If/when hybrid/v2 torrent use becomes significant it might be worth constructing the V2 torrent simply to extract and save the v2 root hashes for use in swarm merging (without even running a V2 swarm)

**Comment by TheBestPessimist** [comment]
> oops, yes, v2 hash trees.

Please update your previous comment with this fix, it helps future readers!


> By overhead I mean your client will need to run double the number of swarms
> [...]
> Each swarm takes resources
> if you have 100s or 1000s then effectively doubling this number could be quite significant

Frankly, I'm thinking that at the point i exceed 100 active torrents (i currently have 87), having double that active is totally acceptable. A JVM needs to have enough memory to do its thing properly w/o GC killing perf. I _believe_ the resources used during actual transfer are much bigger than the resources used for the swarm state, so I _believe_ this overhead is negligible.

I see you've already added this option: https://github.com/BiglySoftware/BiglyBT/commit/d611ccd774162212ab89e1b61db6a8116a5be83b , but i cannot see it in the menu/settings.



> As for the future
> [...]
> to extract and save the v2 root hashes for use in swarm merging (without even running a V2 swarm)

Something doesn't click again here: if we don't run a swarm, nobody will know we have this torrent right? So what's the usability of this?

**Comment by zero77** [comment]
Is v2 swarm merging not already possible with hybrid torrents.

**Comment by parg** [comment]
Yes, swarm merging works just fine with/across v1, hybrid and v2 torrents.

New options are currently hidden under right-click download context menu -> Tracker/Torrent:

    Create Hybrid Download
    Create V2 Download
