### ISSUE TITLE
Magnet links seem to be broken

### ISSUE THREAD

**Issue by christian-ruud** [BiglySoftware/BiglyBT#1873]
About 2/3 of all torrents I download fail when oping a magnet link. Either it says that no sources are found, or it finds a few and keeps timing out. Sometimes they will work after several retries and many hours. If I can get the metadata download to complete the download gets lots of peers and seeds and downloads quickly. I have tensof magnet links I've been trying to download for weeks without success. 

I finally downloaded the official bittorrent client from bittorrent.com. With this client the magnet links (the same links) work immediatly and there are no problems.

**Comment by parg** [comment]
Do you have the 'Mainline DHT plugin' (mlDHT) installed?

**Comment by christian-ruud** [comment]
Yes. I haven't changed any of its settings. If i mouse-over the mIDHT icon it says Initializing for both IP4 and 6

**Comment by parg** [comment]
If it is stuck 'initialising' then something is wrong. When it is running that changes to a 'Node Estimate' with DHT size(s) displayed.

Try going to 

    Tools->Plugins->Log Views->Mainline DHT Log

and see what that says

**Comment by christian-ruud** [comment]
It seems to be receiving invalid DNS addresses from somewhere...


[12:09:58] DNS lookupg for router.silotis.usfailed: router.silotis.us
[12:09:59] DNS lookupg for router.silotis.usfailed: DNS record not found
[12:10:00] DNS lookupg for router.silotis.usfailed: router.silotis.us
[12:10:01] DNS lookupg for router.silotis.usfailed: router.silotis.us
[12:10:03] DNS lookupg for router.silotis.usfailed: router.silotis.us
[12:10:04] DNS lookupg for router.silotis.usfailed: router.silotis.us
[12:10:05] DNS lookupg for router.silotis.usfailed: router.silotis.us
[12:10:06] DNS lookupg for router.silotis.usfailed: router.silotis.us
[19:03:50] updating set of valid bind addresses
 old: [/127.0.0.1, /192.168.1.79, /0.0.0.0]
 new: [/127.0.0.1, /0.0.0.0]
[19:04:00] updating set of valid bind addresses
 old: [/127.0.0.1, /0.0.0.0]
 new: [/127.0.0.1, /192.168.1.79, /0.0.0.0]
[19:04:20] DNS lookupg for dht.transmissionbt.comfailed: DNS error
[19:04:31] DNS lookupg for router.silotis.usfailed: DNS record not found
[19:04:32] DNS lookupg for dht.transmissionbt.comfailed: DNS record not found
[19:04:32] DNS lookupg for router.silotis.usfailed: router.silotis.us
[19:04:33] DNS lookupg for dht.transmissionbt.comfailed: dht.transmissionbt.com
[19:04:33] DNS lookupg for router.silotis.usfailed: router.silotis.us
[19:04:34] DNS lookupg for dht.transmissionbt.comfailed: dht.transmissionbt.com
[19:04:34] DNS lookupg for router.silotis.usfailed: router.silotis.us
[19:04:35] DNS lookupg for dht.transmissionbt.comfailed: dht.transmissionbt.com
[19:04:35] DNS lookupg for router.silotis.usfailed: router.silotis.us
[19:04:36] DNS lookupg for dht.transmissionbt.comfailed: dht.transmissionbt.com
[19:04:36] DNS lookupg for router.silotis.usfailed: router.silotis.us
[19:04:37] DNS lookupg for dht.transmissionbt.comfailed: dht.transmissionbt.com
[19:04:37] DNS lookupg for router.silotis.usfailed: router.silotis.us
[19:04:38] DNS lookupg for dht.transmissionbt.comfailed: dht.transmiss

**Comment by christian-ruud** [comment]
Checking further, I'm able to resolve dht.transmissionbt.com, but not router.silotis.us, when trying manually

**Comment by parg** [comment]
Must be something borked with your DNS setup for Java ( "DNS error" is an odd one...)

Is your setup in any way non-standard?

**Comment by christian-ruud** [comment]
I'm on a regular subnet network 192.168.1.0/24. Ports are forwarded to a static IP host, NAT checks work fine.
I enabled IPv6 on my host now (though I don't really have IPv6 on my network) and after dping so i can resolve manually - it resolves to an IPv6 address. I have two internal DNS servers that serve my local zone - otherwise they forward to 8.8.8.8

mIDHT still says initializing, but the log says: 

[19:17:19] updating set of valid bind addresses
 old: [/0:0:0:0:0:0:0:1, /0:0:0:0:0:0:0:0]
 new: [/0:0:0:0:0:0:0:1, /2a02:2121:c4:6d7e:1cb7:9631:55be:3, /2a02:2121:c4:6d7e:e108:2308:fddb:b53a, /fd1c:b796:3155:be00:e108:2308:fddb:b53a, /2a02:2121:c4:6d7e:216a:7933:9551:b6fe, /fd1c:b796:3155:be00:216a:7933:9551:b6fe, /fe80:0:0:0:e108:2308:fddb:b53a%eth4, /0:0:0:0:0:0:0:0]
[19:17:27] Starting RPC Server /2a02:2121:c4:6d7e:1cb7:9631:55be:3 700E940A5D197101A8C5661CAF521D7B47E548B4
[19:17:27] Starting RPC Server /2a02:2121:c4:6d7e:216a:7933:9551:b6fe F00E940A5D197101A8C5661CAF521D7B47E548B4
[19:17:27] Starting RPC Server /2a02:2121:c4:6d7e:e108:2308:fddb:b53a 300E940A5D197101A8C5661CAF521D7B47E548B4

I also checked whatismyipv6.com - and I have a public IPv4, no IPv6

**Comment by christian-ruud** [comment]
though my internet router does appear to have an external ipv6 address it does not have an internal one

**Comment by parg** [comment]
Well you have been allocated an IPv6 address...

inet6num: 2a02:2120::/30
netname: NO-TELENOR-20100706
country: NO

**Comment by christian-ruud** [comment]
Yeah - according to my internet router I do - but whatismyip6.com can't resolve it. I can resolve ipv6 dns after I enabled it on my host, but BiglyBT still says initializing.

Current log:
ew: [/0:0:0:0:0:0:0:1, /fe80:0:0:0:e108:2308:fddb:b53a%eth4, /0:0:0:0:0:0:0:0]
[22:01:50] bind address no longer valid, removing from active set: /2a02:2121:c4:6d7e:d408:503e:2f01:4069
[22:01:50] Stopped RPC Server /2a02:2121:c4:6d7e:d408:503e:2f01:4069 F00E940A5D197101A8C5661CAF521D7B47E548B4
[22:01:50] bind address no longer valid, removing from active set: /2a02:2121:c4:6d7e:1cb7:9631:55be:3
[22:01:50] Stopped RPC Server /2a02:2121:c4:6d7e:1cb7:9631:55be:3 700E940A5D197101A8C5661CAF521D7B47E548B4
[22:01:50] bind address no longer valid, removing from active set: /2a02:2121:c4:6d7e:e108:2308:fddb:b53a
[22:01:50] Stopped RPC Server /2a02:2121:c4:6d7e:e108:2308:fddb:b53a 300E940A5D197101A8C5661CAF521D7B47E548B4
[22:01:50] updating set of valid bind addresses
 old: [/0:0:0:0:0:0:0:1, /2a02:2121:c4:6d7e:1cb7:9631:55be:3, /2a02:2121:c4:6d7e:d408:503e:2f01:4069, /2a02:2121:c4:6d7e:e108:2308:fddb:b53a, /fd1c:b796:3155:be00:d408:503e:2f01:4069, /fd1c:b796:3155:be00:e108:2308:fddb:b53a, /fe80:0:0:0:e108:2308:fddb:b53a%eth4, /0:0:0:0:0:0:0:0]
 new: [/0:0:0:0:0:0:0:1, /fe80:0:0:0:e108:2308:fddb:b53a%eth4, /0:0:0:0:0:0:0:0]
[22:02:20] updating set of valid bind addresses
 old: [/0:0:0:0:0:0:0:1, /fe80:0:0:0:e108:2308:fddb:b53a%eth4, /0:0:0:0:0:0:0:0]
 new: [/0:0:0:0:0:0:0:1, /2a02:2121:c4:6d7e:1cb7:9631:55be:3, /fe80:0:0:0:e108:2308:fddb:b53a%eth4, /0:0:0:0:0:0:0:0]
[22:02:30] Starting RPC Server /2a02:2121:c4:6d7e:1cb7:9631:55be:3 700E940A5D197101A8C5661CAF521D7B47E548B4

**Comment by parg** [comment]
I'd forget the IPv6 side of things and try and figure out why DNS resolution is failing with an error for dht.transmissionbt.com.

The mainline DHT can also apparently bootstrap of torrent peers (there's an option to only use them in the settings). It isn't my plugin so not entirely sure of that.

From looking at the code it should also try and boostrap from

router.bittorrent.com 
router.utorrent.com

**Comment by parg** [comment]
Perhaps you could go to the Help menu and select Advanced->Show Configuration Changes... and, after reviewing for any private information you might want to remove, paste them here? (or email to paul@biglybt.com if you want) - just in case there's some clues there.

**Comment by david-bakin** [comment]
I have the same problem - about 1/2 magnet links just don't ever proceed past "getting metadata" (forget the exact message) where that used to only rarely occur.  This started for me maybe 2 months ago more or less.  No networking changes on my host or internet router.  I'll try to diagnose as @parg has suggested.

**Comment by Apocalypse612** [comment]
I was having this issue just the other day, when in previous weeks and prior I never had any issues. All of my magnet links simply wouldn't let me download the files, and I didn't touch any settings (aside from a plugin possibly auto-updating?) 

The way I fixed my problem was doing a total uninstall and reinstall, so I don't think this was a lone case.

**Comment by christian-ruud** [comment]
Settings
    Allow Same IP Peers=1
    Auto Upload Speed Enabled=0
    AutoSpeed Available=1
    Default save path=D:\Torrent Downloads
    GUI Refresh=1000
    Ip Filter Autoload File=http://vi-webworks.com/f/tagqfxtteucbuldhezkz/bt_level1.gz
    Ip Filter Autoload Last Date=1394287075969
    IPV4 Prefer Stack=1
    IPV6 Enable Support=1
    locale.set.complete.count=596
    max active torrents=0
    max downloads=0
    Max Uploads=40
    Max Uploads Seeding=40
    Max.Peer.Connections.Per.Torrent=130
    Max.Peer.Connections.Per.Torrent.When.Seeding=65
    Max.Peer.Connections.Total=1100
    min downloads=0
    MyTorrents.SplitAt=4544
    Network Selection Default.I2P=1
    Network Selection Default.Tor=1
    Network Selection Prompt=1
    Play Download Finished File=<default>
    Play File Finished File=<default>
    Plugin.aercm.plugin.info=e
    Plugin.aercm.rcm.ftux.shown2=1
    Plugin.aercm.rcm.search.enable=0
    Plugin.aercm.rcm.ui.enable=0
    Plugin.azintrss.Pairing Migrated=1
    Plugin.azneti2phelper.azi2phelper.external.port.auto=32358
    Plugin.azneti2phelper.azi2phelper.internal.port.auto=29479
    Plugin.azneti2phelper.plugin.info=3/0/0/50/50/80/1/2/3/2/true;false/NfR+/709;3059;97;998;5879/340;7681
    Plugin.aznettor.control_port=32670
    Plugin.aznettor.prompt_on_use=0
    Plugin.aznettor.socks_port=23069
    Plugin.azupnpav.content_port=40888
    Plugin.azupnpav.uuid=uuid:a696f9d6-a573-65f8-59a2-663b9118357a
    Plugin.mlDHT.multihoming=1
    Plugin.UPnP.upnp.device.multipledevices.warned=1
    Prioritize First Piece=1
    Set Completion Flag For Completed Downloads On Start=0
    Show Downloading In Side Bar=0
    SideBar.Expanded.header.devices/1/uuid:06E46E0E-1B94-3BC6-4DD5-C8D3A3337AE9::upnp:rootdevice:13=1
    SideBar.Expanded.header.devices/1/uuid:3BCC7F75-9034-3769-99E3-C3B03A6B7E0A::upnp:rootdevice:19=1
    SideBar.Expanded.header.devices/1/uuid:446EE539-446E-E539-25F9-446EE53925F0::upnp:rootdevice:16=1
    SideBar.Expanded.header.devices/1/uuid:68707da5-6a55-f20d-3169-306b26577dca::upnp:rootdevice:14=1
    SideBar.Expanded.header.devices/1/uuid:7ec3c56a-b7fc-11dc-9151-83751a209937::upnp:rootdevice:12=1
    SideBar.Expanded.header.devices/1/uuid:CB1856E2-5B4E-3C5C-9FBE-8073AC26FCFE::upnp:rootdevice:20=1
    SpeedLimitMonitor.setting.download.limit.conf=MED
    SpeedLimitMonitor.setting.upload.limit.conf=LOW
    SpeedManagerAlgorithmProviderV2.setting.download.max.limit=1569760
    SpeedManagerAlgorithmProviderV2.setting.upload.max.limit=3595776
    SpeedTest Completed=1
    Start Minimized=1
    Start On Login=1
    Status Area Show IPF=1
    Status Area Show NAT=1
    Status Area Show SR=1
    TCP.Listen.Port=57247
    UDP.Listen.Port=57247
    UDP.NonData.Listen.Port=57247
    ui.addtorrent.openoptions=never
    Up Rate Limits Include Protocol=1
    User Mode=2
    v3.Show Welcome=0
    webseed.activation.uses.availability=0
    window.maximized=0
    window.rectangle=0,0,1163,857
    Wizard Completed=1
Plugins
    Swarm Discoveries: 0.8.8
    BiglyBT iTunes Integration: 0.5.1
    Location Provider: 0.4.9
    Message Sync Support: 0.9.5
    I2P Helper Plugin: 0.9.47.1.1
    Embedded Media Player: 4.3
    Rating: 1.7.1
    UPnP Media Server: 0.6.8
    uTP Plugin: 0.6.4
    Measurement Lab (M-Lab): 0.5
    mlDHT: 2.3
    Tor Helper Plugin: 1.2.6
Downloads - 0
Categories
    Categories.all
    Categories.uncategorized
Speed Limits
    Profiles
    Schedule

**Comment by parg** [comment]
I see you have 'prefer IPv4 stack' set - unless you have a good reason for setting that I would deselect it.

Also you have enabled 'multihoming' in the mlDHT plugin - not sure if this is a good thing to do or not, again, perhaps disable it.

**Comment by parg** [comment]
Might also be worth checking your ipfilter to ensure that it isn't blocking required addresses

**Comment by david-bakin** [comment]
In my case it was ipfilter.  But I wonder which list I've added has the bad IPs, so I could just exclude that list and keep the others ...
