### ISSUE TITLE
Idle CPU usage

### ISSUE THREAD

**Issue by asdsadsaasd12312132** [BiglySoftware/BiglyBT#1875]
I was observing the BiglyBT Launcher process in Task Manager and noticed that it fluctuated between 0 and 4%. Why is this the case when it is idle? I don't have any torrents in the library and it isn't subscribed to anything.

* Windows 10 Pro version 20H2
* BiglyBT 2.5.0.0

**Comment by parg** [comment]
DHT activity? Garbage collection?

**Comment by asdsadsaasd12312132** [comment]
It seemed DHT was the main culprit. Disabling it and enabling the low memory start up mode reduced CPU usage to 0 most of the time. I also noticed 150 mb of RAM being used in idle. Can this be reduced?

**Comment by parg** [comment]
Dunno, have you tried reducing the heap size under Options->Startup & Closedown ? Don't make it too small or BiglyBT won't start...
