### ISSUE TITLE
Stream URI's recognized as torrents

### ISSUE THREAD

**Issue by ArneBezuijen** [BiglySoftware/BiglyBT#1876]
Two useful options create an annoying interaction:
- Monitor clipboard for torrent links
- The media servers copy stream URI to clipboard

The problem:
Bigly will recognize the stream URI as a torrent link and attempt to download it, which causes the media server to activate and start sending data until it fails with a "torrent is too big" error. 

Expected behaviour:
Since this link is generated by Bigly, it would ideally recognize it as such and not attempt this at all.

System info:
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4930r7, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.5.0.0/4 az3

**Comment by parg** [comment]
Sounds reasonable, I'll take a look

**Comment by parg** [comment]
Should be fixed in Beta B28 which is now available (See Help menu to join the Beta Program)

**Comment by ArneBezuijen** [comment]
Just tested the beta and it seems to work fine now.

Thank you for the super quick solution!

**Comment by parg** [comment]
no problem!
