### ISSUE TITLE
Separate sort order for tags

### ISSUE THREAD

**Issue by Sauron3019** [BiglySoftware/BiglyBT#1877]
Remember sort order without separate column configuration for tags.

**Comment by parg** [comment]
Bit more info?

**Comment by Sauron3019** [comment]
I use different tags to sort.
I want different sort order for tags while keeping the column configuration.

**Comment by parg** [comment]
still don't understand...

**Comment by Sauron3019** [comment]
![resim](https://user-images.githubusercontent.com/66399617/99878493-d175e800-2c16-11eb-8d0a-b7858cbf9732.png)

Add option to enable separate column sort order for tags.
