### ISSUE TITLE
The "Downloading" Menu file list from the left column of the UI doesn't update when re-selecting files...

### ISSUE THREAD

**Issue by Apocalypse612** [BiglySoftware/BiglyBT#1878]
The "Downloading" Menu file list from the left column of the UI doesn't update when re-selecting files after the initial (1st) time. Even a force re-check doesn't do anything. 

I'm also having issues getting newly selected files from a torrent to start downloading, without the other files finishing first. I've ran a test in that regard, and even with a high priority, they won't budge (this was over a 5-10 minute span of time). All these newly added files were at 0 bytes downloaded. 

System:
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4930r7, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.5.0.0/4 az3

**Comment by parg** [comment]
Are the files you are selecting for download in a different torrent from the currently downloading one(s)? Torrents download in queue order with in the 'downloading' view, the files of torrents further down the queue in a 'queued' state will not download before ones higher, regardless of their priority.

**Comment by Apocalypse612** [comment]
Negative, during my discovery of this, this was the only torrent file I had in the queue, there was nothing else there.
