### ISSUE TITLE
VPN Helper PlugIn (PIA)

### ISSUE THREAD

**Issue by DeathStalker77** [BiglySoftware/BiglyBT#188]
The VPN Helper PlugIn for PIA does not seem to work.  I have tried it with and without my account info (when connected to the PIA client).  I like the idea of just having my client connected for port forwarding, but how does the plugin determine what server location to log onto?

The message I get is -
VPN NOT SET UP CORRECTLY
x Bind IP null

Thanks.

**Comment by TuxPaper** [comment]
hmm, that's an odd one.  Does it still give that error after a few minutes (ie.  after you click the Check Now button, after a few minutes)?

You can also check your "Bind to local IP address" field in Options->Connection->Advanced Network Settings.  You can manually set it to the interface that has a 10.x.x.x address.  ie.  If it lists eth10[0] as "10.4.1.123", then you can fill in the bind field with "eth10[0]" and click save.  I'm not sure if that will help the VPN plugin, but it will guarantee a kill switch within BiglyBT if you lose your VPN.

**Comment by DeathStalker77** [comment]
Yes, it still gives the error.  Could it possibly be that 1) I am connected using the PIA Client &/or 2) I'm also running uTorrent at the same time?  (Neither would seem likely though :( )

**Comment by gitoss** [comment]
Doh, I opened a dupe ticket for this,.. sorry: https://github.com/BiglySoftware/BiglyBT/issues/210

For me, the vpn helper plugin works ok on win7 x86 (but requests a different port from the pia manager app). However it completely fails with the error seen by DeathStalker77 on my x64 win8 and win10 setups... both used to work with Vuze (though running java8 instead of java9 and vpn helper 5.2 instead of 5.5)

**Comment by MarvinParanoidAndroid** [comment]
The VPN Helper PlugIn for PIA stopt working a couple of days ago. I am getting the same message as @DeathStalker77 . I have the latest version of BiglyBT and VPN helper. They are running on a Windows 10 x64 machine.

**Comment by shizknight** [comment]
I am also seeing an issue with port forwarding.  Providing the account details in vpn helper config no longer seems to work and the error just tells you to set the user/pass.  I suspect this is an issue with newer versions of the PIA client itself.  I have a couple of computers with older versions of PIA and vpn helper doesn't have issues there.  I ran into this when setting up a new computer and installed v79 of PIA.

**Comment by gitoss** [comment]
Same over here, by now running PIA client 83 on Windows - the vpn plugin advises I should enter user/pass to get the forwarding port, but it's not working anymore. The vpn can check for the eth config just fine, but you have to copy/paste the port from the PIA tooltip to BiglyBT for the time being.

**Comment by TuxPaper** [comment]
Closing Issue.  We released a new VPN Helper plugin many weeks ago that works with the latest PIA Manager, but missed this Issue when closing the others.  If anyone still has this issue, please file a new Issue.  Thanks!
