### ISSUE TITLE
Already did the donation "One Time Offering"

### ISSUE THREAD

**Issue by petcol** [BiglySoftware/BiglyBT#1882]
Was asked ages ago for the Donation chose the One Time Offering and it is now asking again?

Just wondering is that to be expected, as I think I've done it a few times already.

* OS and version
Win 10 Pro 64-bit

* BiglyBT Version Number
v2.4.0

* For *nix: Desktop Environment

**Comment by parg** [comment]
Whether or not you have donated is recorded locally on your computer, if for some reason this information is lost then unfortunately you will be prompted again.

You can prevent the donation prompt by downloading the following .zip file:

[alreadydonated.zip](https://github.com/BiglySoftware/BiglyBT/files/5582785/alreadydonated.zip)

and unzipping it to get the 'alreadydonated.biglybt' file - then open this in BiglyBT via the File menu's Open->BiglyBT File...

Thanks for supporting BiglyBT!

(there is a version 2.5 out by the way)

**Comment by petcol** [comment]
thanks I guess I'll now wait and see much appreciated.

**Comment by parg** [comment]
Please reopen the issue if needed!
