### ISSUE TITLE
Change data directory doesn't work

### ISSUE THREAD

**Issue by elisionducoeur** [BiglySoftware/BiglyBT#1885]
When selecting multiple torrents and clicking change data directory, the Save In location doesn't change.

Also unable to change data directory for single torrent (the option never shows up)

Also if torrent is completed or partially completed, reinstall biglybt, readd torrent, recheck files shows 0% done.

**Comment by parg** [comment]
Option only shows up when the download is in a 'files missing' error state. Just tried it and it updated the 'save in' location for me, odd.

Verify that the re-added download is actually in the same save location as the previous one - sometimes you can end up with an extra folder in the save path.

**Comment by elisionducoeur** [comment]
Also when adding multiple torrents, only the save location in the torrent options popup for the first torrent can be changed. Every torrent after that doesn't show anything when you click the arrow next to save location

**Comment by elisionducoeur** [comment]
One reason why recheck is failing for partially completed torrents. Partially completed torrent files are in "downloads/partial" and when I add the torrent I can specify that as the download location (and it's reflected in Save in). However, the moment I click recheck, the Save in changes to "downloads/completed", so I'm assuming it's checking the wrong folder.

Some other torrents though, it doesn't change the Save in location. But still can't correctly recheck the partially complete files in "downloads/partial"

Still no idea why it's not correctly rechecking the fully completed torrents.

**Comment by parg** [comment]
A screenshot of the problem might help if you can grab one

**Comment by elisionducoeur** [comment]
I just gave up on the rechecking. Something to note is that biglybt seems to preallocate files. So if you have a set of partially downloaded files in "downloads/progress/MSOffice" and a set of preallocated (but empty) files in "downloads/downloaded/MSOffice", and you add the torrent, select the save location as "downloads/progress/MSOffice", then do a recheck, it'll first switch the save location to "downloads/downloaded/MSOffice", check the empty files, then show 0% completion.

Doesn't seem like intended behavior

Also if "change data directory" is only supposed to show up in "files missing" error state, it's probably also unintended behavior that it shows up when you select multiple files (that are not in that error state) and right click
