### ISSUE TITLE
Set tag through torrent-add

### ISSUE THREAD

**Issue by elisionducoeur** [BiglySoftware/BiglyBT#1886]
Is there a way to set a tag through the transmission RPC request torrent-add? Or set a tag based on the initial save location of the files?
Using xmwebui plugin

**Comment by parg** [comment]
You could setup the client with a Tag using a Tag Constraint (https://github.com/BiglySoftware/BiglyBT/wiki/Tags#Constraints) based on save_path or save_folder to get that Tag auto-assigned

**Comment by parg** [comment]
For example, on windows a Tag Constraint of

    matches( save_folder, "^C:\\downloads\\.*" )

will match against any torrents saved in C:\downloads (\ needs escaping in regex).

If you want this tag to still be assigned after a torrent is moved to another location then you need to set the tag constraint 'scope' to 'addition only'
