### ISSUE TITLE
Column widths lost on program exit

### ISSUE THREAD

**Issue by Oasis644** [BiglySoftware/BiglyBT#1892]
Since upgrading to a 4k monitor, on exiting the program all custom column width settings disappear.

No other changes other than the monitor swap have been made.  This is issue is not experienced in any other programs I have used since the swap.

Any suggestions, please ?

**Comment by TuxPaper** [comment]
Does it happen every time you start BiglyBT, or was it a one time thing?

**Comment by Oasis644** [comment]
It happens every time.
