### ISSUE TITLE
ctrl-a is causing the app to be stuck

### ISSUE THREAD

**Issue by moham96** [BiglySoftware/BiglyBT#1893]
* OS and version: Linux v5.4.80-2-MANJARO, amd64 (64 bit) (manjaro stable),Java 14.0.2 (64 bit)
* BiglyBT Version Number: B2.5.0.0/4 az3
* For *nix: Desktop Environment: tried both deepin-desktop and gnome

To reproduce the problem:
1- left click anywhere in the torrents list.
2- click(ctrl+a) from the keyboard to select all torrents.
3- left click anywhere in the torrents list to remove the selection.

now the app gui is not responding and I have to kill the app and start it again

Regards

**Comment by parg** [comment]
Not happening for me on Kubuntu

**Comment by parg** [comment]
So I installed it in VirtualBox

Java 1.8.0_265 (64 bit)
  Oracle Corporation
/usr/lib/jvm/java-8-openjdk/jre

SWT v4934r5, gtk/3.24.23, zoom=100, dpi=96
Linux v5.8.16-2-MANJARO, amd64 (64 bit)
B2.5.0.0/4 az3

can't reproduce the issue

**Comment by moham96** [comment]
@parg there was a recent update in manjaro which might be causing this issue
you might need to run `sudo pacman -Syu` to fully update the system packages
also you're using java-8 while I'm on java-14.
run `sudo pacman -S jre-openjdk' to install the latest version and then run `sudo archlinux-java set java-14-openjdk` to set it as the default version

regards

**Comment by moham96** [comment]
@parg so deleted the `~/.biglybt` directory and the problem is gone even on java-14 not sure what's going on but I was running a beta version of biglybt and it created the `~/.biglybt` directory so maybe that was the problem ?!
Anyway sorry for the noise. I will reopen the issue if it rises again

**Comment by parg** [comment]
Hmm, don't see how the ~/.biglybt directory could be causing such a problem, it just holds config data and the such. 

I'll try updating the system as you say and try java14

**Comment by parg** [comment]
still works fine with those updates, tried beta programme too.
