### ISSUE TITLE
[Linux] BiglyBT freezes when Changing Data Directory on a newly added torrent

### ISSUE THREAD

**Issue by txtsd** [BiglySoftware/BiglyBT#1894]
After running BiglyBT for a while, when I add a new torrent and set the data directory by right clicking and selecting `Change Data Directory`, BiglyBT freezes and the window and tray icon stop responding.

I've enabled logging and I'll post logs the next time this happens.

* OS: Arch Linux
* BiglyBT Version Number: 2.5.0.0
* For *nix: Openbox, no DE
* System info:
```
Java 14.0.2 (64 bit)
  N/A
/usr/lib/jvm/java-14-openjdk

SWT v4934r5, gtk/3.24.23, zoom=100, dpi=96
Linux v5.9.11-1-ck-zen, amd64 (64 bit)
B2.5.0.0/4 az3
```

**Comment by parg** [comment]
There are a number of people reporting these kind of issues on Linux when interacting with the system file/directory selection dialog. Unfortunately it is most likely something to do with GTK, or the SWT UI Library's use of GTK that causes this and this isn't something we can directly fix ourselves :(

**Comment by txtsd** [comment]
Have any of them gotten close to pinpointing the cause?

**Comment by txtsd** [comment]
It happened again, but there is nothing in the logs. Just network stuff. Any tips as to what logs I should filter out in the logs section of the options?

**Comment by parg** [comment]
I am assuming the issue is not within BiglyBT code so unfortunately any logging we capture won't show anything :( Is your system fully updated?

**Comment by txtsd** [comment]
Yes, it is.

Is there any way to compile the jar so that SWT can output debug logs?

**Comment by parg** [comment]
Not sure... you could try the most recent SWT:

[swt-I20201201-1800-gtk-linux-x86_64.zip](https://github.com/BiglySoftware/BiglyBT/files/5629115/swt-I20201201-1800-gtk-linux-x86_64.zip)

extract the "swt.jar" from that zip file and replace the one in the BiglyBT installation folder (make a backup of the existing one in case)

**Comment by txtsd** [comment]
Replace `swt-aarch64.jar` or `swt-x86_64.jar`?

**Comment by parg** [comment]
hmm, good point, I think the launcher copies the .swt file in on startup. In your case swt-x86_64.jar

**Comment by txtsd** [comment]
That's the one I replaced. I realized later that aarch64 is arm.

**Comment by parg** [comment]
You can check that you've updated things by going to the About dialog - it should say SWT is version

4940r23

**Comment by txtsd** [comment]
Yep. That's what it shows now.

Where does BiglyBT normally acquire it from? The system-installed package, or does it download it separately, or does it ship with one?

**Comment by parg** [comment]
swt is shipped with BiglyBT

**Comment by txtsd** [comment]
It froze again, but this time it happened while right clicking an entry in the downloading list.

**Comment by txtsd** [comment]
It also straight-up crashed a little bit after I added new trackers to some torrents. Nothing in the logs.

**Comment by txtsd** [comment]
Sorry for comment spam, but it froze again when changing data directory, but this time BiglyBT hadn't even been running for more than 5 minutes. Usually, if I have just restarted BiglyBT, it doesn't freeze when I change data directory.

**Comment by parg** [comment]
I guess we can say that the latest SWT didn't help then :(

I don't get any crashes on Kubuntu running with the same GTK version

**Comment by txtsd** [comment]
Did you try with openjdk 14?

**Comment by parg** [comment]
I started installing Arch Linux, went for Plasma, but ran out of space. Screw that process, not going there again.

**Comment by txtsd** [comment]
> I started installing Arch Linux, went for Plasma, but ran out of space. Screw that process, not going there again.

Use an Arch based distro with an easier installation process. There's no need to subject yourself to a raw Arch installation just for a VM lol.

**Comment by parg** [comment]
soooooo what do you recommend?

**Comment by txtsd** [comment]
Manjaro or ArchLabs should be fine. I haven't personally tried either. ArchLabs ships with an Openbox desktop by default, so it will be closer to my setup.

**Comment by parg** [comment]
All these distros drive me nuts

**Comment by txtsd** [comment]
Don't worry about it. I'll spin up an Arch VM and see if BiglyBT breaks or no.

**Comment by parg** [comment]
I have openbox running on ArchLabs latest in VirtualBox and from limited playing around it hasn't crashed *yet*

**Comment by txtsd** [comment]
> EDIT: Try leaving some torrents seeding for an hour or so, then add a torrent in paused state, and change its data directory.

Do this on it.

**Comment by txtsd** [comment]
Ugh, this time it crashed while trying to `Delete from Computer` two torrents at once.

**Comment by parg** [comment]
Try a different window manager?

**Comment by txtsd** [comment]
Might as well, at this point. I'll set up KDE or LXQt tomorrow.

**Comment by txtsd** [comment]
I removed a handful of magnet downloads that were stuck in downloading metadata state, and another handful of torrents that were stuck at 0%, and now the freezes are not happening anymore. Any way these could be related to the freezes?

**Comment by parg** [comment]
can't think of anyway :(

**Comment by txtsd** [comment]
If it doesn't happen anymore at all, I'll re-add those magnets and torrents, and try to replicate.

**Comment by txtsd** [comment]
Nope, it happened again even without those torrents and metadata downloads that I removed.
