### ISSUE TITLE
(android) biglybt is really slow

### ISSUE THREAD

**Issue by legacychimera247** [BiglySoftware/BiglyBT#1895]
hello,
I often download things with my android phone and biglybt, but the thing is, biglybt is really slow if compared to other apps

To give you an example

If i add a magnet to biglybt, the app search for the file and
1 if the file is available, after 20 or 30 seconds, is found and it starts downloading
2 if the file is not available i get the message that no source has been found, but only after a very long time

If i add a magnet to bitcomet and
1 the file is available, it starts downloading it right away (really seconds)
2 is not available, i do have an error in really seconds, and even if the file is found but there are no sources to downloading it, it gets found really quickly

I had then tried a speed test with a file full of seeds
Biglybt starts downloading the file and it's speed it's about 400 kbps (left a minute or two and the speed varied but remained almost the same), in bitcomet i do had immediately almost 1.5 mb speed, and that's because (i guess) bitcomet was seeing peers biglybt was not

Anyway to solve this?

**Comment by TuxPaper** [comment]
How long do you have each client running before adding a magnet?  Both BiglyBT and BitComet (and any other app) need to establish a presence in the DHT, which can take a few minutes on startup of the app.  This might affect the speeds too, if, as you pointed out, BitComet gets a list of peers before BiglyBT does.

**Comment by legacychimera247** [comment]
they were both freshly open

i made another test with some other torrents today where biglybt was kept open for some minute while bitcomet was freshly open

on both cases, biglybt was able to download the magnet, after like a minute, then the speeds where about at 80/90kbs while bitcomet needed just 2 seconds to open the magnet and the download speed was around 150/200 kbs (yeah bad signal from where i tried yesterday)

i feel like there is a difference here...

**Comment by TuxPaper** [comment]
There's a delay setting for looking up torrents in mldht that can be set in "Full Settings"->Plugins->"Magnet URI Handler"->"delay [secs]".  The default is 20.  If you set it to 0, it will lookup the torrent on mlDHT and BiglyBT in parallel.

We are considering changing the default to 0, as the reasons for having a delay have gone away over the years.  If you have time, try it with 0 and let us know if anything improves.

**Comment by legacychimera247** [comment]
Tried but saw no difference at all

I've tried with another torrent and biglybt needed about 20 seconds to find the magnet while bitcomet was almost immediate

On a positive side speed was almost the same althought biglybt reached 1.10 mb max while bitcomet 1.50...

**Comment by legacychimera247** [comment]
Had a try with another torrent, bitcomet taked exactly 2 seconds to download the magnet, biglybt was uncapable of, i tried 6 or 7 times, then i ended up downloading the thing with bitcomet

On a sidenote, to actually delete the magnet and try again i had to shutdown the biglybt service completely because the app was just saying that magnet was already added...

**Comment by legacychimera247** [comment]
Just wanted to point out that latest update solved everything or so it seems, thank you...

**Comment by TuxPaper** [comment]
Thanks for the update, it's good to know!
