### ISSUE TITLE
[Linux] Icons in RSSFeed Scanner view are hidden with no way to resize the view

### ISSUE THREAD

**Issue by txtsd** [BiglySoftware/BiglyBT#1898]
Screenshot of view:
![2020-12-07-090948_960x597_scrot](https://user-images.githubusercontent.com/768728/101308101-116fd880-386f-11eb-8777-a28a51d781fb.png)
There is infact a scrollbar available that lets me scroll to the side and view the icons, but with so much wasted space, I shouldn't need to scroll to see the icons. They should just be visible.

EDIT: Also, the icons don't have any mouseover text.

* OS: Arch Linux
* BiglyBT Version Number: 2.5.0.0
* For *nix: Openbox, no DE
* System info:
```
Java 14.0.2 (64 bit)
  N/A
/usr/lib/jvm/java-14-openjdk

SWT v4940r23, gtk/3.24.23, zoom=100, dpi=96
Linux v5.9.12-2-ck-zen, amd64 (64 bit)
B2.5.0.0/4 az3
```

**Comment by parg** [comment]
ArchLabs!

![image](https://user-images.githubusercontent.com/395293/101339375-3e73b980-3876-11eb-8cdd-9549ca7a07e7.png)

**Comment by txtsd** [comment]
This time I'm on KDE, not Openbox anymore. I'll try without `_JAVA_OPTIONS`
