### ISSUE TITLE
Deleting >200 torrents at a time never completes

### ISSUE THREAD

**Issue by david-bakin** [BiglySoftware/BiglyBT#1902]
(BiglyBT Beta 2.5.0.1_B35 though this issue has been present for at least a year, probably longer.  Windows 2016 Datacenter.)

Deleting large numbers of torrents (>200) at once is extremely slow.  (I've never waited long enough for >250 to actually complete.)  Java is dying the GC death perhaps?  Seems like something is too resource intensive ...?

Suppose you have >4000 entries in Library (and they're all Stopped too) and you want to clean up.  So you go to Library (or Stopped), select the first 250 by order # (which are the oldest 250), and delete them (delete .torrent file as well is checked, apply action to all 250 is checked, and you hit the "delete from computer" button).  BTW - the downloaded files themselves have already been moved away elsewhere, all that is left are the torrent files.

Upon hitting the button CPU rises relatively quickly to 100% and memory usage climbs up to 1Gb.  (Hmm, at this point I should say I have for Java Options: Max Heap 1Gb, Min Heap 256Mb, Max Direct 512Mb, and this is an otherwise unloaded/unused machine with 64Gb main memory.)  Each time I've tried this I bail out after >10 minutes, killing BiglyBt.  (When I restart BiglyBt there are a lot of files in Error state - which I then delete - which is also pretty slow, though it completes.)

By experimentation 200 torrents almost always works though it is ridiculously slow. (7-10 minutes, by timer.)  I've never waited long enough to see if 250 actually completes.

**Comment by parg** [comment]
Hmm! Don't suppose you have any thread_1/2.log files from when it takes all the CPU? Might give a clue

**Comment by GDXN** [comment]
Deletion is inefective and memory intensive, try to change the "Max Heap" to much more than 1Gb, I use 8 GB and even if is slow it's much faster than with 1GB even when deleting a 1000 torrents at the same time ( also in advance mode closing the "My torrents" tab help with the speed).

**Comment by david-bakin** [comment]
Thank you @GDXN - thread logs (as suggested by @parg) definitely indicated death-by-GC.  It didn't occur to me that I could increase the heap past 1Gb - but what the heck, it's a 64-bit VM now, I had forgotten - and that works fine.
