### ISSUE TITLE
Can't force BiglyBT to shut down, process keeps running

### ISSUE THREAD

**Issue by Knocks** [BiglySoftware/BiglyBT#1903]
I exited BiglyBT but it's continuing to run in the background.  Forcing it to close from Task Manager does not do anything.   Terminating the process from the Details tab also does not work ("Access is denied").  It has been 2-3 hours.

* Windows 10 Home
* BiglyBT Version Number 2.5.0.0

**Comment by parg** [comment]
https://superuser.com/questions/585073/how-to-overcome-access-denied-when-killing-process-in-windows ?
