### ISSUE TITLE
BiglyBT changes my keyboard / accented characters don´t work.

### ISSUE THREAD

**Issue by AVA72** [BiglySoftware/BiglyBT#1906]
After I start BiglyBT  my windows accented characters don´t work.

The comma charater displays   ´´   instead of ´  

example.  

typing ´ and o  should display ó, instead is shows ´´o   

I have tried various win 10 version the problem is in all of them. 

Keyboard Layout: Icelandic    Regional setting: Iceland - Windows 10 in English.
BiglyBT version  2.5.0.0
Windows 10 Version : ALL

**Comment by parg** [comment]
hmm, I can switch to Japanese and things work fine - sounds like an issue with your input method - BiglyBT just gets the unicode characters that the OS sends it. Try right-clicking in the text entry widget, there should be some options?

**Comment by AVA72** [comment]
After further inspection this seems to be a win10 issue.
