### ISSUE TITLE
A way to set auto download

### ISSUE THREAD

**Issue by ajhong2** [BiglySoftware/BiglyBT#1907]
I've looked and it doesn't seem to be a way for you to set a directory to automatically start a download to save to a directory.

Example would be to click a torrent/magnet link and then for it to start downloading to a designated folder automatically without having to confirm the location. (This would be something you could turn on/off of course)

**Comment by parg** [comment]
Tools->Options->Files:

1) Set the Default Directory to wherever you want stuff saved
2) Set the following 'when opening a torrent, show options dialog' to 'never again'

**Comment by ajhong2** [comment]
![image](https://user-images.githubusercontent.com/31233783/101982857-aa19a600-3c2b-11eb-9740-54970042b4f0.png)

This box seems to always show up. Not sure if that's not intended. The torrent option doesn't pop up with the setting you mentioned however.

**Comment by parg** [comment]
Ah, you need to set a default torrent file save location too - Options->Files->Torrents
