### ISSUE TITLE
The notificaiton alert starts sliding from the bottom of the screen rather than from the top of the task bar when the task bar is higher than default

### ISSUE THREAD

**Issue by asdsadsaasd12312132** [BiglySoftware/BiglyBT#1910]
https://youtu.be/uAwLMFIBN2I?t=17

I think the alerts should start from where the top of the task bar is by default or as an optional setting rather than from the bottom of the screen. If the user's task bar is high, the alert will spend a significant amount of time sliding up the screen and this can be fairly distracting and annoying.

**Comment by parg** [comment]
Not sure that BiglyBT can tell where the taskbar happens to be. You can always turn the sliding behaviour off in the settings (under Alerts I think)

**Comment by asdsadsaasd12312132** [comment]
I think it does know because if it didn't, how does it stop at the top of my task bar instead of sliding up the way to the top of my monitor?

**Comment by parg** [comment]
yup, you're right :) someone's looking at it!

**Comment by parg** [comment]
Should be fixed in beta B_37

**Comment by asdsadsaasd12312132** [comment]
Fixed.
