### ISSUE TITLE
Interface Issues with BiglyBT 2.5.0.0 on Big Sur

### ISSUE THREAD

**Issue by mattsigal** [BiglySoftware/BiglyBT#1911]
I upgraded my iMac to Big Sur (OS X 11.0.1) last night and now BiglyBT (v2.5.0.0)  is giving me issues. Upon launch, the interface gives the spinning beachball, and looks like:

![Screen Shot 2020-12-12 at 1 30 50 PM](https://user-images.githubusercontent.com/1421758/101995386-56847800-3c7e-11eb-80e0-f828db7903a0.png)

It doesn't load past this point (and I have to force quit the application to get it to go away). I tried reinstalling 2.5.0.0 and, after the reinstall, it launched once although some of the interface elements were a bit wacky (the icon bar, in particular):

![Screen Shot 2020-12-12 at 1 34 14 PM](https://user-images.githubusercontent.com/1421758/101995457-c3980d80-3c7e-11eb-9621-a6afa1ff00ab.png)

However, quitting and restarting the application afterward goes back to the first problem.

Any ideas what is causing this/how to fix it?

**Comment by parg** [comment]
Works OK on my Macbook Pro - if you get it back to the vaguely working state go to the About dialoag and copy/paste the details of the SWT version, zoom etc here please.

**Comment by mattsigal** [comment]
Weird! I wonder what is causing the issue. I did the reinstall trick and it is back to the vaguely working state. Here is the About dialog:

![Screen Shot 2020-12-12 at 2 27 35 PM](https://user-images.githubusercontent.com/1421758/101996318-41abe280-3c86-11eb-8319-1cee94651d30.png)

**Comment by parg** [comment]
I've attached an updated SWT UI library - can you download it and then install it using 

    Help menu->Advanced->Install update manually 

and see if that fixes anything?

[swt_swt-4936r26-cocoa-macosx-x86_64.zip](https://github.com/BiglySoftware/BiglyBT/files/5683906/swt_swt-4936r26-cocoa-macosx-x86_64.zip)

**Comment by mattsigal** [comment]
Thanks for the help! I updated the library and the application now launches (like it does after the update install) but the icons still look funny.

**Comment by parg** [comment]
OK, that's some progress then! Is it just the toolbar icons that are being weird now or are there any other UI issues?

**Comment by mattsigal** [comment]
For sure! And I can confirm that I can now quit/relaunch BiglyBT without having to reinstall which is nice!

RE: UI issues, I spent some time clicking through areas and pretty much everything runs as expected except for the toolbar icons and in the RSSFeed Scanner plugin tab, the Options, Download History, and Help tabs render correctly, but the Status tab is blank (completely grey screen).
