### ISSUE TITLE
Folder names with android 10

### ISSUE THREAD

**Issue by toxicroadkill** [BiglySoftware/BiglyBT#1913]
Android version 10
BiglyBT version 1.3.0.8 build 1030008

When a torrent finishes downloading, I have it set to move to a folder on my phones sd card.

After the move, it renames the folder containing the download data to a filename that is url encoded escape characters, for example

"%2FTo%20All%20The%20............. (rest of the name redacted, but you get the idea)

spaces are converted to %20, and so on
however, the files in the folder (that have the naming issue), are correct

**Comment by TuxPaper** [comment]
Phew, that's a good bug! Thanks for the report

**Comment by toxicroadkill** [comment]
no problem, bugs are always so much fun to track down, and there always seems to be a new one

btw:

Ive started a auction site, and if your interested in listing anything for sale, first 100 people to sign up,, have lifetime free memberships

https://buyersattic.com

**Comment by toxicroadkill** [comment]
btw2: I love your bt client, just started using it on my mac, and it blows away the other clients by a long shot, and actually works very well

I had it on my android 10, but with the filename issue, I had un-installed it, will put it back on the phone again soon


thanks again for quality software and the reply about the bug
