### ISSUE TITLE
remove from library leaves .torrent files

### ISSUE THREAD

**Issue by thatso** [BiglySoftware/BiglyBT#1915]
Java 11.0.9.1 (64 bit)
Debian
/usr/lib/jvm/java-11-openjdk-amd64
SWT v4757, gtk/3.24.5, zoom=100, dpi=96
Linux v4.19.0-13-amd64, amd64 (64 bit)
B2.6.0.0/4 az3

Since the latest 2.6.0.0, remove from library no longer deletes the .torrent file despite the option "delete .torrent files as well" is checked. Never had this issue with older versions.

**Comment by parg** [comment]
Which .torrent file? If you have BiglyBT to save .torrent files (in the 'torrents' folder by default) then they should be deleted from there but the original will remain.

**Comment by thatso** [comment]
In tools -> options -> files -> completion moving I have checked "move completed files (when being removed)" and set a directory. Until previous versions, downloading i.e. Debian10.iso and afterwards "remove from library" with "delete .torrent files as well" would have left only the finished file Debian10.iso. Now it leaves both Debian10.iso and the corresponding Debian10.torrent in the same directory.

**Comment by parg** [comment]
Do you have the option below it (move .torrent) enabled as well?

**Comment by thatso** [comment]
Yes, in tools -> options -> files -> completion moving I have enabled "move .torrent" and did not change any options since the last update.

**Comment by parg** [comment]
Deselect it. There was a change made around recovery of .torrent files on a 'move operation' to fix an issue a user had that is obviously intereacting the the 'move on complete' in a new and interesting way.

**Comment by thatso** [comment]
Thanks, disabling "move .torrent" in "completion moving" reverted the behavior back to what I was used.

**Comment by parg** [comment]
I'll take a look at getting things back to how they were without changing that setting sometime, thanks!
