### ISSUE TITLE
2.6 not showing up in Check Update on B39

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#1916]
Noticed 2.6.0.0 as a peer on a download. Did a Help/Check for Updates. Then Checked the BiglyBT Web Site. Says 2.6.0.0 was up 2 days ago.

So something is not working as it should.

Java 1.8.0_271 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_271

SWT v4930r7, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.5.0.1_B39/4 az3

**Comment by TuxPaper** [comment]
We tend to roll out updates slowly in case there's some major bug discovered.  It'll probably be at 100% in a day or so.  If you really want it you can download the installer, or maybe do Help->Check for Updates 100 times in a row ;) (I don't recommend the latter :P)

**Comment by NaPurHab** [comment]
Hmm, I will wait for it to come in Updates. But I think of Releases, as Cleaner Betas. I keep seeding the last 3 Betas and the Previous Release always. Would be useful if in addition to a Download Link on the Home Page, there was a Magnet so everyone is seeding the same version.  Share the distribution load.

**Comment by NaPurHab** [comment]
Now one week after Release of 2.6.0.0 and
![image](https://user-images.githubusercontent.com/37715552/103105476-1ddc8b00-45fc-11eb-9133-7c2d3295b416.png)
All I want for Christmas is the 2.6.0.0 (Beta). After all whatever you call it, it's just another step in the process.

**Comment by NaPurHab** [comment]
Just got 2.6.0.1_B03

What happened to core_BiglyBT_Update_2.6.0.0_win64.zip?  I never got it. And also, what happened to B01 and B02?  This looks like something is not working as it should.

Can someone supply the HASH for core_BiglyBT_Update_2.6.0.0_win64.zip, I SEED indefinitely (at least until it is replaced by a new version.  Might be a good idea to have a Magnet on the HOME Page for downloading too.

**Comment by parg** [comment]
All updates are available via chat channels:

chat:?BiglyBT%3A%20Updates%5Bpk%3DAQRJRSM5DNDDN3PHTAV3MEWUBMMTTFB4P2YYKNXECONTZXQYUGS32AOGSMZ3D2DGN2VTWYRWEC5K5ZI%26ro%3D1%5D

chat:anon:?BiglyBT%3A%20Updates%5Bpk%3DARJPXVO5NRE3ZG4OBCWPA5I6ZXF6D2JSPDS23Q4GEPW7LRBVIC7EWLRVM2QS6ZAXR357L2B4ZPWAATQ%26ro%3D1%5D

so perhaps you could grab them from there?

**Comment by NaPurHab** [comment]
Found the updates on Chat and got B05. But 2.6 Release, B01, B02, B03, B04 and B05 did not update through the Update. B03a did. I manually got B05 from the chat channel. And had to manually replace the JAR to install it.  And now I can't find the Channel Again. And the 2 links above, I opened both and there is nothing happening in them.  And the Chat that I had in B03a that let me download B05 is now missing. I showed a msg history that had all the versions going back past 2.5.0.0.  Now nothing.

Will see what happens when B06 comes out. If it updates or not.

**Comment by NaPurHab** [comment]
Beta Update Page says B06 is out.  But Check for updates shows:

![image](https://user-images.githubusercontent.com/37715552/103245985-e0476d00-492f-11eb-8c40-fd0a36e3b9b3.png)

Tried downloading 2.6.0.0 Win64 and installed that over.  Then Re-joined the Beta Program.  And still I get the above error.

And I went into the above 2 chat rooms. They are now Empty of updates. And have no history.

![image](https://user-images.githubusercontent.com/37715552/103246225-b80c3e00-4930-11eb-93d5-f87dbdf303a2.png)

Looks like Update is Broken.

**Comment by NaPurHab** [comment]
Finally got B06 to update from Check for updates.
As above I installed 2.6.0.0 release over B05 which would not update. 
Then 2.6.0.0 would not update to B06.
Finally got it to work when I manually reinstalled B03a
Then Check for Updates found B06 and updated.
Not Fun.

**Comment by parg** [comment]
Got 'anonymous updates' enabled?

**Comment by NaPurHab** [comment]
Nope, not checked.
