### ISSUE TITLE
Allow "open torrent" windows to not be filled with clipboard data when opening

### ISSUE THREAD

**Issue by pseudo555** [BiglySoftware/BiglyBT#1918]
* Win 10 20h2
* BiglyBT Version 2.6.0.0

Each time I click on "Open torrent" button, the textarea is already pre-filled with the magnet link present in the clipboard.
Is there a way to avoid that behavior ?
If not, could it be added as an option (like "Automatically fill open torrent windows with torrent/magnet link from clipboard"

**Comment by parg** [comment]
It is highlighted - just hit delete?

**Comment by pseudo555** [comment]
TextArea are blank by default, why filled it automatically ?

To be honest, i don't want to press delete each time i open that window.

I would understand if the text area was filled du to "monitor clipboard for torrent links" option checked, but that's not my case
I also understand that some people might want such behavior, but why force it ?

**Comment by david-bakin** [comment]
Uh, actually I like it the way it is.  I find it useful.  If that matters ...

(And it _is_ highlighted.  But even it if wasn't, ^A would highlight it so you could delete it.)
