### ISSUE TITLE
Multi-file torrents where you're only downloading a single file should be able to be put at "top level" without interfering with other such torrents

### ISSUE THREAD

**Issue by david-bakin** [BiglySoftware/BiglyBT#1920]
Feature suggestion:

Lots of torrents have only one file I want but have other files for various reasons that the original torrent uploader thought important.  (E.g., the frequently seen `metadata.opf` or various `Downloaded from ...` or `Get more free stuff here ....`.)

I use the options under Files/Ignore to ignore nearly all of these unwanted files successfully, via "file names to auto-skip" (using regex for the win!) as well as "extensions of files to auto-skip" _and also_ using "Move files not selected for download into a subfolder".  Plus I'm also using "Move completed files after download" to put all completed torrents into a special directory.

> BTW, I don't understand what "move completed files (when being removed)" is for ... I mean, if you're removing files why are they being moved?

I find that in a group of related torrents like this I'm downloading, frequently there are among them unwanted files with the same name, again, e.g., `metadata.opf` or `cover.jpg` or `Downloaded from ...`.  

The behavior I would like is:

* When there's only one file I want downloaded I want to be able to do the "remove top level folder" so it just gets placed directly in the download folder while downloading and then in the moved-to-folder after completion.  Not under a level of directory.

But if I do that manually (i.e., "remove top level folder") then the unwanted files conflict with each other either at the top level or in the `.DO-NOT-DOWNLOAD` directory I create for them.  They step on each other and I get `error: disk write error: file '...' is in use by ...` message.

So I'd like several things as part of this feature request - first two are most important:

1. This scenario ought to work - the different torrents should not conflict as the only file I'm actually downloading doesn't conflict.  (I understand you need some place to store odd ends of pieces when a piece is shared by both a wanted file and an unwanted file but I don't care actually _what_ that place is called - doesn't have to be the name of the actual file in the torrent ... alternatively, I also don't care that the  `.DO-NOT_DOWNLOAD` I'm using is called that - it could have an arbitrary suffix appended to it for example.)

1. If I do this - do "remove top level" on a multi-file torrent of which I'm only downloading one file - I find that the "display name" of the torrent is set to the download directory - it ought to be set to the name of the single file I'm downloading.  (Or maybe the name of the torrent - in any event setting it to the name of the download directory seems not right.)

1. It would be sweet if, when moving on completion, after the "re-check pieces when download is done" check (which I also do), the unwanted files were actually _deleted_.  (There's an option in Files/File Deletion to delete them when _removing_ a download, but not for _completing_ a download.)

1. It would be sweet if there was an option to actually do this automagically whenever there was a multi-file torrent with only one file selected - i.e., given that case automatically do a remove-top-level folder, give the proper display name, and delete unwanted files after download completed.

(There are probably other options that may affect this behavior if only I knew ... so, I run with:

* checked - auto rename torrent data if files in path look different
* checked - enforce exclusive file write access locking across torrents (when would you want this unchecked, anyway? sounds dangerous?)

**Comment by parg** [comment]
I'm not ignoring this, just been doing some other easier stuff :) 

For your point (1) there is already an option to avoid name clashes - Options->Files: Also add a unique prefix blah blah

**Comment by parg** [comment]
For point (2) I have changed it so that if at the time you select the 'remove top level folder' you have only a single file left for downloading then that will be used as the download name. Note that if you remove the top level and then deselect files then this won't trigger work so order is important...

**Comment by parg** [comment]
For (3) there is the issue that if the download is still loaded into BiglyBT then deletion of the files you don't want will result in the download going into an error state as it is unable to continue seeding (as it is no longer complete, it is missing those annoying partial pieces). That's why it is ok to do it when removing from BiglyBT but not otherwise.
