### ISSUE TITLE
(android) can't delete a file if i download a torrent with multiple files

### ISSUE THREAD

**Issue by legacychimera247** [BiglySoftware/BiglyBT#1921]
Hello, well the title says it all, but here are the steps to reproduce

1 open a torrent with multiple files in it (say 10)
2 download only file 2 of 10
3 after it finishes, delete it, set file 2 to not wanted and set file 3 to wanted, then delete file 2
4 see biglybt downloading file 2 and 3 and file 2 being recreated, and this is endless

any hint to solve it?

**Comment by TuxPaper** [comment]
Are File 2 and File 3 sharing the same torrent piece?  Check the size of file 2, it should be quite small if it's a partial piece.  You can set these "partial files" to be stored in a subfolder in config (as well as change the extension if you wish).

here's an old uTorrent forum post talking about partial files.  I'm sure there's better but it was one of the first results from google search.  https://forum.utorrent.com/topic/51547-multi-file-torrents-and-cross-file-pieces/

**Comment by legacychimera247** [comment]
Don't know honestly but i'll check, as long as the partial piece is not using too much space i think it's ok...

**Comment by legacychimera247** [comment]
So, tried and downloaded only files let's say 15, 16 and 19. Biglybt also downloaded automatically file 20 and couldn't stop any of the files because all of those were resuming automatically just a second after i stopped them

I think that's definitely a bug here, and considering this is not a chunk but the entire file, is not for the torrent chunk question you linked me...

**Comment by TuxPaper** [comment]
Thanks for persevering.  I think I found the bug, or at least **A** bug :)

**Comment by legacychimera247** [comment]
Oh good, will be happy to test a probable fix

**Comment by legacychimera247** [comment]
well i'm sorry to say that the bug is back/still present

started downloading a torrent and then just set some of the files not to be downloaded, they were starting the moment right away i exited the menu...
