### ISSUE TITLE
Crash after cancelling video player download

### ISSUE THREAD

**Issue by brazenvoid** [BiglySoftware/BiglyBT#1922]
So, this happened just after I deleted 3 torrents, and accidentally pressed enter on a video torrent, thus opening the video player download dialog which I almost immediately tried to close. BiglyBT then crashed and on the next launch, downloaded and installed the player regardless.

* Windows 10 20H2
* BiglyBT v2.6

Logs: [save.zip](https://github.com/BiglySoftware/BiglyBT/files/5732636/save.zip)

**Comment by parg** [comment]
Nothing of use in the logs unfortunately :( 

If you uninstall the plugin (Tools->Plugins->Uninstallation Wizard) can you reproduce the crash?

**Comment by brazenvoid** [comment]
After uninstalling the plugin, it still behaves as if it exists. And instead gives me another kind of installation dialog for additional component for the media player. Which just reinstalls the plugin. So, I cannot recreate a similar scenario now.
