### ISSUE TITLE
Movie files DL w/audio but no video

### ISSUE THREAD

**Issue by carvermon** [BiglySoftware/BiglyBT#1925]
Howdy,
Over the last couple of months, several movie files have downloaded with audio but no video. Based on torrent comments, others seem to have successfully downloaded these files. This has happened to maybe 10/20% of recent downloads (but never before this current issue). Any ideas as to what might be causing this?

Thanks!

Mac OS 10.11.6
Bigly 2.6.0.1_B02

**Comment by parg** [comment]
BiglyBT has nothing to do with the content you download so we can't help with specific issues.

If your media player can't play a file correctly then check it is up-to-date or perhaps try an alternative player?

**Comment by carvermon** [comment]
Thank you for the response, parg. 
I get the same no video result whether playing in the BiglyBT player, iTunes or QuickTime. It has been an only occasional issue, so guess I'll live with it till it goes away!

Holiday cheer for you and yours!

**Comment by parg** [comment]
You too!

**Comment by carvermon** [comment]
It's starting to look like my issue is with files coded in H265 (no problems with H264). Not sure if there is anything i can do to remedy it. Hmm.

**Comment by parg** [comment]
Either the encoding is borked (no audio track) or your player can't handle it. Either way it isn't anything to do with BiglyBT. Try VLC?

**Comment by carvermon** [comment]
Yeah - I failed to mention here that I found they WILL play properly in VLC. Unfortunately for me I use iTunes (an older version at that) to send video to AppleTV. Surprised they won't play in the Bigly player though. Oh well.

Thanks again!

**Comment by parg** [comment]
BiglyBT player recommends setting it up to use embedded VLC rather than the ancient mplayer it comes with...
