### ISSUE TITLE
Mldht plugin can't connect to router.silotis.us

### ISSUE THREAD

**Issue by kotenok2000** [BiglySoftware/BiglyBT#1926]
Java 1.8.0_271 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_271

SWT v4930r7, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.6.0.1_B02/4 az3

Nslookup output is this.
C:\Users\frolo>nslookup router.silotis.us
╤хЁтхЁ:  UnKnown
Address:  fe80::1

╚ь :     router.silotis.us
Address:  2001:19f0:5:6d01:5400:2ff:feec:644a

C:\Users\frolo>nslookup google.com
╤хЁтхЁ:  UnKnown
Address:  fe80::1

Не заслуживающий доверия ответ:
╚ь :     google.com
Addresses:  2a00:1450:4010:c05::71
          2a00:1450:4010:c05::66
          2a00:1450:4010:c05::8a
          2a00:1450:4010:c05::8b
          209.85.233.100
          209.85.233.139
          209.85.233.113
          209.85.233.102
          209.85.233.101
          209.85.233.138
[mldhtlog.txt](https://github.com/BiglySoftware/BiglyBT/files/5737181/mldhtlog.txt)

**Comment by ValeZAA** [comment]
There is no A record. Only AAAA record. It is ipv6 only, as AAAA contains ipv6. If you PC cannot handle ipv6 only, update your pc and network. My MTS and MGTS providers support ipv6 only. This site has ipv6 only. https://ipv6.test-ipv6.com/
