### ISSUE TITLE
❓ Can i make a tag `block torrent deletion`

### ISSUE THREAD

**Issue by TheBestPessimist** [BiglySoftware/BiglyBT#1929]
I want to have some torrents which can never be deleted from BBT. I thought i could do it via tags, but i didn't find anything which seemed useful.

What I want to achieve is: as long as a torrent has this particular tab, it will never be deleted: either manually, or automatically. In order to delete said torrent, I will have to untag it first.

Is there a way to achieve this?

**Comment by parg** [comment]
You can't do it but I could add a way to do so

**Comment by NaPurHab** [comment]
My suggestion is to check all your tags, and make sure they are not set to Delete when you reach a given Ratio.   Then setup 1 new tag, mine is `Trash 10:1`, and set that to delete when a ratio is met.

I think your original question is more placing a lock on the Torrent so you can't delete it. Best suggestion make a `Keep Seeding` Tag and make sure the torrents you want to not delete have Only that Tag.

**Comment by TheBestPessimist** [comment]
> Best suggestion make a `Keep Seeding` Tag and make sure [...]

I already have tagged those important torrents.

The thing is I want to protect me of myself. I want to block accidental manual deletions (as well as automatic ones).

**Comment by parg** [comment]
Beta B04 has a new Tag option to prevent download removal

**Comment by TheBestPessimist** [comment]
Can confirm it works at least for manual deletion attempts. Haven't tried automatic yet.

Thank you parg!

**Comment by NaPurHab** [comment]
> The thing is I want to protect me of myself. I want to block accidental manual deletions (as well as automatic ones).
The new `Prevent download removal from BiglyBT when tagged' option will only protect you in BiglyBT. You can still delete, move (break the link to the torrent), etc in the O/S.

Nothing BiglyBT can do, can ever fully protect you from yourself.

**Comment by NaPurHab** [comment]
@parg What happens when the new Option coming into conflict with the `When exceeded` option on share ratios? i.e. the `Delete from Computer` option.

**Comment by parg** [comment]
with great power comes great responsibility

**Comment by NaPurHab** [comment]
Personally, I think the new option is not needed. Clicking Delete brings up a dialog where you can Cancel, Remove from Disk, or Remove from Library.   It is already 2 steps to delete a Torrent.

**Comment by TheBestPessimist** [comment]
closing as solved. Thank you parg!
