### ISSUE TITLE
[support] A wild tag for each torrent client suddenly appeared

### ISSUE THREAD

**Issue by TheBestPessimist** [BiglySoftware/BiglyBT#1931]
Please help me:

I have enabled something, and now i have a lot of tags: one for each torrent client I'm communicating with. 

Is there a way to hide those tags, as this pollutes my tags view?

![image](https://user-images.githubusercontent.com/4482210/103157871-47461400-47c0-11eb-9de3-ea6598ed821d.png)

**Comment by parg** [comment]
Tools->Speed Limits->Schedule and Settings...

Delete the line that says

    peer_set Auto=all,client=auto

**Comment by TheBestPessimist** [comment]
Can you please tell me how did i enable that one?

**Comment by parg** [comment]
Right-click in a Peers View subtab and select

    Auto-categorize peers into Peer Sets

**Comment by TheBestPessimist** [comment]
Thank you for the help. got it.
