### ISSUE TITLE
Can't ready popup messages

### ISSUE THREAD

**Issue by RegProctor** [BiglySoftware/BiglyBT#1932]
The reason is simple, I have a dark theme installed on my OS so the background of the panel for the messages is a dark grey. The text is black and that is very hard to see, particularly on an angle as is the case with my setup. It would be nice of the text color of popup messages was settable, I have already checked the options for a dark theme under color but the settings don't affect this component.

Funny enough, I can read the message below the message that says "Auto-closing in ..." as the lettering of that is white.

* OS OpenSUSE Leap 5.1 with KDE 5
* BiglyBT 2.6.0.0

**Comment by parg** [comment]
Hmm, when I apply a dark theme to Kubuntu the BiglyBT UI doesn't respond to the theme change - the UI library we use (SWT) has direct support on OSX but I'm not sure of the state of play on Linux.

I guess I could get a VM with your setup running and try and reproduce it.

**Comment by parg** [comment]
I take that back, I rebooted and it has picked up the theme change.

**Comment by parg** [comment]
Next beta (B06) will contain some fixes but you have to enable the 'misc other dark things' option to enable them.

Unfortunately there are a lot of places in the BiglyBT UI where explicit colors are used (for text foreground/background, icon design etc) which messes up theme changes. I don't really want to go on a mamoth search for these things but I'm happy to fix up things that cause serious issues

**Comment by RegProctor** [comment]
>Unfortunately there are a lot of places in the BiglyBT UI where explicit colors ...

That's usually the way it is, I'll try the  `misc other dark things` and let you know how it goes.
