### ISSUE TITLE
Portable vmoption doesn't work with UserData config path vmoption

### ISSUE THREAD

**Issue by TheBestPessimist** [BiglySoftware/BiglyBT#1934]
I want to run BBT portable.

I copied BBT into `C:/all/BiglyBT`.

And i used these lines inside `BiglyBT.exe.vmoptions`:

```
-Dazureus.portable.enable=true

-Dazureus.config.path=UserData

-include-options UserData/java.vmoptions
```

However, in this case, the user data (which is normally in appdata) is set to `C:/all/BiglyBT` instead of the expected `C:/all/BiglyBT/UserData`:
![image](https://user-images.githubusercontent.com/4482210/103198846-03ebc280-48f2-11eb-9c25-7972a2690cec.png)

If i remove `-Dazureus.portable.enable=true`, then BBT uses the correct path, as expected:
![image](https://user-images.githubusercontent.com/4482210/103199034-8d9b9000-48f2-11eb-815c-34c0461f5563.png)

Is there a bug regarding these 2 flags? Are we not allowed to use them together because of _reasons_?

**Comment by parg** [comment]
Portable support is very basic, I wouldn't use it. 

It was only ever really designed for a very limited case of BiglyBT being installed on a USB drive along with a single data directory and allows the drive letter to change without screwing things up. It overrides 'azureus.config.path' as you have discovered.

Why do you want a portable mode?

**Comment by TheBestPessimist** [comment]
> Why do you want a portable mode?

It happens that i change systems/locations a lot, so having as much of my apps portable as possible helps.
