### ISSUE TITLE
2 Q's: Releases section jar file & Windows installer uTorrent transfer plugin

### ISSUE THREAD

**Issue by lucknaumann** [BiglySoftware/BiglyBT#1935]
Hi. I hope you are well.

I am wondering about the jar file in the Releases section. Is this is a multi-platform jar file, essentially portable, where it will create whatever files are needed? 

I am on Windows 10 v2009. Your main page states that the Windows installer includes a uTorrent transfer plug-in. I am wondering if this is still the case and how well it works as it appears it was created and then abandoned. 

I should note that I prefer portable versions of programs and while I did come across a post regarding making BiglyBT portable, it seems like a hassle, especially upgrading.

**Comment by parg** [comment]
Hi,
The github release .jar file is just the same one that is included in the installers, it doesn't have any portability magic in it. As you note, BiglyBT doesn't have a proper portable installation as there are quite a lot of places where internally absolute file locations are used. You can arrange for the configuration data itself to be stored where you want (as opposed to in %appdata%\BiglyBT on Windows for example).

The uTorrent transfer plugin hasn't been abandoned, it is pretty functional.

Hope that helps!

**Comment by lucknaumann** [comment]
Hi, @parg. Thanks for the reply and explanations. Yes, that definitely does help! 😄 

> ...it doesn't have any portability magic in it. 😆
