### ISSUE TITLE
Magnet link hangs on metadata 

### ISSUE THREAD

**Issue by torrentdude** [BiglySoftware/BiglyBT#1938]
I’m running OS X Big Sur. Recently switched to Biglybt because Vuse stopped working. All downloads started with biglybt just hang and never start. I’ve updated from 2.5 to 2.6.0.0 but still have the same problem

**Comment by Havokdan** [comment]
https://wiki.vuze.com/w/Torrent_health maybe?

**Comment by torrentdude** [comment]
Thank you for your reply.

That wasn’t it. I can download the biglybt update and it shares fine.

I let biglybt copy the vuze settings during install.

The torrent is public so a passkey isn’t the problem.

The data isn’t missing and I’ve checked that the file location is correct.

I’m not using cryptoport or a proxy.


Everything was working well in OS X Catalina using Vuze. Upgrading to Big
Sur is when the problem arose where Vuze stopped working so I installed
Biglybt.

Thank you for your help. I’m open to looking at anything necessary to
resolve this issue.

**Comment by torrentdude** [comment]
I’ve also updated Java after upgrading to Big Sur and just uninstalled and reinstalled Java just to make sure it wasn’t a problem.

**Comment by Apocalypse612** [comment]
Same magnets issue after updating to the latest stable build. This issue happened for me last time, and the only reason I updated again was that the patch notes said they fixed Magnet issues. Argh, kinda regret it. Gonna uninstall and reinstall again and hopefully, this will resolve my issue again like it did the last time this happened.
