### ISSUE TITLE
add queue limits for tags and categories

### ISSUE THREAD

**Issue by Dramaman** [BiglySoftware/BiglyBT#1939]
the ability to limit active torrents (seed/leech) based on their tag would be great 
I know that can be done with scripts, but having that in that interface would be great.

**Comment by parg** [comment]
Easy to say, not so easy to implement :)

The whole queueing system is based around calculating overall priorities and then applying scheduling to downloads based on priorities and rules (e.g. minimum seeding time, ignore rules). If you try and simply throw in, say, 'max active on Tag X is 3' and X already has 3 active when the rules say 'start torrent T' which is assigned to X what happens? Do we queue an existing torrent S on X to 'make space', potentially violating the rules for S or do we ignore T and move onto a lower priority torrent? What if a torrent is assigned to multiple tags with different limits?

Currently you would need to arrange for things to occur using 'stop' and 'force start', or the Tag 'first priority' setting, as these cause a download to be excluded from, or interfere with, the scheduling system. Not ideal.

Perhaps there is some way ahead if your requirements are limited - can you describe what the minimum is you want to achieve?

**Comment by Dramaman** [comment]
Thanks, to be honest I was thinking more or less for downloading than for seeding (apologies). So maybe instead just focus on downloading. Basically just thinking of scenarios when you have long-term, or large downloads   that you wanted running, but not all the same time, while having your smaller downloads execute parallelly. Hopefully this would be a layer on top of the existing rules.

Perhaps a special queue tag that doesn't allow multiple tagging? (which is more work than I was hoping for) You're right it doesn't seem as easy as if you can multi tag an item. .

**Comment by parg** [comment]
Beta 2601_B11 has a new Tag setting (See TagsOverview view) for the tag's maximum simultaneous downloads. It should work even if a download is assigned to multiple tags with limits.

Please test!

**Comment by Dramaman** [comment]
Sorry, new to GitHub, where can I find this beta?

**Comment by Dramaman** [comment]
Ok, will do

**Comment by parg** [comment]
The Help menu in BiglyBT has a 'join the beta program' option - once you join this you should be updated to the latest beta release. 

Betas releases aren't published on Github,

**Comment by Dramaman** [comment]
Works great so far. Thanks.
