### ISSUE TITLE
Can BiglyBT add trackers to new torrents automatically?

### ISSUE THREAD

**Issue by EricLucife** [BiglySoftware/BiglyBT#1940]
OS:Windows 10 LTSB
Version:v2.6.0.0

I haven't find this function.

**Comment by parg** [comment]
See https://github.com/BiglySoftware/BiglyBT/wiki/Tags#Examples

At the end of the 'add trackers' example note:

    If you wanted to automatically do this for all torrents then set the constraint for the 'AddedTrackers' Tag to 'true' to ensure that all torrents are assigned to it

**Comment by parg** [comment]
If you only want to do it for new torrents then set the Tag Constraint's "scope" to 'new downloads"

**Comment by DumbJoe** [comment]
Wait, you can have a universal tracker list and then have BBT append that list automatically to any newly added torrents?

**Comment by parg** [comment]
If you configured it with a GUI version and then switched to Console/WebUI then yes (via a Tracker Template and a Tag)

https://github.com/BiglySoftware/BiglyBT/wiki/Tracker-Templates-and-Lists

https://github.com/BiglySoftware/BiglyBT/wiki/Tags#tracker-templates
