### ISSUE TITLE
Torrent details tabs don't always disappear from  left pane -> My Torrents  after torrents removed

### ISSUE THREAD

**Issue by rwperrott** [BiglySoftware/BiglyBT#1942]
Torrent details tab(s) can be left with a blank title
* Mint LDME4 (Debian)
* BiglyBT V2.6.0.0
* For *nix: Mate

**Comment by parg** [comment]
Is this when you actually remove the download or is it on a restart when you notice that there are blank entries there? I've seen an issue on restart where an attempt is made to re-open the view for a removed download for some reason.

**Comment by rwperrott** [comment]
After I've removed completed torrents, while the program is still running.

**Comment by parg** [comment]
Every time? Are you using the sidebar view or the classic view in BiglyBT?

**Comment by rwperrott** [comment]
Not every time, so I was surprised when it occurred, and using the sidebar view.

**Comment by parg** [comment]
Managed to reproduce it - it occurs when you have a details view open, restart BiglyBT and then delete the download (doesn't happen if you open the view + delete the download without restarting)

Fixed in next beta - thanks!

**Comment by rwperrott** [comment]
I found it faster switching to using torrent advanced network menu switch items a lot more, so doubt that I will open enough detail views to confirm that this was fixed.
