### ISSUE TITLE
Remaining Stats Messed Up And Full Recheck Always When Files Set To Delete

### ISSUE THREAD

**Issue by brazenvoid** [BiglySoftware/BiglyBT#1943]
**STR:**
1. Have an incomplete torrent with many files and folders. I don't know whether it matters but all those files must be big ~50MB to 3GB
2. Set it to Sequential Download
3. Have the column remaining displayed 
4. Mark only few files out of the many as Normal priority, all else as Delete.
5. Completely download some of those files.

**Case 1**

1. While it is downloading, mark some completed files as Delete, do it repetitively. 
2. All the files you mark with delete will deduct their size from remaining size value.
2. BiglyBT will work for the first 1-3 sets but then collapse into a full recheck.
3. This recheck can also trigger if you set some Delete files to Normal but it is rarer.

**Case 2**

1. Stop the torrent and do the same.
2. I have even seen the remaining column to go to some undefined value which cannot be displayed. Progress bar fills up completely too.
3. Regardless, BiglyBT will do a full recheck when you resume.

I was ignoring these issues but now I am stuck with a ginormous torrent with thousands of files and this full rechecking has only been a thorn on my side. 

![Screenshot 2021-01-07 090545](https://user-images.githubusercontent.com/8722533/103849831-8bda8500-50c7-11eb-8673-e569ff3c1a50.png)

* OS: Windows 20H2
* BiglyBT v2.6

**Comment by parg** [comment]
Setting files to 'delete' while the torrent causes the torrent to be stopped and restarted - if you do this multiple times in a row then things can get confused.

The reason the torrent has to be stopped is that you are removing availability for other peers and there is no way in the bittorrent protocol to inform peers of this - they have to be disconnected and the easiest way of doing this is to stop+restart the torrent.

Not an excuse for the issue you are seeing but some info for you.

**Comment by brazenvoid** [comment]
I understand. Obviously this pertains to case 1 that is during when the torrent is active. But for me when I do the delete, it does not stop and restart for many iterations. It continues without a hiccup, only at a random iteration that it goes into full recheck.

**Comment by brazenvoid** [comment]
Thanks for the info. I will care to not do that from here onward. I hope you will be able to figure out why the delete is causing the wrong remaining size and progress stats leading to the recheck. I am willing to test the beta.

**Comment by parg** [comment]
Beta B12 has quite a lot of rework in this area - it is quite complex code so I might have screwed things up. Please test if you get a chance!

**Comment by brazenvoid** [comment]
Well it is partially fixed I guess. 

- Recheck does not happen but the remaining size and progress bar still are affected when completed downloaded files are set to delete. 
- The size of the files set to delete are essentially deducted from their values. 
- After the round of allocation completes when the torrent is started, they revert back to correct values.

**Comment by parg** [comment]
I only worked on the recheck aspect of things - I didn't observe the issue with the 'remaining' column although I wasn't really looking at that - I'll investigate things a bit more

**Comment by brazenvoid** [comment]
Can you tell me what is this allocating phase for? 

It happens after I resume the torrent after deleting files. Obviously there is nothing to allocate on disk considering we have only deleted files.

**Comment by parg** [comment]
A torrent always goes through an 'allocation' phase, even if it doesn't actually allocate any new files.

**Comment by brazenvoid** [comment]
The fix provided in B13 seems to be a workaround and not really a fix as the values do still change and then change back after a second. :)

**Comment by brazenvoid** [comment]
Also this version did not handle the deletion of a torrent with thousands of files in a good way; the IO wait state sent it to an unresponsive state.
