### ISSUE TITLE
Files Treeview Issues

### ISSUE THREAD

**Issue by brazenvoid** [BiglySoftware/BiglyBT#1945]
**To be clear I am talking about the added torrents' files tree view.**

The tree view though very useful is also frustrating. Please give attention to its issues:

1. The tree view opens with all nested lists expanded which is a bad way to browse a torrent with complex structure. 
2. There should be collapse all and expand all, functionality somewhere. 
3. The tree view's check boxes for nested list items, do not work unless I first click on the item and then again on the checkbox
4. While selecting files in a folder, if by mistake one also selects the following nested item, further selection or deselection causes unintended behavior. Selecting next one does not work while deselection causes deselection to start from the first selected item.
5. Whenever I minimize/maximize the app, the tree view is regenerated anew, resetting the selection, scroll etc.

* Windows 20H2
* BiglyBT v2.6b12

**Comment by parg** [comment]
1. See 2
2. Right-click and select collapse-all

**Comment by brazenvoid** [comment]
Point 4 is a problem when selecting with the keyboard.

**Comment by parg** [comment]
3. For me (Win20H2) I don't have to select the row first, clicking into the checkbox works as expected

**Comment by parg** [comment]
4. Can't reproduce any issues here, I must be missing something?
5. Yup, the view is freed when invisible to save memory

**Comment by brazenvoid** [comment]
4. It is pretty easy to reproduce. Just start selecting a folders files with shift arrow down and go till you select the next folder's name (parent's next sibling).

**Comment by brazenvoid** [comment]
5. Is the memory consumption really so high that it can't be freed until user actually deselects the torrent?

**Comment by parg** [comment]
4. Should have mentioned that you were using arrow keys earlier...

**Comment by parg** [comment]
5. If you configure BiglyBT to minimize to taskbar (as opposed to system tray) then the state isn't lost

**Comment by parg** [comment]
actually, I take that back - the state is retained as long as the FileView tab remains visible - if you switch to another view and then back it is reset

**Comment by parg** [comment]
B13 has a few fixes!

**Comment by brazenvoid** [comment]
The fixes provided are working. 

Are you working on something to possibly retain the tree view? Or not so I may close the issue.
