### ISSUE TITLE
Disk Operations still slow.

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#1949]
We still have the issue of Move/Copy/Allocate occurring at the same time.  In the example below I am moving 5 Torrents to Drive M:, and I have added 2 torrents that are also going to drive M:.   Drive M: is an external WD Easystore 14TB drive. Long sustained writes to the same drive are slower than doing them in FIFO order.   Please adjust this so that all Move/Copy/Allocate are sequential.  Oh and an Order Column would be useful. And on the Progress Meter, could the text be Black? The Gray on Green is hard on my old eyes.

![image](https://user-images.githubusercontent.com/37715552/104229299-17327e00-541a-11eb-83ac-f63926b52907.png)
Here is the same snip of the screen after 10 minutes. Note how little progress has occured.
![image](https://user-images.githubusercontent.com/37715552/104229522-62e52780-541a-11eb-98cb-abc97fb3d1ea.png)

Java 1.8.0_271 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_271

SWT v4930r7, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.6.0.1_B12/4 az3

**Comment by NaPurHab** [comment]
I see the new option in B17 `Limit active major disk operations (allocation, check, move...) to one per file system`. Will have to wait till the next time I have Moves and Allocates at the same time, should be soon.

**Comment by NaPurHab** [comment]
![image](https://user-images.githubusercontent.com/37715552/104854652-f6649f80-58d5-11eb-8993-468bbd143e6a.png)
![image](https://user-images.githubusercontent.com/37715552/104854662-067c7f00-58d6-11eb-84f1-3c374332a61b.png)

As you can see, the new option helps for DL Speed, but ULs are traffic jam, barely moving. Also, I have 2 new Magnets that are not moving, I don't think they count as Major Operations. They are just 64mb, only after they setup for Allocation would they be Major. Metadata should continue through to the Open Torrent Dialog and allow setup of the torrent. Then when it goes to Allocate it would 
![image](https://user-images.githubusercontent.com/37715552/104855338-2d3cb480-58da-11eb-8a5b-3a67d2d1b3b5.png)


Here is what my performance looks like:
![image](https://user-images.githubusercontent.com/37715552/104854881-3aa46f80-58d7-11eb-9fc4-8f598f235ff9.png)

Finally, can we replace the Progress Graphic with the TEXT method use in other places. Examples:
Moving ##.#%
Copying ##.#%
Allocating ##.#%
this would be easier to read. I can't read the gray numbers on the Green background. Low contrast and too small. Even with a magnifying glass it is difficult.  Or you could place the % Text in the Status field, which is currently empty during these operations.

**Comment by parg** [comment]
I'll remove metadata downloads from the allocation restrictions and add a new 'percentage' column or something

**Comment by NaPurHab** [comment]
Thanks, though I noticed that once an item in Disk Operations starts, the Status Field is Empty. You could put the Text based % in that empty space and not need a new column.  Only other new column for Disk Operations would be an Order Column. So they would be in Order of Operation. Or perhaps lock it that Order, so it is FIFO.

**Comment by NaPurHab** [comment]
![image](https://user-images.githubusercontent.com/37715552/104963993-9ccda500-59a9-11eb-93bf-658d84902729.png)
![image](https://user-images.githubusercontent.com/37715552/104964063-ba9b0a00-59a9-11eb-8e7b-5d9268e4e0aa.png)
As you can see above, the Text % could fit in the Type Field. But the Status is Empty in the currently active Disk Operation. So, would be easy to add there without the need for a new column.
