### ISSUE TITLE
Option to disable clearnet traffic

### ISSUE THREAD

**Issue by gh338** [BiglySoftware/BiglyBT#1951]
* Ubuntu 20.04
* BiglyBT 2.6.0.1 B14
* KDE

Could we have an option to disable clearnet ( internet ipv4 ) traffic including broadcast, upnp etc ?
Currently one needs to configure the firewall to prevent BBT to mix up networks.
It would make it easier for beginners to avoid leaking information across TOR/I2P

Thanks

**Comment by parg** [comment]
There are too many possibilities here - if you're that worried then the firewall is the correct approach to take.

**Comment by gh338** [comment]
ok
