### ISSUE TITLE
Pop up notifications too small, unreadable

### ISSUE THREAD

**Issue by Bearbque** [BiglySoftware/BiglyBT#1953]
Whenever I get a pop up message, the pop up window is too small for the content and can't be resized. Here's an example. I had to copy and paste the text into word document to read it. This has been happening for a long time.

![image](https://user-images.githubusercontent.com/77520108/104795151-0d35b580-5761-11eb-9f41-9e7891273b4b.png)

[debug.zip](https://github.com/BiglySoftware/BiglyBT/files/5823713/debug.zip)

**Comment by parg** [comment]
I'll make the window resizeable - obviously not an ideal solution but better than nothing
