### ISSUE TITLE
Check for Updates Failed.

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#1957]
![image](https://user-images.githubusercontent.com/37715552/104852943-8fda8400-58cb-11eb-8f53-725815063971.png)

This Issue has been happening on/off since **2.6.0.1_B04**. Neither Check Updates, or auto update are working. I have had to manually install all the Betas since B11. At a couple times, I was 2-3 betas behind.  When I manually DL from `BiglyBT: Updates: Core[R]`, It opens in the Open Torrent Dialog. Sometimes when I open Magnets from other sites, they include additional TAGS (like I2P).  Would it be possible to have it add a TAG that BBT sees as an Update to automate install. Or perhaps that anything posted to the various Chat Channels for BBT Updates, Plugins, SWT, etc.   could become the update method. New post, download, install

I'm getting tired of doing it manually.
Now off to manually install B17.

Java 1.8.0_271 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_271

SWT v4930r7, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
**B2.6.0.1_B16/4 az3**

**Comment by NaPurHab** [comment]
Still happening in B20. Can't find the update, even though the Chat Channel shows it.

Would be nice if in the chat channel, when I right click, I had the additional option to treat it as an update. Or perhaps the check updates could use the updates chat channels as the source for the check. Since I can see the updates in the channels.

![image](https://user-images.githubusercontent.com/37715552/105613782-ccf2ba80-5d92-11eb-9d2d-a2e104a2636a.png)

**Comment by gudol** [comment]
I have a similar problem, when I check for updates I get following message:

" Check For Updates Failed

The following errors were reported:

BiglyBT Core, Failed to check for core update, Tor helper plugin failed or not available

Platform-specific support, Failed to load plugin details for the platform manager, Plugin list load failed, Tor helper plugin failed or not available

Non-mandatory plugins, Failed to load plugin details, Plugin list load failed, Tor helper plugin failed or not available

Mandatory plugins, Failed to load plugin details, Plugin list load failed, Tor helper plugin failed or not available "

Tor helper plugin and Tor browser plugin are installed and working fine.
I checked the associated protocols, no errors.
