### ISSUE TITLE
Feature Enhancement Request: Make number of chat windows that open on status dbl-click configurable

### ISSUE THREAD

**Issue by DonnyDDEV** [BiglySoftware/BiglyBT#1959]
With BBT 2.6.0 there was a limitation added to only popup 3 chat windows at a time, at most, when you double click on the active message icon in the status bar. This request would be to make that number configurable, 0 .. N, where 0 indicates unlimited windows, and N max number of windows at a time that will open with each double click of the message icon. 

Thank you very much for your consideration.

-donny

**Comment by parg** [comment]
It is 10 in beta rather than 3
