### ISSUE TITLE
PC Crashed but still need to share.

### ISSUE THREAD

**Issue by Flyeboy7** [BiglySoftware/BiglyBT#1961]
Hi,

My PC crashed but I have the backup of all the .torrent files and all files I shared. How do I make BiglyBT add the files to my library again so they are searchable and downloadable by others again.

Regards
Gregg

Windows10
About 2.6.0.0

**Comment by NaPurHab** [comment]
If you had the Backup set to save to another drive. You could reinstall, set the backup to point to the correct backup path. Then Restore the last backup. That should get you close to where you were.

![image](https://user-images.githubusercontent.com/37715552/104964891-6abd4280-59ab-11eb-918f-7957dcd292ae.png)

**Comment by Flyeboy7** [comment]
SHerbit no I lost that. Its fine I will have to start from scratch. Because I have tons of music etc I shared and Videos. One needed that for Torrentday to get points or they kick you out and you cant download. Now I have downloaded only a few files. I will let them run and yes it will take months to get points again but I will get there again thanks. 

I just thought I could add to library again.

**Comment by parg** [comment]
Generally any "points" or "share ratio" earned with a tracker are stored by the tracker, NOT the torrent client, so resetting a PC etc shouldn't cause you any loss.

Clients have a local view of share ratio based on total up/down but the trackers are only told about how much has been uploaded/downloaded in a session.
