### ISSUE TITLE
Moving torrents in order queue ("incomplete" pane) by drag or by reposition menu sometimes reverses them

### ISSUE THREAD

**Issue by david-bakin** [BiglySoftware/BiglyBT#1965]
[Windows Server 2016 Datacenter, been going on forever but just noticed it on 2.6.0.1_B19 and as long as I was submitting another issue I thought I'd mention it.]

Starting with incomplete pane sorted by increasing "Order" select several sequential torrents from the end of the list (max order#) and drag them way up the list.  Sometimes - just sometimes - the order of the moved torrents reverses and what was the last of the group becomes the first, etc.

Also happens - sometimes! - with the Organize/Reposition menu.

I think - maybe only 33.3% certainty - that it has to do with

1. torrents selected are at the _end_ of the last (max order #1208 
2. (maybe! just maybe!) you select the group by first selecting the last one (max order #) and then ctrl-click on the lower-order-# end of the group.

What I expect:  torrents stay in their relative order when moved.

**Comment by parg** [comment]
Are you sure you selected the group of torrents in consecutive order? If you ctrl+click to add torrents to a selection, or shift-select from bottom to top, the order is remembered and applied when moved.

For example, say I have 10 torrents, I click on the 8th and then shift+click on the 6th to select three torrents and then drag that group below the 3rd one you will end up with the 8th one in position 4, 7th on in position 5 and 6th one in position 6.
