### ISSUE TITLE
BIGLY appears to redirect some web access to Delhi, India

### ISSUE THREAD

**Issue by paulgillingwater** [BiglySoftware/BiglyBT#1969]
* OS and version: macOS Catalina 10.15.7
* BiglyBT Version Number: 2.6.0.0
* For *nix: Desktop Environment
Java 1.8.0_261 (64 bit) Oracle Corporation
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home

SWT v4936r26, cocoa, zoom=100, dpi=72
Mac OS X v10.15.7, x86_64 (64 bit)
B2.6.0.0/4 az3

![Screen Shot 2021-01-23 at 5 15 22 PM](https://user-images.githubusercontent.com/45693566/105609310-52c93280-5da0-11eb-8bc8-649562c7792f.png)

How to reproduce: Run BIGLY then access Facebook Settings/Security & login/Where you're logged in.

As per screen shot, Facebook shows login is coming from Delhi, India even though I am based in the UK.  My IP address is unchanged, and the same thing occurs when using a VPN or not.

When I deactivate BIGLY, Facebook shows login from London as expected.

Conclusion: an illicit payload appears to redirect FB traffic to India when BIGLY is running.

**Comment by parg** [comment]
An "illicit payload" that redirects FB traffic - please explain more, this is fascinating.

**Comment by paulgillingwater** [comment]
I carried out more testing, and now believe this is not a problem with BiglyBT.  I switched to using Safari rather than Chrome, and the problem disappeared.  I now suspect there was a Chrome plugin that was compromised.
