### ISSUE TITLE
changing directory all my existing .torrent and data files/folders are in

### ISSUE THREAD

**Issue by coyote3** [BiglySoftware/BiglyBT#197]
I know that when I installed BiglyBT I selected my (identical) directory for all my BiglyBT .torrent and data files/folders (I like them in the same directory) at:

Options|Files|Torrents|Save Directory
Options|Files|Default directory

I'd like to change the directory.  But when I tried that BiglyBT couldn't find any of the moved files despite my changing those settings fields.

Selecting row(s) then Right-click|Advanced|Move torrent file didn't achieve my goal.

Is there a way to do what I want without removing/re-loading all my (about 700) torrents?

**Comment by parg** [comment]
So you want to move both your .torrent and data files? Changing those settings affects newly added downloads, not existing ones.

There is an option to move the data files in the right-click menu under Content (make sure you are running the latest beta if you use this as there was a performance issues with moving files in 1.2.0.0).

Make sure you backup your config before messing too much,

An alternative approach would be to close BiglyBT, manually move the files, then use the 'find existing files' option to match them back up. Unfortunately this will result in them all being rehashed so I'm not sure it is advisable for 700....

**Comment by coyote3** [comment]
First, thank you very much parg for all you have done over the years, and for this reply!

Yes, I want to move .torrent and data files.  (And yes, when I messed it up previously I was thankful I had a fresh backup...but all 700 torrents needed to be rechecked.)

Ah, I didn't see "option to move the data files in the right-click menu under Content"!  

Is there no way to move my existing .torrent files?

**Comment by parg** [comment]
Thanks :)

The 'move torrent file' you tried before should work - I jut tested with 3 torrents and it seemed to do the expected - what went wrong?

**Comment by parg** [comment]
I'm going to move the 'Move Torrent File...' option under 'Trackers/Torrents' - dunno why it isn't there already

**Comment by coyote3** [comment]
Perfect, thank you very much parg!

Maybe what "went wrong" previously was that  I _manually_ moved the files, I dunno.  

I'll report on how it goes.  With using the option to move data files next time.
