### ISSUE TITLE
Missing port.

### ISSUE THREAD

**Issue by NiggaInTheNight** [BiglySoftware/BiglyBT#1970]
Hi. I have a problem with a torrent tracker RuTracker.org. When BiglyBT tries to update peer list from tracker it got error Missing Port. I tries to ask administration, but as i understand this problem only with BiglyBT and i didnt take solution to fix it. Is that message sended by server or its internal BiglyBT error? What port? Where? Port of what? List of sources of peers have correct address, editing with add port didnt work too, proxy didnt help.

Win7
* BiglyBT Version 2.1-2.6

**Comment by parg** [comment]
That would be a message reported by the tracker to BiglyBT. The 'port' number is your incoming listening port - check that you haven't configured yours to be something weird.

Go to Options->Connection and check the 'Incoming TCP listen port'. In general this should be something between 10,000 and 65536

Go to Options->Tracker->Client and make sure you have NOT ticked 'do not announce the listening port to the tracker'

**Comment by NiggaInTheNight** [comment]
Thx for fast response. It works after:
Go to Options->Tracker->Client and make sure you have NOT ticked 'do not announce the listening port to the tracker'

I recommend to add info in translations about it can be problem for take list of peers from tracker.
