### ISSUE TITLE
vpn tunnel errors

### ISSUE THREAD

**Issue by almanteka** [BiglySoftware/BiglyBT#1973]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4930r7, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.6.0.0/4 az3

 i'm getting the following errors after tunneling BiglyBT using a VPN:

ERROR: socket Selector.open() for 'TCP network manager reader' failed 10 times in a row, aborting.
This App / Java is likely being firewalled!

ERROR: socket Selector.open() for 'TCP network manager writer' failed 10 times in a row, aborting.
This App / Java is likely being firewalled!

ERROR: socket Selector.open() for 'TCP Connect/Disconnect Manager' failed 10 times in a row, aborting.
This App / Java is likely being firewalled!

using avast! premium security and surfshark vpn tunnel only for BiglyBT! any ideas or suggestions to try? maybe allowing java ports in avast's firewall? thanks for any info!

**Comment by parg** [comment]
Something is preventing the BiglyBT processs (BiglyBT.exe on windows if you're running it normally) from binding to the incoming listen port.

Normally this happens when your anti-virus software doesn't have an exception for the executable to 'act as a server' so you could check that.

Does it only happen when using the VPN? If so that would add more confusion to the mix.

**Comment by almanteka** [comment]
thanks for your reply! how i can install a fresh copy of BiglyBT to test it out? Using windows add/remove programs? i already made daily backups!

**Comment by parg** [comment]
There's no point in re-installing BiglyBT as it won't change anything - check out your anti-virus software/firewall configuration to see if there are options to allow BiglyBT.exe 'through the firewall' etc

**Comment by almanteka** [comment]
i made an exception to the entire folder, allowed all packets in/out of tcp/udp in the packets rules section of the firewall using the listening port, even allowed all connections to BiglyBT Launcher from the application rules section allowing all connections, all outbound and inbound ports.

**Comment by parg** [comment]
No idea I'm afraid, all these VPN products have their own settings

**Comment by parg** [comment]
Note that if your VPN product does not support incoming connections then the failure for TCP to bind is not much of an issue.

**Comment by almanteka** [comment]
BiglyBT connects to peers, download, upload and seed without any problem. maybe I just need to ignore the little warning triangle.

**Comment by parg** [comment]
If you're happy with the way things are working sometimes that's the best approach!

**Comment by almanteka** [comment]
the only problems i found is that by tunneling thru the vpn it takes 5 minutes to BiglyBT to load and i can't bind it to the vpn network. if i bind it to the vpn, the traffic stops. i know that BigliBT connects thru the tunnel based on the ip it shows using a test torrent, no matter it isn't bind it.

**Comment by almanteka** [comment]
a wrap-up: BiglyBT works perfectly when i'm using the VPN for the entire pc, but there are some local websites that they don't accept vpn connections or ips from another locations. so, my vpn offers a whitelister, there you can select the specific apps you like to use the vpn or to exclude from the vpn. using the option to route thru the vpn, is when BiglyBT throws that errors. i tried utorrent and no errors and green checkmark tunneled thru the vpn, but i moved to BiglyBT almost two years for the additional features! i'm going to continue to test it out another options and keep it posted! already tried a fresh installation with same results!

**Comment by almanteka** [comment]
a question: if i already have java installed, BiglyBT doesn[t install the included version?

**Comment by almanteka** [comment]
ok, the whitelister offers two options: "route via vpn" & "bypass vpn". i was using "route via vpn" with BiglyBT and the errors were constantly, then changed to "bypass vpn", whitelisted only one browser and thunderbird mail & voila!, the errors and problems on BiglyBT disappeared! i think something that BiglyBT uses needs to be in the vpn if "route via vpn" is used! "route via vpn" only force vpn connections to the apps that i select. "bypass vpn" force all apps to use the vpn, except the ones in the whitelist!
