### ISSUE TITLE
BiglyBT cannot bind to UDP ports and cannot use udp trackers.

### ISSUE THREAD

**Issue by vipinjn24** [BiglySoftware/BiglyBT#1975]
* OS and version Windows 10 Pro 20H2
* BiglyBT Version Number 2.6.0.0
* For *nix: Desktop Environment

BiglyBT cannot bind to UDP ports and cannot use UDP trackers.

It says that some program is already using the port, but BiglyBT is the program that is using the port.
And I confirm that only one instance is running at a time, even in task manager we can see only one process in the details tab.

Please see attached screenshot.

![image](https://user-images.githubusercontent.com/1639185/106175224-ded1c480-61bb-11eb-9fd8-7699b617867f.png)

Please see the system information too.
```
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4930r7, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.6.0.0/4 az3
```

**Comment by parg** [comment]
It must be something specific to your setup - I can assure you that UDP trackers work fine for me and all the other Windows users I talk to every day.

Could it be an antivirus program blocking BIglyBT acting 'as a server' ?

**Comment by vipinjn24** [comment]
@parg can antivirus stop an application to bind to udp port?
However the application binding to udp port but still complains for the issue.

Let me disable my firewall and antivirus and check again.

**Comment by vipinjn24** [comment]
ok it did not work with both of em disabled.

let me see if cleaning up all the settings will do the work.

**Comment by vipinjn24** [comment]
That didn't helped either, and after resetting the settings the remote pairing stopped working.
It only works when I restore the settings in biglybt.

**Comment by david-bakin** [comment]
FYI (for future reference to anyone who comes here) to find out who is using what port on Windows use this awesome tool [_Nirsoft LiveTcpUdpWatch_](https://www.nirsoft.net/utils/live_tcp_udp_watch.html).

**Comment by vipinjn24** [comment]
@david-bakin hello david i guess you didnt read the comments. Biglybt is using the ports but still it showing the error and i confirm that only one instance is running.

Well another thing is on windows you have a command already i.e. netstat -ano | find "port number"
It will fetch you the pid by which you can easily find the process.

**Comment by hglecke** [comment]
Hi! I experience the same or very similar problems without solution. I too tried all I could think of to find answers, no good.
Some of my details: The system can no longer find open ports, no matter how many I tried in Nat/Firewall test. Selections for download seem to work fine, Nat turns OK. If I try to share my own file(s) by creating torrents, no matter what, it's a no go. Serious problem for a system with the PRIMARY purpose to share.
The same problems with two separate systems. Both win10, fully updated. VPN and virus protection is used. Disabling either or both does not help. In the past, The NAT/Firewall test did work ok, just do not recall when problems started. Anything I can do to help, just ask.

**Comment by vipinjn24** [comment]
@hglecke Hi I used bittorrent/utorrent both of them worked perfectly fine.
Butt one day it stopped happening with BiglyBT, cant say that it is due to updates.

**Comment by vipinjn24** [comment]
This issue needs to reopen.

Today i updated to version 2.7.0.2 the issue again cameup.

So here is the thing that before updating i got no such error that the address is already in use.
but now after update biglybt cannot bind to the port that i exposed to internet and also cannot use udp trackers.

this update confirmed that this is an issue with biglybt and not my system.

please fix.
