### ISSUE TITLE
Suggestion: w.r.t. "torrent check", prioritize live incomplete torrents over completed torrents.

### ISSUE THREAD

**Issue by david-bakin** [BiglySoftware/BiglyBT#1978]
[BiglyBT 2.6.0.1_B23]

I have:
* "re-check pieces when download is done" = **on**.
* "maximum concurrent checking downloads" = **1**
* "re-check smalled downloads first" = **on**

Sometimes when there are plenty of incomplete torrents the last few "active" ones fluctuate between downloading and queued and stopped.  (For example, one download might be consuming nearly all the download bandwidth limit, so the others fall below the "don't count torrent as using a download slot if speed is below ___" limit, so other torrents start up, then the bandwidth consuming torrent slows down, the earlier torrents in the queue start up, and the later ones stop.)

So when this fluctuation happens sometimes, when a later torrent gets started up again BiglyBT decides to check it.  (I don't know why it does this.)  And if it happens to want to check it while some _completed_ torrent is being checked then it has to wait - because only one torrent is checked at a time (because "max concurrent checks" is 1).  (But it would happen I suppose if the "max concurrent checks" was > 1 if there was more than that number of completed torrents to be checked.)

So the suggestion is: Prioritize incomplete torrents needing re-checking over completed torrents needing re-checking.

**Comment by parg** [comment]
Sounds like a scheme, I'll take a looky

**Comment by parg** [comment]
It looks like it already tries to schedule as you are proposing UNLESS 'recheck smallest downloads first' is enabled.

**Comment by parg** [comment]
Are you using the recently added 'one max disk operation per filesystem'? That currently ignores the 'smallest first' directive (incorrectly, guess I should look at that)

**Comment by parg** [comment]
Try the next beta (B25 when built), hopefully working better

**Comment by david-bakin** [comment]
Okay!
