### ISSUE TITLE
Broken Download Page biglybt.com/download/

### ISSUE THREAD

**Issue by xeoron** [BiglySoftware/BiglyBT#1982]
FYI: it points to a page that just loads this  "!DOCTYPE html" which makes it, basically, an empty page. 

If you want people to more easily find the most current installers, you might want to fix this.

**Comment by parg** [comment]
What browser/OS?

**Comment by xeoron** [comment]
macOS11: Firefox, Safari, Chrome 
I even tried incognito mode to see if any extensions were not causing this issue


Does load on ChromeOS v88

**Comment by parg** [comment]
Safari works fine for me on 10.15, don't have an 11 handy atm

**Comment by xeoron** [comment]
Confirmed... Safari is working

Firefox and Chrome is not. 

It is merely loading the !DOCTYPE html (with braces) and nothing else.
The server must be detecting browser versions and v88 for Chrome and Firefox v84-85 it is running into trouble

**Comment by parg** [comment]
Firefox 85 on 11.2 is working fine for me
