### ISSUE TITLE
seeding connecting never connects or no final piece

### ISSUE THREAD

**Issue by gr88** [BiglySoftware/BiglyBT#1984]
Hi Parg,

I'm using:

BiglyBt 2.6.0.1_B26
Java 11.0.9.1 (64 bit)
  Ubuntu
/usr/lib/jvm/java-11-openjdk-amd64

SWT v4934r5, gtk/3.24.23, zoom=100, dpi=96
Linux v5.8.0-41-generic, amd64 (64 bit)
B2.6.0.1_B26/4 az3
8GB ram

I have created several torrent files using BiglyBt.  I did not add any trackers and just relied on DHT.  
Each time I gave the torrent file to only one of my friends so I could share one large file with him.
The DHT portion worked fine.  After both of us connected to the internet my friend's ip address popped up.
BiglyBt says his ip address is connecting.  
When he used Transmission client, after 15 minutes, the transfer started.
Now for the problems.
There are three cases I'll discuss, 2 different torrent files:

1.  Transmission, took a long time to fully connect after biglybt knew the ip address.
   transferred properly except for a piece 512k somewhere in the middle of the file.
   That piece was the last piece.  All others had transferred.  The last piece (say piece 9256 of 20000 pieces)
   took 3 days to finally transfer.  During that time I rebooted, changed ip addresses, and finally 
   got a new computer, installed biglybt, and ran only that torrent.

2.  uTorrent, very quickly the correct ip address was found. Biglybt said connecting. After 15 seconds
   the connection times out.  Then I either add the ip address or it pops back up by itself.
   Says connecting, but never connected fully, for 19 hours.  Again I tried rebooting, restarting, exit,
   uninstall, reistall with only this torrent, etc.

3.  BiglyBt 2.6.0.1 brand new install on Windows 7.  Same torrent as #2 above. Same results as #2 above.

Other times I have created torrent files with biglybt which have worked. 

I cannot open a port for incoming connections because of my vpn.  
All my other torrents work fine for both downloading and uploading.
My experience level is vey high with bittorrent files and systems.

2021-02-02nd

gr88

seeding connecting never connects or no final piece

**Comment by parg** [comment]
You would need to turn logging on on both ends of the connection to see what is going on.

If BiglyBT is making an outgoing connection to a peer at 1.2.3.4:6789, and that is the correct address and port, and the connection never succeeds then there is something wrong with your network or the remote peer, not BiglyBT (assuming that BiglyBT is connecting to other peers just fine)

For the 'missing piece' you would need to ensure that the remote peer has actually requested (blocks from) the piece - in logging you would see the block requests being made and be able to deduce how BiglyBT responded to them.

Whether a peer is discovered via DHT or tracker makes no difference as long as the address and port is correct.

**Comment by gr88** [comment]
Thank you!
