### ISSUE TITLE
All Trackers Sidebar 

### ISSUE THREAD

**Issue by almanteka** [BiglySoftware/BiglyBT#1985]
Java 15.0.2 (64 bit)
  Oracle Corporation
c:\program files\java\jdk-15.0.2

SWT v4930r7, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.6.0.0/4 az3

just looking for a way to visualize all trackers from all torrents like all peers in the sidebar! that way i can remove the trackers that are not working in a centralized manner and not by torrent file! if there is no way to do that right now, can i suggest it as a feature for new versions of BiglyBT? thanks for your help and  fort the great work with BiglyBT!
![biglybtallpeers](https://user-images.githubusercontent.com/42816936/106925285-52a52d00-66e6-11eb-8f29-ef7daf78c6ab.jpg)

**Comment by parg** [comment]
View->All Trackers?

**Comment by almanteka** [comment]
thanks!!! WOW!!!!

**Comment by parg** [comment]
Anything else you want that we might already have? :)
