### ISSUE TITLE
azexec winrar

### ISSUE THREAD

**Issue by almanteka** [BiglySoftware/BiglyBT#1989]
Java 15.0.2 (64 bit)
  Oracle Corporation
c:\program files\java\jdk-15.0.2

SWT v4930r7, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.6.0.0/4 az3

i'm trying to run the command in BiglyBT "C:\Program Files\WinRAR\WinRAR.exe" x -r "%D\*" "%D" after a torrent is finished to extract rared files. the command already works in utorrent! in BiglyBT runs, but i only got the message "no archives found" from winrar and no files extracted! I see that the switch is the same for both programs, and i'm wondering why only one can achieve the extracting process:
%D - Directory where files are saved
anywhere i can see logs from azexec?
from utorrent the log is:

> Moving files from 'S:\download\testo' to 'S:\complete\software\testo'
> Executing: "C:\Program Files\WinRAR\WinRAR.exe" x -r "S:\complete\software\testo\*" "S:\complete\software\testo"

any ideas or suggestions? thanks!

**Comment by parg** [comment]
What does the log say?

Tools->Plugins->Log Views->Command Runner

**Comment by parg** [comment]
Also, are you using 'move on complete' to move the download to an alternative location on completion? I'm not 100% sure how well that plays with this plugin.

**Comment by almanteka** [comment]
found out : Tools->Plugins->Log Views->Command Runner
`Executing: "C:\Program Files\WinRAR\WinRAR.exe x -r S:\download\testo\* S:\download\testo"`
"no archives found" from winrar

**Comment by almanteka** [comment]
> 
> 
> Also, are you using 'move on complete' to move the download to an alternative location on completion? I'm not 100% sure how well that plays with this plugin.

yes, using move on complete. will try out without move on complete and post about it. thanks!

**Comment by parg** [comment]
Not sure why in your log it appears that %D has been expanded to "S:\download\testo\" in one case and "S:\download\testo" in another

**Comment by almanteka** [comment]
you're right, maybe there is no delay between the moving of the file and the extraction! i disabled move on complete from the label and still the problem! went to options > files > completion moving and disabled "move completed files (after downloads)" and it worked! will see if i found a workaround for this.

**Comment by almanteka** [comment]
> 
> 
> Not sure why in your log it appears that %D has been expanded to "S:\download\testo\" in one case and "S:\download\testo" in another

there is a * in the first argument! but thanks for pointing that out because is evident that the command executes before the moving of the file! the argument must be: "C:\Program Files\WinRAR\WinRAR.exe" x -r "S:\complete\software\testo*" "S:\complete\software\testo" in the software folder, not in the download folder

**Comment by parg** [comment]
I'll look at the plugin, see if it can be made to wait until the 'move on complete' is done before triggering.

**Comment by almanteka** [comment]
thanks! i appreciate your work! as a workaround, i just created a tag that keeps the files on the same folder without me breaking the move on complete for other files!

**Comment by parg** [comment]
I've released version 1.4.6 to beta users - if you can give it a test please. It should wait for the move action to complete before running the command.

See the Help menu for how to join the beta program.

**Comment by almanteka** [comment]
thanks! worked perfectly!!!

> Executing: "C:\Program Files\WinRAR\WinRAR.exe x -r S:\complete\software\testo\* S:\complete\software\testo"

great work!

**Comment by parg** [comment]
Nice, keep your eye on things to make sure it stays that way :)

**Comment by almanteka** [comment]
to extract the file to another folder, just use

> "C:\Program Files\WinRAR\WinRAR.exe" x -r "%D\*" "path-to-folder-where-you-like-your-files\%N\"

replace 

> path-to-folder-where-you-like-your-files

with the path of your folder! %N switch will create a sub-folder with the displayed name of the download and the extracted file inside!
