### ISSUE TITLE
Move Data copy the file

### ISSUE THREAD

**Issue by jeehay** [BiglySoftware/BiglyBT#199]
Hi,

When I click on Move Data it always copy the file and then delete the old file, even when i'm copying file from one folder to another folder.

I'm running latest version of biglybt.
Windows 10 64Bits

**Comment by parg** [comment]
Are you running the latest beta? There was an issue with this in 1.2.0.0 - see the Help menu for details of how to join the beta program,

**Comment by teachnovice** [comment]
I am on 1.2.0.0 and i have join to beta program but still I'm on 1.2.0.0
I have run the update but it comes back with no updates.

Do you know how to download beta

**Comment by parg** [comment]
Are you sure you selected the 'join beta program' option in the dialog? You need to manually select it.

**Comment by teachnovice** [comment]
Under Help it say leave beta program rather then join.
![image](https://user-images.githubusercontent.com/4210686/34197131-fdb54ef0-e55c-11e7-8078-492cbd09d397.png)

**Comment by parg** [comment]
Odd. When you select 'Check for Updates...' you will get an update task - when you select the 'Progress Report' icon in the status bar you get a window that shows the details of the update check. Please open this up, select the 'Details' twisty and see what it says. Here's mine:

![image](https://user-images.githubusercontent.com/395293/34198063-e35538dc-e560-11e7-9bd1-99a710068cbb.png)

**Comment by ddbelina** [comment]
[08:38] 02D4DF
Data file move Problem.  BiglyBT 1.2.0.1_B29 is latest but didn’t work in 1.2 either.  MacOSX 10.13.2 (16GB Memory).  Move data from Lacie 800 Firewir to OWV USB 3.0 4TB.
[08:41] 02D4DF
Open BigBT in New view, select file, right click, select move Data file , window with Select directory pops up with window NOT showing las moveto directory (this worked only once before and never sine)select other suggested directory (shows the proper once used when it worked directory, selecet open button, windows disappears and npthing happens.
[08:43] 02D4DF
Do up to useing the Move data under the connect right click selection, now window shows proper directory to move files to but when select mothing happens.
[08:44] 02D4DF
When selecting file afirst and right clicking, I get a mac busy wheel for a second befor the select destination directory window appear.
[08:45] 02D4DF
will post to github also.

**Comment by davisjackie321** [comment]
Nice
