### ISSUE TITLE
Enhancement to Torrent Options Dialog when added

### ISSUE THREAD

**Issue by Dramaman** [BiglySoftware/BiglyBT#1990]
When you add a new torrent, it opens the torrent options dialog box ( if you set it to), there should be an option to limit how long the torrent options dialog box stays open. The main reason I'm thinking this would be useful is when you add a magnetic link, sometimes it could take days (even weeks) to actually get the torrent information. Also, one might just forget to actually click "OK" when the torrent options dialog box opens up. So having a set of rules in place on how this can be handled, would be great.

I'm thinking we should have the following:
1. The ability to set the time limit before the box auto actions it's instructions
2. The ability to set a tag so that someone knows that this is auto actioned (separate from any other tagging logic)
3. The ability to set the state that should be applied to the torrent when it's auto action (ideally already covered with the global settings of what state a new torrent should be set to when added, but someone may want to override)
4. The ability to predetermine if torrents with similar files should have their save paths auto renamed or not 
5. The ability to predetermine if similar torrents should have their save paths auto renamed or have the tracker data automatically combined with an existing torrent

**Comment by parg** [comment]
That's a lot of work for a pretty uncommon situation...

**Comment by Dramaman** [comment]
Oh ok, what could you implement that would be relatively simpler?

**Comment by parg** [comment]
I suppose an auto-close timer with a fixed tag name (AutoOpened or something) wouldn't be too hard

**Comment by Dramaman** [comment]
That works for me :)

**Comment by parg** [comment]
Beta B32 has a timer option - set your Mode to intermediate or advanced to see the configuration under Options->Files

**Comment by Dramaman** [comment]
Thanks, I see it

**Comment by Dramaman** [comment]
Seems to work fine, thanks.
