### ISSUE TITLE
Tags: Execute on Assign Script only javascript

### ISSUE THREAD

**Issue by almanteka** [BiglySoftware/BiglyBT#1991]
Java 15.0.2 (64 bit)
  Oracle Corporation
c:\program files\java\jdk-15.0.2

SWT v4930r7, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.6.0.1_B29/4 az3

noticed that BiglyBT tags can run an script on assign, which type of scripts can be run? only javascript? or batch too? 
thanks for any info!

**Comment by parg** [comment]
Just javascript unfortunately

**Comment by almanteka** [comment]
thanks for your reply!
