### ISSUE TITLE
Progress bar text font colors

### ISSUE THREAD

**Issue by almanteka** [BiglySoftware/BiglyBT#1992]
Java 15.0.2 (64 bit)
  Oracle Corporation
c:\program files\java\jdk-15.0.2

SWT v4930r7, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.6.0.1_B29/4 az3

i'm wondering if there is a way to change the text color of the progress bar and the height? maybe a gradient between the color scheme and white where the bar is colored?
![biglybt progress bar](https://user-images.githubusercontent.com/42816936/107313482-f9802500-6a68-11eb-8596-f390a30f6782.jpg)

**Comment by parg** [comment]
That's currently not possible - I don't think it looks too bad with the single text colour.

**Comment by almanteka** [comment]
> 
> 
> That's currently not possible - I don't think it looks too bad with the single text colour.

it looks beautiful, but sometimes is hard to read. maybe adjusting the height of the bar and the text expanding with it can make it easier to read. just an idea. maybe i need to use another scheme color! will try. thanks for your reply!
