### ISSUE TITLE
preview/read video before for partial downloaded   video suggestion 

### ISSUE THREAD

**Issue by magicmana** [BiglySoftware/BiglyBT#1993]
hello  
it is possible  to add a setting  for  set the  number of  piece   for  the  option  "download first + last piece  first" .
Generally for .mp4  VLC need 3 or 4  piece  at the  end of  the video  file  for starting   read  the file. each time  i  need  to force some end piece's file manually. 
The  idea is to define  start and end piece to a small  value >1 ,    for sample  BiglyBT   download  first and last 5 piece for  each file  in torrent  before start  sequential download.
thanks.  and good job for this  software.

**Comment by parg** [comment]
If you want things to work then get the media server URI for the incomplete content (right-click option) and paste that into VLC - everything will happen automatically.

**Comment by magicmana** [comment]
hello  should  be complicated to manage.   
my vlc  are in another computer  , because my PC who download  have a small screen . and   i access  file by network
regards

**Comment by parg** [comment]
You have a network between them right?
