### ISSUE TITLE
Need "source flag" functionality

### ISSUE THREAD

**Issue by Zorlin** [BiglySoftware/BiglyBT#1997]
Hi there, I need to use BiglyBT to manage some private trackers (Creative Commons, actually!) but I cannot as the "source flag" functionality is missing. Could you please add it? Willing to donate $20 USD if it's done soon.

Cheers

**Comment by parg** [comment]
Are you talking about https://github.com/qbittorrent/qBittorrent/issues/7965 ?

**Comment by Zorlin** [comment]
Yes @parg exactly :)

**Comment by parg** [comment]
And what do you want to be able to do with it? Set it in the torrent creator, see it in the General view, ... ?

**Comment by Zorlin** [comment]
Set it in the creator :)

**Comment by parg** [comment]
It'll be in the next beta (B32), later today probably

**Comment by Zorlin** [comment]
@parg you are a champion. How do I donate?

**Comment by parg** [comment]
https://www.biglybt.com/donation/donate.php has some options - cheers :)

**Comment by Zorlin** [comment]
@parg as promised, with a little extra for being SO DAMN FAST - $25 USD sent via BCH <3

if it works out I will also put you in the thanks for Riff.CC somewhere

**Comment by parg** [comment]
If you have any other things you'd like to see, send them over!

**Comment by Zorlin** [comment]
Absolutely. I'm blown away, I really am. Thanks again.

**Comment by Zorlin** [comment]
I've had worse support from *enterprise contracts*

**Comment by parg** [comment]
Beta B32's live - tell me if everything's working OK

**Comment by Zorlin** [comment]
Will do! About to sleep but I'll look in the morning. Thanks again, omg the
response time! Amazing!

**Comment by Zorlin** [comment]
Works perfectly, amazing, TYSM
