### ISSUE TITLE
[REQUEST] Command Runner on Add Torrent window

### ISSUE THREAD

**Issue by almanteka** [BiglySoftware/BiglyBT#1999]
Java 15.0.2 (64 bit)
  Oracle Corporation
c:\program files\java\jdk-15.0.2

SWT v4930r7, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.6.0.1_B32/4 az3

is possible to add a button that opens the Command Runner window on the Add Torrent window? that way we can just add the command before adding the torrent and not after. this is to avoid to return to the torrents list to add the command and/or to avoid to run a command globally for all torrents when we need to run it on an specific one. 
thanks for all the hard work involved in BiglyBT and maintain it!
maybe you can add it in this area, near these 3 buttons, or the most convenience area of your choice.
![biglybt command](https://user-images.githubusercontent.com/42816936/107800015-9de9bc00-6d34-11eb-858a-fe4e55a945a8.jpg)

command runner window
![biglybt command2](https://user-images.githubusercontent.com/42816936/107800028-a510ca00-6d34-11eb-8f58-dfbe9a778a5a.jpg)

the option is already available after adding the torrent, but my request is to add it before
![biglybt command3](https://user-images.githubusercontent.com/42816936/107800623-60396300-6d35-11eb-8a10-258a0929bfa4.jpg)

**Comment by parg** [comment]
Why don't you just set things up so the open torrent dialog never shows (Files settings), add torrents in a 'stopped' state and then configure them in the Library before starting them?

Adding stuff to the options dialog to allow a plugin to set details on a download before the download has even been added would require extensive work.

**Comment by almanteka** [comment]
i need to use the add torrent window 'cause i need to change the file names (long names with a lot of info) and do other things just in one place/one time. is only a request and i know you can't add all the requests that people ask. the idea came from utorrent that have that option. thanks for reading my post and for your reply!

**Comment by parg** [comment]
No problem, keep the ideas coming!

**Comment by almanteka** [comment]
> No problem, keep the ideas coming!

just an idea: how about to run the commander under a tag? is that even possible?

**Comment by almanteka** [comment]
just another idea: maybe add the command runner to the tag's options template? execute on assign > apply option template
