### ISSUE TITLE
Translation problems

### ISSUE THREAD

**Issue by Havokdan** [BiglySoftware/BiglyBT#2]
Did not you bring the latest Vuze translations? Brazilian Portuguese is not the last one I made there for Vuze, I also can not install some plugins, such as Vuze translation. Have a nice day.

**Comment by parg** [comment]
Hmm, you're right! I fixed it so that the installation at least works but there appears to be a problem with the plugin once installed - it hangs on the startup view. I'll take a look!

**Comment by Havokdan** [comment]
RSSFeed Scanner also does not work after it is installed, it does not save the settings.

**Comment by parg** [comment]
Does the internationalisation plugin now install and work for you? The problem I am not seeing might only affect OSX users and if you're Windows it might be ok...

**Comment by Havokdan** [comment]
Well, I'll remove the application, install it again and try again, then I'll come back here to respond.

**Comment by parg** [comment]
Also on OSX I'm not seeing any issues with the RSS Feed Scanner config - it is getting written correctly to rssfeed.options in the plugin directory

**Comment by Havokdan** [comment]
Well, the plugin this time I managed to download, but it keeps loading without end.

**Comment by parg** [comment]
Windows or Mac? Does it just stick on the plugin screen with some French text "... de cours' ?

**Comment by Havokdan** [comment]
Yes, windows and stick in loading page.

**Comment by Havokdan** [comment]
Just to recap, problems I'm having with the first version of this promising software:

1 - Chat, which in Vuze, if I closed with an open chat, when reopening the application, reopened the same chat channel, this does not happen with BiglyBT, detail, it behaved correctly when importing the Vuze configuration, when doing A clean installation, did not happen more as it should or as it was in Vuze;

2 - The RSS Feed Scanner plugin did not remember the rss feeds, I put four feeds, I closed and reopened the program and it was like opening the first time;

3 - Some plugins do not install, such as translation, however for this you seem to have corrected this, but the plugin keeps loading and never finishes opening its interface;

4 - BiglyBT did not come with the latest translations I made for Vuze, several plugins and the software itself is with excerpts that I had already translated into Portuguese but still in English.

**Comment by parg** [comment]
Thanks for that!

1. Chat views only automatically re-open if you have them in the sidebar
(there's a menu option for that on the chat windows or a setting under
Friends to open all chats in the sidebar by default), There was a fix
around sidebars in the betas - are you running _B02? If not please join the
beta program

2. Did you press the 'save' button after adding the feeds? If not this
might also be a consequence of (1) above

3. Weird that I saw the issue on OSX and fixed it in a release last night
but that it is still happening on Windows :(

4. Most things should have been copied across, can you give me the names of
the plugins with missing texts so I can take a look?

Thanks

**Comment by Havokdan** [comment]
1 - I'm not using Beta yet.

2 - Yes, I saved the feeds, but when it started it was all empty.

3 - The translation plugin download, but does not finish loading, that screen with a bar carrying text that looks French.

4 - I will give a check, then I edit this item in this post.

**Comment by parg** [comment]
I looked in your latest update here: 

https://forum.vuze.com/Thread-Portugu%C3%AAs-do-Brasil-Brazillian-portuguese?page=13

(attachment https://forum.vuze.com/attachment.php?aid=603)

and there is no entry for 

azbuddy.dchat.ui.hide.search_subs=Hide automatically generated search and subscription messages

Maybe you never uploaded your most recent translations?

**Comment by Havokdan** [comment]
I will install Vuze to confirm this, but that is, when the translation plugin comes back to work, I redo the translation, it is very little.

**Comment by Havokdan** [comment]
I just looked at Vuze, I did not really have that option on Vuze.
