### ISSUE TITLE
Plugin Installation Error

### ISSUE THREAD

**Issue by Taurean75** [BiglySoftware/BiglyBT#20]
Hey --

When I try to install plugins from [here](https://plugins.biglybt.com), it returns the following error:
![plugin_error](https://user-images.githubusercontent.com/8365855/29182319-4c4bbdfe-7db3-11e7-9946-f01bf53bec7e.JPG)

What should I do?  I'm using Windows 10 x64.

Thanks.

**Comment by parg** [comment]
This might be cause by messed up certificates - try going to Tools->Options->Security and hit 'reset certificate store' - you'll need to restart BiglyBT.

If it continues to fail then you can manually download that plugin from

https://s3.amazonaws.com/biglybt-files/plugins/aercm_0.6.4.biglybt

and install it via the File menu

**Comment by Taurean75** [comment]
I still get the same error. Oh well.

**Comment by Taurean75** [comment]
The Amazon link words and installs just fine but not the links on your plugins page. Must be something on your end.

**Comment by TuxPaper** [comment]
hmm, for anyone else having a similar problem (or for @Taurean75 , if you want to fiddle with things), try this as well:

For Windows,
1. Close BiglyBT
1. Open a Command Prompt
1. Enter the two following commands
   ```
   del /q "%APPDATA%\BiglyBT\.certs"
   del /q "%APPDATA%\BiglyBT\.keystore"
   ```
1. Start BiglyBT
1. Try installing a plugin from plugins.biglybt.com

**Comment by Taurean75** [comment]
That fixed it. Thanks! :)

**Comment by Taurean75** [comment]
This problem is back, and the above doesn't help. I'm getting...

> Error :I/O Exception while initializing download of 'biglybt://install-plugin/mlDHT':java.io.IOException: com.biglybt.pif.utils.resourcedownloader.ResourceDownloaderException: https://plugins.biglybt.com/getplugin.php?plugin=mlDHT&version=1.0.0.0&app=BiglyBT&os=Windows+10&osv=10.0&arch=amd64&ui=az3&java=1.8.0_131&swt_platform=win32&swt_version=4757: Should never get here

**Comment by Taurean75** [comment]
I also get...
> Error :I/O Exception while initializing download of 'biglybt://install-plugin/mlDHT':java.io.IOException: com.biglybt.pif.utils.resourcedownloader.ResourceDownloaderException: https://plugins.biglybt.com/getplugin.php?plugin=mlDHT&version=1.0.0.0&app=BiglyBT&os=Windows+10&osv=10.0&arch=amd64&ui=az3&java=1.8.0_131&swt_platform=win32&swt_version=4757: I/O Exception while downloading 'https://plugins.biglybt.com/getplugin.php'

**Comment by parg** [comment]
Do you happen to have 'update anonymously' enabled under Tools->Options->Interface->Start ?

**Comment by Taurean75** [comment]
That apparently isn't the problem. I unchecked it, restarted the application and tried it again, but the result is same.

**Comment by Taurean75** [comment]
Redirection doesn't seem to work within the application.

**Comment by Taurean75** [comment]
I've tried it with default configurations, but it gives the same error.

**Comment by Taurean75** [comment]
Given up on me?

**Comment by TuxPaper** [comment]
Unfortunately, just ran out of ideas, Taurean75.  It's odd that erasing those files worked one time and not the next (and that the problem came back)

For a workaround, you can always take the ful url after the ResourceDownloaderException, and open it in your browser.

You can also try re-installing BiglyBT (it will keep your config unless you check the box to tell it to erase it), which will re-install the app files and maybe fix something? (not likely, but as I said, I ran out of ideas)

**Comment by Taurean75** [comment]
That workaround works. Thanks.
