### ISSUE TITLE
Could you make Bigly remember the last tracker URL used?

### ISSUE THREAD

**Issue by Zorlin** [BiglySoftware/BiglyBT#2000]
Would be incredibly helpful. Running latest beta.

**Comment by parg** [comment]
The torrent creation wizard has a drop down list of tracker URLs used  but I see that it doesn't auto-select the latest use, I assume that's what you mean?

**Comment by Zorlin** [comment]
> The torrent creation wizard has a drop down list of tracker URLs used but I see that it doesn't auto-select the latest use, I assume that's what you mean?

Exactly!

**Comment by parg** [comment]
Should be fixed in the next beta when built (B33)

**Comment by Zorlin** [comment]
Man you're the coolest ;) I'll be adding the name BiglyBT to the credits
for Riff.CC.

**Comment by parg** [comment]
B33 is available, tell me how it works out!

**Comment by Zorlin** [comment]
Works great, thanks again!

You're in the credits!
