### ISSUE TITLE
Feature request: Seeding is important.

### ISSUE THREAD

**Issue by Nospammy** [BiglySoftware/BiglyBT#2001]
I have just had an issue with using BiglyBT to satisfy a seeding requirement on a tracker. I found that it was determined to "queue" the one torrent I had, even though there were no other torrents to 'queue' behind. I saw a comment elsewhere that claimed "there's no point using local resources seeding to no peers" but this is incorrect; not seeding can lead to account termination. It should be easier to toggle a torrent to seed if the user requests it. For example right-click on the status "queued" and select "seed until cancelled". Or, if the torrent is running but queued, the "start" icon should be a 'force start' instead of greyed out. The only way I could get my torrent to seed was to switch to the advanced UI and choose "force start". It shouldn't be that hard. Also, the client already knows if a torrent has the 'private' flag set or not; it would be really smart to use that information to default to seeding since private torrents are the ones likely to carry seeding requirements.

Java 11.0.6 (64 bit)
  Ubuntu
/usr/lib/jvm/java-11-openjdk-amd64

SWT v4934r5, gtk/3.22.30, zoom=100, dpi=96
Linux v4.15.0-91-generic, amd64 (64 bit)
B2.6.0.0/4 az3

**Comment by almanteka** [comment]
i don't know if is the same approach you're looking, but when i need to constantly seed a torrent, i use the force start icon to the right of the start indicated with the red arrow  in the photo below.


![biglybt force start2](https://user-images.githubusercontent.com/42816936/107868739-1ea3d780-6e5d-11eb-9bd0-6de157cb81be.jpg)

**Comment by Nospammy** [comment]
Indeed. This is what I meant by _"The only way I could get my torrent to seed was to switch to the advanced UI and choose "force start". It shouldn't be that hard."_ My fear is that novice users won't switch to the "advanced" UI because seeding as required by private trackers is not an "advanced" requirement, it's mandatory or you're banned. The button you highlight with your arrow does not appear on installation.

**Comment by parg** [comment]
There's a reason for 'force start' not being available in non-advanced mode. When it was available we had users enabling it willy-nilly and ending up with 100s of torrents continually active and consuming CPU/Memory pointlessly on swarms with no peers and then they bitched about the product being 'bloated'...

The 'Queue' rules under Options->Queue are designed to balance seeding requirements with resource usage. There is, for example, a 'minimum seeding time' under Seeding->First Priority.

I suppose the force-start button could be made available in beginner mode if any of the selected torrents are private.

**Comment by parg** [comment]
By the way you can force-start a download by pressing and holding the 'start' button in the Library toolbar

**Comment by Nospammy** [comment]
Thank you for answering. I take the point about resources, but from my perspective, I have an old computer (2014) next to me which is running a different torrent client and is seeding 1,400 torrents simultaneously; it's using 1% CPU and 39MB memory. With this for context, it seems odd that your client, given just ONE torrent to seed, feels that by default it has to 'queue' that torrent after an hour to save resources.

(By the way, I do understand that using java allows for cleaner collaborative work, a faster/easier design process and fewer bugs, and that some sacrifice in the CPU/Memory area is unavoidable; so comparison with a tightly coded program is a bit unfair.)

I would be happy with ANY user interface control that a new user would find; namely:

- Select the problem (torrent) and see a control or menu option that fixes the problem
- Right click on the problem ("queued") and see a menu option that fixes the problem

Pressing and holding a button is not a usual UI feature in Windows or Linux, so 'no'.

You are correct about the "first priority" option, but it was so deeply buried, I did not see it. The reason being, I clicked on 'queue' but it didn't open the sub menu that showed 'seeding'. I'm not even sure I would have recognised "first priority" as what I needed, since I only had ONE torrent, I didn't care about prioritising them (it).

> I suppose the force-start button could be made available in beginner mode if any of the selected torrents are private.

That would do it.

**Comment by parg** [comment]
OK, already done.

I suppose one of the differences between clients is that BiglyBT was never designed for beginners to pointlessly seed torrents just for the sake of some private tracker's rules.

I have a torrent on such a tracker, it has been force-seeding continuously since 20th Feb 2020 and has uploaded zero (yes zero) bytes to peers as there aren't any. It has, however, been clocking up some daft 'seeding points' for the entire time, so, yay for that.

**Comment by parg** [comment]
Perhaps I should add a mode whereby queued, private torrents are kept active on the private tracker for this purpose.

**Comment by Nospammy** [comment]
That's awesome that you already did it! Thank you! I will post a longer reply tomorrow, but wanted to show my appreciation promptly.

**Comment by parg** [comment]
Beta B34 has a 'light seeding' mode for private torrents. Rather than transitioning into a queued state and relying on scrape requests for activation they remain registered with the tracker as seeds while using significantly less resources.

**Comment by ms52538** [comment]
2601_B40
Windows 10
Light Seeding (to the only torrent tracker I use for all my torrents): experienced a drop from 2,700 in seeding down to 1,624 seedings after updating to version 2061_B40. Was this expected? I do not have any restrictions placed in file transfers or queues that I am aware of.

**Comment by parg** [comment]
Keep your eye on things, I decreased the rate at which downloads become eligible to be light-seeds to load balance things, that is possibly a cause.

**Comment by as-muncher** [comment]
> Beta B34 has a 'light seeding' mode for private torrents. Rather than transitioning into a queued state and relying on scrape requests for activation they remain registered with the tracker as seeds while using significantly less resources.

How do you activate this light seeding mode?  I have one finished torrent and I have it set to forced seeding to rack up brownie points so I can download other things too.

**Comment by parg** [comment]
https://github.com/BiglySoftware/BiglyBT/wiki/Seeding#light-seeds

It is automatic for seeds on private trackers with 0 peers

**Comment by Zenya393** [comment]
> https://github.com/BiglySoftware/BiglyBT/wiki/Seeding#light-seeds
> 
> It is automatic for seeds on private trackers with 0 peers

I think "First Priority Seeding" puts the torrents into "Super Seeding" status, and overrrides "Light Seeds", but not sure.

If so, would be easier if the options that do the same thing have the same name: "First Priority Seeding" = "Super Seeding", and perhaps a tooltip explanation too.
