### ISSUE TITLE
Command Runner Under A Tag Assigment

### ISSUE THREAD

**Issue by almanteka** [BiglySoftware/BiglyBT#2004]
Java 15.0.2 (64 bit)
  Oracle Corporation
c:\program files\java\jdk-15.0.2

SWT v4930r7, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.6.0.1_B34/4 az3

is possible to run the commander under a tag? just create a tag and made available the option under execute on assign? or maybe under execute on assign > apply option template? i'm just looking to add the commander option to a group of torrents, not as a globally option where the command will run on all files. i'm just giving ideas for your consideration, where simplicity is a must to avoid you adding work to your already busy schedule! thanks!

**Comment by parg** [comment]
Hmm, the Tags that a download is assigned to are passed as a comma separated list to the command as %L - you could code the command based on this? 

Set the command to run on all downloads but have it do nothing unless %L included whatever tag(s) you were interested in?

**Comment by almanteka** [comment]
command runner can run batch files? tried to run a simple script to say hello world and the cmd window never showed up. how i can add an specific label to run a program if %L=Colored?

i tried a batch script passing %D %N %L to it with no luck, even adding "if %L==Colored" to the commander runner! 

"if %L==Colored then" "C:\Program Files\WinRAR\WinRAR.exe" x -r "%D\*" "%D"

**Comment by parg** [comment]
It can run anything...

On Windows you can start a command shell that then runs notepad.exe with

`cmd.exe /C notepad.exe`

Or try PowerShell - https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/powershell

There's lots of google help for writing batch files, accessing passed parameters etc.

**Comment by parg** [comment]
that notepad example was obviously just a test to show that cmd.exe works - you would need to write a script, say 

`c:\projects\scripts\myscript.bat`

and then call it via

`cmd.exe "c:\projects\scripts\myscript.bat" %D %N %L`

your script can then access the first argument (%D) via %1, the second via %2 and the third (tags) via %3

Not tested the above but if it doesn't work it is close to working :)

**Comment by almanteka** [comment]
thanks! i'll test it out! my problem was calling cmd, but with your suggestions i'll give a try again!

**Comment by almanteka** [comment]
don't know why, but i still can't run any batch file from Command Runner, even simple ones! 

cmd.exe C:\hello.bat

_hello.bat_
**start cmd /k echo Hello, World!**

i tried **cmd.exe /C notepad.exe** and that worked

_another hello.bat_
**echo Hello World
pause**

tried **cmd.exe** alone and the cmd window never showed, or the absolute path **C:\Windows\system32\cmd.exe**

will continue to dig this out!

**Comment by parg** [comment]
Guess I should have tested by reply...

`cmd /C C:\hello.bat`

should work...

or maybe even

`C:\hello.bat'

**Comment by almanteka** [comment]
yes!!! i made it work by:

**"S:\aascripts\!scripts\hello.bat" "%D" "%N" "%L"**

and hello.bat

**rem WinRAR
set fromdir=%1
set name=%2
set label=%3
set todir="S:\complete\unrared files\"
set winrar="winrar.exe"
CD /D "C:\Program Files\WinRAR\"
if %label%==RAR call %winrar% x %fromdir%\* %todir%\%name%\**

thanks for all your help!

**Comment by parg** [comment]
Nice :)

**Comment by parg** [comment]
Just make sure you don't assign more than one Tag to the download otherwise the %label%==RAR will fail

**Comment by almanteka** [comment]
> 
> 
> Just make sure you don't assign more than one Tag to the download otherwise the %label%==RAR will fail

i tried with two labels and passed the test, don't know why, but i tested to be sure!

**Comment by almanteka** [comment]
just a correction to my previous statement, only worked when the RAR label is the first, but not if it's second and so on, so i added

> for /F "tokens=* delims=, " %%a in ("%label%") do (
> set label1=%%a
> set label2=%%b
> set label3=%%c
> )
> 
> if %label1%==RAR goto :UNRAR
> if %label2%==RAR goto :UNRAR
> if %label3%==RAR goto :UNRAR
> 
> :UNRAR
> call %winrar% x -r %fromdir%\* %todir%\%name%\

maybe i need to enhance the script, but i'm still learning!

**Comment by almanteka** [comment]
added some other code 'cause winrar was executed even with non compressed files after adding delims. needed to end the code running all the blocks. leaving it here for others! sorry if there are any redundant commands, maybe someone can improve it! thanks!

> set fromdir=%1
> set name=%2
> set label=%3
> set todir="S:\complete\unrared files\"
> set winrar="C:\Program Files\WinRAR\winrar.exe"
> for /F "tokens=* delims=, " %%a in ("%label%") do (
> set label1=%%a
> set label2=%%b
> set label3=%%c
> )
> 
> if %label1%==RAR goto UNRAR else goto label2
> GOTO END
> 
> :label2
> if %label2%==RAR goto UNRAR else goto label3
> GOTO END
> 
> :label3
> if %label3%==RAR goto UNRAR else goto END
> GOTO END
> 
> :UNRAR
> call %winrar% x -r %fromdir%\* %todir%\%name%\
> 
> :END

***

**Comment by parg** [comment]
Sounds like you're having fun there :)

**Comment by almanteka** [comment]
i force checking after a download completes, any way to create a delay for the command runner to run **after** the download is checked completely? with large files, the commander started the script **before** the checking is not finished and runs at the same time the file is checked. thanks for any suggestion!

**Comment by parg** [comment]
You mean you are manually 'force checking' the download (by right-click + selecting the 'Force Re-check' button)? 

Normally the download will automatically do a (slower) recheck when it completes (unless you have disabled this in the config).

I thought that the command runner waited for the automatic check to complete although I haven't checked.

**Comment by parg** [comment]
Hmm, looking at the code it does wait for any 'move' operations to complete but not 'check' operations.

It could take quite a while for the recheck to complete on a large file - do you really want the command to wait that long before firing? The reality is that the recheck shouldn't actually find any issues (the download was checked as it progressed, the recheck is a 'just in case' thing).

**Comment by almanteka** [comment]
i was referring to the auto recheck. sometimes it found errors and returns the torrent to download, maybe a large file corrupted. i use the commander to fire winrar to extract files, but when this happens, winrar gave me errors of corrupted files because it fires before BiglyBT confirmed the file is not corrupted! maybe i can add a delay to my script.

**Comment by parg** [comment]
One problem is that I think that the attempt to fire the command is only made once-per-download. So if the recheck fails and the download re-enters a downloading state to fix the corrupted blocks, when it completes the second time the action won't get fired...

**Comment by almanteka** [comment]
i think i saw it fire again after the download completed the second time. i need to check that again. also, i think that the problem corrupting the files is winrar running parallel with the recheck of BiglyBT. the two are fighting and take a long time to recheck and decompress when the two are running in parallel. i resolved delaying the entrance of wirar for 2 minutes after the commander is fired and that solved my issue! the commander fires as expected, i only delayed the execution of winrar.

:UNRAR
**timeout /t 120**
call %winrar% x -r %fromdir% \ * %todir% \ %name%\

**Comment by parg** [comment]
Looking further I think you're right - it will re-trigger. I think I'll add an option to wait for the recheck as that would be better than hardcoding 2 minutes or whatever. I'll also make sure that if the recheck fails then it doesn't go ahead and trigger the first time!

**Comment by almanteka** [comment]
your ideas are great! thanks!

**Comment by parg** [comment]
You should auto-update to version 1.4.7 - it has a new option to wait for the recheck. This currently defaults to 'off' so you'll need to change that - tell me how that works out!

**Comment by almanteka** [comment]
![commander](https://user-images.githubusercontent.com/42816936/115188280-b4a0ec00-a0b2-11eb-956f-dea9b8049b4d.jpg)
worked perfectly as you can see in the photo above! two firings of winrar avoided! thanks for all your hard work to make BiglyBT the best torrent client!
