### ISSUE TITLE
make BiglyBT interface cleaner, more orderly, more like qbittorrent's

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2005]
* OS and version
windows 20h2 x64 19042.804

* BiglyBT Version Number
SWT v4930r7, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B2.6.0.0/4 az3

* For *nix: Desktop Environment

I started exploring BiglyBT a few months ago because I was looking for a program that could look through my downloaded files and piece files together, from different download sessions on different computers, and was glad to find it.  I am also really hoping that BiglyBT will be able to download files into my torrent from other torrents, but with identical file names, and do it automatically.  Sometimes, if I've got a torrent called "A" that is 1 GB, and then I haven't checked on btdig that there's actually a torrent called "A" that is the same files, just more, up to 3 GB because a user has added more, I'd like BiglyBT to be able to download from both torrents automatically if it finds them, towards my original "A" torrent.

For the downside: I really had trouble finding a way to get BiglyBT to recognise files with .!qB file extension, which is what qbittorrent normally does.  I think it should be a lot more automated, that BiglyBT should just automatically look for those files with those extensions.

Also, the user interface is way too much.  Honestly, I really like qbittorrent's graphical user interface, with the alternating rows of blue or white to make it easier to find your files, and the view in qbittorrent 4.3.3 when you expand various trees to see the files in a folder, whereas in BiglyBT, it's just way too cluttered, complex.

Also, if you could make the tooltips show immediately when you rest the mouse cursor over the green triangle or the red ex, or whatever buttons, so that I know what each means.  And, I'd really like an option to right-click on a torrent and "force recheck".  It seems like it's hard to do a lot of things that just come so easily and naturally in qbittorrent.  I don't want to have to select all the files in my torrent, and then have to "force recheck".

Also, when I select all the files in a torrent, and then "show in Windows Explorer", what BiglyBT will do is then open 200 Windows EXplorer windows until my system freezes.

Plus, in terms of online safety from those people who would like to accuse me or others for something possibly accidentally downloaded, maybe I have to do more research?  Certain things like enabling downloading from peers, I don't know, wish there was a more safer or anonymous mode.  I haven't done enough research on this yet.  But I almost wish it was available or enabled by default.

If there was a forum, I might have posted this there, and I understand that there are a lot of issues all in this one issue, so I understand if you close this. I just wanted to give some feedback.

**Comment by almanteka** [comment]
i'm using BiglyBT in advance mode, don't know if the following are available in in the intermediate or beginners mode.

force recheck is available when you right-click on the torrent, must be stopped first

![biglybt force recheck 02](https://user-images.githubusercontent.com/42816936/108298263-0d1b4200-7173-11eb-8526-2e404ff9bd11.jpg)

and is available on the top bar too

![biglybt force recheck 01](https://user-images.githubusercontent.com/42816936/108298337-2a501080-7173-11eb-9a40-27a4ae00d6c9.jpg)

for the alternate lines color, you can change the behaviour to the color of your choice at tools > options > interface > color scheme (arrow in the photo below)

![biglybt color scheme](https://user-images.githubusercontent.com/42816936/108298530-8024b880-7173-11eb-96ab-52febc16fb5a.jpg)

**Comment by parg** [comment]
Why would BiglyBT recognise ".!qB" extensions?

There's built in chat - see the Community menu -> Community Chat -> Public

**Comment by as-muncher** [comment]
@almanteka Thanks for the info about alternating rows.  and for your response
@parg BiglyBT would recognise the .!qB extension, as I wrote above, for when a guy wants to have BiglyBT see if there are files on the computer that can be integrated into the files currently being downloaded.  I have taken a torrent with, for example, 5GB of data and done a search for an earlier torrent that has the same name, but only 2GB of data, so that I don't have to re-downloaded the 2GB again.  If I had started the file in qbittorrent, and have it save with a .!qB extension for incomplete files, then it's handy if BiglyBT will automatically recognise that, as it does for whatever the bittorrent file extension is and the utorrent extension.  Sure, qbittorrent is also open source, but it makes sense to help people migrate to use BiglyBT from qbittorrent too.

**Comment by crzsotona** [comment]
> 
> 
If I had started the file in qbittorrent, and have it save with a .!qB extension for incomplete files, then it's handy if BiglyBT will automatically recognise that, as it does for whatever the bittorrent file extension is and the utorrent extension. Sure, qbittorrent is also open source, but it makes sense to help people migrate to use BiglyBT from qbittorrent too.

Why would BiglyBT include support for other torrent clients incomplete extensions by default? What prevents user to rename .!qB to .az!?
Additionally, incomplete files suffix can be changed in BiglyBT interface to anything user wants.

**Comment by as-muncher** [comment]
> > If I had started the file in qbittorrent, and have it save with a .!qB extension for incomplete files, then it's handy if BiglyBT will automatically recognise that, as it does for whatever the bittorrent file extension is and the utorrent extension. Sure, qbittorrent is also open source, but it makes sense to help people migrate to use BiglyBT from qbittorrent too.
> 
> Why would BiglyBT include support for other torrent clients incomplete extensions by default? What prevents user to rename .!qB to .az!?
> Additionally, incomplete files suffix can be changed in BiglyBT interface to anything user wants.

True, but also I am being honest that it's hard to find that setting that I can choose whatever extension.  I did manage to find a program that could bulk rename files with the .!qB extension.  This is the day and age of computers so I figured it didn't take much for a program to automatically include support for other incomplete extensions from other torrent clients.

**Comment by almanteka** [comment]
> True, but also I am being honest that it's hard to find that setting that I can choose whatever extension.


Intermediate or Advance Mode
Tools > Options > Files > File Extensions area > Add suffix to incomplete files

![files](https://user-images.githubusercontent.com/42816936/110407118-b4481680-8059-11eb-9268-257a4a34bd69.jpg)

**Comment by iansebryk** [comment]
i, for one, love the interface layout.  it's really well thought out IMO.  it's one of the reasons i switched to it.  granted, there's a LOT of UI to deal with and the docs on it are... sparse.  but overall, i like it better than any client i've used in the past.  if only it wouldn't force subfolders on you...  :P
