### ISSUE TITLE
BiglyBT stopped working

### ISSUE THREAD

**Issue by LeisureTime69** [BiglySoftware/BiglyBT#2007]
Windows 10, latest Bigly.

Has been working fine for years, and now won't connect. Behind same ExpressVPN.

Not sure it's related, but stopped working about the time I installed Windows Sandbox. Tried uninstalling that, but BiglyBT still broken. Uninstalled BiglyBT and re-installed. No joy. 

Help please!

**Comment by parg** [comment]
Is BiglyBT bound to the wrong interface? Check Options->Connection->Advanced Network Settings

**Comment by LeisureTime69** [comment]
Thanks for the response!

Before the uninstall it was eth13, and after reinstall it is eth1.

eth1	(VirtualBox Host-Only Ethernet Adapter) 	eth1[0]
eth13	(WAN Miniport (IPv6))

I have a crapload of entries under "The following interfaces are available:", including about 70 that begin with eth, 27 of WLAN, couple ppp, and 5 net.

Everything else on my computer seems to be working fine.

**Comment by parg** [comment]
Clear the bind setting out and see if that works

**Comment by LeisureTime69** [comment]
Omg, it looks like that worked! Thank you so much!

I believe the issue was I had chose "explicitly bind" to my VPN, and that probably changed when Windows Sandbox was installed.

**Comment by parg** [comment]
Yay :)
