### ISSUE TITLE
Show total space used in web interface?

### ISSUE THREAD

**Issue by DumbJoe** [BiglySoftware/BiglyBT#2008]
Perhaps in the statistics tab for example here: 
[!](https://i.postimg.cc/tJdPg0rk/stat.png)

Can have another line underneath "Downloaded" stating "Total space of all torrents used up" and then it adds the sizes of each torrent and then totals that figure there so you know how much space all your torrents have used up at a glance.

* OS and version - Debian 9
* BiglyBT Version Number - 2501-B15
* For *nix: web interface

**Comment by magicmana** [comment]
already exist a  lot  of freeware  who make   that perfectly 

personally on  linux  i use baobab
https://help.ubuntu.com/community/Baobab

on windows i  use space sniffer 1.3
 http://www.uderzo.it/main_products/space_sniffer/index.html

but  you should find many more on  the net  , searching disk analyser + your os   on the net

**Comment by DumbJoe** [comment]
> personally on linux i use baobab
https://help.ubuntu.com/community/Baobab

...and how does this gui work on a cli only debian where web interface is the only way to get gui?

Would be more convenient if this feature was apart of biglybt's web server....since most apps require root access to install which i do not have on this particular box....
