### ISSUE TITLE
file is not showing as complete in BiglyBT yet is showing as complete in Windows Explorer, yet VLC finds it incomplete

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2009]
* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment

Windows 20H2 x64
SWT v4930r7, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B2.6.0.0/4 az3

In BiglyBT, I have one .avi file that is showing that it needs 1 more piece, is showing that piece as greyed, about 1/3 of the way into the file.  97.8% complete.  However, in Windows Explorer, it's showing as a .avi file with no extension on it.  I have it set to put a .!qB extension for incomplete files.  It's got that .!qB extension for the other files that are not nearly as complete.  When I open this .avi file in VLC, VLC asks me to play as is or to rebuild the index.  I don't know if the grey piece means that BiglyBT wants to read it to verify it, or what, but I thought I would let you know so that maybe only AFTER the file has been fully verified, then BiglyBT would drop the .!qB extension.

**Comment by parg** [comment]
Hmm, sounds as if the file was completed and then after that time became corrupted somehow and reverted to downloading to fix it.

**Comment by as-muncher** [comment]
What happened is that I had an earlier torrent that had a lower amount of GB in the files, and so then when I added this current torrent to BiglyBT, I had it go searching for any files that it could integrate into this torrent from the earlier completed torrent.  BiglyBT added some numbers and letters to the beginning of this file, and for the other incomplete files, the same letters and numbers.  I'm not sure why it didn't find all the complete files, maybe because it didn't recognise a .!qB extension, although it should have, because I have the setting to have an exact match, 0 change in file size.  I was using the .torrent file that qbittorrent made from a magnet link, so maybe I would have been better to have had BiglyBT make a .torrent file from the magnet link instead?

**Comment by as-muncher** [comment]
I don't think it was downloaded fully because I had been watching it download.  I just happened to lose the connection right at that point where there was 1 block left to download.  Maybe the code actually drops the extension even though the file hasn't been fully verified?
