### ISSUE TITLE
edit path for all existing torrents

### ISSUE THREAD

**Issue by SUCM** [BiglySoftware/BiglyBT#2010]
would like to know what are the files I should edit to move quite a lot of seeding torrents' data (files and directories) to another partition/drive on windows? the paths and directory structure are exactly the same, but they are now under a new directory on another partition (ex. C:\abc.zip -> D:\BiglyBT\abc.zip)

it used to be just the d*.config, but the edited paths are not reflected on the latest Bigly when launched after the edit. exited Bigly then opening up the file shows the edit new path stays, but launching Bigly again still has the old paths on all torrents

also having the same problem with biglybt.config. I directly edited the file to update config, but the edited path in the config doesn't get reflected when launched BiglyBT

I'm using proper decoder/encoder to edit, so the files contents are not messed up

**Comment by parg** [comment]
How about selecting all the downloads and then 'move data files' to the new location?

**Comment by SUCM** [comment]
though all data files are under D:\BiglyBT, the base directory for each varies
below are some examples. hence it's kind of hard to move all to 1 place. I tried a couple torrents, but they just get messed up as Bigly creates new directories (using torrent names) for some of them and another layer of the same directory for others

D:\BiglyBT\EDF\FRKE\<Torrent A data>
D:\BiglyBT\ABD\<Torrent B data>
D:\BiglyBT\EGF\<Torrent C data>
D:\BiglyBT\EGF\<Torrent C data>\S1\<Torrent X data>

**Comment by parg** [comment]
Have you tried 'search for existing data files...' to fix them up in the new location?

**Comment by SUCM** [comment]
search for existing data files found files, but starts creating new files after the hashing. now the whole thing is a total mess...

ex. a torrent had these files
delete_dnd/a.dat.az!
b.cas.az!
c.efd.az!

after search for existing data files found files and forced re-check. now the directory has
a.dat  (this file has size of 0 bytes and was in the do not download folder as this is )
a.dat.az! (this file has size of XX MB)
b.cas
b.cas.az!
c.efd
c.efd.az!

**Comment by parg** [comment]
:( Should always move downloads through the BiglyBT interface, not by hand and then try and recover things...

Obviously there's an issue there with DND files.

**Comment by SUCM** [comment]
all of the DND files under delete_dnd directories of each torrent had their file size zero out

I was expecting to be able to change path for Bigly to pick up as the older versions did. idn't expect the new version would be so hard

**Comment by SUCM** [comment]
think there is a bug with Bigly's move data file

if I added torrent and changed data file name(s) in the new torrent dialogue, Bigly will look for the original file after move data file, not the file names that I had changed to

**Comment by almanteka** [comment]
> 
> 
> think there is a bug with Bigly's move data file
> 
> if I added torrent and changed data file name(s) in the new torrent dialogue, Bigly will look for the original file name after move data file is done, not the file names that I had changed to

i noticed that! i change the name on the add new torrent window and BiglyBT still uses the old name under library view. as a workaround i just select all the torrents and use right-click menu organize > rename and select all the options, click on use for the name i need and click ok. maybe we need an option to change the Display Name, Save Path and *.torrent all at the same time when adding a torrent or maybe the automation is broken some how!

**Comment by parg** [comment]
I'm not seeing that

**Comment by SUCM** [comment]
I see that issue when the data file hasn't been created due to download not started yet

**Comment by parg** [comment]
weird, that's exactly the scenario I tested
