### ISSUE TITLE
Option to move/backup torrent to a sub-directory of the actual files.

### ISSUE THREAD

**Issue by Dramaman** [BiglySoftware/BiglyBT#2011]
It could be useful to have an option to backup the torrent files to a subdirectory relative to the completed files. This could be a global feature or a tag feature.  that way, if your plan to reseed the torrent down the road, it would be easier to find. This is just an automated organization feature.

**Comment by almanteka** [comment]
you can move the files to a folder after completion using tags to organize them or use the option to move to a global location.

i'm using BiglyBT on advance mode, here are the options on a tag for files and *.torrents

![tag folders4](https://user-images.githubusercontent.com/42816936/108630380-f149c180-743a-11eb-9cf3-afafc79f645a.jpg)

and the options for files on the tools > options > files menu to add them globally
for data:

![tag folders3](https://user-images.githubusercontent.com/42816936/108630494-71702700-743b-11eb-8a42-296e25825442.jpg)

for *.torrents:

![tag folders2](https://user-images.githubusercontent.com/42816936/108630530-99f82100-743b-11eb-8742-9bac4c32b458.jpg)

**Comment by Dramaman** [comment]
thanks, I'm speaking of an option to move the torrent file to folder or a sub-folder of the downloaded file (or parent folder in the case of single file downloads), but might be fine with this option too

**Comment by almanteka** [comment]
ok, i think i know now what you're looking for! move or copy the *.torrent file to the downloaded folder. on my previous post the *.torrent goes to the parent folder if using the tag option. something like this

![tag folders5](https://user-images.githubusercontent.com/42816936/108643365-b5394f80-7480-11eb-9bfd-6302c481b42d.jpg)

and you're looking for something like this, inside the downloaded file folder

![tag folders6](https://user-images.githubusercontent.com/42816936/108643376-c2563e80-7480-11eb-9aa5-45b5f0ccd95b.jpg)

the coders of BiglyBT can answer if that is possible!

**Comment by magicmana** [comment]
not a coding  problem ,  torrent  not  use  all  the time a directory.
in this  case  where store  the  torrent  file ?
for sample   if you have 3 movie on your harddrive...
c:\torrent\mymovie1.avi
c:\torrent\mymovie2.avi
c:\torrent\mymovie3.avi
where store the torrent ?
c:\torrent\.torrent\mymovie1.torrent
in this case  in ".torrent"  you will  have "mymovie1.torrent" , "mymovie2.torrent"  and ""mymovie3.torrent""

**Comment by Dramaman** [comment]
if you don't have a folder, perhaps provide the option to create one and move the torrent and single file to that folder, relative to where the torrent would have initially being saved

**Comment by magicmana** [comment]
that  i want to to tell , is that , i'm  not  sure that ,  a lot of people  to have saved  torrent  dispached in some case in some  directory ,  in some case  in other...

you have already  the ability  to  store  all torrent in  a same directory ; and  use your  operating  system search file  engine.

and if you want  specific   things ,  your already  the  ability to make some scripts on  your computer  ;-)



my personal  case  in  not representative and  i don't  need that...
- my  torrent or magnet are  automatically   grabed from  the net  on a linux server.  and  stored in  a mysql  database.
- a   script  i  had made  , choose for me  every  10mn. ; torrent  who  "perhups" interrest  me..  and  past torrent  file , via network to another  windows computer  with  biglybt  .
- biglybt  check  the  forder every mn and add torrent in biglybt with stopped status
- i start manually  torrent i  need , and delete other.  
- all torrent  complete  who are  remove from biglybt as  moved to an  specific  directory   with  the "move on  remove" in tag option .
 - and  finally  i  have a  windows planed task   who start a script  every 10 mn  , who  clean  all  "  .dnd_az! " folder  in all  finished  directory and move   the "purged"   directory to  my  "tv media server" by  the  network...

**Comment by almanteka** [comment]
> 
> 
> not a coding problem , torrent not use all the time a directory.
> in this case where store the torrent file ?
> for sample if you have 4 movie on your harddrive...
> c:\torrent\mymovie1.avi
> c:\torrent\mymovie2.avi
> c:\torrent\mymovie3.avi
> 
> and a movie4.avi who use c:\torrent\mymovie4\mymovie4.avi
> 
> where store the torrent ?
> 
>     * in "torrent"
>       you will  have 2  directory :
> 
> 
> " c:\torrent\torrent\ " with mymovie1.torrent , mymovie2.torrent, mymovie3.torrent
> and
> " c:\torrent\mymovie4\torrent\ " with mymovie4.torrent
> 
> not really interesting.
> 
>     * on parent folder ?
> 
> 
> store the torrent in " c:\ " ? not really interesting too...
> and if you have like me a complete disk " e:\ " reserved to torrent ....
> what is the parent directory of " e:\ " ?


i didn't say that was a coding problem! i said that the coders are the only ones who can answer to the OP request!

**Comment by parg** [comment]
It is a bit of a problem to put the .torrent file into the same folder as a multi-file torrent's data, it doesn't belong there. 

If you went and tried to move the download's data somewhere else via BiglyBT (move data files...) then any unexpected file in the download's folder will not be moved and cause the containing folder to be retained. If the torrent happens to be subsequently moved as well the containing folder won't be deleted...

I can understand your logic regarding having the .torrent file handy for re-seeding but the implications of automation to do that make things too messy.

I can't think of a good solution, the data and the torrent are separate entities and live their own lives - you can move the data, you can move the torrent, but trying to tie the two together would have lots of consequences.

**Comment by Dramaman** [comment]
no problem, it was just a thought.
