### ISSUE TITLE
Quick Rename

### ISSUE THREAD

**Issue by almanteka** [BiglySoftware/BiglyBT#2013]
Java 15.0.2 (64 bit)
  Oracle Corporation
c:\program files\java\jdk-15.0.2

SWT v4930r7, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.6.0.1_B37/4 az3

noticed that quick rename on the add torrent window includes the file extension in the auto-selected text

![quick rename01](https://user-images.githubusercontent.com/42816936/108666967-c305c980-74ae-11eb-995a-292d675a408f.jpg)

when using quick rename from files, the extension is left out

![quick rename](https://user-images.githubusercontent.com/42816936/108667162-fb0d0c80-74ae-11eb-9ec9-d3d57a0a6306.jpg)

any chance to apply the same behaviour from the files area to the add torrent window? that way if i paste the desired name, i don't left the file without the extension! thanks!

**Comment by parg** [comment]
sure

**Comment by almanteka** [comment]
thanks for considering! if there is any reason why the quick rename option is not available when we select more than one file in the add torrent window? in the files area is possible, any chance to add that option too? sorry if i'm asking too much!

**Comment by almanteka** [comment]
just downloaded B38! thanks for including the extension suggestion!

**Comment by parg** [comment]
sure, I'll add support!

**Comment by almanteka** [comment]
wonderful! noticed that you added support for multiple renaming in add torrent window on B39! thanks!

**Comment by david-bakin** [comment]
This dinky little change to _not_ selecting the extension makes such a big different to my workflow when adding torrents, thank you!

**Comment by parg** [comment]
\o/
