### ISSUE TITLE
Auto-prioritize now runs when _re_Queuing a torrent after it has been stopped, not just at the initial torrent launch

### ISSUE THREAD

**Issue by david-bakin** [BiglySoftware/BiglyBT#2015]
[Windows Server 2016 Datacenter. BiglyBT Beta (2.6.0.1_B37).]

This just started happening the last day or two.

I use the option "Auto-prioritize files with [extension]" - usually it is set to something like ".jpg,.jpeg,png.gif".  Works fine in the past - all such files have been prioritized High before the torrent first starts.  Then, sometimes, I watch while the torrent is running (i.e., gettting data off of peers) and when a file is complete (any file, not just these with the auto-prioritize) I manually set it to priority = Low.  And then, by god, it _stays_ there, no matter how many times I stop and start the torrent.

Except now it _doesn't_.  _Now_ completed files keep priority = Low when the torrent is stopped, but as soon as I restart it (Queue) all the completed files with the given extensions pop up to priority = High.  They shouldn't do that ...  

P.S. Completed files which had some other priority, e.g., Normal, and which are _not_ enumerated in the auto-prioritize list keep their (manually assigned) priority = Low.

P.P.S. I'm also observing that auto-prioritize is _not_ actually running when torrents are added ...

P.P.P.S. What is "auto sequential" that you can provide extensions for?

**Comment by parg** [comment]
This is one of these "this hasn't changed recently" things - indeed, looking back through code history it would appear that it has always applied the prioritization when a download starts - it is in the 'allocation' code that is checking that files exist as required.

The priority is irrelevant once a download is complete (it only affects download priorty, not seeding) so while you might find it a bit annoying it isn't affecting anything....

**Comment by parg** [comment]
auto-sequential causes the pieces of files to be downloaded sequentially. Not generally very useful but someone wanted it once upon a time.

**Comment by david-bakin** [comment]
I coulda sworn it was different before.  I need to think about this ...
