### ISSUE TITLE
Write permissione to mounted storage

### ISSUE THREAD

**Issue by sberta** [BiglySoftware/BiglyBT#2016]
Using BiglyBT as torrent client on Nvidia Shield it is not possible to write to mounted network storage (i.e. NAS).
According to there should be an api that allows an application to ask from write permission to mounted storage. Is it possible to add the api to the client?

**Comment by TuxPaper** [comment]
Unfortunately, all the mounted storage on the nVidia Shield are read only, even when we request write permissions.  We've noticed that apps like Plex can write to SMB network shares, but apparently they create their own connections and don't use the shield's built in one.
