### ISSUE TITLE
[Feature Req] Custom list of trackers appended to new downloads

### ISSUE THREAD

**Issue by Hideman85** [BiglySoftware/BiglyBT#2017]
Could you add the configuration for adding a custom list of trackers to new downloads?

**Comment by parg** [comment]
See https://github.com/BiglySoftware/BiglyBT/wiki/Tags#tracker-templates

To only apply to new downloads set the Tag constraint 'scope' to 'new downloads only'

**Comment by Hideman85** [comment]
Whoa it looks to be a cumbersome process but I'm gonna have try later. Thanks for the resource :)

**Comment by zero77** [comment]
This may be of help.
https://newtrackon.com/
