### ISSUE TITLE
RSSFeed Scanner's "Test" button only works if the filter is Enabled, somewhat defeating point

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#2018]
This is a relatively minor one (yay!), but something I just happened to notice — or _re_-notice, probably, as I can't imagine I never caught on to this before.

Because RSSFeed's Filter configuration can be somewhat complex, its Options tab provides a handy "Test match" field for evaluation purposes. You can give it a sample title for an item on the feed, then hit the "Test" button to determine whether the filter definition performs as expected. Great idea!

Unfortunately, the "Test match" functionality is dependent upon the Filter being "**Enabled**", which kind of defeats the purpose of testing your filter logic (something you'd ideally want to do _before_ enabling it for the first time).

Observe, the results of hitting "Test" with the same "Filter" string, same "Test match", only difference in configuration is whether "Enable" is switched on or off:

![Screenshot from 2021-02-25 11-38-41](https://user-images.githubusercontent.com/538020/109185937-7811dd80-775e-11eb-9552-5f144c4c6a4a.png)
![Screenshot from 2021-02-25 11-38-48](https://user-images.githubusercontent.com/538020/109185942-79430a80-775e-11eb-9c7b-7baf8ebae1f3.png)

It'd sure be neat if "Test" could be used without first having to enable the unproven filter.

#### Requisite 'System' block:
```
Java 11.0.10 (64 bit)
  Red Hat, Inc.
/usr/lib/jvm/java-11-openjdk-11.0.10.0.9-0.fc33.x86_64

SWT v4934r6, gtk/3.24.25, zoom=100, dpi=96
Linux v5.10.16-200.fc33.x86_64, amd64 (64 bit)
B2.6.0.1_B40/4 az3
```

**Comment by parg** [comment]
Try version 1.7!

**Comment by ferdnyc** [comment]
Sho'nuff! Thanks!

P.S> I hacked up a fix for another issue that's been bothering me, there's a PR open at BiglySoftware/BiglyBT-plugin-rssfeed#4 if you have a mo'.
