### ISSUE TITLE
Logged in but can't vote at "https://vote.biglybt.com/"

### ISSUE THREAD

**Issue by dbareis** [BiglySoftware/BiglyBT#202]
Simple as that. Clicking the "Vote" button on any issue refreshes the page (vote count not updated).

It shows the text "Logged In as" followed by my picture.

**Comment by TuxPaper** [comment]
Should be fixed now.  Vote away! :)

**Comment by iav** [comment]
Still there

**Comment by dbareis** [comment]
I am now getting "You need to authorize your GitHub account in order to vote".

I log in I authorise it, I try to vote and get the error.  I have disabled my add blocker and reset all cookies for "https://vote.biglybt.com/", no change.

**Comment by TuxPaper** [comment]
Should once again be working

**Comment by dbareis** [comment]
seems to work now
