### ISSUE TITLE
Tooltip (Hoverbox) for Status Column Displays Seeding Rank

### ISSUE THREAD

**Issue by EarthBoundX5** [BiglySoftware/BiglyBT#2023]
* Windows Server 2019
* BiglyBT Version 2.6.0.1_B42

System
> Java 1.8.0_202 (64 bit)
>   Oracle Corporation
> c:\program files\biglybt\jre
> 
> SWT v4930r7, win32, zoom=100, dpi=96
> Windows Server 2016 v10.0, amd64 (64 bit)
> B2.6.0.1_B42/4 az2

When hovering over items in the Status column, information from the Seeding Rank is shown.  Hovering over Seeding Rank shows nothing.  This is the same for both the Downloading and Complete sections.  This was functional before, and is important when relying on small column widths.

Displaying issue below, using only plugin updates and core BiglyBT update as content.
![image](https://user-images.githubusercontent.com/2718666/109488610-67f24a80-7a4b-11eb-9144-e008f7283ec1.png)

**Comment by parg** [comment]
AFAIK all that has changed is that some of the seeding rank info has been added to the status column tooltip, the existing tooltip for the seeding rank column hasn't changed (if you don't have seeding rank debug enabled the 'tooltip' is just shown when the content doesn't doesn't fit available space.

Or are you complaining about something else?

**Comment by parg** [comment]
Ah, maybe I got it, you want the status to show the status not just the rank info...

**Comment by parg** [comment]
Back next beta

**Comment by EarthBoundX5** [comment]
Yep, that was my issue.  Status should show Status for the tooltip.  This has been the case all the way back in the Azureus days, haha.

I'm guessing somehow these tooltips just got mixed up in one of the Betas?

**Comment by parg** [comment]
I added the seeding rank clue to the status tooltip but in doing so lost the default 'show text when column too narrow' part of things

**Comment by EarthBoundX5** [comment]
Just updated to 2.6.0.1_B44 and now see Status in the tooltip as expected!  Stilling seeing rank info, but I'm guessing maybe this wasn't so much a mistake, but maybe was just a request not fully thought out?  Regardless, my issue / bug is resolved by this update!

![image](https://user-images.githubusercontent.com/2718666/109580870-f3f28980-7ac0-11eb-9aa0-15c645cd22e9.png)

Not sure what "lost the default 'show text when column too narrow'" means, but if there is any testing or anything I can do for that aspect, please let me know!

**Comment by parg** [comment]
If you're happy that the status is back in the tooltip then job done. I added the seeding rank info as I am bored of answering the 'why is my torrent queued/...' question and making it a configurable option is pointless as if they can't figure out why it is queued/... then they won't be able to figure out how to turn the option on,

**Comment by parg** [comment]
(and no, I'm not adding an option to turn it off!)
