### ISSUE TITLE
Biglybt terminates

### ISSUE THREAD

**Issue by mwessels93** [BiglySoftware/BiglyBT#2025]
* Ubuntu LTS 20.04
* BiglyBT V2.6.0.0

System:
Java 15.0.2 (64 bit)
  Oracle Corporation
/home/torrenter/java/jdk-15.0.2

SWT v4934r5, gtk/3.24.20, zoom=100, dpi=96
Linux v5.8.0-44-generic, amd64 (64 bit)
B2.6.0.0-00/4 az3

First off, I love BiglyBT and the work you are doing. That said, I do not have a whole lot Linux experience so I hope I can keep up.

BiglyBT was working fine for the first weeks. Then it started crashing after about a night of running. At startup I get some warnings and when I log back into my VM the next day, the terminal states 'BiglyBT terminated' and the application is closed.  
What I tried:
 - reinstall the entire VM
 - upgrade from OpenJDK 11 to 15
 
 It also seems that this issue has caused my OS mounted drive run out of space. Biglybt is the only application running on this VM.

The startup log is attached, as well as the crash dump. If you require any more information, please let me know and I will provide it as soon as possible. 
[debug.zip](https://github.com/BiglySoftware/BiglyBT/files/6062928/debug.zip)
![Disk analyzer (1)](https://user-images.githubusercontent.com/22075043/109525826-32cd1300-7ab2-11eb-9fe6-d112e31da313.png)
![Disk analyzer (2)](https://user-images.githubusercontent.com/22075043/109525833-3365a980-7ab2-11eb-8f58-a2d284030b42.png)
[launch cmd log.txt](https://github.com/BiglySoftware/BiglyBT/files/6062929/launch.cmd.log.txt)

**Comment by parg** [comment]
You're not using BiglyBT, you using "BiglyBT Extreme Mod". This is nothing to do with us, you would need to ask whoever develops it for support.

If I was to make a random guess I'd say you were running out of Java VM heap memory and need to increase it.
