### ISSUE TITLE
change "see Privacy View" to "see Privacy tab"

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2026]
* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4930r7, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B2.6.0.0/4 az3

I see when I am trying to download one torrent, that there is a small little icon that says "1 or more I2P peers, see Privacy View for anonymous downloading options".  Perhaps could you change that to "see Privacy tab" or something to indicate that it's the Privacy tab when you select that torrent, and there are all those other tabs like "General", "Peers", "Swarm", etc.  I was trying to figure out how to get to the Privacy View, and so I selected View from the drop down list near the top of the window, next to "File", and was looking for the Privacy View there and didn't find it.

**Comment by parg** [comment]
If changing a translation didn't result in the loss of all other language versions I would consider it.

**Comment by as-muncher** [comment]
All those other translations will be updated anyways, because I'm sure you will still add new messages to BiglyBT.  You might as well change it and not let yourself be put into a cage.  It will clear up some confusion.

**Comment by parg** [comment]
Thanks for the advice
