### ISSUE TITLE
info about B48 new options

### ISSUE THREAD

**Issue by almanteka** [BiglySoftware/BiglyBT#2029]
Java 15.0.2 (64 bit)
  Oracle Corporation
c:\program files\java\jdk-15.0.2

SWT v4930r7, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.6.0.1_B48/4 az3

B48 is online and new options added:
2601_B48

> Option to specify additional incoming bind addresses
> Option to ignore bind addresses for outgoing LAN connections

any info about it available? Option to specify additional incoming bind addresses can help people with VPNs that change the interface with the type of connection. how to add multiple entries? comma separated? 
thanks for always enhancing the BiglyBT experience!

**Comment by parg** [comment]
The options are specifically aimed at getting LAN connections working between two BiglyBT clients that are running VPNs - see https://github.com/BiglySoftware/BiglyBT/issues/1933

Semicolon separated by the way
