### ISSUE TITLE
Search result screen Add/Edit Templates list

### ISSUE THREAD

**Issue by googlenews** [BiglySoftware/BiglyBT#203]
The pop up screen showing Add/edit sites list is not scrollable, even after extending the window to maximum height, still some of the list that is not visible nor scrollable . 
* MacOS 10.13.3, x86_64
* B1.2.0.1_B27/4 az3

**Comment by parg** [comment]
Indeed, that needs a redesign. In the meantime you can delete templates by right-clicking on them in the search results, if that would help.
