### ISSUE TITLE
biglybt won't recognize complete files

### ISSUE THREAD

**Issue by eddilara** [BiglySoftware/BiglyBT#2031]
Im on newest windows 10 build
and newest biglybt version as of march 5
2601 beta 49
and it doesn't wanna see the files are complete in the folder...they are in what Im guessing is a korean font folder
S:\가자! 우주전함 야마모토 요코 
I downloaded them else where and ran a crc check on them so I know they are complete
but for some reason when I copy them over to the korean folder that bigly is using..it won't see the files are complete after I run a recheck on them
Im guessing it has something to do with them being in a non english font folder

* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment

**Comment by parg** [comment]
Does it see them as 0 percent and create new files? i.e. is it failing to detect that the file exists (due to some name issue)?

In general BiglyBT handles non-ascii file names well.

**Comment by eddilara** [comment]
> Does it see them as 0 percent and create new files? i.e. is it failing to detect that the file exists (due to some name issue)?
> 
> In general BiglyBT handles non-ascii file names well.

Ive tried quit a few ways to get bigly to recognize the files...but doesn't seem to wanna see them
it does seem like it sees the files...cause it doesn't create new ones...but it won't see that the files are complete
and Ive triple checked all the files with crc (the files are anime...so they have the crc in the file names)

**Comment by eddilara** [comment]
update:
there must be something really wrong with the files cause I just used multipar to check the files again the other set of files...and they aren't even close
second update....yep the files in the torrent are bad.....I didn't check them..only the other files I downloaded...stupid me

**Comment by parg** [comment]
\0/
