### ISSUE TITLE
Listening port 6880 error.

### ISSUE THREAD

**Issue by PLMQ2785** [BiglySoftware/BiglyBT#2032]
* OS and version
* => Windows 10 Pro, 20H2 / 19042.844 / Windows Feature Experience Pack 120.2212.551.0
* BiglyBT Version Number
* => Cannot Check the version, due to cannot run the program, but latest version installed.
* For *nix: Desktop Environment

Error occurs when i start the program
![asdf](https://user-images.githubusercontent.com/12977700/110238868-3fa4a780-7f87-11eb-8a19-42e23f495da6.png)

I confirmed that no other process is using the port 6880.
AV(Kaspersky) / Windows Firewall allows all BiglyBT port access.

And.. I found a thread in a similar situation and tried it, but it didn't help.
Refer.
https://github.com/BiglySoftware/BiglyBT/issues/1355

**Comment by parg** [comment]
Did you try the advice in that other issue?

1) run from the command line
2) change the instance port from 6880 to something else

Something is preventing BiglyBT from listening on port 6880 regardless of what you say...

**Comment by magicmana** [comment]
if can  help ....
is biglybt installed on  amovible  media /  crypted  media ?
on  windows default  firewall system   :
  if  you  make a rule for an   executable  "toto.exe"  located on disk L:\
but  if  the disk L:  are monted  after  the windows  firewall service start 
in  firewall  console the rule  for "toto.exe" are  visible   ,  but    the  rules don't work.
  you  need to disable/enable the  rules  , or restart the service ,  after  mount your  disk

**Comment by skycommand** [comment]
I've been experiencing the same problem.

- Restarting the computer seems to make it go away, but closing every other app or even logging off doesn't help.
- When restarting the computer is not an option, you can tweak the control port
    - Running these commands from the Command Prompt helps:

       ```cmd
        cd "C:\Program Files\BiglyBT"
        .\jre\bin\javaw.exe -cp "BiglyBT.jar;commons-cli.jar;swt.jar" -Dazureus.instance.port=16889 com.biglybt.ui.Main
        ```

    - If you prefer PowerShell, here is the one-line launch command:
        ```PowerShell
        Start-Process -FilePath 'C:\Program Files\BiglyBT\jre\bin\javaw.exe' -WorkingDirectory 'C:\Program Files\BiglyBT' -ArgumentList '-cp "BiglyBT.jar;commons-cli.jar;swt.jar" -Dazureus.instance.port=16889 com.biglybt.ui.Main'
        ```
    - **You may have to tweak Java's path, though.**

**Comment by skycommand** [comment]
The issue seems to have disappeared after updating my Firefox add-ons.

**Comment by as-muncher** [comment]
Also now getting this error.  @parg perhaps you could make it a hyperlink in the warning box, so that I can just right-click it, choose "copy link" and then paste that into my web browser?  or just click on the link directly that will open up the web browser?  Or maybe there are privacy reasons for not doing so...   Couldn't you just write in the code to have BiglyBT then offer to change the port?  That would be so much easier.

**Comment by as-muncher** [comment]
Nope, BiglyBT said it had to restart because of a major update, still getting this error.  Thank you to @skycommand for posting the one line powershell command.

**Comment by skycommand** [comment]
My pleasure.

By the way, the link in the screenshot is wrong. The correct link is:

<https://github.com/BiglySoftware/BiglyBT/wiki/Command-Line-Options>

**Comment by as-muncher** [comment]
I was getting this 6880 error last night when I was manually transferring torrents from qbittorrent to BiglyBT.
First of all, the file association wasn't working correctly.  I'd double-click on the .torrent file and it would open in qbittorrent, even though it had a BiglyBT icon.  So, I right-clicked, properties, select BiglyBT again.  
Then, I would cut the data folder or files from my qbittorrent save directory to my biglybt save directory.  I would then double-click on the torrent's .torrent file, and then usually have to delete the "-1" appended as an alternative directory, and click "OK", then get the warning that data will be modified, click "OK".  Sometimes the torrents would check automatically.  Sometimes, they'd start at 0.0% even though there was data there, so I'd have to manually pause the torrent, then force re-check using the yellow recycle icon.  Even though I had my screenshots fully downloaded, sometimes BiglyBT would say that only 1/2 was downloaded.  Sometimes, BiglyBT would allocate out all the files in the torrent, even though I have that turned off, so I would see all these files having data, but the actually data on disk is less than the data stated.  Sometimes, while one torrent was checking, and it got to 77.7% or some other percentage, it would stop immediately when I added another torrent, which later one it checked first, then resumed the older torrent checking.  After about 10-15 .torrent files that were added by double-clicking them and them showing up in BiglyBT, I would get this listening port error message for port 6880.  However, when I drag the .torrent file into BiglyBT, that would always work, but with this error, when double-clicking on a .torrent file, it would take so long, nothing happening, Biglybt not opening up the file, and then maybe getting this 6880 port error.  Restarting Biglybt seemed to help, but I wonder if it was some other reason.  Maybe AVG Antivirus?  Just this morning, it wanted to update the application, so maybe it's a problem with it.  I don't know.

**Comment by parg** [comment]
It isn't a problem with BiglyBT.

I recently did a Windows update and on restart was getting TCP listen port errors (address already in use on whatever port I tried). 

I tried everything I could to fix it.

Only when I rebooted Windows did the problem go away. Still none the wiser.

**Comment by jbae-89** [comment]
I was having the same issue on Windows 10.

**Issue:** 
Error "There appears to be another process already listneing on socket... " when attempting to run BiglyBT from magnet links.

**Troubleshooting:**
Upon further investigation when I click a magnet link I immediately see the BiglyBT process open with TCPView but it doesn't open or provide any functionality for an extended period of time. After waiting for a while the client will eventually launch displaying errors about the TCP network manager and suggesting that the program is being firewalled. However my firewall is completely disabled. 

**Resolution:**
Reinstall VPN software, enable firewall and then whitelist Bigly and VPN software, reboot. 
This is a very hand-wavy fix but it's the only thing that worked for me. 

Just to reiterate, this is _NOT_ an issue with BiglyBT.

**Comment by PetrMachek** [comment]
I'm getting this error also, but what I see in TCPView, that BiglyBT opens port 6880 successfully, then 2sec after this BiglyBT try to open this port again, then appears the window with the error.
![image](https://github.com/BiglySoftware/BiglyBT/assets/5977442/a98620d7-e06a-45f6-9af5-be55f42e9caf)

This problem occuring from time to time on my PC, but restart usually helps.

**Comment by JonEvanCook** [comment]
I am seeing the same problem as PeterMachik BiglBT this started just recently after a Win!0 update I believe, my last update was KB5033372. I'm not sure if this is related to the problem but it seems a bit coincidental. I uninstalled BiglyBT and reinstalled and so far so good. The next restart will be the real test though.
