### ISSUE TITLE
Please implement BEP 21 (partial seeds)

### ISSUE THREAD

**Issue by paxter** [BiglySoftware/BiglyBT#2037]
It's not possible for trackers to determine if a client is leeching or just partial seeding.
Most clients support that behaviour (afaik rtorrent not).

https://www.bittorrent.org/beps/bep_0021.html

Thanks!

**Comment by as-muncher** [comment]
Perhaps with partial seeding, I might be able to get a few .torrent files that I otherwise might not get for a long time.  I think right now they're just coming from confirmed seeders.
