### ISSUE TITLE
Diff dlhistory and config files?

### ISSUE THREAD

**Issue by Omni-Consumer-Products** [BiglySoftware/BiglyBT#2038]
Hi Parg,

Sorry for opening this as an issue - it's just a question but I didn't see a place for questions.

I had a hard drive crash so I didn't have the opportunity to do a proper backup.  I started using Bigly from scratch on my new hard drive, but now I have been able to recover my config directory from my old hard drive.

I'd really like to compare my old settings with my new ones and restore my download history without losing the history I've created on my new hard drive since the crash.  It would also be nice if I could see the torrents I was actively downloading at the time of the crash so I can start them over.

I'm thinking:
biglybt.confg - settings
dlhistorya.confg - torrents that are actively being downloaded - is that right?
dlhistoryd.config - torrents that are done being downloaded - is that right?

But since they're all binary files it's tough to compare the old files and the new ones.   I could probably get through dlhistorya.config as binary since I just need a list of the active downloads and I could pick out the text strings, but trying to diff the config or the dlhistoryd files with their old versions would be really difficult.

So my question is: is there any way to convert the binary files to plain ascii so I could diff them?  Or do you know another way to compare the dlhistory and config  files?

Thanks much!

**Comment by parg** [comment]
The files are 'bencoded' - you can convert them to JSON (slightly more readable) via a tool in the Help->Advanced menu

Hope that helps!

**Comment by Omni-Consumer-Products** [comment]
That should work.  I can convert to json, edit the files in pspad (I can't find a diff tool that will work - stuck merging by hand), then convert back to bencode.   Hopefully the json pretty print format conversion that pspad does won't affect the conversion back to bencode.

Thanks again!

**Comment by parg** [comment]
Good luck!

**Comment by Omni-Consumer-Products** [comment]
Thanks!  One more question: I can't seen to discern an order for the entries in the dlhistory files - I see entries with added (a) and completed (c) dates from all different times in seemingly random order.  I think z is a torrent ID of some sort, and I'm not sure about most of the other numerical values but they don't seem like they are used to sort the entries either.

My question is: can I just put the entries from my new dlhistory file at the end of the old dlhistory file (the one I plan to use as my new merged file) - or do the individual entries from the new file need to be placed in the old file in some specific way to keep the file valid?

**Comment by parg** [comment]
"u" is a unique ID - it is formed from part of the torrent hash and the 'added to BiglyBT' time.

"z" is total torrent file size
"h" is torrent hash
"v" is torrent v2 hash (unlikely to have any of these)

"n" is torrent name in utf-8
"s" is save location in utf-8

"a" is add time
"c" is complete time
"r" is removal time

"t" is a list of tag names in utf-8

There is no particular order in the stored entries, the "unique id" is the thing used to identify entries, if you happen to have two entries with the same uid then the second one encountered will be used.

**Comment by Omni-Consumer-Products** [comment]
Perfect.  Thanks!
