### ISSUE TITLE
I cannot add movies in my [TV] Samsung 6 Series (55) (QE55Q6FAM)

### ISSUE THREAD

**Issue by 74lobster** [BiglySoftware/BiglyBT#2039]
Hi,

I cannot add movies (mostly mkv) in my [TV] Samsung 6 Series (55) (QE55Q6FAM)

![bigly](https://user-images.githubusercontent.com/68000642/111484524-22659b00-8736-11eb-8e20-9fb7fee82fa0.jpg)
![bigly2](https://user-images.githubusercontent.com/68000642/111484528-22fe3180-8736-11eb-823e-ec8c88443dae.jpg)

Miss some plugins ?

Please take a look and update me.

Thanks a lot

* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment

**Comment by NaPurHab** [comment]
I've played with this feature on and off for years. Never works for me. My advice is to see if your Smart TV has the PLEX Player App on it. If it does, it is a simple matter to setup a PLEX Media Server on your computer.  Then you use the App on the TV to select what you want to watch. PLEX takes care of any Transcoding Issues for you. So Smooth Sailing.
Note that PLEX is FREE for in Home Streaming. If you want to Stream Outside your home (on the go, Friends, Family) then you need a PLEX Pass. If you go for that, try the monthly to see if your happy with Streaming Outside the home. A Lifetime PLEX Pass is about the cost of 3 Annual PLEX Passes. So if you find you will be using it for years, its a good deal.
For now I would skip the PLEX Pass, unless you have Friends and Family you want to stream to. As with the Pandemic, most of us are not on the go.
Stay Safe.
