### ISSUE TITLE
Menu bar icon still not visible in dark theme mode 

### ISSUE THREAD

**Issue by googlenews** [BiglySoftware/BiglyBT#204]
Pretty straight forward, the BBT menu bar icon does not show up when user switch to dark theme mode. The mouse over show the data and icon is there but it is invisible and creates a blank space. 

MacOS 10.13.3, x86_64
B1.2.0.1_B27/4 az

**Comment by deus0ww** [comment]
This really is an annoying bug.

![macdarkmodeicon](https://user-images.githubusercontent.com/6702585/37709676-8bc1f158-2d3d-11e8-8f43-d8bdaf8b7e88.jpg)

**Comment by googlenews** [comment]
Yeah. I reported this bug a while back. I really like dark mode.

**Comment by deus0ww** [comment]
Why did you close this? It's definitely still a bug.

**Comment by googlenews** [comment]
I didn’t realize this was logged as “closed” it certainly still is a bug. :(
