### ISSUE TITLE
Search For Existing Data Files (SFEDF) efficiency/optimization possibility?

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#2040]
This isn't any sort of report or request, think of it more like an RFC, or me thinking out loud (and hoping to possibly spark ideas in others).

I normally use SFEDF with fairly small files (though potentially a lot of them), but today I happened to have the opportunity to use it with a torrrent containing multi-gigabyte files, so its behavior and interaction with the filesystem / torrent management was more obvious. Here's a step-by-step account of the process:

1. Imported the torrent in a Stopped state
2. Went into its Files tab view, and started SFEDF on the entire set of files (by right-clicking the root parent, in Tree view)
3. Selected Link match handling, pointed it at my source directory, and fired off the scan
4. Of the 20-something large files in the torrent, there were (as expected) 6 matches, each at least 0.9GB in size. **Each potential match was detected by its size, fully scanned against the torrent manifest (a slow, tens-of-seconds process for each, due to the file sizes), then confirmed as an existing file match** and linked into the torrent.
5. When that process was done, and I had 6/20 files linked, I deselected whatever remained that I didn't want to download, and left the (one) file that I _did_ want to download enabled.
6. **As I was doing this, I noticed that the linked existing files were gradually progressing upwards from 0% completion, because when I completed SFEDF it initiated an automatic piece re-check on the torrent.**
7. **Once the re-check was finished, they'd all reached 99.0%-or-better completion (due to border pieces shared with adjacent files not being complete)** and were ready to be shared when I started the torrent (which I then did).

The bold parts in steps 4, 6, and 7 are the thing I want to focus on. As I said, the existing-files scan process is a slow one with large files, because much like during a re-check, it's necessary to checksum every piece of the file for consistency with the torrent index.

In fact, that process is so much _like_ a re-check, that in all honesty it basically **IS** a re-check, making the one that occurs on the torrent immediately afterwards sort of redundant. So, I'm wondering if it's possible for SFEDF's scans to _be_ a re-check (instead of merely approximating one), and for them to populate the necessary data structures so that the files in question exit the process (or "enter the torrent", if you want to think of it that way) with their eventual 99%-or-better completion level (not counting border pieces) rather than 0%, and don't have to be immediately _re_-scanned in their entirety just to update the piece map?

Like I said, just a thought I had, watching the process occur in much slower motion than I normally see it when working with small, tens-of-megabytes sized files. (Any optimization of this type would be far less effective there, due to the relatively high percentage of border pieces.)

**Comment by ferdnyc** [comment]
One issue I already spotted, myself, with this idea:

Using the matching scan as a piece re-check sort of implies that the candidate is _assumed_ to be a match for the torrent, because (unlike in a normal re-check) any failures don't represent incomplete pieces, they represent a mismatch that results in the _entire_ file being rejected as a candidate. Which means the completion status of all pieces is irrelevant (including, and especially, any pieces that _did_ match); all piece status based on that failed candidate file should be discarded. Candidate matching-scan results really don't become torrent piece check results UNTIL and UNLESS the scan produces a match.

So, I recognize the complication there. And perhaps it's reason enough to reject this idea as unworkable.

**Comment by parg** [comment]
Sorry for the delay, I didn't want you to think that I hadn't read it! 

I suppose one possibility would be for the candidate matching phase of the process to only require some subset of piece hashes to verify successfully rather than the entire file... The risk of course being that an incorrect candidate selection is made and you end up with a download that contains the wrong file and potentially gets overwritten should the download be started.
