### ISSUE TITLE
Cant figure out Tags

### ISSUE THREAD

**Issue by pto199** [BiglySoftware/BiglyBT#2043]
Sorry this doesnt appear to be a bug per say, but I cant find any discussion forums for Biglybt.

I'm having trouble figuring out how to get a tag to delete my torrents after X amount of time.  I setup a tag with a constraint and the torrents are added to the Tag after the conditions are met, but then when I right click on the tag and select "execute on assign" I'm only given the options to Start,force start, not force start,stop,pause and resume the torrent, but not delete.  I noticed the "removal policy" at the bottom under limit settings but not sure how to execute those?  I, trying to have the tag delete my torrents after 12 days of seeding (Delete the data and remove from the library)

![Untitled](https://user-images.githubusercontent.com/77364088/111727186-a21f6280-8827-11eb-86a9-c8083392ae7b.png)

**Comment by parg** [comment]
See https://github.com/BiglySoftware/BiglyBT/wiki/Tags - search for 999999
