### ISSUE TITLE
Display issues Windows 10/64 bit

### ISSUE THREAD

**Issue by eurobank** [BiglySoftware/BiglyBT#2045]
Hello.

Using the latest biglybt 2.7 (happens to older versions) and Windows 10 pro/64 updated. Maximizing the biglybt window and back in advanced view has some issues.

Since it is very hard to explain what happens, please view the video. 

https://user-images.githubusercontent.com/4467158/111798854-24b12c00-88d3-11eb-9b4d-10e7d4e9a1a4.mp4

**Comment by parg** [comment]
hmm, if you switch to the 'detailed' view then are things OK for you?

**Comment by eurobank** [comment]
Yes i don't see any such issues to detailed view.

**Comment by TuxPaper** [comment]
I have no idea what's going on, but thanks for the video, it saves a lot of questions.

**Comment by eurobank** [comment]
Did you find anything, this is rather annoying issue. Visually, still if you have any ideas .....

**Comment by eurobank** [comment]
not fixed, but no reason to keep this open.
