### ISSUE TITLE
Show warning messages in status or in a new field

### ISSUE THREAD

**Issue by silverbacknet** [BiglySoftware/BiglyBT#2049]
The only two places to find the text of the newer Bittorrent 'warning message' field is the little error popup on the bottom right, which is a little too easy to accidentally dismiss, or by opening the console and forcing a tracker update. It needs to be displayable somewhere, because trackers are using it as a field to stuff their errors into, even if that goes against it being just a "warning".

I'm personally in favor of appending it to the status message, similar to how errors have classically worked, but a separate column would be acceptable.

**Comment by parg** [comment]
It isn't a new bittorrent feature (been there forever) but perhaps trackers are using it more? 

Appending any warning messages to the 'Status' column information in the 'Sources' view is doable.

**Comment by parg** [comment]
It'll be in 2703_B01 once built (join the Beta Program via the Help menu to get beta updates)

**Comment by silverbacknet** [comment]
Thanks! It does seem so, I'm getting OKs with error messages only in that field. That doesn't seem in the spirit of the spec, but... what can you do?

**Comment by parg** [comment]
The beta is now available if you want to test it.
