### ISSUE TITLE
When selecting a file, then pressing Context Menu button on keyboard, the cursor opens the context menu for the line that the mouse cursor rests on

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2052]
* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment

SWT v4930r7, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B2.6.0.0/4 az3

When one file in my torrent is selected, if I press the Context Menu button, just to the right on my keyboard of the Alt Car button, which itself is just to the right of the spacebar, the line that the mouse cursor is hovering over but hasn't selected will become selected and the context menu will pop up for that line.  It makes it difficult to just navigate by keyboard because then I have to see where the mouse is pointing, and if I wanted to bring up the context menu for where the mouse is pointing, I would press right-click, not ContextMenu.  I would rather that the line that I selected either with the mouse or keyboard would bring up the context menu.

**Comment by TuxPaper** [comment]
Might be better in 2703_B02.  I don't have a menu key on my keyboard, but I think I reproduced it with the equivalent Shift-F10 key combo.  

Sidebar context menu has a similar issue -- it shows the menu for the row under the cursor.  I haven't fixed that one yet.

Unfortunately, the standard context menus (file list context menu) will still pop up wherever the cursor is, and I may not be able to change that.

**Comment by TuxPaper** [comment]
B02 will include a fix for the sidebar too

**Comment by NaPurHab** [comment]
B02 broke the context menu for me. See my issue post for image.

**Comment by TuxPaper** [comment]
Thanks.  I forgot about scrolling, lol.

**Comment by NaPurHab** [comment]
B03 fixed it. Thanks

**Comment by as-muncher** [comment]
You can also use the On-Screen keyboard built into Windows and that context menu key works the same as if you pushed it on the keyboard, and the issue is the same with the On-Screen keyboard.  I haven't tested it with B02 nor with B03 - maybe I should try that now.

**Comment by NaPurHab** [comment]
> You can also use the On-Screen keyboard built into Windows and that context menu key works the same as if you pushed it on the keyboard, and the issue is the same with the On-Screen keyboard. I haven't tested it with B02 nor with B03 - maybe I should try that now. **I don't know how to get B03**.

Check for updates is the usual way, if you have the BETA Program turn on.  Also you can check the CHAT channel `BiglyBT: Updates: Core[R]`.  You can download from there by Right-Click on any posted files.  You will then have to manually install the Update by replacing the BiglyBT.jar with the Update file. Remember to Exit BiglyBT before replacing the JAR file.

**Comment by TuxPaper** [comment]
If you haven't found it yet:

Help->Join Beta Program...

**Comment by as-muncher** [comment]
ok, thanks for the info on how to join the beta program.  I am using 2.7.0.2 and the issue is still there with regards to the context menu button.  Is B03 after 2.7.0.2?

**Comment by parg** [comment]
Yes - 2.7.0.2 is the latest full release, from that point onwards betas are named 2703_B01, 2703_B02 etc

**Comment by as-muncher** [comment]
I think this issue is fixed.
