### ISSUE TITLE
Right Click Menu not where it should be.

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#2053]
When I right click the Menu is far off the bottom. Now the odd thing is that as in the image it is on the NEW Tag. When I right click on a file in the Active Tag then the Menu is closer, but each time I right click the same file, the menu comes up in a random place.  This only began with B02.

I just completed replacing B02 with B01 and the problem disappears. Seems like something changed between B01 and B02.

![image](https://user-images.githubusercontent.com/37715552/112403047-0fc60580-8ce4-11eb-96af-83f01ae50d10.png)

Java 1.8.0_281 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_281

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.7.0.3_B02/4 az3

**Comment by TuxPaper** [comment]
B03 will be victorious!

**Comment by NaPurHab** [comment]
B03 fixed it. Thanks
