### ISSUE TITLE
BBT not respecting UDP listen port for torrent transfers

### ISSUE THREAD

**Issue by showstoppre** [BiglySoftware/BiglyBT#2054]
System
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.7.0.2/4 az3

--------------------------------------------------
I've configured separate TCP and UDP listen ports.

UDP(uTP) connection couldn't be established from another client to my BBT client's UDP listen port.

UDP connection to the port number configured for TCP is still accepting UDP connection when it shouldn't.

Moreover UDP connections initiated by BBT are using the TCP port number.

Tested in LAN and WAN. Results are the same.

Can be reproduced by configuring different ports for TCP and UDP in Option->Connection.

**Comment by parg** [comment]
What does the NAT test show under Help->NAT / Firewall Test ...

**Comment by showstoppre** [comment]
Testing port UDP 22346 ... 
    Sending outbound packet and waiting for reply probe (timeout=5000)
    Sending completion event
OK ! (x.x.x.x)

**Comment by showstoppre** [comment]
I'm behind a CGN(full-cone). I don't have trouble receiving incoming UDP connections. 

To be more precise, the UDP listen port 22346 I've configured is working for inbound and outbound DHT connections.

However for torrent transfers, TCP listen port number is used for both outbound and inbound.

**Comment by parg** [comment]
The uTP plugin uses the same UDP listen port as everything else

**Comment by showstoppre** [comment]
So is my understanding correct that uTP plugin is supposed to use UDP listen port under Option->Connection.

If that is the case, it is currently misbehaving, as it uses the same port as "Incoming TCP listen port"

**Comment by parg** [comment]
Hmmm, actually, you might be right

**Comment by parg** [comment]
Not misbehaving I would add, as designed.

**Comment by parg** [comment]
Trackers, DHT, PEX only return a single port for a given peer - thus both TCP and uTP connections have to operate over the same port.

**Comment by showstoppre** [comment]
Aw I see. Thanks for your continued support. 

I have a better understanding now. 

I believe this issue can be closed.

Just curious though if there is any real benefit for having a separate setting for TCP and UDP listen port as it is only used for DHT. In most of the other clients the listen port is one and the same for TCP and UDP.

**Comment by parg** [comment]
There were (are?) routers that didn't properly support forwarding of the same port for both TCP and UDP - this is going back many years though, I would hope that things had improved. Beyond that, not sure.

**Comment by showstoppre** [comment]
Thanks again for clarifying :)
