### ISSUE TITLE
Jackett not searching anymore

### ISSUE THREAD

**Issue by Asgardsurfer** [BiglySoftware/BiglyBT#2057]
Parg et al, thanks so much for all the hard work.
Jackett worked perfectly before, now it just sits there.
I've tested it in Safari and it works fine. 
Deleted the old template and created a new one and inserted the API Key, still does not search.
I also increased the timeout to 300 sec.
Anyone else seeing this behaviour?
Thanks!

Java 1.8.0_281 (64 bit)
  Oracle Corporation
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home

SWT v4942r22, cocoa, zoom=100, dpi=72
Mac OS X v10.14.6, x86_64 (64 bit)
B2.7.0.2/4 az2

**Comment by Havokdan** [comment]
Everything's ok here.

**Comment by parg** [comment]
Works fine for me on Windows 10 - Jacket v0.17.790

**Comment by parg** [comment]
Here's the JSON verison of my search template with the apikey replaced with ****************

`{"vuze":{"components":[{"content":{"web.time_zone":"GMT-11","web.required_cookies":[],"name":"Jackett","select_rec":1,"uid":"\\xd88b5ff4189272385eaf\\x","last_updated":1548157139579,"az_version":5,"version":2,"selected":2,"source":2,"id":2929201020,"l1_map":[{"from":6,"to":6,"maps":[]}],"l2_map":[{"from":6,"to":8,"maps":[]}],"web.search_url_format":"http:\/\/127.0.0.1:9117\/api\/v2.0\/indexers\/all\/results?apikey=**************************&Query=%s&_=1548156611274","web.needs_auth":0,"web.auto_date":1,"json.path":"Results","rank_bias":"1.0","web.maps":[{"field":6,"name":"CategoryDesc"},{"field":1,"name":"Title"},{"field":102,"name":"Link"},{"field":103,"name":"Comments"},{"field":2,"name":"PublishDate"},{"field":3,"name":"Size"},{"field":5,"name":"Seeders"},{"field":4,"name":"Peers"},{"field":200,"name":"InfoHash"}],"pref_count":"0.0","web.full_cookies":null,"type":2,"web.auth_method":"transparent"},"type":1}]}}`

**Comment by Asgardsurfer** [comment]
Thanks guys, I guess it's on my end then, glad to hear it's not broken. Will do more testing and report back. ￼

**Comment by Asgardsurfer** [comment]
![Screen Shot 2021-03-26 at 1 36 17 PM](https://user-images.githubusercontent.com/10076020/112671492-9e4b9b80-8e38-11eb-8683-9560ebe2006b.png)
This is the error Im getting..any thoughts?

**Comment by Havokdan** [comment]
Do you have authentication on jackett?

**Comment by Asgardsurfer** [comment]
If you mean if I have a password set, I do not

**Comment by Asgardsurfer** [comment]
It’s clearly on my end, I will figure it out guys thank you for all the support

**Comment by parg** [comment]
API-key embded into the BiglyBT search template wrong? Try copying your Jacket search template to clipboard and check it

**Comment by Asgardsurfer** [comment]
Just copied the template to clipboard and checked it and yes the API key is correct. Wonder if some thing is blocking. It’s weird because when I use jacket in Safari, my search results come up.

**Comment by Asgardsurfer** [comment]
Will check if the VPN is the cause

**Comment by parg** [comment]
"401 Unauthorized" means that the connection to Jacket is working but either your API-key or credentials are incorrect. Not sure how BiglyBT handles username/password authentication, I assume you haven't enabled this in your Jacket config?

**Comment by parg** [comment]
I think the apikey is supposed to be 32 characters, your screenshot shows an apikey that's shorter than this (although it might be truncated and displaying incorrectly in the tooltip...)

**Comment by Asgardsurfer** [comment]
"username/password authentication, I assume you haven't enabled this in your Jacket config?"
NO
I blurred a little part of it in the picture.
I'll keep working on it
Just counted the API Key and I have 32 digits

**Comment by Asgardsurfer** [comment]
parg, as you are here, just want to report that the "tab bar button" in the tabs section does not activate anymore, does not open the sidebar. Seems to be a new thing.

**Comment by Asgardsurfer** [comment]
![Screen Shot 2021-03-26 at 2 58 13 PM](https://user-images.githubusercontent.com/10076020/112680397-b674e800-8e43-11eb-99fd-69f45f21c861.png)

**Comment by parg** [comment]
There's supposed to be an & before the Query...

"http:\/\/192.168.1.5:9117\/api\/v2.0\/indexers\/all\/results?apikey=****************&Query=%s&_=1548156611274"

You're in classic UI - there isn't even supposed to be "tab bar button"... I don't have one!

**Comment by Asgardsurfer** [comment]
Wow, now I have things others don't have...what a day.
You are right, my screenshot does't have the "&" I just dumped to clip board again and its there.
I copied exactly the quote so it's even more strange...

{"vuze":{"components":[{"content":{"web.time_zone":"GMT-11","web.required_cookies":[],"name":"Jackett","select_rec":1,"uid":"\\xd88b5ff4189272385eaf\\x","last_updated":1548157139579,"az_version":5,"version":2,"selected":2,"source":2,"id":2929201020,"l1_map":[{"from":6,"to":6,"maps":[]}],"l2_map":[{"from":6,"to":8,"maps":[]}],"web.search_url_format":"http:\/\/127.0.0.1:9117\/api\/v2.0\/indexers\/all\/results?apikey=**************************&Query=%s&_=1548156611274","web.needs_auth":0,"web.auto_date":1,"json.path":"Results","rank_bias":"1.0","web.maps":[{"field":6,"name":"CategoryDesc"},{"field":1,"name":"Title"},{"field":102,"name":"Link"},{"field":103,"name":"Comments"},{"field":2,"name":"PublishDate"},{"field":3,"name":"Size"},{"field":5,"name":"Seeders"},{"field":4,"name":"Peers"},{"field":200,"name":"InfoHash"}],"pref_count":"0.0","web.full_cookies":null,"type":2,"web.auth_method":"transparent"},"type":1}]}}

**Comment by Asgardsurfer** [comment]
Just for the heck of it I ran a search in QBittorent and Jackett returned results. 
Thanks again, I'm sure it will sort itself out eventually...
