### ISSUE TITLE
swarm merge with incomplete/broken pieces?

### ISSUE THREAD

**Issue by SUCM** [BiglySoftware/BiglyBT#2058]
there seemed to be some bug with regard to the merged files between different torrents when I only selected some of the files from each torrent. hopefully below steps would make reproducing steps clear. I rarely do this, so not sure if this would be consistently reproducible (timing/racing condition?)

0. have 2 torrents A and B where both are different torrents with lots of completely different files, but have ~300 files with the exact same name and binary content. however, these files and its folder are structured very different between both torrents, so they share different pieces with others files different between both torrents
1. add torrent A selecting ~300 files
2. add torrent B selecting the exact same files as torrent A, such that both torrent will download the exact same files which would have no difference when binary diff between them
3. start downloading
4. after a while, torrent A finished downloading those 300 files while torrent B has yet to finish. BiglyBT moved torrent A to the download completed panel. BiglyBT also reports information on many (but not all of the files) were merged between the 2 torrents
5. do a force re-check of torrent A
6. BiglyBT reports torrent A still has 1 or 2 pieces (ex. if a piece is 4MB, then exactly 4MB or 8MB remain to be downloaded) incomplete and move it back to the download incomplete panel
7. start torrent A again to download
8. after a while, both torrents finished downloading at the same time. BiglyBT move both to download completed section and also report a few more files were merged between the 2 torrents
9. now do a force re-check on both and both stayed 100% downloaded

* Win 10
* BiglyBT 2.6.0.0
Java 11.0.9 (64 bit)
  Oracle Corporation
c:\program files\java\jdk-11.0.9

SWT v4930r7, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.6.0.0/4 az3

**Comment by as-muncher** [comment]
I've often wondered if BiglyBT simply just looks for a filename in the torrent that is exactly a match, and if so, then it copies it over.  Does BiglyBT actually look through files that match to make sure that there are pieces in there that are valid?  I've found that it doesn't but probably should look at files that have different extensions even though the filename is the same, and try to assimilate all it can.  If I download file A at one time that has a chunk at the beginning, and another same file A just downloaded at a different time, but this one has a chunk at the end, I'd hope that BiglyBT could take the beginning chunk from the first file A and the end chunk for the same file A downloaded at a different time, and integrate them into the currently-downloading file A.  Oops, I guess this isn't really swarm merging but "check if files exist.." eh?

**Comment by SUCM** [comment]
> 
> 
> I've often wondered if BiglyBT simply just looks for a filename in the torrent that is exactly a match, and if so, then it copies it over. Does BiglyBT actually look through files that match to make sure that there are pieces in there that are valid? I've found that it doesn't but probably should look at files that have different extensions even though the filename is the same, and try to assimilate all it can. If I download file A at one time that has a chunk at the beginning, and another same file A just downloaded at a different time, but this one has a chunk at the end, I'd hope that BiglyBT could take the beginning chunk from the first file A and the end chunk for the same file A downloaded at a different time, and integrate them into the currently-downloading file A. Oops, I guess this isn't really swarm merging but "check if files exist.." eh?


probably not as simple as it merges with files even with different name.  my guess is BiglyBT looks at file hashes from torrent for comparison, but I suspect there are complications due to torrent pieces shared among multiple files. sometimes (but not always) BiglyBT merges files and claim download is 100% complete, but the merged text files (ex. a 271KB txt file) are still binary filled with all 0's when I open them. a force re-check would confirm those files weren't downloaded yet

**Comment by as-muncher** [comment]
Yeah, I saw @parg make a comment on another thread about having that very issue, where there could be junk put in to the file and BiglyBT says it's 100% complete.  I don't know about others, but I know for myself, I have the settings to force a recheck after the download is complete for that very reason.  It has happened that files that said were 100%, after a recheck went down to 95.7% or so and had to redownload parts of it.  I almost think a forced recheck after a download completes should be on by default.
