### ISSUE TITLE
trying to run the install script for BiglyBT results in error Fedora KDE 32

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2059]
* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment

Fedora 32 KDE Plasma live dvd
Operating System: Fedora 32
KDE Plasma Version: 5.18.3
KDE Frameworks Version: 5.68.0
Qt Version: 5.13.2
Kernel Version: 5.6.6-300.fc32.x86_64
OS Type: 64-bit
BiglyBT is currently 2.7.0.2

So, I'm not a complete newbie to linux, but I just wanted to post an error that I found after I download the BiglyBT installer script, and right-click -> run in Konsole.  
Warning: Could not find '/home/liveuser/Downloads/BiglyBT_Installer.sh', starg '/bin/bash' instead.  Please check your profile settings.
It must be a problem with the operating system.  When I opened konsole, then dragged the biglybt installer file into the console window, I got:
[liveuser@localhost-live ~]$ /home/liveuser/Downloads/BiglyBT_Installer.sh 
bash: /home/liveuser/Downloads/BiglyBT_Installer.sh: Permission denied

Plus, it's not in the fedora 32 repository, so I can't install it that way.

**Comment by TuxPaper** [comment]
the program that downloaded it probably didn't mark it as executable.

`chmod +x /home/liveuser/Downloads/BiglyBT_Installer.sh`

should make it runnable.  I'm not sure we can do anything on our end, we mark the file as mime type 'application/x-sh' on our main server, and we don't have control at all over github's release download's mime types.

**Comment by as-muncher** [comment]
I downloaded it using Firefox, so I don't think it would automatically change the file attributes.  Or maybe it wasn't allowed to save it with the "executable" attribute?  Even though I right-click -> run script it needs that "x" attribute, eh?  I guess it's got that attribute on the file itself on the server, then.  Thanks for getting back to me.
