### ISSUE TITLE
Would like to intall older version of BiglyBT...

### ISSUE THREAD

**Issue by nathan-elke** [BiglySoftware/BiglyBT#2063]
I was running version 2.7.0.2...had updated it two days ago. Ever since doing the update, I've been having issues with my PC (windows 10)...it will start to slow down, then completely freeze. I'd like to install the previous version; is there a place I can do that?

**Comment by Havokdan** [comment]
All previous releases can be downloaded here in Github: https://github.com/BiglySoftware/BiglyBT/releases

**Comment by Pags921** [comment]
Hey Nathan,

did you ever get it to work again? I went back until 2.2.0.2 and still have the issue.
For me it started after the last Windows update.

Have a nice day,

PaGs

**Comment by nathan-elke** [comment]
it worked for me...haven't had a freeze since I backed up to the previous version. It keeps mentioning "there's an update", to which I politely decline. :) :) :) 

Nathan Elke 
Saskatoon, SK

**Comment by carvermon** [comment]
I would also like to revert to a previous version, as one of my torrent sources isn't supporting 2.7. I see the link to the list (thanks Havokdan!), but will admit to being baffled as to how to install 2.6.  I see the list of assets, but unsure as to how to proceed/which to download. Any help for this bumpkin?

**Comment by Havokdan** [comment]
> I would also like to revert to a previous version, as one of my torrent sources isn't supporting 2.7. I see the link to the list (thanks Havokdan!), but will admit to being baffled as to how to install 2.6. I see the list of assets, but unsure as to how to proceed/which to download. Any help for this bumpkin?

If you use Windows, you have to install one of the versions that ends with the .exe extension, if your Windows is 32-bit, you install it with 32 in the name, if it is 64-bits, install the 64 Name, to know click on BiglyBt> About and see that version is your current one, for example:

![Sem título](https://user-images.githubusercontent.com/6549729/113407218-3e4a7d00-9383-11eb-88c3-8af75c649f2a.png)

In the example I gave up, I am using 64-bits, as shown in the image.

**Comment by carvermon** [comment]
Howdy Havokdan, and thanks again. 
Sorry I hadn't mentioned my OS - it is Mac 10.11.6 64-bit, leaving me still uncertain as to the proper link/s needed to install Bigly 2.6.0.0, and if it would simply replace my current version (2.7.0.3 B07) or if would need to uninstall anything (I have just left the beta program).
