### ISSUE TITLE
[Feature Request] force re-check for selected files only

### ISSUE THREAD

**Issue by SUCM** [BiglySoftware/BiglyBT#2064]
from #2058, can we have a new feature where we can just select a few files (thinking of making selection in the Files tab) to for force re-check instead of re-check the whole thing? it's ok to re-check a bit more file due to other files sharing the same pieces. the idea is that I want to force re-check just on the merged files based on the popup info, so I don't have to stop seeding while re-check the whole torrent especially if it's large

**Comment by SUCM** [comment]
when I tried on 2.6.0.0, I right click on a 3GB (selected to download but download not yet completed) file within a larger than 100GB torrent then click on Recheck as you had suggested. this caused that torrent to go into allocation mode for some time, then re-check starts when the Remaining column got reset to whole torrent size and starts counting down similar to recheck the whole torrent. not sure if it was just display issue or something else, but I thought that means the Files tab's Recheck triggers re-check on all files in the torrent

**Comment by parg** [comment]
I ran a few tests and it only rechecks the file(s) I've selected, pehaps there's something about the state of your incomplete download

**Comment by SUCM** [comment]
Bigly later reported the file was merged with the file from another torrent. I just did a few test where I completely stopped all torrents then randomly selected few files and was able to confirm recheck worked correctly on just the selected files
