### ISSUE TITLE
Internal vs Hard

### ISSUE THREAD

**Issue by ms52538** [BiglySoftware/BiglyBT#2066]
Hola - hope the new year has been treating everyone well and all are safe and healthy!

So about this 'internal' vs 'hard' switch option when searching for existing files ... can you explain what is happening with those?  I am unclear as to what they do - or how they differentiate from what had been the default function in the past.

:) 

Gracias!

**Comment by parg** [comment]
Some people wanted to use a https://en.wikipedia.org/wiki/Hard_link when matched existing files rather than the existing mechanism where BiglyBT internally links the file to the alternative location.
