### ISSUE TITLE
What's going on in AppData\Roaming\BiglyBT\active?

### ISSUE THREAD

**Issue by david-bakin** [BiglySoftware/BiglyBT#207]
I see _writing_ into a large number of files in my user's AppData\Roaming\BiglyBT\active and \tmp directories - at a time when there are no torrents active and only one (large) torrent being checked.  I didn't expect that.

(Actually, it seems to have petered off and the torrent is still being checked.  I had been running about 8 torrents and paused them all at the same time. By "petered off" I mean that the Windows Resource Monitor has a somewhat large "smoothing" on its readings and can show I/O activity on a file for some time after it stops.)

- What's going on there - what's written to those `*.dat` and `*.tmp` files?
- Is there a configuration where I can put that activity somewhere else?  (E.g., I'd like to move the activity off of the system volume; in fact, I'd like to move it to a separately encrypted volume.)

[Java 1.8.0_152 (64 bit) Oracle Corporation c:\program files\biglybt\jre

SWT v4757, win32
Windows Server 2016 v10.0, amd64 (64 bit)
B1.2.0.1_B28/4 az3]

**Comment by david-bakin** [comment]
No, I spoke too soon.  No change in what's going on - one large torrent being checked and no other torrents running at all - and a bunch of files in \active just got written.  Small writes - but a lot of them.

**Comment by parg** [comment]
One .dat per torrent in general - housekeeping data such as amount transferred, activity etc.

**Comment by TuxPaper** [comment]
Closing Issue.  Sounds like there might be a valid new issue about reducing write frequency to .dat files. If that's still an issue for anyone, please file a new Issue.  Thanks!
