### ISSUE TITLE
Feature suggestion: Missing pieces marked on Files tab

### ISSUE THREAD

**Issue by david-bakin** [BiglySoftware/BiglyBT#2070]
[BiglyBT Beta (2.7.0.3.B08)]

You know how on the General tab there's a single piece-presence bar for the entire torrent and if the swarm (that is, the peers you're connected to for that torrent) as a whole is missing a piece then that piece is marked in red?

Can we have that too for the piece-presence bars for each file on the Files tab?

**Comment by parg** [comment]
There's an 'availability' column in the Files View - isn't that enough to tell that the file has one or more unavailable pieces?

**Comment by parg** [comment]
I'll add it for the next beta

**Comment by david-bakin** [comment]
Looks good!  Only question is - is this red color different from the red color used for other purpose like active pieces (I've never actually been sure what that red color is blinking on and off on various pieces ...)  (In my brief inspection so far I didn't manage to catch both a partially available torrent and an active piece blinking on and off ...)

**Comment by parg** [comment]
You can change the colour by right-clicking on the Availability image in the General View

**Comment by david-bakin** [comment]
ok.  plus it turns out its a "deeper" red anyway so different.  Thanks for this feature!
