### ISSUE TITLE
Support biglybt showing up, and up, and up and up, every single file. and not displaying fully

### ISSUE THREAD

**Issue by pseudo555** [BiglySoftware/BiglyBT#2074]
Each and every single time i click on OK to download a new torrent, the support biglybtwindows shows up.
Is there a way to get it only once per day or even 20 minutes instead ?
That's a really annoying behavior.

Furthermore, why can't this windows display its content completely ?
I mean, i got a 1440p and the popup use scrollbar...

* Win 10 x64 20h2
* BiglyBT Version 2.7.0.2
 
![biglyBug](https://user-images.githubusercontent.com/18347988/114061633-f2259e00-9896-11eb-98f5-f282eddc3f49.png)

**Comment by parg** [comment]
Hmm, that's not good... There is a 'no thanks' link top right - if you click that to close it then does it stop prompting?

It is designed to only show infrequently so obviously something's borked.

**Comment by pseudo555** [comment]
you're right, using no thank's button make it dissapear.
I guess the onClose action on the frame doesn't include the "no thanks" part which keep that dialog to not be displayed for a while.
