### ISSUE TITLE
Explorer operations extremely slow when BT is running

### ISSUE THREAD

**Issue by homerepope** [BiglySoftware/BiglyBT#2076]
Explorer operations are extremely slow when BT is running (i.e. opening and copying files, only 1mb sec when copying, after close BT copying is back ar 90 to 1OOmb sec) 
Have not see this in previous versions.
*Windows 10 Pro 20H2
*Processor	AMD Ryzen 9 5950X 16-Core Processor               3.40 GHz
*Installed RAM	32.0 GB
*System type	64-bit operating system, x64-based processor
* BiglyBT Version Number 2.0.7.2

**Comment by parg** [comment]
Look at the Task Manager views to see how much disk IO is associated with the BiglyBT process?

**Comment by homerepope** [comment]
![Snapshot](https://user-images.githubusercontent.com/10887296/114221672-96f9b700-993b-11eb-9c22-8e205e48b10b.png)

**Comment by parg** [comment]
transcoding something at the same time?

**Comment by homerepope** [comment]
Yes

**Comment by parg** [comment]
perhaps that's hammering your system then

**Comment by homerepope** [comment]
Problems Yes.

**Comment by homerepope** [comment]
Believe we can close this as non issue.
