### ISSUE TITLE
Can I remove the status bar from the upper left corner of the screen?

### ISSUE THREAD

**Issue by CEcustom** [BiglySoftware/BiglyBT#2077]
I just updated BiglyBT and now have a separate status bar in the upper left corner of the screen.  It stays on top of everything even when BiglyBT is minimized.  How can I remove it?

* Windows 10
* BiglyBT 2.7.0.2

**Comment by parg** [comment]
Have you enabled the 'transfers bar' - Tools->Transfers Bar (or right-click it and select 'close') ?

**Comment by CEcustom** [comment]
While I can right click and close, sometimes there are 20 or so on top of each other, so that is not practical.  But you did point me in a direction that worked....thanks
