### ISSUE TITLE
SOCKS proxies

### ISSUE THREAD

**Issue by joliett** [BiglySoftware/BiglyBT#2078]
When using SOCKS proxies, I enter the address my provider gives me, but biglyBT automatically fills in htps:// in the address field...
Setting, Connection, Proxy, HOST.
I was getting disconnected from the Proxy and my VPN support told me to remove the http://  and  the last / at the end of the address.  That worked and the problem was solved.

So suggest that BiglyBT stop filling that in....

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.7.0.2/4 az3

**Comment by parg** [comment]
I don't get any auto-complete, BiglyBT isn't doing that, could it be Windows trying to be clever?

**Comment by joliett** [comment]
Now that I  check, you are correct....When I copy a link address that says
*amster.nl.socks.hold.net <http://amster.nl.socks.hold.net>*
which is in KEEP notes, or the address bar in Wndows or Edge and paste it
anywhere - not just BiglyBT
It paste :
*http://amster.nl.socks.nord.net/ <http://amster.nl.socks.nord.net/>*

Thank you!

**Comment by parg** [comment]
\o/
