### ISSUE TITLE
Having trouble setting up download of .torrent files to a specific folder

### ISSUE THREAD

**Issue by MarathonZephead** [BiglySoftware/BiglyBT#2079]
Hi

I've been scratching my head, trying all the combinations of checking and unchecking the Files > Torrents sub-options and none of them seem to work for me.

When I download a new torrent, I want the .torrent file to download to E:\APPS\DOWNLOADS\zTORRENT FILES (the data downloads to a different folder) and it will only download to E:\APPS\DOWNLOADS.  I can't see where BiglyBT is configured to download to that folder and I don't know what I'm doing incorrectly.  I thought it might be restricted to a certain number of folder levels but I have no problem with completed .torrent files automatically moving to a subfolder of zTORRENT FILES.

Also, even though the 'Save .torrent file to (folder)' box isn't checked, it still downloads, so I don't understand the purpose of that feature.

Assistance appreciated.

Thank you!

Edit: RESOLVED

Files > Completion Moving > Check Move Completed Files (after download) box: LEAVE FOLDER BLANK

Check Move .torrent...Torrent directory if different from above box: E:\APPS\DOWNLOADS\zTORRENT FILES\Completed Files For Deletion

Torrents > Check Save .torrent files box: Save Directory: E:\APPS\DOWNLOADS\zTORRENT FILES

Check Delete original .torrent files after download added box (incidentally, this is slightly misleading as it should state .torrent file (no 's')

Hope this helps somebody!

**Comment by parg** [comment]
Thanks for resolving, I was just about to take a look!
