### ISSUE TITLE
aarch64 Ubuntu Mate error on starting BiglyBT

### ISSUE THREAD

**Issue by akidburn** [BiglySoftware/BiglyBT#208]
Hi all,
i am currently trying to run bigly on an odroid c2, sadly the thing has an aarch64 architecture.

![error](https://user-images.githubusercontent.com/25623510/34338658-2a782324-e96b-11e7-8121-4a26d545a627.jpg)

Current Bigly Version.
Ubuntu 16.04
Mate 1.12.1
uname output:
`Linux odroid64 3.14.79-116 #1 SMP PREEMPT Tue Sep 26 01:19:06 BRT 2017 aarch64 aarch64 aarch64 GNU/Linux`

thanks 

akidburn

**Comment by TuxPaper** [comment]
Try copying this file into `~/biglybt/swt/` (or, the `swt` subfolder where you installed biglybt)
https://s3.amazonaws.com/biglybt-files/swt/swt-aarch64.jar

Let us know how it goes.. we've never ran BiglyBT on a aarch :)

(Technical: the `biglybt` script will look for a swt file named `swt-${uname -p}.jar`, which should be `swt-aarch64.jar` for you.  Alternatively, you can rename the `swt` dir so it can't be found, and just place the `swt-aarch64.jar` in `~/biglybt/`)

**Comment by akidburn** [comment]
didnt have time to test it, sry. 
tried to install a propritary ups manager and it smoked the ubuntu.
ran a small java app the same day i opened the issue, no performance what so ever.
didnt try to install java on any arm device since, though ripping out the gui system helped for the nextcloud instance i'm running on it

thx anyway
akidburn
