### ISSUE TITLE
Misspelled.

### ISSUE THREAD

**Issue by hglecke** [BiglySoftware/BiglyBT#2081]
* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment

**Comment by hglecke** [comment]
Very minor issue:
In the 'Share Exporter Log File' the word "processing" is misspelled. It is missing one letter 's'.
When the share exporter plugin is enabled and the torrent directory is left blank, an error message is written to the log. Maybe a valid entry should be required when the plugin is enabled by the user.

Procesing share 'H:\Share\Bach, JS - Brilliant Classics Bach Edition (Vol 1) (23CD) (2001) [320kbps] F'
ShareExporter: Torrent directory '' doesn't exist

**Comment by parg** [comment]
Thanks!
