### ISSUE TITLE
Private Tracker returning "no/erroneous BT client listening or misconfigured router" error

### ISSUE THREAD

**Issue by MarathonZephead** [BiglySoftware/BiglyBT#2082]
I have been a member of the private (legitimate) music tracker Dimeadozen and have used this client to leech/seed for years.

I have recently been getting the error message "no/erroneous BT client listening or misconfigured router" from the tracker.  I have checked my port (32459) with canyouseeme.org and it's definitely open.  I haven't changed any settings with BiglyBT and I'm wondering if there's something in the latest version that could be causing this, because the issue has only appeared since I rebuilt my PC following a 3 month absence, when it updated to the latest version.

Could the 'light-seeding' feature be causing this?

Also, is it possible for me to download version 2.6? And if it's v2.7 that is causing the issue, is it possible for me to configure 2.6 so it doesn't update to 2.7?

Help appreciated!

Many thanks!

**Comment by parg** [comment]
Do you only get this message for torrents in a 'light-seeding' state (as shown in the status column)? If not then I wouldn't imagine that is related. You can turn light-seeding off - see https://github.com/BiglySoftware/BiglyBT/wiki/Seeding

I'm guessing that the error message actually relates to the fact that the tracker is attempting to connect to your incoming listen port and that it is failing to do so - usually this is a NAT issue. Try running the NAT Test (Help menu), particularly the TCP port test.

If that doesn't help I can point you at 2.6

**Comment by MarathonZephead** [comment]
I deleted the single torrent that showed 'light-seeding' and the tracker returned the same error.

However, 30 mins or so later, the error msg disappeared, which was both good and bad because I'd like to know how the error arose to avoid it recurring.  If it was at my end then it can only be the 'light-seeding' but since you said that's unlikely then the error must have been with one of the 3 Dimeadozen trackers.

I'll post back if I get this again when I have a light-seeding torrent.

Thanks again.

**Comment by MarathonZephead** [comment]
I can confirm that my assumption re Light seeding was correct (thank you for the pointer for turning it off).

I saw the error again.  I turned off Light seeding, refreshed the tracker and the error disappeared immediately.

Error resolved.

**Comment by parg** [comment]
In case you're interested, the latest beta (2703_B15) should play better with light-seeding and NAT testing

**Comment by MarathonZephead** [comment]
Many thanks Parg. I need a bit of convincing that I need this feature.  My priority is maintaining or improving my share ratio.  If light-seeding can help with that then I'm all for it.

**Comment by parg** [comment]
It gives you the opportunity to run a lot more active torrents that have zero peers without too much resource usage. If a peer comes along then BiglyBT will react much more quickly to it and give you the opportunity to seed to it. Without light-seeding these torrents would be in a 'queued' state and only 'see' the peer the next time they scrape the tracker, by which time it might have already completed.

Whether this will help you in reality depends on how frequently peers appear on relatively inactive torrents.

**Comment by MarathonZephead** [comment]
OK thanks - typically, I don't tend to seed for longer than a day or two, once I have completed a download and I'm very rarely the only seed.  Would light-seeding be of benefit here?

**Comment by parg** [comment]
Probably not :)
