### ISSUE TITLE
Adds data in sfv on scan

### ISSUE THREAD

**Issue by faltaren** [BiglySoftware/BiglyBT#2084]
* OS and version Ubuntu 20.04
* BiglyBT Version Number 2.7.02
* For *nix: Desktop Environment
Java 11.0.10 (64 bit)
  Ubuntu
/usr/lib/jvm/java-11-openjdk-amd64

SWT v4942r22, gtk/3.24.20, zoom=100, dpi=96
Linux v5.8.0-50-generic, amd64 (64 bit)
B2.7.0.2/4 az3

Bigly adds this (se below) to my some of my sfv files when i scan the torrent. The sfvs are clean but when i scan this SOMETIME happens. i also get banned for sending corrupt data. Never happend before, only after the update.  \00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00

**Comment by parg** [comment]
I can't see how BiglyBT is doing this - perhaps you have some other app messing with your files. BiglyBT checks file contents against pieces hashes in the torrent file, it doesn't go around adding stuff to files.

**Comment by faltaren** [comment]
I see now its also nfos. If you want to see. Create a torrent with unix eol on sfv and nfo. Then change the files to windows eol. Scan the torrent and get the error. then change back to unix eol and scan again.

**Comment by parg** [comment]
So you create a torrent, change some of the files and then are surprised that the torrent no longer checks correctly?

**Comment by faltaren** [comment]
Are you even reding what im writing? Bigly write crap to the nfo and sfv.

**Comment by parg** [comment]
Erm, no.

**Comment by faltaren** [comment]
This bugg is still there. Bigly add \u0 to fill out the woid when the eol dosent match.

**Comment by faltaren** [comment]
Noticed now that it ocurs when there is a new line missing in the in a sfv/nfo. Then Bigly add \u0 to fill the void.
