### ISSUE TITLE
REQUEST: Toggle subfolders on/off for torrents

### ISSUE THREAD

**Issue by iansebryk** [BiglySoftware/BiglyBT#2088]
it would be nice to be able to just download a torrent without an autmatic encapsulating subfolder.  i'm used to the ability, from another torrent client, to either have an empty field for the subfolder (resulting in no subfolder created) or a checkbox that toggles this capability.  having to constantly run scripts to move files out of containing folders to the Save Location is a pain not to mention the read/write thrashing involved.  below is what would be useful:

![BiglyBT-fileWindow](https://user-images.githubusercontent.com/1943574/116610279-99c04a00-a8f2-11eb-877c-48149fc7ee93.jpg)

**Comment by parg** [comment]
There is an option to do it - you have to right-click in the area that lists the files...

![image](https://user-images.githubusercontent.com/395293/116691638-000ca180-a9b3-11eb-926e-a4819239fe50.png)

**Comment by parg** [comment]
Well it doesn't rename the torrent if you deselect the 'rename torrent on top level folder change'...

Obviously the general problem with removing the top-level folder is that there are frequent name-clashes in the resulting file sets.

I suppose there could be a specific torrent-watch-folder-option under Options->Files->Torrents to do this that might work for your specific case?

**Comment by parg** [comment]
So you have two torrents with folder structure

    download_a
        this-is-great.mkv
        sample.mkv

and

    download_b
        so-is-this.mkv
        sample.mkv

and you remove the top-level folders 'download_a' and 'download_b' and there isn't a name clash on 'sample.mkv' ?

**Comment by iansebryk** [comment]
nope.  you can choose to either overwrite it (and who really uses sample vid files??) or 'rename it' (aka add a number to the end) in the prefs.

sorry for delay.  work's been hella busy.

**Comment by parg** [comment]
You can't overwrite it in general as the torrent pieces will overlap the end of the file

**Comment by iansebryk** [comment]
i'm just telling you how BitTorrent works.  i don't know how they handle it, it just works.  🤷  believe me, as a fellow dev, i often wonder how the hell other devs do what they do too!  😝

**Comment by parg** [comment]
I can tell you that if you have two torrents with a name-clash of, say, sample.mkv, and you select to overwrite one sample.mkv with another then you will (very likely) not be able to seed both torrents correctly. The reason is that you seed/download pieces (made up of blocks) and these pieces are not (in general) aligned to file boundaries. This is true even if you decide not to download the sample.mkv files.

**Comment by iansebryk** [comment]
again, i'm just telling you how it works.  download it and give it a whirl, you'll see.  bottom line is that your software behaves differently.  that's cool.  as much as i'd like the functionality from another software, this one has better features that meet more of our needs and i can adapt to what's missing with some post-processing in Python.  please don't stress about it.  :smiley:

**Comment by parg** [comment]
heh, I'm not stressing, don't worry :P

**Comment by mckenzieja** [comment]
Gonna have to agree on this one. The ability to simply select the directory I need the torrent to download into without getting into "top level directory" menu navigation scavenger hunts isn't really a great UI/UX experience. A simple fix for this I suppose would be to have an option toggle in config to enable this simple directory selection for us weridos.

**Comment by iansebryk** [comment]
looks like this is simply not a feature the dev is interested in providing.  unfortunate.  would've been the perfect client otherwise.

**Comment by parg** [comment]
such a shame.
