### ISSUE TITLE
How to allocate files for stopped torrent?

### ISSUE THREAD

**Issue by david-bakin** [BiglySoftware/BiglyBT#2091]
When you _add_ a torrent you get a dropdown of which one of the values is "Allocate and Stop" (something like that) where it will preallocate all files but add the torrent in the stopped state.

If you didn't do that when adding the torrent - so the files aren't there - but you want to do it _later_, how do you do it?

**Comment by parg** [comment]
Currently the only way to cause a 'stopped and unallocated' download to allocate its file is to start it.

**Comment by parg** [comment]
B19 has added a 'Stopped (Unallocated)' status for downloads that are stopped and as yet unallocated. I also added an explicit 'Allocate' option to the right-click menu under 'Advanced'

**Comment by david-bakin** [comment]
That'll be helpful (the unallocated state) - sometimes you wonder if you have enough disk space left for this new large torrent given all the ones queued ...

And the allocate option is nice.

Also I discovered that "force recheck" does the job (at the cost of writing (?) all the files that are nonexistent - it takes a long time in the Disk tab ... I didn't check if it was writing or reading or what but it sure wasn't simply _creating_ them - don't need it now though!

**Comment by parg** [comment]
"force recheck" shouldn't allocate files that aren't required but what it does do is perform a hash check of all the required files contents against the torrent piece hashes. Obviously it doesn't make sense in general to allocate a new file and then check its contents but it isn't designed as a means of forcing allocation, rather it is for rechecking downloaded data for correctness.

**Comment by david-bakin** [comment]
Actually, with B20, I find that the "advanced>allocate" menu is always greyed out (even when the torrent is not allocated).  (I tried only torrents that have multiple files of which I selected only one file and did the "remove directory" option.)

**Comment by parg** [comment]
It only works on downloads that have been added in a stopped state and never started - seems to work ok for me under your test scenario. As a bonus its status in the Library should show as "Stopped (Unallocated)" as opposed to "Stopped"

**Comment by david-bakin** [comment]
w.r.t. "it only works on downloads that have been added in a stopped state and never started" - with 2.8.0.1_B03 I just tried it on several torrents in that state - the advanced>allocate menu item was active - I used it - then the torrents in question went to "queued" state but _were not_ allocated ...

**Comment by parg** [comment]
If your queue rules won't even allow the torrent to 'start' (i.e. they are queued) then allocation won't occur until they become eligible to start. i.e. the queued state comes prior to allocation in the flow.
