### ISSUE TITLE
macOS: Subscriptions not displaying Cyrillic characters

### ISSUE THREAD

**Issue by rwmarvin** [BiglySoftware/BiglyBT#2092]
Hello all,

I looked through the issues and didn't see this. Wondering if anyone has see it and/or has a fix.

In a subscription list, the names are not being decoded correctly. 

They look like this in the subscription list:
![image](https://user-images.githubusercontent.com/34894184/116812235-5ee92c80-ab13-11eb-9b45-c0eaa45f3ed7.jpeg)

In the RRS feed the name starts with this:
_%D0%90%D0%B7%D0%B1%D1%83%D0%BA_

Once they are added to the Library they decode and appear correctly. Not a fatal bug, but annoying.

Thanks for any assistance.

-Rob

Info:
Java 1.8.0_281 (64 bit)
  Oracle Corporation
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home

SWT v4942r22, cocoa, zoom=200, dpi=72
Mac OS X v10.16, x86_64 (64 bit)
B2.7.0.2/4 az3

**Comment by parg** [comment]
Are you sure that the RSS feed encoding isn't borked in someway? I renamed a download to "Азбук", created an RSS feed from it and it displayed fine.

**Comment by rwmarvin** [comment]
Yes. I think you are correct. I was able to make another RSS feed and the Cyrillic is displaying correctly. Thanks for the insight.
