### ISSUE TITLE
BUG: Selected files in Files tab, priority is reset to normal when torrent is started

### ISSUE THREAD

**Issue by PrototypeZero** [BiglySoftware/BiglyBT#2093]
When in the files tab of a stopped torrent, if you press the start button to start the torrent the previously set priority for those highlighted files are reset to "Normal" from ie "Delete".
Can get a bit annoying with multi file torrent with lots of files you don't want and you've just finished selecting them and setting them to Delete/DND  you press to start to start the download and suddenly all those unwanted files start downloading too.

**Comment by parg** [comment]
It is a feature - when you have selected files in the Files View the toolbar start/stop buttons affect the selected files' state, not the downloads.

**Comment by PrototypeZero** [comment]
IMO It would make sense if clicking on start button with highlighted files downloaded ONLY those files and not start the whole torrent as it does now and change priority without any warning. Maybe have a button to do this specifically?

Otherwise whats the point of highlighting a file changing some priority if its going to reset them and start downloading ALL the files?

**Comment by parg** [comment]
I agree it is confusing, indeed I do think it is a bug that the 'start' button changes the priority of a stopped torrent's file(s) AND starts the download - it should either act on the file(s) OR the torrent - I'll take a look.
