### ISSUE TITLE
Missing Information

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#2099]
Just noticed this display issue.

![Missing Move on Copy](https://user-images.githubusercontent.com/37715552/117873185-822b7e80-b26d-11eb-9f8b-e01f2392ba46.jpg)

As you can see I am downloading files to `C:\TEMP`, They have the TAG `PLEX TV`. Here is the TAG Overview for `PLEX TV`.

![image](https://user-images.githubusercontent.com/37715552/117873595-f82fe580-b26d-11eb-9442-7ac69fa6b78f.png)

As you can see, there is a MOVE ON COMPLETE that is SET for `PLEX TV`.  But it is not showing as being SET in the Downloads section of the Active View (Image 1).

I only came across it because I wanted to change the MOVE ON COMPLETE to a different location. Only to find it saying it was not SET._

Interestingly, when I right-click and go to MOVE ON COMPLETE, it offers SET, but Clear is greyed out.  This suggests that the initial save location is being used from the TAG Settings, but is delaying setting the MOVE ON COMPLETE, until the file finishes. As it does put the files in the MOVE ON COMPLETE path.

Up to you to decide a course of action.

Java 1.8.0_291 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_291

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.7.0.3_B21/4 az3

**Comment by parg** [comment]
The 'move on complete' shown there is just the explicit one, not any Tag specific ones or the global default one.

**Comment by parg** [comment]
I could update it to show any Tag MOC currently in force if there is no explicit per-download MOC set I suppose

**Comment by parg** [comment]
B22 should show the Tag MOC when applicable

**Comment by NaPurHab** [comment]
As I said, up to you how your want to handle it.  The torrents were still downloading to the Initial Path. And I wanted to change the destination of the Move on Complete. I just thought it should show what will happen when complete.

![image](https://user-images.githubusercontent.com/37715552/118050181-d0fc1580-b34c-11eb-8e3f-227b26dcd3d8.png)

Seems a bit much to include both the Tag and Directory.   As you can see in the image, I already have the TAGS column beside it. So, including the TAG in the MOC is redundant.  Perhaps just the PATH would be better to save space. I had to widen the column to snip that image.

**Comment by parg** [comment]
Well in general it isn't redundant as (1) it makes it clear that it is tag related (2) you can have multiple assigned tags with MoC set

**Comment by NaPurHab** [comment]
I would think that the MOC should be conisder4ed as explicit.  As in when the download dialog is set and TAGs applied. Once OK is clicked, it should be considered as the same as a manually set MOC. 

![image](https://user-images.githubusercontent.com/37715552/118095714-683d8900-b39e-11eb-891a-d9caa047c711.png)

For example, in the above the line where it says C: and the storage stats.  There is a ton of white space to the right.  MOC is hidden under the MORE button.  And you can see the initial tags include `movies DC` which would set a MOC. Perhaps you could use that white space to show the MOC in download dialog that the TAGS would set. Or if the hidden MOC option was used. It is a lot of empty white space. 

As to the MOC field we are discussing, I like less clutter, so at least the brackets seem unnecessary. And instead of putting the TAG as text, you could just use the Green Tag from the TAGS field, a space, then the path. It would be shorter by a little.  i.e.   **`PLEX TV`** K:\PLEX TV       without the brackets and the ->.

**Comment by parg** [comment]
I'll put it back how it was
