### ISSUE TITLE
auto-prioritize reprioritizes when torrent is (re-)started, not just when torrent is added

### ISSUE THREAD

**Issue by david-bakin** [BiglySoftware/BiglyBT#2101]
[BiglyBT Beta 92.7.0.3_B22, Windows 2016 Datacenter]

This is new (and undesired, IMO) behavior:

Suppose you use the option "Auto-prioritize files with" to specify certain extensions you want promoted to high priority in a newly added torrent.  

1. Now add such a torrent.  Those files get prioritized "high" as expected (the rest are "normal" as expected).
1. Now start the torrent (don't know if this is necessary) and take those "high" files and set them to "normal" or "low".
1. Now stop the torrent.
1. Now exit biglybt and restart it (don't know if this is necessary).
1. Now look at the torrent: the files you manually set to "low" are still "low".
1. Now start the torrent.  Wait a second or two for the UI to update.
1. Now look at the torrent: the files you manually set to "low" have been moved back to "high".

That last line is the new (unwanted) behavior: It didn't used to do that.  The "auto prioritize" used to happen only when you added the torrent.  Manually changing a file's priority would persist.

Don't know when this started happening.  Just noticed it today since installing B22 but it could have been on B21 as well and I just didn't notice it.  But it must be fairly recent.

**Comment by parg** [comment]
Pretty sure it has always done that... looking at the initial BiglyBT code it sets the priorty on files every time the download is started,

**Comment by david-bakin** [comment]
Uhhh ... oookaaaay ... can't argue with the code but I was really sure this is new behavior ...

**Comment by parg** [comment]
I could probably hack it to only apply the auto-prioritisation only once, just wonder what it might bork :) 

What I can't easily fix is the fact that it will override any file priority changes made in the 'open torrent' dialog as the auto-prioritisation is applied when the download is started, by which time any intent from the 'open torrent' dialog has been applied and lost...
