### ISSUE TITLE
hard to select which file to download in the list/tree view if a download already started

### ISSUE THREAD

**Issue by legacychimera247** [BiglySoftware/BiglyBT#2102]
hello,
so, if i want to select some files that i haven't selected yet (or the contrary) on a torrent that has already started, i have to go to the files tab, which is very very small and confusing, yes i know i can resize it, but considering i would have to resize it back, wouldn't be nice to have a pop-up menu like the one when you are opening a torrent for the first time?

**Comment by parg** [comment]
Pop the Files View out as a separate window, do whatever and then close it.

**Comment by legacychimera247** [comment]
thank you this is what i needed, but now we have another problem, i noticed that if doing that and then selecting list/tree and then the same again, the app hangs for a few seconds then crashes... 

i could give you some terminal output if you tell me how to open biglybt from terminal (i'm on fedora workstation 34)

**Comment by parg** [comment]
If the BiglyBT process is crashing it often generates a dump file named hs_err_pid<process-id>.log in the install directory

**Comment by legacychimera247** [comment]
[hs_err_pid8557.log](https://github.com/BiglySoftware/BiglyBT/files/6487102/hs_err_pid8557.log)
[hs_err_pid10198.log](https://github.com/BiglySoftware/BiglyBT/files/6487103/hs_err_pid10198.log)
[hs_err_pid396110.log](https://github.com/BiglySoftware/BiglyBT/files/6487104/hs_err_pid396110.log)


thank you, there you are

**Comment by parg** [comment]
Looks like the same issue as another user reported

    https://bugs.eclipse.org/bugs/show_bug.cgi?id=573208

**Comment by legacychimera247** [comment]
well good to know i'm not the only one...

**Comment by FraMecca** [comment]
I have the same bug. Is there any news on this?

**Comment by parg** [comment]
No updates from the Eclipse project unfortunately ;(

**Comment by parg** [comment]
Hang on, just checking whether by "same bug" you mean the crash or the original issue "hard to select which file to download in the list/tree view if a download already started" ?

**Comment by parg** [comment]
See https://github.com/BiglySoftware/BiglyBT/issues/2087
