### ISSUE TITLE
Tree view enabled by default on torrent files selection

### ISSUE THREAD

**Issue by legacychimera247** [BiglySoftware/BiglyBT#2103]
Hello,

when you download a torrent with multiple folders inside, you generally use the tree view, cause the list one can be quite messy, it would be nice then, to have it by default, or at least when there is more than one folder in the torrent...

**Comment by parg** [comment]
The FilesView should remember your tree-view selection?

**Comment by legacychimera247** [comment]
the one on the tab bar yes, not the one when you open a torrent from browser...

**Comment by parg** [comment]
Ah! Having that dialog auto-open would be a bit weird, is it really that hard to click the 'tree view' button every time?

**Comment by legacychimera247** [comment]
just inconvenient i guess, deluge already have that and it's not weird, but at this point i guess we can close that, don't worry...
