### ISSUE TITLE
Checking after Allocating Issue is back.

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#2107]
![image](https://user-images.githubusercontent.com/37715552/118886989-b59e8680-b8c7-11eb-8660-955132c62767.png)

In the image note the currently Allocating, and the 2 Checking.  It is the Checking that I consider the issue.  Both are from the same set of 6 torrents I had just added. And both had just been allocated. Is it necessary that immediately after being allocated, they need checking?

Java 1.8.0_291 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_291

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.7.0.3_B23/4 az3

**Comment by parg** [comment]
They're both scheduled, not actually checking - are you sure that when they become active the actually required actual disk checks to be made to progress? All downloads go through a 'Checking' stage every time they start, it is just that most of the time when each piece is looked at it is found that an actual check isn't required.

I understand that for a newly added torrent you'd prefer not to see the checking state at all.

**Comment by NaPurHab** [comment]
I'm just reporting what I see. You will note that one of them shows 2.2% done, while the other shows 12.6% done.  To all appearances they are checking, though perhaps changed to scheduled to prioritise the allocation.

All I can say for sure is that they were just added and allocated. And checking of just allocated torrents was a issue previously.  Also, note the position numbers, there are 2 1s, 2 2s, and 2 3s, so the numbers should be from 1-8.

**Comment by parg** [comment]
It is an 'indicative position', i.e. an indication of perhaps when it will be scheduled.

For example, the two 'Moving' tasks with value 3. Either of them could actually run first depending on whether 'easystore' or 'video6' is available by the time they get to run.

**Comment by as-muncher** [comment]
Windows 21h1 x64
biglybt 2.8.0.0

A lot of times, even though I have told BiglyBT not to pre-allocate files, I'll start up BiglyBT just to get a "Allocating..." and then "checking..." for various torrents, even though I haven't touched the files on the hard drive.  I don't know if it's just a matter of BiglyBT taking too long to shut down, or what, as my hard drive is encrypted.  This doesn't happen all the time, but it does happen quite often.  I'm not killing the BiglyBT process using Task Manager or anything like that, just letting BiglyBT shut down normally.
