### ISSUE TITLE
Small Request.  Copy to Clipboard in About.

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#2108]
![image](https://user-images.githubusercontent.com/37715552/118887717-b97ed880-b8c8-11eb-8f3c-356c1d991da4.png)

Could you add a `Copy to Clipboard` for the System Info. Perhaps right of where it says System. I know it's a minor thing. But it might point out to people who take a look at the About, that there is a reason to copy the System Info.  I see many who neglect to include it.  Perhaps a way to gently remind them to do so.

Java 1.8.0_291 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_291

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.7.0.3_B23/4 az3

**Comment by parg** [comment]
Sure
