### ISSUE TITLE
What is the Tracker Server needed for?

### ISSUE THREAD

**Issue by coyote3** [BiglySoftware/BiglyBT#2109]
I just realized I have no idea what
Options|Tracker|Server
is for.

Is this just for people who want to host their own torrent tracker?  

I don't think I do; I just use external (public and private) trackers.  So is there any reason for me to engage a Dynamic DNS service to keep my external IP address current?

(Is DHT aided by this, for example?)

B2.7.0.3_B23/4 az2 on Win 10 Pro x64 Desktop

(Is it OK that I asked a question here, is there a better place to?)

**Comment by parg** [comment]
It is simply if you want to run your own tracker - 99.99% of people don't. 

If you were running a public tracker using BiglyBT then you would need a reliable IP/DNS name and might want to employ DDNS to achieve this if you didn't have a static IP at home. 

If you are not running a public tracker then you most likely don't need a DNS name (you only need one if you find yourself needing to enter it into BiglyBT configuration, so it is pretty evident)

The DHT doesn't use/benefit from a DNS name.
