### ISSUE TITLE
Request option to Ignore Queue|Seeding|First Priority Ratio

### ISSUE THREAD

**Issue by coyote3** [BiglySoftware/BiglyBT#2110]
A mod on a major tracker and I have been discussing this option.  We would both like to have the option to Ignore "A share ratio under".

Neither of us wish for share ratio to be a factor in our seeding First Priority.  Long ago without thinking about it much, I started setting it to "1:2".
(My un-thought-through thinking was that this would minimize the torrents it applied to.)

My mod friend, OTOH, has been setting it to "50:1" with the same goal (of minimizing the torrents it applied to).  
( I guess which better achieves our goal depends on what the ratios are on our torrents.)

But we'd both very much like to simply disable this with an "Ignore" option.

I understand if BiglyBT might consider this to be counter to BT etiquette.

But the reason we don't care is that our share ratios are enormous and all we care about is best serving the realtime needs of peers.

B2.7.0.3_B23/4 az2 on Win 10 Pro x64 Desktop

**Comment by parg** [comment]
I'll ask @TuxPaper - he's a seeding rule guru

**Comment by coyote3** [comment]
Thank you very much for considering this, Parg!!

**Comment by parg** [comment]
Next beta (B24) will have an 'ignore' option

**Comment by coyote3** [comment]
Parg, thank you **very** much!!!
