### ISSUE TITLE
Local peer issue

### ISSUE THREAD

**Issue by KirklandLaing** [BiglySoftware/BiglyBT#2111]
Hi, I'm using this torrent client. I'm in the UK and using a VPN server in Holland. The local peer on the torrent client however is in the UK. How is this possible please? Am I leaking my real location somehow?

* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment

**Comment by parg** [comment]
Where are you seeing the 'local peer' details?

**Comment by KirklandLaing** [comment]
Thanks for replying. When I click the "peers" button towards the bottom of the screen. The horizontal list of -- general -- files -- tags etc. The peers show up with the national flag. I might be downloading something from a dozen peers from various nations but all of their upload to me comes to me via the local peer.

**Comment by parg** [comment]
Ah, just ignore that, the 'local peer' is a constructed entry there to show aggregate peer data. It is probably showing a cached IP address

**Comment by KirklandLaing** [comment]
Many thanks. :)
