### ISSUE TITLE
An idea/suggestion: Consolidated "Moving..." boxes

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#2113]
Say you want to move the data for several torrents, all to the same place. 

1. You multi-select all <var>N</var> of the rows in the list
2. Right-click, choose **Advanced** > **Files** > **Move Data Files...**.
3. A folder-selection dialog comes up, so you pick a destination and hit **OK**
4. <var>N</var> individual **"Operation in Progress"** dialogs pop up.
5. They all then politely take turns, only allowing one move operation to be active at any given moment, until all of the data files are relocated.

At least for me, on Linux, step 5 is a bit worse than it sounds because it seems like the dialogs always stack in reverse order: The topmost one is the _last_ to activate, waiting for all of the previous operations to execute in dialogs hidden beneath it. The actively-copying dialog always seems to be the _bottom_-most one.

Since they're obviously communicating with each other _already_, though (in order to all wait their turn, like all well-behaved filesystem operations must), would it be possible to have the multiple operations all _combine_ into a single dialog? Like, after the first one comes up, additional operations just append themselves to that window instead of opening their own separate dialog? An "Operations [in Progress] Manager", if you will.

Just a thought, since the reverse-stacking behavior of the current multi-dialog functionality makes it slightly frustrating.

**Comment by parg** [comment]
The 'Disk Operations' view is probably what you want, it shows the active move operations and you can pause/cancel them from there if you want.

You can either manually close all the annoying separate move dialogs or disable them in the options

Interface->Display: suppress the file move popup dialog
