### ISSUE TITLE
Keep failed torrent-from-magnet in library

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2114]
* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment

Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B2.7.0.2/4 az3

I've been noticing that BiglyBT has been having a hard time downloading the necessary information when I cause it to open a magnet link.  BiglyBT fails with some sort of message.  What I'm asking is that you keep that failed magnet in the library.  If I'm going on to other things, and have closed down the web tab with that magnet link, and then you delete that failed magnet link from the library, then I've lost all that information.  At least if you keep that failed magnet in the library list, I can copy the magnet link from that and have qbittorrent try to download that information, which it has been successfully accomplishing consistently.

**Comment by parg** [comment]
Options->Plugins->Magnet URI Handler

Set the 'Overall lookup timeout' to 0

**Comment by as-muncher** [comment]
Ok, thanks.  You didn't want to make the value 0 by default?

**Comment by parg** [comment]
I don't suppose I did
