### ISSUE TITLE
Plenty of seeds online but file won't download 

### ISSUE THREAD

**Issue by GitHubFan123456** [BiglySoftware/BiglyBT#2115]
Hi,
Can you please help? 

1. Even though there are over 6 seeds currently "online" listed in the options for my download file, the file won't download and if it does download sporadically, it says it will take 30 - 300 plus days for a few seconds then will stop downloading altogether. 

2. Usually even when there is just 1 seed, the file downloads in a matter of a few minutes if not seconds because I have a very fast wifi connection and computer. Yet this file barely downloads or not at all even after several hours while there are over 6 seeds, over several hundred peers, and at least over 5 completed downloads online at the moment of this report.  The non-responsive file is acting as if there are 0 seeds. 

3. I've tried restarting BiglyBT and deleting the file from my computer and then re-uploading into BiglyBT several times already as well as restarting my computer. I've even tried stopping all other downloads and let this file be the only downloading file. 

What can be done to get this file to download? Usually this only happens when there are no seeds or completed downloads. Yet this is not the case with this file. I tried scrubbing all but relevant & allowable info in the attached screenshot. Screenshot was taken after 48 hours of trying all the above to no avail and giving each time several hours for download to work. 

Thank you for any help you can give. 

* OS and version: Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=200, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B2.7.0.2/4 az3

![BiglyBT prob DL vs Seeds SEND](https://user-images.githubusercontent.com/85142132/120256588-50418280-c243-11eb-8e6d-feb42b20e186.jpg)

* BiglyBT Version Number: 2.7.0.2 
* For *nix: Desktop Environment

**Comment by as-muncher** [comment]
Any update on this with current beta versions of BiglyBT?
