### ISSUE TITLE
Files tab for torrent details: where?

### ISSUE THREAD

**Issue by coyote3** [BiglySoftware/BiglyBT#2118]
I can't find the Files tab that used to be in torrent Details.  (Where I would set specific files to not download.)

2.7.0.3 b25

**Comment by parg** [comment]
Maybe you closed it - right-click in the tab-folder header area for a menu

**Comment by coyote3** [comment]
Bingo!!  Thanks parg; it never occurred to me those tabs were hide-able, stupid me!

**Comment by parg** [comment]
You can drag+drop them to re-order as well....
