### ISSUE TITLE
a small nitpick (typo)

### ISSUE THREAD

**Issue by Xemnarth** [BiglySoftware/BiglyBT#2120]
hovering over "stop selected torrent(s)" shows "start selected torrent(s) instead

**Comment by parg** [comment]
Anything in particular needed to trigger this? The tooltip seems to be correct for me.

**Comment by Xemnarth** [comment]
are you running the latest beta release?

**Comment by parg** [comment]
I created the latest beta release...

**Comment by Xemnarth** [comment]
issue persists even after latest stable release (2.9.0
![Screenshot 2021-11-23 123831](https://user-images.githubusercontent.com/6406869/142994194-bf3c8422-7430-48f0-97c1-9797c5db18ca.png)
)

**Comment by parg** [comment]
Fixed next beta (B03)
