### ISSUE TITLE
BiglyBT Newbie - Infinity ETA for downloading/No progress

### ISSUE THREAD

**Issue by nephsys** [BiglySoftware/BiglyBT#2121]
![image](https://user-images.githubusercontent.com/84450684/120851336-92830080-c570-11eb-9428-b64f690d15c0.png)

Hello everyone!

BiglyBT/Torrent newb here :) 

I've installed BiglyBT, tried to install a Sims codex and there is no estimated eta other than infinity.

There are seeds on the torrent link so I can rule this out. I've not done anything other than install BiglyBT and allow this through my firewall. 

My internet is good, over 300/ps so no issues there.

Do you know what may be the issue?

Thank you!

Neph

**Comment by parg** [comment]
Try downloading this torent:

https://download.documentfoundation.org/libreoffice/stable/7.1.3/win/x86_64/LibreOffice_7.1.3_Win_x64.msi.torrent

If it works then there must be an issue with whatever it is you are downloading.
