### ISSUE TITLE
Warning Icon weird behaviour

### ISSUE THREAD

**Issue by SUCM** [BiglySoftware/BiglyBT#2122]
* OS and version: WIN 10
* BiglyBT Version Number 2.7.0.2

unexpectedly discovered this. I typically always do click-to-show when there is the yellow warning icon at right bottom of Bigly to view, act and dismiss them.

today I did the click-to-show but then directly went to view the torrent reported in the warning without dismissing the warning, the warning floater disappeared and can no longer be brought up by click on the yellow icon (which hasn't disappear). I then right click yellow icon and click "Dismiss All" and the yellow icon disappeared. However, the warning floater with the (now) dismissed warning shows up again some time later without the yellow icon requiring me to go and dismiss it again

**Comment by parg** [comment]
The yellow warning window is an 'on top' dialog separate from the main UI. You can see this by making it visible and then moving the main window. It sounds as if somehow that dialog lost its 'on top'ness when you navigated away and then got it back later when it reappeared.

**Comment by SUCM** [comment]
I see. I had expected Dismiss All to rid of all warning msg and pop-ups especially for torrents with unreliable trackers that generate multiple errors hence warnings (ex. invalid hash) quite often, so that was a surprise
