### ISSUE TITLE
Tracker status DHT Backup only after exiting sleeping mode

### ISSUE THREAD

**Issue by CptVinyl** [BiglySoftware/BiglyBT#2123]
Hello. 
Today I discovered some strange BiglyBT behavior after starting PC from sleeping mode. 
All "seeding" torrents became with this status:
![BiglyBT_xnVvwOrJ4S](https://user-images.githubusercontent.com/84813181/120884205-470d3880-c5ea-11eb-88ba-4e3cd2172993.png)

When I check "Sources" the timer goes in negative value: 
![BiglyBT_GjMOGq5ZXg](https://user-images.githubusercontent.com/84813181/120884207-4bd1ec80-c5ea-11eb-9e6f-23d2986fe93e.png)

I tried to wait near 9-10 hours and torrents remained all time with that status. 
They will not start seeding, just counting time with "-". 
And there will be -9 hours on timer.  
Sorry no screenshot of that :(

But, relaunching BiglyBT fix this issue, all active torrents receive normal status and timers:
![BiglyBT_VBFTMxebAx](https://user-images.githubusercontent.com/84813181/120884210-4f657380-c5ea-11eb-9840-024f92c88f3e.png)
Also seeding became active and I see some uploads. 

It happens almost every time when I exiting sleeping mode (or hybernating) and when there is no internet at first minute when PC is starting up. 

What happens on my side:
- PC goes into sleeping mode with all active things (also internet connection is active) at 01:00 AM
- I starting the PC at 08:00 AM same day
- There is no internet connection from starting to 1-2 minutes after launch. 
- Checking Bigly BT and see DHT Backup only with negative timers.

Am I doing something wrong? Or this is normal activity?

The problem is relevant for stable and beta versions. 
I`m apologize if there is an answer somewhere, but I can not find IT. I check Bigly BT wiki several times, tried to google and check topics on Reddit, no info about that Bigly BT behavior. 

* OS and version - Windows 10 x 64 21H1 (19043.1023)
* BiglyBT Version - 2.7.0.3_B25 
Java 1.8.0_261 (64 bit)
 Oracle Corporation
jre1.8.0_261

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.7.0.3_B25/4 az3

**Comment by parg** [comment]
Hmm, that doesn't sound right! I'll investigate when I get a chance,

**Comment by CptVinyl** [comment]
Maybe I can help you somehow? 
Gather some logs... console logs? Or smt like that? 
But I need a small instruction how to do that. I`m still new to bigly bt :) 

Also small addition to my words. 
This issue I can repeat when rapidly put the computer to sleep and than turn it on without internet at first 1-2 minutes. 
Than put the computer to sleep again and turn it on and the issue will appear.

**Comment by parg** [comment]
I experimented on OSX with a torrent with a single tracker, disabled the wifi, put computer to sleep, waited a while, woke it back up, re-enabled network after a few minutes and I can't reproduce the issue. The tracker always recovers and successfully updates.

It sounds like for you the tracker update event is getting lost. You could try grabbing a 'debug.zip' diagnostic dump when the problem is being exhibitted (i.e. after computer wakes and you have an ever increasing negative time shown for the next tracker update) - go to the Help menu and select the last option there. 

Please email the debug.zip to paul@biglybt.com (rename it before sending to something like debug_zip to avoid any mailer issues)

Thanks!

**Comment by CptVinyl** [comment]
I just sent you the debug.zip on the e-mail that you provided.

**Comment by parg** [comment]
Thanks for that.

Looks like a bug in Java to me - all the tracker announce threads are stuck in 

        java.lang.Object.wait(Native Method)
        java.lang.Object.wait(Unknown Source)
        java.net.InetAddress.checkLookupTable(Unknown Source)
        java.net.InetAddress.getAddressesFromNameService(Unknown Source)
        java.net.InetAddress.getAllByName0(Unknown Source)
        java.net.InetAddress.getAllByName(Unknown Source)
        java.net.InetAddress.getAllByName(Unknown Source)
        java.net.InetAddress.getByName(Unknown Source)
        java.net.InetSocketAddress.<init>(Unknown Source)

or

       java.net.SocketInputStream.socketRead0(Native Method)
        java.net.SocketInputStream.socketRead(Unknown Source)
        java.net.SocketInputStream.read(Unknown Source)
        java.net.SocketInputStream.read(Unknown Source)
        java.io.BufferedInputStream.fill(Unknown Source)
        java.io.BufferedInputStream.read(Unknown Source)
        com.sun.jndi.dns.DnsClient.continueTcpQuery(Unknown Source)
        com.sun.jndi.dns.DnsClient.doTcpQuery(Unknown Source)
        com.sun.jndi.dns.DnsClient.query(Unknown Source)
        com.sun.jndi.dns.Resolver.query(Unknown Source)
        com.sun.jndi.dns.DnsContext.c_getAttributes(Unknown Source)
        com.sun.jndi.toolkit.ctx.ComponentDirContext.p_getAttributes(Unknown Source)
        com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.getAttributes(Unknown Source)
        com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.getAttributes(Unknown Source)
        sun.net.spi.nameservice.dns.DNSNameService$2.run(DNSNameService.java:176)
        sun.net.spi.nameservice.dns.DNSNameService$2.run(DNSNameService.java:174)
        java.security.AccessController.doPrivileged(Native Method)
        sun.net.spi.nameservice.dns.DNSNameService.resolve(DNSNameService.java:173)
        sun.net.spi.nameservice.dns.DNSNameService.lookupAllHostAddr(DNSNameService.java:291)
        sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
        sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        java.lang.reflect.Method.invoke(Unknown Source)
        com.biglybt.core.util.spi.AENameServiceDescriptor$NameServiceProxy.invokeSupport(AENameServiceDescriptor.java:348)
        com.biglybt.core.util.spi.AENameServiceDescriptor$NameServiceProxy.invoke(AENameServiceDescriptor.java:292)
        com.sun.proxy.$Proxy0.lookupAllHostAddr(Unknown Source)
        java.net.InetAddress.getAddressesFromNameService(Unknown Source)

which makes me think that the sleep/resume process has somehow resulted in some hung TCP connections to the DNS server.

You could try installing a more recent version of java - check out https://github.com/BiglySoftware/BiglyBT/wiki/Java-Versions

**Comment by CptVinyl** [comment]
Hm, thanks! 
I will try clean install of new version of Java and test this for a couple of days. 
I will report the results a little later.

May VPN connection cause this problem?

**Comment by CptVinyl** [comment]
Well yes. You was right, the problem was in Java. I reinstalled to JDK 16, but there was some text issues. 
So I installed JDK 15, and all running good. No problem after starting PC from sleeping mode.
Thanks!

**Comment by parg** [comment]
Thanks for the update!
