### ISSUE TITLE
Want to change but - Command Runner not supported

### ISSUE THREAD

**Issue by n1diot** [BiglySoftware/BiglyBT#213]
I am new to this forum, and apologies if I have posted in the wrong area.

I would like to change from Vuze to BiglyBT but one of my most important plugins seems not to be available.

I did install BiglyBT but had to remove this plugin - command runner.

I use command runner to automatically extract the RAR files into a directory when the download finishes.

My question is, is there any hope for BiglyBT to code the plugin (Command Runner) to the BuglyBT client?

Thank you in advance;
n1diot

**Comment by n1diot** [comment]
biglybt://install-plugin/azexec

Found the plugin - must have been developed, and I should have looked before posting!

**Comment by parg** [comment]
great!
