### ISSUE TITLE
Piece Map/Pieces  Acting Odd.

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#2130]
Make of this what you will. I will just include the Piece Map and the top part of the Pieces Tab. As you will see in the scroll bar for the Pieces Tab, it is very long. The only sequential setting that is in effect is:
![image](https://user-images.githubusercontent.com/37715552/122122570-fb813880-cdfa-11eb-9716-b8fca141e30c.png)
So all I can do is report this odd-looking behaviour, and let you think on it.

![image](https://user-images.githubusercontent.com/37715552/122121454-ab55a680-cdf9-11eb-967c-593357ccb9ce.png)
![image](https://user-images.githubusercontent.com/37715552/122121526-c1636700-cdf9-11eb-9729-a06b801e0ac5.png)

Java 1.8.0_291 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_291

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.7.0.3_B26/4 az3

Love the new COPY Button on About. Makes adding the System Info so easy.

**Comment by parg** [comment]
Thought about it a while, haven't got a clue! The piece picker isn't supposed to start that many active pieces, quite why it has done so, and seemingly given up after grabbing a few initial blocks, evades me.

If you select those pieces in the 'Pieces View' right-click and 'reset piece', does the issue reappear after a while?

**Comment by NaPurHab** [comment]
I just woke up, and time has moved past that point.  I had 4 files remaining in that torrent and that issue was spread over the first 3 of the 4, now on the last half of the last file and past the issue. So can't do more on that now, but will keep an eye open. Just thought I would point it out. Make of it what you will,
