### ISSUE TITLE
New Idea: Transition downloads to 'force seeding', if less than ## seeds.

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#2132]
I recently had a HD Fail, and am replacing a lot of content.  As a result, I sometimes need to Force a download that I want now, not when the queue gets to it. But I don't necessarily need to continue to Force Seed it later. But if it is a difficult to get torrent, because there are few seeds, slow seeds, or seeds that disappear for hours - coming and going. I want to Force Seed them after I download them. But not everything I am in a hurry to get.

Also, I have the habit of Longterm Seeding torrents with few seeds.  So, my idea is a new option in the Queue settings:

`Transition downloads to 'force seeding', if less than ## seeds.`
it could also be worded: `if ## or less seeds.`  if you wanted to do '<='.

I considered Constraints, but NEW is not a true Tag and has no settings.  And I only want it to apply to NEW Completed Torrents, not everything in my Library. Basically, a simple if/then when a download completes.

Now this is not to my view a sub-option of the `Transition force start to force seeding on complete`. As these would not be previously forced, but be a case of seeing a low seed count and deciding to keep the torrent alive.

Mockup of what I think it would look like:
![BiglyBT - Force Seeding on Low Seeds](https://user-images.githubusercontent.com/37715552/122612983-10a3d480-d052-11eb-8af5-781f8eb45540.jpg)

**Comment by parg** [comment]
I'd propose using a Tag with a constraint something like

`completed_age < 120 && seed_count < nnn`

and an 'execute on assign' of 'force start

**Comment by NaPurHab** [comment]
How should the scope be set.  This is why I suggested it as an option. Everyone from Newbies to Average users will not understand Constraints. It is more a Power User to Expert skill.

![image](https://user-images.githubusercontent.com/37715552/122977538-8914d900-d363-11eb-96f9-2a602cb45c78.png)

As to the `Execute on Assign`, perhaps just like there is a Drop Down for Scope, perhaps a Dropdown for `Execute on Assign` on the Tag Settings. If the `View in Sidebar` is unchecked, it would be useful to have, I had to turn `View in Sidebar` On the Off to set it.

And why `completed_age < 120` and not `isNew()`? Seems more specific.

**Comment by NaPurHab** [comment]
![image](https://user-images.githubusercontent.com/37715552/122982704-2fafa880-d369-11eb-8f4c-e6cd2feb6da9.png)
 Just tried the above without the `execute on assign` and it grabbed everything currently downloading. Instead of only applying to the files that are transitioning from Downloading to Seeding.

![image](https://user-images.githubusercontent.com/37715552/122984665-43f4a500-d36b-11eb-923c-1b3d102ca0ab.png)

I just tried `isNew()` instead of `completed_age < 120`, and I went from 44 down to 27 torrents selected.  But the `seed_count < 5` is not working as expected. Here is what is being selected with `seed_count < 5`.
![image](https://user-images.githubusercontent.com/37715552/122984362-eceed000-d36a-11eb-98c0-092dabd63601.png)

Obviously a lot of those have more than 5 seeds.
Good thing I didn't turn on the `Execute on Assign` just yet.

**Comment by NaPurHab** [comment]
Oh, and now I have a TAG that is pushing everything off to one side.  I was hoping for a Option that quietly does what it is designed for.
![image](https://user-images.githubusercontent.com/37715552/122985994-d47fb500-d36c-11eb-8eea-717da55c39f6.png)

**Comment by parg** [comment]
Oh well, never mind
