### ISSUE TITLE
Transfer Bar not staying on Top

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#2133]
The first image show where I have the transfer bar located.

![image](https://user-images.githubusercontent.com/37715552/122617514-6bd9c500-d05a-11eb-9031-d9ba1b4985f7.png)

At some point, and I have not been able to figure out what is the trigger. The Transfer Bar goes behind the BiglyBT window, as in the second image.

![image](https://user-images.githubusercontent.com/37715552/122617446-4b116f80-d05a-11eb-9e5b-fa12ea1a4c55.png)

When I turn it off and back on, it stays on top for a while. But again at some point will drop behind BiglyBT.  Annoying little problem.  I will let you think on it, not a rush.

Java 1.8.0_291 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_291

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.7.0.3_B26/4 az3

**Comment by dbareis** [comment]
My transfers bar was off (I think this morning), but still selected, toggling the value off and on restored it to it's normal location.

**Comment by parg** [comment]
That's a Windows feature as far as I know - BiglyBT just creates the windows with 'ON_TOP' specified - Windows is then supposed to ensure it is always above everything else.

**Comment by dbareis** [comment]
At least in my case the bar wasn't visible in it's normal location where there was no window (so either it had moved location or wasn't being displayed, reported in the past, it was restored to it's correct location)

**Comment by NaPurHab** [comment]
Well, it has been a month and a few versions. The transfer bar still drops behind BBT after varying times and no trigger that I can find.  Did a reboot before bed with nothing but my VPN Client and BBT running. And still the transfer bar was behind BBT in the morning.

Anyway, ADD it to your bucket list of things to do.  I'll wait for this to get fixed.

Java 1.8.0_291 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_291

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.8.0.1_B01/4 az3
