### ISSUE TITLE
Changing Priority in multi-file torrents from non-downloading to downloading resets list scrolling position

### ISSUE THREAD

**Issue by dizzyMongoose** [BiglySoftware/BiglyBT#2135]
When changing the Priority of files within the Files tab of a multi-file torrent, changing from a non-downloading (Delete/Do not download) to a downloading (Low/Normal/High) priority and vice versa resets the list scrolling position back to the top of the file list, which is annoying when trying to pick out a small subset of files near the end of a large torrent. Expected behavior would be for the list to maintain its current scrolling position and have the file priority changed without its position changing.

Note that changing between non-downloading priorities or downloading priorities doesn't exhibit this bug; it only happens when switching the downloading state. For example, you can change between Normal and Low without anything moving, but changing from Low to Delete will jump the file list back to the top of the torrent.

System:

Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=111
Windows 10 v10.0, amd64 (64 bit)
B2.7.0.2/4 az3

**Comment by parg** [comment]
I assume you don't have the 'hide files not selected for download' enabled?

**Comment by dizzyMongoose** [comment]
No, I don't, so I see all of the files in the torrent listed.

**Comment by NaPurHab** [comment]
@dizzyMongoose - I've seen this too. But since I usually use Ctrl or Shift to select multiple files it is less annoying.  Give multi-select a try. It will make it more manageable.
