### ISSUE TITLE
Too many files open error?

### ISSUE THREAD

**Issue by DumbJoe** [BiglySoftware/BiglyBT#2136]
Checking console command: `Disk read error: open fails for '[file path x]', File not found: [same file path x] (Too many open files)[03:27:35]`

When accessing WebUI: `d14:failure reason91:/media/sdk1/fffff/.biglybt/plugins/xmwebui/transmission/web/index.html (Too many open files)e`

**Comment by parg** [comment]
OS? 

Options->Files->Performance Options: Max files open for read/write ?

**Comment by DumbJoe** [comment]
It's Debian, no GUI.

**Comment by DumbJoe** [comment]
?
