### ISSUE TITLE
"completing and seeding" a torrent before recheck occurs.

### ISSUE THREAD

**Issue by pto199** [BiglySoftware/BiglyBT#2137]
So I have a problem occasionally with my internet connection where it goes down and then comes back up.

If a torrent is downloading during this drop, the piece its currently grabbing gets corrupted.  After the torrent is complete, it moves over to the seeding Q and does its recheck (I have biglybt set to recheck using the "re-check pieces when download is done" option).  It finds the corrupted piece, throws the torrent back into the download Q at like 99.8% or something, re downloads the piece and finishes again with another re-check, at which time is successful.

So while this works fine on its own, its causing problems when used in conjunction with radarr and sonarr.  Both radarr and sonarr begin processing (moving) a file as soon as its completed.  But they get the ok from biglybt as soon as the torrent is done, before it does its re-check.  So now radarr is importing this corrupted movie file.  After biglybt corrects it, its too late.  radarr already has the corrupted file.  Is there anyway biglybt can NOT put a file into the seeding q/have it be marked as completed until AFTER the recheck is complete and verified that its 100% ok?

**Comment by parg** [comment]
Pieces are downloaded, checked, written to disk - an internet interruption can't cause pieces to become corrupt because if the data received over the network is corrupted then the piece check will not succeed.

So your post-download piece check errors must be being caused by some local error.

When you say radarr/sonarr begin processing a file as soon as completed, how do they detect this completion event?

**Comment by NaPurHab** [comment]
I had no idea what radarr/sonarr were. But found the following Wiki that covers it all.  Looks useful.

[WikiArr](https://wiki.servarr.com/)

**Comment by pto199** [comment]
> 
> 
> Pieces are downloaded, checked, written to disk - an internet interruption can't cause pieces to become corrupt because if the data received over the network is corrupted then the piece check will not succeed.

Well I notice it happens when a torrent looses connection.  Regardless of the cause, the issue remains


> So your post-download piece check errors must be being caused by some local error.
> 
> When you say radarr/sonarr begin processing a file as soon as completed, how do they detect this completion event?

They poll the torrent client I suppose?  You enter the torrent client details into sonarr and radarr and it knows when downloading is finished.  Im not sure how, probably completed flag, or torrent switched to seeding from downloading.

Biglybt seems to put it into seeding mode right away, and then check as its seeding.  So radarr and sonarr see it as complete and begin moving the file over immediately.  No other torrent client seems to do this.  They all check before they turn into seeding mode.

**Comment by parg** [comment]
All other torrent clients perform an entire recheck post download?

**Comment by pto199** [comment]
> 
> 
> All other torrent clients perform an entire recheck post download?

If you enable it they do, just like biglybt.

I made a thread in the radarr forums to see if there was a delay for the softwares processing so I could give biglybt time to recheck.   Somebody there mentions qbittorrent and how it works properly. https://www.reddit.com/r/radarr/comments/o8leo6/how_to_delay_radarr_post_processing/

I mean I'm not hard pressed to use Biglybt, Ive just been using it for a long while and enjoy the UI and features.  But if nobody cares to look at this issue its ok, i'll just switch clients.  I was just thinking the dev(s) of this app might be interested in solving this problem with the client

**Comment by parg** [comment]
disable it for BiglyBT then

**Comment by parg** [comment]
Every piece is hash checked before writing it to disk during the download process. Therefore once the download is complete the file(s) will be correct on disk. The 'recheck on complete' is there to catch disk errors or potentially other software that has messed with the file post-download.
