### ISSUE TITLE
[feature req] "all trackers" filter request

### ISSUE THREAD

**Issue by iav** [BiglySoftware/BiglyBT#2140]
Plugins → All trackers view
Up part of window list of all trackers touched by BBT from the creation of earth.
Some of them offline for years.
Some of offline for years referenced in torrents, some not.

Would you please to add a way to sort by new type of a column  or a kind of checkmark on top, near the "find" field — to remove trackers not referred in torrents?
Ideal — both: checkbox "only referred in torrents", and column "referred in torrents", number of referred torrents.

**Comment by parg** [comment]
It is computationally expensive to acurately keep track of how many torrents each tracker currently occurs in which is why there isn't an existing 'number of torrents' column.

What is known is whether or not any torrents with a given tracker have been loaded in BiglyBT since it was last started - this could be used to populate a 'removable' column  along with the ability to remove such entries - any good?

**Comment by iav** [comment]
I ask for this option for:
1. look for torrents that need to be redownloaded because have a new release
2. remove outdated trackers from some "composite" multi-tracker torrents
3. detect obsoleted torrents (no one working tracker, or all tracker reject this torrent)

want to stop abuse network infrastructure trying to connect to down trackers for years.

yes, I think your proposal will help on this way

a little related: why on some trackers I receive notification by BBT "torrent not registered" with torrent name, but for many (on other trackers) — newer?

**Comment by parg** [comment]
If you have torrents with trackers that are dead then you should create a 'removal action' for them

Right-click the tracker in the All Trackers view, select 'Remove from Current and Future Downloads' and either create a new removal action for it or add it to an existing one you already created.

The 'removal actions' correspond to Tags and Tracker Templates that are configured to remove trackers as required.

**Comment by iav** [comment]
Yes, I already found this function. 
But trackers stay in list. lots, lots of trackers.
And now I look for a way to keep obsoleted trackers somewhere (to keep last ok and fail since info) but not see it in list when I no next periodic torrent housekeeping.

**Comment by parg** [comment]
"torrent not registered" means that the tracker doesn't know about the torrent. Some trackers (e.g. private trackers) have a list of authorised torrents. Others (e.g. public open trackers) don't and will accept any torrent without registration.

The All Trackers view will show the last error reported - if you have multiple torrents on a tracker that requires registration and one or more of the torrents has been removed from the tracker then you will get 'ok' reported for those still registered and 'not registered/...' for those that aren't.

**Comment by iav** [comment]
Thank you for clarification.
Then how BBT decides it should make a popup "torrent not registered" or keep it silent?

**Comment by parg** [comment]
If it is explicity reported by the tracker as a 'failure reason' in the protocol response then it is shown as a popup

**Comment by iav** [comment]
ok.
Then I'd like to have something to not to click one-by-one trackers to find non-empty (no one torrent use it).
Like your first proposal.
