### ISSUE TITLE
Extra Icons on Toolbar - What are they - How to get rid of them.

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#2142]
I maintain 2 media servers. On the 2nd, BiglyBT is showing icons I don't see on my system.
![image](https://user-images.githubusercontent.com/37715552/124025093-0c66a800-d9be-11eb-8af6-ebdb0114d100.png)

 by comparison here is my main system.
![image](https://user-images.githubusercontent.com/37715552/124025256-38822900-d9be-11eb-8710-5a26f26ad461.png)

What are the 2 Extra Icons in the middle of image? And how do I get rid of them. Already turned off `Automatically search for devices`.  And I don't see anything in `Options - Interface` that seem to apply.

Java 1.8.0_291 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_291

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.7.0.3_B26/4 az3

**Comment by parg** [comment]
They're UPnP media server renderers.

Disable the Media Server plugin if you don't want them.
