### ISSUE TITLE
feature/bugfix: filter for all trackers/all peers/all pieces views

### ISSUE THREAD

**Issue by Xyrio** [BiglySoftware/BiglyBT#2144]
filter should aslo support regex and its ! (not) operator, search case insensitiv
current state:
all trackers: has search element but regex search with ! does not work
all peers: no search element
all pieces: no search element

functionality already exists for search element in libraries view

in my case i wanted to exclude short connections (because i have disconnect seeds when seeding enabled) to column "Time Remaining" (sorted asc) which puts "Finished" values first (0 remaing time) in all peers view to stop the constant popin of other peers. or filter file names in all pieces view.

System: Windows 7, B2.7.0.2/4 az3

**Comment by parg** [comment]
all trackers does support ! however it also searches across both tracker name and status and is implemented incorrectly

**Comment by parg** [comment]
Not sure I understand your all-peers request - how would a search filter help? You can't just magically assume that the search filter searches on the field that you have in mind and not something else... Perhaps some modification to how things sort would work?

**Comment by Xyrio** [comment]
by default i would expect it to search all columns.
for all peers i gave the example what i tried to use it for. (excluding "Finished" when sorting asc by Time Remaining)

**Comment by parg** [comment]
No existing filters search by all columns - they generally search by whatever the 'name' column is

**Comment by Xyrio** [comment]
so add it? new feature?
another way would be to do it similar to how it works in library view. when : is used use what comes before it as column name search and what is after as content search. depending on mode both use either plain or regex search. 
example: 
(plain) name:.txt
(regex) remaining:!finished
when multiple columns match use first match or just concatenate all matches and search.
search the currently visible columns and use the localisation that is currently active (what the user sees as column names)

**Comment by parg** [comment]
BiglyBT is open source, maybe someone will do it for you

**Comment by Xyrio** [comment]
i c. if you dont want to do it thats ok :)

**Comment by parg** [comment]
latest beta has a search filter in the all-pieces view

**Comment by parg** [comment]
how about sorting all-peers by 'connected time' ?

**Comment by Xyrio** [comment]
i want them sorted by time remaining asc but dont want finished to appear at top pushing stuff down then disappearing again (because connections to seeds are dropped for seeding torrents by configuration) which makes list constantly move down/up making it hard to read. it is not a big deal. 

adding other columns to sort dont get rid of "Finished" ones appearing at the top since i want time remaining as the primary sorting column. the easy and intuitiv way is to use a filter that excludes "Finished".

**Comment by Xyrio** [comment]
confirmed:
all trackers ! operator with regex working
all pieces searces name

all peers could also at least search in name. that would still be useful sometimes.
