### ISSUE TITLE
Improve ARM support

### ISSUE THREAD

**Issue by jogger2510** [BiglySoftware/BiglyBT#2147]
I am running V2.7.0.2 on 32bit Armbian Buster. Possible by copying /usr/lib/java/swt-gtk-4.6.0.jar to ./swt/swt-unknown.jar. Works since years despite endless console error messages. However there is a GUI freeze when you click right-click on a torrent with a tooltip popping up at the very same moment. Need to quit via console then.

Workaround: Only right-click on positions in columns that do not provide tooltips such as percentages.

**Comment by parg** [comment]
meh! there is an option to disable tooltips in BiglyBT somewhere...
