### ISSUE TITLE
Too many Incoming Connections

### ISSUE THREAD

**Issue by eurobank** [BiglySoftware/BiglyBT#2148]
BiglyBT 2.7.0.2 and Windows 10/64 pro.

I have DHT disabled and MIDHT also disabled. And some dht related options also disabled in several places.

Still i have a huge ammount of Incomming connections and that creates some issues in other applications i use.

How can i limit this?

![2021-07-06 20_03_01-Window](https://user-images.githubusercontent.com/4467158/124640276-dcc01000-de95-11eb-86a3-475d29c05e54.png)

**Comment by parg** [comment]
Change your incoming port number, disable UPnP forwarding and make sure your router isn't forwarding connections

**Comment by eurobank** [comment]
"disable UPnP forwarding" where?

**Comment by parg** [comment]
Options->Plugins->UPnP

**Comment by eurobank** [comment]
thanks
