### ISSUE TITLE
How to send magnet uri to web remote access with curl?

### ISSUE THREAD

**Issue by gradha** [BiglySoftware/BiglyBT#2156]
Hi, I'm using the web access to add manually magnet uris:

![add](https://user-images.githubusercontent.com/101927/125280086-f8ec0300-e314-11eb-969d-968347aa5b2c.png)

Since Safari doesn't support magnet uris, I was thinking of creating a local app which would open when safari clicks on a magnet uri, then perform a curl post request to the web remote control. However, I'm not getting it to work. I've tried to prototype the post request with Insomnia putting the HTML's forms into a Multipart request, but the uri doesn't get added and the server just answers with 200 and returns an HTML:

```
* Preparing request to http://host:9091/#
* Current time is 2021-07-12T11:24:58.178Z
* Using libcurl/7.73.0 OpenSSL/1.1.1j zlib/1.2.11 brotli/1.0.9 zstd/1.4.9 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.41.0
* Using default HTTP version
* Disable timeout
* Enable automatic URL encoding
* Enable SSL validation
* Enable cookie sending with jar of 2 cookies
* Too old connection (221 seconds), disconnect it
* Connection 2 seems to be dead!
* Closing connection 2
* Hostname in DNS cache was stale, zapped
*   Trying 192.168.200.1:9091...
* Connected to host (192.168.200.1) port 9091 (#3)

> POST / HTTP/1.1
> Host: host:9091
> User-Agent: insomnia/2021.3.0
> Cookie: X-Transmission-Session-Id=0x1.518ab16a4a4e8p-4; vuze_pairing_sc=GEGZYPFTN6TMQNCWBAJ5LJQHFATLCJYC
> Content-Type: multipart/form-data; boundary=X-INSOMNIA-BOUNDARY
> Authorization: Basic Z3JhZGhhOmdyYWRoYQ==
> Accept: */*
> Content-Length: 644

| --X-INSOMNIA-BOUNDARY
| Content-Disposition: form-data; name="torrent_upload_url"
| magnet:?xt=urn:btih:03e76f903f…
| --X-INSOMNIA-BOUNDARY
| Content-Disposition: form-data; name="add-dialog-folder-input"
| /Users/user/torrents
| --X-INSOMNIA-BOUNDARY
| Content-Disposition: form-data; name="torrent_auto_start"
| 1
| --X-INSOMNIA-BOUNDARY--

* We are completely uploaded and fine
* Mark bundle as not supporting multiuse

< HTTP/1.1 200 OK
< Last-Modified: Mon, 12 Jul 2021 11:24:58 GMT
< Expires: Mon, 12 Jul 2021 11:24:58 GMT
```

Is it possible to perform such a request with curl?

**Comment by parg** [comment]
That won't work. If you look at the web remote code in "transmission.js" you will see that the form fields are extracted and sent to BiglyBT as an AJAX request...

If you launch the BiglyBT.app with a magnet-uri as an argument it might pass it to an existing running BiglyBT instance, works on Windows, not so sure about OSX.

**Comment by gradha** [comment]
Did manage to get that working, for reference I ran `java -jar BiglyBT/.biglybt/BiglyBT.jar magnet:foobar`. I could put that behind a simple mini web form and request through curl from another machine. However, an undesirable effect of this is that the BiglyBT app was started in _low resources mode_ without windows, and running the command opens the window. Is there any additional switch that could be tacked on the command line to prevent this from happening?

**Comment by parg** [comment]
I was thinking more like "open -a BiglyBT.app magnet:foobar" - can you get something like that to work?

**Comment by gradha** [comment]
It works the same way, the app is brought to front on the machine.
