### ISSUE TITLE
[packaging question]  how I change the code to force instaltations in user dir ? 

### ISSUE THREAD

**Issue by sergiomb2** [BiglySoftware/BiglyBT#2157]
biglybt when starts in a clean environment  try install azupdater and dorkbox-tray on /usr/share/java/biglybt when works well if install locally 

* Fedora 33 to Fedora 35 
* BiglyBT last version 
* Any Desktop

**Comment by parg** [comment]
https://github.com/BiglySoftware/BiglyBT/wiki/Command-Line-Options has a section on options required to install a second instance of BiglyBT which shows what to set to force everything to a single dir
