### ISSUE TITLE
Run two UIs at the same time

### ISSUE THREAD

**Issue by moham96** [BiglySoftware/BiglyBT#216]
Hi,
is it possible to run the console ui and the swt ui at the same time ?
I run biglybt as a deamon in a raspberrypi using console ui but sometimes  i need to run the swt ui (gui) to change some settings which is easier in the gui than the console ui but the program complains that another instance is already running. so i have to kill the daemon every time i open the gui. is there another way where running the gui just connects to the daemon (like in deluge)?

**Comment by parg** [comment]
The console UI has a command to start the SWT UI:

ui swt

You can subsequently close the SWT ui and keep the console UI running via a File menu option

**Comment by moham96** [comment]
@parg yeah that worked,  thanks

**Comment by moham96** [comment]
Hi, 
I'm facing new issues again.
I'm trying to manage biglybt on a headless vps but as previous issues i posted it seems that in the end i have to use the swt gui for some features, so to keep the load to minimum on my vps i didn't install and run a full-fledged desktop environment, instead a made a simple setup with vnc server and a i3wm window manager.
The server execute the following command on boot:

> /usr/bin/java -cp "home/mohammad/biglybt/BiglyBT.jar:/home/mohammad/biglybt/dorkbox-systemtray.jar:/home/mohammad/biglybt/commons-cli.jar:/home/mohammad/biglybt/log4j.jar:/home/mohammad/biglybt/junit.jar:/home/mohammad/biglybt/swt.jar" com.biglybt.ui.Main --ui="console,telnet"
This command is run inside a systemd service which has `Environment="DISPLAY=:1"` so that when i run the command below it can find the correct X server display.

Now if I want to run the swt interface i use my vncviewer to login to the vps and run:
`/usr/bin/java -cp "$HOME/biglybt/BiglyBT.jar" com.biglybt.ui.Main --ui=swt --open`
which will spin the swt window and i can do what i wanted to do and then close it, which will only close the window and not kill the main process that runs the consoleui and telnetui (this was added recently ? it used to kill the process i think), now there are two problems here
- Given that i login using a vnc in [virtual mode](https://www.realvnc.com/en/connect/docs/man/vncserver-virtuald.html) this means that as soon as I log out of the vnc session it will close all windows and kill the X server, the problem is that right now if the X server is killed (logout of vnc) it will cause the main process to be killed and not just the window with this error in the terminal:


`Gdk-Message: 14:37:56.373: BiglyBT: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.`

I think this should just cause the biglybt window to close instead of crashing the main service running in systemd

- If for some reason it failed to start the swt interface (for example if the DISPLAY variable is not set or incorrect) it will kill the main process with this error displayed:
`Unable to init server: Could not connect: Connection refused`
instead of just displaying an error, this is not a big issue since I always have the DISPLAY variable set, but just in case other issue happen that causes the swt to not work, is it possible to have it so that it doesn't crash the main process ?
