### ISSUE TITLE
Feature request - Version overrides

### ISSUE THREAD

**Issue by clefranc** [BiglySoftware/BiglyBT#2165]
Hi,
Is it possible to have an option to overrides the current version exposed by BiglyBT to trackers?

Christian

**Comment by parg** [comment]
Unfortunately that is a contentious issue - private trackers generally ban clients that report fake version numbers.

**Comment by clefranc** [comment]
@parg, not fake, hardcoded previous versions, so an upgrade doesn’t deny access until new version allowed.

**Comment by parg** [comment]
I know what you're saying, but that's not the way tracker admins see it
