### ISSUE TITLE
Pending Items not showing in Disk Operations

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#2166]
I am using `Export Data and Torrent Files` to backup some torrents that had low seeds and were very slow to get.  The Target drive is a Wireless MyPassport Pro. I had a drive die and lost a lot of content. Now that I have replaced it, I am re-acquiring all the lost data. But it is slow for some. I have 1 torrent that only has one seed in Suriname, and never tops 10kbit/s, it should be complete in about 6 months. Hence the backups.

![image](https://user-images.githubusercontent.com/37715552/126223706-1759c1bc-bfd5-4d03-9c38-53eee13260d9.png)

The thing of note is that I selected 4 Torrents, and it is currently working on the 2nd of 4 torrents. But as you can see in the image, it only shows the current torrent. There should be 2 more items queued for Export. Also, the status, size and done fields are empty.

Could you do a bit a refinement on the Disk Operations so it shows the pending exports. Size, Done and Status I will leave to you. But pending items not showing is an issue.

Java 1.8.0_291 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_291

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.8.0.1_B01/4 az3

**Comment by parg** [comment]
Try B02.

The operations will run concurrently unless you enable 

Files->Performance Options: Limit active major disk operations (...) to one per file system

**Comment by NaPurHab** [comment]
It is not a matter of concurrent.  In a Move or Allocate, pending jobs are queued. And there is a % done that shows.  Export Data and Torrent files, seems to be the exception.  I am using the `Limit active major disk operations (...) to one per file system`. 

I started 4 Jobes for Export. That was the 2nd. Where are the other 2?  Concurrent is not an issue. And useless as the device I am exporting to is Wireless, so slower still that between internal HDs. If I turn off the limit, at lease Move and Allocate show multiple jobs.  Export is the Exception, it only show the current one.

B02 does me no use as I have 28 Exports going now and I can only guess it is about half done after 12 hours. As it is not showing the remaining jobs, I can't even Cancel them. Judging by looking at source and destination in file explorer, I have about 600 GB left to export to a Wireless MyPassport Pro. Since it already did 745gb of the 28 jobs, I should be able to try B02 in about 11 hours.

**Comment by parg** [comment]
Stop moaning before you've even tried it

**Comment by NaPurHab** [comment]
The Moaning was the 28 Exports that I could not see. And were not in Disk Operations.  Now it's working. But I had to wait almost 24 hours for those to complete.

![image](https://user-images.githubusercontent.com/37715552/126514678-55214c55-8d44-47e8-b75f-3a91e38b237e.png)

Now working for Exports. 

Java 1.8.0_291 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_291

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.8.0.1_B03/4 az3
