### ISSUE TITLE
Wrong link in Vuze popup for BiglyBT update!

### ISSUE THREAD

**Issue by Pasharacc** [BiglySoftware/BiglyBT#2170]
The link in the popup directs you to biglybt.net and not .com (so the page doesnt load, had to google you guys)
Mailed this to the info@ address as well.
Nice to know you guys are still out there - keep up the good work!

* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment

**Comment by parg** [comment]
Looks like a few domains had some configuration errors, thanks!
