### ISSUE TITLE
Request: Disk Read Error - More Info in the report.

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#2171]
![image](https://user-images.githubusercontent.com/37715552/126861883-b662ba53-3a73-4f02-9364-945d86eaf892.png)

Could you make this error include the Drive Letter.  This could indicate a drive failing, but without a reference, there is no way to know where the problem is.

i.e.  Disk Write Error (X:): flush: inconsistent entry length, position wrong

You should also do this to all other similar error reports that can benefit from the addition of a simple Drive Letter.

Java 1.8.0_291 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_291

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.8.0.1_B03/4 az3

**Comment by parg** [comment]
Don't you end up with a download in an error state when this happens? That should give you drive details (assuming the download is being saved to a single drive)

**Comment by NaPurHab** [comment]
Yes, but it has always been annoying how Error Reports often lack information.  Microsoft's Blue Screen of Death is an example. Just an Error Code, that you have to note down, lookup, and then find it really doesn't explain anything. Sure, I figure it out. But newbies need information to help them. And is adding a Drive letter such a problem.

Just like I would like to see every page in Tools/Options have a HELP link, that would point at a Wiki page with more information.

Documentation is a weakness of all software. Sometimes it is a lack of documentation. Other like some of the manuals for various tech out of Asia, clearly need a proof reader before going to print. regardless more information is always a good thing.

And now that paper manuals are no longer as needed, since we can supply documentation electronically. There is less reason to not have that documentation.

Which reminds me. Was on Wikipedia. VUZE has a wikipedia page, BiglyBT does not.  It could help get more users for BiglyBT. If linked to the Vuze Article, it could help Vuze users looking for an update.

**Comment by parg** [comment]
Wikipedia has repeatedly removed articles about BiglyBT - feel free to try and make one...

They also remove any attempt to add BiglyBT to https://en.wikipedia.org/wiki/Comparison_of_BitTorrent_clients

In the "good old days" we had users that were willing to invest time in writing and maintaining a wiki. It is a non-trivial process. I personally don't have the time or energy to both code BiglyBT and manage a wiki.

**Comment by NaPurHab** [comment]
Have you tried the methods listed at:
https://en.wikipedia.org/wiki/Wikipedia:Dispute_resolution
It seems odd that articles about BiglyBT are removed, without a reason being given. Especially when https://wiki.vuze.com/ appears to be hosted on Wikipedia platform. There are elements at the top that make it look like it.  If all else fails, we could start a write in campaign to Wikipedia about their bias in this case.
