### ISSUE TITLE
[Feature Request] Add a tag constraint scope "New Download / Torrent Renaming" or add Re-evaluation Delay

### ISSUE THREAD

**Issue by rajibkhan** [BiglySoftware/BiglyBT#2175]
<Feature Request>

PROBLEM: 
Lots of tags with constraints for automation having "Addition and Removal" can tremendously slow down a system with significant number of torrents in the library. Such slowdown is even more pronounced when there are Regex based name matching for auto tagging.

SOLUTION:
Instead of continuously re-evaluating all torrents all the time, it would be better if there is a scope to re/evaluate a torrent with match() function only when a torrent is newly added or when a torrent is renamed.

Alternatively, there can be way to add a re-evaluation delay time before an auto tag with scope:addition/removal is re-evaluated.

In fact, there can be global option to set such delay timer for all auto tags to be easy on older systems.

Thanks

**Comment by parg** [comment]
'matches' results are supposed to be cached although looking at it I'm not happy with it - I'll rework that a bit

**Comment by parg** [comment]
Beta B05 has a bit of rework and a config parameter under Options->Interface->Tags to specify the re-evaluation frequency (default 30 seconds as it was before).

Have a play and see if that improves/breaks things

**Comment by rajibkhan** [comment]
> Beta B05 has a bit of rework and a config parameter under Options->Interface->Tags to specify the re-evaluation frequency (default 30 seconds as it was before).
> 
> Have a play and see if that improves/breaks things

@parg Thanks for the info. I haven't checked out that Beta yet. I intend to give it a try.

**Comment by rajibkhan** [comment]
@parg Hope you're doing well. I was quite busy for a while. And now I'd like to give Beta that you suggested a try. 
However, pardon my ignorance, I cannot seem to find our from where can I download the beta compilation. 
Where is it available? any URL? Your help will be appreciated. 

Thx.

**Comment by NaPurHab** [comment]
I'm having a problem with the `Help/Check for Updates` finding the new betas.  My solution is to download them from the `Chat: Public - 'BiglyBT: Updates: Core[R]`.  Here is what is currently available there:

![image](https://user-images.githubusercontent.com/37715552/129517426-b82aa5af-c332-44b9-99e2-8549ce2cedcb.png)

**Comment by rajibkhan** [comment]
> Beta B05 has a bit of rework and a config parameter under Options->Interface->Tags to specify the re-evaluation frequency (default 30 seconds as it was before).
> 
> Have a play and see if that improves/breaks things

@parg Yes, that makes the UI somewhat faster and more responsive when increased sufficiently higher. Since I have a lot of torrents and lot of tags, I increased it to 300s. maybe I'll play around more to find my sweetspot. Though, the same setting for each constraint could be give more granular control, because for some tags, only once an hour evaluation can be good enough, just saying. 

However, about that settings, there is a subsequent issue with the settings visibility. Once the interval settings in options>interface>tags is changed and saved, and you move to another option page, and then come back to tags page again, the interval settings becomes hidden. It comes back again when the options page/windows is closed and reopened all over again.

**Comment by parg** [comment]
oops, fixed next build
