### ISSUE TITLE
Secondary Window opening when I download from search

### ISSUE THREAD

**Issue by Swampgirl** [BiglySoftware/BiglyBT#2178]
* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment
* 
OS Sierra, Bigly 2.8.0.0
Hi to all!
I just updated to latest version, and discovered that a new (new to me), window opens when I search one of my subscriptions that replicates the search results. How do I prevent this from happening?  I did read through the questions, but after a while I stopped because I do not even know what I am looking for. It seems like it would be a display setting, but if it is, I don't know which one. So this is not a universal problem per se, as much as something I don't know about because I have been slow to update.

Thank you for fixing all my previous nits. Always grateful for the work you do.

**Comment by parg** [comment]
That will open if you double-click the side bar entry as opposed to single clicking it to select it

**Comment by Swampgirl** [comment]
Thank you Parg. 
After leaving this question, I went back to the software, and your answer became all too apparent. I'm "a double-clicker" from way back. I've since changed my ways. 

Thank you again.
I wish all my problems were this easily rectified!
