### ISSUE TITLE
log file of previously opened videos?

### ISSUE THREAD

**Issue by mkrier** [BiglySoftware/BiglyBT#2179]
UPDATE: oops I realized I posted this on the biglybt page not the VLC list thanks sorry!

Java 11.0.11 (64 bit)
  Ubuntu
/usr/lib/jvm/java-11-openjdk-amd64

SWT v4924r25, gtk/3.22.30, zoom=100, dpi=94
Linux v5.4.0-80-generic, amd64 (64 bit)
B2.2.0.2/4 az3
Ubuntu 18.04 gnome (do you want gnome version where do I find that? it's whatever came with 18.04)

Is there a log file for what videos have been seen? 

(Btw if you're wondering why I'm running such an old version it's because it won't upgrade.  I tell it to upgrade, it restarts and asks me to upgrade again. Lather, rinse, repeat. I've reported it before no need to rehash it here thanks. I bet the log file will be in the same location.)

thanks

**Comment by parg** [comment]
There's no history of what you have and haven't opened/played/run/whatever. There is "Download History" (See the View menu) that tells you what you have downloaded though.

**Comment by mkrier** [comment]
> There's no history of what you have and haven't opened/played/run/whatever. There is "Download History" (See the View menu) that tells you what you have downloaded though.

Oh thanks sorry I realized I was posting this on the biglybt page not the vlc page.
