### ISSUE TITLE
Constraints using contained file names or file count

### ISSUE THREAD

**Issue by carl0ski** [BiglySoftware/BiglyBT#218]
This will assist in tagging and arranging torrents based on their file contents such as 
treat 1 .iso file or multiple zip files differently

**Comment by parg** [comment]
file_count and file_names will be in the next beta. example usage:

isEQ( file_count, 1 )

contains( file_names, ".zip" )
matches( file_names, "zip$" )

**Comment by parg** [comment]
B31 is now out, please test

**Comment by TuxPaper** [comment]
closing because I'm sure it works awesomely the OP is speechless.
