### ISSUE TITLE
Screen realestate

### ISSUE THREAD

**Issue by hglecke** [BiglySoftware/BiglyBT#2181]
When creating a subscription by selecting "find more like this..." the subscription is created ok.
However, the title is displayed with an automatically added prefix 'More:' . To display meaningful information, the column width has to be made wide enough to display this prefix and the title. Yes, I can edit the display of each subscription entry, individually, eliminating the unwanted prefix, a cumbersome process.
Is that prefix needed at all?

Thanks

Win10
2.8.0.1_b05 and earlier

**Comment by parg** [comment]
I was going to look at this - why the lost of interest? :)

**Comment by hglecke** [comment]
HiSorry, no lost interest.Just some butterfingers trying to correct an accidental duplication. Guess I should have left bad enough alone.
Thanks for checking back.Thanks for taking a look.
Helmut
Sent from the all new AOL app for Android 
 
  On Sat, Jul 31, 2021 at 5:52 PM, ***@***.***> wrote:   


I was going to look at this - why the lost of interest? :)

**Comment by parg** [comment]
I thought about adding an option to set the subscription name when creating it but then decided too much effort and just removed the "More: " prefix - live in beta B06

**Comment by hglecke** [comment]
Thanks for an impressive response.Helmut

Sent from the all new AOL app for Android 
 
  On Sun, Aug 1, 2021 at 12:35 PM, ***@***.***> wrote:   


I thought about adding an option to set the subscription name when creating it but then decided too much effort and just removed the "More: " prefix - live in beta B06
