### ISSUE TITLE
Restored archives, not finding torrent files, after move of backup dir.

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#2183]
![image](https://user-images.githubusercontent.com/37715552/127768971-b6e81c0a-edb9-4154-9656-5a39df9254ac.png)

I keep getting this type of error on items that were archived, but restored so I could export them to a new drive that will be an offline archive.

I recently made changes to my system and one of those was a WD Black 7200rpm drive.  I partitioned a small partition on the end of the drive to handle my Plex Database and the BiglyBT torrents and backups. All of which generate a lot of small files that cause a lot of fragmentation when on the same drive as video content.  On this small partition, they can fragment all they want and I won't need to defrag my video drives as much.

The change was that I changed this:
![image](https://user-images.githubusercontent.com/37715552/127769219-dd1fa999-f047-486d-a506-f4c5ba506dd3.png)

to this:
![image](https://user-images.githubusercontent.com/37715552/127769240-081b599b-79dc-4f91-84d4-88638e259953.png)

And moved the contents of the BiglyBT Dir to the new drive X: .   That included all the torrent backups, and the scheduled BBT Backups.   When I restored from Achived torrents, they don't look to the backup directory for the torrents, but the OLD path.

Since others may do something similar.  Could we get a fix so that restored archives, wither days, weeks, months or years in the archive. Will look for the backup torrents in the path define. Instead of an old path that was stored when originally archived.

Java 1.8.0_301 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_301

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.8.0.1_B05/4 az3

**Comment by parg** [comment]
shure

**Comment by parg** [comment]
B06 should perform better, report if not!

**Comment by NaPurHab** [comment]
I have been checking for B06, but as the image taken at 20:18 GMT shows, it's not showing up.

![image](https://user-images.githubusercontent.com/37715552/128241853-0aaee538-8151-443b-bcd2-e1eab2929d60.png)

This shows up from time to time as a problem, Usually I check the BiglyBT: Updates: Core [R]  to manually get it but here is a clip I just took:

![image](https://user-images.githubusercontent.com/37715552/128242388-951c53f5-8b24-400a-bec9-f3fe305c6cac.png)

Did it somehow not get posted?

**Comment by parg** [comment]
\o/
