### ISSUE TITLE
Scrape Error: Transport unavailable, Address already in use: Cannot bind

### ISSUE THREAD

**Issue by nokti** [BiglySoftware/BiglyBT#2187]
* Win10
* BiglyBT 2.8.0

Today I am getting this error on all my torrents. What is it and how do I fix it? I haven't changed any of the settings so I don't know what's wrong.

edit: I changed the port for BBT and the error has disappeared. I'm checking what application was using the same port as BBT but all I see is svchost.exe (LocalServiceAndNoImpersonation -p), which is I think a legit Windows process.

**Comment by parg** [comment]
Weird - what was the original port number causing the problems?

**Comment by nokti** [comment]
61600 It's been the same port for ages ...

**Comment by coyote3** [comment]
I started getting this message after enabling a VPN even though I excluded BiglyBT from it (split tunneling).  The message
"Scrape Error: Transport unavailable, Cannot assign requested address: Cannot bind (< 5m)"
doesn't appear on some torrents that seem OK and have peers.  (Though for some reason the Dimeadozen tracker shows me as firewalled.)  I'm very confused.

**Comment by parg** [comment]
An issue for your VPN support perhaps? 

If you excluded BiglyBT from being affected by the VPN then why would enabling the VPN break BiglyBT?

**Comment by parg** [comment]
I wouldnt spend the money!
