### ISSUE TITLE
BiglyBT interrupted shut down error when shutting down iMac - Operation In Progress Closing

### ISSUE THREAD

**Issue by Stepcraft** [BiglySoftware/BiglyBT#2188]
I recently upgraded from BiglyBT version 2.2.0.2 to 2.7.0.2. I was using 2.2.0.2 on an old 2012 iMac and it worked perfectly. I bought a new 2020 iMac and upgraded to 2.7.0.2.

I'm having a problem with BiglyBT shutting down properly. When I try to shut down my iMac with the "Shut down" option under the Apple Menu, I get a system error saying "BiglyBT interrupted shut down. To continue shutting down, quit BiglyBT". I can see that BiglyBT is starting to shut down with its window showing "Operation In Progress - Closing BiglyBT". This shutdown process seems to take a long time. With 2.2.0.2 it quit immediately and didn't cause any issues when shutting down my iMac.

Is there a way to change a setting on BiglyBT to fix the shutdown problem? Why does it take so long to shut down compared to 2.2.0.2?

**Thanks for all your hard work on BiglyBT. It's an amazing app!**

My specs:
iMac (Retina 5K, 27-inch, 2020) / 128 GB / 3.6 GHz 10-Core Intel Core i9 / macOS Big Sur 11.5 (20G71)
Java 1.8.0_301 (64 bit) / BiglyBT 2.7.0.2

This screenshot is from my system when I try to shut down my iMac:
![BiglyBT interrupted shut down](https://user-images.githubusercontent.com/59187451/128269053-d909cfbe-94b1-44f8-9f61-d70d907104f5.jpg)

This screenshot is from BiglyBT:
![BiglyBT Closing Operation In Progress](https://user-images.githubusercontent.com/59187451/128269076-6b968463-a380-486d-b7f5-5225302f3012.jpg)

**Comment by parg** [comment]
Does it always get stuck on "Stopping mlDHT"? 

The BiglyBT closedown process was improved to allow things to shut down tidily but this was mainly in the area of ensuring that all trackers had been updated with the 'stopped' state. This part of the process has a timer that can be adjusted (Options->Tracker->Client: maximum time to wait for tracker updates on closedown )

The rest of the closing down interface is just about reporting what's going on.

If it is always getting stuck on the mlDHT one then there's something weird with that. Otherwise you might finf that lowering the tracker timeout helps.

Or of course close BiglyBT by hand first :)

**Comment by Stepcraft** [comment]
No. It does not get stuck on "Stopping mlDHT". Sorry, that screenshot was probably misleading. I just happened to take the screenshot at that exact moment. It normally looks like this:

![BiglyBT Closing Operation in Progress Waiting 20 Seconds](https://user-images.githubusercontent.com/59187451/128370394-e0345d9a-3a1f-4b74-8326-a77660047160.jpg)

Changing the "maximum time to wait for tracker updates on closedown" to 0 helped a lot. I still get the system error, but even though it gives the error, after a few seconds it continues the system shutdown. I don't have to click the "Try Again" button, it continues the shutdown without clicking it.

You mentioned the closedown process was improved to "ensuring that all trackers had been updated with the 'stopped' state". Am I causing any issues with setting the max time to 0? Why does it matter if the trackers are updated with "stopped" instead of just disconnecting from them?

Thanks for all your help! You're awesome!

**Comment by parg** [comment]
Trackers, particularly private ones, keep a total of what you have uploaded and downloaded in order for them to calculate things like your share-ratio. They are periodically updated while a torrent is running and also at the point the torrent 'stops'. If BiglyBT is closed without reporting the latest stats then they are lost (there is no clean way of reporting them later on restart). 

Also when the "stopped" event is received by the tracker it should remove your peer from its active list and therefore not pass your details out to other active peers, thus saving the other peers the hassle of trying and failing to connect to you.

Like I said, this is of particular value to private trackers where they often enforce things based on this data - if you are only downloading from public trackers then it isn't such an issue.

**Comment by Stepcraft** [comment]
Thank you very much for your detailed response!
