### ISSUE TITLE
BBT associate torrents despite being told not to

### ISSUE THREAD

**Issue by nokti** [BiglySoftware/BiglyBT#2192]
* Win 10 20H2 19042
* BiglyBT V2.8.0.0

I just did a clean reinstall of BBT and despite unchecking the torrent files association during setup, torrent files are now associated with BBT. This happened before whenever there was a new version of BBT. This is annoying because BBT is not my main client since it is not allowed on private trackers.

**Comment by parg** [comment]
Did you delete %APPDATA%\BiglyBT before installing? If your previous BiglyBT was set to automatically re-apply associations and you didn't remove the config data there then it would carry on as before.

**Comment by nokti** [comment]
When I uninstalled I also selected delete configuration. The file association was never selected anyway because BBT was never my main client (nothing to do with the client itself, I like it and it works really well on my system).
