### ISSUE TITLE
Torrent display name is now "Metadata download for magnet:...."

### ISSUE THREAD

**Issue by david-bakin** [BiglySoftware/BiglyBT#2194]
BiglyBT Beta 2.8.0.1_B09 (Windows 2016 Datacenter R2)

The new B09 is now naming torrents "Metadata download for magnet:...".  (Display name).

The torrents in question have all their files in a subdirectory.  They are actually downloaded to the proper subdirectory (even if you rename it via the "Subfolder" text box in the Open Torrent dialog).

This is new behavior with B09.  No settings changed since I upgraded from B08 - where it was working fine - to B09.

**Comment by parg** [comment]
Hmm, looks like a change I made to persist names changes to magnet downloads has unintended consequences! I shall investigate

**Comment by parg** [comment]
Hopefully fixed in B10!

**Comment by david-bakin** [comment]
Yes, seems to be fine now, thanks!

**Comment by david-bakin** [comment]
There's no "discussion board" for biglybt, is there?  So I'll add this as a comment here:

B10 happily _reverted_ a behavior which I didn't like - which was introduced, oh, maybe 2 months ago?  Maybe 1 month ago?

The behavior I didn't like was that when running with "Monitor Clipboard For Torrent Links" activated, whenever I went to a repository on GitHub I wanted to clone on my machine, and then clicked on the green "Code" button, and selected "https", and then hit the "copy to clipboard" icon - BiglyBT would think that was somehow a torrent link to download and it wouldn't ever time it out either!  It just persisted - I had to close them by hand.  The proper behavior now _restored_ by B10 is that it thinks about the link for a fraction of a second and then says "hey, this isn't a torrent link" and drops it.  Much better!  Don't know what it is about those github "copy" repository links - as far as I know they're simply a repository URL - e.g., `https://github.com/BiglySoftware/BiglyBT.git` - but for a month or so they were confusing BiglyBT in an annoying way.  Gone now!  Hope it stays that way!

**Comment by david-bakin** [comment]
Never mind.  It's back, in the same B10.  Must have been a transient where it worked right, maybe something GitHub did and then _they_ reverted.  Still I kind of wish it wouldn't do it for GitHub ...

**Comment by parg** [comment]
Something in the reply from github looks like a torrent hash which is why this happens. There is a chance I could add something for this specific case but then something else would no doubt pop up and do the same :(

**Comment by parg** [comment]
I'll try a fix in next beta!

**Comment by david-bakin** [comment]
Did you look into it?  I was thinking that the bare github repo url must redirect through something that looks like an infohash or something ... is that it?

**Comment by parg** [comment]
Just some code we have to parse webpages for magnet links - it was picking up a raw hash by "accident" so I removed that check as to be honest it is unlikely to ever produce anything worthwhile. Famous last words...
