### ISSUE TITLE
When saving a .torrent file from a magnet link, save the .torrent file immediately until the data fully comes in

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2198]
Windows 21H1 x64
BiglyBT 2.8.0.0

My request is that, when choosing to save the .torrent files, when downloading using a magnet link, save the .torrent file immediately at the requested location, with as much as information as you can, until you get the full torrent information.  For instance, perhaps you could at least save the info hash?  Sometimes I use live linux distributions, and so I may only have a limited time at a certain location, and if the magnet link hasn't sucked the torrent information yet, then bye bye torrent information when I shut down the computer.  At least if the infohash is saved, in a .torrent file at first, then perhaps the name changed, if possible, to the name of the torrent plus the infohash, then I don't have to go to a .txt file to save the magnet link information or the infohashes myself.

**Comment by parg** [comment]
The magnet download details are already stored in the 'tmp' folder in the BiglyBT config folder. Their name is

<torrent hash>_<random number>.metatorrent

**Comment by as-muncher** [comment]
I've also noticed that the magnet downloads are being saved as <infohash>.torrent.  I wanted to select all the .torrent files, then drag them into BiglyBT so that it could load them all at the same time, but biglybt says it doesn't appear to be a .torrent file.  Could you please fix this so that I can load up all my magnet links all at once?  Or infohashes?
