### ISSUE TITLE
Getting last few pieces of a torrent can be slow

### ISSUE THREAD

**Issue by david-bakin** [BiglySoftware/BiglyBT#220]
I just switched from uTorrent to BiglyBT and I find that some torrents with reasonable availability (>10) are really slow to complete - even after the bulk of the torrent has downloaded at speeds >10Mbps the last few pieces (<10) might take several minutes to ten minutes to complete.

This didn't happen with uTorrent and I think the reason might be that uTorrent has a facility where when the torrent is down to the last few pieces and those pieces are currently requested from a "slow" (or _very_ slow peer) uTorrent will request those same pieces from other peers that have them (without waiting for the slow peer to finish).  So I guess there are multiple requests for the same pieces outstanding and whichever comes in first wins.

Is that something BiglyBT can support?  Or maybe it already does support it and I don't know the option/configuration setting.

**Comment by parg** [comment]
BiglyBT already has an 'end game mode' to theoretically help with this issue and it works in the same way as uTorrent. Of course this can result in wasted bandwidth so BiglyBT has some limits to restrict this. EGM won't be entered until there is around 25MB remaining. It will also de-activate after around a minute.

**Comment by david-bakin** [comment]
I think maybe I noticed this most on torrents with 16Mb piece size (too large IMO not sure why people do that!).  Maybe the 25Mb could be adjusted based on piece size ...

**Comment by parg** [comment]
Well it isn't really piece size dependent as requests are always 16KB - if anything it is more likely to be availability based. That being said, for some reason the EGM enabling logic does use piece-size which isn't right, especially if you have a number of fairly complete large pieces. I'll rework this to be piece-size independent.

**Comment by parg** [comment]
Beta build B31 has the changes in - if you get a chance please test to see if that helps!

**Comment by david-bakin** [comment]
I will shortly - it's running now - but I have to find some 100% available
torrents with a 16Mb piece size..  Sorry I don't know the proper
terminology - I guess I do know that the minimum transfer size is 16kb
which I thought was called a "block" - I'm talking about the "Size" that's
listed on the "General" tab of a torrent under the # of pieces which I
thought was called a "piece" - these torrents have a 16Mb "Size".

(It seemed to me, from observation over time,  that the EGM in uTorrent was
supposed to alleviate the problem of uTorrent being "sticky" on a "piece"
to whatever peers kind of "belonged" to that piece (sometimes more than
one) - and so if you had a large piece (e.g., 4Mb or larger) and it was
talking to a slow peer and it was the last piece then it would plod along
forever with 16kb blocks trickling in slowly from the slow peer.  But
with EGM it would be able to jump to other, faster, peers just to get the
last two or three pieces in - and it switched to EGM when and only when all
blocks of all remaining pieces had been requested from their peers.)

(BTW, as a new BiglyBT user, thanks for the efforts!)

**Comment by david-bakin** [comment]
You know, I hate to bring this up ... but I think end game has been broken since this fix.  It actually works for the 16Mb case but in many other cases (e.g., 1Mb pieces) it rarely seems to kick in.  (Of course, it could be the peers.)

When I'm looking at the Pieces tab - is there a color to indicate that that piece is multiply-requested due to end game?

**Comment by parg** [comment]
I added some info to the pieces view - green blocks for end-game-mode requests with the request count shown - might need to make the column longer for big piece sizes...
Also the piece-map header area shows some egm info when active (time remaining, num blocks, whether abandoned)

**Comment by parg** [comment]
Actually the debug was borked, it'll be fixed in the next beta (B13 when built)

**Comment by TuxPaper** [comment]
Closing issue do to age and lack of update. If anyone still has this issue, please file a new one.  Thanks!
