### ISSUE TITLE
BiglyBT won't start: another process on socket 6880

### ISSUE THREAD

**Issue by namitgpta** [BiglySoftware/BiglyBT#2200]
* OS and version: Windows 11 Pro 21H2 22000.120
* BiglyBT Version Number: 2.8.0.0

![image](https://user-images.githubusercontent.com/60420298/129187299-6256fbb5-16fd-455c-bd40-27a74d74a1dc.png)
I have checked my ports with the help TCPview software and there is no process linked with port 6880.
Rebooting the PC solves the problem for some time only, the problem comes again after some time after rebooting. I have faced this error now for 5 times in the past 3-4 days.

I can still open BiglyBT on some different port by running this command in terminal:

Start-Process -FilePath javaw.exe -WorkingDirectory 'C:\Program Files\BiglyBT' -ArgumentList '-cp "BiglyBT.jar;commons-cli.jar;swt.jar" -Dazureus.instance.port=16889 com.biglybt.ui.Main'

But clicking on a torrent file or magnet links, simply doesn't work now because of this port error. Everytime I have to open it with help of cmd and then open that particular torrent file in it. It is a very cumbersome task.
I have never faced this problem before in my lifetime.
Please provide a permanent solution/fix to this problem.
Can we change its port/socket number from 6880 to something else, permanently by default??

**Comment by parg** [comment]
https://github.com/BiglySoftware/BiglyBT/wiki/Command-Line-Options#configuration-persistence ?

**Comment by namitgpta** [comment]
Thanks a lot for your help. I am closing this issue.
