### ISSUE TITLE
'Periodically Recheck Incomplete Pieces' doesn't seem to actually check the disk.

### ISSUE THREAD

**Issue by Jeff-182** [BiglySoftware/BiglyBT#2201]
Background: 
I use two VMs to download. Both are on the same host.
Each is connected to its own VPN and Bigly is mapped to the corresponding interface (TAP-V9) in 'Advanced Connection Settings'.
This breaks the ability to use the 'LAN Peer Finder' even though the VMs can send information between them.
Lan Peer Finder does work when the non-VPN Ethernet interface is specified but that defeats the purpose.

So, my idea was the following:
1 ) Disable 'Enforce exclusive write locking across torrents'.
2 ) On a shared location set both clients to work from the same files.
3 ) Use the 'Periodically Recheck Incomplete Pieces' option. This should (ostensibly) scan the disk for changes coming from each respective download and effectively merge them similar to "swarm merging" of two downloads on the same machine.

So as VM 1 downloaded the first 0-40% of the file and VM 2 downloaded the last 40% of the file both VM 1&2 would see an 80%-completed download (as an example, I know they'd often try to download the same content because they're not aware of each other.

The Issue is that this simply doesn't occur.
VM 1 will report that 60% total is downloaded. VM 2 will report that 30% is downloaded.
If you stop and run 'Force Recheck' they will then tell you that 73% total of the files on both machines have completed and the availability is then identical... until it instantly gets out of sync again.

To test this I had VM 1 throttled to 1kbps and VM 2 downloading at a still-slow but relatively way-faster speed.
I let it sit for two days and VM 1 hit 5% and VM 2 hit 85%.
Stop both, recheck both, each are now at 86.5%.

And yes, this option *is* checked for the download on *both* VMs.
So, it appears as though 'periodically re-check incomplete pieces' does not actually check the disk?

The documentation here: https://wiki.vuze.com/w/Multiple_torrents_accessing_shared_file(s)
Suggests that it was, at one point, limited to 250 KiB/s.
Perhaps there is a way to make that more aggressive? The files are too large so it will take... months to sync?

I'm fully-aware that this is probably (/is definitely) an extremely-niche use case but if it's simply checking too slowly this might be a very easy problem to solve.

Thanks in advance.

Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=200, dpi=96
Windows 10 v10.0, amd64 (64 bit)

B2.8.0.0/4 az3

**Comment by parg** [comment]
If you turn on logging you should see entries like

[12:03:46.532] {peer} Rescanning piece 1; 	| Torrent: 'LibreOffice_6.4.4_Win_x64.msi'
[12:03:49.639] {disk} Piece 1 failed hash check.; 	| TorrentDM: 'LibreOffice_6.4.4_Win_x64.msi'
[12:21:55.202] {peer} Rescanning piece 131; 	| Torrent: 'LibreOffice_6.4.4_Win_x64.msi'
[12:21:55.203] {disk} Piece 131 passed hash check.; 	| TorrentDM: 'LibreOffice_6.4.4_Win_x64.msi'

Also the 'Cache' tab in the Statistics view shows file reads at around 220kb/sec

For me it is working - I don't have two processes writing to the file, rather I manually replaced an incomplete file with a complete one, however I would have thought the result would be the same.
