### ISSUE TITLE
[Feature Enhancement Request] Tag Group List sorting order is unpredictable

### ISSUE THREAD

**Issue by rajibkhan** [BiglySoftware/BiglyBT#2203]
Hi Again,

Problem: When trying to assign a tag to a group, the right click popup brings the tag group list. But the order is unpredictable. 
It's difficult to figure out if there is any order at all, or is it based on chronologically based on group creation timestamp, but it's definitely not alphabetical. It's confusing to find a group. Same thing is also true for drop down group assignment menu when creating a tag. 

Suggestion: Alphabetical order would be great. Being able to manually (if use case requires) put a order metric (number) would be greater. 

Thx.

**Comment by TuxPaper** [comment]
Aha! It was a bug, and we definitely wanted it sorted alphabetically

Next beta snapshot should have this fixed.

Thanks for the report

**Comment by rajibkhan** [comment]
@TuxPaper : Thanks for the fix.
