### ISSUE TITLE
Help: Check for Updates not finding new Betas

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#2204]
![image](https://user-images.githubusercontent.com/37715552/129516658-8d308a08-3f50-475e-ba20-382a3e1d3452.png)

I manually started the download from the `Chat: Public - 'BiglyBT: Updates: Core[R]`. Then I started the Check for Updates. As you can see, the Check did not find the next Beta. This also happened between, B06 and B10.  I ended up skipping 7,8,9 because the check is not finding the updates. I have the following settings.  I will install B11, manually after this.

![image](https://user-images.githubusercontent.com/37715552/129517225-2c5f63c3-34d5-436d-91b0-1e006d2841ec.png)

Java 1.8.0_301 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_301

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.8.0.1_B10/4 az3

**Comment by parg** [comment]
If you manually download the update you have to manually install it - see https://github.com/BiglySoftware/BiglyBT/wiki/Updating-BiglyBT

**Comment by NaPurHab** [comment]
I already knew about `Help->Advanced->Install Update Manually` (See Below).  The problem is that `Help->Check for Updates` is acting up again. As the image shows, it was saying B10 was the latest. While I was manually downloading B11. I had even run `Check for Updates` before I went to the Chat to get the latest Beta.  Used to be BBT checked and notified me without me having to use the Beta Chat and `Help->Advanced->Install Update Manually`.

I got up to B06 with BBT automatically notifying me. Missed B07, B08, B09,  then manually downloaded and installed B10, B11. Don't know if it is BBT or the location it is looking for Updates.  Hmm, possible broken Link. Just wanted you to know about the issue.

Java 1.8.0_301 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_301

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.8.0.1_B11/4 az3

**Comment by parg** [comment]
"Check for updates" simply connects to "version.biglybt.com" or "version6.biglybt.com" and asks for the latest version. If the clear-net connection fails and you have the "Tor Helper" plugin installed then it will attempt to connect to the service over Tor via "7zq2rhfhvgcv7pkt.onion"
