### ISSUE TITLE
Weird error when adding 47 torrents all at once through WebGUI

### ISSUE THREAD

**Issue by DumbJoe** [BiglySoftware/BiglyBT#2205]
![error biglybt](https://user-images.githubusercontent.com/36319788/130037977-0b8bf417-7383-4c43-bed9-957a0cd565ee.PNG)

Not sure what this means, too many torrents at once? Or I've reached the limit of BiglyBT and it can't handle more than 99 torrents at once?

**Comment by parg** [comment]
You're adding a PNG file instead of a .torrent file?

BiglyBT can handle 1000s of torrents...

**Comment by DumbJoe** [comment]
> 
> 
> You're adding a PNG file instead of a .torrent file?
> 
> BiglyBT can handle 1000s of torrents...

They all have .torrent extensions, so unless some of them are fake .torrent files and are actually png files instead....how do I tell? edit file extension from .torrent to .png for all of them and see if any of them opens up in windows photo and fax viewer?
