### ISSUE TITLE
Make a torrent: piece count number being truncated

### ISSUE THREAD

**Issue by 11chubby11** [BiglySoftware/BiglyBT#2206]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.8.0.0/4 az3

UI bug when making torrents.  Torrents are still created correctly with the correct piece count.

When reducing the piece size, instead of the piece count increasing, sometimes it reduces in value (to 10% of what it should be).
It seems to not be allowing the length of the piece count number to increase from its default value.
E.g. If the default piece count is a 4 digit number, it will not display a 5 digit piece count number if the piece size is decreased. In this case it will only display the first 4 digits of the 5 (or 6) digit piece count number.
Tested with several files from 1 to 80 GB.
![image](https://user-images.githubusercontent.com/16216830/130198856-d43d7ab8-793d-460e-b6ba-9d08cd45d7a1.png)
![image](https://user-images.githubusercontent.com/16216830/130199029-6d3cd98d-8298-49cb-bb6f-4d6407a98e45.png)
Reducing the piece count from 2MB to 1MB should double the pieces from 9485 to 18970.  Instead 1897 is displayed.

**Comment by parg** [comment]
Thanks, fixed next beta
