### ISSUE TITLE
Feature Request - Save Path Column

### ISSUE THREAD

**Issue by cglmrfreeman** [BiglySoftware/BiglyBT#2207]
* OS and version: openSUSE Tumbleweed 20210820
* BiglyBT Version Number: 2.8.0.0
* For *nix: KDE 5.85.0 / Plasma 5.22.4

Greetings. I migrated from the older version of uTorrent when I switched to a Linux based OS. One of the nicest features I miss from uTorrent is being able to sort my torrents by what BiglyBT calls the "Save Path". A column with the save path I think would be very useful, so I could easily see which files have been saved in the same directory.

This is sort of indirectly a request because every time I add a magnet to BiglyBT from the browser and the magnet only contains 1 file, it auto-starts downloading the file into the last known save directory. I believe my subscriptions also do this. So I have probably half my library in arbitrary locations and find it difficult to navigate to every item and scroll down the info tab to see where it is saved. I would rather see if "Meeting John Doe S01E04" was in the "Karma Chameleon Hour" directory at just a glance, I could relocate the files via BIglyBT's interface.

Thank you for your time.

**Comment by parg** [comment]
You can add a column to show Save Path (and then sort by it) - right-click on one of the existing column headers and select 'Column Setup' from the menu. This opens a dialog with available columns - filter by "save" if you want to find it quickly. You can set its position (and alignment and colour) there too, or drag+drop headers around in the Library view later.

You can make BiglyBT always prompt for a save path via Options->Files: When opening a torrent, show options dialog: "every time"

**Comment by cglmrfreeman** [comment]
Absolutely perfect! I have no idea why that was so hidden to me! You are a lifesaver! Thank you so much! Case closed!
