### ISSUE TITLE
Manually-assigned tag but with a constraint (!isCompleted()) - possible?

### ISSUE THREAD

**Issue by david-bakin** [BiglySoftware/BiglyBT#2208]
[BiglyBT Beta (2.8.0.1_B12)

Is it possible to assign a tag manually but have a constraint (or something) that it only shows up in the tag's tab/pane if it is not completed?

(When you set a constraint you get a popup saying something like it'll remove tags from manually-tagged torrents.)

**Comment by parg** [comment]
You can create a separate Tag to do this. Call the manually assigned one "A". Create a second Tag and set its constraint to

`hasTag("A") && !isComplete()`

**Comment by rajibkhan** [comment]
@david-bakin I think, you can use the tag constraint: isComplete() and set policy to 'remove only'
That way when the torrent is complete, the constraint will be fulfilled and the tag will be removed from the torrent. Then it will not be visible in the tag tab anymore. You can manually assign tags once the policy is 'New Download' and 'Remove Only'.

Well, unless you still expect to have the primary tag still be assigned to your download even after completion.
In that case, you'll have to use a secondary tag to do the trick, as parg suggested.

Hope it helps.
