### ISSUE TITLE
Seeding window doesn't update checking percentage

### ISSUE THREAD

**Issue by david-bakin** [BiglySoftware/BiglyBT#221]
Sometimes (maybe all the time?) the Seeding window doesn't update the %checked value for torrents that have just completed and are in the "Seeding + Checking: nn.n%" state.  You've got to switch to another window and then back to get the correct (current) values.  (This works fine in the Active window: the %checked value continually updates.)

> [Java 1.8.0_152 (64 bit)  Oracle Corporation c:\program files\biglybt\jre
> SWT v4757, win32
> Windows Server 2016 v10.0, amd64 (64 bit)
> B1.2.0.1_B30/4 az3]

**Comment by dbareis** [comment]
Yep, I get this too even on the latest beta:

Java 1.8.0_151 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_151

SWT v4757, win32
Windows 10 v10.0, amd64 (64 bit)
B1.2.0.1_B30/4 az2

**Comment by parg** [comment]
Fixed in next beta, thanks!

**Comment by parg** [comment]
B31 is out, please test

**Comment by dbareis** [comment]
Seems to be fixed here

**Comment by parg** [comment]
great!

**Comment by david-bakin** [comment]
yeah working for me
