### ISSUE TITLE
DorkBox System tray update will not install - Linux Mint 20.1

### ISSUE THREAD

**Issue by pnewbery** [BiglySoftware/BiglyBT#2216]
![image](https://user-images.githubusercontent.com/15089304/131339383-2f459aea-2fd1-41fb-b3ab-c03a89a04cf1.png)

Java 11.0.11 (64 bit)
  Ubuntu
/usr/lib/jvm/java-11-openjdk-amd64

SWT v4942r22, gtk/3.24.20, zoom=100, dpi=96
Linux v5.10.0-1044-oem, amd64 (64 bit)
B2.8.0.0/4 az3

Clicking restart goes through all the expected processes, requesting admin authority etc. but simple comes back with the same update available window.

**Comment by pnewbery** [comment]
Can anyone help please?

**Comment by pnewbery** [comment]
OK, so this started as the Dork box thingy not updating, which it still won't, but now, neither will core update 2.9.0.0. BigblyBT simply restarts and re-presents the update for installation.
Can anyone suggest a way forward in diagnosing this issue please?

**Comment by parg** [comment]
A work-around is to download the main update file

https://github.com/BiglySoftware/BiglyBT/releases/download/v2.9.0.0/GitHub_BiglyBT.jar

and rename this to "BiglyBT.jar". Then replace the file in the install directory with this.

**Comment by pnewbery** [comment]
Thanks for your reply Parg. I did as you suggested and sure enough, things have changed. I now get a message "A new BiglyBT Startup Script is available. It is recommended that you re-start BiglyBT now", which appears after every restart. 
So progress... of a sort.

**Comment by parg** [comment]
https://github.com/BiglySoftware/BiglyBT/blob/master/core/src/com/biglybt/platform/unix/startupScript

was modified to solve a few issues, the SCRIPT_VERSION has been updated from 9 to 10

**Comment by pnewbery** [comment]
OK, the new startup script works fine and thanks for that, but I am still left with the original DorkBox update situation. Are you able to throw any light on that?

**Comment by parg** [comment]
The 'dorkboxupater' plugin is supposed to copy the file ~/.biglybt/plugins/dorkboxupdater/dorkbox-systemtray.jar into the install directory (same place the BiglyBT.jar is). Perhaps you can manually do that.

**Comment by pnewbery** [comment]
Hi there, the dorkbox-systemtray.jar (dated 21/01/2019) is already in the install directory. I'm not sure where I should be looking to find any later version.

**Comment by parg** [comment]
Hmm, no idea then - I have exactly the same file on my kubuntu and everything works fine :(
