### ISSUE TITLE
Active Torrents are not moving /sorting themselves on page

### ISSUE THREAD

**Issue by Swampgirl** [BiglySoftware/BiglyBT#2219]
OS Sierra 10.12.6
BiglyBT Version  2.8.0.0

I'm not sure how to inquire about this once given feature. When torrents were downloading, they would move themselves to the start or bottom of my download page.  I vaguely remember being able to choose this. Now the downloading torrents stay in one place and do not move. So, instead of my downloading torrents all grouping together at the bottom of the downloading page, they stay where  they land, so I may have torrent downloads at the bottom of the downloading page, and have to scroll up to see other downloading torrents.  How do I get torrent downloads to sort themselves together into a group on the page again?

Please forgive my clunkiness regarding my description and question. My use of the software, despite doing so for nearly 20 years, is largely based on intuition.

Best Regards,
Swampgirl

* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment

**Comment by parg** [comment]
Hmm, perhaps you need to sort your downloads via the 'order' column? In the screenshot below you can see the order column towards the left and clicking on the column header selects the sort (clicking again will select 'reverse sort'). If you can't see the order column then right-click on some other header in the table and select 'column setup' to show the column chooser.

![image](https://user-images.githubusercontent.com/395293/131578998-f2c5c0ce-e549-4cf5-b988-8f778536ab16.png)

**Comment by Swampgirl** [comment]
Hi Parg,
Thank you for your response - I appreciate you taking the time.

I did sort the column, and I even repositioned a few titles by changing their position numbers. 

Was there ever a time downloads positioned themselves, so the titles actively downloading would move themselves to either the top or bottom of the "Downloads" page depending on whether the list is in ascending or descending order? Is there a setting that helps them do this?

I seem to remember this happening.... 

Best Regards,
Swampgirl

**Comment by parg** [comment]
If you sort by 'status' then that will put those labelled as "Downloading" together.

If you're using the "advanced list" view in the Library (see the toolbar icons at the top to switch between "simple" and "advanced" views) then the incomplete downloads will be in the upper area and the complete ones in the bottom area. This makes it clear which downloads are incomplete regardless of how you then sort them.
