### ISSUE TITLE
Run command plugin on torrent state = stopped

### ISSUE THREAD

**Issue by abegreen** [BiglySoftware/BiglyBT#2220]
I'm always happy when I discover a new torrent client in hope to finally get rid of utorrent 2.2.1.

First thing I look for is if it can run command on certain torrent state.

...and it can't...

External script can't manipulate files when torrent download finishes, because it's still seeding for certain time depending on settings. Only after, when torrent state = stopped.

In case of utorrent 2.2.1 torrent state stopped = 11 as shown below:

<a href="https://picstate.com/view/full/14142074_jsz01" target="_blank"><img src="https://picstate.com/files/14142074_jsz01/ScreenShot_20210901151057.png" alt="ScreenShot_20210901151057.png" border="0" /></a>

So script runs on every torrent state but the first lines of the script look something like:

if %S=11 do:
delete this
rename that
copy this
move that

**Comment by parg** [comment]
Tags support a "constraint expression" and "execute on assign"

So you can create a Tag that downloads get assigned to when, for example, they are "complete" and "stopped"

"execute on assign" currently supports a script value. At the moment that script has to be Java Script which, while it works if you know what you're doing, isn't very friendly and Java has removed built in support in recent versions which mean, meh.

There is a "command runner" plugin that at the moment does something similar to uTorrent except it only triggers when the download completes, not when it subsequently stops.

I suppose I could enhance the "script" option of the Tags to also support invocation of the command runner script.

**Comment by abegreen** [comment]
Yaaaah! That's hot :)))

Yes, I'm talking about "command runner" plugin in combination with python script.

If this gets solved I will finally get rid of 20 years old client, da hell, I'll even donate and get married to celebrate.

My script has 4000 lines of code. Useless on every client except the prehistoric one which has a tone of problems like speeds are 100kbps on a gigabit dedicated server...

I prey to God to find a better, newer client.

**Comment by parg** [comment]
If you join the beta program (see the Help menu to do so) then you should update to version 2801_B16. Once this is done you should then find the "Command Runner" plugin updates to version 1.4.8

This combination of updates supports a script type of "plugin" that allows you to pass the command to execute to the command runner plugin. The "plugin ID" of this plugin is "azexec" and as such the Tag 'Execute on assign' script syntax becomes

plugin( azexec, "command to be run by the plugin" )

The command follows the same expansion syntax. For example, to open a torrent download location in notepad (obviously stupid) you would use

plugin( azexec, notepad.exe %D )

Tell me how that works for you.

**Comment by abegreen** [comment]
I'm speechless...

I'll be playing with it tomorrow. Never seen a torrent client with so much options...

I can't believe you did it already. I've been requesting this from Qbit developers for a year.

Wonderful news my friend.

**Comment by parg** [comment]
You're welcome - I'm sure it'll need some more work :)
