### ISSUE TITLE
show/hide time 

### ISSUE THREAD

**Issue by hglecke** [BiglySoftware/BiglyBT#2221]
In My Torrents - New - Column "completed on" - right click heading - show/hide time - does not alter the display in that column.

* OS and version Win 10
* BiglyBT Version Number 2.8.0.1_B15

**Comment by parg** [comment]
Does for me - have you set a custom date format?

**Comment by hglecke** [comment]
You are right, once again!
Somehow, sometime a custom time format was set. Once removed all is well.

Thank you
