### ISSUE TITLE
add option to add torrent to watch window when deleting the torrent

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2222]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B2.8.0.0/4 az3

When I choose to delete a torrent, BiglyBT asks me if I want to delete the .torrent file as well.  What about adding a checkbox to add the torrent to a watch list.  I think that would be good for those people who would like to seed torrents, but can't have all the torrents on their hard drive at the same time, but maybe will seed it when there are a certain number of peers or it hasn't been seeded in a long time.  I'm not completely sure if BiglyBT has watch windows like this to cater more to seeders instead of leechers, but I thought I'd suggest it.  That way, BiglyBT is not going to try to download the torrent, just to see who needs it.  But is this a bad suggestion?  I'm sure there are torrents out there that maybe are being watched because they have accusable content.  It's just a thought, anyways.  Maybe it hasn't been implemented for very good reasons.

**Comment by parg** [comment]
Just leave the download in your Library in a stopped state, manually delete the data (that I assume you have archived somewhere else) and let the existing "scrape stopped torrents" periodically check for peers. Assign these downloads to a Tag if you want to identify them somehow.

BiglyBT does have the 'archive' feature but that no longer scrapes the downloads.

**Comment by as-muncher** [comment]
ok, thanks.
