### ISSUE TITLE
Incorrect torrent seeds

### ISSUE THREAD

**Issue by sandoe41** [BiglySoftware/BiglyBT#2223]
[debug.zip](https://github.com/BiglySoftware/BiglyBT/files/7095936/debug.zip
The number of my torrent seeds is not being shown correctly. * OS and version Windows 10
* BiglyBT Version Number 2.8.0.0
* For *nix: Desktop Environment

**Comment by parg** [comment]
The number of seeds is reported by the tracker. The tracker is only periodically asked for the information (and if your torrent is in a stopped state this is much less frequent).

Look at the "Sources" sub-tab for a torrent - this shows when the tracker will next be asked for the information.

**Comment by as-muncher** [comment]
I have one seed like that, and in the sources tab, I see that DHT is disabled.  When I choose "Mainline DHT -> Announce", it still is an option available to me, not greyed out, so how would I enable DHT?  For two of the trackers, I see "Error: Offline (Network not enabled for url 'udp://tracker....')"  and then I saw that one of the trackers went online.

**Comment by parg** [comment]
DHT disabled -> probably a private torrent

Network not enabled -> network not enabled (Public net disabled for a public tracker for example)
