### ISSUE TITLE
Where is my lost torrent?

### ISSUE THREAD

**Issue by david-bakin** [BiglySoftware/BiglyBT#2224]
[BiglyBT Beta (2.8.0.1_B16)]

Occasionally the sidebar torrent#s in each category don't add up.  This has been going on quite awhile, but I finally decided to ask about it.

Right now, my sidebar is showing under "My Torrents":

|Category|#|
|:--:|:--|
|**Library**|**2252\|2256**|
|**Downloading**|**3**|
|**Stopped**|**2253**|
|New|2248|
|Error|0|
|Incomplete|3|
|Initializing|0|
|Paused|0|
|Seeding|0|

So 3 are "incomplete" and "downloading". "library" thinks it has 2256, which is "stopped"+"downloading".  OK.  But then what is the 2252 which is 4 off from 2256, not 3. It seems I'm missing one which is _not_ downloading (or incomplete), nor initializing, paused, seeding, or error.  Where is it?

(And I also don't understand "new" at 2248.)

(Frequently the unaccounted for delta is >1, always <10.)

**Comment by parg** [comment]
For the Library counts of "X|Y" - X = total items in the "simple list" view, Y = total items in the "advanced list" view (see toolbar items to switch between these)

The difference between these two views is that the "advanced" one includes BiglyBT update torrents, the "simple" one doesn't. Obviously the "advanced" one is split between incomplete and complete as well.

So you have 4 update torrents (e.g. "azlocprov_0.5.4.zip")

**Comment by david-bakin** [comment]
Good to know!  (Not obvious!)
