### ISSUE TITLE
stop a torrent after seeding/downloading completes "help wanted"

### ISSUE THREAD

**Issue by MrDarius125** [BiglySoftware/BiglyBT#2225]
is there any way to set a single torrrent to stop or pause after a seeding target is reached or is downloaded without it effecting any other torrents downloading/seeding?

i can't seem to find this option anywhere except for shutting down the entire client.

* Windows 10
* BiglyBT  2.8.0.0

**Comment by parg** [comment]
Right-click the download, select "show details" and go to the Options tab - there is a target share ratio there.

Or enable the 'share ratio' column (if not already visible) and right-click on the download in that column, go the the 'Other' tab and select 'set share ratio'

**Comment by MrDarius125** [comment]
![12](https://user-images.githubusercontent.com/20372449/132712256-9e217421-179e-42b2-965b-146287102e3e.jpg)

**Comment by MrDarius125** [comment]
is there a way to stop torrents have have reached a target seed ratio 1.00 individually. without shutting down the whole client after all of the torrents have reached a seed ratio of 1.00

**Comment by parg** [comment]
Did you read my comment?

**Comment by parg** [comment]
![image](https://user-images.githubusercontent.com/395293/132729546-b77768b7-661f-4da7-a79e-3fc18b8a5987.png)

**Comment by parg** [comment]
![image](https://user-images.githubusercontent.com/395293/132729898-1fd760ed-b5e3-4f0f-bbd4-271454fa57ed.png)

**Comment by parg** [comment]
Torrents should enter a "Queued" state when the ratio is met.

If you want to stop/pause them then you can arrange for this to happen via Tags

**Comment by MrDarius125** [comment]
checked the settings and i found that by setting "Minimum seeding time in seconds" to 1 from 120 made the torrent enter "Queued". I guess i was just seeding too fast so this option prevented the torrent from stopping :p

thanks anyway.
