### ISSUE TITLE
Remembering last window position interacts poorly with cascaded windows from adding multiple torrents

### ISSUE THREAD

**Issue by david-bakin** [BiglySoftware/BiglyBT#2226]
[BiglyBT Beta 2.8.0.1_B16]

(This issue is the lowest-priority of all low-priority issues, IMO.)

I _like_ that BiglyBT always remembers the last location of a window of each "type" of window, and next time you see a window of that type it puts in that place. (Let's me arrange the different windows nicely.)

I also _like_ that BiglyBT lets you drag a bunch of torrents over it and adds them all - and if you're in the mode "show open torrent dialog for each added torrent" then it pops up a nice set of windows so you can select files or change download location or whatever and then click "OK" on them one at a time.

But those two features interact poorly with each other, IMO.  BiglyBT should remember the location of the _first_ open torrent dialog so that _next_ time you open a torrent the window will pop up where you put it last.  But in fact BiglyBT remembers the location of the _last_ of the opened cascaded windows.  So the next time you open a bunch of them via drag/drop they continuing marching across the screen where they left off (and if you open just one, e.g., via copy a magnet link or torrent hash, it also opens in some location which is _not_ where you put it).

Sad.

**Comment by david-bakin** [comment]
Fixed in B17, right?  Thanks!

**Comment by parg** [comment]
maybe!

**Comment by david-bakin** [comment]
Yes, fixed!
