### ISSUE TITLE
Unable to install on ubuntu 21.04

### ISSUE THREAD

**Issue by alculete** [BiglySoftware/BiglyBT#2227]
I'm unable to install  with the error bellow
`./BiglyBT_Installer.sh `
`don't need JNA`
`not wayland`
`No suitable Java Virtual Machine could be found on your system.`
`The version of the JVM must be 1.8.`
`Please define INSTALL4J_JAVA_HOME to point to a suitable JVM.`

* OS: Ubuntu 21.04 x86_64 
* Shell: bash 5.1.4 
* DE: GNOME 3.38.4 
* BiglyBT Version Number v2.8.0.0

**Comment by realseb1g** [comment]
You don't have a OpenJDK installed
try "sudo apt install openjdk-8-jre"

**Comment by alculete** [comment]
I have version 11
```
java --version
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2, mixed mode, sharing)
```
