### ISSUE TITLE
Package as snap  [Feature request-Linux] 

### ISSUE THREAD

**Issue by alculete** [BiglySoftware/BiglyBT#2228]
Having this software package as snap (or maybe flatpack) would make installation easier without java version issue
More information on this [link](https://snapcraft.io/about)

**Comment by o0nd7ots** [comment]
BiglyBT is avalible as a [flatpak](https://flathub.org/apps/com.biglybt.BiglyBT). As far as I know it is not packaged officially.
@TuxPaper is it?
