### ISSUE TITLE
Unreadable texts on Fedora 34 

### ISSUE THREAD

**Issue by realseb1g** [BiglySoftware/BiglyBT#2231]
* OS and version: Fedora 34
* BiglyBT Version Number: 2.8.0.0
* Desktop Environment: GNOME 40
* GTK Theme: Adwaita-dark

So, I switched from Windows to Fedora and have noticed there are unreadable texts all over the place on the BiglyBT user interface
![unknown](https://user-images.githubusercontent.com/86971938/132867091-d591ac41-cac6-43d5-9f4c-db5431e08f24.png)
![Kuvakaappaus 2021-09-10 17-12-44](https://user-images.githubusercontent.com/86971938/132867233-1ee3fb9a-feed-48b7-b22d-90242dbcf235.png)

I wonder what is wrong with this

**Comment by parg** [comment]
yup, dark theme fail - use another theme or such it up (or feel free to fix the source, it is open...)

**Comment by parg** [comment]
You might be able to force just BiglyBT to use a non-dark theme by adding something like the following to biglybt.sh

    export XDG_CURRENT_DESKTOP=GNOME
    export QT_QPA_PLATFORMTHEME=lxqt
    export GTK_THEME=Default
