### ISSUE TITLE
choosing networks when downloading through magnet links

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2232]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B2.8.0.0/4 az3

Could I have the option to choose the networks I use, in order to download a .torrent file using magnet links?

**Comment by parg** [comment]
Options->Plugins->Magnet URI Handler?

If the magnet URI has clearnet resources in it (e.g. &tr=http://example.com/) then that might cause the clearnet to be enable though, can't remember.

You can always add &net=I2P to the magnet

**Comment by as-muncher** [comment]
@parg thanks for your response.  What about downloading magnet links - I see seeds and peers and wish that they would send me the .torrent file, but then I see that I require encryption, RC4 or higher, but it looks like that also applies to magnet links.  Maybe it's for a good reason that BiglyBT is coded this way?  I'm not sure.  I just want to get those .torrent files so I can start downloading.  I'm not sure why people choose "No encryption" - maybe encryption is banned in their countries.
