### ISSUE TITLE
B19 Torrents search box text far too small

### ISSUE THREAD

**Issue by coyote3** [BiglySoftware/BiglyBT#2234]
On B19 the text in the My Torrents search box is unreadably small.
![BiglyBT-SearchTextTiny](https://user-images.githubusercontent.com/30500973/133296299-16c8d4b3-d61c-4c1c-ba3b-359abf839c82.jpg)
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.8.0.1_B19/4 az2

**Comment by parg** [comment]
meh, stupid dark theme and SWT on Windows

**Comment by coyote3** [comment]
You're right, I think I am using Dark Theme!
