### ISSUE TITLE
2.8.0.1_B19 > Interface Messed Up.

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#2235]
I just installed B19 and all text in the sidebar is gone, and the Transfer Bar is black, with no visable text,  Was all fine in B18.

![image](https://user-images.githubusercontent.com/37715552/133309973-94deef2e-381e-46b0-ad44-b1136a4cd7a9.png)

Java 1.8.0_301 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_301

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.8.0.1_B19/4 az3

**Comment by parg** [comment]
yup, fixed next beta

**Comment by NaPurHab** [comment]
Thanks, I reinstalled B18, and it cleared. Was definitely B19 that changed something. Will watch the `Chat: Public - BiglyBT: UPdates: Core [R]` for next beta.   Interestingly, even though B19 installed, it is not in the Chat.  Here is an image of the chat at this time.

![image](https://user-images.githubusercontent.com/37715552/133314328-617b267a-dc01-44c8-9444-e9eef7d144a4.png)

I know I can right-click and add the Jar for download. But would be nice if it was possible to Add for Download and then Install. Currently I would have to then use Manual install and then hunt down the JAR with the Open Dialog. 

The other option would be that after Right-Click, and Add. That Bigly can SEE the Jar just downloaded as an Update, and take action as if through the normal update method.

**Comment by NaPurHab** [comment]
B20 fixed it. Thanks.
