### ISSUE TITLE
ISSUE: Ctrl+C copies wrong text when copying in selected text in Filter Edit Control.

### ISSUE THREAD

**Issue by rajibkhan** [BiglySoftware/BiglyBT#2237]
Hi,
Using Ctrl+C after Selecting text in library view filter edit control does not copy selected text. Instead, it copies fields of the torrent (selected/first in list) or column headers in case where the filtered list is empty. Using copy via right click control menu copies the selected text properly, but that's not always convenient.

PS. it is same for any filter edit. Tag view/file view/library view.

* OS Windows 10
* BiglyBT 2.8.0.1_B20 (This has been a persistent issue not a B20 specific issue)

**Comment by parg** [comment]
fixed next beta

**Comment by rajibkhan** [comment]
@parg thanks.

**Comment by rajibkhan** [comment]
@parg the issue isn't fixed yet as of Beta 21 although it's stated fixed in release note.

OS: win10

**Comment by parg** [comment]
Ah, I fixed it in the Library filter box but I see it wasn't a good fix as other things are still affected - I'll rework it

**Comment by rajibkhan** [comment]
Fixed. Thx.
