### ISSUE TITLE
ISSUE: Left sidebar tag group collapse button behave erratically and often unintentionally select the tag group.

### ISSUE THREAD

**Issue by rajibkhan** [BiglySoftware/BiglyBT#2238]
Trying to collapse/uncollapse TagGroups (with grouped tree view) in left SideBar by clicking on the triangle icon, very often causes to select the tag group unintentionally, and it causes the list view to change. Often, it's not expected or intended behavior. It often more often while collapsing. 

While collapse/uncollapsing number of groups in sequence it takes rendering time. With heavy workload it also slows down performance, even freezes momentarily. Expected behaviour should be: only clicking on *group name* or elsewhere along the row (except 'arrow' on the left and 'cross' button on right) changes the view to the selected group.

In addition, a number of tags in a group is 'visible', it takes all the individual tags to be closed separately until the group is hidden. I think adding a close button for the entire group can be helpful in certain organizational task-oriented scenario, to hide all the tags together. 

* OS Win 10
* BiglyBT B2.8.0.1_B20 [It's not this particular beta specific issue.]

**Comment by parg** [comment]
Hmm, does this happen when the sidebar selection is on an item inside the group you are collapsing? The sidebar has to have selection somewhere (that's how it is designed) so in this case selection should be placed on the previously selected item... When selection isn't inside the collapsed group I can't reproduce it.

**Comment by rajibkhan** [comment]
@parg, I understand the contextual fallback situation you mentioned. But no. It's not necessarily so. It happens even when i'm in a completely different tag/library view in a different group.
