### ISSUE TITLE
[Feature Request] Copy manually applied tags from one torrent and paste/apply to others.

### ISSUE THREAD

**Issue by rajibkhan** [BiglySoftware/BiglyBT#2239]
In certain cases, it will be helpful to be able to copy manually applied tags to one torrent and paste and apply to other single/multiple selected torrents.

**Comment by parg** [comment]
Next beta has buttons to copy/paste/clear and invert manual tag selection in the Tags sub-tab

**Comment by rajibkhan** [comment]
Appreciated!
