### ISSUE TITLE
ISSUE: in Options>Files>Torrents, no way to remove extra/empty "Import Directory>Assign to Tags" slots.

### ISSUE THREAD

**Issue by rajibkhan** [BiglySoftware/BiglyBT#2241]
Once new slots are added, there is no way to remove empty slots if there is no longer need for them. Leaving them empty doesn't remove them automatically either.

**Comment by parg** [comment]
I'll fix it so that any empty entries at the end of the list are removed when the view is rebuilt (switched away then back for example)

**Comment by rajibkhan** [comment]
Thx. The 'switch away...' should do it. 
The same issue also remains with true for Options>Interface>Tags (Files, Extensions) section. Maybe apply the same trick there as well why you're working on it.

**Comment by NaPurHab** [comment]
I have brought this up in the past.  Could we get something as simple as the image.  Just a delete option in the empty space on the left.  I have about 20 entries, and if I wanted to remove one in the middle, then the idea to only remove blank entries at the end would not work.  I would have to manually move entries up into the empty space. Better to have a X on the left and just kill the line/entry.

![image](https://user-images.githubusercontent.com/37715552/134572528-fd25b5ed-ce7e-4813-b635-ac03952b301f.png)

**Comment by parg** [comment]
sure, it'd be better, but I'm not about to work on it
