### ISSUE TITLE
[Feature Request] View tags of only one particular TagGroup in tags overview

### ISSUE THREAD

**Issue by rajibkhan** [BiglySoftware/BiglyBT#2243]
Sometimes, while reconfiguring tags, it is helpful to be see the list of tags of one particular tag group only.
Since, filter now works with tag constraint, I thought of trying to use **hasTagGroup("group1")** function in the filter, but it doesn't work.

**Comment by parg** [comment]
Only the Library view filters work with Tag Constraints unfortunately :( 

You can enable the 'Group' column in Tags Overview and then sort by that to group them together.

I could include tag group name in the filter logic which would work unless of course tag name and tag group name overlap.

I could do the same thing as we have in the Library view by using a prefix to specify filter context. So "g:<groupname>" would filter against group name only (for example)

Perhaps sorting by the Group column is sufficient? :)

**Comment by rajibkhan** [comment]
The g: prefix would be great. 

As to what you suggested otherwise, yes, that's how I've been doing things.
But sometimes with lots of tags in a group, organizing (regrouping/reconfiguring/decluttering) requires sorting tags by other criteria (# items, save path, etc.) for decision making. Doing so, changes the whole list view. Yes, then I can resort by group again and the previous sorting order remains within the new sort, but sometimes, that that unpredictably changes scroll location. Plus, it requires multiple extra sort-resort drills. 

My philosophy is, "I love patterns and repetition, cause they create scope for automation. But, I hate doing repetitive tasks repetitively, cause computer can do I faster than me once programmed." 
{ expecting a retaliation 🙄, fingers crossed 😂. I know the universe doesn't revolve around me. }

**Comment by rajibkhan** [comment]
BTW, Now that you mention the prefix, I think using t: prefix for tag-based filtering in library could be more efficient addition beside tag-constraint filtering. That way incomplete/wrong syntax issue could be evaded.

**Comment by rajibkhan** [comment]
Thx
