### ISSUE TITLE
Row Elements in TagsOverview>Settings subtab is unnecessarily too wide and fixed in width, and not responsive to resizing.

### ISSUE THREAD

**Issue by rajibkhan** [BiglySoftware/BiglyBT#2244]
I prefer to have tags overview as panel in my left SideBar for quick tag related operations. 
However, most frequently used row items in the Settings sub tab items have fixed width (e.g. tag name control, file settings event based action slots, tag constraint edit control, etc.) 
As such, when the side bar panel is narrow, most right side elements (tag color/icon button, or clear button for file settings, etc) are out of view and horizontal scrolling back and forth becomes inevitable for bulk operations. 
Their width could be reduced and flexible/responsive based on whole panel width ratio to bring the out-of-view elements in view and make them eazily accessible. 

In addition, the tag constraint text edit control can only accommodate two lines. there is not way to increase it's height by dragging any control handle, neither does it change size automatically based on length/lines of typed text. Composing multiline javascript constraint becomes difficult, with only two lines visible. Scrolling up and down while composing code is distracting for coding.

**Comment by parg** [comment]
How about you add Tags Overview to 'quick links' - then you can double-click the quick-link icon to quickly open a separate Tags Overview window to do your dirty work?

**Comment by rajibkhan** [comment]
Just tried it. Not sure how that address 'out of view' the challenge. 🤔 
The issues remain same even when not seeing in sidebar but in full window tag overview view, if the window isn't big enough.

The tag name edit has a certain lowest width limit of around 100 chars. It increases to fill empty space when upscaling the window, but doesn't decrease enough when making window smaller. 
Same goes for Save location path slots. which pushes right side buttons out of view.

Tag names shouldn't even take 100 character (but could be just me, I guess.) Yet, I think that lowest width limit can be lowered. 
Save paths might tough. But if full path cannot be seen when in resized (if implemented) then a tooltip to show the full path can be handy since that slot isn't interactive anyway other than viewing the path as fixed text.
