### ISSUE TITLE
Existing File Search suggestion: Everything <https://www.voidtools.com>

### ISSUE THREAD

**Issue by rajibkhan** [BiglySoftware/BiglyBT#2245]
It's just a thought. 
This *Everything* tools has an SDK and CLI released in it's download section. 
It's very fast in searching existing files throughout the system (of course with few caveats, pre-indexing and all that)
But once indexed (which doesn't take too long either) it can find out any file very very fast. 
Can this somehow be integrated into BiglyBT to assist or improve existing but manually/externally relocated files?
Doing so could improve automatically relocating moved files/folders.
Once matched by size using this, then checksum operation can be performed to accurately locate specific file, and update their path in biglybt.

**Comment by acrinym** [comment]
This would be wonderful! I use Everything and Listary.
