### ISSUE TITLE
[Feature Request] Tags: Change color of multiple tags at once, and duplicating existing tags.

### ISSUE THREAD

**Issue by rajibkhan** [BiglySoftware/BiglyBT#2246]
1. Being able to select multiple tags at once, and change their color to a specific color in on single operation would be great.

2. Duplicating an existing can also be very helpful. The new tag can have a number automatically added at the end just. It is often helpful for tags which has constraints and other settings configured. Duplicating them and modifying only some of the settings or partially modifying the constraints can make some automation tasks faster.

3. Being able to set a default color for a tag group can helpful in addition. New tags of that group will inherit that color by default.

**Comment by parg** [comment]
1. multi-select them in Tags Overview and set their colour in the Settings sub-tab

2. Sounds possible

3. Sounds possible

**Comment by parg** [comment]
Done in B21

**Comment by rajibkhan** [comment]
@parg 
1. Sorry I actually couldn't explain the context properly. I know the solution you mentioned and In fact, I've been doing it that way.  My bad. What I actually wanted to say is changing color selected tabs via right click menu command, 'change tag(s) color'.

**Comment by parg** [comment]
There was a menu command to do that before but it was moved into the TagSettings way of doing things. Having a million menu items to do configuration setting isn't a great way of doing things really but as you can tell, there's still a chunky menu left...

**Comment by rajibkhan** [comment]
> There was a menu command to do that before but it was moved into the TagSettings way of doing things. Having a million menu items to do configuration setting isn't a great way of doing things really but as you can tell, there's still a chunky menu left...

__SUGGESION__:      // TL;DR version
  You can: 
      A) put it inside *Properties* submenu.
      B) or you can put it in the color change button tag rename dialog, since F2 calls the tag rename dialog
      C) all of the above.


__EXPLANATION__: 
I understand your point of view, and you're right. Too much item in a serial menu causes clutter. 
But that's one particular UI issue with feature filled apps. It's very difficult to determine which user needs what on regular basis, and in what context/sequence they're going to need it. That's why such apps give users certain level of UI customization controls to choose the placement of their preferred tools in user-friendly way. Same does BiglyBT for so many operations, except this action and a few other. There are many item in the menu actually, that I never use, but I feel the need of this one. I'm sure other users feel the need of those commands more. So, my preference alone cannot be a defining factor for an default application wide decision. 
  
However, In a particular context when I'm needing to operation (change tag color) repetitively, but not exclusively, and not solely serially but based on other factors, the sequence goes like this: 
  
DO { 
        1. go to tags overview (page/view transitions), 
        2. searching/typing the tag (additional actions ++ ), 
        3. select the tag
        4. focus in to setting tab, and additional scroll right maybe often needed since the button goes out of view due to window size, 
    5. changing the color (**actual intended operation**), 
        6. come back again were before
      
  } WHILE { you feel the need for same operation for another torrent based on certain condition }
  
  I'm sure that explains the number of pre-requisite action as entry barriers before I can perform the actual intended operation.  

Structure is important, but from UX perspective, , but also removing entry barriers to perform an intended action is more often of higher importance. especially, if it requires page/view transitions, where as the action operation is very simple, the entry barriers takes more user and processor time, and puts a higher toll on the action. (Just imagine, had I  put the <Suggestion>, after all this talk 😉 )

**Comment by rajibkhan** [comment]
> There was a menu command to do that before but it was moved into the TagSettings way of doing things. Having a million menu items to do configuration setting isn't a great way of doing things really but as you can tell, there's still a chunky menu left...

> There was a menu command to do that before but it was moved into the TagSettings way of doing things. Having a million menu items to do configuration setting isn't a great way of doing things really but as you can tell, there's still a chunky menu left...

__SUGGESIONS__:      // TL;DR version
  You can: 
      A) put it inside *Properties* submenu.
      B) or you can put it in the color change button tag rename dialog, since F2 calls the tag rename dialog
      C) all of the above.


__EXPLANATION__: 
I understand your point of view, and you're right. Too much item in a serial menu causes clutter. 
But that's one particular UI issue with feature filled apps. It's very difficult to determine which user needs what on regular basis, and in what context/sequence they're going to need it. That's why such apps give users certain level of UI customization controls to choose the placement of their preferred tools in user-friendly way. Same does BiglyBT for so many operations, except this action and a few other. There are many item in the menu actually, that I never use, but I feel the need of this one. I'm sure other users feel the need of those commands more. So, my preference alone cannot be a defining factor for an default application wide decision. 
  
However, In a particular context when I'm needing to operation (change tag color) repetitively, but not exclusively, and not solely serially but based on other factors, the sequence goes like this: 
  
DO { 
        1. go to tags overview (page/view transitions), 
        2. searching/typing the tag (additional actions ++ ), 
        3. select the tag
        4. focus in to setting tab, and additional scroll right maybe often needed since the button goes out of view due to window size, 
    5. changing the color (**actual intended operation**), 
        6. come back again where I was before
      
  } WHILE { I feel the need for same operation for another torrent based on certain condition }
  
  I'm sure that explains the number of pre-requisite action as entry barriers before I can perform the actual intended operation.  

Structure is important, but from UX perspective, , but also removing entry barriers to perform an intended action is more often of higher importance. especially, if it requires page/view transitions, where as the action operation is very simple, the entry barriers takes more user and processor time, and puts a higher toll on the action. (Just imagine, had I put the <Suggestion>, after all this talk 😉 )

**Comment by rajibkhan** [comment]
> There was a menu command to do that before but it was moved into the TagSettings way of doing things. Having a million menu items to do configuration setting isn't a great way of doing things really but as you can tell, there's still a chunky menu left...

**Comment by rajibkhan** [comment]
> There was a menu command to do that before but it was moved into the TagSettings way of doing things. Having a million menu items to do configuration setting isn't a great way of doing things really but as you can tell, there's still a chunky menu left...

__SUGGESION__:      // TL;DR version
  You can: 
      A) put it inside *Properties* submenu.
      B) or you can put it in the color change button tag rename dialog, since F2 calls the tag rename dialog
      C) all of the above.


__EXPLANATION__: 
I understand your point of view, and you're right. Too much item in a serial menu causes clutter. 
But that's one particular UI issue with feature filled apps. It's very difficult to determine which user needs what on regular basis, and in what context/sequence they're going to need it. That's why such apps give users certain level of UI customization controls to choose the placement of their preferred tools in user-friendly way. Same does BiglyBT for so many operations, except this action and a few other. There are many item in the menu actually, that I never use, but I feel the need of this one. I'm sure other users feel the need of those commands more. So, my preference alone cannot be a defining factor for an default application wide decision. 
  
However, In a particular context when I'm needing to operation (change tag color) repetitively, but not exclusively, and not solely serially but based on other factors, the sequence goes like this: 
  
DO { 
        1. go to tags overview (page/view transitions), 
        2. searching/typing the tag (additional actions ++ ), 
        3. select the tag
        4. focus in to setting tab, and additional scroll right maybe often needed since the button goes out of view due to window size, 
    5. changing the color (**actual intended operation**), 
        6. come back again where I was before
      
  } WHILE { I feel the need for same operation for another torrent based on certain condition }
  
  I'm sure that explains the number of pre-requisite action as entry barriers before I can perform the actual intended operation.  

Structure is important, but from UX perspective, , but also removing entry barriers to perform an intended action is more often of higher importance. especially, if it requires page/view transitions, where as the action operation is very simple, the entry barriers takes more user and processor time, and puts a higher toll on the action. (Just imagine, had I  put the <Suggestion>, after all this talk 😉 )

**Comment by rajibkhan** [comment]
> 1. multi-select them in Tags Overview and set their colour in the Settings sub-tab
> 2. Sounds possible
> 3. Sounds possible

Thanks for #2 and #3 implementation. #2 has an linked constraint issue. I'm creating a separate issue for that.
