### ISSUE TITLE
[ISSUE] sometimes applied manual tags gets inverted.

### ISSUE THREAD

**Issue by rajibkhan** [BiglySoftware/BiglyBT#2247]
I don't know how to explain this or reproduce it step-by-step. But based on whatever pattern I noticed so far, sometimes, when system is under load, and the UI is jittery/irresponsive, typing in filter control, somehow inverts all the tags applied to the currently/last selected torrent(s). That is, the tags already manually assigned becomes unassigned, and all other tags not assigned to the torrent(s) become activated/assigned.
With lots of tags in my installation, reverting or undoing them becomes really hectic, since there is no atomic 'tag/untag all' function. 
I think it has something to do with typing {space/tab} in the filter control. Since biglybt might be frozen at that time, the {space/tab}  remains queued in the buffur, and then when the focus changes, it uncontrollably but reccursively gets applied on the tab panel elements. which inverts all the tags.
As I said, I still couldn't figure out the exact action sequence to reproduce this issue. But I faced it so many times. 

[Just FYI, I have an IT company and we work on UI/UX design. Therefore, UI/UX matters are quite touchy factors for me while I'm using other software in my everyday life]

**Comment by parg** [comment]
FYI I hate working on UI... :)

**Comment by rajibkhan** [comment]
> FYI I hate working on UI... :)

😂 Guess I know what you mean. Not sure though that was sarcasm or resentment to my 'overwhelming demands', but either way it's ok. And. I lead a group of UI designers and close work with UI developers, so, I know most of them hate working on UI, more so when I'm involved (#confession). Anyways, Sorry if I'm expecting too much. I already love BiglyBT/Vuze. I already appreciate the hard work you've been voluntarily putting in keeping Vuze alive and thriving through BiglyBT. It's anyday one of the most feature rich application used. 

Frankly speaking, I'd like get my hands dirty to help you improve these things, but I'm primarily into design, and for hands on coding, my language is Python, and a li'l bit of JS (but not Java). However, in addition, I'm also into System Admin, so that's why I feel all the 'crazy need' for automation, process efficiency.

**Comment by rajibkhan** [comment]
@parg Let me try to help by suggesting a quick-and-dirty solution to tackle this issue. Unless/until the actual cause can be identified to dissolve the problem, a symptomatic remedy to the problem can be adding an 'Invert tags' action-button tags sub-tab, whcih will help invert all the manually applied tags in one go. That can give a quick way-out to solve the issue if encountered, instead of doing that manually on hundreds of tags.

**Comment by rajibkhan** [comment]
Thx for feature.
