### ISSUE TITLE
Magnet URI infohash should be hex encoded, not base32 encoded.

### ISSUE THREAD

**Issue by 11chubby11** [BiglySoftware/BiglyBT#2248]
When copying the magnet URI for a torrent in BiglyBT, the infohash is base32 encoded.  I believe it should be hex encoded as it is more widely used and recognised in this format, and BEP 9 calls for it to be hex encoded.

**Comment by parg** [comment]
The original specification used base32 (I should know, I wrote support for it back in the early 2000s) and then some people unilaterally decided to switch it:

https://stackoverflow.com/questions/29334707/why-magnet-generated-by-libtorrent-are-invalid

"The original magnet link format had the info-hash be base32 encoded, for space. At one point we (libtorrent and utorrent) decided it would be better to use hex (base16 encoded) for simplicity. This was probably around 2009 or 2010 iirc."

From Bep 9

<info-hash>
Is the info-hash hex encoded, for a total of 40 characters. For compatability with existing links in the wild, clients should also support the 32 character base32 encoded info-hash.

**Comment by parg** [comment]
I'll switch it and send anyone who complains in your direction.

**Comment by 11chubby11** [comment]
Alright, fair enough. Thanks.
I know Vuze still gives the magnet URI with a base32 infohash, but all other clients I've used give it in base16. It will make it easier for those of us who identify torrents by reading the infohash in the magnet link.
Also, the general tab for torrents gives the infohash in base16 which contradicts base32 in magnet URI.
