### ISSUE TITLE
I've Updated the Tag Icons, would you like a Copy?

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#2250]
I spent some time working on the Icons posted in the Tag Icons Wiki. I cleaned up quite a few. Some had white backgrounds, that I changed to transparent. That looks better on different coloured backgrounds.  Below are the ones I am currently using. If you would like a copy of updated set, let me know. Then you can package them as sets and replace the ones on the Wiki Page.

Here is what my settings look like. #D6FEED is the color for both Alternating Lines and the Sidebar Background.  As you can see all Icons are now Transparent Backgrounds.

![image](https://user-images.githubusercontent.com/37715552/133680333-0e8df1bd-ce22-4b5a-a118-f4d39e0ebce3.png)

**Comment by NaPurHab** [comment]
I decided to just provide a link and let you decide.

[![image](https://user-images.githubusercontent.com/37715552/133683546-acd0e974-b2b2-4125-8826-ecd7f2b4b1c6.png) tagicons.rar](magnet:?xt=urn:btih:V2FBJLAQZ4XT3QY3LM37XLXYJRMXKCSQ&dn=tagicons.rar&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce)

**Comment by parg** [comment]
Thanks, I've added them to the Wiki
