### ISSUE TITLE
[Feature Enhancement] make 'tags' (tagnames) available as defined variable for tag constraint.

### ISSUE THREAD

**Issue by rajibkhan** [BiglySoftware/BiglyBT#2251]
With reference to 'defined variables' currently mentioned in this [wiki](https://github.com/BiglySoftware/BiglyBT/wiki/Tags#Constraints)

Can the tag names be made available via a defined variable so that it can be used with contains() or matches() function for partial match evaluation. I understand multiple tags becomes an array.

Actually, I'm just looking for a way to regex/partial matching with tag names. Any suggestion? or JS function codesnippet/template?

TIA

* OS Win 10

**Comment by parg** [comment]
done next beta (tag_names)
