### ISSUE TITLE
Highlighter and light row color by Tag constraint SetColor() conflict.

### ISSUE THREAD

**Issue by rajibkhan** [BiglySoftware/BiglyBT#2255]
Selecting/highlighting torrents having light row background color set by SetColor() via tags constraints turns the text white, but the highlighted background doesn't change to dark(blue). 

Result = highlighted light text on light background = unreadable text.

* OS Win10
* BiglyBT 2801_B22

**Comment by parg** [comment]
Indeed, if you have set an explicit foreground/background it doesn't change on selection - you need to select your colours carefully. What if you select a background colour that is the same as the selected colour? Then you can't easily see your selection...

**Comment by rajibkhan** [comment]
As per my scenario, The background actually doesn't change, but text does. That actually causes the readability issue. Maybe changing the z-order the highlighter color painted on canvas such that highlighter/selector's background color is drawn on the explicitly set background color. This much should at least resolve the current readability issue.

However, to address the scenario you mentioned, instead of inheriting hardcoded/fixed color from system/preference, interactive color layer blending advanced math can be applied, but that will cause analysing a lot of if-then factors under diverse use-case scenarios. might even make matters worse for simple users. 

I'm putting some hint in the **Extra** below, indulge if you're curious...

**Comment by rajibkhan** [comment]
**EXTRA**
Sharing a quick overview of an approach that comes to my mind. ( It's not perfect or even complete, just food for thought )
Invert or darken (color burn) the background of highlighter background based on row's background color value (resultant BG), and invert to lighten (color dodge) foreground/text's color relative resultant BG value.
However, unless further sophisticated approach is used in implementation, it can actually cause confusion for unaware users by 

Unless you're already aware of how the color math works, checkout the Darken/Lighten mode explanation and math in the special 8 section of the article:
https://photoblogstop.com/photoshop/photoshop-blend-modes-explained#TheSpecial-8-BlendModes
I'm not expecting you learn photoshop, I'm just referring to math formulas and explanation of their results.
This article has simpler concise explanation than the Wikipedia article:
https://en.wikipedia.org/wiki/Blend_modes
