### ISSUE TITLE
Changing tag names breaks effectiveness of tag constraint dependency.

### ISSUE THREAD

**Issue by rajibkhan** [BiglySoftware/BiglyBT#2258]
It's been a persistent issue, if tag *A* depends on tag *B*, changing *A*'s name later to *AA* can cease to auto-assign *B* to eligible torrents.
It's not feasible to check each tag settings separately. For temporary symptomatic remedy, An *Evaluation Error* column can be used in tag overview to mark error states if any such dependency isn't working, as error message is shown right next to tag constraint during saving.

I guess, so happens, 'probably'* because the dependency isn't created via any any backend unique ID but straight-forward tag name text only.
It's understandable that reverse constraint redefinition as text is difficult even if backend UID's are used.
But if such ID is created, and visible via column, it's possible to create tag constraint using something like "hasTagID("12BAF7")" function to be more resilient. I'm sure you can think of a better way.

Another issue is tag regrouping/reassigning, which is not within the scope of this issue title, but may involve relevant implementation case/technique: 

Tag Groups (I guess) are also 'probably' not connected via backend IDs. 
Since there's not direct way to rename an existing tag group, the way is to create new tag group (via "group->> add-group") while intended tags are selected and reassignment. It works, but with large number of selected tags, often takes quite a while (in minutes), sometimes the even UI freezes or app crashes. Same freezing/crashing also happens for reassigning large number of tags to a different existing group.

(*Disclaimer: since I don't know the nooks and crannies of the backend, I'm guessing a lots of things about core here, and might be wrong in doing so.)

PS:
Also, sorry for my verbose reports. I know you're busy and your time is precious. 
I try to share my thoughts/experiences to help you in understand the scenarios and to help in analyzing and finding a solution. 
If only mentioning the facts and keeping my thoughts to myself helps you better, let me know. I'll be quieter and keep them to the least facts/info required, and leave the rest upto you.

* OS Win10
* BiglyBT 2801_B22

**Comment by parg** [comment]
The 'status' column in Tags Overview will show any such errors.

When you say you have performance issues when re-assigning a lot of tags, how many tags are you talking about? When I do it with 20 tags it is pretty much immediate.

**Comment by rajibkhan** [comment]
20 tags is also not a problem for me either. But for me, sometimes 100-150 tags causes freezing/crashing. So I have change them in smaller groups which takes redundant repetitive-actions, and most importantly time.

Other than reorganizing/reassigning reason, I actually often just need to rename tag-groups to tweak alphabetical sorting, so that I have the most relevant tags at the topmost (visible part) of my 'Tags' subtab in the library view for eazy accessibality. Later at a different time and purpose, I move the group back down and put some other tag-groups to top via alphabetical ordering (by renaming). But reassigning is the only way to rename group or put tags accessible at the top.

However, with thousands of tags, dragging and dropping just a single tag from one gruop to another (in sub-tab view) takes a long time tearing down the entire tags canvas one by one, and redrawing it with updated view.

My diagnosis however is that most of the time 80% CPU consumed JVM is caused by auto-tags evaluation. since most of them are regex. That causes other activities sluggish.

**Comment by rajibkhan** [comment]
My System: 
========
Intel i7 + 32 GB + System on SSD. I leave around 8 GB max assigned to JVM. While running, my BBT Takes upto 5/6 GB. 
However, I do have lots of stopped downloads/downloaded are in my library. 
My disk operations are inherently a bit sluggish though (due to MS storage spaces redundancy disk volume, and some of the disks are on USB connected docks.


My regular case: 
===========
300 torrents queued (since many are stuck, 30-50 torrents active/uploading/downloading, 5-10 forced, 100 queued/paused. 5000+ stopped/completed. However, I keep some completed ones running (unpaused) for long time for seeding.

Since BBT cannot be run in multiple instance. All my media actully in the same library. 
If Multiple instance/profile were possible to run separately, Maybe I could distribute the workload in a more compartmented. manner.

My scenario:
=========
Actually, I use BBT as a center point (media library) to traverse/search and open my media/shows/movies/music/ebooks, instead of looking for them in the explorer. Even if I delete, content for recovering storage, I keep the torrent, so that I can redownload them later. 

My Internet isn't superfast, so it actually takes loong time to download even a single episode let alone a season. 
Plus, old torrents often don't have seeds. That's why I prefer having them organized by tags. 
It took me 3 months to download all seven seasons of Macgyver. Hercules never showed up in full. (duh).Y eah, i'm 80/90s kid.]

However, unless I'm really done with old outdated contents such as old versions linux.iso and such, I don't send downloads to, since the manual tags are lost, organization is broken and single point searching is hindered.

**Comment by parg** [comment]
You can run multiple instances of BiglyBT if you start it via the command line - see https://github.com/BiglySoftware/BiglyBT/wiki/Command-Line-Options#running-multiple-biglybt-instances

Not saying that is a great solution as it most likely introduces other issues.

**Comment by NaPurHab** [comment]
> It took me 3 months to download all seven seasons of Macgyver. **Hercules** never showed up in full. (duh). Yeah, I'm 80/90s kid.]

I just reliably DLed **Hercules** last month from RARbg.  All 6 seasons + Specials. Check it out.  Only about 4 seeds each, but all completed DLing.

**Comment by rajibkhan** [comment]
> You can run multiple instances of BiglyBT if you start it via the command line - see https://github.com/BiglySoftware/BiglyBT/wiki/Command-Line-Options#running-multiple-biglybt-instances
> 
> Not saying that is a great solution as it most likely introduces other issues.

I actually tried that with vuze. Long time back. As you said, had other issues. Can't clearly remember what. 
But, I guess I'll give that another try.
Thx.

**Comment by rajibkhan** [comment]
> > It took me 3 months to download all seven seasons of Macgyver. **Hercules** never showed up in full. (duh). Yeah, I'm 80/90s kid.]
> 
> I just reliably DLed **Hercules** last month from RARbg. All 6 seasons + Specials. Check it out. Only about 4 seeds each, but all completed DLing.

@NaPurHab Thx for the great lead. 😃 Hope you're still seeding.

**Comment by parg** [comment]
So I added a 'rename group' menu option to the last beta (B24) - it doesn't do anything smart but is a but easier than manually selecting all the tags and setting their group. You can do it from the 'subtabs' view by right-clicking the group name, that way doesn't cause any sidebars focus switching issues.

To investigate performace, have you tried checking the thread_1/2.log files in the "logs" folder? They track the most active threads, might give a pointer into what could be looked at.
