### ISSUE TITLE
click on "swarm merge available" and then where is it?

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2261]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B2.8.0.0/4 az3

I see this "swarm merge available!" and then when I click that little icon, it disappears, and I see this window, but then maybe I closed it and then how do I find it again?  I right-clicked on my torrent, and looked through the different tabs like Content, Control, etc. and found nothing that mentioned anything about that available swarm merge.  How do I get it back?

**Comment by parg** [comment]
The window is the download's specific chat - go to the Chat subtab, select the type as Download and then select the 'public chat' tab.

**Comment by as-muncher** [comment]
I went looking for it and couldn't see it.  Does BiglyBT delete those old swarm merge messages?  I did what you said in going to the Chat subtab, and Download was already selected, and there was nothing there, just some grey text that wasn't anything to do with the swarm merge message.
