### ISSUE TITLE
Error on Privacy Tab

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#2264]
![image](https://user-images.githubusercontent.com/37715552/134567578-ebf2cbfd-76be-470c-8cec-979dc5c1b8ca.png)

Have not used this Tab in about 3 versions. When I clicked Search DHT, I saw the highlighted error. Not sure why. I have not updated Java in a while, the version I have is the latest. And has not been updated in a few months.

Not sure what it means `Other destinations not enabled`.

Java 1.8.0_301 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_301

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.8.0.1_B23/4 az3

**Comment by parg** [comment]
You've disabled 'other destinations' under

Options->Plugins->I2P Helper->Tunnels: Other

why would you do this and then waste my time complaining about it? If you don't understand things then don't mess with them.
