### ISSUE TITLE
Change network option with command runner

### ISSUE THREAD

**Issue by veermetri05** [BiglySoftware/BiglyBT#2266]
I want to change the network settings for torrents, once download is complete.

Downloading from clearnet and seeding on I2P, I don't want to want to keep seeding on clearnet. The seeding that occurs while downloading in ok, after I completely download it, I want to change the network to I2P.

I installed to command runner. I didn't understand anything. Even if it requires to code in Java or JavaScript it is okay.

**Comment by parg** [comment]
I can modify the Simple API plugin to support setting of network - requires a bit of figuring out how to use it though. You would use the 'command runner' plugin to kick off a script that then invoked a URL to change the network.

https://github.com/BiglySoftware/BiglyBT/wiki/Plugins

**Comment by veermetri05** [comment]
Thanks for adding the feature to change the network with Simple API. It is really 'simple'.
