### ISSUE TITLE
Cant Seem to Install Bigly

### ISSUE THREAD

**Issue by SanguineSol** [BiglySoftware/BiglyBT#2270]
Hey so whenever i attempt to install Bigly using the standard windows installer on the website i get this message....

https://gyazo.com/5e958ceee1317e4bd5d0624abe231995

- I have attached the log file that was created if that helps.
- Im using Windows 10
- My antivirus is off. (Malwarebytes)
- I had used Bigly a really long time ago +1 year so i am unsure if that is casuing some sort issue.
- This is a fresh install.
- Any help would be much appreciated!
[i4j_nlog_15.log](https://github.com/BiglySoftware/BiglyBT/files/7238128/i4j_nlog_15.log)

**Comment by parg** [comment]
Hmm, it is picking up your Java 10 installation from 

c:\program files\java\jre-10.0.1

Not saying this is the cause but perhaps you could remove it and see if it helps (unless you have it for a reason)?

**Comment by SanguineSol** [comment]
> 
> 
> Hmm, it is picking up your Java 10 installation from
> 
> c:\program files\java\jre-10.0.1
> 
> Not saying this is the cause but perhaps you could remove it and see if it helps (unless you have it for a reason)?

Removed the 10.0.1 Java as you suggested and now it works!
thank you @parg for your super fast help!
Its greatly appreciated!

**Comment by parg** [comment]
glad it worked!
