### ISSUE TITLE
Problems with installer

### ISSUE THREAD

**Issue by bennettbrad** [BiglySoftware/BiglyBT#2271]
I'm having problems with the Linux installer. I get the error below. Since it looks like the installer hasn't been changed in a couple of months, this seems impossible. Anyone have any ideas? I've tried this on Debian 10 KDE Plasma and 11 KDE Plasma. Both yield the same error. And of course, I've tried downloading it several times.
don't need JNA
not wayland

gzip: sfx_archive.tar.gz: not in gzip format

I am sorry, but the installer file seems to be corrupted.
If you downloaded that file please try it again. If you
transfer that file with ftp please make sure that you are
using binary mode.

**Comment by TuxPaper** [comment]
Did you download the installer from github or biglybt.com?

For github sha256sums on https://github.com/BiglySoftware/BiglyBT/releases
The installers on biglybt are the same and should have the same values. Only the filename is different.
