### ISSUE TITLE
[enhancement request] Max Global # of upload slots limit 

### ISSUE THREAD

**Issue by rafi-d** [BiglySoftware/BiglyBT#2276]
Hi,
Can you add that limit to the already existing "max # slots per torrent" , like we have for # of connetions - per torrent and global?

This is helpful, when you have *many* seeding torrents, but only limited resources in your router/PC.
We can still leave 1 as minimum that will override the above  in case the # of seeding torrents exceed this maximum. 

The idea is to split this maximum between all seeding torrents equally when the max # per torrent (*  # of seeding torrents) is reaching to a higher than this new max limit  (or based on some other criteria like # of peers in swarm).

Rafi

**Comment by Seeker2** [comment]
This is also useful to get an average speed per upload slot.
Example:
1000 KB/sec max upload speed with 100 global max upload slots = 10 KB/sec average per upload slot.

**Comment by parg** [comment]
How would you implement this?

**Comment by parg** [comment]
For example, you have 10 upload slots, 100 seeding downloads each with 5 connected leechers, max upload speed of 1000KB/sec. 

Your current upload speed is 500KB/sec

What do you do next?

**Comment by rafi-d** [comment]
If you are you asking about the limit *I* suggested, if you have a global limit set to 500 slots, you will just allow only 5 per seeding-torrent. The rest will be handled by the existing global upload speed limiter (if active). 

You can provide an option to also auto-set-limit per torrent or per-slot , but I didn't suggest that, and I am  not sure it is desire-able... May be as an advanced option...

**Comment by parg** [comment]
So you simply want the upload-slots-per-torrent to be automatically set to

global-upload-slot-limit / number-of-seeding-torrents

What if you have 500 slots and 500 active torrents. 499 of your torrents have no connected leechers. 1 of your torrents has 500 connected leechers. You want that torrent to have a single upload slot?

**Comment by rafi-d** [comment]
> So you simply want the upload-slots-per-torrent to be automatically set to
> 
> global-upload-slot-limit / number-of-seeding-torrents

Only when this maximum is being exceeded... 
I guess we can tune the logic, so that:
1. you can count only active connections toward the global max, but always try 1 (as I suggested - 1 is mandatory minimum)
  1.a you might also define "active" as above some minimum X speed, say 3KB/s
2. and to your example - with this modification, this active one will be set to your per-torrent max # of slots, so, say 10 for example...

**Comment by parg** [comment]
Which system/router resources are you most worried about? You still have connections to peers when they don't have an upload slot, router load isn't going to change much.

**Comment by rafi-d** [comment]
Use cases, would be - users  that has thousands of torrents, and seeds hundreds  of them (like Seeker2 ... ? ). 

So, 1000+ seeding torrents x 10 connection per torrent can become quite a large # of connections. So, yes, limiting the amount of connections in the router is one aspect (I don't think uTP connections are visible to the router). Also diskio & cpu load handling so may - can be ocwe-loading the HD I/O and their cache.

We have download global max, and per-torrent max for both upload AND download. Why shouldn't upload connections|slots  be  dealt with similarly?

You can definitely default it to a large number as default (so to be similar to the current state and avoid issues), or even disable the feature and options for it as default.

**Comment by parg** [comment]
But your proposal doesn't limit the number of connections in the router, it only has potential to reduce the number of connections that are uploading. 

Also having 1000+ seeding torrents with 10 connections each seems an extremely unlilkely scenario - do you have 10,000 peer connections?

**Comment by rafi-d** [comment]
True, I don't think it is possible to limit it directly in the router, so this is in-directly doing it. 
As for  stats with running thousands of torrents - Seeder2 can respond better..

**Comment by parg** [comment]
How is it indirectly limiting the number of connections in the router?

The number of connections isn't limited by your proposal. Your proposal only limits the number of connections that are sending data to peers. 

The only benefit your proposal appears to have is to increase the average upload speed for those that are unchoked (at the cost of stopping uploading to other peers) assuming that

1) you are hitting your network upload limit (if not then reducing the uploading peers will reduce your overall upload speed)
2) the peers that remain unchoked are actually capable of being uploaded to faster (if not then this will reduce your overall upload speed)

**Comment by rafi-d** [comment]
Well, true, I was not sure about active vs all (as I started), it is surely something to think about. 

Also, you can think of another advantage : being able to define a large # slots/torrent, and a "reasonable" global for your environment. So, if you know average 100 seeding torrents, set a large (say 100 slots) per torrent and define 1000 as a  global max, and with a smart algo, you can provision in-demand torrents (in larger swarms) with more (>10 ) slots, and less active - with less (<10), all within your 1000.

**Comment by Seeker2** [comment]
> So you simply want the upload-slots-per-torrent to be automatically set to
> 
> global-upload-slot-limit / number-of-seeding-torrents
>
> What if you have 500 slots and 500 active torrents. 499 of your torrents have no connected leechers. 1 of your torrents has 500 connected leechers. You want that torrent to have a single upload slot?

Before I answer your question I must make fun of the nomenclature.

Those 499 torrents don't matter.
There is effectively only 1 active torrent.
...connected to 500 peers but won't upload to all 500 at once even if max global or per torrent upload slot limit is higher than 500.

Probably 50+ "random" peers will be connected but idle.
Which peers are idle can change drastically from minute-to-minute.

There's also likely 30+ peer disconnects per minute.
Some of the peers became seeds and disconnect from your seed. Some lost connection due to packet loss or bugs in their programming.
Some could be disconnecting due to shark or squirrel attacks ...biting the wires.

The more peers you connect to, the more idle and disconnecting peers you'll see due to unstable peers mixed in.

To answer your question:
No. If there's 500 global max upload slots and 1 torrent has ALL 500 of them because the other torrents have ZERO peers... I don't see a problem.

**Comment by rafi-d** [comment]
For an initial (simpler) release of such feature I'd say that we need:

- 0.  Average == GLOBAL divided by Per-torrent count (minimum   - 1)

- 1. Add that global  setting in the GUI

- 2.a Add "Equalizer" mode logic per-torrent, to stop populating (re-connecting) new slots in a torrent in case the global max is reached, and the # of slots for this torrent is *ABOVE* the average

- 2.b Add "Equalizer" logic to *always* add a slot to a torrent if it is the first/only one AND there are other torrents with more than 1 slot OR it's slot count is below the average 

This kind of mode-logic will give a "mode" of-  equal # slots per torrent up to 1, and a max # of seeding torrents - is always equal or less that this GLOBAL MAX.

**Comment by rafi-d** [comment]
Adding a reference from qBittorrent:

![image](https://user-images.githubusercontent.com/2458280/146635707-01f873bc-c363-4b29-82a5-d7e12976fbca.png)
