### ISSUE TITLE
 Failed to load class SLF4J.

### ISSUE THREAD

**Issue by Achaean** [BiglySoftware/BiglyBT#2278]
**Hi!**  :-)
Latest BBT version (2.8), on  Devuan oldstable x64 KDE.

Java 1.8.0_302 (64 bit)
  Oracle Corporation
/usr/lib/jvm/java-8-openjdk-amd64/jre

SWT v4942r22, gtk/3.22.11, zoom=100, dpi=96
Linux v4.9.0-16-amd64, amd64 (64 bit)
B2.8.0.0/4 az3

When starting BBT from console, I'm getting this error.
Not sure what it is and can't see any visible effect.
I suppose it's a developer warning of some kind.
I'm just reporting it:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details
```.

**Comment by parg** [comment]
Thanks, yup, just something to ignore.
