### ISSUE TITLE
Updater error.

### ISSUE THREAD

**Issue by Achaean** [BiglySoftware/BiglyBT#2279]
**Hi!** :-)
Latest BBT version (2.8), on Devuan oldstable x64 KDE.

Java 1.8.0_302 (64 bit)
Oracle Corporation
/usr/lib/jvm/java-8-openjdk-amd64/jre

SWT v4942r22, gtk/3.22.11, zoom=100, dpi=96
Linux v4.9.0-16-amd64, amd64 (64 bit)
B2.8.0.0/4 az3

I ran the updater, as I prompted from a plugin's uninstallation (and it failed)?
Here's the output:

```
>./updateBiglyBT
+ '[' '' = rerun ']'
+ ISRERUN=0
+ '[' 0 -eq 1 ']'
++ realpath ./updateBiglyBT
+ SCRIPT=/home/giorgos/biglybt/updateBiglyBT
++ dirname /home/giorgos/biglybt/updateBiglyBT
+ SCRIPTPATH=/home/giorgos/biglybt
+ '[' '' = '' ']'
+ PARAMS=("com.biglybt.update.Updater" "updateonly" "${SCRIPTPATH}" "${HOME}/.biglybt")
+ for i in "${!PARAMS[@]}"
+ '[' com.biglybt.update.Updater = updateonly ']'
+ '[' com.biglybt.update.Updater = restart ']'
+ for i in "${!PARAMS[@]}"
+ '[' updateonly = updateonly ']'
+ PARAM_IDX_APPPATH=2
+ break
+ '[' '!' -w /home/giorgos/biglybt ']'
+ for i in "${!PARAMS[@]}"
+ '[' com.biglybt.update.Updater = updateonly ']'
+ '[' com.biglybt.update.Updater = restart ']'
+ for i in "${!PARAMS[@]}"
+ '[' updateonly = updateonly ']'
+ PARAM_IDX_USERPATH=3
+ break
+ echo Running Updater..
Running Updater..
+ java -cp /home/giorgos/.biglybt/plugins/azupdater/Updater.jar com.biglybt.update.Updater updateonly /home/giorgos/biglybt /home/giorgos/.biglybt
Error: Could not find or load main class com.biglybt.update.Updater
+ '[' 0 -eq 1 ']'
+ echo Done
Done
>
```

**Comment by Achaean** [comment]
PS. Despite the above mentioned error, updater worked properly.
(I prompted to use it, from the plugin uninstaller wizard and indeed the plugin uninstalled (It was the "Friends" plugin)).

**Comment by parg** [comment]
That is a weird one - does 

/home/giorgos/.biglybt/plugins/azupdater/Updater.jar

exist? If so does it contain a class file called Updater.class (in directory com/biglyby/update) - note that a .jar file is simply a .zip file renamed.

**Comment by Achaean** [comment]
> That is a weird one - does
> 
> /home/giorgos/.biglybt/plugins/azupdater/Updater.jar
> 
> exist? 

**Nope!**
There isn't even a azupdater catalog there:
```
>ls /home/giorgos/.biglybt/plugins/
aercm  azlocprov  azmsgsync  azneti2phelper  aznettor  azrating  azupnpav  azutp  dorkboxupdater  mlDHT
>
```

Or actually, **there is** one, but at **different path:**
```
>ls /home/giorgos/biglybt/plugins/azupdater/Updater.jar
/home/giorgos/biglybt/plugins/azupdater/Updater.jar
>
```

**Comment by as-muncher** [comment]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B2.9.0.1_B12/4 az3

I've got an updater error too.
BiglyBT updater, failed
Under details:
    Mandatory plugins -     Failed to load plugin details: Plugin list load failed, https://10.75.141.21/update/pluginlist3.php?type=&&version=2.9.0.1_B12&&app=BiglyBT&&os=Windows+10&&osv=10.0&&arch=amd64&&ui=az3&&java=1.8.0_202&&swt_platform=win32&&swt_version=4942&&pmv=1.27&&epids=3dview%3Aaercm%3Aazlocprov%3Aazemp%3Aazmsgsync%3Aazneti2phelper%3Aaznettorbrowser%3Aazrating%3Aazupnpav%3Aazutp%3Amigratetorrentapp%3Amlab%3Amldht%3Aaznettor%3Avuzexcode%3A: I/O Exception while downloading 'https://plugins.biglybt.com/update/pluginlist3.php', Connect timed out
    Mandatory plugins - Failed
Finished
