### ISSUE TITLE
After changing priority a file is not visible in Library

### ISSUE THREAD

**Issue by KonradKl** [BiglySoftware/BiglyBT#2280]
If a file has priority changed from Do not download/Delete to Normal, the change is not reflected in Library. The file is invisible from Library/Downloading section.

Java 17 (64 bit)
  Oracle Corporation
c:\program files\java\jdk-17

SWT v4942r22, win32, zoom=100, dpi=96
Windows 8 v6.2, amd64 (64 bit)
B2.8.0.1_B31/4 az3

**Comment by parg** [comment]
Fixed next beta (B32) - thanks

**Comment by KonradKl** [comment]
Thanks for fix. Working.

**Comment by parg** [comment]
great
