### ISSUE TITLE
Automatic & Force Recheck Action Both Complete without saying Anything (if OK)

### ISSUE THREAD

**Issue by dbareis** [BiglySoftware/BiglyBT#2281]
It would be nice if the torrent was somehow marked as having passed the check.

---
![Screenshot @ 6_10_2021 , 3_48_53 PM, D_ 0 00 k U_ 0 00 k +](https://user-images.githubusercontent.com/295230/136142627-55974297-c537-47be-833a-3055c3427aa8.png)

Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.8.0.1_B32/4 az2

**Comment by parg** [comment]
If it failed then it wouldn't be at 100% done...

**Comment by dbareis** [comment]
You never get to see "100% done" and sometimes you are not even sure it did
it in the first place.

**Comment by parg** [comment]
B34 has a new log view under Tools->Plugins->Log Views called "Alerts" that lists them. Not a plugin view but it is the best place for it.

**Comment by dbareis** [comment]
Thanks, I assume the others are all plugin related (I'd never seen that
menu if I want to view something I look under view), maybe the whole
submenu could be duplicated under "View", but happy with it as it is
and thanks for that.

---
Thanks
Dennis
