### ISSUE TITLE
Request: A way to Delete a torrent that matches a constraint and an AGE.

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#2282]
I was looking through the Constraints to figure out how to setup a tag to delete a torrent once it was a year old.  I keep all my content as 1080p, but some also have 4K versions.  The 4K is for friends that request specific content.  Mostly it is for immediate use.  Though I tell them after a time, if I need the space, it will fall back to only 1080p being available.

So I need 2 things, a way to identify the target torrents, which I can do with constraints:
`contains( name, "2160p", 1 ) && >age(weeksToSeconds/wtos/w2s(52))`
and a way to Delete from Computer when an AGE is passed. Which would eliminate the 2nd half of the constraint I just listed.

2 possible methods of Delete By Age are:

**1)**. Add to the SCOPE, the Actions from Share Ratio for When Exceeded, to be applied to Constraints.

**2)** ADD on behind Scope (or a new line)
`Max Age (Days) [input field]   When Exceeded [Action Selector]`

Then combined with the constraint `contains( name, "2160p", 1 )` that identifies 4K content, it would be problem solved. _That plus setting it as `is Filter`._

Note that I am thinking that Delete by Age, should be tied to Constraints. And that if the constraints is blank, it should do nothing if Set. Otherwise it could wipe out every thing.

**A last idea**
A TEST Button for Constraints, that pops up a window listing what would be effected by the constraints and options as set.  Would help prevent mistakes.

**Comment by NaPurHab** [comment]
That is a Volume/Quantity control. I am looking to limit by age.  I keep 1080p content on my PLEX Server. As a Bonus to my Friends/Family, when I know they have a 4K TV, I also get the 4K Versions when available.  But I want to limit the 4K Bonus Content to remain for a year maximum. Only if I need space would I remove 4K Content manually.

Now that I think about it, the idea of ADDing on behind Scope (or a new line)
`Max Age (Days) [input field] When Exceeded [Action Selector]`
would work best.

**Comment by parg** [comment]
Everyone wants a simple solution to their very specific requirements. How many other people have asked for this feature? Erm, none. If 100 people asked me for it I might consider making an effort to make it simple. When one person asks me for it and the ability already exists, no.

**Comment by parg** [comment]
Oh, and if testing with the _Old tag you would want to modify the constaint to avoid continual attempted application:

`contains( name, "2160p", 1 ) && >age(weeksToSeconds/wtos/w2s(52)) && !hasTag( "RemoveOld_Old" )`
