### ISSUE TITLE
selecting files in a torrent and to Show in Explorer freezes my system

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2287]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B2.8.0.0/4 az3

So when I select 10 files in my torrent, choose "Show in Explorer", that should bring up 10 Windows Explorer windows, right?  That ends up freezing my system.  So I guess I ought not to do that.  I'm just letting you know.  It might be handy if a prompt comes up asking if I want one window or 10.... just a thought.  

The other thing is that when I choose a file in a torrent, do a search for existing data files, what happens is that, after it checks, then Biglybt checks the whole torrent.  If you've selected 5 files in that torrent and do a search for existing data files for each one, and then BiglyBT is also trying to check the whole torrent at same time that it's also looking for additional data, that really really slows things down.  Maybe if there are such checks with multiple files in the same torrent, wait until they all finish before checking the whole torrent.  And if checking is already in progress, maybe it should be halted?

**Comment by davidalb97** [comment]
I confirm that I could replicate the issue on Archlinux with any OpenJDK 7, 8, 11 and Oracle's JDK 7, 8, 11.
Freezes and slows down my entire system UI.
Using Nvidia drivers video-nvidia-470xx.
