### ISSUE TITLE
says data is missing

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2288]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B2.8.0.0/4 az3

So, to create more space on my hard drive, I wanted to move some files to an external drive.  I copied them over in Windows Explorer.  Then, in BiglyBT, I set those files to "Delete" and didn't do it in Windows Explorer in case BiglyBT needed a chunk or two from those files for other files in the torrent.  BiglyBT deleted all the files except for about 5K in one file.  Then, I changed the status to "Do not download".  However, when I started BiglyBT again, it said that data was missing and put the torrent in a stopped state.  I had to check the whole torrent over again.

**Comment by as-muncher** [comment]
I'm also finding, perhaps a new issue, is that sometimes data doesn't show up in my torrent anymore, like maybe 1/3 of it is there, so I have to pause or stop, then recheck.  I don't know why the data is disappearing all of a sudden.  Is it maybe because I lowered the java virtual machine cache from 100 MB to 32 MB? and then 78 MB of cache disappears?  I don't know.  It's weird, though.

**Comment by exekutive** [comment]
this happens to me too. Whenever I change a file priority from "delete" to "do not download" , the torrent says error data missing

**Comment by as-muncher** [comment]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.0.0.1_B27/4 az3

To recreate:
When downloading a torrent, copy some of the complete files to another directory.  Delete the torrent, and then add it again using your usual save directory, but put the torrent in a paused state.  Do a search for existing data files, but for the directory where you saved those completed files.  After the torrent has checked, mark the complete or close-to-complete files as Do Not Download.  Select all the files in that torrent, and Clear Links.  Start the torrent again, says Error: Data is missing

**Comment by exekutive** [comment]
why was this closed?

**Comment by parg** [comment]
Nobody's going to look into it.
