### ISSUE TITLE
Problem Archiving Torrents

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#2290]
![image](https://user-images.githubusercontent.com/37715552/137395302-0ac236b5-10ee-4cb4-bf85-78e07d3c2302.png)

I have 3 torrents that were archived, but I wanted to change the path on disk. I use a TAG `As-Is` for torrents I use without change. I had placed them in the Root of a Category Path. But wanted to Move them to a Named Sub-Path that would group them.   I restored them from Archived, Moved them, then tried to Archive them again.  First by adding back the `ArcOver 10` Tag (Max Ratio 10 then Archive). That failed to archive them.  Next I selected them, Right-Click Menu and Organize/Archive. Again Fail. Though it did oddly remove the `ArcOver 10` Tag. Finally I tried dragging them to the `Archived Downloads` Tag, and got the above Error.  I had them in a stopped state at the time. So they should have been in an archivable state.

Also, when I clicked on the `the Wiki` link in the error, I got a:
![image](https://user-images.githubusercontent.com/37715552/137396480-8daa7de4-0508-4b82-8ae7-6016576b6e62.png)

I just want to return these torrents to the `Archived Downloads`, but it is simply not working.

Java 1.8.0_301 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_301

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.8.0.1_B34/4 az3

I created an Icon for `ArcOver 10` Tag, though the number can be whatever.  Here is the Icon you can add it to the Pack.  Also a Blank Tag for the Untagged. They are in in the correct 20x14 ratio.  I have then in the Tag Icons/Type directory.
![Vault - Archive](https://user-images.githubusercontent.com/37715552/137397944-8a65e960-0c3d-421e-aaca-a84f778ce5b5.png)
.
![Untagged](https://user-images.githubusercontent.com/37715552/137397959-93c3e8fd-1155-44e2-b139-a40ff489774d.png)

**Comment by NaPurHab** [comment]
I just thought to Force a Re-Check.  Still after that, It will not Archive, and when I try Right-Click, Organise/Archive when in a Stopped State, it Fails to Archive, and removes the `ArcOver 10` Tag.   **Odd.**

**Comment by parg** [comment]
yup, thanks
