### ISSUE TITLE
Feature Request: Desperately need a way to change drive letters and/or Root Paths of data files

### ISSUE THREAD

**Issue by Poorman65** [BiglySoftware/BiglyBT#2294]
* OS: Windows 10
* BiglyBT Version Number: 2.8.0.0

I occasionally need to refactor my data files to different hard drives and it is always a nightmare that takes weeks to accomplish. It should be as simple as moving the files in Windows and then changing the root path in BiglyBT to the new location. Even simple changing the drive letter in Bigly would make it relatively painless. Unfortunately, there doesn't seem to be any way to accomplish this task without a ton of work.

The "Move Data Files ..." option will place all of the selected files in the same folder and lose any subfolders that I have created. So if I have my files collected in folders "01" through "99", I would need to go through each of those folders in order to do the move within Bigly. I then would need to copy all of the remaining content that I no longer keep in the Bigly library, into those folders manually anyway. ... and I have several thousand folders to deal with, so it isn't remotely feasible anyway.

The "Search For Existing Data Files" is very flaky. I always end up with a mess that I need to fix, torrent by torrent.  Also, it is not very straightforward to get the search option to appear. It seems like I need to force the files to switch to the downloading state, and then stop them, before the option appears. It would be much easier if the option was always available, at least on Stopped torrents, even if they are in the completed section. 

This latest attempt, I combined multiple drives full of torrents into one 20 TB drive.  I have spent the last two weeks trying to fix things. Last time I tried to do this, I ended up giving up, and just removed the messed up files from my Library entirely.

I have several hundred torrents where they were found on the new drive, but the "Save Path" wasn't updated. Bigly thinks that the files are fine. Under the "Files" tab, it shows the correct drive letter, but in the "Save Path", it still shows the original path. If I "Check if Files Exist", it finds them. But if I right click on the torrent's row, and "Show in Explorer", it attempts to go to the original folder, which doesn't even exist.

In order to solve this, we either need the ability to edit  a file in order to update the paths with a simple text editor, or the Move needs to be much more robust, so that we can have more granular control over the path.

**Comment by hatewesterncivilization** [comment]
It's a nightmare todo that thing during last two weeks, and it even only trying.

Useful feature and yet super-tricky, if you can repath torrents just in one moment and minute. 

I am all for the feature, thanks.

**Comment by Poorman65** [comment]
Is that a pre-release build? I have the latest available through the Updates menu. I can run some tests with it, but I have finally completed my mass move. I may do another drive merge in a few months.

**Comment by parg** [comment]
Oh well
