### ISSUE TITLE
Update Bigly torrent info from modified torrent files?

### ISSUE THREAD

**Issue by Poorman65** [BiglySoftware/BiglyBT#2295]
* OS: Windows 10
* BiglyBT Version Number: 2.8.0.0

Is there a way to get BiglyBT to update its information from the torrent files? 

Not sure if this a standard practice, but the site where I get most of my torrents, uses the comment field to hold a link back to the torrents web page. They had server issues and no longer are using the same root address. I was able to do a bulk change to the addresses in the torrent files, but it appears that Bigly keeps the information internally. Is there an easy way to get Bigly to update from thousands of torrent files?

**Comment by parg** [comment]
BiglyBT keeps a copy of torrents in the "active" directory, they are named after the hash of the torrent with a ".dat" extension instead of ".torrent". If you want you can try updating those files (when BiglyBT is closed) but I'd make a backup first incase things go wrong.

**Comment by Poorman65** [comment]
This worked great! I had only been looking in the location where the torrents are moved to. I didn't realize that there was a .dat file in the AppData folder used by BiglyBT.
