### ISSUE TITLE
plugins_aercm_0.9.0.zip - Discover by... is missing

### ISSUE THREAD

**Issue by KonradKl** [BiglySoftware/BiglyBT#2297]
Options  like"Discover by..." disappeared in context menu of "Content Discovery".
This coincides with installation of plugins_aercm_0.9.0.zip.

Java 17 (64 bit)
  Oracle Corporation
c:\program files\java\jdk-17

SWT v4942r22, win32, zoom=100, dpi=96
Windows 8 v6.2, amd64 (64 bit)
B2.8.0.1_B36/4 az3

**Comment by parg** [comment]
Did you restart BiglyBT? If not then try closing the Swarm Discoveries view in the sidebar and then re-open it
