### ISSUE TITLE
"you downloaded..." popup disappeared so easily

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2301]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B2.8.0.0/4 az3

I saw this popup that said I downloaded so much, but then it disappeared so easily, I think, just from me pressing the down arrow.  I don't even know what it really said.

**Comment by parg** [comment]
Probably the donation popup, if it fails to load correctly for some reason then it auto-closes
