### ISSUE TITLE
Insists on installing MLab no matter what

### ISSUE THREAD

**Issue by Searinox** [BiglySoftware/BiglyBT#2305]
OS: Windows 10 2004 x64 Pro
BiglyBT Version: 2.4.0

From day one of installing BiglyBT over a year ago to this day on every launch BiglyBT attempts to install. "faster downloads", aka m-lab. It does this on every single startup. Despite showing up as installed - but not marked active - in the plugins page. I have removed it.

I have cleared out update.config. I have cleared out the subs directory. No matter what I do ever, BiglyBT insists on installing the plugin on every startup. I have disabled everything I could find remotely resembling updates or subscriptions for the program and its plugins. I've let it install it. It still goes on to install it again on the next startup, showing me the "faster downloads" "please wait while the speed test component is installed" popup, adding a torrent for plugins_mlab_0.5.zip, which never downloads.

It is uninstalled and not showing up in the installed plugins list. It is not present in program files\biglybt\plugins, it is not present in appdata\roaming\biglybt\plugins.

I do not want this plugin. I have no use for this plugin. How do I stop it from trying to install on every single startup? Where is this task saying that mlab has to be installed being fetched from?

**Comment by Seeings** [comment]
I saw your post now and have to say that I have a similar problem as you, it installed that plugin and others even though when I installed BiglyBT I only chose Mainline DHT as the only plugin that I wanted.

I created an Issue topic before noticing your post:
https://github.com/BiglySoftware/BiglyBT/issues/2329

**Comment by msdobrescu** [comment]
This is a typical malware activity, pushing stuff regardless the user's decision or without asking for permission.

**Comment by parg** [comment]
Uncheck the "load at startup" for the plugins that you don't want loading.

No, it isn't "typical malware activity", it is a component of BiglyBT. If you don't like it fork the source and create your own software.

**Comment by msdobrescu** [comment]
Sorry that I think it is, as long as I unload it, uninstall it and it keeps coming back despite that and to the fact that BiglyBT works without it.

**Comment by parg** [comment]
Here's the deal. I sit here pretty much every day developing my software, BiglyBT, for free. People are welcome to use it for free. People are welcome to come up with suggestions for improvements and report problems. What they are not welcome to do is some here with inflamatory comments such as accusing me of being a malware developer or distributor.
