### ISSUE TITLE
display issues, request for default behaviour

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2312]
Java 1.8.0_302 (64 bit)
  Temurin
/opt/openjdk-bin-8.302_p08/jre

SWT v4942r22, gtk/3.24.29, zoom=100, dpi=96
Linux v5.14.10-redcore, amd64 (64 bit)
B2.8.0.0/4 az3

I've selected in Options for all advanced options to show.  But when I download a magnet, it does not show up in my transfer list.  Only in the advanced list, which takes some searching to make show up.  I'd like magnet links to show permanently in the simple list.

Also, Biglybt is telling me it can't get some magnet links, and so then just deletes them.  This is unacceptable.  The default behaviour should be to keep those magnet links and search for them until I tell biglybt to stop.  It should never just delete them because it gave up trying to find them after only 10 minutes.  I'm using a live distribution.

Also, even though I expand the column for the size of the torrent, it still shows as 32.66... instead of showing the GB, even though it has lots of room.  This is in the simple list view only, not the advanced list view.

Also, when adding the torrent, the window that pops up with the list of all the files in the torrent, the networks, etc, the search box on the right-hand side needs to be expanded vertically, because it's cut off somewhat, only showing about 50% of what it needs to show.

**Comment by parg** [comment]
Change the timeout

Options->Plugins->Magnet URI Handler

The default has been changed to 0 (infinite) for a while now

**Comment by as-muncher** [comment]
Ah, thanks so much.  I'm not sure if the GB... thing not showing in simple view has been changed.  I've been using 2.8.0.0 and hopefully 2.9.0.0 will be released soon.
