### ISSUE TITLE
Windows 11 goes to sleep while BiglyBT downloading unattended

### ISSUE THREAD

**Issue by eurobank** [BiglySoftware/BiglyBT#2319]
Windows 11 Pro, BiglyBT latest stable version.

While having downloads in queue and apparently downloading, i find my pc in sleep mode (hibernation). 

Any ideas why? I recently switched to Windows 11, could that be the issue?

**Comment by parg** [comment]
Dunno, none of my machines are eligible for upgrade - screw Windows 11

**Comment by eurobank** [comment]
Not an issue of BiglyBT. 

Some recoding video software was set to switch Sleep to my PC, after finishing.
