### ISSUE TITLE
Add "Errored" to My Torrents

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2324]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B2.8.0.0/4 az3

Could you add an Errored category to the My Torrents section, please?  Thanks.

**Comment by parg** [comment]
There's an automatic Tag called "Error" - make it visible in the sidebar from Tags Overview

**Comment by as-muncher** [comment]
Thanks.
