### ISSUE TITLE
add ability to copy infohash from a torrent or magnet link

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2325]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B2.8.0.0/4 az3

I see that I can copy the magnet link for a torrent, but could I please be able to copy the infohash?  I've been transferring files over from qbittorrent, and qbittorrent saves a backup .torrent file for each torrent or magnet link with the infohash.torrent

**Comment by parg** [comment]
You can copy the hash from the General subtab

**Comment by as-muncher** [comment]
That's where it's hiding.  Thanks.
