### ISSUE TITLE
cannot download azplatform2 from web

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2327]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B2.8.0.0/4 az3

**Comment by parg** [comment]
azplatform2 is on https://plugins.biglybt.com/ under "BiglytBT platform-specific support"

**Comment by as-muncher** [comment]
Yes, it eventually installed, but I was getting that error.
