### ISSUE TITLE
Error: DNS SPI not loaded

### ISSUE THREAD

**Issue by csylvain** [BiglySoftware/BiglyBT#2330]
for many Beta revision updates lately, and without any particular configuration change on my part, the warning pop-up with messages "Failed to install DNS manager" and  "Error: DNS SPI not loaded" is presented upon every start up of BiglyBT.

presently, the system details are as follows:
Java 17 (64 bit)
  Private Build
/usr/lib/jvm/java-17-openjdk-amd64

SWT v4942r22, gtk/3.24.20, zoom=100, dpi=96
Linux v5.11.0-40-generic, amd64 (64 bit)
B2.8.0.1_B41/4 az3

**Comment by parg** [comment]
It is your Java version - they removed support for some stuff we use. Which is why Java 8 is recommended. Yes, I know it is old, but it is still receiving security patches. 

See https://github.com/BiglySoftware/BiglyBT/wiki/Java-Versions for a work-around.

**Comment by csylvain** [comment]
o i c
"In the future the BiglyBT launcher may be updated to do this" <-- it is time to do it now?

added (( --add-opens java.base/java.net=ALL-UNNAMED )) to java.vmoptions
see Startup & Shutdown -> Local JVM options file

all better for now

**Comment by Kopime** [comment]
Took me a few mins to figure out where exactly to add that line. Finally figured out you just add to after where you edit the Xmx 'heap memory size'. On my BiglyBT 3.2.0.0 its line 218 and looks like this: 

${JAVA_PROGRAM_DIR}java -Xmx256m --add-opens java.base/java.net=ALL-UNNAMED\
