### ISSUE TITLE
auto extraction of rar files after download

### ISSUE THREAD

**Issue by k9393** [BiglySoftware/BiglyBT#2335]
* OS and version = macOS 11.2.3
* BiglyBT Version Number = 2.9.0.0

Is it possible to auto extract rar files after the download?  If so, how?

Thanks

**Comment by parg** [comment]
The "Command Runner" plugin can do this as long as you can write a simple script:

https://github.com/BiglySoftware/BiglyBT-plugin-azexec

**Comment by o0nd7ots** [comment]
@TuxPaper Is this good enough to close this issue?
