### ISSUE TITLE
"Failed to install DNS Manager" message on startup

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#2340]
Since commit b8e6c3c37a291ba7ca2751b8983c42263ddb10b9, I seem to be getting a "Failed to install DNS manager" popup at every restart. My network is up and performing as expected, so I'm not sure what it's all about.

It's claiming... hang on, I'll grab a screenshot. Here:

![image](https://user-images.githubusercontent.com/538020/143362910-10411762-b998-4647-8f2d-d34719ad754f.png)

Every startup, same message. Doesn't appear to impact functionality.

## System block
Java 11.0.13 (64 bit)
  Red Hat, Inc.
/usr/lib/jvm/java-11-openjdk-11.0.13.0.8-1.fc34.x86_64

SWT v4942r22, gtk/3.24.30, zoom=100, dpi=96
Linux v5.14.17-201.fc34.x86_64, amd64 (64 bit)
B2.9.0.1_B04/4 az3

**Comment by ferdnyc** [comment]
Anticipating possible questions, I have:

1. Nothing set in Connection > DNS. The server I'm running on uses Google's DNS addresses in its `/etc/resolv.conf`
2. Nothing enabled in Connections > Proxy except for "Disable plugin proxies... when a SOCKS server is configured" (but one isn't).
3. No address bindings or notable checkmarks in Connection > Advanced Network Settings
4. Nothing in Connections > Transport Encryption
5. Connections > Pairing **is** enabled
6. LAN Peer Finder is loaded, activated, enabled, and "Automatically add loopback/link/site local networks..." is checked. (Though TBH I don't use it and only run one instance locally, under normal circumstances, so I'm not sure why I have it enabled.)

**Comment by ferdnyc** [comment]
<details>
<summary>Actually, here's a sanitized "Show configuration changes", up to the point where it starts listing downloads.</summary>
<pre><code>
Settings
    ASN Autocheck Performed Time=1188107206359
    Auto Adjust Transfer Defaults=0
    Auto Upload Speed Enabled=0
    Auto Upload Speed Version=3
    auto_remove_inactive_items=1
    AutoSpeed Choking Ping Millis=550
    AutoSpeed Latency Factor=40
    AutoSpeed Max Decrement KBs=6
    AutoSpeed Max Increment KBs=2
    AutoSpeed Max Upload KBs=96
    AutoSpeed Min Upload KBs=32
    Beta Programme Enabled=1
    Bias Upload Slack KBs=19
    br.backup.auto.enable=1
    br.backup.auto.everyhours=1
    br.backup.auto.retain=14
    br.restore.doplugins=0
    Check Bind IP On Start=0
    Close To Tray=0
    config.style.forceSIValues=0
    confirmationOnExit=1
    Default save path=XXXXXXXXXXXXXXXXXXXXXXX
    Default Start Torrents Stopped=1
    DefaultDir.AutoUpdate=0
    Delete Partial Files On Library Removal=1
    diskmanager.perf.cache.enable.read=1
    diskmanager.perf.cache.flushpieces=0
    diskmanager.perf.cache.notsmallerthan=2048
    diskmanager.perf.cache.size=32
    diskmanager.perf.read.maxmb=16
    diskmanager.perf.write.maxmb=8
    DNS Alt Servers=
    DNS Alt Servers SOCKS Enable=0
    Dual IPV4 IPV6 Connection Action=2
    Enable Sparse Files=1
    Enable System Tray=0
    File Max Open=320
    File.move.download.removed.enabled=1
    File.move.download.removed.move_partial=1
    File.move.download.removed.path=XXXXXXXXXXXXXXXXXXXXXXX
    File.save.peers.enable=0
    File.save.peers.max=20
    File.Torrent.AutoSkipMinSizeKB=5
    Graphics Update=2
    GUI Refresh=2000
    GUI_SWT_bFancyTab=0
    GUI_SWT_DisableAlertSliding=1
    IconBar.enabled=0
    IconBar.visible.play=0
    IconBar.visible.run=0
    Insufficient Space Download Restart Enable=1
    Insufficient Space Download Restart Period=60
    Ip Filter Autoload File=XXXXXXXXXXXXXXXXXXXXXXX
    Ip Filter Autoload Last Date=XXXXXXXXXXXXXXXXXXXXXXX
    Ip Filter Ban Block Limit=128
    Ip Filter Ban Discard Min KB=2048
    Ip Filter Ban Discard Ratio=15.0
    Ip Filter Clear On Reload=0
    LAN Speed Enabled=0
    Library.CatInSideBar=0
    Library.LaunchWebsiteInBrowser=0
    Library.showFancyMenu=0
    Library.ShowTabsInTorrentView=0
    Library.ShowTagButtons.CompOnly=1
    Library.ShowTagButtons.FiltersOnly=1
    Library.TagGroupsInSideBar=0
    list.dm.dblclick=1
    locale=en
    locale.set.complete.count=2030
    Logger.Enabled=1
    max active torrents=6
    Max Download Speed KBs=3218
    Max File Links Supported=1768
    Max Upload Speed KBs=85
    Max Upload Speed Seeding KBs=115
    Max Uploads=3
    Max Uploads Seeding=6
    Max.Peer.Connections.Per.Torrent=20
    Max.Peer.Connections.Per.Torrent.When.Seeding=4
    Max.Peer.Connections.Total=120
    Message Popup Autoclose in Seconds=8
    min downloads=3
    MyTorrents.SplitAt=3160
    NameColumn.showProgramIcon=0
    network.admin.maybe.vpn.enable=0
    network.bind.local.port=XXXXXXXXXXXXXXXXXXXXXXX
    network.max.simultaneous.connect.attempts=3
    network.tcp.max.connections.outstanding=5
    network.transport.encrypted.fallback.incoming=1
    network.transport.encrypted.fallback.outgoing=1
    Newly Seeding Torrents Get First Priority=0
    Non-Public Peer Extra Connections Per Torrent=10
    Non-Public Peer Extra Slots Per Torrent=3
    Pieces View Show Uploading=1
    Play Download Error File=<default>
    Play Download Finished File=<default>
    Play File Finished File=<default>
    Play Notification Added File=<default>
    Plugin.azintsimpleapi.apikey=XXXXXXXXXXXXXXXXXXXXXXX
    Plugin.azutp.utp.logging.enabled=1
    Plugin.azutp.utp.prefer_utp=0
    Plugin.default.pairing.enable=1
    Plugin.Magnet URI Handler.MagnetPlugin.rename.using.dn=1
    Plugin.Magnet URI Handler.MagnetPlugin.rename.using.dn.only.with.ext=1
    Plugin.Magnet URI Handler.MagnetPlugin.timeout.secs=200
    Plugin.Magnet URI Handler.MagnetPlugin.use.md.download.delay=10
    Plugin.rssfeed.AutoStartManual=0
    Plugin.rssfeed.KeepMax=100
    Plugin.rssfeed.KeepOld=7
    Plugin.rssfeed.RSSFeed.Config.netforce=1
    Plugin.rssfeed.RSSFeed.Config.netforce.Public=1
    Plugin.UPnP.upnp.alertdeviceproblems=1
    Plugin.UPnP.upnp.alertothermappings=1
    Plugin.UPnP.upnp.grabports=1
    Plugin.UPnP.upnp.ignorebaddevices=0
    Plugin.UPnP.upnp.refresh_on_bad_nat=1
    Plugin.xmwebui.Pairing Migrated=1
    Plugin.xmwebui.Port=XXXXXXXXXXXXXXXXXXXXXXX
    Plugin.xmwebui.Protocol=https
    Prioritize Most Completed Files=1
    Proxy.Check.On.Start=0
    Proxy.SOCKS.ShowIcon=0
    quick.view.maxkb=397
    Refresh When Inactive=1
    Rename Incomplete Files=1
    Rename Incomplete Files Extension=.part
    ReOrder Delay=0
    Save Resume Interval=3
    saveTo_list.max_entries=16
    Search View Is Web View=0
    Security.JAR.tools.dir=/usr/lib/jvm/java/lib/
    Set Completion Flag For Completed Downloads On Start=0
    Sharing Permit DHT=0
    Show Downloading In Side Bar=0
    Show New In Side Bar=0
    Show Options In Side Bar=1
    Show Status In Window Title=1
    Show Timestamp For Alerts=1
    Side Bar Close Position=1
    Side Bar Top Level Order=1, 2, 6, 3
    Sidebar.Plugin.SplitAt=7804
    SpeedLimitMonitor.setting.download.limit.conf=LOW
    SpeedLimitMonitor.setting.upload.limit.conf=LOW
    SpeedLimitMonitor.setting.upload.used.download.mode=70
    SpeedManagerAlgorithmProviderV2.intervals.between.adjust=5
    SpeedManagerAlgorithmProviderV2.setting.download.max.limit=4707072
    SpeedManagerAlgorithmProviderV2.setting.upload.max.limit=353536
    SpeedTest Completed=1
    StartStopManager_bIgnore0Peers=0
    StartStopManager_bNewSeedsMoveTop=0
    StartStopManager_bRetainForceStartWhenComplete=1
    StartStopManager_bStopOnceBandwidthMet=0
    StartStopManager_iFirstPriority_ignoreSPRatio=20
    StartStopManager_iFirstPriority_ShareRatio=1500
    StartStopManager_iIgnoreShareRatioSeedStart=50
    StartStopManager_iMaxActiveTorrentsWhenSeeding=6
    StartStopManager_iMaxStalledSeeding=0
    StartStopManager_iMinSpeedForActiveDL=49152
    StartStopManager_iMinSpeedForActiveSeeding=15360
    StartStopManager_iRankType=4
    Stats Dir=XXXXXXXXXXXXXXXXXXXXXXX
    Stats Graph Dividers=1
    Stats Period=60
    Stats Smoothing Secs=300
    Status Area Show IPF=1
    Status Area Show NAT=1
    Status Area Show SR=1
    Stop Ratio=2.0
    Subfolder for DND Files=.AZ_EXCLUDE
    subscriptions.auto.start.downloads=0
    Suppress File Move Dialog=1
    suppress_file_download_dialog=1
    Table.sort.intuitive=1
    tb.confirm.delete.content=2
    TCP.Listen.Port=XXXXXXXXXXXXXXXXXXXXXXX
    Tracker Client Closedown Timeout=30
    Tracker Client Concurrent Announce=40
    Tracker Client Connect Timeout=15
    Tracker Client Numwant Limit=0
    Tracker Client Read Timeout=35
    Tracker Client Scrape Stopped Enable=0
    Tracker Host Add Our Announce URLs=0
    Tracker Log Enable=1
    Tracker NAT Check Timeout=30
    Tracker Network Selection Default.I2P=0
    Tracker Network Selection Default.Tor=0
    Tracker Poll Interval Min=121
    Tracker Scrape Cache=5001
    Transfer Bar Show Icon Area=0
    UDP.Listen.Port=XXXXXXXXXXXXXXXXXXXXXXX
    UDP.NonData.Listen.Port=XXXXXXXXXXXXXXXXXXXXXXX
    unix.script.lastaskversion=3
    Up Rate Limits Include Protocol=1
    update.autodownload=0
    useCustomTab=0
    User Mode=2
    v3.topbar.height=176
    Watch Torrent Folder=1
    Watch Torrent Folder Interval Secs=30
    Watch Torrent Folder Path=XXXXXXXXXXXXXXXXXXXXXXX
    Watch Torrent Folder Path Count=7
    Watch Torrents Add Mode=1
    window.maximized=0
    window.rectangle=156,0,1127,1002
    Wizard Completed=1
    XferStats.show.samples=0
Plugins
    DorkBox-SystemTray Updater: 1.0
    Message Sync Support: 0.8.3
    uTP Plugin: 0.6.4
    UPnP Media Server: null
    Rating: 1.6.7
    Swarm Discoveries: 0.6.12
    Tor Helper Plugin: 1.2.4
    BiglyBT Web Remote: 1.0.6
    Location Provider: 0.3.1
    I2P Helper Plugin: 0.9.39.2.1
    Measurement Lab (M-Lab): 0.3
    Java Scripter Plugin: 0.3
    mlDHT: 2.6.2
    RSSFeed Scanner: 1.8
</code></pre>
</details>

**Comment by parg** [comment]
Whoa! Thanks

**Comment by ferdnyc** [comment]
Aha! The problem appears to be that `dns.test.client.vuze.com` is _not_ a valid address, while `dns.test.client.biglybt.com` **IS**. As is `bibble.frooble.biglybt.com`, and anything else I try. Leave it to AWS to default-configure their domain hosting to respond to all subdomain queries with an IP. :stuck_out_tongue_closed_eyes:

**Comment by ferdnyc** [comment]
You could probably use `test.example.com` — I'm pretty sure that one's guaranteed to be unresolvable. (Don't use `example.com`, though, it **DOES** resolve, to serve https://example.com/.)

**Comment by ferdnyc** [comment]
Hmm. In [rfc6761](https://www.rfc-editor.org/rfc/rfc6761.html) (the same place where `example.com` is reserved as a special domain name), it's documented that the entire `.test` TLD is reserved, and required to return negative results for all queries. So just `biglybt.test` might be another option.

**Comment by ferdnyc** [comment]
Fixed by 43e5bd54.
