### ISSUE TITLE
Biglybt crashes because of mshtml.dll

### ISSUE THREAD

**Issue by kotenok2000** [BiglySoftware/BiglyBT#2342]
* OS and version windows 11 [Version 10.0.22000.318]
* BiglyBT Version Number
* For *nix: Desktop Environment
Java 1.8.0_311 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_311

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.9.0.1_B04/4 az2
[hs_err_pid10456.log](https://github.com/BiglySoftware/BiglyBT/files/7605472/hs_err_pid10456.log)
[debug.zip](https://github.com/BiglySoftware/BiglyBT/files/7605473/debug.zip)

**Comment by parg** [comment]
This was when you were closing BiglyBT?

You have the following DLL loaded in process

C:\Program Files (x86)\0patch\Agent\0patchLoaderX64.dll

Not saying it is related but I'm always wary of code being injected and doing who-knows-what.

The crash associated with the UI library we use - SWT. You can try running with the (nearly) latest version to see if they have fixed any issues. Grab

https://www.eclipse.org/downloads/download.php?file=/eclipse/downloads/drops4/S-4.22RC1-202111171830/swt-4.22RC1-win32-win32-x86_64.zip

Open the .zip file and extract the "swt.jar" - replace the swt.jar in the BiglyBT installation directory with this (make a copy of the old one so you can put it back later)
