### ISSUE TITLE
more info about devices wanted to keep unauthorised out

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2344]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B2.9.0.0/4 az3

I see under Devices in the left hand panel, that there are at least 2 devices that I don't know what they're all about.  I see this CODA- and other numbers and letters after that, and then I see a DESKTOP- with some other numbers and letters, and BiglyBT says they're both offline right now.  Sure, it helps a little bit to see which operating system the DESKTOP- device is, but then how can it be offline if my computer is using BiglyBT right now?  What are these two devices that are offline?  People who have gained access to my system without me being aware of it?  IF so, I'm glad that BiglyBT will at least show those devices.  But how do I get rid of them, keep them from accessing my system, block them?  I don't access this computer remotely, so there should just be one device, and it should show that I'm online.  Help me out here, please.

**Comment by as-muncher** [comment]
I guess the devices are hardware devices that I attach to my system?  I'm not quite sure what the point of having that device list in BiglyBT is for, though.

**Comment by parg** [comment]
They are UPnP devices, they are on your network - BiglyBT can't do anything about blocking them, it is just listening for UPnP device broadcasts.
