### ISSUE TITLE
Tooltip from toolbar's stop torrent button is wrong

### ISSUE THREAD

**Issue by detelosk** [BiglySoftware/BiglyBT#2345]
When using separate buttons for the start and stop buttons of the toolbar, the tooltip for the stop one reads “Start selected torrent (s)”.

Steps to reproduce:

1. Start BiglyBT.
2. Enable the “Use separate start/stop buttons” setting from the Interface→Display section of the configuration options/preferences.
3. Hover over the stop button of the toolbar of a torrent view (e.g. the Library).

Expected result: It should read “Stop selected torrent (s)”.

Actual result: It reads “Start selected torrent (s)”.

Tested using:
* macOS 10.15.7
* BiglyBT 2.9.0.0
* Java 11.0.12, Homebrew OpenJDK build

**Comment by parg** [comment]
Already fixed in latest beta, thanks
