### ISSUE TITLE
spelling and grammar fix in Interface -> Tables

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2348]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B2.9.0.1_B09/4 az3

Change to "Override this for websites containing a website.  Open in browser"

**Comment by parg** [comment]
I don't think so

**Comment by as-muncher** [comment]
That's hilarious.  But really, you should change it.  Right now, it says "Override this for websites contain a website, open in browser."  That's confusing and it's not proper English.

**Comment by parg** [comment]
It doesn't say that. It says

    Override this for downloads contain a website and open in browser

Admittedly that needs the addition of a "that" or an "ing" but if I change a resource all other languages will require retranslation and I try and avoid that.

Your suggestion is ridiculous - "Override this for websites containing a website"

**Comment by as-muncher** [comment]
I didn't think the suggestion was ridiculous.  I mean, if code has an error, then you fix it, right?  Maybe some of the translations of English have already used proper grammar and spelling in that language.  Oh.... I didn't know that it was supposed to be "Override this for downloads THAT contain a website..." I didn't see that until you pointed it out.  I thought it was supposed to be "containing" not "contain".  Your code, your program, this was just a suggestion.

**Comment by parg** [comment]
hah! I just saw your "website containing a website" bit. How can a website contain another website? Surely it is then just one bigger website!

**Comment by as-muncher** [comment]
@parg - Yeah, you're right.  Thanks for pointing that out.  Whoops.  I meant "downloads containing a website".  Circuits crossed in the brain.
