### ISSUE TITLE
Add highlighting for different networks

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2349]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B2.9.0.1_B09/4 az3

I had this great idea last night, that if I am downloading torrents using other networks other than Public, that it would be very good to have those torrents highlighted in a certain way, whether for using one colour for I2P, or another colour for Tor, or a different colour for both networks.  It sure would be good to see something like that immediately, rather than finding out the hard way accidentally that you're downloading on a public network.

**Comment by parg** [comment]
You can do that with Tags. For example

hasNet( "I2P") && setColors( #00a0a0 )

**Comment by as-muncher** [comment]
@parg I was looking in the Options, and was expecting to see something under Color Scheme with regards to torrents that are using certain networks, but it's not there.  But thanks that there's an option to do it using tags.
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.0.0.1_B29/4 az3

**Comment by as-muncher** [comment]
Could you make BiglyBT, by default, to add a red highlighting of the torrent line, say, if it is using tor and/or i2p, but not the open web?  That way, it's easy for the user to see that something is only on private networks.  (hopefully private).  and not on the clear web by mistake.

**Comment by parg** [comment]
Use a Tag

https://github.com/BiglySoftware/BiglyBT/wiki/Tags#Change_downloads_row_color_when_it_contains_certain_file_types

You would need a constraint of `!hasNet( "Public" )`

as I said above....

**Comment by as-muncher** [comment]
Yes, I know you wrote that above.  But I was hoping for something that would be set by default to do this.  I tried reading through that page and found it hard to find the spot where it talked about where exactly to enter that javascript.  BiglyBT is feature-rich, yes.

**Comment by parg** [comment]
It isn't javascript, it is a Tag Constraint

![image](https://user-images.githubusercontent.com/395293/193395856-85f7598a-4910-4932-af3f-c3ef084a4044.png)

**Comment by as-muncher** [comment]
Where do you get -1 and #f0f0e0 from?

**Comment by parg** [comment]
from https://github.com/BiglySoftware/BiglyBT/wiki/Tags

setColors( foreground [,background] [,priority]) - Set downloads assigned to the Tag's row colors in Library views:
    colors are specified as #rrggbb or 0xrrggbb with rr, bb, gg in base 16. e.g. #ffffff = white, #ff0000 - red
    Use -1 for a color if you don't want to set it
    priority is used to resolve issues when more than one color applies to a row - the highest priority on will be selected.
    If you want a tag you can manually add/remove downloads from then set its constraint to the setColors you desire and then set its scope to 'removal only'
    NOTE. For the colors to be shown you MUST enable the 'Tag Colors' column in the Library view.
