### ISSUE TITLE
Changelog URL Broken (Help->Whats New -> https://plugins.biglybt.com/changelog.php)

### ISSUE THREAD

**Issue by dbareis** [BiglySoftware/BiglyBT#235]
The link is broken and in the current release goes to "https://plugins.biglybt.com/changelog.php?version=1.2.0.1_B31".

Is the "Release Notes" item also supposed to be updated it currently starts with:

`
BIGLYBT CHANGELOG
-----------------
   
2017.11.03 | BiglyBT 1.2.0.0
` 
Its possible this is only update on release but it may even be less work to update for the betas (youy must be keeping a separate list otherwise or trying to recollect all the changes after the fact).

**Comment by parg** [comment]
Thanks - I've done a quick fix by redirecting it to the changelog source. For beta users the sidebar entry that shows https://www.tumblr.com/blog/biglybt is currently the way to track updates.
