### ISSUE TITLE
Backup Error

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#2354]
Every time a backup runs, I get the same error. Always says the same file failed to copy.  Been going on for over a year. Tried deleting the listed file, in the hope that if was recreated that would fix it. But nothing works. Ideas?

![image](https://user-images.githubusercontent.com/37715552/144667126-46574c4d-ebca-485c-a1a3-a8c85a31acc9.png)

Here is what I get when I click the `View Details`.
 
![image](https://user-images.githubusercontent.com/37715552/144667249-4a42c15d-89b4-460a-96c8-9cf47f6e9862.png)

Java 1.8.0_311 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_311

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.9.0.1_B10/4 az3

**Comment by parg** [comment]
Do you have the "Chromium SWT Plugin" installed for some reason?

**Comment by NaPurHab** [comment]
![image](https://user-images.githubusercontent.com/37715552/144706655-fd76ca96-43c5-401f-807f-1372c6473078.png)

Yes

**Comment by parg** [comment]
And the reason? Does it work? The reason I ask is that that plugin is in a somewhat unknown state...

**Comment by NaPurHab** [comment]
I don't use Browsing much in BBT, So not sure if it works. Can't remember when or why I added it. But at the moment I have UnTicked it and will wait and see if the Backup Error continues.  If it stops, then we have a possible cause for the error.
