### ISSUE TITLE
Add checkmark to Do not Download or add Do Download

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2358]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B2.9.0.1_B10/4 az3

Ok, so sometimes, I'll see a file in a torrent that is fully available, yet bits and pieces of other files are being downloaded, which are not yet complete.  Sometimes, I've had to just ctrl-a to select every file in that torrent, then set priority to Do Not Download so that I can at least get one complete file right away.  However, when it full downloads, there's no Un-(Do Not Download).  I now have to choose a priority, like "Normal" for everything that I selected, and I lose all the original priorities that I had for the files.  All those boxes were unchecked, but now I just want to re-checkmark them again.  So, maybe there can be an Un-(Do Not Download), or a Download option or something like that?  Thanks.

**Comment by parg** [comment]
How about setting the file that you want to a very high priority? Or perhaps try making the file sequential download as well? Assuming there is good availability across the files then that should give the file you want priority.

**Comment by as-muncher** [comment]
@parg, Yes, I have done that.  I have chosen one file that has full availability to a priority of High (5), higher than other priorities.  But I've seen it where the file is available, with a priority High (5) and BiglyBT still downloads pieces from here and there.  Sometimes I wonder if the settings in Options are taking priority over the settings that I personally set, such as High (5) or whatever else.  I have BiglyBT set to try to download files with fewer pieces first.  And then even sometimes that doesn't work.  For instance, I have had a number of files in my torrent close to completion with just a few pieces left to download, and they have full availability, and yet BiglyBT is busy downloading part of other files in my torrent, so to force it to at least finish those files, I've had to uncheckmark all the other files in that torrent, and that works.

**Comment by parg** [comment]
You can hover over a piece in the piece map view to see its priority. Bittorrent is supposed to be a "rarest piece first" algorithm. Whilst various priority hints can be supplied (file priority, first/last piece etc) the rarest aspect still remains buried in the priorities. 

Also generally blocks of pieces won't be re-requested from secondary peers. So you can end up with pieces completing slowly if requests are allocated to slow peers.
