### ISSUE TITLE
BBT freezes when opening 'filters' tab in preferences (beachball)

### ISSUE THREAD

**Issue by Sagmegar** [BiglySoftware/BiglyBT#2361]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
/Applications/BiglyBT/.install4j/jre.bundle/Contents/Home/jre

SWT v4942r22, cocoa, zoom=100, dpi=72
Mac OS X v10.13.6, x86_64 (64 bit)
B2.9.0.0/4 az2

**Comment by ferdnyc** [comment]
@Sagmegar You're referring to Options > IP Filters, correct?

Normally filtering is disabled and there are no predefined filters in the list, in which case that view should come up pretty much instantly.

Did you previously configure any IP filters? Are they autoloaded from a local file? From a URL?

I have a rather large filter set (hundreds of blocks), and it takes a few seconds for "IP Filters" to come up each time, just from the work of populating the list — but it does eventually come up. The filters are downloaded from a remote URL as a GZipped file, updated weekly.

If the URL were inaccessible and it was timing out attempting to load the remote list, though, that's one possibility for why it might hang for longer. A much bigger filter list is another possibility. (Having both IPv4 and IPv6 lists would also complicate things further.)

**Comment by Sagmegar** [comment]
Hi,

Yes, I had a list (URL) in Vuze I deactivated some months ago, before I switched over to BBT. It shouldn’t be loaded or cause BBT to hang.

Since I switched I’ve had two other problems (corresponding issues created on GH):
- opening magnet links from FF only works once;
- when I order MacOS to shutdown the computer BBT doesn’t terminate (manual quit required).

**Comment by ferdnyc** [comment]
> - opening magnet links from FF only works once; - when I order MacOS to shutdown the computer BBT doesn’t terminate (manual quit required).

Hm. I wonder if those could be related? I'm not sure how magnet link handling is provided on macOS (it's different in each OS), but if whatever is opening the link in the existing BiglyBT instance doesn't properly exit afterwards, then it could both interfere with attempts to open additional links, _and_ with shutdowns.

Do you still have shutdown problems if the running instance _hasn't_ been used to open any URLs from Firefox, not even once?

> Yes, I had a list (URL) in Vuze I deactivated some months ago, before I switched over to BBT. It shouldn’t be loaded or cause BBT to hang.

Well, agreed — _nothing_ "should" cause BiglyBT to hang. But something is, so we're clearly in uncharted territory. But what I was trying to get at is, there _were_ previous filter configs. It would be worse (and harder to troubleshoot) if that view were hanging when you'd never configured filters at all.

Here's one thing you could try doing: Terminate all running BiglyBT instances, then go to your settings directory (which I guess is just `~/.biglybt/` even on macOS, probably?) and _delete_ (or rename) any `ipfilter.*` files in there. If you deleted the filter URL, it shouldn't need them anymore. And even if it does, they're just scratch files that will be recreated at the next launch.

It's possible there may be some old/bad data in there, that's causing hangs when you try to open Options > IP Filters.

**Comment by Sagmegar** [comment]
Since I deleted the old IPF files everything has gone back to normal.

**Comment by ferdnyc** [comment]
@parg Sounds like this one can be closed.
