### ISSUE TITLE
Dark Mode color palette issue: (some) hyperlinks

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#2362]
One issue remaining with "dark mode" is that some hyperlinks are still colored in the standard dark blue, which is way too dark against the gray background of dark mode. But weirdly, it's only some of them.

For example, in Options / Startup & Shutdown, the link in Java Options is shaded properly for the dark palette:

![image](https://user-images.githubusercontent.com/538020/145057332-3604b973-d289-4f9a-aaf9-56d0b924440c.png)

But the "Help" link at the bottom of the Options view isn't:

![image](https://user-images.githubusercontent.com/538020/145057432-92eee004-4a3f-499b-87a8-582652c03ebb.png)

The links in Torrent Details > General for both the Hash value and "User Comment:" are also mis-shaded:

![image](https://user-images.githubusercontent.com/538020/145057590-498c8e90-54dc-45fb-9859-0b3bda165037.png)

As is the "Tracker URL:" link in the Sources tab.

This isn't an exhaustive list (I can try to compile one, but there are a lot of places to look through), just a general note that some links aren't displayed with the correctly-themed text color.

### System block

> Java 11.0.13 (64 bit)
>   Red Hat, Inc.
> /usr/lib/jvm/java-11-openjdk-11.0.13.0.8-2.fc35.x86_64
> 
> SWT v4942r22, gtk/3.24.30, zoom=100, dpi=96
> Linux v5.15.4-201.fc35.x86_64, amd64 (64 bit)
> B2.9.0.1_B11/4 az3
>

**Comment by ferdnyc** [comment]
Oh, add all of the links in the About window, as well:

![image](https://user-images.githubusercontent.com/538020/145058504-95c2ab31-2d92-4cdf-b16d-05d18e50fa3b.png)

**Comment by parg** [comment]
I'll take a look, ta

**Comment by parg** [comment]
B12 has a few fixes, tell me if you spot any more

**Comment by ferdnyc** [comment]
@parg WOW that was quick! I updated to B12 just as a matter of course, and didn't even check what it contained — suddenly I was seeing right-colored links, going, "Was I _wrong_? Had I forgotten to apply some setting before..?" :rofl: Then I finally realized that, no, the bug I reported was already fixed. Service! :+1: 

 I don't see any more examples currently, but I'll keep an eye out. Thanks!

**Comment by parg** [comment]
I've done quite a lot of twatting around with dark mode in B15 - still a work in progress but feedback always good!
