### ISSUE TITLE
Encryption Key Access Popup repeatedly coming up. "Friend Online Status"   I did not set this up.

### ISSUE THREAD

**Issue by Dragonsi2** [BiglySoftware/BiglyBT#2364]
![Encryption Key Access Popup 12-09-21](https://user-images.githubusercontent.com/71967021/145491280-4b67d4be-d239-4f13-8b87-8e58ada1a227.jpg)

This morning, when I booted it up, it downloaded "plugins_azneti2phelper-win32_1.6.1.1.1.zip, and asked me if I wanted to restart, but I said No, and I would do it later on, I was in no hurry, since I go to bed in the mornings.

I went to sleep, woke up, and now see this over and over: Encryption Access Key, Friend Online Status. I cancelled it out, but now it pops up literally every few seconds. I did not enable this and never saw this in the past year & 1/2 since I started using this during quarantine. I was able to go to Options/Security & Copy my own Access Key and pasted it in here, thinking that is what it is asking for, but nope??

**Comment by parg** [comment]
Hmm, that's a feature that doesn't normally see the light of day, for some reason your configuration has decided it should.

Under Options->Security there is a "public/private keys" section. Back in the days when the product had a centrally managed (optional) credentials system users would have login details - these were also used to secure the private key that BiglyBT uses to secure your "friends" connections to other users.

When the central system was removed it was pretty obvious that your average user didn't want the hassle of "logging on" to BiglyBT when starting it so the password protection was removed. It has always been possible to turn it back on by the "reset" button there. What you need to do is hit "reset", hit "OK" to the warning message and then change "password persistence" to "forever" and hit OK (you can leave the password as blank)

This will generate you a new public/private key pair and change your "friend" identity, but if you're not using the friends feature this won't affect you.

**Comment by Havokdan** [comment]
That's what happened to me too ...
