### ISSUE TITLE
make this BiglyBT issues page omit is:open by default

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2365]
I know I usually have to delete the is:open if I want to search this page to see if maybe others have had the same issue I'm having, because if it was closed, then at least I can see possibly a solution.   I guess, though, on the downside, people including myself might not know that there is such an option, such as is:open or is:closed

**Comment by ferdnyc** [comment]
There is no way for a project to do that. You'd have to take it up [with Github](https://support.github.com/?tags=dotcom-footer).

**Comment by as-muncher** [comment]
@ferdnyc  Do you know which one of Github's projects deals with its web pages?  Thanks for the link,

**Comment by ferdnyc** [comment]
@as-muncher 
The GitHub UI isn't open source, I'm afraid. Any issue tracking or source code management is all internal/private.

**Comment by ferdnyc** [comment]
They do have a discussion category for issues feedback at: https://github.com/github/feedback/discussions/categories/issues-feedback

Not really sure whether that covers the existing Issues, or only their new-and-improved beta.
