### ISSUE TITLE
Make priority "Delete" to move files to Recyle Bin

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2366]
2.9.0.1 beta 15 on windows x64 21h2

One wrong choice of priority, and there deletes your files in your torrent.  One whoops.  What do you think about sending it to the recycle bin instead?  I'm sure there would be good and bad with that.

**Comment by as-muncher** [comment]
Ah, thanks.  Perhaps there can be an option later to choose to option or permanently delete.  But thank you for the addition.

**Comment by as-muncher** [comment]
When the files are moved to the recycle bin, though, the files are mangled. There's really nothing worth salvaging, except maybe some end pieces, under 10kB in size.  I know I recently did a search for existing data files, internal link, to an external hard drive, and then I selected the files and "delete" and they all ended up gone, just garbage files in the recycle bin, couldn't restore them.

**Comment by parg** [comment]
That's right - you delete incomplete files you end up with incomplete files

**Comment by as-muncher** [comment]
No, complete files get deleted as incomplete files.
