### ISSUE TITLE
2.9 and Autopilot

### ISSUE THREAD

**Issue by eurobank** [BiglySoftware/BiglyBT#2369]
Sometimes Autopilot plugin removes the finished torrent and BiglyBT doesn't RECHECK the file (while enabled in settings to recheck finished torrents).

Apparently if some setting of Autopilot comes to a limit and removes it, this happens before BiglyBT does the recheck.

**Comment by parg** [comment]
You saying this is something specific to 2.9? Perhaps you should try and rework whatever it is you're doing with Autopilot to use Tags - I don't particularly want to support Autopilot.

**Comment by eurobank** [comment]
Understood.
Specific to 2.9? I have no idea, 2.9 is what i use right now.
