### ISSUE TITLE
Too many to list

### ISSUE THREAD

**Issue by shapeshifter910** [BiglySoftware/BiglyBT#2371]
Slackware 14.2
BiglyBT 2.9

Magnet pasted or file open actions don't do anything.
I have to download torrents first with some other method, then drag and drop onto BiglyBT, then it finally starts the torrent.
Toolbar has all blank buttons
I have to use tool tips to tell what is what.

The fact that most all software works fine on Slackware 14.2 but BiglyBT has these huge fault, tells me that something is seriously wrong with the way it was developed.
I've seen apps on Windows that work fine from Windows XP all the way up to Windows 10 and similarly I've seen apps on Linux that work across many versions and distros without problems.
Azureus never gave me any issues for example.
So why can't you accomplish same?
Pick a highly compatible toolkit and have at it FFS! Just about everybody has managed that so why can't you?
Can you tell I'm frustrated?!
If this shit is not fixed in next version, I'm dumping BiglyBT for good.

**Comment by parg** [comment]
Fuck off then

**Comment by parg** [comment]
(or perhaps try the latest beta first)
