### ISSUE TITLE
Magnet links added early end up corrupted

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2372]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B2.9.0.1_B15/4 az3

When starting up BiglyBT, you just see Dashboard, and maybe Library, and that's it while everything's loading up.  When you add magnet links at this stage, before everything's really started up, when the metadata download windows come up, the magnet links are corrupted.

**Comment by parg** [comment]
"corrupted" meaning?

**Comment by parg** [comment]
Ah, I can see that they don't get processed correctly - I'll add a fix in bext beta (B19(

**Comment by as-muncher** [comment]
Many thanks.
