### ISSUE TITLE
"Illegal reflective access" warning

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#2378]
I recently had BiglyBT crash and dump core on me, this was the contents of the VNC server's console log at the time of the crash. I'm not _sure_ the warning is related to the crash, but I figure it's worth reporting anyway. (Especially since the message asked so nicely!)

> WARNING: Illegal reflective access by com.biglybt.core.util.spi.AENameServiceJava9 (file:/[PATH]/BiglyBT.jar) to field java.net.InetAddress.impl
> WARNING: Please consider reporting this to the maintainers of com.biglybt.core.util.spi.AENameServiceJava9
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> No shutdown tasks to do
> BiglyBT TERMINATED.
> 

### System block
Java 11.0.13 (64 bit)
  Red Hat, Inc.
/usr/lib/jvm/java-11-openjdk-11.0.13.0.8-2.fc35.x86_64

SWT v4942r22, gtk/3.24.30, zoom=100, dpi=96
Linux v5.15.6-200.fc35.x86_64, amd64 (64 bit)
B2.9.0.1_B19/4 az3

**Comment by parg** [comment]
That warning isn't related to the crash, it is just the JVM developers bitching about something that used to be permitted and they decided to prohibit (the warning can be removed by following the instructions in https://github.com/BiglySoftware/BiglyBT/wiki/Java-Versions)

**Comment by ferdnyc** [comment]
@parg Aha! Thanks.

Hmm. That page got me wondering, though.

> BiglyBT uses its own 'DNS Service Provider' proxy to prevent the attempted resolution of I2P and Tor addresses via DNS

...Which makes sense. But, I'm sure I'm not the only user who _doesn't use_ I2P or Tor at all — in fact, I don't even have those plugins installed. In which case, it sounds like BiglyBT's DNS Service Provider is entirely unnecessary, really. No?

Given that it seems to rely on black-magic hackery [ :wink: ], do you think it would be a worthwhile undertaking (were someone to get ambitious) to make it optional functionality? Either by extracting it into its own plugin (that's required by the I2P and Tor helpers), or letting it stay in the core, but with a switch to control its activation? (Could be a user-facing one that's required to be enabled when I2P or Tor is in use, or a hidden one that's automatically enabled when either/both of the helper plugins is loaded.)

Or is it so deeply integrated into the code, that any such foolhardy aspirations will only end in tears?

**Comment by parg** [comment]
It intercepts attempts to resolve .i2p addresses, prevents them from hitting the "real" DNS system and leaking the fact that you are  using an i2p address. It also prompts to install the I2P plugin if you hit a .i2p address and it is not yet installed. So it can't be part of the I2P plugin itself...

**Comment by parg** [comment]
oh, and it also does some stuff preventing local resolution of tracker host names when using a SOCKS proxy and forces remote host name resolution.

**Comment by ferdnyc** [comment]
Busy code! :grin:
