### ISSUE TITLE
Dark palette issue: Console messages

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#2382]
In Dark mode, the console text is changed from black to white. That works well enough for the Information level, where the blue background is darkened to match:

![image](https://user-images.githubusercontent.com/538020/147016068-9e9eacd9-98ae-4515-9617-a4f44d999874.png)

And it works acceptably for the Warning level:

![image](https://user-images.githubusercontent.com/538020/147016102-e665c126-49de-4364-a0ec-db77e048e2de.png)

But not at all for the Error level, where the background is far too light:

![image](https://user-images.githubusercontent.com/538020/147016154-fd1a3bbc-c028-4876-89d6-daa6adf480b2.png)

For fixes, two ideas come to mind:

1. Use luminance-based thresholding to select the appropriate text color (black or white) for a given background color, same as in the tag canvas.
2. Also use the configured (or default) Warning and Error colors (from Options > Interface > Color Scheme) to set the background color for those console levels. The default colors are dark enough that white text should be visible on both:
    ![image](https://user-images.githubusercontent.com/538020/147016574-da0fcdf1-c007-4df3-bb60-69458fa11997.png)

#### System block
Java 11.0.13 (64 bit)
  Red Hat, Inc.
/usr/lib/jvm/java-11-openjdk-11.0.13.0.8-2.fc35.x86_64

SWT v4942r22, gtk/3.24.30, zoom=100, dpi=96
Linux v5.15.8-200.fc35.x86_64, amd64 (64 bit)
B2.9.0.1_B19/4 az3

**Comment by parg** [comment]
Thanks!

**Comment by ferdnyc** [comment]
Looks good as of _B20! :+1:
