### ISSUE TITLE
Acronis active protection reporting 'ransomeware injection detected' in I2P Helper plugin state files

### ISSUE THREAD

**Issue by THEKINGSTAR** [BiglySoftware/BiglyBT#2385]
* OS and version  WINDOWS 11
* BiglyBT Version Number LATEST
* For *nix: Desktop Environment 
![InkedScreenshot 2021-12-24 082958](https://user-images.githubusercontent.com/25788408/147325626-282432e7-927d-413b-b74d-21df369e0d9e.jpg)

![InkedScreenshot 2021-12-24 083020](https://user-images.githubusercontent.com/25788408/147325615-cdf54db6-1b47-443f-8669-40cadce9bd0c.jpg)

BIGLYBT KEPT FREEZING THE WINDOWS UPON EXITING IT, I uninstalled it and reinstalled a new fresh copy and this is the message I get from Acronis backup utility , and the anti-virus is Kaspersky 

 this problem is the anti-virus didn't catch it,
the   HDD backup software did catch it !!!!!!

**Comment by parg** [comment]
Those .dat files are record of peers in the I2P network database - who knows what Acronis is moaning about. They contain cryptographic information (keys etc) that are effectively radom byte sequences, perhaps they happen to match something the AV is looking for.

**Comment by THEKINGSTAR** [comment]
So, we don't torrent anymore!?
 if this is a companies action in response to pirating, I wouldn't be surprised🥲
