### ISSUE TITLE
Expand/collapse torrent arrows missing

### ISSUE THREAD

**Issue by cwaynedavis1946** [BiglySoftware/BiglyBT#2386]
Recently the expand/collapse arrows in the name column disappeared.  A workaround is to right click Show Details-Files but I highly preferred the arrows.  I have BiglyBT on 2 PCs.  PC1 still has the arrows, PC2 doesn't.  See `screenshots.

![PC1 BBT arrows](https://user-images.githubusercontent.com/45526946/147364124-180d7537-40ca-4e8e-b35a-8cd2d162ed2a.jpg)
![PC2 BBT no arrows](https://user-images.githubusercontent.com/45526946/147364148-4cc1c2ce-fbf1-43a1-a847-37d30e75f3f2.jpg)

I exported column setup from PC1 to PC2, arrows did not appear.  Reset PC2 column setup, added back what I wanted but no arrows.  Can't figure it out.  BiglyBT on both PCs reports up to date.

About System shows different Java versions, tried to update Java on PC2 but Java reports up to date.
Last line of About System shows az3 vs. az2 but have no idea what that means.

PC1:
Java 1.8.0_311 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_311

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.9.0.0/4 az3

PC2:
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.9.0.0/4 az2
`
I'm sure this is something simple but I can't find it.

**Comment by parg** [comment]
The one without the arrows is in "classic UI" mode - this UI doesn't show them.

Options->Interface->Start: Display BiglyBT UI Chooser
