### ISSUE TITLE
Ip bind changes after lxc container install

### ISSUE THREAD

**Issue by bluboyo** [BiglySoftware/BiglyBT#2387]
Java 11.0.13 (64 bit)
  Ubuntu
/usr/lib/jvm/java-11-openjdk-amd64

SWT v4942r22, gtk/3.24.20, zoom=100, dpi=96
Linux v5.11.0-43-generic, amd64 (64 bit)
B2.9.0.0/4 az3
* OS and version Ubuntu 20.04
* BiglyBT Version Number 2.9.0.0.
* For *nix: Desktop Environment

I have problem that bigly wont stay on the nic bind. Never had this problem before. It only affects Bigly, no other apps.
I bind a nic and after i installed lxd it changes to the lxc containers nic. If i change back it takes about 1-2 min then its back to the lxc nic. Tested with qbit and i dosent affect qbit. Only way i get bigly to work again is to delete the lxc instance and bridge.

**Comment by parg** [comment]
You explicitly bind BiglyBT via 

Options->Connection->Advanced Network Settings: Bind to local IP address or interface

and that magically changes you say?

**Comment by faltaren** [comment]
Exactly. Ive tried both nic and ip. Still changes. Like magic...

**Comment by parg** [comment]
Options->Connection->Advanced Network Settings: Automatically try and detect the presence of VPNs and prompt to configure their binding  ?

**Comment by faltaren** [comment]
Noop that is not checked. I also tried to uncheck Check bind ip on startup and enforce ip bindings. They get checked when the change happens. Ive left the settings open and i see when it happens. If i save and close it still happens.

**Comment by faltaren** [comment]
Install lxd and set a bridge. I bet it happens.

**Comment by faltaren** [comment]
Update: Added a second fysical nic. Same happens. Bigly wants the new nic for some reason and the bind wont stick.

**Comment by faltaren** [comment]
The pluggin vpn helper may be the problem. It autobinds?
