### ISSUE TITLE
just updated how to stop bigly from opening chromium?

### ISSUE THREAD

**Issue by mefink86** [BiglySoftware/BiglyBT#2388]
Hi how do i stop biglybt from opening the annoying chromium webtorrent tab? I do not want this on my computer period! I hate your stupid update I will cease support of biglybt permanently if you keep forcing this on us. Please tell me how i can block this stupid chromium from opening I do not use chromium and hate chromium and you had zero right to force this onto my laptop against my consent! I will file lawsuit if not fixed

**Comment by mefink86** [comment]
Your app is opening things i never agreed to allow to be opened that is not okay

**Comment by mefink86** [comment]
How do i stop the stupid thing from opening webtorrent in chromium? I swear you all have become severely ignorant and rude and think its okay to force use of 3rd party apps programs without our consent. That is illegal period give us a way to disable this or your breaching our rights plain and simple

**Comment by mefink86** [comment]
Can we get help from someone at BiglyBt whom is not a rude belittling asshole like parg is?

**Comment by mefink86** [comment]
oh and Parg you have been officially reported you constantly rude belittlung users who want things fixed. seems BiglyBt does not hire professionals just ignorant rude jerks

**Comment by parg** [comment]
hahaha

**Comment by parg** [comment]
Let's recap shall we? You install some free software. You don't pay for it. Some other people spend many years developing it for free. Then you come along and post an issue with the following in your opening quest for support:

"annoying chromium"
"don't want it on my computer period"
"hate your stupid update"
"cease support of biglybt permanently"
"forcing this on us"
"stupid chromium"
"you had zero right to force this"
"against my consent"
"I will file lawsuit"

YOU agreed to install the webtorrent support plugin. YOU were prompted if you wanted to install it. YOU said yes. YOU clearly don't understand what the plugin is and how it works.

Please, uninstall BiglyBT and go and find some simple software that works at a level that you can understand.

**Comment by mefink86** [comment]
i never agreed to any invasive webtorrent nah. you all forced us to update
instead of using older version i used for awhile! i never even agreed to
the update biglybt forced the update even after I had repeatedly declined
abd said no. i have filed formal charges with police for this unlawful
forced action. i gave you a chance to rectify your criminal actions but you
chose to be an asshole so now you can go to fucking jail and rot and my new
life goal is to not rest til u are in prison you are a total scumbag. ps i
never downloaded it from github! i actually use the actual straight from
Biglybt's official website version. so you're assumptions are full of shit
and wrong! you're a stuck up ignorant bigoted asshat! hope u piss off and
pull this Karen tude on someone far less nice than I Been one day! maybe
when u piss off someone less nice and get shot you'll learn being an
asshole has consequences
