### ISSUE TITLE
BiglyBT reporting false stats to private tracker

### ISSUE THREAD

**Issue by ghost** [BiglySoftware/BiglyBT#2390]
* OS and version: Windows 10
* BiglyBT Version Number: 2.9.0.1_B20
* For *nix: Desktop Environment: N/A

BiglyBT is reporting false download/upload statistics to the private tracker.

Examples:
BiglyBT's side
![BiglyBT_ZjwnydTQaY](https://user-images.githubusercontent.com/86971938/147661967-b18aa9ec-eceb-4498-b4a3-0f5f4b2fcb41.png)
 
Private Tracker side 
![8ZdE71ZZWz](https://user-images.githubusercontent.com/86971938/147662021-f0481e57-6bc9-430a-850b-6ad3a126463d.png)

As you can see, the tracker displays the down/up stats as higher than the size of the torrent and uploaded on BiglyBT itself so it is obvious that false stats are being reported.

**Comment by parg** [comment]
You can turn on tracker logging in the "All Tracker" view - right-click on the tracker and select "enable tracker logging". All interactions with the tracker will be logged to a file that you can access via the same right-click menu.

In the "Sources" tab you can enable "reported sent" and "reported received" columns to see download specific stats.

BiglyBT does not report false stats.

**Comment by realseb1g** [comment]
Hmmm, weird as the tracker is seeing more than BiglyBT shows.

**Comment by parg** [comment]
Obviously something is weird, maybe BiglyBT lost its local record of the stats.

**Comment by parg** [comment]
Anyway, like I said, if you think something is wrong then turn on the tracker logging. Lots of people use BiglyBT on private trackers without any issues.

The fact that your BiglyBT view shows "downloaded" as 0 bytes indicates you have some local stats issues.

**Comment by realseb1g** [comment]
I'll check out tracker logging, however the downloaded stat on BiglyBT isn't technically wrong as the torrent was created in the same instance of BiglyBT and i have the files already

**Comment by as-muncher** [comment]
I've noticed something like this, when I do a search for existing data files for torrents.  BiglyBT will show that I have uploaded something like the full size of my torrent, when that was impossible.

**Comment by parg** [comment]
The share ratio is set to that - the assumption being that if you have the file on your hard drive then you downloaded it at some point (and are trying to recover the download)

The information isn't reported to the tracker though - only data actually downloaded while the download is running is reported to the  tracker.

**Comment by parg** [comment]
sorry, that was a crap answer - I was talking about the amount downloaded not uploaded.

Anyway, the second part holds regarding reporting to trackers.
