### ISSUE TITLE
One more dark-mode hyperlink styling bug

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#2392]
Spotted one more example of bad hyperlink styling, in the "Check for Updates Results" dialog:

![Screenshot from 2021-12-30 02-37-11](https://user-images.githubusercontent.com/538020/147733246-030164ca-939c-45a9-bb85-7cd040ce2a42.png)

## System block
Java 11.0.13 (64 bit)
  Red Hat, Inc.
/usr/lib/jvm/java-11-openjdk-11.0.13.0.8-2.fc35.x86_64

SWT v4942r22, gtk/3.24.31, zoom=100, dpi=96
Linux v5.15.11-200.fc35.x86_64, amd64 (64 bit)
B2.9.0.1_B20/4 az3

**Comment by parg** [comment]
Thanks!

**Comment by ferdnyc** [comment]
Fixt in B21! :+1:
