### ISSUE TITLE
Cosmetic Issue: Piece Map, showing Half Pieces.

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#2394]
![image](https://user-images.githubusercontent.com/37715552/147891274-359813e8-50a5-403c-ac80-9f9db342d1c8.png)
![image](https://user-images.githubusercontent.com/37715552/147891713-77c45f2f-61bb-427d-9e92-62f9d8875783.png)

Notice the right side of the Piece Map, it is showing half peices. Seems a small display issue. Just thought you'd like to know. Probably should be White Space if it can not display a full piece. In the 2nd image the Dark Strip is my Desktop Background.

View is Tag:Downloading, with the Tabs from the bottom expanded to the Piece Map.

Java 1.8.0_311 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_311

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.9.0.1_B21/4 az3

**Comment by parg** [comment]
Hmm, tempermental view that - try resizing the window slightly, it already makes quite an effort to keep the pieces whole.

**Comment by NaPurHab** [comment]
I would but the main BBT window is sized to fit a FancyZone (MS Powertoys). Only wiggle roon is to resize the side bar. That just creates larger or smaller slices of the blocks.

My monitor setup is dual, portrait mode. 2 zones on the Left Monitor (Upper/Lower),  and on the Right 6 zones (3 across the top, 1 Large for BBT in the Middle, and 2 at the bottom in a 60/40 width).

Anyway, just reporting it. If you're not inclined to deal with it now. Add it to your To Do list.
It is annoying to see, but doesn't break anything. So no rush.

**Comment by parg** [comment]
It is something to do with the way PowerToys enforces the window size - the piece map component stops getting resize events and therefore doesn't update as required. Couldn't find a way to fix it. If you switch to another subtab and back it seems to start working.

**Comment by parg** [comment]
Actually it is caused by the label at the top of the view, might be fixed next beta.
