### ISSUE TITLE
MPC

### ISSUE THREAD

**Issue by MuhammetEminCakir** [BiglySoftware/BiglyBT#2396]
* OS and version: Win 11 21H1
* BiglyBT Version Number: 2.9.0.0
* For *nix: Desktop Environment

Add support for MPC-HC and MPC-BE like VLC.

**Comment by parg** [comment]
"MPC-HC is not under development since 2017. Please switch to something else."

**Comment by MuhammetEminCakir** [comment]
https://github.com/clsid2/mpc-hc/releases/

**Comment by parg** [comment]
Anyway, unless there's some simple Java api for controlling it (ala https://github.com/caprica/vlcj) then it isn't going to happen.
