### ISSUE TITLE
Subscriptions screen freezing

### ISSUE THREAD

**Issue by hglecke** [BiglySoftware/BiglyBT#2397]
Subscriptions screen freezing.

Win 10 Pro v21H1 (64bit)
OS Build 19043.1415
BiglyBT v2.9.0.1_B22/4
(Applies to earlier BiglyBT releases as well)

After prolonged activities with a substantial subscriptions list, the screen fails to populate.
A message informs of "a GUI error, more messages may be displayed."
Switching to the library screen at this point usually works normally, data transfers continue OK as indicated on the bottom of the screen.
If closing and re-loading BiglyBT at this point usually works OK. After the re-load screens display normally.
If operations are continued without re-loading, all screen interactions fail eventually, a forced shutdown of BiglyBT with CTRL-Alt-Del is required.
My un-educated guess is that BiglyBT runs out of display resources. Operating system functions, such as file explorer, are not effected by the BiglyBT screen locks.

Questions:
What and where are settings in BiglyBT to allocate more resources?
Can the error messages be enhanced with selectable links to the appropriated settings?
Can suggested actions be displayed as choices to implement the required changes? 
Can a lock-out of BiglyBT be prevented, even if resources are about to be depleted?

Thank you for your continued efforts.

**Comment by parg** [comment]
Funnily enough I recently (yesterday?) found a resource leak in the subscription results UI - fix will be in the next beta.

**Comment by hglecke** [comment]
Thanks, but I just installed it.

**Comment by hglecke** [comment]
Great! You beat me to the punch by a few hours. 
Sent from the all new AOL app for Android 
 
  On Sun, Jan 9, 2022 at 11:11 AM, ***@***.***> wrote:   


Funnily enough I recently (yesterday?) found a resource leak in the subscription results UI - fix will be in the next beta.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hglecke** [comment]
Update:
For testing I deliberately pushed the issue and eventually the error repeated, the same error message was displayed. However, now BiglyBT recovered promptly and operations continued OK without a re-start. Running out of resources eventually is to be expected. The response now is good.
Thank you.

**Comment by parg** [comment]
When you get the "GUI Error" message, is there a yellow warning triangle displayed bottom right in BiglyBT? If so can you click on it and get the details of the error?

**Comment by hglecke** [comment]
Will try in future!
I continued to poke around after I posted my previous note. Finally, the screens became unresponsive, again. I had to do the unpopular 'Ctrl-Alt-Del'
This time I had no error message and no triangle.
Happy hunting.

**Comment by hglecke** [comment]
![Screenshot 2022-01-10 080633](https://user-images.githubusercontent.com/67717126/148772396-f175dcf1-c3fc-4ca5-9d9a-81e31d417cb1.jpg)
Just got this warning, as many times before.
An example of 'can we get links and selections' to implement the change.

**Comment by parg** [comment]
It tells you what to do for that - go to Options->Tracker->Client and increase the tracker update concurrency...

**Comment by hglecke** [comment]
Hi:
Been there many times and each time I was challenged by differences in wording in the error message and the tracker client screen. May be I am too dense, but consistency and automation are very good.
Thanks for trying to help.

**Comment by parg** [comment]
Options->Tracker->Client: Maximum concurrent announce tasks

is the one

**Comment by hglecke** [comment]
![Screenshot 2022-01-10 115120](https://user-images.githubusercontent.com/67717126/148805596-b5840948-84b3-4620-a2e2-4a16af7ecc3d.png)
![Screenshot 2022-01-10 114641](https://user-images.githubusercontent.com/67717126/148805597-96cabef4-12da-49d1-b80f-7b5c5c630254.png)
Attached screen shots as requested. Multiple screens were unresponsive to mouse clicks. I was able to restart BiglyBT from within the Files pull down. Before the restart clicking on the yellow triangle produced no reaction.

**Comment by parg** [comment]
You're definitely on B23 ?

**Comment by hglecke** [comment]
![Screenshot 2022-01-10 161046](https://user-images.githubusercontent.com/67717126/148840185-e6208914-d8dc-4a17-b6de-938219b60a1d.png)
![Screenshot 2022-01-10 161127](https://user-images.githubusercontent.com/67717126/148840214-d0b0b160-f13f-4c09-be4c-a01912f655ec.png)

**Comment by hglecke** [comment]
Last issue was triggered by my deleting entries from various subscription screens. All deleted entries had the 'IN' field blank. My gut tells me that the index is not updated regularly, not releasing resources as I continued to delete, going from subscription screen to subscription screen. However, my gut is not very educated or reliable.
Thanks for your continued efforts.

**Comment by hglecke** [comment]
Confused:
![Screenshot 2022-01-10 221637](https://user-images.githubusercontent.com/67717126/148877088-42588d3c-a11d-4172-b386-a00d9242c464.png)
This error is displayed at startup of BiglyBT.
The screen shot of 'about BiglyBT' sent earlier shows installed version V1.8.0_202 (64bit).
I downloaded the current version from Oracle (V8u311(build 1.8.0_311-b11) and installed into BiglyBT. Now BiglyBT shows:
![Screenshot 2022-01-10 223503](https://user-images.githubusercontent.com/67717126/148877533-7b1e17d8-eab5-449b-8257-2abf7afec09f.png)
It went from _202 to _311.
What about v1.11 as shown in the error message?
Sorry, I confuse easily. I got started on this because of the error message, thinking it might also effect the original problem. Only hope not to have caused additional problems for your efforts.
Thanks

**Comment by parg** [comment]
The webtorrent plugin was recently updated to use an alternative implementation and that unfortunately requires java 11.

You are running Java 8 (or confusingly 1.8, they had some version "rework" to get away from everything being 1.x forever) - the latest version of 8 (1.8) is 1.8.0_311

If you don't need the webtorrent plugin (i.e. you're not dealing with torrents that have webtorrent trackers/peers) then just uninstall it.

**Comment by parg** [comment]
If you want Java 11 (or higher) then go to 

https://www.oracle.com/java/technologies/downloads/archive/

**Comment by hglecke** [comment]
Big improvement noticed.
When I returned to more 'normal' operations with picking one or two new entries of interest in a subscription, then on to the next subscription with new entries, again picking one at a time, I had no repeats of earlier screen update problems. Whatever was done for B23 release worked, except in extreme conditions.
This could move the original issue #2397 from 'urgent, important' to 'when time and energy permit'.
Thank you for all your efforts and patience.

**Comment by parg** [comment]
thanks!
