### ISSUE TITLE
[REQ] Shutdown Options 

### ISSUE THREAD

**Issue by Taurean75** [BiglySoftware/BiglyBT#24]
Hey --

I think the shutdown options are buried too deep in Options. It should be in Tools -- one level higher.

Thanks!

**Comment by parg** [comment]
You could enable the Plugin Bar (view menu) and then select 'Quick Config' - some shutdown options are there

**Comment by Taurean75** [comment]
Thanks -- although I don't like using extra space.

**Comment by parg** [comment]
you can get to/from that view via the F8 key if that helps

**Comment by Taurean75** [comment]
Thanks.
