### ISSUE TITLE
Suggestions: Easy "select all" option for each window.

### ISSUE THREAD

**Issue by Dramaman** [BiglySoftware/BiglyBT#2401]
When using a tablet it would be nice for each window to have a select all option (incomplete windows, complete window, merged view)

**Comment by parg** [comment]
Any suggestions as to how?

**Comment by Dramaman** [comment]
![Screenshot 2022-01-11 031106](https://user-images.githubusercontent.com/76974959/148904910-89a5d100-1c26-4c75-9769-0b0dc733fd61.png)
Similar concept to windows folders: have an optional column that allows you to select all or individual

**Comment by parg** [comment]
Hmm, nice idea but a lot of work (the header checkbox isn't something easily implemented unfortunately) - how about a right-click menu open to 'select all' ? 

There's the existing CTRL+A but I suppose it isn't simple to enter that.

**Comment by Dramaman** [comment]
Right click menu would work too

**Comment by parg** [comment]
Added in beta B24

**Comment by Dramaman** [comment]
Works nicely, thanks.
