### ISSUE TITLE
Simple API 'error: method missing'

### ISSUE THREAD

**Issue by unarj** [BiglySoftware/BiglyBT#2403]
win10 64 * OS and version
2.9.0.0 * BiglyBT Version Number

not 100% sure this is an issue as it's functionality that's new to me, but I can't find info on it elsewhere...

Simple API is installed and loaded, I've tried modifying config settings (eg, access 'all', whitelist '*') which doesn't seem to be relevant for internal calls anyways.

When going to Tags Overview, right-clicking on 'Seeding', selecting 'Execute on Assign', and setting the script to 'plugin(simpleapi,"setnetworks&networks=I2P")' (which is straight out of the wiki page examples) the Simple API log file says... 

    execAssign("Seeding","<torrent_name>") - setnetworks&networks=I2P
        error: method missing 

...there are no other log entries, no further hints to fix issue.  Tried mixing up the quotes (eg, 'setnetworks&networks=I2P',"setnetworks&networks='I2P'") and also tried different names for I2P (eg, "setnetworks&networks='I2P network'") with no success.

**Comment by parg** [comment]
You're not wrong, the wiki was incorrect - fixed. It was missing a "method=" bit:

`plugin( simpleapi, "method=setnetworks&networks=I2P" )`

**Comment by unarj** [comment]
that got it, cheers!

**Comment by parg** [comment]
thanks for testing :)
