### ISSUE TITLE
Alternate Rows' color affects on tables inside Options window

### ISSUE THREAD

**Issue by adem4ik** [BiglySoftware/BiglyBT#2407]
* OS and version: Windows 10 x64
* BiglyBT Version Number: B2.9.0.1_B24 (lastest beta)

1. Enable `Options->Interface->Color Scheme : Dark Tables`
2. Set any dark color for `Alternate Rows` (i.e. 2E2E2E)
3. Open `Options->Plugins`

**Result:** Rows with alternative color aren't read-able

**Assumed result:** 
- Or `Dark Tables` setting should affect on tables of Plugins too
- Or `Alternate Rows` color shouldn't work on tables of Plugins

![image](https://user-images.githubusercontent.com/4707112/149241301-3872587d-da68-4feb-8c63-5796e1a32988.png)
![image](https://user-images.githubusercontent.com/4707112/149241419-c738246d-9e37-4423-b477-1857933b3010.png)

**Comment by parg** [comment]
Thanks, I'll take your second approach...

**Comment by parg** [comment]
BTW, dark-mode support on OSX+Linux is pretty reasonable, the issue with Windows is that the SWT UI library that BiglyBT uses doesn't have built-in support for it (yet), hence the current bodge job.

**Comment by adem4ik** [comment]
It is fixed in the latest beta B2.9.0.1_B25, thanks!
![image](https://user-images.githubusercontent.com/4707112/149424961-dd0d89ad-02a1-4c4e-93fa-16b5998daa3c.png)

**Comment by parg** [comment]
As fixed as it'll get!
