### ISSUE TITLE
This is going to sound silly but where are the .torrent files stored? I want to put the torrents onto a thumb drive to open on another computer 

### ISSUE THREAD

**Issue by bketten** [BiglySoftware/BiglyBT#241]
Any posts or screenshots displaying torrent names, search results, subscription names, will be removed without notification, unless they are linux distros.

For bugs, please include the "System" section of the Help->About window, or if you don't have access to the window, include:
* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment

Erase all this text before submitting the issue :)

**Comment by parg** [comment]
Check Tools->Options->Files->Torrents for the save location
