### ISSUE TITLE
? malware - PUADlManager:Win32/iBryteInstaller in azneti2phelper

### ISSUE THREAD

**Issue by JBitte** [BiglySoftware/BiglyBT#2411]
hello, Win10 with latest patches and Anti-Virus Microsoft Defender

Today for the first time I got ->

PUADlManager:Win32/iBryteInstaller
Detected by Microsoft Defender Antivirus

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=PUADlManager%3aWin32%2fiBryteInstaller&threatid=311987

against JCPUID.DLL in package azneti2phelper
is this a known false positive?
![bt-azneti2phelper-issue](https://user-images.githubusercontent.com/6049555/149660473-5c8d99f7-1b5b-4f48-a337-9ec117b27df5.png)

* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment

**Comment by parg** [comment]
Same BS as this from 2 years ago? https://github.com/BiglySoftware/BiglyBT/issues/1546

**Comment by JBitte** [comment]
yes, same as #1546
