### ISSUE TITLE
sqlite error 8, does it matter?

### ISSUE THREAD

**Issue by JBitte** [BiglySoftware/BiglyBT#2414]
hello, Win10 with latest patches, BT beta up to date

Some time ago, I noticed messages in the Java console noting: "Cookie sqlite error 8"

does it matter?

![bt-sqlite-error-Untitled](https://user-images.githubusercontent.com/6049555/149661526-9ffe2dda-2b7e-486f-98c8-c1fbaee9d7df.png)

* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment

**Comment by parg** [comment]
BiglyBT doesn't use sqlite - maybe it is the Chromium thing again.

**Comment by JBitte** [comment]
this Cookie sqlite error 8 error comes up with the internal browser -> Beta Program update
![bt-beta-notifier1](https://user-images.githubusercontent.com/6049555/150107430-87095094-c377-4658-a74a-509e6c0b6d90.png)

**Comment by parg** [comment]
Did you install the Chromium Browser plugin?

**Comment by JBitte** [comment]
yes, bgchromiumswt v3071.3 enabled

**Comment by parg** [comment]
Debug spew is coming from that then - that plugin never really made it to the big time, I worked on it when it looked as if SWT on Windows would have embedded browser problems but they haven't materialised (yet)

**Comment by JBitte** [comment]
ok, I will disable uninstall then
