### ISSUE TITLE
Categories/Tags Upload Prioritization

### ISSUE THREAD

**Issue by jetfighterx22** [BiglySoftware/BiglyBT#2418]
Wanted to report a bug (more of an annoyance than anything critical). When creating a category, putting some torrents into the category, and then clicking on upload prioritization setting in the Tag Overview tab, it works for that session. When restarting the application, the upload prioritization setting for the category/tag remains checked, but uploads are not prioritized. The current workaround is just to uncheck and then check the upload prioritization box to get the setting working again.

Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B2.9.0.0/4 az2

**Comment by parg** [comment]
Should be fixed in beta B28 (See help menu to join the beta program) - thanks!

**Comment by jetfighterx22** [comment]
Thank you! Appreciate all the hard work
