### ISSUE TITLE
Manually triggering RSSFeed Scanner magnet download reports (spurious) failure

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#2419]
This is possibly only happening since, and as a consequence of, a334368c9cb44a935224e5e3dec6ad7dd7789901 or f63c8d59a70cd3670efa576c82288c6afa292f41 or 1cb6e8e10e1af4538f50321ab8c9e43d1bff8aa0. (Though those changes are _very_ welcome, in general — no more endless serial magnet downloads when catching up a backlogged feed! \o/)

My BiglyBT configuration is that all newly-imported torrents begin in a Stopped state.

When I (now) go to RSSFeed Scanner's "Status" list, and I double-click to manually download one of the undownloaded feed items on the list (a feed that contains only private-tracker `magnet:` torrent listings), the status in the "Matches" column for that feed item changes to:

```
Fail - Download::stop: download already stopped
```

This is, on the face of it, quite true. The download _is_ already stopped, and is **supposed** to be stopped. But everything is fine with the newly-added torrent, I can start it whenever I choose, and absolutely nothing is wrong anywhere.

So it's not really any sort of "Fail" condition, and probably shouldn't be reacted to quite so alarmingly. (Nobody likes a drama-queen table column.)

(I qualify with "possibly" in the beginning because, could this actually have started happening **weeks** ago, and just gone unnoticed until today? Yes, without question that is _entirely_ possible.)

#### System block

> Java 11.0.13 (64 bit)
>   Red Hat, Inc.
> /usr/lib/jvm/java-11-openjdk-11.0.13.0.8-2.fc35.x86_64
> 
> SWT v4942r22, gtk/3.24.31, zoom=100, dpi=96
> Linux v5.15.13-200.fc35.x86_64, amd64 (64 bit)
> B2.9.0.1_B27/4 az3

The plugin version involved is:
> RSSFeed Scanner: 1.8.1

**Comment by parg** [comment]
Hopefully fixed in 1.8.2

**Comment by ferdnyc** [comment]
@parg Indeed 'tis! Thanks! The status now proceeds to "Done" with no alarming messages.

There's a momentary flash of "Starting" prior to "Done", which is weird in the case of import-as-Stopped torrents, but nowhere near worth spending time on.
