### ISSUE TITLE
High CPU usage and delayed dragging of Options window

### ISSUE THREAD

**Issue by adem4ik** [BiglySoftware/BiglyBT#2422]
* OS and version: Windows 10 x64
* BiglyBT Version Number: B2.9.0.0 /  B2.9.0.1_B27 (latest stable & latest beta), fresh & clear config
* Java 1.8.0_202 (64 bit)
* CPU: Intel Xeon E3 1270 v2 (server version of Intel Core i7-3770 Ivy Bridge)

1) Open Tools -> Options
2) Type "test" inside "type filter text" field
3) Try to move Options window using mouse

Result: Window feels delayed according to the real mouse movement, Task manager shows 100% CPU usage of one of the cores
Video: https://user-images.githubusercontent.com/4707112/150328740-df8cc7f0-f9f4-46d4-b60e-fa8ea7ae818c.mp4 (you can notice 2 mouse cursors at the end, left one is delayed)

Extra info: 
- If you close Options window and open it once more - problem disappears.
- I couldn't reproduce the same problem in Manjaro Linux on the same PC.

**Comment by parg** [comment]
Yes, weird one that one - I've tried profiling but nothing in BiglyBT shows up as sucking CPU :(
