### ISSUE TITLE
Advanced mode tick does not persist. The, proxy indicator does not show the proxy as activated even though the options > proxy test works.

### ISSUE THREAD

**Issue by controlunit** [BiglySoftware/BiglyBT#2425]
* OS and version: 
* 
*  Debian GNU/Linux 11 (bullseye)

* BiglyBT Version Number:  
* 
* Java 11.0.13 (64 bit)
  Debian
/usr/lib/jvm/java-11-openjdk-amd64

SWT v4936r26, gtk/3.24.24, zoom=100, dpi=96
Linux v5.10.0-10-amd64, amd64 (64 bit)
B2.6.0.0/4 az3

* For *nix: Desktop Environment
Gnome 3.38.5

There are bugs. In the options panel the boxes dont stay ticked. This causes features not to work, such a proxy.

**Comment by parg** [comment]
2.6? Latest version is 2.9

Not sure what you mean, please elaborate.

**Comment by controlunit** [comment]
There are bugs. In the options panel the boxes dont stay ticked. This causes features not to work, such a proxy.

**Comment by as-muncher** [comment]
> There are bugs. In the options panel the boxes dont stay ticked. This causes features not to work, such a proxy.

Yeah, but why not update to 2.9 first?

**Comment by controlunit** [comment]
There is no way to verify the Bigly software. I want to either install using apt, or be able to verify it with a checksum and a signed checksum file. Thanks07.02.2022, 12:17, "as-muncher" ***@***.***>:

There are bugs. In the options panel the boxes dont stay ticked. This causes features not to work, such a proxy.

Yeah, but why not update to 2.9 first?

**Comment by as-muncher** [comment]
> There is no way to verify the Bigly software. I want to either install using apt, or be able to verify it with a checksum and a signed checksum file. Thanks07.02.2022, 12:17, "as-muncher" ***@***.***>: There are bugs. In the options panel the boxes dont stay ticked. This causes features not to work, such a proxy. Yeah, but why not update to 2.9 first? —Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

oh

**Comment by controlunit** [comment]
Bigly is a little weird anyway it like downloads all sorts of weird stuff to you system. Transmission is better because of this.08.02.2022, 13:36, "as-muncher" ***@***.***>:

There is no way to verify the Bigly software. I want to either install using apt, or be able to verify it with a checksum and a signed checksum file. Thanks07.02.2022, 12:17, "as-muncher" @.>: There are bugs. In the options panel the boxes dont stay ticked. This causes features not to work, such a proxy. Yeah, but why not update to 2.9 first? —Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.>

oh

**Comment by controlunit** [comment]
I mean Bigly is pretty good, but I dont know why it tries to download and install strange helpers and speed helpers and all sorts of other weird things in the background. One does not know if they are some sort of  malware or something.08.02.2022, 19:44, "super man" ***@***.***>:Bigly is a little weird anyway it like downloads all sorts of weird stuff to you system. Transmission is better because of this.08.02.2022, 13:36, "as-muncher" ***@***.***>:

There is no way to verify the Bigly software. I want to either install using apt, or be able to verify it with a checksum and a signed checksum file. Thanks07.02.2022, 12:17, "as-muncher" @.>: There are bugs. In the options panel the boxes dont stay ticked. This causes features not to work, such a proxy. Yeah, but why not update to 2.9 first? —Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.>

oh
