### ISSUE TITLE
system standard browser with WebTorrent plugin

### ISSUE THREAD

**Issue by HieronymusCH** [BiglySoftware/BiglyBT#243]
Hi there
the WebTorrent plugin doesn't open the system standard browser. It open the stinking Chrome browser from Google.

**Comment by parg** [comment]
Indeed, that is how it works, although it isn't Google Chrome, it is Chromium. There is no option to use anything other than that at the moment although you might be able to hack something by switching the bundled Chromium browser with something else

**Comment by davisjackie321** [comment]
Nice

**Comment by mefink86** [comment]
How do i disable this please i do not want this to keep opening on my laptop! and where and which version of biglybt can i download the older version that did not need this crap? I will not support biglybt as long as it forces open chromium period end of story

**Comment by parg** [comment]
Wow, how aggressive. Why do you feel the need to be so offensive?

**Comment by parg** [comment]
Actually, fuck off, I forbid you to use BiglyBT and if I catch you doing so I will file a lawsuit.

**Comment by mefink86** [comment]
you are a moron and abusive asshole hope u get covid and die
