### ISSUE TITLE
There are not checksums and keys to use to verify this software. That is why I install the lesser version that supports debian apt install. But it has bugs.

### ISSUE THREAD

**Issue by controlunit** [BiglySoftware/BiglyBT#2430]
OS and version:

    Debian GNU/Linux 11 (bullseye)

    BiglyBT Version Number:

    Java 11.0.13 (64 bit)
    Debian
    /usr/lib/jvm/java-11-openjdk-amd64

SWT v4936r26, gtk/3.24.24, zoom=100, dpi=96
Linux v5.10.0-10-amd64, amd64 (64 bit)
B2.6.0.0/4 az3

    For *nix: Desktop Environment
    Gnome 3.38.5

**Comment by parg** [comment]
There are checksums in the GitHub release:

    https://github.com/BiglySoftware/BiglyBT/releases/tag/v2.9.0.0

**Comment by controlunit** [comment]
How can the checksum file be verified, do you use signing keys?22.01.2022, 23:59, "parg" ***@***.***>:
There are checksums in the GitHub release:
https://github.com/BiglySoftware/BiglyBT/releases/tag/v2.9.0.0

**Comment by parg** [comment]
and down the rabbit hole we go

**Comment by controlunit** [comment]
Nope. Other software does it.23.01.2022, 13:17, "parg" ***@***.***>:
and down the rabbit hole we go
