### ISSUE TITLE
[request] more column options

### ISSUE THREAD

**Issue by HarkTu** [BiglySoftware/BiglyBT#2431]
Sorry, I couldn't find how to create a request.
More column options would be nice. like "total uploaded size", "last active date"

**Comment by parg** [comment]
right-click on a column header and select "column setup"

**Comment by HarkTu** [comment]
There is no such options in mine. I use latest release 2.9

**Comment by parg** [comment]
![image](https://user-images.githubusercontent.com/395293/150768573-7f4b0ae4-b329-4eef-97cb-03be58c33a67.png)

**Comment by HarkTu** [comment]
Tnx found them under filter intermediate. Those options would be better under beginner, I couldn't find them by myself as a beginner :)

**Comment by parg** [comment]
sounds like you are an intermediate user to me
