### ISSUE TITLE
Torrent Download popup missing?

### ISSUE THREAD

**Issue by LuvBiglyBT** [BiglySoftware/BiglyBT#2432]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.9.0.0/4 az3

Has the progress popup for download of torrents been removed from the program?  I am getting no indication of whether a torrent has been added or not except to see it show up in my download library, or not show up if there are no sources available..

Thanks.

**Comment by parg** [comment]
There are two popups for magnet downloads. Firstly the "operation in progress" one controlled by

    Options->Interface->Display: Suppress File Download popup dialog

Then the "open torrent options" dialog controlled by 

    Options->Files: When opening a torrent, show options dialog:

**Comment by LuvBiglyBT** [comment]
Thank you Parg!  As usual, your response is not only timely, but right on point.  I have no idea how it was changed.  I did not even know that option was available.  Needless to say, somehow suppression got checked.  I did try to find such an option before contacting you and I must have missed it.  It is working fine now.  Thank you for all your attention to the program and helping us out._

**Comment by parg** [comment]
No problem!
