### ISSUE TITLE
tor helper plugin failed message popping up all the time

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2435]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B2.9.0.0/4 az3

Ok, so I installed biglybt, wanted to do a swarm merge, but am in airplane mode, and I keep getting this popup that automatic installation of the tor helper plugin failed.  I selected "do not remind me again" and it still pops up every 10 seconds or so.  It's quite annoying.  Does it have to pop up every 10 seconds?  Why doesn't the window cease to pop up?  Oh well, finally connected to the web and the popups ceased.  But still, if I choose to not be bothered about it any more, it should listen.

**Comment by parg** [comment]
There are a few dialogs, which one were you getting?

**Comment by as-muncher** [comment]
I think it was aznettor.

**Comment by parg** [comment]
The actual dialog details would be useful - there are a few involved with plugin intallation, the one that detects that you might have network issues for a given domain for example.

**Comment by as-muncher** [comment]
It was the tor helper plugin, but I'm not getting it now.  I understand if you close this issue.  When I installed biglybt, I wasn't connected to the web, and even though I chose to not be notified about this helper plugin anymore, it still came up every 10 seconds.

**Comment by as-muncher** [comment]
the message is:
Install Failed
Automatic installation failed.
Please go to the plugins website, https://plugins.biglybt.com/, manually download the Tor helper plugin 
and install it via File->Open->BiglyBT File...
