### ISSUE TITLE
can't do search for existing data files with insufficient hard disk space, or even recheck the torrent

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2436]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B2.9.0.0/4 az3

So I was hoping to do a search for existing data files, but biglybt wouldn't even let me check the torrent for existing data.  i could pause the torrent.  It's what I've been saying - BiglyBT tries to allocate even though that option is turned off.  The torrent is say 150 GB, and I have only 50 GB of hard disk space.  So I couldn't even do a recheck on my torrent for incomplete files in my torrent that I moved into that torrent save directory, let alone even do a search for existing data files.  What I ended up having to do is to change my save location to an external hard drive with enough space for the whole torrent and play around there.

**Comment by parg** [comment]
This is with sparse files?

**Comment by as-muncher** [comment]
No, sparse files was unchecked.  This is with the settings from just after a clean installation.

**Comment by parg** [comment]
Perhaps you should check it for future files.

**Comment by as-muncher** [comment]
With sparse files checked, one doesn't get this issue.  However, biglybt is still creating all these shell files (allocating) even though that is turned off by default.  Maybe that's caused by adding the .!qB extension, not sure.
