### ISSUE TITLE
Dark mode rendering issue: Meta Search download notice

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#2440]
I just experimentally clicked "Download" on one of my Meta Search results, and was presented with this dialog:

![image](https://user-images.githubusercontent.com/538020/151675347-8231ba07-51c1-431b-b58b-f9a001956808.png)

So, that's not ideal. Dark mode strikes again!

_Originally posted by @ferdnyc in https://github.com/BiglySoftware/BiglyBT/issues/2439#issuecomment-1024974952_

**Comment by ferdnyc** [comment]
Interestingly, however the text is being rendered in that dialog (if it is), I can't pull the usual trick of selecting it to make it visible. My mouse cursor acts like there's nothing there at all.

**Comment by parg** [comment]
Thanks - fix on fail these things are!
