### ISSUE TITLE
Torrent Details > Files tab "Move Files" from tree view flattens directory structure

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#2441]
If I have the Files list in tree mode, I can select on one or multiple tree parents (directories) and choose "Move Files" to relocate their contents. However, doing so unexpectedly flattens the original directory structure, lumping all of the recursive contents of each selected directory into the destination folder.

Say a torrent contains this structure:

* Directory One/
    * A file
    * Second file
    * Third file
* Totally separate directory/
    * More embarrassing file
    * More important file
    * More special file
    * Subdir LOL/
        * Squirreled-away file

I select both "Directory One" and "Totally separate directory", then right-click and select "Move Files". In the resulting dialog, I select `/var/tmp/` as the destination.

### Expected results
```
/var/tmp/Directory One/A file
/var/tmp/Directory One/Second file
/var/tmp/Directory One/Third file
/var/tmp/Totally separate directory/More embarrassing file
/var/tmp/Totally separate directory/More important file
/var/tmp/Totally separate directory/More special file
/var/tmp/Totally separate directory/Subdir LOL/Squirreled-away file
```

### Actual results
```
/var/tmp/A file
/var/tmp/Second file
/var/tmp/Third file
/var/tmp/More embarrassing file
/var/tmp/More important file
/var/tmp/More special file
/var/tmp/Squirreled-away file
```

#### System block

> Java 11.0.14 (64 bit)
>   Red Hat, Inc.
> /usr/lib/jvm/java-11-openjdk-11.0.14.0.9-2.fc35.x86_64
> 
> SWT v4942r22, gtk/3.24.31, zoom=100, dpi=96
> Linux v5.15.16-200.fc35.x86_64, amd64 (64 bit)
> B2.9.0.1_B31/4 az3

**Comment by parg** [comment]
Yeah......

Selecting a folder in the tree view is just a UI-level shorthand for selecting the "leaf" files contained therein, as you have discovered.

I suppose some more intelligent behaviour could be implemented.

**Comment by parg** [comment]
B32 might work more as you expect
