### ISSUE TITLE
EOF and DHT issues

### ISSUE THREAD

**Issue by eas125** [BiglySoftware/BiglyBT#2447]
I've been having these tracker statuses for a few weeks now.  Gone through basic troubleshooting.  Routing and NAT are green.

EOF while reading reply header
DHT (Backup Only)

Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.9.0.0/4 az3

[debug.zip](https://github.com/BiglySoftware/BiglyBT/files/7987215/debug.zip)

**Comment by parg** [comment]
You have bound BiglyBT to net0 (NordLynx Tunnel #2) - perhaps there is something wrong with that?

Options->Connection->Advanced Network Settings: Bind to local IP address or interface

**Comment by eas125** [comment]
OK.  Turned that off, but still getting these errors.  It switches between the errors.
![image](https://user-images.githubusercontent.com/33065246/152256949-18959e5c-b7a4-4024-902e-30bd5a6a8b60.png)
![image](https://user-images.githubusercontent.com/33065246/152257060-14e5aa29-eebd-4b89-be11-cb034fc1c8bb.png)
![image](https://user-images.githubusercontent.com/33065246/152257089-56c16eff-c93f-4029-8797-9ae5310e6a61.png)

**Comment by eas125** [comment]
Tried a different DL path.  It looks like it's the site's tracker, not Bigly.  Probably needed to turn of binding anyway.

**Comment by parg** [comment]
There's nothing wrong with binding when you want to route traffic through a particular interface (e.g. a VPN). 

However, if the interface isn't working properly, it can cause errors that look as if they are associated with the things BiglyBT is trying to connect to rather than the interface itself, which is why I suggested it might be a cause.

**Comment by eas125** [comment]
Got it.  I have it routing through Nord.  I tried the same torrent last night from two sites and it looks like it was just a tracker issue.  One worked (OK status) and the original had the same errors.  I copied the good trackers to the torrent with errors and it worked fine.

**Comment by parg** [comment]
Glad you figured it out

**Comment by eas125** [comment]
Yep.  Thanks for the help.
