### ISSUE TITLE
Slow downloads NAT issue.

### ISSUE THREAD

**Issue by Jirnkuu** [BiglySoftware/BiglyBT#2448]
Hello.
I had an open issue from my previous user, but for some reason the issue post is deleted, and I did not manage to see the reply.
So I'm posting again in hopes to solve my issue.

my torrents have a dark blue icon saying I do not have remote connection.
I opened the port I am using on my router, both TCP and UDP, but for some reason only the TCP passes the NAT test, while UDP fails, I am not sure why that is.
the program is also open on my firewall.

I still get peers, but my download speed is much slower than it used to be when torrents were green icon, back when both tests were good.

what may be the issue? and how can I fix it?

I have windows 10
biglybt version is 2.9.0.0

**Comment by parg** [comment]
So you deleted you old user, Jirnku, which deleted your old posts and the reply I had spent time making, without reading it?

You will still get incoming connections with only the TCP port open as clients will fallback to TCP when UDP fails so I'm not sure what your problem is.

**Comment by Jirnkuu** [comment]
I didn't delete it, I lost access to it, but I had the post bookmarked, so I'm not quite sure what happened to it, I'm sorry.

I understand what you're saying about the TCP port, but why am I losing download speed? download speed used to up to 6-7 mb/s when torrent was green, now it doesn't go beyond 2mb/s when it's dark blue

**Comment by parg** [comment]
Check the "Speed" sub-tab for the download, it shows the "swarm average download speed" against which you can compare (for the peers you're connected to at least)
