### ISSUE TITLE
Check for updates failed

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2449]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B2.9.0.0/4 az3

I tried checking for updates.
Title bar says: check for updates failed
The following errors were reported:
Platform-specific support, Failed to load plugin details for the platform manager, Plugin 'azplatform2' not found

**Comment by parg** [comment]
Works for me

`
...
    Non-mandatory plugins -     Plugin: azplatform2versions (current=1.27_CVS, latest=1.27_CVS)
...
`

**Comment by as-muncher** [comment]
hmm, for some reason, it ended up working for me too.

**Comment by as-muncher** [comment]
I have another:
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.0.0.1_B13/4 az3

This is the message box that comes up:
The following errors were reported:
BiglyBT Core, Failed to check for core update,
http://version.biglybt.com/biglybt-files/core/BiglyBT3001-B15-signed.jar.torren
t?i2p=1: I/O Exception while downloading
'http://version.biglybt.com/biglybt-files/core/BiglyBT3001-B15-signed.jar.torre
nt', Connect timed out

I'm using the institutional wifi and would still like to get updates to BiglyBT.  is no one seeding using I2P or Tor?  It would be nice if BiglyBT noticed this and offered some other way to update the software, or to offer to install I2P or Tor (which I already have installed in BiglyBT).  Maybe BiglyBT could offer to download using port 80?

**Comment by as-muncher** [comment]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.0.0.1_B25/4 az3

The following errors were reported:

Platform-specific support, Failed to load plugin details for the platform manager, Plugin list load failed,
and much more

![image](https://user-images.githubusercontent.com/33010279/168393997-410fc481-4dd2-427d-b33a-40ca9f857626.png)
![image](https://user-images.githubusercontent.com/33010279/168394052-58d8566e-00f5-4a87-ae26-e8d9bfa35353.png)
