### ISSUE TITLE
Content always saving in Bigly folder

### ISSUE THREAD

**Issue by hatewesterncivilization** [BiglySoftware/BiglyBT#2451]
Java 18-ea (64 bit)
  Oracle Corporation
c:\users\first\downloads\jdk-18

SWT v4948r5, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.9.0.1_B32/4 az3

Even I re-add it as various modes. Hope, it will garantee fixed.

**Comment by hatewesterncivilization** [comment]
It like just that, see

https://prnt.sc/26pwk3p

We need help with that.

**Comment by parg** [comment]
Not sure what your problem is - are you saying that you select to save it in location X but it always gets saved in C:\BiglyBT? Or that the data files are missing?

**Comment by hatewesterncivilization** [comment]
Hi, Paul, yep, that's - "select to save it in location X but it always gets saved in C:\BiglyBT" - the problem. Very annoying, btw. Hope, there are easy workaround. If not, I'm ready to wait. Thanks.

**Comment by parg** [comment]
Are you sure you haven't set up a Tag with initial-save-location? Something must be switching it, "C:\BiglyBT" isn't a special location

**Comment by hatewesterncivilization** [comment]
> Are you sure you haven't set up a Tag with initial-save-location? Something must be switching it, "C:\BiglyBT" isn't a special location

Nope, I even do not adding to any tag, but, of course, I right now going to check things and see. Btw, these problematic torrents was get from magnet, any accordance with that?

**Comment by parg** [comment]
Hmm, can you send me an example of a magnet that causes this and perhaps a "debug.zip" generated via the Help menu to parg@biglybt.com ?

**Comment by hatewesterncivilization** [comment]
Yes, when I'll send, when I reach home, thanks.

**Comment by hatewesterncivilization** [comment]
Done, Paul.

**Comment by parg** [comment]
Nothing arrived :( Rename the .zip file to something else?

**Comment by hatewesterncivilization** [comment]
Ok, wait, again.

**Comment by parg** [comment]
Got it, thanks.

I see that your default save path is "C:\" which may well not be writeable (or a particularly good idea!). Your Java "home" directory is "C:\BiglyBT" - I wonder if somewhere BiglyBT is trying to save stuff to "C:\", failing to do so and falling back to "C:\BiglyBT"? I can't think where that might happen but you could try changing your default save location to somewhere other than "C:\" and see if that changes things?

Options->Files: Default directory:

**Comment by hatewesterncivilization** [comment]
Yes, Paul, it so easy, how I were not think about this? Going to try, and
write you back, if good or not. Sorry, bro, it's my fault and my bad to be
honest.

**Comment by hatewesterncivilization** [comment]
When I changed it to disk F:, it switched to F:)

Then I clear this field of default directory to download, right now I will
check is this helps or not (not, it not help), again switched to C:\BiglyBT.

Paul, sounds it's addressing to setting of
"-Dazureus.config.path=C:\BiglyBT\\" or maybe interpretation of concrete
Java version work with?

**Comment by hatewesterncivilization** [comment]
Also I have granted to Bigly rights to start as admin. Downloaded JDK 19,
JDK, because I want -server mode.

**Comment by hatewesterncivilization** [comment]
Didn't help anything.

**Comment by parg** [comment]
Try disabling the "use best guess" option - setting is next to the "default save location".

**Comment by hatewesterncivilization** [comment]
https://prnt.sc/26ry7d4

Doesn't helping.

**Comment by hatewesterncivilization** [comment]
Paul, I have found an solution, just created folder "cont" at C: drive,
then all starts working fine!
