### ISSUE TITLE
Unable to update from 2.8.0.0 to 2.9.0.0

### ISSUE THREAD

**Issue by Conkuist** [BiglySoftware/BiglyBT#2453]
Install Verification Failed

Verification of 'Core BiglyBT Version' failed: Signature missing from file (C:\Users\Username\AppData\Roaming\BiglyBT\tmp\AZU3971523280567417276.tmp)

Windows 10 Pro (version: 21H2 build: 9044.1466)
BiglyBT 2.8.0.0

**Comment by Conkuist** [comment]
Clearing the %TEMP% folder fixed my problem

**Comment by parg** [comment]
Excellent!
