### ISSUE TITLE
send cancelled .torrent files to recycle bin instead of delete

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2454]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B2.9.0.0/4 az3

Hi, if I open a magnet link with BiglyBT, it downloads, and I have the settings to save the .torrent files in a directory.  The torrent information downloads, a screen pops up with the information about the torrent, and I see that the .torrent file is saved in my directory.  However, when I click the x or cancel, the .torrent file gets deleted.  Would you consider sending it to the recycle bin instead?

**Comment by as-muncher** [comment]
The reason for this anyways, is because I tried saving a .torrent file in qbittorrent and it gave me an error, so I'm glad that BiglyBT could do it for me!  :)  I just wanted the .torrent file.

**Comment by parg** [comment]
If you have enabled 

Options->Files: Move deleted files to the Recycle Bin

then I think that torrent files will end up there
