### ISSUE TITLE
The new "Sidebar Options..." link

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#2458]
Regarding 34ab3e73c720179c0e0f548fc475741d8a035545:

Here's my confusion:

1. "Sidebar Options..." shows up when right-clicking the "My Torrents" heading. Cool.
1. It shows up **ONLY** there, apparently, even though nothing about the preferences section it links to is specific to "My Torrents" in any way.
1. It doesn't show up when right-clicking "Plugins & Extras" or "Devices" headings, but in those specific cases that's because you instead get "Plugin Options..." or "Options..." (which should really be relabeled "Device Options..." now), respectively.
1. Right-clicking "Dashboard" offers no option link of any sort.
1. And when you right-click the "Content Discovery" or "BiglyBT" section headings, there's _no_ context menu provided. **AT ALL**.
1. Right-clicking on an empty part of the sidebar (the widget background) similarly produces no context menu whatsoever.

I totally understand number 3 — it makes tons of sense to show the specific options links for Plugins or Devices instead of "Sidebar Options...", there. (Though, like I said, "Options..." under "Devices" should really be renamed to "Device Options..." for consistency, now.)

But since **Nothing** about the target of "Sidebar Options..." is in any way specific to the "My Torrents" section of the sidebar, why is the menu option otherwise limited to only being reachable from that one heading? Shouldn't it be a general context-menu option **anywhere** on the sidebar, even in the empty spaces, unless overridden for some specific case (like the items in number 3)?

**Comment by parg** [comment]
Yeah, I know - didn't want it appearing on every heading menu as it would add to the clutter, I wanted to add it somewhere so at least so people were aware that configuration options exist for it. I suppose I could add it to the general sidebar panel.

**Comment by parg** [comment]
reworked a bit in B35!

**Comment by ferdnyc** [comment]
Nice! Actually undoes number 3 also, now we have both. Works for me. :+1: 

There is only _one_ small thing... :angel: 

The context menu now works in the spaces _between_ the sections of the sidebar (assuming the spacing is set to > 0 rows)... but it doesn't work _underneath_ the last section. Effectively, there appears to be an invisible bottom to the sidebar at the end of the last item in the last section, even though it visibly occupies the full height of the interface.

(...Also, totally unrelated, but WTF is with _this_ option, and is it even still meaningful?)

![Screenshot from 2022-02-13 01-30-07](https://user-images.githubusercontent.com/538020/153741825-4f3002ec-03e9-4bbb-b78b-3c2eb954645d.png)

"CVS only"? What decade is that even from!? :laughing:

**Comment by parg** [comment]
Ah, yeah, I'll fix that.

The CVS thing only appears on beta builds and, as you say, is from times-of-old... It forces the first-time devices dialog to be shown for debugging purposes - not really meaningful but keeps things interesting.

**Comment by ferdnyc** [comment]
> not really meaningful but keeps things interesting.

And isn't that what life is really all about? :wink: 

> The context menu now works in the spaces _between_ the sections of the sidebar (assuming the spacing is set to > 0 rows)... but it doesn't work _underneath_ the last section.

Fixed to completion in _B36! :+1: Thanks.
