### ISSUE TITLE
setLength fails, ftruncate failed: EPERM

### ISSUE THREAD

**Issue by mortefer** [BiglySoftware/BiglyBT#2462]
There is an error on nvidia shield after recent uodate to Android 11 for the new torrent files. It reads basically the following:
 setLength fails, ftruncate failed: EPERM (Operation not permitted) (allocateFiles existing:/storage/2D81-1929/ NVIDIA_SHIELD/tvshows/....)

However when downloading the torrents that have files already allocated - like interrupted downloads, everyhting works just fine, files are downloaded successfully.

* OS and version - Android TV 11
* BiglyBT version - latest from the market
* For *nix: Desktop Environment

**Comment by mortefer** [comment]
Correction on interrupted downloads: when file is close to be completed the following error pops up:
Disk access error: close fails, close failed: EPERM (Operation not permitted)

All the permissions to access the files are set to Allowed in system settings for thrle app

**Comment by mortefer** [comment]
Can be closed, update 9.0.1 to nvidia shield fixed the issue

**Comment by parg** [comment]
Thanks for solving it :)
