### ISSUE TITLE
Do I need to use port forwarding with my PIA VPN?

### ISSUE THREAD

**Issue by Racerron** [BiglySoftware/BiglyBT#2463]
I am a former Vuse user and now Bigly (v2.9).  
I have always used port forwarding on my VPN (Private Internet Access v3.2).  I have been having difficulty with Bigly making inbound connections on both TCP & UDP.  My OS is W10H (20H2 x64) on a virtual machine using VMWare Workstation (V16.1.1).  
Is there a way to configure Bigly to not need port forwarding?
I have 2 similar computers set up this way.  Bigly with the VM on one computer works fine (both inbound & outbound) but inbound doesn't work on the other computer.

**Comment by parg** [comment]
Are you using the "VPN Helper plugin" (https://plugins.biglybt.com/) to setup port forwarding with PIA or doing it manually via

https://www.privateinternetaccess.com/helpdesk/kb/articles/how-do-i-enable-port-forwarding-on-my-vpn

?

**Comment by Racerron** [comment]
I am using the VPN Helper plugin.  That says everything is good, but when I do a connectivity test, I don't get any incoming connections.  BTW, if I use the Wire Guard (instead of OpenVPN) protocol in PIA, I do get incoming connections but I can't get a stable connection with it.  The connection keeps dropping out.  I am currently working with PIA to see if I can get it straightened out.

**Comment by Racerron** [comment]
I am using the VPN Helper plugin.  It states everything is fine.  BTW, if I use the Wire Guard (instead if OpenVPN) protocol in PIA, I get inbound connections, but the connection is not stable and keeps dropping out.  I am working with PIA on this issue trying to get it working.

**Comment by Racerron** [comment]
I am using the VPN Helper plugin.  It states everything is fine.  
BTW, if I use the Wire Guard (instead of OpenVPN) protocol, everything works fine.  But, my connection using Wire Guard is unstable and keeps dropping out.  I am working with PIA on this issue trying to get it working.
I am using the Bigly internal network connections test for my information.

**Comment by parg** [comment]
Good luck!

**Comment by Racerron** [comment]
Thanks Parg.
If someone can answer my original question, "Can Bigly be configured to run without port forwarding?", it would be appreciated.

**Comment by parg** [comment]
Torrenting works pretty well without port forwarding (you can connect to peers to upload/download, they can't connect to you - so as long as the swarm has a few peers that are connectable things work)

The DHT will struggle somewhat though.

**Comment by JoshuaGloriod** [comment]
Hi Racerron, if you're going to use port forwarding with PIA and not forward that back to the correct one, I think you'll find that a lot more services are broke than just torrents. It's just not possible I think, but you don't have to necessarily use that port forward. That kind of thing is closer to a reverse VPN than what most people are used to.

And what that means, is that it's intended to make sure that random people can't connect to it. You can see why it's a bad feature to use for torrents.

By the way, for anonymizing a torrent connection, you don't want to use port forwards by VPN. That does nothing for you (security it does some, but almost nothing for anonymity). For hiding your traffic, you'll want to look at network encryption plus maybe a port forward. That's something else that commonly is done by VPN's. But what else is a swarm than a virtual network? And your client should offer encryption of some sort.

More than that, you need to host the torrent client on a different network for further anonymization.

**Comment by andrasfuchs** [comment]
Thank you @Racerron for your report, I have the same issue with PIA VPN and its OpenVPN setting. I still couldn't get the port forwarding working properly, although the VPN Helper plugin states that everything fine for me too.

Please get back to us, if you have any feedback from PIA VPN.
