### ISSUE TITLE
[Feature Request] Request a plugin that dynamically changes the client name

### ISSUE THREAD

**Issue by CalunVier** [BiglySoftware/BiglyBT#2464]
Sorry, I didn't find the plugin's development documentation and don't know where it would be more appropriate to request a new plugin. I had to file an issue here.
Here's the thing. Many selfish clients only share files with clients of the same model. (There is one such client in China - Xunlei, which has an extremely large private group, which is one of the main obstacles for Chinese users to use other BT clients) . So, I hope to have a plugin. For a specific client, BiglyBT can pretend to be the client model desired by the other party in order to obtain a peer-to-peer connection. For other regular clients, continue to use the BiglyBT name (to avoid being considered a bloodsucker by other clients).
This plugin will greatly help Chinese users break the monopoly, and will also greatly improve the BT community (this is a community that advocates sharing, isn't it). If the developers don't have enough energy, maybe point me to a link to the development documentation. I would appreciate any help

**Comment by parg** [comment]
Unfortunately having such a feature would cause issues with private trackers that rely on client names to whitelist/blacklist clients on their sites. Many of them would ban BiglyBT, something we'd like to avoid.

**Comment by CalunVier** [comment]
> Unfortunately having such a feature would cause issues with private trackers that rely on client names to whitelist/blacklist clients on their sites. Many of them would ban BiglyBT, something we'd like to avoid.

I don't know about private tracker. Maybe there is a way to just fool the selfish clients, not the Tracker?

**Comment by CalunVier** [comment]
I searched a bit. Maybe private trackers have banned those selfish clients? I can't think of a torrent client that refuses to share with others to work under the private tracker. That is to say, in this scenario, there is no need to deceive other people. business as usual

**Comment by acrinym** [comment]
This might be what you're looking for. 
Looked at qbittorrent for it though :)
https://github.com/qbittorrent/qBittorrent/issues/10258

**Comment by Lucienest** [comment]
> Unfortunately having such a feature would cause issues with private trackers that rely on client names to whitelist/blacklist clients on their sites. Many of them would ban BiglyBT, something we'd like to avoid.

If I get that correctly he's suggesting that there should be a way to change the client request name / version string similar
to Web browser's user agent strings.
Since some torrent clients will whitelist clients based on their arbitrary preferences.
Although most torrent clients won't do that.

**Comment by CalunVier** [comment]
> That's a different thing - you can block clients in BiglyBT by name
> 
> https://github.com/BiglySoftware/BiglyBT/wiki/Tags#Peer_Sets https://github.com/BiglySoftware/BiglyBT/wiki/Speed-Limit-Scheduler#Peer_Sets
> 
> Simplest way is to right-click on a Peer in, say, the "All Peers" view and select "Auto categorize peers into PeerSets"
> 
> Then wait for the client to appear in your sidebar under a red "Client_auto" Tag, right-click on it and select "Execute on assign->Delete"

No, no, I'm not trying to ban those clients. I want to join them, or make them think I am one of them, so that they will be willing to share their resources with me.

**Comment by CalunVier** [comment]
> This might be what you're looking for. Looked at qbittorrent for it though :) [qbittorrent/qBittorrent#10258](https://github.com/qbittorrent/qBittorrent/issues/10258)

It's not a ban, it's pretending to be them and exchanging data with them

**Comment by CalunVier** [comment]
> > Unfortunately having such a feature would cause issues with private trackers that rely on client names to whitelist/blacklist clients on their sites. Many of them would ban BiglyBT, something we'd like to avoid.
> 
> If I get that correctly he's suggesting that there should be a way to change the client request name / version string similar to Web browser's user agent strings. Since some torrent clients will whitelist clients based on their arbitrary preferences. Although most torrent clients won't do that.

That's exactly what i mean

**Comment by Lucienest** [comment]
> > > Unfortunately having such a feature would cause issues with private trackers that rely on client names to whitelist/blacklist clients on their sites. Many of them would ban BiglyBT, something we'd like to avoid.
> > 
> > 
> > If I get that correctly he's suggesting that there should be a way to change the client request name / version string similar to Web browser's user agent strings. Since some torrent clients will whitelist clients based on their arbitrary preferences. Although most torrent clients won't do that.
> 
> That's exactly what i mean

@parg can you look into it?

We're basically asking about being able to change the user agent (UA) string in a way so that those clients which only accepts requests from 'from-xx-version' won't have issues with connections.

**Comment by parg** [comment]
As I said before, faking client identity is not something I am about to work on.

Before you say "I'm not talking about informing the tracker, I just mean the connection between peers" you need to realise that often private trackers will attempt a peer-peer connection to ascertain whether the client has a NAT/port forwarding issue.

Also I'm not happy just to enable it for public torrents as having the ability to change client identity in the client, regardless of how use of it might be restricted, is something that some private tracker admins with itchy fingers and lack of time/interest to investigate will use to ban BiglyBT.
