### ISSUE TITLE
Connection problems to peers on private tracker

### ISSUE THREAD

**Issue by irvingtelder** [BiglySoftware/BiglyBT#2465]
It's a private tracker and the BiglyBT log messages are always:

`Incoming connection from [R: [xxx.xxx.xxx.xxx](: yyyyy] to torrentfilename dropped as peer source disabled`

where xxx.xxx.xxx.xxx is an IP, yyyyy is a port number and torrentfilename is the name of the torrent.

I'm not sure where to fix this "peer source disabled" thing.

In their general guidelines (written several years ago) the tracker admins say that DHT and PEX should be disabled…which I believe I've done and always did using the old uTorrent app up through Mojave.

Thanks in advance.

macOS Monterey 12.2.1
BiglyBT 2.9.0.0

**Comment by parg** [comment]
Sounds as if you might have disable the "Incoming connection" peer source?

Options->Connection: Incoming connection

**Comment by parg** [comment]
right-click on an individual download and select the "peer sources" menu item - see if the incoming connection is disabled theere?

**Comment by irvingtelder** [comment]
It was! I guess the preferences are applied when the torrent is added?

Anyway, I've selected all and added "incoming connection" and the console error messages are gone. Uploads are actually happening.

Thanks, parg!

**Comment by parg** [comment]
no problem!
