### ISSUE TITLE
Unix Release Package Launch Script Uses Windows Line Breaks

### ISSUE THREAD

**Issue by DigitalDJ** [BiglySoftware/BiglyBT#2471]
Hi,

Looking at the Unix GitHub release packages for 3.0.0.0 (https://github.com/BiglySoftware/BiglyBT/releases/download/v3.0.0.0/GitHub_BiglyBT_unix.tar.gz). The biglybt startup shell script seems to be in DOS/Windows line endings, which causes a problem with most shells.

Looks like the source script (https://raw.githubusercontent.com/BiglySoftware/BiglyBT/master/core/src/com/biglybt/platform/unix/startupScript) uses Unix line endings.....so something doing the packaging is breaking it.

Not sure what other files are affect by this, but the other scripts in the package seem unaffected. Maybe something to look into?

Thanks :)

**Comment by TuxPaper** [comment]
Thanks.  I've removed the unix installers from Github while I build ones that work.

**Comment by TuxPaper** [comment]
Installer updated on GitHub.  Tested on Ubuntu 21.10 with Java 11.0.13 (64 bit)
