### ISSUE TITLE
HASH COPY

### ISSUE THREAD

**Issue by eddilara** [BiglySoftware/BiglyBT#2473]
when coping the hash of the torrent from the details tab....or anywhere.....can you remove the spaces in the hash....its really annoying when trying to google search the hash and having to manually remove the spaces

**Comment by parg** [comment]
If you just click the hash on the details tab (rather than right-click and select 'copy to clipboard') then you get the hash without spaces.

Annoying though, I agree.

**Comment by parg** [comment]
I'll change it in a couple of places for the next beta (3001_B01)
