### ISSUE TITLE
BiglyBT 3.0; VPN - Can't get -> java.lang.NullPointerException

### ISSUE THREAD

**Issue by TheRealPD** [BiglySoftware/BiglyBT#2475]
So, I've just upgraded to BiglyBT 3.0 & the VPN plugin is now reporting "BAD"/"VPN NOT SET UP CORRECTLY" using PIA...

...where, what the dialogue is showing is -

BiglyBT UDP is currently bound to /XX.XX.XXX.XXX aka net0 (Wintun Userspace Tunnel)
+ Nat Devices: Can't  get -> java.lang.NullPointerException
+ Can't determine VPN's local IP
x Keep existing binding of net0[0]
PIA CLI active. Last open port status returned was 'XXXXX'

Whilst I've tried both the standard option & forcing Port Forwarding with my u/n & password.

Any thoughts?

**Comment by parg** [comment]
The underlying exception should be logged to the console - see if you can find it by enabling logging in options and opening the console (Tools menu)

**Comment by parg** [comment]
It isn't my plugin but I hacked something into version 5.12 - please update and see if that helps

**Comment by TheRealPD** [comment]
Touch wood that looks to have sorted it. 

Many thanks - it's greatly appreciated. :)

**Comment by parg** [comment]
No problem!
