### ISSUE TITLE
looking forward to public network torrents being downloaded through i2p or tor

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2477]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.0.0.1_B02/4 az3

I don't think tribler is doing it, but I think they aim to.  But it sure would be nice to be able to download torrents from seeders using  public networks through i2p or tor.

**Comment by absolutep** [comment]
I2P doesn't have any out-proxy at the moment.

Someone would need to make an I2P out-proxy first, for this to work.

TOR has out-proxies, I think that is the reason why Tribler works successfully cuz they copied the TOR network.
