### ISSUE TITLE
Checked items

### ISSUE THREAD

**Issue by BVarkentine** [BiglySoftware/BiglyBT#2483]
Somehow the step where I check the items (songs) in a torrent I want to download has stopped.  Have I done something inadvertently to shut it off?

**Comment by parg** [comment]
Perhaps you changed

Options->Files: When opening a torrent, show options dialog:

**Comment by BVarkentine** [comment]
Not sure how I did that, but it does seem to've been the case.  It's fixed now.  Thanks!

**Comment by parg** [comment]
great :)
