### ISSUE TITLE
Feature request : Can there be a channel system?

### ISSUE THREAD

**Issue by absolutep** [BiglySoftware/BiglyBT#2484]
Can there be a channel system, that will allow users to post their torrents in their own channels?

Something like as shown in screenshot 

![Untitled](https://user-images.githubusercontent.com/97702149/157005715-e2913ff6-c3cc-4379-a474-0442c3adb093.png)

**Comment by parg** [comment]
You can create your own "chat" - https://github.com/BiglySoftware/BiglyBT/wiki/Decentralized-Chat

Then drag+drop downloads to it (there are other ways of publishing to it also)

You'd need to advertise your chat channel yourself
