### ISSUE TITLE
Why can i not connect to most peers?  In fact, why are most peers not visible in BiglyBT?

### ISSUE THREAD

**Issue by RobustCoder** [BiglySoftware/BiglyBT#2485]
* OS and version: Windows 10 for Workstations, fully patched
* BiglyBT Version Number 3.0.0.0, the very latest as of today

<img width="1476" alt="BiglyBT" src="https://user-images.githubusercontent.com/11069380/157335409-6aa72fe4-c493-481d-9be7-4828abc7c1ad.png">

The PNG file attached is the typical situation that I find myself in: I am only able to connect to a fraction of my peers:
a) on the 7.31 GB file, I am connecting to only 1 out of 5 peers, and am only uploading a pathetic 11.2 KB / s to it
b) on the 11.12 MB file,  I am connecting to only 1 out of 25 peers, and am not even uploading anything to it

When I was downloading that big 7.3 GB torrent last night, I think that I was commonly only connecting to only 1-3 out of more like 25+ peers.  I wish that I had captured a screenshot then.

Any idea why this is happening?

I have configured BiglyBT in ways that I think should allow maximum connectivity.  Examples:
Tools --> Options --> Connection --> Networks: all 3 choices are checked.
Tools --> Options --> Connection --> Transfer: KB/s global max upload speed: 0 [unlimited]

I use a torrent friendly VPN (Torguard), have port forwarding setup, and in BiglyBT Tools --> NAT / Firewall Test... both TCP and UDP tests immediately pass with "OK !".

I use both Windows Defender as well as MalwareBytes Premium (MBAM).  Since MBAM often complained when I use BiglyBT about it connecting to bad websites, I went into its "Real-Time Protection" area and turned off "Web Protection" which stopped it from complaining.

_Is what I am experiencing normal for most folks, or is there something I have misconfigured?_

Related to this is the fact that the number of peers shown in BiglyBT is often **way** less than what I saw on the website.  For example, last night when I downloaded that 7.31 GB file: the website said that there were > 200 peers, but when I started downloading it in BiglyBT, there were maybe only like 25 of them (and I was only able to connect to a few of those).

I think that this second issue may have been discussed a few years ago [here](https://github.com/BiglySoftware/BiglyBT/issues/836).  The conclusion at that time seems to be that lots of trackers lie, which screws up the websites...

**Comment by parg** [comment]
Trackers are indeed often inaccurate. Your second torrent example is a BiglyBT update torrent - for this one it is often the case that peers are unavailable as they have a quick "turn around" leading to tracker inaccuracies (or indeed DHT inaccuracies).

Generally speaking you won't connect to all the peers and if it is a busy completed torrent you will find it difficult to upload to peers when the seed-to-peer ratio is high - see https://github.com/BiglySoftware/BiglyBT/wiki/Seeding
