### ISSUE TITLE
exposed I2P peers?

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2486]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.0.0.1_B03/4 az3

So I am downloading this one torrent, and I see in the Peers tab that he is from this one country, and I have "show local peer" enabled.  So I see this one seeder from this one country, and the local I2P peer with a different IP address.  The download speed is identical for both.  And then when I look at my main download section for this torrent, the download speed is the download speed that is matching for both of these peers (the I2P one and the one from that country).  So does this expose this I2P user's IP address?  The one peer from that country is at 100% availability, and the I2P one has a matching download speed, but the availability is only 32%.  If these were two different downloads, then I would see a sum of the download speeds for my torrent, right?

**Comment by as-muncher** [comment]
Ah, it seems that the download rate of the local I2P peer is the sum of all the other peers.  What is this local BiglyBT I2P peer?

**Comment by parg** [comment]
The "local peer" gives a representation of yourself in the swarm. If you are connected to two peers and downloading from one at 30KB/sec and the other at 70KB/sec then overall your "local peer" is downloading at 100KB/sec.

If you run the I2P network then you will see your local I2P peer details there. It is just informational.

**Comment by as-muncher** [comment]
But if I'm not downloading 100 kB/s using the i2p network, then why would it be showing that?  Wouldn't it make sense that if I was actually uploading or downloading using the i2p network, then it would show those rates?  But if it's just representing me in the swarm, well, are my torrents actually coming in to my computer using the i2p network?  or are my torrents exposed?

**Comment by parg** [comment]
Turn it off if you don't like it.

If your torrents are have the "public" network enabled on a download then your IP address (or VPN's IP address if you are using one) is visible to other peers.

If you only have the "I2P" network enabled on a download then other peers can only see your "pure" I2P network address which is private.

If your torrent has both "Public" and "I2P" networks enabled then your IP (or VPN IP) is visible to other peers, as is your "mix" I2P address, and the two can be correlated by various means. However, this "mix" I2P address is separate from the "pure" one.

**Comment by as-muncher** [comment]
If the local i2p peer is not actually downloading over the i2p network, then I would expect it still to show, but to show zero upload and download.  That way, there would be no confusion.  So when I see the local i2p peer with a download speed, then that would indicate that it's using i2p, which it's not, so I am asking that you would fix this.
