### ISSUE TITLE
disabling "Show Title" doesn't persist

### ISSUE THREAD

**Issue by coyote3** [BiglySoftware/BiglyBT#2489]
I've disabled
Settings|Interface|Tables|My Torrents|Show Title

but every restart the titles ("Incomplete Torrents","Complete Torrents") reappear.  If I right-click on one of them and try to /enable/ the Titles, they disappear!

Though the vertical space for the title remains (at first, sometimes the space will disappear too).

FYI my "Custom Header Height" = 6.

This began with one of the most recent Betas.

Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B3.0.0.1_B04/4 az2

**Comment by parg** [comment]
Thanks, fixed next beta

**Comment by coyote3** [comment]
Thank you parg, you are the best!
