### ISSUE TITLE
Signature missing from file: Verification of 'Core BigBT Version' failed

### ISSUE THREAD

**Issue by ewillson007** [BiglySoftware/BiglyBT#2491]
Am getting this message when auto updating from BiglyBT version 2.9.0.0 to 3.0.

File name is AZU26175046890833.

Any ideas how I can rectify? Thanks in advance.

**Comment by parg** [comment]
You can download the update from

https://biglybt-files.s3.amazonaws.com/core/BiglyBT3.0.0.0.jar

rename the file to 

core_BiglyBT3.0.0.0.jar

and install the update manually via the Help menu: Help->Advanced->Install Update Manually...

**Comment by ewillson007** [comment]
Thank you kind sir! Will give that a try.
