### ISSUE TITLE
autoprioritize not working with new torrent window

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2492]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.0.0.1_B04/4 az3

Hi.  When I have a magnet link downloading, and then my torrent dialogue window comes up when the .torrent file has downloaded, in my settings, I have it set to autoprioritize .jpg, .jpeg, .zip, and others, but when the dialogue window comes up, I see a lot of .jpg files in the screenshots directory that are not automatically set to "high" priority.  I would love it if this could be corrected.  Thanks for all the good work you's all put in.

**Comment by as-muncher** [comment]
However, when the torrent starts to download, then the .jpg files etc autoprioritize.  I'm talking about when the torrent dialogue window pops up, I would like the .jpg and other autoprioritized file extensions to show the high priority.

**Comment by parg** [comment]
Done in next beta

**Comment by as-muncher** [comment]
Thank you!
