### ISSUE TITLE
please seed plugins_maxshareratio_1.0.zip

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2493]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.0.0.1_B04/4 az3

Please seed that file.

**Comment by ferdnyc** [comment]
@as-muncher  You can download it directly from https://plugins.biglybt.com/.

**Comment by ferdnyc** [comment]
(That URL should probably be less of an easter egg, come to think of it. I don't think it's even linked to from any of the Wiki pages. The only way I ever remember it's there is when I see it go by in the plugin updater logs.)

**Comment by as-muncher** [comment]
> @as-muncher You can download it directly from https://plugins.biglybt.com/.

Yes, that's where I found it initially, but I think it doesn't download directly from there.  It goes into BiglyBT, which must then download it from who-knows-where, and so it was sitting there and sitting there for weeks without downloading.

**Comment by ferdnyc** [comment]
> It goes into BiglyBT, which must then download it from who-knows-where, and so it was sitting there and sitting there for weeks without downloading.

That's if you use the "Install" link. There's a direct "Download" link underneath it.
