### ISSUE TITLE
Request: Add "copy to..." or "export to..."

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2494]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.0.0.1_B04/4 az3

Sometimes when my hard drive gets full, I need to offload some of my files.  It's not great for others who may need those files in my torrent, but I need space.  If I select a few files in my torrent, then press the context menu key on my keyboard or right-click, I see a "retarget" and another option says to "move" and I don't know what the difference is between those two options, but what I'd like is to be able to export to an external device, so that the file structure is recreated, and those files I selected are copied there.

**Comment by parg** [comment]
"retarget" is used to link the file to an EXISTING file

"move" should so what you want, move the file(s) to an alternative location. Folder structure might be preserved, I added something recently to do that but you never know...

**Comment by as-muncher** [comment]
@parg I think "copy to" is better than "export" because "export" is like "move".
The reason I'm asking is because I used "move", but then biglybt expects the file to be at the new location, which can be an external drive, and when the drive is disconnected, then I can't even recheck the torrent because biglybt says it can't recreate the file structure, because now my drive is ejected.  So then, I had to select those files in my torrent and move back to my regular save directory, in order for the whole torrent to be checked again.
If there was a copy function, though, that would recreate the file structure (and maybe that could be a checkmarked option to recreate the file structure) then I could copy those files to an external drive, then set those files in my torrent to "delete" and then I could empty my recycle bin and save space.

**Comment by as-muncher** [comment]
Also, the thing is, when I do a search for existing data files, internal linking mode, then, if I want to copy those files that are complete or mostly complete to my save directory, I can't unless I do each one individually, by "show in explorer" for each one, copy it over manually.  The "copy to" could be bi-directional, with the option to choose which way to go, because, as it is, once I do a search for existing data files, internal link mode, then I can't do another search for existing data files, copy mode or piece mode, because the file is already internally linked.

**Comment by as-muncher** [comment]
Oh, ok, thanks for pointing that out.

**Comment by as-muncher** [comment]
Still, having used both "move" and "retarget", I find those confusing.  I still don't see an option to recreate the directory structure at the destination, which would be really handy, and is my request.  I think I used "move" or "retarget" to an external drive, then cleared the links, then BiglyBT said data was missing.

**Comment by as-muncher** [comment]
@ferdnyc Yes, I suppose that would work if I wanted to carry around an external drive everywhere.  But perhaps I can keep that in mind if I want to offload an entire torrent.
