### ISSUE TITLE
allow to search for existing data files for a seeding torrent unless perhaps the torrent is fully downloaded and 2) delay acting on checkboxes

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2496]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.0.0.1_B05/4 az3

So I was downloading a torrent, just the .jpgs and then biglybt put it into the seeding category when it was done.  However, I couldn't do a search for existing data files on the torrent, even though I figured that I could add some pieces or whole files to it.  What I'm asking is that it would be possible to do a search for existing data files even though the torrent is seeding, unless perhaps if all the data in the torrent is already downloaded.  See what happened is that I tried to click on the greyed checkbox, and so biglybt was acting instantaneously, and maybe it went first to be unchecked, and then to checked, because then all the files that had already been downloaded, which maybe are included in the various pieces of the torrent that had the .jpg files, that then they all ended up in the recycle bin.  And biglybt almost hangs a little, while it is doing this.  So then I saw that my torrent was at 0.0% completion, and then I went into my recycle bin and selected all -> restore, and then got this dialogue box, asking which files I wanted to keep.  There were over 300 files I'd have to compare, so I just ended up restoring it all.  

So that's why it leads to my second request, is that maybe you can delay acting on the checkboxes, maybe 5 seconds, so that I wouldn't have to fish all my stuff out of the recycle bin again. But then this might have been averted if I could have done a search for existing data files on a seeding torrent.

**Comment by parg** [comment]
You really need to stop the download before searching for existing files, it is just too messy to try and do it on an active download. 

Delaying actions would just lead to confusion - most other users out there would expect things to react straight away and would come complaining if there was a confusing lag.
