### ISSUE TITLE
Tracker generating false Seeds as political speech

### ISSUE THREAD

**Issue by coyote3** [BiglySoftware/BiglyBT#2500]
Hi parg, this is not really a problem or an issue with BiglyBT, but just an FYI:

This morning I noticed that some of my long-stalled downloads suddenly all have a specific suspicious number of seeds/peers:
![BiglyBT-420](https://user-images.githubusercontent.com/30500973/159727178-8e21f5fd-20b9-4773-8fcb-2a017c2592ec.jpg)
which it looks to me are a form of political speech:
![BiglyBT-GloryToUkraine](https://user-images.githubusercontent.com/30500973/159727303-d5601aef-811f-41c3-a508-4a9226711871.jpg)
I'm assuming this situation will resolve itself at some point.   (It's of minimal concern, certainly relative to the invasion.)

Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B3.0.0.1_B06/4 az2

**Comment by parg** [comment]
The text shown in the brackets after "Online" comes directly from the tracker's announce response - there is a key in the named "warning message" that is normally used to indicate problems like "incoming port firewalled". I guess it has been appropriated by atrack.pow7.com.

**Comment by parg** [comment]
You can turn that message off via

Options->Tracker->Client: Show warning messages reported by trackers
