### ISSUE TITLE
make first selection of greyed checkbox to go to full rather than to empty and delay acting on it

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2501]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.0.0.1_B06/4 az3

I have/had a torrent where it was only partially downloaded, so the checkmark box was greyed.  When I click it again, though, it goes to empty first instead of full first.  The problem with this is that then when I click the check box again, it goes to full, and then has to recheck the torrent again fully.  If there was a delay on acting on checkboxes, I would save myself some time and disk usage because then biglybt would act on it after a delay of, say, 5 seconds, and then I would have made my somewhat final choice of whether I wanted full or nothing.

**Comment by parg** [comment]
Don't use the checkbox if you don't like it, right-click and set priority as required.

**Comment by as-muncher** [comment]
Yes, I know, I have switched to doing that.  It's a little more hassle than just checking the box, though.  Maybe I'm the only person who has verbalised an issue with this.  Thanks for all your contributions.
