### ISSUE TITLE
In the New Torrent window, the file names keep moving around

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2502]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.0.0.1_B06/4 az3

When adding a torrent, the new torrent window comes up.  When I click "select all" and then "unmark", all the file names keep moving around.  However, this stops when I type something in the search box.  But this will lead to the next issue.

**Comment by parg** [comment]
Don't order the table by the "download?" column?

**Comment by as-muncher** [comment]
@parg, Hi, so you figure that I am just click on the download column?  No.  The file names keep moving around by themselves.

**Comment by parg** [comment]
If you have the table sorting by that column then I see the file names moving about because it is continually trying to resort by that column as the download/do-not-download status changes. 

Obviously it is a "bug" but you can avoid it by not having that column as the sort column,

**Comment by parg** [comment]
Should be fixed in next beta

**Comment by as-muncher** [comment]
Oh, I'm wondering why the download/do-not-download status changes.  I'm glad it will be fixed in the next beta.   Thanks.
