### ISSUE TITLE
searching in the new torrent window not working

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2503]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.0.0.1_B06/4 az3

When a new torrent is added, and I see the list of files in that torrent, when I do a search, it's not working.  BiglyBT is not finding that phrase in the torrent file name, or in the path.

**Comment by parg** [comment]
Search in the file name works for me - it doesn't search in the path.
