### ISSUE TITLE
missing data after checkmarking to download screenshots

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2504]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.0.0.1_B06/4 az3

I was downloading a torrent, finished downloading one file, another file was partially downloaded, and then I see and there is a screenshots directory (I'm not sure why it's not listed at the top instead of under 's') and so I clicked to download that, biglybt made one file in there high priority and the rest normal, and so I right-clicked the screenshots directory, chose normal for all, and then I see that the first file that was previously fully downloaded is now downloading all over again, and the second one is redownloading too.  I only had selected those 2 files at first to download.

**Comment by as-muncher** [comment]
I think this happened because I was using the checkboxes, instead of selecting a directory and choosing my download priority.  Since the checkbox (last time I checked) defaults to "do not download", I think all my already-downloaded data ended up in the garbage, and so when I clicked the checkbox again to download it, all my data had to be redownloaded.

**Comment by parg** [comment]
setting a file's priority to "do not download" **doesn't** delete the data - that's one of the differences between "delete" and "do not download"

**Comment by as-muncher** [comment]
Well I don't know what happened with that one torrent, then.

**Comment by ferdnyc** [comment]
@as-muncher Old issue, I know, but... are you sure the already-downloaded files were actually downloading again?

Sometimes, when you add additional download items to a partially-completed torrent, BiglyBT will decide that it needs to re-check the existing pieces. So it resets all of their progress to 0%, then updates as the piece checks complete.

So, from the Files sub-tab, it can _look_ like everything is redownloading, but actually the data is only being synced against local storage. 

The easiest way to tell the two apart is, when rechecking none of the files' pieces will ever turn "downloading" color. (Red, in the dark theme.) They just go straight from gray to blue.

**Comment by as-muncher** [comment]
Again, when I have a torrent that is downloading, and some boxes are checked and others not, the default behaviour for clicking on the check box next to the torrent root that is somewhat greyed, is to be unchecked instead of fully checkmarked.  When the box becomes unchecked by default, all the file priority settings are lost because they're all set to "Do Not Download".  But then when you click the box to check all, then all the file priorities are set to "normal" instead of their previous file priority settings.  When the torrent has some files checked and others not, it makes more sense that the default behaviour when clicking on a somewhat greyed checkbox is to make it fully checkmarked, with the current file priorities as they are, and the other files set to "normal".

**Comment by parg** [comment]
maybe

**Comment by parg** [comment]
just right-click and select the priority from the menu, no confusion then

**Comment by as-muncher** [comment]
@parg, So when I have multiple file priority settings in my torrent, with some files not marked for download, if I right-click for the whole torrent and select "Download priority normal", then I will lose my other file priority settings.

**Comment by parg** [comment]
You can't expect everything to behave exactly as you want in the moment. It isn't as if you don't have enough options to do things.

**Comment by as-muncher** [comment]
@parg, I can't be the only one who is finding this frustrating.  I'm not asking you to do something that is crazy.  I think I make suggestions that make sense.  So if I have some files checkmarked for download, and those files have different file priorities, you go and try to select the rest of the uncheckmarked files, if there are like 200 of them, and set them to download.

**Comment by parg** [comment]
ok, I'll switch it
