### ISSUE TITLE
add option to start filling in other files when percentage or amount of hard disk remains

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2505]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.0.0.1_B06/4 az3

What is happening now is BiglyBT will download until there is just about nothing left of hard disk space.  Is there an option so that when a certain amount of hard disk space is left, BiglyBT will rather start filling in what it can of other files whose space is fully allocated in the hard drive but are still missing pieces?

**Comment by parg** [comment]
There isn't an option to do that. Use "sparse" files, then there won't be any such allocated-but-not-filled-in space.

**Comment by as-muncher** [comment]
I am using sparse files.  The thing is, then when BiglyBT can't write to the disk, then the torrent is stuck with an error, and then I have to recheck the whole torrent when disk space is free because it couldn't write to disk.
