### ISSUE TITLE
display of torrent contents changes after one of those files finishes downloading

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2511]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.0.0.1_B09/4 az3

Hi, thanks for all your hard work.
When I have selected a torrent, and am looking at its contents, and I have "sequential download" checkmarked, then when one of those files finishes downloading completely, it resets the display of the contents window so that I have to scroll down and find my place again.

**Comment by parg** [comment]
What is the sort column? Is it that the table is resorted due to the completion and thus the file moves?

**Comment by as-muncher** [comment]
The sort column is "# of pieces".  The table is sorted a certain way.  I have sequential download turned on for this torrent.  Then, when the one file finishes downloading, the display of the torrents resets to the top position, even though I had scrolled down, looking at the torrents completing.  The table is not resorted.

**Comment by parg** [comment]
Display of "torrents" resets or display of "files" in the Files View? I have followed your instructions and don't see any issues.

**Comment by as-muncher** [comment]
I have one torrent selected, and so when I have the column of # of pieces sorted from most at the top, and sequential download is turned on, I have scrolled that files window down a ways so that I can see the file being completed.  When one of them reaches 100%, then that files area resets to the top of the listing and I have to scroll down again.  Maybe it's torrent-specific - I'm not sure.  I'm not sure what else I can say to help you with this unless I sent the .torrent file.

**Comment by as-muncher** [comment]
Can you recommend a screen recording program that will allow me to blur out the torrents?

**Comment by parg** [comment]
OK, I reproduced it - it requires an "incomplete file suffix" to be added to the files. Without this the view reset doesn't occur. I'll take a look at fixing it.

**Comment by as-muncher** [comment]
Thanks so much!
