### ISSUE TITLE
[Feature Request] Force Post-Completion Checking to Occur BEFORE Post-Completion Moving

### ISSUE THREAD

**Issue by MoonPie75** [BiglySoftware/BiglyBT#2514]
Current behavior in the (excellent and much appreciated) client is unpredictable as to what order checking and moving occur after a download completes. Sometimes it checks then moves, sometimes it moves then checks, sometimes it starts to check then moves and then finishes checking. It all seems to depend on how many torrents are being checked/moved/etc. at that particular moment and what combination of relevant settings one has enabled.

An issue therefore arises as I have BiglyBT set to recheck after completion and to move torrents on completion to a network share. When moving occurs before the check I end up with extra network traffic clogging the pipes as the check has to be done over the network instead of off the local drive. This can seriously slow down everything - downloading, seeding, moving, and checking - when there are lots of downloads completing, moving, and checking all at the same time.

The logical solution would be to force the program to check before moving on completion. Barring that, an option to force that behavior would be greatly appreciated.

Thanks!

**Comment by parg** [comment]
Do you have

Options->Files->Performance Options: Limit active major disk operations (allocation, check, move...) to one per file system

enabled?

**Comment by MoonPie75** [comment]
I do have it limited to one operation per file system which does improve the network traffic issue to some extent at the expense of time lost by not having parallel operations. 

However, that really doesn't address the root of the problem. 

One way or another a move before a check to a network share ends up needlessly sending the data over the network twice. Not a big issue for a 50mb file . . . a ton of heartache for a 200GB monster.

**Comment by parg** [comment]
With that option enabled check operations are supposed to be scheduled before move operations when a shared file system is involved. I'll look into it

**Comment by MoonPie75** [comment]
Sorry, parg. My reply wasn't really complete enough.

You've got it right that check is scheduled before move when the one-operation-per-filesystem option is enabled. However, this is not really a solution because large torrents still choke the post-completion process. If I have a large torrent checking with that option enabled all of the smaller torrents that then complete will just get queued up behind the big one waiting for it to finish. This does cut down on network traffic, but you pay a price in not being about to complete checking on more than one download at a time.

The ideal solution would be to force check before move on everything (or allow it as an option) regardless of what order the torrents completed in. That will both lighten the load on the network and allow for parallel checking/moving which will keep big torrents from blocking the processing of everything else - the best of both worlds.

I hope that makes it clearer. Thanks for such quick attention to requests!

**Comment by parg** [comment]
To be honest you could just turn off the "recheck on complete" option as it is only there to catch very rare errors (disk I/O errors for example, and these could happen any time) - the download is fully checked as it is downloaded.

You can increase the number of concurrent rechecks to prevent a few small ones getting stuck waiting to check while the big one does but then they would get stuck waiting to move I suppose.

**Comment by parg** [comment]
Beta 3001_B11 (just released) has two new options:

Options->Files: Perform the check prior to any potential move operation

The ordering without enabling this option is actually somewhat undefined - the code attempts to schedule the "move" before the "check" but actually both are done in parallel so I added this option to make it explicit. From the comments the code preferred to do the move before the check as it was worried that if the move was interrupted (user closing BiglyBT or something) then that was more of an issue that the (slow) recheck being interrupted. Anyway, set the option!

Options->Files->Performance Options: Only enforce for write operations (allow concurrent reads)

Enabling this should allow multiple rechecks to run one the same drive while a move operation concurrently moves data from that drive elsewhere.

**Comment by MoonPie75** [comment]
Too awesome. I'll give it a try.

Thanks!

**Comment by as-muncher** [comment]
Since you're working with the disk usage code, I've noticed that biglybt, while checking one big torrent, will start checking a second torrent if a check is initiated on it, if it is less in size than the first torrent.  However, let's say there is 1 GB left to check on a 100 GB torrent.  Then, if I initiate a check on a second torrent, of only 80 GB, BiglyBT will start checking the 80 GB torrent instead of just finishing up with the first one that only has 1 GB left.  Perhaps, an idea would be to only start checking a second torrent if there is less than 1/2 the amount left to check in the first torrent.

**Comment by parg** [comment]
Right, if you have the "check smallest downloads first" enabled that's what will happen. I suppose the sort logic could be reworked to take into account how much is left to check instead of overall size, the sort would still be stable.

**Comment by as-muncher** [comment]
I think if it sorts rather by estimated time to complete checking that torrent, that would be better, because some devices are slower than other, such as the network, or on a regular hard drive vs SSD.

**Comment by parg** [comment]
I implemented size-remaining, that'll have to do

**Comment by MoonPie75** [comment]
I've been using the "Perform the check prior to any potential move operation" and "Only enforce for write operations (allow concurrent reads)" options and both are working perfectly on the beta (now on B12). Checking is running in parallel. Moving is running serial. Post-completion operations are finishing much faster and my network now has 50% less post-completion traffic.

I could not be happier. That was an extraordinary job completed in record time.  Thank you sooo much.

I can't kick over a donation out of our grant money (damned government rules) but there will certainly be a few cups of coffee coming from my own pocket and I'm encouraging my colleagues to do the same. Thanks again for an amazing response.

I see that someone else has commented in the thread so I'll leave closing the issue up to parg. I for one, however, am a quite satisfied customer.

Cheers!

**Comment by parg** [comment]
Thanks, I'm amazed it is working OK :)

Always happy to work on specific user requests, it beats sitting here dreaming up new features that nobody will ever use - keep 'em coming!

**Comment by as-muncher** [comment]
> Thanks, I'm amazed it is working OK :)
> 
> Always happy to work on specific user requests, it beats sitting here dreaming up new features that nobody will ever use - keep 'em coming!

How does the saying go?  "If they build it, they will come."  There are lots of features that people have asked for, so you don't necessarily have to dream up new ones.  But even if you do dream up new ones, they will come.  That's why I came.  I came because of swarm merging.

**Comment by as-muncher** [comment]
> Right, if you have the "check smallest downloads first" enabled that's what will happen. I suppose the sort logic could be reworked to take into account how much is left to check instead of overall size, the sort would still be stable.

Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.0.0.1_B25/4 az3

I had a 1.76 GB torrent stop at 97.5% checking to check another torrent of 1.60 GB, so I'm not quite sure this is working.

**Comment by parg** [comment]
Where both rechecks automatic or manual? Manual ones always take priority over automatic rechecks I believe.

**Comment by as-muncher** [comment]
@parg, They were both automatic.
