### ISSUE TITLE
Mouse scroll wheel should not change comboboxes

### ISSUE THREAD

**Issue by drelephant** [BiglySoftware/BiglyBT#2519]
I'm using BiglyBT 3.0.0.0 on Ubuntu 18.04.6 LTS (Gnome).

I love BiglyBT, but I find it really annoying that when you use the mouse scroll wheel, when it happens to go over a combobox it changes the values of the combobox.

So you try to scroll down in the window but you get stuck on comboboxes that you couldn't even see when you started scrolling, and then you don't know what the original value of the combobox was!!

Is there any way to disable that behavior??

**Comment by parg** [comment]
I'll add something in the next beta that prevents combo + spinner controls on configuration panels from grabbing an overall scroll action (for a second or so) - see how that works for you (next beta will be 3001_B13)

**Comment by drelephant** [comment]
That sounds good, but in my opinion it would be even better if there was a way to disable it entirely, maybe a tickbox in the UI preferences?

Thanks for whatever you do though, I really like BiglyBT!

**Comment by parg** [comment]
I can't prevent the individual controls from grabbing focus as they are scrolled over - they are part of a native widget library, not my code. Not great but hey ho.

**Comment by drelephant** [comment]
No worries, the solution you proposed will be good, thanks a lot.

**Comment by ferdnyc** [comment]
See, I actually really _like_ that UI — as a longtime Linux user, I've become very used to being able to change a combo box selection with a quick scroll of my mousewheel. IMHO it's a feature, not a bug.

That being said, I can sympathize how it might not be to everyone's liking. I'd fully support it being configurable, but unfortunately it'd likely be the purview of one of the GNOME projects, and as we know their general philosophy is pathologically anti-configuration.

**Comment by parg** [comment]
You can still change a combo box with a mouse wheel scroll but not immediately when it grabs focus as part of a larger UI component being scrolled and the mouse happening to pass over the combo box during this process.
