### ISSUE TITLE
Repeated "Allocating" and checking

### ISSUE THREAD

**Issue by PrototypeZero** [BiglySoftware/BiglyBT#2524]
* Windows 10
* 3.0.0.1_B14

For quite a while now everytime I use recheck on a new torrent (because I have 99%+ of the files in an older version of the torrent) the system unnecessarily Allocates and checks files when it doesn't need to.

What I am doing is getting a new torrent in a stopped state. Status shows "Stopped (Unallocated)" .
Put the old files in the correct location and running a "Force recheck".  Now instead of doing the recheck BBT status shows "Checking: 0.0%" (_this never increases the % displayed or the completed %_) but is in the background _actually "allocating" **not** checking_ if you look in Devices/Disk.  Once this allocation has completed status now reads "Stopped" (without the Unallocated).
Running a recheck now will usually do as its supposed to and check the data and increase % done. Fine.
Now attempt the start the torrent downloading and it does one of 4 things.

**1)** Instead of starting the download it starts "Checking" the whole torrent again, completely ignoring the fact it already checked and found data.  Then it may or may not start a round of "allocating" again. Finally it may actually start downloading or most likely return to stopped (so I come back expecting the torrent to be done and instead its as I left it) :-( . 

**2)** Instead of starting the download it starts "Checking" the whole torrent again but then part way though it starts "allocating" then it starts downloading. Better outcome but often **wastes a LOT of time** unnecessarily before starting.

**3)**  Instead of starting the download it starts "Checking" the whole torrent again, then **_completely ignores the data it found_** and starts downloading from 0.0%.  If I'm not there to catch it it means wasted downloading/time and having to run a recheck _yet again!_

**4)** It works as it should first time, this is **VERY RARE** (about 1 in 10 times).

This is just annoying with small torrents, but when the torrents involved are between 80GB and **2.5TB** on HDD it takes forever to get the old data recognised and the download actually started at the progression it should.

I didn't used to have this problem until a few months ago, I used to be able to just put old files in place, force a recheck and start the downloading without a hitch, none of this forced to check 2 or more times.

**Comment by parg** [comment]
When you say "until a few months ago", can you be more specific?

**Comment by parg** [comment]
Tried to reproduce the issue and failed (mostly)

If you add the torrent in a stopped state it shows as "Stopped (unallocated)". 

If you happen to have all of the files and copy them into the right place and select "recheck" then it rechecks and goes into a seeding state.

If you don't have all the files so copy in a subset then when you hit "recheck" it notices that some of the files are missing and allocates them. It then goes into a "Stopped" state without rechecking (OK, not great). However, if you now hit "recheck" again it will recheck the files and leave the download stopped at a done percentage based on the missing files (95% if 5% missing). Now if you hit "start" it goes into "Downloading" at (e.g.) 95%.

Perhaps you can come up with a reproducible example I can try out?

**Comment by parg** [comment]
Try 3001_B16 - I fixed the not-rechecking bug and it might have helped with other issues

**Comment by PrototypeZero** [comment]
Thanks (sorry for getting back to you earlier).
Seems you managed to fix the problems :-D , I've tried about a dozen or so torrents and they all seem to be working as expected in B16-B20 so far.
I'll get back to you if any of the problems re-occur.
:)
