### ISSUE TITLE
BiglyBT uses up free space on drive C after running for hours/days

### ISSUE THREAD

**Issue by andrasfuchs** [BiglySoftware/BiglyBT#2528]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B3.0.0.0/4 az3

I'm not sure if it's a problem only on my system, but if I run my BiglyBT client for days I noticed that my free space on drive C gets less and less, approximately by 1 GB/night. If I stop/restart BiglyBT the space is not released.
Some of the space gets released after a complete Windows restart, but some of it gets only freed up after I run the `chkdsk c: /f` command.

Does anyone else noticed this behavior?

**Comment by parg** [comment]
If space is only freed after fixing disk errors I would look at the health of your disk

**Comment by andrasfuchs** [comment]
I agree, that was my first thought too, but I run a few other processes for days and they don't seem to have any effect on my free space.

I configured BiglyBT to use another drive for downloaded and .torrent files. Configuration directory is still set to C. Logging is not enabled.

I'll try to monitor BiglyBT's access to drive C and let you know if I find something unusual.

**Comment by parg** [comment]
You could try pre-allocating the files (under Files settings - allocate and zero). That way BiglyBT won't be causing small blocks to be allocated on-the-fly.

**Comment by andrasfuchs** [comment]
I did further tests and I'm confident that only BiglyBT causes this strange free space disappearance. 

I tried the `Allocate and zero new files on creation` setting you mentioned, and I also tried `Start in low resource usage mode`, and the `BiglyBT-console.exe --ui=console` startup option, but I still got the problem.

I'm not sure if it's important, but I don't really download new files, I only seed the ones already have.

I turned on logging now, and I'll let you know if I find something suspicious.

**Comment by andrasfuchs** [comment]
I did 3 more tests, all running for exactly 4 hours. I checked the free space on drive C before and after the tests, and I also used [a software](https://www.mindgems.com/products/Folder-Size/Folder-Size.html) to check the sum of the file sizes on the drive to see how much is the valid used space. (The two deltas should be the same.)

A, Running my system normally, without BiglyBT.
Used delta: +0.8 GB
Free delta: -0.8 GB

B, BiglyBT running, but stop all my torrents, so there is no active uploads or downloads.
Used delta: +0.6 GB
Free delta: -1.8 GB

C, BiglyBT running, with 54 torrents force-seeding (with no active downloads).
Used delta: 0 GB
Free delta: -1.3 GB

My download and seed folders are not on my drive C, the only BiglyBT related thing on it is its configuration folder. The free space doesn't change after I quit BiglyBT.

I'm a little bit out of ideas at the moment. Could you recommend me anything else to check?

**Comment by parg** [comment]
I suppose you could move the configuration folder off of the C drive - you would need to run a separate instance as you can't just manually move it elsewhere and expect things to work unfortunately.

Details of how to do this can be found in https://github.com/BiglySoftware/BiglyBT/wiki/Command-Line-Options

**Comment by andrasfuchs** [comment]
I tried to run it with the command line you suggested. (There is a small typo [in the doc](https://github.com/BiglySoftware/BiglyBT/wiki/Command-Line-Options#running-multiple-biglybt-instances), the last character of the command line should be deleted.)

If I run it like this
`javaw.exe -cp "BiglyBT.jar;commons-cli.jar;swt.jar" -Djava.library.path="r:\Services\biglybt\" -Duser.dir="r:\Services\biglybt\" -Dazureus.config.path="r:\Services\biglybt\" -DMULTI_INSTANCE=true com.biglybt.ui.Main`
nothing happens.

But if I run it like this
`javaw.exe -cp "BiglyBT.jar;commons-cli.jar;swt.jar" -DMULTI_INSTANCE=true com.biglybt.ui.Main`
it runs.

What should I do to make it work?

I also tried to replace the jre directory with [Eclipse Adoptium JRE 17](https://adoptium.net/temurin/releases/) and it felt quicker/more responsive, but the space-disappearance problem remained.

I checked the logs and they look ok to me.

**Comment by parg** [comment]
Try removing the trailing "\\" you have on the three -D...=r:\\Services\\biglybt\\" arguments

**Comment by andrasfuchs** [comment]
Removing the tailing "\" worked, thank you!

So, my next test was done by running it with the parameters above for 4 hours, theoretically using only my drive R.

D, BiglyBT running, with default configuration and no torrents in the library, using drive R
Used delta on C: 0.1 GB
Free delta on C: -0.9 GB
Used delta on C: 0 GB
Free delta on C: -0.1 GB

This phenomena prevents me from using BiglyBT as a long running service.

Could you please check if you experience something similar on your machine? 
I'm running the latest Windows 11 x64, my C partition is my boot partition on an SSD with NTFS.

**Comment by andrasfuchs** [comment]
That was copied from the Help/About menu [as instructed](https://github.com/BiglySoftware/BiglyBT/issues/new) while using the included (older) JRE. 

The newer [Eclipse Adoptium JRE 17](https://adoptium.net/temurin/releases/) detects Windows correctly:
```
Java 17.0.2 (64 bit)
  Eclipse Adoptium
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=96
Windows 11 v10.0, amd64 (64 bit)
B3.0.0.0/4 az3
```

**Comment by parg** [comment]
Looks like this might well be being caused by some code in the "mainline DHT plugin" interacting badly with the Windows 11 file system - I've released version 2.6.3 of mlDHT, please test it out.

**Comment by andrasfuchs** [comment]
Thank you for looking this up.

I run [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) and [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon), added a few filters to find something interesting.
I'll copy a few screenshots, I'm not sure if it helps.

![image](https://user-images.githubusercontent.com/910321/164106671-d3fd1d51-770e-40ed-a906-8b9b83e22310.png)
Some plugin .zip files are created again and again in the default Temp folder on drive C?

![image](https://user-images.githubusercontent.com/910321/164106911-9fa29438-4b90-4eb3-ad46-79e7ff5276af.png)
And before that the whole folder structure gets queried?

![image](https://user-images.githubusercontent.com/910321/164107062-e3c46a9c-a468-437e-be19-eba894d333a1.png)
I don't know what these are on the root of drive R.

![image](https://user-images.githubusercontent.com/910321/164107151-c7f1c478-1ddb-48bb-91be-85b74f0c44d4.png)
This one looks interesting, I wonder if these can be disabled by removing a plugin or changing a setting?

**Comment by parg** [comment]
Please allow BiglyBT to update the mlDHT plugin to version 2.6.3 and then see if that helps

The "anon-mapping" files in your last screenshot are the ones I believe causing the issue and they should go away with the update.

**Comment by andrasfuchs** [comment]
I did a few more tests and it looks like you fixed it with the new mlDHT version! Thank you for your efforts!
