### ISSUE TITLE
[Question][Not a Bug] Is it possible to automatically export the .torrent file alongside downloaded data files upon torrent completion?

### ISSUE THREAD

**Issue by jeffward01** [BiglySoftware/BiglyBT#2532]
**NOT A BUG**

----

# Goals

* I want to keep my `.torrent` files organized 'side-by-side` with the associated data files

### Why?
* This helps with organization purposes and managing seeding using self-created tools
* Its good for many users for a variety of reasons to keep the `.torrent` files easily accessible (without using the BiglyBT client) with the associated data files.

# Example Structure - Download Complete

`/completed-torrents/` <-- Root for Downloaded Torrents
`/completed-torrents/<my-torrent-name>/` <-- Downloaded torrent creates a new sub-directory

**Example Structure for associating `.torrent` with data files**
`/completed-torrents/<my-torrent-name>/<my-torrent-name>.torrent`
`/completed-torrents/<my-torrent-name>/<my-torrent-name>DataFiles/`

#  Question

Without using external scripts, is there a way to automatically export the `.torrent` file alongside the downloaded data files upon torrent download completion?

**Comment by parg** [comment]
You can configure BiglyBT to "move on complete" at various levels (global, tag, per-download)

The global one is under "Options->Files->Completion Moving: Move completed files (after download)"

There is an option there to also move the .torrent file.

However none of them will add an extra folder <my-torrent-name> as per your request, rather they all end up in the level above. Of course there are potential issues with name conflicts, both with the existing scheme and your <my-torrent-name> one.

**Comment by parg** [comment]
Beta B17 has a new option in the completion moving config to add a sub-directory. You would need to configure both the download data and the torrent file to be moved to the **same** location and then enable that option. The result won't be quite as in your example but will end up with

`<move to folder>\<download name>\blahblah.torrent`
`<move to folder>\<download name>\<download data>`
