### ISSUE TITLE
When at a torrent download screen, keep a new torrent download screen from taking focus

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2533]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.0.0.1_B17/4 az3

When I'm downloading a magnet link and then a torrent download screen comes up, please keep consecutive torrent download screens from taking focus until I'm done with the current screen.

**Comment by parg** [comment]
Try B18

**Comment by as-muncher** [comment]
I'll take your word for it.  Many thanks!

**Comment by as-muncher** [comment]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.5.0.0/4 az3

I'm noticing again that when I am looking at a new torrent window that BiglyBT brings up after having downloading the information through a magnet link, that if the same thing happens with another torrent, instead of putting the new window behind the one I'm looking at, it puts it in front.

**Comment by parg** [comment]
Not going to do anything more on this, sorry.
