### ISSUE TITLE
Bigly BT Error (No Bind Address for IP4V)

### ISSUE THREAD

**Issue by Villanus666** [BiglySoftware/BiglyBT#2537]
* OS and version - Win 10  - up to date
* BiglyBT Version Number - 3.0.0.0
* For *nix: Desktop Environment

I am not an IT technician so please be gentle with me!  I have successfully run Bigly BT for a number of years with no issue but yesterday I couldn't download any torrents as I got the above error message against all my seeding library and downloads.  I also couldn't check for any updates as I got a BT Core failure message in the log.  Would appreciate any help with this. Thanks!

**Comment by Villanus666** [comment]
Here's the screenshot of the communication test log.
![Screenshot 2022-04-23 07 57 38](https://user-images.githubusercontent.com/104247188/164883939-4f7c8943-524b-41cf-a052-5cefe932b82e.png)

**Comment by parg** [comment]
Somehow you have bound BiglyBT to an IPv6 address (see the "bind address" log line)

To unbind from this right-click on the "Routing" icon (green pipe thing) in the status bar and select "Remove binding to ..."

Or go to 

Options->Connection->Advanced Network Settings: Bind to local IP address or interface

and do it there

**Comment by Villanus666** [comment]
Wonderful!  Thank you so much - the description of "green pipe thing" was just the sort of technical guidance I needed! :-)
