### ISSUE TITLE
Android TV BiglyBT Error: Disk read error - Failed to allocate a 33554451 byte allocation with 11862152 free bytes and 11MB until OOM, target footprint 201326592, growth limit 201326592

### ISSUE THREAD

**Issue by OliverPearmain** [BiglySoftware/BiglyBT#2538]
I am getting the following error when I try to download a specific magnet link torrent....

>  Error: Disk read error - Failed to allocate a 33554451 byte allocation with 11862152 free bytes and 11MB until OOM, target footprint 201326592, growth limit 201326592

 Other torrents seem to work just fine. 
 
 I have tried the following, but I always get the error after about 5 minutes or so of downloading...
- rebooting the box
- freeing up space to ensure I have the spare disk
- deleting the torrent and reopening the magnet link

Any help greatly appreciated 🙏  thx

**Environment**

* SHEILD Android TV 9.0.2 (33.1.0.319)
* BiglyBT Version Number 1.1.8
<img width="1372" alt="Screenshot 2022-04-23 at 14 14 18" src="https://user-images.githubusercontent.com/765324/164896530-c91ac9e8-1f43-4254-b43c-d8e1898c18de.png">

**Comment by as-muncher** [comment]
Wow, I had no idea that an android tv uses BiglyBT.  :)
