### ISSUE TITLE
Options section focus-highlighting in dark mode is... bad

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#2539]
When using a context menu option like "Library Options..." or "Sidebar Options..." that takes you to a specific section of the Options interface, the "focus" highlighting that's applied to call your attention to the target section... well, it definitely does that, but only because it renders the section barely-readable:

![Screenshot from 2022-04-26 04-56-03](https://user-images.githubusercontent.com/538020/165266275-aec44562-b1ae-4c46-b930-90e1ea647ce7.png)

![Screenshot from 2022-04-26 04-57-10](https://user-images.githubusercontent.com/538020/165266247-bfde1efa-7726-4757-bd50-1e05ba6833f6.png)

### System block

> Java 11.0.14.1 (64 bit)
>   Red Hat, Inc.
> /usr/lib/jvm/java-11-openjdk-11.0.14.1.1-5.fc35.x86_64
> 
> SWT v4942r22, gtk/3.24.31, zoom=100, dpi=96
> Linux v5.17.4-200.fc35.x86_64, amd64 (64 bit)
> B3.0.0.1_B18/4 az3

**Comment by parg** [comment]
It used to be a lot worse, at least you can read it

**Comment by parg** [comment]
I made it a bit darker in B19.

Anything else you'd like to see changed/fixed/added? I have some free cycles at the moment :)

**Comment by ferdnyc** [comment]
LOL! Don't tempt me. :wink: The current version is definitely an improvement, tho. Thanks!

Actually, on that note: I was looking at the code for the highlighting ­— one of the reasons it still looks kind of "off", IMHO, is that `highlightControl()` isn't recursive. It'll call `highlightText()` or `highlightText2()` on a container child it finds, but those won't necessarily cause _their_ children to be highlighted. It might need to call _itself_ instead, when it encounters container children. WDYT?

That's what causes the unhighlighted combo boxes (though that's not necessarily a bad thing, those don't look so bad), as well as weirdness like the block of unhighlighted controls in the "Header order" settings. 

(It also happens in the System Tray options with "Enable hiding of the interface without...", because the string is long enough that the checkbox label is detached and made a separate layout element.)

**Comment by ferdnyc** [comment]
Oh, also @parg : Have you seen #2517? I cc: tagged you there yesterday, I think...  my comment explains the reason.

**Comment by ferdnyc** [comment]
So, recursive highlighting has landed! I think it works:

![Screenshot from 2022-05-04 15-40-30](https://user-images.githubusercontent.com/538020/167808662-5ec65beb-7b7b-44a4-82b5-1905c24c0038.png)

I _was_ going to report that the everything-is-bold text transformation could mess with the layout (and subsequent painting):

![Screenshot from 2022-05-04 15-41-45](https://user-images.githubusercontent.com/538020/167808911-4954907e-b38d-4b6b-81cc-cd31fb9519c1.png)

But, weirdly, I only saw that _**one time**_ and now I can't reproduce it. Everything is fine since:

![Screenshot from 2022-05-11 04-44-36](https://user-images.githubusercontent.com/538020/167809122-3f780568-f05e-43ad-ad04-4517f80432b9.png)

So, I guess, "Well, that happened!" Closing as fully addressed, thanks!

**Comment by parg** [comment]
hurrah!
