### ISSUE TITLE
When selecting more of a seeding torrent to download, while it is selected, focus is lost and I have to find the torrent again in the top panel

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2541]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.0.0.1_B19/4 az3

So when I have a torrent that's seeding, but all the data in the torrent hasn't been downloaded, but just a certain part, if I choose to now select more files in that torrent to download, I lose focus and I have to go and find it again in the top panel where all the other "Downloading" torrents are.  Could you please make it so that focus is kept, so that I can still see the torrent contents and not have to go hunting for that torrent?  Thanks.

**Comment by parg** [comment]
Why not just switch to a view that doesn't have the separation between top+bottom? Doing what you want isn't going to happen as the two panels have separate "currently focused" managers and when one moves from one to the other it can't affect the other's focus as they are independent.

**Comment by as-muncher** [comment]
Ok, which view?  I currently have Side Bar, Quick Links, Search Bar, all checkmarked.  I have it on Advanced View, and I normally have Library selected.  I find it handy to see which torrents are seeding, though.

**Comment by parg** [comment]
There are two toolbar buttons to switch between "Simple List" and "Advanced List"

**Comment by parg** [comment]
Or use the library view filter to easily find the download

**Comment by parg** [comment]
Also I believe the download will always go to the bottom of the downloading section (when sorted by "Order")

**Comment by as-muncher** [comment]
As it is, the focus thingy doesn't quite work right anyways.  For instance, a torrent in the top and middle panes will be highlighted, but you don't know which one is showing the torrent contents in the bottom panel in the Files tab.  It shouldn't be that hard to change the focus from one pane to another.

**Comment by parg** [comment]
You need to stop saying things like "It shouldn't be that hard" without having a clue as to how the existing mess of code works.

**Comment by as-muncher** [comment]
:)  You're right.  But, it si what it si, right?  :)
You always seem to work wonders with the code and make it look so effortless, so that's why I say that.

**Comment by as-muncher** [comment]
Same thing happening, with regards to focus.  I may have my torrents organised, so that ETA is smallest on top.  When I select a torrent, and then choose to download more, the selected torrent moves to the bottom, so I have to go searching for it again, instead of BiglyBT changing my focus to the selected torrent.  I'm not sure how this would work with multiple torrents selected and them jumping all over the sorted list, but at least with one, I find it a bit annoying to have to go searching for it.
