### ISSUE TITLE
Lost torrents - best way to re-add to recover all torrent settings?

### ISSUE THREAD

**Issue by drelephant** [BiglySoftware/BiglyBT#2543]
Using BiglyBT 3.0.0.0 on Ubuntu 18.04.6 LTS (Gnome).

BiglyBT crashed, and when I restarted it there were a bunch of torrents missing, although the tags still show on the left-hand side but with zero torrents allocated to the tags.

I had setup the backup folder in the settings, and that does seem to contain the torrent files.

Each tag was downloading to a different destination folder and also some torrents only had some files within the torrent selected, so it's a pain to set that up manually again.

What's the easiest, most automatic way to recover everything, ie torrents under the correct tags and with the file destinations and priorities like they were before?

**Comment by parg** [comment]
You can restore from a backup using Options->Backup & Restore - isn't that working?

**Comment by drelephant** [comment]
Stupidly I didn't even notice that there was a Restore button in there!

When the crash happened, I looked around in there and did a backup, but that was _after_ the torrents were missing.

So... it actually crashed over a week ago and I hadn't got around to opening this issue until now, so unfortunately because it was only set to save 5 days of backups, the day before has now been lost.

Anyway I'll now be aware of how to solve it if it happens again. Luckily for me I didn't have too many torrents in there.

Just a comment as well, when you restore, although the GUI says, "biglybt will now restart to complete the operation", it just shuts down and needs manual restarting. Says "BiglyBT TERMINATED" on the console.

Not a big deal but I suppose it would be better if it did what it says it will do. :-)

Thanks for the help.

**Comment by parg** [comment]
The code does attempt to restart, something must have failed during the process :(
