### ISSUE TITLE
Enter key doesn't engage default actions 

### ISSUE THREAD

**Issue by ballo** [BiglySoftware/BiglyBT#2545]
* OS and version
MacOS Mojave, also more recent versions
* BiglyBT Version Number
3.0.0.0

If I Open URL (command-U) and paste a URL, I should be able to enter it by typing enter (then enter a 2nd time to save the file in the default folder). Instead I have to reach for the mouse and click the little button that is highlighted. Twice. In a different location.
Really annoying when you have a lot of URLs to process!

**Comment by parg** [comment]
I'll fix it so you can hit CTRL+enter in the dialog to accept your input.

If you don't want to see the "open torrent options" dialog then disable it by going to 

Options->Files: When opening a torrent, show options dialog:

and setting it to "never"

**Comment by ballo** [comment]
I don't think this has anything to do with the open torrent dialog. Also I don't understand why I would have to hit Ctrl. Maybe you misunderstood me?

**Comment by parg** [comment]
Try the latest beta
