### ISSUE TITLE
search for existing data files will find 0 pieces, then copy the whole file later

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2548]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.0.0.1_B21/4 az3

Maybe this has changed in B21, but when I do a search for existing data files, sometimes BiglyBT will find 0 pieces in one file, then when it says "looking for other potential name-based matches", it copies the whole file over anyways, which is a .!qB pre-allocated file, which on disk is zero bytes, but when it gets copied from an external to internal hard drive, then all that data is written out, maybe all as zeroes, who knows.

**Comment by parg** [comment]
You keep asking for this code to be changed, perhaps you should stop.
