### ISSUE TITLE
"Get Plugins" only opens the Bookmark editor on KDE/Debian11

### ISSUE THREAD

**Issue by mYnDstrEAm** [BiglySoftware/BiglyBT#2549]
When I open Tools->Plugins->Get Plugins it opens KDE's Bookmark Editor, instead of a BiglyBT window for getting plugins. This is a bug in the version in Debian's repos.

```
Java 11.0.14 (64 bit)
  Debian
/usr/lib/jvm/java-11-openjdk-amd64

[...]
Linux v5.10.0-14-amd64, amd64 (64 bit)
B2.6.0.0/4 az3
```
* Debian11
* 2.6.0.0
* KDE

**Comment by parg** [comment]
It just "launches" 

https://plugins.biglybt.com/

and let's the OS decide what to do with that
