### ISSUE TITLE
CODING_GUIDELINES.md below link is not working.

### ISSUE THREAD

**Issue by ketankbc** [BiglySoftware/BiglyBT#2551]
[BiglyBT/PreferencesJavaCodeStyleFormatter.xml](https://github.com/BiglySoftware/BiglyBT/blob/master/BiglyBT/PreferencesJavaCodeStyleFormatter.xml).
<img width="766" alt="Screenshot 2022-05-07 at 2 55 25 AM" src="https://user-images.githubusercontent.com/37349261/167218740-517b98bc-8279-46e7-9322-2fdc837a4f13.png">

**Comment by parg** [comment]
Thanks, fixed
