### ISSUE TITLE
Move on Same File System Not working

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#2552]
System setting is:
![image](https://user-images.githubusercontent.com/37715552/167496126-6b26f717-dfe4-49af-b39d-99b42ac1551c.png)

Yet I am seeing the following:

![image](https://user-images.githubusercontent.com/37715552/167496012-c3bb5ed2-76d7-47ee-87c4-feeece343ec0.png)

It is clearly ignoring the setting.

Java 1.8.0_331 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_331

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B3.0.0.1_B21/4 az3

**Comment by parg** [comment]
Code looks reasonable - it does fall back to a copy+remove action if the direct attempt to move/rename the file fails for some reason. Unfrotunatley this isn't logged, I'll change that.
