### ISSUE TITLE
[Question] Is there any API Documentation beyond 'Simple API' and 'Web Remote'?

### ISSUE THREAD

**Issue by jeffward01** [BiglySoftware/BiglyBT#2553]
Hello all!

I did some reasearch, and I could not find the answer to my question, so please forgive that I am opening a ticket for this.

First of all, I have tried MANY torrent clients, and BiglyBT is the best by far. Thank you developers! I am a C# developer (C# is Java's younger sister, or brother depending how you view C#) myself, I know how much time development takes, thank you for your awesome work!

I want to interact with the client app in basic ways such as:

* Add torrent
* Start / Stop Torrent
* Get  a list of all torrents
* Get a list of torrent current statuses
* Create tags
* Add tags to torrents
* Remove tags from torrents
* Remove Torrent

Basically thats it, more would be great, but thats the basics.

I have read about the '[Simple API](https://github-wiki-see.page/m/BiglySoftware/BiglyBT/wiki/Plugins)', but it seems to only support adding Tags to torrents **IF** you already know the torrents `hashid`.  The problem is that I do not know how to submit a query to get a list of all torrent's `hashid`'s.

I have also read about the '[Web Remote](https://github.com/BiglySoftware/BiglyBT-plugin-xmwebui)'  and I think that it is based off of  [Vuze](https://wiki.vuze.com/w/Vuze_Web_Remote), but again, I struggle to see a list of commands that are able to be ran. Vuze uses `rpc`, while BiglyBT uses `http` / `https` protocols in the 'Web Remote' area 
![image](https://user-images.githubusercontent.com/12589359/167517630-5011f58b-c027-44dc-906c-44bd6862ee46.png)

**Question**

Does BiglyBT have a document like this https://petstore.swagger.io/ for API methods?

I have seen some users have _some_ success with using the Transmission RPC client... But not sure if it was successful as torrents were added in the 'failure' state, and they had difficulties, it did not seem smooth. [Here is the BiglyBT ticket which mentions this ](https://github.com/BiglySoftware/BiglyBT-plugin-xmwebui/issues/5)

Thanks all!

**Comment by parg** [comment]
There are various ways of interacting with BiglyBT remotely but generally documentation is flakey...

The "Web Remote" is the most comprehensive, take a look at https://github.com/BiglySoftware/BiglyBT-plugin-xmwebui/blob/master/rpc-spec.txt

The "Simple API" plugin could easily be extended to support more features but it might end up not being a "Simple API" at all.

**Comment by jeffward01** [comment]
Thank you!! I have experimented with it some and see that I can communicate via RPC ports. I still have some more experimenting to do on it before I have it 'working' properly, however you have been a **HUGE** help and I really appreciate you pointing me in the correct direction!

 I will close this ticket and open a new one with additional questions, if any.

Thank you again!  🚀

**Comment by parg** [comment]
good luck!
