### ISSUE TITLE
No JVM could be found on your system.

### ISSUE THREAD

**Issue by jrmain** [BiglySoftware/BiglyBT#2557]
A few days ago, right after I updated Java, I started getting this error when I try to run BiglyBT.exe:

"No JVM could be found on your system. Please define EXE4J_JAVA_HOME to point to an installed 64-bit JDK or JRE from www.java.com."

I tried adding the EXE4J_JAVA_HOME environment variable, reinstalling Java, removing all Java installs and installing it again, and rebooting the computer, none of which helped.

I discovered that I can still use BiglyBT by running BiglyBT.jar, and it works okay, except that torrent and magnet file associations still try to open the EXE version. But I found workarounds for that.

I just noticed that BiglyBT.jar is dated 2022Feb24, while BiglyBT.exe is dated 2021Mar18. Does that seem weird?

-------------------------------------------------------------
Help > About:
Java 1.8.0_333 (64 bit)
  Oracle Corporation
C:\Program Files\Java\jre1.8.0_333

SWT v4942r22, win32, zoom=100, dpi=96
Windows 8.1 v6.3, amd64 (64 bit)
B3.0.0.0/4 az3

**Comment by jrmain** [comment]
I reinstalled BiglyBT and that fixed the problem.

**Comment by parg** [comment]
Great!
