### ISSUE TITLE
setting a file in a torrent to "Do Not Download" makes the file disappear in the display of the torrent contents

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2561]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.0.0.1_B27/4 az3

When I do a search for existing data files, internal link, I see some files in my torrent that are near 100% complete.  I select these to "Do Not Download", which makes them disappear out of the list.  Then, I select all the files in my torrent, Clear Links.   What should happen is that the file should not disappear out of the display.  If I need to change that file status to "Normal" or whatever else, I need to be able to see it.

**Comment by parg** [comment]
I don't understand - you say that "Clear Links" is making them disappear from the display? What display? My Torrents? Files View?

**Comment by as-muncher** [comment]
No, not Clear Links.  Setting a file to "Do Not Download" makes it disappear.  So, when you select a torrent in the top panel, and then in the bottom panel, you select the Files tab, you see all the files in that torrent.  When I select one file and change priority to Do Not Download, it disappears, so that I don't see the progress graph for that file, its availability, nothing.

**Comment by parg** [comment]
But you explicitly said "Clear Link" in your original post.

Disappears from where? My Torrents? Files View?

**Comment by as-muncher** [comment]
> But you explicitly said "Clear Link" in your original post.
> 
> Disappears from where? My Torrents? Files View?

Yes, I said "Clear Links" in my original post, but I did not say that "Clear Links" was making the files disappear out of the display.  I said explicitly that it was setting the file to "Do Not Download" that was causing the file to disappear out of the display, and in my second message, I said that it was disappearing out of the Files view.  Thanks for looking at this.

**Comment by PrototypeZero** [comment]
Sounds like OP has "Hide files not selected for download" check box selected, at top of file list.

**Comment by as-muncher** [comment]
@PrototypeZero Ah, I hadn't seen that before.  It must be new.  There's no way that she be enabled by default.  That should definitely be unchecked.

**Comment by as-muncher** [comment]
@parg I was looking for a setting under Options to see if there was a setting that would automatically have that box checkmarked or not, and didn't find one.  So, I selected all my torrents and unchecked that box to hide files not selected for download.  But the thing is, when I add new torrents, then I have to manually select them all, too, and uncheck the box?  Then I'll have some checked and some unchecked.  I really think that those files should not be hidden, by default.
