### ISSUE TITLE
Unallocating Option

### ISSUE THREAD

**Issue by LovelyBloom** [BiglySoftware/BiglyBT#2562]
* Windows 11 Insider 25115
* BiglyBT Version 3.0.0.0

If we had an additional option when right-clicking on a torrent to **unallocate and delete all files** that would help out a lot especially if you have way too many torrents and mistakenly queued them filling the entire drive within minutes. 
and now to fix this you have to manually delete the files/folders **one by one** and recheck at biglybt when you decide to allocate them or if you queue them **you'll get an error**

**Comment by parg** [comment]
Remove the torrent and re-add it.

**Comment by LovelyBloom** [comment]
seems a little risky doesn't it? think of the scenarios. and what if you have a huge list of torrents. adding and selectively "do not download" parts etc.
not the best strategy
