### ISSUE TITLE
BiglyBT causing all linux UI freeze, CPU thread usage to 100% on KDE

### ISSUE THREAD

**Issue by davidalb97** [BiglySoftware/BiglyBT#2568]
This issue happens to me regularly and when it happens, there's no way to kill Bigly without opening a new tty, logging in and killing it.
The whole UI from my DE (KDE) freezes and is completely unresponsive.
I also noticed that every time I go to the tty, Bigly is using 100% of the  CPU thread it's running (maybe some kind of SWT / Xorg deadlock?).
These freezes only occur when I am interacting with Bigly's UI, most notably on selecting a torrent, changing data directory, stopping and rehashing the torrent.
Selecting multiple torrents and right-clicking might also freeze bigly's UI but the whole KDE's. 
Switching to different Java versions & SWT libraries did no effect on this issue (tried multiple fixes from other issues).

### Steps to replicate: 
- Tip: In the worst possible scenario, the DE's UI hangs, you can recover with CTRL+ALT+F2 and killing bigly with htop.
- Install Manjaro Linux KDE edition;
- Install any JDK >= 8;
- Enable user write permissions to /opt/biglybt;
- Go to "Add remove software" > Preferences > Third Party > Enable AUR support;
- Restart "Add remove software";
- Re-open "Add remove software" search & install biglybt;
- Open BiglyBT;
- In BiglyBT, start downloading a 20+ torrents;
- In BiglyBT, ensure all torrents are prealocated and **stopped**;
- Externally move all the torrents to other location.;
- In BiglyBT, for each torrent, select it with right-click and select "Move Data Files";
- In BiglyBT, for each torrent moved, select then press F2 (rename torrent) and rename it to whatever you want;
- In BiglyBT, for each torrent moved, select it with right-click and stop, then "Force-Recheck";

### Expected behavior 
BiglyBT Adds, Stops, Moves and Rechecks  the torrent normally without freezing.

### Observed behavior 
One of three outcomes are currently observed:
- BiglyBT might do it without freezing
- BiglyBT's UI freezes and can be killed through an in session terminal.
- BiglyBT's UI freezes but so does the DE UI, spiking CPU usage and requiring external tty session to kill it.

### BiglyBT information
```
Java 1.8.0_332 (64 bit)
 Oracle Corporation
/usr/lib/jvm/java-8-openjdk/jre

SWT v4942r22, gtk/3.24.33, zoom=100, dpi=96
Linux v5.17.6-1-MANJARO, amd64 (64 bit)
B3.0.0.0/4 az3
```

### System information
```
Display Server: Xorg 21.1.3-4
Operating System: Manjaro Linux
KDE Plasma Version: 5.24.5
KDE Frameworks Version: 5.93.0
Qt Version: 5.15.3
Kernel Version: 5.17.6-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 24 × AMD Ryzen 9 3900X 12-Core Processor
Memory: 47,0 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 750 Ti/PCIe/SSE2
```

**Comment by davidalb97** [comment]
Edit: Added more info to the issue.

**Comment by as-muncher** [comment]
By "hole" you mean "whole", right?

**Comment by davidalb97** [comment]
> By "hole" you mean "whole", right?

Right! :sweat_smile:

**Comment by as-muncher** [comment]
I've noticed this issue, too, where the user interface freezes, and so I have to terminate BiglyBT, and this is using KDE in openSUSE.  I think what happens is that writes are done to the hard drive, but then the interface stops responding, the reads/writes to disk stop and one has to terminate biglybt.  It makes BiglyBT almost unuseable.  But I wonder if the log files are being written to disk.  I tried finding the log files and couldn't find them, so maybe not being able to create log files causes BiglyBT to hang until that's done.  I was on B29, and so log files should be written automatically, right @parg?  I even enabled logging also in the Options menu, but still didn't see any log files.

**Comment by as-muncher** [comment]
Personally, I don't like manjaro, not that helps your issue.  I don't like Manjaro's update program, and it also didn't accept my password for updates in the update program, but I can use that same password in the terminal console and it works.  I couldn't find how to make kde not use wayland but use x11 instead.  So I quit using Manjaro.  But I like that you can choose which filesystem you want to format your system as, at installation.

**Comment by bonze82** [comment]
I ran into an issue the other day that might be related. Check your dmesg when bigly crashes for segfaults for libcairo or other libraries that the ui might use. You can watch it by issuing "dmesg -W". I've sent in bug reports for debian and kernel already for this bug as it occasionally resets X11 back to startup conditions across all of my systems including vm's.

**Comment by davidalb97** [comment]
I no longer experience these problems, so I'm closing the issue.

BiglyBT: 3.1.0.0

### System information
Java 11.0.15 (64 bit)
  Oracle Corporation
/usr/lib/jvm/java-11-openjdk

SWT v4942r22, gtk/3.24.34, zoom=100, dpi=96
Linux v5.18.12-3-MANJARO, amd64 (64 bit)
B3.1.0.0/4 az3

Note: I am no longer opening the torrent's location from Bigly to the file explorer, avoiding BiglyBT from interacting with Dolphin, might also be the reason, idk.
