### ISSUE TITLE
Issue with a downloading file 

### ISSUE THREAD

**Issue by deadbeatdandylyon** [BiglySoftware/BiglyBT#2569]
Hello, I am new to the site and new to the software so I apologize ahead of time If I'm asking about something that has already been resolved. I am getting the following error when attempting to download a file

"Error: Disk Read Error: Flush Fails, Write Fails... NOT BE PERFORMED BECAUSE OF AN I/O DEVICE ERROR"

What I normally do is right click on the file > Go to social > copy the magnet URL > remove the file from the client and computer and start over, But I'm wanting to know is there something else I can do to resume the download without losing progress?

**Comment by as-muncher** [comment]
@spudly1987 I would just pause or stop the torrent, then recheck.

**Comment by parg** [comment]
I/O errors are often indications of hardware issues with a disk rather than a software problem
