### ISSUE TITLE
Failure to save to a network drive (Host > VM)

### ISSUE THREAD

**Issue by E30-318is** [BiglySoftware/BiglyBT#2571]
I have a Win Server 2019 host (running Hyper-V), with a HDD physically mounted to the machine. On the host, I am running a Windows 10 VM for BiglyBT and the VM has access to the drive. 

The physical drive on the host is mapped as a networked drive and can be accessed (read, write, edit - full permissions) by the VM running Bigly and access to the drive works fine via File Explorer, in the past I have been able to download/save media to the drive from BiglyBT, but as of late, all previous downloaded media now cannot be found through the Bigly UI, any in-progress downloads state there's a username/password error, and when initiating a new download, the filepath (\\ExampleServer\D) cannot be accessed. 

Throughout this issue, the drive can still be accessed fine from the VM, which leads me to believe it isn't a credentials/access error despite the error messages in Bigly. 

Previously, a reinstall of Bigly fixed this for around a week and now the issue has cropped up again. 

I am running version 3.0 of Bigly, both the host & the VM are fully up to date in terms of Windows updates available. 

Thanks

**Comment by parg** [comment]
How about if you map the network share to a local drive (e.g. S:)  and then use that from within BiglyBT (as S:\Downloads or whatever)?
