### ISSUE TITLE
create "Done %" and "Done Bytes" categories

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2572]
Java 11.0.15 (64 bit)
  Oracle Corporation
/usr/lib64/jvm/java-11-openjdk-11

SWT v4942r22, gtk/3.24.31, zoom=100, dpi=96
Linux v5.14.21-150400.22-default, amd64 (64 bit)
B3.0.0.1_B29/4 az3

Please change "Done" to "Done %" and add the "Done Bytes" category.  Reason?  Well, when I am offline, and adding torrents, and BiglyBT beautifully does the swarm merge with existing data (thank you so much for that), the Done column shows the percentage of what is done, but the Downloaded field will stay at zero, which it should because there was nothing downloaded.  However, with a Done Bytes field, one can see how much is done.  I guess the same would go for Done with DND - make a Done with DND % and a Done with DND Bytes.

**Comment by parg** [comment]
Done (bytes) added in next beta, thanks

**Comment by as-muncher** [comment]
biglybt 3.4.0.0 on win 11 x64

I have noticed that the Done column is available for the files inside a torrent, that section, but that the top section which lists all the torrents still has a Downloaded column but not a Done column, which I think should be the default.  Could you please add the Done (bytes) column to the top section that lists all the torrents?  I'm not sure how you would work it to show GB or MB or all that, but if it showed the highest unit, something readable instead of the exact bytes, that would be great.  Thanks.

**Comment by parg** [comment]
I thought you'd ditched BiglyBT and were using qb?

**Comment by parg** [comment]
Column Setup for the Library has Done and Done (bytes) - right-click on an existing column header adn then enable them.

**Comment by as-muncher** [comment]
@parg, I don't mind using BiglyBT sometimes for swarm merging, but I've been finding that, if I use swarm merging, that I am losing some data in my torrents, which is not good, plus, you said you were ignoring most of what I was writing in terms of issues, but at least if I need to do some swarm merging, I will use BiglyBT.  

Thanks for the response - I must have somehow missed seeing the Done (bytes) column in the column setup.
