### ISSUE TITLE
Bigly bt non responsive, error open fails

### ISSUE THREAD

**Issue by Tom-Neverwinter** [BiglySoftware/BiglyBT#2577]
* OS and version windows 10 pro
* BiglyBT Version Number 3.0.0
* For *nix: Desktop Environment

Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=144
Windows 10 v10.0, amd64 (64 bit)
B3.0.0.0/4 az3

[debug.zip](https://github.com/BiglySoftware/BiglyBT/files/8816110/debug.zip)

**Comment by parg** [comment]
Not sure what's going on with your file system but there are lots of logs about accessing files taking a long time and the thread dump shows things stuck in native file access routines.

**Comment by Tom-Neverwinter** [comment]
its been a really strange item lately. everything appears to be functional

**Comment by bonze82** [comment]
Tom do you have an ssd drive? If so it may be failing, I'm an IT guy and have replaced atleast a dozen in the last year from the same issues "Drive seems slow". Setup an run smartclt against the drive in question, or all drives if you have multiple.

**Comment by Tom-Neverwinter** [comment]
Its definitely not the SSD, it seems to be trying to access the NAS the nas is not responding fast enough

**Comment by bonze82** [comment]
Saw that in your diag log, still might be wise to check your nas drives. I've seen raid cards fail to state that there was a drive problem until there was major data loss.

**Comment by Tom-Neverwinter** [comment]
I'll run some tests overnight. its going to be a bit

**Comment by as-muncher** [comment]
Java 11.0.15 (64 bit)
  Oracle Corporation
/usr/lib64/jvm/java-11-openjdk-11

SWT v4956r12, gtk/3.24.31, zoom=100, dpi=96
Linux v5.14.21-150400.22-default, amd64 (64 bit)
B3.2.0.1_B05/4 az3

I'm getting a lot of "error: open fails" after I've added my torrents and biglybt is checking them.
