### ISSUE TITLE
BiglyBT gets stuck on "Downloading" window

### ISSUE THREAD

**Issue by LeisureTime69** [BiglySoftware/BiglyBT#2579]
I've been using BiglyBT for years (thank you very much for the program!), but the last few days it has stopped working. It gets stuck on "Operation in Progress" window that says "Downloading: <name of file>"

I see that it also started to download plugins_mlDHT_2.6.3.zip but returned an error. I have attached a log file.

BiglyBT version 3.0.0.0, 64 bit
Windows 10, 64 bit

Java 1.8.0_202 (64 bit)
[biglybt.log](https://github.com/BiglySoftware/BiglyBT/files/8830077/biglybt.log)

  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B3.0.0.0/4 az3

**Comment by parg** [comment]
Hard to say from the information you provided - off the top of my head is BiglyBT bound to a network interface explicitly? You can tell by looking at

Options->Connection->Advanced Network Settings: Bind to local IP address or interface

or check the status bar area for an icon that looks like a pipe and right-click on it if it is there.

**Comment by LeisureTime69** [comment]
After a few days it went back to working 🤷‍♂️

**Comment by parg** [comment]
Let's hope it stays that way!
