### ISSUE TITLE
Suggestion:  Add TAG to BiglyBT Updates.

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#2581]
I would like to see all the Updates and Plugins to have a TAG attached.  This would allow me to set an initial save location for them.  Now they end up in Untagged.  Which is where Sonarr adds torrents.  As I have Sonarr adding torrents to a \Sonarr Downloads path. I am unable to set an initial path for Untagged, as it would re-direct they Sonarr downloads.  Would be easier if Sonarr passed a TAG.

Anyway can all Updates and Plugins be added with a tag `BiglyBT`?

**Comment by NaPurHab** [comment]
I thought TAGS were to replace Categories.  Back in the VUZE days, I used Categories, then when TAGS came out I switched. Thought Categories would be removed eventually. Hope they finally are removed from BiglyBT.  Should have been back in VUZE after TAGS became the New standard.

As to Sonarr, I have no idea how to get it to pass a TAG or Category.  Though I would prefer a TAG.  But a TAG for BiglyBT Updates and Plugins would allow me to place them in a path \BiglyBT\UPdates. I already have a \BIglyBT for torrents and \BiglyBT\Backup.  So it is an organization issue.  Having a BiglyBT TAG on all Updates and Plugins would allow easy handling.  Plus it is easy to add to the meta data when the updates are added/created.

As to Sonarr it was a pain to setup. It has a VUZE profile, but its not a perfect fit to BiglyBT. The setting for the Download Client Vuze, is full of references to `Transmission`. It like they didn't try to customise the Download Client setting for each product.

If Sonarr passed the TAGS it uses for Profiles, I could easily Match them to the TAGS in BiglyBT.  I tried that, created matching tags like `TV_Documentary` in both BiglyBT and Sonarr.  Then Add the TAG to the Show in Sonarr.  And no luck, Sonarr does not pass the TAG when adding the torrent.  If It did, everything would be golden.  I have PLEX point to the paths each TAG in BiglyBT goes to.  So passing the TAGS would be the easiest solution.

**Comment by Havokdan** [comment]
Here i use Tag Restriction: "contains ( save_folder, "C:\Users\Username\Downloads\Sonarr" ) || hasTag( "Sonarr" ) || matches( save_folder, ".+Sonarr\.*")"

**Comment by NaPurHab** [comment]
I can't see how that would work on my system.

contains ( save_folder, "K:\Sonarr Downloads")  - that would work.
hasTag( "Sonarr" ) - has tag NONE, it goes to untagged.
matches( save_folder, ".+Sonarr.*")"  - I don't understand this, seems to indicate in the 2nd part that the filename should contain Sonarr.

And we are off topic.  A BiglyBT TAG on updates and plugins.

**Comment by parg** [comment]
Tags were supposed to replace Categories. But you know users :) Categories do have an "exclusive" property although this is also supposed by Tags by using a Tag Group and setting it as "exclusive".

You can auto-assign "low noise" torrents to a Tag via a constraint of "isLowNoise()" - this pretty much catches BiglyBT torrents.

However, auto-assigning a BiglyBT Tag sounds like a plan.

**Comment by parg** [comment]
The tag will be called "BiglyBT Updates"

**Comment by NaPurHab** [comment]
Thank-you, as it is not in the code, but in the meta-data of the torrent, i figured it would be easy.
