### ISSUE TITLE
A few strings from Statistics>Vivaldi/Vivaldi CVS aren't available for translation

### ISSUE THREAD

**Issue by adem4ik** [BiglySoftware/BiglyBT#2584]
* Windows 10 x64
* BiglyBT vB3.0.0.1_B34

1. Open Tools > Statistics
2. Open Vivaldi/Vivaldi CVS tab

Result: a few strings aren't translated and they are not presented in crowdin project:
- `Our error`
- `Use mouse wheel to scale, left+drag to move, right+drag to rotate`
![image](https://user-images.githubusercontent.com/4707112/172991533-2cb18832-d72c-4175-becb-bb08823004a5.png)

**Comment by parg** [comment]
Fixed, thanks!
