### ISSUE TITLE
change color of progress column

### ISSUE THREAD

**Issue by johnvolfovits** [BiglySoftware/BiglyBT#2587]
* win 7
* 3.0.0.0
![Untitled1](https://user-images.githubusercontent.com/107244103/173020596-b6322ce8-07c3-4825-afb7-e829fd9613c7.png)

* For *nix: Desktop Environment
how to change color of progress column
the color of this column used to be blue and when torrent complete it get green. But now the color doesn't change and by this color the note that shown on column such as percentage of complete, speed and etc are completely unreadable. i want to change color myself or at least change the color to what it was before

**Comment by parg** [comment]
Can't explain that one... my Windows 7 is showing blue/green for downloading/seeding download, grey for those in other states.

There is a transparent image that is drawn over the background to give it the vague 3D look, I wonder if something's weird about that.

**Comment by parg** [comment]
The next beta (3001_B35) will have a right-click column header option to disable the 3D look, see if that helps.

**Comment by johnvolfovits** [comment]
is that has a relate to win theme?
is there any way to set that myself

**Comment by parg** [comment]
your guess is as good as mine. B35 will be available in 30 mins

**Comment by johnvolfovits** [comment]
its not working
is there any way to set that myself

**Comment by parg** [comment]
what's not working?

**Comment by parg** [comment]
You installed B35. Then you right-clicked on the "Progress" column header and deselected the "3D Look" option?

**Comment by ferdnyc** [comment]
I don't think this is the 3D look — that wouldn't explain why the _text_ (which is drawn **on top** of the shaded bar) is also gray.

Hey @johnvolfovits, you don't have the preference
Interface > Color Scheme > Color Overrides > Force non-system colors to grayscale
turned on, by any chance, do you?

(I'm not sure that would affect this either, as those colors are practically _hardcoded_ — but I also don't know how that option actually works, so maybe it would.)

**Comment by johnvolfovits** [comment]
hi 
yes that's right i turned i on and when i unchecked this it get fix
thanks anyway
