### ISSUE TITLE
Some Ideas for housekeeping items.

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#2589]
Something I have ask for in the past was a `X` on the side of each line in both the `Auto Tagging` and the `File\Torrents\Auto Import`.   In Both, if you blank a line it just stays there.  Would be nice to be able to clean/remove them.  Both sections have an `ADD` button, but no way to remove.  I thought of an easy way to solve this.

On the Right side of the `ADD` Button add the following text:
`Blank lines will be removed when Saved`

Then remove blank lines in these 2 sections when the `SAVE` Button is clicked.

2nd cleanup idea:   When clicking `Save` for the `Files\Torrents\Auto Import`,  Sort the entries by Directory Name.  Makes it easier to compare to File Explorer, to make sure I didn't forget a path.

3rd Cleanup idea:  Change the `Assign to Tag` text to be a button. Then Reuse code from the Right-Click on a Torrent, Organize, Tags  to Make it a Selectable Item.  Would help to prevent Typos, and reuse existing Tag Handling.

Last Idea:  Simply MOVE all the `Files\Torrents\Auto Import` items to the Tag Overview. Just add a line in Tag Overview in the File Settings Section. What is one more line.  It could say `Auto-Import Torrents` then the Button to choose the path.   And Transfer/Remove the now Old `Files\Torrents\Auto Import`.    Which would be better than when TAGS were added as a replacement for Categories, but then Categories was never removed.  Simply do it all at once. Of course this removes Ideas #2 and #3.

**Comment by parg** [comment]
multiple blank entries at the END of the list are removed once saved (and you move away from and back to the view)

**Comment by parg** [comment]
I've done your 3rd idea
