### ISSUE TITLE
[Feature Request] Show Tag Groups in Tags Overview for ease of use

### ISSUE THREAD

**Issue by pietchaki** [BiglySoftware/BiglyBT#2597]
Would it be possible to list Tag Groups as a "Tag Type" in the Tags Overview?
Or any way to configure Tag Groups better then right-click > Group > Settings > [Group Name] > Rename

Also, when Renaming a group, the old name remains as an option in the libraries Column Setup.

OS: Windows 10
BiglyBT 3.0

**Comment by parg** [comment]
Doesn't make sense to add them as a 'Tag Type' - a full UI would need a separate table which would require quite a bit of work and I don't have the enthusiasm to work on it.

I'll look at the library column thing, they go away after a restart...

**Comment by pietchaki** [comment]
Yeah, I think you right... not much sense there, just would be easier to edit.
I guess that its a single time configuring the Tag groups, I was just getting to know how they work and made a lot of changes to mine. Probably won't touch that again in a long time... so don't worry.

Thanks for your time!

**Comment by parg** [comment]
There's a few things to fix up anyway, thanks for reporting!
