### ISSUE TITLE
Styling of Tag names in a Tag Group colunm

### ISSUE THREAD

**Issue by pietchaki** [BiglySoftware/BiglyBT#2598]
When I create a Tag Group, I can then add it as a column in the Library, to show the assigned Tag Names that are in that group.
But it shows just the name, while in the Tags column they are stylized. It would be better if both get stylized.

Example below shows the Tag Group columns to the left and the default "Tags" column to the right
![image](https://user-images.githubusercontent.com/6844712/174444138-883dfe5d-1aee-4853-85a6-53194d45fd90.png)

Also, when I rename a Tag group, the column in libraries continue to show the old one (now without any Tags), and also remais as an option in the Column Setup Menu. My guess is that it creates new group, moves tags to that and set old as removed. If that's the case, then maybe search libraries that use the old column name and change to the new one. And in the Column Setup screen filter out the removed groups.

OS Windows 10
BiglyBT 3.0

**Comment by parg** [comment]
done in next beta (B42)
