### ISSUE TITLE
Support for Lokinet low-latency onion routing for enhanced privacy

### ISSUE THREAD

**Issue by jan-kleks** [BiglySoftware/BiglyBT#2601]
I have recently been reading about an interesting WIP lower-latency alternative to Tor -- Lokinet. Maybe it is something that could potentially be integrated into BiglyBT in the future for higher anonymity? Either by using an exit node to "clearnet" and/or by downloading/uploading everything exclusively inside Lokinet (similar to how I2P torrents can work in BiglyBT).

Lokinet on GitHub: https://github.com/oxen-io/lokinet

[Blog post about Lokinet's speed](https://www.oxen.io/blog/lokinet-speed-and-scale)

**Comment by absolutep** [comment]
I second this.

Just like i2p plugin, lokinet plugin would be great.
