### ISSUE TITLE
Can we have a BiglyBT lite version with only i2p plugin?

### ISSUE THREAD

**Issue by absolutep** [BiglySoftware/BiglyBT#2607]
As mentioned above.

All rest of the settings are default and only i2p plugin be available.

Meaning - no tags, no swarm merge, no search, do not even want ability of sequential download - a light weight client with just i2p plugin.

I know i2p is not light by virtue of its functioning but still rest settings do bloat much on lesser laptops.

**Comment by parg** [comment]
Use the built in snark torrent client

**Comment by parg** [comment]
https://geti2p.net/en/about/software - see "I2PSnark"

If you know what you're doing I'm sure you can run BiglyBT in a VM with only I2P and Tor able to route to the public network (don't ask me though, not something I've looked at)

**Comment by as-muncher** [comment]
@parg, interesting, but I know I for one would love to make sure that BiglyBT for sure doesn't use any other networks other than i2p, or tor or both.  I know I have i2p only, and then biglybt can't update, so I do a manual update by using the script.  But to not have any identity leaks would be fantastic.

**Comment by parg** [comment]
My main issue with trying to create such a leak-free version is that BiglyBT/Java is a complex beast and I don't personally want the responsibility that comes with claiming it is "leak free"...

**Comment by as-muncher** [comment]
@parg, got you.  But hopefully there are some people who will be willing to help you make an i2p-only version, something leak proof.
