### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by Bavarello** [BiglySoftware/BiglyBT#2608]
Hello,
I can't update, my info below

Java 1.8.0_331 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_331

SWT v4942r22, win32, zoom=100, dpi=144
Windows 10 v10.0, amd64 (64 bit)
B3.0.0.0/4 az3

Edizione	Windows 10 Pro
Versione	21H2
Data installazione:	‎18/‎06/‎2020
Build sistema operativo	19044.1766
Esperienza	Windows Feature Experience Pack 120.2212.4180.0

Nome dispositivo	MiG
Processore	Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz   3.79 GHz
RAM installata	32,0 GB
Tipo sistema	Sistema operativo a 64 bit, processore basato su x64

![image](https://user-images.githubusercontent.com/22433856/175565948-5ea1e624-78de-4d8b-a3ff-9bfc6f3fff2f.png)

[debug.zip](https://github.com/BiglySoftware/BiglyBT/files/8977251/debug.zip)

Regards

**Comment by parg** [comment]
Ucheck "update anonymously" in the settings
