### ISSUE TITLE
keep piece information current for files marked Do Not Download

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2610]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.0.0.1_B43/4 az3

Unfortunately, sometimes BiglyBT doesn't prioritize completing files in a torrent, pieces that are available, like just 3 pieces or 1 piece left, so I set the priority to High (5) or High (3) but I find that, still, that BiglyBT still keeps busy with what it's downloading and doesn't really try hard enough to just go for those files that I marked as those high priorities.  So, I select all the files in the torrent that have pieces missing, mark as Do Not Download, and then I see that BiglyBT gets to working faster on those files that have high priority.  The thing is, then I see that all those files I marked as Do Not Download show white in it, as if those pieces are now available, but I'm pretty sure they're not all available.  There are no dark red areas.  So, could you please keep the piece availability information for those files current?  But if I mark them as "Delete", I could see you not keeping piece information current.  But for Do Not Download, I need to know, so that I can mark them for download if I see that the whole file is now available.

**Comment by as-muncher** [comment]
I think what happens, is BiglyBT is so busy with the file it's currently working on, that it doesn't care to take notice that I've changed the download priority for other files.  As a side note, I've also noticed, that if I choose to download files sequentially, then quit BiglyBT, that upon starting up BiglyBT again, Bigly will go to the next file in the torrent instead of finishing the file that it had been downloading previously.  Would be neat if there could be an option to prioritise whether I want to finish a file in a torrent first, or go by the priority first, or any other priorities, like file name extension priority.

**Comment by parg** [comment]
Are you talking about the pieces graphic in the Files View or in the General View?

**Comment by parg** [comment]
Anyway, unwanted pieces are deliberately excluded from the bad-availability drawing logic. You don't want the file so why would you want to be bothered about whether it is available or not.

**Comment by as-muncher** [comment]
@parg, I'm talking about the Files tab view.  I can see your point of view.  But as I stated above, I guess it's been frustrating to see BiglyBT downloading pieces of files with normal priority, when I've set other files to a numeric High priority and it's taking a long time to get to those.  So I figured that I'd have to select a whole bunch of the other files, set it to Do Not Download, and then I see those files that have high priority worked on right away.  And I see BiglyBT trying to download pieces of files in my torrent which files are incomplete, so then I choose those files that are complete, to have a high priority.  I can understand if BiglyBT is trying to get rare pieces.  So, that's why I was asking to be able to see the piece availability for files that I chose to Do Not Download, because I will want them later.  Just some feedback, a wish.

**Comment by as-muncher** [comment]
yup, definitely have to mark a whole bunch of files as Do Not Download in order for BiglyBT to get to the High (5) and High (4) ones, or even just the ones marked High.

**Comment by parg** [comment]
You can see the effective priority of a piece by hovering over it in the Piece Map view.

Effective priority is a combination of a lot of this - how rare a piece is, whether start/end of files are prioritised, sequential downloading, file priority, the desire to complete a partial piece in preference to starting a new one...
