### ISSUE TITLE
how to show my torrent's availability to the the peer?

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2613]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.0.0.1_B45/4 az3

In the Files tab, I see the Availability column, to see how much the peer has that I want.  But is there a column that I can select that will show how much of what I have, the peer wants?

**Comment by parg** [comment]
Files tab? You mean Peers tab right? 

I can add a "Wanted" column that computes the opposite of "Available"

**Comment by as-muncher** [comment]
I wouldn't call it "Wanted".  Maybe "wanted by peer" or "% peer wants".  "Wanted" is a bit confusing: does it mean % I want or % peer wants?  Even when you have "Available" you could change that to "% I want" or "% available to me".  But I know, it makes the column headings that much larger.  But something less confusing would be better.  Thanks so much for adding it.

**Comment by parg** [comment]
There is a tool-tip that explains in more detail (also shown in the column-setup window). You can always rename it via right-click on the header.

**Comment by as-muncher** [comment]
@parg Wow, the option to rename it?  feature-rich indeed.  Yes, I found the tooltip helpful, thank you for that.  Thanks again for adding this.  :)

**Comment by as-muncher** [comment]
I was looking at the commits, and did something change?  Did you change the title of the commit?  I thought I was looking at the commit, and saw the green lines that were added that specifically said "Wanted" in it and I saw how you added the green lines that added to the Features of BiglyBT, but now I can't seem to see that commit.

**Comment by parg** [comment]
https://github.com/BiglySoftware/BiglyBT/commit/478e0321c975aa9e25f0bd91775d4419967f1d31
