### ISSUE TITLE
[INFO] What happens during the "allocating" check anyway?

### ISSUE THREAD

**Issue by david-bakin** [BiglySoftware/BiglyBT#2614]
[BiglyBT Beta (3.0.0.1_B45 on a Windows Server 2016 Datacenter system with an unfortunately very slow HDD array ...]

So I'm downloading (for several days) a torrent ~5TB and ~60000 individual files.  ~4TB downloaded so far.  And every once in awhile I think I'm focused on the browser window when I hit ^P to print and instead I'm in the BiglyBT window and the torrent pauses.  So when I notice that the printer isn't printing I go over and make the torrent continue.

And when I do it takes ~20-30 minutes for the "allocating" phase to go from 0 to 100%, while the disk reads happen at ... a paltry 10MB/s or less.  (Oh, and while it is doing this no job shows up in the "Disk" tab.)

So, what's it doing?  It isn't immediate, even though I've just paused and restarted in the same BiglyBT window w/o restart, so it is clearly doing _something_.  But it also isn't reading the entire 5TB to validate individual blocks, either, which would take _hours_ and _hours_.  (Days and days in fact, at 10MB/s.)

Just curious.

(Also is there a way to remap ^P to do ... nothing?)

**Comment by parg** [comment]
During the allocation phase it checks that the files exist on disk as expected, probably going through 60,000 such checks.

There is an option to skip this for completed files
    Options->Files: Defer completed download file checks until first use - improves startup times but delays the discovery of inaccessible or incorrectly sized files

but currently not incomplete ones.

You might be able to disable ctrl+p by editting MessagesBundle.properties in BiglyBT.jar to remove

MainWindow.menu.transfers.pausetransfers.keybinding=Meta+P

**Comment by parg** [comment]
I could add an option to skip the checks for incomplete downloads I suppose, 20 minutes is quite a while...

**Comment by parg** [comment]
It'll be in B46

**Comment by as-muncher** [comment]
Why call it "allocating" then?  Whenever I've seen BiglyBT allocate, it creates all the subdirectories in a torrent (as of a recent beta) or create empty files with the incomplete file extension that I specify.   Right now, I've got an error "Failed to create parent directory '<where my torrent is saved>' (ALLOCATEFILES: <and then one of the files in my torrent>)
