### ISSUE TITLE
Prevent Tag from showing in Library?

### ISSUE THREAD

**Issue by drelephant** [BiglySoftware/BiglyBT#2619]
Not an issue, more of a question...

I usually have Library view open but I'd like to hide particular tags from clogging up that view.

Is there any way to prevent a particular tag's files from showing in the Library?

**Comment by parg** [comment]
You can type a Tag constraint into the filter box. For example, to exclude downloads that are assigned to a tag named "fred" type

!hasTag("fred")

Or you could create a separate tag with that constraint and switch to that tag's library view when wanted

**Comment by parg** [comment]
Nice answer my friend!

**Comment by drelephant** [comment]
Thanks for the detailed answer, looks like a great option.
