### ISSUE TITLE
Feature Request: Ignore files in specified subfolders

### ISSUE THREAD

**Issue by PrototypeZero** [BiglySoftware/BiglyBT#2622]
Would it be possible to add the feature to set files in certain folders to Delete/DND, ie Ignore the files in folders specified (using regex if possible to match slight variations just like the current ignore files does for just files)?

ie If a torrent contains files in a folder named "Cache" set the priority of all files in them to DND  automatically on add, but leave files elsewhere in the torrent to download.
The current Ignore files feature won't work for torrents I download as the files in the unwanted folder(s) are similar in name to files I want to download elsewhere in the torrents and I just want not to download the entirety of files in certain folders.

**Comment by parg** [comment]
If the match (or regular expression) starts or ends with a path separator then the match could be applied against the whole relative path rather than just the name?

**Comment by parg** [comment]
Well, maybe contains a file separator rather than starts/ends with one

**Comment by PrototypeZero** [comment]
Thanks parg.

That working fine. :D 👍

**Comment by parg** [comment]
yay
