### ISSUE TITLE
Show full text in tooltip

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2624]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.0.0.1_B47/4 az3

When I hover the mouse cursor over whatever, could you please show the full text in the tooltip?  I hover the tooltip over my torrent name, or over an error message, and can't see the full thing and I don't want to have to move the column width to the extreme in order to see it all.

**Comment by parg** [comment]
For me the tooltip shows the full text.

**Comment by as-muncher** [comment]
What exactly were you hovering the mouse cursor over?  Doesn't work for me.  If I look carefully, I see a lot of the text in the tooltip, but there is ... in the middle.

**Comment by parg** [comment]
Ah, you mean if the text is super-long. Yeah, there's a limit to the tooltip length.

**Comment by parg** [comment]
I'll add an option to disable it: Options->Interface->Tables: Truncate excessively long tooltips

**Comment by as-muncher** [comment]
Truncate it?  Why?  I opened this issue so that I could see the full text, not see a truncated version.  It's already truncated.

**Comment by as-muncher** [comment]
Thanks, I've been trying it out.  I'm encountering where the tooltip will reach the right-side of the screen.  Perhaps when showing the full tooltip, you can put it into a tooltip block with multiple lines instead of one super long line?  Maybe the tooltip block could be 100 characters wide, as a suggestion?

**Comment by as-muncher** [comment]
bump
Again, I'm noticing that the full tooltip won't fit in the width of the screen, but shows the last so many characters.  If you could find a way to show the full tooltip, but put it on multiple lines if need be, that would help.  Thanks!

**Comment by parg** [comment]
No

**Comment by as-muncher** [comment]
ok, but the purpose is somewhat defeated.  I'd have to turn on truncation to see the beginning of the text, and then turn it off to see the end.
