### ISSUE TITLE
question

### ISSUE THREAD

**Issue by johnvolfovits** [BiglySoftware/BiglyBT#2637]
hi
what's the purpose of boost and what's it doing
![boost](https://user-images.githubusercontent.com/107244103/178573613-39bedf8f-de25-4fec-a9dc-5d8bf313a8ed.png)

**Comment by parg** [comment]
When you "boost" a peer you set it as a "partial buddy" or  "partial friend" as it was renamed to at some point.

See View->Friends

A "full friend" is one that you have exchanged keys with, it is a symmetric relationaship where you both recognise when you are connected to each other and prioritise uploading/downloading to each other.

A "partial friend" is one-sided, you prioritise upload to the peer but they don't know anything about you.

When upload is prioritised by default LAN transfer rate limits are applied and the peer will get priority in terms of upload over other peers.

So, if for some reason you want to prioritise upload to particular peers then "boost" them.

**Comment by johnvolfovits** [comment]
thanks
