### ISSUE TITLE
Some errors should be evaluated every time BiglyBT starts up

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2638]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.1.0.1_B03/4 az3

Hi.  When there's an error, say, Failed to create parent directory ('my torrent save directory on an external drive' (ALLOCATEFILES: and then the name of one of those files in the torrent), is this re-evaluated every startup?  For instance, if my external drive is not attached, and so then BiglyBT can't create that directory, it seems currently that even if I re-attach the drive, make sure the proper drive letter is assigned, then restart BiglyBT, the error remains, so I wonder if BiglyBT is evaluating the error every startup, which I think would be helpful, as qbittorrent does.  That way, I don't have to re-check my entire torrent.

**Comment by as-muncher** [comment]
Hi, is there an estimated time of completion on this?  At least could you start with one error: "Failed to create parent directory"?  At least that one should be re-evaluated every time biglybt starts up, so that if I forgot to attach my external drive, I can just restart biglybt after I insert my external drive and make sure Windows has assigned it the correct drive letter.  As it is now, the error is there and then just stays there and I have to recheck all 150 GB or so.

Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.1.0.1_B11/4 az3

**Comment by parg** [comment]
Estimated time of completion? Infinite at the moment, I'm not working on it and don't plan to. You raise so many issues I tend to tune them out.

**Comment by as-muncher** [comment]
@parg That's funny.  Well, I know qbittorrent re-evaluates "can't create parent directory" errors on every startup.  I do raise issues, but they benefit everyone when they're fixed.  That's okay if you tune out my issues.  But I'm sure that others will raise them.

**Comment by as-muncher** [comment]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.2.0.1_B18/4 az3
still says data missing for data on external device that I forgot to plug in

So I find this is still happening, where I have a torrent saved to an external drive, and if I forget to plug in that device and start up biglybt, I get that "error data missing", which means I have to recheck the whole thing, even though I may plug in the device and restart biglybt.

**Comment by parg** [comment]
And you enabled

Options->Files: Periodically restart downloads that appear to have missing files

?

**Comment by as-muncher** [comment]
I'm so sorry.  I thought maybe that would be turned on by default and I didn't think to look for that option in the new beta.

**Comment by as-muncher** [comment]
@parg, Could you please consider making this turned on by default: to periodically restart downloads that appear to have missing files?  This recently happened again, where I started BiglyBT before my external hard drive was plugged in, which has the torrent data, and I got those missing data errors, meaning it took hours to recheck hundreds of gigabytes.  qBittorrent has it automatically, that if the same thing happens there, and you quit qbittorrent, plug in your hard drive and make sure Windows assigns the proper drive letter to it, then start qbittorrent again, starts up fine, don't have to recheck all the data.  I would think that BiglyBT would also have this on by default, so that all I'd need to do is the same process, start BiglyBT again, and everything's good.
