### ISSUE TITLE
how to make BiglyBT move data to external device still using sparse files instead of using Windows Explorer to copy

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2639]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.1.0.1_B03/4 az3

Hi.  You know how it is.  Sometimes there's only a small part of a file that's downloaded, say 4k of a 5 GB file, and then when you move the file to an external device, the whole 5 GB is copied.  It seems that BiglyBT is using Windows Explorer to do it that way, instead of using sparse files at the destination when I select in BiglyBT "Move to..."  Could you possibly see about fixing this?  I mean, yes, it's not broken, but it sure would be nice to save some space at the destination by using sparse files if possible.

**Comment by parg** [comment]
Sounds like something the underlying OS should do don't you think? Assuming you haven't enabled the "copy and delete across file systems" option then all BiglyBT does is ask the system to rename file A to file B.

**Comment by as-muncher** [comment]
I think the reason why I'm asking for this is still because of allocating happening, where BiglyBT makes all these shell files with the .!qB extension that have no data in it, and then when BiglyBT goes to move the thread over to external storage, files that are next to zero in real size are being copied over full, so there are hundreds of GB being copied over that don't need to be.  It seems that the allocating could be happening when "forced seeding" is happening or when a torrent goes from "seeding" to "forced seeding".

**Comment by parg** [comment]
compress the external drive?

**Comment by parg** [comment]
What allocating problem? The partial files have to be created to hold the overlapping piece data at file start/end. As you say, they're "next to zero in real size", not actually zero.

How would you recreate the sparse files? Does the destination drive support sparse files? You would have to create the file and then only write the parts that you know are used - i.e. it isn't a low-level operation, it would require knowledge at the torrent-file level, which blocks had been downloaded. Not impossible but not something trivial as I'm sure you believe it is.

**Comment by parg** [comment]
Also I just did a test. With sparse file allocation the .!qB files are allocated to contain just the data needed (i.e. piece data from start/end of file before/after) and then when moved still only contain that much data.

**Comment by as-muncher** [comment]
For some reason, it's not working on my computer.  Maybe it depends on the torrent.  I find that, many times if not all the time, all the files in the torrent are pre-allocated so there are all these empty files with the .!qB extension, and not as you say.  It's not happening for me where the files are just being created as they are being downloaded or created due to swarm merging.  Perhaps I will send you a screenshot.

**Comment by as-muncher** [comment]
I may have to use search for existing data files to possibly move from one location to the next, in order to create the sparse files.  I'm pretty sure sparse files is supported on my internal hard drive, but how would I know for sure?  Is there a program for that?

**Comment by parg** [comment]
No idea, you can search the internet just as well as me
