### ISSUE TITLE
"Please seed" messages

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2640]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.1.0.1_B03/4 az3

Hi, I know I sometimes get "Please seed" messages from my own BiglyBT on my computer.  But not once have I ever received those messages from someone else's BiglyBT.  I guess it makes sense for me to see those messages if they're going out.  But if I'm not getting those from others' computers, is anybody actually getting mine?

**Comment by parg** [comment]
Yes, if they bother to check their download messages.

**Comment by as-muncher** [comment]
I almost don't even want to read my own "please seed" messages.

**Comment by parg** [comment]
don't then. 

View->Friends->Decentralized Chat: Enable automatic generation of/checking for download-specific messages

**Comment by as-muncher** [comment]
I still have never ever seen a message from someone asking to seed a certain torrent.  I'd like to.
