### ISSUE TITLE
how to show overhead / tell if network is being fully utilised

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2642]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.1.0.1_B06/4 az3

Is there a way of telling if the network is being fully utilised, and how much bandwidth is being spent not on actually downloading but on making connections etc.?  Sometimes I see low download speeds and I don't know if it's due to the seeders not being able to send the data fast enough, or if it's a problem on my end.

**Comment by parg** [comment]
BiglyBT doesn't know enough about the network - you'd need some other tool to figure something like that out (don't ask me what, I don't know, but for TCP for example it would need to be able to show details about window sizes and packet loss)
