### ISSUE TITLE
Dark mode graph-legend issue

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#2648]
I noticed a minor issue with the dark-palette rendering of graph views (like, for instance, the Tools > Statistics > Tracker graphs) that graph multiple data points which can be individually enabled/disabled in the graph legend.

When you click a legend item once to disable it, the label turns from white to gray. When you click a _second_ time to re-ENABLE it, the text turns from gray to black instead of gray to white. For example, in this graph I've disabled and then reenabled the green "Scrapes" line:

![image](https://user-images.githubusercontent.com/538020/179430410-e9ebd07f-634b-4aa9-bbde-5ed4ef458e23.png)

#### System block
```
Java 11.0.15 (64 bit)
  Red Hat, Inc.
/usr/lib/jvm/java-11-openjdk-11.0.15.0.10-1.fc36.x86_64

SWT v4942r22, gtk/3.24.34, zoom=100, dpi=96
Linux v5.17.12-300.fc36.x86_64, amd64 (64 bit)
B3.1.0.1_B07/4 az3
```

**Comment by parg** [comment]
Thanks!

**Comment by ferdnyc** [comment]
Fixed!
