### ISSUE TITLE
How to remove auto-restart notification?

### ISSUE THREAD

**Issue by Kanishk-Kumar** [BiglySoftware/BiglyBT#2649]
Please add an option to remove it.
![image](https://user-images.githubusercontent.com/45518770/179939757-80d367d5-dbef-4e5f-a607-4ec16b816958.png)
Windows 10
BiglyBT Version 3.1.0.0

**Comment by parg** [comment]
or do you want the feature but just hate the notification?

**Comment by Kanishk-Kumar** [comment]
I want the feature but just hate the notification.

**Comment by parg** [comment]
OK, option will be added in beta version B3101_B9
