### ISSUE TITLE
Exit-confirmation dialog broken in latest beta?

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#2653]
The changes to the exit confirmation for update restarts may have had some collateral damage, because running _B09, I _didn't_ get a confirmation just now after clicking the window Close button to exit BiglyBT — despite having the confirmation dialog setting enabled in Options > Interface. BiglyBT just shut right down immediately.

#### System block
```text
Java 11.0.15 (64 bit)
  Red Hat, Inc.
/usr/lib/jvm/java-11-openjdk-11.0.15.0.10-1.fc36.x86_64

SWT v4942r22, gtk/3.24.34, zoom=100, dpi=96
Linux v5.17.12-300.fc36.x86_64, amd64 (64 bit)
B3.1.0.1_B09/4 az3
```

**Comment by parg** [comment]
oops :)

**Comment by ferdnyc** [comment]
Fixed in B10. :+1:
