### ISSUE TITLE
Dark palette issue: Statistics > Transfers > Routing tab

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#2658]
Another text-background issue in dark mode, lurking in the Transfers tab of the Statistics view. The Connections graph is fine, but switch to the Routing (sub-)tab and you get this:

![image](https://user-images.githubusercontent.com/538020/180777957-3d4d553a-311e-48b5-a242-3cc9acb62862.png)

There's actually incredibly-light-gray-on-white text there that I can faintly _detect_, but not even remotely read.

#### System block
```text
Java 11.0.15 (64 bit)
  Red Hat, Inc.
/usr/lib/jvm/java-11-openjdk-11.0.15.0.10-1.fc36.x86_64

SWT v4942r22, gtk/3.24.34, zoom=100, dpi=96
Linux v5.17.12-300.fc36.x86_64, amd64 (64 bit)
B3.1.0.1_B02/4 az3
```

(Ignore the _B02, it's actually a build artifact generated from the CI for PR #2656, based on post-_B11 sources.)

**Comment by parg** [comment]
I'll fiddle with it, ta

**Comment by ferdnyc** [comment]
@parg 

Oops, have a second one, though this may not be the correct repo: The Swarm Discoveries "Welcome" dialog contents are rendered in white-on-white (except for the hyperlinks), in dark mode.

**Comment by parg** [comment]
This one?

![image](https://user-images.githubusercontent.com/395293/180964550-8b8d5899-93ac-4c9f-a7f6-7453b51b711b.png)

looks ok to me :)

**Comment by ferdnyc** [comment]
@parg 

Whoops! My version of the plugin was way out of date. I forgot that because BiglyBT doesn't update unloaded plugins. (Maybe there should be an automatic update check — if update checking is enabled — immediately after a manual load is done?)
