### ISSUE TITLE
webtorrent plugin doesn't install after I install Java 11+

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2660]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.1.0.1_B11/4 az3

I tried to install the webtorrent plugin from the plugins website, and was told that it requires Java 11+.  I went and downloaded Java 18.0.2 for Windows, 64-bit, and installed it.  When I restarted BiglyBT, it says that it still could not install azwebtorrent, that it requires Java 1.11 or higher.  But I remember doing this yesterday, and the webtorrent plugin installed.  webtorrent 1.4.1_CVS  Maybe it actually didn't install yesterday.  And after I installed Java 18.0.2, I still get the above Java version quoted by BiglyBT.

**Comment by as-muncher** [comment]
I tried installing 17.0.4, same issue.  I still get the error in BiglyBT "Plugin azwebtorrent requires Java version 1.11 or higher".  What do I need to do?

**Comment by parg** [comment]
Your "system block" shows you're running Java 1.8 from c:\program files\biglybt\jre

Delete c:\program files\biglybt\jre

**Comment by as-muncher** [comment]
Java 18.0.2 (64 bit)
  Oracle Corporation
c:\program files\java\jdk-18.0.2

SWT v4942r22, win32, zoom=100, dpi=120
Windows 11 v10.0, amd64 (64 bit)
B3.1.0.1_B12/4 az3

Thank you, it installed.

**Comment by as-muncher** [comment]
But in Brave, Brave ends up using its own webtorrent thingy in a non-private window, instead of BiglyBT's.  I'd like to use BiglyBT's.

**Comment by parg** [comment]
WTF is Brave?

**Comment by as-muncher** [comment]
@parg Brave is a web browser.

**Comment by parg** [comment]
You expect Brave to use BiglyBT's implementation of webtorrent? Not going to happen!

**Comment by as-muncher** [comment]
I was hoping for some sort of solution so that I could still torrent over networks that block torrent traffic, even if it is encrypted.  I thought maybe there was a BiglyBT chrome plugin or firefox plugin that could connect with BiglyBT on the system or if I can't run BiglyBT on the system, to run independently.  So I guess I would have to use Chrome?  How does one use the BiglyBT webtorrent plugin?  If I'm running BiglyBT and all the connections are blocked, will it automatically start using the webtorrent plugin to work that way?

**Comment by parg** [comment]
It'll use webtorrent for torrents that have webtorrent trackers (ws:// or wss:// urls) - see https://openwebtorrent.com/ for example
