### ISSUE TITLE
Window position in multimonitor setup wrong after unminimize

### ISSUE THREAD

**Issue by de-served** [BiglySoftware/BiglyBT#2661]
* OS and version: tested on 3 Win10 machines + 2 VM's; Win10 1809...21H2
* BiglyBT Version Number: Any version, including 3.1.0.0
* Multimonitor config 1: DISPLAY0 0,0-1920,1080; DISPLAY1 1920,0-3840,1080; DISPLAY2 -1920,0-0,1080
* Multimonitor config 2: DISPLAY1 0,0-1920,1080; DISPLAY2 1920,0-3840,1080; DISPLAY0 -1920,0-0,1080
* Multimonitor config 3: DISPLAY1 0,0-1920,1080; DISPLAY0 1920,0-3840,1080; DISPLAY2 -1920,0-0,1080
* Config settings: Start BiglyBT minimized.

1. Start BiglyBT.
2. Move to main/center monitor (0,0-1920,1080) and resize to a maximum possible for current monitor (not by maximize but by dragging borders of the window, for example 0,0-1920,1052)
3. Close/exit BiglyBT or Minimize it and exit from icon in statusbar.
4. Start BiglyBT. Unminimize BiglyBT.
5. Result - BiglyBT starts at leftmost monitor (-1920,0-0,1080)

Must be started at the same position with same size when it was closed if position/size is in the range of available desktop space.

PS: it is possible that this is because "padding" of "win 10" windows. BiglyBT opens at leftmost monitor with 3 px paddings at left/right/bottom sides.

**Comment by parg** [comment]
Meh, stupid Windows lying about things. I'll hack in some slack in the verification tests.
