### ISSUE TITLE
Windows 11 hibernation issue

### ISSUE THREAD

**Issue by dimalif** [BiglySoftware/BiglyBT#2662]
Hi.
I use Windows 11pro/64 latest. Also i use Biglybt latest beta.

I have set my Windows 11 to hibernate in 15 minutes. The thing is BiglyBT doesn't seem to matter and while i'm downloading a linux release ..... Windows go to sleep. 

I have the SLEEP option of Biglybt to prevent this when downloding enabled but it seems not to matter.

Any ideas?

**Comment by dimalif** [comment]
Als this verifies my problem:
![2022-07-29 21_19_59-Administrator_ Windows PowerShell](https://user-images.githubusercontent.com/53921528/181820826-0496f99e-4309-4274-9074-e23425f882bb.png)

**Comment by parg** [comment]
BiglyBT resets the sleep-idle-timer every 30 seconds when attempting to prevents sleep via setThreadExecutionState( SYSTEM_REQUIRED).

Not sure how you can see that in powershell or whatevs

**Comment by dimalif** [comment]
Well, it doesn't work right. It Hibernates. You are the boss, you know why and the details.

**Comment by dimalif** [comment]
https://stackoverflow.com/questions/72436579/setthreadexecutionstatees-system-required-does-not-prevent-system-sleep-on-win

**Comment by parg** [comment]
Try the next beta (B14)

**Comment by dimalif** [comment]
B14 seems to work just fine, all night. No issues.

Thank you

**Comment by parg** [comment]
Nice!
