### ISSUE TITLE
Add magnet url from clipboard using only the keyboard?

### ISSUE THREAD

**Issue by drelephant** [BiglySoftware/BiglyBT#2663]
When I have a magnet link in the clipboard, and I press `Ctrl-U` to add it, the magnet link is automatically in the box which is good.

Unfortunately it also highlights and selects the text, so if I try to press `Enter` to choose `OK`, it just replaces the magnet text with a carriage return.

Even if I press tab it replaces the magnet text with a tab character.

Is there any way I can add a magnet link that is in the clipboard without having to use the mouse at all?

Ideally I'd like to just press `Ctrl-U`, then `Enter`.

**Comment by parg** [comment]
ctrl+enter?

**Comment by drelephant** [comment]
Thanks! Worked.

What's ctrl+enter?

**Comment by parg** [comment]
https://github.com/BiglySoftware/BiglyBT/issues/2545

**Comment by ballo** [comment]
Neither urls not file names have carriage returns, thus having to use Ctrl is nonsensical

**Comment by parg** [comment]
you are nonsensical
