### ISSUE TITLE
Failed to load module "canberra-gtk-module"

### ISSUE THREAD

**Issue by gyurmogyuri** [BiglySoftware/BiglyBT#2665]
^^>>> flatpak run com.biglybt.BiglyBT                                                                            13:20:34 
Starting BiglyBT...
Suitable java version found [java = openjdk 11.0.14 2022-01-18]
Using swt/swt-x86_64.jar v4.942
Processing config presets: /app/biglybt/custom/custom-presets.config
        update.periodic -> bool:false
        update.start -> bool:false
Presets applied
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.biglybt.core.util.spi.AENameServiceJava9 (file:/app/biglybt/BiglyBT.jar) to field java.net.InetAddress.impl
WARNING: Please consider reporting this to the maintainers of com.biglybt.core.util.spi.AENameServiceJava9
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Gtk-Message: 13:21:18.106: Failed to load module "canberra-gtk-module"
Loading BiglyBT:
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.biglybt.core.util.spi.AENameServiceJava9 (file:/app/biglybt/BiglyBT.jar) to field java.net.InetAddress.impl
WARNING: Please consider reporting this to the maintainers of com.biglybt.core.util.spi.AENameServiceJava9
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Processing config presets: /app/biglybt/custom/custom-presets.config
        update.periodic -> bool:false
        update.start -> bool:false
Presets applied
DEBUG::Sat Jul 30 13:21:25 CEST 2022  Successfully migrated key management
Gtk-Message: 13:21:26.065: Failed to load module "canberra-gtk-module"
UIFunctions/ImageLoad took 0ms
new shell took 100ms
new shell setup took 51ms
skin init took 50ms
MainMenu init took 50ms
pre skin widgets init took 25ms
skin widgets (1/2) init took 176ms
skin widgets (2/2) init took 50ms
pre SWTInstance init took 0ms
Init Core Columns took 50ms
SWTInstance init took 0ms
shell.layout took 0ms
---------SHOWN AT 1659180086726;719ms
---------DONE DISPATCH AT 1659180087002;995ms
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
DEBUG::Sat Jul 30 13:21:27 CEST 2022  com/sun/jna/Callback
---------READY AT 1659180087077;1070ms
shell.open took 351ms
processStartupDMS took 0ms
postPluginSetup init took 0ms
Locale Initializing took 0ms
DEBUG::Sat Jul 30 13:21:27 CEST 2022  Successfully migrated key management
Core Initializing took 401ms
java.net.SocketException: A hálózat elérhetetlen
        at java.base/sun.nio.ch.Net.connect0(Native Method)
        at java.base/sun.nio.ch.Net.connect(Net.java:483)
        at java.base/sun.nio.ch.DatagramChannelImpl.connect(DatagramChannelImpl.java:851)
        at lbms.plugins.mldht.kad.utils.AddressUtils.getDefaultRoute(AddressUtils.java:221)
        at lbms.plugins.mldht.kad.DHT.start(DHT.java:734)
        at lbms.plugins.mldht.azureus.MlDHTPlugin$9.runSupport(MlDHTPlugin.java:670)
        at com.biglybt.core.util.AsyncDispatcher$1.run(AsyncDispatcher.java:168)
        at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:334)

**Comment by ferdnyc** [comment]
@gyurmogyuri 

libcanberra is the Gtk sound "effects" module, it's used for playing audio feedback for GUI events (login/logout sounds, window effects, mouse clicks, etc.) It's fine for BiglyBT not to be able to load it, at worst you won't get interface sounds that would otherwise be played — but presumably, if libcanberra isn't installed on your system, you aren't expecting to have those anyway.

You didn't mention what distro you're using, and there don't seem to be any hints in the log you posted. But if you **_want_** the canberra module to be loaded, you'd want to install whatever package contains `libcanberra-gtk3.so.0`. On Fedora/CentOS/RHEL that's `libcanberra-gtk3.rpm`, though on Debian-derived it'll probably be named something like `libcanberra0gtk3`.

But the missing module is not a _problem_, per se, for BiglyBT. It's just triggering a notice that some non-essential functionality (sound effects) will not be available.

**Comment by ferdnyc** [comment]
> You didn't mention what distro you're using

(Please try to include the contents of the "System" box from Help > AboutBiglyBT when filing bug reports, as the new issue form requests. There's a handy "Copy" button there that will copy the entire contents to the clipboard, for easy pasting. That gives us all of the information needed to help solve any problems reported.)
