### ISSUE TITLE
Adding new torrent deletes the most recently completed torrent (which is being seeded).

### ISSUE THREAD

**Issue by Kanishk-Kumar** [BiglySoftware/BiglyBT#2668]
Could be something to do with the AutoPilot plugin. But is definitely a bug. Should I upload a log file or something? If yes, please tell how. Thanks.

Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.1.0.0/4 az3

**Comment by parg** [comment]
BiglyBT itself doesn't have many options to auto-remove torrents, the one that comes to mind is Tag based and requires you to configure the Tag explicitly to do so which doesn't sound as if you have done.

I don't know Auto Pilot very well but it does have a "remove when complete" option, if you think it is that and you have enabled that option then perhaps that is it.

**Comment by Kanishk-Kumar** [comment]
Yes seems to be an AutoPilot bug. I'd configured it to delete torrents once seed ratio hits 2.0. But whenever I add a new torrent, it deletes the most recently completed one which is being seeded with ratio <2.0 (0.003 in today's case). Hoping it gets fixed.🙏🏻

**Comment by parg** [comment]
I don't use or particularly want to maintain the plugin but I think it is behaving as the designer of it wanted. If you have

`Options->Plugins->AutoPilot: Stop seeding when there are one or more incomplete torrents queued for download`

enabled then that will stop seeding downloads when you add a new download to the queue and once the download is stopped it is considered "complete" and will therefore be removed if you have

`Options->Plugins->AutoPilot: Remove when complete`

enabled...

**Comment by Kanishk-Kumar** [comment]
That's exactly what happened. Thanks for clearing it up. Disabled both of those options now.
