### ISSUE TITLE
new files are not being created with extension for incomplete files

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2669]
Java 17.0.4 (64 bit)
  Oracle Corporation
c:\program files\java\jdk-17.0.4

SWT v4942r22, win32, zoom=100, dpi=120
Windows 11 v10.0, amd64 (64 bit)
B3.1.0.1_B14/4 az3

Add suffix to incomplete files: and I have it as ".!qB" without the quotation marks.
New files are not being created with that extension.

**Comment by parg** [comment]
This a new problem? Nothing's changed

**Comment by as-muncher** [comment]
This is fairly new, within the last month, I think.

**Comment by parg** [comment]
Works for me with a simple test. Must be something else going on. The setting only applies to downloads that have been added to BiglyBT with it enabled, changing it later doesn't affect already added downloads.

**Comment by as-muncher** [comment]
If I add .torrent files, then the extension is added.  But I recently added a magnet link, which then saved the .torrent file and started downloading, and the contents of the directory allocated (shell files) with no added incomplete extension.

**Comment by parg** [comment]
Maybe you exceeded

**Comment by as-muncher** [comment]
As I mentioned in my email, if I open the magnet link, then unmark all, then search for "jpg" and then mark all those for download, then search for "compilation", and mark those, when I look at all the shell files that are still being created, none of them have the .!qB extension added, but when I add .torrent files, all those created files have the .!qB extension, so it can't be that I've exceeded the maximum file links, seeing that you said that those files with .!qB extension are considered file links.

**Comment by as-muncher** [comment]
and even still, doing this with a different magnet link / torrent, the .!qB extension is being added, so it must be something with the specific magnet link I sent you, so if you could please look at that and tell me why this is happening or fix the problem, that would be appreciated.

**Comment by parg** [comment]
Can you send the magnet again, I can't seem to find it

**Comment by parg** [comment]
The torrent has > 2048 files

With 

Options->Files: Maximum file links per download

set to the default of 2048 the extension is not added, as you report. This is as designed

If you increase

Options->Files: Maximum file links per download

to, say, 4096, the extension is added.

**Comment by as-muncher** [comment]
Oh.  I thought you meant all files being handled by biglybt.  I didn't pay attention to it as "maximum file links per download".  Ok, thanks for looking into this for me.
