### ISSUE TITLE
Invalid Save Location strangeness

### ISSUE THREAD

**Issue by ggowins** [BiglySoftware/BiglyBT#2673]
* Ubuntu 20.04.1
* BiglyBT 3.1.0.0
* For *nix: Desktop Environment:  Cinnamon

So this is a weird one.  I'm using BiglyBT on linux, and my torrents get saved to an NFS mount point.  After I upgraded TrueNAS from 12 to 13, I now get "Invalid Save Location" when downloading a torrent. But on the next window that opens after I click OK, when I select the exact same location as in the error message, it downloads fine.  Any clues on what to look for?    I'm guessing there is some strange permission change that was introduced on the new TrueNAS version, but no clue why it works in one place in the app, but not another.

**Comment by parg** [comment]
Can't see how permissions would affect exactly the same save path in one place and not another! How is the invalid save location being selected? Is it the default in 

Options->Files: Default directory:

?

**Comment by ggowins** [comment]
yeah, I have it defined there as `/mnt/savehere` and that is what is shown in the initial Invalid Save Location message.  When I click ok, the save location in the new window is blank, and when I use  `/mnt/savehere` there it works fine.

**Comment by ggowins** [comment]
I am certain it isn't a BiglyBT issue, as it was working fine before I upgraded my TrueNAS server.   But so far this app is the only one that is working differently after the upgrade.  Might be a timing issue with writing to the NAS location.

**Comment by ggowins** [comment]
It was something with the TrueNAS upgrade.  I deleted the share and recreated it, and the BiglyBT issues went away.   Very strange one.
