### ISSUE TITLE
Support .deb file

### ISSUE THREAD

**Issue by dtantono** [BiglySoftware/BiglyBT#2678]
* OS and version: Ubuntu 20.04
* BiglyBT Version Number 3.1
* For *nix: Desktop Environment: GNOME
* Hi,
Linux beginners tend to use Debian based distros. So, for the sake of ease of installation. Is it possible to support deb file?

**Comment by parg** [comment]
We haven't ventured into linux distro packaging for any of the variants as we don't have the resources :(

**Comment by legacychimera247** [comment]
as much as i would love an rpm i would say they provided linux installer is damn easy to use, and anyway, althought i find the version provided here to me more responsive, someone also done a flatpak of the app, easisly findable on flathub...

**Comment by ferdnyc** [comment]
> someone also done a flatpak of the app, easily findable on flathub...

Of course, naturally Canonical backed Snap instead. :roll_eyes:
