### ISSUE TITLE
Javascript plugin only works on Java8 but not on higher versions

### ISSUE THREAD

**Issue by gh338** [BiglySoftware/BiglyBT#2679]
* Kubuntu 20.04
* BBT 3.1.0.1_B7 ( and any lower version )
* KDE

Javascript plugin only works on Java 8.
Higher versions including LTS ones do not work.

**Comment by parg** [comment]
BiglyBT officially supports Java 8.

The Java developers decided to remove JavaScript support unfortunately, there is no current work around for this.

https://openjdk.org/jeps/372#:~:text=The%20deprecation%2Dfor%2Dremoval%20of,in%20JDK%2014%20and%20beyond.

**Comment by gh338** [comment]
Could you add an option to have manual tags assign networks ?

Cheers

**Comment by parg** [comment]
You can using the SimpleAPI plugin from a script - https://github.com/BiglySoftware/BiglyBT/wiki/Plugins

There's even an example there on how to set networks:

plugin( simpleapi, "method=setnetworks&networks=I2P" )
