### ISSUE TITLE
BiglyBt renames files inside of torrent from double quotes to single quotes

### ISSUE THREAD

**Issue by AnimusPEXUS** [BiglySoftware/BiglyBT#2680]
I don't know why it's happening, but looks like BiglyBt treats filenames with double quotes as filenames with single quotes.

For instance, if I have directory `123` and file `cool "very" name.txt` in it and create new torrent using BiglyBt's torrent creation tool, the resulting file is ok and contains name with double quotes (I've checked this with Fedora's 'Torrent File Editor' app). but if I add this new torrent file to BiglyBt and trying to seed, BiglyBt says it can't find file `cool 'very' name.txt`.

**Comment by parg** [comment]
Hmm, maybe 

Options->Files: Character conversions for torrent files [, separated]

**Comment by AnimusPEXUS** [comment]
yes, deleting everything (`"='`) from this field helped

**Comment by parg** [comment]
Obviously it isn't great that BiglyBT can't seed a torrent it creates with the default options though :(

**Comment by AnimusPEXUS** [comment]
thanks again. I'm ok to close issue.
