### ISSUE TITLE
Network testing is broken

### ISSUE THREAD

**Issue by trancephorm** [BiglySoftware/BiglyBT#2681]
Java 11.0.16 (64 bit)
  Ubuntu
/usr/lib/jvm/java-11-openjdk-amd64

SWT v4942r22, gtk/3.24.20, zoom=100, dpi=144
Linux v5.4.0-124-generic, amd64 (64 bit)
B3.1.0.0/4 az3

TCP is reported not functional in "Network Status>Inbound connections", but they are, I just tested it from the outside with telnet. My port forwarding is setuped correctly.

NAT / Firewall test passes OK.

**Comment by parg** [comment]
What error is reported?

**Comment by trancephorm** [comment]
Test starting
Default public address is 185.123.143.222
Bindable addresses: 10.108.102.246, 192.168.100.2, 127.0.0.1, 172.17.0.1
No explicit bind address set
Testing TCP port 56732 inbound
    Test failed: NAT test failed: Connection to x.x.x.x:56731 (your computer) refused
    Check your port forwarding for TCP 56731
Testing UDP port 56731 inbound
    Sending outbound packet and waiting for reply probe (timeout=5000)
    Sending completion event
    Test successful
1 public/external addresses found
    185.123.143.222
    AS details: as=9009,asn=M247, GB, bgp_prefx=185.123.142.0/23[/185.123.142.0-/185.123.143.255]
Test complete

**Comment by parg** [comment]
Microsoft Windows [Version 10.0.19044.1865]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Paul>telnet 185.123.143.222 56731
Connecting To 185.123.143.222...Could not open connection to the host, on port 56731: Connect failed

C:\Users\Paul>

**Comment by parg** [comment]
Microsoft Windows [Version 10.0.19044.1865]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Paul>telnet 185.123.143.222 56731
Connecting To 185.123.143.222...Could not open connection to the host, on port 56731: Connect failed

C:\Users\Paul>

**Comment by trancephorm** [comment]
That is not my port number, I intentionally changed it in this post.

**Comment by parg** [comment]
Well here's the log from the BiglyBT net-test server earlier:

[15:26:13] 185.123.143.222:56713 -> Connection to 185.123.143.222:56713 (your computer) refused (as=9009,asn=M247, GB,locale=en)

**Comment by parg** [comment]
and here's the result from me testing now

C:\Users\Paul>telnet 185.123.143.222 56713
Connecting To 185.123.143.222...Could not open connection to the host, on port 56713: Connect failed

**Comment by parg** [comment]
and 
[15:26:44] UDP NAT: 185.123.143.222:56452 -> Timeout (as=9009,asn=M247, GB,locale=en)

so I don't know what you're up to

**Comment by trancephorm** [comment]
Yeah, surely at one point it didn't work because I was experimenting. Now you made me look like I'm fooling around. Surely it's not that case, I will let you enter my desktop if you want, so I can show you. Thing is I'm travelling in an hour, if you're interested, you can contact me here in about 10 days.
