### ISSUE TITLE
Windows 10 case sensitivity enabled directories and torrents with "duplicate" files

### ISSUE THREAD

**Issue by arandomusertoo** [BiglySoftware/BiglyBT#2684]
So I have a torrent containing several "duplicate" files like:

`file 1.txt`
`File 1.txt`

On windows 10, I've enabled case sensitivity (https://docs.microsoft.com/en-us/windows/wsl/case-sensitivity) on all the folders BiglyBT uses.

However, BiglyBT seem to ignore the case sensitivity support and continues to error out with the "File occurs more than once in download" message.

Realistically, assuming that the directories used by BiglyBT support case sensitivity, it should allow the torrent to start downloading after the allocation process.

Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B3.1.0.0/4 az3

**Comment by parg** [comment]
There is an old assumption baked into the code that Windows doesn't support case-sensitive file systems. I suppose I can remove this, try the next beta (B20)

**Comment by arandomusertoo** [comment]
All good, no rush on my part or anything, just letting you know.
