### ISSUE TITLE
Question: The numbers of seeders and leechers in the web interface includes you or not?

### ISSUE THREAD

**Issue by DumbJoe** [BiglySoftware/BiglyBT#2687]
For example here: 
![image](https://user-images.githubusercontent.com/36319788/186069718-1710256e-ff1b-4174-8216-083113e8cd66.png)

In the the "Seeders:" part, if there's one, and you're in seeding queue or currently seeding, would that be you or someone else? Same with the "Leechers:" part - if you're currently downloading or just waiting for downloading, that adds one to the tracker or omits you? And if there is more than one tracker, which one do you belong to if you are included in the count?

Speaking of this interface, I notice that it no longer keeps track of downloads, announcements or last scrapes, as that now shows N/A where as before it would show the actual number of downloads, announcement(s) since (and when the next one is) and time of last scrape...

Also, what's the difference between scrape and announcement? Just for my information, that's all.

Thanks!

**Comment by parg** [comment]
I'll fix up a couple of those TODOs

**Comment by DumbJoe** [comment]
So using this other example of a torrent's tracker tab (where I've edited the 5 trackers to Tracker 1, 2, 3, 4, and 5 to simplify it slightly) where I am currently seeding:
![image](https://user-images.githubusercontent.com/36319788/186140740-f2541d7b-e84f-4fe4-866c-c1208066fcd3.png)
There should at least be 1 in "Seeders" or 1 added to whatever seeder count was before, in all trackers? And if that's the case, how come Tracker 1 has seeders at 0? What about LAN, the two Plugins, PEX and Incoming trackers? 

And also the opposite should be true if I were to download from this torrent, at least 1 in "Leecher" count or 1 added to whatever count the leecher was on before in all trackers? And then when I stop the torrent, the "Seeders" count should be 0 since apparently I'm the only one seeding for all trackers?

So what's Peer cache used =70, DHT, plugin, plugin, PEX and Incoming? I presume the two plugin trackers is I2P and TOR? But which is which if that's the case? Are you able to distinguish between them with the plugin names instead of "Plugin"? LAN should be self explanatory, that's for when if there are other BiglyBT clients also running on the same network (same external IP but different internal IP) whose also happen to be seeding or leeching the same torrent, right?

Whoa, it looks like you got a lot of TODO's on there!

Thanks for explaining the difference between announce and scrape!

**Comment by parg** [comment]
Tracker 1 is not active.

**Comment by DumbJoe** [comment]
Can you also answer (or confirm) the other questions too please?

Is there a way to enforce encryption for all connections? I presume the encryption also doubles as a data integrity check per piece?

**Comment by parg** [comment]
Not at the moment, I'm busy
