### ISSUE TITLE
Support BEP-55 Holepunch extension

### ISSUE THREAD

**Issue by L2501** [BiglySoftware/BiglyBT#2690]
With more and more people behind NATs due to IPv4 exhaustion and VPNs due to scary letters being connectable is not a given anymore.
[BEP-55 Holepunch extension](http://bittorrent.org/beps/bep_0055.html) is one attempt to help connectivity.

Other clients supporting BEP-55:
- µTorrent
- BitComet
- libtorrent based (qBitTorrent, Deluge)

**Comment by parg** [comment]
I'll take a look

**Comment by parg** [comment]
Beta 3101_B25 has some support for it

**Comment by L2501** [comment]
Seeing some incoming uTP connections so I guess it is working, btw the status flags on web interface are wrong i think.

**Comment by parg** [comment]
Hmm, what is your issue with the status flags?

**Comment by parg** [comment]
Looks like it never has been, I'll fix that
