### ISSUE TITLE
Drag of torrent to new position in "Incomplete" view no longer works

### ISSUE THREAD

**Issue by david-bakin** [BiglySoftware/BiglyBT#2691]
[Windows Server 2016, BiglyBT Beta 3.1.0.1_B24]

Click-then-drag of torrent to new position in "Incomplete" view no longer works.  Just does nothing.  Up/Down arrows does work to reposition selected torrent.

Just noticed this, either this version or the one before.

**Comment by parg** [comment]
Works for me (tm) . Make sure you are sorting by "position"

**Comment by david-bakin** [comment]
Yes, sorting by column named "Order".  I don't think I've changed anything.  Are there any options that may affect this?

**Comment by parg** [comment]
Not that I know of - very strange

**Comment by david-bakin** [comment]
Also sometimes the bug is back where when you select a torrent (in incomplete view) and hit the up (or down) arrow to reposition it one step then the arrow goes grey (instead of remaining green) and you have to deselect the torrent and select it again to get it active again.  I wish I knew why these are occurring now - I'm _sure_ I haven't changed anything ...

**Comment by david-bakin** [comment]
Came back, around B28.  Don't know why.

**Comment by david-bakin** [comment]
And ... it came back.  3.2.0.1_B21.  Java 1.8.0_181. WinSvr 2016.

**Comment by david-bakin** [comment]
And ... it came back.  Can't drag torrents with mouse, "incomplete view", while sort column is "Order".  3.2.0.1_B21.  Java 1.8.0_181. WinSvr 2016.
