### ISSUE TITLE
remote pairing is not available, also on local network

### ISSUE THREAD

**Issue by legacychimera247** [BiglySoftware/BiglyBT#2694]
everytime i try to do a remote pairing, biglybt says it can't do remote pairing, and that's fine cause i can't open my ports, but shouldn't be able to do it at least on my local connection?

it would be nice to control biglybt when in another room, but no code is shown telling me i can only do the remote pairing on the local connection

on a sidenote, has the android client been , well, abandoned?cause no one is replying to it's github anymore :)

**Comment by L2501** [comment]
you can use the webui without pairing see "Manual Password" section in  https://wiki.vuze.com/w/Setup_WebUI_without_GUI

**Comment by legacychimera247** [comment]
yes, but on a phone i would still use the app which will ask for the pairing code...
