### ISSUE TITLE
remove defaults search templates or at least filter them permanently

### ISSUE THREAD

**Issue by legacychimera247** [BiglySoftware/BiglyBT#2695]
hello, when using the search function it would be nice if we could remove some search sites permanently,

i know we can filter them but everytime we do a new search they are enabled again, so it would be nice to have those removed or at least unchecked permanently

by the way, is the vuze search template really necessary considering the vuze network is quite abandoned now?

**Comment by parg** [comment]
Tried the "Add/Edit Templates" button?

**Comment by legacychimera247** [comment]
Yes but cannot remove those, can only remove custom ones

**Comment by parg** [comment]
Deselecting the "Use sites popular with Vuze users" at the top and hitting "Save" works for me

**Comment by legacychimera247** [comment]
oh yes, exactly what i was looking for...
