### ISSUE TITLE
Unknow PeerID AD 14.0.2.0 Advanced Download Manager

### ISSUE THREAD

**Issue by L2501** [BiglySoftware/BiglyBT#2698]
Advanced Download Manager https://play.google.com/store/apps/details?id=com.dv.adm&gl=US
Android torrent client based on Frostwire/jlibtorrent
They use a Static ID for all version
in their code:
```
libtorrent.generate_fingerprint("AD", 14, 0, 2, 0)
```

**Comment by parg** [comment]
Can't be bothered to keep up with all these libtorrent clones

**Comment by L2501** [comment]
"Unknown AD 14.0.2.0" / "ADM 140007"
"Unknown AD 11.5.6.0" / "ADM 110506"

**Comment by parg** [comment]
Like I said.

They should register a proper client name rather than ADM xxyyzz.
