### ISSUE TITLE
right click menu

### ISSUE THREAD

**Issue by legacychimera247** [BiglySoftware/BiglyBT#2699]
Hello, sometime ago i've done a right click on a torrent and instead of the usual menu with the "control, organize, content and social" tabs i had a menu without tabs that was much longer and easier to understand. Anyway after a reboot that menu was gone and the usual one was back, wonder if there is a way to have this menu back?tried setting the rookie settings but wasn't that

any hint?or was i just dreaming? :P

**Comment by parg** [comment]
You did a double-right-click

**Comment by parg** [comment]
There is "Options->Interface->Tables: Show Fancy Menu (Requires Restart)" as well

**Comment by legacychimera247** [comment]
exactly what i was looking for, thank you...
