### ISSUE TITLE
Add as "Downloading metadata" and...

### ISSUE THREAD

**Issue by SamSmith90** [BiglySoftware/BiglyBT#2703]
BiglyBT doesn't have the bandwidth prioritization ability for each torrent which is handy as low-medium-high and instead works on priority by the number of the torrent which doesn't work well on 7,000 torrents and not always one wants prioritization so they must make it like in Bittorrent and uTorrent and qBittorrent to choose only when you want low-medium-high for each torrent and for each file/folder in each torrent (this exists in BiglyBT). BiglyBT mustn't show the popup of install "web downloader" (something like that), once I pressed install (allow also "never install") it then install it silently and not show a pop up while I'm playing a video game so don't disturb my full screen playing, it should be done without a pop up at all.

When adding a torrent add it as: "Downloading metadata" like in other clients, to keep the order of the torrents by date added, and not have one being added to the list after 1 week from pressing the magnet.

Show the "Queued" torrents in somewhat green color to distniguish them from "Stopped" torrents.

**Comment by parg** [comment]
Thank you for your list of demands.

I might work on the metadata order one.

You can colour things in the library by using Tags, see https://github.com/BiglySoftware/BiglyBT/wiki/Tags#Change_downloads_row_color_when_it_contains_certain_file_types for clues. Don't tell me it is too complicated, that's the way things are.

**Comment by SamSmith90** [comment]
Thx.

About this:
"You can colour things in the library by using Tags, see"...
My explanation:
I mean the progress column bar, the one where it says for example: "Downloading" or "Stopped" or "Queued", when it has been downloaded and it's Queued to seeding, show its porgress bar in somewhat green color and not grey, not exactly like grey stopped torrents.

**Comment by SamSmith90** [comment]
As mentioned before I want to stress the importance:
There's a critical problem in BiglyBT that may even force me to change to another client, it sometimes opens a window to install something called similar to: "Web download helper" even after I clicked that I agree to install it before, and bothers my full screen playing or full screen video watching, would you please make it not go to front and instead be silent?

**Comment by SamSmith90** [comment]
If you do not want to make Webtorrent Support Client install be silent after choosing the option of whether to install it or not when installing BiglyBT for the first time and can be changed in settings, then would you please tell me how to migrate my 7,000 torrents to another client? (with order and tags), at least allow an option in settings: "Do not show Webtorrent Support Client's popup window".

**Comment by parg** [comment]
Let it install and then disable it:

![image](https://user-images.githubusercontent.com/395293/188390987-7532c65e-936e-479a-89b6-c59705125744.png)

**Comment by SamSmith90** [comment]
It has done install many times, and I can't find "azwebtorrent" in the plugins as you have it, sorry, for now I downloaded qBittorrent and I'm gonna use it and hopefully move my 7,000 torrents from BiglyBT to qBittorrent with tag names and order, I left Bittorrent because it doesn't have a 64-bit version and the ability to use more ram, let me know if you listen to the feedback an advanced user is giving you (me) and fix the problems and only then will I stop looking for a way to move my torrent to qBittorrent and instead recommend BiglyBT on FB.

**Comment by parg** [comment]
Wow, don't bother mate.

**Comment by parg** [comment]
Actually the prompt to install "azwebtorrent" should have a "don't ask again" option in it.

**Comment by SamSmith90** [comment]
I don't know if I didn't see the "don't ask again" checkbox in the first time it asked me but I think there wasn't, but now it just opens a window that goes to front when I'm in a video game with text and a progressbar only and closes when it finishes installing, with no option to not show it again.

**Comment by parg** [comment]
If it finished installing then it wouldn't install again later as it is already installed. 

There would also be an entry for "azwebtorrent" in the plugin list.

If you think that BiglyBT has remembered your previous response to the installation prompt window then go to 

`Options->Interface: Clear remembered dialog decisions`

and hit the "Clear" button.

**Comment by parg** [comment]
Latest beta might help with azwebtorrent.

You can select your own progress bar colours by right-clicking on the progress library header and selecting "Set Colours"

By default magnet downloads should be placed in the location they were when initiated. I might change the default though as users have varying views on this.
