### ISSUE TITLE
HELP! cant upload files, no connect to leechers

### ISSUE THREAD

**Issue by Chikitico** [BiglySoftware/BiglyBT#2705]
Hi, i want change uTorrent with BiglyBT, my question is, uTorrent is better or i am stupid ? i cant seed, the velocity for upload is 30 or 40k, top 200k, i changed the configuration 200 times until now, and reinstall cleaning the configuration, many times, importing configuration from uTorrent and with out, manuali changed, in one tiene only i guet 1MB for 3 minutes, and open the utorrent and inmediatly 3 o 4 MB, my connection is fiber 100Mb, i dont know if i can do someting. In uTorret i see more leechers, and are the same trackers.

**Comment by parg** [comment]
First of all please switch to the latest beta version - see the Help menu in BiglyBT, select the "join beta program" item and then select the "update me with the latest stable beta version" option.

See if this helps.

**Comment by Chikitico** [comment]
50 minutes working
![01](https://user-images.githubusercontent.com/68825489/188762840-da1a936c-e499-43f3-a262-68e1d74f839b.png)
5 minutes working
![02](https://user-images.githubusercontent.com/68825489/188763050-dcf707d5-c0f5-4824-ad22-bda5b8e29f87.png)
are in a 2008r2 virtual, i am not an a expert in torrent, i am tecnician it, tried all i can think, an disabled the firewall as wel

**Comment by Chikitico** [comment]
> First of all please switch to the latest beta version - see the Help menu in BiglyBT, select the "join beta program" item and then select the "update me with the latest stable beta version" option.
> 
> See if this helps.

and now take the same torrent, one in utorrent in my server and other in one new pc, in a second internet connection, and bigly dont conect whit the mayority


![utorrent1](https://user-images.githubusercontent.com/68825489/188809001-9fcc022c-b8ff-47ca-b756-cc5347c37582.png)

![bigly1](https://user-images.githubusercontent.com/68825489/188809034-4c0a6d38-1a28-4f7b-ad44-49e28b025d7d.png)

**Comment by parg** [comment]
You're not running the latest beta

**Comment by parg** [comment]
Also check the settings under

`Options->Transfer: Max connections per torrent default [0: unlimited]`

You don't appear to have run a speed test as your upload speed limit is set to "unlimited", it may be that BiglyBT has set your maximum connections per torrent to a low value.
