### ISSUE TITLE
Newly added magnet shows up in "order" according to when added, not when torrent finally retrieved

### ISSUE THREAD

**Issue by david-bakin** [BiglySoftware/BiglyBT#2707]
`BiglyBT 3.1.0.1_B29 (Possibly B28)`

This just started happening and is new behavior.  I prefer the old behavior but won't press strongly for it.  But if it is achievable that would be nice.

_Old behavior_:  Add a bunch of torrents by  double-clicking on selected magnet links with "monitor clipboard for torrent links enabled".  That starts a bunch of fetches of torrents from the DHT.  (You get the little in-progress dialog stacking up.)  Eventually those torrents get returned from the DHT and one at a time the full "add torrent" dialog pops up.  Sometimes several in a row (they're stacked) and sometimes there's quite a delay (hours even!).  Whichever, the torrents are _added_ to the "incomplete" list in the order in which the "add torrent" dialog "OK" is clicked.  That is, if sorting by column "order" they show up in the order added by the "OK" button.

_New behavior_: Do same thing.  But _now_ when you click the "add torrent" dialog "OK" button it shows up in the list _inserted_ in the order in which you double-clicked the magnet links!  

So the issue for me is: Sometimes I've got a _lot_ of torrents downloading/queued for downloading.  And the newly added torrents _used_ to go at the end of the list where I could spot them.  Now they get inserted much higher up in the list where they're mixed in with everything else.  Also, I use the "add torrent in stopped state" setting.  Which means I have to go chase them down whereever they end up in the list to start them.

**Comment by parg** [comment]
Ah, you can't please all the people all the time! There was a user that wanted the actual downloads to be positioned where they would have been had the magnet download completed immediately so I added

`Options->Plugins->Magnet URI Handler: Position actual download in library based on magnet download start time`

and defaulted it to "selected" as I thought it was vaguely sensible.

You can explicitly set the add position to first/last in the torrent options dialog (there's a new "auto" value that magnet-added torrents are assigned) but that's obviously a pain to do every time.

You could switch the new option of course.

But that makes me wonder, do you think the new option would default better to "unselected" for users?

**Comment by david-bakin** [comment]
I totally get not being able to satisfy everyone at once!  And I also totally get not knowing that there was anyone really depending (psychologically!) on the old behavior since there isn't anyone (including me) filing issues saying "I like this behavior, please don't change it in the future"!

But what I _really_ get is a commitment - which takes continual effort to create _and maintain_! - to make sure that just about every such intentional UI change comes with an option _somewhere_ to control whether it happens or not! **Thank you!**

Only issue remaining is that such changes don't come with a note in the release notes pointing out the existence of the new option (or the change in behavior).  And the search function in options - though generally useful - can be problematic unless you happen to hit the right word to search on.  (I was searching on "order" because that's the name of the column, not "position" ...)

(Oh, and I don't know whether checked or unchecked would be better as a default....)
