### ISSUE TITLE
Cannot search for "++" in the new torrent window, but can when the torrent information is downloaded

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2713]
Java 17.0.4 (64 bit)
  Oracle Corporation
C:\Program Files\Java\jdk-17.0.4

SWT v4942r22, win32, zoom=100, dpi=120
Windows 11 v10.0, amd64 (64 bit)
B3.1.0.1_B31/4 az3

I was downloading a torrent, and was searching for "++" without the quotation marks and the new torrent window will not show that.  I think it replaces all the + signs with p, so that it becomes pp instead of ++.  But when I downloaded the torrent information, and then did a search, I could do a search for ++ and find what I was looking for.

**Comment by parg** [comment]
It only searches on file name unless you have a file separator in the search expression. There is a difference between the "new torrent window" and the "files view" search, the former includes the "\" in the search expression so requires an exact path match  - I should fix that.

**Comment by parg** [comment]
Made it consistent with the Files View
