### ISSUE TITLE
"Display BiglyBT UI Chooser" does not work

### ISSUE THREAD

**Issue by Eidroerahs** [BiglySoftware/BiglyBT#2719]
Hi,

it looks like the "Display BiglyBT UI Chooser" no longer works.

When choosing the a.m. option I cant get it to the Classic Version with the side-bar.
Using restart directly, or close and restart manual, doesn't make any difference.

Hope someone can give me some feedback upon how to work this out; if it's not a version bug.

* Windows 7 Ultimate SP 1 64 bit
* BiglyBT 3.1.0.0

![01](https://user-images.githubusercontent.com/113787503/190866371-37b0ac2f-4520-4c48-922a-04d53b27ce6d.jpg)
![02](https://user-images.githubusercontent.com/113787503/190866380-6b408ab4-255c-4d14-af7c-f3d30beb2cb2.jpg)

**Comment by parg** [comment]
Did you hit the OK button on the UI choser dialog? If you change it and then close the dialog via the 'x' or escape it doesn't register the change

**Comment by Eidroerahs** [comment]
> Did you hit the OK button on the UI choser dialog? If you change it and then close the dialog via the 'x' or escape it doesn't register the change

I definitely did; each time (so the program restarts itself). Even re-booted the PC several times after changing ... but no results.
My error was choosing the new style while updating, I didn't like it, and wanted to change back to classic.

Thx for posting parg.

**Comment by parg** [comment]
Try going to 

Options->Logging: Advanced

Set the advanced option name to `ui` and the value to `"az2"` hit the "set" button, "save" and restart.

**Comment by Eidroerahs** [comment]
Excelent parg, set the value to "az1" and it worked (side-bar version).
Option value "az2" will show the recent tabbed version.

Thanks a lot 

*solved, closed*
