### ISSUE TITLE
Unified I2P Tunnel

### ISSUE THREAD

**Issue by gh338** [BiglySoftware/BiglyBT#2720]
* Kubuntu 20.04
* BiglyBT 3.1.0.1_B31
* KDE

Currently BBT has 3 I2P tunnel types, Mixed - I2P Only - Other.
Could you make an option to have a single unified I2P Tunnel that handles all 3 roles ?

Thanks.

**Comment by parg** [comment]
why? they have different roles

**Comment by gh338** [comment]
> why? they have different roles

i am not aware of how these roles work - sorry for that.
i am therefore not sure if it is possible in the first place.
if you have a BBT running clearnet + tor + i2p you need all 3 types currently, as you never know what network the torrents are mapped to. 
i guess due to my lack of knowledge the question seems nonsensical.
