### ISSUE TITLE
Magnet downloads not working

### ISSUE THREAD

**Issue by simoncbarker** [BiglySoftware/BiglyBT#2722]
Downloading from piratebay or YTS and get this message every time:

Downloading From:magnet:?xt=urn:btih:BF3EEDF5D1091B4F6EC4A1F61EE8B18D5E4D4479&&&&...
Searching...
Metadata download created
Found 0

Any ideas?

**Comment by melowman666** [comment]
i am having the same issue and on the sources tab the DHT shows nothing. Your working magnet is not working for me

**Comment by melowman666** [comment]
ok reinstalling biglybt fixed the issue for me...-__-
