### ISSUE TITLE
BW PeerID is mostly BitTorrent Web not BitWombat

### ISSUE THREAD

**Issue by L2501** [BiglySoftware/BiglyBT#2724]
https://github.com/BiglySoftware/BiglyBT/blob/d80c56ee44d44a4ff5a6b5df5a9666a0700986d8/core/src/com/biglybt/core/peermanager/utils/BTPeerIDByteDecoderDefinitions.java#L256
BW is identified as BitWombat a very old obsolete client that nobody actually uses
It is actually BitTorrent Web https://www.bittorrent.com/products/win/bittorrent-web-free/
Many people confused about this https://old.reddit.com/r/PiratedGames/comments/tzv9iq/i_view_my_torrent_clients_statistics_from_time_to/i41lf49/

**Comment by parg** [comment]
Guess I'll remove it
