### ISSUE TITLE
Plugins keep reinstalling and reactivating

### ISSUE THREAD

**Issue by gh338** [BiglySoftware/BiglyBT#2725]
* Kubuntu 20.04.3
* BiglyBT 3.1.0.1_B36
* KDE

Some plugins like Tor Helper and mlDHT keep reinstalling and reactivating.
Is there a way to remove plugins completely ?

**Comment by parg** [comment]
You probably want the mlDHT plugin but up to you I guess.

For the mlDHT plugin you need to let it install and then uncheck "load at startup"

![image](https://user-images.githubusercontent.com/395293/191447326-8357091c-3cef-442e-bc7f-b8d195396f9d.png)

Either do the same for the others or, in the case of the Tor Helper plugin, there is a prompt to install it - you might have responded "don't ask again" previously so you would need to hit

`Options->Interface: Clear remembered dialog decisions`
