### ISSUE TITLE
BiglyBT core stops working after some time

### ISSUE THREAD

**Issue by FakeJoe** [BiglySoftware/BiglyBT#2726]
* Android TV 
* Latest (25.09.22)

Hello, this happens for the second time in a row so I decided to raise a ticket. So, I am running BiglyBT as a torrent downloader on my Nvidia Shield with Android TV (latest official version).

I configure it to download torrents directly and expose web interface to be able to access it remotely with port forwarding on my router.
It works fine for a few days (up to several weeks), but then, suddenly I can't access it through Web interface anymore.
Trying to open it on Android TV, and it says following: 
![20220925_162753](https://user-images.githubusercontent.com/4153741/192148926-d54e0789-3d3f-40d1-942e-a2c38476cdb9.jpg)

So now, to make it work, I have to completely uninstall it and install from scratch. Quite annoying to be honest.

Please let me know if I can provide more information.

Thanks.

**Comment by SoundFactor** [comment]
You instead of closing these. You could actually provide some information on whats causing it other then just blaming Android. For years BiglyBT worked flawlessly until last November.

**Comment by parg** [comment]
You need to open this issue in the Android project, this is the Desktop project.
