### ISSUE TITLE
Expand searching capability to include files inside of torrents and not just torrent names

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2733]
Sorry, no biglybt version right now.  2022-10-04
Windows 11

Right now, when doing a search in the top pane, it only searches torrent names, but I would like to be able to search for a certain name in all those torrents.  Do I have to just select all the torrents, and then in the middle panel, in the files tab, just search for the name I want?  I want to be able to start those torrents that have that matching file name, or partial match.

**Comment by parg** [comment]
Check the tooltip - prefix with f:

**Comment by as-muncher** [comment]
I see the * next to the search box in the top panel, but for the Files tab, the * doesn't seem to do anything.
