### ISSUE TITLE
While a torrent is checking after a search for existing data files is cancelled, the stop button does not work

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2734]
windows 11, sorry, no biglybt version right now

When I do a search for existing data files, then cancel it, the torrent will start checking.  When that happens, the stop button shows but not the pause button.  When I click the stop button, the torrent does not stop checking, but the pause button shows.  Then, when I press the pause button, then the torrent pauses.

**Comment by parg** [comment]
You can't pause the **checking** process using the pause button, it only applies to started or stopped torrents. If you actually want to pause (and resume) the checking process then go to the "disk operations" view.
