### ISSUE TITLE
Drag and drop capability over the biglybt icon working in Windows 11?

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2735]
I don't know if this is a Windows 11 issue or what, but when I select some .torrent files and drag them over the BiglyBT icon in the taskbar, the BiglyBT window does not maximize so that I can drag the selected .torrent files into the top panel.  What I have to do is open BiglyBT, make it a smaller size than maximum and then drag those .torrent files into the top panel.

**Comment by parg** [comment]
That is a Windows operation, BiglyBT has nothing to do with drag-over-task-bar operations.
