### ISSUE TITLE
Panels inside collapsed sidebar groups aren't selected, when opened via menus

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#2736]
Let me preface this by saying that it's officially the dumbest, most trivial thing I've ever reported, and I would be fully behind a close of, "OMG so not important enough to fix!" So, that being said...

If a sidebar group is collapsed, and one of its member panes is opened via the View menu, the group will be expanded, and the chosen pane displayed in the main interface, _but_ the sidebar selection will not be moved to that pane's entry.

### Steps to reproduce
1. Switch to the Library view
1. Collapse the "Devices" group, in the sidebar
1. Choose **View > Disk Operations** from the application menu

### Actual result
The disk operations view is displayed, and "Devices" is uncollapsed, but the sidebar selection remains on Library

### Expected result
Same, but the selection moves to Devices > Disk in the sidebar

### Additional information
If Devices is expanded before using the View menu, the sidebar selection _does_ move to Devices > Disk.

The same thing can be seen with e.g. BiglyBT > Beta Program, if the BiglyBT group is collapsed before activating. I'm sure there are numerous other sidebar entries that exhibit the same behavior.

### System block
```text
Java 11.0.16.1 (64 bit)
  Red Hat, Inc.
/usr/lib/jvm/java-11-openjdk-11.0.16.1.1-1.fc36.x86_64

SWT v4942r22, gtk/3.24.34, zoom=100, dpi=96
Linux v5.19.8-200.fc36.x86_64, amd64 (64 bit)
B3.1.0.1_B43/4 az3
```

**Comment by parg** [comment]
Works fine on Windows and surely that's all that matters :)

**Comment by ferdnyc** [comment]
And yet, it's fixed in _B44. (Specifically, in 64e76e0eb84d03a64802a1970e45811126d24ba9.) ...What's your game, mister? 😑
