### ISSUE TITLE
'IP Filter Enabled' column does not present any information

### ISSUE THREAD

**Issue by JBitte** [BiglySoftware/BiglyBT#2737]
hey, for some time I noticed that the 'IP Filter Enabled' never shows anything in the Library/Download view.

++++++++++++++++++++++++++++
Java 1.8.0_341 (64 bit)
  Oracle Corporation
C:\Program Files\Java\jre1.8.0_341

SWT v4942r22, win32, zoom=100, dpi=120
Windows 11 v10.0, amd64 (64 bit)
B3.1.0.1_B43/4 az3

**Comment by parg** [comment]
Works for me.

You need to have the overall IP Filter enabled: Options->IP Filters: Enable

**Comment by JBitte** [comment]
okay. user error. I see that now by enabling IP Filter in Tools menu.
A bit of an odd implementation.
![ip-filter-enabled-Untitled](https://user-images.githubusercontent.com/6049555/194362537-0c586a5f-dedd-4b34-8e7e-c6c0bf1d0825.png)

**Comment by parg** [comment]
Bit of an odd user.
