### ISSUE TITLE
Automatically fix "Error: GC overhead limit exceeded"

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2747]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.2.0.1_B02/4 az3

Does this error need to be something that I have to recheck my torrents over, or could you please make it something that can be fixed automatically.  Perhaps you could make BiglyBT do what it needs to do so that the GC error doesn't come up again?  I don't want to have to manually increase the JVM size.

**Comment by parg** [comment]
Perhaps I could, I don't know, I have many things to do.

**Comment by as-muncher** [comment]
No rush, just putting it out there as a wish.

**Comment by as-muncher** [comment]
Yeah, this GC overhead thing is a pain.  I thought at first that "GC" meant "graphics card" but it means "garbage collection", right?

**Comment by parg** [comment]
right
