### ISSUE TITLE
Offer to automatically fix "Can't read 'plugin.properties' for plugin: file may be missing

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2748]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.2.0.1_B02/4 az3

At least one of those plugins, I see errored in the middle panel, so I can recheck it, and then start it.  But another one "azlocprov", can't find that one, will have to go searching on the website for it.  and mlDHT.

**Comment by parg** [comment]
Just reinstall.

**Comment by as-muncher** [comment]
The point was that it get fixed automatically.  Now I have to go searching for those other plugins on the plugins page.
