### ISSUE TITLE
Invert selection in Files tab, or how to select NOT (expression)

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2749]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.2.0.1_B02/4 az3

If I've selected a torrent, and in the bottom panel, select the Files tab, how do I invert the selected files?  For instance, if I search for "jpg", how do I select everything that is NOT "jpg"?

**Comment by parg** [comment]
In 3201_B02 you can type

`name:!\.jpg`

in regular expression mode into the filter box and then ctrl+a
