### ISSUE TITLE
Add option to save .torrent file as torrent name

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2751]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.2.0.1_B02/4 az3

It's great that biglybt saves a backup copy of the .torrent file.  But sometimes, you have files like p232223322.torrent, and then when I go to move that torrent to an external drive or elsewhere, I like to move the .torrent file that goes with it too.  Right now, I can use biglybt to export the .torrent file, which is great, but often it does not match the name of the torrent.  Then, I have to go to qbittorrent to open that .torrent file that I got from Biglybt or from the web, some t33422.torrent name or something like that, and then qbittorrent will save the .torrent file as <torrent name>.torrent.  If there are 2 or more torrents with the same torrent name, then don't make it abc.torrent, abc 1.torrent, abc 2.torrent, but make it abc and then the infohash then .torrent.

**Comment by ferdnyc** [comment]
-1 from me. For reasons:

1. That directory is an internal cache, it's not meant for user consumption. It should be optimized for the needs of the _code_, not the user. There's no reason to add another level of indirection (and therefore another set of dereferences) every time the file needs to be accessed.
1. (This is the bigger one:) The overlap between torrent names and legal Windows filenames is less than 100%. There are several torrent name characters that are not permitted in Windows filenames, which means the torrent name would have to go through _another_ level of indirection where it's sanitized into a valid filename.

On Linux, you could use any Torrent title as a filename unless it contained a forward slash. But Windows is far more restrictive.

**Comment by as-muncher** [comment]
> -1 from me. For reasons:
> 
>     1. That directory is an internal cache, it's not meant for user consumption. It should be optimized for the needs of the _code_, not the user. There's no reason to add another level of indirection (and therefore another set of dereferences) every time the file needs to be accessed.
> 
>     2. (This is the bigger one:) The overlap between torrent names and legal Windows filenames is less than 100%. There are several torrent name characters that are not permitted in Windows filenames, which means the torrent name would have to go through _another_ level of indirection where it's sanitized into a valid filename.
> 
> 
> On Linux, you could use any Torrent title as a filename unless it contained a forward slash. But Windows is far more restrictive.

I think you might have replied to the wrong issue.  
But thank you for replying.
