### ISSUE TITLE
[info] Difference in the Windows installers?

### ISSUE THREAD

**Issue by Euphoriarules** [BiglySoftware/BiglyBT#2752]
There are 3 different installers for Windows installation (excluding the 32Bits version):
- GitHub_BiglyBT_Installer64.exe
- GitHub_BiglyBT_Installer64_J14.exe
- GitHub_BiglyBT_Installer64_WithJava.exe 

What is the difference between them?

Thx.

**Comment by Havokdan** [comment]
1 - Without Java
2 - Java version 14+
3 - With Java 14-

**Comment by TuxPaper** [comment]
Havokdan has it right.  The reasoning is installer size:

1 - Without Java. 12M. Will try to use existing Java **if it's Java 13 or below**, and will install Java 8 locally if it can't.  

2 - Without Java. 31M. Will try to use any existing Java (Java 8 or higher), and will install Java 8 locally if it can't.

3 - With Java.  60M. Bundled with Java 8, so installation won't require internet. Will still try to use existing Java installation if there is a valid one (Java 13 or below)

Starting with Java 14, they removed the pack/unpack util, which makes the installer over twice the size :(

**Comment by Euphoriarules** [comment]
Thx. @Havokdan and @TuxPaper . Now I understand why I always got the 1.8 version regardless of which one I installed on my Windows system. I leave it like this.
