### ISSUE TITLE
3.2 update fails on Mac Ventura

### ISSUE THREAD

**Issue by Dave-8080** [BiglySoftware/BiglyBT#2753]
* MacOS Ventura on Apple Silicon HW
* BiglyBT Version Number 3.2
* For *nix: Desktop Environment

The installer dialog box never appears, and the installer process never completes.

**Comment by parg** [comment]
erm, yah, there is no full installer update for Apple silicon, it should perform a .jar based update. lemme check

**Comment by parg** [comment]
os_arch of "aarch64" is pushed through .jar, something must be borked. 

What does the rest of the system-info show in the About dialog?

**Comment by Dave-8080** [comment]
Here's the info from 3.1 

Java 1.8.0_202 (64 bit)
  Oracle Corporation
/Applications/BiglyBT/.install4j/jre.bundle/Contents/Home/jre

SWT v4942r22, cocoa, zoom=200, dpi=72
Mac OS X v10.16, x86_64 (64 bit)
B3.1.0.0/4 az3

**Comment by parg** [comment]
Hmm, that's annoying, it is showing as I suppose should be expected as x86 :(

Can you generate a "debug.zip" (Help menu, last option) and send to paul@biglyby.com ?

That .zip has a lot of information in it, please remove anything that you're not happy with privacy-wise. The main thing I'm interested in is the "evidence.log" file it contains.

**Comment by Dave-8080** [comment]
Emailed it, but got an unknown recipient message back.

**Comment by parg** [comment]
sorry, there's an obvious typo there!

paul@biglybt.com

**Comment by parg** [comment]
Thanks. I was hoping that there would be something in the system properties that indicated that the underlying processor was Apple silicon so it could be used to control the update process but alas no.

With the x86 updater you'll see that BiglyBT downloads a zip file called BiglyBT_Update_3.2.0.0_osx.zip - inside this there is a further .zip named BiglyBT_Update_3.2.0.0_osx_app.zip

If you unzip this you'll see a "BiglyBT Update.app" application - if you unpack this and execute it in a terminal does it output any kind of error message?

**Comment by Dave-8080** [comment]
After a few minutes, I force quit the updater. When I checked, the program shows version 3.2. Maybe it updated, but did not show any progress or status.

> On Nov 18, 2022, at 1:07 PM, ***@***.*** wrote:￼
> Sorry, could not find the file. When The updater launched, it seems to hang at an app identified as java. Here are some screenshots.
> <Screenshot 2022-11-18 at 1.04.40 PM.png><Screenshot 2022-11-18 at 1.05.27 PM.png>

**Comment by parg** [comment]
Spun up an Apple Silicon OSX on AWS, installed the x86 3.1 BiglyBT and it updated successfully - not sure what's causing the process to hang for you :(

BTW we now have an Apple Silicon installer for 3.2

https://github.com/BiglySoftware/BiglyBT/releases/download/v3.2.0.0/GitHub_BiglyBT_Installer_Silicon.dmg

Seems to work OK

Some plugins don't (and most likely never will) work on it, e.g. 3DView and the Embedded Media Player.

**Comment by Dave-8080** [comment]
Thanks for your help.

**Comment by parg** [comment]
I'll close this, please re-open or create a new issue if you have further problems
