### ISSUE TITLE
[FeatureRequest] Last Active column data

### ISSUE THREAD

**Issue by timlance** [BiglySoftware/BiglyBT#2754]
It seems this column's data only tracks back as far as the time BiglyBT was last opened. It would be more useful (well, certainly at least for me) if the date shown for a torrent's last activity was the date/time the torrent last saw true action (i.e. seeding, in most cases). I know qBittorrent does this as that is where I come from and how I had learned to rely on such data.

Thanks for any consideration.

**Comment by parg** [comment]
There's an "up idle" column that shows time since last upload

**Comment by timlance** [comment]
PERFECT! Thanks.
