### ISSUE TITLE
Interface glitch.

### ISSUE THREAD

**Issue by Achaean** [BiglySoftware/BiglyBT#2755]
From the swarm option.
Latest version, on Devuan oldstable.
Java ver: openjdk 11.0.16.
![Screenshot](https://user-images.githubusercontent.com/3608053/196316285-628ce806-3503-4136-96d7-18646333a3f8.png)

**Comment by Achaean** [comment]
I think I found the cause.
It's a wrong color combination.
The letters are white on white background.
I didn't change the default  color combination. I have (at KDE) activated the "Dark" background
Obviously Bigly, doesn't like it.  :-)
I'm attaching another one screenshot, with a similar effect.
![Screenshot_2](https://user-images.githubusercontent.com/3608053/196331892-9747d419-fa53-4faa-b565-e6465bee3ef4.png)

**Comment by parg** [comment]
When you say "latest version" do you mean 3.2?

**Comment by Achaean** [comment]
Yes, sorry! Forgot to mention.
V.3.2.

Java 11.0.16 (64 bit)
  Debian
/usr/lib/jvm/java-11-openjdk-amd64

SWT v4942r22, gtk/3.24.5, zoom=100, dpi=96
Linux v4.19.0-22-amd64, amd64 (64 bit)
B3.2.0.0/4 az3

**Comment by parg** [comment]
Hmm, that's unfortunate, dark mode works pretty well on some other Linux variants (e.g. kubuntu). Looks like BiglyBT isn't detecting that dark mode has been enabled :(

Overall is the UI pretty much in dark mode? I can add an option to override things that might work.

**Comment by parg** [comment]
If you join the Beta Program (see the Help menu to do so) and let BiglyBT update to beta B03 then there is a new option under Tools->Options->Interface->Color Scheme

It is at the top and will force the internal components to use a dark theme - set it and restart BIglyBT

**Comment by Achaean** [comment]
OK! I joined Beta.
However the problem remains.

Java 11.0.16 (64 bit)
  Debian
/usr/lib/jvm/java-11-openjdk-amd64

About:
SWT v4942r22, gtk/3.24.5, zoom=100, dpi=96
Linux v4.19.0-22-amd64, amd64 (64 bit)
B3.2.0.1_B03/4 az3

Screenshot_3 : Running the stable beta.

Screenshot_4: Problem remains.

Screenshot_5: Selecting the text with the mouse, proves that it is there. Only with the wrong color.

![Screenshot_3](https://user-images.githubusercontent.com/3608053/196441772-3ff2dfeb-2f87-4af7-8d4c-1f2050f8d228.png)
![Screenshot_4](https://user-images.githubusercontent.com/3608053/196441802-5dc50537-fcb9-4f70-9af6-b29438bbd931.png)
![Screenshot_5](https://user-images.githubusercontent.com/3608053/196441827-79e4371a-35e4-414a-bf72-e61125a3e4cf.png)

**Comment by parg** [comment]
And you enabled that new option I added and restarted?

**Comment by parg** [comment]
yay
