### ISSUE TITLE
Some file options ignored when torrents added via plugin, but not when added manually

### ISSUE THREAD

**Issue by PrototypeZero** [BiglySoftware/BiglyBT#2757]
Whenever a torrent is added automatically via a plugin (ie rssfeed), the options in _**Files**_ are not applied.
ie _**Auto prioritise**_ doesn't apply to matching files and **_Ignore_** (auto-skip files) doesn't apply the "delete" priority to the files.
Don't know if any other setting is not applied.

Adding the same torrents manually works as intended.

Minor issue I know, but any chance this could be fixed?

**Comment by parg** [comment]
I recently fixed this for torrents added through the "BiglyBT Web Remote" by adding an option that cause them to go through the "add torrent options" dialog (i.e. the dialog that appears when you add them manually (assuming you haven't disabled it)).

It is currently the option dialog that applies all the options (and gives you the chance to make further amendments)

I could probably do the same for other plugins, would this work for you and if so which plugins?

**Comment by PrototypeZero** [comment]
Its mainly the RSSFEED plugin (there are a couple of other non public plugins that do a similar job too), it would be nice without the add dialog popping up unexpectedly (as it would whenever rssfeed found a new match) but if thats the easiest way to do it then I'm ok with it.  

Otherwise perhaps an exception list for plugins that add downloads not to show the dialog but still apply options if that's possible?

**Comment by parg** [comment]
Best I can do is add an option to apply them (no dialog will be shown when enabled)

Check out version 1.8.3
