### ISSUE TITLE
Update files from different torrents and directories

### ISSUE THREAD

**Issue by VamuveTV** [BiglySoftware/BiglyBT#2758]
How to update files in BiglyBT from different torrents ?

Let´s say i have 2 torrents containing files which are the same as others found in another torrent. examples:

1 - Torrent A = fileA, FileB, FilleC 
2 - Torrent B = file A, FileM, FileC

The files in torrent A i save them in c:\temp1
Suddenly, i found that those files are incomplete because they are not beinbg seeded. Say  that the seed stopped when the files reached these completed percentage:
On c:\Temp1, i have:
FileA = 88%
FileB = 25%
FilleC  = 75%

Then, i have on torrent B, those files (some of them) saved in c:\temp2 and they also are not being seeded but the percentage of completeness is a bit different. Like this:

On c:\Temp2, i have:
FileA = 98%
FileM = 100%
FilleC  = 48%

On tempp1 and Temp2, i want to update 2 files only (because they are the same). So, how can i update FileA and FileC from c:\Temp1 and c:\Temp2 in order t try to complete those files and reach a higher level of complete (or even reaching 100%) ?

So, how can i merge two identical files those files together in order to they get their maximum percentage of complete ?

For example. If on FileA from temp1 directory (which is completed with 88%, we have some areas that were filled - say the beginning of the file. And on FileA from C:\temp2 is the beginning of the file that contains no data. Then i want to get the data from temp1 and merge with temp2

**Comment by parg** [comment]
Swarm Merging should automatically do this if both torrents are in BiglyBT. Turn on the Swarm Merge column in the Library view and hover over it for details. Or check the log under View->Log Views->Swarm Merge

**Comment by parg** [comment]
By the way, the log is paused by default, you need to uncheck the "paused" checkbox at the bottom to see the details

**Comment by as-muncher** [comment]
@parg, But I think swarm merge won't work if the piece sizes are different, right?  unless the files are both at 100%.

**Comment by parg** [comment]
swarm merge doesn't require the piece sizes to be the same

**Comment by DumbJoe** [comment]
Does swarm merging work on the nix version and how do I enable it if it isn't (or to check if it is running or not)?

**Comment by DumbJoe** [comment]
Also wouldn't FileA and FileB from both torrents be different unless they both have the exact same file hashes?
