### ISSUE TITLE
Move some items under Help to other areas

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2760]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=96
Windows 7 v6.1, amd64 (64 bit)
B3.2.0.1_B04/4 az3

I noticed that "Speed Test" was under Help.  Perhaps it should be under Tools?  And some of the other network items listed around there - maybe they should be moved under Tools or View?

**Comment by parg** [comment]
Indeed the menus could do with rework. However everytime I move something people moan that they can't find it anymore so I don't tend to bother...

**Comment by ferdnyc** [comment]
It's not part of **Help**, but I definitely think that _three_ copies of the **Log Views** list is excessive.

You can find it:
* As a submenu under **View**
* As a sub-submenu under **Tools > Plugins**
* Appended to the **Debug** menu

**Comment by as-muncher** [comment]
@ferdnyc  Well, might as well also put it under Help too!  :)
