### ISSUE TITLE
Make swarm searches persistent

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2761]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=96
Windows 7 v6.1, amd64 (64 bit)
B3.2.0.1_B04/4 az3

It would be nice to keep the swarm searches persistent so I don't have to keep adding them each time I restart BiglyBT.

**Comment by parg** [comment]
Turn them into subscriptions vis the RSS button?

**Comment by as-muncher** [comment]
@parg, What I've found works for me but what I think needs tweaking for access' sake is to right click on any torrent in Incomplete Torrents, Content tab, Find More Like This...  and then add the search term that I'm looking for, that BiglyBT will search the swarm for - thank you for that.  It works best this way, but it's kind of a hidden thing.  When I right-click on Subscriptions, Add Subscription, my search term comes up under Swarm Discoveries, and I think the web is searched too, instead of just the swarm.  I think it would make sense to make the Add Subscription work more like "Find More Like This...".
