### ISSUE TITLE
feature request: deselect all when loading .torrent or magnet megatorrent

### ISSUE THREAD

**Issue by JBitte** [BiglySoftware/BiglyBT#2762]
when loading a megatorrent, it's a pain to deselect hundreds of files when I don't want to download.
I do use the Ignore Extensions of Files feature to get rid of Ads and Junk to filter that out already.

![bt-deselect](https://user-images.githubusercontent.com/6049555/197335341-2985a808-58f8-4bd1-9ac9-fedf0ad8fb69.png)

Java 1.8.0_351 (64 bit)
  Oracle Corporation
C:\Program Files\Java\jre1.8.0_351

SWT v4942r22, win32, zoom=100, dpi=120
Windows 11 v10.0, amd64 (64 bit)
B3.2.0.1_B04/4 az3

**Comment by parg** [comment]
Multi-select, right-click and select Priority->Delete (or Do Not Download)

**Comment by ferdnyc** [comment]
Another option: You can load the torrent in Stopped state, go into the Files tab with Tree View enabled, to deselect the entire tree with a single click on the root checkbox. (That's how I do it, as most of my torrents come in via RSSFeed Scanner and bypass the Open dialog entirely.)

**Comment by as-muncher** [comment]
When the torrent dialogue box opens for me, I click "select all", then "uncheck", then I search in the search box for the extension that I want, and then click "select all", then start the torrent.
