### ISSUE TITLE
Comodo reporting "application contained" and "running virtually" hourly since BiglyBT 3.2.0.0 upgrade

### ISSUE THREAD

**Issue by halfmybrain** [BiglySoftware/BiglyBT#2763]
BiglyBT 3.2.0.0

Windows Home 11
Version 10.0.2261, build 2261

I get a new anonymous looking executable shown as (auto) contained by Comodo Internet Security, basically every hour. Explorer searches show no such file name. No application is associated with these executables.

These notices are preceded by notices with options. Taking no actions will CONTAIN (default option). This Comodo notification says for example,

"nwjzh5f3.exe could not be recognized and requests unlimited access to your computer" with choices
Run inside Container Default
Run Unlimited
Block
(or Trust this application toggle checkbox).

I also automatically upgraded to Firefox 106.0.1 (or 106.01?) recently with a Windows restart. No other installs were done recently.

**Comment by TuxPaper** [comment]
We don't have a nwjzh5f3.exe, so blocking/quarantining that executable would probably be wise.

My first thought is that you may have a sleeper virus that wakes up at a certain date, or via some bot command, and is now "awake" and distributing itself throughout your computer.  A full virus check (one that reboots your computer and scans before windows starts up) might be worth doing.

If you can hunt down the process/app that's creating the nwjzh5f3.exe, that also might give you a clue to where the origin is

**Comment by halfmybrain** [comment]
I have done a full scan. I used the phrase "for example" because every time the notice comes up it's a different random collection of letters and numbers. "vftbgirs.exe" and "ddcm3qb5.exe" and "ry312vo5r.exe" and "rip2egx2.exe" are other examples. A search of my whole PC or of the C drive only, does not complete before the program is auto-contained by Comodo (I have 2 or 3 minutes after initial notice and auto-contain)

Yes I'm trying to hunt it down!!!

**Comment by TuxPaper** [comment]
hmm, watching Task Manager in "Details" tab might help track it down, but it will be a lot of time staring at it.  Something's gotta be creating those new exe files, and the moment they pop up in Task Manager, there might be another process that spikes in CPU at the same time.  like if "steam.exe" spikes up in CPU by 10% every time a weirdly named exe is launched, that might indicate that steam.exe isn't what we think it is.  It's not a great way of finding what's wrong, but it might be something.

Good luck hunting it down.

**Comment by CristianZatt** [comment]
Also having windows defender reporting the 3.2.0.0 update as PUA.

![image](https://user-images.githubusercontent.com/12812656/198902949-25edf37c-4b79-424a-ac03-1e47e2d61d13.png)
