### ISSUE TITLE
Failed to access torrent file.  Ensure sufficient temporary file space available (check browser cache usage).

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2768]
Java 11.0.15 (64 bit)
  Oracle Corporation
/usr/lib64/jvm/java-11-openjdk-11

SWT v4956r12, gtk/3.24.31, zoom=100, dpi=96
Linux v5.14.21-150400.22-default, amd64 (64 bit)
B3.2.0.1_B05/4 az3

Couldn't this be fixed automatically?  I'm not even sure what this means or how to fix it.  Do I increase JVM?

**Comment by parg** [comment]
Some issue with writing the torrent file to disk - the location of a torrent file is passed to BiglyBT but when it goes to access it it doesn't exist. Seems that this was typically an issue with browser file cache when clicking on a .torrent file in a web page. 

So nothing to do with JVM

**Comment by as-muncher** [comment]
Nope, no torrent was added from a web page. It was from .torrent files.  But I found out what the problem is.  I saved the torrent data to an external hard drive, using Windows.  And with Windows, it will save some characters in the .torrent name or in the torrent's file's names, that Linux doesn't recognise.  For instance, I have one torrent with "•" in the filename, without the quotation marks and opensuse shows it as 3 question marks each in a black diamond.  Also, there are many torrents that have files with ' in the filename and so in opensuse, it puts it as ? when none of the files have ? in the filename.  Do you need me to send you any more information?  I haven't yet tried these torrents in qbittorrent to see if it will work there in Linux as I like swarm merging and would prefer to use biglybt.

**Comment by parg** [comment]
Nothing wrong with the torrent file, fix your external hard drive so it supports UTF-8 or whatever

**Comment by as-muncher** [comment]
ok, but when I chose the option in biglybt to choose from various encodings, I think utf-8 was there, but I will double check.

**Comment by as-muncher** [comment]
My external hard drive supports utf-8 and my operating system supports utf-8.  Transmission works fine with my torrent names, .torrent files, and torrent files.  So it must be a problem with BiglyBT.  It can't view certain characters in my .torrent files properly but changes them.

**Comment by as-muncher** [comment]
still issue as of
Java 11.0.16 (64 bit)
  Oracle Corporation
/usr/lib64/jvm/java-11-openjdk-11

SWT v4956r12, gtk/3.24.34, zoom=100, dpi=96
Linux v5.14.21-150400.24.28-default, amd64 (64 bit)
B3.2.0.1_B08/4 az3
