### ISSUE TITLE
Upgrade attempts sometimes wedge CPU & go out to lunch

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#2769]
Twice now, BiglyBT has tried to update from _B05 and _B06, and both attempts have failed. Specifically, when it tries to launch the updated version, the GUI never appears. Instead, my CPU spikes to 100% load, java trundles along until it starts throwing out-of-memory exceptions in the console log, and things continue that way until I issue a `killall -9 java` to terminate the process. (`killall java` without the -9 (aka `SIGKILL`) has no effect.)

Post-install failure message:

![image](https://user-images.githubusercontent.com/538020/198814257-9a90f5f0-1a9b-4459-b886-1e48fa04e0c1.png)

I'd love to provide logs, but at least the OOM errors don't appear in the `debug_1/2.log` files, and the _console_ output file maintained by my VNC server gets corrupted each time I terminate the process. (It's also 8+ megs of mostly binary gibberish, so I have a feeling java is dumping core _into_ the console log. Which is... just weird.)

I can't see how the problem could **possibly** be caused by c8fe091e03793ad1d2d7f12f77c22504d0124aa7 or a6a9fa78d384ec59284ab01a6ce1216a30e450f6, so either 
9dc0fc70a39365dd5973bde6fb4b83000978840a or 8771c579c6936584215a33a930ca42070d26581b are the most likely culprit.

9dc0fc70a39365dd5973bde6fb4b83000978840a seems unlikely, though, because it still should only affect macOS or Windows. If I'm reading the change correctly.

#### System block, for the un-upgraded version

> Java 11.0.16.1 (64 bit)
>   Red Hat, Inc.
> /usr/lib/jvm/java-11-openjdk-11.0.16.1.1-1.fc36.x86_64
> 
> SWT v4956r12, gtk/3.24.34, zoom=100, dpi=96
> Linux v5.19.13-200.fc36.x86_64, amd64 (64 bit)
> B3.2.0.1_B05/4 az3

**Comment by ferdnyc** [comment]
Decided to try a third time, so I could capture debug logs anyway. Naturally, the update succeeded and now everything seems fine.

Never seen it fail _twice_ in a row before, but whatever. **#SoTHAThappened**

**Comment by parg** [comment]
I have to say that I have seen this happen once recently (restart hanging with 100% CPU). For me it happened when BiglyBT did the latest SWT update. Crap, I thought, there's something wrong with the update. However it hasn't happened since :(

**Comment by ferdnyc** [comment]
\*nod\* The CPU spiking was definitely odd, as was the fact that it happened _twice_ in a row. I've definitely seen failed updates, _plenty_, but usually they're one-offs and they happen because BiglyBT has been running for a long time **before** the reboot. I've never seen an update fail when it was done immediately after startup, until yesterday.

The other thing I noticed, in hindsight, is that there was _plenty_ of free RAM on the system -- it's a headless box with 6GB in it, RAM consumption rarely goes above ~40%. So, if Java was out of memory, that must've been in terms of the constraints of its **allocation**, not the actual available free RAM. Which makes me wonder if maybe I'm just flying too close to the sun, and I need to goose my `-Xmx` or `-Xms` numbers. Could be that newer builds have the _potential_ to use slightly more memory, depending on exactly what order everything starts up in.

If nothing else, if I raise the values and the same thing happens **again**, at least that theory will be disproven.

**Comment by ferdnyc** [comment]
Well, just for S&G I hiked the memory values from 640/550 to 800/600, and so far _B07 started up with no issues on its first attempt. Which tells us as **close to** nothing as can be detected by modern equipment, without actually _being_ nothing.  `¯\_(ツ)_/¯`

**Comment by ferdnyc** [comment]
@parg Reopening this as it happened again, but I was able to do more investigating. Some items of note:

1. I **could not** attach a `jconsole` to the wedged `java` process. It saw it, recognized it as a JVM, but any attempts to connect to it from the `jconsole` process would just fail after a timeout.

1. I managed to grab the console output from the wedged process this time. AFAICT this starts from right around the point where it wedged, which seems to be as it was trying to shut down. (IOW, it was the _old_ process with 4 days of uptime on my system that got wedged. When it tries to shut down, instead of succeeding it throws an exception from practically every class (OK, exaggerating), logs an OOM error, and starts tossing out full thread dumps. I included the first one here, but they were repeating every few minutes until I `kill -9`-d it.

    I _had_ increased the VM memory allocations after the last time, as I'd said I would. Didn't make any difference. So, clearly that's not really the core issue. I suspect no matter how much memory I threw at the process, it would still fill it up eventually.

[biglybt-upgrade-wedge.log](https://github.com/BiglySoftware/BiglyBT/files/9999394/biglybt-upgrade-wedge.log)

**Comment by ferdnyc** [comment]
Huh. Once **again** it happened twice in a row, and then the third time's the charm. Bizarre.

**Comment by ferdnyc** [comment]
Heh! Oh, and I now see that `_B12` contains a (possible) fix for this very problem. Well... now that I've finally gotten it installed, cool! :+1:  Hopefully no more of these, then.

**Comment by parg** [comment]
We can live in hope

**Comment by ferdnyc** [comment]
![image](https://user-images.githubusercontent.com/538020/201727607-fa3687f5-74c7-422c-9fd5-16cedabdac55.png)
