### ISSUE TITLE
3.2 build for MacOs Ventura 13,0 crashes after magnet begins to download torrent file

### ISSUE THREAD

**Issue by FranklinSeal** [BiglySoftware/BiglyBT#2770]
MacOs Ventura 13.0
BiglyBT 3.2
Desktop

Quits whenever magnet completes download of the torrent file
Tested with multiple different magnets

App is completely broken and useless now

**Comment by parg** [comment]
Is this with the x86 installer or Apple Silicon?

**Comment by parg** [comment]
If I were to guess I'd say there's an issue with the donation popup window. You can test this theory by setting your "mode" to "advanced" in Options->Mode and going to 

Options->Logging: Advanced

and setting 

name=Already Donated
value=true

and hitting "set"

**Comment by FranklinSeal** [comment]
X86
That solved the problem. Thanks!

**Comment by parg** [comment]
Can you try joining the Beta Program (See the Help menu to do so), let BiglyBT update to version 3.2.0.1_B07 and then let it update the SWT library to version 4956r12 ? Then go to the Help menu and see if "Make a Donation" crashes things?

**Comment by FranklinSeal** [comment]
I eventually solved it by disabling the internal browser in settings. That has fixed it. Thanks.

**Comment by parg** [comment]
Did you ever try joining the Beta Progam and running with the latest stuff? I'd like to know if that fixes things before trying to get my hands on a Ventura install to test with...

**Comment by parg** [comment]
Hmm, https://github.com/eclipse-platform/eclipse.platform.swt/issues/452

**Comment by jljiraffe** [comment]
I joined the beta and downloaded B3.2.0.1_B14. BT is still crashing when the Make a Donation window comes up, which it does despite setting
name=Already Donated
value=true

**Comment by jljiraffe** [comment]
How do I disable the internal browser? I can't find this setting.

**Comment by parg** [comment]
Options->Interface->Display: Disable all use of the internal browser.

In you type "internal" into the config options search box then it will highligh this

**Comment by jljiraffe** [comment]
Disabling the internal browser prevents the crash

**Comment by parg** [comment]
It does but it isn't a solution to the issue

**Comment by jljiraffe** [comment]
Agreed. But it's a reasonable short term workaround.

**Comment by parg** [comment]
Rumour has it that it is fixed in 13.2 - please verify!

**Comment by jljiraffe** [comment]
It appears to be working!
