### ISSUE TITLE
Help Needed with download/resume after changing computers

### ISSUE THREAD

**Issue by BiglyBTUser** [BiglySoftware/BiglyBT#2771]
Hi Everyone. I would appreciate any help.

Few days ago I was downloading several large files with BiglyBT. But I had to move to a new PC and I saved the unfinished downloaded files as well as the torrent files. I copied them to a new PC and downloaded BiglyBT and installed it. I then opened the torrents links for the incomplete files.

I am actually having an issue letting BiglyBT recognize the partially downloaded files and resume downloading. I checked the internet but could not find any hint. I do want to start downloading the files again from scratch as the downloaded incomplete files are about 200GB.

Any advice is appreciated. 

Thanks in advance

**Comment by as-muncher** [comment]
I may be having the same problem.  Which operating system is your new system?  and what's the error message?  Just don't include the name of the torrent or the infohash in the error message.

**Comment by parg** [comment]
You just need to target the download to the same storage location and then "recheck" the download. What are the exact issues you are having?

**Comment by BiglyBTUser** [comment]
Hi Parg and thank you for your reply. Let me explain my problem.

I had BiglyBT installed on a PC and I was downloading some large files.  The torrents links are saved in AppData/roaming/BiglyBT/torrents and the partial files on one of my internal hard disks (disk Y).

I had an issue with win10 and I had to format the C drive and make a fresh installation of win10. I therefore saved the torrents links  to an external drive before formatting the C drive.

After finishing the fresh Win10 installation, I downloaded and installed the latest version of BiglyBT . I then copied all the torrent links back to AppData/roaming/BiglyBT/torrents. The partial downloads were still on the same location on the Y drive.

When I launched BiglyBT it did not recognize any of the torrents  links and the Library view was empty.  I then opened one pf the torrents links and it started making a new download from start. I stopped it and made a 'search for existing data files' from the menu and directed it to the Y drive.   The files were found (message below):


**11/8/22 12:26 PM: Enumerating files in Y:\Music Resources\VST downloads\East West\Hollywood Harp Diamond  v1.0.5 previous

Found 8757 files with 1786 distinct sizes
Processing 'Hollywood Harp Diamond v1.0.5', piece size=8.00 MB
    Matched=0, complete=13618, ignored as not selected for download=0, no candidates=0, remaining=1948 (total=8757)
11/8/22 12:26 PM: Complete, downloads updated=0**

After pressing OK.... nothing happened and BiglyBT did not recognize these files  or resumed downloading them. It was still making a fresh copy.

I tried all I could think of from the menus but nothing worked, I could not restore the partial downloads and resume downloading.  

Your input would be highly appreciated.



Note: One of the issues is that there is no detailed manual of BiglyBT functions so it's trial and error ....

Thanls in Advance
Joseph

**Comment by parg** [comment]
If you had done a backup (Options->Backup & Restore) then you would have had more luck with restoring things!

BiglyBT stores download state in a few places, the "torrents" folder is just a backup of the torrents. For example, there is a folder named "active" that has details of each download in BiglyBT and a "downloads.config" that controls the overall list.

Assuming you have lost those configuration files then one approach is to add the torrents with exactly the same save location as before but in a STOPPED state (see "Options->Files->Torrents: By default add new torrents in a stopped state" or do this individually in the torrent options dialog) . BiglyBT should moan about the files already being present - ignore this. Then right-click on the download and select the "force re-recheck" option (there's a "refresh" icon in the menu to do it). This should go over the existing files and get you back to where you were.

**Comment by parg** [comment]
There is a wiki by the way - https://github.com/BiglySoftware/BiglyBT/wiki

Also, "search for existing data files" should work if you point it at "Y:\" as the root to search for rather than somewhere within the download's data.

**Comment by parg** [comment]
Nice one.

"search for existing data files (SFEDF) " works well when you're trying to match existing files from various sources with a torrent, but if you are recovering partial downloads as in your case then the explicit re-add + re-check works well. Of course, if you had 1000s of downloads that becomes a pain.

SFEDF requires the files you are searching to be fully allocated (i.e. their size on disk has to match the expected size in the torrent). If you have partial downloads and haven't explicitly fully allocated them then matching will fail.

**Comment by as-muncher** [comment]
Well, one has to keep an eye out for when a torrent is being added.  I know that sometimes, I have to delete the -1 from the end of the file and other times, biglybt seems to add the -1 anyways and not prompt that it's going to recheck.
