### ISSUE TITLE
Base64 error

### ISSUE THREAD

**Issue by arlexTech** [BiglySoftware/BiglyBT#2772]
Hello,
i'm trying to setup a biglybt instance on my headless debian server but i'm facing an issue
when i try to add a torrent on the web interface i have a have the following error:
Error adding torrent: error: NoClassDefFoundError: org/gudy/bouncycastle/util/encoders/Base64, ClassNotFoundException: org.gudy.bouncycastle.util.encoders.Base64

**Comment by parg** [comment]
That class is definitely in the BiglyBT.jar - where are you seeing the error? I assume you're using the "BiglyBT Web Remote" interface

**Comment by arlexTech** [comment]
oke it's solved
i was using the linux installer version so i downloaded the archieve and it runs perfectly

**Comment by ajdelgado** [comment]
Adding a local torrent file from the web interface, this error is shown
