### ISSUE TITLE
'reopening' 3.2 build for MacOs 13.0 X86 chip crash/popup

### ISSUE THREAD

**Issue by FranklinSeal** [BiglySoftware/BiglyBT#2773]
X86
That solved the problem. Thanks!

_Originally posted by @FranklinSeal in https://github.com/BiglySoftware/BiglyBT/issues/2770#issuecomment-1296179252_

**Comment by FranklinSeal** [comment]
Well, actually, it didn't. It seemed to have solved it, but then it started crashing again because despite having set the name/value per your instructions, the popup continues. Based on your guess about it having to do with the popup, however, I tried loading the magnet link directly into the search field (as opposed to clicking a magnet link in my browser with it set to auto open in BiglyBT.) By loading the link "manually" it then gives me the selector window when the torrent file is downloaded, instead of the donation popup. That workaround is successful at avoiding the crash. Assuming that perhaps the popup employs the "internal browser" function, I'm going to disable use of the internal browser and see if that solves it.

**Comment by jljiraffe** [comment]
How do you disable the internal browser function in BT?
