### ISSUE TITLE
The website is down

### ISSUE THREAD

**Issue by trodiz** [BiglySoftware/BiglyBT#2775]
Because the update plugin relies on the URL below, I am getting a 503 error code for the past two days.

`https://plugins.biglybt.com/update/pluginlist3.php`

**Comment by Hobbes-Is-Real** [comment]
I had just installed BiglyBT two days ago for the first time.... I thought this was my issue as I get the same error

**Comment by TuxPaper** [comment]
That's spooky.

I restarted the server.  Seems to be ok now

**Comment by as-muncher** [comment]
Yeah, I wonder why the website was down, because I got that error code too.
