### ISSUE TITLE
[Enhancement] Better access to log views?

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#2781]
I mentioned:

It's not part of **Help**, but I definitely think that _three_ copies of the **Log Views** list is excessive.

You can find it:
* As a submenu under **View**
* As a sub-submenu under **Tools > Plugins**
* Appended to the **Debug** menu

_Originally posted by @ferdnyc in https://github.com/BiglySoftware/BiglyBT/issues/2760#issuecomment-1304666387_

Thinking about it more, the menu should probably have _no_ list of individual logs, each of which opens an individual viewer instance.

Instead of opening individual, separate log views, a nicer interface might be to have a consolidated Log Viewer that provides access to everything, with a switcher that lists all of the available logs. I guess it would have to support multiple instances, so that someone who wants multiple logs open at once could still manage that.

(Also, why do some log-view sidebar entries have a context-menu **Options...** item that opens **Options > Subscriptions**? Seems like that's the default unless it's overridden for a particular log. (**Plugin Update > Options...** opens **Options > Plugins > Plugin Update**, for example.) But that seems like a super random default.)

**Comment by parg** [comment]
I'll fix the Subscriptions thing :)

**Comment by parg** [comment]
and some others but wait for the complaints!

**Comment by ferdnyc** [comment]
Why We Can't Have Nice Things™.
