### ISSUE TITLE
questions on BiglyBT's WebTorrent Protocol browser

### ISSUE THREAD

**Issue by SUCM** [BiglySoftware/BiglyBT#2783]
would like to clarify a few questions on BiglyBT's WebTorrent Protocol Chromium browser since I don't see the answers on the wiki or documentation

1. firewall reports that it's blocking all of this Chromium instance's connections (to the outside world). is this ok?
2. once the rare web client is gone, can we safely close the browser so that BiglyBT would only spawn browser again when another web client shows up? right now, it looks like BiglyBT wants Chromium to stay forever once you hit a web client
3. wiki say a dedicated instance of Chromium is used prior to 1.4.0, does that mean I no longer need this chromium to spawn when running BiglyBT 2.7.x.x with WebTorrent support? if so, is there any instruction on how to kill/remove just the Chromium while retaining WebTorrent support

**Comment by parg** [comment]
Since plugin version 1.4.0 the WebTorrent support plugin has the option to use a built-in WebRTC library instead of the Chromium browser. However, this requires you to be running with Java 11 or higher, so you need to ensure this is the case as BiglyBT comes with Java 8. See

https://github.com/BiglySoftware/BiglyBT/wiki/Java-Versions

If you use the Chromium based approach then in theory you can close the browser when idle and it will automatically re-open it whan required.

**Comment by SUCM** [comment]
I'm running Java 11. after updated to the 2nd latest Java 17 (latest is 19), installing BiglyBT using -manual option no longer accepts the java.exe file. Bigly Installer says no JVM could be found on your system.

Java 11 and newer seems to be adding a common path to system's PATH variable at <system root>:\Program Files\Common Files\Oracle\Java\javapath

**Comment by SUCM** [comment]
since the current Torrent Web Support plugin on my system is quite outdated, I decided to use plugin uninstallation wizard to uninstall the plugin and selected both UPNP Media Server along with WebTorrent Support. However, the whole BiglyBT just freezes at the uninstallation in progress forever (2 hours so far). I never saw next step t which is the confirmation of removal selection showing up. looks like uninstalling one of the (core?) plug-in would not work, but we probably need a better way than freezing the whole program to handle it. I'm going to use task manager to kill BiglyBT for now

**Comment by SUCM** [comment]
answering my own questions in this ticket

- the latest installer still checks for Java version between 1.8 and 13 to error out, but that doesn't stop the installed Bigly to run any newer Java found on the system
- after download BiglyBT installer and running installation with Java 11 to install latest BiglyBT 3.2.0.0, I was able to use plug-in uninstallation wizard to uninstall UPNP Media Server plugin. now it shows No Version
- since I updated to newer Torrent Web Support  plug-in where I opt to not use browser, firewall blocking browser connection is probably not as important now. would be interesting to know whether firewalling the browser would had any impact though

**Comment by ferdnyc** [comment]
@SUCM 

> 1. firewall reports that it's blocking all of this Chromium instance's connections (to the outside world). is this ok?

Is it blocking all connections _to_ the outside world, or **from** the outside world? Standard consumer Windows aren't set up to firewall outbound connections by default. If it has a rule explicitly blocking the connection, it will, but all other traffic is allowed.

What it **will** do is intercept any attempt to bind a local port to a listen socket, AKA the first step in receiving incoming connections from the outside world. When that happens, it displays the familiar firewall-authorization dialog and asks if you want to permit the process to receive data over the network.

Of course, if you're running a third-party firewall or your system is managed by corporate or campus IT, there may be restrictions above and beyond the standard Windows Firewall default configs.

Blocking inbound internet traffic from reaching Chromium, I would think is a good thing that you want.

(The fact that the firewall thinks it's _trying_ to accept network traffic is probably a false positive. BiglyBT and Chromium likely communicate over a "network" link between 
them, via sockets on the local network stack. That data is never routed to the external network, so it doesn't cross the firewall and the connection can be made even if the firewall is blocking incoming attempts. But, opening those internal network links _does_ catch the firewall's attention, as it can't tell the process is only listening for local traffic. So it offers to prevent external connection attempts.)

**Comment by ferdnyc** [comment]
> So it offers to prevent external connection attempts.

Correction: It's already preventing external connection attempts, has always been preventing them, and will continue to prevent them unless its configuration is changed. So the firewall is technically offering to create a rule in its configuration that will _start allowing_ external connections to the port(s) the process is listening on, since a listening process is clearly able to accept network connections.

**Comment by SUCM** [comment]
@ferdnyc 
we have third party firewall that differentiates protocol, inbound, outbound...etc

Chromium browser launched by BiglyBT was clearly initiating multiple outbound connections to domains like analytics.google.com, accounts.google.com...etc and IP addresses for DNS/peers discovery and whole bunch other things. these are completely unrelated to torrent which is why I asked. I don't use that browser and had tried followed online guides to disable Google accounts, update...etc on this Chromium browser yet it continues to make all those outbound connections multiple times every few minutes whenever it launched and running by BiglyBT
