### ISSUE TITLE
Mac OS 13.0 BiglyBT crashes when loading torrent file- using latest version

### ISSUE THREAD

**Issue by topdog111** [BiglySoftware/BiglyBT#2784]
* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment

**Comment by parg** [comment]
See https://github.com/BiglySoftware/BiglyBT/issues/2770 and https://github.com/BiglySoftware/BiglyBT/issues/2773

**Comment by topdog111** [comment]
thanks
tried both - logged Already Paid and True
Then pasted the torrent url into the Bgly window - started download - up popped the contribution window and she crashed (again). Seems clarly connected with the contribution prompt? Ideas?

**Comment by parg** [comment]
Enable

Options->Interface->Display: Disable all use of the internal browser.

**Comment by topdog111** [comment]
thank you
works for me 
very good
