### ISSUE TITLE
No Fallback to IPv4 when IPv6 tracker connection is refused

### ISSUE THREAD

**Issue by L2501** [BiglySoftware/BiglyBT#2788]
* Java 8
* BiglyBT 3.2

When a connection to dual-stack tracker over IPV6 is refused (firewall reject, not timeout) the tracker Errors permanently instead of trying over IPv4.

**Comment by parg** [comment]
Common scenario is it?

**Comment by parg** [comment]
There's a fix in the next beta, please test

**Comment by L2501** [comment]
when bind to single interface get connection refused (interface has ipv6 & ipv4). without binding works ok.
test torrent: [test.zip](https://github.com/BiglySoftware/BiglyBT/files/10701189/test.zip)

**Comment by L2501** [comment]
Did some more testing and enabling 
Options->Connection->Advanced Network Settings: Prefer IPv6 addresses when both IPv6 and IPv4 are available
breaks it. works ok with it disabled

**Comment by parg** [comment]
More tinkering in the next beta

**Comment by L2501** [comment]
:+1: working now with BiglyBT 3.3.0.1_B05
