### ISSUE TITLE
Allow minimizing BiglyBT while it is shutting down

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2793]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.2.0.1_B12/4 az3

On slow hard drives, and lots of torrents, it can take a while to shut down biglybt.  Could you please allow the user to click the minimize button so that biglybt can be minimized while it is shutting down?

**Comment by parg** [comment]
Try B13

**Comment by as-muncher** [comment]
Ok, thanks so much!
