### ISSUE TITLE
how do i remove a collapsed folder?!?!?!

### ISSUE THREAD

**Issue by fislysandi** [BiglySoftware/BiglyBT#2797]
![BiglyBT_fJDZ3l3Aql](https://user-images.githubusercontent.com/45166203/202472674-5c263c9e-73de-4a1d-8fb3-334520af005e.png)
![BiglyBT_QxYbmEYRXi](https://user-images.githubusercontent.com/45166203/202472692-a3f4734b-673a-4d5e-8d37-2f698723016a.png)
![BiglyBT_6NqOcl9ZfY](https://user-images.githubusercontent.com/45166203/202472695-778bd272-f15f-42a4-8740-fed319e95032.png)

i also wanna make a critique of this app in the future and outline what parts of it makes it suck. one of the reasons is this,

**Comment by parg** [comment]
Thanks for the feedback

**Comment by fislysandi** [comment]
sorry i found out how to close it
