### ISSUE TITLE
[Feature Request] add the ability to route search requests through the specificified ip and port (i2p/Tor)

### ISSUE THREAD

**Issue by fislysandi** [BiglySoftware/BiglyBT#2798]
![BiglyBT_jQLKEv4UAQ](https://user-images.githubusercontent.com/45166203/202567992-23ee48c3-c68f-47db-a3bc-fc382d5aa859.png)

is it possible to do it? i just dont want to enable tor for this.

**Comment by parg** [comment]
dunno, how do I2P out-proxies work?

**Comment by fislysandi** [comment]
hmm i added the outproxies to my external i2p installation maybe add a textbox where you can specify ip and port to route requests to? like 127.0.0.1 5678 .
