### ISSUE TITLE
follow system theme (gnome linux)

### ISSUE THREAD

**Issue by legacychimera247** [BiglySoftware/BiglyBT#2801]
I know biglybt is not a gtk app but it still would be nice if it could follow the system theme (dark or light variant) so that at night it's dark as the entire system and we don't need to set that manually

as the title suggest i am talking about the gnome desktop environment, since it has a dark/light mode (theme) available...

**Comment by parg** [comment]
So the "dark mode" works fine with BiglyBT when started with a dark theme, the issue is that it doesn't switch modes when already started?

**Comment by legacychimera247** [comment]
Exactly that, i need to manually check the respective boxes in settings, and since the app is rendered in gtk2 i also need to set the legacy dark theme in gnome tweaks tool, to have a black titlebar...
