### ISSUE TITLE
UI gets stuck in "All Blocks" view

### ISSUE THREAD

**Issue by david-bakin** [BiglySoftware/BiglyBT#2802]
BiglyBT 3.2.0.1-B20

BiglyBT gets "stuck" in "All Blocks" view.  ("All Blocks" view which I just discovered is totally great, BTW, very mesmerizing!)

Anyway, I'm not sure of the conditions, but when you switch into "All Blocks" view and you've got several torrents going (I've got a consistent max download speedof 160Mb/s in case it is "busyness" related) and let it run for a bit (I dunno, >30s) then you can't switch to another view by clicking on the other view's button in the sidebar.

Only way I've discovered to switch views, in this state, is to click on one of the top-level menu buttons on the menu bar.  Then it (nearly) immediately switches to one of the other views you've already clicked on.

**Comment by parg** [comment]
Ah! Yes, probably speed related, the view works well at lower rates but probably needs rework to be usable at 160Mb/s !

**Comment by parg** [comment]
Next beta (B21) has a limit to the number of active blocks shown:

Options->Interface->Display: Views: Blocks:  Max active blocks displayed - setting this too high will impact performance

lazy solution but probably sufficient
