### ISSUE TITLE
Solid green bar for a peer in "Peers View" - what does it mean?

### ISSUE THREAD

**Issue by david-bakin** [BiglySoftware/BiglyBT#2803]
This has been going on for quite awhile and I'm stumped.

Sometimes in the Peer View there will be one peer (never more than one) with a solid green bar.  What does that mean?

**Comment by parg** [comment]
established connection but no piece details yet

**Comment by david-bakin** [comment]
ok, even though the peer is uploading at a nice rate?  

![image](https://user-images.githubusercontent.com/4162948/205816168-99d090b4-6479-41f5-8983-ed9412aae732.png)

**Comment by parg** [comment]
Yup, don't need to have received a bitfield to service requests (technically)

I added the green state a while back because I was confused to see peers uploading without having sent a bitfield...

I guess it is a valid thing to do protocol-wise although I'm not sure why you would do that.
