### ISSUE TITLE
Lost all settings after todays update!

### ISSUE THREAD

**Issue by alexeipavlov** [BiglySoftware/BiglyBT#2805]
Lost all settings after todays update. Even 'exe' itself was lost.

**Comment by parg** [comment]
"today's update" being the latest beta (B21) or the latest full version update (3.2.0.0)?

User config and the .exe are stored in separate locations and would require different "failures" to cause both to be lost.

A beta update doesn't touch the .exe, it just updates the BiglyBT.jar file

A full version update (that goes through the installer dialogs) doesn't touch your settings unless you select the "clear configuration" option (which is defaulted to NO)
