### ISSUE TITLE
Always-high CPU usage (250%) when VPN enabled - MacOS

### ISSUE THREAD

**Issue by andrew-davie** [BiglySoftware/BiglyBT#2807]
BiglyBT 3.1.0.0 running on MacOS Ventura 13.0
MacBook Air 2022

Problem:  When VPN is enabled, BiglyBT hovers > 250% CPU usage.
When I disable the VPN, it drops down to about 50%. This is still very high, as I have no torrents active, and no files being shared. It's just the plain vanilla BiglyBT "doing nothing" in other words.  The VPN is Private Internet Access.
This problem has been bugging me for some time; I have only just realised it's VPN-related, hence this report.

To reproduce (for me!)
1. Start VPN (it's usually always on anyway)
2. Start BiglyBT.  Cpu is > 250% and remains there.
3. Disable VPN. BiglyBT CPU usage drops to about 50% and remains there.

<img width="467" alt="Screenshot 2022-12-10 at 2 31 27 pm" src="https://user-images.githubusercontent.com/16424075/206829340-a5846a00-216c-4a06-b7ab-f05aa989c89a.png">
<img width="617" alt="Screenshot 2022-12-10 at 2 33 42 pm" src="https://user-images.githubusercontent.com/16424075/206829347-0ae2b2ea-9f50-4524-87fc-2d0beabecbdf.png">

A secondary issue is - why is BiglyBT at 50% CPU or more, when it's doing nothing?

**Comment by parg** [comment]
BiglyBT knows nothing about the VPN - any increased CPU is caused by the VPN software.

Under Tools->Options->Startup & Shutdown: Java Options

there is a "JVM memory usage history" "View" button

This shows memory + CPU usage within BiglyBT

**Comment by andrew-davie** [comment]
> BiglyBT knows nothing about the VPN - any increased CPU is caused by the VPN software.
> 
> Under Tools->Options->Startup & Shutdown: Java Options
> 
> there is a "JVM memory usage history" "View" button
> 
> This shows memory + CPU usage within BiglyBT

I understand your reply, and I would just point out that I showed a system monitor screenshot - it is BiglyBT that is recorded in the OS as using 250% of CPU time.  The VPN is recorded as another process/thread, taking approximately 0.4% CPU.  There appears to be something happening here with BiglyBT that looks like it's chewing CPU time when it's configured to torrent only when the VPN is active.

Here's the requested(?) log of the JVM...  there is a clear difference where I turned off the VPN, though not as significant. Even if these figures were the entire CPU usage, BiglyBT using 50% of CPU while not torrenting is ... very strange to me (I'm a developer).  Both the upload and download graphs are showing 0 b/s.

When the JVM is showing 75% CPU (as below), the OS activity monitor is showing 233% right now.  Something's borked.

<img width="629" alt="Screenshot 2022-12-10 at 6 44 39 pm" src="https://user-images.githubusercontent.com/16424075/206841806-96a5c77c-6687-4ce4-9151-f34968ee8489.png">

**Comment by parg** [comment]
Disable the mlDHT plugin? Options->Plugins

Uncheck the "load at startup" box next to "mlDHT" and restart.

See if that helps?

**Comment by andrew-davie** [comment]
> Disable the mlDHT plugin? Options->Plugins
> 
> Uncheck the "load at startup" box next to "mlDHT" and restart.
> 
> See if that helps?

Yes. Huge difference.  CPU now hovering around 50% (OS value) regardless of if I enable the VPN or not.

**Comment by parg** [comment]
Unfortunately that plugin was mostly written by a third-party who no longer maintains it

**Comment by andrew-davie** [comment]
> Unfortunately that plugin was mostly written by a third-party who no longer maintains it

Is it required?  Can I torrent happily with it disabled?
Also, TY for the help.

**Comment by parg** [comment]
The plugin provides access to peers in the "mainline DHT". Generally speaking things work fine without it, you might just take a little longer to build up peer connections if downloading a torrent that has no working tracker (for example). Once a non-private download is up and running you can get peers from other peers and things work just fine.

**Comment by andrew-davie** [comment]
> The plugin provides access to peers in the "mainline DHT". Generally speaking things work fine without it, you might just take a little longer to build up peer connections if downloading a torrent that has no working tracker (for example). Once a non-private download is up and running you can get peers from other peers and things work just fine.

TY for the explanation.

**Comment by andrew-davie** [comment]
Confirming torrents still working for me with mlDHT disabled. CPU usage (OS value) now around 25% (instead of 250% previously). VPN on/off doesn't change that figure. Issue resolved for me, TY.  Happy for issue to be closed, but didn't do it myself as I expect you may want to keep the mlDHT bug/issue active.

**Comment by parg** [comment]
It must be something to do with the VPN's network interfaces and the way the plugin deals with them - unfortunately I've never encountered that myself and it is therefore hard to diagnose :( Might of course be OSX and/or VPN specific to complicate the issue
