### ISSUE TITLE
Error moving completed files

### ISSUE THREAD

**Issue by gh338** [BiglySoftware/BiglyBT#2808]
* Kubuntu 20.04.5 LTS
* 3.2.0.1_B21
* KDE Plasma 5.18.8 / Framework 5.68.0 / Qt 5.12.8

I get this message since a few months back  - not exactly sure with what BBT update it appeared:

Error moving completed files
Move of file /home/user/BiglyBT Downloads/<filename.extension> failed, File '/home/user/BiglyBT Downloads/<filename.extension>' has not been reserved (no entries), '<hashsum>[5]'

Please advise.

**Comment by parg** [comment]
No idea. "since a few months back" doesn't really help...
