### ISSUE TITLE
 Tracker Status & Tag Capability

### ISSUE THREAD

**Issue by MasTech** [BiglySoftware/BiglyBT#2809]
Do tag constraints recognize/read/understand the 'tracker status' column?

I am attempting to create a tag named 'Unrecognized' based of tracker status/response.  

When private trackers remove a torrent we generally see one of these as the tracker status: 
1. 'scrape error: file not found'
2. 'torrent not authorized for use...'
3. 'error (unregistered torrent)'
 
Even if the torrent is removed the transfer continues if seeds are already peered in the client. 

I would like to have the tag assigned to matched torrent/tracker response keywords/phrases (unregistered, not authorized for use, not found, etc.)

Is this possible? If yes... how? Can this be a feature request if need be?

* Win 10 / 11
* BiglyBT v3.2.0.0

**Comment by parg** [comment]
There is a "tracker_status" tag constraint variable. You can use a constraint of

contains( tracker_status, "unregistered" )

or 

matches( tracker_status, "unregistered|not\sauthorized" )

for example

 torrent can have multiple trackers, the "tracker_status" represents the response from the tracker that BiglyBT considers the "main" one.

**Comment by CTImundi** [comment]
I followed this when it was first asked. It worked perfectly.

I updated to 3.4.0.0 recently and noticed that the label isn't being applied using either example above nor either one below

contains( tracker_status, "unregistered|not\sauthorized|unauthorized" )

or

matches( tracker_status, "unregistered|not\sauthorized|unauthorized" )

**Comment by parg** [comment]
I have a constraint of

`matches( tracker_status, "scrape\serror" )`

thast works fine, so it isn't a general error.
