### ISSUE TITLE
Can't install BiglyBT

### ISSUE THREAD

**Issue by philming2022** [BiglySoftware/BiglyBT#2811]
Hi all,
I tried to reinstall BiglyBT, but the installer just hangs after the "install wizard" splash screen.
I have the installer in the dock named "java" but nothing happens...
Not sure what this is related to (authorisation from the system to access the disk ?)
Any help would be welcome :)

* MacOS Ventura
* BiglyBT 3.2.0.0
* For *nix: Desktop Environment

**Comment by parg** [comment]
Have you killed it and tried running it again? Might be a gremlin. 

Are you on Intel or Mac silicon? 

There is an unfortunate issues with WebKit on Intel with Ventura - https://bugs.webkit.org/show_bug.cgi?id=247387

Doesn't affect the installer but does cause BigylyBT to crash when using the SWT browser component (In the "Getting Started" view and donation popup)

**Comment by philming2022** [comment]
I'm still on Intel. Latest Mac OS.

**Comment by parg** [comment]
ah, yes, the magnet issue is that crash - BiglyBT tries to show the donation popup and that uses the SWT browser :(

**Comment by parg** [comment]
I've released a patch that should disable the internal browser and therefore prevent the crash. However I'm not sure what to suggest regarding the installer problem. I don't have access to a Mac with Ventura installed, mine is stuck on Big Sur :(

**Comment by philming2022** [comment]
Thanx for the input. I hope a new version of the installer comes out soon, I had to revert back to Vuze in the meanwhile... :-(

**Comment by parg** [comment]
If you have a chance can you try installing an older version of BiglyBT, just to see if that works? For example

https://github.com/BiglySoftware/BiglyBT/releases/tag/v2.8.0.0

has two assets

https://github.com/BiglySoftware/BiglyBT/releases/download/v2.8.0.0/GitHub_BiglyBT_Installer.dmg
https://github.com/BiglySoftware/BiglyBT/releases/download/v2.8.0.0/GitHub_BiglyBT_Installer_LegacyOSX.dmg

**Comment by philming2022** [comment]
Same issue on 2.8 I'm afraid. The installer asks permission to access the download folder, and then hangs. Nothings happens... I don't use a Firewall (and stuff like Little Snitch I've deactivated incase the issue was coming from there)...

Edit. Actually the "Legacy" allowed me to make the install, but then its the endless jumping of the icon in the dock. It doesn't go anywhere...

**Comment by parg** [comment]
OK, thanks for trying!

**Comment by philming2022** [comment]
My pleasure :) How can I be notified if something new shows up ?
It really is a bummer because Bigly's the only client I know of that uses IP binding (along with Vuze) and I really want to keep using this function (unavailable in all other clients I have tested...)

**Comment by parg** [comment]
It is possible to install it without using an installer, let me see if I can zip up something

**Comment by parg** [comment]
This is a zip of a clean install - put in it Applications and then unzip it

[BiglyBT_Update_3.2.0.0_osx_installed.zip](https://github.com/BiglySoftware/BiglyBT/files/10248021/BiglyBT_Update_3.2.0.0_osx_installed.zip)

**Comment by philming2022** [comment]
Thanx so much for trying :) But unfortunately this one went even run... Probably because it's an Silicon version ?

**Comment by parg** [comment]
It is intel - seemed ok on my MAC - you unzipped it I assume, it isn't an installer... Right-click and select extract (or something similar)

**Comment by philming2022** [comment]
Yes That's what I did. And launching it doesn't do a thing (no dock jumping or anything) I'm afraid...

**Comment by parg** [comment]
meh!

**Comment by parg** [comment]
We've rebuilt the OSX installer with the latest version of the packaging too - the assets have been replaced on

https://github.com/BiglySoftware/BiglyBT/releases/tag/v3.2.0.0

Can you give

https://github.com/BiglySoftware/BiglyBT/releases/download/v3.2.0.0/GitHub_BiglyBT_Mac_Intel_Installer.dmg

a whirl sometime? Thanks!

**Comment by philming2022** [comment]
YES ! Working flawlessly. Install, magnets, everything is working great now, thanx so much :)

**Comment by parg** [comment]
thanks for reporting and working through things!

**Comment by shadowfighter29** [comment]
Had same issue would not resolve using Mac_Intel dmg until clean uninstall and reinstall not keeping current configuration.

**Comment by nick-in-mersey** [comment]
> We've rebuilt the OSX installer with the latest version of the packaging tool - the assets have been replaced on
> 
> https://github.com/BiglySoftware/BiglyBT/releases/tag/v3.2.0.0
> 
> Can you give
> 
> https://github.com/BiglySoftware/BiglyBT/releases/download/v3.2.0.0/GitHub_BiglyBT_Mac_Intel_Installer.dmg
> 
> a whirl sometime? Thanks!

Thank you Thank you Thank you Thank you Thank you  Finally - a fix that works!!
