### ISSUE TITLE
Wrong DNS query string on macOS when using DNSCrypt proxy

### ISSUE THREAD

**Issue by jakwings** [BiglySoftware/BiglyBT#2813]
I wonder if this is why it always fails to install DNS manager since I've upgraded BiglyBT from v2.9 or what I don't remember.

Checking my dnscrypt-proxy logs it shows that BiglyBT is using `http://dns.test.client.biglybittorrent.com/` as a query string which is invalid. `nslookup http://dns.test.client.biglybittorrent.com/` returns either `REFUSED` or `NXDOMAIN`.

`nslookup dns.test.client.biglybittorrent.com` also returns NXDOMAIN.

**Comment by parg** [comment]
It is supposed to not exist. 

If the DNS proxy is installed then it intercepts this and returns something explicit to indicate that it is working

**Comment by parg** [comment]
Hmm, failing on Java 1.8 is indeed odd...

**Comment by parg** [comment]
Can you check the debug_1.log or debug_2.log files in the "logs" folder? See if there's anything that mentions the DNS issue in there.

**Comment by parg** [comment]
Interesting. I'll leave things at that, we're not far off switching away from Java 8 as our minimum Java level.
