### ISSUE TITLE
downloads.config corrupted after crash

### ISSUE THREAD

**Issue by daci12345** [BiglySoftware/BiglyBT#2814]
After a BBT crash downloads.config got corrupted (i think), and the ui doesn't load properly unless I delete that file. The problem with deleting that file is that I have over 370 torrents and readding it and pointing them to the downloaded path would take a lot of time. Is there any way to recover it somehow?

* OS and version EndeavourOS
* BiglyBT Version Number 3.2.0.0
* For *nix: Desktop Environment xfce4

**Comment by parg** [comment]
I assume you turned on backups - it does nag you regularly to do so.

If not then if depends somewhat on whether you have download the 370 torrents in their entireity or if you have partial files.

If you have generally downloaded all the files then add a bunch of them to the "add torrents" dialog and select the "search" button to locate the existing data files (multi-select the downloads in that dialog and do it once). This might require you to join the beta program, can't remember when the search feature was added.

If not then you can add all the torrents in a "stopped" state, multi-select them and use "search for existing files" context menu item

**Comment by daci12345** [comment]
Thank you for the tip with the stopped state, instead of hours it only took 30 mins to readd more or less everything. I have "Back up configuration files for recovery purposes" turned on, but downloads.config.bak was the default config file without my torrents, I only use BBT for a couple of weeks, maybe the back up didn't happened yet (which is strange since according to my fm the file was modified today, perhaps BBT backed up the corrupted config?).

**Comment by parg** [comment]
Glad you managed to recover things. The backup I'm talking about is under

Tools->Options->Backup & Restore

and can be configured to periodically save backups to an "external" location
