### ISSUE TITLE
Bind IP Null with VPN Helper (PIA)

### ISSUE THREAD

**Issue by Tarthrin** [BiglySoftware/BiglyBT#2816]
* OS and version : Windows 10 x64
* BiglyBT Version Number : 3.2.0.0

![Capture](https://user-images.githubusercontent.com/99377982/209155819-050774a8-41b7-45de-8e1f-5eff78523271.PNG)

Hello,

I am getting a "Bind IP Null" error with the VPN helper and PIA. I have an interface bound. "net1". I have also tried "net1[0]" and the specific IP address listed under net1[0] with no difference.

I have a port forward file listed in the VPN helper. I have also tried "use PIA's CLI to get an open port" and "Try port_forward_assignment RPC call to get an open port"

This started because I was able to download, but have been unable to upload. So I reset VPN settings and tried to re-do them to see if it would help. So I probably messed something up. To try and narrow down the issue I also installed qBittorrent to see if the issue was PIA or with BiglyBT. I am able to download/upload using qBittorrent, so I have the right interfaces/IP info. I checked the vpn and qBittorrent with https://ipleak.net/ and that seems to be working.

**Comment by parg** [comment]
Hmm, not sure why you're getting that... 

The error is generated when attempting to display your current ip binding, for some reason even though you have net1 there it isn't finding any. The way it looks for the current binding is a bit odd though, it checks BiglyBT's UDP handlers.

If you have set the bind address explicitly to net1 then things should be working - you should get a green pipe symbol in the status bar that shows the binding status.

**Comment by Tarthrin** [comment]
I ran the network status tool in Bigly and got the following:

Test starting
Default public address is X.X.X.X
Bindable addresses: X.X.X.X, X.X.X.X, X.X.X.X
0 NAT devices found
No SOCKS proxy found
No HTTP proxy found
1 bind addresses
    X.X.X.X 
Testing HTTP outbound
    Test successful
Testing TCP outbound
    Test successful
Testing UDP outbound
    Test successful
Testing TCP port PORTFORWARD# inbound
    Test failed: NAT test failed: Connection reset by peer (X.X.X.X:PORTFORWARD#)
    Check your port forwarding for TCP PORTFORWARD#
Testing UDP port PORTFORWARD# inbound
    Sending outbound packet and waiting for reply probe (timeout=5000)
    Sending outbound packet and waiting for reply probe (timeout=10000)
    Sending outbound packet and waiting for reply probe (timeout=15000)
    Sending completion event
    Test failed: Inbound test failed
    Check your port forwarding for UDP PORTFORWARD#
1 public/external addresses found
    X.X.X.X
    AS details: as=XXX,asn=XXX, XX, bgp_prefx= X.X.X.X, X.X.X.X, X.X.X.X
BiglyBT Services test
    BiglyBT Website - www.biglybt.com
        Certificate: CN=biglybt.com
        Connection result: 200/OK
    Version Server - version.biglybt.com
        Connection result: 200/OK
    Plugins Website - plugins.biglybt.com
        Certificate: CN=biglybt.com
        Connection result: 200/OK
Indirect Connect test
    Connecting to https://www.biglybt.com/
    Certificate: CN=biglybt.com
    Connection result: 200/OK
Distributed protocol test
  Incoming routing established for DE…
  Searching 0 contacts for 0 test targets
  Searching complete, 0 targets found
  Results
      insufficient outbound connects for analysis
  Incoming routing destroyed for DE…
Test complete
  Destroying tester

**Comment by parg** [comment]
Yes, well the VPN Helper plugin is supposed to help with the port forwarding - if it isn't then you need to manually figure out what the PIA port forwarding is and then set BiglyBT to use that port.

**Comment by Tarthrin** [comment]
Sorry I censored the number, but the number 12345 is shown in the PIA app and same in BiglyBT. I put that number in "Location (File/Url) containing open port number. It points to a .txt file with the number in it.

Under VPN helper it has "Excellent, Bind port already set to open port 12345"
Under Connection it has "Incoming TCP" and "UDP Listen Port" also set to 12345

**Comment by parg** [comment]
I'm not sure why the inbound test is failing then, sorry (don't have PIA to test with).

Note that this isn't a terrible problem to have, things will generally work well without incoming ports being open.

**Comment by Tarthrin** [comment]
I resol

**Comment by parg** [comment]
Glad you figured it out, let's hope it stays working!
