### ISSUE TITLE
Alt-space opens BiglyBT's windows menu and changes view mode

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2818]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.2.0.1_B24/4 az3

For some strange reason, my touchpad's not working, so I have to navigate using the keyboard and using Mouse Keys in Windows.  I'm noticing that when I press Alt-Space to bring up BiglyBT's window to minimise it or maximise it or whatever, I notice that BiglyBT also changes the view of my complete torrents (middle panel) to the torrents of my private tracker.  And also changes the incomplete torrents (top panel) to BiglyBT Updates.  Pressing Alt-Space again doesn't change the views, but at least the main BiglyBT window menu comes up.

**Comment by parg** [comment]
Sounds like more than your touchpad's broken

**Comment by as-muncher** [comment]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.2.0.1_B28/4 az3

I just tried it again.  When I press alt-space, my private tracker sections are highlighted (the button to the right of "BiglyBT Updates" fills in".  When I press alt-space again, they don't unselect.

**Comment by as-muncher** [comment]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.5.0.0/4 az3

What happens at this time is that, when pressing alt-space, the menu shows up, for Restore, move, etc. but also the private trackered torrents are shown only, and the website of the private tracker shown as a button, is selected.  Pressing alt-space again doesn't change anything.
