### ISSUE TITLE
Please use reddit for general discussion

### ISSUE THREAD

**Issue by parg** [BiglySoftware/BiglyBT#2821]
We're using reddit for general discussion, please head over to https://www.reddit.com/r/BiglyBT/

If you have specific BiglyBT bugs to report or have an enhacement request then go ahead and raise an issue here.

**Comment by nydave69** [comment]
tooo bad,  I avoid using reddit for anything.. Think discussions here would be more effective since the bugs are also reported here.

**Comment by parg** [comment]
Feel free to hang around here and help users with their issues.

**Comment by SimWarlock** [comment]
My Bigly has been downgrading time & time again this needs to be looked into
![Feb 8 24 (3-5-0-0)](https://github.com/BiglySoftware/BiglyBT/assets/144575246/68e124cd-9d57-4b7d-8034-5c87cdce0baa)
![2-9-24 update](https://github.com/BiglySoftware/BiglyBT/assets/144575246/d6a1a535-8673-49e4-ab9e-e62e0e422a3a)
![2-9-24 (3-4-0-0)](https://github.com/BiglySoftware/BiglyBT/assets/144575246/0b69eb0e-264d-433d-ad3d-23585ff5d400)

**Comment by NonVolatileHuman** [comment]
And what about help and support? The subreddit is almost barren.
