### ISSUE TITLE
Issues with naming - extension for incomplete files

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2825]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.2.0.1_B28/4 az3

So I had a torrent, showed up as complete in BiglyBT, seeding, but when I right-clicked the torrent, and "export data and torrent", to an external hard drive.  The torrent has one folder, and in the folder, the .avi file and the .jpg movie cover, or at least, that's what it's supposed to have.  So when I did the "export data and torrent", I noticed that just the folder was written to the external hard drive, but it was empty.  It showed as 100% done.  When I opened up the folder location, I saw that it had the .avi file, then a complete and viewable 01.jpg, and also a 01.jpg.!qB file.  When I did a recheck of the torrent, BiglyBT showed it as 99.8% complete instead of 100%.  I don't know why Bigly didn't look first for the complete file and then secondarily for one with the incomplete file extension, because it probably should have seen that the 01.jpg was complete, then possibly ignored or maybe deleted the one with the .!qB extension.  What I had to do is to delete the .jpg.!qB file, then do a recheck, and then when at 100% completion, then chose to export the torrent data and .torrent file, it exported everything correctly instead of the .jpg file, which it wrote to the external hard drive as .jpg.!qB.  I click on the torrent, look at the display name, and BiglyBT displays the .jpg file as .jpg.!qB, instead of .jpg.  The written .jpg.!qB file is viewable, complete, just with a wrong extension.

**Comment by parg** [comment]
Did you have the .jpg marked as "do not download"?

**Comment by parg** [comment]
If you have DND files then they won't be exported even if they happen to be complete because their content spans pieces from files that have been downloaded. So if you did that, switched the exported folder to be the save location of a torrent and then rechecked it you would end up with the DND files showing as incomplete.

**Comment by as-muncher** [comment]
I have since removed the torrent, but I am pretty certain that they were not set to "do not download", because I didn't change anything with the download status, and as I wrote, that the torrent data + .torrent file did export completely.  I find it kind of confusing, then, to know which option to choose so that I can copy my torrent data and .torrent file to a new location without Biglybt changing the save location for it.  

But no, I did just as I described above.

**Comment by as-muncher** [comment]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B3.2.0.1_B30/4 az3

I recently downloaded two torrents.   The second was internally linked with the first, at first anyways, and it linked at 99.8%, but then I did a piece mode search, pointing at the first torrent folder (which torrent was completed fully), and BiglyBT found no pieces, oddly.  Now, the second torrent has finished downloading, was checked, but the .!qB extension still remains, even though the torrent has been checked twice and now sits at 100% complete.  There are a couple of files that still have the .!qB incomplete file name extension.

**Comment by as-muncher** [comment]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B3.2.0.1_B35/4 az3
Ok so after I exported the first torrent, I deleted the data.  When I "Show in Explorer" with the second torrent having the same name as the first torrent (now gone), I see that most of the data is there, with some files with the .!qB extension, and this in the torrentname-1 folder.  But now I see that the torrentname folder has been re-created, with zeroed files, so I am guessing that that is why when I choose to re-check the torrent, that it shows as 0% done.  No option to "set location" to choose download location.  I chose "revert file locations", but that didn't do anything because the folder is where it's supposed to be, with the -1 appended to it, and then that option greyed out.  

When I add a torrent with one .torrent file name, and then try to add another torrent with different .torrent name but same display name, BiglyBT tells me that the media has already been added.  Thing is, it's a different torrent, with different content, different size.  You can use biglybt to download different magnet links, but the .torrent files will be saved as torrent.torrent and _torrent.torrent, but you can't open _torrent.torrent if its display name is the same as torrent.torrent's.

**Comment by as-muncher** [comment]
biglybt 3.4.0.0 on win 11 x64

the file extension for incomplete files has been added, but this is not happening for private trackered torrents.  I could make this a separate issue if you like.
