### ISSUE TITLE
Cleanup Request: Interface:Tags:File Extensions.

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#2826]
![image](https://user-images.githubusercontent.com/37715552/210086106-c1fbb52c-a3d1-4bce-ba73-056d4004f5a8.png)

The Above is what I got after removing Auto-Tagging of Video File Tagging.  After a Save, and Restart, the empty fields persists.

![Screenshot 2022-12-30 Interface-Tags-File Extensions](https://user-images.githubusercontent.com/37715552/210090403-316c31c0-03dc-4341-9337-e1729df4df90.png)

As you can  in the Mockup,  I am looking for something like, `Remove Blank Entries and Sort`. (Blank being File Extensions), TAGS can be Empty)    Also for easy cleanup, the X to delete the line, located on the left.

It should also be possible to Add File Extensions to a line and have the `Assign to Tag` be Empty. Thereby selecting them for download, but applying no TAG. So in the above, I would fill the File extensions with `mp4;m4p;mkv;mpg;mp2;mpeg;mpe;mpv;ogg;avi;wmv;mov;qt;webm` but leave the TAG Empty.

Java 1.8.0_351 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_351

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B3.2.0.1_B28/4 az3

**Comment by parg** [comment]
If you want to have a line be removed then it needs to be at the bottom I'm afraid...

You're confusing tagging with selection for download. The section about just deals with tagging. For download selection go to 

Options->Files: Extensions of files to auto-skip when adding a torrent [; separated]

**Comment by NaPurHab** [comment]
The images in my post are from the Options->Files: Extensions.    I am asking for **Sorting**, to put the Blanks at the bottom, then if there are 2 or more blanks the extra can be removed.  OR like I asked add a X on the Left to Delete the entry/line.

Wait 20 minutes for my next post which is related. It has to do with Options->Files: Torrents.

**Comment by NaPurHab** [comment]
The X are a bit big, Half that size would look better.  Now one more place they could be useful. IN Files: Torrents, Take a look.

![image](https://user-images.githubusercontent.com/37715552/210899889-42ea3c9a-c92c-4aea-838f-5bd7275e616f.png)

Again a SMALL x in the already existing space on the Left would work well. :)

**Comment by parg** [comment]
Really? I hadn't though of that.

**Comment by NaPurHab** [comment]
Works anywhere there is an `ADD` button, as there are in the above and the extensions.  Still think a small lowercase x at the front in the empty space would work well.  I use a portrait mode on my monitor, so horizontal space is at a premium.

You could also put a Empty check box at the front of each line, and to the right of the `ADD` button, place a `Remove aelected Directories` and a `REMOVE` Button.  A balanced solution.
