### ISSUE TITLE
Auto Select Subtitles (Interface:Tags)

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#2827]
Some torrents have a lot of subtitles for the video(s).  I see a possibility to Auto Tag them. It would be 2 fields. 

The first a Text Field for the Subtitle Format for example (srt;ssa;ass). There are other Text Based formats, but I rarely see them. And sub is usually with and idx so is image based, though there is a Text based sub file.

The Second would be a Multi-Select Drop Down, containing a List of all Languages found in Torrents. For example here are 2 images of Languages I commonly Select, and the 2nd of all the DND Languages.

![image](https://user-images.githubusercontent.com/37715552/210094871-c1f8ef9a-2e3c-41b3-8266-829a2b556740.png)
![image](https://user-images.githubusercontent.com/37715552/210094944-3622f0a7-570a-479d-8df6-83bf841bc9f2.png)

The name format is 1 or more #s followed by and underscore, the Language and finally the extension. The Language is either Full Name or 3 character Code.  So a Multi-Select Drop Down for all the Languages would speed a tedious task along.

Here is a link to a Wikipedia Article on Language Codes:

[List of ISO 639-1 codes][(url)](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes#:~:text=List%20of%20ISO%20639-1%20codes%20%20%20,aka%20%2B%202%20%2046%20more%20rows%20)

A few like Chinese have multiple  `zho , chi`. One is for Traditional the other for Simplified. But with the list, it should help to get them all.

As I indicated in the title, I think this fits in the `Interface:Tags:Auto Tagging` section.

Java 1.8.0_351 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_351

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B3.2.0.1_B28/4 az3
[Chinese](https://en.wikipedia.org/wiki/Chinese_language)	[zh](https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?iso_639_1=zh)	zho	chi

**Comment by NaPurHab** [comment]
Oh one addition, default for the subtitle type(s) field should be `srt;ssa;ass` and Default for the Multi-Select Drop Down should be `All`.

**Comment by parg** [comment]
Most likely all the subtitles fit into a single piece and will be downloaded regardless.

**Comment by NaPurHab** [comment]
Not a single piece, they are all separate files.  Perhaps a Table, with the left column containing extension, and a 2nd column with the languages.  For example:

Column 1 (File Extension(s), ; seperated): srt;ssa;ass
Colmn 2 (Languages, ; separated): English;Chinese;Vietnamese
Note: Extensions and Languages will be selected for download, other files will follow pre-existing auto select rules. Languages are sub-strings i.e. 3_English.srt
