### ISSUE TITLE
Options->Files: Torrents - Bypass DL Dialog, Go direct to DL

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#2828]
I would like a Selectable option to make Imported Torrents from a path to nat be stopped at a DL Dialog.  I cam home from a trip, I had saved some torrents to my Google Drive on my Laptop, And then my PC Opened the DL Dialog and waited for me to come home. I had 32 windows open. I have the following set:
![image](https://user-images.githubusercontent.com/37715552/210097652-9185387a-0ac2-48de-9688-25c0a441323c.png)
This is because I want the DL Dialog to stay open for torrents I add from Magnets or are Add by Sonarr.  Torrents save to disk for Import should obey all Auto Tag/Select rules, then start immediately.

I realise that one solution doesn't fit all. So why I want an Option for **`Bypass DL Dialog and DL Immediatelly`**

Combined with Auto Tag/Select, the below Adds the TAGS. So I am good to go.

Though it would be nice if I could in the `Assign to Tag` Enter something like Movies;PLEX    A few of the paths I want more than 1 Tag on.  This is why on the previous posts I wanted to be able to Select Video File Types without including a TAG.  As not all target torrents would need that Tag.

![image](https://user-images.githubusercontent.com/37715552/210097415-4e206d8b-5152-4a1b-af68-5d9b9e3ebdd6.png)

Java 1.8.0_351 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_351

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B3.2.0.1_B28/4 az3

**Comment by parg** [comment]
If you want to assign multiple tags on torrent import then create an intermediate tag and set it's "execute on assign" to assign the tags you want.

**Comment by parg** [comment]
AFAIK any .torrent files auto-imported don't go through the "torrent options" dialog so not sure what you mean.
