### ISSUE TITLE
Cross Seeding — BitTorrent v2 root hash

### ISSUE THREAD

**Issue by kovalensky** [BiglySoftware/BiglyBT#2829]
My question is duplicate of [#2296](https://github.com/BiglySoftware/BiglyBT/issues/2296) 

Any updates on this one? 
Since qBitTorrent introduced creating hybrid torrents as default, more people were creating BitTorrent v2 supported torrents.
I started this discussion in libtorrent https://github.com/arvidn/libtorrent/issues/6289 also, there were nice proposals but then it got dead, since maintainer doesn't have time for new feature development.

I was wondering if BiglyBT could deliver such distinct feature, with relatively small memory consumption and easy design, for it to be become a proposal BEP to other clients to implement it too. Thanks.

**Comment by parg** [comment]
BiglyBT has been doing an approximation of this using file size (in the absence of root hashes) for a long time, I don't see the need to do anything more.

**Comment by kovalensky** [comment]
> BiglyBT has been doing an approximation of this using file size (in the absence of root hashes) for a long time, I don't see the need to do anything more.

I didn't understand it first, now I do. Thanks.

In this case there's no need for new protocol implementation, only one more additional check:

If BiglyBT in accordance with BEP52 set 4th most significant bit in the last byte of the reserved bitfield request (for v1 hashes found in DHT), so that remote peers could respond with new v2 info hash with file root hashes in metainfo dictionary, it would speed up approximation for BiglyBT, since in this case there wouldn't be need for downloading this file with same size and again checking it for piece match, since its sha2 hash already differs.
It would accelerate scanning for hybrid or v2 only torrents.

**Comment by kovalensky** [comment]
No answer followed
