### ISSUE TITLE
B33: Dark Mode Issues: Testing Results

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#2832]
Noticed B33 was mostly about Dark Mode, So I turned in Interface: Color Scheme, I turned on the Options:
Force non-system colors to grayscale
Dark Tables
Miscellaneous Other Dark Things

Here is an image:
![image](https://user-images.githubusercontent.com/37715552/211403605-bc426b70-4297-4029-8580-d7d2e2db11f3.png)

The Result is this:
![image](https://user-images.githubusercontent.com/37715552/211405728-e6bb4b13-ac5d-42fb-b0ac-50c4c8680ee7.png)

As you can see in the image, in the download section the light grey rows the text is difficult to read. While in the Seeding section, the Dark rows are not showing contrasting text but the base black text. Black on Black doesn't work.  I suggest the solution to Dark Mode is to have Pre-set Themes As tiles like this:
![image](https://user-images.githubusercontent.com/37715552/211407275-6c4a2e98-e37d-46e2-a15e-6bc84d343349.png)

Then Dark Mode, or any other color setup can be a predefined and tested Theme. Ensuring that what you intended actually works. While keeping the current settings as a Custom Mode. Perhaps Radio Buttons to choose Themes or Custom.

As for me, I probably will never use it. Just thought I would test it and report my results. Since B33 was focused on Dark Mode, and had 6 lines of changes. Whole point of Beta Testing.

No reply needed, you can Close this once you read it. Hope it helps iron out the wrinkles.

Java 1.8.0_351 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_351

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B3.2.0.1_B33/4 az3

**Comment by parg** [comment]
Dark mode doesn't work properly on Windows as SWT doesn't support it. Try Linux/OSX, it works pretty well...

**Comment by parg** [comment]
Here's an example from Kubuntu

![image](https://user-images.githubusercontent.com/395293/211411818-1500d879-c3e3-4ea1-9340-bf44fffd1115.png)
