### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by francescocmazza** [BiglySoftware/BiglyBT#2833]
Hello,
I would like to migrate my torrent library from  vuze to biglybt. I need to keep inherit the custom torrent settings for each torrent in order to migrate, so importing just the all the torrent files won't do the trick for me.  Comparing backup files in both programs it seems that the core of the application is the same as backup files are extremely similar between the two applications. is there some way I can perform  this operation or could this feature be implemented?

thank you so much

**Comment by parg** [comment]
When you install BiglyBT there is an option to migrate from Vuze. It tries to migrate quite a lot of the settings but I'm not sure it does it 100%. You could try and see - it doesn't touch your Vuze settings so if it didn't do what you want it wouldn't cause any "damage".

Most of the download specific settings are stored in the "active" directory in the config folder. There is a file in there for each download in your library - it is named after the torrent hash of the download.

If some download-specific settings aren't migrated then you could try

1) perform the migration
2) stop BiglyBT
3) copy the /active directory contents from Vuze to BiglyBT
4) restart BiglyBT
5) cross your fingers

**Comment by francescocmazza** [comment]
hello, sorry for the late reply.
I tried using the restore procedure from vuze backup. the restore completes
saying that it needs to restart biglybt to complete the restore from
backup, but actually it never restarts the program. even if I do restart it
manually no changes appear. The log reports the following:

[23:04:37] DEBUG::Sun Jan 15 23:04:37 CET 2023
 com.biglybt.ui.swt.systray.TrayDork
[23:13:50] [alert] Alert:3:Can't restart without the 'azupdater' plugin
installed
[23:13:50] [stderr] DEBUG::Sun Jan 15 23:13:50 CET
2023::com.biglybt.core.util.DebugLight::printStackTrace::35:
[23:13:50] [stderr]   com.biglybt.core.CoreException: Can't restart without
the 'azupdater' plugin installed

I cant seem to find this plugin neither on my boglybt installation nor in
the available additional plugins.

can you please help me?

thank you very much
Francesco

Il giorno lun 9 gen 2023 alle ore 22:44 parg ***@***.***> ha
scritto:

**Comment by parg** [comment]
Don't install BiglyBT from the package on whatever Linux you're running, install it from https://www.biglybt.com/

Then try again.

**Comment by francescocmazza** [comment]
Will do and get back to you. Thank you!

Il lun 16 gen 2023, 22:37 parg ***@***.***> ha scritto:

**Comment by francescocmazza** [comment]
Tried with the latest version from website, Still cannot restore vuze
backup. here is the error log i'm getting when starting biglybt from
linux terminal:
﻿

(BiglyBT:8443): Gtk-CRITICAL **: 01:25:51.896: gtk_container_foreach:
assertion 'GTK_IS_CONTAINER (container)' failed
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f33d1c4f3cd, pid=8443, tid=8460
#
# JRE version: OpenJDK Runtime Environment (11.0.17+8) (build
11.0.17+8-post-Ubuntu-1ubuntu222.04)
# Java VM: OpenJDK 64-Bit Server VM
(11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode, sharing, tiered,
compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libswt-pi3-gtk-4942r22.so+0x4f3cd]
Java_org_eclipse_swt_internal_gtk_OS_G_1OBJECT_1TYPE+0x0
#
# Core dump will be written. Default location: Core dumps may be
processed with "/lib/systemd/systemd-coredump %P %u %g %s %t
9223372036854775808 %h" (or dumping to
/home/gamesvm/Programs/biglybt/core.8443)
#
# An error report file with more information is saved as:
# /home/gamesvm/Programs/biglybt/hs_err_pid8443.log
Compiled method (nm)   64981 4261     n 0
org.eclipse.swt.internal.gtk.OS::G_OBJECT_TYPE (native)
 total in heap  [0x00007f34004d2390,0x00007f34004d2738] = 936
 relocation     [0x00007f34004d2508,0x00007f34004d2538] = 48
 main code      [0x00007f34004d2540,0x00007f34004d2730] = 496
 oops           [0x00007f34004d2730,0x00007f34004d2738] = 8
Compiled method (nm)   64983 4261     n 0
org.eclipse.swt.internal.gtk.OS::G_OBJECT_TYPE (native)
 total in heap  [0x00007f34004d2390,0x00007f34004d2738] = 936
 relocation     [0x00007f34004d2508,0x00007f34004d2538] = 48
 main code      [0x00007f34004d2540,0x00007f34004d2730] = 496
 oops           [0x00007f34004d2730,0x00007f34004d2738] = 8
Compiled method (nm)   65016 4261     n 0
org.eclipse.swt.internal.gtk.OS::G_OBJECT_TYPE (native)
 total in heap  [0x00007f34004d2390,0x00007f34004d2738] = 936
 relocation     [0x00007f34004d2508,0x00007f34004d2538] = 48
 main code      [0x00007f34004d2540,0x00007f34004d2730] = 496
 oops           [0x00007f34004d2730,0x00007f34004d2738] = 8
#
# If you would like to submit a bug report, please visit:
#   https://bugs.launchpad.net/ubuntu/+source/openjdk-lts
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
./biglybt: line 227:  8443 Aborted                 (core dumped)
${JAVA_PROGRAM_DIR}java -Xmx256m -cp "${CLASSPATH}"
"-Djava.library.path=${PROGRAM_DIR}"
"-Dazureus.install.path=${PROGRAM_DIR}" "-Dazureus.script=$0"
${JAVA_PROPS} ${JAVA_ARGS} ${START_CLASS} ${OTHER_PARAMS} "$@"
Exit from BiglyBT complete
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by
com.biglybt.core.util.spi.AENameServiceJava9
(file:/home/gamesvm/Programs/biglybt/BiglyBT.jar) to field
java.net.InetAddress.impl
WARNING: Please consider reporting this to the maintainers of
com.biglybt.core.util.spi.AENameServiceJava9
WARNING: Use --illegal-access=warn to enable warnings of further
illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
No shutdown tasks to do
BiglyBT TERMINATED.


What can I do? Thank you!

Il giorno mar 17 gen 2023 alle ore 00:22 francesco Claudio Mazza
***@***.***> ha scritto:

**Comment by parg** [comment]
Not having much luck are we!

I've seen that crash on exitting BiglyBT but never on startup. Referenced in that crash log you posted is this file:

/home/gamesvm/Programs/biglybt/hs_err_pid8443.log

can you upload that to this issue please?

**Comment by francescocmazza** [comment]
Hello, well, thank you very much for your help in the meanwhile!
here is the file it is referring to. I hope you can make some sense of
it, honestly I have no clue!

Thank you friend

Il giorno mar 17 gen 2023 alle ore 11:44 parg
***@***.***> ha scritto:

**Comment by parg** [comment]
Hmm, it doesn't seem as if you attached the file - try going to https://github.com/BiglySoftware/BiglyBT/issues/2833 in a browser and drag+dropping the file onto a reply

**Comment by francescocmazza** [comment]
oops, sorry. here it is
[hs_err_pid8443.log](https://github.com/BiglySoftware/BiglyBT/files/10446578/hs_err_pid8443.log)

**Comment by parg** [comment]
Try downloading this file

https://biglybt-files.s3.amazonaws.com/core/BiglyBT3201-B38-signed.jar

Then rename it to BiglyBT.jar and use it to replace the existing one in the BiglyBT installation folder, /home/gamesvm/Programs/biglybt/  ( I assume)

**Comment by francescocmazza** [comment]
Thank you friend for your kind help. Still no luck. Biglybt does not start
with your update.
Here is the error I'm receiving when I start it from terminal:
---------------
Starting BiglyBT...
Suitable java version found [java = openjdk 11.0.17 2022-10-18]
SWT v4.956
Invalid maximum heap size: -Xmx1g
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Loading BiglyBT:
Invalid maximum heap size: -Xmx1g
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Exit from BiglyBT complete
Invalid maximum heap size: -Xmx1g
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
BiglyBT TERMINATED.
----------------

Thanks!


Il giorno mer 18 gen 2023 alle ore 14:30 parg ***@***.***> ha
scritto:

**Comment by parg** [comment]
If you edit the script that you're using to start biglybt ("biglybt") then it should have a line like

```
${JAVA_PROGRAM_DIR}java -Xmx256m \
        -cp "${CLASSPATH}" \
        "-Djava.library.path=${PROGRAM_DIR}" \
        "-Dazureus.install.path=${PROGRAM_DIR}" \
        "-Dazureus.script=$0" \
        ${JAVA_PROPS} \
        ${JAVA_ARGS} \
        ${START_CLASS} \
        ${OTHER_PARAMS} \
        "$@"
```

in it. I have no idea where the -Xmx1g error you're getting is coming from, as you can see from the above it is supposed to be 256m - did you edit the file? Perhaps you didn't edit it correctly?

**Comment by francescocmazza** [comment]
Hello, no. Ididnt edit it. Will correct that script by your explanation and
get back to you
Thank you

Il mer 18 gen 2023, 23:29 parg ***@***.***> ha scritto:

**Comment by francescocmazza** [comment]
Your solution worked! My vuze backup was also backing up that setting that
was not being recognized by BigLyBT, that's why it could not start or apply
the changes I guess. Anyway with your Jar update and your feedback on the
memory allocation I was finally able to make it work! Thank you so much!

Il giorno mer 18 gen 2023 alle ore 23:55 francesco Claudio Mazza <
***@***.***> ha scritto:

**Comment by parg** [comment]
Great!
