### ISSUE TITLE
Why Dashboard sites are not browsable?

### ISSUE THREAD

**Issue by Real1-0912** [BiglySoftware/BiglyBT#2835]
I have added some websites to dashboard but clicking on the links doesnt work? s there any way to enable it?

**Comment by parg** [comment]
We have had a lot of issues in the past with the built-in browser that BiglyBT uses and its support for arbitrary HTML (causing crashes etc). You will also note that there are no browser controls (forward/back etc) which makes navigation somewhat hard...

So it is restricted to rendering the page unfortunately.

**Comment by parg** [comment]
I could add an option to allow links to be followed, think it is worth it?

**Comment by admobmj** [comment]
Yes
whats the engine for the browser? seems very weak!
