### ISSUE TITLE
select file

### ISSUE THREAD

**Issue by arkmch** [BiglySoftware/BiglyBT#2846]
* OS and version: Linux Mint
* BiglyBT Version Number: 3.2.0.0
* For *nix: Desktop Environment: XFCE  

"Show file" should open the default file manager and select the file in its directory.

**Comment by arkmch** [comment]
"Show file" should select or highlight the file in its directory.

**Comment by parg** [comment]
Works on Kubuntu, must be something strange about Mint/XFCE

**Comment by arkmch** [comment]
I should add that the default file manager is Nemo and  "Show File" opens the containing directory but does not select any the file in the directory.

**Comment by arkmch** [comment]
Hi,

I have just noticed you closed the issue. I have just tested it with linux
mint mate and it is still there. Show file opens the containing directory
but does not select the file. Why would this be a problem at all? No
problem if there are only a few files in the directory, but it becomes an
issue if there are tens of files in it. This is the way show file works
with chrome on Linux or used to work with Vuze (did not test it with
BiglyBT) on Windows.

**Comment by parg** [comment]
There's no general way of opening the default file manager with a file selected on Linux that I know of.

On my kubuntu (KDE Plasma) you can execute

`dolphin --select <file>`

But what about other file managers? https://itsfoss.com/file-managers-linux/ lists a few...

**Comment by parg** [comment]
I'll add a new type of "launch helper" (Options->Interface->Table) that allows you to specify your own command line syntax to be executed when you "show file"

**Comment by parg** [comment]
Beta 3501_B18 supports this, give it a go:

![image](https://github.com/BiglySoftware/BiglyBT/assets/395293/6fc34dc4-f04c-456c-81f2-d37c0222aa82)

**Comment by arkmch** [comment]
Thank you. Works form me now.
The command I use is /usr/bin/nemo (no command-line arguments).

**Comment by doggeddalle** [comment]
> Beta 3501_B18 supports this, give it a go:
> 
> ![image](https://private-user-images.githubusercontent.com/395293/296756938-6fc34dc4-f04c-456c-81f2-d37c0222aa82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MTQxMDQsIm5iZiI6MTczMjUxMzgwNCwicGF0aCI6Ii8zOTUyOTMvMjk2NzU2OTM4LTZmYzM0ZGM0LWYwNGMtNDU2Yy04MWYyLWQzN2MwMjIyYWE4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNVQwNTUwMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOTYyYTg5NGJmZTUwYjYzMTQ0ZjM0OTMzNjg1NWQ4NGJhMzRlODVkMTllODdhMTQ3MDZhZDQzOTM1Yjg1YTdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vS9y8-fHQJkT0jXN1_F6xGMWk60L7zjG1H-2qm6HyOw)

confirmed working in nemo with command

`nemo --no-desktop`
