### ISSUE TITLE
Client filter

### ISSUE THREAD

**Issue by daci12345** [BiglySoftware/BiglyBT#2847]
I think a tixati like client filter would be a nice addition to BBT, we would have an option to block clients that were designed to leech, and harm torrent swarms.
Example image:
![example](https://i.postimg.cc/7hBsN4Nc/b.png "example image")

**Comment by parg** [comment]
You can already achieve something like this by using "Peer Sets" - https://github.com/BiglySoftware/BiglyBT/wiki/Speed-Limit-Scheduler#peer-sets

For example, add the following to the speed limit configuration:

peer_set Leechers=All,client=(?i)(xunlei|QQ|bitcomet|flashget|torch|mediaget|bitlord|unknown|^ttorrent)

This will create a Peer Set Tag named "Leechers" in your sidebar (assuming you have enabled Options->Interface->Tags: Show Tags in Sidebar)

You can right-click on this and select "Execute on Assign->Disconnect" to disconnect any peers that match the regular expression in the Peer Set config

**Comment by daci12345** [comment]
Thanks, it seems to work alright.

**Comment by parg** [comment]
You can also set upload/download limits instead of disconnecting peers.
