### ISSUE TITLE
Add "export configuration" to Tools menu

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#2851]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B3.2.0.1_B46/4 az3

I see biglybt mention from time to time that I should make a backup of my configuration.  So why not put an option like that in the Tools menu, so that it is easy to find?

**Comment by parg** [comment]
Users are continually prompted to turn on backups. Can't protect against stupid.

**Comment by as-muncher** [comment]
@parg.  Lol.  :)  You are good with words - answering a question and insulting at the same time.  :)
