### ISSUE TITLE
Java 17 - Issues with dorkbox-systemtray shows blank UI

### ISSUE THREAD

**Issue by biggestsonicfan** [BiglySoftware/BiglyBT#2853]
* Linux - OpenSUSE Tumblweed
* BiglyBT Version Number : 3.3 (assumed)
* For *nix: KDE Plasma

![Screenshot_20230202_004223](https://user-images.githubusercontent.com/9744201/216274548-18eec88a-8eb1-4766-95ab-e67905a15aa0.png)

The UI appears to be completely broken. `View`, and `Community` menu dropdowns are blank. I can't initiate any dialog boxes such as "Open Torrents" or "Tools - > Options". "Generate Debug Info" also does not work.

**Comment by parg** [comment]
Suse Leap works, probably some SWT issue on whatever version it is you're using. Try updating GTK and check the console for errors

**Comment by parg** [comment]
The previous SWT version is available here

https://biglybt-files.s3.amazonaws.com/swt/swt-4942r22-gtk-linux-x86_64.zip

With 3.2beta + 3.3 if you are running Java 11 or higher BiglyBT switches to a newer version of SWT (SWT stopped supporting Java 8 a while back)

**Comment by biggestsonicfan** [comment]
> Suse Leap works, probably some SWT issue on whatever version it is you're using. Try updating GTK and check the console for errors

Did a `zypper dup` shortly before this, all packages are up to date and I get the `Nothing to do` message.  See attached log for terminal output: [terminal-output.log](https://github.com/BiglySoftware/BiglyBT/files/10567187/terminal-output.log)

**Comment by biggestsonicfan** [comment]
> The previous SWT version is available here

Did the trick, so BiglyBT is running for now. It's already asking for a restart for the update to which this time I will tell it to restart later. Output of about: 
```
Java 17.0.5 (64 bit)
  N/A
/usr/lib64/jvm/java-17-openjdk-17

SWT v4942r22, gtk/3.24.35, zoom=100, dpi=91
Linux v6.1.8-1-default, amd64 (64 bit)
B3.3.0.0/4 az3
```

**Comment by parg** [comment]
Nothing of significance in the log unfortunately, which is odd if the UI is totally borked with the new SWT ;(

I'll install Tumbleweed, see what I can see.

Obviously once you restart BiglyBT you'll be back where you were. I can disable the newer SWT updates for linux but that'll currently affect all linux users.

**Comment by biggestsonicfan** [comment]
> Nothing of significance in the log unfortunately, which is odd if the UI is totally borked with the new SWT ;(

Trying to copy the log, the line which produced `org.eclipse.swt.SWTException: Invalid thread access` appeared once per second indefinitely until Java was manually killed.

**Comment by parg** [comment]
Yup, there's something obviously wrong there but I can't see how it can affect BiglyBT UI in a significant way. That error is to do with the "Dorkbox" system tray BiglyBT uses.

**Comment by biggestsonicfan** [comment]
Ah, well, if there's anything further I can do to assist in debugging, I'd be more than happy to help!

**Comment by parg** [comment]
Installed Tumbleweed,, KDE Plasma, seems to work fine with the updated SWT in light and dark modes

Hmmm!

![image](https://user-images.githubusercontent.com/395293/216296855-90630269-d17b-47a7-bb2b-a64ef932478e.png)

**Comment by parg** [comment]
You have a DPI of 91- interesting number, any idea why it is that?

**Comment by parg** [comment]
Could you try removing the "dorkbox-systemtray.jar" in the biglybt installation directory? See if that makes any difference

**Comment by biggestsonicfan** [comment]
> You have a DPI of 91- interesting number, any idea why it is that?

Actually, I have no idea... I should probably change that, lol.


> Could you try removing the "dorkbox-systemtray.jar" in the biglybt installation directory? See if that makes any difference

Oh ho, that did the trick!

**Comment by parg** [comment]
hmm, have to think on that!

**Comment by zkwj** [comment]
Same issue for me. Removing the dorkbox-systemtray.jar file made it work as well. I'm on a slightly older build of Tumbleweed:
# VERSION="20230129"

Let me know if there is anything I can provide that will be of assistance.

**Comment by parg** [comment]
don't suppose you have a copy of the removed jar?

**Comment by zkwj** [comment]
[dorkbox-systemtray.zip](https://github.com/BiglySoftware/BiglyBT/files/10571397/dorkbox-systemtray.zip)

**Comment by parg** [comment]
Ah, ok, seems to be Java version related. Java 11 is fine with the dorkbox jar but Java 17 is screwed. Very odd, I'll carry on investigating

**Comment by zkwj** [comment]
Thanks for all the work you do, much appreciated!

**Comment by biggestsonicfan** [comment]
Just did a fresh install on top of my old OS and was greeted with this.

![Screenshot_20230609_131010](https://github.com/BiglySoftware/BiglyBT/assets/9744201/26bdd6ad-4a45-42ea-a68a-45772bea15d2)

Is it safe to close the issue as resolved?

**Comment by parg** [comment]
You tell me :)

**Comment by biggestsonicfan** [comment]
The only odd thing here, however, was that after I restarted BiglyBT, I found out I installed my OS incorrectly. Accidentally installed it with legacy boot on the partition instead of uefi, so I had to reinstall the OS again. No biggie, but after installing BiglyBT on top of my data again, the dialog box did show again, which I thought it had detected and removed it the first time.
