### ISSUE TITLE
Retry same piece over and over and over ... (rare issue)

### ISSUE THREAD

**Issue by david-bakin** [BiglySoftware/BiglyBT#2855]
Last saw it sometime _before_ upgrade to 3.3.0.1 (which of course was quite recent).

Sometimes, and I mean very rarely, I get a torrent that runs nicely all the way to _nearly_ the end, then the last piece retries over and over and over ... and over again - checksum error I presume.

Now the interesting thing is that for these torrents it _always_ works to stop it, force recheck it, then start it again.  And, voilà! - last piece runs fine, torrent is complete.

So - something somewhere got corrupted.  The issue is that this keeps going until I come back later and discover it and reset it as above.

Suggestions:

1) Iteration count - if a single piece fails too often (especially if it is the _last_ one!) - error the torrent with an explanatory message.
1) Super duper extra credit - stop the torrent, force recheck it, start it again, then only error it out if that piece continues to fail.

Really, it is quite rare.  Maybe a few times a year.  So erroring it out on too many retries is all that is necessary (if even that).

**Comment by parg** [comment]
Probably too late now but when a piece check fails you should get a log to the console and (possibly) the peer that sent the corrupt data gets banned (see the IPFilter for this)

So in theory you should select different peers to download the failed piece from and eventually run out of peers if they are all deemed to be sending bad data.
