### ISSUE TITLE
Use ZeroNet Tor mode to download torrents with the Tor network

### ISSUE THREAD

**Issue by mx5kevin** [BiglySoftware/BiglyBT#2856]
ZeroNet using a Tor mode to connect peers together, download files. BiglyBt with Tor are can not connect together the users and download files. With I2P and Tor the downloads and seed will be much more faster. They solved the problem that this software does not work. Currently have a Tor plugin but the peers are not connected together and can not download and seed files like with the I2P network with anonymous mode.

https://zeronet.dev/ and https://zeronet.io/

* OS and version Windows 10
* BiglyBT Version Number 3.3.0.0
* For *nix: Desktop Environment

**Comment by parg** [comment]
Tor network doesn't want to be used for torrenting.

**Comment by mx5kevin** [comment]
> Tor network doesn't want to be used for torrenting.

However, it has been working for years and is much faster than I2P.  The Zeronet Tor setup system (what using a Torrent protocol) has been operating for years and an acceptable speed can be achieved with it.  I2P is terribly slow, and BiglyBt poorly optimized to seed the users clearnet torrent to the I2P network (pre installed I2P plugin default way). The problem they are has been solved for years, which BiglyBt cannot and have a working secured, fast, P2P Torrenting system what using the Tor network without any anonymity problems. What is needed en masse is anonymous torrenting (without paid VPN). With a similar system on Tribler it does not work. In terms of other functions, there are many other torrent clients that do the same or even better than BiglyBt. Compared to other torrent clients, this torrent client has no other advantages than the anonymous mode. Which loses its meaning if it cannot be used to download torrents from public sites (need to seed BiglyBt users to the I2P, and Tor network to work it).

**Comment by parg** [comment]
You used to be able to configure BiglyBT to run over Tor - you had to set up your local onion service and register it as a tracker-override I believe. Perhaps you can figure it out.

**Comment by mx5kevin** [comment]
> You used to be able to configure BiglyBT to run over Tor - you had to set up your local onion service and register it as a tracker-override I believe. Perhaps you can figure it out.

Zeronet with Tor always mode connect all users together without a central server or hidden central server like a normal torrent client.  BiglyBt in my tests with I2P mode  have maximum 200 MB/s download unstable speed. Zeronet with Tor Always mode was 800 MB/s stable speed. All BiglyBt users who download torrents can seed to I2P and Tor network for torrent for the anonymous users. Need to be integrated the Tor setup for future downloads and need a stable correct download/upload speed. And need to be allowed in the future for all BiglyBt user at installation to the Tor/I2P plugin and the mixed Public/anonymous download/seed default way to get seed in the anonymous networks default way. Right now the I2P mode are extremely slow, and does not have I2P seeders in public torrents. This is the developer fault that does not use these settings in the client default. Both problems can be fixed. The BiglyBt software would gain an advantage that the competitors do not have. Many users have indicated their need for such an anonymous system to various torrent client developers. The technology is already developed, working and open source. It should just be integrated. Without this feature, this torrent client is one of many.

**Comment by parg** [comment]
Why don't you write a detailed specification of how you would expect things to work? By this I mean exactly what would need to be configured in BiglyBT and what, if any, developments to BiglyBT would be needed. Not saying I'm going to do anything on this but at least I would understand what you're on about.

**Comment by mx5kevin** [comment]
> Why don't you write a detailed specification of how you would expect things to work? By this I mean exactly what would need to be configured in BiglyBT and what, if any, developments to BiglyBT would be needed. Not saying I'm going to do anything on this but at least I would understand what you're on about.


**-When BiglyBt installed I2P and Tor plugin all user install default way. During the installation, the plugin must be installed and checked default way.**

**-When a torrent downloaded use Public Anonymos mixed mode all BiglyBt users because from public to anonymous network the users not have seed without it.**

The first two options can be easily implemented by the developer. Basically, I don't understand why it doesn't work that way. Because the anonymous option is useless without it. The option is there in the client but by default it is set so that the client does not install it. Thus torrents downloaded in normal mode are not get seeded in the I2P network. This setup throws the work and the essence of the option into the trash. You have to wait for someone who are have installed BiglyBt downloaded from the public network and seeding the torrent. This does not work because the 2 plugin not installed by default on the installation (Check the installer).

**-The Tor plugin be done to make it to work work like the same way as the I2P plugin seed/dowload it Torrents with it (not just this hidden webseed mode with the Tor plugin from a central server).  This has been working on the Zeronet network for years without any hidden central server.**

A working anonymous torrent client is widely needed. Apart from this project, you can't find anything that works anywhere. It only works with a paid VPN everywhere or with another paid services (like seedboxes). I have described these problems in detail previously. Only the developer doesn't care about the user’s  feedback.
That's the goal I2P and Tor plugin install default way and seed/download the users public/anonyimous mix way default way. And with the Tor plugin make it work the download/seed connecting together users available (not just this hidden webseed mode for which there is no widespread demand).

**How i would expect things to work: When the torrent are added clear way ask the mode public/anonymos or just anonymous download and/or seed in the popup Open Torrent options window. Don't search and bother with unnecessary settings. This simple setting should not be made it to complicated for users. This can be simplified like this.**  And this is the option that is widely used by users. Se issue: https://github.com/BiglySoftware/BiglyBT/issues/2858 For this, the described basic settings must be optimized. The listed settings must be set as default for the user. It is too important an option not to be easily used by everyone. And it is a major function that makes people choose this torrent client widely, competitors don't know this, there is a wide demand for a function that allows torrents on the open net to be downloaded anonymously.

**Comment by parg** [comment]
My question was about how it works technically. I don't think I simply install the existing TorHelper plugin and everything magically works over Zeronet. There must be development work required, what would it be?

**Comment by parg** [comment]
Also https://github.com/HelloZeroNet/ZeroNet is dead

**Comment by mx5kevin** [comment]
> My question was about how it works technically. I don't think I simply install the existing TorHelper plugin and everything magically works over Zeronet. There must be development work required, what would it be?



> Also https://github.com/HelloZeroNet/ZeroNet is dead


https://zeronet.dev/ GitHub link: https://github.com/ZeroNetX/ZeroNet the working link (ZeronetX). He took over the development. The are using TCP protocol and trackers. The project are open source. All users with Tor always mode connect together download and seed in the network without a central server. Download and upload speeds are good. Using point to point encryption. The network has been working this way for a long time. Through Tor, the Torrent protocol works perfectly. Many people from censored countries such as China or Iran also use the network. All censorship bypass options used in the development of the Tor network are working. DHT could not be resolved, but everything else works perfectly with the torrenting  across the Tor network. That would be expected with BiglyBT Tor helper plugin too. There has been widespread demand for this option for a long time. Everyone can anonymously connect to each other and download from each other. Users who using Tor always mode and who are not without any problem they can download/seed from each other. It is not a fresh undeveloped solution with connection and other problems. People find each other quickly, the network are fast. It has been widely used and works for years. The network is a decentralized torrent-based network for decentralized torrent-based websites. With BiglyBt Tor helper plugin can not connect together the users decentralized way and download/seed from each other. This currently only working with the I2P plugin. This issues the ZeroNet developers are  all solved.

**Comment by parg** [comment]
So, no technical information then.

Looks like you are simply proposing to use Tor to download clearnet torrents using clearnet trackers, sending tracker+peer connections over Tor. 

Which the Tor project specifically don't want you to do. https://blog.torproject.org/bittorrent-over-tor-isnt-good-idea/

Unless you're saying that ZeroNet runs its own separate Tor network.

**Comment by mx5kevin** [comment]
> So, no technical information then.
> 
> Looks like you are simply proposing to use Tor to download clearnet torrents using clearnet trackers, sending tracker+peer connections over Tor.
> 
> Which the Tor project specifically don't want you to do. https://blog.torproject.org/bittorrent-over-tor-isnt-good-idea/
> 
> Unless you're saying that ZeroNet runs its own separate Tor network.

ZeroNet not runs its own separate Tor network.  The ZeroNet+Tor system is designed to work perfectly and made by professional developers. Tor project  don't recommends  the users to configure Torrent clients with Tor (what not designed to that and using UDP protocol, Tor using TCP). It does not work with Tor if the user to configure it a  torrent client. If it works, it works by bypassing the Tor network (it doesn't matter what kind of torrent client). No one said that this is not recommended when integrated into a system developed by professional developers. Bittorrent over Tor isn't a good idea blog I know and it does not apply to what I am talking about. In all these years, no one had a problem with ZeroNet+Tor combination. What they have solved must be integrated here. Otherwise, users cannot use the Tor system with the Torrent network in any way from any Torrent client. This ZeroNet+Tor system is designed to share larger files and decentralized websites with Tor (using TCP protocol not UDP). The project is open source a competent programmer can see how it works. You can also contact the developers for technical information. If this has been working on ZeroNet for years, why wouldn't it work here? I was talking about a long time working developed system, it can be tested. Apart from the Tor and I2P network, there is no other long time working anonymous network that can be integrated. Tribler tried his own (UDP) onion network which has not working for years. On BiglyBt with the I2P finding peers each other are slow, download and seed extremely slow, and with the Tor plugin can not download/and seed files the users. This would be a solution  Zeronet with Tor always mode the peers find each other fast way and have a good seed/download bandwidth.

**Comment by parg** [comment]
So does ZeroNet run its own trackers within the Tor network and have each peer define its own "Onion Service" for Tor-internal peer connections?

Or does it simply proxy clearnet tracker/peer connections over the Tor network?

Professional developers?
Competent programmers?

Not sure what you're trying to say there.

**Comment by mx5kevin** [comment]
> So does ZeroNet run its own trackers within the Tor network and have each peer define its own "Onion Service" for Tor-internal peer connections?
> 
> Or does it simply proxy clearnet tracker/peer connections over the Tor network?
> 
> Professional developers? Competent programmers?
> 
> Not sure what you're trying to say there.

They are special zero://onion adress.onion:port (onion) trackers. I'm not the developer. The program is open source using (Python language), if you review the code you will understand how it works. All traffic goes through the Tor network, including trackers in Tor always mode. Blocking the program with firewall and alowing only Tor the program works perfectly. Users with tor always mode and without Tor always mode are connect each other. With Tor always mode the users use the Tor network only, with normal mode both with Tor and normal P2P connection so everyone can connect with everyone. Without Tor always mode are possible the client are using normal clearnet trackers where the users directly connect each other and connecting the anonymous network too. I have been following the project for years, if there was a serious security problem, the users would have indicated it. Developers do not delete, close user comments either as someone who is not quite correct like in GitHub. They wouldn't even know because there are such decentralized forums on the network that the news of such things spreads quickly. If the developer of BiglyBt cannot understand how the program works, he cannot integrate it either. It is the developer's job to understand an open source programming language. If BiglyBt does not come from someone else's stolen work (Vuze etc), the developer can solve it.  Whoever developed the BiglyBt and Vuze systems has the expertise.  Download, test it, see currently how it’s work, the program using open source programming language, the developers are also helpful, I helped what I could, I did not recommend a crappy system which is not worth an integration.  Unnecessary questions because the BiglyBt developer will download the program, test it, interprets the source code, if necessary, talk to the developers. The ZeroNet team would also be happy to receive help, for example, in the integration of I2P.

**Comment by mx5kevin** [comment]
> So does ZeroNet run its own trackers within the Tor network and have each peer define its own "Onion Service" for Tor-internal peer connections?
> 
> Or does it simply proxy clearnet tracker/peer connections over the Tor network?
> 
> Professional developers? Competent programmers?
> 
> Not sure what you're trying to say there.

There are no separate central servers on the network. There is no difference between the original owner of the file and other users. The original owner of the files has a private key which he can use to edit or delete files. No central public or hidden server exists on the network like a centralized public or hidden webseed from a public or onion address from a web server. All users are using one ZeroNet link to access the files, and other content behind which there is no central server. It's like the magnet link for torrents. Users who have the content seed it to another users. Who seed it it is not possible to tell whether it was downloaded from the original file owner or by someone else. BiglyBt Tor plugin can connect only with a centralized hidden server where you can clearly only connect to the content owner and that makes the content owner much more vulnerable.

**Comment by parg** [comment]
Dude, I developed Azureus, Vuze and BiglyBT - stop going on as if I'm an idiot.

**Comment by parg** [comment]
Latest beta and I2P plugin works fine with .onion trackers and Tor peer-peer connections.

Try with

[BiglyBT3301-B19-tor.jar.torrent.zip](https://github.com/BiglySoftware/BiglyBT/files/11039056/BiglyBT3301-B19-tor.jar.torrent.zip)
