### ISSUE TITLE
Magnet links without seed failed to add the download list and remove Metadata download window when magnet added

### ISSUE THREAD

**Issue by mx5kevin** [BiglySoftware/BiglyBT#2857]
The client try to connect a user to get some info from the files. Metadata download. Without it not added the files to the download list. This way can not add magnet links to the client with zero seed. Automatic way add the magnet link to the download list like other torrent clients do it. This is a very unfriendly solution, and many people cannot use the client in this way.  The client throws an error message with zero seeded magnets. Add to the magnet to the download list without this metadata download window like other torrent clients. Like qBitorrent, Utorrent, or Bittorrent do it. And use only the open torrent window.

* OS and version Windows 10
* BiglyBT Version Number 3.3.0.0
* For *nix: Desktop Environment

**Comment by parg** [comment]
Just close the metatdata download window, it'll stay in your Library.
