### ISSUE TITLE
On Open torrent window missing the clear Privacy setting when a torrent added and default way  install Tor and I2P plugin

### ISSUE THREAD

**Issue by mx5kevin** [BiglySoftware/BiglyBT#2858]
On open torrent window have a Privacy button when a torrent or magnet link are added but no clear Privacy settings level like Public Only, Public/Anonymous mix (default), Anonymous, Invalid. The Privacy mode only stopped the torrent when added. And need to select the Privacy Tab, install the I2P and Tor Plugin and select them, Starting the stopped torrent which is all an unnecessary and complicated procedure. Anonymous When the program installed I2P and Tor plugin not selected. Please install it in the future in all BiglyBT client. Public/Anonymous mix (default) will be important to allow all BiglyBT client in anonymous only mode most torrent files are not available because not have Public/Anonymous seeds. This makes the client difficult to configure. When the torrent or magnet are added in the Open torrent window ask the user Privacy settings like Public Only, Public/Anonymous mix (default), Anonymous, Invalid clear way, do not stop the torrent, use a installed Tor and I2P plugin, allow Tor and I2P network. Instead of many complicated settings, this could be done with a single button press when adding the torrent file. This option are missing in the Open Torrent window when a user adding a torrent and comes after this window.

* OS and version Windows 10
* BiglyBT Version Number 3.3.0.0
* For *nix: Desktop Environment

**Comment by parg** [comment]
As with everything, people bitch when it doesn't work exactly how they want. Then they undertstand how it works and it isn't such a problem. I get very very tired of people coming here and telling me it should work exactly how they want it to.

**Comment by mx5kevin** [comment]
> As with everything, people bitch when it doesn't work exactly how they want. Then they under stand how it works and it isn't such a problem. I get very very tired of people coming here and telling me it should work exactly how they want it to.

The only advantage of the program the anonymous torrenting with I2P. To make this work with popular torrents all user must use BiglyBT with I2P plugin Public/Anonymous mix. There are very few of the Top torrents what working with I2P mode. Requires little effort to in the future the next versions install default way the I2P and Tor plugin. Currently, there is no similar working torrent client that supports anonymous torrenting and works. The option will not work if all users not install the Tor and I2P plugin default way and seed Public/Anonymous mix.

A minor problem is that it is too complicated to select when adding a torrent Anonymous mode with Tor and I2P when new torrent or magnet added.  Plugins must be installed, the torrent are stopped, in Sources tab I2P stopped, and the user sees that it does not work. It doesn't even offer the option when the user add the torrent. I2P users find each other slowly. The user thus does not know whether the function is working at all. See the similar torrent client Tribler interface when a new torrent added how easily the developers solved this. Anyone can set it up in a matter of seconds there. It can be solved with the push of a button when new torrent are added without complicated procedures. It is the most important part of the client that makes it stand out from other torrent clients.

It took me half a day to find out that the anonymous only with I2P option works at all or not. The setup requires too many unnecessary actions for the majority of users.
