### ISSUE TITLE
ipv6 support for UDP trackers

### ISSUE THREAD

**Issue by L2501** [BiglySoftware/BiglyBT#2859]
https://www.bittorrent.org/beps/bep_0015.html
IPv6 announces have the same structure as v4 ones, including the used action number except that the stride size of <IP address, TCP port> pairs in the response is 18 bytes instead of 6.

As far as I understand, the current code incorrectly interprets these 18 bytes as 3 pairs of <IPv4 address, TCP port>.

**Comment by parg** [comment]
That'd probably be because it was written before someone wrote that BEP.

**Comment by L2501** [comment]
Possibly change UDP annouces to be ipv4 only to prevent connection attempts to invalid peers?

**Comment by parg** [comment]
Next beta may have it working

**Comment by L2501** [comment]
:+1: there is also another ipv6 issue when a tracker has ipv6 but is refusing connections on it https://github.com/BiglySoftware/BiglyBT/issues/2788
