### ISSUE TITLE
Missing torrent comments for I2P torrents

### ISSUE THREAD

**Issue by Nampo** [BiglySoftware/BiglyBT#2860]
Torrent comments can be viewed with I2PSNARK, but they are absent in BiglyBT.
I suppose they should be shown in the 'General' tab of the torrent, which is always empty.

About - System:
Java 1.8.0_361 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_361

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B3.3.0.0/4 az3

**Comment by zzzi2p** [comment]
ref: 2017-03-30 http://zzz.i2p/topics/2156
"ut_comment sounds like a plan, might be possible to bridge Vuze's comments onto it and vice-versa. Not promising anything soon though :)"

**Comment by parg** [comment]
Torrent comments (set in the "comment" key under the torrent meta-data root) are displayed in the "Torrent Comment" field of the General tab.

User comments (locally entered) are shown under the "User Comment" field (above the torrent comment) and also in a Library column

ut_comment never made it into https://www.bittorrent.org/beps/bep_0000.html - no idea who supports it

BiglyBT/Vuze "ratings and comments" plugin stores ratings and comments in the DHT. Nobody else supports it

BiglyBT/Vuze "decentralised per-torrent chat channels" also replicate comments. Nobody else supports it.

**Comment by zzzi2p** [comment]
The 1-paragraph spec is linked at the top of the zzz.i2p thread above, but I don't blame you for not wanting to invest in something nonstandard. I'm in the same boat re: your DHT comments, as we discussed back in 2017.

**Comment by DumbJoe** [comment]
They don't show up on the web portal either....which is supposed to be the GUI for nix users....
