### ISSUE TITLE
Unselected files are still being downloaded

### ISSUE THREAD

**Issue by Aholicknight** [BiglySoftware/BiglyBT#2861]
* OS and version: Windows 11 
* BiglyBT Version Number: 3.2.0.0
* For *nix: Desktop Environment

![image](https://user-images.githubusercontent.com/7843719/216847019-c7fccb60-cdbd-4402-8183-cc8342e11c7b.png)
I selected 3 and 4 to not download. 

![image](https://user-images.githubusercontent.com/7843719/216847464-c5390c69-e08c-42f7-974c-7096d599adcd.png)
But the files are still being downloaded. How can I fix this? Thank you!

**Comment by Havokdan** [comment]
https://wiki.vuze.com/w/Selective_downloading

> The files marked with Delete will not be allocated to your hard disk, while those with DND will be allocated and created. (This may confuse you, as the file directory in Explorer/Finder will show you the full size of the DND file.) And even the "Delete" files will be allocated to the extent that their content is part of a piece, which will be downloaded due to other files.

The whole bittorrent logic is based on dividing the data files to even-sized pieces, typically 256 kB, 512kB, 1MB or 2 MB. And then the pieces are further divided into 16 kB blocks. Clients request/send the blocks, but maintain download correctness assessment (checksums) based on full pieces. If you look Files details tab of torrent's details, you will notice that for each file there is listed the number of first piece and the number of pieces.

As file lengths do not match piece boundaries, it is very typical that a piece will contain parts of several files (at least 2 files, but e.g. a 2 MB piece might easily contain 5-10 JPG images). Even if you mark some of those files DND or delete, but the piece contains contents of files you want, then the whole piece will be downloaded and written to disk. Thus you may end up with at least parts of files you did not want.

**Comment by Aholicknight** [comment]
I see. Thank you for helping me figuring this out.
