### ISSUE TITLE
Transcode Profile Not Found 

### ISSUE THREAD

**Issue by EthicalObligation** [BiglySoftware/BiglyBT#2863]
Java 19.0.2 (64 bit)
  N/A
/usr/lib/jvm/java-19-openjdk

SWT v4942r22, gtk/3.24.36, zoom=100, dpi=96
Linux v6.0.5-3-rt14-MANJARO, amd64 (64 bit)
B3.3.0.0/4 az3
![image](https://user-images.githubusercontent.com/92163467/217035809-969ca27f-c7b9-4f33-82f3-177c6c21c8aa.png)

**Comment by EthicalObligation** [comment]
I think it is not recognizing or finding the transcode profiles.
relevant log from transcoder: 

TPP: 0 profiles for generic (Media Analyser)

**Comment by parg** [comment]
Indeed, I'll fix that

**Comment by EthicalObligation** [comment]
Checking it out now.

**Comment by EthicalObligation** [comment]
Working now! Thank you!
