### ISSUE TITLE
(Redundant) .torrent file in auto-import dir is causing BiglyBT to endlessly re-tag existing torrent

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#2864]
Sooo, this is kind of a weird one. (Yes, _again_!) And it feels like something that's changed recently (meaning, within the past _year_ — it's not a situation I'd have run into often). I'm sure I would have noticed before now, if it was _always_ like this.

#### The setup

I have a set of subdirectories in my Dropbox space that I've configured as auto-import locations (under **Options→Files→Torrents: Import new .torrents/.magnets automatically**). Each one shares its name with a different categorization tag, and is configured to "Assign to Tag" that tag.

(I do that so that I can download `.torrent` files locally on my desktop machine, toss them into Dropbox, and they'll get synced over to my server for BiglyBT to pick up automatically. Less than a minute after I download the file one one machine, it's loaded into BiglyBT on a completely different one, tagged and ready to go without any manual intervention from me. BiglyBT auto-deletes the `.torrent` file after import, and Dropbox syncs the deletion back to my desktop so even the cleanup is fully automated.)

Occasionally I do accidentally download the same `.torrent` file _twice_ into one of those directories. When that happens, the second one will sit there indefinitely. BiglyBT will refuse to import a torrent that's already in its library, and when the import doesn't happen, it also doesn't delete the file. Still no problems so far...

#### The weirdness

What I just discovered a few minutes ago, tho, is that I **can't** manually remove that categorization tag from one of my torrents!

Normally that works fine: I right-click, go to Tags > $THETAG, uncheck it, and done. 

But with _this_ torrent, every time I remove the tag, within 30 seconds (the poll time I have set for the import dirs), it gets reapplied and the torrent is right back on the filtered list for that tag. Apparently, because there happens to be a duplicate `.torrent` file sitting in the import directory, BiglyBT is updating the tags on the _existing_ library torrent each time it tries (and then refuses) to do the import!

I'm sure that deleting the `.torrent` file will "fix" things and stop BiglyBT reapplying the tag to the live torrent. But it seems kind of weird that, if BiglyBT **isn't** importing a file because it's a duplicate of an existing torrent, it would still run the assign-to-tag part of the process each time it polls... no?

### System block

Java 11.0.17 (64 bit)
  Red Hat, Inc.
/usr/lib/jvm/java-11-openjdk-11.0.17.0.8-1.fc37.x86_64

SWT v4956r12, gtk/3.24.36, zoom=100, dpi=96
Linux v6.1.8-200.fc37.x86_64, amd64 (64 bit)
B3.3.0.1_B02/4 az3

**Comment by ferdnyc** [comment]
Theory confirmed: as soon as I removed the redundant `.torrent` file from the import dir, the tag-removal "stuck" on the live torrent.

**Comment by parg** [comment]
Seems that's how it works. 

As it is all non-atomic the code assumes that if there's a .torrent file there with a corresponding download but without the tag then something crashed during the import process and it reapplies the tag and renames the .torrent file. However, it won't move it if the ".imported" file already exists (guess it doesn't want to risk deleting something) hence the behaviour.

Guess I could smarten that up a bit.

**Comment by parg** [comment]
Having said that it also requires you to have

1) you have "Options->Files->Torrents: Save .torrent files" set to false
2) you have "Options->Files->Torrents: Always rename imported torrents (".imported" suffix added)" set to false

Is this right?

**Comment by ferdnyc** [comment]
Just putting the 'does this file already exist in the torrent directory?" _check_ ahead of the tagging would probably do it, right? I mean, if the torrent was not only imported, but the source `.torrent` file was moved into the runtime dir, that's pretty good evidence the import process went just fine. (Or if it didn't, a missed tag seems like a small price to pay — heck, it's probably better that it be missing, and call attention to the problem.)

> Is this right?

Good question. Hm...

Nope, 'Save .torrent files' is checked. With the save directory set to `$HOME/.biglybt/torrents`. The two suboptions are unchecked.

'Always rename...' is false, though.

**Comment by ferdnyc** [comment]
'Delete original .torrent files...' is also unchecked, amusingly for my appreciation of the so-called "auto-cleanup" feature. I guess relocation from an import directory doesn't count as deletion.

**Comment by ferdnyc** [comment]
Were the more recent betas supposed to have changed anything about how this works? Because, I just thought to re-test today, and nothing has changed. Torrent re-import is still attempted, manually-removed tag is still re-applied, (redundant) torrent file is still left in import dir.

I'm only asking because ISTR one of the recent changelog entries mentioning something about import. If there aren't any expected changes, then I'm just confused and shouldn't be looking for them.
