### ISSUE TITLE
add/new torrent prompt layout gets reset by donation prompt

### ISSUE THREAD

**Issue by SUCM** [BiglySoftware/BiglyBT#2866]
this has been there for quite some time (years?)

sometimes, when you add a new torrent, Bigly's donation prompt would show up. you need to close the donation prompt to see the add/new torrent prompt. however, the torrent prompt layout after the donation prompt always get reset where pretty much all elements are collapsed

**Comment by parg** [comment]
weird one, think I fixed it

**Comment by ChrisWLeon** [comment]
I also have this problem

**Comment by parg** [comment]
And is it fixed in the latest beta?

**Comment by shapeshifter910** [comment]
I get the donation prompts every time I'm adding a torrent. Very annoying and as a result I will never donate.

**Comment by parg** [comment]
Hit the "close" link top right, don't close the dialog by closing the window. You wouldn't donate anyway, don't make empty threats.
