### ISSUE TITLE
Low upload speed limit.

### ISSUE THREAD

**Issue by Achaean** [BiglySoftware/BiglyBT#2870]
Java 11.0.18 (64 bit)
  Debian
/usr/lib/jvm/java-11-openjdk-amd64

SWT v4956r12, gtk/3.24.5, zoom=100, dpi=96
Linux v4.19.0-23-amd64, amd64 (64 bit)
B3.3.0.0/4 az3

I'm running it on KDE.

**Hi!**  :-)
My upload-seed speed limit, is at 60kbps.
I expected to be somewhere at 110kbps.

I  set at options to be unlimited, though it's still at 60.
Am I missing something???  :-)

![Screenshot_1_options](https://user-images.githubusercontent.com/3608053/218312089-fbf57017-dc19-472a-8a6d-5eeb43e4dc4c.png)
![Screenshot_2_limits](https://user-images.githubusercontent.com/3608053/218312095-59b89c7a-cd87-4624-9809-cbc1c3dc1154.png)

**Comment by parg** [comment]
You seem to have manually set your upload speed limit to 61K/sec - turn that off by via

Options->Transfer: KB/s global max upload speed [0: unlimited]

for example.

**Comment by Achaean** [comment]
**THANKS!!!**  :-)
That did the trick!

I don't know what changed this value.
It probably is, the M-LAB plugin.
I have it uninstalled, but once I changed the above value -> 0, it started running again, so I canceled it.

Somehow, it always was problematic for me and seems to still is, even if it looks uninstalled.
