### ISSUE TITLE
BiglyBt now pops to the top (again!) when a magnet torrent is received and the torrent dialog is opened

### ISSUE THREAD

**Issue by david-bakin** [BiglySoftware/BiglyBT#2871]
[BiglyBT Beta 3.3.0.1_B05; Windows 2016 Datacenter (I've really gotta upgrade this whole machine one of these days, huh?)]

Sometimes - not every time - but sometime:  When a torrent file finally gets read (after having been given a magnet hash) and the torrent dialog pops up the entire BiglyBt window pops to the top/front.  And then, whatever you were typing in some other window where you were doing work gets sent to the dialog window.  And if you hit enter the torrent is accepted.  If you hit escape the torrent is gone.

This is really annoying, as it may take minutes/hours/even days for that magnet to complete and it just pops up and is either dismissed or added with possibly incorrect properties (e.g., files selected which you wanted to unselect).

This started happening again quite recently.  I _think_ but I'm not sure that I didn't notice it until the 3.3.0.1 series of releases.  It _used_ to happen quite awhile ago (a few years).  (In fact I could have sworn I reported it and you fixed it but I can't find it in the issues (closed or open). But I may have just missed it.)

I have _not_ seen it happening when you drag an actual torrent file to the biglybt main window which is _not_ on top and which is partially obscured by other windows.  In that case the torrent dialog pops up _behind_ the obscuring windows (which is fine, though one might think in _that_ case, a deliberate user action, it _would_ pop up.  Whatever. That behavior is fine.)

Anyway, BiglyBt shouldn't pop to the top and interrupt your other work.

**Comment by david-bakin** [comment]
This behavior went away for some time.  But now it's back (for several weeks).

**Comment by parg** [comment]
Question is, what changed several weeks ago to cause it to start happening again? Don't think it is anything BiglyBT related...
