### ISSUE TITLE
Speed limits pause integrity check

### ISSUE THREAD

**Issue by Snake883** [BiglySoftware/BiglyBT#2874]
Integrity check on a torrent gets paused when the network limit is reached.

Linux
Java 11.0.16.1 (64 bit)
  Flathub
/app/jre

SWT v4942r22, gtk/3.24.36, zoom=100, dpi=96
Linux v6.1.11-arch1-1, amd64 (64 bit)
B3.3.0.0/4 az3

**Comment by parg** [comment]
Should be fixed in B07
