### ISSUE TITLE
Forced Downloads do not work with Speed Limits

### ISSUE THREAD

**Issue by Snake883** [BiglySoftware/BiglyBT#2875]
Downloads are not forced to download when speed limit threshold has been reached.

**Comment by parg** [comment]
Can you explain what you mean in more detail please?

**Comment by Snake883** [comment]
For example...
I have a speed limit threshold of "net_limit daily total=5G".
But I want "forced downloads" to ignore the limit, and be forced into downloading, even if that means downloading more than 5 gigabytes for the day.

Perhaps the option to not apply speed limit threshold rules to forced downloads (just in case a user doesn't want to bypass the limit).

**Comment by parg** [comment]
I added a "pause_force_downloads=no" option to the config for the next beta, B08. 

Not tested, I'll leave that to you!
