### ISSUE TITLE
Tag's Max Down Speed gets reset

### ISSUE THREAD

**Issue by Zenya393** [BiglySoftware/BiglyBT#2876]
I set "Max Down Speed" for a Tag, but those limits get reset to unlimited.
I suspect it has something to do with speed limit profiles or speed limit scheduler.

BiglyBT B3.3.0.0

**Comment by parg** [comment]
Probably... is the Tag mentioned in any of the speed limit scheduler config?

**Comment by Zenya393** [comment]
Speed limits and profiles is a bit confusing for me...so I'll try to explain what I think might be happening, and then the way I wish it would work.

I think when I update a tag's speed limit, it must not be getting saved in the speed limit profile.  Then the speed limit profile is reloaded, with the previous speed limit (unlimited), and my setting gets erased.

The reloading of the profile happens very quickly.  Too quick, because its a race to to save the profile before it gets reloaded, and then I end up saving the profile with the reloaded/previous settings, and never win or save the new settings.

I have a tag "S0".  I manually set the download limit to 1 kB/s:

![Issue1](https://user-images.githubusercontent.com/125422293/221427382-931230aa-1184-4a80-b369-6353d60dcafd.png)

After a few seconds, S0 is now unlimited:

![Issue2](https://user-images.githubusercontent.com/125422293/221427385-2933b830-f590-40b2-991f-1328cd0c892c.png)

Suggestions:
1)  Changes should be saved immediately, or at least shouldn't be reset/overwritten after 1 second, which makes any changes not possible.  Maybe 1 second is too soon.  Maybe allowing edits shouldn't be allowed if a profile is active (because edits just get overwritten within 1 second, unless you are fast enough to save it within that time).
2)  I would like to manually edit the speed limits, scheduler, profile via file.
3)  Schedules, settings, limits, profiles is still confusing.  Perhaps because it's in multiple places, precedence can be a issue.  Maybe all the settings in an editable file.

The speed limits and bandwidth is a fantastic feature, and one of the primary reasons I choose BiglyBT to manage my limits from my ISP....thank you!

**Comment by parg** [comment]
If you have speed limit schedule settings that control a Tag's rate limits then BiglyBT will try and ensure that the up/down limits are "as expected" - you shouldn't manually try and change them as they'll get reset.

If you want to manually decrease a limit then you could create another Tag, say S0M, with a constraint of "hasTag( "S0" )". You can then apply lower rate limits to that. Obviously this doesn't work the other way as higher limits  don't override lower ones.
