### ISSUE TITLE
Speed Limit Profile Rules pause torrents being rechecked.

### ISSUE THREAD

**Issue by Zenya393** [BiglySoftware/BiglyBT#2878]
Speed Limit Profile Rules pause torrents that are being rechecked.

1. Setup a speed limit rule (SLR) that will pause all torrents when limit is reached.
2. Start a torrent integrity recheck.
3. When SLR threshold is reached, the torrent that was performing the integrity recheck will "pause", and not continue the recheck.
4. When SLR is reset and torrents resume, the recheck does not resume.  Basically, the recheck never completes, and if you weren't watching, you would assume the recheck did complete.

* BiglyBT 3.3.0.0

**Comment by parg** [comment]
Should be fixed in B07
