### ISSUE TITLE
Please enable HTTPS connection to version.biglybt.com

### ISSUE THREAD

**Issue by vyings** [BiglySoftware/BiglyBT#2879]
Privacy concerns aside, I'm afraid of ISPs stealthily modifying the update torrents someday. And it seems the torrents are not signed and verified by BiglyBT.

For now I have blocked connection to version.biglybt.com and checkip.dyndns.org but it keeps retrying once per miniute, not so great.

BTW is there an option to stop the beta version from reporting to version.biglybt.com even after I disable auto update notification?

**Comment by parg** [comment]
Update torrents are signed and verified

**Comment by parg** [comment]
To enable HTTPS we would have to add a AWS load balancer, a cost we can't afford at the moment.
