### ISSUE TITLE
Sequential download is not working sometimes. No dependence when it happens found

### ISSUE THREAD

**Issue by de-served** [BiglySoftware/BiglyBT#2881]
B3.3.0.0/4 az3
Java 19.0.2 (64 bit) Eclipse Adoptium

Settings > Files > Auto sequential download file extensions: .mp4;.mkv;.avi;.mp3;.flac;.m4a
mp4/mkv/avi downloaded as suggested - sequentially
but mp3/flac - not.
Sender's torrent clients - different, not recorded, but I've seen different clients there.

PS: only 1 torrent with .flac's of 35 torrents with .mp3's/.flac's are automatically prioritized - pieces priority is >110000; all others are 0.

**Comment by desirepl** [comment]
It happens on any file/extension, even on videos.
It's just a matter of number of files as I understand now.
No any visible dependence when it's happening. Different senders clients, different torrent files - it happens at some torrents, but at others - don't.
Even ticking "Sequential download" at torrent properties with RMB options didn't help.
