### ISSUE TITLE
Last version 3.3.0 requires 10.12 does not open in 10.11. Legacy flavor if it works

### ISSUE THREAD

**Issue by MacTerrassa** [BiglySoftware/BiglyBT#2882]
* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment
According to the download page if you use system 10.11 you have to download the current version, either in the universal form or for intel as I understand it, but both versions come in the form of an installer application that requires system 10.12, including an icon with the symbol of prohibited and that when double-clicked, the finder warns of its new requirements.
If I try the legacy version, supposedly for 10.7 or later systems, it installs without any warning and the program opens anyway.
The data on the download page should change. It is not a big problem because they still offer a working version, but they should indicate it or perhaps an intermediate version could be created for that system, more current than the one installed with the legacy version, but that still works without requiring system 10.12. If possible, of course. But at least the correct version to install should be indicated on the download page.
Regards
MacTerrassa

P.S. Message translated mechanically as I do not speak English, I apologize if I have not expressed myself correctly.

**Comment by TuxPaper** [comment]
Thanks for the report!

I've updated the text to say 10.12, and to choose the Legacy installer when it detects your OS is under 10.12..
