### ISSUE TITLE
LegacyOSX.dmg is damaged and can’t be opened

### ISSUE THREAD

**Issue by jefft666** [BiglySoftware/BiglyBT#2883]
The BiglyBT GitHub_BiglyBT_Installer_LegacyOSX.dmg installer for Release v3.3.0.0 is failing to run (on multiple Mac OS's) with the following error:

“GitHub_BiglyBT_Installer_LegacyOSX.dmg” is damaged and can’t be opened. You should move it to the Trash."

Have recreated the issue with both the DMG on GitHub and the one on BiglyBT.com and have tried on both Mac OS Monterey 12.6.3 (21G419) and Mac OS El Capitan 10.11.6 (15G22010).

**Comment by jefft666** [comment]
Should have also mentioned that the automatic in app update is downloading a version of the updater that won't run on Mac OS El Capitan. Running the "" contained within the downloaded zip file results in the following error message:

> You can't use this version of the application "BiglyBT Update" with this version of OS X.
> You have OS X 10.11.6. The application requires OS X 10.12 or later.

**Comment by TuxPaper** [comment]
We've changed the in-client update for OSX 10.11 to use a jar update, which bypasses the problem.  Thanks for reporting it.

As for the legacy installers, I'm not sure if there's much we can do.  You can follow the steps at https://www.howtogeek.com/803598/app-is-damaged-and-cant-be-opened/ , specifically:

<code>xattr -d com.apple.quarantine /path/to/GitHub_BiglyBT_Installer_LegacyOSX.dmg</code>

which will remove it from Apple's quarantine, and allow for installation.

However, that's not very practical for normal users.  Fortunately, Apple loves to force people to their newer OS versions, where our new non-legacy installers work without any security issues.

**Comment by jefft666** [comment]
Cool! Thanks for the update.

jeff
