### ISSUE TITLE
Duplicate magnets, one with error added

### ISSUE THREAD

**Issue by eurobank** [BiglySoftware/BiglyBT#2885]
Windows 11Pro/64.

Latest biglybt version, tried latest beta also.

When adding a magnet, sometimes TWO instances are shown, both with same number (# 1 in the capture), the second with error:

Error: File 'Z:\Downloads\BiglyBT\xxxxx is in use by 'xxxxxxxxxxxxxx [write],xxxxxxxxxx [read]' (allocateFiles existing:Z:\Downloads\BiglyBT\xxxxxxx.txt)

Any ideas ?

![2023-02-20 16_01_36-BiglyBT](https://user-images.githubusercontent.com/4467158/220129411-2d9017a4-74d4-466b-b378-d9256d5f629a.png)

And it gets better. When i delete within biglybt the second in error magnet, biglybt starts to auto showdown because of finished downloads (wrong).

**Comment by parg** [comment]
How are you adding these magnets? Do you go through the "torrent options" dialog? What happens if you just leave the error one sitting there?

**Comment by parg** [comment]
Also check the DiskOps_1/2.log files, maybe upload relevant bits here?

**Comment by eurobank** [comment]
> How are you adding these magnets? Do you go through the "torrent options" dialog? What happens if you just leave the error one sitting there?

As i always do, from a magnet link of a site.

**Comment by eurobank** [comment]
> How are you adding these magnets? Do you go through the "torrent options" dialog? What happens if you just leave the error one sitting there?

I don't know what happens, i delete the one in error. But after i delete it, the correct is also gone.
