### ISSUE TITLE
Biglybt doesn't count ratio well on a private tracker.

### ISSUE THREAD

**Issue by libellula** [BiglySoftware/BiglyBT#2886]
Hi.
A couple of times I've used biglybt for a private tracker like rutracker it removed a disproportional amount of ratio from my account. I hope it can be fixed because that's pretty much the only thing keeping me from switching to biglybt completely.
Thanks.

* Windows 11 22h2
* BiglyBT 3.2

**Comment by parg** [comment]
Turn on tracker logging (All Tracker's view, right-click on the private tracker entry and and enable logging).

There are no known issues with the way BiglyBT reports upload/download to tracker.

**Comment by libellula** [comment]
Ok it seems qbittorrent is doing pretty much the same, maybe there's just something I did wrong or it's down to some rules in the site. Thanks btw, @parg .
