### ISSUE TITLE
all trackers display dates cosmetic issue

### ISSUE THREAD

**Issue by JBitte** [BiglySoftware/BiglyBT#2888]
seeing this today in latest beta, all trackers view,

50-Feb-2023 date field

![bt-trackers-dates-issue](https://user-images.githubusercontent.com/6049555/220335625-ee9cf300-1bcb-4b0c-bb31-b76781d3f593.png)

+++++++++++++

Java 1.8.0_361 (64 bit)
Oracle Corporation
C:\Program Files\Java\jre1.8.0_361

SWT v4942r22, win32, zoom=100, dpi=120
Windows 11 v10.0, amd64 (64 bit)
B3.3.0.1_B05/4 az3

**Comment by parg** [comment]
Set some kind of weird date format? Right-click on the column header

**Comment by JBitte** [comment]
yes, it seems format was unhappy

![bt-trackers-dates-issue2](https://user-images.githubusercontent.com/6049555/220534855-3337462b-d55b-4cff-bba8-c4d69c30d8d4.png)

**Comment by parg** [comment]
There's a link in https://github.com/BiglySoftware/BiglyBT/wiki/User-Interface#date-and-time-formats that explains how to format things.

DD is "day in year"
