### ISSUE TITLE
Betas via Flatpak

### ISSUE THREAD

**Issue by Zenya393** [BiglySoftware/BiglyBT#2891]
Is it possible to use/test betas via Linux Flatpak's?

https://github.com/flathub/com.biglybt.BiglyBT/

I can't run beta's or test anything because of the SWT problem.

**Comment by ghazyami** [comment]
Currently, the main flatpak is build by pulling the binary from BiglyBT's release page. I can not see the beta binaries there.
So if those are published somewhere else, then we can use them. Otherwise, it has to be built from source.

**Comment by parg** [comment]
Beta jars are available as AWS S3 objects, for example the latest beta is

https://biglybt-files.s3.amazonaws.com/core/BiglyBT3301-B19-signed.jar

The latest beta can be figured out by hitting the version server with

http://version.biglybt.com/?d9:beta_prog4:truee

The result is "bencoded" in the same way that .torrent files are.

Not great but there you go!
