### ISSUE TITLE
create filter

### ISSUE THREAD

**Issue by johnvolfovits** [BiglySoftware/BiglyBT#2892]
* OS and version win11
* BiglyBT Version Number v3.3

how could i create my own filter in subscription 
![asd](https://user-images.githubusercontent.com/107244103/220873072-033264ff-d905-47ae-bfed-f489703e2962.png)
adding some filter of my own to filter bar

**Comment by parg** [comment]
Normally there is a "save" button in the filter area that allows you to make filters persistent. Not sure why it is missing for you - did you create that subscription with an earlier version of BiglyBT? It looks as if it has come from a "find more like this" operation - recent versions don't include the prefix "More: " in the title.

**Comment by johnvolfovits** [comment]
No i don't.
is there any solution for that?

**Comment by parg** [comment]
What are you trying to achieve?

**Comment by johnvolfovits** [comment]
to make my own filter by parameter of my own that I used repeatedly for not typing it everytime

**Comment by parg** [comment]
How are you creating the subscription? If you have an RSS feed URL then click on the "+" sign next to the subscriptions header in the sidebar, select the "create new subscription" button, select the RSS tab and enter the URL and name it. You can then add your own filters and save them.

**Comment by johnvolfovits** [comment]
very helpful
thanks
