### ISSUE TITLE
avoid full disk allocated

### ISSUE THREAD

**Issue by icesof** [BiglySoftware/BiglyBT#2894]
* OS and version: windows 10 22H2
* BiglyBT Version Number: 3.3
* For *nix: Desktop Environment

During downloading, BiglyBT will take all the free disk space if possible. Could some of the disk be reserved by parameter?

**Comment by parg** [comment]
Try beta B09 - https://github.com/BiglySoftware/BiglyBT/wiki/Speed-Limit-Scheduler#storage

**Comment by DumbJoe** [comment]
Might be relevant question: So I presume the latest version now allocates blank data(which slowly turns into actual data as you download the parts) to make up the size of the torrent so that you're not surprised by lack of space when you look for more torrents to download?
