### ISSUE TITLE
Make a distinction between 'active' torrents and 'running' torrents

### ISSUE THREAD

**Issue by Xemnarth** [BiglySoftware/BiglyBT#2898]
For example in:
![image](https://user-images.githubusercontent.com/6406869/222063626-ed97117c-dbd3-4e83-af01-2b6792304c39.png)

Running/started items in any tag are not necessarily 'active' and listed under the 'Active' entry .

**Comment by Xemnarth** [comment]
simply put, the word 'active' in tag windows should be renamed to 'started' to be more accurate and since we already have an entry for actually active items :)

**Comment by parg** [comment]
I could change that but then we'd lose all the translations of it and it is an "in your face" piece of text

**Comment by Xemnarth** [comment]
Then maybe just edit the one in the English repository to reflect this
minor change? Thanks for all your work on this!

**Comment by parg** [comment]
That's not how it works... With the CrowdIn translation system we use if you modify the core (i.e. English) translation for an item then it automatically invalidates all of the translations of it...

Anyway, I've managed to bodge it by using other translated texts :)
