### ISSUE TITLE
Add Tag Constraint for Remaining Size

### ISSUE THREAD

**Issue by Zenya393** [BiglySoftware/BiglyBT#2899]
Requesting a tag constraint for remaining size (e.g. size_remaining_gb).
Or the ability to perform math:  size_gb - downloaded_gb

**Comment by parg** [comment]
I'll add a "remaining" entry. Don't really want to do what I did before with the _mb _gb variants - do you really need gb resolution?

**Comment by Zenya393** [comment]
> I'll add a "remaining" entry. Don't really want to do what I did before with the _mb _gb variants - do you really need gb resolution?

I can workaround it.  However there's a precedence, "size" is defined as:
`size, size_mb, size_gb: numeric - size of torrent file in bytes/MiB/GiB (binary - use suffixes for more control)`

**Comment by parg** [comment]
I'll add toMB and toGB functions then so you can write toGB( remaining )
