### ISSUE TITLE
Feature Request: Path from combined "Files" list (in Tags Overview) to source torrent

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#2904]
I frequently use the Tags Overview's Files tabs to explore a combined view of all the files for torrents associated with a given tag. It's a handy way to track down a file when you know it's (probably) in _some_ torrent, but you're not sure which one.

Problem is, while I can find a _file_ that way (and even set it to download, if it isn't, or open it, or find its location on disk), there's no easy way to get back to the **torrent** it comes from.

So, for that particular view, since it's not a sub-tab of a particular, single torrent and the files listed come from _many_ different torrents, it'd be nice to have a context menu entry to access the torrent that owns a given file, in one of the following ways (I'm not picky):

1. Switch to the Library view and select the torrent in the list
2. Switch to the Torrents tab (still in the Tags Overview, right next to thE Files tab) and select the torrent
3. Open the torrent's Details view

**Comment by parg** [comment]
There actually is a "Show Download" right-click menu item there. It does select the download in the Library but it doesn't switch to that view...

**Comment by parg** [comment]
I've implemented (2)

**Comment by ferdnyc** [comment]
> There actually is a "Show Download" right-click menu item there.

Was that always there? It's so low on the list I don't think I even spotted it. Or, maybe I tried it and it appeared to do nothing, so...

> I've implemented (2)

Makes me happy, thanks! Closing.
