### ISSUE TITLE
Unable to connect to Desktop Remote

### ISSUE THREAD

**Issue by EthicalObligation** [BiglySoftware/BiglyBT#2906]
* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment

Java 17.0.6 (64 bit)
  N/A
/usr/lib/jvm/java-17-openjdk

SWT v4942r22, gtk/3.24.36, zoom=100, dpi=96
Linux v6.1.12-1-MANJARO, amd64 (64 bit)
B3.3.0.0/4 az3

**Comment by EthicalObligation** [comment]
![image](https://user-images.githubusercontent.com/92163467/223128880-8b71fbfe-b279-4c82-a511-18cf494de3f0.png)
Even though reachable from remote.biglybt.com. The Android client hangs like the above.

**Comment by EthicalObligation** [comment]
Will check it out again

**Comment by Igiko** [comment]
i got that problem too it just hangs, funny enough if i only have it on wifi it says no internet even know there is?
