### ISSUE TITLE
win64, install - extra items can not be downloaded

### ISSUE THREAD

**Issue by the-Arioch** [BiglySoftware/BiglyBT#2911]
Just downloaded the installer from your site and...

![Bigly-xm)](https://user-images.githubusercontent.com/937774/224743715-f85cb416-bd04-4c06-b001-e8c17363b071.png)

Frankly, i think you'd better revert to Vuze/Azuerus mode of plugins install: first install the core, then us it to donload okugins via p2p (including http source, but noit having it as the only source / single poitn of failure)

**Comment by parg** [comment]
You can do it the "old way", just don't select plugins to be installed by the installer

**Comment by the-Arioch** [comment]
Sure. I  juest mean that the official installer should not confuze novices from get go.

And i understand that snall team can not always keep all their servers 24/7 - that is exactly why i think proper long-term fix would be not "fix your server" but remaking the installation flow into non-blocking one.
