### ISSUE TITLE
Tracker/Torrent > Update Tracker query

### ISSUE THREAD

**Issue by MarathonZephead** [BiglySoftware/BiglyBT#2912]
Hi

I'm curious to know what the Update Tracker function actually does.

When I have used it, it updates the number of seeders and leechers, but does it actually find new connections and refresh existing ones as well?

I have uploaded torrents where the upload rate has dropped significantly and I don't know if it's a coincidence or not that when I Update Tracker the upload speed sometimes increases.  If that's what Upload Tracker does, then why do I need to do that manually to achieve that? Is there a setting(s) that will permanently give me the optimum upload speed instead of having to check on it every so often? I have not set a manual max upload speed on any individual torrents or overall speed.

Many thanks!

**Comment by parg** [comment]
"Update Tracker" will add any new peers that the tracker responds with.

In general a tracker tells a client how frequently it wants to be updated, BiglyBT respects this. Manually updating may exceed the tracker's refresh frequency so care should be taken.

If it is a public tracker then new peers can be found via peer exchange and the DHT anyway. However, for private trackers the only way to discover new peers is from the tracker itself so it may be the case that a manual update will find new peers.
