### ISSUE TITLE
Peers bypassing limits

### ISSUE THREAD

**Issue by Zenya393** [BiglySoftware/BiglyBT#2918]
In this screenshot you can see a peer bypassing upload limits:
![BiglyBT bug 1](https://user-images.githubusercontent.com/125422293/227748994-f908bd2a-7710-400c-898a-a15e8eae7cdf.png)

Observations:
The peer is getting "LAN" privileges.
I suspect this may have happened because I previously "boosted" this peer.  When boosting, the peer bypasses all WAN network limits.  I then removed "boost", but the LAN privileges remained (evidence in above screenshot).

I haven't been able to reproduce the problem by clicking on the "boost" check mark, but I do have the screenshot to prove that at some point there's no boost check mark, yet there is LAN status.

I also think it is misleading that "boost" turns the peer into a LAN peer (see screenshot).  I'm not sure if "boosting" changes bandwidth  priority, or simply bypasses all WAN limits (I have no LAN limits).

B3.3.0.1_B20/4 az3

**Comment by parg** [comment]
It isn't misleading, that is how it is designed. Don't boost stuff if you don't like it.

**Comment by Zenya393** [comment]
Boost isn't enabled (there is no check mark in screenshot).

Why does LAN have an asterisk (*)?  That peer and I are not on the same LAN, ISP, or country.  <--- So identifying the peer is on my LAN is not true and misleading.

But again, the main part:  Why is the peer identified as LAN, when the peer is not boosted?

**Comment by parg** [comment]
LAN can be defined as anything - Options->Plugins->LAN Peer Finder: Local networks

When a peer is boosted its IP address (not ip:port) is added to the set of addresses considered to be "LAN Local"

Any peer from that IP will be included, maybe that's the reason, I don't know.

**Comment by Zenya393** [comment]
"Boosted" IP Addresses are not listed in LAN:
![BT LAN](https://user-images.githubusercontent.com/125422293/227977780-c7130f4f-ffe0-4056-80e1-e878487350e9.png)

I don't know where to go so I can see all the peers/torrents that I have "boosted".  Is there a screen?  Is there a tag?  Or is there a feature so I can create my own "boosted" tags?

I've been manually "boosting" peers because downloads seem to get stuck/snubbed, and by "boosting", the peers will start downloading.  Even when the torrent is "forced", the peers still are stuck.  Also, the peers in the screenshot are grayed (which
![BT Snubbed](https://user-images.githubusercontent.com/125422293/227978058-9d25c351-1095-4488-9b4e-bce1e441ce01.png)

If clicking the boost box is categorizing remote/WAN peers to my LAN, then it would be more intuitive to call it "LAN" instead of "Boost".

**Comment by parg** [comment]
View->Friends
