### ISSUE TITLE
Disk write error: flush fails, write fails, Invalid argument

### ISSUE THREAD

**Issue by azatsh** [BiglySoftware/BiglyBT#2919]
I'm downloading a film with size 16 Gb. Initially it didn't want to start but then I enabled an option "Append data to files as downloaded and reorder" which solved the issue. 
But after downloading 23% of the file it gives now different issue:
"Disk write error: flush fails, write fails, Invalid argument"

I tried to restart and force start but get the same.
The usb flash stick has more enough memory (100 Gb) so I don't know what to do.

Any thoughts ?

OS and version:
Core version 4.9.125
Build BRAVIA_ATV2_EU-user 9 PTT1.190515.001.S52 672101

BiglyBT Version: 1.3.2.0

**Comment by parg** [comment]
Hard to say what's going on - how is the USB drive formatted? FAT32 only goes up to 4GB

**Comment by mckmeper** [comment]
I am receiving the same messages on my iMac with a 2T external SSD. The downloads complete 98% and stop with the "Disk write error" message in red. BiglyBT B3.3.0.1_B22/4 az3, Macos 13.3. Approximately 15 downloads have ended this way in the past two days.
![Screenshot 2023-03-28 at 3 11 41 PM](https://user-images.githubusercontent.com/9400338/228378188-233c3c71-3f4e-437f-835a-8e3d1ecdf740.jpg)

**Comment by azatsh** [comment]
> FAT32 only goes up to 4GB

Yeah, you're right. It was formatted by TV itself and it chose FAT32 file system.
I resolved my issue using NTFS file system.
