### ISSUE TITLE
Displayed date and time in All Trackers view never fully visible

### ISSUE THREAD

**Issue by dizzyMongoose** [BiglySoftware/BiglyBT#2927]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=111
Windows 10 v10.0, amd64 (64 bit)
B3.3.0.0/4 az3

When looking at the **All Trackers** view, the timestamps for the **Last OK**, **Last Fail**, and **Failing Since** columns always have ellipses (...) instead of showing the time of day, no matter how much you resize the column.

![image](https://user-images.githubusercontent.com/26749854/229370652-7bf453d1-242f-46b8-a016-a8e730540eec.png)

Note in the screenshot that the date and time columns all have ample room on the left, but still don't fully display the time.

**Comment by parg** [comment]
Probsably something to do with your weird DPI of 111

**Comment by NaPurHab** [comment]
@parg Perhaps drop the day of the week, and instead of spelling out the month, go for  dd/mm/yy or mm/dd/yy or yy/mm/dd depending on where you are.

**Comment by parg** [comment]
That column tries to be smart and change the date format depending on the width. If the calculations of how much space a given string are somehow incorrect then perhaps you end up with what you're seeing.

You can set a custom date format for tables or columns. For columns right-click on the column header for the option - there's a link to details on how custom date formats work.

**Comment by dizzyMongoose** [comment]
> Probsably something to do with your weird DPI of 111

Possibly, but I don't have display issues with other dates in BiglyBT (the dates in the Library look fine, for example), just with the ones in All Trackers.

> That column tries to be smart and change the date format depending on the width. If the calculations of how much space a given string takes are somehow incorrect then perhaps you end up with what you're seeing.
> 
> You can set a custom date format for tables or columns. For columns right-click on the column header for the option - there's a link to details on how custom date formats work.

Now that I inspect the various date columns, I notice that the ones in the Library already have a format assigned to them as `[MMM dd, yyyy hh:mm aa]`; the ones in All Trackers that look weird have `[Table Default]` as their format. If I copy-paste the format from the Library to the All Trackers columns, they do start behaving.
