### ISSUE TITLE
Text Alignment Issue in Connection: Advanced Network Settings

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#2928]
@parg You can clean this up when you get time. Not a rush.  You can close this issue after you read it.  

Can you clean up the alignment in this section?  I have highlighted the out of line entries to show the issue.  Oh, after `The following interfaces are available: `, can you add a blank line. It would be a bit cleaner looking.

And some ideas.  What would you think of a Check Box (so it is optional) labeled `Hide entries with no IP Address`  I'm thinking it would reduce the clutter. And let users focus on the entries that IP Addresses.  In the image, that could reduce the list to `lo, eth6, ppp1`. It would be more focused.

Last Idea, a refresh button. Sometimes there is a delay for the entry with the IP to show up. I have to open, close, wait, open to see the updated IP for ppp1.  Where on the first time I open `Connection: Advanced Network Settings` it doesn't show ppp1.  A refresh button would be handy.  Placement could be on the right side of the line: `The following interfaces are available: `.

![Socket Options Screenshot 2023-04-03 163329](https://user-images.githubusercontent.com/37715552/229624447-c5a1e9d0-ef26-438b-8037-c4817c38f50d.png)

Java 1.8.0_361 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_361

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B3.3.0.1_B25/4 az3

**Comment by NaPurHab** [comment]
> Problem with alignment is that it is a simple tab separating the interface name/description and a native component renders it, so figuring out if, for example, two tabs would result in things lining up better, isn't easy.

You already have a different TAB for `name[0]` entries with IP Address.  As to the other, set the TAB Stop at the wider place. Then if it had nothing in the first column but text in the second column, it would align.  Or just use a simple 2 column table and the `name[0]` entries with IP Address can align up with the 2nd column.

> To refresh switch to a different config tree item and then back, should rebuild.

That works, if you explain to each new user how that works.  A clearly labeled button, needs no explanation.

> I could add the option to only show those with addresses though.

It could help, less clutter. And the alignment could be easier to do.

**Comment by NaPurHab** [comment]
> Try B26, it's a bit better

Tried Help: Check for Updates and got the following.  Odd as I have Port Fowarding on my VPN set to ALL. So should be working.

![image](https://user-images.githubusercontent.com/37715552/230131223-e8e2dd90-421d-4526-9bbf-d6e5e97b41f8.png)

Luckily I can grab it from the Chat  `Public - BiglyBT: Updates : Core[R]`.

**Comment by NaPurHab** [comment]
Hmm, B26 is stalled.

![image](https://user-images.githubusercontent.com/37715552/230136090-a04600c2-05a8-4eea-8383-ee420f43ef5b.png)

**Comment by NaPurHab** [comment]
Hmm, this explains why it is stalled:

![image](https://user-images.githubusercontent.com/37715552/230138509-1db905e3-ba6e-4883-9b83-5e2adb5f24a0.png)

**Comment by NaPurHab** [comment]
Merged the following in and now seeing some seeds:

trackerlist:https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_best.txt

**Comment by NaPurHab** [comment]
![image](https://user-images.githubusercontent.com/37715552/230151049-5b3e55b1-ff8d-4946-b957-7ba6e21141f8.png)

Works a charm.  Though, still alignment issues.

Java 1.8.0_361 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_361

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B3.3.0.1_B26/4 az3

**Comment by parg** [comment]
yah, alignment isn't going to be fixed, sorry.
