### ISSUE TITLE
Something odd with statistics.

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#2931]
I created a Dashboard with Statistics on the top 2/3s and the Dish Operations on the bottom.   I started a torrent and wanted to see how it performed over time.  Then as it is cramped in 2/3 of the Dashboard, I tried viewing Statistics directly.  Below are 2 images taken 30 seconds apart.

So, the question is, why are there 2 statistics running at different paces?  Would that not be both repetitive and slow down BBT?

![Dashboard Stats Screenshot 2023-04-07 184600](https://user-images.githubusercontent.com/37715552/230690368-a7444402-d265-4266-bd00-601117d132b9.png)

![Statistics Screenshot 2023-04-07 184703](https://user-images.githubusercontent.com/37715552/230690372-5c8cf578-4e50-45b7-b5c6-3c9d8fc9e5c3.png)

Java 1.8.0_361 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_361

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B3.3.0.1_B26/4 az3

**Comment by parg** [comment]
Each view collects and shows its own statistics, the assumption being (I guess) that there would probably only ever be a maximum of one open at a time.

When there are no statistics views open no stats are collected or maintained.

So the question is, when the majority of users never open a stats view, wouldn't it slow down BiglyBT to collect stats that are of no use?

**Comment by parg** [comment]
BTW, I'm just saying how it works. I didn't design it and I probably wouldn't do it that way but it kinda works and I have 0 interest in changing it.
