### ISSUE TITLE
Feature Request - Right click on "Tags" column

### ISSUE THREAD

**Issue by drelephant** [BiglySoftware/BiglyBT#2932]
Java 11.0.18 (64 bit)
  Ubuntu
/usr/lib/jvm/java-11-openjdk-amd64

SWT v4942r22, gtk/3.22.30, zoom=100, dpi=96
Linux v4.15.0-204-generic, amd64 (64 bit)
B3.3.0.1_B27/4 az3

It would be cool if you could right-click on the "Tags" column to instantly bring up a menu to select a tag for that download.

Thanks!

**Comment by parg** [comment]
The "Tags" sub-tab is good for managing a download's tags.

Or right-click on any column other than the Tags column, select the "Organise" tab on the "menu" and there's a Tags menu item to add a tag.

**Comment by drelephant** [comment]
Thanks, I'm aware of those spots. It's just something I do so often that I think it'd be good to be accessible directly from the list.

The one I always do is double-clicking on the Tags column, but I'd rather it was a right-click menu.

Thanks anyway for the great program!
