### ISSUE TITLE
error : no data found

### ISSUE THREAD

**Issue by cordial69** [BiglySoftware/BiglyBT#2934]
do no download with this error
[debug.zip](https://github.com/BiglySoftware/BiglyBT/files/11190074/debug.zip)

* OS and version  windws 11
* BiglyBT Version Number  3.3.0.0
* For *nix: Desktop Environment

**Comment by parg** [comment]
"Data missing" can mean that the file has been deleted by, say, your anti-virus software. You can right-click on the download and select "force recheck", this will attempt to recreate the file and allow the download to continue.

However, if it is your anti-virus software deleting the file it might be sensible to think before doing so.

**Comment by cordial69** [comment]
No deleted file. file must be created wiith torrent items
See attached file
![Snap2](https://user-images.githubusercontent.com/130362426/230897385-7a7ec827-62a7-4317-8fa9-766bda67c4be.jpg)

**Comment by parg** [comment]
Can you download

https://download.documentfoundation.org/libreoffice/stable/7.5.2/win/x86_64/LibreOffice_7.5.2_Win_x86-64.msi.torrent

If so then the problem is with what you are downloading, not something I can help with.

**Comment by cordial69** [comment]
same problem see attachment
![Snap5](https://user-images.githubusercontent.com/130362426/230901547-11a63069-6bda-47e3-bae4-35a955df6bf5.jpg)

**Comment by parg** [comment]
Maybe you don't have write permission to 

C:\Users\ga69\Documents\Vuze Downloads

try saving the download somewhere else?

**Comment by cordial69** [comment]
I downloaded to desktop and it is ok
i don't understand why ?

**Comment by parg** [comment]
me neither

**Comment by cordial69** [comment]
I tried to move datas to another folder and it don't worrk and stay in desktop

**Comment by SodaWithoutSparkles** [comment]
Ah, I remember having to deal with these sorts of problems. You have anti-virus installed? Dont ever save non-office documents in the docunents folder, especially any form of source code, as they would be delt with by your AV. 

I once cloned my own github repo to documents and have such a headache. I solved it by placing it somewhere else under my username. For exanple, try moving to `C:\Users\ga69\torrents` instead.

You may also need to reboot your device. Last resort: backup configs, nuke the install, install again to the new location.
