### ISSUE TITLE
RSSFeed Scanner download history grows forever, creates interface lag

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#2937]
I happened upon [a very old conversation](https://forum.vuze.com/Thread-RSSFeed-download-history) @ the Vuze forums, believe it or not, that reminded me about this issue. I'd discovered it at the time, dealt with the immediate symptoms, and then promptly forgot about the actual _cause_ which remains unaddressed.

#### Those who remember history _too well_ ...
RSSFeed Scanner has options to control how much feed data it retains and for how long, but it **DOESN'T** provide any configuration at all for its Download History tab, a table which gains an entry for every feed URL that's imported into BiglyBT as a torrent download, whether `magnet:` or `.torrent`-file based, and which retains an unlimited amount of that history for eternity, forever growing larger.

Worse, the data for that table is stored in the `rssfeed.options` file _along with_ the user's feed configuration, which means the entire download history has to be exported or imported with every configuration save/load. Over time, this can have a serious impact on the UI responsiveness for the plugin.

#### ...are doomed to suffer for it?

I just checked (after reviewing that old conversation) my Download History, and sure enough the list contained **EVERY SINGLE TORRENT** I've ever imported via RSSFeed Scanner since I started using BiglyBT way back in 2017. There were literally thousands upon thousands of rows, and all that data had bloated the `rssfeed.options` file's disk size to over 4MB of tightly-packed binary serialization. Exported to JSON (just as a precaution), it became 6.2MB.

#### Forget the past!

Here are the results of manually deleting everything before mid-2022 from my history list. (Fortunately, the table interface _does_ allow mass-selection of rows, and there's a "Delete selected torrents" context menu to remove them.):
* My `rssfeed.options` is reduced by well over 80%, to less than 500K on disk
* The list itself is a few hundred rows or less, down from an unknown thousands of entries
* When first loading the plugin tab, the UI initializes in a fraction of a second, instead of the 3-4 seconds it was _previously_ taking due to the amount of history data that had to be loaded.
* (I'm sure the client's overall memory consumption dropped as well, though that's a relatively minor concern for me personally.)

The plugin could really, _**really**_ use some way of constraining the history list's endlessly-ballooning corpulence, whether by item count, retention period, etc. (Any one would do, "all of the above" is certainly good as well but hardly a requirement.)

But the onus definitely shouldn't be entirely on the user to give the list regular prunings, or to suffer severe interface slowdowns for their "negligence".

### System block
```text
Java 11.0.18 (64 bit)
  Red Hat, Inc.
/usr/lib/jvm/java-11-openjdk-11.0.18.0.10-1.fc37.x86_64

SWT v4956r12, gtk/3.24.37, zoom=100, dpi=96
Linux v6.2.10-200.fc37.x86_64, amd64 (64 bit)
B3.3.0.1_B30/4 az3
```

### Plugin details
* RSSFeed Scanner: 1.8.4
* Configuration:
    Plugin.rssfeed.AutoStartManual=0
    Plugin.rssfeed.KeepMax=100
    Plugin.rssfeed.KeepOld=7
    Plugin.rssfeed.RSSFeed.Config.netforce=1
    Plugin.rssfeed.RSSFeed.Config.netforce.Public=1
    Plugin.rssfeed.ui.tabFolder.sel.index=2

**Comment by parg** [comment]
You know where the source is :) https://github.com/BiglySoftware/BiglyBT-plugin-rssfeed

**Comment by ferdnyc** [comment]
@parg Fair! Consider this my note-to-self reminder not to forget about the problem for _another_ 5 years.
