### ISSUE TITLE
Vuze wiki seems to have gone Away™

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#2939]
Not going to hold my breath on it coming back, either.

So, I just created the repo https://github.com/ferdnyc/biglybt-wiki-import/ that contains:

- (In the `html/` subdirectory) Wayback-Machine captures (collected with the clever [`wayback` Python module](https://github.com/edgi-govdata-archiving/wayback)) of every page that's referenced in `com.biglybt.core.utils.Wiki`.
- (In the repo root) GitHub-Flavored Markdown conversions of same, created with `pandoc`.

(I couldn't get the Wikitext source — the Wayback Machine doesn't scrape the edit interface for wiki pages, only the rendered output, so with the wiki down grabbing the source is no longer an option. So is grabbing the edit history, to properly credit the original contributors, which is honestly quite a bummer.)

But the conversions aren't so bad! They're _almost_ readable enough as MarkDown to replace the in-client wiki links; there's just a few items on my TODO list:

- [x] (Biggest item:) Gather all of the `<img>` tags' `src=` strings, and download the Wayback-Machine captures of those images.
- [ ] One of:
    - [ ] Replace said `<img src=>` attributes with references to the local copy, and reconvert
    - [ ] Substitute the `<img>` tags in the `.md` files with MarkDown image embeds.
- [ ] Remove all of the `[edit]` links on the section headings
- [ ] Remove the long section at the bottom of each file that's converted from the wiki chrome (sidebar, footer, etc.)

That's mostly it, there's plenty of other cleanup to be done but it'd have to be case-by-case and can be after-the-fact; the stuff on the checklist is stuff that every file needs, and can be done programmatically.

...I'm _assuming_, in all of this, that it's something that would be useful and desired, if BiglyBT were to put up its own copies of these pages to replace [this (now-broken) silliness](https://wiki.biglybt.com/wiki.php?q=UG_Options_Interface_Format_Overrides)?

If so, the big question becomes: Where does it go? Do you want to create a new repo under the BiglySoftware organization umbrella, to push all of this into so it can be published from, and linked to, there? Or, is it better to import it all into the GitHub wiki for _this_ repo, so it's right here?

(Oh, and I should mention that _technically_ converting **to** wikitext from the HTML is also possible — `pandoc` has that feature as well. I don't know how it would come out, but iff it were all going to go up at https://wiki.biglybt.com/, that might also be an option.)

**Comment by parg** [comment]
Any idea how long it has been down for? I hadn't noticed

**Comment by ferdnyc** [comment]
Not entirely sure, but a few days, at least, by now.

**Comment by ferdnyc** [comment]
Just finished scraping the images (into an `images/` subfolder) and pushed, but they're not replaced into the source files yet.

**Comment by ferdnyc** [comment]
. o O (I think I _took_ some of these screenshots!) :rofl:

**Comment by parg** [comment]
Is there a way of spidering the wayback content to grab pages not directly referenced? It would be a shame to lose them.

I'm thinking that any copy of the wiki should, if it makes sense to publish it, remain separate from any BiglyBT wiki and no updated with any BiglyBT stuff - just from a desire to avoid anyone moaning about, well, stuff

**Comment by ferdnyc** [comment]
> Is there a way of spidering the wayback content to grab pages not directly referenced? It would be a shame to lose them.

Pages that are referenced _nowhere_? Probably not, because they wouldn't have even scraped them to begin with. But any page that's in at least one category will be linked to _from_ the category index... and (in part due to [a bunch of work I did nearly a decade ago](https://forum.vuze.com/Thread-Wiki-organization-improvements)) that should be **most** pages on the wiki. Wayback captured the category indices, so it'll have all of those pages.

> I'm thinking that any copy of the wiki should, if it makes sense to publish it, remain separate from any BiglyBT wiki and no updated with any BiglyBT stuff - just from a desire to avoid anyone moaning about, well, stuff

Mmm, I get that argument, though
1. It kind of makes this all way less useful, as it doesn't do anything to solve the "off-project"-links-in-BiglyBT thing. (The goal for me here is mostly to quit leaning on Vuze, and jumpstart a long-overdue Actual BiglyBT Wiki™ replacement.)
2. Especially not updating it; setting up a **new** source for wildly-outdated, questionably-relevant information feels... unproductive? (_Personally_ I'm not real interested in retaining this stuff for "posterity"; as said, that's not really my goal here.)

If it were any typical wiki I'd say, "Hey, screw 'em if they can't take a joke. They knew the score when they set up a public wiki filled with content available under a free license."

(Those are the terms typically associated, maybe even synonymous, with wiki content; and it's certainly the terms under which my own contributions were assumed to have been made. You can't _have_ a public wiki with restrictive licensing, unless all of the **contributors** are made to sign over their rights to their own contributions, and agree to place them under the same terms. Which we did not do.)

Buuuuuuuut, I see now that, putting aside the question of whether the wiki's collective content **can** actually be licensed restrictively or not, Vuze cleverly managed to avoid even confronting that question because they _didn't make **any** license statement_ for the wiki. Like, not only are there no _free_ license terms, there are NO license terms _**AT ALL**_.

The wiki's `LocalSettings.php` appears to have a `$wgRightsText` variable that, instead of holding the MediaWiki-recommended default "Text is available under the [Creative Commons Attribution-ShareAlike License 3.0](https://en.wikipedia.org/wiki/Wikipedia:Text_of_the_Creative_Commons_Attribution-ShareAlike_3.0_Unported_License); additional terms may apply." statement, or something else equivalent/comparable, contains only this:
> Any use of Vuze® and Vuze+™ that violates the rights of any person or entity is not allowed. [More](http://vuze.com/corp/legal.php)

...Which says jack-all about the wiki content! (Nor is the topic covered at the lawyeriffic page at the other end of that link.)

This Vexes FeRD™.

**Comment by TuxPaper** [comment]
One thing to consider is ChatGPT.

In theory, one could feed ALL the biglybt/vuze wiki pages into ChatGPT and have it generate the individual wiki pages, as well as overview pages and intros/etc.  Plus it would/could adjust the reading level to make it easier to read, and pick out any discrepancies between information.  I'm not a ChatGPT export, but things like "WHen appropriate, include general bittorent information to provide needed context and instruction" might even generate something better than we could ever write.  Even just passing one wiki page to ChatGPT and asking it to "make it easier to read and more informative" does magic.
