### ISSUE TITLE
Application closes abruptly

### ISSUE THREAD

**Issue by RegProctor** [BiglySoftware/BiglyBT#2940]
I can't show much because it just disappears now. I'll open it, it will do some startup stuff and then I guess some internal event happens and it immediately closes itself without warning. I just downloaded and reran the installer hoping it would install some newer files that would fix it but it's still happening.

My distro is Linux Tumbleweed and I keep up to date pretty much weekly.

It happens maybe 50-60% of the time when I open the app. and if I leave it running over night it is almost always closed when I get up the next day.

Java 11.0.18 (64 bit)
  Oracle Corporation
/usr/lib64/jvm/java-11-openjdk-11

SWT v4942r22, gtk/3.24.37, zoom=100, dpi=96
Linux v6.2.10-1-default, amd64 (64 bit)
B3.3.0.0/4 az3

**Comment by RegProctor** [comment]
I managed to catch crashing with `journclt -f` running and here's the log:

Apr 21 00:46:19 quark java[7007]: g_dbus_server_get_client_address: assertion 'G_IS_DBUS_SERVER (server)' failed
Apr 21 00:46:19 quark plasmashell[7007]: #
Apr 21 00:46:19 quark plasmashell[7007]: # A fatal error has been detected by the Java Runtime Environment:
Apr 21 00:46:19 quark plasmashell[7007]: #
Apr 21 00:46:19 quark plasmashell[7007]: #  SIGSEGV (0xb) at pc=0x00007f7950c36e16, pid=7007, tid=7028
Apr 21 00:46:19 quark plasmashell[7007]: #
Apr 21 00:46:19 quark plasmashell[7007]: # JRE version: OpenJDK Runtime Environment (11.0.18) (build 11.0.18+0-suse-3.2-x8664)
Apr 21 00:46:19 quark plasmashell[7007]: # Java VM: OpenJDK 64-Bit Server VM (11.0.18+0-suse-3.2-x8664, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
Apr 21 00:46:19 quark plasmashell[7007]: # Problematic frame:
Apr 21 00:46:19 quark plasmashell[7007]: # C  [libswt-gtk-4942r22.so+0x36e16]  Java_org_eclipse_swt_internal_C_strlen+0xf
Apr 21 00:46:19 quark plasmashell[7007]: #
Apr 21 00:46:19 quark plasmashell[7007]: # Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /home/reg/biglybt/core.7007)
Apr 21 00:46:19 quark plasmashell[7007]: #
Apr 21 00:46:19 quark plasmashell[7007]: # An error report file with more information is saved as:
Apr 21 00:46:19 quark plasmashell[7007]: # /home/reg/biglybt/hs_err_pid7007.log
Apr 21 00:46:19 quark plasmashell[7007]: Compiled method (nm)  576404 4753     n 0       org.eclipse.swt.internal.C::strlen (native)
Apr 21 00:46:19 quark plasmashell[7007]:  total in heap  [0x00007f797862c310,0x00007f797862c6a8] = 920
Apr 21 00:46:19 quark plasmashell[7007]:  relocation     [0x00007f797862c488,0x00007f797862c4b8] = 48
Apr 21 00:46:19 quark plasmashell[7007]:  main code      [0x00007f797862c4c0,0x00007f797862c6a0] = 480
Apr 21 00:46:19 quark plasmashell[7007]:  oops           [0x00007f797862c6a0,0x00007f797862c6a8] = 8
Apr 21 00:46:19 quark plasmashell[7007]: Compiled method (c1)  576404 19884       3       org.eclipse.swt.internal.Converter::cCharPtrToJavaString (39 bytes)
Apr 21 00:46:19 quark plasmashell[7007]:  total in heap  [0x00007f7973743390,0x00007f7973743ae8] = 1880
Apr 21 00:46:19 quark plasmashell[7007]:  relocation     [0x00007f7973743508,0x00007f7973743588] = 128
Apr 21 00:46:19 quark plasmashell[7007]:  main code      [0x00007f79737435a0,0x00007f79737438c0] = 800
Apr 21 00:46:19 quark plasmashell[7007]:  stub code      [0x00007f79737438c0,0x00007f7973743940] = 128
Apr 21 00:46:19 quark plasmashell[7007]:  oops           [0x00007f7973743940,0x00007f7973743948] = 8
Apr 21 00:46:19 quark plasmashell[7007]:  metadata       [0x00007f7973743948,0x00007f7973743958] = 16
Apr 21 00:46:19 quark plasmashell[7007]:  scopes data    [0x00007f7973743958,0x00007f7973743a10] = 184
Apr 21 00:46:19 quark plasmashell[7007]:  scopes pcs     [0x00007f7973743a10,0x00007f7973743ad0] = 192
Apr 21 00:46:19 quark plasmashell[7007]:  dependencies   [0x00007f7973743ad0,0x00007f7973743ad8] = 8
Apr 21 00:46:19 quark plasmashell[7007]:  nul chk table  [0x00007f7973743ad8,0x00007f7973743ae8] = 16
Apr 21 00:46:19 quark plasmashell[7007]: Compiled method (nm)  576405 4753     n 0       org.eclipse.swt.internal.C::strlen (native)
Apr 21 00:46:19 quark plasmashell[7007]:  total in heap  [0x00007f797862c310,0x00007f797862c6a8] = 920
Apr 21 00:46:19 quark plasmashell[7007]:  relocation     [0x00007f797862c488,0x00007f797862c4b8] = 48
Apr 21 00:46:19 quark plasmashell[7007]:  main code      [0x00007f797862c4c0,0x00007f797862c6a0] = 480
Apr 21 00:46:19 quark plasmashell[7007]:  oops           [0x00007f797862c6a0,0x00007f797862c6a8] = 8
Apr 21 00:46:19 quark plasmashell[7007]: #
Apr 21 00:46:19 quark plasmashell[7007]: # If you would like to submit a bug report, please visit:
Apr 21 00:46:19 quark plasmashell[7007]: #   https://bugreport.java.com/bugreport/crash.jsp
Apr 21 00:46:19 quark plasmashell[7007]: # The crash happened outside the Java Virtual Machine in native code.
Apr 21 00:46:19 quark plasmashell[7007]: # See problematic frame for where to report the bug.
Apr 21 00:46:19 quark plasmashell[7007]: #
Apr 21 00:46:19 quark WebKitWebProces[9050]: Theme parsing error: gtk.css:1649:16: '-gtk-icon-size' is not a valid property name
Apr 21 00:46:19 quark WebKitWebProces[9050]: Theme parsing error: gtk.css:1652:16: '-gtk-icon-size' is not a valid property name
Apr 21 00:46:19 quark systemd[1]: Started Process Core Dump (PID 9051/UID 0).
Apr 21 00:46:20 quark ksmserver[24175]: [2023-04-21 00:46:20.702] [   ] [debug] autosave no need
Apr 21 00:46:30 quark systemd-coredump[9065]: [🡕] Process 7007 (java) of user 1000 dumped core.
                                              
                                              Stack trace of thread 7028:
                                              #0  0x00007f798e758d7c __pthread_kill_implementation (libc.so.6 + 0x8fd7c)
                                              #1  0x00007f798e707356 raise (libc.so.6 + 0x3e356)
                                              #2  0x00007f798e6ef897 abort (libc.so.6 + 0x26897)
                                              #3  0x00007f798d48401b _ZN2os5abortEbPvPKv.cold (libjvm.so + 0x28401b)
                                              #4  0x00007f798e0b1914 _ZN7VMError14report_and_dieEiPKcS1_P13__va_list_tagP6ThreadPhPvS7_S1_im (libjvm.so + 0xeb1914)
                                              #5  0x00007f798e0b241b _ZN7VMError14report_and_dieEP6ThreadjPhPvS3_PKcz (libjvm.so + 0xeb241b)
                                              #6  0x00007f798e0b244e _ZN7VMError14report_and_dieEP6ThreadjPhPvS3_ (libjvm.so + 0xeb244e)
                                              #7  0x00007f798de2ba71 JVM_handle_linux_signal (libjvm.so + 0xc2ba71)
                                              #8  0x00007f798de1e338 _ZL13signalHandleriP9siginfo_tPv (libjvm.so + 0xc1e338)
                                              #9  0x00007f7749ad9bdc n/a (libjavascriptcoregtk-4.0.so.18 + 0x10d9bdc)
                                              #10 0x00007f798e707420 __restore_rt (libc.so.6 + 0x3e420)
                                              #11 0x00007f7950c36e16 Java_org_eclipse_swt_internal_C_strlen (/home/reg/.swt/lib/linux/x86_64/libswt-gtk-4942r22.so + 0x36e16)
                                              #12 0x00007f797862c574 n/a (n/a + 0x0)
                                              #13 0x00007f7973743604 n/a (n/a + 0x0)
                                              #14 0x00007f7970800cc9 n/a (n/a + 0x0)
                                              #15 0x00007f798da9c823 _ZN9JavaCalls11call_helperEP9JavaValueRK12methodHandleP17JavaCallArgumentsP6Thread (libjvm.so + 0x89c823)
                                              #16 0x00007f798db22e5c _ZL17jni_invoke_staticP7JNIEnv_P9JavaValueP8_jobject11JNICallTypeP10_jmethodIDP18JNI_ArgumentPusherP6Thread.constprop.1 (libjvm.so + 0x922e5c)
                                              #17 0x00007f798db25bbc jni_CallStaticLongMethodV (libjvm.so + 0x925bbc)
                                              #18 0x00007f7950c3756f callback (/home/reg/.swt/lib/linux/x86_64/libswt-gtk-4942r22.so + 0x3756f)
                                              #19 0x00007f7950c3af5b fn57_2 (/home/reg/.swt/lib/linux/x86_64/libswt-gtk-4942r22.so + 0x3af5b)
                                              #20 0x00007f795066f4f0 g_closure_invoke (libgobject-2.0.so.0 + 0x174f0)
                                              #21 0x00007f7950682946 n/a (libgobject-2.0.so.0 + 0x2a946)
                                              #22 0x00007f79506898e6 g_signal_emit_valist (libgobject-2.0.so.0 + 0x318e6)
                                              #23 0x00007f7950689a5f g_signal_emit (libgobject-2.0.so.0 + 0x31a5f)
                                              #24 0x00007f774ac08bc5 n/a (libwebkit2gtk-4.0.so.37 + 0xa08bc5)
                                              #25 0x00007f774abf40dd n/a (libwebkit2gtk-4.0.so.37 + 0x9f40dd)
                                              #26 0x00007f774abf5a14 n/a (libwebkit2gtk-4.0.so.37 + 0x9f5a14)
                                              #27 0x00007f774abf5f3f n/a (libwebkit2gtk-4.0.so.37 + 0x9f5f3f)
                                              #28 0x00007f774aba5fad n/a (libwebkit2gtk-4.0.so.37 + 0x9a5fad)
                                              #29 0x00007f774ac6d079 n/a (libwebkit2gtk-4.0.so.37 + 0xa6d079)
                                              #30 0x00007f774ac6d559 n/a (libwebkit2gtk-4.0.so.37 + 0xa6d559)
                                              #31 0x00007f774ac6d9df webkit_web_view_run_javascript (libwebkit2gtk-4.0.so.37 + 0xa6d9df)
                                              #32 0x00007f774e206956 Java_org_eclipse_swt_internal_webkit_WebKitGTK_webkit_1web_1view_1run_1javascript (/home/reg/.swt/lib/linux/x86_64/libswt-webkit-gtk-4942r22.so + 0x6956)
                                              #33 0x00007f797080f930 n/a (n/a + 0x0)
                                              #34 0x00007f797080a203 n/a (n/a + 0x0)
                                              #35 0x00007f7970809f80 n/a (n/a + 0x0)
                                              #36 0x00007f79708099d0 n/a (n/a + 0x0)
                                              #37 0x00007f797080a203 n/a (n/a + 0x0)
                                              #38 0x00007f797080a203 n/a (n/a + 0x0)
                                              #39 0x00007f797080a203 n/a (n/a + 0x0)
                                              #40 0x00007f797080a203 n/a (n/a + 0x0)
                                              #41 0x00007f797080a203 n/a (n/a + 0x0)
                                              #42 0x00007f797080a203 n/a (n/a + 0x0)
                                              #43 0x00007f7970809f80 n/a (n/a + 0x0)
                                              #44 0x00007f797080a203 n/a (n/a + 0x0)
                                              #45 0x00007f797080a203 n/a (n/a + 0x0)
                                              #46 0x00007f7978d93b5c n/a (n/a + 0x0)
                                              ELF object binary architecture: AMD x86-64
Apr 21 00:46:30 quark systemd[1]: systemd-coredump@8-9051-0.service: Deactivated successfully.
Apr 21 00:46:30 quark plasmashell[6908]: /home/reg/biglybt/biglybt: line 227:  7007 Aborted                 (core dumped) ${JAVA_PROGRAM_DIR}java -Xmx256m -cp "${CLASSPATH}" "-Djava.library.path=${PROGRAM_DIR}" "-Dazureus.install.path=${PROGRAM_DIR}" "-Dazureus.script=$0" ${JAVA_PROPS} ${JAVA_ARGS} ${START_CLASS} ${OTHER_PARAMS} "$@"
Apr 21 00:46:30 quark plasmashell[6908]: Exit from BiglyBT complete
Apr 21 00:46:30 quark kded5[23863]: Service  ":1.1949" unregistered
Apr 21 00:46:30 quark systemd[1]: systemd-coredump@8-9051-0.service: Consumed 9.124s CPU time.
Apr 21 00:46:30 quark plasmashell[9081]: WARNING: An illegal reflective access operation has occurred
Apr 21 00:46:30 quark plasmashell[9081]: WARNING: Illegal reflective access by com.biglybt.core.util.spi.AENameServiceJava9 (file:/home/reg/biglybt/BiglyBT.jar) to field java.net.InetAddress.impl
Apr 21 00:46:30 quark plasmashell[9081]: WARNING: Please consider reporting this to the maintainers of com.biglybt.core.util.spi.AENameServiceJava9
Apr 21 00:46:30 quark plasmashell[9081]: WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
Apr 21 00:46:30 quark plasmashell[9081]: WARNING: All illegal access operations will be denied in a future release
Apr 21 00:46:31 quark plasmashell[6908]: No shutdown tasks to do
Apr 21 00:46:31 quark plasmashell[6908]: BiglyBT TERMINATED.
Apr 21 00:46:31 quark systemd[4037]: app-biglybt-8a7a48a3391740919e89b2f9e1e14757.scope: Consumed 5min 16.375s CPU time.

**Comment by RegProctor** [comment]
[hs_err_pid7007.zip](https://github.com/BiglySoftware/BiglyBT/files/11293551/hs_err_pid7007.zip)
Here's the log file mentioned in the dump.

**Comment by parg** [comment]
Yeah, I was semi-joking :) Just annoying when something updates and seems to break BiglyBT. Try that updated SWT jar, the crash is in the old version of it.

**Comment by parg** [comment]
If that doesn't fix it then try going to 

Options->Interface->Display: Disable all use of the internal browser.

and disabling the internal browser.

**Comment by RegProctor** [comment]
There's no actual swt.jar where it was installed. I'm going assume I need to rename it to swt-x86.jar to match my system. No need to respond if this is correct but please do correct me if I got that wrong.

**Comment by RegProctor** [comment]
I think the update to swt.jar file fixed it. Even without running it for long the very first thing I noticed was that it started up in less than 30% of the time it used to take. This is for a very long time, over a year I would think, and, it immediately started to download files that it wouldn't even acknowledge were there before. I'll leave it running for a few hours before saying so for sure but I suspect this issue is closed.

**Comment by parg** [comment]
Sounds hopeful. I would make that the default SWT for linux but unfortunately there are some users (hopfully not you!) having issues with it.

**Comment by RegProctor** [comment]
This as far as I can tell is fixed.
