### ISSUE TITLE
Metadata downloads to user profile folder instead of configured paths

### ISSUE THREAD

**Issue by Maxispark** [BiglySoftware/BiglyBT#2942]
Java 1.8.0_361 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_361

SWT v4942r22, win32, zoom=100, dpi=96
Windows 7 v6.1, amd64 (64 bit)
B3.3.0.0/4 az3

When downloading metadata for new torrents that have been selected from the content discovery section, BiglyBT seems to ignore configuration and downloads to the Windows profile path. i.e. C:\Users\<username>\AppData\Roaming\BiglyBT\torrents\md

Every path within the BiglyBT options dialogs has been set to be with the E:\_BiglyBT\ tree but torrents sometimes download to the Windows profile path regardless. This isn't sporadic. It switches from the configured E: path to the Windows profile path and remains there. It also seems to download the actual files of the torrent to the metadata path and I had to delete those since the C drive is not the download drive and I do not want it growing by gigabytes.

Based on all the paths being configured to E: I would expect that anything to do with torrent links or downloaded files to appear on E: and only configuration-related files for BiglyBT to be on C:

**Comment by parg** [comment]
torrents/md is supposed to be transitory and entries deleted once the metadata download is complete. I just checked a few BiglyBT instances that have been running a long time and both folders are empty. So I'm not sure why you're getting stuff in there.
