### ISSUE TITLE
BBT looping back on peers, trying to connect to itself.

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#2948]
![image](https://user-images.githubusercontent.com/37715552/235328364-44cb8329-3b42-4d4f-9061-3dedfd5c66fe.png)

I have reported this in the past.  I keep seeing this in the peers tab on torrents.  The green line is the 'Show local peer' option, while the other line is BBT trying a local connection to a remote peer. The issue is that it is trying to connect to itself. This is a long-standing issue.

The Fix for it could be done by having a temporary IP ban applied to the routing IP. Try to keep it from trying to connect to itself.  Similar to a 'Kick and Ban for', but tied instead to the Routing, and automatically applied when a new Routing takes effect. It would expire the previous bad, and apply a new Ban for the Routing IP.

Anyway that is my idea for a possible solution. But its an issue that has been there for years.

Java 1.8.0_371 (64 bit)
  Oracle Corporation
c:\program files\java\jre-1.8

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B3.3.0.1_B33/4 az3

**Comment by parg** [comment]
Ignore it, not like it is a major problem is it?

**Comment by NaPurHab** [comment]
More just annoying. It should know not to connect to itself, it's a bit like masturbation.

**Comment by parg** [comment]
speak for yourself
