### ISSUE TITLE
Flatpack folder change on each startup

### ISSUE THREAD

**Issue by Musickiller** [BiglySoftware/BiglyBT#2951]
# Description

All folders I choose, are being converted from `/home/name/Downloads/HDD-Downloads/biglybt/` to `/run/flatpak/doc/<random thing>/biglybt/` which seem change on every startup. Is there a way to choose folders directly or mitigate the issue in some other way?

It may be caused by the fact that my torrents are stored on a second drive, but it gets mounted with fstab, so there should be no issue o_O

Note: HDD-Downloads is a link to /home/name/other/btrfs/home/mk/Downloads/ which is another drive. Will try to save directly to that folder, instead of a link... I think o_O

Anyway, I will test with my Downloads folder later.

# Reproduction

1. Install BiglyBT with flatpack,
2. save torrent to some folder,
3. restart,
4. observe missing data due to folder being empty (unmounted?)
5. select "new" folder (the same as last time)
6. Files found, continue download

# About
Java 11.0.16.1 (64 bit)
  Flathub
/app/jre

SWT v4942r22, gtk/3.24.37, zoom=100, dpi=96
Linux v6.1.25-1-MANJARO, amd64 (64 bit)
B3.3.0.0/4 az3

* For *nix: Desktop Environment: KDE

**Comment by parg** [comment]
You might want to ask here - https://github.com/flathub/com.biglybt.BiglyBT/issues
