### ISSUE TITLE
Why is the graceful-exit option not in Startup & Shutdown?

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#2953]
I _fully_ get that things just end up where they end up, sometimes, and there isn't always a real "reason". Buuut...

Why is the "Wait for BiglyBT to close tidily on exit/restart and display progress" preference located in **Options->Interface->Display->Various** ("Various", in particular, makes it seem like it was just randomly tossed there), when there's a whole "Startup & Shutdown" options category?

(And in fact, **Options->Startup & Shutdown->Shutdown** contains the _very_ related option, "Force terminate if shutdown stalls for <var>N</var> minutes". Seems like those should be _near_ each other, at least?)

Is it a core-vs.-ui thing? I don't really remember how the options code is partitioned offhand. If it's a chore or confusing to mix core options and UI options, I can accept that.

#### System block (not that it's relevant)

```
Java 11.0.18 (64 bit)
  Red Hat, Inc.
/usr/lib/jvm/java-11-openjdk-11.0.18.0.10-1.fc38.x86_64

SWT v4956r12, gtk/3.24.37, zoom=100, dpi=96
Linux v6.2.13-300.fc38.x86_64, amd64 (64 bit)
B3.3.0.1_B36/4 az3
```

**Comment by parg** [comment]
Exactly, "Startup & Shutdown" isn't in the "Interface" options tree...

**Comment by ferdnyc** [comment]
Asked & answered!
