### ISSUE TITLE
Weird empty-row (COMPLETELY empty) visual glitch in Library tables

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#2960]
This is something weird that seems to have cropped up recently, for me. It _may_ have started only after I upgraded to Fedora 38 on the server running BiglyBT... or, it may have started with the installation of one of the recent beta builds. Can't say for sure.

It **seems** to have something to do with a new row getting added to a table _not_ in place of one of the existing (empty) rows, but instead extending it unnecessarily. 

![image](https://github.com/BiglySoftware/BiglyBT/assets/538020/7a268e16-baa6-4c9e-a8c8-343bf7067819)

#### A timeline of events leading to this screenshot

1. I had three torrents (1, 2, and 3, as indicated in the second column — which is "Order", renamed to "#") active in the Incomplete section of my Library view (seen here).
2. Below those three torrents were ~6 empty rows and change, to occupy the remaining vertical space.
3. I placed a new `.torrent` file in one of the client's auto-import directories, which was duly imported as torrent number 4.
4. _Even though_ there were plenty of empty rows in the table, **adding the new fourth torrent caused the table height to grow by one row, so that now the table can scroll vertically** despite not needing to. (There's still a row for torrent 1 at the top of the table, in the screenshot. It's just scrolled off the top edge of the widget.)
5. Obviously, the extra row _doesn't need to be there_ for any reason; there was plenty of room to add the torrent in one of the existing, empty rows instead. And at least _some_ of the code seems to realize that, because **rather than painting the row-that-should-not-be (which is always the one directly beneath the last "occupied" row) it'll just appear as a completely white void**, as seen here.
6. (That's seemingly _guaranteed_ to happen if I double-click one of the rows to open its Details view, then close that view to return to the Library. When I arrive back at the Library view, bam: White row.)
7. Clicking the blank row deselects any previously-selected row(s). Sometimes, it also makes the blank row disappear. (That seems more likely if the selection was previously on the row immediately above it.) Clicking one of the other (painted) blank rows sometimes does nothing, sometimes causes the blank row to appear/disappear. Clicking the occupied rows sometimes does the same, or nothing. The table remains one row taller than it should be, though, whether all of the rows are painted correctly or not. It can be scrolled vertically by one row, despite there being no need to do so, whether or not there's a white row. 
8. It's not 100% predictable _visually_, but despite its appearance being a heisenbug the unnecessary extra row is persistent until either:
    * the table shrinks (torrents complete / are deleted and their rows removed), or
    * I resize the widget vertically

### System block

> Java 11.0.18 (64 bit)
>   Red Hat, Inc.
> /usr/lib/jvm/java-11-openjdk-11.0.18.0.10-1.fc38.x86_64
> 
> SWT v4956r12, gtk/3.24.37, zoom=100, dpi=96
> Linux v6.2.13-300.fc38.x86_64, amd64 (64 bit)
> B3.3.0.1_B39/4 az3
>

**Comment by ferdnyc** [comment]
And I just noticed that, when the row-that-should-not-be isn't painted, the even/odd row background effect also skips over it. Everything, visually, points to the row **below** it being treated as if it should actually be the one occupying the space where that blank row shows up.

**Comment by ferdnyc** [comment]
Here's what the table looks like, scrolled to the bottom when there **isn't** a white row. Notice the still-weird disruption in the alternating-colors effect in the very last rows:

![image](https://github.com/BiglySoftware/BiglyBT/assets/538020/4340202c-91a0-4f31-a9f3-f28b771e2700)

**Comment by parg** [comment]
yeah....

I'm going to go for Fedora somehow being to blame, nothing has changed recently in the way tables are drawn that I can remember and I've not seen it anywhere else.

Have you changed the row-height of the view? ctrl+mouse-scroll or header context menu to change.

How reproducible is it?

**Comment by ferdnyc** [comment]
@parg Row height was set to `19 px`, which AFAICT was 1 more than the default "1 line" height which == `18 px`.

Setting it back to "1 line" _may_ have helped with the weird, on-again/off-again blank white row thing. (At least, I'm having trouble triggering that now.)

But it definitely doesn't eliminate the "table scrolls vertically even though there's plenty of room to display all of its populated rows" issue. That still happens 100% of the time, even with 1 line / `18 px` row height. As soon as the table reaches 4 occupied rows, there'll be a height "overhang" of ~ 1 row, making the table vertically scrollable by that amount.

**Comment by parg** [comment]
I cranked up a Fedora 38 and although I managed to create some visual cheese by fiddling with viewport size and scrolling it never ended up with an extra row :(

**Comment by ferdnyc** [comment]
@parg 

Eek, if I'd known you were going to go through all of that, I'd probably at least have mentioned that I'm using LXDE as the desktop environment (it's a headless server). I _doubt_ that matters, but who knows?

I do have another data point to add: In some more testing, the overscroll thing only occurs if the columns are also _wider_ than the table width. (So, a horizontal scrollbar is already present.) If they fit in the widget, adding torrents doesn't affect the table height (until there are more rows than can be displayed in the available height).

Also, _migrating_ torrent rows from Completed to Incomplete never causes the scroll height to change. So, if I have a partially-complete torrent in Completed, and I enable some new files to download so it moves back to Incomplete, the table height is normal.

So it's only:
1. when importing torrents (creating entirely new rows), whether manually or automatically,
2. into an Incomplete table with more total column width than it can display within the available widget area,

...that the _height_ also ends up (prematurely) exceeding the available display area.

**Comment by ferdnyc** [comment]
> In some more testing, the overscroll thing only occurs if the columns are also _wider_ than the table width. (So, a horizontal scrollbar is already present.) If they fit in the widget, adding torrents doesn't affect the table height (until there are more rows than can be displayed in the available height).

That makes me think the issue may be related to the hover-expanding scrollbars the interface draws.

Like, maybe something is using the _widget_ height to make decisions about how many rows to draw, but the _usable_ height (without needing to scroll) is actually the widget height **minus** the height of the horizontal scrollbar when expanded, with the expectation that the area immediately under the scrollbar will be kept empty or taken up by a blank row. It _is_ awfully hard to click anywhere in the last row of a table with a horizontal scrollbar, since it can hide **completely** behind the scrollbar when it's expanded by hovering the mouse over it. The usual solution to that is to keep a blank row (or at least a spacer) at the very bottom of any table wider than the viewport, so that the last _active_ row can always be scrolled up above the horizontal scrollbar. But I notice BiglyBT tables don't do that.

Perhaps SWT _is_ trying to allow for that extra space at the bottom of the table. Could be that BiglyBT is querying and filling the entire **widget** height (including the space behind the horizontal scrollbar that it shouldn't be drawing into), instead of some "table height" that would indicate how much height it actually has to work with, with the expanded height of the horizontal-scrollbar subtracted out when present?

Kind of a wild theory, but it _would_ fit the facts at hand.

Hrm... except it still wouldn't explain why tables that are **taller** than the viewport don't get any extra space tacked onto the bottom of them. So, maybe I'm totally off base.
