### ISSUE TITLE
Version Reversion

### ISSUE THREAD

**Issue by muffinbane** [BiglySoftware/BiglyBT#2967]
The latest update has borked both bigly and my pc; I've never before seen an app that could drive my ryzen 9 to 80% CPU utilization, it's slower than molasses, spending most of its time spinning-wheel mouse pointer, and everything else in my PC is staggering as well.

I need to revert to an earlier version, but haven't been able to find a binary, only the stub installer. Everything I try seeks to force me to the current version that's broken.

Please. WHERE can I find an earlier version, eg 3.3?

Ryzen 9 3900, win 7 pro, 96gb ram.

Thanks.

**Comment by Havokdan** [comment]
https://github.com/BiglySoftware/BiglyBT/releases ?

**Comment by muffinbane** [comment]
Ok, I reverted to 3.3; it's behaving just a little better, but still burning 75% CPU, and UI is severely lagged. :(

**Comment by Havokdan** [comment]
Perhaps there is another factor involved, an update, java version, let's wait for the developer to show up, but it would be good for you to create a debug file and other information you can to help him detect or reproduce the problem.

**Comment by muffinbane** [comment]
I retract the comment about 75% CPU; it appears 3.3 didn't install on the first try, perhaps a dialog box manifested behind another window or something like that. After a reboot, I got prompts that suggested that 3.3 was THEN installing.

And now I'm running normally.

I'll still have to wonder when I dare permit an update, lest this recur.

**Comment by casnewydd** [comment]
Since this update, despite all my settings being the same, my d/load speed won't go above 4.5MB/s.  I'm going to try a reversion also.

**Comment by parg** [comment]
Maybe try https://github.com/BiglySoftware/BiglyBT/wiki/Diagnostics
