### ISSUE TITLE
can't update the app (fedora linux)

### ISSUE THREAD

**Issue by legacychimera247** [BiglySoftware/BiglyBT#2970]
hello, the app is working perfectly fine but seems i can't update it

yesterday i tried updating from 3.1 to latest 3.4 but with no result at all, also tried joining the beta program but that didn't work either

every time the update is complaining about not being able to update the plugins list, so i updated by manually downloading latest version from biglybt site and installing that over the old one

tried also doing a clean reinstall but had no luck at all, even a clean reinstall can't check for updates

this is the error i get
![image](https://github.com/BiglySoftware/BiglyBT/assets/22254556/01bac02a-1c4e-476f-9c71-d64d31661871)
for the record, i am on fedora workstation 38 and these are my system specs
`Java 17.0.7 (64 bit)
  Red Hat, Inc.
/usr/lib/jvm/java-17-openjdk-17.0.7.0.7-5.fc38.x86_64

SWT v4942r22, gtk/3.24.37, zoom=100, dpi=96
Linux v6.2.15-300.fc38.x86_64, amd64 (64 bit)
B3.4.0.0/4 az3`

**Comment by parg** [comment]
Disable Options->Interface->Start: Update anonymously ?

**Comment by legacychimera247** [comment]
i wonder why it was checked, especially since i was still stuck at 3.1 which was released almost 4 months ago

still, that solved my issue, despite both plugins being installed...

thank you...
