### ISSUE TITLE
return the older progress bar look

### ISSUE THREAD

**Issue by legacychimera247** [BiglySoftware/BiglyBT#2972]
stupid request, since i updated to latest version i saw progress bar increased in thickness which is good (really), but was wondering if there was a way to have the old 3d gummy look back (the like rounded one), cause it was in my opinion nicer than the edging new one

on a secondary note, was thinking that biglybt has been my default torrent app since it had a (very beautiful) black interface and was called azureus, that's what happen when you release very good software i guess :)

**Comment by parg** [comment]
Been gone for a few releases - see https://github.com/BiglySoftware/BiglyBT/pull/2647

Perhaps you could comment on that. I quite like the non-3D look myself!

**Comment by legacychimera247** [comment]
yeah well, not bad i must say, so i've enabled that, i guess we can close this one...
