### ISSUE TITLE
3.4.0.0 Install Issue

### ISSUE THREAD

**Issue by Soldier1st** [BiglySoftware/BiglyBT#2974]
When Trying to update to the new 3.4.0.0 version, the installer closes and generates a text file named BiglyBT_Installer64_error and the error in the text file says: Error: BiglyBT\jre\bin\fontmanager.dll: Can't find dependent libraries
The JRE is not fully functional on this system.

I do not have any JRE installed as the BiglyBT 3.3.0.0 installer came with the jre. The previous version installed and worked correctly.

* OS Windows 10 x64 Build 22H2
* BiglyBT Version Number 3.3.0.0

**Comment by parg** [comment]
Please try deleting the folder

BiglyBT\jre

and then re-install, hopefully that'll fix things.

**Comment by Soldier1st** [comment]
Deleting that folder fixed the issue. Thanks.

**Comment by parg** [comment]
great :)
