### ISSUE TITLE
"Media Server: play on renderer" is using wrong ip address

### ISSUE THREAD

**Issue by drelephant** [BiglySoftware/BiglyBT#2985]
Java 11.0.19 (64 bit)
Ubuntu
/usr/lib/jvm/java-11-openjdk-amd64

SWT v4942r22, gtk/3.22.30, zoom=100, dpi=96
Linux v4.15.0-211-generic, amd64 (64 bit)
B3.4.0.1_B05/4 az3

When I try to play a file using `Right Click-Media Server-MediaServer: play on renderer Kodi`, kodi gives an error that it can't play the file.

Looking through the kodi log, I discovered that it is trying to play using an ip of a docker network interface, and not the internal LAN interface that BiglyBT is bound to in `Options-Connection-Advanced Network Settings-Bind to local IP address or interface`.

How can I get BiglyBT to send the correct internal IP to kodi when I try to play on that renderer??

**Comment by parg** [comment]
Dunno, what do you have for Options->Plugins->Media Server: Apply interface bindings from BiglyBT connection configuration ?

**Comment by drelephant** [comment]
![image](https://github.com/BiglySoftware/BiglyBT/assets/6712036/e4cd8f82-1625-4593-8bcf-71dc3c17b922)

![image](https://github.com/BiglySoftware/BiglyBT/assets/6712036/c2b23946-52d3-46a6-99e5-40c384d5dfdc)

That ip is a docker interface, not the same interface that biglybt is set to listen on.

Not sure why, but about half the time it seems to detect kodi on that interface and half the time on the correct one. Even though the docker stuff is always running.

When it's on the docker one, `play on renderer Kodi` doesn't work.

Any ideas??

**Comment by drelephant** [comment]
Today:

![image](https://github.com/BiglySoftware/BiglyBT/assets/6712036/041f7b76-3aae-4116-82e7-5102dd3343b6)

Not sure if this is a kodi problem or a biglybt problem.

**Comment by parg** [comment]
How about this setting:

Options->Plugins->UPnP: Selected interfaces (';' separated, e.g. eth0;eth1) [blank: all]

? Perhaps if you put 10.0.x.y in there it'll fix things
