### ISSUE TITLE
QoL suggestion: Have checks continue after pauses for losing binding

### ISSUE THREAD

**Issue by dizzyMongoose** [BiglySoftware/BiglyBT#2994]
* Windows 11 Pro Version 22H2
* BiglyBT Version 3.4.0.0
 
Suggestion for how two options interact: I have the options "Re-check pieces when download is done" and the "Enforce IP bindings..." and "Pause downloads on loss of binding..." options on so I make sure BiglyBT only downloads with my VPN. However, it looks like the action to pause for binding takes precedence over the check action, so in the case where I finish a download and my newly finished download is Checking & Seeding, if I disconnect from my VPN, it will stop the check and pause the torrent, meaning I need to restart the check from scratch or wait until the check is done before disconnecting my VPN. It would be nice in this situation to instead have the check continue as a standard no-seeding check (since you still don't want any transmission without the binding) and then have it pause when the check is completed.

**Comment by parg** [comment]
Seems like a good idea. Please join the Beta Program and test the latest build, 3.4.0.1_B07 - it should effectively do what you propose. It does this by preventing all peer connections until the recheck is complete and should then pause it.

See https://github.com/BiglySoftware/BiglyBT/wiki/Beta-Program
