### ISSUE TITLE
Subscriptions do not automatically update at startup

### ISSUE THREAD

**Issue by LuvBiglyBT** [BiglySoftware/BiglyBT#2996]
For many years I have been used to subs automatically updating when I start the BiglyBT.  After the last major update (3.4.0.0) it no longer happens and I have to manually update them.  Is this a change or is it a bug? I have tried to find an option to restore, but nothing has been found in the options list.

Win 11
3.4.0.0
Do not know what a *nix: desktop Environment is

Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B3.4.0.0/4 az3

* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment

**Comment by parg** [comment]
No change AFAIK. Check the Subscriptions_1/2.log files in the logs folder, it shows stuff about the update schedule

**Comment by LuvBiglyBT** [comment]
Sorry to bother you parg, but why for over 15 years have they all automatically updated on start up of the program, but have only stopped doing that in the last month?
________________________________

**Comment by parg** [comment]
Did you check tjhe log? They have never automatically updated on startup, they have a schedule based on when the RSS feed reports it's update frequency is.

**Comment by LuvBiglyBT** [comment]
Parg,Subscriptions_1 0r 2.log does not exist anywhere on my computer.  I run a dual boot system and it DOES show up on my second OS SSD. LuvBiglyBT Sent from Mail for Windows From: pargSent: Friday, June 30, 2023 1:36 PMTo: BiglySoftware/BiglyBTCc: LuvBiglyBT; AuthorSubject: Re: [BiglySoftware/BiglyBT] Subscriptions do not automatically update at startup (Issue #2996) No change AFAIK. Check the Subscriptions_1/2.log files in the logs folder, it shows stuff about the update schedule—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by LuvBiglyBT** [comment]
Ok, Parg.  Installed the latest Beta and now I have a Subscriptions_1.log.  Opening it, I see subscriptions that I deleted years ago and I do not know what I am looking for as far as updates. Is it possible that I mistook updates that happened after shutting the program down the night before and it updating because I had gone past the 120 minute update by having my computer off for the night?  Did I mistake that for auto updating in the morning? Sent from Mail for Windows From: pargSent: Monday, July 3, 2023 10:38 AMTo: BiglySoftware/BiglyBTCc: LuvBiglyBT; AuthorSubject: Re: [BiglySoftware/BiglyBT] Subscriptions do not automatically update at startup (Issue #2996) Maybe that log only gets written when you're running a beta version, try that?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by parg** [comment]
Click on the Subscriptions header in the sidebar and check the list of subscriptions shown in the table on the right. It is possible that you thought you had deleted a Subscription by hitting the "x" by it in the sidebar - this doesn't delete it it just removes it from the sidebar view. You have to right-click on it and select "Delete" to actually delete it.

Subscriptions have an absolute "next update" date+time (based on their update frequency). If you close BiglyBT, wait a week and then open BiglyBT again then all of the Subscriptions with a "next update" in the past week will update on startup.
