### ISSUE TITLE
[Performance improvement] Prevent computer from sleeping

### ISSUE THREAD

**Issue by user8446** [BiglySoftware/BiglyBT#300]
Under options>startup & shutdown there are only 2 options to keep the computer from sleeping: "downloading" and "first priority seeding is active". It would be a performance improvement to have additional options such as when there are active torrents, when seeding at all, etc. Some trackers will flag you as a hit-and-run if you don't seed for a minimum amount of time and BiglyBT will allow the computer to sleep which obviously disconnects.
Thank you

**Comment by parg** [comment]
How about setting a minimum seeding time for first-priority seeds via Tools->Options->Queue->Seeding->First Priority?

**Comment by user8446** [comment]
parg - You're right, that in combo w/ prevent computer from sleeping when first priority is active will achieve that. Thanks!
