### ISSUE TITLE
Keeping RARBG’s torrents alive by adding new trackers to them

### ISSUE THREAD

**Issue by hollownights** [BiglySoftware/BiglyBT#3002]
With the close down of RARBG’s trackers, a bunch of good content is on the way to just disappear: RARBG only added their own trackers to their torrents, so now that they are offline those torrents are relying solely on DHT, which just doesn’t works great. So, as a way to keep those torrents alive, I propose:

1) When a new torrent is being added, detect if it uses RARBG trackers. If yes, add new trackers to it;
2) When opening BiglyBT for the first time after an update, offer to check the user’s torrents library for torrents that use RARG’s trackers and add new trackers to them. This feature should also be available as an option in the settings (“Scan torrents and add trackers...”).

As for which trackers to add, check ngosang’s “[trackers_best](https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_best.txt)” list of [public trackers](https://github.com/ngosang/trackerslist).

**Comment by parg** [comment]
BiglyBT is content agnostic, it would be inappropriate to add such functionality to it.

As an aside you can configure it to add trackers from a list based on criteria such as existing trackers by using Tags and Tracker Templates. Check out the wiki.

**Comment by hollownights** [comment]
@parg Well, a measure like that is content agnostic, isn't it? You would looking at torrents, not at their content. Besides that, you would just be making sure that the things justify the usage of a torrent client are still working. Content agnostic, but not protocol agnostic, if you will ;)

But good to know about such functionality!
