### ISSUE TITLE
app can't detect vlc player

### ISSUE THREAD

**Issue by legacychimera247** [BiglySoftware/BiglyBT#3003]
hello, wanted to trying out the stream features but it does not work, as biglybt is always complaining it can't find the vlc player, despite being correctly installed

now, why on linux (i'm on fedora 38) i can only use vlc and not the embedded player as in windows?and why vlc only and not for example, totem (gnome videos) or clapper?

by the way, i am on fedora 38 with latest biglybt, just for info...

**Comment by parg** [comment]
Right-click the file in BiglyBT, select "Media Server->Copy Stream URI To Clipboard" and paste into your favourite player.

**Comment by legacychimera247** [comment]
oh that's absolutely wonderful, thank you
