### ISSUE TITLE
Feature request  " auto tag " when i download torent file then the program can set tag for me auto

### ISSUE THREAD

**Issue by maloadjav** [BiglySoftware/BiglyBT#3004]
just like what is in  bittorrent  . they called it autolabel

when i download the torerent file  then  the program can check the file name and then make autotag  for me

thank

**Comment by parg** [comment]
There's https://github.com/BiglySoftware/BiglyBT/wiki/Tags#user-content-AutoTagging

Depends what you want to match on - you can also use Tag Constraints to match based on file name.

**Comment by maloadjav** [comment]
okay .

i have learn it from here


*  To auto-tag based on part of the filename, just add a "contains" tag constraint. In the tag constraints section, type:

contains(name,"AnimeChickName")

*


but  if  i want to  add  tag  to    2  file   ,,   1  first   have  "  juq  " in thier  name 
                                                                   2  the second file  have    " wot" in their  name 

and i want  2 of them in the same " tag " 

so  how do i  need to   write in the contain  ???

    i test  so  many  line 

    contains(name,"juq", wot )   or  contains(  name  " juq, wot ")

or something else  ??  

 can you guide  a little bit ??

**Comment by parg** [comment]
You can also use regular expressions with the "matches" operator. For example

`matches( name, "juq|wot")`

Regular expressions are quite powerful, see https://github.com/BiglySoftware/BiglyBT/wiki/Regular-Expressions

**Comment by maloadjav** [comment]
thank you so much
