### ISSUE TITLE
[UI] Torrent size is collapsed when Size column is too wide (MacOS)

### ISSUE THREAD

**Issue by superbonaci** [BiglySoftware/BiglyBT#3010]
System:
```
Java 1.8.0_292 (64 bit)
  Azul Systems, Inc.
/Applications/BiglyBT/.install4j/jre.bundle/Contents/Home

SWT v4944r26, cocoa, zoom=200, dpi=72
Mac OS X v13.4.1, aarch64 (64 bit)
B3.4.0.0/4 az3
```
Displayed size is `5.11 ...` where there's enough room to display the full value:

<img width="1173" alt="bitly-no-scroll-bars" src="https://github.com/BiglySoftware/BiglyBT/assets/8339596/b16abf91-7d28-4c9e-b490-6ecf277b9450">

Vuze 5.7.7.0 displays correctly the full value with same configuration (different torrent size because is another download):

![vuze-always-bars](https://github.com/BiglySoftware/BiglyBT/assets/8339596/88741851-7890-4e67-9d34-8c2787878010)

**Comment by parg** [comment]
Please try a newer Java - see https://github.com/BiglySoftware/BiglyBT/issues/3009
