### ISSUE TITLE
"Move on removal" is not enabled.

### ISSUE THREAD

**Issue by Morpjeus** [BiglySoftware/BiglyBT#3017]
I have noticed that when Deleting or Removing a Torrent File and the associated Torrent, the Torrent re-emerges in the Download section. This happens regardless of whether the Torrent is deleted from the Completed Torrents or Incomplete Torrents section.
I have checked the Log file and I am seeing "Move on removal" is not enabled.

Yet this option does not appear in the Options.
I have set the options to move the file and torrent to a Torrent Complete Folder, the file is moved correctly but the Torrent re-emerges even though it appears in my "Recycle Bin"
I have also removed the Torrent from the Recycle Bin and it still re-emerges in the Download section. I normally have to repeat the process multiple times before BiglyBT deletes the Torrent and does not put it back into the Incomplete Download section.

Any pointers on how I can fix this?

**Comment by parg** [comment]
Are you removing the download from BiglyBT by using the "delete" icon in the toolbar or right-clicking on the download and selecting "Delete"?

If you remove the file(s) directly from the download location then BiglyBT will assume that the data for the download has been lost and prepare to re-download it.
