### ISSUE TITLE
Make it easier to bind to a running VPN

### ISSUE THREAD

**Issue by feldegast** [BiglySoftware/BiglyBT#3020]
on  Windows when I go to bind my connection to my VPN I get a massive list of interfaces making it hard even to find my VPN interface, most interfaces are for virtual devices from virtual machine apps that are not even running, see the list below
having a quick way to refresh the list below, and eliminate adaptors without IP addresses would be a big help in finding the correct one to bind to
additionally being able to ping addresses to eliminate connections that have no access to the internet would further reduce the list below...

	net0		(Microsoft 6to4 Adapter)
	lo		(Software Loopback Interface 1)
		lo[0]	127.0.0.1
	net4		(WAN Miniport (SSTP))
	net3		(WAN Miniport (IKEv2))
	net2		(Microsoft IP-HTTPS Platform Adapter)
	net1		(TAP-Windows Adapter V9)
		net1[0]	172.22.63.67
	net8		(TAP-Windows Adapter V9-WFP Native MAC Layer LightWeight Filter-0000)
	wlan9		(Intel(R) Wireless-AC 9560 160MHz-COMODO Internet Security Firewall Driver-0000)
	net7		(WAN Miniport (PPTP))
	wlan8		(Intel(R) Wireless-AC 9560 160MHz-VirtualBox NDIS Light-Weight Filter-0000)
	net6		(WAN Miniport (L2TP))
	wlan7		(Intel(R) Wireless-AC 9560 160MHz-Npcap Packet Driver (NPCAP)-0000)
	net5		(Microsoft Teredo Tunneling Adapter)
	wlan6		(Intel(R) Wireless-AC 9560 160MHz-Fortinet NDIS 6.0 LightWeight Filter-0000)
	wlan5		(Intel(R) Wireless-AC 9560 160MHz-Native WiFi Filter Driver-0000)
	wlan4		(Intel(R) Wireless-AC 9560 160MHz-Virtual WiFi Filter Driver-0000)
	wlan3		(Intel(R) Wireless-AC 9560 160MHz-WFP Native MAC Layer LightWeight Filter-0000)
	wlan2		(Microsoft Wi-Fi Direct Virtual Adapter #2)
	net9		(TAP-Windows Adapter V9-Fortinet NDIS 6.0 LightWeight Filter-0000)
	wlan1		(Intel(R) Wireless-AC 9560 160MHz)
	eth8		(WAN Miniport (IP))
	wlan0		(Microsoft Wi-Fi Direct Virtual Adapter)
	eth7		(VMware Virtual Ethernet Adapter for VMnet8)
	eth6		(VMware Virtual Ethernet Adapter for VMnet1)
	eth5		(Realtek PCIe GbE Family Controller)
		eth5[0]	192.168.20.2
	eth4		(Fortinet SSL VPN Virtual Ethernet Adapter)
	eth3		(WAN Miniport (IPv6))
	eth2		(Microsoft Kernel Debug Network Adapter)
	eth1		(Fortinet Virtual Ethernet Adapter (NDIS 6.30))
	eth0		(Bluetooth Device (Personal Area Network))
	wlan20		(Microsoft Wi-Fi Direct Virtual Adapter #2-WFP Native MAC Layer LightWeight Filter-0000)
	wlan21		(Microsoft Wi-Fi Direct Virtual Adapter #2-Native WiFi Filter Driver-0000)
	wlan22		(Microsoft Wi-Fi Direct Virtual Adapter #2-Fortinet NDIS 6.0 LightWeight Filter-0000)
	wlan23		(Microsoft Wi-Fi Direct Virtual Adapter #2-Npcap Packet Driver (NPCAP)-0000)
	wlan24		(Microsoft Wi-Fi Direct Virtual Adapter #2-VirtualBox NDIS Light-Weight Filter-0000)
	wlan25		(Microsoft Wi-Fi Direct Virtual Adapter #2-COMODO Internet Security Firewall Driver-0000)
	wlan26		(Microsoft Wi-Fi Direct Virtual Adapter #2-QoS Packet Scheduler-0000)
	wlan27		(Microsoft Wi-Fi Direct Virtual Adapter #2-WFP 802.3 MAC Layer LightWeight Filter-0000)
	eth15		(Realtek PCIe GbE Family Controller-COMODO Internet Security Firewall Driver-0000)
	eth14		(Realtek PCIe GbE Family Controller-VirtualBox NDIS Light-Weight Filter-0000)
	eth17		(Realtek PCIe GbE Family Controller-WFP 802.3 MAC Layer LightWeight Filter-0000)
	eth16		(Realtek PCIe GbE Family Controller-QoS Packet Scheduler-0000)
	eth11		(Realtek PCIe GbE Family Controller-WFP Native MAC Layer LightWeight Filter-0000)
	eth10		(WAN Miniport (Network Monitor))
	net14		(TAP-Windows Adapter V9-WFP 802.3 MAC Layer LightWeight Filter-0000)
	eth13		(Realtek PCIe GbE Family Controller-Npcap Packet Driver (NPCAP)-0000)
	eth12		(Realtek PCIe GbE Family Controller-Fortinet NDIS 6.0 LightWeight Filter-0000)
	net11		(TAP-Windows Adapter V9-VirtualBox NDIS Light-Weight Filter-0000)
	net10		(TAP-Windows Adapter V9-Npcap Packet Driver (NPCAP)-0000)
	net13		(TAP-Windows Adapter V9-QoS Packet Scheduler-0000)
	net12		(TAP-Windows Adapter V9-COMODO Internet Security Firewall Driver-0000)
	eth19		(Bluetooth Device (Personal Area Network)-COMODO Internet Security Firewall Driver-0000)
	eth18		(Bluetooth Device (Personal Area Network)-Npcap Packet Driver (NPCAP)-0000)
	wlan10		(Intel(R) Wireless-AC 9560 160MHz-QoS Packet Scheduler-0000)
	wlan11		(Intel(R) Wireless-AC 9560 160MHz-WFP 802.3 MAC Layer LightWeight Filter-0000)
	eth20		(WAN Miniport (IP)-WFP Native MAC Layer LightWeight Filter-0000)
	wlan12		(Microsoft Wi-Fi Direct Virtual Adapter-WFP Native MAC Layer LightWeight Filter-0000)
	wlan13		(Microsoft Wi-Fi Direct Virtual Adapter-Native WiFi Filter Driver-0000)
	wlan14		(Microsoft Wi-Fi Direct Virtual Adapter-Fortinet NDIS 6.0 LightWeight Filter-0000)
	wlan15		(Microsoft Wi-Fi Direct Virtual Adapter-Npcap Packet Driver (NPCAP)-0000)
	wlan16		(Microsoft Wi-Fi Direct Virtual Adapter-VirtualBox NDIS Light-Weight Filter-0000)
	wlan17		(Microsoft Wi-Fi Direct Virtual Adapter-COMODO Internet Security Firewall Driver-0000)
	eth26		(WAN Miniport (IPv6)-Fortinet NDIS 6.0 LightWeight Filter-0000)
	wlan18		(Microsoft Wi-Fi Direct Virtual Adapter-QoS Packet Scheduler-0000)
	eth25		(WAN Miniport (IPv6)-WFP Native MAC Layer LightWeight Filter-0000)
	wlan19		(Microsoft Wi-Fi Direct Virtual Adapter-WFP 802.3 MAC Layer LightWeight Filter-0000)
	eth28		(WAN Miniport (Network Monitor)-Fortinet NDIS 6.0 LightWeight Filter-0000)
	eth27		(WAN Miniport (Network Monitor)-WFP Native MAC Layer LightWeight Filter-0000)
	eth22		(WAN Miniport (IP)-Npcap Packet Driver (NPCAP)-0000)
	eth21		(WAN Miniport (IP)-Fortinet NDIS 6.0 LightWeight Filter-0000)
	eth24		(WAN Miniport (IP)-QoS Packet Scheduler-0000)
	eth23		(WAN Miniport (IP)-COMODO Internet Security Firewall Driver-0000)
	eth29		(WAN Miniport (IPv6)-Npcap Packet Driver (NPCAP)-0000)
	eth9		(VirtualBox Host-Only Ethernet Adapter)
	eth31		(WAN Miniport (IPv6)-COMODO Internet Security Firewall Driver-0000)
	eth30		(WAN Miniport (Network Monitor)-Npcap Packet Driver (NPCAP)-0000)
	ppp0		(WAN Miniport (PPPOE))
	ppp1		(PPPoP WAN Adapter)
	eth33		(WAN Miniport (Network Monitor)-COMODO Internet Security Firewall Driver-0000)
	eth32		(WAN Miniport (IPv6)-QoS Packet Scheduler-0000)
	eth34		(WAN Miniport (Network Monitor)-QoS Packet Scheduler-0000)

**Comment by parg** [comment]
Are you running version 3.4? If not then update.

**Comment by parg** [comment]
If you are then check the option below that list that says "only show interfaces with addresses"

**Comment by feldegast** [comment]
i am, when i enable that option my list becomes:
	lo		(Software Loopback Interface 1)
		lo[0]	127.0.0.1
	net1		(TAP-Windows Adapter V9)
		net1[0]	172.22.63.67
	eth5		(Realtek PCIe GbE Family Controller)
		eth5[0]	192.168.20.2

none of these match the IP address of my VPN which starts with 45
