### ISSUE TITLE
Folder icon data corrupt

### ISSUE THREAD

**Issue by Sagmegar** [BiglySoftware/BiglyBT#3022]
MacOS Monterey
BiglyBT 3.4.0.0

![image](https://github.com/BiglySoftware/BiglyBT/assets/50022359/92a3bf82-29d5-4766-bb54-a853f85dd4ad)

**Comment by Sagmegar** [comment]
Hi ~

Re-installing has no effect.

Could the installer be the cause of this ?

Regards.

**Comment by o0nd7ots** [comment]
I do not know how MacOS works. Does it get the icon from a certain file? If so, could you open it and see if it is corrupted?

It is possible that it is the OS's fault and not the program's.

**Comment by ferdnyc** [comment]
@Sagmegar Which installer did you use? There are (at least) four, for macOS. From the official download page at https://www.biglybt.com/download/, you can get: 

1. Universal
2. Intel
3. Apple Silicon
4. (I assume not this one) Legacy OS X 10.7+

...But I assume it's also possible to install via other channels, as well.

**Comment by ferdnyc** [comment]
Oh, nope, I see it too. After booting up my Hackintosh VM running 10.15.7 (the only Mac I have access to), and installing BiglyBT using the Universal installer download from the link in my previous comment, I get...

![image](https://github.com/BiglySoftware/BiglyBT/assets/538020/c43622d9-e138-479b-ab72-6c36586c5092)

**Comment by ferdnyc** [comment]
Not sure _why_, as my Linux system can display the same icon extracted from that installer (at internal path 
`/BiglyBT Installer.app/Contents/Resources/app/user/biglybt-folder.icns`) just fine.

![image](https://github.com/BiglySoftware/BiglyBT/assets/538020/6903b1de-7536-441c-b256-25292cd19441)

Unless maybe Install4J is somehow corrupting the file on install.

**Comment by ferdnyc** [comment]
Well, that just makes NO sense! Looking inside the installer, _on macOS_:

![image](https://github.com/BiglySoftware/BiglyBT/assets/538020/153e430e-6379-4ada-b218-0d9eb6476265)

...Why would the icon _preview_ be uncorrupted, but display corrupted in the Finder?!?

**Comment by Sagmegar** [comment]
Sorry, I don’t remember. Probably Intel.

**Comment by ferdnyc** [comment]
Aha! Mystery solved. The full contacts sheet for that `.icns` file's contents, according to macOS Preview:

![image](https://github.com/BiglySoftware/BiglyBT/assets/538020/ab6dfeea-2b5e-47d3-9bd7-86f6cfc63da6)

**Comment by ferdnyc** [comment]
Interestingly, though, `iconutil -c iconset biglyby-folder.icns` produces a `biglybt-folder.iconset` directory containing five perfectly-valid, uncorrupted PNG files.

**Comment by ferdnyc** [comment]
@parg Here's the repaired `biglybt-folder.icns` file (the result of that double-conversion operation in my last comment), since the one being included in the macOS installers does indeed appear to be corrupt.

[biglybt-folder.icns.zip](https://github.com/BiglySoftware/BiglyBT/files/12385280/biglybt-folder.icns.zip)

**Comment by parg** [comment]
I'll ping @TuxPaper, he's the installer guru - thanks!

**Comment by TuxPaper** [comment]
I've added the uncorrupted icn to the installer repo.  Next installer build will get it.  Thanks @ferdnyc

**Comment by ferdnyc** [comment]
Hmm, I guess since we're still only on beta builds of 3.4.0.1 so far, this is still pending a release-release?

**Comment by TuxPaper** [comment]
Yes, very soon.  We've been on hold while we went through the hoops of getting a new Code Signing Certificate

**Comment by ferdnyc** [comment]
Fixed in 3.5.0.0! \o/
