### ISSUE TITLE
Inverted right-click menu

### ISSUE THREAD

**Issue by BGFHA** [BiglySoftware/BiglyBT#3024]
* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment

System:
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B3.4.0.0/4 az3

BiglyBT in full screen mode.

In the Library view, if I right-click on an item towards the top of the list, I get the expected menu, displayed below the selected item
![BiglyBT Normal Menu](https://github.com/BiglySoftware/BiglyBT/assets/52361038/34738a63-024c-4182-8c97-7a5340c29ba3)

If I right-click on an item at the bottom of the list, where the menu would go beyond the bottom of the application window, rather than the menu being displayed at a higher location, as it would be e.g. in Windows Explorer, it is displayed inverted at a higher location
![BiglyBT Inverted Menu](https://github.com/BiglySoftware/BiglyBT/assets/52361038/76f66cd9-7770-4e17-8161-207bf1476ac3)

Is this normal behaviour?
Is there a setting to have the menu displayed "right way up"?

**Comment by parg** [comment]
That's the way it is built to work.

**Comment by parg** [comment]
BTW, if you double-right-click you'll get the old-style menu that behaves more like a "normal" menu. You can also disable the "fancy" one in the options

**Comment by BGFHA** [comment]
OK, just wanted to check! I'll disable the fancy one. 😀
