### ISSUE TITLE
Biglybt does not show metadata downloads in the Incomplete tag

### ISSUE THREAD

**Issue by Dramaman** [BiglySoftware/BiglyBT#3025]
In this case, I have three metadata downloads.
These are items 1 to 3, but you can see the list number starts at 4.

![image](https://github.com/BiglySoftware/BiglyBT/assets/76974959/98f88d33-7e35-4de0-819d-911517017a7e)
I've noticed this for years, just thought I would comment now :)

* OS and version : Windows 11
* BiglyBT Version Number: 3.4.0.0

**Comment by parg** [comment]
You need to switch to the "detailed list" using (for example) the toolbar icon for it

**Comment by Dramaman** [comment]
Haha, thanks

**Comment by Dramaman** [comment]
Works
