### ISSUE TITLE
Jackett will not allow downloads

### ISSUE THREAD

**Issue by LuvBiglyBT** [BiglySoftware/BiglyBT#3028]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B3.4.0.1_B07/4 az3

Yesterday, all of a sudden, using Jackett will not allow downloads.  No problem with updating the subscriptions, but I get errors upon trying to download.  I have tried restoring to a previous backup with no luck.  If I download the torrent directly from the torrent site (e.g. 1337x) I have no problem.

This is an error I get:

Downloading From:http://127.0.0.1:9117/dl/1337x/?jackett_apikey=akxtyfkx0tndkeno6pipf4wtqki5a1hl&&&&...
Error:Failed to download 'http://127.0.0.1:9117/dl/1337x/?jackett_apikey=***********dkeno6pipf4wtqki5a1hl&path=Q2ZESjhBZGlWRGhYeWM1UGg4VlFaYXprbVRod0FyMm1xMnlSbHNMNjN1RTZZVmpPeXpfNTJ6MEJMWWEyRWtYcTNKbDViMHdHOElxYVZwOWZGekh3aEFDWDlNNG5PY20zX2hpNlJnV1V0U082NGVjc2NOSzlmZFY1ZDkyWk1LSEZhT2Zra2FhMTFvRzhtRmF6NEExcGVyLU1oM1c5c0FjTHR5amFEd0xIekhmVGN3N1hoQmJ3TWJnc3lVV01UTXZXcV9EM1NDVlBRNk9pcGRZdWVBbmQ1cTlMYXp3&file=********.S07E02.720p.WEB.x265-MiNX%5BTGx%5D' to 'F:\Quicken F\torrents\Torrent973187203573255168': <nul

I have truncated the apikey and exact torrent name for security reasons.

Any thoughts?

**Comment by ferdnyc** [comment]
Is Jackett accessible and working normally, if you visit http://127.0.0.1:9117/UI/Dashboard in a browser?

**Comment by LuvBiglyBT** [comment]
Yes, it is activ Sent from Mail for Windows From: Frank DanaSent: Saturday, August 19, 2023 12:56 AMTo: BiglySoftware/BiglyBTCc: LuvBiglyBT; AuthorSubject: Re: [BiglySoftware/BiglyBT] Jackett will not allow downloads (Issue #3028) Is Jackett accessible and working normally, if you visit http://127.0.0.1:9117/UI/Dashboard in a browser?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by ferdnyc** [comment]
@LuvBiglyBT 

> Yes, it is activ 

Since you're responding by email, you probably didn't see my edits to my previous comment...

There's also a "View Logs" button on the Jackett configuration page, which might provide some insights. (See if it's even receiving the download request from BiglyBT, and if so what it's doing with it.)
