### ISSUE TITLE
Super seeding does not work

### ISSUE THREAD

**Issue by brazenvoid** [BiglySoftware/BiglyBT#3031]
Turning on super-seeding stops seeding altogether and Bigly disconnects from all connected peers. Even turning it off, does not revert the behaviour. I have to in addition stop and start the torrent. Shouldn't it like complete current pieces and then start distributing unique ones around?

I am uploading a huge torrent to a private tracker, at 112GB, and I had 10 connected peers, I thought I could optimize seeding of the first copy.

* Windows 10 64-bit Latest
* BiglyBT v3.4

**Comment by brazenvoid** [comment]
So how much time should I rationally wait before I term it not working then?

**Comment by parg** [comment]
Turn on logging to see what's going on - Options->Logging and check Tools->Console

That should show what peer connections are being attempted and what happens to them.

**Comment by parg** [comment]
To be honest superseeding is somewhat over-rated in my opinion. With "normal" seeding any connected peers should generally request the rarest piece from you. If there are a number of rarest pieces then it should select one at random. So the chance of multiple peers requesting the same piece from you is pretty low, especially early on in the seeding process. Once another peer has a piece then any other peers connected to it and you shouldn't request that piece from you either as it is no longer as rare.

Anyway, have a play around.
