### ISSUE TITLE
BiglyBT allocates 'deselected' files as 0 byte placeholders

### ISSUE THREAD

**Issue by Pandoriaantje** [BiglySoftware/BiglyBT#3032]
System:
```
Java 20.0.1 (64 bit)
  Azul Systems, Inc.
C:\Program Files\Zulu\zulu-20

SWT v4956r12, win32, zoom=100, dpi=120
Windows 11 v10.0, amd64 (64 bit)
B3.4.0.0/4 az3
```

When deselecting certain files, as to exclude downloading them when importing a magnet link (or torrent file) BBT insists on creating 0 byte placeholders for the files in the destination directory. Is this by design?\
In the end BBT actually (partially) downloaded the file? Why?

**Comment by parg** [comment]
See https://github.com/BiglySoftware/BiglyBT/wiki/Torrents-and-Files#why-are-files-being-createdallocated-on-disk-when-they-are-deselected
