### ISSUE TITLE
Cannot remove multi-selected trackers from All Trackers

### ISSUE THREAD

**Issue by Zenya393** [BiglySoftware/BiglyBT#3034]
When multi-selecting a group of trackers (17) from All Trackers, the "Remove" option in the right-click menu is grayed out:
![biglybt](https://github.com/BiglySoftware/BiglyBT/assets/125422293/03a89660-2567-4ea1-ad01-a0a49ec593ff)

But I can remove a group of 16 trackers:
![biglybt2](https://github.com/BiglySoftware/BiglyBT/assets/125422293/aebd6bdf-4eb1-4712-83df-43ceafedcc4f)

Java 1.8.0_381 (64 bit)
  Oracle Corporation
c:\program files\java\jre-1.8

SWT v4942r22, win32, zoom=100, dpi=96
Windows 7 v6.1, amd64 (64 bit)
B3.4.0.1_B19/4 az3

**Comment by parg** [comment]
You can only remove a tracker that has no torrents/downloads that use it (enable the "torrent count" column). If you want to remove one that has torrents then you will need to remove that tracker from those torrents first. You can do that by right-clicking and selecting either "remove from current downloads" or "remove from current and future downloads".

**Comment by parg** [comment]
Oh, and there is a "removable" column there too
