### ISSUE TITLE
Assign tags at "Open Torrent(s)" dialog

### ISSUE THREAD

**Issue by Zenya393** [BiglySoftware/BiglyBT#3038]
When adding a magnet via "Open Torrent(s)" dialog, I would like to assign tags, and not need to wait for the "Open Torrent Options" dialog window.

This would be especially useful because sometimes I have to wait a long time for a magnet to find a peer, sometimes never find a peer, and I want to keep organized.

Also would be nice to be able to add trackers to the magnet too.  And select networks.

**Comment by parg** [comment]
When the "metadata download" for the magnet appears in your Library you can assign tags there. Other things not so much.
