### ISSUE TITLE
script

### ISSUE THREAD

**Issue by johnvolfovits** [BiglySoftware/BiglyBT#3039]
* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment
* where can i find wiki for this script
![Untitled1233455](https://github.com/BiglySoftware/BiglyBT/assets/107244103/3dff88a8-ea2c-4748-b98b-9024c7d716c5)

**Comment by parg** [comment]
What are you trying to achieve? Stop posting new issues.

**Comment by johnvolfovits** [comment]
what's that script and where can i find help for it

**Comment by parg** [comment]
That is a script run when a new SUBSCRIPTION RESULT is found, nothing to do with downloads.

An example of its use is https://github.com/BiglySoftware/BiglyBT/wiki/Plugins#invocation-from-subscriptions
