### ISSUE TITLE
BiglyBT disappears if the Explorer crashes and restarts

### ISSUE THREAD

**Issue by LovelyBloom** [BiglySoftware/BiglyBT#3040]
* Windows 11 Insider Preview
* 3.4.0.0

when explorer hangs up or crashes, I'll either have to restart explorer manually or it'll restart itself. but biglybt's interface doesn't come back like the others. you can still access biglybt by running the executable but it's no longer in tray menu or anywhere else, so it could be peering or seeding for hours, on metered internet without you realizing it.

**Comment by Havokdan** [comment]
This happens to me in these scenarios too, I never knew why, the process continues in the task manager, however to reappear the interface you have to click on the application icon, still it disappears minimizing to system tray, just restarting the BiglyBT to normalize. 
Windows 10 x64 and this has happened to me for several versions of BiglyBT, my instincts tell me it's SWT related.

**Comment by LovelyBloom** [comment]
> This happens to me in these scenarios too, I never knew why, the process continues in the task manager, however to reappear the interface you have to click on the application icon, still it disappears minimizing to system tray, just restarting the BiglyBT to normalize. Windows 10 x64 and this has happened to me for several versions of BiglyBT, my instincts tell me it's SWT related.

I remember this happening to me when I was o Windows 10 as well. so we can rule out windows' version about this issue.
so I think you're right the bug must be from the app. yet I'm not sure if it's SWT

**Comment by LovelyBloom** [comment]
how long do think it'll take them to label this as a bug.

**biglybt can't be found if explorer crashes and restarts**

**Comment by parg** [comment]
Who label it as a bug? Clearly it is a Windows bug, Explorer shouldn't crash should it?

**Comment by Havokdan** [comment]
Well, the problem is that BiglyBT is "hidden" after the crash, the other applications reappear normally.

**Comment by parg** [comment]
Nothing's going to be done about this unfortunately.

**Comment by parg** [comment]
(Unless someone else is willing to spend time on it - I'm certainly not)
