### ISSUE TITLE
Error: File ______ occurs more than once... on a a file I'm not downloading.

### ISSUE THREAD

**Issue by crogonint** [BiglySoftware/BiglyBT#3043]
Java 1.8.0_381 (64 bit)
  Oracle Corporation
c:\program files\java\jre-1.8

SWT v4942r22, win32, zoom=100, dpi=96
Windows 7 v6.1, amd64 (64 bit)
B3.4.0.0/4 az3

I can't figure out how to un-squirrel this one. This is what I get for using Windoze, I suppose. Anyway, I grabbed a magnet link for another torrent for swarm merge purposes, but the new torrent is like 487GB bigger than my available hard drive space. SO, I just selected the relevant section to download. NOW.. it's finding "duplicates" (on the move, On The Move, because Windoze is stupid) for files that I'm not even downloading.

Help..?

**Comment by parg** [comment]
Meh :( If you follow the advice of renaming the file in the Files View does the problem go away for that file at least?

**Comment by parg** [comment]
Another possibility - select the download and go to the "Files" sub-tab. 

Sort the files by name

Select all the files (ctrl+a) and right-click to get the "Rename or Retarget (batch)" option

Go through and stick a _1 (or something) on duplicate file names

Note you can copy/paste that text out into something better for amending and paste it bak afterwards

**Comment by parg** [comment]
(I can add a feature to do some kind of auto-rename of duplicates (when ignoring case) but I'd rather not have to...)

**Comment by crogonint** [comment]
Sorry, the ROOT of the problem is that, for this torrent, I only selected about 1/4 of the total files for download. It is a freaking HUGE torrent.  My issue is that BiglyBT is asking me to rename a file that I didn't even include in the files that I want to download. So, I don't even SEE the file(s) that BiglyBT says need to be renamed in my download list. 

I'm not sure how to proceed. I have a handful of ideas on where I MIGHT access these files, but I really can't figure out HOW.

**Comment by parg** [comment]
See https://github.com/BiglySoftware/BiglyBT/wiki/Torrents-and-Files#why-are-files-being-createdallocated-on-disk-when-they-are-deselected for why files other than those you select are being downloaded.

**Comment by crogonint** [comment]
I'm not sure if I'm explaining this correctly. I understand perfectly well how pieces can cause you to download extra files. The PROBLEM is, I am still not seeing THESE files in my download list. The files which are blocking the torrent from ding downloaded are NOT listed on the Files tab for the torrent in question. I cannot rename the file(s) because I cannot see it/them.

**Comment by parg** [comment]
Send me the torrent or its hash if it is public, paul@biglybt.com

**Comment by crogonint** [comment]
Sent! Thanks so much, Paul!

**Comment by parg** [comment]
Beta B22 has a new right-click option in the FilesView - use ctrl+a to select all the files, right-click and select Advanced->Rename->Rename Duplicates...

**Comment by crogonint** [comment]
Hmm.. Haven't tried a beta of BiglyBT in about a decade.. I'll give it a shot. :)

**Comment by crogonint** [comment]
Um.. where do I find the beta?

**Comment by parg** [comment]
Join the beta program - Help menu option

**Comment by crogonint** [comment]
Well.. the function worked. It renamed the duplicate files in the subdirectory that I am downloading. It did NOT rename the file in the subdirectory that I am NOT downloading.
![BiglyBT Error](https://github.com/BiglySoftware/BiglyBT/assets/23371790/2d0a425d-ae55-42da-bf8d-e06530def4f8)

**Comment by crogonint** [comment]
Would it help to mention that it's doing this while it's allocating space? The root folder for this torrent isn't even on my hard drive yet, regardless of what the error says.

**Comment by parg** [comment]
Make sure you don't have "hide files not selected for download" checked in the FilesView - it only renames duplicates within the set of files you select.

**Comment by crogonint** [comment]
I did indeed have that checked. I am an idiot. However, your new function still did not detect the duplicate that was reported in the torrent listing on the table. I assume this is because there are 30,000+ files to sort through? It seemed like it concluded that there were no duplicates entirely too fast.
![BiglyBT Error2](https://github.com/BiglySoftware/BiglyBT/assets/23371790/656d6c62-b50e-41dc-96de-e4601efeaba2)

When I searched for "song", the duplicate file(s) in question were listed right up top. When I ran the Rename Duplicates function while the search function was being used, it DID detect and repair that specific duplicate.

WELL.. I was suspecting that there would be more duplicates detected among those 30,000+ files, but shockingly, there were not! The torrent is currently downloading so I'm happy about that. However, I suspect that your new function needs some sort of ability to deal with huge torrents like this. Perhaps a "% complete" thing to tell us that it's working..?

**Comment by crogonint** [comment]
One final note.. as soon as the download started, I lost access to select those 30,000+ files that I wasn't downloading. My list now only has the 2,541 files in the subdirectory that I selected for downloading. Not sure if that's intended behavior or not.
