### ISSUE TITLE
ΒigLy crash when add a torrent file / Stable to Βeta

### ISSUE THREAD

**Issue by MagnumGR** [BiglySoftware/BiglyBT#3047]
* Linux Fedora 38
* BiglyBT 3.4.0.0 / 3.4.0.1b19
* For *nix: Gnome

Java 1.8.0_382 (64 bit)
  Red Hat, Inc.
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.382.b05-2.fc38.x86_64/jre

SWT v4942r22, gtk/3.24.38, zoom=100, dpi=96
Linux v6.4.6-200.fc38.x86_64, amd64 (64 bit)
B3.4.0.1_B19/4 az3

Suddenly after my vacation ΒigLy crash when adding torrent file or when a try to switch from Stable to Βeta.

I have try different Βigly version and Java JRE (Oracle/ΟpenJDΚ) with the some result....
[debug.zip](https://github.com/BiglySoftware/BiglyBT/files/12577263/debug.zip)

**Comment by parg** [comment]
Try disabling the user of the "internal browser":

Options->Interface->Display [Internal Browser]: Disable all use of the internal browser.

**Comment by parg** [comment]
Yup, unfortunately some SWT library bug, at least it is working!
