### ISSUE TITLE
[NothingBroken] Tag Capability Inquiry / How-To

### ISSUE THREAD

**Issue by CTImundi** [BiglySoftware/BiglyBT#3048]
* OS and version
Windows 11 Professional 22H2.22621.2066
* BiglyBT Version Number: 
BiglyBT 3.4.0.0
* For *nix: Desktop Environment

Is it possible to automatically order torrents by size (ascending) and move them to the bottom of the over all queue for a **specific tag only**?

The goal is to have all other D/Ls run before the tagged ones D/L in order of ascending size.
Any newly added/imported  D/Ls would automatically queue before the tagged ones to D/L.

I've tried everything I could think of  based on what's documented @https://github.com/BiglySoftware/BiglyBT/wiki/Tags

**Comment by parg** [comment]
How about two Tags:

Tag1, called "YYYY" for example, that you use to assign to the torrents you want at the bottom

Tag2 with constraint

`!isComplete() &&  hasTag( "YYYY" ) ?setTagSort( size )  : setTagSort(0)`

and with the "Automatically apply sort periodically [seconds; 0:disabled]" option set to some short period.

**Comment by CTImundi** [comment]
Wow. You're fast on responding.

Thanks !! That worked perfectly.

Side note. The quick wiki updates for things you think more users will find useful is 👍.

**Comment by parg** [comment]
Cheers ;)
