### ISSUE TITLE
BiglyBT running super slow after adding Amazon eero PoE Gateway - Blue-Dot next to torrent files

### ISSUE THREAD

**Issue by Stepcraft** [BiglySoftware/BiglyBT#3050]
I've used the Amazon eero Pro 6 Mesh with 2 nodes hardwired for about 3 years and everything has worked flawlessly, except they're only capable of 1G internet (I pay for 1.2G.) I was getting around 925Mbps doing online speed tests. I finally decided to add an Amazon eero PoE Gateway because it has 8 2.5G & 2 10G ports. Now I'm getting online speed tests of 1192Mbps (29% increase as expected.) So my new setup is the Amazon eero PoE Gateway with the 2 eero Pro 6 nodes and the modem plugged into the 2.5G ports and my iMac and NAS in the 10G ports. Everything is hardwired.

My problem is after adding the eero PoE Gateway, my BiglyBT transfer speeds have dropped way down, and all the torrent files have a Blue-Dot next to them that says "Means that the tracker is ok, you're connected to peers, but you don't have any remote connection. You may have a NAT problem if your torrents stay on this status all the time." It shows tons of seeds and peers, but it's not connecting to them.

Just to be sure, I tried plugging the modem directly into my computer and BiglyBT was back to super fast speeds. When I run the modem through the eero PoE Gateway, BiglyBT is super slow.

See pictures below.

I hope @parg or someone can help.

**Thank you so much for all your hard work on BiglyBT!**

My specs:
iMac (Retina 5K, 27-inch, 2020) / 128 GB / 3.6 GHz 10-Core Intel Core i9 / macOS Big Sur 11.7.9 (20G1426)
Java 1.8.0_292 (64 bit) / BiglyBT 3.4.0.0

.
![speedtest net - eero Pro 6 Mesh - 925 Mbps](https://github.com/BiglySoftware/BiglyBT/assets/59187451/a53d4897-5b40-4813-9439-efe3e6ef17eb)
Original Amazon eero Pro 6 Mesh 2 nodes (all hardwired) online speed test

.
![speedtest net - eero PoE Gateway and 2 eero Pro 6 Mesh - 1192 Mbps](https://github.com/BiglySoftware/BiglyBT/assets/59187451/99f71137-3d4c-47b4-b94f-1a2296f4f734)
New Amazon eero PoE Gateway and eero Pro 6 Mesh 2 nodes (all hardwired) online speed test

.
![BiglyBT Download - Modem through eero PoE Gateway - 1 min later - blacked out](https://github.com/BiglySoftware/BiglyBT/assets/59187451/d30bbd2b-9373-4e13-8847-bb3c22843f20)
Modem through eero PoE Gateway and eero Pro 6 Mesh 2 nodes (all hardwired). This is 1 minute after starting to download these files. Transfer speed 1.98 MB/s and only connected to 8 total Seeds/Peers. Even 10, 20, 30 minutes later it still will not have connected to a couple more Seeds and Peers.

.
![BiglyBT Download - Modem direct to iMac - 1 min later - blacked out](https://github.com/BiglySoftware/BiglyBT/assets/59187451/29e2ed81-407d-446d-bfdc-03b665cb9fb7)
Modem direct to iMac. This is 1 minute after starting to download these files. Transfer speed 141.35 MB/s and connected to 700+ Seeds/Peers

**Comment by parg** [comment]
Hmmm, hate these kind of hardware related issues as I obviously don't have access to it to test.

When going through the gateway try going to the All Peers view and see if there is anything common regarding the peer connections that are succeeding. I assume they're all outbound connections as you appear to be getting no inbound. Are they all TCP or are there uTP/UDP connections?

**Comment by Stepcraft** [comment]
Here's the All Peers view.

Thanks a lot for your help!!!

![BiglyBT All Peers View](https://github.com/BiglySoftware/BiglyBT/assets/59187451/63e993cc-09dc-4970-a4ee-4389458e0a39)

**Comment by parg** [comment]
Well you have both TCP and UDP outgoing connections, so it isn't protocol specific.

No incoming connections so your gateway setup has introduced NAT problems. Is it all a single network segment? Does the gateway have a firewall?

All connections in that view are via the DHT - are the trackers OK in the Sources subtab?
