### ISSUE TITLE
Tab captions are white text on light background

### ISSUE THREAD

**Issue by Scorg** [BiglySoftware/BiglyBT#3056]
Linux Mint 21.1 Vera (Ubuntu 22.04 jammy)
Cinnamon 5.6.8

Java 19.0.2 (64 bit)
  Private Build
/usr/lib/jvm/java-19-openjdk-amd64

SWT v4956r12, gtk/3.24.33, zoom=100, dpi=96
Linux v6.2.0-32-generic, amd64 (64 bit)
B3.4.0.0/4 az3

See the screenshot: https://imgur.com/a/oO0S9Vw
The captions are pretty much unreadable unless the tab is active. Also notice the colors of maximize/minimize buttons to the right.

**Comment by parg** [comment]
Is that with a system "dark" theme?

There's a few theme settings under Options->Interface->Colour Scheme but they probably won't help.

**Comment by Scorg** [comment]
System theme is light except for taskbar. I am using Mint-Y-Aqua for windows and Mint-Y-Dark-Aqua for desktop/taskbar. Tried switching to a dark theme for windows, and the problematic text remained white (but on a dark background now). 

What I also started to notice is that the text is black for the first second after opening the window first time before it switches to being white.
