### ISSUE TITLE
BiglyBT error following PIA upgrade to v3.5

### ISSUE THREAD

**Issue by WarpoMarxs** [BiglySoftware/BiglyBT#3057]
* OS and version Windows 10 Home ver 2H22 OS 19045.3448
* BiglyBT Version Number
* Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B3.4.0.0/4 az3

The BiglyBT error message that regenerates every time the VPN connection is checked:
![image](https://github.com/BiglySoftware/BiglyBT/assets/145873813/6bc9b061-2570-4d6f-b764-d4c51d10710a)

Please help a relative amateur.

**Comment by TuxPaper** [comment]
PIA 3.5 crashes after I click the connect button on it (The UI doesn't crash, the button just turns green, then back to gray, and the crash report dialog appears).  I'd say this version of PIA is DOA.

You can get the older version at https://www.privateinternetaccess.com/pages/changelog  (Go to v3.3.1 and the dl links are on the right).  After re-installing the old version, PIA worked normally for me.

The PIA subreddit seems  to be full of problems with 3.5, but the PIA devs monitor the threads there, so they are aware of the issues and are hopefully fixing them soon
