### ISSUE TITLE
No "download" under actions in content discovery

### ISSUE THREAD

**Issue by Benu-Athanasia** [BiglySoftware/BiglyBT#306]
As of today (before and after running the update) I'm missing the option to download under actions. The only option is "details."

Anyone know how to fix this?

Mac OS X v10.11.6, x86_64 (64 bit)
B1.4.0.0/4 az3

**Comment by parg** [comment]
If a search result/subscription doesn't contain enough information to directly download the torrent (e.g. a hash, magnet link) then BiglyBT can't display a 'download' link, You would need to go to the details and download from there manually.
