### ISSUE TITLE
WebTorrent java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by DubiousTunic** [BiglySoftware/BiglyBT#3061]
I am getting this error 
[0:02:09] Activating
[0:02:09] Local WebRTC provider
[0:02:09] Plugin failed
java.lang.ExceptionInInitializerError

when i try to download a torrent using webtorrent plugin. the webtorrent seeds and downloads in browser just fine. my java system is 11.

**Comment by parg** [comment]
What OS? Plugin version 1.5.1 seems to work ok on Windows

**Comment by DubiousTunic** [comment]
I fixed the problem by using the shell script installer on Ubuntu instead of apt-get install and plugin 1.5.1.

**Comment by parg** [comment]
Excellent
