### ISSUE TITLE
WebTorrent plugin hanging

### ISSUE THREAD

**Issue by DubiousTunic** [BiglySoftware/BiglyBT#3062]
OS Ubuntu 22.04.2. Plugin version 1.5.1. I can't seem to download using webtorrent internal processor. Tracker says OK. Chrome instance doesn't work either. I am using the internal webtorrent tracker. I sometimes get it to work on local for 5-10 minutes before torrents stop seeding. But sometimes I can't get torrents to seed at all, even right after the client is restarted. Could this be a reconnect issue when my internet is goes out (I'm on shoddy WiFI but when I check the seed using webtorrent in the browser i'm sure i have Internet)? I don't want to use Chromium but when I try Chromium in the console it says failed to create RPC peer connection, too many RPC peer connections, and tracker says DHT backup only. Too many RTC peer connections is also a problem in WebTorrent-desktop, but like I said i'd rather not use Chromium.

**Comment by parg** [comment]
To be honest I have no idea, sorry. I can say that using the Chromium based implementation is really not recommended.

**Comment by parg** [comment]
(for background I wrote the plugin years ago, spent a lot of time twatting around with it, nobody uses it, I don't have time to look into it)
