### ISSUE TITLE
[BUG] Subscription enabled property not honored when Auto-Download is enabled

### ISSUE THREAD

**Issue by gh338** [BiglySoftware/BiglyBT#3063]
* Kubuntu 22.04.3
* BiglyBT 3.4.0.1_B29
* KDE Plasma

[System]
Java 17.0.8.1 (64 bit)
  Private Build
/usr/lib/jvm/java-17-openjdk-amd64

SWT v4956r12, gtk/3.24.33, zoom=100, dpi=96
Linux v5.15.0-1032-realtime, amd64 (64 bit)
B3.4.0.1_B29/4 az3

[BUG]
Subscriptions that have Auto-Download new results enabled are adding downloads even if the subscription is NOT enabled.

cheers

**Comment by parg** [comment]
Thanks, should be fixed next beta (B30)
