### ISSUE TITLE
Incoming stream does not match any known byte pattern: ... 00000000 00100005 ...

### ISSUE THREAD

**Issue by GuillaumeBailey** [BiglySoftware/BiglyBT#3066]
* OSX Ventura 13.5.1
* BiglyBT Version Number 3.4.0.0

I see many lines similar to:
```
[22:27:45.805] {nwman} Incoming stream from [/[redacted]:6887] does not match any known byte pattern: 13426974 546F7272 656E7420 70726F74 6F636F6C 00000000 00100005 9499BFF2 [truncated]
```

That decodes to:
```
0000000  dc3   B   i   t   T   o   r   r   e   n   t  sp   p   r   o   t
0000020    o   c   o   l nul nul nul nul nul dle nul enq  94  99
0000040   81   n  . . .
```

The [protocol](http://www.bittorrent.org/beps/bep_0003.html#:~:text=The%20handshake%20starts%20with%20character%20ninteen%20(decimal)%20followed%20by%20the%20string%20%27BitTorrent%20protocol%27) seems to indicate that this is correct at first.

[After the fixed headers come eight reserved bytes, which are all zero in all current implementations. If you wish to extend the protocol using these bytes, please coordinate with Bram Cohen to make sure all extensions are done compatibly.](http://www.bittorrent.org/beps/bep_0003.html#:~:text=After%20the%20fixed%20headers%20come%20eight%20reserved%20bytes%2C%20which%20are%20all%20zero%20in%20all%20current%20implementations.%20If%20you%20wish%20to%20extend%20the%20protocol%20using%20these%20bytes%2C%20please%20coordinate%20with%20Bram%20Cohen%20to%20make%20sure%20all%20extensions%20are%20done%20compatibly.)

From [here](http://bittorrent.org/beps/bep_0004.html), looks like these defined extensions are set:
```
reserved[5]
0x10  LTEP (Libtorrent Extension Protocol)

reserved[7]
0x01  BitTorrent DHT
...
0x04  suggest, haveall, havenone, reject request, and allow fast extensions
```

Not sure if BiglyBt lacks support for one of these, or we have a race or other error setting the pattern matchers.

**Comment by parg** [comment]
It means an incoming connection has been attempted to a torrent that isn't running (stopped,removed,...)
