### ISSUE TITLE
how to remove some torrent form " tag"  (  tag is grey)

### ISSUE THREAD

**Issue by maloadjav** [BiglySoftware/BiglyBT#3067]
win  10 

i have setting for add  torrents into  " tag "  

but its too good ,,  it add lots of  torrents that i dont want  to add (  because  i dont understand much about it )

anyway  ,,  i have easy way  ,,,,  just  remove  the torrents from the " tag" myself

but how to do it .... the tag always " grey " 

this is my setting for "tag "

![Untitled](https://github.com/BiglySoftware/BiglyBT/assets/85825392/f6e9af32-6377-4e45-8d5e-8dcad5704ef3)
![Untitled2](https://github.com/BiglySoftware/BiglyBT/assets/85825392/0cd88b71-bf6d-4e66-8807-8cf0cbaa1689)

**Comment by parg** [comment]
If you have a tag set up with a constraint (as you do) then addition to it is automatic and normally you can't remove it (as the constraint is still matched so it would just add it back) 

There is a setting called "constraint scope" - https://github.com/BiglySoftware/BiglyBT/wiki/Tags#user-content-Constraint_Scope

If you set this to "new downloads" then new downloads will have the constraint tested but after that you can manually remove things from the Tag

**Comment by maloadjav** [comment]
thank you so much
