### ISSUE TITLE
App name in menubar is wrong in macOS 14.0

### ISSUE THREAD

**Issue by deus0ww** [BiglySoftware/BiglyBT#3070]
<img width="910" alt="Screenshot 2023-10-12 at 00 49 25" src="https://github.com/BiglySoftware/BiglyBT/assets/6702585/ccd42af6-c7df-4254-ba22-e48666e09306">

**Comment by parg** [comment]
Yup, that's a known issue, requires latest SWT to fix and that in turn requires Java 11 whereas BiglyBT currently supports Java 8

**Comment by deus0ww** [comment]
[This issue?](https://github.com/eclipse-platform/eclipse.platform.swt/issues/779)

I'm on Java 21 and SWT 4.29.  I'll try a newer SWT.

**Comment by deus0ww** [comment]
SWT 4.30M1 fixes this issue.
