### ISSUE TITLE
Show Open Torrent Option window when automatically importing torrent file

### ISSUE THREAD

**Issue by Zenya393** [BiglySoftware/BiglyBT#3072]
When automatically importing _file_ torrents, show the "Open Torrent Options" window.

The Open Torrent Option window appears when importing files via manually adding a torrent file.
The Open Torrent Option window appears when importing _magnet_ links via automatic clipboard monitoring.

So I'm asking for automatic file import to show the Open Torren Option window just like it works for all other methods of imports (file, magnet links, automatic, manual).

Or at the very least, provide me the option to display the Open Torrent Options window for a torrent from the main window pane.

Java 1.8.0_381 (64 bit)
  Oracle Corporation
c:\program files\java\jre-1.8

SWT v4942r22, win32, zoom=100, dpi=96
Windows 7 v6.1, amd64 (64 bit)
B3.4.0.1_B32/4 az3

**Comment by parg** [comment]
I assume you're talking about files imported due to your settings for

Options->Files->Torrents: Import new .torrents/.magnets automatically

?

**Comment by parg** [comment]
Beta B33 has a new option to do that, please test
