### ISSUE TITLE
Nothing Downloads

### ISSUE THREAD

**Issue by beybrakers** [BiglySoftware/BiglyBT#3073]
Nothing seems to be downloading, it started a few months ago, but every time I try and download something, nothing happens, I have the brave browser downloaded, and it works on that, but not on biglybt, and I don't know why. 
* Windows 11
* BiglyBT Version 3.4
* For *nix: Desktop Environment

**Comment by parg** [comment]
Have you checked https://github.com/BiglySoftware/BiglyBT/wiki/Downloading ?

**Comment by beybrakers** [comment]
Yes, yes I did, as I said, my downloads work fine when using another torrent platform (the brave browser) with the same torrents, it's just bigly bt that isn't working.

**Comment by parg** [comment]
So given all those possible causes for issues there is nothing untowards? Try testing with

https://download.documentfoundation.org/libreoffice/stable/7.6.2/win/x86_64/LibreOffice_7.6.2_Win_x86-64.msi.torrent

**Comment by beybrakers** [comment]
download is stuck at infinity, has been for the last hour

**Comment by parg** [comment]
Tracker status? Peer status? You really have to make a bit of effort to diagnose the issue because you're giving me nothing to work on...

**Comment by parg** [comment]
Go to the Help menu, select Advanced and then Show Configuration Changes.

Copy/Paste the result into here (check it first to ensure it doesn't have anything in it you don't want to be made public)

**Comment by beybrakers** [comment]
**** Please review the contents of this before submitting it ****

Settings
    AutoSpeed Available=1
    Bind IP=net5
    Default save path=D:\BiglyBT Downloads
    Enforce Bind IP=1
    General_sDefaultTorrent_Directory=D:\BiglyBT Downloads
    LAN Speed Enabled=0
    locale.set.complete.count=22
    Max Upload Speed KBs=385
    Max Uploads=10
    Max Uploads Seeding=10
    Max.Peer.Connections.Per.Torrent=100
    Max.Peer.Connections.Per.Torrent.When.Seeding=50
    Max.Peer.Connections.Total=600
    Plugin.aercm.plugin.info=f
    Plugin.aercm.rcm.sidebar.initial.show=0
    Plugin.azintrss.Pairing Migrated=1
    Plugin.azintsimpleapi.apikey=mgib3cpq6cxhym3zz2ym4drcdmbzp66xlyusraiyg53s7nfkghsa
    Plugin.azneti2phelper.azi2phelper.external.port.auto=24409
    Plugin.azneti2phelper.azi2phelper.internal.port.auto=35802
    Plugin.azneti2phelper.azi2phelper.socks.port.last=60941
    Plugin.azneti2phelper.plugin.info=3/1/0/50/50/80/1/2/3/2/true;true/LU/269;596;119;179;469/0;2
    Plugin.aznettor.control_port=28605
    Plugin.aznettor.socks_port=29117
    Plugin.azupnpav.content_port=46249
    Plugin.azupnpav.uuid=uuid:66737f87-c790-4956-4e44-1de5c55870f2
    Plugin.default.device.tivo.enable=1
    Plugin.DHT.dht.reachable.0=0
    Plugin.DHT.dht.reachable.4=0
    Plugin.UPnP.upnp.device.multipledevices.warned=1
    Plugin.xmwebui.Pairing Auto Auth=0
    Plugin.xmwebui.Pairing Migrated=1
    pluginbar.visible=1
    Set Completion Flag For Completed Downloads On Start=0
    SideBar.Expanded2.NBSWCZDFOIXGIZLWNFRWK4ZPGEXXK5LJMQ5DKMZUGBRGCMJQFUZDCZJQFU2GGOLDFU4DOYJUFVSTONJUHA4DONBTMRRTAOR2OVYG44B2OJXW65DEMV3GSY3FHIZQ=1
    SideBar.Expanded2.NBSWCZDFOIXGIZLWNFRWK4ZPGEXXK5LJMQ5DMZBYGMYGCM3BFVRDAMRRFU2DEYJQFU4DEYZVFVRWEYLDHA4GKMZTGRRWEOR2OVYG44B2OJXW65DEMV3GSY3FHI2Q=1
    SideBar.Expanded2.NBSWCZDFOIXGIZLWNFRWK4ZPGEXXK5LJMQ5DQMBQGAZDANBYFUYTAMRUFU2DAOJWFVQWEY3EFU3TIZRYMRRDMNLCGYZGIOR2OVYG44B2OJXW65DEMV3GSY3FHI3Q=1
    SideBar.Expanded2.NBSWCZDFOIXGIZLWNFRWK4ZPGEXXK5LJMQ5DQNRSHBQWIMBWFVSWEOJWFU2GMN3CFU4DSOLEFU4GCYZVGA3TOZRVGNTGIOR2OVYG44B2OJXW65DEMV3GSY3FHI2A=1
    SideBar.Expanded2.NBSWCZDFOIXGIZLWNFRWK4ZPGEXXK5LJMQ5GGNTBGYYWEOBRFVRWCNJWFU2DEOJSFVQTENRTFVRDENBTGI2DSYLDG5RGMOR2OVYG44B2OJXW65DEMV3GSY3FHIZA=1
    SideBar.Expanded2.NBSWCZDFOIXGIZLWNFRWK4ZPGEXXK5LJMQ5GKYTGGVQTAYJQFUYWIZBRFUYTCYRSFVQTSMDGFU2WGN3EG5SDCZRTMU3GEOR2OVYG44B2OJXW65DEMV3GSY3FHI3A=1
    SideBar.Expanded2.NBSWCZDFOIXGIZLWNFRWK4ZPGEXXK5LJMQ5GMYZUMVRTKN3FFUZDQYRRFUYTCZDCFU4DQZRYFVQTCNRYGMYDSNJWGIZTGOR2OVYG44B2OJXW65DEMV3GSY3FHI4A=1
    SideBar.Expanded2.NBSWCZDFOIXGIZLWNFRWK4ZPGEXXK5LJMQ5HK4DOOAWUS3TUMVZG4ZLUI5QXIZLXMF4UIZLWNFRWKLJZGVBTGRJRIY2TOMRRIY5DU5LQNZYDU4TPN52GIZLWNFRWKORZ=1
    SpeedLimitMonitor.setting.download.limit.conf=LOW
    SpeedLimitMonitor.setting.upload.limit.conf=LOW
    SpeedManagerAlgorithmProviderV2.setting.download.max.limit=72192
    SpeedManagerAlgorithmProviderV2.setting.upload.max.limit=235008
    SpeedTest Completed=1
    TCP.Listen.Port=20903
    UDP.Listen.Port=20903
    UDP.NonData.Listen.Port=20903
    User Mode=2
    window.maximized=0
    window.rectangle=370,85,1669,753
Plugins
    Location Provider: 0.6.0
    Swarm Discoveries: 0.9.6
    Message Sync Support: 0.9.6
    I2P Helper Plugin: 2.1.0.1.1
    Rating: 1.7.2
    UPnP Media Server: 0.6.8
    uTP Plugin: 0.6.8
    Measurement Lab (M-Lab): 0.5.3
    mlDHT: 2.6.5
    BiglyBT Web Remote: 1.0.9
    Tor Helper Plugin: 1.2.8

**Comment by parg** [comment]
And what is "net5" ?

Bind IP=net5

**Comment by beybrakers** [comment]
I don't know, I just copy pasted what you told me to
