### ISSUE TITLE
Settings seed limits and light seeding (with private tracker - dime)

### ISSUE THREAD

**Issue by fncll** [BiglySoftware/BiglyBT#3078]
I'm asking this here because I don't think I can post images in the Reddit thread.

I am trying to set limits for a private tracker (Dimeadozen) and in doing so have made things worse. I simply want to have as many seeds available as possible while not getting in trouble for "too many seeding peers on this account." In trying to set limits, I now have no seeds showing as "light seeding" (which may not be a problem) but all of the torrents show as seeding and so many have the error. 

According to the Dime docs, 

- Your total peers active on DIME may not exceed sixty 
- A user with forty or more current seeding peers may not enter an additional torrent as a seeder

Here are my current settings. Can you tell me what I am doing wrong?

![CleanShot 2023-10-30 at 10 09 12](https://github.com/BiglySoftware/BiglyBT/assets/1208889/4f808dc3-c293-4126-b930-135363bb12fa)

![CleanShot 2023-10-30 at 10 09 48](https://github.com/BiglySoftware/BiglyBT/assets/1208889/e6522338-bd43-442c-8801-70e6f3831dee)

![CleanShot 2023-10-30 at 10 10 07](https://github.com/BiglySoftware/BiglyBT/assets/1208889/35b6bef0-5eff-49db-acf8-229a9367b031)

![CleanShot 2023-10-30 at 10 10 16](https://github.com/BiglySoftware/BiglyBT/assets/1208889/7382c52a-8fb4-446b-8666-cd51d574262f)

![CleanShot 2023-10-30 at 10 10 26](https://github.com/BiglySoftware/BiglyBT/assets/1208889/2cf572d7-3598-4d41-9555-06b00cd0ceee)

![CleanShot 2023-10-30 at 10 10 34](https://github.com/BiglySoftware/BiglyBT/assets/1208889/75b05d1d-00a5-4ac7-9c85-70779f05d1d4)

```
Java 1.8.0_292 (64 bit)
  Azul Systems, Inc.
/Applications/BiglyBT/.install4j/jre.bundle/Contents/Home

SWT v4942r22, cocoa, zoom=200, dpi=72
Mac OS X v10.16, x86_64 (64 bit)
B3.4.0.0/4 az3
```

**Comment by parg** [comment]
You don't want to use a Tag constraint, that just restricts what downloads are automatcally assigned to the Tag. What you want to do is remove the constraint and look above it at the "transfer settings" group, There you will see the seeding limits.

Have you set the tracker properties so that only Dime tracker torrents are assigned to it?

**Comment by parg** [comment]
Did you ever figure this out?

**Comment by fncll** [comment]
Thanks, sorry. That took care of things. I'm not doing any "light seeding" but I don't think that's a problem since there are no resource issues and things seem to be working as intended!

**Comment by parg** [comment]
coolio!

**Comment by rawther23** [comment]
> You don't want to use a Tag constraint, that just restricts what downloads are automatcally assigned to the Tag. What you want to do is remove the constraint and look above it at the "transfer settings" group, There you will see the seeding limits.
> 
> Have you set the tracker properties so that only Dime tracker torrents are assigned to it?


Greetings!
Sorry to bring this up, would it be possible for you to explain how I supposed to do this part?

_Have you set the tracker properties so that only Dime tracker torrents are assigned to it?_

I would like to have a standard configuration guide for dimeadozen private tracker, do you happen to have something that can help me out?
Out of the box it just works, but I feel like I'm not getting the most of it 

much appreciated

**Comment by parg** [comment]
If you have a tracker with tracker URL, say, "http://www.awesometracker.com/", you can create a Tag that automatically has any downloads that use that tracker assigned to it. 

Create a Tag (e.g. via the Add Tag button top right of the "Tags Overview" panel (View->Tags Overview)

Call it, say, "AwesomeTracker".

This will appear in the list of Tags in the Tags Overview. Right-click on it there (ignore the Settings panel below, not all settings are available there for historical reasons) and select the "Properties" menu item followed by "Trackers..."

A dialog will appear that allows you to specify the trackers. Enter "www.awesometracker.com" here - if your tracker has multiple URLs then enter them all, comma separated.

You should now see that all downloads that use "www.awesometracker.com" are automatically assigned to the Tag.
