### ISSUE TITLE
VPN NAT issues on BiglyBT

### ISSUE THREAD

**Issue by RavingIdjut** [BiglySoftware/BiglyBT#3080]
* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment

**Comment by RavingIdjut** [comment]
No good deed goes unpunished. Two days ago I finally sent a contribution to the developers. An hour or so later my BiglyBT went straight down the toilet. All downloading files, save for 1 sometimes 2, have been reduced to bytes or in the low kbs. I keep getting a message that "Listen server socket on [...] doesn't appear to be accepting inbound connections". When I ran a test in the Bigly program I got a message saying that "Test failed: NAT test failed on TCP" and "Test failed: Inbound test failed". As you can surmise no, I am not the most tech savvy person even in a rudimentary sense. I have used BiglyBT and before that Azure for years with few problems, but something has happened that I did not command.. Hell it was running gangbusters before I sent in the donation. 
OK, I just now checked on it and most of my 22 seedings are reading "OK (DHT backup only)" in red, others reading "Scraping..." or "Scraping failed".
Does anyone have any idea what's going on and how to fix it.
PC WIN10
BiglyBT 3.4 (I even tried the 3.3 version a guy said that solved his issues)
BiglyBT Issues. 
Sorry about the above "message" as that was my first time trying to post.
Thanks for any light you can shed, a RavingIdjut

**Comment by parg** [comment]
Check out https://github.com/BiglySoftware/BiglyBT/wiki/Downloading#bound-to-incorrect-network-interface
