### ISSUE TITLE
(Fedora 39) BiglyBT crashing

### ISSUE THREAD

**Issue by legacychimera247** [BiglySoftware/BiglyBT#3083]
hello there, seems that everytime i try to add a torrent to biglybt it crashes

the fedora bug report tools says it's related to java-17-openjdk-headless version 1:17.0.8.0.7-1.fc39.x86_64

i can say it happens from when i switched (3 days ago) from fedora 38 to 39

any suggestions?

**Comment by legacychimera247** [comment]
tried right now, and it solved the problem, thank you

i should anyway point out that any use of the internal browser crashes the app...

**Comment by parg** [comment]
right, that's what the beta does, detects the crash and disables the internal browser. maybe one day they'll fix that

**Comment by legacychimera247** [comment]
on the contrary, i disabled the browser myself, couldn't join beta as it was triggering a browser action (the blog for betas) and that was crashing the app

i don't know about the beta but on the stable if i don't disable the browser manually, the app just crashes...

**Comment by parg** [comment]
ah, ok.

perhaps you can join the beta program now, enable the internal browser and see if it automatically disables it again?

**Comment by legacychimera247** [comment]
done just now, it crashed the app...

**Comment by parg** [comment]
Just installed Fedora 39 and I don't get any crashes.

Java 11.0.20 (64 bit)
  Red Hat, Inc.
/usr/lib/jvm/java-11-openjdk-11.0.20.0.8-1.fc39.x86_64

SWT v4956r12, gtk/3.24.38, zoom=100, dpi=96
Linux v6.5.9-300.fc39.x86_64, amd64 (64 bit)
B3.4.0.1_B37/4 az3

**Comment by legacychimera247** [comment]
Well thank you for trying, i guess openjdk 17 is bugged then?

**Comment by parg** [comment]
Does it crash on openjdk 11 for you?

**Comment by parg** [comment]
Works fine for me under 17

Java 17.0.8 (64 bit)
  Red Hat, Inc.
/usr/lib/jvm/java-17-openjdk-17.0.8.0.7-1.fc39.x86_64

SWT v4956r12, gtk/3.24.38, zoom=100, dpi=96
Linux v6.5.9-300.fc39.x86_64, amd64 (64 bit)
B3.4.0.1_B37/4 az3

What version SWT and GTK do you have? Check BiglyBT->About
