### ISSUE TITLE
Add Archive button to toolbar

### ISSUE THREAD

**Issue by benedictleejh** [BiglySoftware/BiglyBT#3088]
* OS and version: Windows 11 23H2
* BiglyBT Version Number: 3.4.0.0

Currently, archiving a torrent requires right clicking  and moving over to the Organize menu. It would be much easier if the Archive button was available in the Toolbar, especially as the remove torrent dialog suggests archiving it. While I am currently on 3.4.0.0, checking the release notes for 3.5.0.0, and all commits suggests this is not available in 3.5.0.0 either.

**Comment by parg** [comment]
3501_B02 has an "archive" toolbar item. You need to enable it via

`Options->Interface->Display [Toolbar]: Archive`

**Comment by benedictleejh** [comment]
I assume that means 3.5.0.1 will have the Archive toolbar item? Awesome! Thanks for the quick implementation!

**Comment by parg** [comment]
Already available if you join the beta program (see the Help menu)
