### ISSUE TITLE
I2P (not sure) - Freezing Windows 11/64 pro

### ISSUE THREAD

**Issue by eurobank** [BiglySoftware/BiglyBT#3089]
Using Windows 11/64 pro latest update. Enabling I2P seems to freeze Biglybt. The freeze doesn't always happen, mostly when adding a new magnet. During the freeze (not responding message), the files are for some reason queued and not started. 

The freeze when started, it comes and goes.

Any ideas?

**Comment by parg** [comment]
Check the SlowUI_1/2.log files?

**Comment by eurobank** [comment]
Must i enable something? Where is that log located?

**Comment by parg** [comment]
%appdata%\BiglyBT\logs

**Comment by eurobank** [comment]
Shall i zip and attach them here, because i have no idea about all that

**Comment by parg** [comment]
sounds good!

**Comment by eurobank** [comment]
Ok, thanks. Here they come.
[SlowUI_2.zip](https://github.com/BiglySoftware/BiglyBT/files/13341971/SlowUI_2.zip)

**Comment by parg** [comment]
There's some interesting stuff there but nothing that points directly to I2P stuff :(

If the freezes last for quite a while perhaps you could try and grab some diagnostics while it is frozen,

Take a look at https://github.com/BiglySoftware/BiglyBT/wiki/Diagnostics

At the top it details a URL that you need to load in a browser while BiglyBT is in a frozen state - if it works it will generate a "ThreadDump.log" file in the logs folder, upload it here please.

**Comment by eurobank** [comment]
I will try to do all that when next freeze appears and i will update here.

**Comment by eurobank** [comment]
Here it comes ...

[debug_2.zip](https://github.com/BiglySoftware/BiglyBT/files/13347011/debug_2.zip)

**Comment by eurobank** [comment]
I will. In the meaning I2P seems not to be related to the issue. It happened also while I2P was disabled.

**Comment by eurobank** [comment]
After i updated to the latest beta, i'm unable to replicate the issue. Still i will keep an eye open for 1-2 days and update here.

**Comment by eurobank** [comment]
It seems to be solved now. **Many thanks.**

IF i see it again, i will reopen here.
