### ISSUE TITLE
Problems with UI - bottom part disappeared

### ISSUE THREAD

**Issue by o0nd7ots** [BiglySoftware/BiglyBT#3091]
Right now my BBT looks like this:
![image](https://github.com/BiglySoftware/BiglyBT/assets/124466962/988fa475-fdbf-49cc-8148-1e6d882d2feb)
It has the `Incomplete Torrents` and `Complete Torrents`.
O am missing the element where I can easily tag downloads, see the sources and so on.
I mean the lower half with `General`, `Files`...
![image](https://github.com/BiglySoftware/BiglyBT/assets/124466962/ed666bd4-cb45-4393-8a8c-053a742a363e)

I am aware that I have probably caused this but I do not know how to revert that change.
Does anyone know how to do that?

* Linux 6.6.1
* BiglyBT 3.4.0.0
* For *nix: Plasma 5.27.9

**Comment by parg** [comment]
There is an option to hide the subtabs -` Options->Interface->Tables [Library]: Show sub-tabs in Library views (Restart Required)`

**Comment by o0nd7ots** [comment]
Thank you very much, this fixed this!

I must have turned it off my mistake.
