### ISSUE TITLE
Installer appears grayed-out in dark mode

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#3093]
On macOS 10.15.7, when using the 3.5.0.0 installer (or the 3.4.0.0 installer; this is not a new issue), the palette for the EULA page is extremely low contrast. It has the appearance of being "grayed-out", as if it's disabled (though it's not):

![image](https://github.com/BiglySoftware/BiglyBT/assets/538020/fb6eddb5-66da-470a-9f59-efc5925a6e25)

(It's also telling that, other than the window chrome drawn by the system itself, the palette remains virtually **unchanged** when switching to another application. One would normally expect that it _would_ become grayed-out when that happens. Other than the window decorations, the **only** visual indication that the installer is no longer active is that the "focus ring" around the EULA text, which is normally blue when the application is in a focused/foreground state, becomes gray when a different window is selected):

![image](https://github.com/BiglySoftware/BiglyBT/assets/538020/0809cc86-0ae0-47ff-9ce7-0b203edb9808)

(That selection is there because, normally when an application loses focus, text selections are one of the things that become grayed-out... but that doesn't happen here either.)

Focused:

![image](https://github.com/BiglySoftware/BiglyBT/assets/538020/a9c1ee28-38a2-422b-8cf7-a80e10d7c275)

Unfocused:
![image](https://github.com/BiglySoftware/BiglyBT/assets/538020/667a8f13-d8ba-489d-8915-9f2df3b9be55)

**Comment by ferdnyc** [comment]
(Actually it's not just the EULA page, it's every page.)

**Comment by ferdnyc** [comment]
The file `Contents/Resources/app/i4jparams.conf` inside the installer `.app` package appears to control the appearance of the window, and while there isn't _much_ color configuration in there, there is some. Changing the `backgroundColor` property at line 250 to `25,25,25,255` for dark mode darkens the _header_ background, and adding a `foregroundColor` property immediately after with the dark-mode values set to `255,255,255,255` makes the _header_ text fully white:

![image](https://github.com/BiglySoftware/BiglyBT/assets/538020/44941d59-2c35-4e19-8931-168cc1a3eb51)

...All of which is an improvement, but doesn't affect the dialog body elements. Still, it seems to indicate that the palette is configurable, if the necessary parameters are added.

**Comment by ferdnyc** [comment]
Hmm. I also see this, at around line 440 (I inserted that `foregroundColor` that pushed everything down, so it's hard to be exact):

```xml
<lookAndFeel type="crossPlatform" darkModeStrategy="auto"
 lightTheme="lightIntelliJ" darkTheme="darcula"
 customLightThemeName="" customDarkThemeName="" />
```

**Comment by ferdnyc** [comment]
UGH. So, apparently this (terrible, washed-out nonsense) is simply the Install4J default dark-mode palette, as can be seen by running their own tools in dark mode, or even just browsing [the Install4J online documentation](https://www.ej-technologies.com/resources/install4j/help/doc/main/introduction.html) and activating the dark-mode style.

While they ship _two_ different dark-mode theme options, "Flat Dark" and "Flat Darcula", I'll be damned if I can find even the tiniest difference between the two.

Confirmed, the [theme docs for the FlatLaf theme engine](https://www.formdev.com/flatlaf/themes/) show that the differences between FlatLaf Light and FlatLaf IntelliJ, or between FlatLaf Dark and FlatLaf Darcula, have nothing to do with color palette and everything to do with the appearance of form controls.

...It would appear FlatLaf has a "macOS dark theme" which looks not-terrible enough to be a good candidate for the dark-mode theme on all platforms, at least color-wise:

![image](https://github.com/BiglySoftware/BiglyBT/assets/538020/dde65d6f-d800-4ab5-826b-94889e3a9196)

(Certainly, better than the crappy Flat Darcula default.)

However, I've also filed https://github.com/JFormDesigner/FlatLaf/issues/762 regarding the contrast issues with the default Dark / Darcula color palettes.

**Comment by TuxPaper** [comment]
Good sleuthing!

Install4j gives me the option between "Flat Darcula" and "Flat Dark", as well as allows for a custom IntelliJ Theme (json file) which apparently allows me to use any of the themes from https://plugins.jetbrains.com/search?tags=Theme

I personally don't have a preference, although I agree that the current dark theme is fairly faded.  So if there's a theme that you prefer from the Theme Site, let me know and I think I can swap it out.

**Comment by ferdnyc** [comment]
@TuxPaper The macOS theme looks great _for macOS_, but I get the impression it's **only** for macOS. (To the point of not being available on other platforms.) Even if it were, beyond the color scheme there's also the control styling, which is very Mac-oriented and would probably make things look weird on other platforms.

A tweet [back in March](https://twitter.com/JFormDesigner/status/1640719364298248192) made mention of Cupertino themes (light and dark) as sort of a cross-platform macOS theme:

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Apache <a href="https://twitter.com/netbeans?ref_src=twsrc%5Etfw">@NetBeans</a> 17 comes with two new look and feels: <a href="https://twitter.com/hashtag/FlatLaf?src=hash&amp;ref_src=twsrc%5Etfw">#FlatLaf</a> Cupertino Light and Dark.<br><br>They look similar to macOS, but are available on all platforms. Mac users will love them. Especially the dark one.<br><br>Go to &quot;Tools &gt; Options &gt; Appearance &gt; Look and Feel&quot; and try them out. <a href="https://t.co/a5I2xrwKJI">pic.twitter.com/a5I2xrwKJI</a></p>&mdash; JFormDesigner (@JFormDesigner) <a href="https://twitter.com/JFormDesigner/status/1640719364298248192?ref_src=twsrc%5Etfw">March 28, 2023</a></blockquote>

...But for right now, I'd say let's hold off for a bit and see if there's any movement on https://github.com/JFormDesigner/FlatLaf/issues/762.

I made a bunch of (IMHO) solid, science-based arguments for why their current default dark themes fail on the contrast front and make bad defaults. (Not least, the fact that even IntelliJ IDEA (the application FlatLaf Dark & Darcula were designed to imitate, thematically) has since launched a New UI replacing that old theme with a significantly improved design.)

If the FlatLaf designers buy in and decide to make some improvements to their default themes, all the better and zero work on our end! If not, we can see about picking a substitute.

**Comment by ferdnyc** [comment]
@TuxPaper 

Well, no response at all to my issue, even though more-recently opened ones have been responded to. So, I don't know what to make of that.

If we are going to load a theme, I think it should be the "New UI" IntelliJ theme, which can be found in their community repo here: https://github.com/JetBrains/intellij-community/blob/master/platform/platform-resources/src/themes/expUI/expUI_dark.theme.json

It loads fine into the FlatLaf Demo application, so presumably it would load fine into the installer as well. It does complain about some embedded icon file paths, tho, so here's a modified version with all of those paths removed (the icons used will be the FlatLaf default ones):

[expUI_dark_noPaths.theme.json](https://github.com/BiglySoftware/BiglyBT/files/13432150/expUI_dark_noPaths.theme.json)

Here's how it looks loaded into their demo app:

![image](https://github.com/BiglySoftware/BiglyBT/assets/538020/4afaec54-2f3b-425f-8c05-6977b0a54421)

There's also a light version, if you wanted to switch for consistency. (I haven't done the scrubbing-it-of-paths thing yet, but here's how it looks in the demo app:)

![image](https://github.com/BiglySoftware/BiglyBT/assets/538020/61292591-27cb-4583-995c-b722abe11b26)

**Comment by ferdnyc** [comment]
Oh, the IntelliJ Platform license is Apache 2.0, FTR. Apparently including the theme files.
