### ISSUE TITLE
Unknown DHT requests on starting private torrents

### ISSUE THREAD

**Issue by paxter** [BiglySoftware/BiglyBT#3094]
<img width="1064" alt="ws" src="https://github.com/BiglySoftware/BiglyBT/assets/5040710/5bf5dba0-7cdf-486e-a4b3-1fd5e48c45a3">

What is this? Happens every time on starting a new (private) torrent. However it's not the infohash of the torrent file. Where this hash comes from? There is no other torrent in the client.

I'm using the latest BBT version 3.5.0.0 and did a fresh install before testing without any config changes. OS is macOS (arm64).

Looks like a (huge?) security/privacy issue for me. I'm not interested into sending strange hashes to foreign servers I don't know. Maybe anybody can explain this behaviour.

**Comment by parg** [comment]
Looks like a "mainline DHT" message. This is disabled for private torrents - check the torrent actually is private by looking in the General tab for the torrent and checking the "private" field. Some private trackers use public torrents.

The hash is, afaik, the SHA1 of the torrent hash.

**Comment by paxter** [comment]
As I said. This is not the SHA1 hash of the added torrent. The hash is unknown to me. Also there is no other torrent added to BBT and each time there is another Info-Hash used for such requests. Looks for me more like testing of a service or sending analytics data. There is no reason for sending this.

**Comment by parg** [comment]
sha1 of the torrent hash is not the torrent hash, it is sha1(torrent hash), which is not "As I said".

**Comment by parg** [comment]
Then again, maybe it uses the infohash directly - https://en.wikipedia.org/wiki/Mainline_DHT

I didn't write it.

**Comment by parg** [comment]
Anyway, going back to your original post.

You have a private torrent with torrent hash X1 as shown in the General tab. It also shows "Private Torrent: Yes" on that tab

When you go to the Sources tab you can see the BiglyBT there, called DHT, shown as "Disabled" under "Status". You won't see a line there for the "mainline DHT" (mlDHT) as the torrent is private. If the torrent wasn't private then there would be a line there with type "Plugin" and details showing "mlDHT".

Whenever you start this torrent you see a Get_peers message with an info_hash Y1 that is not X1 and is always Y1 when you stop and start the torrent multiple times.

If you do the same with a different private torrent with hash X2 then this shows a Get_peers with hash Y2, which is not Y1, and is always Y2 when you start X2.

Right?

**Comment by paxter** [comment]
I did another wireshark capture.
Obviously, this issue is not related to private torrents. It's a general behaviour of BBT with default settings. As you stated, probably because of miDHT, which is enabled by default.

<img width="1290" alt="mainlinedht" src="https://github.com/BiglySoftware/BiglyBT/assets/5040710/0026f449-c71a-4975-b023-2e6448040f78">

In my opinion, no open source bittorrent should sent any data without permissions of the user. Feel free to close this issue. But for me it's a privacy issue.

Thanks for help and clarifying. :)
