### ISSUE TITLE
Cursor keys didn't work in input fields

### ISSUE THREAD

**Issue by de-served** [BiglySoftware/BiglyBT#3095]
Bigly BT 3.5.0.0/4 az3
Java 20.0.1 x64 Eclipse Adoptium
Win 10 x64
SWT v4956r12

Currently I started to manage my categories/tags to exclude manual applying to torrents and... found that cursor keys (Up/Down/Left/Right) didn't work in any text input field (maybe other fields too, but it's enough pain with text fields)
Because that I've spending a ton of a time with mouseclicking when there will be enough just one keypress.

What I'm talking about:
For example, I'm adding constraint to a tag. Written "matches()" and want to enter to "()" field and pressing "Left" (I'm writing both "(" and ")" at once to avoid mispairment) - after "Left" keypress... input field lost tabstop/focus - selection jumps to other elements, but not inside text editing field.
When I want to go to beginning/end of the text I'm pressing "Up"/"Down" and focus jumps out of the input field too... "Home"/"End" works.
But most of the time I need "Left/Right/Up/Down" to move in entered text.

Checked this problem in Filter at the main window (where [  .*x] are) - the same situation. When I try to press "Left/Right" for editing entered text focus jumps from input field. So to get to precise position I MUST use mouse cursor and not keyboard cursor (it is much-much slower - when I need to point mouse cursor at precise letters position, with keyboard working it will be much faster - click anywhere in text, press n-times Left/Right/Up/Down and done). Each time I need to change text cursor location I must take my hand out of the keyboard, get the mouse, move it, locate mouse cursor, point it to desired location, click, if I missed - relocate, click etc - with properly working keyboard it will be only just a keypress or two that eats 0.01 s in compare to mouse 1-3+ s) :((

Same situation in "Instruments -> Settings" - when I try to enter something in search field, for example missed one letter inside the text - now I need to get the mouse to point cursor OR delete all text to the missed letter and retype (it is even much faster than using a mouse).
PPS: there must be a delay 50-200 ms at Settings searchbox input before start filtering - it starts lagging just after a first letter because BiglyBT starts to search all texts just right after keytype... Interface stucks.

**Comment by de-served** [comment]
It's strange enough, but after ~1-1.5 hours it is "selffixed" (for unknown time?) - I changed nothing. Did not reboot, did not restart BiglyBT, did not unload any software and did not start any other software. Just sitting in BiglyBT and editing tags/constraints and attaching/detaching tags manually to see what I've done...

**Comment by parg** [comment]
Those are "native" widgets created by the SWT UI library, mapping key strokes to behaviour is not handled by BiglyBT at all. No idea what you are experiencing, never seen it myself and nobody else has reported it... Perhaps it'll never happen again!
