### ISSUE TITLE
Tag edit dialog + Tag (re) assignment issues

### ISSUE THREAD

**Issue by de-served** [BiglySoftware/BiglyBT#3096]
Bigly BT 3.5.0.0/4 az3
Java 20.0.1 x64 Eclipse Adoptium
Win 10 x64
SWT v4956r12

Tag edit dialog > File settings
Fill all 5 paths - Initial Save Location, Move on Complete, Copy on Complete, Move on Remove, Move on Assign
Press "Clear" button for each of the paths then after clearing restore it.
For 4 paths it works as expected - clears only path field that button belongs to.
Except last "Move on Assign". It clears "Initial Save Location" too.

I'm using only this two paths - Initial and Move on Assign. Including that "Clear" works immideately without any "Apply" button + my experiments with understanding how all this works... and a few more bugs with tags (re)assignment lead to extreme high file movement last day - tons of Gigs are travelling from HDD to SSD and vice versa few times.

Assigned Tag is not shown at Tag submenu by RMB at torrents and selecting currently selected tag [reassignment?] didn't apply paths set in Tags options most of the time, and there are no option to clear Tag and provoke autotagging to check/reassign correct paths; Tagging View > Explain shows correct autotagging; all torrents are old, no new downloads, so not checked if it fails only at old or for new torrents too
It's possibly due to autotagging by Constraint.

Screenshots 1-2: Autotagging by Constraint, RMB, Tags menu - active/selected tag is not shown [FAIL]
Screenshots 1-2, when Autotagging.
Select "Torrents (n)" tab, RMB at torrent, select correct tag (autoselected by constraint, not shown as active now!!
) - current path will not be updated/changed if it is not as it must be (not as in Move on Assign or Initial) - it is not possible to "reset" path by selecting tag. Only by manual move of files. If there are tons of torrents with number of tags/subtags - it is a pain to fix it. DIDNT WORK.
![1](https://github.com/BiglySoftware/BiglyBT/assets/18093731/fd3346cc-75d6-48eb-9ac4-f8e5d5a8a80a)
![2](https://github.com/BiglySoftware/BiglyBT/assets/18093731/ecf16c61-3d4b-4f31-9543-8f3bb89b59e3)

Screenshots 3-4: Manual tagging (Constraint clear), RMB, Tags menu - active/selected tag is not shown [OK]
Screenshots 3-4, when manual tagging.
If there was an error in path/wrong path, then RMB at torrent, select correct tag (it is shown as active now) - this provokes reassignment correct path and move files if checkbox "Move" is active - works OK.
![3](https://github.com/BiglySoftware/BiglyBT/assets/18093731/eb5d70d8-19fa-409f-abdf-f5245fade08d)
![4](https://github.com/BiglySoftware/BiglyBT/assets/18093731/e396dc7b-4960-48dd-8b87-690ddb8d6bce)

Screenshot 5: Centering of Path field in details - hard to understand path issues if they are there when different path lenghs.
![5](https://github.com/BiglySoftware/BiglyBT/assets/18093731/de4f1f2a-5922-4717-9245-c3bf2b0cf6cd)

**Comment by parg** [comment]
Move-on-assign also sets the initial save location as you have discovered:

**Comment by parg** [comment]
Right-click on a Tag in the sidebar or elsewhere and there is a Files menu that has entries for the various operations. These generally have an "Apply to current" option to apply them to currently assigned downloads.

**Comment by de-served** [comment]
> Right-click on a Tag in the sidebar or elsewhere and there is a Files menu that has entries for the various operations. These generally have an "Apply to current" option to apply them to currently assigned downloads.

Thanx for this. It is very helpful.
But what about not "happy path" you provided (user must know about that... I'm on BiglyBT from the beginnig and a few years at Vuze previously and didn't know about that till now...) but with a path as I did, at the tag's options tab or at the main window where all torrents are, by (re)assigning tag -- it is possible to fix that?

PS: Tags options non-active tab "Torrents (n)" is not updating (n) if torrents with this tag is (un)associated by RMB or constraint. It is updates only if I select this tab.

**Comment by de-served** [comment]
> Right-click on a Tag in the sidebar or elsewhere and there is a Files menu that has entries for the various operations. These generally have an "Apply to current" option to apply them to currently assigned downloads.

Interesting...
When I RMB at Tags at sidebar > Files > Move on Assign > Apply to Current -- it works as expected.
Tested the same with selecting Files > Initial Location > Apply to Current -- not works.

Initial save Location and Move on Assign paths are identical, [v] Move checkbox are on.

**Comment by de-served** [comment]
@parg How I can send you few .config's not publicly?
There is a weirdness... at some torrents RMB shows selected tag, at othe dont, part of tags are shown, part no, if I clear constrait for not shown subtag with all parent tag then all tag with children are shown... I can't understand any logic
PS: in tag.config I see tags that I've 100% deleted (there are icons info I don't want to expose but I see path I don't want to show - I've checked for which tag it belongs to - but all that tag icon paths are changed by me, so there are dead tags with old paths that I've deleted previously but ther are in config
My head is near blowing

**Comment by parg** [comment]
I'll get around to looking at it, working on some other stuff at moment...

**Comment by parg** [comment]
"save location" is left aligned, maybe you changed it in Column Setup

**Comment by parg** [comment]
Tags options non-active tab "Torrents (n)" updates for me - please give me a specific example of how to reproduce this

**Comment by parg** [comment]
Screenshots 1-2: Autotagging by Constraint, RMB, Tags menu - active/selected tag is not shown [FAIL]

should be fixed next beta (B04)

**Comment by de-served** [comment]
`"save location" is left aligned, maybe you changed it in Column Setup`
Wow. Really didn't know and didn't used it as long as I know. Maybe some day long-long ago in a galaxy I've pressed it once occasionally but it is always left aligned in all other windows so I even didn't think about it until started to use this *%2#@!!@%$ "constraints" :(

`Tags options non-active tab "Torrents (n)" updates for me - please give me a specific example of how to reproduce this`
Just enter Tags view (I've opening now it external window by DblClick at Tags view in sidebar.
Then I see Tags at upper part and Settings/Torrents(n) at lower part.
Enter something in constraint that will touch some torrents, Save it and voila - mine is not updating. I must press Torrents(n) tab to update this number.
Then do opposite - go Settings, clear constraint, Save - Torrents(n) tab is not updating again.
Ok, with ...
Strange. I've cleaned constraint and torrent did not lost autoassigned tag... next bug?

Let's continue - ok, with cleaned constraint and Torrents(n) not updated RMB at any torrent in main window and add/remove tag that we experiment with, looking at Tags view screen with Torrents(n) tab - it is not updating too. No matter what I do - until I press it it never updates.

PPS: can it be possible to use all .configs in HRF (Human Readable Form(at))? I understand that there are some deep bugs that break something and there are not existant tags that I've removed but they are saved in tag.config and seems like they never be removed and maybe other tags with other bugs and I have zero desire to recreate all tags from the ground and reassociate and recreate everything in my library with 600+ torrents. I've already have a chaos in locations because BBT tosses files when I play with constraint. And it doing this not every time so it is frustrating too...

And please, add an option to save current locations of files when first time Saving constraint (it warns ONLY if I write constraint and save it first time, all next clear+save then write+save did not warns and did not move files so it is much better... if I cancel warning then constraint is not applied so it is pushes me to move files if current tag MoveTo paths are not as torrent files are [if I previously moved them manually to path I want and it differs from tags parameters])
