### ISSUE TITLE
Tags editing/selection dialog issues

### ISSUE THREAD

**Issue by de-served** [BiglySoftware/BiglyBT#3097]
Bigly BT 3.5.0.0/4 az3
Java 20.0.1 x64 Eclipse Adoptium
Win 10 x64
SWT v4956r12

![8](https://github.com/BiglySoftware/BiglyBT/assets/18093731/43a37193-e35c-440a-8145-a28e28c268b0)
There was a few more tags I've deleted. Now it is only 4 tags in group.

![9](https://github.com/BiglySoftware/BiglyBT/assets/18093731/8bdf3a25-d6c1-4f74-b4c0-4d1c38ed7ae2)
There are a Group "Soft\Server" with 4 tags.

![10](https://github.com/BiglySoftware/BiglyBT/assets/18093731/257c79af-b178-4597-9157-aa85bfcb0493)
When RMB on torrent (at torrents listing in main window) and selecting "Tags" I didn't see a group "Soft\Server", and Group "Soft\Security" has phantom tags.

Only restart fixes deleted phantom tags, but group "Soft\Server" are not in list.

**Comment by ferdnyc** [comment]
I wonder if the backslash is causing problems? It's an escape character in most string implementations. It might be better to use a forward slash, instead.

**Comment by de-served** [comment]
It happens if no slashes at all. I can't understang a logic (I'm trying to use a lot of things - naming of tags, grouping, changing groups, adding to other groups, adding new groups and adding to them, duplicating tags, creating new tags and fill with the same name/Initial/Assign paths etc - not even an idea what's happening...)
If there were a debug startup option or something that can log such desicions, why BBT decides to show or not to show tags and other things that it decides - it would be perfect...

**Comment by de-served** [comment]
Besides, if I enter "constraint" the first time and click "Save" then BBT warns me that all curent tag will be reset. If constraint includes all currently torrents here then it is partially ok, mostly not, because it will reapply paths if it is suddenly differs from where torrent files are (autoapplying path if I added Move On Assign Root Folder for Group...)

Then if I clear constraint and Save, I'll get all torrents inside this tag to go to WithoutTag.
Then I enter constraint as before and Save - and NOW ... it is not warns me, it is NOT moving torrents to MoveOnAssign folder - it works differently than it was at first time.

Much better if it warns me that all tags will be reassigned AND will ask if I want to move torrents or not. When I clear-add constraint second+ time then it is not runs OnApply movement and it is good for me (I'm tired of torrents tossing for last 5 days... now I have a full chaos in my torrents... why I started to use this constraints(??) I wish to get an automatic sorting at adding new torrents and not to make a chaos in my fully structured 600+ torrents)

After Saving constraint Tab "Torrents" are not updating until I click at it. Never.

**Comment by parg** [comment]
I don't know what you're trying to achieve and I'm not about to wade through pages and pages of comments to try and figure it out.

Move on Assign works when a download is assigned to a tag. It triggers at this point in time, assignment. Once the download is assigned to the tag it won't be re-checked and moved again.

The warning you get when you set a tag constraint on a tag that didn't have a tag constraint before is triggered if you have manually assigned downloads to that tag already. It is warning you that you will lose those tag assignments you have bothered to make by hand as the membership of that tag will be controlled by the constraint, not your manual assignements.

If you have an issue then open a new issue WITH A SINGLE ISSUE CONTAINED WITHIN IT. If you have two issues then open two issues.

**Comment by parg** [comment]
Phanton tags in groups when deleted should be fixed in the next beta (B04)

**Comment by de-served** [comment]
I found why Tag Groups didn't show at RMB
If all Tags in a Group have Scope "Addition and Removal" then all Group are not shown.
If ANY of the Tag in that Group have different than "Addition and Removal" Scope then all Group are shown.
If I select Scope for one Tag or for all Tags in a Group as "Addition only", "Removal only" or "New Downloads" then Group are shown.

**Comment by parg** [comment]
the group isn't shown if you're not able to manually assign any of the tags in the group

**Comment by ferdnyc** [comment]
@parg I wonder if Tags maybe needs another type (that's not "Manual"), to identify tags with constraints governing their torrent assignment? Since they're kind of... explicitly _not_ "Manual". In fact exactly the opposite ­- you _can't_ manually apply those "Manual" tags.

(If the constraint-driven tags were considered something _other_ than "Manual", then the context-menu tag list could then be easily explained with: "Only Manual tags show up there".)

**Comment by parg** [comment]
@ferdnyc I can see what you're saying :) The "Manual" is supposed to refer to the fact that you have manually created them, as opposed to the "Automatic" ones that are automatically created and assigned to show download state (Downloading, Seeding, Checking, Moving....)

i.e. Manually Created, not Manually Applied

In some places Manual tags that are auto-assigned are shown as greyed out/italisized (e.g. the Tagging view). In the menus it was decided to remove them as the menus get a bit out of control.
