### ISSUE TITLE
Attempted donation window (with internal browser disabled) reappearing daily

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#3099]
Literally every day, for the past week or so, I connect to the fileserver I have running BiglyBT to find this window:

![image](https://github.com/BiglySoftware/BiglyBT/assets/538020/180911f6-41aa-480d-a74a-1e4575faaf59)

I DO have the internal browser disabled, but I didn't realize that was a punishable offense. :wink: 

#### System block
Java 11.0.20 (64 bit)
  Red Hat, Inc.
/usr/lib/jvm/java-11-openjdk-11.0.20.0.8-1.fc39.x86_64

SWT v4956r12, gtk/3.24.38, zoom=100, dpi=96
Linux v6.5.11-300.fc39.x86_64, amd64 (64 bit)
B3.5.0.1_B03/4 az3

**Comment by parg** [comment]
Running Linux is a punishable offence :)

If you actually click on the link the window shouldn't come back - I'll take a look as to why it is so frequent though!
