### ISSUE TITLE
endless plugin update loop

### ISSUE THREAD

**Issue by csylvain** [BiglySoftware/BiglyBT#31]
I'm seeing
  Version 2.0_CVS of plugin 'mldht/mlDHT' installed successfully
over and over and over again. I suppose everytime the clock runs out and the client goes out to check.

I looked in Debug -> Plugin Update and it's there over and over.. but since there are no timestamps anywhere (see Issue #30 ), I can't really tell how often it's happening.

**Comment by parg** [comment]
Can you check if the plugin installation folder (go to Tools->Options->Plugins to see the plugin install location) has a 'plugin.properties' file in it? (alongside the mlDHT_2.0.jar file) - if so delete it and restart and see if that fixes things.

**Comment by csylvain** [comment]
there was a plugin.properties file in the mlDHT directory. it contained a reference to version 1.6.1 even though the version 2.0 jar file was present and loaded.

**Comment by csylvain** [comment]
now, many hours later, there has not been a mlDHT plugin reinstall.
so it seems the transition from 1.6.1 to 2.0_CVS set up the endless loop.

**Comment by parg** [comment]
OK, we've found the issue - the migration from Vuze to BiglyBT was incorrectly extracting the plugin.properties file from the jar and that resulted in the update issue you found. Thanks

**Comment by trancephorm** [comment]
I'm having the same problem, but with updating BiglyBT itself. Says directory is unwriteable, but I understand it runs under root because it asks for root's password, and the directory is writeable by owner, which is root acc.

**Comment by csylvain** [comment]
oh my. please don't run stuff as root. i'll bet you've got stuff owned and not owned by owner (not root!) now. quickest way to undo the mess is compare carefully the owner and group of all the files with those of another system where you've never run it as root. or preserve your config file and blow the mess away to reinstall clean and then plop your config file in.
