### ISSUE TITLE
have incomplete downloads on a different folder

### ISSUE THREAD

**Issue by legacychimera247** [BiglySoftware/BiglyBT#3100]
hello, i would love to have incomplete downloads to a different folder rather than the same as downloaded, but i cannot find a way to do it.

Any hint?

Don't think it's relevant but i'm on fedora workstation 39

**Comment by parg** [comment]
Have you looked at "move on complete"? There are lots of ways to do it but the simplest is via

`Options->Files->Completion Moving: Move completed files (after download)`
