### ISSUE TITLE
New advanced column: Total Seeds

### ISSUE THREAD

**Issue by Xemnarth** [BiglySoftware/BiglyBT#3101]
I've noticed that the current "Seeds" column in the torrent transfer list only reflect the no. of seeds as reported by the last scraped tracker and not total seeds when there are multiple trackers. I'd suggest either tweaking the current Seeds column to display total scrapped seeds across all trackers in a torrent or just add a new Total Seeds column to preform this function, whichever is easier to do.

Thank you!

**Comment by parg** [comment]
The problem with aggregating seeds counts across trackers is that all the clients out there are registering on all the trackers so the total is completely useless.

**Comment by Xemnarth** [comment]
Then maybe consider changing the column's behavior to only show the highest Seeds count when multiple trackers are being scrapped?

**Comment by parg** [comment]
There's quite a bit of logic to attempt to select the "best" scrape values to use. Prioritise real trackers over the DHT for example. Don't flip-flop between results are these are driving the seeding rules and you don't want downloads constantly starting and stopping when different trackers respond with differing values.

If you're that interested in the individual results then that's what the Sources sub-tab is for.
