### ISSUE TITLE
Request: (option to) save config files in Human Readable Format

### ISSUE THREAD

**Issue by de-served** [BiglySoftware/BiglyBT#3102]
It's not a but but feature request

Can you add (sometime in a close future) savins configs in HRF? Maybe json or something? As an option or as a permanent change/update format to it?

Some things goes sometimes wrong and it is much easier to manually edit configs than ask you/write issues here if it is not so critical
Some things much easier to edit by keyboard than a mouse movements/clicking (for example for pixel-perfect crazy people like me sometimes I've spent a lot of time to align upper and lower columns with torrent info to be absolutely identical... but it was too hard to do it with mouse OMG)
Some time ago config files are growing like a monster each restart and lead to config reset and I write issue here and you fixed it after some time, but if configs was in HRF at that moment then it was be too easy to understand what's going on and how to fix it much faster from your side
It will be helpful in backup and/or migrate - everyone can make git repo at the BBT directory and control changes, save them etc

And other situations when it be better than now
How do you think?
Thank you

**Comment by parg** [comment]
Help->Advanced: convert bencoded to/from JSON 

I advise against editting config files directly, you don't know the dependencies between things.
