### ISSUE TITLE
Tag Group are not shown in Tags selection dialog when RMB at torrent

### ISSUE THREAD

**Issue by de-served** [BiglySoftware/BiglyBT#3103]
Issue was closed and I can't reopen it, but I've found a source of a problem:
https://github.com/BiglySoftware/BiglyBT/issues/3097#issuecomment-1823247388

**Comment by de-served** [comment]
You said
> the group isn't shown if you're not able to manually assign any of the tags in the group

What is the difference of "Addition and Removal" for Scope with other three options? Why this "and" mades impossible of manual addition/removal while "Addition only" and "Removal only" allows manual adding/removal tag? Absolutely ununderstandable :|

**Comment by parg** [comment]
Think about it, all these things need is a bit of intelligence. If you don't understand a feature then don't try and use it...

Addition only - the constraint is applied when considering when to ADD a download to the tag. So downloads that satisfy the constraint will automatically be added to the tag.  It isn't considered when looking to remove a download from the tag. So obviously you can manually add a download to the tag that doesn't satisfy the constraint. 

Removal only - the constraint is applied when considering when to REMOVE a download from the tag. You can add any downloads you want to the tag, ones that satisfy the constraint will automatically be removed. So obviously you can manually add a download to the tag.

Addition AND removal - the constraint totally controls what can be added to the tag. If the constraint isn't satisified the 1) it won't be added and 2) if it was added automatically and the constraint becomes false it will be removed.

**Comment by de-served** [comment]
I understand this things.
I don't understand why if only ONE Tag in Group have not "Addition and Removal" Scope then ALL Tags in this Group are shown.
If there would be correct logic as you previously said, then ANY Tag that has Scope "Addition and Removal" will be unaccessible by user. But it is not. So I played a lot with all of that to find a problem that occurs only when ALL Tags has the same "Addition and Removal" Scope.
Do you think it's normal behavior?.......

**Comment by de-served** [comment]
Constraint feature has a new bug-o-feature.
It can be avoided of forced move/apply filepaths (for a first time applying) to torrents IF constraint has an error (occasionally or... for avoiding/experimenting) - warning appears, confirm then error appears and applying stopped. "Fix bad" constraint, press Save and no warning and no files move.

**Comment by parg** [comment]
the addition removal thing is how it is implemented. normal is defined by the implementor, which isn't me.

Don 't fuck around with editting constraints on things that have significant side effects. Get your constraint right, on a test Tag if needed, and ONLY THEN set about configuring the side effects of things being assigned to a tag. That is the intelligent way of doing things, isn't it?
