### ISSUE TITLE
Tag Editor > Settings > Constraint disabling Save/Reset buttons 

### ISSUE THREAD

**Issue by de-served** [BiglySoftware/BiglyBT#3104]
Bigly BT 3.5.0.0/4 az3
Java 20.0.1 x64 Eclipse Adoptium
Win 10 x64
SWT v4956r12

Tag Editor > Settings > Constraint
Enter something, press Save, when Warning appears - press Esc or click at Cancel
Buttons Save/Reset now is disabled so to enable them user needs to change constraint. Add/Remove space, for example, if constraint was ok and user changes his mind

**Comment by parg** [comment]
The "reset" button resets the constraint to the currently saved value.

Once you press "save" the value becomes "the currently saved value" (even if wrong), there is no "previous value" to reset it to.
