### ISSUE TITLE
'Category' tag type isn't translated inside Tag overview

### ISSUE THREAD

**Issue by adem4ik** [BiglySoftware/BiglyBT#3112]
* OS and version: Windows 10 x64
* BiglyBT Version Number: 3.5.0.1 beta 5

1. Switch language to Russian or Brazilian
2. Open `Tag overview`

Result: `Category` tag type isn't translated.

![изображение](https://github.com/BiglySoftware/BiglyBT/assets/4707112/fc2593dc-02c0-4e65-9a01-7f03cdb09919)

**Comment by parg** [comment]
Thanks, fixed next beta. The "tag group" column should switch language after a restart for categories, not straight forward to update dynamically.

**Comment by adem4ik** [comment]
@parg thanks! fix is confirmed in 3.5.0.1 beta 6:
![изображение](https://github.com/BiglySoftware/BiglyBT/assets/4707112/3ac31045-47d9-43ac-86a6-de8c7b37c40a)
