### ISSUE TITLE
prefix added to all files, not just moved files.

### ISSUE THREAD

**Issue by Pandoriaantje** [BiglySoftware/BiglyBT#3118]
Java 20.0.1 (64 bit)
  Azul Systems, Inc.
c:\program files\zulu\zulu-20

SWT v4956r12, win32, zoom=100, dpi=120
Windows 11 v10.0, amd64 (64 bit)
B3.5.0.0/4 az3

I have the following options set:

- Add suffix to incomplete files
- move files not selected for download into subdir
- add unique prefix to the modified/moved files

It was my impression, that only the moved files/pieces in the subdir would have a prefix, but BiglyBT seems to add a prefix to all files now. I guess the 'prefix logic' sees the incomplete suffixed files, as modified/moved files?
Is this intentional behavior or an oversight in the prefix logic?

**Comment by Pandoriaantje** [comment]
Thanks. I thought as much.

I thought the prefix logic would be a little 'smarter' and not count incomplete/downloading files/pieces as "modified" or "moved" (as the option implies explicitly).

It depends on how you look at it. Not a 'problem" perse, but it would be easier on the eyes, if actual incomplete files only had the suffix, and not the prefix (so by design be handled differently in the prefix logic).  But the end result is the same. everything get renamed as it should, so not that big of a deal.

Thanks for the quick answer.

**Comment by Pandoriaantje** [comment]
I reopened this, as the options given are not really clear, and I'm not able to get the results i am looking for.
So hare are my additional questions:

I have the following options set:

- Add suffix to incomplete files [.az!]
- Move files not selected for download into subfolder [.dnd_az!]
- Also add unique prefix to the modified/moved files to avoid potential name clashes
- When removing a download from the library delete any partial files for those selected as 'do not download' or 'delete'

First question: Does BiglyBT, use subdirectories for files flagged as 'do not download'? for example in my case, ../.dnd_az!/subfolder/notneededfile.ext or does it place all files flagged as 'do not download' in the root of the [.dnd_az!] subfolder? (making sure the prefix option is needed, or optional).

Second question: Why is it that I have the option set to remove partial files for those selected as 'do not download' or 'delete', but when I remove a completed torrent from the library, the [.dnd_az!] subdir and its partial files are never removed, leaving a lot of clutter and unneeded/unintentional diskspace usage behind?

**Comment by parg** [comment]
I just did a test. The files left in ".dnd_az!" for me are the ones that were actually completed due to the fact that their pieces overlapped completely with files that were required. i.e. they are no longer "partial files".

However, I can see that having the directory remain with the files in is probably not what a user would expect.

**Comment by Pandoriaantje** [comment]
> I just did a test. The files left in ".dnd_az!" for me are the ones that were actually completed due to the fact that their pieces overlapped completely with files that were required. i.e. they are no longer "partial files".
> 
> However, I can see that having the directory remain with the files in is probably not what a user would expect.

That is what I thought. for the torrent I tested, they were small txt files "downloaded from", "url link", etc, so they overlap. so it is actually a bug with the code logic.

**Comment by parg** [comment]
Dude, you've made your point, move on and waste someone else's time with your incessant messages.

**Comment by Pandoriaantje** [comment]
So this is what it comes to? you reject a valid bug report, because it does not suite your logic? even though it affects a lot of users, and is against the logic implied by the options in the program?  I get no real reply from you except some reflection, so I'm just supposed to keep quit? well thanks. and good luck with your project. I seemed promising on paper, but the code, and dev lack consistency.

**Comment by Pandoriaantje** [comment]
> So here I am working on changing the code so that the behavior' coincides with how you think it should work and then you give me this shit? People these days.

No, I'm just pointing out how it should behave (and is advertised to behave), wit the options active. if there there is any other behavior, it should says so in the option popup. or else the code is at fault. but you argued it is "isn't a bug"... so what am I to think?

**Comment by Pandoriaantje** [comment]
Works as intended now. for which my gratitude.
 sorry about the dissipation, nothing personal.  rough day, and your reply fueled the flame. I was under the impression my bug report was not taken serious and being discarded. Again my apologies, and thanks for the fix.

**Comment by parg** [comment]
likewise :)
