### ISSUE TITLE
Wrong URL for FAQ

### ISSUE THREAD

**Issue by sharkbit** [BiglySoftware/BiglyBT#3121]
In the Options menu -> Tracker -> Server: 

  the link for "See the FAQ for further info..." does not return the correct FAQ Anymore.  

https://github.com/BiglySoftware/BiglyBT/blob/c8e737dddee4ae9c6f128213e1d8fc4e97981db6/core/src/com/biglybt/ui/config/ConfigSectionTrackerServer.java#L153

**Comment by parg** [comment]
well, yes, as the extensive comment in that code shows...

**Comment by sharkbit** [comment]
Ahh I Like that I fond the code but didn't read the comments.  You don't want to bring that comment into your GitHub wiki

**Comment by parg** [comment]
that's why I never write comments in my code, nobody ever reads them
