### ISSUE TITLE
Automatically imports torrent files into existing torrents, and automatically merge trackers.

### ISSUE THREAD

**Issue by Zenya393** [BiglySoftware/BiglyBT#3124]
I would like a feature that:
Automatically imports torrent files into existing torrents, and automatically merge trackers.

I frequently receive different torrent files, for the same torrent/hash, with different trackers.  I need these files imported, and merged, automatically.

Currently BiglyBT is not importing new torrent files when the torrent already has been imported.

Java 17.0.9 (64 bit)
  Private Build
/usr/lib/jvm/java-17-openjdk-amd64

SWT v4962r3, gtk/3.24.33, zoom=100, dpi=96
Linux v6.1.64-Unraid, amd64 (64 bit)
B3.5.0.0/4 az3

Thank you.

**Comment by Zenya393** [comment]
> Are you talking about auto-import (Options->Files->Torrents: Import new .torrents/.magnets automatically) doing the same?

Yes please.

**Comment by parg** [comment]
Try out beta B10 please

**Comment by Zenya393** [comment]
Automatic import works, however:
I have "Delete original .torrent files after download added" selected, but the .torrent file still exists after automatically imported.

Thank you.

**Comment by parg** [comment]
B11 any better?

**Comment by Zenya393** [comment]
B11 is better.
I also noticed there's no notification or popup letting me know it was imported or trackers were merged.
My preference is notification, rather than popup.

Thank you!

**Comment by parg** [comment]
Nah, check the import log, no notifications for this.

**Comment by Zenya393** [comment]
> check the import log, no notifications for this.

I liked the idea of the Torrent Importer Log better than the notification tray (thanks).

Notes (for others):

The Torrent Importer Log viewer logs every import interval (mine is currently 10 seconds).
So imports are going to scroll off the screen and may not be seen.

![BiglyBT Auto Import](https://github.com/BiglySoftware/BiglyBT/assets/125422293/95afca99-06cc-461d-82e6-e0ec4e56767d)

I have found adding the regular expression to the filter box "Do not display lines matching this regular expression: Processing /in/autoload" to work sufficiently to suppress interval messages.

![BiglyBT Auto Import2](https://github.com/BiglySoftware/BiglyBT/assets/125422293/7c559a50-058a-4ea8-9775-52b6675eb6c7)

Thank you Parg!

**Comment by parg** [comment]
Glad it works! I might remove the "processing" log every "interval", it isn't very useful and as you say it causes more interesting logs to get lost.
