### ISSUE TITLE
BiglyBT disrupts TV (decoder)

### ISSUE THREAD

**Issue by Xuchilbara** [BiglySoftware/BiglyBT#3127]
Hello, mates.

Since my ISP changed the TV decoder I've been having problems that I've been able to confirm are related to BiglyBT (or P2P in general). Both the TV decoder and my PC are connected via ethernet to the new router, which has UPnP activated and all.

Everytime I have the program running, I get errors on my TV and can't watch many things.

I have like 600 Mbps download and like 100 Mbps upload and I barely use even 10 % of that with BiglyBT, which I always have limits set for, like upload at 1 MB/s or 3 MB/s at most, IF there's any download or upload activity at all...

I've been messing around with ports. All the same. It looks normal, ports are open.

I should mention just in case everytime I start BiglyBT it says my system is lagging or something, I've tried to remove as many torrents as possible (have around 280 now) and mess around with settings... All the same.

Can it be I need even more upload speed from my ISP, or BiglyBT is sucking too much broadband (even if it's not specified in the speed at the bottom right of the program, as in scraping for too many trackers or something), or...?

I have no clue at this point...

* OS and version: Windows 10 Pro x64 22H2 with all updates.
* BiglyBT Version Number: Just the latest one with all updates, happened with the previous version too.
* For *nix: Desktop Environment: Yes, desktop.

I hope you can help me. I eagerly await for answers.

Note: I will contact the ISP if this keeps this way, it's just I want to try everyting else first, and learn more... and solve it myself if I can.

PS: I also noticed when BiglyBT is running I frequently get errors when browsing webs and I have to refresh/reload the page a few times for it finally to work. Happens with Firefox and Edge (possible all browsers).

Thank you,

Sergi.

**Comment by parg** [comment]
Sounds like the new router is incapable of handing all of the connections that P2P applications tend to make - you say your ISP changed your TV decoder but also "new router"...

**Comment by Xuchilbara** [comment]
> Sounds like the new router is incapable of handing all of the connections that P2P applications tend to make - you say your ISP changed your TV decoder but also "new router"...

Yes, they changed the router to a new one as well as the TV decoder. Astonishing they would change the old router, which always worked perfectly, to a new, worse one... I also noticed my browsing speed is significantly more fast without BiglyBT running.

Can I do something about this lousy router... besides complaining to or changing the ISP company? Some settings like number of connections, limiting more the speed...?

Thanks a lot for the reply.

**Comment by parg** [comment]
If you have the "I2P Helper" plugin installed and don't need it then remove it.

If you only download private torrents then you could consider disabling the DHT ("Distributed Database") plugin.

**Comment by Xuchilbara** [comment]
I luckily solved it.

I complained to the ISP, they told me they would change my router for something better, precisely a Wifi 6 router or something like that.

When they finally did it, everything seems to be working as always if not even better.

So it definitely was the router/modem, they use nowadays some domestic, basic ones for everyone... except for the few of us that still do something more complex.

The technician also told me if that didn't work I could use a neutral modem and set the ISP router to «bridge» mode, so the router from the company just sends the data to the powerful modem which actually does all the connections management.

Anyway, I'm happy now and I hope this can help somebody else.

Thanks and best regards.
