### ISSUE TITLE
memory is running low

### ISSUE THREAD

**Issue by exekutive** [BiglySoftware/BiglyBT#3130]
Often I get these memory warnings in the notification area, and it progressively gets worse,  even though I'm not adding any downloads or even using the program. It's just running in the background.

The "you have X MB remaining" gets lower and lower until BiglyBT stops working.

<img width="219" alt="Screenshot 2023-12-08 at 23 02 33" src="https://github.com/BiglySoftware/BiglyBT/assets/4755215/0a983651-7d37-4e68-98a5-09df1650e4a6">

<img width="691" alt="Screenshot 2023-12-08 at 23 06 44" src="https://github.com/BiglySoftware/BiglyBT/assets/4755215/35373d47-cb68-41aa-bf92-2fcd17489bbc">

**Comment by parg** [comment]
Go to VIew->Logs->JVM Info and see what is going on. Sometime these notifications can be triggered when not really a problem

If you want you can increase the memory a bit via 

`Options->Startup & Shutdown [Java Options]: Max Heap memory size [blank=default,min=32 MB]`

Put "350m" in there (for example) and restart

**Comment by exekutive** [comment]
> Go to VIew->Logs->JVM Info and see what is going on. Sometime these notifications can be triggered when not really a problem

it actually does seem low

<img width="734" alt="Screenshot 2023-12-09 at 02 13 10" src="https://github.com/BiglySoftware/BiglyBT/assets/4755215/329c2dfa-d1a8-4dca-a099-5f2a76e592b7">

**Comment by parg** [comment]
It isn't terrible - you probably have 80MB free. 

You are running the I2P plugin, this can use a fair amount of memory. If you have memory to spare then bump the max up a bit and see how that goes.

**Comment by exekutive** [comment]
Thanks. I'll keep an eye on it.

**Comment by exekutive** [comment]
I increased it to 350 and it still seems to get eaten up.
when I first open Bigly there's lot of memory. (image 1 - 200MB free). As time goes on it drops and gets almost used up (image 2 - 20MB free).  Is this normal?
<img width="1362" alt="bigly" src="https://github.com/BiglySoftware/BiglyBT/assets/4755215/8697dcca-6698-4934-b4d3-762b29519371">
<img width="843" alt="Screenshot 2023-12-11 at 22 39 04" src="https://github.com/BiglySoftware/BiglyBT/assets/4755215/ed1a1198-1c75-4e6d-aa15-f62a7ada9af5">

**Comment by parg** [comment]
You need to look at the "alloc" value. The "max" is the maximum that the JVM will be allowed to grow to if needed. The "alloc" is how much has currently been allocated, i.e. the memory actually in use. "free" shows how much of the "alloc" is currently not in use.

The JVM is a "garbage collected" virtual machine. It is normal for there to be big fluctuations in how much of the "alloc" is "free" due to the way memory is managed.

**Comment by exekutive** [comment]
I am still getting low memory warnings. Especially when I have more than about 20-25 torrents.
Heap size is set to 478MB right now.
Can I just keep increasing it?

**Comment by parg** [comment]
Yes
