### ISSUE TITLE
Option to pause newly added torrent if disk space less than.

### ISSUE THREAD

**Issue by abegreen** [BiglySoftware/BiglyBT#3132]
I'm using RSS to download automatically and torrents are being added as queued. Very often when I don't login for a few days I experience zero disk space. Even .torrent files can't get saved to disk because every last KB is used. Many problems also happen on my seedbox when disk space gets to a zero.

I've been thinking of a few solutions for the case of low disk space:

1. Option in settings to pause newly added torrent if disk space less than XX Mb/Gb.
2. Tag constraint to auto assign tag to newly added torrent if disk space is less than XX Mb/Gb. Tag can than be used to auto switch torrent state to paused/stopped.
3. Command line command to be sent to BiglyBT by python script to pause torrent. (If even possible)

Of course any solution that comes to mind is very welcome.

Thank you.

**Comment by parg** [comment]
Probably the best solution would be to have a File option to pause a download when its save location has less that X bytes available. Pausing them when adding them doesn't really work as if you have sparse files enabled then existing downloads can use up all the space as they download anyway.

Would that work?

Alternatively there is the "Simple API plugin" - https://github.com/BiglySoftware/BiglyBT/wiki/Plugins#simple-api

I could add methods to pause/resume a download if you're keen to write some script...

**Comment by abegreen** [comment]
Thank you for such a rapid response.

I agree that "file option to pause a download when its save location has less that X bytes available" is the easiest and the most practical solution.

Whatever you think is best to prevent 0 disk space, I'll find a way to make use of.

Many thanks, love the client and love the support.

**Comment by parg** [comment]
Actually there's already a way to pause downloads when insufficient space is available on a given storage root.

`Check Tools->Speed Limits->Schedule and Settings...`

There's a command for doing this:  `storage (<root>|*) min_space=<space>`

e.g.

`storage D:\ min_space=10GB`

**Comment by abegreen** [comment]
Hi,

I've been testing this option and it does pause new torrent but as soon as the first chunk starts downloading, it allocates full size on the disk. So it doesn't prevent it to take up space, it only pauses torrent after download has already started and disk space is already allocated.

I've tried different allocate options, but Bigly always seem to allocate the full size on disk. Can I set it up to start from zero and build up the file as is downloads? (I remember that's how utorrent worked)

**Comment by parg** [comment]
@abegreen  Use "sparse files" (Files config) if available. The file might appear to be fully allocated but it will only actually use space as required. Note this only applies to newly added torrents, changing it won't affect existing downloads.

Alternatively there is the `Options->Files: Append data to files as downloaded and reorder pieces as the download progresses.` option but I much prefer sparse files to that.

**Comment by abegreen** [comment]
Sparse files option didn't do anything on my Windows 2019. But Append data as downloaded option did exactly what I needed.

Thank you for your support!
