### ISSUE TITLE
Updates Uninstalling

### ISSUE THREAD

**Issue by SimWarlock** [BiglySoftware/BiglyBT#3138]
For some reason My version keeps downgrading and requires a new update this has happened at least 4 times in the past couple months I have even reinstalled from scratch and this reoccurs 

![updates](https://github.com/BiglySoftware/BiglyBT/assets/144575246/481db2ce-497b-468b-9925-da30e597793f)
![updates 1](https://github.com/BiglySoftware/BiglyBT/assets/144575246/dab750d0-2b13-4689-a459-ca25bc93f6cd)
![Untitled](https://github.com/BiglySoftware/BiglyBT/assets/144575246/223a325e-5f02-4e9d-8ffa-b33d7facf597)

**Comment by parg** [comment]
There's no way I know of for BiglyBT to automatically downgrade itself, you'd have to somehow over-install it with an older version yourself (but you'd know this!) or the drive it was on would have to be reverted to a previous state somehow (from a backup). Neither sounds as if you wouldn't know it had happened!

**Comment by SimWarlock** [comment]
This is getting out of hand now
![2-9-24 (3-4-0-0)](https://github.com/BiglySoftware/BiglyBT/assets/144575246/83b8b0ca-451e-4d1a-9254-dc6bc07781b7)
![2-9-24 update](https://github.com/BiglySoftware/BiglyBT/assets/144575246/c70237ed-43eb-41b4-9f30-ff1e66399ba8)
![Feb 8 24 (3-5-0-0)](https://github.com/BiglySoftware/BiglyBT/assets/144575246/0c72ea13-e8e9-4b6b-be40-57a9b00b61f8)
![2-12-24 downgrade](https://github.com/BiglySoftware/BiglyBT/assets/144575246/77e77acd-93c4-4693-acd9-033e8ca84175)

**Comment by SimWarlock** [comment]
and the only way I update is with the update link I don't have the install program on the PC

**Comment by parg** [comment]
So why is one running off the C: drive and the other off the I: drive?
