### ISSUE TITLE
Keyboard CTRL-P pauses all torrents without warning

### ISSUE THREAD

**Issue by Zenya393** [BiglySoftware/BiglyBT#3139]
I accidentally hit CTRL-P on my keyboard and ended up pausing all torrents.  
Even worse, I had a _single_ torrent selected, and it still paused _all_ torrents. 
I also was only looking at a few torrents within a tagged list (12 torrents out of many in my full library), and it still looks like it paused all torrents in my library.

The problem is that some torrents were purposely paused, and I don't want to un-pause those torrents, and I have no way to tell (last active can give me some clues if old).

I selected "Start Selected Torrent" button, which appears to not start the torrents if they are stopped (which I thought it would, but glad it didn't).

Proposals:

1. CTRL-P should only be applied to the selected torrents.

2. To prevent accidents, do not pause any torrents when no torrents are selected.  Even when just the list is selected on the left pane.  You'll have to select/highlight all the torrents you want to pause.
 

*****
Java 17.0.9 (64 bit)
  Private Build
/usr/lib/jvm/java-17-openjdk-amd64

SWT v4962r3, gtk/3.24.33, zoom=100, dpi=96
Linux v6.1.64-Unraid, amd64 (64 bit)
B3.5.0.1_B11/4 az3

**Comment by parg** [comment]
LOL, that's how it works! File->Transfers->Pause

I propose you don't hit CTRL+P unless you want to pause all torrents.

**Comment by Zenya393** [comment]
What if I only want to pause the current/selected torrent using a keyboard shortcut?

**Comment by parg** [comment]
You can't. There's a million things you can't do with keyboard shortcuts.
