### ISSUE TITLE
downloaded data goes missing if I pause a torrent while it is checking after having downloaded fully

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#3140]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.5.0.0/4 az3

So, I had a torrent, downloaded it to completion, but since I'm writing to an external HDD, I didn't want my download speed to reduce while this torrent was checking, so I paused it.   What happened then is, after having downloaded a bunch more, I quit biglybt.  When I started it up at a later point, the message I got was that Error: data missing.  Why was data missing?  I have no clue.  I tried searching debug_1.log and debug_2.log fro the torrent's infohash, but it didn't show up.  So what happened is that all that data that had downloaded was now gone, after having done a forced recheck of that torrent.

**Comment by parg** [comment]
No idea, not like I can fix this from your description.

**Comment by parg** [comment]
Use "search for existing data files" if you don't know where they are. BiglyBT will not have deleted them.

**Comment by as-muncher** [comment]
@parg, ok will try that, thanks for the info

**Comment by as-muncher** [comment]
@parg, You fooled me.  Of course, when the torrent shows up in red with "Error: Data missing" of course I had to do a recheck, and yes, the data really is missing.  Why?  I don't know.
