### ISSUE TITLE
client won't load

### ISSUE THREAD

**Issue by Xemnarth** [BiglySoftware/BiglyBT#3141]
client won't load after resetting heap memory to blank (default), it keeps crashing and restarting and some times partially loading with not responding and eventually shutdown, is there a way to edit heap memory before launching the app?

**Comment by parg** [comment]
Windows? Delete %APPDATA%\BiglyBT\java.vmoptions

**Comment by Xemnarth** [comment]
Didn't seem to work even after deleting said file. Luckily I made a backup
a few days ago and used the one there. At first I tried replacing the
config file but that didn't work. Thanks for the quick response
nevertheless. Client is working now
