### ISSUE TITLE
Tags are ignored on auto-imported .magnet downloads

### ISSUE THREAD

**Issue by drelephant** [BiglySoftware/BiglyBT#3142]
```
Java 11.0.21 (64 bit)
  Ubuntu
/usr/lib/jvm/java-11-openjdk-amd64

SWT v4942r22, gtk/3.24.20, zoom=100, dpi=96
Linux v5.4.0-167-generic, amd64 (64 bit)
B3.5.0.1_B11/4 az3
```

On Ubuntu 20.04.6 LTS.

Lately I have been adding .magnet files containing magnet links as text into an auto-import folder.

This creates a Metadata download in biglybt, and I can manually add tags to that download, but when the actual torrent is downloaded, it does not inherit the tags that I added to the Metadata download.

If I add the magnet link manually, using `File-Open-URL, Magnet or Hash...`, this also creates a Metadata download, but in this case the manually-added tags will be added correctly to the torrent when it is downloaded.

**Comment by parg** [comment]
Try 3501_B12

**Comment by drelephant** [comment]
The original problem seems to be fixed in B12, but now it doesn't seem to reliably scan the auto-import folder?

In my testing just then, I needed to restart biglybt every time for the magnet download to show up, and sometimes had to restart it a few times.

Also the GUI seemed to crash a LOT more than usual, not sure if this is [this old issue](https://github.com/BiglySoftware/BiglyBT/issues/2566) rearing it's ugly head for me again...

I've attached the stdout "log" from one of those times. For this time I had a .magnet file in the auto-import folder but it wasn't picked up. This log is from the next running of biglybt, which imported the .magnet, but then the GUI became unresponsive immediately, which seems to be what is happening now - it doesn't auto-import, and then when I restart biglybt it _mostly_ then imports the .magnet, but then the GUI will immediately become unresponsive. Then I press ctrl-C in the xterm that I'm running it from and it eventually closes.

[biglybt.log](https://github.com/BiglySoftware/BiglyBT/files/13757635/biglybt.log)

**Comment by parg** [comment]
Maybe you're short of JVM heap memory - check View->Logs->JVM Info

**Comment by parg** [comment]
BTW, in case you missed it there's  separate log for torrent imports under View->Log Views->Torrent Importer

**Comment by drelephant** [comment]
Thanks again. I just tested with another .magnet, and it did have an entry in there for it saying, "Adding magnet to queue", but that magnet never showed up in the Library view.

Where is this queue and how can I see what's clogging it up?

Another thing is that the .magnet files do not always get the .imported suffix in the auto-import folder, even for some of the ones that were downloaded successfully. So maybe it's adding those to the queue again and never clearing them?

I do have the "Always rename imported torrents (".imported" suffix added)" setting enabled.

I looked in that JVM Info log view, and typically it says "[19:51:50] : cpu: SWT Thread=1%, mem: max=512.00 MB, alloc=365.00 MB, free=61.30 MB", with the free value ranging from 130 down to 30Mb. How can I make that larger?

**Comment by parg** [comment]
Sounds OK, until "alloc" gets to "max" things are going just fine as the JVM has "max-alloc" space available to allocate it if needs it. You need to check that log when things are starting to misbehave.

Also it isn't a great idea to have a lot of .magnet links being auto-imported to be honest. How many do you have? There is no way to see the "queue", it is an internal one and a bit of a hack.

**Comment by drelephant** [comment]
> How many do you have?

There's 7 in the folder now, but I've stopped using auto magnet importing for the moment because it's so unreliable at picking them up (needs a restart nearly every time), and doesn't auto-rename them after so would leave a lot of messy files in there for me to clean up later.
