### ISSUE TITLE
A poorly configured inconvenient default settings which is bad for users and the functioning of torrents

### ISSUE THREAD

**Issue by mx5kevin** [BiglySoftware/BiglyBT#3145]
* OS and version Windows 10
* BiglyBT Version Number 3.5.0.0

-Not easy to setup run at system startup with minimized mode.

Default way run at system startup are not set up. If the user set it up hard to run it minimized mode. It opens the program at every startup, which is annoying.

-Previous torrents not seeded, the torrent's status are QUEUED, DHT Trackers are stopped.

It arbitrarily stops older torrents seeding, which is not good at all.

-In the installation install default way I2P and Tor helper plugin. Without it the Public/Anonymous network are not bridged!

From simple users are not expected to make complicated settings. The default settings in the current setup are incorrect.

**Comment by parg** [comment]
Thanks for the feedback.
