### ISSUE TITLE
Disable "separate download" dialogs?

### ISSUE THREAD

**Issue by coyote3** [BiglySoftware/BiglyBT#3148]
Is there a way to disable the "Media has already been added as...Do you want to add this torrent as a separate download?" popups?

I like the 'do you want to add the trackers' messages, but I'm never going to want multiple instances of a torrent.

**Comment by parg** [comment]
I'll make it an option to remember your previous decision

**Comment by coyote3** [comment]
Sounds great, thank you very much!
