### ISSUE TITLE
When removing networks from a torrent, the current peers are dropped

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#3150]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.5.0.0/4 az3

If I have Public, I2P, and Tor as the networks for a torrent, and I have the Peers tab showing, I can see that if I deselect "I2P", that all the connected peers are dropped, and if I deselect Tor, too, I see that the same thing happens.  Then, peers are reconnected, and the download speed goes up again.

**Comment by parg** [comment]
That's how it works, don't mess around with the networks on a running download (for one it can reveal your I2P identity - https://github.com/BiglySoftware/BiglyBT/wiki/I2P#network-mixing )
