### ISSUE TITLE
Losing access to local connection

### ISSUE THREAD

**Issue by SoundFactor** [BiglySoftware/BiglyBT#3151]
* OS NVidia Shield Pro and version 9 - (8.2.2)
* BiglyBT Version Number 3.3.4

I've been losing access to my local connection and can't see any of my torrents, I had to re-install the app the last time this happened and it temporarily fixed it but ended up losing my torrent list. I did this last week and it has recently happened again, at this rate, I can't be re-installing the app weekly since it's a huge pain to set up.

**Comment by SoundFactor** [comment]
I fail to see a solution here. Why is this closed?

**Comment by parg** [comment]
because nothing is going to be done about it

**Comment by SoundFactor** [comment]
You didn't even try. Good one.

**Comment by parg** [comment]
Its an Android bug, report it to the Android project
