### ISSUE TITLE
Unselected files still downloading

### ISSUE THREAD

**Issue by osprey012** [BiglySoftware/BiglyBT#3154]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=144
Windows 8.1 v6.3, amd64 (64 bit)
B3.5.0.0/4 az3

I have a file that is 64 GB, I unselected the majority of files and kept four files, which was about 6,3 GB. The files I unselected also do not show when 'hide files not selected for download' is checked. However, BiglyBT tried to still allocate 64 GB, and when I checked my downloads folder, it had allocated space for the files I had unselected. When I verified that they were unselected and tried again, I saw the unselected files being allocated in my downloads folder in realtime. I have had this issue continually, with　other　folders　where　I　unselect　half　of　the　files,　they　were　still　all　downloaded.　I do not believe this is an issue of partial portions of other files being downloaded with the files I want to download. I ended up setting the priority of the unselected files from do not download to delete to fix the issue, but that has to be done after the file configuration pop-up.

**Comment by parg** [comment]
Try Options->Files: Use sparse files when supported by the file system
