### ISSUE TITLE
GUI becoming unresponsive when multiple items selected

### ISSUE THREAD

**Issue by drelephant** [BiglySoftware/BiglyBT#3155]
On Ubuntu 20.04.6 LTS, running biglybt inside a vnc session.

```
Java 11.0.21 (64 bit)
  Ubuntu
/usr/lib/jvm/java-11-openjdk-amd64

SWT v4942r22, gtk/3.24.20, zoom=100, dpi=96
Linux v5.4.0-169-generic, amd64 (64 bit)
B3.5.0.1_B15/4 az3
```

I can reliably make the Biglybt GUI completely unresponsive by selecting multiple items in the Library using shift-click.

I seem to see this error on the sysout quite often when it happens (amongst many others, but this one seems the most common last error before the GUI freezes):

```
DEBUG::Mon Jan 08 10:47:50 AEDT 2024::com.biglybt.core.security.SESecurityManager::installServerCertificates::133:
  Certificate install failed for 'https://127.0.0.1:80/'
    connectSocketAndWrite (UrlUtils.java:2524), connectSocketAndWrite (UrlUtils.java:2363), connectSocketAndWrite (UrlUtils.java:2340), runSupport (ClientIDManagerImpl.java:647), AERunnable.run, ThreadPool.runIt
javax.net.ssl.SSLException: Unsupported or unrecognized SSL message
        at java.base/sun.security.ssl.SSLSocketInputRecord.handleUnknownRecord(SSLSocketInputRecord.java:457)
        at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:175)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1511)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1421)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:427)
        at com.biglybt.core.security.impl.SESecurityManagerImpl.installServerCertificates(SESecurityManagerImpl.java:1301)
        at com.biglybt.core.security.impl.SESecurityManagerImpl.installServerCertificates(SESecurityManagerImpl.java:1041)
        at com.biglybt.core.security.SESecurityManager.installServerCertificates(SESecurityManager.java:133)
        at com.biglybt.core.util.UrlUtils.connectSocketAndWrite(UrlUtils.java:2524)
        at com.biglybt.core.util.UrlUtils.connectSocketAndWrite(UrlUtils.java:2363)
        at com.biglybt.core.util.UrlUtils.connectSocketAndWrite(UrlUtils.java:2340)
        at com.biglybt.pifimpl.local.clientid.ClientIDManagerImpl$httpFilter.runSupport(ClientIDManagerImpl.java:647)
        at com.biglybt.core.util.AERunnable.run(AERunnable.java:36)
        at com.biglybt.core.util.ThreadPool.runIt(ThreadPool.java:336)
        at com.biglybt.core.util.ThreadPool$threadPoolWorker.run(ThreadPool.java:726)
        at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:334)
```
I run biglybt by running `~/biglybt/biglybt 2>&1 > biglybt.log` in an xterm.

When the GUI is unresponsive the only way I know to cleanly kill biglybt is to press `Ctrl-C` a few times in the xterm.

How can I diagnose what is happening to make the GUI unresponsive, and is the Certificate Install error a likely cause?

**Comment by parg** [comment]
The certificate install is unlikely to be related.

See https://github.com/BiglySoftware/BiglyBT/wiki/Diagnostics for details of how to grab some diagnostics

**Comment by drelephant** [comment]
Of course it hasn't crashed today and I've been multi-selecting, etc...

I just tried going to [http://127.0.0.1:45100/setinfo?name=AZMSG&value=AZMSG;0;config;log-diags;;](http://127.0.0.1:45100/setinfo?name=AZMSG&value=AZMSG;0;config;log-diags;;) and it didn't come up with anything but a 20x20 black square? This is the html when I inspect:

```
<html><head><meta name="viewport" content="width=device-width; height=device-height;"><link rel="stylesheet" href="resource://content-accessible/ImageDocument.css"><link rel="stylesheet" href="resource://content-accessible/TopLevelImageDocument.css"><title>setinfo (BMP Image, 20&nbsp;×&nbsp;20 pixels)</title></head><body><img src="http://127.0.0.1:45100/setinfo?name=AZMSG&amp;value=AZMSG;0;config;log-diags;;" alt="http://127.0.0.1:45100/setinfo?name=AZMSG&amp;value=AZMSG;0;config;log-diags;;"></body></html>
```

Is this right?

**Comment by parg** [comment]
Yes, that's what it is supposed to do. It triggers a thread dump to the debug_1/2.log files

**Comment by parg** [comment]
And also ThreadDump.log

**Comment by drelephant** [comment]
Oh, yeah sorry I should have read that page more carefully. I'll get the log next time it happens.

**Comment by parg** [comment]
ThreadDump.log should still be in the logs folder unless you've manually deleted it

**Comment by drelephant** [comment]
Yes, there are those files in the log folder, but I'll wait until it crashes again next and get them, because I last ran that diagnostics thing while biglybt was actually still working.

Thanks again for the help.

**Comment by drelephant** [comment]
Hopefully I can still comment on this closed issue...

OK it just happened again.

I dropped a few torrents into my auto-import folder, then I opened biglybt, shift-selected three torrents, then right-click, "organize-tags" and selected the tag I wanted to add.

That particular operation seems to often lock it up.

Here's the debug files:
[debug_2.log](https://github.com/BiglySoftware/BiglyBT/files/14019391/debug_2.log)
[ThreadDump.log](https://github.com/BiglySoftware/BiglyBT/files/14019392/ThreadDump.log)
[debug_1.log](https://github.com/BiglySoftware/BiglyBT/files/14019393/debug_1.log)

**Comment by parg** [comment]
Seems to be stuck in a native call from the SWT UI library we use

    SWT Thread: Runnable, 7940ms CPU, B/W: 79/522
        app//org.eclipse.swt.internal.gtk.GDK.gdk_window_get_origin(Native Method)
        app//org.eclipse.swt.widgets.Control.toDisplay(Control.java:1747)
        app//com.biglybt.ui.swt.skin.SWTBGImagePainter.buildBackground(SWTBGImagePainter.java:532)
        app//com.biglybt.ui.swt.skin.SWTBGImagePainter$2.runSupport(SWTBGImagePainter.java:203)

Not a lot to be done :( 

Are you running in a VM? Also there should be a SlowUI" log there as well, might as well post that here if you can find it,

**Comment by drelephant** [comment]
No, not in a VM. In a vnc session (tigervnc).

[SlowUI_2.log](https://github.com/BiglySoftware/BiglyBT/files/14023627/SlowUI_2.log)
[SlowUI_1.log](https://github.com/BiglySoftware/BiglyBT/files/14023628/SlowUI_1.log)

**Comment by drelephant** [comment]
Thanks for checking it out.

I'm not even sure what WM is running in the vnc session really.

I run KDM locally on that PC, but my ~/.vnc/xstartup file has these lines (cobbled together from googling when I've had problems with stuff over the years):

```
x-window-manager &
gnome-panel &
gnome-settings-daemon &
metacity &
```
