### ISSUE TITLE
Unallocated and Sparse File Moves?

### ISSUE THREAD

**Issue by Zenya393** [BiglySoftware/BiglyBT#3156]
When moving unallocated files/torrents to another drive, does BiglyBT copy the fully file/torrent allocation?  
Or does BiglyBT copy zero byte files?

Same question for sparse files.
When moving sparse files/torrents to another drive, does BiglyBT copy the fully file/torrent allocation?  
Or does BiglyBT copy zero byte files?

Java 17.0.9 (64 bit)
  Private Build
/usr/lib/jvm/java-17-openjdk-amd64

SWT v4962r3, gtk/3.24.33, zoom=100, dpi=96
Linux v6.1.64-Unraid, amd64 (64 bit)
B3.5.0.1_B16/4 az3

**Comment by parg** [comment]
I replied to the original post, didn't see you had editted it so missed the bit about "unallocated".

**Comment by as-muncher** [comment]
The same thing happens to me - I choose in BiglyBT to move the data to a new location, and it copies over the zero byte files too and doesn't just copy over the sparse data to the new location.  Zero byte files are copied at full size as if they were complete.
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.5.0.0/4 az3
