### ISSUE TITLE
BiglyBT is allocating when that's off, creating thousands of zero byte files

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#3158]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.5.0.0/4 az3

sparse files is on
A torrent downloaded through magnet, torrent creation window came up, queued, then I went to force start it, and it's now allocating.  I had chosen just to download .jpg files at first, and now I see that there are thousands of them.  I see BiglyBT is "allocating", and I open the directory in Windows Explorer and see the directory structure created, but also thousands of zero byte files created.  This is not necessary.  Those files only need to be created when data is actually written into those files, either directly from the web or swarm merging.  Then of course, if you want to move the data, these zero files get moved at full value too taking up unnecessary space.  I would just continue writing on a similar Github Issue that covered the same topic, but the issue is closed now, and I am doubtful that any attention gets paid to fixing an issue that is closed here on Github but is not really solved, so thus this new issue.  If this is unacceptable, then in the future, I will just append to a closed issue.

**Comment by as-muncher** [comment]
Plus, since there are tens of thousands of files in this torrent, the .!qB extension is not being added.  I think @parg mentioned that there's a limit for the .!qB extension or other extension for incomplete files to be added, but maybe that should not be the case, and especially not the case where it's allocating - that should not happen whatever the # of files in the torrent.  Thanks.

**Comment by parg** [comment]
Remove the torrent, add it again and only select the files that you want to download.

If you start a torrent with file X selected for download then file X will be created, that's how it works.

**Comment by as-muncher** [comment]
@parg The thing is, I usually download all the files in a torrent.  Perhaps you could see this issue as a problem with BiglyBT, not a problem with my method.
