### ISSUE TITLE
how increase available memory?

### ISSUE THREAD

**Issue by coyote3** [BiglySoftware/BiglyBT#3159]
![BiglyBT-memory](https://github.com/BiglySoftware/BiglyBT/assets/30500973/d8122017-e954-47d3-a359-990c95e09673)

I got this Warning which said the Wiki would give details, but the Wiki page said "BiglyBT does not have a wiki page for this topic yet".

I have vastly more RAM on the PC (128 GB) than I ever use.  Memory configuration advice please?

Java 1.8.0_333 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=200, dpi=96
Windows 11 v10.0, amd64 (64 bit)
B3.5.0.1_B16/4 az2

**Comment by parg** [comment]
Change the line in that screenshot 

Options->Startup & Shutdown [Java Options]: Max Heap memory size [blank=default,min=32 MB]
