### ISSUE TITLE
[Suggestion] 'Random' button for connection ports

### ISSUE THREAD

**Issue by adem4ik** [BiglySoftware/BiglyBT#3160]
1. Open Tools > Options > Connection

**Suggested result:** both TCP and UDP port numbers have `Random` button similar to qBittorent's one.

**Use-case:** sometimes user can be very lazy to think about proper port number, so he can just press that button to get a random one.

![изображение](https://github.com/BiglySoftware/BiglyBT/assets/4707112/134692fc-87ed-4b91-91c7-5c83d9545ce8)

**Comment by parg** [comment]
The port is already randomised, if they want to change it then they can figure that out themselves.
