### ISSUE TITLE
Two clicks are necessary to close a menu (File, View, Community, Tools, etc)

### ISSUE THREAD

**Issue by glaubersm** [BiglySoftware/BiglyBT#3164]
Hi

I'm using version 3.5 on Arch Linux running the Wayland session of KDE Plasma 6 RC1 desktop environment.

Java 21 (64 bit)
  N/A
/usr/lib/jvm/java-21-openjdk

SWT v4942r22, gtk/3.24.39, zoom=100, dpi=96
Linux v6.7.0-arch3-1, amd64 (64 bit)
B3.5.0.0/4 az3

Steps to reproduce:
1. open BiglyBT
2. click on any menu on top (File, View, Community, Tools, etc) - the menu opens, as expected
3. click on the same menu again - the menu remains open
4. click on the same menu again: now the menu closes

Expected result: the menu should close after the step 3

**Comment by parg** [comment]
Not within our control, that's up to the OS/SWT library I'm afraid.

**Comment by parg** [comment]
In case you're wondering, I'm the only one really supporting BiglyBT, I don't use Linux and I don't have time to go around installing release candidates of display manager X on Linux version Y to look into a bug that isn't in the BiglyBT code base.

**Comment by glaubersm** [comment]
I can't reproduce on X11 session. Probably it's a bug related to Xwayland.
Thanks for your help.
