### ISSUE TITLE
Add "save path" to "column setup"

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#3169]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.5.0.0/4 az3

Sometimes, torrent data may be saved to different locations.  It's handy to have a clear way to see where those are, a sortable column.

**Comment by parg** [comment]
Save Path is already a selectable column in the Library views...

![image](https://github.com/BiglySoftware/BiglyBT/assets/395293/b0f2ade0-0dff-49a5-b087-d87f5dc8dfdf)

**Comment by as-muncher** [comment]
apologies, thank you
