### ISSUE TITLE
Latency of report charts

### ISSUE THREAD

**Issue by arturum** [BiglySoftware/BiglyBT#3171]
Hi,

Not the big issue, as overall BiglyBT is a GREAT piece of software, but for the aficionados it can be quite unnerving...
Both spotted on torrent details Speed tab, but I believe it occurs across entire UI.

1.  The time axis and the scale of both Time left and Speed charts don't match. When the chart is rescaled (to fit the top value) the labels on the vertical axis update only after next refresh.

2. The 'current' value label (where the line crosses the vertical axis - either time or speed) is always displayed one refresh cycle AFTER the actual change - i.e. it is always either below or above the actual line/axis crossing.

If these are possible to fix, it would be great for the users, who (like me) find watching the torrent progress quite mesmerising...

Best! And thanks for this great app!

Java 1.8.0_392 (64 bit)
  Azul Systems, Inc.
/Applications/BiglyBT/.install4j/jre.bundle/Contents/Home

SWT v4944r26, cocoa, zoom=200, dpi=72
Mac OS X v14.2.1, aarch64 (64 bit)
B3.5.0.0/4 az3

**Comment by parg** [comment]
The "current" value is deliberately (according to the code...) the average of the last 6 values, hence it trails around. Obviously whoever wrote it wanted this behaviour. I agree it is confusing, could change it to be the latest value I guess, someone will complain though...

**Comment by arturum** [comment]
Ah OK - now it makes sense (though should be explained in the legend
perhaps).

But are the horizontal axes not following scale change (to fit current
visible top value) also deliberate? Can't see the reason...


wt., 30 sty 2024 o 10:49 parg ***@***.***> napisał(a):

**Comment by parg** [comment]
I'll fix a few things up, I agree the current behaviour is crap.

**Comment by parg** [comment]
(I've known for ages, just been ignoring it :)

**Comment by arturum** [comment]
:D
Yeah, it is not that I just spotted it also - just dared to complain only
now...

wt., 30 sty 2024 o 11:48 parg ***@***.***> napisał(a):

**Comment by parg** [comment]
Actually can you give some more detail on the axes scaling issue? The vertical scale seems to resize correctly when I change the height of the charts

**Comment by arturum** [comment]
It is regarding the automatic updates of the scale.
When torrenting is in progress, and the chart flows, it re-scales
automatically to fit the min and max values. E.g. vertical axis for ETA
shows anything from 0 to 57 yrs... When the time passess by (and the
highest value disappears from the screen), the whole chart rescales to show
the current max value near the top edge. But the labels on the axis stay
the same (e.g. 57 yrs), until next refresh (1 sec in my settings), when
they are updated to values matching the new scale / new max (e.g. 7 hrs).
Same with sudden slow down of transfer - when the ETA rises, because of a
slowdown, the top label still shows, say, 5 min, though the scale of the
chart has been updated. Only after next display refresh, they change to
values matching the scale (e.g. 2 hrs).

Essentially it seems that the chart is updated first, and the vertical axis
value follows with the next refresh.



wt., 30 sty 2024 o 12:03 parg ***@***.***> napisał(a):

**Comment by parg** [comment]
Try beta B24 - join the beta program via the Help menu option, it should then update you

**Comment by arturum** [comment]
Hah, just tested! Works perfectly!

Thanks heaps!

Now I need to find a torrent large enough to sit and watch for hours :)

wt., 30 sty 2024 o 19:26 parg ***@***.***> napisał(a):

**Comment by parg** [comment]
Don't dare to complain about anything else though :)
