### ISSUE TITLE
Moving data to Library (Windows)

### ISSUE THREAD

**Issue by KonradKl** [BiglySoftware/BiglyBT#3172]
When I try to move completed download(s) to Libraries/Documents,  then an error message with text "Library is chosen. Choose  folder instead." appears.
Then if I choose from Recent Places "Libraries/Documents/My Documents" (that is pointing to exactly the same location) the location is accepted.
I am using polish version of Windows, so translations may be a bit inaccurate. 

Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=96
Windows 7 v6.1, amd64 (64 bit)
B3.5.0.1_B23/4 az3

**Comment by parg** [comment]
It is a Windows error message, not a BiglyBT one...

e.g. https://stackoverflow.com/questions/5425758/how-can-i-get-the-commonopenfiledialogs-initialdirectory-to-be-the-users-mydoc
