### ISSUE TITLE
Disable file allocation

### ISSUE THREAD

**Issue by Xemnarth** [BiglySoftware/BiglyBT#3176]
Is there a way to disable file allocation if no pieces are received similar to how qBittorent works? My cliently currently allocates all files as soon as a torrent is started. Also, if files' priority are set to 'Do not download', they're fully allocated anyway...

**Comment by parg** [comment]
Use "sparse files" (under Files settings)

**Comment by Xemnarth** [comment]
I tried with a small file, it still allocates when 0 seed and no peers active

**Comment by as-muncher** [comment]
@parg, @Xemnarth   "Sparse files" does not keep BiglyBT from allocating.  If you restart BiglyBT, BiglyBT will do the same thing all over again - spend time "Allocating".  Maybe in the current session, BiglyBT will not allocate when you switch to sparse files, but all the times afterwards, it will allocate.  It could be an issue with libtorrent - I don't know if you use that.
