### ISSUE TITLE
Request: Child tags inhert column setup from parent

### ISSUE THREAD

**Issue by Zenya393** [BiglySoftware/BiglyBT#3182]
When creating child tags, I want the child tags to inherit the column setup from the parent.

I it would also be nice to establish a column setup template that is automatically reused when creating new views.

Java 17.0.9 (64 bit)
  Private Build
/usr/lib/jvm/java-17-openjdk-amd64

SWT v4962r3, gtk/3.24.33, zoom=100, dpi=96
Linux v6.1.64-Unraid, amd64 (64 bit)
B3.5.0.1_B27/4 az3

**Comment by parg** [comment]
You can copy column setup details from the Column Setup dialog and apply them to other views - see the import/export buttons in the right panel - obviously still a manual process.

**Comment by parg** [comment]
Oh, next beta (B29 when it is built) has the "reset" button (or reset columns menu item) reset things to the default settings if you've set them. Plus there's a bug fix in there with the existing changes.
