### ISSUE TITLE
When i open chrome from biglybt it opens http://single-argument/ in addition to desired page

### ISSUE THREAD

**Issue by kotenok2000** [BiglySoftware/BiglyBT#3183]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
e:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B3.5.0.1_B28/4 az3
When i press "Google Search Name" it opens http://single-argument/ in addition to correct page.
Looks like command line syntax was changed.

![image](https://github.com/BiglySoftware/BiglyBT/assets/8822292/def685dd-d71d-4f84-8a72-6ab284000592)

![image](https://github.com/BiglySoftware/BiglyBT/assets/8822292/fdb4e27a-6e47-436b-b1f1-480a603e1178)

**Comment by parg** [comment]
Fixed in plugin aercm version 1.1 available to Beta users - thanks.

**Comment by kotenok2000** [comment]
I am already on version 3.5.0.1_B28
I can't find it at plugins.biglybt.com

**Comment by parg** [comment]
Should update if you go to Help->Update

**Comment by kotenok2000** [comment]
It doesn't update when i press "check for updates"

**Comment by parg** [comment]
Probably cached state - try a restart sometime.
