### ISSUE TITLE
Jackett search

### ISSUE THREAD

**Issue by LuvBiglyBT** [BiglySoftware/BiglyBT#3185]
Been dealing with Jackett not able to search my subscriptions for the last week and a half.  It started working for 2 days last week and then stopped again.  Anyone have any ideas why this is happening?

Thanks.

Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B3.5.0.0/4 az3

![BiglyBT error2](https://github.com/BiglySoftware/BiglyBT/assets/34841335/068f6788-b86e-40af-a9fc-9662899cc125)

**Comment by parg** [comment]
No idea, looks like a probem with "extra.to"
