### ISSUE TITLE
This is getting out of hand now

### ISSUE THREAD

**Issue by SimWarlock** [BiglySoftware/BiglyBT#3186]
This is getting out of hand now
![2-9-24 (3-4-0-0)](https://github.com/BiglySoftware/BiglyBT/assets/144575246/83b8b0ca-451e-4d1a-9254-dc6bc07781b7)
![2-9-24 update](https://github.com/BiglySoftware/BiglyBT/assets/144575246/c70237ed-43eb-41b4-9f30-ff1e66399ba8)
![Feb 8 24 (3-5-0-0)](https://github.com/BiglySoftware/BiglyBT/assets/144575246/0c72ea13-e8e9-4b6b-be40-57a9b00b61f8)
![2-12-24 downgrade](https://github.com/BiglySoftware/BiglyBT/assets/144575246/77e77acd-93c4-4693-acd9-033e8ca84175)

_Originally posted by @SimWarlock in https://github.com/BiglySoftware/BiglyBT/issues/3138#issuecomment-1939532566_

**Comment by parg** [comment]
Don't waste my time creating new issues
