### ISSUE TITLE
Systray icon does not work with Waybar (xembed?)

### ISSUE THREAD

**Issue by o0nd7ots** [BiglySoftware/BiglyBT#3188]
Hello,
I wanted to start using Bigly on my new rig with just a window manager (wayland compositor) installed.
I noticed that waybar did not show notifications of Bigly, contrary to KeePassXC for example.

I have read that might is due to waybar not supporting the legacy `xembed` (yet?).
If it is so, I suggest adding the newer standard to bigly.

* BiglyBT Version: 3.5.0.0

**Comment by parg** [comment]
There's nobody that works on BiglyBT who will ever get around to looking at this unfortunately.

Please feel free to figure out how to get things working and then send over a pull request.

Cheers
