### ISSUE TITLE
Bencoded response malformed

### ISSUE THREAD

**Issue by BotGGias** [BiglySoftware/BiglyBT#3189]
Hi, 
not sure what informations i need to provide, i tested BiglyBT 3.5. On some trackers its working fine. On others i get this error message for Scrapes. Whats does it mean - how can it be fixed? 
I replaced the trackerurl since i think its not supposed to be public

`[20:56:16.542] {tracker} Error from scrape interface https://***trackerurlredacted***.php : Bencoded response malformed: BDecoder: unknown command '195, remainder = �†(Òýÿd8:completei3e10:downloadedi2e10:incompletei0eeee; `

When i use QBittorrent on the same tracker that error does not appear.

---------------
Java 21.0.2 (64 bit)
  Azul Systems, Inc.
c:\program files\zulu\zulu-21

SWT v4956r12, win32, zoom=100, dpi=96
Windows Server 2012 v6.2, amd64 (64 bit)
B3.5.0.0/4 az2

**Comment by parg** [comment]
That'd be the tracker that is returning shite.
