### ISSUE TITLE
Re-evaluate piece downloads more often

### ISSUE THREAD

**Issue by as-muncher** [BiglySoftware/BiglyBT#3190]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.5.0.0/4 az3

So, if I am downloading a torrent, what I'm seeing happen is BiglyBT will start downloading a couple of files in the torrent, when I have set the priority to High or High (3), but then when I select some other files and change the priority to High (6), BiglyBT is still continuing with the two files in my torrent, and all the files I set to priority High (6) have at least 2 seeds.  Perhaps then, BiglyBT needs to check the download priority a little more often, because 5 minutes later, those two files are still being downloaded, and I have "download in sequential order" unchecked.  Is there a way to see if "Sequential Download from file" is active?  It doesn't show in the options if I right-click the torrent.

**Comment by parg** [comment]
The piece picker reavaluates things very frequently, hover over the pieces in the piece map view to see their priorities.
