### ISSUE TITLE
Creating Torrent: Lose all torrent info/objects when going back to first screen.

### ISSUE THREAD

**Issue by Zenya393** [BiglySoftware/BiglyBT#3191]
### Undesired Behavior:
When creating a torrent, after I add files, clicking the back button removes all the files/folders/containers that I previously added.

### Desired Behavior:
I should be able to move around the Create Torrent wizard, back to the first screeen, and not lose the input information of what I've already started to create.
***
Java 17.0.9 (64 bit)
  Private Build
/usr/lib/jvm/java-17-openjdk-amd64

SWT v4962r3, gtk/3.24.33, zoom=100, dpi=96
Linux v6.1.74, amd64 (64 bit)
B3.5.0.1_B30/4 az3

**Comment by parg** [comment]
Should be fixed in B31 - please check that it all works as expected
