### ISSUE TITLE
Creating Torrent: Title Display Name

### ISSUE THREAD

**Issue by Zenya393** [BiglySoftware/BiglyBT#3192]
### Current Behavior:
When creating a torrent, the display title/name of the torrent uses the container name.  

### Desired Behavior:
I would like the torrent display title/name that is different from the container name.
I use the container name for the storage folder structure.
I use the title/name for the "Displayed Name".

***
Java 17.0.9 (64 bit)
  Private Build
/usr/lib/jvm/java-17-openjdk-amd64

SWT v4962r3, gtk/3.24.33, zoom=100, dpi=96
Linux v6.1.74, amd64 (64 bit)
B3.5.0.1_B30/4 az3

**Comment by parg** [comment]
Not possible, that is how torrents work,

**Comment by parg** [comment]
https://wiki.theory.org/BitTorrentSpecification
