### ISSUE TITLE
AutoSpeed not doing anything

### ISSUE THREAD

**Issue by Zenya393** [BiglySoftware/BiglyBT#3193]
In the status bar I selected "Auto" for auto speed download limit.
In the configuration I setup Auto Speed to limit the download speed to 7.81 MB/s.
But when I look at the download speed, it is 12 MB/s, and I'm expecting a maximum of 7.81.

![BiglyBT AutoSpeed](https://github.com/BiglySoftware/BiglyBT/assets/125422293/7b61350f-efff-43e7-845d-ada0ddbd3f17)

There's also some strange UI behavior.  I can't tell if auto is truly selected, or unlimited:
![BiglyBT AutoSpeed 1](https://github.com/BiglySoftware/BiglyBT/assets/125422293/64e2df82-2a3e-4cbe-baa2-d9469d005bf3)

***
Java 17.0.9 (64 bit)
  Private Build
/usr/lib/jvm/java-17-openjdk-amd64

SWT v4962r3, gtk/3.24.33, zoom=100, dpi=96
Linux v6.1.74, amd64 (64 bit)
B3.5.0.1_B30/4 az3

**Comment by parg** [comment]
If it doesn't work for you then don't use it. It doesn't work very well.
