### ISSUE TITLE
 IPv6 binding plugin interferes with connection 

### ISSUE THREAD

**Issue by hilarleo** [BiglySoftware/BiglyBT#3199]
since installing   IPv6 binding plugin on OSX 12.7.2 having   issues familiar from  github.com/BiglySoftware/BiglyBT/issues/1662 .  magnets appear to sit in the client for weeks waiting for megainfo. sometimes a cluster of torrents will suddenly download- Aha, yes! i are the crackhead coder. Disabling the plugin has not resolved the hangup. If only the OSX GIGO interwebs of compulsory commerce could locate a link to the magical Plugin-removal Wizard i read in the comments!

**Comment by parg** [comment]
Not really a useful bug report is it?
