### ISSUE TITLE
Download for subscription

### ISSUE THREAD

**Issue by Gunni** [BiglySoftware/BiglyBT#32]
Sometimes i notice download for subscription appearing after adding a torrent to downloads.

![rcfrjk9](https://user-images.githubusercontent.com/358099/29493428-2dac6644-8585-11e7-8a3c-2ab26787c245.png)

Sometimes i even see dozens of them.

I have no subscriptions.

**Comment by parg** [comment]
That is BiglyBT looking up subscriptions for things you are downloading -
they are descriptions of the subscriptions and once downloaded they will
appear against the relevant download. For example, if you download 'Fred_1'
and another user has also downloaded 'Fred_1' by using a subscription
*they* have (e.g. 'The Fred Series') then you will be shown details of 'The
Fred Series' in case you also want to subscribe to it

**Comment by Gunni** [comment]
Is that what pops sometimes up as "Web browser has been disabled"? because that's annoying me sometimes too.

**Comment by parg** [comment]
Not sure about that - the use of an Embedded web browser within BiglyBT is small - where are you seeing this exactly?

**Comment by Gunni** [comment]
Sometimes after i add a torrent, that dialog pops up.

**Comment by parg** [comment]
Can you go to Tools->Options->Interface->Display, scroll down to the 'Internal Browser' section and un-select the 'disable all use of the internal browser'? Hopefully that'll make your problem go away.

**Comment by Gunni** [comment]
No you misunderstood, i don't want an internal browser, and the popup telling me its disabled is annoying. Additionally can I disable the subscription feature completely?

**Comment by parg** [comment]
You can't not have it - it is probably the donation window popping up and not displaying due to a previous issue (did you migrate from Vuze?) with the browser it uses.

Tools->Options->Subscriptions
