### ISSUE TITLE
[BUG] Unit3D PT's RSS without size.

### ISSUE THREAD

**Issue by i990049** [BiglySoftware/BiglyBT#3201]
* OS and version：window 10
* BiglyBT Version Number 3.5.0.0
This is other PT's RSS with size.
[img]https://s2.loli.net/2024/03/02/NhtqbzHDSX2ZBrk.png[/img]
This is Unit3D PT's RSS without size.
[img]https://s2.loli.net/2024/03/02/6NLlFaSwmpiUqtW.png[/img]

**Comment by parg** [comment]
What does the actual RSS content show? i.e. the XML

**Comment by i990049** [comment]
> What does the actual RSS content show? i.e. the XML

https://at-12project.cc/
https://itatorrents.xyz/register/null
Here are the Unit'3D PT site. You can change the language in the control panel or use the broswer to translate it into English. BiglyBT RSS don‘t show the size, but other Nexusphp PT site is OK.

**Comment by parg** [comment]
I'll fix BiglyBT in the next beta to parse the size out from the description but it would be better to state it explicitly.

How to do so has some "history" but one approach is to use something like

```
<rss xmlns:torrent="http://xmlns.ezrss.it/0.1/" version="2.0">
    <channel>
        <item>
        <title>sdsdsd</title>
        <torrent:contentLength>134483319</torrent:contentLength>
        <torrent:infoHash>33DEFFAA6BFC49E510AB17881BADB74CF2DE2596</torrent:infoHash>
```

**Comment by parg** [comment]
Try 3501_B35 (see the Help menu to join the beta program)

**Comment by Roardom** [comment]
Hello @parg,

May I ask which RSS specification is the most relevant to implement? I see https://www.bittorrent.org/beps/bep_0036.html. Is it up to date, or is there another specification more rigorously followed by modern clients. Any links to examples properly implementing the spec would also be great. Our current RSS xml template can be found here: https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/master/resources/views/rss/show.blade.php

Regards.

**Comment by Roardom** [comment]
Thank you for the details. I spent many additional hours looking into it and I think I'm going to make our RSS torznab-compatible - it seems to be the leading RSS specification for torrents from what I can tell.

**Comment by parg** [comment]
ok, if you have an example feed using that then if you give me the link I can ensure BiglyBT works with it!
