### ISSUE TITLE
I want to add comments to tag constraints

### ISSUE THREAD

**Issue by Zenya393** [BiglySoftware/BiglyBT#3202]
Within the Tag Constraint section, I would like the ability to:

1. Ignore (or comment out) a line of code/constraint. 
2. Add comments.
3. Disable constraint.

This also makes it easier to test constraints.

***
Java 21.0.1 (64 bit)
  Private Build
/usr/lib/jvm/java-21-openjdk-amd64

SWT v4962r3, gtk/3.24.33, zoom=100, dpi=96
Linux
B3.5.0.1_B33/4 az3

**Comment by parg** [comment]
Try 3501_B34. Only whole line comments are supported, prefixed by # or //

For example

`// blah`
`# wibble`

**Comment by parg** [comment]
B35 supports # // comments anywhere on a line and also /* */
