### ISSUE TITLE
Bigly no longer working on Plasma 6

### ISSUE THREAD

**Issue by SalamiMommy** [BiglySoftware/BiglyBT#3208]
GUI could not be loaded. java.lang.ClassNotFoundException: org.eclipse.swt.widgets.Display

6.8.1-artix1-1
Bigly 3.5.0.0-1
KDE Desktop Plasma 6

**Comment by parg** [comment]
Please submit more debug - run it in a terminal,

**Comment by SalamiMommy** [comment]
Sorry, I'm relatively new. Is that just typing biglybt -v ?

**Comment by SalamiMommy** [comment]
Starting BiglyBT...
Suitable java version found  [java = openjdk 21.0.2]
./biglybt: line 148: unzip: command not found
SWT check failed with: java.lang.ClassNotFoundException: org.eclipse.swt.widgets.Display
Loading BiglyBT:
changeLocale: *Default Language* != English (Canada). Searching without country..
changeLocale: Searching for language English in *any* country..
changeLocale: no message properties for Locale 'English (Canada)' (en_CA), using 'English (default)'

BiglyBT started at 25-Mar-2024 22:57:30
DEBUG::Mon Mar 25 22:57:30 MDT 2024  Data Missing: /run/med/hom/Gam/Tor/Ric
DEBUG::Mon Mar 25 22:57:30 MDT 2024  Data Missing: /run/med/hom/Gam/Tor/[Na
DEBUG::Mon Mar 25 22:57:30 MDT 2024  Data Missing: /run/med/hom/Gam/Tor/Ric
DEBUG::Mon Mar 25 22:57:30 MDT 2024  Data Missing: /run/med/hom/Gam/Tor/Dem
DEBUG::Mon Mar 25 22:57:30 MDT 2024  Data Missing: /run/med/hom/Gam/Tor/Dar
Bind IPs not resolved: tun0

See Tools->Options->Connection->Advanced Network Settings
Attempting to load aliases from: /home/home/.biglybt/console.aliases.properties
Running BiglyBT 3.5.0.0...
Using configuration settings from:
  /home/home/.biglybt/
> -----
Available console commands (use help <command> for more details):

  [] xml   [#] hack   [a] add   [] create   [c] check   [q] queue   
  [r] remove   [tar] torrent_archive   [s] start   [h] stop   [] host   
  [] publish   [] forcestart   [tl] tlog   [m] move   [rs] runstate   
  [] share   [+] set   [sh] show   [u] ui   [] logout   [] quit   [?] help   
  [] echo   [] logging   [] alias   [] prio   [] plugin   [pair] pairing   
  [ar] archive   [cfg] config   [subs] subscriptions   [tag] tag   
> -----
Update available for 'Core Patch Checker', new version = 
Apply these updates with the 'plugin update' command

**Comment by parg** [comment]
./biglybt: line 148: unzip: command not found

Try installing zip ?

**Comment by SalamiMommy** [comment]
Reinstalling unzip solved the issue, thanks!

**Comment by parg** [comment]
weird that it was missing - hopefully a one-off!
