### ISSUE TITLE
Add option of Copy torrents to... when completed (automatic contents backup)

### ISSUE THREAD

**Issue by Xuchilbara** [BiglySoftware/BiglyBT#3210]
This is a feature suggestion or request. If this isn't the right section, forgive me, I don't know/can't find where this is done.

I would love if BiglyBT would **automatically copy** the torrents, their contents, their files, when they're **completed** to another location (device) in order to make a backup just in case the main HDD/SSD has a malfunction or some issue. I think now there's an option to move them, but I want to make duplicates, not move the contents. It would be nice if this new feature was global of course, not per torrent, or maybe both options.

After losing many many files due to various HDD getting broken suddenly and without warnings, I'm now doing this manually, and it's quite a time waster and annoying task, not to talk about when I can't access the computer for a few hours.

Why not download the torrent again in case of failure, you say? Because I don't want to waste more expensive energy and HDD working lifespan, plus many torrents have very few seeds or as low as just one and could be your last chance to download it.

So... What do you think? Thank you!

**Comment by parg** [comment]
Feature already exists - you need to use tags to do it (see https://github.com/BiglySoftware/BiglyBT/wiki/Tags#manual)

If you want it to happen automatically then you need to arrange for downloads to be automatically assigned to that tag. Use a "Tag Constraint" to do this - the most simple one is to use a constraint of "true" - this will result in all downloads being assigned to the tag.

**Comment by Xuchilbara** [comment]
Man, BiglyBT really is a feature-filled program...

Seems a bit complicated though, that's why I couldn't figure it out while looking for it around the menus...

Having to use tags and then programming the copy of the tagged torrents... I would look into it, but that's new to me... and I've been using Vuze and BiglyBT for decades, thousands of torrents!

Then the suggestion would be possibly making it simpler for the average user maybe if possible?

Thank you (also for the fast reply)!

**Comment by parg** [comment]
If I Google `"copy on complete" biglybt` it comes up :)

There's a lot of automation possible with Tags which is why it is there. If it was a commonly asked for feature then perhaps it could be made "simpler" to find, however I prefer in general to add features to Tags as they can then be used in a more flexible way. 

For example, you can have different "copy on complete" locations based on, say, which trackers they use.
