### ISSUE TITLE
Bad scrape URL /a/scrape

### ISSUE THREAD

**Issue by zzzi2p** [BiglySoftware/BiglyBT#3211]
* Java 1.8.0_402 (64 bit)  Private Build /usr/lib/jvm/java-8-openjdk-amd64/jre
* SWT v3836, gtk/null, zoom=100, dpi=96 Linux v6.5.0-26-generic, amd64 (64 bit)B3.2.0.0/4 az3
*  i2p plugin 2.1.0.1.1

OP @vituperative of your ticket #2452 from two years ago bugged me about it today, I had been stumped on it and gave up last year.

I am still stumped. Actually tried to reproduce with biglybt and zzzot tracker and no luck. OP has local mods and that may have something to do with it.

But what I do see is biglybt "guessing" a scrape URL http://example.i2p/a/scrape from an announce URL http://example.i2p/a - that's not going to work on zzzot, it's going to either return 404 or serve you the zzzot home page or serve you the announce page. Perhaps under some circumstances with a non-UTF8 GET info_hash param to some page (not the announce or scrape page) that is expecting only UTF-8 params, the encoding error could appear. (it also depends on whether the URL is /tracker/a/scrape or /a/scrape; we support both /tracker/a and /a, but the results vary if you add /scrape to the end)

The ancient bittorrent spec said to replace "announce" with "scrape" to get the scrape URL, otherwise if "announce" is not in the URL then scrape is not supported. The current spec doesn't say that, but appending "/scrape" to the URL as a guess seems worse then replacing "/a" with "/scrape". I verified that bigly does convert /announce to /scrape, but converts /a to /a/scrape.

We're going to try to update zzzot to handle /a/scrape and /tracker/a/scrape, but you should probably fix it on your side also. Either don't attempt to scrape unless the URL has "announce" in it, as the old spec said, or do better at guessing the scrape URL.

**Comment by parg** [comment]
"back in the day" there was a tracker(s) where appending "/scrape" to the URL worked - from the comment in the code

```
    // some trackers support /scrape appended but don't have an /announce
    // don't do this though it the URL ends with .php (or infact .<anything>)
```

Whether these still exist I do not know but given how stagnent the bittorrent landscape is I am wary of changing the behaviour...

**Comment by zzzi2p** [comment]
You could special-case it down as far as you want to go, check for */a, or *.i2p/*/a, or http://*/*/a, or http://*.i2p/*/a, to avoid breaking something else. I'm sure most trackers are on udp, so you could craft something appropriate that's http-only, or i2p-only, or both.

Ref: #2452, after further investigation we've confirmed it was caused by OP's flawed local mods, which forwarded scrapes to a target that expected UTF-8 params.

**Comment by parg** [comment]
Out of interest, if you support scrape then why aren't you simply using /announce in the URL? Why /a ?

**Comment by zzzi2p** [comment]
zzzot supports both /announce and /a, can't control what people put in their torrents, but tbh never before noticed the "/announce means we support /scrape" thing in the original spec, now in BEP 48

**Comment by parg** [comment]
Added support for /a in next beta
