### ISSUE TITLE
Enhancement Request: Add a "select all" option for the open torrent screen

### ISSUE THREAD

**Issue by Dramaman** [BiglySoftware/BiglyBT#3213]
Hello,

It would be nice to have a "select all" option to select all torrents on the open torrent screen - that or a check box option

![Screenshot 2024-03-27 101413](https://github.com/BiglySoftware/BiglyBT/assets/76974959/ae6e869c-ca0b-438f-bf3c-6fe485890b32)

this would make it easier for touch screens users

**Comment by parg** [comment]
don't have a touch screen but you can use CTRL+a to select all

**Comment by parg** [comment]
Oh, and there's a "select all" in the right-click menu when invoked on a torrent entry

**Comment by Dramaman** [comment]
> don't have a touch screen but you can use CTRL+a to select all

yes, but this is annoying on a touch screen or phone as you need to bring up the full virtual keyboard to get those buttons :)

**Comment by parg** [comment]
added menu option to header in next beta
