### ISSUE TITLE
Does Swarm Discovery search queries have length limits?

### ISSUE THREAD

**Issue by bnm12** [BiglySoftware/BiglyBT#3214]
I try to filter my searches in Swarm Discovery pretty precisely, so I have quite the long list of negative filters, some plain and some using more advanced RegEx to avoid common patterns.

I find that every time my search string hits about 250 chars in length I suddenly don't get any results for queries that will return plenty results with a just slightly shorter query.

Are there any known limitations here that are just not listed in the docs, or is this some kind of weird edge case where the search times out or something?

https://github.com/BiglySoftware/BiglyBT/wiki/User-Interface#searching-swarm-discoveries

**Comment by parg** [comment]
Are you talking about the filters in a subscription created from a swarm discovery result? Or the swarm discoveries search results "filter" box (top right). Or the swarm discoveries search expression itself?

**Comment by bnm12** [comment]
Specifically the swarm discoveries search expression itself (it also breaks subscriptions created from such a search) 
![image](https://github.com/BiglySoftware/BiglyBT/assets/2268946/3070ab13-1063-44ef-b865-11f8983c657c)

I think I've managed to work around it by searching simple and then using the "without words" filter on the subscription when it's created. That seems to handle longer strings so far.

After some poking around I also think I've learned how to create a template and using "Depends on" to manage my generalized filters. But I gotta admit it was hard to find any information on how that worked exactly

**Comment by bnm12** [comment]
I have actually found a few issues with using the "Without Words" filters too. One is probably to be considered a bug, the other is more of a design choice

1. Filters are forced lowercase, which probably isn't an issue since the matches seem to be case insensitive. *Except* RegEx tokens can have different meanings depending on if they are upper or lowercased such as `\w` vs `\W` which is currently causing me some issues
2. The max results for a subscription can be reached without it showing any results when using filters this way since the result is still counted when it's filtered. This would probably be fine and expected if the filters seemed a bit more temporary, but seeing as they are configured and saved possibly even with the "Depends on" templating it does seem like a bit of a strange choice to show and count unread results that aren't even visible. And considering that there's no way to apply complex filters to the query to actually exclude the results due to the ~250 char limit

**Comment by parg** [comment]
I'll fix it so that regular expressions aren't lowercased (although they will still employ case-insensitive matching) so the \w \W type of issue is fixed.

Also when you save a filter I'll ensure that non-matching results are removed.

If you change a depend-on template itself you will need to go and explicitly save any dependent subscriptions to have their now non-matching results removed, I don't intend to change this unless it really seems to be a big issue.

**Comment by bnm12** [comment]
I think that alleviates my primary pains. Thank you

**Comment by parg** [comment]
(the 250ish character limit on the swarm search can't easily be increased - it is caused by a UDP packet serialisation limit which ain't easy to raise - I'll limit the entry box text limit to at least make the restriction visible)

**Comment by bnm12** [comment]
I figured that might be the case as 250 seems suspeciously close to a power of 2 which might indicate some low level datastructure restriction. I think limiting the input box more clearly communicates the limitations of the feature so that's good. Maybe consider adding a "Max 250 chars" help text to the label also so it's communicated ahead of time rather than when the user suddenly (and probably unexpectedly) hits the textbox limit

**Comment by parg** [comment]
No problem :)
