### ISSUE TITLE
Locks up when trying to remake links

### ISSUE THREAD

**Issue by Midnight-Starseed** [BiglySoftware/BiglyBT#3215]
When trying to remake links bigly locks up, sometimes taking the whole system down. Its worse when selecting 2 or more finished torrents to try to fix. I reinstalled bigly, even removing all old config data in case I was restoring errors each time I restored bigly. This helped but has not fixed the issue. Trying to import previously downloaded torrents and remaking the links is impossible. To reproduce move files on the computer so bigly cant see them. Then try selecting a few and right clicking then search for existing data files. Occasionally it works but it will eventually freeze.

I've used bigly for a few years, before that vuze, before that azureus. Bigly used to be stable but this issue started a few releases ago. Sorry if this has been reported before I did a few searches but could't find it so I'm posting this.

Linux Mint 21.3  Reinstalled 04/03/24
3.5.0.0
Cinnamon

**Comment by parg** [comment]
If your system is completely hanging then I would suggest something more fundamentally wrong with it than a BiglyBT issue - perhaps a disk problem?

If BiglyBT itself is hanging while the system continues to function then you should find something of use in the SlowUI_1/2.log files in ~/.biglybt/logs (or the Debug log files there) - take a look

Also you may be able to trigger some thread dumps, take a look at https://github.com/BiglySoftware/BiglyBT/wiki/Diagnostics#biglybt-hangs-or-is-slow-to-respondreact

**Comment by Midnight-Starseed** [comment]
Thanks for the reply. It's definitely bigly causing it and mostly when I try to remake links. I used to repair computers for a living. I'll  have a look at the files you suggested and get back to you. Have you not got this behaviour your end?

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by parg** [comment]
Not had any other reports of it

**Comment by Midnight-Starseed** [comment]
One other thing worth mentioning. When the UI freezes, bigly is still working in the background. I know because when I'm downloading torrents and bigly freezes I have system monitor running and can see the data coming down the network. When bigly is close to finishing a torrent and the UI locks up, I use system monitor to see when it finishes the download. I then give it a certain amount of time to move the finished file into the folder I preselected and check the torrent. Then I click the x top right which brings up the "force close" window and shut bigly down and restart.

This behaviour is on two different computers and at least three different ssd drives. Multiple OS reinstalls and at least two bigly fresh reinstalls in case I was compounding errors by restoring bigly backups. I'm wondering if Its the specific settings I have in bigly whether that's  why it locks up for me? idk, I looked through the log files you suggested but couldn't see anything although I don't now what I'm looking for nothing jumped out to me.

I'm going to try reinstalling bigly but keep default settings and see if that stabilises it.




------------------------------------------------------------------------------------
Many Thanks
________________________________

**Comment by Midnight-Starseed** [comment]
I've reinstalled bigly. I kept all the settings on default and started changing one at a time, mostly relating to where I download and move torrents to when finished. I started to import my previously downloaded torrents most of which are in my nas. Bigly has started locking up. I videoed a couple of small clips to show you bigly ui frozen but its working in the background. They're only a couple of mins each but they show you what is happening. Hope this is ok.

[https://res.cdn.office.net/assets/mail/file-icon/png/video_16x16.png]Bigly Lockup.mp4<https://1drv.ms/v/s!AgFxI8ClV08Fgw54cazbyHXS1XhO>
[https://res.cdn.office.net/assets/mail/file-icon/png/video_16x16.png]Bigly Lockup 2.mp4<https://1drv.ms/v/s!AgFxI8ClV08Fgw9r0kW9YXoKPpqM>

I had to upload to onedrive as they were a bit too big to email. When bigly locked up I just grabed my phone and recorded, so my dialog was unrehersed. Hopefully you can understand what I'm showing you.


------------------------------------------------------------------------------------
Many Thanks
________________________________

**Comment by parg** [comment]
What would be most useful is if you looked for the log files I asked for in my initial reply (and also perform the action to trigger a thread dump when the UI is locked up) - thanks!

**Comment by Midnight-Starseed** [comment]
Apologies for missing what you said before.

I have done what you asked and attached the relevant files. The thread dump shows "locked by java" would that help you identify the problem? I attached the slow ui in case they are helpful to you. I don't know what I'm looking at.

Hope this helps. I would love to get to the bottom of this issue.



Glen

------------------------------------------------------------------------------------
Many Thanks
________________________________

**Comment by parg** [comment]
No attachments... Feel free to email them over to paul@biglybt.com if that's easier

**Comment by parg** [comment]
Thanks for the logs. It seems that things are hung up in native UI code:

   SWT Thread: Runnable, 63650ms CPU, B/W: 102/565
        app//org.eclipse.swt.internal.gtk.GDK.gdk_window_get_device_position(Native Method)
        app//org.eclipse.swt.widgets.Display.getWindowPointerPosition(Display.java:6121)
        app//org.eclipse.swt.widgets.Control.gtk_motion_notify_event(Control.java:4164)
        app//org.eclipse.swt.widgets.Widget.windowProc(Widget.java:2348)
        app//org.eclipse.swt.widgets.Control.windowProc(Control.java:6830)
        app//org.eclipse.swt.widgets.Display.windowProc(Display.java:6077)
        app//org.eclipse.swt.internal.gtk.GTK.gtk_main_do_event(Native Method)
        app//org.eclipse.swt.widgets.Display.eventProc(Display.java:1537)
        app//org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(Native Method)
        app//org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4568)

which is an external library. Are you running in a VM of some kind?

**Comment by Midnight-Starseed** [comment]
No vm.




------------------------------------------------------------------------------------
Many Thanks
________________________________

**Comment by parg** [comment]
No idea then, sorry :( If possible could you another flavour of Linux/window manager?

**Comment by Midnight-Starseed** [comment]
Well at least I have some idea of which direction now to try and get to the bottom of it. If I ever figure it out I'll get back to you.




------------------------------------------------------------------------------------
Many Thanks
________________________________

**Comment by parg** [comment]
please do!

**Comment by Midnight-Starseed** [comment]
A quick question.

Do you think if I compiled the source for bigly on my system would that help? Yes, no or maybe




------------------------------------------------------------------------------------
Many Thanks
________________________________

**Comment by parg** [comment]
Don't think it would help, the issues you're seeing don't appear to be related to the BiglyBT code directly
