### ISSUE TITLE
Large (in both size and file count) torrents sometimes dropping state, when file selection modified while active

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#3218]
As I've mentioned in the past, I frequently work with large (tens or more gigabytes in size) torrents containing thousands of files. Most of the time, I'll select only a subset of the contents for download, at least initially, but will often adjust those selections later.

On more than one occasion, recently, I've observed the following when interacting with such torrents:

#### Initial setup
1. Import the torrent and initially disable all of its files.
2. Select for download, or use SFEDF to enable for seeding, some subset of the torrent's contents.
3. Queue the torrent, then let it complete downloading the requested files and enter Seeding mode.

#### The problem
1. With the torrent still Queued, enter its Files view.
2. Select additional contents for downloading by checking additional files.
3. At some point, the torrent will lose the download state of its contents (that's normal and has always happened), **BUT**...

* Where the loss of state **used to** always trigger a "Checking" pass that would re-populate the already-downloaded files' completion percentage...
* **RECENTLY** (over the past couple of months, at least, by my rough estimate), instead of automatically going into "Checking..." mode, the torrent will sometimes (not always, but not infrequently) remain in active state, with its "Remaining:" size equal to the size of **all enabled files**, even the already-downloaded ones.

In order to avoid re-downloading the entire selected contents of the torrent, it's necessary to manually Stop it and Force Re-Check. That will re-populate the download state, and reduce the "Remaining:" size to just the newly-enabled (not yet downloaded) files.

Then, the torrent can be re-Queued and it will proceed as normal.

The automatic triggering of "Checking..." mode after a loss of completion state just seems to have become unreliable, whereas in the past it always ran whenever needed.

#### System block

Java 11.0.22 (64 bit)
  Red Hat, Inc.
/usr/lib/jvm/java-11-openjdk-11.0.22.0.7-1.fc39.x86_64

SWT v4956r12, gtk/3.24.41, zoom=100, dpi=96
Linux v6.7.9-200.fc39.x86_64, amd64 (64 bit)
B3.5.0.1_B42/4 az3

Running under LXQT on Fedora 39 x86_64

**Comment by parg** [comment]
I'll have a fiddle - no idea what might have changed but there's definitely some scope for improving the handling of things

**Comment by parg** [comment]
try B44, might have improved things, might not :)

**Comment by ferdnyc** [comment]
@parg Thanks for trying! Unfortunately, no love so far.

I opened up one such torrent, total size of 204GB of which I've downloaded-or-shared 24.95GB, enabled a swath of ~10 files in a row, then started clicking down the following ones one at a time.

When I hit the 4th or 5th checkbox (so, 14-15th newly enabled file), the completion percentage column blanked. Going back to the General tab, the torrent was still Downloading, but now showed "Remaining: 25.35GB". Stopping and force-checking it got it back to showing the correct "Remaining: 394.95MB".

**Comment by parg** [comment]
How about B45?

**Comment by ferdnyc** [comment]
Good question... now, at least so far, I _can't get it_ to ever **lose** the completion data at all.

Which makes it hard to confirm the auto-Checking behavior, but I'll tolerate it. :wink: (Nice!)

**Comment by parg** [comment]
Closing as seems to be OK

**Comment by ferdnyc** [comment]
Yeah, I didn't want to close it as fixed on the basis of my simply failing to trigger the behavior, in case you came back with, "But I didn't fix that, it should still lose state eventually." But all seems well!
