### ISSUE TITLE
make console ui more "bash-like"

### ISSUE THREAD

**Issue by moham96** [BiglySoftware/BiglyBT#322]
Hi,
I run biglybt using console ui but sometimes it feels very difficult to deal with, here are some problem that I wish get fixed so the user can interact with it more easily:
1-Biglybt is not catching signals such as SIGINT to interrupt the ongoing procces instead when pressing ^C(control+c) the proccess is killed, this could be helpfull,for example when I tried installig a plugin then decided to cancel the proccess.
2-Enable arrow keys like in bash: for example upper arrow key should show last commands executed, left and right arrow to edit the current command

**Comment by moham96** [comment]
Hi, any progress on this?
I run biglybt on a headless vps server and it is very hard to change settings,the webui is basic and doesn't allow much settings and since biglybt doesn't have a thin client like transmission and deluge have I'm forced to use consoleui to change settings but it's extremely hard.
1- It's hard to find the setting you're looking for, just typing `set` reveals all the settings but no way to search them, adding a search function to search through the settings would be nice
2- The settings also need a short description next to them(the same description in the `swt` ui), I was trying to add a directory for biglybt to automatically add torrents files  "Import new .torrent/.magnet automatically) and i still can't get the setting name (id? i don't know what its called in consoleui) i tried to search for "import", "auto" and nothing, I found out later that it's called "Watch Torrent Folder" !! this is not the same name of the setting in the swt ui, these names need to be consistent or at least have consistent description when listed through the `set` command.

PS:This  could be a very big change but replacing the basic webui that comes with biglybt with a feature rich webui that includes all the settings could be useful for people running biglybt on headless seedboxes, I like the webui of deluge in this manner since all the settings are available through the desktop ui are available though the webui, even if you install a plugin, it's settings are available through the webui

Regards

**Comment by TuxPaper** [comment]
If you have v2.0.0.0, check out the `cfg` command.  It will list its params if you specify none.  `cfg` groups config by section, lets you search, and has the descriptions avail.

For fun, here's the output of `cfg queue` :
![image](https://user-images.githubusercontent.com/725353/59566942-96cc5100-901b-11e9-9cbc-6e7f3acd174d.png)


From your OP, arrow keys and last command aren't easily doable due to Java.  Java's access to console input is only received after you press enter :(  There's some pre-compiled binary hacks for specific OSes out there, but I'm not sure how well they work, how safe they are, or how maintained there are.  However, it might be more possible for key-events via the telnet UI, but no effort has been made to look into it yet.

**Comment by moham96** [comment]
@TuxPaper Wow, cfg looks very promising this should've been included when consoleui was introduced, I'm sure it will come in handy for me on the vps I'm running biglybt on, nevertheless this only covers the configuration part of managing biglybt seedbox, there are many other features that can't be used other than using the swt interface right now(e.g swarm merging and chat) so I have to run the swt interface from time to time on my vps(run mainly in consoleui and then pass ui swt as an argument) I found some bugs in this approach and I will open separate issues for them.

> From your OP, arrow keys and last command aren't easily doable due to Java. Java's access to console input is only received after you press enter :( There's some pre-compiled binary hacks for specific OSes out there, but I'm not sure how well they work, how safe they are, or how maintained there are. However, it might be more possible for key-events via the telnet UI, but no effort has been made to look into it yet.

hmmm, how about just saving a text file in `~/.biglybt` with the last commands in it and then retrieve last command with each up arrow pressed(similar to `.bash_history` file)? sorry if I didn't fully understand the issue you described.

Regards
