### ISSUE TITLE
Connections drop in-n-out after limiting upload speed

### ISSUE THREAD

**Issue by DohnJoe2** [BiglySoftware/BiglyBT#3223]
I'm getting these pattern-like connection drops after setting the upload speed limit, while unlimited speed limit works fine with no drops. 
Tried googling around, went through Issues here but couldn't figure a fix for it yet. 

Statistics screenshots
![Screenshot_4](https://github.com/BiglySoftware/BiglyBT/assets/132614863/70387482-2ba6-42fe-84c9-facafd868844)
![Screenshot_5](https://github.com/BiglySoftware/BiglyBT/assets/132614863/fa01889d-8c5e-4cf6-8c7d-17cb669aff55)
![Screenshot_6](https://github.com/BiglySoftware/BiglyBT/assets/132614863/06e05d85-f040-4a1b-92d1-7db214e000e2)

Video (10x sped up)
https://github.com/BiglySoftware/BiglyBT/assets/132614863/9cce457b-322f-4eb7-914c-4eec143b9f25

Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B3.5.0.1_B46/4 az3

**Comment by parg** [comment]
From the video it seems that when upload stalls the downloads are entering a "queued" state and then going back to "seeding" - is this correct?

**Comment by parg** [comment]
Perhaps you could post your "configuration changes" - see the Help menu -> Advanced. Make sure you remove anything you don't want to be made public.

**Comment by parg** [comment]
One other thing, if you go to "View->Log Views->Start/Stop Rules" then there might be some clues there as to why the downloads are entering a "queued" state.

**Comment by DohnJoe2** [comment]
> Perhaps you could post your "configuration changes" - see the Help menu -> Advanced. Make sure you remove anything you don't want to be made public.

https://pastebin.com/pvKFttSL

I noticed that "Max Uploads=6, Max Uploads Seeding=6" doesn't reflect "Queue > Max only when seeding=1", but "max active torrents=2, max downloads=2" does reflect correctly. 
Maybe this could be the culprit of the problem, that it over-saturates my network somehow and everything drops with only 100kbs available bandwidth at that moment?

> One other thing, if you go to "View->Log Views->Start/Stop Rules" then there might be some clues there as to why the downloads are entering a "queued" state.
> 
> Note you have to enable "Options->Queue: Log debug information"

A couple of these "Ignored somethingChanged: new scrapeResult (RT_ERROR)", I think just before or after dropping the connections.

**Comment by parg** [comment]
There should be more logging than that around the time that the a seeding download flips from Seeding to Queued giving some info as to why.

In the meantime can you try disabling "Options->Queue: Don't start any more torrents when upload/download speed limit is reached" to see if that changes things?

**Comment by DohnJoe2** [comment]
> There should be more logging than that around the time that the a seeding download flips from Seeding to Queued giving some info as to why.
> 
There's a sea of logging statements of course, I only could make sense of that error keyword - I can send you the full log.

> In the meantime can you try disabling "Options->Queue: Don't start any more torrents when upload/download speed limit is reached" to see if that changes things?

I have it checked from the beginning and also "Options->Queue->Seeding: Upload limit approximation (percentage or absolute reduction in KB/sec)" to 40% - doesn't help.

Here's the current situation with unlimited upload speed. 8 active for some reason, when I would rather it to be 1 or 2. 
In Configuration Changes it says: "Max Uploads=8, Max Uploads Seeding=8".
![Screenshot_4](https://github.com/BiglySoftware/BiglyBT/assets/132614863/57257bed-0afa-45cf-9150-b6cec6f9f421)

**Comment by parg** [comment]
Overall configuration settings of "Max Uploads=8, Max Uploads Seeding=8" refer to the number of PEERs that an individual download will concurrently upload to by default (upload slots as they are called). They are configured until Options->Transfer.

Control of active downloads is configured under Options->Queue (max active torrents etc)

**Comment by DohnJoe2** [comment]
So, I unchecked the "Options->Queue: Max when only seeding [0:unlimited]" which was previously set to 1 and I think the drops are gone, not yet entirely sure though. 
When I go to the Configuration Changes, the "Max Uploads=8, Max Uploads Seeding=8" is not shown.

**Comment by DohnJoe2** [comment]
Confirmed, the "Options->Queue: Max when only seeding [0:unlimited]" was the root cause of the connection drops. 
![Screenshot_3](https://github.com/BiglySoftware/BiglyBT/assets/132614863/03985399-5212-4201-98bc-aeac40b4f37d)

**Comment by Seeker2** [comment]
If there is only 1 upload slot per torrent, it may be the optimistic unchoke upload slot which often picks peers that are "barely interested" or hopelessly slow, triggering at the least upload speed stalls -- falling near or to 0 speed.
