### ISSUE TITLE
remote pairing

### ISSUE THREAD

**Issue by Thermalgeek2** [BiglySoftware/BiglyBT#3228]
hello been using biglybt for some time now, had migrated from vuze
since i live in a house where we share internet we get it free but open port on houses router, only the one i own myself, and while using vuze even if it was only in my room, it was nice to see progress on my phone, but since i migrated to biglybt, i havdt been able to do that no more it just.. hangs, D:
What can i do to fix this?

* win 10 22h2
* BiglyBT 3.5.0.0
* For *nix: Desktop Environment

**Comment by parg** [comment]
Tools->Options->Connections->Pairing shows information about your current pairing deatils. There's a link you can click on there to see current registration details. That opens a webpage - at the bottom there is a "services" section, the "biglyby web remote" plugin shows there as "xmwebui". There should be a test link on the right for IPv4. Try that.

**Comment by Thermalgeek2** [comment]
the first link "sid:  protocol=https port=9091 [client IPv4] "failed
the tunnel says it succeded, 
but when i tried in the biglybt's web remote plugin it says (in bigly bt app downleft of main screen there is a plugin section and its there) it says Attempting direct secured connection: https://xxx.xxx.x.xx:9091/
    Failed: Tunnel unavailable for a further 16s due to failure, HTTP GET for https://xxx.xxx.x.xx:9091//pairing/tunnel/create?ac=xxxxxxxx&sid=xmwebui failed, Connection refused: connect
Attempting proxy secured connection: https://pair.biglybt.com/
    Failed: Tunnel unavailable for a further 15s due to failure, Authentication failed: Bad authorisation response: {op=4, status=failed}

**Comment by Thermalgeek2** [comment]
checked without the https and just did http, nothing D :cant even seem to acces it on computer normally either when i go in test , and checked the detected local ipv4 and it is indeed my computers ip adresse

**Comment by Thermalgeek2** [comment]
also got a yellow popup saying it failed to listen on web remote

**Comment by Thermalgeek2** [comment]
also when i try connect it via access code it seems to be hanging hope all that could help a little

**Comment by parg** [comment]
Check VIew->Log Views->Bigly Web Remote for any logs.

If it is failing to listen then something is borked with your local network setup/antivirus/firewall.

**Comment by Thermalgeek2** [comment]
strange.. no errors.. but phone cant find it, and when i try use web, it says Please make sure BiglyBT is running and accessible.but ports are open..

**Comment by parg** [comment]
Any bind ips set in "Options->Connection->Advanced Network Settings [Socket Options]: Bind to local IP address or interface" ?

**Comment by Thermalgeek2** [comment]
nothing in the place is written

**Comment by parg** [comment]
oh well, works for others so must be some issue with your network config - closing as not planning to do anything more on this.
