### ISSUE TITLE
[GUI] the scroll bar doesn't always show after running the program

### ISSUE THREAD

**Issue by moham96** [BiglySoftware/BiglyBT#323]
Hi,
This happened to me on my Linux machines I don't know if it happens on windows.
the problem is after opening the program the left scrollbar doesn't show immediately, I need to change to another sub-tab so the scroll bar appears.
I know this is a minor bug but it does affect the user experience

![deepin-screen-recorder_select area_20180122091756](https://user-images.githubusercontent.com/10559702/35208152-d00e76f6-ff57-11e7-95fa-3542eabd602a.gif)

**Comment by parg** [comment]
Seen that happen occasionally but not reliably enough to be able to track it down :(

**Comment by Havokdan** [comment]
Yes, its happen in windows for while.

**Comment by parg** [comment]
Managed to reproduce it on Windows - potential fix in the next beta (B07, should be out today or tomorrow)

**Comment by moham96** [comment]
@parg that's great

**Comment by parg** [comment]
Well B07 is out - tell me if it helps. I'm a little unsure as...
1) I found an issue with my attempted fix
2) Removed the fix to look at it again and then completely failed to reproduce the original problem :(
3) So put back a modified fix that doesn't cause the related issue but I haven't been able to test that it works

grrr!

**Comment by parg** [comment]
Let's hope it hasn't just decided to hide for a while like it did for me :)
