### ISSUE TITLE
BiglyBT will not close BiglyBT Launcher on my new Windows 11 laptop

### ISSUE THREAD

**Issue by joliett** [BiglySoftware/BiglyBT#3230]
When I close BiglyBT the file BiglyBT Launcher does not close - as seen in Win11 task manager.  
I installed Java 8 after reading BiglyBT uses java for its interactions with system files, but still BiglyBT Launcher will not close.

When BiglyBT would close on my older computer, it would take a significantly longer process, while now it closes instantly.

**Comment by parg** [comment]
Do you have "Options->Interface->Display [Various]: Wait for BiglyBT to close tidily on exit/restart and display progress" enabled?

**Comment by joliett** [comment]
Yes OPTIONS is  CONFIGURED CORRECTLY...but still the program closes
instantly.

**Comment by parg** [comment]
And you're closing it the File->Exit menu ?

**Comment by joliett** [comment]
Yes!

**Comment by joliett** [comment]
The problem with ignoring the failure to close properly problem, is that
the BiglyBT log directory keeps growing.  I had 60 files in there.
I wish this closing error could be fixed.  Regards, Joel

**Comment by parg** [comment]
Perhaps you can grab some debug?

Close BiglyBT and kill the background process.
Clear out the logs directory completely.
Start BiglyBT.
Exit BiglyBT to reproduce the problem.
Follow the procedure here:

https://github.com/BiglySoftware/BiglyBT/wiki/Diagnostics#biglybt-hangs-or-is-slow-to-respondreact

Kill the background process.
Zip up the entire logs directory.
Rename the .zip file to something like "debuglogs" (some mailers don't like .zip files)
Email the "debuglogs" file tome at paul@biglybt.com.

Thanks

**Comment by parg** [comment]
ah!, no problem!
