### ISSUE TITLE
Windows - No update for 3.5 ?

### ISSUE THREAD

**Issue by eurobank** [BiglySoftware/BiglyBT#3234]
Running 3.5 on Windows 11 and it seems there is no update of 3.6?

Also trying to manually update, the installer says 3.5.

Am i missing something?

**Comment by eurobank** [comment]
Ok, we had to download the guthub release  for 3.6 manually

https://github.com/BiglySoftware/BiglyBT/releases/tag/v3.6.0.0

**Comment by parg** [comment]
Autoupdate is phased, it'll get to everyone eventually

**Comment by eurobank** [comment]
I get that, still the installer was 3.5.
