### ISSUE TITLE
Provide more flexibility for storing unmarked files

### ISSUE THREAD

**Issue by vadimplSPb** [BiglySoftware/BiglyBT#3235]
According to https://github.com/BiglySoftware/BiglyBT/wiki/Torrents-and-Files#why-are-files-being-createdallocated-on-disk-when-they-are-deselected now BiglyBT forcibly saves parts of files that the user does not need at all.
The maximum that BiglyBT currently offers is to create a subfolder for such files, which does not solve the problem of "garbage" in this directory of the disk in any way.

Therefore, I suggest adding the ability for the user to specify not just a subfolder, but the prefix of the absolute path on another disk, and BiglyBT will add the path:

Example:
The default path for "garbage" (one setting for all downloads) specified by the user: Z:\PiecesOfFiles\
The path to download a specific torrent: D:\DirDownload\Torrent1\
The full path for storing "garbage" for this torrent = "Z:\PiecesOfFiles\" + "D:\DirDownload\Torrent1\" = Z:\PiecesOfFiles\D\DirDownload\Torrent1\

What will it give:

1) the user will have the content of the disc downloaded at this location that meets his requirements;

2) the user will be able to optimally allocate disk space.
For example: the download disk has a block size of 2048 KB (on one disk I really have this), the disk for storing "garbage" is the standard 4 KB

**Comment by parg** [comment]
Nothing has changed and I'm not going to implement that as it beaks torrents should you come to reseed them.
