### ISSUE TITLE
option to autohide empty tags, and tag groups in the sidebar

### ISSUE THREAD

**Issue by Dramaman** [BiglySoftware/BiglyBT#3237]
It would be great to have an option to autohide empty tags in the sidebar. This includes: Manual tags, tag groups, categories, and download states.
2 ways I can suggest

1. You could have a global setting in the tags option menu. The option to "show in sidebar" would still need to be selected for each individual tag you want to show (when not empty)
2. You could have an "auto hide when empty" option for each individual tag. (Maximum flexibility and keeps all related settings in one area)

**Comment by parg** [comment]
Beta 3601_B02 has a per-tag option to set "hide when empty" - you can multi-select entries in the "Tags Overview" to set multiple at once if needed.
Tag groups should hide anyway when they have no visible members.

**Comment by Dramaman** [comment]
works nicely, thanks
