### ISSUE TITLE
Assign "Download State" tags to a tag group "Download State"

### ISSUE THREAD

**Issue by Dramaman** [BiglySoftware/BiglyBT#3238]
Would it be possible to assign download states tags to a tag group?
Don't need to be fancy, can be a "built in" / "hard coded" group called "Download State"
It would allow us to group and collapse the download state tags similar to how we can group and collapse tag groups for manual tags.

Not a big deal, but I think it would be a nice touch. There could be an option to toggle this on or off based on user preference.
It could be a check box on each tag setting "Add to Download State tag group" or there could be a global setting.

![Screenshot 2024-04-29 140140](https://github.com/BiglySoftware/BiglyBT/assets/76974959/e4b940cc-075c-4087-ab55-016e9b19434b)

**Comment by parg** [comment]
B03 puts the download-state tags into a group

**Comment by Dramaman** [comment]
Looks good. Thanks.
