### ISSUE TITLE
Tracker Count

### ISSUE THREAD

**Issue by Xemnarth** [BiglySoftware/BiglyBT#3241]
Please add a new column in the transfer list view to count trackers in a transfer job. Thanks!

**Comment by parg** [comment]
Transfer List/Job? What do you mean?

**Comment by Xemnarth** [comment]
transfer list, library views, tag view, main transfer menu, are they all the same?
a transfer job is just another way of saying torrent transfer/addition

**Comment by parg** [comment]
Why is the tracker count of any relevance though? I can't see how that information would be of help?
