### ISSUE TITLE
Outbound and Inbound test failures after 3.6.0.0

### ISSUE THREAD

**Issue by Xemnarth** [BiglySoftware/BiglyBT#3243]
![Screenshot 2024-05-06 111409](https://github.com/BiglySoftware/BiglyBT/assets/6406869/3b35ded3-22e5-496e-b408-ed3e4f2d8947)
Manually checked if the port is open using a public tool and it said yes, but not in BiglyBT. Might be a visual bug?

**Comment by parg** [comment]
Its a bug, fixed in 3601_B05
