### ISSUE TITLE
[Serious question] Is the license GPLv2 or v3?

### ISSUE THREAD

**Issue by aaronliu0130** [BiglySoftware/BiglyBT#3247]
Currently, the LICENSE file in this repo (and the terms and conditions on the website) are both GPLv2. However, in [this FSF interview](https://www.fsf.org/blogs/licensing/the-licensing-and-compliance-lab-interviews-biglybt) with @parg and @TuxPaper, all of you state that GPLv3 is the license. So which one is it?

**Comment by parg** [comment]
2+
