### ISSUE TITLE
Multiline descriptions (in torrentlist view) jumps when first line break is not a single linebreak 

### ISSUE THREAD

**Issue by de-served** [BiglySoftware/BiglyBT#3249]
1. I use classic view.
2. I Enabled "Description column" and use it
3. Copy/paste/write any description longer than one line. After first line press Enter twice (or more). Continue description, divide for any number of lines by any number of linebreaks.
4. See the result: if first linebreak consists of only one linebreak then description shows correctly. If there are two linebreaks - first description line moved halfline up. If there are three+ linebreaks - it moved full line up and unseen. Linebreaks after second non empty text line did not breaks anything.

![image](https://github.com/BiglySoftware/BiglyBT/assets/18093731/7418b023-29f5-41ea-b487-3d68b353dffd)
![image](https://github.com/BiglySoftware/BiglyBT/assets/18093731/97478c27-26ad-4c4e-87da-7a0afbab4534)
![image](https://github.com/BiglySoftware/BiglyBT/assets/18093731/88881c44-8a38-4f08-a391-51ed65ae1f1b)

* OS and version - Any
* BiglyBT Version Number - All versions

**Comment by parg** [comment]
Try beta 3601_B07 - I fiddled with things a bit (See the Help menu to join the beta program)

**Comment by de-served** [comment]
Why? :~(

**Comment by parg** [comment]
I'm not going to do any more to try and fix it, feel free to have a go.
