### ISSUE TITLE
IP filter failed to fetch URL

### ISSUE THREAD

**Issue by LordSky00** [BiglySoftware/BiglyBT#325]
I use an IP filter list from iblocklist.com. I was able to get BiglyBT to fetch the list via url every 7 days and it has worked perfectly. But today it stopped working. Since there are no logs or any way of checking what is happening, I can't troubleshoot the issue. Can we get some sort of log of how ip filter works? 

FYI, I use a zipped P2P list and it has been working fine until recently. I am able to fetch the list from the same url from my browser and manually pointed it there for now. Also if the ip filter fails to fetch the list it still show "last updated on (current date/time)" when you hover over the ip filter on the status bar.

also, no updates (no new java, same BiglyBT ver, etc.) since it IP filtered worked to when it failed to fetch from a URL.

Java 1.8.0_152 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4757, win32
Windows 7 v6.1, amd64 (64 bit)
B1.4.0.0/4 az3

**Comment by parg** [comment]
Have you looked in the debug_1/2.log files located in the logs folder in the BiglyBT configuration folder? Errors often get dumped there. The IP filter updater also logs some messages to the general log file (enabled under Tools->Options->Logging) but this log file is pretty verbose. Obviously errors should be reported more clearly...

**Comment by LordSky00** [comment]
It started working again! Not sure what I did. I did empty my temp folder. Not sure what else could have changed that would affect it. I looked at debug_1 and debug_2. There doesn't seem to be anything related to the IP filter failing.
