### ISSUE TITLE
CloudFlare

### ISSUE THREAD

**Issue by LuvBiglyBT** [BiglySoftware/BiglyBT#3252]
Good day,

It seems like more and more indexers  when using Jackett have added CloudFlare to their sites as well as such sites like EzTVx.to, so searches get blocked.  The following is the error I receive:

![image](https://github.com/BiglySoftware/BiglyBT/assets/34841335/5d3f9624-ae55-4d25-908b-0b41b23174d7)
 
Numerous indexers, such as 1337x and Lime Torrents have also added CloudFlare in the last month or two.  Is there a simple workaround?  I have tried doing an Internet search with minimal results.  One solution I found seemed really complex and seemed to only avoid CloudFlare on a per incident basis, requiring code (which I do not understand) to be run every time I boot up.

Any help out there?

Best,
LuvBiglyBT

![Clipboarder 2024 05 21](https://github.com/BiglySoftware/BiglyBT/assets/34841335/95cba82c-4af0-4f5f-a3a9-252f6786f3fc)

Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B3.4.0.0/4 az3

**Comment by parg** [comment]
Not something BiglyBT is going to/can fix. Try something like https://github.com/Jackett/Jackett

**Comment by parg** [comment]
and https://github.com/BiglySoftware/BiglyBT/wiki/Search-Templates#jackett
