### ISSUE TITLE
Heap memory running out

### ISSUE THREAD

**Issue by Xemnarth** [BiglySoftware/BiglyBT#3254]
![Screenshot 2024-05-26 120054](https://github.com/BiglySoftware/BiglyBT/assets/6406869/2f2f9fcc-8ee7-4236-a65e-7bea05a8d98f)
I keep getting this warning message whenever I run a lot of (seeding) torrents after a few minutes. Is there a higher maximum heap memory or do I have to do a config reset in case there's an issue with my settings?

**Comment by parg** [comment]
Check out https://github.com/BiglySoftware/BiglyBT/wiki/Performance-Tweaks

**Comment by Xemnarth** [comment]
Thanks for the info. Just to know, is the maximum heap generally fixed at 2 GB on all machines or can it be further tweaked?

**Comment by parg** [comment]
On a 64-bit JVM you can go way higher if needed.
