### ISSUE TITLE
Move files always make copy+delete operations

### ISSUE THREAD

**Issue by de-served** [BiglySoftware/BiglyBT#3257]
IDK is it a bug or not if there is an option. Will leave there

BBT 3.6.0.1_B10

I can't find parameters in the settings to change this. Maybe I'm searching wrong (move, alloc, delete)
When I check "move data files..." and select another folder on the same disk (parent folder, child folder), BBT copies files and then deletes them. If I have a torrent that is 100-200Gb in size then such a "move" takes too much time on slow HDDs and wears out SSDs.

If my config is not so perfect as it theoretically can be and I made an error in Tag constraints and *all* my torrents have their paths changed then all the downloaded files will be copied/moved for a long time and/or wear out SSDs.

Maybe there is an option that I can't find to enable moving by only one operation - updating MFT's data?

**Comment by parg** [comment]
"Options->Files->Completion Moving: Copy and then delete the original data rather than move it in one operation " ?

**Comment by de-served** [comment]
> "Options->Files->Completion Moving: Copy and then delete the original data rather than move it in one operation " ?

[ Off ] Copy then delete rathen than move...
 |--[ Off, Disabled ] But only do this when the source...

**Comment by parg** [comment]
It might be caused by a progress-feedback listener, there is no way in Java to receive progress events from the JVM when it is asked to move a file. So if the move was automatic (e.g. move-on-complete) then it is possible that an "atomic" move would occur.

I'll take a look at it.

**Comment by parg** [comment]
Having said that that only occurs across file systems.

**Comment by parg** [comment]
Next beta (B11) has some added logging around this - check the DiskOps_1/2.log files when the beta is available
