### ISSUE TITLE
Keeps crashing on VM machine running linux

### ISSUE THREAD

**Issue by francescocmazza** [BiglySoftware/BiglyBT#3259]
Hello,
I'm running Biglybt on a Virtualbox virtualmachine. 
Biglybt crashes very often. The issue I get is that the program freezes and never recovers. Data keeps being transferred so it appears to be an interface issue, but I get it very often. Here are some occasions that bring the interface to freeze.
- if I click and select a few torrents on the completed torrent to start them seeding the program freezes
- If I have more than 10 torrents seeding it often freezes

The VM is operating fine and I'm having the same issue even in another VM I created for other testing purposes.
I have a lot of files in the log/save folder. The Biglybt interface shows errors in the bottom right corner saying that biglybt did not shutdown tidly.

I'm running linux mint 21.3 64 bit, biglybt 3.6.0.0 and java 11.0.22

What other info can I give you to help me solve the issue?

Thank you very much 

* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment

**Comment by parg** [comment]
Try a Kubuntu VM - Linux (support) sucks, sorry

**Comment by parg** [comment]
The crashes are almost always related to the UI library we use (called SWT) that is based on GTK. Different linux variants/desktops seem to cause issues

**Comment by francescocmazza** [comment]
Thank you very much for your kind explanation!

Il giorno lun 27 mag 2024 alle ore 11:42 parg ***@***.***> ha
scritto:
