### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Xemnarth** [BiglySoftware/BiglyBT#3260]
![image](https://github.com/BiglySoftware/BiglyBT/assets/6406869/2c8f59ac-b60e-47f3-899e-57bbd010b98c)
"Downloads" corrected to torrents or transfers for better wording (since these options apply to all types of status)

**Comment by parg** [comment]
"Downloads" is a generic term that applies to things you download (whether complete or not), or even if you originate them and actually only ever seed them.

"Torrents" actually should apply only to the ".torrent" files themselves in my opinion.

"Transfers" is a stupid term for entities, it should only really apply to things in the act of being transferred. Probably.

Anyway, I'm not about to go around changing things for two reasons: 1) it would be a massive job to engage on some kind of constency in the usage of these terms 2) everytime a translated text is changed it kicks all existing translations

**Comment by Xemnarth** [comment]
Yeah, I'd have to agree about the strive to maintain consist usage of terms and its overarching implications. That aside, I think you meant transferers and transferees as entities. Makes me wonder if anything besides .torrent files can be added to the client...
