### ISSUE TITLE
Jumping focus from torrent to tags in tags view

### ISSUE THREAD

**Issue by de-served** [BiglySoftware/BiglyBT#3261]
BBT 3.6.0.1_B10

1) Classic view.
2) Open Tags view (mine now is at separate window)
3) Show bottom pane (Settings, Torrents, Files...)
4) Select Torrents Tab at bottom pane
5) Select any tag/tags at upper pane
6) Select any torrent at bottom pane (for example by LMB)
7) Press F2 to "edit" torrent OR LMB at "Description" edit if it is enabled OR Del
8) Press Esc

Result - Focus jumps to tabs, not returns to torrents. So using keyboard like (Up/Down > F2/Del > Esc/Enter [> Up/Down] & mass repeat) is impossible without mouse. Focus must return to torrents bottom pane if it was there.
If focus was at tags then it returns to them.

**Comment by parg** [comment]
Should be fixed in B11 but I'm sure it will have broken something else
