### ISSUE TITLE
Tags view > Settings tab > Constraint edit state changes without entering any letters

### ISSUE THREAD

**Issue by de-served** [BiglySoftware/BiglyBT#3262]
BBT 3.6.0.1_B10

1) Classic view
2) Tags view opened at separate window
3) Bottom pane is opened (Settings/Torrents/Files tabs)
4) Select any tag in upper pane
5) Select Settings tab at bottom pane
6) Click at Constraint edit (or Tab-Tab-Tab-Tab... there)
7) Press Shift/Alt/Ctrl/Arrows/etc - any non letter keys

Constraint "(non)edited" state changes to edited.

**Comment by parg** [comment]
try B11
