### ISSUE TITLE
Tags view - cloning tags with icons issues

### ISSUE THREAD

**Issue by de-served** [BiglySoftware/BiglyBT#3263]
BBT 3.6.0.1_B10

1) Classic view
2) Tags view opened in different window
3) Settings pane is opened (Settings/Torrents/Files tabs at lower pane)
4) Select any tag with icon set.
5) Clone tag
6) Click at new cloned tag
7) Point to a Icon set for a tag

**1**
1.1 If original icon was set out of BBT directory then path for cloned tag icon was changed to %AppData%... If I just need to select another icon from the same directory where was original icon then I must travel through all directory tree if icon's library somewhere deep.
1.2 The more clones of the tags the more icon copies are appeared at %AppData%\BBT\tagicons directory. When I found that there was a ... loooot of them. Deleted them all and manually relinked to external icons library. That was hard...
1.3 BBT didn't remember last path where icons was used. Each new tag pressing changing icon button starts "from the beginning".
1.4 If I use simlink/junction for %AppData%\BBT\tagicons then BBT didn't see icon at all. Only real directory where new copies appears and I delete them again and again and relink manually to icons external library. 😭 

**2**
Icon cloned too but must be used the same.
To easy use/open the same directory where original icon was, most common situation - lot of icons, just select needed or left the same as original tag.

**Comment by parg** [comment]
Might be inconvenient but it works. I'll make it remember last directory location.

**Comment by de-served** [comment]
What about making duplicates of original icons and changing their paths?
Ignoring sim/hardlink for %AppData%\BBT\tagicons?

**Comment by parg** [comment]
I'm the only one supporting this product as a hobby, I'll decide what I fix
