### ISSUE TITLE
[Feature request] Allow to apply Initial/Move on .../Copy on .../ for all selected TAGS, not only one

### ISSUE THREAD

**Issue by de-served** [BiglySoftware/BiglyBT#3265]
BBT 3.6.0.1_B10

1) Classic view
2) Changed something in constraints, made an regexp that didn't use something needed and tags are mixed out
3) Trying to fix torrents by RMB > Files > *** Save Location > Apply to Current

If there are lot of tags (mine is a lot) + frequently not working "Initial ... apply" then there are too much work to fix every tag/torrent.
If there will be option to use this for all selected torrents then it will be only some clicks away from result.

I'm cleared all "Move on assign" parameters because of other bugs and use only "Initial Save Location" only (copy/move files disabled in BBT options but they are copied/moved for every path change so I disabled it - I'm working now with constraints a lot and I have a troubles with that, so cleared [and this is a butthurt too, because clearing only Move on assign is impossible - it clears Initial Save Location too - then I need to move through the path tree for Initial Save Location for every tag... Set/Clear/travel/Set... etc])

**Comment by parg** [comment]
Next beta
