### ISSUE TITLE
Tags view - sorting method A-Z didn't remembered

### ISSUE THREAD

**Issue by de-served** [BiglySoftware/BiglyBT#3267]
3.6.0.1_B10

1) Classic view
2) Tags view at sidebar
3) Click on it
4) Lower pane with Settings/Torrents/Files tabs are opened
5) Click any column to sort by A-Z
6) Select any number of torrents to see a result (sorted by A-Z, arrow shows A-Z sorting)
7) Click at any option at sidebar - My library, Downloads, All Trackers, All Pieces, Disk, All peers - any except Tags view
8) Click at Tags view - sorting now is Z-A, column is ok.

Repeat 5-8 with any other column, select A-Z sorting
Result the same - sorting always set as Z-A.

**Comment by parg** [comment]
Fixed in B11
