### ISSUE TITLE
[Feature request] Don't update GUI (or line under cursor) when pointer at the "New" indicator

### ISSUE THREAD

**Issue by de-served** [BiglySoftware/BiglyBT#3268]
3.6.0.1_B10

1) Open "Unopened" (or "Unseen", IDK how it is in enu-translation, don't want to delete .properties from .jar/com\biglybt\internat to look how it is look like)
2) "New" column (blue circles) must be enabled, there must be a lot of torrents with status "New" enabled
3) GUI update time must be set for fast updates (250-500 ms is ok)
4) If there are lot of torrents then move mouse pointer to blue circles and click-click-click each line to disable (or disable/enable) them

At the moment when GUI updates mouse is under the line that was not chosen to disable, and if GUI updates fast enough then there is a high risk that what is accidentally set as "read" will be "lost"/forgotten in a mass of torrents

Pause GUI updates if mouse pointer is at the blue circle zone (or at the "New" column - it's better, because pointer can be upper/lower than blue marker, so there must be a no-reaction zone) or maybe much much better - update when no mouse movement/keypress for a 3-5 sec (or x12-16-24-32 periods of GUI repaint). I changed table resort to x16 of repaints (250ms) but even with such rare table updates it leads to confuses.

**Comment by parg** [comment]
That's why you can multi-select entries to mark as "not new", right-click in the "New/Unopened/Unseen" column and select the "toggle new marker" menu item
