### ISSUE TITLE
Memory overrun/no free handles/leak

### ISSUE THREAD

**Issue by de-served** [BiglySoftware/BiglyBT#3269]
3.6.0.1_B10
192 Gb RAM

0) Classic view
1) For example, we have 500 tags (I think 200-250 would be more than enough, but...)
2) Open Tag viewer
3) Select all tags that can be visible
4) Enable visibility, disable "hide when no items"
5) Goto top of tags
6) Click one tag/tab, it opens
7) Click next tag/tab, repeat some time... (repainting/updating GUI is very slow, I understand that it's java etc etc etc, but...)

After some number of (No)7-clicks there would be no reaction - tag will not open. Clicking previous tag/tab will show what was before. But no new clicks will be shown. After some more clicking even Downloads/Tags view/Dashboard will not be shown

<details>
  <summary>Screenshot</summary>
  <img src="https://github.com/BiglySoftware/BiglyBT/assets/18093731/2b9c82e8-978a-4853-aed4-b549fdbe02b3">
</details>

PS: I'm changing Simple list view to Detailed list view for every tag, but now I tried without that just clicking - and after 30-45 tags it's appeared again. Repeatability 100%. Checked at VM, at second physical machine, at remote machine - it happens on every machine.
I you will not be able to reproduce... and if you need detailed debug logs I can run debug version of BBT, just send me it.

**Comment by parg** [comment]
Yah, don't do that.

You can find many ways to fuck up BiglyBT by doing unreasonable things. If you think I am going to get up every morning and spend time and effort going through 10 new issues that you've raised then think again.

**Comment by de-served** [comment]
It's not a bugtest, it's my common use of BBT last week.
Fixing consequences of other bugs.

**Comment by parg** [comment]
I assume you've increased your JVM heap size from the default 256MB? View->Log Views->JVM Info shows VM stats

**Comment by de-served** [comment]
Yes, to 1G
alloc= always 447Mb,
free= 65..190
SWT Thread jumps from almost zero to even 85%
