### ISSUE TITLE
Resetting Location paths after restart

### ISSUE THREAD

**Issue by de-served** [BiglySoftware/BiglyBT#3270]
3.6.0.1_B10

1. Classic view
2. Tags view at sidebar
3. Click on it
4. Select any tag, it must have `Group` and `Tag Name`, For example `Group = 01. Some group\sub` and  `Tag Name = Docs\Vids`.
5. Set/change `Move on Assing/Initial Save Location` to directory outside of "Home" torrent downloads directory. For example, Home dir is `F:\Downloads\Torrents`, change it to `G:\OtherLocation`
6. Left at Tags view, restart BBT
7. Select the same Tag, check `Move on Assign/Initial Save Location` - right now it is what we set at (5)
8. Restart BBT again, Select the same Tag, check `Move on Assign/Initial Save Location` - now it is `F:\Downloads\Torrents\Docs\Vids` - "Home dir" + "Tag Name"

**Comment by parg** [comment]
And you haven't set a "move on assign root folder" for the Group?

**Comment by de-served** [comment]
Never.
Set only for tags.
Last few days cleared "Move on assign" for every tag and (re)set for "Initial" because clearing "Move on assign" clears "Initial".
But it's irrelevant - "Move on assign" set or not set (few tags has both) - paths resets always after second restart of BBT if not in "Home" dir (`Settings > Files (paths, drives, speed) > Standard directory options - Standard directory [F:\Downloads\Torrents]`)

**Comment by parg** [comment]
Can't reproduce it

**Comment by parg** [comment]
The only way I can see this happening is if you have right-clicked on a TagGroup in the sidebar and set the "Move On Assign Root Folder" for it. The second-restart thing could be a UI update issue (it is getting reset on first restart but the settings dialog isn't showing it)

**Comment by de-served** [comment]
Tried to search this `Move On Assign Root Folder` after your words.
Found in `RMB > Group > Settings > [GroupName] > Move On Assign Root Folder`
Fount that part of groups has this set on and part was not. Maybe I tried to do with that some time ago to understand what it's purpose.
Ok... clear...
And.... now `Initial Save Location` and `Move on Assign` are gone (!!!) for every tag in this groups! But I set them manually and spent a lot of time for that.
Now I need to set it again? What a... :(((((((
Why it resets manually set paths?

I understand that I need to all added tags must have it's own subdirectories as tag names and sometime ago found that this will lead to what I need.
But this reset manually set paths after restart or two makes this function unusable. Something broken there.

**Comment by parg** [comment]
Who knows? You go around setting things that you don't understand, forget them, waste my time complaining about issues, whatever

**Comment by de-served** [comment]
Tactless boor
If the advanced capabilities of BBT aren’t used, it ends up being the same as µTorrent.
In this case, why would anyone need BBT if they can just use µTorrent?
Why am I spending the limited time I have left of my life trying to help make this product better?
It’s easier not to use any additional features at all and instead install µTorrent with its predictable interface that instantly responds to any actions, redraws without memory leaks and other glitches.
Now there's one less BBT user, and there were already very few to begin with.
Be happy and use your product alone.
