### ISSUE TITLE
Tag selection reverts to last opened by "RMB > Settings"

### ISSUE THREAD

**Issue by de-served** [BiglySoftware/BiglyBT#3271]
3.6.0.1_B11

1. RMB at any tag at sidebar
2. Click `Settings` - `Tags view` will open and this tag is selected
3. Click at any other tag to change tag focus
4. Click any other tab at sidebar, for example `My Library`
5. Click `Tags view` again

We expect that the tag that was selected/highlighted last will be highlighted after click at `Tags view` but no - selection jumps to tag that was selected at (1-2)

**Comment by parg** [comment]
Fixed in B12
