### ISSUE TITLE
[Feature request] Make it possible to enter tags > file settings > paths to be entered/edited manually

### ISSUE THREAD

**Issue by de-served** [BiglySoftware/BiglyBT#3274]
Please, if it's possible, make paths editable.
If there are tags that has directories set that not exist now (no torrents associated at a time and empty directories are removed) then to set a correct paths for Initial Save Location, Move On Assign etc I need to recreate full path for them to be able to set it. Then remove this empty directories created only to set this parameters...

If it will be editable then there will be a very fast and easy way to set paths for locations - Ctrl-V, Ctrl-C, subdir name, Enter.

**Comment by parg** [comment]
Next beta
