### ISSUE TITLE
v3.6.0.0 Installer not working

### ISSUE THREAD

**Issue by clshortfuse** [BiglySoftware/BiglyBT#3285]
* Windows 11 (23H2 22631.3672)
* 3.6.0.0

The `GitHub_BiglyBT_Installer64.exe` installer of 3.6.0.0 doesn't work. It starts loading up and closes. `GitHub_BiglyBT_Installer64_WithJava.exe` also does the same. Nothing gets written to eventvwr, so I'm not sure where to debug.

The 32bit installer works as does the 64bit version of 3.5.0.0.

**Comment by clshortfuse** [comment]
![image](https://github.com/BiglySoftware/BiglyBT/assets/9271155/252a0459-1fdd-41f1-87ce-0b3de0902afe)

This the best I could capture. But "BiglyBT is preparing the install4j Wizard which will guide you through the rest of the setup process process." flashes for a couple of frames before closing.

the last entry in the log in `%temp%` is `[0:119] Creating JVM`

**Comment by clshortfuse** [comment]
I was able to install by removing OpenJDK completely, but I'd be breaking other applications now.

**Comment by parg** [comment]
What version of the OpenJDK did you have installed?

**Comment by clshortfuse** [comment]
`OpenLogic-OpenJDK JDK with Hotspot 8u382-b05 (x64))`

**Comment by parg** [comment]
Everything seems to work OK for me with

C:\Program Files\OpenLogic\jre-8.0.412.08-hotspot
