### ISSUE TITLE
update reboot message too quick

### ISSUE THREAD

**Issue by coyote3** [BiglySoftware/BiglyBT#3299]
After the last few beta updates, when I click restart on the update message I get a message that it's too soon to restart (because something is in progress); I guess the updater is no longer waiting long enough to present me with the message to approve the restart.

Java 1.8.0_333 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=200, dpi=96
Windows 11 v10.0, amd64 (64 bit)
B3.6.0.1_B20/4 az2 en_US_classic

**Comment by parg** [comment]
Does it say what is in progress? Nothing's changed AFAIK.

**Comment by parg** [comment]
The message should say what's going on (file moving, copying,...) Also the dialog will close and restart once the operation completes so...

**Comment by coyote3** [comment]
I don't remember what it said but it just waits for response.  When I wait
to click restart I don't get it.

And I won't get another until I update again.  I'd be happy to downgrade
then update again if I knew how to downgrade.

**Comment by parg** [comment]
It is designed to auto-close when whatever the operation(s) that are pending/executing complete.

**Comment by coyote3** [comment]
I don't think that functionality is working, based upon that when I waited myself this time I didn't get the message.

Next time I upgrade (happy to do so now if there's an easy way to downgrade) I'll printscreen the dialog and wait several minutes instead of just 20 seconds.

**Comment by parg** [comment]
Just wait until it happens next time, probably easiest

**Comment by coyote3** [comment]
With the new update it said something to the effect that 'operations involving the <update jar file> were in progress...' then (to my great surprise this time) it quickly disappeared and I didn't get the usual Windows UAC message to approve and I didn't get the usual wait to restart.

**Comment by parg** [comment]
I'll consider it closed!
