### ISSUE TITLE
Fancy right click menu doesn't work under Hyprland

### ISSUE THREAD

**Issue by jobukkit** [BiglySoftware/BiglyBT#3300]
Under the Hyprland window manager, the fancy right click menu appears in the center of the screen and immediately disappears when you move the mouse.

**Comment by parg** [comment]
turn it off then

**Comment by parg** [comment]
Options->Interface->Tables [Library]: Show Fancy Menu (Requires Restart)

Seriously, I don't have the bandwidth to try and figure out SWT issues with specific window managers
