### ISSUE TITLE
Search for Existing Data Files in the "Link - Internal" mode always marks all files as Relocated

### ISSUE THREAD

**Issue by 2peer** [BiglySoftware/BiglyBT#3310]
All files are marked with a * in the Relocated column (even those that were not found/linked). 
There are files where path remains relative (.) yet they are all marked.

**System/version info:**
* OS and version : Linux - Fedora 40
* BiglyBT Version Number: 3601_B22
* For *nix: Desktop Environment : KDE Plasma

**Comment by parg** [comment]
You sure this isn't to do with "incomplete file suffix"? That currently causes them to be shown as a "*" as they have been relocated, from X to X.az! or whatever.

Right-click on the file and select Advanced->View File Links

**Comment by 2peer** [comment]
> You sure this isn't to do with "incomplete file suffix"? That currently causes them to be shown as a "*" as they have been relocated, from X to X.az! or whatever.

Could be, I have both:
`Options->Files [File Extensions]: Add suffix to incomplete files`
&
`Options->Files [File Extensions]: Move files not selected for download into subfolder`
enabled.

The question is when/why do these .az! get created (they are still in a Delete prio and most of them share pieces only with files in similar prio too, so there is no need to create an .az! file).

Interestingly I'm trying to investigate / replicate another related issue that I encountered several times. It has something to do with these two options &  switching between "Do not download", "Delete" & "Normal" priority (possibly while torrent was stopped). It resulted in BiglyBT failing to create or move the .az! file and torrent ending up in an Error state complaining that it is missing. Stopping and starting the torrent (possibly with additional "force recheck" -  not sure) fixed the issue.

> 
> Right-click on the file and select Advanced->View File Links

The Advanced sub-menu seem to be unfortunately missing from the Classic UI.


### Regarding the recent upgrade of how the file Path is displayed within the torrent file listing:

The difference currently seems to be:
- "./" - for an already downloaded file (not marked as relocated)
- "." (missing /) for .az! file with Delete priority in reality located in .dnd_az! subdir (and marked as relocated)

Maybe it would be a good idea to show the .dnd_az! subdir in the Path as well (  so the UI better matches the Biglys expectation / reality)

**Comment by parg** [comment]
View Links... is right there in the main menu with the classic UI

Stop twatting about with the .az! extension stuff, I'm pretty close to removing the feature entirely

**Comment by 2peer** [comment]
> View Links... is right there in the main menu with the classic UI

OK. Wrong menu - right-click on the file (per your instruction) VS right-click on torrent

> 
> Stop twatting about with the .az! extension stuff, I'm pretty close to removing the feature entirely

Please don't. It's a very useful feature to be able to immediately distinguish within a file manager which files are already completed.
