### ISSUE TITLE
[Feature request] Ability to easily view the whole error status of the torrent

### ISSUE THREAD

**Issue by 2peer** [BiglySoftware/BiglyBT#3312]
Torrent Error status message can get quite long.
In the torrent context, there currently doesn't seem to be an easy way to view the whole wording of the error message (they get clipped to certain length in both General & Info tab).

Would be nice to make the status field scrollable (either single line or multi-line read only text-field - you can use cursor/mouse to scroll, select & copy text).

_NOTE:_ There is the right click -> copy to clipboard feature on the status field, so a solution exists, but would be nice to able to just view what seems to be the problem directly (+ easier discovery)

**Comment by parg** [comment]
Doesn't the tooltip show the whole message?

**Comment by 2peer** [comment]
> Doesn't the tooltip show the whole message?

Don't have a really long Error to test it right now ,but you are probably right (mouse over tooltip in the "My Torrents" overview, not in torrents General tab details). That combined with "Copy Text To Clipboard" (works on both) context menu entry is probably sufficient (most of the time I want to extract some file path out of there , but I can do that in separate text editor).

**Comment by parg** [comment]
I'll assume that's sufficient then
