### ISSUE TITLE
Opening GitHub_BiglyBT.jar gives a "A Java Exception has occured" error.

### ISSUE THREAD

**Issue by barkoder** [BiglySoftware/BiglyBT#3314]
* Windows 7 Ultimate Version 6.1 (Build 7601: Service Pack 1)

* BiglyBT version v3.6.0.0

* java version "1.8.0_411"

* Java(TM) SE Runtime Environment (build 1.8.0_411-b09)

* Java HotSpot(TM) 64-Bit Server VM (build 25.411-b09, mixed mode)

Steps to reproduce:

1. Download GitHub_BiglyBT.jar from https://github.com/BiglySoftware/BiglyBT/releases/download/v3.6.0.0/GitHub_BiglyBT.jar

2. Double Click the Downloaded file.

3. "Java Virtual Machine Launcher" window gives a `A Java Exception has occured.` error.

Thanks for any help.

**Comment by parg** [comment]
You can't just run the .jar, see https://github.com/BiglySoftware/BiglyBT/wiki/Command-Line-Options
