### ISSUE TITLE
command runner plug-in issue with spaces

### ISSUE THREAD

**Issue by blitus** [BiglySoftware/BiglyBT#332]
command runner plug-in has issues with spaces in parameters (ie file/dir), I believe this issue that the command to run is purely a string, rather than a string array:
		final String command_to_run = command;
		..
		Runtime.getRuntime().exec(command_to_run);
		plugin_interface.getUtilities().createProcess(command_to_run);

if changed to use an array spaces wouldn't be an issue, something along the lines of:

		final String[] commandarray = ... build the array from the command template
		Runtime.getRuntime().exec(commandarray);
		
Regards

**Comment by parg** [comment]
Yes, that's unfortunate,,, Can you work around it by using quotes in the command spec around the parameters with spaces?

**Comment by blitus** [comment]
Sadly not, the command template string already has them, eg:
somecommand.cmd "%D" "%N"
I have tried various combinations of quotes eg. single quotes, double quotes, quotes at start and end etc. 

Cheers

**Comment by parg** [comment]
Beta version 1.4.1 of the plugin (and core _B10) should handle this better - please test!

**Comment by blitus** [comment]
Parg, works great, no more issues with spaces in dir/file names.

Just one slight issue - the command runner log - it logs messages such as these now:
Executing: [Ljava.lang.String;@5b9be7df
Executing: [Ljava.lang.String;@7fc56eac

which I'm sure you know is the line below as command_to_run isn't a string now:
channel.log("Executing: " + command_to_run);

probably affects this line to:
channel.logAlert("Unable to run \"" + command_to_run + "\".", t);

btw, the quick response and fix is very much appreciated! many thanks! keep up the good work.

Cheers

**Comment by parg** [comment]
duh! will fix in next version, thanks!

**Comment by parg** [comment]
1.4.2's out!

**Comment by blitus** [comment]
works great! many thanks again!

**Comment by parg** [comment]
no probs
