### ISSUE TITLE
Unsupported address type.

### ISSUE THREAD

**Issue by Achaean** [BiglySoftware/BiglyBT#3324]
Java 15.0.2 (64 bit) 
Oracle Corporation
/usr/lib/jvm/jdk-15.0.2 

SWT v4942r22, gtk/3.24.38, zoom=100, dpi=110
Linux v6.6.36-pclos1, amd64 (64 bit)
B3.6.0.0/4 az3 el_GR

I'm getting this warning:

`java.net.SocketException: Unsupported address type  at java.base/sun.nio.ch.Net.translateToSocketException(Net.java:187)  at java.base/sun.nio.ch.Net.translateException(Net.java:217)  at java.base/sun.nio.ch.Net.translateException(Net.java:223)  at java.base/sun.nio.ch.SocketAdaptor.bind(SocketAdaptor.java:103)  at com.biglybt.core.networkmanager.impl.tcp.TCPConnectionManager.addNewRequest(TCPConnectionManager.java:426)  at com.biglybt.core.networkmanager.impl.tcp.TCPConnectionManager.addNewOutboundRequests(TCPConnectionManager.java:339)  at com.biglybt.core.networkmanager.impl.tcp.TCPConnectionManager$7.run(TCPConnectionManager.java:298)  at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:334) Caused by: java.nio.channels.UnsupportedAddressTypeException  at java.base/sun.nio.ch.Net.checkAddress(Net.java:161)  at java.base/sun.nio.ch.SocketChannelImpl.bind(SocketChannelImpl.java:661)  at java.base/sun.nio.ch.SocketAdaptor.bind(SocketAdaptor.java:101)  ... 4 more`

**Comment by parg** [comment]
Probably an IPv6 issue - try the latest beta, it prevents some cases like this. Otherwise ignore it.

**Comment by Achaean** [comment]
I'll ignore it.
Strange though!
I've disabled IPv6 altogether.
**Bye!**  :-)
