### ISSUE TITLE
failed "Files: -> Completion Moving" by lack of space

### ISSUE THREAD

**Issue by icesof** [BiglySoftware/BiglyBT#3326]
* OS and version: Windows 10 22H2
* BiglyBT Version Number: 3.6

In setting, Files -> Comletion Moving -> enable "Move completed files (after download)"
The Directory in a different volume, which is almost full used. The moving action will fail because of lack of space. 

Suggestion: check avaible space before moving

**Comment by parg** [comment]
While I guess it is annoying I don't think is worth attempting to do - most (all?) other applications assume you manage your disk space yourself.

**Comment by icesof** [comment]
When the download has been completed and the files' consistency has been verified, the process attempts to copy files to another drive after the download has been completed. Due to previous downloads occupying most of the drive space, it is likely that the failures to copy files will continue to occur if torrents continue to be downloaded continuously. 

Would we consider preventing that failure from occurring?
