### ISSUE TITLE
Upload-only torrents (download speed set to "Disabled") might not be counted among the "active torrents"

### ISSUE THREAD

**Issue by 2peer** [BiglySoftware/BiglyBT#3327]
I have the "Options->Queue: Max active torrents" setting set to 12 yet I see a lot more active torrents than that (around 20). Large part of them (7 or 8) are in the "upload only" state. Is it possible that such torrents are currently not  counted upon the active (and not observing the set limit)?

**Comment by parg** [comment]
See

Options->Queue: Don't count completed torrent as using a slot if speed is below

**Comment by 2peer** [comment]
> See
> 
> Options->Queue: Don't count torrent as using a download slot if speed is below Options->Queue: Don't count completed torrent as using a slot if speed is below

I'm aware of those options, but I'm afraid that's not it. I have them set to 1kB/s yet those torrents sit well above that. I'm not saying that it's not something else affecting those numbers, but the total is kind of suspicious (torrents I would count as active based on speed avg. =~ my limit + the active "upload only" torrents).

Is there some way to display if the torrent is currently counted as active (to validate)?

**Comment by 2peer** [comment]
BTW. to what speed do those refer to? I would expect the total (upload+download), but maybe I'm mistaken.

**Comment by parg** [comment]
View->Log Views->Start/Stop Rules ?

**Comment by 2peer** [comment]
> View->Log Views->Start/Stop Rules ?

I enabled "Options->Logging: Enable logging", but this view still shows empty on my system (waited a few minutes, nothing appeared) .

**Comment by 2peer** [comment]
Ok, probably a false alarm. I now have approx 20 active torrents (limit is still 12) but none of them are "upload only". Might be the temporary slots or something else, hard to say.
