### ISSUE TITLE
Process already listening?

### ISSUE THREAD

**Issue by LuvBiglyBT** [BiglySoftware/BiglyBT#3333]
Can someone please explain how to deal with the error that I have been receiving for MONTHS when I try to download a magnet link from the net?  I have followed the suggested link in the error message and the page cannot be found.  Please see a screen shot of the error attached.

Thanks as always...

Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B3.4.0.0/4 az3

![Bigly BT Screenshot 2024-07-12 122222](https://github.com/user-attachments/assets/73ae038f-a0e4-42f1-b345-2f3e00459650)

**Comment by parg** [comment]
https://github.com/BiglySoftware/BiglyBT/wiki/Command-Line-Options#changing-the-control-port

exists for me!

**Comment by parg** [comment]
(and that redirects from https://wiki.biglybt.com/w/Commandline_options#Changing_the_Control_Port )

**Comment by LuvBiglyBT** [comment]
Parg,

As always I appreciate your timely response.  I have copied and pasted your example into both powershell and command prompt without success and many errors.

Primary:
 C:\Windows\System32>start /D "C:\Program Files\BiglyBT" javaw.exe -cp "BiglyBT.jar;commons-cli.jar;swt.jar" -Dazureus.instance.port=16889 com.biglybt.ui.Main
The system cannot find the file javaw.exe.

I am not by any means adept a coding and I am sure I am making some mistakes.  Can you help me out?

Thanks as always,
LuvBiglyBT

Java 1.8.0_202 (64 bit)
  Oracle Corporation
C:\Program Files\BiglyBT\jre

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B3.4.0.0/4 az3

**Comment by parg** [comment]
Yeah, problems problems!

The easiest fix is not to launch BiglyBT from a command prompt but to go to 

`%appdata%\BiglyBT`

(for me that resolves to `C:\Users\Paul\AppData\Roaming\BiglyBT` ) and create a (or edit the existing) file in there called "java.vmoptions" for me the file is

 `C:\Users\Paul\AppData\Roaming\BiglyBT\java.vmoptions` 

Put a single line of text in that file - 

`-Dazureus.instance.port=16889`

Then launch BiglyBT as usual via BiglyBT.exe

**Comment by LuvBiglyBT** [comment]
I succeeded at adding the line and it is now using the new port but I am getting the same error but now it is 16889 LOL!  What I am trying to do is download a torrent from the internet as opposed to from a search inside BiglyBT.  Does that affect the resultant error?

Thanks again.
________________________________

**Comment by parg** [comment]
Must be an antivirus program or firewall on your computer that is preventing the BiglyBT.exe from listening on ports (or "acting as a server as it is sometimes put) or interfering with the process. Do you get an alert when you start BiglyBT (yellow warning triangle bottom right) saying that it couldn't establish a listen?

When you click on a link in your browser the browser is configured to launch BiglyBT.exe with the link passed as a parameter. If BiglyBT isn't running this will start BiglyBT for you. If it is already running the the second BiglyBT.exe will simply pass the link to the existing BiglyBT.exe and exit - the first one receives the link and adds it to your library.

This is the process that isn't working - the second BiglyBT.exe isn't managing to pass the link.

If you can't figure out what is stopping this then the simplest solution is to copy the link in the browser and paste it into the search box at the top of BiglyBT - that should open the torrent. Failing that right-lick on the link in the browser and save the .torrent file to disk. Then drag+drop that only BiglyBT or open it via the File->Open menu.

**Comment by NaPurHab** [comment]
I've seen this issue.  What your doing is allowing the browser to OPEN a Torrent or Magnet directly. This results in the Browser Call up a 2nd copy of BiglyBT.   The solution is to SAVE Torrents to disk in a path that you configure under **Options->Files->Torrents**. Then setup Import Automatically and add a Path and Tag (or more if you want to group them, ie Movie, TV, Audio).

If you previously given permission to your browser to OPEN Torrents and Magnets. You will have to revoke the Automatic Permission.  Then always Save Torrents to the preconfigured Import Path, or Copy Magnets (see next paragraph).

If your dealing with Magnets, the same, don't let the browser launch a new copy of BiglyBT.  Instead, Right-Click the Magnet and Copy.  Then your existing copy of BiglyBT will see it and load it.  Again at the Bottom of **Options->Files->Torrents** set the option Monitor Clipboard, and then your golden.

**Comment by LuvBiglyBT** [comment]
Thank you, Parg And NaPurHag. When  I Find the time to implement your suggestions, I will let you know the result.
________________________________

**Comment by parg** [comment]
Closing as not going to make any further progress
