### ISSUE TITLE
Disk Operations - Scheduled, how to turn off.

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#3334]
This has been happening recently, and I have no idea where to adjust a schedule.  The Tools -> Speed Limits -> Schedule and Settings   is configured to 'enable=no' and should have no effect.  So any idea how to turn off this scheduling?

![image](https://github.com/user-attachments/assets/66f9996c-fde3-44c5-abc2-b5f8cc1f2209)

Java 1.8.0_411 (64 bit)
  Oracle Corporation
c:\program files\java\jre-1.8

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B3.6.0.1_B29/4 az3 en

**Comment by NaPurHab** [comment]
At one point, I had almost 20 moving piled up as Scheduled.  All being moves from N: to another drive.  N: is a WD Black 1 tb SSD, all other drives are WD Black HD, except C: which is a 1 tb Samsung 980.

**Comment by parg** [comment]
Did they complete eventually?

**Comment by parg** [comment]
Options->Files->Performance Options: Limit active major disk operations (allocation, check, move...) to one per file system

**Comment by NaPurHab** [comment]
Once I manually right-clicked and choose Start, then they completed.  Still doesn't explain why the one per file system would put them in Scheduled instead of Queued. Switching 20 torrents from Scheduled to Start (not queued) is annoying as I need to wait for each to complete.

It would be better if the One Per File System rule worked with the Queue, instead of Scheduled which seems to Lock Up, and fail to switch to Queued.

Also a few were added to my Trash Tag 1.25:1 and would be deleted when moved.  Except they got stuck in Scheduled. 

_When Move on Assign is set, and the Share Ratio is exceeded and Action is Delete, then it would be better to skip the Move if it is just going to delete immediately after the move._  Often torrents in NEW exceed 10:1 while waiting for me to process them. After I process the content, then the Trash Tag is faster then the remove/delete for system, which take more clicks.

![image](https://github.com/user-attachments/assets/9dee2507-35ea-484c-9062-0378019edd00)
You might think a Share Ratio of 1.25:1 is low, but I only apply it to torrents that have hundreds of seeds. I have other Trash Tags for torrents with less seeds.
