### ISSUE TITLE
Why can't it be automatically shut down based on how many seeds ?

### ISSUE THREAD

**Issue by i990049** [BiglySoftware/BiglyBT#3336]
* OS and version Windows 10
* BiglyBT Version Number 3.6.0.0
This can be done with other software, such as utorrent/bitcomet/tixati/vuze. This is very helpful for uploaders. As an uploader, it is not accurate to decide the auto-shutdown time based on the upload ratio. Many private trackers require at least some torrents produce before they can stop uploading, and it should be very convenient to have this feature.

**Comment by parg** [comment]
You list Vuze there. You do realize that BiglyBT is the successor of Vuze?

**Comment by parg** [comment]
Anyway, Options->Startup & Shutdown [Shutdown]: When seeding is complete etc

**Comment by i990049** [comment]
The same setting in vuze and bigly bt，vuze automatically shut down after 10 seeds nomatterwhat the ratio is，bigly just queued，don‘t’ auto shut down. I tried both Nexusphp and Unit3d private trackers.
<img width="757" alt="2024-07-23_235959" src="https://github.com/user-attachments/assets/559d254c-d1f8-4c37-9ce2-0dfb4a7d62dc">
<img width="960" alt="2024-07-24_004214" src="https://github.com/user-attachments/assets/37559e7c-7542-4a69-a14d-41110fa73ae1">

**Comment by parg** [comment]
And how about the settings under 

Startup & Shutdown [Shutdown]

?

**Comment by i990049** [comment]
> And how about the settings under
> 
> Startup & Shutdown [Shutdown]
> 
> ?
both vuze biglybt the same Shutdown

**Comment by parg** [comment]
Post a screenshot of the shutdown settings

**Comment by i990049** [comment]
As soon as there is a torrent with more than 10 seeds according to my seeting, Vuze will automatically shut down.I used to upload several torrents at the same time.How should I set biglybt automatically shut down after all torrents more than 10 seeds? Thank you.
<img width="757" alt="2024-07-22_183358" src="https://github.com/user-attachments/assets/9a57370e-0b77-495f-84e4-87ef78901028">
<img width="960" alt="2024-07-24_013055" src="https://github.com/user-attachments/assets/1984bcc2-bed5-4a4d-927d-093e4c64e5cb">

**Comment by parg** [comment]
Looking at the code the "seeding" shutdown is triggered when

1) nothing is in a downloading state

2) BiglyBT has been actively seeding AND is no longer is seeding

So it has to move from a state where at least one torrent is seeding with nothing downloading to a state where all the seeding downloads have moved to a queued state (or been removed) and nothing is downloading

In your second screenshot you have three torrents actively seeding - nothing will happen until these become queued.

**Comment by i990049** [comment]
How about the situation download and upload several torrents at the same time？Vuze/BiglyBT will auto shut down as soon as download is complete, but the rest upload don't finish. utorrent/bitcomet/tixati have the setting auto shutdown after every transfer finish, how to set the same setting in BiglyBT? Thanks.
<img width="960" alt="屏幕截图(294)" src="https://github.com/user-attachments/assets/294ff037-8833-4206-9b75-a491d0129fe6">

**Comment by parg** [comment]
You have it configured to shutdown when Downloading is complete (as per your screen shot). This is what is happening. If you want to wait until seeding is complete then don't configure the "downloading is complete" action, just configure the "seeding is complete" action

**Comment by i990049** [comment]
In private trackers , the files are relatively large, there may be hundreds of GB or even several TB. it is impossible to predict whether the download will be completed first or the upload will be completed first, so the best way is to shut down after all the files have finished transferring, hoping that the next version can provide this feature just like utorrent/bitcomet/tixati. Thanks.

**Comment by parg** [comment]
I don't undestand your problem so it isn't possible for a feature to be added.

If you configure the "shutdown when seeding is complete" then it'll do what you want. When all torrents have completed downloading, progressed to seeding and then all those seeds have become queued then the computer will be shutdown (or whatever you have set it to do)

If that doesn't happen then there's a bug
