### ISSUE TITLE
Scrape issue with one private tracker

### ISSUE THREAD

**Issue by Xemnarth** [BiglySoftware/BiglyBT#3337]
I get this announce error message when trying scrape the tracker with a paused torrent

> Stopped: Scrape Error: Could not decode response, appears to be a website instead of tracker scrape: BDecoder: unknown command '60, remainder = html><head><meta name="robots" content="noindex, nofollow" /></head><body>Nothing to see here</body></html> (< 57m)

This error goes away when the torrent is running

**Comment by parg** [comment]
I guess your private tracker doesn't support scrapes.
