### ISSUE TITLE
log about BiglyBT didn't auto shutdown.

### ISSUE THREAD

**Issue by i990049** [BiglySoftware/BiglyBT#3338]
* OS and version Windows 10
* BiglyBT Version Number 3.6.0.0
* For *nix: Desktop Environment
* Make a torrent upload and down torrent at the same time, both BiglyBT/Vuze won't auto shutdown after every transfer complete. It just queed and keep seeding.

[biglybt.zip](https://github.com/user-attachments/files/16391115/biglybt.zip)

![屏幕截图(300)](https://github.com/user-attachments/assets/6fac6016-67f9-4da9-9410-da88d5ddb94b)

![屏幕截图(301)](https://github.com/user-attachments/assets/4eff4a32-a7c2-4a79-9be2-a11daaca2141)

![屏幕截图(299)](https://github.com/user-attachments/assets/e67750f1-b4e7-43ce-85cf-75be31e1cc8a)

**Comment by i990049** [comment]
I suggest ‘when upload is complete’ in the picture change into ‘when every transfer is complete’ just like utorrent/bitcomet/tixati, nomatterwhich upload/download transfer last complete, Biglybt will auto shutdown. That's the setting logical of auto shutdown.

**Comment by parg** [comment]
You can't say "queued and keep seeding". If it is SEEDING then it isn't QUEUED. If it is QUEUED then it isn't SEEDING.

As I said before, to shutdown when seeding is complete ALL OF YOUR DOWNLOADS HAVE TO ENTER A QUEUED STATE.

If any of them are still in a SEEDING state then SEEDING is NOT COMPLETE.

You have to set up your SEEDING RULES in order to control when a download becomes QUEUED after SEEDING. For example, when the are 0 PEERS. Or a certain share ratio is met.

**Comment by i990049** [comment]
![erweima](https://github.com/user-attachments/assets/4d546066-67fb-4243-a4ba-a3a9e756f8be)
<img width="757" alt="351416914-559d254c-d1f8-4c37-9ce2-0dfb4a7d62dc" src="https://github.com/user-attachments/assets/b7e792d1-a9f6-4b33-9b65-c88f151c438d">
How should I set to queue a download complete torrent with 0 ratio and more than 10 seeds without any peer？There is 11 seeds with 0 ratio in the picture before.

**Comment by parg** [comment]
Ignore rules - zero peers

**Comment by i990049** [comment]
> Ignore rules - zero peers

You didn't see the log and the picture with one upload torrent queue and one complete download torrent keeping seed. I already set 0 peer. It didn't work.

**Comment by parg** [comment]
Turn on seeding rules debug

Options->Queue: Log debug information

enable the "seeding rank" column in the seeding torrents table and it will say why the download is seeding
