### ISSUE TITLE
Metadata refusing to load

### ISSUE THREAD

**Issue by tonywr71** [BiglySoftware/BiglyBT#3339]
Windows 11 Pro N 10.0.22631 
BiglyBT 3.6.0.0

Bigly BT used to work beautifully for me, ever since someone provided me with a way to get the interfaces to auto match (see issue [#1741)](https://github.com/BiglySoftware/BiglyBT/issues/1741) 

Now my VPN provider has changed things and the metadata refuses to download now, even though the routing icon is green.

The provider is PureVPN, and their new "Quantum resistance" P2P connections work only with UDP protocol. I'm wondering if this is the issue.

On the interface screen, it still shows (PureVPN|TAP-Windows\sAdapter\sV9) in the "Bind to local IP address or interface" box.

My interfaces are like the following:
`	lo		(Software Loopback Interface 1)

		lo[0]	127.0.0.1
		lo[1]	0:0:0:0:0:0:0:1
	net4		(TAP-Windows Adapter V9)
		net4[0]	172.22.xx.xx
		net4[1]	fe80:0:0:0:fadf:xxxx:xxxx:xxxx%net4
	wlan4		(Killer(R) Wi-Fi 6 AX1650x 160MHz Wireless Network Adapter (200NGW))
		wlan4[0]	192.168.xxxx.xxxx
	wlan1		(Microsoft Wi-Fi Direct Virtual Adapter #2)
		wlan1[0]	fe80:0:0:0:b3dc:49c1:xxxx:xxxx%wlan1
	eth8		(Hyper-V Virtual Ethernet Adapter)
		eth8[0]	172.19.xxxx.xxxx
		eth8[1]	fe80:0:0:0:8c49:bdea:xxxx:xxxx%eth8
	wlan0		(Microsoft Wi-Fi Direct Virtual Adapter #4)
		wlan0[0]	fe80:0:0:0:974b:779b:xxxx:xxxx%wlan0
	eth6		(Bluetooth Device (Personal Area Network))
		eth6[0]	fe80:0:0:0:db1c:dadf:xxxx:xxxx%eth6
	eth3		(Realtek PCIe GbE Family Controller)
		eth3[0]	fe80:0:0:0:eee6:c016:xxxx:xxxx%eth3
	eth1		(Realtek USB GbE Family Controller)
		eth1[0]	fe80:0:0:0:d615:8024:xxxx:xxxx%eth1`

The only way I seem to be able to get the metadata downloaded is to change location. After changing the location, the metadata seems to load and the files then download.

How can I fix this?

**Comment by parg** [comment]
No idea, you'd need to talk to PureVPN if the issue seems to be with their software?

When you say the UDP protocol I assume you mean the that the VPN connections themselves are run over UDP, not anything to do with BiglyBT's TCP/UDP connections that run over the VPN.

**Comment by tonywr71** [comment]
It might be due to changes with PureVPN, but it still appears to be a
standard way of operating. What is it that makes the meta data load behave
differently? Does that use a particular protocol?

**Comment by parg** [comment]
Metadata downloads generally use the DHT(s) to locate their initial peers although magnet links can include explicit trackers and also BiglyBT can also add default trackers via

Options->Plugins->Magnet URI Handler: Additional trackers for metadata peer discovery [one per line]

Adding random trackers to any download will only work if other clients add the same ones of course.

**Comment by parg** [comment]
Closed due to lack of progress
