### ISSUE TITLE
Error: Offline (ConnectException: connect: Address is invalid on local machine, or port is not valid on remote machine)

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#3340]
I've been having problems connecting to the following private tracker. (Note <private_key> replaces the actual key)

http://tracker.gay-torrents.net:6970/<private_key>/announce
http://tracker.gay-torrents.net:6971/<private_key>/announce

Torrents from the site are Private and no other trackers are allowed.
In BiglyBT when connected to PureVPN, I get the message:
Error: Offline (ConnectException: connect: Address is invalid on local machine, or port is not valid on remote machine)

However, if I connect with BiglyBT and NO VPN, it works fine. No connection issue. But I have to pause all other torrents to avoid exposure.  Not an ideal situation.

As a test, I installed qBittorrent 4.6.5 and loaded a torrent from disk that is from the site.
Under the VPN, it worked just fine, and at this time is seeding to a Remote Client at around 150 KiB/s.

So the question is why this tracker works in qBittorrent under PureVPN, but BiglyBT reports an error. With both using the same torrent.

Java 1.8.0_421 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_421

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B3.6.0.1_B31/4 az3 en

**Comment by parg** [comment]
Maybe BiglyBT is messing up the binding to the VPN interface and selecting an invalid local address. Check what set under

Options->Connection->Advanced Network Settings [Socket Options]: Bind to local IP address or interface

Also check the logs to see if there is any more context to the error.

**Comment by NaPurHab** [comment]
![image](https://github.com/user-attachments/assets/3a7275d4-f73b-4d09-af6c-6ca0b84c26bf)

It is binding correctly to PureVPN, the IP matches what the VPN shows and also when I mouse over Routing at the bottom of the main display.

As to checking the logs, I would not know what to look for.

**Comment by parg** [comment]
Look to see if there is an associated stack trace for the error in debug1/2.log

**Comment by parg** [comment]
Also from your post I assume other trackers worth with PureVPN with BiglyBT?

**Comment by NaPurHab** [comment]
> Also from your post I assume other trackers worth with PureVPN with BiglyBT?

I assume you ment Work instead of Worth. But other trackers are working, or report the following: 
Error: Offline (No data received from tracker)
Error: Offline (Unknown host tracker.lelux.fi)
Error: Offline (Exception: IPv6 disabled)
Error: Offline (ConnectException: connect: Address is invalid on local machine, or port is not valid on remote machine)

The IPv6 is because my ISP does not support IPv6. 

Here is a image of all trackers on one torrent.

![image](https://github.com/user-attachments/assets/aab4fbc7-f8d5-467e-9bd2-5e5ace17779d)

As to Debug Logs, see attached
[debug_1.log](https://github.com/user-attachments/files/16473632/debug_1.log)
[debug_2.log](https://github.com/user-attachments/files/16473633/debug_2.log)

**Comment by parg** [comment]
There's a bunch of errors regarding an attempt to bind to a local address of 127.0.0.1:80 - any ideas what might be generating that?

**Comment by NaPurHab** [comment]
Well the only BIND TO I know of is this:
![image](https://github.com/user-attachments/assets/376ec2a7-9119-42d0-836d-8ab434aebd5b)

And the only reference to 127.0.0.1 is the following:
![image](https://github.com/user-attachments/assets/2781adb0-e40e-4577-ba68-f927f05a7f99)

But that should not be causing a BIND TO 127.0.0.1
Unless you know another place to look for it.

**Comment by parg** [comment]
Nope, no idea

**Comment by NaPurHab** [comment]
Well I can find nothing to indicate why this error occurs.  Nor can I find anything that would cause a Bindto 127.0.0.1

So all that can be done is you add it to your list of things to watch for, and we can close this issue.  Hope you will in time, find the solution.
