### ISSUE TITLE
Folder Permissions Needed

### ISSUE THREAD

**Issue by azatsh** [BiglySoftware/BiglyBT#3342]
Hi !
When I try to download a torrent that has a folder I get an error "Folder Permissions Needed".
If I download another torrent without folder (just files) it works normally.
BTW I did setup BiglyBT to use registered media storage which is available for writing. I can create folders using adb (connecting from home PC) and linux commands. 
Please help !

Details:
* Android TV (Core version 4.9.125)
* BiglyBT 1.3.4.3

Pics:
![error1](https://github.com/user-attachments/assets/11dba80b-6592-4cc8-a2ec-dbed3db9805f)
![error2](https://github.com/user-attachments/assets/a2bec93c-a92c-493a-bcad-c609a21f61f0)
![bt_version](https://github.com/user-attachments/assets/82d42f36-4a1d-4f9a-b037-8a7a761a4338)
![device](https://github.com/user-attachments/assets/1802e4fb-c358-4092-892e-34c86f13e002)
![storage](https://github.com/user-attachments/assets/86353802-590b-4670-bca2-60d2cfb36562)

**Comment by parg** [comment]
Sorry but can you please raise this issue against the Android client? See https://github.com/BiglySoftware/BiglyBT-Android

**Comment by azatsh** [comment]
Thanks !
Raised: https://github.com/BiglySoftware/BiglyBT-Android/issues/250
