### ISSUE TITLE
problems with video transfers

### ISSUE THREAD

**Issue by deeparsons** [BiglySoftware/BiglyBT#3344]
why won't bigly transfer my downloaded videos into the azureus folder? for years the videos automatically go into azureus, now I have 9 videos seeding and azureus is showing empty, I then copy them onto my hard drive. I hope somebody can help me, Dee

**Comment by parg** [comment]
Click on a seeding download and look in the General tab below to see where the files are located.

For me the default location is

C:\Users\Paul\Documents\BiglyBT Downloads

You can change the default location via 

Options->Files [Default Directory Options]: Default directory:
