### ISSUE TITLE
Recursively deleting empty directories system wide

### ISSUE THREAD

**Issue by AnotherObligation** [BiglySoftware/BiglyBT#3349]
Manjaro 6.5.13-7 
KDE 6.0.5
Biglybt 3.4.0.0

All empty folders created by my user account have been deleted across all drives and any new empty folders created are deleted automatically while Biglybt is running, even ones made as root.

When I was trying to stop a big torrent with a few thousand files in it Biglybt crashed and I had to force close it and it kept crashing when I tried to restart Biglybt. After restarting my computer Biglybt only shows a splash screen that says "Loading" and when trying to access the settings I get "View will be available when core is done loading".  I checked the debug logs and found this repeated error message

`[17:04:35] [stderr] DEBUG::Mon Aug 12 17:04:35 MDT 2024::com.biglybt.core.util.FileUtil::recursiveEmptyDirDelete::471:`
`[17:04:35] [stderr]   java.lang.NullPointerException`
`[17:04:35] [stderr]     FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, FileUtil::recursiveEmptyDirDelete::421, TorrentUtils::recursiveEmptyDirDelete::4519, DownloadManagerController::setState::1416, DownloadManagerController$8::run::1179, NonDaemonTaskRunner$taskWrapper::run::202, NonDaemonTaskRunner$1::run::160, AEThread2$threadWrapper::run::334`

**Comment by parg** [comment]
How would BiglyBT remove a folder created by the root user when not running as root?

No idea what you've done to achieve this, perhaps you have a torrent saving to "/" - obviously a bad idea

**Comment by parg** [comment]
Also the latest version of BiglyBT is 3.6

**Comment by parg** [comment]
}else if ( state_set_by_method == DownloadManager.STATE_ERROR ){

		      		// the process of attempting to start the torrent may have left some empty
		      		// directories created, some users take exception to this.
		      		// the most straight forward way of remedying this is to delete such empty
		      		// folders here

	  				TOTorrent	torrent = download_manager.getTorrent();

	  				if ( torrent != null && !torrent.isSimpleTorrent()){

	  					File	save_dir_file	= download_manager.getAbsoluteSaveLocation();

	  					if ( save_dir_file != null && save_dir_file.exists() && save_dir_file.isDirectory()){

	  						TorrentUtils.recursiveEmptyDirDelete( save_dir_file, false );
	  					}
	  				}
	  			}

**Comment by parg** [comment]
closed due to lack of progress
