### ISSUE TITLE
Option to not to open Operation in Progress sub window

### ISSUE THREAD

**Issue by SESH01** [BiglySoftware/BiglyBT#3350]
SWT v4942r22, win32
Windows 10 v10.0, amd64 (64 bit)
B3.6.0.0/4 az3 en_GB
Java 1.8.0_202 (64 bit)

An option should be added to enable / disable opening of "Operation in Progress" sub window for every torrent.
This opening is degrading performance drastically.

**Comment by parg** [comment]
Options->Interface->Display [Various]: Suppress File Download popup dialog
