### ISSUE TITLE
Error : Conversion to/from piece reorder not supported??

### ISSUE THREAD

**Issue by Alpskier** [BiglySoftware/BiglyBT#3353]
What causes this error?
Error : Conversion to/from piece reorder not supported

How can this be fixed or prevented??  

Tried rechecking files and moving to a new directory ( on different HD even) 

Do I just need to delete the existing data files and restart the torrent??

**Comment by parg** [comment]
Don't use

Options->Files: Append data to files as downloaded and reorder pieces as the download progresses.

**Comment by Alpskier** [comment]
Thanks -- I turned off the option -- but the error won't clear on the affected files -- is there a method to reset this error - or should I delete and redownload -- these do happen to be very large files - with most subfiles downloaded.

**Comment by parg** [comment]
Unfortunately there is no way to reset this for existing downloads - sorry. Already downloaded files will be fine. Remove the download from your library but leave the data files. Re-add the download with the same save location and recheck them.

The "re-order during download" option was useful at one time but given the wide availability of file systems supporting "spare files" I should really remove it.
