### ISSUE TITLE
BiglyBT is completely frozen

### ISSUE THREAD

**Issue by iibosshog75** [BiglySoftware/BiglyBT#3360]
I can't run BiglyBt or unistall it or reinstall it. It doesn't even load and no process is running in task manager. I updated Java (v8 build 1.8.0-b09) and It hasn't solved the problem. It's frozen. It doesn't load directly if I click on the file in the folder. I ran a chkdsk but it didn't solve the problem. If you give me a console or cmd line solution please be clear and give me a step by step explanation because I am not an expert. Thank you.

* Windows 11 Pro 23H2
* Latest BiglyBt version (can't retrieve it)

**Comment by iibosshog75** [comment]
<!--
I can't run BiglyBt or unistall it or reinstall it. It doesn't even load and no process is running in task manager. I updated Java (v8 build 1.8.0-b09) and It hasn't solved the problem. It's frozen. It doesn't load directly if I click on the file in the folder. I ran a chkdsk but it didn't solve the problem. If you give me a console or cmd line solution please be clear and give me a step by step explanation because I am not an expert. Thank you.

* Windows 11 Pro 23H2
* Latest BiglyBt version (can't retrieve it)

**Comment by parg** [comment]
https://www.reddit.com/r/BiglyBT/comments/1eydff1/biglybt_is_completely_frozen/
