### ISSUE TITLE
'Nothing to show for' is missing from translation

### ISSUE THREAD

**Issue by adem4ik** [BiglySoftware/BiglyBT#3362]
* Manjaro Linux 
* BiglyBT 3.6.0.0
* KDE Plasma 6.0.5

0. BiglyBT has full Russian translation
1. Switch to Russian
2. Watch at Devices section at the left panel

**Result:** `Nothing to show for` isn't translated. This string can't be found at https://crowdin.com/project/biglybt

![изображение](https://github.com/user-attachments/assets/fbde68b3-3258-44ec-a4ec-473c0d78a5d6)

**Comment by parg** [comment]
I've fixed that (and a couple others in the same file), should pop into CrowdIn sometime soon
