### ISSUE TITLE
"Enable IPV6 support" is disabled by default in "Connection -> Advanced Connection Settings" and why?

### ISSUE THREAD

**Issue by Ghost-chu** [BiglySoftware/BiglyBT#3375]
I don't know why this option is off by default, I'm inclined to think it's a relic from the days of Vuze.
Enabling IPV6 by default is crucial today. I don't know why the switch is off by default.

Downloading and seeding are significantly affected without IPV6 support. Considering that no one uses Windows XP anymore (Java 8 is apparently not considering supporting it), I think enabling it by default is a good move.

![image](https://github.com/user-attachments/assets/b8b74a0b-b3c0-4e83-bda3-9c085118f0d6)

**Comment by parg** [comment]
If you have a usable IPv6 network then this should automatically get enabled and you should be messaged

**Comment by Ghost-chu** [comment]
> If you have a usable IPv6 network then this should automatically get enabled and you should be messaged

I have an IPV6 network available (and it works just fine after I manually enable it), and BiglyBT never prompted me to enable it. I wonder when BiglyBT pops up a suggestion dialog?

I noticed that on first launch, BiglyBT did run a network test using M-Lab. But it was interrupted by the BiglyBT update window that followed.

Even when I ran this test manually, it took quite a while and never actually finished. This could be an issue with M-Lab's servers being blocked in my country.

But I think it would be good to have IPV6 enabled by default, especially as more and more users have IPV4 addresses behind NAT. More and more users are upgrading to newer Windows versions, and I haven't seen a Windows XP device in years. Java has apparently dropped support for Windows XP devices as well. This means that the IPV6 network stack should be available on almost any device, as long as the ISP provides IPV6 addresses and the router supports it (which routers usually support by default).

Today, BiglyBT should make a change in attitude towards IPV6, especially since many ISPs are even stopping allocating IPV4 addresses to devices and switching to 4in6.

This will help improve the BitTorrent community environment and greatly improve the user experience.

![image](https://github.com/user-attachments/assets/4b0555f0-5d18-4599-8f73-1b68f0a4d6ba)

**Comment by Ghost-chu** [comment]
I'm trying to promote BiglyBT in the community, but IPV6 is really making it difficult for me to continue. I live in China, and we have a pretty big BT network (and a lot of private trackers). Despite the infamous GFW, BitTorrent is ironically completely legal.
Due to the large number of Internet users, IPV4 addresses are heavily used for NAT, so it is difficult for ordinary users to get an IPV4 address (and may encounter extremely bad NAT environments). But the good news is that the government is encouraging the development of IPV6, and almost everyone's home network has been connected to the IPV6 public network and obtained a usable IPV6 address.
This means that IPV6 is an issue that must be considered.

IPV6 = Light speed download and better connectivity.  
IPV4 = Almost nobody can connect to/you.


So in my opinion, there is no downside to enabling this switch by default, and there are significant benefits.

**Comment by parg** [comment]
It isn't anything to do with the mlab test.

I've just checked and the "auto IPv6 enable" stuff is broken, I'll take a look...

**Comment by parg** [comment]
Actually, it isn't broken (for me), I was using a VPN when testing :)

So it uses "Options->Connection->Advanced Network Settings: Domain name for connection testing" to see if it has a working IPv6 interface - perhaps this is the issue as it defaults to www.google.com ?

**Comment by Ghost-chu** [comment]
> Actually, it isn't broken (for me), I was using a VPN when testing :)
> 
> So it uses "Options->Connection->Advanced Network Settings: Domain name for connection testing" to see if it has a working IPv6 interface - perhaps this is the issue as it defaults to [www.google.com](http://www.google.com) ?

ah thats make sense, google is blocked by government since 2008, so yes it doesnt work for sure.

**Comment by Ghost-chu** [comment]
Maybe BiglyBT can try testing from multiple URLs? (I know of a Steam game where when the game fails to test the connection from google.com, it tries again from www.sina.com. Then a special plot is triggered for players who are truly disconnected from the Internet)

Or just keep IPV6 enabled by default - if that fails, BiglyBT looks like it will fall back to IPV4 connections when IPV6 doesn't work too.

**Comment by parg** [comment]
how about biglybt.com addresses ?

**Comment by Ghost-chu** [comment]
> This whole thing makes no sense, mIDHT uses ipv6 address only, literally, so router.silotis.us only has AAAA record. That means if that DHT start working ipv6 works, I do not see the need to have ipv6 disabled by default, also as was said ipv4 is being removed, White House of USA removed ipv4 for some of their servers. Most people will not even get white ipv4, I have CG-NAT e.g., 100.0.0.0 ipv4.

I totally agree.
Keep the switch on and if IPV6 is available then BBT will obviously go for it; even if it's not available then it will fall back to IPV4 with no ill effects.
However, if it's off by default, users will always miss the pop-up prompt to turn on IPV6 in some cases.

**Comment by Ghost-chu** [comment]
I would still like to see enabling IPV6 by default be considered. Especially given the current IPV6 coverage and the fact that BBT seems to fall back to IPV4 when IPV6 is not available.
There is no tight release schedule at this time, and we should have enough of a window of time to validate this change.

**Comment by parg** [comment]
I'm not doing anything on this at the moment.

The popup prompt isn't telling users they need to turn it on, it tells them it has been turned on for them

**Comment by Ghost-chu** [comment]
> I'm not doing anything on this at the moment.
> 
> The popup prompt isn't telling users they need to turn it on, it tells them it has been turned on for them

I still don't understand why it's necessary to test (request a certain URL), BiglyBT is perfectly capable of enabling it by default right? Modern downloaders are enabling IPV6 by default, BBT can do it too without any negative effects.

This just sounds like it's increasing the load on the test URL server and putting users in the same position again when the test URL server shuts down one day.

**Comment by parg** [comment]
OK, I'll switch the default. If it causes any problems I am expecting you to deal with the support requests.
