### ISSUE TITLE
Avoid use AWT native TrayIcon

### ISSUE THREAD

**Issue by Ghost-chu** [BiglySoftware/BiglyBT#3376]
I actually have the same problem with my Java Application. When using AWT TrayIcon on Windows platform, CJK characters are not displayed.

This is a Java bug that was discovered and reported at least 7 years ago, but has never been patched.  
The only solution is to compile the application using the platform encoding (instead of UTF-8), but this is unacceptable and only fixes encoding issues for a single language.

Maybe use JPopupMenu/SWT for it or just English?

The tray icon is "Bigly BT Notifaction", the SWT's popup menu that used by BiglyBT it self seems not affected.

![image](https://github.com/user-attachments/assets/4ac11c8e-8025-4c40-9631-50af0d36fc41)

**Comment by parg** [comment]
Well we use

org.eclipse.swt.widgets.Tray

so who knows

**Comment by Ghost-chu** [comment]
> Well we use
> 
> org.eclipse.swt.widgets.Tray
> 
> so who knows

https://github.com/BiglySoftware/BiglyBT/blob/8cde295d8b689c81daed7c312c2522c267f5458c/uis/src/com/biglybt/ui/swt/UserAlerts.java#L25

**Comment by Ghost-chu** [comment]
I believe the UserAlerts still use AWT's TrayIcon and that is why.

**Comment by parg** [comment]
You are correct!

**Comment by parg** [comment]
The alert raised in UserAlerts seems to work ok - it results in an alert of this form:

![image](https://github.com/user-attachments/assets/17bfb2b0-aee8-478c-832e-036e444d8062)

**Comment by parg** [comment]
ah, sorry, I see it

**Comment by parg** [comment]
I'll just replace the text with "X"
