### ISSUE TITLE
[Question] Light Seed

### ISSUE THREAD

**Issue by Ghost-chu** [BiglySoftware/BiglyBT#3380]
I've noticed that BiglyBT's Light Seed is very interesting, but the Wiki doesn't go into much more detail than “keep an active connection to the Tracker”.

Does this mean that when the seed is put in Queued state, if a user tries to connect to the Light Seed, this seed will be started and reset to Queued state upon completion.

Or it stops actively accepting connections unless the number of seed sources drops to a certain value before BiglyBT activates Light Seed.

**Comment by parg** [comment]
Internally the core keeps the download in a "queued" state. However, unlike normal queued seeds it announces to the tracker and keeps capacity available so that if an incoming connection is detected the queued seed can be started to service the incoming connection.

**Comment by parg** [comment]
I should add that they only enter this state when the tracker is returning "0 peers" to announces
