### ISSUE TITLE
Request：Please add support for 256MB block of seeds

### ISSUE THREAD

**Issue by i990049** [BiglySoftware/BiglyBT#3383]
Can Bigly BT support 256MB block of seeds? All the libtorrent kernel BT clients QB/TR/DL can open this seed.

[test.zip](https://github.com/user-attachments/files/17003612/test.zip)

PS: When will the Android new version release? The latest Android version is 3.4.0.0. Is it possible for BIgly BT to release a docker version?

**Comment by Ghost-chu** [comment]
![image](https://github.com/user-attachments/assets/caf4b891-eac1-42f7-86fc-997f072595f6)
![image](https://github.com/user-attachments/assets/a356b8ec-3148-4ea3-a8ea-298a4ef66fc7)

I can load this torrent without any issues on BiglyBT 3.6.0.0

**Comment by parg** [comment]
Ah, you mean 256MB piece size in the torrent. Why on earth would anyone create a torrent with such large pieces? This is the unit of verification.

**Comment by i990049** [comment]
> For me I can load the torrent and recheck it just fine.
> 
> Whast OS are you using and what version of Java?



> For me I can load the torrent and recheck it just fine.
> 
> Whast OS are you using and what version of Java?

GitHub_BiglyBT_Installer64.exe 3.6.0.0
win 10 auto install JAVA 8
torrent is created by tixati，large files upload to private tracker need smaller torrent file，which won't be too big size to upload.

**Comment by Ghost-chu** [comment]
> > For me I can load the torrent and recheck it just fine.
> > Whast OS are you using and what version of Java?
> 
> > For me I can load the torrent and recheck it just fine.
> > Whast OS are you using and what version of Java?
> 
> GitHub_BiglyBT_Installer64.exe 3.6.0.0 win 10 auto install JAVA 8 torrent is created by tixati，large files upload to private tracker need smaller torrent file，which won't be too big size to upload.

Could you try set `Max direct memory` to a higher value that more than your torrent block size?

![image](https://github.com/user-attachments/assets/18a0047f-a44c-4b26-99ac-c0beec449fd9)

**Comment by i990049** [comment]
> > > For me I can load the torrent and recheck it just fine.
> > > Whast OS are you using and what version of Java?
> > 
> > 
> > > For me I can load the torrent and recheck it just fine.
> > > Whast OS are you using and what version of Java?
> > 
> > 
> > GitHub_BiglyBT_Installer64.exe 3.6.0.0 win 10 auto install JAVA 8 torrent is created by tixati，large files upload to private tracker need smaller torrent file，which won't be too big size to upload.
> 
> Could you try set `Max direct memory` to a higher value that more than your torrent block size?
> 
> ![image](https://private-user-images.githubusercontent.com/30802565/369100964-18a0047f-a44c-4b26-99ac-c0beec449fd9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NjYzMDYsIm5iZiI6MTcyNjc2NjAwNiwicGF0aCI6Ii8zMDgwMjU2NS8zNjkxMDA5NjQtMThhMDA0N2YtYTQ0Yy00YjI2LTk5YWMtYzBiZWVjNDQ5ZmQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDE3MTMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhNDYxMmRkZTQ1NWQyMDlmM2UyZTE1MjFhZGJhMTRhMzAyYjc3ZjlmYjVmOTMxNzY1NGQ1YWVmMDdkYjllMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SRNy_My3OLWVBdvIEbTtyA3HdL_v1qRwNJf6zxKLXQQ)

这是哪个设置里面的选项？你是JAVA 11？

**Comment by i990049** [comment]
It works. default setting is 247MB

**Comment by Ghost-chu** [comment]
> It works. default setting is 247MB

Glad to hear that, maybe BiglyBT should fix that. @parg

**Comment by Ghost-chu** [comment]
> > > It works. default setting is 247MB
> > 
> > 
> > Glad to hear that, maybe BiglyBT should fix that. @parg
> 
> 我看你挺熟悉这个软件的，如果你有空能不能帮作者把软件剩下没翻译的界面全部翻译好？有些地方的中文翻译有点生硬。

#offtopic This not related to this issue. It's best if we don't continue with irrelevant topics here.

If you want continue talk with me, send email to me is a better choice. ghostchu {at} qq.com.

And yes, the chinese translation improvement & correction has been in progress.

**Comment by parg** [comment]
The default is "blank" - this let's the JVM decide what the best setting for direct memory is. According to https://eclipse.dev/openj9/docs/xxmaxdirectmemorysize/

Java 8 By default, the amount of native memory used for Direct Byte Buffers is limited to 87.5% of the maximum heap size.

Java 11 plus By default, the amount of native memory used for Direct Byte Buffers is limited to the maximum heap size.

**Comment by Ghost-chu** [comment]
> The default is "blank" - this let's the JVM decide what the best setting for direct memory is. According to https://eclipse.dev/openj9/docs/xxmaxdirectmemorysize/
> 
> Java 8 By default, the amount of native memory used for Direct Byte Buffers is limited to 87.5% of the maximum heap size.
> 
> Java 11 plus By default, the amount of native memory used for Direct Byte Buffers is limited to the maximum heap size.

afaik, BiglyBT default Max Heap Size is restricted to 256MB by default, so i think that's why it doesn't work for him (Java8) but works for me (Java21)

**Comment by Ghost-chu** [comment]
I think BBT can request more memory, 256MB seems too little at 2024. 512MB is a good choice.

**Comment by parg** [comment]
Nobody should create torrents with a piece size of 256MB

**Comment by i990049** [comment]
> Nobody should create torrents with a piece size of 256MB

private tracker uploading TB file size do care about the torrent size.

**Comment by parg** [comment]
Nobody should create torrents with TB size :)

**Comment by parg** [comment]
By the way you do get TWO alerts raised telling you about the issue:

Memory allocation failed: Out of direct memory space.
To fix: Use the -XX:MaxDirectMemorySize=512m command line option,
or upgrade your Java JRE to version 1.4.2_05 or 1.5 series or newer.

我的BT软件: One or more piece checks failed: Cannot reserve 268435456 bytes of direct buffer memory (allocated: 303619, limit: 201326592)

**Comment by parg** [comment]
That's an old error message, I'll improve it (and make internationalise it)

**Comment by Ghost-chu** [comment]
> Nobody should create torrents with TB size :)

In today's modern world, HTTP hypertext transfer is sufficient for transferring medium and small sized files.

BitTorrent is often used for very large files (to minimize server costs, and to increase speed through peer-to-peer networks), in which case the seed size can be very large indeed.
The Uploader creates a collection of file packages and downloads the portion of the files it needs through the downloader's selective file download. This avoids having to slice a seed into multiple ones -- multiple seeds are more likely to lose all their source.

**Comment by i990049** [comment]
> Nobody should create torrents with TB size :)

If you are a user of private tracker, you can find files larger than 1TB. such as
Urusei yatsura AKA Those Obnoxius Aliens S01 1981 1080p JPN Blu-ray AVC LPCM 2.0 
1.367 TiB
Some PT restrict the torrent size.256MB piece size make the torrent file smaller and higher upload speed. Smaller piece size makes torrent file bigger can't be uplaoded to PT.

**Comment by Ghost-chu** [comment]
> > Nobody should create torrents with TB size :)
> 
> If you are a user of private tracker, you can find files larger than 1TB. such as <censored> 1.367 TiB Some PT restrict the torrent size.256MB piece size make the torrent file smaller and higher upload speed. Smaller piece size makes torrent file bigger can't be uplaoded to PT.

Mention the torrent name in anywhere in this repository will be deleted for legal reason, dont do that.
