### ISSUE TITLE
Torrents disappear after opening

### ISSUE THREAD

**Issue by ThrowawayLawd** [BiglySoftware/BiglyBT#3392]
I tried starting to DL a torrent via magnet. It took too long to load, so I decided to abort it and use the manual .torrent file to start the DL.  
Torrent refused to open/disappears. 
Magnet is the same case.  It shows up on the interface, but shortly after it disappears.
No matter which torrent I try it's the same result.  
No errors shown. 
I can make a video if needed. 
(used vuze/bigly for years, nothing like this happened before)

Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B3.6.0.0/4 az3 en

**Comment by parg** [comment]
Check the debug_1/2.log files in %appdata%\BiglyBT\logs

Also check your configuration setup under Options->Files  and Options->Files->Torrents for default save locations etc
