### ISSUE TITLE
Additional tracker problem.

### ISSUE THREAD

**Issue by Aalbergsjo** [BiglySoftware/BiglyBT#3393]
Hello. I have lately been adding some trackers in BiglyBT. Now, i do think i got most figured out. But one of my trackers changed from http:// to udp://. Me thinking i wrote wrong, so i changed it back. And now i have two trackers togheter in one group. Same URL, one with udp and the other with http. I have tried in every possible way i can think of, to get it fixed now. Everytime i add udp://tracker.opentrackr.org:1337/announce, i also get hes "twin brother" http with him. Please tell me there is someone here who knows a fix for it? I have tried Edit Tracker URL from all kinds of directions, i also deleted BiglyBT and reinstalled it without any luck. 

* Windows 10 PRO
* BiglyBT 3.6.0.0
* For *nix: Desktop Environment

**Comment by parg** [comment]
It is a consequence of

https://www.bittorrent.org/beps/bep_0034.html

If you don't like it then disable it via

Options->Tracker->Client [Protocol]: Enable handling of DNS tracker records used to ameliorate accidental DDOS

**Comment by Aalbergsjo** [comment]
Thats great. Thank you so very much.
