### ISSUE TITLE
Error: Offline (IOException: Server returned HTTP response code: 403 

### ISSUE THREAD

**Issue by 0tk-01** [BiglySoftware/BiglyBT#3394]
im getting this of the sudden after update ill reseerach IOE to try fix it 

* OS and version:win11: version 23H2
* BiglyBT Version Number:3.6.0.0

**Comment by 0tk-01** [comment]
i gave user full controll made sure file is not read-only

**Comment by parg** [comment]
How about putting some actual information in your issue?
