### ISSUE TITLE
Feature Request: add Prometheus metrics

### ISSUE THREAD

**Issue by Mikle-Bond** [BiglySoftware/BiglyBT#3395]
I would like to monitor BiglyBT externally, via Prometheus. My reason is that Prometheus integrates well with AlertManager and can be configured to notify me about any anomalies before they escalate.

As for implementation, I see that a lot of stats are available in UI in "Tools -> Statistics -> Counters" tab. In theory, the baseline implementation would be just to convert the names for them from `dot.notation` into `underline_notation`, prefix with something like `biglybt_` and serve on HTTP endpoint with some comments per metric.

There are some caveats, of course. Prometheus encourages to give names to counters that end with one of `_total/_sum/_count/_bucket`, which is already somewhere done correctly. Notable exceptions I see are `net.utp.connection.count` and those metrics that have `.con.` part - those are gauges, not counters.
Maybe some of the metrics would benefit from extracting some labels, for example `net.read.control.***.count` could become `biglybt_net_read_control_count{state="***"}` (or something similar).

As for what is not covered by this selection of counters, I would love to see a counter for tracker successes/errors. Maybe even with a label corresponding to the error type. This would help me to indicate moments when my ISP implements horrors beyond my comprehension.

I see the #122 mentions similar request, but the answer there suggests using "Options -> Statistics -> Snapshot" feature that saves XML files, and I'm not sure what software can parse and process those.

**Comment by parg** [comment]
Sounds like an interesting project. I could create a simple plugin to do the "baseline" implementation and then you'd need to drive it from there by requesting changes/enhancements to it?

**Comment by parg** [comment]
I created a skeleton plugin, see https://plugins.biglybt.com/ for "Prometheus Statistics"

All it currently does is replace "." with "_" in the entry names.

I'm pretty busy and have no interest in the plugin myself so can you detail the changes and additions that would help and I'll try and get around to making them.

**Comment by Mikle-Bond** [comment]
Thank you @parg , that looks promising! I only could try it out a bit yesterday, but here's what I found.

## Line endings

Prometheus returns errors on scraps. I assume this might be due to line endings: plugin returns CRLF, while prometheus expects LF. At least that's the only difference I see between plugin's output and other exporters.

```logfmt
ts=2024-10-03T15:29:39.736Z caller=scrape.go:1362 level=debug component="scrape manager" scrape_pool=biglybt target=http://localhost:9093/ msg="Append failed" err="strconv.ParseFloat: parsing \"0\\r\": invalid syntax while parsing: \"disk_read_bytes_multiple 0\\r\""
```

## Default port

 `9093` is used by default by AlertManager. There's a [list of ports](https://github.com/prometheus/prometheus/wiki/Default-port-allocations) used by other exporers. I would suggest changing the default to something unused, e.g. `9089` is currently free. This way we can add this plugin to that list)

## QoL things

- default path for metrics is `/metrics`
- returned content-type is usually `text/plain`
- I still think metrics should be prefixed with "biglybt_". When autogenerating metric names, this is a less error-prone thing to do.
- I'd like to help more, but I am not familiar with Java ecosystem. Is there some guide how to build and test this plugin locally?

**Comment by parg** [comment]
I've built version 0.1.1 which should be available for auto-update - it has your changes from above.

The source is available in 

https://github.com/BiglySoftware/BiglyBT-plugin-prometheus

with the main dependency being on the main repository

https://github.com/BiglySoftware/BiglyBT

The main repository has soem basic info on setting up a dev environment on the main repository page. This is for core development but if you can get that working then setting up plugin development is pretty straight forward.

I use the Eclipse IDE from https://eclipseide.org/

However if you just want to send me the details of the changes you would like to see I'm happy to implement them.
