### ISSUE TITLE
How to set auto update RSS without auto download torrents when opening BiglyBT ？

### ISSUE THREAD

**Issue by i990049** [BiglySoftware/BiglyBT#3399]
* OS and version win 10
* BiglyBT Version Number 3.6.0.0
* For *nix: Desktop Environment
My setting only update after 90 minutes, can't update RSS when opening BIGLYBT.
<img width="756" alt="2024-10-03_095203" src="https://github.com/user-attachments/assets/22bb3286-fb95-477f-82f1-70750471736e">

**Comment by parg** [comment]
RSS update frequency is what it is, it is obeyed across restarts.

You can change the frequency of a feed by right-clicking it and selecting "update period"

If you want to update them all manually then right-click on the Subscriptions header in the sidebar and select "Update All Now"

**Comment by i990049** [comment]
So BIGLYBT doesn't have the setting auto updating all RSS when open it？I have to do it manually？

**Comment by i990049** [comment]
So BIGLYBT doesn't have the setting auto updating all RSS when open it？I have to do it manually？It's very different from other bittorrent software. Hope next version can add this setting. Thank you.

**Comment by i990049** [comment]
So BIGLYBT doesn't have the setting auto updating all RSS when open it？I have to do it manually？It's very different from other bittorrent software. Hope next version can add this setting. Thank you.
