### ISSUE TITLE
Metadata transfer not completing (stuck at 64 MBytes) not connecting "to any peers while transferring"

### ISSUE THREAD

**Issue by jalambertc** [BiglySoftware/BiglyBT#3400]
I try to download a torrent to BiglyBT, but the metadata transfer gets stuck at 64 Mbytes (for all torrents) despite there being several peers and seeds but none are connected

* OS and version - Windows 11
* BiglyBT Version Number 3.6.0.0
* For *nix: Desktop Environment  SWT v4942r22, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B3.6.0.0/4 az3 pt_BR

**Comment by parg** [comment]
So you already posted this on redit, twice. Maybe the peers are fake, who knows.

**Comment by ValeZAA** [comment]
"metadata transfer"

Here Java heap by default cannot even open 23 megabyte torrent files downloaded using magnet links. Try bt v1 hash: 51603bff88e0a1b3bad3962614978929c9d26955
