### ISSUE TITLE
Odd issue with dark theme - text is blue on a grey background

### ISSUE THREAD

**Issue by SleepyCatten** [BiglySoftware/BiglyBT#3401]
Using the dark theme, certain elements have blue text on a light grey background. Is this intended behaviour, something that can be edited, or a bug? Do I perhaps have a corrupted theme, installation or similar?

![image](https://github.com/user-attachments/assets/18e5c6e7-a0b0-49f4-a2df-2f3950a7c84f)
![image](https://github.com/user-attachments/assets/793593f5-5c09-4553-88dc-bd4cba6e7810)
![image](https://github.com/user-attachments/assets/2b86ae00-c8dc-417a-bdfe-fcfb67acf8a3)

* OS and version - Windows 10 22H2 OS Build 19045.3930
* BiglyBT Version Number - 3.7.0.0

**Comment by parg** [comment]
That's as good as it gets I'm afraid, Dark mode support on Windows isn't great.

**Comment by XCanG** [comment]
Is there possibility to fix directory input in popup on adding new torrent on dark theme? The thing is: when a window is opened and it show previous directory - it is in correct dark mode, but when I start typing or open selection (dropdown), it become white and won't go back to dark theme. It is quite difficult to type and see light gray text on white background.

**Comment by parg** [comment]
sure
