### ISSUE TITLE
Repeated restart request after update. Wrong encoding in restart.bat

### ISSUE THREAD

**Issue by dimagsv** [BiglySoftware/BiglyBT#3404]
I've got repeated restart request after update from 3.6.0.0 to 3.7.0.0.
The reason for this is incorrect encoding of the path in the file restart.bat. The path is in ansi encoding, but should be in oem encoding.

* windows 10 22H2
* BiglyBT 3.6.0.0 -> 3.7.0.0

Java 11.0.17 (64 bit)
  BellSoft
c:\program files\bellsoft\libericajre-11-full

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B3.7.0.0/4 az3 ru_RU

**Comment by parg** [comment]
Doubt it, the restart mechanism has worked well for hundreds of thousands of users over a decade.

Perhaps it is somethign to do with your JVM, never heard of it.
