### ISSUE TITLE
Request add IP filter from url

### ISSUE THREAD

**Issue by i990049** [BiglySoftware/BiglyBT#3405]
why need it？
https://github.com/anacrolix/torrent/discussions/891
https://github.com/Simple-Tracker/qBittorrent-ClientBlocker
https://github.com/PBH-BTN/PeerBanHelper

so I want to add this to bigly BT just like tixati, thanks.
https://bcr.pbh-btn.ghorg.ghostchu-services.top/combine/all.txt
![屏幕截图(294)](https://github.com/user-attachments/assets/456f020e-61ec-4516-b55e-a8fc37765e91)

**Comment by parg** [comment]
You mean

Options->IP Filters [Auto Loading]: IP filter file to autoload

?

**Comment by i990049** [comment]
![屏幕截图(295)](https://github.com/user-attachments/assets/70fc97b3-c154-4d2b-ae80-a1118be4c21d)
Regular updates from url
https://bcr.pbh-btn.ghorg.ghostchu-services.top/combine/all.txt

**Comment by parg** [comment]
So putting that url in the config field I indicated doesn't work?

**Comment by i990049** [comment]
it works here, maybe there is no ip needed to be block of your torrent.
https://www.cometbbs.com/t/94202/1
