### ISSUE TITLE
crash when handling large torrent files

### ISSUE THREAD

**Issue by Tom-Neverwinter** [BiglySoftware/BiglyBT#3406]
* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment

Windows 10
latest biglybt version

mame sets seem to make biglybt really unhappy

**Comment by parg** [comment]
Try beta 3701_B05+

**Comment by parg** [comment]
Closing due to lack of feedback

**Comment by Tom-Neverwinter** [comment]
seems to resolve the issue. if it has to resume it will fight you but you can complete it. same  if it has a error you can run the recheck function after fighting it
