### ISSUE TITLE
Seed and anonymous bridge optimalization required with simple new default settings

### ISSUE THREAD

**Issue by mx5kevin** [BiglySoftware/BiglyBT#3408]
* OS and version: Windows 10
* BiglyBT Version Number: 3.7.0.0

Make this settings default to help Seeding and easier downloads 

1. Tools/Options/Startup&Shutdown/Start BiglyBT on login

2. Tools/Options/Interface/Close minimize to system Tray (BiglyBT not started minimized without this at system startup)

3. Check default way Tor and I2P Helper plugins in the installation process (not checked default way currently) and add to them in the installer package. This required to bridge widely from the public network to the anonymous network torrents what seeded BiglyBT users. Without it, one of the most useful function of this client will not work because public torrents are not bridged to the anonymous network. This is the most important.

**Comment by parg** [comment]
Thanks for the advice
