### ISSUE TITLE
BBT stealth enabling I2P on clearnet torrents

### ISSUE THREAD

**Issue by frederick-bruckman** [BiglySoftware/BiglyBT#341]
All downloading cleanet torrents stealthily enable I2P at random times and also roughly when they transition to seeding. (Seeding clearnet torrents, once I2P is disabled, are NOT automatically enabled.)  The transfer rates between clearnet and i2p are so disparate, there's no really no sense mixing on download, so I try not to: If there's only clearnet trackers, I turn off I2P in the open dialog. Nonetheless, BBT keeps enabling the I2P network for these torrents, even after I keep disabling it in the Privacy tab.

Some additional information: typically, "Search DHT" in the open dialog or in the Privacy tab detects no other nodes except my own node.  (Also, the issue happens even if I don't use "Search DHT" all.) 

I have UNCHECKED ``Options -> Plugins -> I2P Helper -> "Enable the automatic tracking of public network torrents in the I2P network''. 

This is happening consistently with both 1.2+ Betas, 1.4 and 1.4+ Betas, and with the older Java 8.

Current System Info:

Java 1.8.0_162 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_162

SWT v4757, win32
Windows 10 v10.0, amd64 (64 bit)
B1.4.0.1_B12/4 az3

**Comment by parg** [comment]
Your use of the word 'stealth' implies that it is being done on purpose, behind your back, which it isn't.

However, there does appear to be a bug that is causing the disabling of mixing to be ignored which I will fix.

By the way, the purpose of network mixing isn't really to support people primarily performing public downloading, it is there to altruistically help people anonymously downloading things that are poorly seeded within the anonymous network itself.

Thanks

**Comment by parg** [comment]
Should be fixed in version 0.9.33.1.2 - please report if you are still seeing the issue

**Comment by frederick-bruckman** [comment]
I stand corrected (about the stealth thing). Since it takes the unfortunates (who aren't using BBT -- BBT on I2P downloads quite a bit faster than the included I2P client) several days to take a ~1GB torrent, giving them a few pieces in the 15 minutes it takes me to download on the clearnet scarcely helps them at all. It's just as well to do one thing at a time. I'll report after I've downloaded a few things. Thanks!

**Comment by frederick-bruckman** [comment]
It seems to be fixed. Thanks!

**Comment by parg** [comment]
No problem, thanks for reporting!
