### ISSUE TITLE
can't open magnets anymore

### ISSUE THREAD

**Issue by legacychimera247** [BiglySoftware/BiglyBT#3412]
Hello, i suppose the title says it all

all of a sudden clicking on a magnet does nothing, is there a way to restore magnet association?it should be in "settings>interface" but couldn't find it

tried installing another torrent client, and it just open magnets, then as soon as i remove it, magnets aren't opened anymore

also tried re-installing clearing old configuration but that didn't help

i'm on fedora 41 freshly installed with biglybt 3.7

**Comment by parg** [comment]
Normally it is

Options->Interface: Reset file associations (.torrent) and magnet handler (magnet:?xt=...)

but that isn't supported on Linux.

Try Google, first hit for me when searching "browser magnet association linux" is

https://forums.linuxmint.com/viewtopic.php?t=275637

Linux Mint I know but the answer is out there...

**Comment by legacychimera247** [comment]
hello, probably but i do suppose this is another problem

i was able to reset the association but when i click on a magnet bigly does not open at all, so i do suppose it's another problem

browser actually asks me if i want to launch bigly, but upon clicking yes nothing happens...

so i du suppose it's different

i will have a look at that file in the meantime
