### ISSUE TITLE
Column Setup buttons overlap each other in different translations

### ISSUE THREAD

**Issue by adem4ik** [BiglySoftware/BiglyBT#3416]
* Windows 10 x64
* BiglyBT Version Number: B3.7.0.1_B10/4

1. Switch UI language to Deutsch/Russian
2. Open Library view
3. RMC on columns header -> choose Column Setup

**Result:** `Reset`, `Default`, `OK` are overlapped.

![изображение](https://github.com/user-attachments/assets/6ccfa57e-5f08-4767-b9bc-6a897c91d63a)

**Comment by parg** [comment]
I'll make it a bit wider :)
