### ISSUE TITLE
On completion move fails due to invalid characters

### ISSUE THREAD

**Issue by Dingmatt** [BiglySoftware/BiglyBT#3418]
I have a setup where BiglyBT (installed on Linux Mint 22) copies files, on completion, to a shared Windows (NTFS) directory. 

The problem I'm experiencing is that BiglyBT occasionally tries to create files or folders (either ones within the torrent or created using the 'Extend the move-to location with a sub-directory based on download name' option) that contain invalid characters, at least for Windows, so the 'on completion' task fails.

I realize it's a fringe case but would it be possible to add an option to remove/replace certain characters on file/folder generation?

Example: Torrents named "Test: Test Torrent 1", with the "Extend the move-to location" option enabled BiglyBT tries to create a "Test: Test Torrent 1" folder on the Windows drive, which fails, as the colon character isn't valid.

* Linux Mint 22 (Xfce Edition) / Windows 11
* BiglyBT Version Number 3.7.0.0

**Comment by parg** [comment]
BiglyBT tries to protect you against unspported characters on the system it is running, unfortunately it doesn't do that across operating systems (if you were running on Windows it would rename ":").

Only solution is to use

Options->Files: Character conversions for torrent files [, separated]

to covert : into something else.

This will break any existing downloads you have with converted characters though.

**Comment by Dingmatt** [comment]
I had considered that setting, so I'm glad to see i was on the right track. Unfortunately I couldn't seem to get it to work.

Would you mind giving me an example of how you'd set up converting the colon character? I can then sort things out on a per case basis.

Many thanks

**Comment by parg** [comment]
The syntax is supposed to be (for example)

`a=b,c=d,e=f`

to replace 'a' with 'b', 'c' with 'd' and 'e' with 'f'

So to replace ':' with '_' you would use

`:=_`
