### ISSUE TITLE
Is it possible to support lsd and pex protocols?

### ISSUE THREAD

**Issue by i990049** [BiglySoftware/BiglyBT#3421]
I have download part of torrent by cellphone, now I want to download the rest on Windows. If bigly BT support lsd and pex protocols, it will be convenient.

**Comment by parg** [comment]
It supports PEX. It has its own version of local peer discovery which works between BiglyBT instances.

**Comment by i990049** [comment]
why can't bigly bt connect to other client by lsd? possible to  update it?

**Comment by parg** [comment]
Not unless someone wants to go and write a plugin. Do you?
