### ISSUE TITLE
Text isn't wrapped inside Options - Files - Performance options

### ISSUE THREAD

**Issue by adem4ik** [BiglySoftware/BiglyBT#3428]
* OS: Windows 10
* BiglyBT: B3.7.0.1_B22/4

1. Open `Options - Files - Performance options`

Result: Text isn't wrapped. That causes a long scrollbar.
Expected result: Text is wrapped as it shown on the old screenshot from Crowdin.

![изображение](https://github.com/user-attachments/assets/a5f0ec82-40e1-4dec-aad7-9304c279fefd)

**Comment by parg** [comment]
Ta, fixed next beta
