### ISSUE TITLE
Strange display corruption when scrolling in Library view

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#3433]
Has anything changed recently with the way the Library rows are drawn, that might be affecting the display when scrolling long tables? I can't rule out the possibility that this is being caused by Fedora 41 bringing either (a) a newer SWT version or (b) a TightVNC server update, but lately this is what I'm seeing in the Library views:

My lower (Completed) torrents list is far longer than the 14 visible rows, so it can scroll vertically. (And horizontally, but that's not relevant AFAICT.)

If I scroll down the list _slowly_ with the mouse wheel, only the bottom two rows move upwards, while the other 12 remain static, and the upward-scrolled rows all seem to bunch up on top of each other (in the Z-axis sense) on row 12.

If I scroll the list _faster_, it breaks out of that mode and all of the rows move as they should. But if I go back to scrolling more slowly, back to only partial movement.

I know that _sounds_ exactly like a VNC display corruption issue, but I'm on a local gigabit LAN so there's no reason to think the VNC connection would be bandwidth-starved  or heavily compressed, and it doesn't happen with other long lists, like the RSSFeed Scanner history view. So I'm inclined to think it's BiglyBT or SWT, not the display server.

It *does* also happen if I switch to a tag view (full-window, double-height rows) — same symptoms, only the bottom two rows move when scrolling slowly.

### System block

Java 11.0.25 (64 bit)
  Red Hat, Inc.
/usr/lib/jvm/java-11-openjdk-11.0.25.0.9-3.fc41.x86_64

SWT v4956r12, gtk/3.24.43, zoom=100, dpi=96
Linux v6.11.10-300.fc41.x86_64, amd64 (64 bit)
B3.7.0.1_B24/4 az3 en

**Comment by ferdnyc** [comment]
OK, this feels like a red flag, especially based on the timing: b696c0c.

**Comment by parg** [comment]
Thanks, try out B25
