### ISSUE TITLE
Completed & Manually Stopped Torrents Restart Themselves

### ISSUE THREAD

**Issue by dbareis** [BiglySoftware/BiglyBT#3438]
Completed & Manually Stopped Torrents Restart Themselves (to queues/ seeding state).

This has been happening for beta versions for a while.  I don't think I have set any option that might do this but in any case I looked for such options and didn't find them.
---

Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B3.7.0.1_B25/4 az2 en

**Comment by parg** [comment]
Only way this can happen (as far as I know) is if you have configured a Tag "execute on assign" action to do so.

**Comment by dbareis** [comment]
I only have 1 action and that is to stop seeding.  Can this be deemed
somehow?

---
Thanks
