### ISSUE TITLE
Add MANAGE_EXTERNAL_STORAGE permission

### ISSUE THREAD

**Issue by wIRC** [BiglySoftware/BiglyBT#3444]
* Android TV 12
* BiglyBT 1.3.4.3

Add MANAGE_EXTERNAL_STORAGE permission so we can use an external drive on Android TV.

Android TV doesn't have a built in file picker, so we cannot add permission to a specific folder.

**Comment by parg** [comment]
Please use https://github.com/BiglySoftware/BiglyBT-Android/issues for Android issues
