### ISSUE TITLE
3.7.0.0 tracker Error: Offline (ConnectException: Connection refused: getsockopt)

### ISSUE THREAD

**Issue by SUCM** [BiglySoftware/BiglyBT#3446]
just realized that every torrent in BiglyBT (been up for ~10 days) have tracker issue yesterday but other sources like peer cache and mlDHT...etc still worked fine, so I checked source list and saw every tracker has below status
`Error: Offline (ConnectException: Connection refused: getsockopt)`

I tried whole bunch of things including network test, but couldn't resolve that error on any tracker. searched through Bigly logs but also yielded nothing. in the end, a restart of Bigly resolved the issue. however, 12 hours later, I started seeing this error showing up again on few trackers on random torrents. I wonder if all trackers on all torrents will eventually get into this status when given enough time (~1 week?). don't think I had seen this in 3.6.0.0 or earlier versions even when running Bigly for more than 3 weeks continuously. other torrent clients running concurrently don't have this issue, so this seems to be isolated to Bigly

let me know what I can check to debug this

**Comment by parg** [comment]
Some kind of network level bug, nothing comes to mind. Perhaps try a reboot. try a different Java version
