### ISSUE TITLE
Midi DHT update problem in Spreadsheet original view

### ISSUE THREAD

**Issue by RigmarRadio** [BiglySoftware/BiglyBT#35]
* Windows 10 64 bit Creators Edition
* BiglyBT Version 1.0.0.0!
* BiglyBT Tabbed Speadsheet Advanced View

Dear All,  I seem to have a problem in that I have never had a BiglyBT update and restart and I keep getting a MidiDHT plugin update from Version 1.6 to Version 2 downloading at the start of every BiglyBT session which reports as having installed correctly, but you have guessed it, on restart of BiglyBT it goes back and downloads and reinstalled the exact same update it reported as having installed correctly.

Have I really got the latest version of BiglyBT that is Version 1.0.0.0! or as I suspect is the Auto updater also not working for me. 
![untitled](https://user-images.githubusercontent.com/22588387/29562508-de2f54bc-8739-11e7-9cd5-a95f2d347e1e.jpg)
![untitled1](https://user-images.githubusercontent.com/22588387/29562507-de2f094e-8739-11e7-8050-afc5ae980fe7.jpg)
![untitled2](https://user-images.githubusercontent.com/22588387/29562509-de311b80-8739-11e7-830c-363c96230edd.jpg)

Kind regards.

**Comment by parg** [comment]
Hmm, can you take a look in your per-user plugin folder (the ...\Roaming\BiglyBT\plugins one) for the 'mlDHT' subfolder and see if there is a 'plugin.properties' file in there? If so try deleting it and restarting.

**Comment by RigmarRadio** [comment]
Wow did not expect such personal service.  Thank you.  Yes I will go take a
look and report back right way.   Thank you.

Malta Music Services - Rocking Malta since 2010
internationalmusicservices@gmail.com (Sales & Service)

+356 2703 0790 Office
+356 9901 1827 Mobile

HD Media/Playout system Lease to Bars, Clubs, Hotels, Receptions - anywhere
where the public will enjoy Music Video's

**Comment by RigmarRadio** [comment]
OK that directory did not exist on my NVME SSD boot drive, so I have cleaned and uninstalled all files from Vuze and BiglyBT as well as my Java and started again with a clean install.   I got this error message right away when installing plugins:

![untitled](https://user-images.githubusercontent.com/22588387/29611358-885cc514-87fd-11e7-8b57-1a96c74b5859.jpg)
![untitled1](https://user-images.githubusercontent.com/22588387/29611363-8ab4b1dc-87fd-11e7-957a-3580720d39ed.jpg)

I will now attempt to install midHT and again report back.   Note it would be helpful in in Windows 10 I could copy the error box texts rather than having to send you a screen shot, but for whatever reason highlight the RED error text would not allow me to Copy, Cut or Past in this OS.

**Comment by RigmarRadio** [comment]
OK this time around midHT latest Version 2 did install, so just looks like the BiglyBT updater is the only problem left that I have.   Hope you can read the screen shot ok.   I will try make the font larger my end if not.

**Comment by RigmarRadio** [comment]
Not sure if this helps but this is a screen shot of the Plugin Overview showing miDHT correctly installed now but the updater does not seem to be working as I am still on your first release version of BiglyBT.
![untitled](https://user-images.githubusercontent.com/22588387/29611729-fcc4bd3e-87fe-11e7-80ef-7fb94d0a7ce0.jpg)

**Comment by parg** [comment]
The errors you say with the azupdater/azplatform2 plugins are weird as those components usually come pre-installed with BiglyBT (they're not 'real' plugins in the sense that they are core components) - not sure why you got the errors but at least things seem be working! Thanks

**Comment by RigmarRadio** [comment]
Yes things seem to be working but please confirm that we are on the release version and that there have been no updates as my version still reads !BiglyBT 1.0.0.0!

Cheers.

**Comment by parg** [comment]
There have been a few beta versions since 1.0.0.0 - join the beta program if you are interested in them! See the Help menu for the option to join,.

**Comment by RigmarRadio** [comment]
Cool,  I will thank you.   I always looked forward to the Beta Versions on Vuze until they stopped.   Thank you for your help in solving my minor problem.
