### ISSUE TITLE
Please port Tracker URL Adder plugin

### ISSUE THREAD

**Issue by deus0ww** [BiglySoftware/BiglyBT#351]
Please port this plugin. It's very useful for old torrents with few seeds. Thank you.

https://plugins.vuze.com/details/aztrackerurladder

**Comment by parg** [comment]
You can do the same using Tags - see https://github.com/BiglySoftware/BiglyBT/wiki/Tags#Tracker_Templates

**Comment by deus0ww** [comment]
I've been using Azureus/Vuze/BiglyBT for over a decade and never knew about this. This is freaking incredible.

**Comment by parg** [comment]
Tell me if you have any problems and I'll take a look :)
