### ISSUE TITLE
No Option to Download Beta Versions

### ISSUE THREAD

**Issue by LuvBiglyBT** [BiglySoftware/BiglyBT#353]
Hello All!  Finally took the dive and switched over to BiglyBT after many years as a Beta tester for Vuze.  In would like to continue as a beta tester for BBT but, even though I migrated my testing staus to BBT and then left and returned the beta program, for the life of me, i cannot find a way to download the beta versions.  I have tried checking for updates via About: when it shows their is an update available..nothing.  I tried going to the site, I tried clicking on the linkafter opening the Beta entry in the nav window on the left.  Nothing works.

Can someone help me out with this?

Thanks, LuvBiglyBT (formerly LuvVuze)

Java 1.8.0_152 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4757, win32
Windows 10 v10.0, amd64 (64 bit)
B1.4.0.0/4 az3

**Comment by parg** [comment]
Welcome :)

If you click on the 'progress reporting' icon in the status bar after doing a 'check for updates' there should be some log info there (click on 'details' to expand it) - copy/paste that info here so we can see if there are any clues.

thanks!

**Comment by LuvBiglyBT** [comment]
Well HELLO again, Parg!

 

Nice to be back and hear from you again.

 

Here is the “log”:

 

Checking for Updates - added

Checking for Updates

    Core Patch Checker -     Adding update: Core Patch Checker

    Core Patch Checker - Finished

    Platform-specific support -     Failed to load plugin details for the platform manager: Plugin list load failed, Proxy not available

    Platform-specific support - Failed

Failed

    Mandatory plugins -     Failed to load plugin details: Plugin list load failed, Proxy not available

    Mandatory plugins - Failed

Failed

    Non-mandatory plugins -     Failed to load plugin details: Plugin list load failed, Proxy not available

    Non-mandatory plugins - Failed

Failed

    BiglyBT Core -     Core: latest_version = '1.4.0.1_B15', file = 'http://version.biglybt.com/biglybt-files/core/BiglyBT1401-B15-signed.jar.torrent?i2p=1'

    SWT library -     SWT: current version = 4757, latest version = 4757

    SWT library - Finished

    BiglyBT Core -     Adding update: Core Azureus Version

    BiglyBT Core - Finished

Finished

 

Obviously something is not right :(

 

Best regards,

 

LuvBiglyBT

**Comment by parg** [comment]
hi :)
Have you selected 'update anonymously' under Tools->Options->Interface->Start? Also check that you have the 'TorHelper' plugin installed.

**Comment by LuvBiglyBT** [comment]
Parg,

 

Download Anonymously was checked.  Not knowing if this was the issue or not, I unchecked it, saved, and restarted the program.  When I checked updates again, the update screen came up and I was able to download the update.

 

So, should I leave it unchecked or it supposed to be able to download while it is checked?

 

LuvBiglyBT

**Comment by parg** [comment]
It used to work but it uses the TorHelper plugin to perform the update check over Tor - if this plugin isn't installed or something is borked with it then the process will fail.

**Comment by GV-Mike** [comment]
I had a similar problem.  I UNCHECKED "update anonymously" and problem corrected.  I am guessing at an explanation:  I have a TorGuard proxy which requires a username and password.  The update request is being sent thru the proxy and sent as anonymous (i.e. without then required proxy identification) and thus is rejected by the proxy - resulting in proxy not available error. No list downloaded and failure.  If non-anonymous, proxy connection, list downloaded and check performed.

**Comment by LuvBiglyBT** [comment]
Thanks Parg and GV-Mike.  I am not going to dig deeper into this, even if I could :).  Unchecking Update Anonymously seems to fix the issue.

Parg, it's nice to know that some things do not change.  Case in point, your remarkably timely responses to users' needs and questions.  Know that it is appreciated.
