### ISSUE TITLE
Exiting biglyBt takes 30 minutes or an hour or never, some process running in the background

### ISSUE THREAD

**Issue by gr88** [BiglySoftware/BiglyBT#355]
Exiting biglyBt takes 30 minutes or an hour or never, some process running in the background

I will touch on several issues, and focus on the main one.

There appears to be a part of biglyBt that is constantly running (endless loop?) and *greatly* slows *some* of biglyBt's functions down.  
The most obvious function is Exit, and "Transfers, Stop All", and some others which become tediously slow.
Many of the biglyBt function are not as slow.  The reason most fuctions remain fast is probably because I have set the heap at 2gb of ram.  I also set the other 2 ram java vm settings to 2gb; 
max direct memory and the other 1.
These setting are not the cause of the problem.  In fact they are why I have been able to run biglyBt (and Vuze before).  
I listed this same problem a couple of months ago.  It went away for awhile.  I am on the beta program.  The problem did not come back immediately after a new beta version.  It was a few days later.
1401B13 was running when I noticed the problem was back. So I don't think the problem was re-introduce by a beta version.  

Here is an article, most of which I don't understand, which may show how to track a memory or thread problem in a java vm.
https://dzone.com/articles/java-memory-and-cpu-monitoring-tools-and-technique
There may be something here to help track down the "process" which is slowing my biglyBt.
Enabling JMX Ports
Using HPROF
JVisualVM

I have disabled all of the plugins.  This did not help.  By the way:  The plugin function is difficult to understand and sometimes doesn't work.  This is a secondary problem not connect to exiting slowly.
In the plugin dialog, there is a button for disable or uninstall selected.  There are check boxes by each plugin.  Does "selection" mean 1 single plugin which is highlighted or all those with a check in the box?

"Close all detail" does not affect my slow exiting.
Secondary problem with "close all detail":  Sometimes this button goes gray even when there are some details to close.  This happened once when I closed all details, everything slowed to a crawl, because 
of the same problem about slow exiting, nad when half of the details had closed, I pressed it again.  This seemed to confuse biglyBt programming greatly.
Secondary problem: On the left sidebar where the torrent name is shown for the Details, there are many X's which should be used to close 1 detail at a time.  
These x's used to be barely accessable and now are not.
This is because of the automatic scroll bar that appears when you are trying to point at the X.  It used to be if you were extremely accurate and slow you might maybe be able to hit the x, around the scrollbar. 
Now the scrollbar covers the x and it is not accesable.  
Noramlly, I liked to keep all torrents showing a "detail" entry on the left side.  When I shut down all "detail" listing, in did not affect my slow exit problem.
By the way, there are other locations which have scrollbars, such as the bottom of most "spreadsheet" areas where the scrollbar interferes with the selection of a file or torrent.

If I turn off my internet connection before closing biglyBt, it seems to make the slow exit problem more pronounced, more time.  I may be wrong on this point.
It used to be that if I could sneak up on biglyBt quickly after it started, and stop or pause all downloads, it would help the exit time.  
This is not so anymore.

I have 650 torrents active at all times.  My average upload speed in about 1 to 2 MB/s (Bytes).

Another secondary problem, the Tor Helper Plugin pops up a window for 1/2 a second if all is running well or for 5 seconds if biglyBt is running slow.  There is no way to make is stop re-occuring.

Starting BiglyBT...
Suitable java version found [java = openjdk 1.8.0_151]
Using swt/swt-x86.jar v4.757

>>> The next line has been a long running problem which may or may not be connected to my slow exit problem.
(java:21808): Gtk-WARNING **: GTK+ module libgail.so cannot be loaded.
GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported.

...

>>>The next line has been another long running problem.  But the warning usually says Critical.
(BiglyBT:21831): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to underallocate SwtFixed's child GtkProgressBar 0x58cb0130. Allocation is 5x4, but minimum required size is 152x4.

...
---
Java 1.8.0_151 (32 bit)
  Oracle Corporation
/usr/lib/jvm/java-8-openjdk-i386/jre

SWT v4757, gtk/3.22.0
Linux v4.7.9-64, i386 (32 bit)
B1.4.0.1_B15/4 az3

24 gig of ram

**Comment by parg** [comment]
The first thing to look at when things are running slowly like this are the thread_1.log and thread_2.log files in the 'logs' directory in the BiglyBT config directory. These contain periodic logs showing the most active thread and the memory usage. Alternatively use the Help menu 'Generate Debug Info' option to create a debug.zip (which should include these files and more) and send to me at parg@users.sf.net.

**Comment by gr88** [comment]
It is amazing that you can answer so quickly and keep up with all of the posts and programming.  I'll look at the logs and possibly send them to you.

**Comment by parg** [comment]
I need to get a life :)

**Comment by gr88** [comment]
Hi, I sent debug.zip by email.

**Comment by gr88** [comment]
I forgot to ask;  Have there been any cases of linux vuze or linux biglyBt being hacked or having a virus?  If so, how can I tell?  The 2 sets of logs I sent will probably hold all answers.

**Comment by parg** [comment]
Not aware of any cases of Vuze or BiglyBT being hacked. Not got any logs yet - which email did you use? parg@users.sf.net works

**Comment by gr88** [comment]
Good Morning !   I sent and email with logs to parg@users.sf.net at about 7am Central Time.

**Comment by parg** [comment]
Thanks! Can you try decreasing the size of the disk cache you have configured in BiglyBT - looks like you have 320MB allocated - just out of interest drop this to something small, 16MB say. Also turn off the cache trace as it generates a lot of logs.

You might also try limiting the max-active downloads to something like 100?

I don't see anything obvious that might be causing slow closedown unfortunately :(

**Comment by tankorsmash** [comment]
@parg Not sure if this is related, and I'll open a new issue if it's not, but my Bigly client is dead slow, like maybe 5 seconds for the UI to react to me changing from 'Downloads' to 'New' at all, then maybe 10-15 seconds for the UI to load in.

My disk cache was 4MB and I bumped it to 16MB in case that was it, just because you never know, but the UI is still real slow. I've got an i7 and a GTX 1080, and Vuze ran just fine before this, so I don't think it's a hardware thing.

I did import my years-old config from Vuze though, maybe I set something wrong there. Is there something I can try to resolve this?

You can sorta see how slow the UI is in this GIF I just made. The delay isn't as bad because I had already loaded the different tabs but it was several times slower on the first load  

https://i.imgur.com/cPFPNVO.gif

**Comment by tankorsmash** [comment]
@parg 1.5.0 seems to have resolved the slowness and now the UI works as it should, thanks!

**Comment by gr88** [comment]
I am now at 2.1.0.1 B16.  Linux.  For many many versions I have been able to (& can still) shut down normally.  Maybe a 5 or 6 second shutdown process. Thanks. ... gr88       

2019-10-22 17:14
