### ISSUE TITLE
Java 9 & Java 10

### ISSUE THREAD

**Issue by hatewesterncivilization** [BiglySoftware/BiglyBT#361]
Hello, I wanna inform currently using Java 9 & 10 not much possible due to in my case there are just lots of broken torrents if I trying working with new Java versions. Maybe Java 10 not truely yet supported.

Java 10 is dumn good and interesting with Parallel GC for G1 collector, I was little testing this thing, and yes, there are some good improvements. Can I address confirmation that you are on the way to support new Java quickly?

Thanks a lot for the BiglyBT, it's just supergreat.

**Comment by parg** [comment]
I am not aware of any issues with Java 9/10 and 'broken torrents' - can you give me an example of such breakage? There is/was a Java 10 bug in the Java runtime (https://bugs.openjdk.java.net/browse/JDK-8196296) that I reported to Oracle and they claim to have fixed but I have yet to test this.

**Comment by hatewesterncivilization** [comment]
Of course, I will provide an screenshot, it is literally some mass error with lot of torrents. While on 1.8 Java all fine right here in couple minutes while I'm put away J9 & 10.

Hope, it's not specific additional problem on my side say with linkage files to torrents while Bigly and Java just fine by itself.

**Comment by TuxPaper** [comment]
I'm closing this due to age.  If you find any specific issues, please file a new bug report. :)
