### ISSUE TITLE
A few references to "Core Azureus Version" in auto updater

### ISSUE THREAD

**Issue by tankorsmash** [BiglySoftware/BiglyBT#362]
https://github.com/BiglySoftware/BiglyBT/blob/482ced77f42c1ed43cc2136baa9bf73f25df0ee9/core/src/com/biglybt/update/CoreUpdateChecker.java#L346

Might be deliberate, but I'd expect it to read "Core Bigly Version", despite its history.

**Comment by parg** [comment]
Indeed, thanks :)
