### ISSUE TITLE
How to switch to classic UI (question)

### ISSUE THREAD

**Issue by WPFilmmaker** [BiglySoftware/BiglyBT#364]
As per title how do I switch to classic UI?I cant find it anywhere in the options.

**Comment by parg** [comment]
Tools->Options->Interface->Start: Display BiglyBT UI Chooser button

**Comment by WPFilmmaker** [comment]
@parg Thank you for your answer however I cannot find"Start: Display BiglyBT UI Chooser button" anywhere, I took a screenshot https://s18.postimg.org/ymm7i0tzd/bigly.png

**Comment by parg** [comment]
'Start' is a sub-view of Interface - you should be able to expand the 'Interface':
![config](https://user-images.githubusercontent.com/395293/36324061-1ec5e4a8-134b-11e8-93d8-b4f00983d9c3.png)
