### ISSUE TITLE
BiglyBT 1.4.0.0 options behave in a weird way (possible bug?) 

### ISSUE THREAD

**Issue by WPFilmmaker** [BiglySoftware/BiglyBT#365]
When I select the options menu in BiglyBT I get a weird behavior which I suspect it could be a bug, but it could also be an intended behavior...

**What do I do:** Open options->change something-> hit save
**What I would expect:** Options closes and I can use the software
**What happens instead:** The "save" button remains selected and nothing happens. I try to hit the X to close the menu and nothing happens, after a few seconds the menu closes. Changes to the settings are saved.

Is it a normal behavior? (Which IMHO is very weird) or a bug?
Thanks a lot.

Lubuntu 16.04.3

BiglyBT Version Number 1.4.0.0

Desktop Environment LXDE

System: Java 1.8.0_151 (64 bit)
  Oracle Corporation
/usr/lib/jvm/java-8-openjdk-amd64/jre
SWT v4757, gtk/3.18.9
Linux v4.4.0-112-generic, amd64 (64 bit)
    B1.4.0.0/4 az3

**Comment by parg** [comment]
hitting 'save' doesn't close the dialog - you have to close it via the 'x' - not sure why it takes so long to close though

**Comment by WPFilmmaker** [comment]
@parg Thank you I found it. It takes about 5 seconds to close the menu from the "X" am I the first to report such thing?

**Comment by parg** [comment]
yes :) can't imagine what is causing the delay to be honest - closes straight away for me
