### ISSUE TITLE
Bigly 14: New d/ls not all showing in Library view

### ISSUE THREAD

**Issue by ExRobotGuy** [BiglySoftware/BiglyBT#368]
Normally in Vuze and now Bigly, when I d/l a file it will be added to my Library with finished files showing up below it.

It has started to add these files in various 'views'. How can I corral them to the view I want?

This appear to be a bug but I know nothing of these type of things!

Thanks all,

ExRobotGuy

Java 1.8.0_152 (64 bit)
  Oracle Corporation
/Applications/ 3RD PARTY APPs/INTERNET/BiglyBT/.install4j/jre.bundle/Contents/Home/jre

SWT v4528, cocoa
Mac OS X v10.13.3, x86_64 (64 bit)
B1.4.0.0/4 az3

**Comment by parg** [comment]
Do you mean the various tags such as 'active'? You can hide these by right-clicking them and selecting show/hide tags.

**Comment by ExRobotGuy** [comment]
No. Not the side-bar. That’s always there. It’s the files, and info about d/ls that I normally get [and want] on the Library view only.

Thanks,

**Comment by parg** [comment]
Hmm, not sure I understand your issue - can you explain in a bit more detail?

**Comment by ExRobotGuy** [comment]
If I could send you screen caps it would help explain it. BUT I have deleted all my d/ls and seedings and quit the app, now. If I may, if it happens again I would appreciate it.

Just so you know; I’m 71 and don’t know the correct terminology, perhaps, to get my problem understood.

Thanks for your offer to help.

Ex

**Comment by gr88** [comment]
I may be way off here, but if there is a word or letter in the search box in the upper right hand corner of the screen, during library view, it will appear some torrents are missing.

**Comment by parg** [comment]
Sounds plausible - if you have focus on the library and type a key then the view is automatically filtered by that key (and subsequent ones) - if this is the case you will see the current filter text in the search box top-right. Hit 'escape' or clear the search box to go back to an unfiltered view.

**Comment by KonoromiHimaries** [comment]
![2019-04-07-](https://user-images.githubusercontent.com/5884000/55686784-c6007b00-5965-11e9-951a-136f892c7632.png)
