### ISSUE TITLE
Biglybt 1.4.0 does not remember that the bottom info bar is minimized

### ISSUE THREAD

**Issue by WPFilmmaker** [BiglySoftware/BiglyBT#369]
**What do I do:** minimize the bottom info bar-> close BiglyBT and restart the system -> open BiglyBt again 
**What I would expect:** The bar is still minimized
**What happens instead:** The bar is not minimized which defeats the reason why I wanted it minimize (make the interface more slim).
Thanks a lot. 

Lubuntu 16.04.3 
BiglyBT Version Number 1.4.0.0 
Desktop Environment LXDE 
System: Java 1.8.0_151 (64 bit) Oracle Corporation /usr/lib/jvm/java-8-openjdk-amd64/jre SWT v4757, gtk/3.18.9 Linux v4.4.0-112-generic, amd64 (64 bit) B1.4.0.0/4 az3

**Comment by parg** [comment]
When you say 'bottom info bar' do you mean the sub-tabs with 'General', 'Sources', 'Peers' etc? 

For me that area respects the minimized/maximized state over a restart.

**Comment by WPFilmmaker** [comment]
@parg Yes thats what I mean. OK seems we have different expectations from the behavior of the software, no problem :)
