### ISSUE TITLE
Help -> Release Notes

### ISSUE THREAD

**Issue by csylvain** [BiglySoftware/BiglyBT#37]
"Welcome Window: Error loading resource: /changelog.txt"

I went to check what the changes were for Beta 05, and got that instead.

**Comment by TuxPaper** [comment]
Release Notes should be there now (at least for v1.0.2.0).  I haven't tested the betas, but the Beta Program sidebar entry probably has a more up to date list of changes than the changelog.txt file will have

**Comment by csylvain** [comment]
it is indeed there. B1.0.2.1_B03 .. mostly I check the Release Notes at the major updates, and yes, I know if I want to see the most recent changes I should check via the Side Bar.
