### ISSUE TITLE
CPU usage spikes while downloading 1 torrent

### ISSUE THREAD

**Issue by WPFilmmaker** [BiglySoftware/BiglyBT#370]
I am testing BiglyBT in a virtual machine with 2gb of ram. I downloaded 1 torrent and noticed that BiglyBT has CPU spikes up to 50% and on average it is  between 25% and 40%. I read at the least two other tickets about memory usage, and I understood that java is not the lightest but I was wondering whether such spikes of cpu were normal or there could be room for improvements.
Thanks

Here you can see a screenshot (torrent is a ubuntu iso): https://s18.postimg.org/h2qev5sah/biglymemory.png

Lubuntu 16.04.3
BiglyBT Version Number 1.4.0.0
Desktop Environment LXDE
System: Java 1.8.0_151 (64 bit) Oracle Corporation /usr/lib/jvm/java-8-openjdk-amd64/jre SWT v4757, gtk/3.18.9 Linux v4.4.0-112-generic, amd64 (64 bit) B1.4.0.0/4 az3

**Comment by parg** [comment]
How 'powerful' is the VM - what is the host OS CPU usage? I don't see anything significant when running BiglyBT natively on my fairly old Windows 7 Machine.

**Comment by WPFilmmaker** [comment]
I tried adding another torrent and the situation did not get worse but did not improve ether. Same behavior. The impact of VM on my system is negligible, nothing strange. VM has 2048mb of memory, here is a screenshot of the stats: https://s18.postimg.org/6jqvp2grd/bigly2.png
