### ISSUE TITLE
"Error: Failed - Bad client (BiglyBT 1.4.0.0). Read the FAQ for a list of available clients."

### ISSUE THREAD

**Issue by Atrion** [BiglySoftware/BiglyBT#372]
When trying to use torrents from a private tracker site they all do not download and give this error "Error: Failed - Bad client (BiglyBT 1.4.0.0). Read the FAQ for a list of available clients."

I'm on a Windows 8.1 pc, Recently switched from vuze (These torrent work in it).

**Comment by parg** [comment]
Tools->Options->Plugins->Client Identification ?

**Comment by Atrion** [comment]
Changing That option did not have any effect.

**Comment by CalTrask** [comment]
Hello,

I am having the same issue as Atrion: Torrents from private trackers refuse to download, and give the same error as listed. If I stop the download the status reads "Scrape Disabled."

I have tried changing the value at Tools->Options->Plugins->Client Identification as suggested with zero difference/effect. Any other ideas?

Thanks :)
