### ISSUE TITLE
Some suggestions (Vote problem, Portable, NewTrackon service integration)

### ISSUE THREAD

**Issue by Corsten56** [BiglySoftware/BiglyBT#374]
Hello.

Thanks for software. I will follow the development process.
Some questions:
1) I have a problem with voting on https://vote.biglybt.com/ - can't vote fore something.
Github Authorization is ok, but next step when trying to vote - I'm unauthorized. And so on.
2) There will be portable version of BiglyBT for Windows? Most needed feature I think.
3) My suggestion - integration of this service - https://newtrackon.com/list
Snatching and adding trackers from this list to public downloads, if it possible. 

Best regards.

**Comment by parg** [comment]
Regarding (2), the instruction for a portable version of Vuze on Windows (https://wiki.vuze.com/w/Portable_Vuze) should work for BiglyBT with some changes. For example, the start class is now com.biglybt.ui.Main, Azureus2.jar is BiglyBT.jar etc. The system properties (-Dazureus.config.path etc) are the same as for Vuze

**Comment by parg** [comment]
Regarding (3) Not sure of the privacy implications of automating this. A tracker knows which IP addresses are downloading which torrents. Adding unknown trackers from this service might not appeal to everyone.

**Comment by Corsten56** [comment]
Thanks for fast reply.
About (3) I mean option disabled by default or something like plugin.

**Comment by parg** [comment]
I'll take a look into (3)

**Comment by parg** [comment]
Beta version B21 has a new option when defining a 'tracker template'  - see https://github.com/BiglySoftware/BiglyBT/wiki/Tags#Tracker_Templates

You can add a 'list' as an entry via the tracker template editor - for example https://newtrackon.com/api/stable or a file (e.g. file:///C:/temp/tl.txt)

When this template is applied the list will be expanded. You can manually apply a template or automate it via Tags. For example, to apply a list to all public torrents simply create a Tag with a constraint of '!isPrivate()' and set its 'tracker template' property to apply the required template.

**Comment by smaragdus** [comment]
@parg 

You may consider an easier way to start BiglyBT in portable mode:

- portable mode installation option;
- command-line argument (for example 'BiglyBT.exe -portable);
- portable flag in program folder triggers portable mode;
- specific sub-folder inside program folder (for example - Data) triggers portable mode;

Regards

**Comment by TuxPaper** [comment]
vote.biglybt.com should be working now.
Closing because there's multiple issues in one issue.  If one of your items is still an problem, please file a separate issue for it.
