### ISSUE TITLE
DLP features wanted

### ISSUE THREAD

**Issue by yexinglanghun** [BiglySoftware/BiglyBT#376]
some client like XL0012 need a powerful plugin to block it. And this is the leecher only from PC. some IDC peers will use ut3.0.0.0 or libtorrent/1.6.0.0. It will keep 0% forever. That libtorrent peer even still downloading when I block it by Stuffer plugin. untill I block it IP.

**Comment by TuxPaper** [comment]
Notes:
XL00012 refers to Xunlei torrent client
DLP refers to Dynamic Leecher Protection. "DLP was originally developed by Xman, the developer of Xtreme, one of eMule 's mods."
