### ISSUE TITLE
Internet access gets cut off while BiglyBT is running. 

### ISSUE THREAD

**Issue by gamingnista** [BiglySoftware/BiglyBT#379]
Everytime I run BiglyBT my internet access gets cut off and I have to restart my system. It is not automatic, it can take 1-5 hours to do this.

**Comment by parg** [comment]
sound like your router sucks...

**Comment by gamingnista** [comment]
I think something is loose with the wiring in my walls. If I or my cats touch the plugs the electricity flickers. I just wanted to make sure it wasn't a software issue, Thanks.

**Comment by parg** [comment]
Also check out https://www.google.co.uk/search?q="network+connection+dying"

**Comment by gamingnista** [comment]
Lowering the max upload rate worked, Thanks
