### ISSUE TITLE
can't sign in for beta in fedora 26

### ISSUE THREAD

**Issue by legacychimera247** [BiglySoftware/BiglyBT#38]
everytime i try to join the beta channel the update downloads but it fails to install...this should probably has something in common with the fact i was never able to restart vuze in fedora (well at least i guess)

**Comment by legacychimera247** [comment]
an update to this one...seems that's biglybt cannot write in the default install position since it's not root...opening as a root solved the issue...

**Comment by TuxPaper** [comment]
This is on my list to look at.  I know the plugin updates will try to sudo (well, specificly `pkexec`, `gksudo`, `kdesudo`, or `sudo`) if they don't have write access, but I haven't tried it with a beta update.  Perhaps it's using a different way to install the beta (probably!)
