### ISSUE TITLE
Cannot change command in command-runner

### ISSUE THREAD

**Issue by kwloafman** [BiglySoftware/BiglyBT#380]
Once entered, I cannot change a command.  The dialog pops up, but there is no command entry space like the initial one.  See attached.  Thanks!

Java 1.8.0_161 (64 bit)
  Oracle Corporation
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home

SWT v4528, cocoa
Mac OS X v10.13.3, x86_64 (64 bit)
B1.4.0.1_B21/4 az3

![image](https://user-images.githubusercontent.com/158032/36666823-7374f1d4-1ab1-11e8-895a-48e4c2c1bc3d.png)

**Comment by parg** [comment]
Thanks, fixed in next beta of the core - B22 when built in the near future (it was a BiglyBT bug causing the combo box not to be displayed, not a plugin one)
