### ISSUE TITLE
Auto-Shutdown options in tray menu

### ISSUE THREAD

**Issue by Ilithy** [BiglySoftware/BiglyBT#382]
Primary thanks for the Software, is the 
most rich features Bittorrent client.

It's possible to add Auto-Shutdown 
option on BiglyBT icon in system tray menu?
I think this makes their accessibilities easier, thanks.

Ilithy

**Comment by parg** [comment]
One way of getting to options quickly is to assign a control key to the config panel in question. For example, you can assign CTRL+s to the 'Startup & Shutdown' section by right-clicking in the header area:

![image](https://user-images.githubusercontent.com/395293/36677502-34cdeae4-1b06-11e8-9d80-b12d286ffa12.png)

Once done you can get to that panel by hitting CTRL+, (to show options) followed by CTRL+s
