### ISSUE TITLE
Please add download/upload speed viewer on the dock icon (macOS)

### ISSUE THREAD

**Issue by Lnds500** [BiglySoftware/BiglyBT#389]
This is the only reason I still haven't left Vuze. I have a plugin installed that displays your download/upload speed. It's incredibly useful for knowing how fast your download goes, if it's complete, how fast you are seeding etc etc. Please add something similar.

**Comment by parg** [comment]
Which plugin?

**Comment by Lnds500** [comment]
This is the one. 

https://darkdust.net/index.php/writings/vuzemacdockplugin

**Comment by parg** [comment]
Have you asked the owner if they are willing to port it to BiglyBT? All they would need to do is change some package imports. I could take a look at it myself if they're not interested.

**Comment by parg** [comment]
Actually I'll email them myself

**Comment by DarkDust** [comment]
Hi folks, I've done a quick-and-dirty port of my Mac dock plugin for BiglyBT. But boy, that thing is _old_ and you get deprecation warnings for APIs that have been deprecated back in 10.9… the text rendering should be done using CoreText instead.

Anyway, the ready-to-use JAR can be downloaded here: https://darkdust.net/files/BiglyBTMacDockPlugin.jar

The source is here: https://darkdust.net/files/BiglyBTMacDockPlugin.zip

To compile the plugin, you need to put a `GitHub_BiglyBT.jar` in the `lib` folder.

**Comment by Lnds500** [comment]
Thanks. I didn't think of contacting him because I thought it would be more beneficial for everyone if this feature came baked into the application, without the need for an additional plugin.

**Comment by Lnds500** [comment]
Thanks a lot DarkDust. Time to move over to BiglyBT I guess :D

**Comment by parg** [comment]
BiglyBT does have some native notification support that is unpinned by Java enhancements (java.awt.TrayIcon etc).

**Comment by Lnds500** [comment]
DarkDust you are amazing! Works as expected :D Thanks a lot!!

**Comment by jamesdeluk** [comment]
Looks like this no longer works (unsurprising given the age!) Is there a new way to implement this?
