### ISSUE TITLE
"Add Category" box disappearing

### ISSUE THREAD

**Issue by TemporalNihon** [BiglySoftware/BiglyBT#39]
When I right-click on a torrent, and move to "Organize tab > Assign Category > Add Category..." the box pops up and disappears again in less than a second. I can assign torrents to existing categories through the right-click menu just fine.

I'm still able to create new categories by right-clicking My Torrents in the side bar. The box pops up and and works properly.

OS: Windows 10, Version 1703, Build 15063.540
BiglyBT Version 1.0.0.0

**Comment by TuxPaper** [comment]
This should be fixed in 1.0.2.0
