### ISSUE TITLE
BiglyBT System Tray icon

### ISSUE THREAD

**Issue by JoeConti** [BiglySoftware/BiglyBT#390]
I am using BiglyBT v1.4.0.0 using Windows 10 - brand new install. Had the same issue with the old install of windows 10.

My BiglyBT System Tray icon vanishes on startup. Not always. Since I start my BiglyBT minimized, I have to locate my BiglyBT icon in the start menu and click that to open BiglyBT.

Help ?

**Comment by parg** [comment]
If you right-click on the Task Bar, select 'Task Bar Settings' and then scroll down to 'select which icons appear on the taskbar' is BiglyBT listed there?

**Comment by JoeConti** [comment]
Its set to show ALL icons .. sometimes i appears and other times, like now, it doesn't.

**Comment by parg** [comment]
Just checking that BiglyBT is definitely still running when the icon vanishes and it hasn't crashed? I've never seen the icon disappear myself unless BiglyBT crashed (or you explicitly disable the tray icon in the options and then it is obviously permanently missing)

**Comment by JoeConti** [comment]
It's running for sure - because I use the browser interface to monitor it sometimes and it will be up and running!
