### ISSUE TITLE
Fixing the 'Actions' column in Subscriptions 

### ISSUE THREAD

**Issue by Xemnarth** [BiglySoftware/BiglyBT#391]
Fix the 'Details' option in the 'Actions' column under Subscriptions to view the page from which the torrent came from. Currently, this option links to the .torrent file which is a duplicate function of 'Download' option in the same column.

**Comment by parg** [comment]
Does the subscription actually have a link to the details available? If it is based on an RSS feed then look at the feed content and check to see if it is present. If you want me to check then export the subscription (right-click menu option) send it to parg@users.sourceforge.net

**Comment by Xemnarth** [comment]
Yes, the original RSS feed does include links to pages of the .torrent files.

**Comment by parg** [comment]
Can you either send me the subscription or RSS feed details or tell me where the info is present in the feed?

**Comment by Xemnarth** [comment]
Just sent you the export file. Note that pages syntax ends with /view/ID#

**Comment by parg** [comment]
Thanks - fixed in Beta 24 (See the Help menu to join the beta program)
