### ISSUE TITLE
New mouse click action

### ISSUE THREAD

**Issue by Xemnarth** [BiglySoftware/BiglyBT#395]
Left clicking an already highlighted/selected torrent from the transfer list to deselect it so its details won't show in the sub-tabs. Can we implement this behavior or will it interfere with something else?

**Comment by parg** [comment]
You can do this already with ctrl+click

**Comment by Xemnarth** [comment]
Thanks for the tip, however, doing so only hides the details of the viewed/selected sub-tab. Have you noticed?

**Comment by parg** [comment]
no :) I'll see if that can be fixed

**Comment by parg** [comment]
fixed in beta B25
