### ISSUE TITLE
Delete .torrent bug?

### ISSUE THREAD

**Issue by Xemnarth** [BiglySoftware/BiglyBT#398]
Selecting the option to 'Delete original .torrent files after download added' doesn't seem to work. 

Update: choosing to 'Save .torrent files' seems to override this option.

**Comment by parg** [comment]
Seems to be behaving for me, not sure why you are seeing different behaviour

**Comment by Xemnarth** [comment]
Do you have 'Save .torrent files' selected? If yes, is it the default directory?

**Comment by Xemnarth** [comment]
it only works without having 'Save .torrent files' selected but then it keeps asking where to save .torrent files which is annoying

**Comment by parg** [comment]
I assume you're on version 1.4, not an earlier one?
As far as I can see the only time it won't delete the torrent (when you have 'save torrents' disabled) is if the torrent is already in the 'active' folder.

**Comment by Xemnarth** [comment]
These options are kinda confusing and not clear enough. I understand 2 things for sure:
- When you cancel the torrent add dialog, the torrent file will not be stored (good), but
- when you add the torrent to the transfer list, it will be stored in your defined directory in 'Save torrents' option regardless of choosing to delete or keep the torrent file after it's added.

**Comment by parg** [comment]
Ah, that makes things a bit clearer - you mean that when 'save torrents' is enabled and you also enable 'delete after add' then the torrent file remains in the 'save torrents' folder? That is how it is supposed to work. Say you have a torrent file in

C:\Whatever\fred.torrent

and you have 'save torrents' enabled. When added to BiglyBT the torrent is copied into the 'save' folder and the ORIGINAL torrent in C:\Whatever is not deleted.

When you enable 'delete on add' then the ORIGINAL torrent in C:\Whatever WILL be deleted after adding (but not the one in the save folder).

BiglyBT needs a long-term persistent torrent to run a download. It uses either the original one OR the one copied into the 'save' folder.

Confusing I guess.

**Comment by Xemnarth** [comment]
Yes. 
Oh, I wasn't sure about the 'original' part and thought my .torrent files go straight into the 'save' folder. Perhaps there is a temp (original) copy which gets deleted.
