### ISSUE TITLE
Option to copy/export magnet URI?

### ISSUE THREAD

**Issue by Xemnarth** [BiglySoftware/BiglyBT#399]
I couldn't find this option so I thought it would be nice to have.

**Comment by parg** [comment]
Right-click on the Download and select the 'Social' tab from the menu, then 'Copy Magnet URI to Clipboard'

**Comment by Xemnarth** [comment]
I don't know why I don't have this option. Is it shown by default?

**Comment by parg** [comment]
ahhhhh, you need to switch to the 'detailed' torrents view (see the 'view as an advanced list' toolbar icon)

**Comment by parg** [comment]
I'll add it to the basic view

**Comment by Xemnarth** [comment]
Thanks a lot
