### ISSUE TITLE
ram usage

### ISSUE THREAD

**Issue by legacychimera247** [BiglySoftware/BiglyBT#40]
i've always been an azureus users from the time it still had that wonderful (and greatly missed) black interface, but unfortunately it always had a too high ram usage. switched to linux some times ago and then switched to transmission (it was more i was not liking the direction azureus was taking) and now that BiglyBT is created i am thinking about coming back, but my main concern is still the higher usage of ram. For example BiglyBT uses  (at least) 400 mb of ram with only swarm discoveries installed and 1 torrent running, while TransmissionBT uses less than 100 mb with 6 torrent running. Now, i know bigly it's a full featured client while transmission is designed to be lightweight but still 400 mb sounds too much to me for a torrent client (especially when you have only 3 gb of ram). Some hope for the future?

**Comment by hatewesterncivilization** [comment]
I do confirm this one, Azureus does fine .vmoptions thing, while Bigly doesn't, ram usage goes constantly over the setting specified in .vmoptions. Can be that fixed, so, I start use BuglyBT in constant way?

**Comment by TuxPaper** [comment]
hmm, @hatewesterncivilization , .vmoptions should still work.  It's BiglyBT.exe.vmoptions in the windows app dir (which should already be there with at least one entry in it).  There's also %appdata%\BiglyBT\java.vmoptions, which is the preferred one to edit (or create).

@legacychimera247 You can adjust the max amount of memory we use in `Tools->Options->Startup and Shutdown`, in the "Java Options" section.  The "Max Heap" is probably the most important value there.  But, of course, if you set it too low and BiglyBT needs more memory, there will be problems.  

So, if you aren't using the UPnP Media Server, you can disable by going to `Tools->Options->Plugins` and unchecking the `azupnpav` plugin (and restarting).  That plugin can sometimes take up a lot of memory.

Also, if you never have problems getting .torrent files or seeds, you may not need the mlDHT plugin.  That one can be disabled or uninstalled, and is primarily used to get torrents and peers if we can't find any on the trackers or the Azureus DHT.

**Comment by legacychimera247** [comment]
thanks for your reply...anyway i set all the values to use only 100 mb of ram but biglybt is taking 200 mb...is it normal or there is something wrong?

**Comment by TuxPaper** [comment]
@legacychimera247 Yeah, it's pretty normal for Java apps.  Java has several different memory pools, so all the "max" values add up.

fwiw, after a good 10 - 15 minutes or running, we do remove a bunch of stuff from memory (like the unused text strings).  It's not a huge memory gain, but it's not insignificant either.  It's usually washed out by the fact that by then, DHT is fully running and peers are connecting, etc.

**Comment by legacychimera247** [comment]
thanks, well i will evaluate the situation, i don't know for biglybt yet but unfortunately ram usage was one of the reasons i switched from azureus to transmission...and altough transmission is great, i've used azureus for 10+ years so it would be really nice to be back :)

**Comment by hatewesterncivilization** [comment]
@TuxPaper I'm not sure why client after some short time completely deadlocking. Yesterday I leaving PC for night and it didn't back at morning. Azureus fine with the same .vmoptions, also I was disabled all unnecessary plugins. I'm very waiting fixes for that.

Here is .vmoptions content, just same as for Azureus

> -Dazureus.config.path=J:\BiglyBT\\
-server
#-XgcPrio:deterministic 
#-XpauseTarget=30
-d32
-Djava.awt.headless=true
-XX:+UnlockExperimentalVMOptions
-XX:+UnlockDiagnosticVMOptions
-Xquickstart
-Xnoclassgc
-Xverify:all
-XX:+TieredCompilation
-XX:CompileThreshold=1000
-XX:-DontCompileHugeMethods 
#-XX:CICompilerCount=1
-XX:ReservedCodeCacheSize=256m
#-XX:MaxInlineSize=1024  
#-XX:FreqInlineSize=1024 
-XX:+AggressiveOpts
-XX:+AlwaysPreTouch
-XX:UseSSE=4
#-XX:+UseLargePages
#-XX:LargePageSizeInBytes=2m
-XX:-BytecodeVerificationLocal 
-XX:-BytecodeVerificationRemote 
-XX:+PerfDisableSharedMem
-XX:SoftRefLRUPolicyMSPerMB=1
#-Xss2m
-Xms1650m
-Xmx1650m
-Xmn50m
-XX:MaxDirectMemorySize=500m
#-XX:+UseThreadPriorities
#-XX:ThreadPriorityPolicy=1
-XX:+UseCompressedOops
#-XX:+DoEscapeAnalysis
-XX:+UseFastAccessorMethods
-XX:+UseTLAB
-XX:+DisableExplicitGC
-XX:+UseParNewGC
#-XX:+CMSParallelRemarkEnabled
-XX:+UseConcMarkSweepGC 
#-XX:+CMSScavengeBeforeRemark
#-XX:+CMSConcurrentMTEnabled
-XX:ParallelGCThreads=4 
-XX:+ExplicitGCInvokesConcurrent 
-XX:NewRatio=2
-XX:GCTimeRatio=2 
-XX:MaxGCPauseMillis=100
-XX:PermSize=128m
-XX:MaxPermSize=128m
-XX:NewSize=128m
-XX:MaxNewSize=128m
-XX:+CMSClassUnloadingEnabled
-XX:SurvivorRatio=256
-XX:TargetSurvivorRatio=90
-XX:+CMSIncrementalMode 
-XX:+CMSIncrementalPacing 
-XX:CMSIncrementalDutyCycleMin=0 
-XX:CMSIncrementalDutyCycle=10 
-XX:MaxTenuringThreshold=0 
-XX:CMSInitiatingOccupancyFraction=60
-XX:+UseAdaptiveGCBoundary
-XX:-UseGCOverheadLimit

**Comment by hatewesterncivilization** [comment]
@legacychimera247 You should use -Xms and-Xmx settings in .vmoptions file like the above by me, if you don't know about that. Set both memory amount (made they a same) depending to free system memory, just leave for the system/OS comfortable amount.

You don't need place java.vmoptions file in C:\Users\<username>\AppData\Roaming\BiglyBT, if you are on Windows, java.vmoptions content in my case just a "include-options J:\BiglyBT\BiglyBT.exe.vmoptions" and both files, java.vmoptions & BiglyBT.exe.vmoptions file I've placed at the custom installation dir. While BiglyBT.exe.vmoptions file content like above.

**Comment by legacychimera247** [comment]
no i'm on linux, thanks for your tip anyway...i might give it a try but it would be nice anyway to see some ram improvements...
