### ISSUE TITLE
Batch Retargetting

### ISSUE THREAD

**Issue by mighelch** [BiglySoftware/BiglyBT#402]
Could you add dialog where you can replace paths like this.
...\A\01.mp3 <-- ...\A\CD1\01.mp3
...\A\02.mp3 <-- ...\A\CD1\01.mp3
....
...\A\09.mp3 <-- ...\A\CD2\09.mp3
...\A\10.mp3 <-- ...\A\CD2\10.mp3
instead of retargeting one by one, just replace one list of paths with another.
Useful for crosseeding and keep data organized.

**Comment by parg** [comment]
Beta B26 has a right-click batch option - please test and report if it is working!

**Comment by mighelch** [comment]
It works fine.
It would be nice to isolate file index. So one can paste paths directly into dialog.

**Comment by parg** [comment]
Maybe you can copy/paste the list into a spreadsheet, mess around with it there and then paste it back.
