### ISSUE TITLE
Open Location does not  point to file

### ISSUE THREAD

**Issue by prometheus860** [BiglySoftware/BiglyBT#403]
In the context menu, under content, is a button to "Open Containing Folder." When this is selected, an explorer window opens that points to the root folder.  This is fine when a torrent has its own subfolder and there are not many files to choose from; when it does not, then it becomes extremely cumbersome to find the actual file. 

Other torrent applications have the same feature, but it will actually point to the file in question.
This seems like a simple change that would greatly improve the experience of managing torrents.

i'm on windows 7 64 bit
Bigly 1.4.0.0

besides the magnet link delay and the issue above, this is a superb application

thank  you

**Comment by parg** [comment]
There's an option under Tools->Options->Interface->Display called

Use "Open Containing Folder" instead of "Show In Explorer" in torrent menus

Is that checked?

**Comment by prometheus860** [comment]
Hi, 
thanks for the response. Yes that is checked. Changed it, and now no problem. 

My confusion stemmed from the use of the verbs in "**open** containing folder" which sounds more specific, than "**show** in explorer". I think it would be clearer if the verbs were switched/changed. Something like: "open folder in Explorer" and "Show containing Folder."

Anyhow, thanks for the help!
