### ISSUE TITLE
Client doesn't scrape

### ISSUE THREAD

**Issue by Xemnarth** [BiglySoftware/BiglyBT#405]
I've tested with many trackers of stopped torrents and I get "Scrape Disabled" message next to every tracker although I set my options to enable scrapping. Tested scrapping with uTorrent by setting 'bt.scrape_stopped' to true and it worked.

**Comment by parg** [comment]
What options have you enabled/disabled regarding scraping?

**Comment by Xemnarth** [comment]
Options>Tracker>Scrape>Enable scrapping & scrape torrents that aren't running but still doesn't scrape.

**Comment by parg** [comment]
can you send me one of these torrents to test with? parg@users.sourceforge.net - thanks!

**Comment by parg** [comment]
Has the torrent ever been started or did you add it in a 'stopped' state?

**Comment by parg** [comment]
(the reason I ask is that it is by design that such an 'add stopped' torrent doesn't scrape - it is to allow a user to adjust the enabled networks (public/I2P) before any network activity takes place)
