### ISSUE TITLE
Search for torrents ability

### ISSUE THREAD

**Issue by psychic717** [BiglySoftware/BiglyBT#407]
Hello.
I've been using Vuze since I remember downloading torrents and I always loved using it. 
Now that BiglyBT is fully open source and add free it's even better than before.

This probably isn't the place, but I would like to know if it's now possible to add a search funcionality that actually works and finds torrents from different sites/trackers. 
qbittorrent does this pretty well with the python addon and having the plugins page with different sites we can add to the search engine; I've been using it to search for torrents and then copy the magnet over to BiglyBT.

Isn't something like this possible for BiglyBT now that it's open source? Or at least making a page with updated and working search templates for people to add if they can not be included with the installer?
I feel the lack of torrent search using popular trackers is the biggest drawback from using BiglyBT compared to other clients.

Thanks for all your hard work on BiglyBT!

**Comment by parg** [comment]
Have you tried swarm search? Right-click on 'Swarm Discoveries' in the sidebar and select 'Discover by Search'. There is a 'search more' option under the 'filter options'  button in the results view - you can also set up a subscription for the search that will periodically look for more matches based on the subscription update frequency (set it to something low if needed) - right-click on the results entry in the sidebar to do this.

**Comment by psychic717** [comment]
I never used Swarm Discoveries before, but now I see it's actually useful.
Doesn't exactly find as many results as I'm used to, sometimes the same search gives less results after a few minutes and most of the time the "search more" is needed to find what we want. But it works better than I expected.

I still think having working search templates for the popular sites would be better, but I guess most people will find this enough.

**Comment by kwloafman** [comment]
The mention of Python plugins would be great for search!  Or maybe even
just a program call with a clear interface would be better and more
flexible.  I'd suggest these as totally separate projects supported by
users, with only the interface supported by BiglyBT.  A link on the BT
website and maybe a disclaimer would be sufficient.

**Comment by psychic717** [comment]
Yeah, that would be perfect. I don't think qbittorrent guys would mind either.

**Comment by Havokdan** [comment]
There are some templates on this site: http://torfeat.logicize.co

**Comment by psychic717** [comment]
Thanks but both Zooqle and Torrentz aren't working and 1337x template doesn't have a download button, only the list of torrent. The only one working I saw was TPB, which is nice.

**Comment by kwloafman** [comment]
Plus, the torfeat searches go through logicize.co, probably to keep from
having to publish a new search template every time something changes.
However, it is a point of possible privacy loss depending on how much you
trust logicize.co.  Interesting approach.

**Comment by Havokdan** [comment]
Actually I'm using [Jackett](https://github.com/Jackett/Jackett)
