### ISSUE TITLE
Option to auto-mark completed torrents as watched

### ISSUE THREAD

**Issue by Xemnarth** [BiglySoftware/BiglyBT#408]

**Comment by parg** [comment]
If you aren't interested in the 'watched' status then just remove the column from the Library view

**Comment by Xemnarth** [comment]
not possible to remove

**Comment by parg** [comment]
You can't right-click on the column header and deselect the check mark next to the 'New' column?

**Comment by Xemnarth** [comment]
there is no check mark or 'x' next to the New column

**Comment by parg** [comment]
Ah, I think you're talking about the 'New' entry in the sidebar that shows 'unwatched' downloads, as opposed to the 'New' column.
I'll add an option under Tools->Options->Interface->Display: Sidebar to enable/disable the view entirely

**Comment by Xemnarth** [comment]
That's correct!

**Comment by Xemnarth** [comment]
Can we have an option to actually mark complete transfers as watched, not just hide the view?

**Comment by parg** [comment]
what would  be the point? Just hide the view and remove the column
