### ISSUE TITLE
Option to delete .torrent files from defined save directory after download added 

### ISSUE THREAD

**Issue by Xemnarth** [BiglySoftware/BiglyBT#409]

**Comment by Xemnarth** [comment]
This would keep me from manually deleting torrents from C:\Users\xemna\AppData\Roaming\BiglyBT\torrents since they're not needed anyway

**Comment by parg** [comment]
Just select the option to remove the torrent file when removing the download from BiglyBT.

**Comment by Xemnarth** [comment]
yes that works only outside the torrent file save folder, I want an option to also apply the rule to saved torrent files in \AppData\Roaming\BiglyBT\torrents

**Comment by parg** [comment]
odd - works for me

**Comment by Xemnarth** [comment]
oh did you fix that in the latest beta?

**Comment by Xemnarth** [comment]
yes, it's working now!

**Comment by Xemnarth** [comment]
Actually it only works after you cancel the torrent add dialog. The downloaded torrent file will stay in the folder after it's added to the transfer list (which shouldn't as it's not needed anyway).

**Comment by parg** [comment]
But is is needed - BiglyBT keeps a copy of the torrent around (either the original or one copied into the /torrents folder) until the download is removed from the Library (and only then is it deleted if you select the 'delete .torrent file' option. Possibly this is not how you would like things to work but that's the way it does.

**Comment by Xemnarth** [comment]
but you can still export the torrent from the transfer list inside BiglyBT without even having the original .torrent file

**Comment by parg** [comment]
If you enable the 'Torrent Location' column in the Library this will show where BiglyBT is storing the torrent file

**Comment by Xemnarth** [comment]
yeah but even if the .torrent file doesn't exist anymore inside any folder, the client will still indicate to its original location. anyway, this isn't exactly what we should be talking about.

**Comment by Xemnarth** [comment]
The new option should read something like "Also delete from Save Directory" next to the "Delete original .torrents files after download added" option.

**Comment by parg** [comment]
Just a quick question, why do you have the 'save torrent files' option enabled anyway?

**Comment by Xemnarth** [comment]
Good question, because I don't want to keep selecting where to save .torrent files.

**Comment by parg** [comment]
Please check the latest beta

**Comment by Xemnarth** [comment]
Can you extend this option to .torrent files downloaded for jobs already existing? Currently, it doesn't delete those. Thanks as always.

**Comment by parg** [comment]
Can't you just go to the .../torrents folder and manually delete everything?

**Comment by Xemnarth** [comment]
I can but I need to always remember to do it to avoid unnecessary files in the client backup, and knowing how many torrents I'm going to add, it can get pretty big...

**Comment by parg** [comment]
I must be missing something - once you've enabled the 'delete saved .torrent files' option all newly added torrents won't end up in the save folder - so where are these new ones coming from that you need to manually delete?

**Comment by Xemnarth** [comment]
that's correct, everything won't be kept expect when you try to add a torrent which is already in your client, you can reproduce this easily

**Comment by parg** [comment]
When I add a torrent that is already in BiglyBT then I get an info popup that says the torrent is already in the client and no .torrent file in the save folder...
