### ISSUE TITLE
return the last black interface back

### ISSUE THREAD

**Issue by legacychimera247** [BiglySoftware/BiglyBT#41]
if there's something i greatly miss from the old azureus is it's black interface, it was clean and simple and it was working very well. I've asked all over the forum at vuze and on the voting page but none ever gave me a reply about that...so now i'm asking you to give us that interface back...

i already know the answer is no, but hey trying will not hurt :)

**Comment by Ilithy** [comment]
Hi;
If the "Classic" theme is conserved, it's a very good enhancement and most sweet for eyes.

**Comment by jeffward01** [comment]
IMO - leave this to third-party developers as what [qBittorrent](https://github.com/qbittorrent/qBittorrent) has done.

Leave these visual enhancements to third-party developers, and keep the maintainers focused on writing code for better features. 

Also, we can already do this:
![BiglyDarkMode](https://user-images.githubusercontent.com/12589359/164048224-4f547b53-0e97-4f6e-914d-77e0d3a3cf45.png)


----

Note: I just saw this is a very old feature, whoops, 3 years late, I see its already done
