### ISSUE TITLE
Option to use a 'Tree View' in the 'Files' sub-tab

### ISSUE THREAD

**Issue by Xemnarth** [BiglySoftware/BiglyBT#411]
Similar to the one accessed from the torrent options/add dialog.

**Comment by Havokdan** [comment]
I think it's a good idea.

**Comment by parg** [comment]
Big job that one

**Comment by Xemnarth** [comment]
Doesn't seem to work as intended

**Comment by parg** [comment]
How about some useful feedback?

**Comment by Xemnarth** [comment]
Not sure how to explain this. Pressing the Tree View dial basically just moves you to the parent directory, unlike the view in the Torrent Addition Dialog or qBittorrent.

**Comment by Xemnarth** [comment]
Where is the beta chat channel?

**Comment by Xemnarth** [comment]
Please can you just make it look like the Content sub-tab in qBittorrent?

**Comment by parg** [comment]
It is what it is
