### ISSUE TITLE
The Sources tab is always blank 

### ISSUE THREAD

**Issue by MrDemocracy** [BiglySoftware/BiglyBT#412]
* OS and version Windows 10
* BiglyBT Version Number B1.4.0.1_B27/4 az3
* For *nix: Desktop Environment

The Sources tab is always empty. I think this started after I clicked the reset columns option. 
<img width="491" src="https://user-images.githubusercontent.com/23060864/37452849-15f5e8be-2836-11e8-859e-f5a9cc72555a.png">
I can still interact with the trackers, but I can't see which of them I'm clicking.

**Comment by Havokdan** [comment]
There are times that I minimize the BiglyBT and when I restore, the tab is empty, even if there is a torrent highlighted, I need to click on some torrent to appear normally. It would be for you too?

**Comment by MrDemocracy** [comment]
That doesn't fix it for me.

**Comment by parg** [comment]
Whoa! OK, I'll look into that. In the meantime you can re-instate the columns by opening the 'Column Setup' dialog (right-click in the table header area) and add them back.

**Comment by MrDemocracy** [comment]
Ah, thanks now I see the columns again. But they all disappear when I click 'reset columns', and I guess that's not the intended behavior of the reset columns option?

**Comment by parg** [comment]
Fixed in next beta!
