### ISSUE TITLE
BiglyBT for Sailfish OS

### ISSUE THREAD

**Issue by legacychimera247** [BiglySoftware/BiglyBT#42]
so, i have a wonderful Jolla Phone with Sailfish OS as a system...you may not know Jolla but it was born from the ashes of nokia and resurrected the wonderful Meego project...

now, i don't usually download torrents with my phone but when in need to, it would be wonderful to have BiglyBT as torrent app, and it will be even a nice way to make you know to the public more, since Sailfish users will surely check your desktop counterpart, and you will be the first real torrent app we'll have since now my solution is a transmission daemon with the web gui...

don't know if it's doable but it might worth a look :)

**Comment by csylvain** [comment]
no Java --> no go.
