### ISSUE TITLE
Apply Intuitive/Numerical Sorting Mechanism

### ISSUE THREAD

**Issue by Xemnarth** [BiglySoftware/BiglyBT#428]
I noticed that BiglyBT uses the classical/literal method when sorting the Save Path column (in torrent transfer lists) and Tag Name column (in Tags Overview). Can you perhaps apply intuitive/numerical sorting for all columns? Thank you!

Reference example:
![image](https://user-images.githubusercontent.com/6406869/38244639-633997c2-374c-11e8-9c4c-e5fddc6166c2.png)

**Comment by parg** [comment]
Check the next beta - there's an option under Tools->Options->Interface->Tables

default is current behaviour in case existing users love it

**Comment by ldgbc** [comment]
I think it also call "Logical" sorting. 

Thanks!
