### ISSUE TITLE
How do I submit a translation update?

### ISSUE THREAD

**Issue by Havokdan** [BiglySoftware/BiglyBT#43]
How do I submit a translation update?

Here for PT-BR:

[BiglyBT.zip](https://github.com/BiglySoftware/BiglyBT/files/1256151/BiglyBT.zip)

**Comment by parg** [comment]
Posting them here works - or if you want to battle git and do things via repository changes and pull requests you could look at https://gist.github.com/Chaser324/ce0505fbed06b947d962

Personally I'd just paste them here :)

Thanks!

**Comment by parg** [comment]
Perhaps create an issue called "Translation updates: PT-BR" next time and post them there?

**Comment by TuxPaper** [comment]
You can also literally edit the file in GitHub, and paste in the contents of your new file. https://github.com/BiglySoftware/BiglyBT/blob/master/core/src/com/biglybt/internat/MessagesBundle_pt_BR.properties

Instructions at [Editing Files in another user's repository](https://help.github.com/articles/editing-files-in-another-user-s-repository/).  The advantage is that the change goes through a pull request, and your account credited for the commit and line changes.
