### ISSUE TITLE
Api

### ISSUE THREAD

**Issue by RimfireFoShizzle** [BiglySoftware/BiglyBT#439]
Hi, I have a question.

Does Bigly have an api? I'd like to connect it with Sonarr and Radarr.

Or is the api the same as Vuze? (I think that would mean I don't have to change my settings in Sonarr/Radarr)

**Comment by parg** [comment]
Thing should work as with Vuze - tell me if you have any issues

**Comment by RimfireFoShizzle** [comment]
Works like a charm!

Issue closed

**Comment by parg** [comment]
Great - tell all your friends :)
