### ISSUE TITLE
ScaneRSS

### ISSUE THREAD

**Issue by Havokdan** [BiglySoftware/BiglyBT#44]
Are you thinking of bringing other plugins to BiglyBT? I wanted ScaneRSS (https://plugins.vuze.com/details/scanerss), since what was brought to BiglyBT was RSS Feed Scanner that did not work with me since version 1.5.2 onwards. (Ironically, it stopped working with me. Let me add my translation to the plugin, I do not know if it would be related to this problem at all.)

**Comment by BiglyBT** [comment]
I added it to https://plugins.biglybt.com/ - not tested though. Also not sure how well it works these days, good luck!

**Comment by Havokdan** [comment]
Thanks

**Comment by Havokdan** [comment]
I found only slight bug, it looks like I have to open and close, then open again for the application to appear correctly. That is, it only opens correctly on the second attempt. Otherwise, it's okay.
