### ISSUE TITLE
once minimized to the Kubuntu systemtray it stays there forever

### ISSUE THREAD

**Issue by HieronymusCH** [BiglySoftware/BiglyBT#440]
The GUI will never pop up once it is minimized by the settings or by KDocker.

System:
Kubuntu 17.10
KDE-Plasma 5.12.4
KDE-Framework 5.44.0
Kernel 4.13.0-39
64-bit
openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-8u162-b12-0ubuntu0.17.10.2-b12)
OpenJDK 64-Bit Server VM (build 25.162-b12, mixed mode)

**Comment by WPFilmmaker** [comment]
@TuxPaper Still relevant as Jan 2019.

Happens on my system too:
BiglyBT 1.7.0.0
Lubuntu 16.04.3
LXPanel 0.8.2
Java 1.8.0_191 (64 bit)
  Oracle Corporation
/usr/lib/jvm/java-8-openjdk-amd64/jre
SWT v4757, gtk/3.18.9
Linux v4.4.0-141-generic, amd64 (64 bit)
B1.7.0.0/4 az2

**Comment by WPFilmmaker** [comment]
Update: 1.8.0.0 still has this bug, seems that dorkbox plugin doesn't help :(
