### ISSUE TITLE
Program crash

### ISSUE THREAD

**Issue by jeehay** [BiglySoftware/BiglyBT#444]
Hi, biglybt crash if I have more then 600 active torrent. it just crash with no errors.

My PC is windows 10 i7 with 16GB ram.

**Comment by parg** [comment]
600 active is quite a lot! You probably need to increase your Java heap limit - go to Tools->Options->Startup & Shutdown (might need to set your 'Mode' to 'Advanced' under the Mode settings first) and increase the 'Max Heap Size'

**Comment by tea-dragon** [comment]
yeah, setting out 12 GB of memory without touching other jvm flags is likely to only make things much worse.
