### ISSUE TITLE
No option to migrate torrent files from Vuze post-BiglyBT installation

### ISSUE THREAD

**Issue by interzone826** [BiglySoftware/BiglyBT#445]
It's handy that the installer provides the option to migrate Vuze settings, but I have 2500 torrents in my Vuze app. Even with all of them stopped, importing them into BiglyBT soon causes it to hang (though the same is happening with Vuze, because for some reason, moving my boot drive to a newer machine with more RAM, and upgrading from OSX 10.6.8 to OSX Sierra, is causing Vuze to behave sluggishly on the new machine when it worked fine on the old).  So I installed a clean version of BiglyBT and did not migrate, and then adjusted the Java memory options from within BiglyBT. 

With the new memory settings: 
-Xmx232m
-Xms32m

I'd like to now try a migration. How can I migrate post-install?

**Comment by don-reba** [comment]
Installation is not an appropriate time to migrate files to begin with. Installation can (and should) be done under a different user account than the one doing the torrenting. And there may be multiple users on the machine. Post-install is the only time migration should be done.

**Comment by interzone826** [comment]
Thanks, but I don’t believe I said anything about migrating files during installation, hence the use of the word “post-“ in the subject line of my question….

I am curious, though, as to why you say one should create a separate user account for the installation. What is the logic behind that move?

Regards

**Comment by don-reba** [comment]
I was referring to "It's handy that the installer provides the option to migrate Vuze settings."

> I am curious, though, as to why you say one should create a separate user account for the installation.

I just mean installing programs using the admin account and torrent under a non-admin one.
