### ISSUE TITLE
For torrents seeding pre-existing files, Downloaded size should be zero

### ISSUE THREAD

**Issue by sklm** [BiglySoftware/BiglyBT#446]
Suppose I downloaded a *.torrent for which I already have all the files locally, so I just point BiglyBT to the preexisting files and begin seeding them immediately. For example, cross-seeding.
In this case, I believe the General:Transfer:Downloaded info should show 0 bytes because I haven't downloaded any data for this *.torrent. Instead, it shows the total size of the included  files as if I actually downloaded them. This may be very confusing.

**Comment by parg** [comment]
It does that so set the 'share ratio' to 1.0

Check Tools->Options>Queue->Seeding: Consider 'add for seeding' downloads to have downloaded this number of copies: 1

**Comment by sklm** [comment]
Thanks. That's exactly the settings option I was looking for.
