### ISSUE TITLE
Media Player - NullPointerException

### ISSUE THREAD

**Issue by sungerbob** [BiglySoftware/BiglyBT#45]
Systtem Section:
https://user-images.githubusercontent.com/31207969/29832020-8ae4f58a-8cef-11e7-9b5f-e5260827966f.JPG

If you select "Tabbed(Old)" ui on installation setup, you will get "NullPointerException" error on Embedded Media Player
https://user-images.githubusercontent.com/31207969/29832038-95e22fd4-8cef-11e7-9166-fc6d614ad4fb.JPG

https://user-images.githubusercontent.com/31207969/29832042-9b936f6a-8cef-11e7-89af-87ab47159313.JPG

same torrent. 
It's working if i select "Sidebar" ui on installation setup. I don't know why it's not working

**Comment by sungerbob** [comment]
Also, VLC option in settings doesn't working. #10

**Comment by parg** [comment]
Currently streaming playback isn't supported with the classic (tabbed) UI - obviously it should fail in a more obvious way though, I'll try and improve the error message.
