### ISSUE TITLE
Frequent 'hangs' causing system reboot reqd...

### ISSUE THREAD

**Issue by Quiffster** [BiglySoftware/BiglyBT#453]
Hi- recently switched to BiglyBT from Vuze, but suffering terrible instability - with frequent system 'hangs' requiring a full reboot to remedy.  I wonder if this is because of upgrade / settings issues from Vuze.

Is a removal of Vuze / fresh install of BiglyBT recommended?

Steve.

**Comment by tea-dragon** [comment]
reducing variables is always a good idea. however there is likely a way to back up your settings if they are intricate.

**Comment by Tom-Neverwinter** [comment]
I can confirm this issue as well. started after windows 1803 update
