### ISSUE TITLE
Move files not working

### ISSUE THREAD

**Issue by BikerDom** [BiglySoftware/BiglyBT#457]
After upgrading to version 1.5.0.0 when I have a file or mutliple files selected while viewing a torrent that when I select 'Move Files' nothing happens

**Comment by parg** [comment]
can you try the latest beta - see the Help menu to get it

**Comment by strange-antiquark** [comment]
This is also an issue for me, but joining the beta team is not really an option for me. 
What would be the implications (eg other bugs) of reverting to ver. 1.4? 
If that is feasible, is it necessary to run the full 1.4 installation shell?

**Comment by parg** [comment]
Why isn't joining the beta program an option? If you want to do it manually then download the latest .jar file from 

https://s3.amazonaws.com/biglybt-files/core/BiglyBT1501-B10-signed.jar

rename it to BiglyBT.jar and replace the one in your Big;lyBT installation folder with that one.

**Comment by strange-antiquark** [comment]
If you join a beta program, that sorta commits you to poking around and trying to break things :grin: I just don't have the time to do a decent job of it. Besides, I'm only using a small portion of the features -- just grabbing torrents off private trackers. 
Maybe later in the year, or early next year, I'll have the time (I may retire, and will need something to do :smile: ) and if so, I'll reconsider, and we'll see what happens.
Meanwhile, thanks for the quick response, and I'm def. looking forward to 1.6 when it's released.
