### ISSUE TITLE
Java.lang.Null.Pointer Exception message after today's update...and more

### ISSUE THREAD

**Issue by Swampgirl911** [BiglySoftware/BiglyBT#461]
Hi! 
I received the following Java message today after the update, and could not figure out how to fix it on my own.
java.lang.NullPointerException
	at org.eclipse.swt.widgets.Control.internal_new_GC(Control.java:2124)
	at org.eclipse.swt.graphics.GC.cocoa_new(GC.java:210)
	at org.eclipse.swt.widgets.Tree.sendMeasureItem(Tree.java:2596)
	at org.eclipse.swt.widgets.Tree.cellSize(Tree.java:288)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5590)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper_stret(Native Method)
	at org.eclipse.swt.widgets.Widget.expansionFrameWithFrame_inView(Widget.java:814)
	at org.eclipse.swt.widgets.Tree.expansionFrameWithFrame_inView(Tree.java:1274)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5969)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend_bool(Native Method)
	at org.eclipse.swt.internal.cocoa.NSRunLoop.runMode(NSRunLoop.java:42)
	at org.eclipse.swt.widgets.Display.sleep(Display.java:4740)
	at com.biglybt.ui.swt.mainwindow.SWTThread.<init>(SWTThread.java:285)
	at com.biglybt.ui.swt.mainwindow.SWTThread.createInstance(SWTThread.java:64)
	at com.biglybt.ui.swt.Initializer.<init>(Initializer.java:179)
	at com.biglybt.ui.swt.UI.takeMainThread(UI.java:108)
	at com.biglybt.ui.Main.main(Main.java:236)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:65)
	at com.install4j.runtime.launcher.MacLauncher.main(MacLauncher.java:67)
It just showed up on its own.

Here's the computer info:
Mac OS Sierra 10.12.6

Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro9,2
  Processor Name:	Intel Core i7
  Processor Speed:	2.9 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	4 MB
  Memory:	16 GB
  Boot ROM Version:	MBP91.00D9.B00
  SMC Version (system):	2.2f44
  Serial Number (system):	C02HX0U1DV31
  Hardware UUID:	1306422B-E6AC-59F2-AB0F-481493A402F9
  Sudden Motion Sensor:
  State:	Enabled
I am running BiglyBT Beta, Version: 1.5.0.1_B04

Forgive my piling on, but while the “New” entry and the “Download Entry” in the sidebar have improved, once the download entry is emptied of content, it disappears, and must be checked again within the options menu for it to reappear.  The “New” entry stays in the sidebar, but becomes unchecked (just to bug me). Also, something weird is happening (and maybe someone else spoke to this, but I was not sure), when the files complete downloading and then move. They ARE moving to an external drive, but show an error every time (even though they moved just fine), perhaps because they don’t stay long in the default directory (on my MBP). Also, (and I may have fixed this with Tags, which I have not used before), the .torrent file is not moving to its designated directory “Torrents”, but instead moves to the designated data directory (both on an external drive). Finally, when I enable the box at the top of the page of the  “Tor helper,” my subscriptions begin to populate with yellow yield signs. It took me a bit to figure out how to reestablish connectivity. To remedy, there was little I could do. It seems as though once something is checked or chosen, there are no “backsies” (i.e., if I uncheck something I have fiddled with, it doesn’t seem to respond, even after a restart - it just behaves as if it is still checked. So I unchecked the Tor Helper, then uninstalled/reinstalled BiglyBT - and all was in good working order again. Sigh. :)

I would love to learn how to debug myself, and spent a good part of the day trying to figure it out, but I could not find any tutorial that spoke as though I was seven years old, and had it to do all over again.

Thank you so very much for all of your efforts. I greatly appreciate BiglyBT, and that there is someone looking out for it, in his “spare time.” You make a difference, and have made a difference in my life. Swampgirl911

Thank you for all that you do!
Warm Regards,
Swampgirl911

**Comment by parg** [comment]
Not much that can be done about that initial exception - it is being thrown from within the graphics library we use (SWT) - shouldn't cause any problems though

I thought I'd fixed the Downloading thing - weird. Same with 'New', the options to show them should only change if you explicitly remove them from the sidebar by hitting the little 'x'. I did find an error that caused the Downloading view to show on startup when there were no downloads. I've added some debug to the next beta that might shed some light on things.

I just checked the 'move torrent' option under Tools->Options->File->Completion Moving and it worked ok for me ;(

The 'Tor Helper' is used to attempt to automatically connect to things such as Subscriptions over the 'Tor' network when it appears that directly connecting over the internet is being blocked. Sometimes this also fails but I'm unsure why enabling it would cause things to go from working -> not, and also why disabling it wouldn't revert things.

**Comment by Swampgirl911** [comment]
Dear Parg,

Thank you so very much for taking the time to reply. I saw that you replied
right away (May 10th), and was so surprised, but I was also in the middle
of family descending down upon me.

I just found your email in the always neglected Gmail Forums category as I
am not a big Forums person, but boy was I surprised. Of the four emails
hanging out in there, one of them was YOURS!!!!!!   You  also *emailed me -
WOW!  *I mean it.  Thank YOU!
Anyway, the "New" Category in Bigly BT stays, whether there is new stuff or
not.  I like this - apparently I am averse to categories disappearing - who
knew?   However, as I am sure you are well aware, if I choose things to
download, the Download category does not appear.  I must go into
options>Interface>display and choose it. If all my downloads complete, the
Download category disappears again.  If I start new downloads, even without
restarting Bigly BT, I must again choose the Download category in
Options>Interface>display.  (I am on a Mac running OS Sierra - I believe I
sent you my specs, if there is something else I should send along, please
let me know and I will happily "fork" it over (very bad pun).

Thank you for the reassurances regarding the null pointer exception; the
warning comes up a few times, then stops.

Regarding the "Move Torrent" option.  I am attaching 2 screen shots of my
configuration.  The first is the Default directory on the "Files" page; the
torrent and data initially download to a file in my Documents Directory on
my hard drive. Then the torrent and data moves from there to an external
drive, where I would like the data to go into the Downloads directory, and
the Torrents to the Torrents Directory.  I wonder if I have the correct
options checked, i.e., is my configuration the problem.  Also, the torrent
files are saved in Users/Home/Library/Application Support/BiglyBT, all on
their own, but not all are there.  This may have something to do with my
removing then re-downloading BiglyBt a number of times, because I've done
something I can't figure out to undo, or like the last time, BiglyBt just
refused to open.  I'm not sure why, but user error was what I assumed at
the time.

Regardless, both the data and the torrent move into the Downloads directory
on my external drive, and sometimes, a torrent also moves to the Torrents
Directory as well.  Is there a limit to how many Torrents can move to the
External Drive Torrents Directory?

Another reason there are inconsistent Torrent files in some places and not
others, is that after tiring of trying different configurations to no avail
(the Torrent files *still* ended up in the External drive's Downloads
Directory), I tried to reinforce my choices by using the options in
specific Tags.   I included how I configured these (all purple).  The
problem is, I forget to reconfigure these tags after I remove and
re-download BiglyBT, and for whatever reason, the Tag configuration does
not remain in the saved config file.  I do know that for a brief moment in
time, the torrents did not appear in the Data Directory. Unfortunately, I
did not make note of the particular configuration that worked briefly.  I
think the Tag configuration also disappears if I restart my computer.
Plus, I do not know if the Tag configuration has anything to do with
anything. 😊

I am aware that I can just delete them - so I believe it is just the
principle of the whole thing; I didn't used to have to ever think about it.
It just took care of itself.  I will get over it if need be. I have become
even more adept than ever at deleting. 😁

I admit to avoiding the Tor helper altogether.  I might try again and see
if it repeats causing a mess o' trouble, or if I caused the trouble by
changing another option as well (I never remember).   If I try again, and
fiddle with nothing else, and BiglyBT grinds to a halt, I'll let you know.

Thank you so very much for your help and writing me. I know now to check my
Forums folder, as your email will now will be the only one that appears in
it!

Warmest Regards, and thank you for all that you do!

Leslie L Gordon

**Comment by parg** [comment]
Hi,
Thanks for the reply! Can you just double check that you are still having the issue with the 'Downloading' category going AWOL in the latest beta (B12)?

Regarding the non-movement of .torrent files, you didn't attach the screenshots so I'm not 100% sure of your configuration. However, it should either work or not! Quite why occasionally the .torrent file is moved is beyond me. Unless it has something to do with the original .torrent file being deleted before things complete. Perhaps you could find a download for which the .torrent file didn't move and see if you can figure out where the original .torrent file is? There are options to automatically delete torrent files under Tools->Options->Files->Torrents, perhaps check them out?
cheers
Parg
