### ISSUE TITLE
No mouse response if menu is open when shutdown triggers

### ISSUE THREAD

**Issue by Galane** [BiglySoftware/BiglyBT#462]
I had the shutdown option set to shutdown BiglyBT. I clicked the Tools menu, was going to change it to not shutdown, and immediately after that the shutdown window popped up with the timer.

BiglyBT then would not respond to mouse clicks anywhere. The menu was still open and wouldn't close. I was able to hit the right arrow key then Enter to stop the shutdown on the timer window.

This was on Windows 10 x64

**Comment by parg** [comment]
There are a few weird issues like that regarding focus being grabbed away from controls. Unfortunately the issue is in the graphical library that BiglyBT uses (SWT) and is not something we can fix ourselves.
