### ISSUE TITLE
The New feature isn't working anymore...

### ISSUE THREAD

**Issue by Xuchilbara** [BiglySoftware/BiglyBT#464]
Hello, since the last stable version of BiglyBT the New feature isn't working anymore. When a new torrent completes downloading, it goes to the Library and no notification in New, nor anywhere else is displayed.

I tried all tabs and categories, tried to restore all of them, tried creating new ones... No luck. Still can't get BiglyBT to show me the new torrents in a special section, which I loved because it did that automatically and was very useful!

I installed the latest beta, and still the same...

Thanks.

Windows 7 Ultimate X63 SP1.
BiglyBT 1.5.0.1_B04 and previous stable release.
Desktop Environment.

**Comment by parg** [comment]
Hmm, 'works for me' - is the New section visible in the sidebar at all? A new option was added to allow it to be removed completely

**Comment by parg** [comment]
Go to Tools->Options->Interface>Display - scroll down to the 'SideBar' settings and tick the 'Show the 'New' entry' box

**Comment by Xuchilbara** [comment]
Now it seems to be working as usual! All the recent torrents are still there, even...
It was silly easy, but I think the option should also be in the area, for example in the My Torrents sidebar context menu...
Anyway, thank you very much, solved!
