### ISSUE TITLE
Search for existing data files options

### ISSUE THREAD

**Issue by BPDunbar** [BiglySoftware/BiglyBT#466]
I have a torrent which matches some files I already have, they are in a different directory structure and not always by the same name. I would like to be able to skip downloading them. If I use the search for existing data files option in the right click menu it will find them and amend the torrent directory tree to point at the existing files in their current location. This isn't always what I want to happen.

I would like at the end of the matching process an option to either use the matched files in their current location move them to the location in the directory tree specified by the torrent or create a copy the location in the directory tree specified in the torrent. It should also have an option to rename while doing this.

If such a feature exists it isn't obvious how to find it.

You could do it by having a select between "use in place/move/copy" and a tick box for rename files whern selecting "search for existing data files".

**Comment by parg** [comment]
The latest beta has an option to copy the files rather than link - see the Help menu to join the beta program

**Comment by alexandru5500** [comment]
Hello Prag,

Please tell us if it's possible to have also an option to move matched files instead of copying them.

Thank you.
