### ISSUE TITLE
Advanced Renaming Capabilities - FEATURE ADD Suggestion

### ISSUE THREAD

**Issue by ms52538** [BiglySoftware/BiglyBT#467]
Not an issue, but a HUGE suggestion: Advanced Renaming Capabilities

I have an extensive and large collection of torrent files - as do many. I also use a few different media server packages for streaming such as Plex.  Something that I struggle with constantly in my management of torrents is renaming: renaming torrent files as they are downloaded, renaming torrents in my BiglyBT library, tagging them, renaming them, adjusting punctuation, at the file level within the OS (Windows 10 64bit in this case). And to simply put it: there really aren't any features in the function of renaming torrents/files within BiglyBT (nor Vuze). I would think this is a challenge for many, not just myself, and that added feature functionality around the renaming task is warranted for consideration?

I've used several different renaming apps for Windows, my favorite of which is "Advanced Renamer" by Kim Jensen. She has developed a remarkable app that is wonderful to use - in Windows at the file name level within the OS. I can't tell you how many times I wish her apps features and functions were incorporated directly into BiglyBT to help with my mass management of thousands of torrents files and the subsequent files names within each torrent. It has a mass search/replace feature, auto numbering feature, lower/upper case feature, etc.. And while I love it - I can't use it within BiglyBT without causing havoc with changes made at the OS file level and not within BiglyBT. The "Advanced Renamer" app can be found here: https://www.advancedrenamer.com/

Another feature I would suggest is the ability to sort text that is highlighted with options such as custom character separation of terms, ascending/descending of words. A few great tools are out on the internet written in PhP (I presume). A few examples of these are "The Alphabetizer" (https://alphabetizer.flap.tv/), and "SortMyList" (http://sortmylist.com/).  This feature really would be handy when attempting to add then sort the names of actors in a video into the torrent file name, or the embedded torrent names within a torrent file.

Love the development effort taking place. I just hopped onto the beta bandwagon and grabbed the .04 changes and notice them difference already (i.e. move file within a torrent to differing directories (thanks for fixing this btw - like the new interface pop-up).

Regards,
Mark

**Comment by parg** [comment]
Hi Mark - thanks for the feedback! The only feature in BiglyBT that might vaguely address your needs in the fairly recently introduced 'batch rename' feature - it is a right-click option in Files View. Note that you can select multiple downloads in the Library at once and all of their files appear in the Files View so it gives you the ability to fiddle with multiple torrent's files in one operation. That being said it is pretty rudimentary in that it gives you a text file to make modifications to and then applies the changes in batch. Might help for find/replace type changes if you copy the text into an editor, fiddle and then copy back. Of course you need to ensure that you don't change the non-path entries in the file as it your changes will then cause confusion and possibly worse :)

**Comment by ms52538** [comment]
Thank you sir, it works just as described. One big step forward - for sure! Great feature add. Thank you. :)
While I have your attention, quick question: is there a way to rapidly condense multiple torrents in a view from the library or other views. I have so many torrents with twisties that I have to scroll and click to open, then close. I was hoping there was a way to rapidly close all twities in a single swoop. :)

**Comment by ms52538** [comment]
Awesome!! :) Thank you!

**Comment by ms52538** [comment]
Hey, I see B11 is out. Not sure if a release had come between 4 and 11, but I def note that I'm 11 now after a clean install, hop onto beta, and restore from backup. I see the collapse feature is there, and in testing it, works great! Is there somewhere that release notes are available for new features/add/changes/fixes/deletes?  Thanks much! Great work. :)

**Comment by parg** [comment]
There is https://www.tumblr.com/blog/biglybt - not verbose but might give a clue as to what is in each beta

**Comment by ms52538** [comment]
Awesome, thank you! - and I just picked up 12.
