### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by CabildoBaggins** [BiglySoftware/BiglyBT#468]
Every time I open the app I get a request to update to v 1.5. I make it as far as accepting terms and conditions but then when I click on "Next" nothing happens.

Mac OS 10.13.4
  Model Name:	iMac
  Model Identifier:	iMac11,3
  Processor Name:	Intel Core i7
  Processor Speed:	2.93 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Memory:	16 GB
  Processor Interconnect Speed:	4.8 GT/s
  Boot ROM Version:	IM112.005C.B00
  SMC Version (system):	1.59f2

**Comment by ms52538** [comment]
I had that exact problem yesterday. I back up my config directory, used the rest option, re-applied the beta check box, and manually selected the update button, was golden after that. A few files came down, I applied, and was updated.

**Comment by CabildoBaggins** [comment]
Not following you. Config Directory sounds like something for Windows or Linux and I'm on a Mac. Beta check box???

**Comment by ms52538** [comment]
No expert on Mac, sorry, I just ass-umed the program had the same features, universally. Guess not.
