### ISSUE TITLE
scrape error files not found

### ISSUE THREAD

**Issue by Phoenix22334455** [BiglySoftware/BiglyBT#469]
hi,
* OS and version Windows 10 Build 1803
* BiglyBT Version Number 1.5
* For *nix: Desktop Environment

i have a problem, BiglyBT show me a message from tracker : scrape error , "files not found".

when, i would go in content from biglyBT , show me where is my files and this files are present.

i have restarted BiglyBT and now all it's correct. wut ???

ps: if , i wrong on any word, sorry for my bad english ^^

**Comment by Phoenix22334455** [comment]
maybe, but can i disable it ?

**Comment by ZeuPuniSheR** [comment]
hello, every one !
I have the same problems on almost all my seeding torrents since the beginning i use BiglyBT.
My version is 1.7.0.0 but i had the same problems with oldest versions. 
My principal tracker is : http://tracker.ygg.is:8080 and in the details i can see there isn't DHT activated...
I know that's important but for what ...? :-p

**Comment by parg** [comment]
'file not found' errors from trackers are usually due to the tracker no longer having the torrent registered - i.e. old torrents. It may also be the case that the tracker doesn't support 'scrape' protocol, although that is rare. Do you get the same error for something you have recently downloaded?

**Comment by ZeuPuniSheR** [comment]
All my torrents are existing on the tracker although...the most recents (less than 48h) are ok...

**Comment by parg** [comment]
I'd ignore those messages then, sounds like the older torrents are no longer on the tracker

**Comment by ZeuPuniSheR** [comment]
But I just told you the torrents exist on the tracker ... Even the oldest
one...

**Comment by parg** [comment]
ah, sorry, mis-read it. Perhaps you could post a torrent with the issue here, or email to parg@users.sf.net
