### ISSUE TITLE
PayPal donation

### ISSUE THREAD

**Issue by gnavascues** [BiglySoftware/BiglyBT#47]
I can't make a donation without PayPal ?

**Comment by TuxPaper** [comment]
The only other option other than Paypal is Bitcoin (BTC or BCH).  You can (somewhat) easily get bitcoins at one of the [many exchanges](https://www.bestbitcoinexchange.io/) and donate to our address,  1BiGLYBT38ttJhvZkjGc5mCw5uKoRHcUmr

The link above is pretty good at listing the pros and cons of each exchange, and how you can fund it (CC, cash, bank, etc)
