### ISSUE TITLE
Installer fails to copy tmp files sparsely, explodes disk usage

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#471]
**Environment Details:**
* OS: Fedora Linux 28 x86_64
* BiglyBT Version: 1.5.0.0 from GitHub_BiglyBT_Installer.sh
* For *nix: Desktop Environment not a factor, but running installer from shell remotely displayed (via SSH X-forwarding) in Gnome Shell 3.26.2 running on Fedora Linux 27 x86_64

Running the BiglyBT 1.5.0.0 installer just now, I selected the option to have it migrate settings from my existing `$HOME/.azureus` directory. I noticed that, though `$HOME/.azureus/` is only 233M in size, `$HOME/.biglybt/` blew up to 4.6G(!) before the installer proceeded to the next step.

The extra space turned out to be consumed entirely by `$HOME/.biglybt/tmp/`, which contained all of the same files as `$HOME/.azureus/tmp/`, and at the same sizes, but occupied 20× as much space on disk.

The files `$HOME/.azureus/tmp/*.tmp/*` are all sparsely populated, they occupy a tiny fraction of their total size in actual disk space. But when BiglyBT's installer copies them, it fails to preserve the file sparseness, and the sizes explode:

```console
$ cd ~/.azureus/tmp && du -sch */* |cut -c1-35 > /tmp/azureus.out
$ cd ~/.biglybt/tmp && du -sch */* |cut -c1-35 > /tmp/bigly.out
$ paste /tmp/azureus.out /tmp/bigly.out
8.0K	AZU1110516799710251866.tmp/134	65M	AZU1110516799710251866.tmp/1345
88K	AZU1650058651076236701.tmp/C481	65M	AZU1650058651076236701.tmp/C481
8.0K	AZU2010771874208788221.tmp/D70	65M	AZU2010771874208788221.tmp/D707
8.0K	AZU2068510907066745837.tmp/76C	65M	AZU2068510907066745837.tmp/76CD
8.0K	AZU2091037623073721998.tmp/27D	65M	AZU2091037623073721998.tmp/27D7
4.0K	AZU2245047228488012771.tmp/3AD	65M	AZU2245047228488012771.tmp/3AD0
8.0K	AZU2506480165240227968.tmp/1A0	65M	AZU2506480165240227968.tmp/1A0F
8.0K	AZU2575687720561798284.tmp/550	65M	AZU2575687720561798284.tmp/5509
8.0K	AZU2806439823719227476.tmp/22F	65M	AZU2806439823719227476.tmp/22F3
4.0K	AZU2868651833714704724.tmp/5BF	65M	AZU2868651833714704724.tmp/5BF4
24K	AZU3047073407676822624.tmp/28A2	65M	AZU3047073407676822624.tmp/28A2
8.0K	AZU3107436153943015620.tmp/F34	65M	AZU3107436153943015620.tmp/F344
8.0K	AZU321242269550238755.tmp/C109	65M	AZU321242269550238755.tmp/C109E
8.0K	AZU3222572271403421340.tmp/EBA	65M	AZU3222572271403421340.tmp/EBAA
8.0K	AZU3252554768117036896.tmp/D4F	65M	AZU3252554768117036896.tmp/D4F9
8.0K	AZU3271691635297599138.tmp/7BB	65M	AZU3271691635297599138.tmp/7BB9
8.0K	AZU3412156078128992223.tmp/0B6	65M	AZU3412156078128992223.tmp/0B67
28K	AZU3589067454527128399.tmp/A236	65M	AZU3589067454527128399.tmp/A236
8.0K	AZU4090725051555131907.tmp/05C	65M	AZU4090725051555131907.tmp/05C9
8.0K	AZU4701847263825563906.tmp/4BF	65M	AZU4701847263825563906.tmp/4BFE
8.0K	AZU482477254866577314.tmp/216D	65M	AZU482477254866577314.tmp/216D9
8.0K	AZU4869178321888133464.tmp/027	65M	AZU4869178321888133464.tmp/0279
8.0K	AZU4937927212652992132.tmp/BDC	65M	AZU4937927212652992132.tmp/BDC9
8.0K	AZU5268031569189508600.tmp/DA5	65M	AZU5268031569189508600.tmp/DA5A
8.0K	AZU5347552641977779349.tmp/B26	65M	AZU5347552641977779349.tmp/B26D
28K	AZU5534321386543011637.tmp/3A22	65M	AZU5534321386543011637.tmp/3A22
8.0K	AZU5681120069673983898.tmp/511	65M	AZU5681120069673983898.tmp/5116
24K	AZU571120206263864812.tmp/37490	65M	AZU571120206263864812.tmp/37490
8.0K	AZU582348477443116352.tmp/2F75	65M	AZU582348477443116352.tmp/2F752
32K	AZU601190338231900902.tmp/6E4A0	65M	AZU601190338231900902.tmp/6E4A0
8.0K	AZU6050863201626599124.tmp/3C0	65M	AZU6050863201626599124.tmp/3C0F
4.0K	AZU620092404396185116.tmp/C173	65M	AZU620092404396185116.tmp/C1731
4.0K	AZU6341236618723526517.tmp/69C	65M	AZU6341236618723526517.tmp/69C5
8.0K	AZU6356764119167241469.tmp/811	65M	AZU6356764119167241469.tmp/811B
8.0K	AZU64471581461114894.tmp/C045B	65M	AZU64471581461114894.tmp/C045B6
8.0K	AZU6509021663425699321.tmp/EDD	65M	AZU6509021663425699321.tmp/EDD5
24K	AZU6551110880437913353.tmp/492C	65M	AZU6551110880437913353.tmp/492C
8.0K	AZU656446947977782255.tmp/EEC8	65M	AZU656446947977782255.tmp/EEC8E
8.0K	AZU6595255135323080564.tmp/E7E	65M	AZU6595255135323080564.tmp/E7EE
8.0K	AZU6893914811277127693.tmp/9D7	65M	AZU6893914811277127693.tmp/9D7E
8.0K	AZU6910758475634005887.tmp/2C7	65M	AZU6910758475634005887.tmp/2C7E
8.0K	AZU6929917822174167222.tmp/76D	65M	AZU6929917822174167222.tmp/76DA
8.0K	AZU6954804198722005958.tmp/149	65M	AZU6954804198722005958.tmp/1499
32K	AZU7124506257967557025.tmp/F67B	65M	AZU7124506257967557025.tmp/F67B
8.0K	AZU7343008710290563171.tmp/C17	65M	AZU7343008710290563171.tmp/C173
4.0K	AZU7387550084300037500.tmp/76D	65M	AZU7387550084300037500.tmp/76DA
8.0K	AZU7425777301819123711.tmp/3AD	65M	AZU7425777301819123711.tmp/3AD0
8.0K	AZU7564568797579264953.tmp/073	65M	AZU7564568797579264953.tmp/0736
52K	AZU785339900341684825.tmp/67DAF	65M	AZU785339900341684825.tmp/67DAF
64K	AZU8076536927631758766.tmp/7686	65M	AZU8076536927631758766.tmp/7686
8.0K	AZU8094646499423858174.tmp/5CA	65M	AZU8094646499423858174.tmp/5CA6
28K	AZU8212926069759662367.tmp/E01B	65M	AZU8212926069759662367.tmp/E01B
8.0K	AZU8223867497670246328.tmp/589	65M	AZU8223867497670246328.tmp/5899
72K	AZU8436462416689036272.tmp/6F5F	65M	AZU8436462416689036272.tmp/6F5F
8.0K	AZU8445207246478383057.tmp/69C	65M	AZU8445207246478383057.tmp/69C5
8.0K	AZU8485308706730934752.tmp/08E	65M	AZU8485308706730934752.tmp/08EB
8.0K	AZU8534011315412812744.tmp/60D	65M	AZU8534011315412812744.tmp/60DA
8.0K	AZU8587470328251576117.tmp/5BF	65M	AZU8587470328251576117.tmp/5BF4
8.0K	AZU8608865422779345041.tmp/74F	65M	AZU8608865422779345041.tmp/74F9
8.0K	AZU866400401006325349.tmp/6E8E	65M	AZU866400401006325349.tmp/6E8E3
28K	AZU8937860747812756921.tmp/C357	65M	AZU8937860747812756921.tmp/C357
8.0K	AZU9049712540079487707.tmp/B89	65M	AZU9049712540079487707.tmp/B895
8.0K	AZU908893277018702779.tmp/D437	65M	AZU908893277018702779.tmp/D4370
28K	AZU918049741599924635.tmp/52BC4	65M	AZU918049741599924635.tmp/52BC4
8.0K	AZU9199015771590746240.tmp/C66	65M	AZU9199015771590746240.tmp/C669
8.0K	AZU9200745411993956285.tmp/FD7	65M	AZU9200745411993956285.tmp/FD7C
948K	total                        	4.2G	total
```

I worked around it by just manually blowing away `$HOME/.biglybt/tmp/`, and replacing it with a sparse copy:
```console
$ rm -r ~/.biglybt/tmp
$ cd ~/.azureus/
$ tar cpSf - tmp/. | (cd ~/.biglybt && tar xvpSf -)
[...]
$ cd ~/.biglybt/tmp && du -sch *
16K	AZU1110516799710251866.tmp/
96K	AZU1650058651076236701.tmp/
16K	AZU2010771874208788221.tmp/
16K	AZU2068510907066745837.tmp/
[...]
48K	speedTestTorrent.torrent
2.6M	total
```

**Comment by TuxPaper** [comment]
Thanks for the detailed report.  That's just crazy.  The migration doesn't do anything special for the tmp directory compared to the other directories it copies, so it's a bit of a mystery.  I'll try to spin up a Fedora and see if I can reproduce it.

**Comment by ferdnyc** [comment]
Well, the thing is that file sparseness isn't ever preserved on copy, under Linux, unless you specifically take steps to preserve it. A straight `cp -R ~/.azureus/tmp/* ~/.biglybt/tmp/` will blow up all of the file sizes too. That's why I use `tar` with the `-S` flag to do the duplication, the flag means "preserves sparseness".

**Comment by ferdnyc** [comment]
(So I guess what I'm saying is, the _problem_ is that the migration doesn't do anything special for `tmp/` — It needs to. :grin: )

**Comment by ferdnyc** [comment]
Huh, actually I'm wrong, seems `cp(1)` grew sparse-file detection at some point. That's new-ish! From the man page:
> By default, sparse SOURCE files are detected by a crude  heuristic  and
> the corresponding DEST file is made sparse as well.  That is the behav‐
> ior selected by --sparse=auto.  Specify  --sparse=always  to  create  a
> sparse  DEST  file  whenever  the  SOURCE  file  contains a long enough
> sequence of zero bytes.  Use  --sparse=never  to  inhibit  creation  of
> sparse files.

So `cp -R ~/.azureus/tmp/* ~/.biglybt/tmp/` would probably preserve sparseness on at least most of the files. But if you're copying the files using the tools in whatever language the installer is written in, those tools may not be as smart about handling sparse files.

**Comment by ferdnyc** [comment]
Hmm, it seems Java 7 added [a `SPARSE` flag](https://docs.oracle.com/javase/7/docs/api/java/nio/file/StandardOpenOption.html#SPARSE) to the `StandardOpenOptions` for file streams, which "When used with the `CREATE_NEW` option ... provides a _hint_ that the new file will be sparse." But it's still not clear to me whether that will automatically cause sparseness to be preserved, or if a copy operation would also have to avoid duplicating the sparse sections as runs of null bytes. There's shockingly little information related to sparse-file handling in Java, from what I can find on the web.

**Comment by TuxPaper** [comment]
I wonder if I would be able to use `fallocate -d` on the files after java does the evil copy.  [Wikipedia's Sparse File](https://en.wikipedia.org/wiki/Sparse_file#Creation) article suggests I can.  [man of fallocate](http://man7.org/linux/man-pages/man1/fallocate.1.html)

**Comment by ferdnyc** [comment]
Yes, I tested that. (I hadn't actually `rm`'d the exploded version of the files, I tossed them in `trash:///`.) `fallocate -d  (any AZ*.tmp/*.part)` returned it to its normal sparseness.

**Comment by ferdnyc** [comment]
**Although**, if you're going to call `fallocate -d` in the shell, kind of seems like you might as well just call `cp --sparse=always` instead of doing the Java copy at all. :wink:
