### ISSUE TITLE
Installing on Ubuntu 16.04

### ISSUE THREAD

**Issue by canonlp** [BiglySoftware/BiglyBT#477]
When I run the installer, it gives me an error
`don't need JNA
not wayland
Starting Installer ...
\#
\# A fatal error has been detected by the Java Runtime Environment:
\#
\#  SIGSEGV (0xb) at pc=0x00007f1494457009, pid=559, tid=560
\#
\# JRE version: OpenJDK Runtime Environment (9.0) (build 9-internal+0-2016-04-14-195246.buildd.src)
\# Java VM: OpenJDK 64-Bit Server VM (9-internal+0-2016-04-14-195246.buildd.src, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
\# Problematic frame:
\# C  [libjava.so+0x1d009]  JNU_GetEnv+0x19
\#
\# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
\#
\# An error report file with more information is saved as:
\# /home/donut/BiglyBT_Installer.sh.534.dir/hs_err_pid559.log
\#
\# If you would like to submit a bug report, please visit:
\#   http://bugreport.java.com/bugreport/crash.jsp
\# The crash happened outside the Java Virtual Machine in native code.
\# See problematic frame for where to report the bug.
\#
./BiglyBT_Installer.sh: line 796:   559 Aborted                 $INSTALL4J_JAVA_PREFIX "$app_java_home/bin/java" -Dinstall4j.jvmDir="$app_java_home" -Dexe4j.moduleName="$prg_dir/$progname" -Dexe4j.totalDataLength=11814144 -Dinstall4j.cwd="$old_pwd" "-Dsun.java2d.noddraw=true" "$vmov_1" "$vmov_2" "$vmov_3" "$vmov_4" "$vmov_5" $INSTALL4J_ADD_VM_PARAMS -classpath "$local_classpath" com.install4j.runtime.launcher.UnixLauncher launch 0 "" "" com.install4j.runtime.installer.Installer "$@"`

I've already installed openjdk 9

**Comment by TuxPaper** [comment]
Looks like you hit this bug:
https://bugs.openjdk.java.net/browse/JDK-8173626

Same Ubuntu version (16.04) and same Java version (build 9-internal+0-2016-04-14-195246.buildd.src)

The openjdk issue suggests trying a newer version of Java.  If one isn't (easily) available, you could also try switching to Java 8 instead and see if that helps.
