### ISSUE TITLE
Pixelated text in File tree view

### ISSUE THREAD

**Issue by res1492** [BiglySoftware/BiglyBT#478]
Hello.
Im not sure if the text is meant to be doing this but just wanted to inform you of a bug that happens in Files section whilst using tree view.
As you can see from the screenshot the folder text is very strange, it looks like it is meant to be italic but is very pixelated.
Might just be me but meh!
Thanks for your hard work people!!!!

![pixelated text](https://user-images.githubusercontent.com/33879366/40577551-869d4c5e-60ff-11e8-97fa-c472156b8903.JPG)

Java 1.8.0_171 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_171

SWT v4757, win32
Windows 10 v10.0, amd64 (64 bit)
B1.5.0.0/4 az2

**Comment by parg** [comment]
Should be fixed in 1600 - please re-open if not the case
