### ISSUE TITLE
Right-click menu is extremely unresponsive

### ISSUE THREAD

**Issue by Makere** [BiglySoftware/BiglyBT#481]
Hi,

My BiglyBT is really slow when navigating right-click menues, the UI might freeze for minutes when hovering over the tabs in the menu and selecting items.

It seems that it gets slower over time as BiglyBT is running, 

This issue has persisted from 1.4, when I started using BiglyBT.

System info:
Java 1.8.0_171 (64 bit)
  Oracle Corporation
/usr/lib/jvm/java-8-oracle/jre

SWT v4757, gtk/3.18.9
Linux v4.4.0-100-generic, amd64 (64 bit)
B1.5.0.0/4 az2

**Comment by ferdnyc** [comment]
I've occasionally seen that happen as well, and I'm still really not sure what causes it. It doesn't seem to happen _all_ the time (at least for me), but occasionally the context menu will get extremely unresponsive, to the point where even getting it to come up feels almost impossible.

I should mention that, in my case, I'm using the Classic Interface and the un-Fancy Menus (so, no menu tabs).

#### System:
Java 1.8.0_171 (64 bit)
  Oracle Corporation
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.171-4.b10.fc28.x86_64/jre

SWT v4757, gtk/3.22.30
Linux v4.16.14-300.fc28.x86_64, amd64 (64 bit)
B1.5.0.0/4 az2

**Comment by parg** [comment]
Do you have a large number of downloads selected? In the past there have been issues when computing the state of the context menu items caused (for examples) the selected downloads' files to be accessed. That being said those issues have to my knowledge been fixed. Also you are both Linux, dunno if that could be related to it.

**Comment by Makere** [comment]
For me as well, it doesn't matter the amount of torrents selected, however, it seems to be readily responsive right after restarting the BiglyBT client, and slows down after running for some hours/days (feels like the longer I have the client running, the slower it gets).

I can try disabling the fancy menu to see if it affects the performance in anyway.

**Comment by Makere** [comment]
Switching off fancy menues seems to make it much more responsive,
Although first time I turned off the fancy menues, the client lost all the torrents so I had to do a restore from my automatic backup.

I will let the client run for couple days to see if it slows down (to same as @ferdnyc)
