### ISSUE TITLE
Android client

### ISSUE THREAD

**Issue by Shusshu** [BiglySoftware/BiglyBT#49]
Do you have the source for the Android client?

I'd be happy to improve it

**Comment by parg** [comment]
There source is here: https://github.com/BiglySoftware/BiglyBT-Android

How do you know it needs improving, it hasn't been released yet :)

**Comment by Shusshu** [comment]
Isn't it a fork of Vuze Remote for Android ?

Do you have the source for the Torrent Downloader on Android ?

I make Android apps for a living ;)

**Comment by TuxPaper** [comment]
We had 0 coding involvement with the Vuze Torrent Downloader for Android, other than to provide a vuzecore.jar (which was azureus2.jar without the UI and some Android checks).  I can not attest to the quality of that app, or what license it's under, and don't recommend anyone to use it.  (Personally, I think it's pretty ugly)

The Vuze Remote client, however, was done 100% by me and is fully GPL.  It had an option to use a full torrenting client, but it wasn't promoted as such.   The BiglyBT-Android project has made the full client an equal partner (It's actually the first option for new users).  In either case (Full client or remote control), it uses the xmwebui to communicate with the core, which really means it uses the Transmission RPC.  I'll be writing up a better Getting Started Dev guide for BiglyBT-Android sometime after it's released.

**Comment by Shusshu** [comment]
Ok, I'll improve that one then.
