### ISSUE TITLE
RSSFeed Scanner plugin's Status table expanders broken with SWT_GTK3

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#490]
I noticed that, when viewing the RSSFeed Scanner's Status tab (the table that lists configured feeds and the torrents received on each feed), the expanders (plus sign inside a square, or `[+]`) on the far left of each feed row aren't... sane.

If I left-click the `[+]` on the first row, it will expand some **other** row. That other row is _usually_ the second row, but I've also gotten it into even more confused states.<sup>1</sup> In the nominal case, though, it's the row below, and **every** expander in the list will expand the next row _below_ the one I click on, except for the one in the last row which does nothing.

The same (wrong) row can be collapsed by left-clicking the same `[+]` again. (It's a `[+]` still because, since the row being clicked didn't expand, its expander icon didn't change to a `[-]`. The expander in the other row (the one actually expanded) does change to`[-]` when that row is expanded.)

If I double-click on a row, the correct row (the one double-clicked) will expand/contract.

If I run BiglyBT with `export SWT_GTK3=0` in the startup script, all of these issues go away and the expanders all operate correctly on their own row.

**Plugin version**: RSSFeed Scanner 1.6.7
**System:** BiglyBT 1.5.0.0 installed from `GitHub_BiglyBT_Installer.sh`
Java 1.8.0_171 (64 bit)
  Oracle Corporation
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.171-4.b10.fc28.x86_64/jre

SWT v4757, gtk/3.22.30
Linux v4.16.14-300.fc28.x86_64, amd64 (64 bit)
B1.5.0.0/4 az2

#### Footnotes
1. An example of one of those "even more confused states" I just experienced, in a table with 5 feed rows: 
   1. The expanders on feeds 1 and 2 expanded feeds 2 and 3, respectively. 
   1. The expander for feed 3 expanded feed 5. 
   1. The expander for feed 4 _also_ expanded feed 5. 
   1. The expander for feed 5 did nothing.

**Comment by ferdnyc** [comment]
Now that I've given it a spin, the same behavior is present with the RSSFeed Scanner sidebar pane in the new interface.

**Comment by parg** [comment]
I've updated it to use the SWT Tree widget instead of the deprecated TreeTable - please try plugin version 1.6.8 (you need to be in the beta program to get it)

**Comment by ferdnyc** [comment]
Hmm, even after enabling Beta the update checker isn't showing a new version so far...
```
Checking rssfeed
    Current: 1.6.7_CVS, Latest: 1.6.7_CVS
```

**Comment by parg** [comment]
darn it, configuration error - please try again!

**Comment by ferdnyc** [comment]
Yup, got it now. And, problem solved — all the little twisties operate on their own row, as expected. Thanks!
