### ISSUE TITLE
Plugin timedautostart?

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#491]
I was originally going to write to request a port of this plugin to BiglyBT. (I tend to use it rather frequently, to stagger starting of multiple torrents when I have a backlog, since starting them all at once can be hard on my internet connection.) But I notice in the comments to #19 that @Shusshu has created [Shusshu/biglybt-plugin-timedautostart](https://github.com/Shusshu/biglybt-plugin-timedautostart).

So I guess my questions now are,
1. Is [Shusshu/biglybt-plugin-timedautostart](https://github.com/Shusshu/biglybt-plugin-timedautostart) usable?
1. If it is, can we get it listed on https://plugins.biglybt.com/ ?

If it's not functional, I'm back to requesting a port of the plugin. :smile:

**Comment by parg** [comment]
It is there under 'Stopped Torrent Auto-starter' :)

**Comment by ferdnyc** [comment]
So it is! Neeeeeeeeeevermind. :grin:
