### ISSUE TITLE
Feature Request: Sidebar Switch and Details Close buttons

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#495]
I'd like to request the addition of interface chrome to facilitate performing two operations conveniently with the mouse, using the new (non-Classic) interface:

1. A Sidebar visibility switch on the toolbar.
   
   Currently, hiding/unhiding the sidebar requires either pressing the <kbd>F7</kbd> key, or going into the menus to select View > Side Bar. It'd be nice to have a way to switch it open/closed with just a mouse click.
   
1. A Close button for the currently open Details view.
   
   With the sidebar _hidden_, opening a Torrent Details view leaves the user with no obvious way to close it again. The only real option is to open the sidebar (which does show a close icon for the details view), since there isn't even a menu option to close the current details view (Only File > Close **All** Details or Window > Close **All** Details), and surprisingly enough <kbd>Ctrl</kbd>+<kbd>w</kbd> has no effect in the Torrent Details view.

   It'd be really nice to have a standard "close" × icon somewhere in Torrent Details, that would close the details view and return to the previous view (presumably either Library or a tag view). It'd also be nice if <kbd>Ctrl</kbd>+<kbd>w</kbd> worked simply because it feels like it should, but that's separate from the need for a close icon outside of the sidebar.

**Comment by parg** [comment]
Next beta (B13) has an optional 'sidebar' toolbar button (go to Tools->Options->Interface->Display to enable it) and a small'x' button top left when sidebar collapsed (next to the existing two icons to expand sidebar/show menu form) to close current view

**Comment by ferdnyc** [comment]
> Next beta (B13) has an optional 'sidebar' toolbar button (go to Tools->Options->Interface->Display to enable it) 

Great, I will look forward to it!

>and a small'x' button top left when sidebar collapsed (next to the existing two icons to expand sidebar/show menu form) to close current view

...You lost me there. 

"the existing two icons to expand sidebar/show menu form"? I cannot for the life of me figure out what that's referring to. This is what the upper left corner of BiglyBT's window looks like for me, in the Library view with the sidebar collapsed.

![screenshot from 2018-06-15 10-52-39](https://user-images.githubusercontent.com/538020/41474678-9d310984-708a-11e8-87d0-3f03505e012f.png)

I mean, I guess I'll see soon enough when B13 rolls out, so it doesn't really matter.

**Comment by parg** [comment]
Ah, darn it, you have the search bar hidden and those controls are part of it :(

![image](https://user-images.githubusercontent.com/395293/41476781-7467fe74-70ba-11e8-99a1-25abb35f0a60.png)

**Comment by ferdnyc** [comment]
Oops, yeah, sorry. I don't use internal search _at all_, all of the torrents that come in to my client are either from browser-based searches (on a completely different computer; they're added either as `.torrent` files dropped in a Dropbox-synced watched directory space, or `magnet:` links exported to the Remote WebUI by a browser extension), or over configured RSS feeds.

**Comment by HieronymusCH** [comment]
I'm not quite sure if my problem really belongs into this thread.

As shown in the attached screenhsot sidebar entries without a counter/number displayed are not closable because the scrollbar overlays the "x" that should do the trick.

![Bug BiglyBT Sidebar Screenshot_20190606_094543](https://user-images.githubusercontent.com/3083524/59016376-64636c80-8841-11e9-87a0-ddc88e6dd116.png)

**Comment by parg** [comment]
Yup, annoying that one - a work around is to right-click on them and select 'close'

**Comment by parg** [comment]
Added "close view" menu item to the file menu - will be in 3501_B17
