### ISSUE TITLE
BiglyBT Web Remote: Link ignores configured port#, Access is overly restrictive

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#496]
Kind of a silly little thing, but the "Click to open the WebUI in your browser" hyperlink towards the bottom of Options > Plugins > BiglyBT Web Remote always links to `http://127.0.0.1:9091/`, even if you've configured the WebUI to listen at a different port#.

Also, setting Access to a range of IPs seems to cause it to exclude **all** other IPs, including localhost. Which means that link fails when Access is set to an IP range (unless 127.0.0.1 is part of that range, I suppose. Unlike the "Host whitelist" setting it doesn't appear to accept a comma-separated list of parameters, so setting an IP range has the side effect of always locking out local access.

**Plugin version**: BiglyBT Web Remote 0.8.2
**System:** BiglyBT 1.5.0.0 installed from `GitHub_BiglyBT_Installer.sh`
Java 1.8.0_171 (64 bit)
  Oracle Corporation
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.171-4.b10.fc28.x86_64/jre

SWT v4757, gtk/3.22.30
Linux v4.16.14-300.fc28.x86_64, amd64 (64 bit)
B1.5.0.0/4 az2

**Comment by ferdnyc** [comment]
Oh, nope, I take it back. After restarting the client, the Options link now uses the configured port#. It's just immediately after a change that it still uses the old value.

**Comment by parg** [comment]
It does accept a comma separated list although if you are entering anything other than "local" or "all" then every entry has to be an ip address range. So you would need, say,

192.168.0.1-192.168.0.255, 127.0.0.1

**Comment by ferdnyc** [comment]
Aha! That makes sense, thanks.
