### ISSUE TITLE
Many Inbound Connections from Biglybt

### ISSUE THREAD

**Issue by eurobank** [BiglySoftware/BiglyBT#498]
I'm running the latest beta (1.5.x) under Windows10/64 Pro.

I see that the client open a LOT of inbound connections (approx from 1000 to 1500). I'm downloading just one file and i have other 4 in queue. 

Not sure how that can happen and what they are. They bring down my router at home.

Any ideas appreciated.

![2018-06-18 18_05_54-](https://user-images.githubusercontent.com/4467158/41544811-4fc81422-7322-11e8-9da1-3847a3eab80a.png)

**Comment by parg** [comment]
That'll be the DHT I'd imagine - generates quite a bit of UDP traffic

**Comment by eurobank** [comment]
Thanks. Actually removing the extra DHT plugin, made things much better.

**Comment by eurobank** [comment]
Did some tests and it seems that other torrent clients open half of those connections. Not sure why.

Is there any way to limit those? Killing my router. Now i see 1500+ incoming.....

**Comment by eurobank** [comment]
My pc, NO transfers, No queue, nothing. Empty. Idle for 10 minutes.

This is an other open source (non commercial) torrent client.

![2019-12-24 17_26_09-Window](https://user-images.githubusercontent.com/4467158/71418443-31fd4d80-2673-11ea-83a5-543f44c91d04.png)

This is Biglybt client. No queue, nothing. Empty. Idle for 10 minutes.

![2019-12-24 17_29_18-Window](https://user-images.githubusercontent.com/4467158/71418459-44778700-2673-11ea-8f1d-bc5234917b7e.png)

**Comment by parg** [comment]
DHT probably

**Comment by eurobank** [comment]
DHT for what? No transfers, no queue. empty.

Just installed a 3rd closed source client and also a few connections. Biglybt is a chamption in this. And that causes problems with the routers that companies distribute with their services.

Anyway. Thanks. I can't use anymore this client. Having 4 torrents active, i can't even talk on the phone at the same time.

**Comment by parg** [comment]
laters
