### ISSUE TITLE
Download Deleter and Starter Plugin 

### ISSUE THREAD

**Issue by Taurean75** [BiglySoftware/BiglyBT#5]
This [plugin](https://plugins.vuze.com/details/azdowndel) cannot be installed due to different signature and data.

Anyway, I setup a tag specifically for automatic deletion with "removal only" scope and constraints "hasTag( "TV Show" ) && I(isGE( shareratio, 1 ) || IsStopped()) && !isPrivate()".

Would this work?

Thanks.

**Comment by Taurean75** [comment]
Thanks for your reply.

I've read on the forum that the limit should be set to 1, no?

**Comment by parg** [comment]
When you use the Tag 'limit' feature to control the maximum number of downloads that a Tag can have assigned to it then a value of 1 would allow a maximum of one download to match the constraint, any extra ones being removed automatically by whatever policy you select (remove from library, remove from computer etc). Unfortunately 0 was initially used to mean 'unlimited' so if you actually wanted a maximum of 0 downloads for the Tag then you couldn't specify it. Therefore the number 999999 was selected to have a meaning of 'none'

Can you explain your two tag set up in a bit more detail? If all you want to do is remove a download under circumstances such as the above then you just need the one tag. Also you probably should ignore the 'scope' setting for the Tag as it is unlikely to be needed for your scenario

**Comment by Taurean75** [comment]
This is what I use for torrent addition:
![tag](https://user-images.githubusercontent.com/8365855/28979503-e8aaff3e-78fe-11e7-81aa-e4d5cd1797b6.JPG)

What do need to change for it to automatically delete 'em?  I've tried changing the removal policies, but nothing seems to work.

**Comment by Taurean75** [comment]
For the "TV Show" tag, I can't set its limit to none as it adds public trackers to added torrents.

**Comment by parg** [comment]
ah, I see what you mean! You need a separate tag to handle the removal action

**Comment by Taurean75** [comment]
Exactly!

**Comment by Taurean75** [comment]
Your plugin was very handy for this...

**Comment by Taurean75** [comment]
Removal tag:
`"hasTag( "TV Show" ) && ( isStopped() || IsPaused() || IsComplete() ) && !isPrivate()"`
with the limit set to 1 and "Remove from Library" policy. Scope is both addition and removal.

Does this look ok?

**Comment by parg** [comment]
Try it :) A limit value of 1 will mean you'll end up with 1 torrent assigned to that tag and not removed yet - when another is added then the old one will be removed and so on - if you use the value 999999 instead of 1 then the torrent will be removed from your library as soon as the Tag condition is met.

**Comment by Taurean75** [comment]
I get the idea, but would the constraint be applied even when torrents don't get added to the tag?

**Comment by parg** [comment]
BTW, there is currently no obvious feedback as to the correctness of a constraint expression - the next beta (B03) will show errors on the Tag Settings page :)

**Comment by parg** [comment]
When a Tag has a constraint BiglyBT will automatically add torrents to the Tag when the constraint is true and automatically remove them if the constraint subsequently becomes false (unless you use the 'scope' settings which control whether or not these actions are automatic.

Once a torrent is added to a Tag the Tag's 'limit' setting is consulted to see if the addition of the torrent to that Tag requires action to enforce the 'limit'. If the 'limit' is 999999 then the torrent will immediately be remove from the Library (or whatever the policy is)

**Comment by Taurean75** [comment]
Thanks, I'll give it a try. :)

**Comment by parg** [comment]
In case you want to use the old plugin it is now available for installation on BiglyBT

**Comment by Taurean75** [comment]
I gave up. I'm just going to use your plugin.

Where is the new one?

**Comment by Taurean75** [comment]
I still get an error:
![error](https://user-images.githubusercontent.com/8365855/28996537-79aaf404-79b7-11e7-90ca-4437669e8537.JPG)

**Comment by parg** [comment]
Go to the Tools menu in BiglyBT, select the Plugins sub-menu and then 'Get
Plugins' (I think, not on computer at the mo) - browse to 'Downlosd deleter
and starter. plugin

**Comment by Taurean75** [comment]
Now I get:
![error](https://user-images.githubusercontent.com/8365855/28997221-09c46866-79c4-11e7-8e9e-487b82c4c5df.JPG)

**Comment by parg** [comment]
Weird, you're not having much luck! Please try pasting
https://s3.amazonaws.com/biglybt-files/plugins/azdowndel_1.6.biglybt into
the search area at the top of BiglyBT and hit enter

**Comment by Taurean75** [comment]
That worked -- thanks! :)

One more question: Does this work with tags, or do I need a category?

**Comment by parg** [comment]
It is a pretty old plugin and just works on categories - one day I should
update it to support Tags as well...

**Comment by Taurean75** [comment]
Thanks again!
