### ISSUE TITLE
Kotlin

### ISSUE THREAD

**Issue by Shusshu** [BiglySoftware/BiglyBT#50]
Do you plan to use kotlin ?

**Comment by TuxPaper** [comment]
No plans yet.  I don't have anything against Kotlin (in fact, from what I've read, there's some nice things that make coding easier), but there's far more important things for me to focus on (like actual coding) than to switch to Kotlin and find out I don't understand it as much as I think ;)   Or worse, find out it's so awesome, I spend 90% of my time for the next few months restructuring/recoding things to look beautiful.

To give some perspective of how slow to adopt new things we are, we just made the core have a minJDK of Java 8, after years for being Java 6, and there isn't even a Lambda in the core yet!  The BiglyBT-Android still is minSDK 9!!

Anyway, this question should be in the BiglyBT-Android project, but I can't seem to find a way in GitHub to move it there.  You are welcome to create an Issue there as a feature request, and I can label it so users can vote on it :)

**Comment by Shusshu** [comment]
Well kotlin is both for a java program or an Android app
