### ISSUE TITLE
VLC Enabled - Still the embeded player shows

### ISSUE THREAD

**Issue by eurobank** [BiglySoftware/BiglyBT#500]
Windows 10/64 Pro.

I enable VLC, test the installation and shows OK, still the embeded player launch for the videos.

Thanks

**Comment by parg** [comment]
Well it launches VLC inside the embedded player window - if you want stand-alone VLC then configure it as a 'launcher'

**Comment by eurobank** [comment]
This is what i mean. NO Vlc anywhere, Embedded or whatever.

**Comment by parg** [comment]
What are you expecting to see?

**Comment by eurobank** [comment]
I'm sorry but i don't follow. I download a video via biglybt. I press Play and i expect to see VLC launched to view. Instead i see the the other player.

**Comment by parg** [comment]
Like I said - VLC is used to render the video WITHIN THE EMBEDDED PLAYER FRAME - if you want to see VLC as a separate app then configure it as a launcher in Tools->Options->Interface->Tables: Launch Helpers

**Comment by eurobank** [comment]
Ok, what you actually say is that the engine of VLC is used but doesn't really show anywhere in the embedded player.

Thanks.

**Comment by parg** [comment]
Yup :)
