### ISSUE TITLE
Media :null has already been added - Torrent wont start

### ISSUE THREAD

**Issue by MrDemocracy** [BiglySoftware/BiglyBT#503]
I get this message when I try to a the torrent file:

> Media `:null` has already been added as '**(FILEHASH)**_3122.torrent'
> 
> Do you want to add additional trackers from the new download to the existing one?

I can't find this torrent in either the windows client or the web UI.
I think this happend beacuse I added the magnet and torrent file almoust simultaneously.
 
System:
Java 1.8.0_152 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4757, win32
Windows 10 v10.0, amd64 (64 bit)
B1.5.0.1_B14/4 az3

**Comment by parg** [comment]
Sounds like exactly right :) Just ignore it if you can

**Comment by parg** [comment]
or if you can't make sure you are in 'advanced list' view and delete the 'magnet download' before adding the torrent

**Comment by parg** [comment]
the library view has a 'simple' and 'advanced' list - there are toolbar buttons to switch. Magnet 'downloads' are hidden in the simple view
