### ISSUE TITLE
Health tooltip named color differs from actual color displayed

### ISSUE THREAD

**Issue by profile90** [BiglySoftware/BiglyBT#508]
![image](https://user-images.githubusercontent.com/15268286/42258579-b3e0c7ba-7f5c-11e8-95e1-6a470bac62b8.png)

I guess this is legacy from Vuze? The current icon is blue, but the tooltip text says it's yellow. Small, though noticeable especially for newbies.

(used the text from the wiki, as to not show any torrents)

**Comment by parg** [comment]
thanks!
