### ISSUE TITLE
Use BiglyBT as offsite Backup /Sync software

### ISSUE THREAD

**Issue by googlenews** [BiglySoftware/BiglyBT#51]
Hi I'm new here, Ive always wonder why users can't use BT apps to do private offsite backups and Syncing.
Please add this feature or make it possible to do this easily kinda link Resilio Sync software.

add to voting :)

Mac OS X v10.13, x86_64 (64 bit)
B1.0.0.0/4 az3

**Comment by parg** [comment]
You can achieve replication of content assigned to a Tag in BiglyBT by creating an RSS feed from the Tag (right-click option) and then either sharing that RSS feed directly with another client as a Subscription (setting auto-download on it), or indirectly by a decentralized chat channel (using the RSSToChat plugin) and then in the other client turning the chat back into a local RSS feed and subscribing to that. For example...

**Comment by hatewesterncivilization** [comment]
I'm so sorry, can anyone please give an explanation, how can I get latest beta versions? Isn't the only way to do the singly described compilation?

**Comment by parg** [comment]
Install BiglyBT from http://www.biglybt.com/ and then when it is running go to the Help menu in BiglyBT and select the 'Join Beta Program' option

**Comment by hatewesterncivilization** [comment]
Yes, thanks, successfully updated to last beta through internal client tools. 

But I'm still encountering serious problems with kind of deadlocking of client, good it's now happens much later with last beta. Maybe I should just increase heap memory amount settings, but I'm not quite able to do that, only 4 GB of RAM is all I have, 

With current settings overall system memory load percentage is >91% about. 

Looking forward for solution for this thing, thanks. I will give more testing for way out of this.

**Comment by googlenews** [comment]
Thanks Parg. You solution sounds good but I wish there was a more built and straightforward method. I’ll think and noodle your suggest some more.

**Comment by googlenews** [comment]
If I use the RSS and tag function to achieve remote backup, I would like pieces encrypted before sending. I also want to split the data between two or more computers whenever possible so all my archive/back up is not on a single computer excepto the original. Unlike regular torrents which works better if multiple copies exist. For security I guess, I don’t want this to be easily reconstructed except by owner.

**Comment by parg** [comment]
You'd be better off handling the crypto/splitting outside of BitTorrent - split the files, dump the bits into TrueCrypt volumes (or something) and then torrent them around backup sites.

**Comment by googlenews** [comment]
I guess I misspoke when I said split… I meant “pieces” as in the way the torrent bits are divided for seeding,  I do not want any 1 peer to have 100% of the file I’m backing up/off site archiving. Is There a way to limit each peer to only get 25% random pieces if I have 4 peers or have the software automatically determine what percentage each peer receives? 
Also, I’ve never used the friends feature, I was wondering if I can automatically upload/archive my files to my friends computer once it’s marked as “force seed” instead of doing all the RSS subscriptions thing. 

Anyone and everyone are free to reply with ideas to get to the seamless solution I seek, not only Parg. I think adding this functionality without the hoops with be very useful.

Perhaps where it says in the file menu, New Torrent. There should also be “New Torrent Archive” selection. Then all the above step will be automatically applied to the file, including tags, percentage limiters, force seed to friends. 

Just a suggestion/enhancement request. :)
