### ISSUE TITLE
Automatic update of BifglyBT removed all torrents and config

### ISSUE THREAD

**Issue by Gatak** [BiglySoftware/BiglyBT#516]
* OS and version
Windows 10
* BiglyBT Version Number
1.5.01_B16
* For *nix: Desktop Environment

BiglyBT wanted to update itself. I choose ok, but to restart later. When I reboot the computer all BiglyBT settings are gone, as well as all loaded torrents.

How to I revert this and get my old settings etc back?

I see there are several .bak and .bad and .bak.bad files in the settings folder. The "BiglyBT\active" contains many .dat and .dat.bak files - are they the torrents? Why are they not loaded?

**Comment by Gatak** [comment]
I found a backup-copy from yesterday. I removed BiglyBT from %appdata% and restored the backup. It all now works.

**Comment by parg** [comment]
Glad you fixed things up!
