### ISSUE TITLE
Problems Downloading Plugins

### ISSUE THREAD

**Issue by eurobank** [BiglySoftware/BiglyBT#518]
Many times trying to download a plugin, fail. 

Remains Forced and no sources or anything are found. Right now Vuzexcode plugin is waiting to be downloaded for more than an hour or so.

Is something wrong in my side or something else is happening ? I run the latest beta, Windows 10/64 Pro.

**Comment by Havokdan** [comment]
Do you use ipfilter? By disabling it for updates, downloads of the plugins occur normally.

**Comment by eurobank** [comment]
No ipfilters.
