### ISSUE TITLE
DATA LOSS : "Search For Existing Files" can delete discovered matches!

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#530]
Ahh, crap. I'd originally [discovered this bug in Vuze 5.7.5.1_B10](https://forum.vuze.com/Thread-BUG-Search-For-Existing-Files-deletes-matches-DATA-LOSS?pid=20550#pid20550), and I was hoping it wasn't also present in BiglyBT... but I just tested, and it totally is.

The "Search for Existing Files" tool in Link mode has a rather nasty side effect when run on torrents which are configured with only some files selected for download (in which case it sets the rest to Priority: Delete), which can cause it to _**delete**_ the original files which it matches to your torrent. 

The easiest way to explain is with a set of steps to reproduce.

### Prerequisites/Setup
1. You'll need a multi-file torrent, call it `guineapig`, for which you have 
   1. The `guineapig.torrent` file
   2. All of the files from the torrent, downloaded to a folder `guineapig/`
2. The `guineapig` torrent should **NOT** be loaded into BiglyBT currently
3. The `guineapig` folder should be somewhere outside of BiglyBT's default download directory

### Steps to reproduce
1. Make a _second_ copy of the `guineapig/` folder and all its contents, and put it in a different location from both the original `guineapig/` and the torrent download directory. I copied mine to `/var/tmp/guineapig`
1. Load `guineapig.torrent` into BiglyBT, and configure it as follows:
   1. Add Mode: STOPPED
   1. Save Location: Default
   1. (This is the important part:) Select **half** of the torrent's files, and click "Unmark" to **UNCHECK** the "Down?" column on that group of files
      So if it's a torrent with 10 files, the first 5 are checked, and 5 are unchecked.
1. Click OK to add the torrent to the Library in **Stopped** state
1. Right-click on the torrent and choose Advanced > Files > Search For Existing Data Files...
1. Set the Mode to Link, and the Explicit search location to `/var/tmp/guineapig/` (or wherever you stored the _copy_ of the torrent's data files)
1. Let the tool scan the directory.

What you'll see happen is that _every_ file in the torrent will be matched with its corresponding file in the directory (as you'd expect)... and so, for all the files you set _not_ to download, because they Priority "Delete" in the torrent, **BiglyBT will _respect_ that "Priority: Delete" setting and delete your original files.**

In a matter of moments, BiglyBT has just happily wiped out half of the (previously-)existing files for your torrent. (Or, in this case, only the sacrificial copy we made.)

Clearly, Search For Existing Data Files should reset the Priority on any file it matches to either Normal or Do Not Download, and it should most definitely _not_ ever delete any of the source files it matches simply as a consequence of matching them... no matter how the torrent is configured prior to the scan.

#### System Details
```
Java 1.8.0_172 (64 bit)
  Oracle Corporation
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.172-9.b11.fc28.x86_64/jre

SWT v4757, gtk/3.22.30
Linux v4.17.3-200.fc28.x86_64, amd64 (64 bit)
B1.5.0.1_B19/4 az3
```

**Comment by parg** [comment]
Good catch :( 

I think I'd prefer the solution to be for the 'delete' or 'do not download' files to be excluded from the matching process - it doesn't feel right to amend the priority that you have set for the files. 

A draw back of this would be that partial edge-pieces for matched files would be re-downloaded though.

Thoughts?

**Comment by ferdnyc** [comment]
Hmmm. I'm of two minds about that...

> I think I'd prefer the solution to be for the 'delete' or 'do not download' files to be excluded from the matching process - it doesn't feel right to amend the priority that you have set for the files.

And I do see your point, if the user disabled the files then their expectation may be that those files will not be shared to the swarm by them, and just because they have copies stored locally shouldn't make any difference in whether that expectation is met. It's definitely safest to exclude them.

But at the same time... because some of the controls and actions here are a bit overloaded, it's hard not to end up with multiple interpretations of their meaning. For starters, a negative answer to the question "should I download this?" _doesn't_ really mean "Delete" — so I'd argue that in the "unchecked the files in the Open Torrent dialog" scenario, the user never really _set_ the Delete priority to begin with. They simply chose not to download them. That those files end up set to Delete instead of Do Not Download is, in a sense, a minor priority... "escalation", I guess?

And by the same token, if we take another step back, "Do Not Download" (DNDL) doesn't _really_ mean "Do Not **Upload**", so the fact that files are set to DNDL doesn't necessarily have to mean they shouldn't be shared to the swarm, only that their pieces shouldn't be requested. (In fact, when you *manually* reconnect a torrent with its piece data by dropping files into the download directory and hitting "Force Recheck", any DNDL files which contain data will still be scanned, and if any complete pieces are found within the DNDL files those pieces will be advertised to the swarm. So, the manual equivalent of "Search For Existing Files" already does allow restoration of piece data for files set DNDL.

#### Feel free to ignore everything up to this point
...Ugh, I didn't mean for this to get so long and convoluted. Long and short: I agree, the safest approach is to exclude the files. I just wanted to note the slight inconsistency, since there are other places where a more liberal interpretation of the Priority flag is used... but that alone isn't an argument against being more conservative here, since this process is far more automated and therefore warrants extra caution.

Oh, and I do still feel that conflating "Do not Download" and "Delete" — something BiglyBT has done in various different scenarios going all the way back to the Azureus days — can make it much more difficult to divine the user's wishes and make intelligent decisions about their file data. DNDL _feels_ like it should mean something very different from "Delete", when set as the Priority on a file, and making that distinction could be useful at various times (this being one). But because files will be automatically flipped from one to the other, any possible distinction gets lost and they end up having to be treated as synonyms.

**Comment by parg** [comment]
The reason we have the DND/Delete inconsistencies is somewhat historical. Initially there was only DND implemented simply by not downloading the pieces contained entirely within DND files (or spanning purely  DND files). However, with some file-system allocation schemes, this lead to DND files actually being allocated to their full size (due to their last piece overlapping with a non-DND file). So 'compact' storage was introduced to use minimal disk space to store these partial pieces. In theory these partial chunks could have been stored somewhere invisible to the user (to stop those moaning about 'how come I deselected these files but they still appear to be being downloaded) but the issue with this is that to seed/backup the files into a state that allows recovery it is necessary to store the partial pieces. Also if the partial pieces were stored separately and that location ran out of space....

Anyway, the priority of 'delete' was introduced to represent 'DND + compact storage' mode and when a user deselects a file in the open-torrent-dialog then this is the resulting priority.

Later the 're-order-pieces' disk access mode was created - this pretty much does that 'compact' storage does, 

I'll implement things to skip DND/Delete files when searching for excisting.

**Comment by ferdnyc** [comment]
And indeed, I  recreated my test with _B20 and, using the same 74-file torrent I tested with last time:
```
    Matched=34, complete=0, ignored as not selected for download=40, no candidates=0, remaining=0 (total=74)
7/17/18 9:35 PM: Complete, downloads updated=1
```
No data was deleted, though as you indicated the last enabled file at the "border" of the DNDL area shows 94.2% complete. Which is to be expected as its final block is shared with one of the disabled files and would need to be re-downloaded and checksummed before displaying 100% complete (even though in reality the file already is). I split up the enabled and disabled files based on their `file_index` order within the torrent, so for the purposes of my test there was only one such block. :+1: 

> The reason we have the DND/Delete inconsistencies is somewhat historical.

That's an understatement, like I said it's one of the things I remember (in at least some form) going all the way back to when the program was actually still _called_ Azureus! :laughing: 

Thanks for all the background, though. It's actually really interesting, and laid out end-to-end like that it's a lot easier to understand how and why things evolved to where they're at today.
