### ISSUE TITLE
CSS Theme support

### ISSUE THREAD

**Issue by v-dawg** [BiglySoftware/BiglyBT#54]
.

**Comment by TuxPaper** [comment]
Theme's have always been on the back of our minds.  A lof of the pieces are there, but need a lot more work to make it easy.  We have property lists for icons, colors, and a good portion of the screens and dialogs.  Converting these to a more friendly CSS/HTML/XML style would be the ultimate goal, but is also very time consuming.

Thanks for filing the issue.  We'll keep it here as an enhancement for people to vote on :)

**Comment by hatewesterncivilization** [comment]
I'm in for that, users who want themes support must easily get it, a fortiori, it's been a long, long time Azureus been without of this. 

Many thanks for the gracious offering!
