### ISSUE TITLE
Rename Download (top folder name) while opening torrent / magnet link

### ISSUE THREAD

**Issue by Sachielizumo** [BiglySoftware/BiglyBT#541]
An issue started from Vuze that there is no way to rename the download while starting a new download from a torrent and magnet link. I can only rename the file name within the folder instead of the top folder name if the download file contains a lot of sub-folders and files. The only way to rename the new download is to move to the organize tab and chose rename download and this is quite annoying.

**Comment by parg** [comment]
Azure? Right-click in the Files view in the open-torrent-options dialog

**Comment by Sachielizumo** [comment]
I think BiglyBt is based on Azure and has the same issue, you can't rename the TOP FOLDER name while in the open-torrent-options dialog, but you can rename its file names separately, ie: the download folder name is "Top Folder" and contain "Sub 1" and "Sub 2" subfolder, each sub-folder contain file 1 2 3 4. In the open-torrent-options dialog, you can rename file name of file 1 2 3 4, but you cant rename the name of "Top Folder" and "Sub 1" and "Sub 2". The only way to rename them is to use the rename function in organize tab when right click the downloading job. It is sad that this renaming function is quite annoying and Bitcoment makes this far better than Azure and BiglyBT.

**Comment by parg** [comment]
But you can - like I said, right-click on a file in the Files area and select from the menu:

![image](https://user-images.githubusercontent.com/395293/43035265-94df1bb0-8ce4-11e8-89ef-93d7c0473781.png)

**Comment by Sachielizumo** [comment]
Thanks parg, 
but seems that the rename of the Top level folder name is the list shall not equal to the case. This Top Level Folder name is the name of my default directory, like "Downloads" in your case, where you could change where not saving in "Downloads" but other paths. If the torrent or magnet link contains a lot of folder and files which the top folder name, ie "Main Folder", your saving path shall be C:\Downloads\Main Folder,  you could use the change Top Level Folder Name function to change the path into other like C:\Testing\Main Folder, however, you can't change the name of "Main Folder" in this case. You can only change it through the Rename in Organize tab when right click the downloading job.

**Comment by parg** [comment]
Sounds like you simply want to change the save-path?

![image](https://user-images.githubusercontent.com/395293/43037838-0b38019e-8d0a-11e8-92b4-be8ab7191308.png)

Or am I missing something?

**Comment by Sachielizumo** [comment]
A little bit confused, but I don't want to change the save path. I just want to have a fixed save path every time but change the folder name separately. In your case, the save path (Default) is C:\Downloads, and the torrent name (folder name) is 5750, therefore all your files shall save at the location C:\Downloads\5750. However, is there any way to change the folder name "5750" is this dialog?
The only way I could use is to make it through Organize tab and rename the whole folder.

**Comment by Sachielizumo** [comment]
You shall find that I could change the folder name with a fixed default directory while using Bitcoment
![image](https://user-images.githubusercontent.com/41503899/43038253-957a549a-8d48-11e8-9931-597a7dfbc806.png)

**Comment by parg** [comment]
Well if I right-click on the File view, select 'Change Top Level Folder Name', browse to C:\Downloads\Trout  (I created that folder in the browse dialog) I end up with things being saved in 

C:\Download\Trout

instead of

C:\Downloads\5750

![image](https://user-images.githubusercontent.com/395293/43038437-72268564-8d10-11e8-8b66-eb2fe76d643d.png)

**Comment by Sachielizumo** [comment]
Thanks parg,
then I think the words "rename" here is quite misleading as I am totally changing the whole path by creating a new subfolder under my default directory all manually instead of the programme and this is quite stupid indeed.
Why can't the programme make this a little bit simple like what BitComet did? You can change the subfolder name in the dialog and the programme create it automatically for you.

**Comment by parg** [comment]
Well really the only difference is that you have to create the folder instead of typing its name into text box. I hear what you're saying though

**Comment by Sachielizumo** [comment]
Thanks parg, hopefully there is a mod or integrated function for this issue in the future update, which could save us lot of time.

**Comment by Xemnarth** [comment]
Is there a fix in the works for this issue?

**Comment by TuxPaper** [comment]
I think the subfolder thing added next to the download dir was the fix for this.  Closing! :)
