### ISSUE TITLE
request forbidding Passkey on DHT

### ISSUE THREAD

**Issue by ViperCode7** [BiglySoftware/BiglyBT#543]
Hi

There are some trackers which impose a ratio but also have crappy speeds for tracker only sources so they enable DHT and non-private torrents with passkey.

Would it be possible or is there already a way to either configure DHT to not share the torrent I have, which also includes the passkey when someone asks for it via DHT, thereby preventing the leaking of the passkey. The problem is that the tracker doesn't supply all the peers, I assume for anti-snooping reasons and it's tough to get a recent ratio that way since I mostly get seeds, but not new peers. Right now I'm doing 10KB/s upload when usually it's something like 100-500 KB/s.

Or a better idea if the tracker has a passkey embedded in the URL, the DHT should strip the torrent of the announce URL and supply it without the passkey... just an idea.

**Comment by parg** [comment]
Why not just grab the torrent, remove the private tracker's URL from it (edit the torrent sources) and then just download it for free? The amount of effort that has been put into supporting private tracker sites and their private torrents makes the fact that they don't actually set their torrents as private ridiculous.

**Comment by ViperCode7** [comment]
I know it's ridiculous, but the issue is something else. I want to contribute to the community, i.e. upload at least 1:1, and I'm not doing it for for the admins, it's for the peers who put an effort into sharing. Thus I require to announce to the tracker my passkey so that the ratio is properly set and not get my IP banned, which is static, but at the same time I don't want to leak the passkey via DHT. The solution for them is to use old clients like utorrent pre 2.0, even more ridiculous is that they've put ALL azureus core clients in the ... aham... "high security vulnerability" list. "the use of clients is strongly discouraged".

I was just curious if it's possible as an option to deny uploading of torrents on DHT requests, pretty much like we have the option to selectively disable peer sources. I think this should pretty much be enough to make them shut them up.

**Comment by parg** [comment]
Well metadata torrent transfers don't actually include tracker details, it is just the 'info' portion of the torrent that is sent.

I could add an option to deny the original Vuze DHT torrent transfer (which only works between Azureus/Vuze/BiglyBT clients) I guess

**Comment by ViperCode7** [comment]
Maybe I'm not understanding decentralized tracking but isn't DHT a gateway to full torrent file exchanges? A part of the whole.

I know DHT, as a lookup table service, broadcasts the infohash of the torrent, which is also a part of the magnet URI, and receives infohash broadcasts from "nearby" users.

But once that is done, and there's a rogue user on the decentralized network who did not add his torrent via file download from the tracker, but got just the info hash, made himself an URI and started to fish the decentralised network for clients with DHT enabled, once DHT found a matching peer for the infohash in question, wouldn't that victim peer offer him the torrent file with the tracker and his passkey? Or the torrent gets stripped of all data but the piece hashes and file names?

The admin in question goes on about tracker exchange. Is that swarm discoveries in BiglyBT?

**Comment by parg** [comment]
See http://www.bittorrent.org/beps/bep_0009.html for the 'mainline' approach to obtaining torrents from other peers. Note the "This extension only transfers the info-dictionary part of the .torrent file." - the 'info-dictionary' does NOT include the torrent's tracker list and therefore does NOT include passkeys in tracker URLs.

My reference to the Azureus/Vuze/BiglyBT approach to obtaining torrents from other peers is separate from this and does transfer the entire torrent (but of course not for private torrents). Note that BiglyBT supports both approaches.

Hence my offer to add an option to BiglyBT to prevent the non-mainline torrent transfer from being permitted - you would need to enable this option to prevent the possibility of other Azureus/Vuze/BiglyBT peers from obtaining the public torrent from you.

**Comment by ViperCode7** [comment]
Yes, that sounds in order. What about "tracker exchange". Is that a thing in BiglyBT?

**Comment by parg** [comment]
Nope :)

**Comment by ViperCode7** [comment]
Alright, thanks again!

**Comment by parg** [comment]
Option will be in the next beta or release

**Comment by tvasenin** [comment]
@parg thanks for implementing this option -- it finally enables users of few major Russian trackers to use BiglyBT :)

Still, need a few clarifications though.

I don't want the passkeys to ever get leaked for non-private torrents with trackers containing passkeys in the following form:
http://tracker1.example.net/ann?pk=0123456789abcdef0123456789abcdef (32-char lowercase hexadecimal)
http://tracker2.example.net/ann?uk=FooBar2019 (10-char case-sensitive [a-zA-Z0-9] format)

Could you pls confirm, that, for both passkey formats, in order to completely prevent passkey leaking:
- In BiglyBT 1.6.0.0 and above I just need to disable torrent transfer between DDB peers.
- In BiglyBT 1.5.0.0 and below I have to disable whole DDB plugin.
- For Azureus/Vuse, DDB-disabling workaround is also enough.

Basically, I need to understand if there are any other ways to leak passkeys, other then one you've addressed with the new DDB plugin option.

**Comment by parg** [comment]
AFAIK there are no other ways of leaking passkeys within BiglyBT - the only way a public torrent's tracker URL (including a passkey) could be passed to another client was via an Azureus/Vuze/BiglyBT magnet transfer request and the option I added prevents this.

It has always been prevented for private torrents.
