### ISSUE TITLE
Sidebar item close icons don't align because of variable counter widths

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#544]
It's a pretty minor thing, but since the next release is looming I figured I'd throw it out there:

### Sidebar entry close icons
For items below the Library in the sidebar (either tag views, or torrent detail views), each row's close icon doesn't align with any of the others, because their placement is dependent on the width of the counter item (torrent count for tags, completion percentage for torrent details) they're placed next to, which can vary quite a bit. As a result, you end up with a column of scattered close icons like this (enlarged to 200% size for visibility):

![screenshot from 2018-07-21 15-26-36](https://user-images.githubusercontent.com/538020/43039525-137358ac-8cfd-11e8-8f69-1990584d37cf.png)

Because they're literally the only clickable element in the entire row, I think it would be more ergonomic and user-friendly if the close icons were in a consistent place on every item. Whether it's swapping them with the counts (so the close icons are to the right), or moving one item (either the close icons or the counts) over to the other side entirely, and floating them left...).

#### Digression: Tag color placement
Actually, TBH I've long thought that the tag colors, at least (if not torrent counts) should make use of the tag icon. Rather than every tag having the same green icon, and then also having a colored bullet next to it. I'd originally imagined something perhaps like this (again, same 200% scale):

![biglybt-tagcountmockup](https://user-images.githubusercontent.com/538020/43039602-abdc1b96-8cfe-11e8-8d2a-8dc66048c0d3.png)

Though I guess now that tags have customizable icons, this isn't really viable anymore.

### Back to the real point
Still, leaving that aside, if the close icons could be placed so they all line up at a consistent horizontal location within the sidebar, for both Tag and Torrent Details lines, it would make finding and clicking them a lot more convenient.

**Comment by parg** [comment]
Not sure I like the gap we get for non-closeable items if we put the x on the right:

![image](https://user-images.githubusercontent.com/395293/43077856-8f1f3546-8e80-11e8-8bd9-c4e5226db729.png)

**Comment by ferdnyc** [comment]
What if the item-counts were floated left instead of right, and just came after the label with a space or two between them? No real reason _they_ need to be aligned, is there?

If there's nothing immediately to its left, the gap is no longer a gap, it's just a row without a close icon.

**Comment by parg** [comment]
I've added an option to B25 to allow the icon position to be selected:

To left of indicator (default, as before)
On right (as above)
Never (close icon not shown at all, right-click menu option added)

Hopefully that'll keep people happy

**Comment by ferdnyc** [comment]
(You're going to _hate_ me :angel: )

I tried out the option in _B25, and it works nicely. My only issue... 

![screenshot from 2018-07-24 07-38-02](https://user-images.githubusercontent.com/538020/43135902-0dd0a548-8f15-11e8-883b-81c9f4e0b36d.png)

It feels a little 'tight'. On both sides. More than in your screenshot, even, on the right. I don't know if that's just because my sidebar doesn't scroll, maybe? Regardless, the close icons are a bit hard to target. Like maybe 4px of "breathing room" on either side and I promise I'll be happy forever. (Until the next thing.) :wink:

**Comment by ferdnyc** [comment]
Come to think of it, what is that _chasm_ to the left of the icons even for? Does anything ever appear there? 

I know the items are grouped below the section headers, but even the I'd expect them to be indented only the width of the twisties, so the left edge of the icons aligns with the left edge of "My" or "BiglyBT" in the section headings. But the sub-items are indented like **three times** as far as that.

I'm just curious why it seems like everything is huddled over to the right side of the sidebar, when there's all that space to the left that _seems_ completely unused. (Unless it is used for something that I'm just not remembering / aware of, in which case never mind.)

**Comment by parg** [comment]
You're suffering from being on Linux it would appear...

**Comment by ferdnyc** [comment]
It only feels like _suffering_ on the bad days. Which is most of them.

**Comment by parg** [comment]
heh - the sidebar is somewhat unloved I'm afraid - there was the GTK2 -> GTK3 transition (that wasn't nice) and then there are DPI issues. Unfortunately I'm not really up on that side of things :(

**Comment by ferdnyc** [comment]
> there was the GTK2 -> GTK3 transition (that wasn't nice)

You'll no doubt be happy to hear that GTK4 is due... I think they're hoping by the end of the year, maybe? "Soon", anyway, at least on a glacial timescale.

**Comment by TuxPaper** [comment]
We should be able to tweak the font size somehow (the SWT library doesn't have a robust way of requesting specific sizes of a font), but there's a good chance that the indenting is part of the theme choice and we don't have a clean way to paint outside the bounds.

**Comment by parg** [comment]
How does the sidebar look with B27?

**Comment by ferdnyc** [comment]
> How does the sidebar look with B27?

Um, the font's bigger? Which is cool. Only difference I can see, though.

![screenshot from 2018-07-26 14-45-21](https://user-images.githubusercontent.com/538020/43281937-ea631a44-90e2-11e8-9a20-da3c2e0a6f08.png)

**Comment by parg** [comment]
That was it, thanks :)

**Comment by ferdnyc** [comment]
The addition of the preference **Options > Interface > Display > Side Bar > Close icon display location** satisfies this one as far as I'm concerned, closing.
