### ISSUE TITLE
Allow Folder Modification When Saving

### ISSUE THREAD

**Issue by chiefstank** [BiglySoftware/BiglyBT#55]
If the torrent that's being added is a folder of file, we should be able to rename the parent directory the files are being placed in. This is NOT the same as the download folder. The torrent has a name set and this is added a sub-folder of the destination directory and the files are downloaded to this name directory. Please allow modification of this name directory that is created.

**Comment by parg** [comment]
You can right-click in the 'files' area of the options dialog you get when adding a torrent and select

'change top level folder name'
