### ISSUE TITLE
add support for Fopnu "magnet:" (fopnu:) and fopnu decentralized tracker

### ISSUE THREAD

**Issue by KonoromiHimaries** [BiglySoftware/BiglyBT#550]
https://www.fopnu.com/

**Comment by parg** [comment]
AFAIK Fopnu is an entirely different P2P network - it doesn't use torrents for example. So supporting 'fopnu:' would require implementing the entire Fopnu P2P protocol in BiglyBT.

If someone wants to go and write a Java-based Fopnu client then please do so!

**Comment by ferdnyc** [comment]
Doesn't appear that's possible, [according to this post](https://forum.fopnu.com/offtopic/16) (on _their_ forum, though it's not an official statement) the protocol is proprietary and the client is not open-source.

**Comment by ferdnyc** [comment]
Apparently the open-source "debate" [raged on quite a bit](https://forum.fopnu.com/support/32?p=1) on that forum a year ago, absent any participation from the actual developers of Fopnu. But it doesn't sound like they've signaled any interest in opening up the protocol/network to other clients or implementations.

**Comment by parg** [comment]
Thanks for looking into it in detail!
