### ISSUE TITLE
Wrong tags applied to downloads from radarr

### ISSUE THREAD

**Issue by droopanu** [BiglySoftware/BiglyBT#552]
Java 1.8.0_162 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4757, win32
Windows 10 v10.0, amd64 (64 bit)
B1.5.0.1_B25/4 az3

I'm using radarr to send downloads to BiglyBT 1.5.0.1_B25 using the web remote protocol.
From time to time the downloads are marked with a tag automatically. I do not want any tags on these download.

Is there a way to figure out how/why these tags are applied automatically?

See an example of a download command below:
-> {  "method": "torrent-add",  "arguments": {    "filename": "magnet:?xt=urn:btih:44bf03ebbc9f584510a116852dcdc78c793aa909&dn=The.AAAAA&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710&tr=udp%3A%2F%2F9.rarbg.to%3A2710&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce",    "download-dir": "Y:\\Radarr"  }}
<- 179

**Comment by droopanu** [comment]
Nevermind .... It looks like a bug in ScaneRSS plugin. 
Looks like ScaneRSS matches the manually added torrent and applies the tags... argh!!!

17:08:40] Found manually added Download checking filters: AAAAA (2017) 1080p BBBB HDRip x264 AC3 by JJJ
[17:08:40] Item: AAAAA (2017) 1080p BBBB HDRip x264 AC3 by JJJ passed Filter HD checking HashDownloadHistory now.
[17:08:40] Item: AAAAA (2017) 1080p BBBB HDRip x264 AC3 by JJJ passed HashDownloadHistory and is added to the Download.
[17:08:40] Filter matched: HD
[17:08:40] Adding tag : TV

**Comment by parg** [comment]
Not sure it is a 'bug' as from the logging ScaneRSS is designed to be able to handle manually added torrents. However I can add an option to exclude them from being tagged if that would help.

**Comment by droopanu** [comment]
That would be perfect, thank you.

**Comment by parg** [comment]
already released!

**Comment by droopanu** [comment]
Magic :)

Thank you very much!
