### ISSUE TITLE
Is there a way to add a download path via the console?

### ISSUE THREAD

**Issue by SearchAndDestroy** [BiglySoftware/BiglyBT#553]
I would like to be able to add torrents via the console but specify a root path where to download it.
e.g.
BiglyBT-console.exe --path C:\Temp\Linux SomeLinuxDistro.torrent

Thanks

**Comment by parg** [comment]
You can specify download location in the 'open-torrent-options' dialog. If you are not seeing this then go to Tools->Options->Files and set 'When opening a torrent, show options dialog' to 'every time'

**Comment by parg** [comment]
The latest beta (B26) has a new --savepath <path> parameter - please test!

**Comment by SearchAndDestroy** [comment]
It looks like it's working even with folders with spaces. I tested by directly using biglybt-console and I will test with my application but it should work.
Also I am getting these warnings:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.biglybt.core.util.spi.AENameServiceJava9 (file:/C:/Program%20Files/BiglyBT/BiglyBT.jar) to field java.net.InetAddress.impl
WARNING: Please consider reporting this to the maintainers of com.biglybt.core.util.spi.AENameServiceJava9
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by parg** [comment]
Great.

Those warnings are related to

https://bugs.openjdk.java.net/browse/JDK-8201428

**Comment by SearchAndDestroy** [comment]
I tested it further and it's working great.
Just one more question: I am using uTorrent now and when I specify a folder to save to it replaces the top folder, is it possible with BiglyBT?
e.g. the torrent file contains:
```
TopFolder\SubDir1\Files001.txt
TopFolder\SubDir1\Files001.txt
TopFolder\SubDir1\Files001.txt

**Comment by parg** [comment]
You can do it when adding via the UI but not by the command line. Is it that much of an issue?

**Comment by SearchAndDestroy** [comment]
Yes it is if I am adding the torrent to seed, otherwise it's not a big problem.
Also I need to check if a torrent has peers and remove it if it's been a certain time (like 7 days) without any peers but I suppose it can be done via a plugin.
I will be using the command line to add/remove and check since it's automated and I am getting the torrents file via another program.

**Comment by parg** [comment]
BiglyBT maintains an 'up idle' statistic - the amount of time elapsed since the torrent last uploaded data to a peer. If this was made into a Tag Constraint variable you could combine this with the existing age/completed_age variables along with a max-tag-entries policy to automatically delete downloads that have not uploaded for a given time
