### ISSUE TITLE
Remove failed/selected trackers from bulk selected torrents

### ISSUE THREAD

**Issue by belico1976** [BiglySoftware/BiglyBT#557]
I would like the ability to remove specific 'sources tab' trackers from a group of selected torrents
and/or
the ability to remove them from the tracker status query queue completely, or just stop them temporarily from being retried

eg
 failed/dead/offline

**Comment by parg** [comment]
Use Tags and removal templates - https://github.com/BiglySoftware/BiglyBT/wiki/Tags#Examples

**Comment by parg** [comment]
Assuming all good.
