### ISSUE TITLE
UI Not updating when large amount of torrents exist

### ISSUE THREAD

**Issue by jaymzjulian** [BiglySoftware/BiglyBT#560]
Version: 16.0.0.0
OS: Debian Linux
Java: OpenJDK 64-Bit Server VM (build 9.0.4+12-Debian-4, mixed mode)
Extra Java Parameters: -Xmx20g (visualvm shows 15gig heap used - does not seemt to be in GC hell!)

To be fair, there is around 40,000 torrents currently in the download queue (and around 140,000 in the downloaded), although only 928 are in the queued/downloading state (the rest are stopped).  Previously, the system has basically worked even when a large percentage of those were active.

I _am_ using tags pretty heavily, and particularly using a constraint based on names, and a javascript execution to push one tag to the top (javascript('download.setPosition(1);').  I have also used tags to push all torrents in this tag (which is the aforementioned 928) into the started state (otherwise torrents come in stopped, for now, which I work through this issue)

The java process is spinning all four CPUs, which to be honest is also surprising given the configuration - i'd expect the entire system to be network bound, but I'll accept that as the way things are(tm) if it is the way things are(tm) (System is 32gig ram, i3-4130 @ 3.4Ghz x 4)

(For flavour: Additional torrents are fed to the system via a script by calling the commandline.  The behaviour persists if this is turned off, however)

One thing of note - I am getting logs like: read took 67915 for can/link=/[omitted],raf=java.io.RandomAccessFile@28c4c8f4,acc=1,ctrl = type=1,acc=linear

although iostat -kx 2 indicates not much in the way IO load (my first thought was maybe IO is screwed, given the above warnings)

If I start with downloads.config moved out of the way, things do change a little - but the UI is still weirdly unresponsive, but at least then I can get into options to check it.  Options of note:

* Open files was set to 1024.  I'm trying increasing this to see if it helps.... originally it was reduced to save memory
* disk cache is set to 16meg
* Max connections is set to 3000, though we're not hitting anywhere near that.  I'm still include to reduce this to 300 for my next test run, but since current used was only 70.... i doubt that's the issue?

I'm unsure where to proceed from here to debug this :(.

**Comment by parg** [comment]
If you take a look in the 'logs' directrory (~/.biglybt/logs perhaps?) there will be two (rotating) log files called Thread_1.log and Thread_2.log. These capture details of the most active thread and memory usage - perhaps you could paste some of the lines into this issue?

**Comment by jaymzjulian** [comment]
Oddly, though I have debug log files, the thread logs have nothing in them at all - I assume I must have disabled those somehow, though it could just be related...   That said, some more investigation with htop showed that all of that CPU time is actually going into ParGC threads, so it looks like the JVM is at least part of the culprit here.   (That said, if i can get into options at some point - usually I have to move the downloads.config to do this right now - maybe I can re-enable that).  I'm going to try switching off all GC params, which should switch it to G1GC on this JVM i think, and see if that helps with that... I'm wondering if i managed to bundle a JVM upgrade into the update without thinking, which could be a thing that made this worse.  Beyond that, I've also set up stdout logging so once it fully restarts (it takes about 2-3 hours to start up, which is unsurprising given how much crap it has to load - downloads.config is over 100 meg alone), i should be able to generate some heap dumps and such like via visualvm.

I did make it somewhat better by turning off the execute-on-assign start/no-force-start on the tags - though I'm pretty convinced at this point that's symptom not cause.

**Comment by jaymzjulian** [comment]
Update on that: I did manage to get the UI somewhat responsive by doing a couple of things:

1) Updated to openjdk 10
2) Removed heap parameters that i'd previously set, reverting to G1GC
3) de-prioritizing the GC threads with the following script:

        for j in $(ps -eL|grep GC|awk '{print $2}'); do renice -n 10 $j; done
        for j in $(ps -eL|grep G1|awk '{print $2}'); do renice -n 10 $j; done

Of course, using G1GC is causing higher general heap usage than parallelgc - parallelgc was around 18gig average, G1GC is actually ooming after a couple of hours at 25gig.  Note I have not tried the GC de-prio with parallelGC, which may help.  (Being only a 32gig box, I don't want to push heap _much_ higher than that, though I'll try with 30gig).  

I'm going to investigate heap dumps of this running configuration next, since I _suspect_ that there is something doing a lot of objects-per-torrent that is causing GC to be painful - is there anything known to be suspect in this regard?  (I do have a couple of plugins - particularly, mainline dht, which I've heard can cause this)

**Comment by jaymzjulian** [comment]
Thanks - I'll work more on getting the thread log and heap today, with the tag thing if it's relevant my tag constraint is actually quite long - it looks like:

!isComplete() && (contains(name, "x") || contains(name, "y") || contains(name, "z") || ...)

the actual constraint is 4070 chars long (obviously redacted).  I have wondered if actually a javascript constraint instead might be more efficient for this, though I'd assumed that javascript is always worse.  This _would_ track with having turned off marking state with constraints having improved things, too!

Interestingly, my experience has not generally been low memory usage with inactive torrents - 16gig+ heaps in order to function were my normal well before we started using tags - my current thinking, though, is that they could be churning lots of small objects, causing GC hell, of course.

**Comment by parg** [comment]
For the constraint you could try a single 'matches' call with a regular expression instead of separate 'contains'. Apart from reducing the number of separate 'contains' evaluations the 'matches' result is cached per download to avoid re-evaluation.

**Comment by jaymzjulian** [comment]
I did turn off tag constraints entirly for now, to ensure I could reproruce without them/.

First pass - this is from about an hour and a half run time, after which the JVM sadly crashed - this actually hasn't happened before!    In any case, I'll try and generate a longer run as well

[thread_1.log](https://github.com/BiglySoftware/BiglyBT/files/2264575/thread_1.log)
[thread_2.log](https://github.com/BiglySoftware/BiglyBT/files/2264577/thread_2.log)

**Comment by jaymzjulian** [comment]
Update #2: with more heap (25gig), and the tag constraints re-set, the UI works again!  Huzzah!  It's still requiring 25gig of heap, but it does seem the tag constraints processing _was_ throwing a lot of things off.  I'm happy to do more investigation as to why the heap is so huge if you're interested in that, otherwise i'd also be happy to close this if you're not!  (I understand i'm well otuside the normal user ;)).  Thanks.

**Comment by jaymzjulian** [comment]
Update #3: It did end up locking up again after a while, attached thread logs!
[thread_1.log](https://github.com/BiglySoftware/BiglyBT/files/2264928/thread_1.log)
[thread_2.log](https://github.com/BiglySoftware/BiglyBT/files/2264931/thread_2.log)

**Comment by parg** [comment]
Thing did seem to quieten down until the free heap space started getting small - it would be good to know if there was a memory leak somewhere or just if the GC can't keep up with the object allocation rate...

**Comment by jaymzjulian** [comment]
Interestingly, the biggest user is com.biglybt.core.disk.impl.DiskManagerPieceImpl, at 6gig/94 million objects.  Surprising ones though, are 69 million java.util.LinkedList$Node entries totaling around 6gig.

I threw a copy of the heap dump at https://artificial-stupidity.net/html/heapdump.hprof.gz .

**Comment by parg** [comment]
Hmm, DiskManager (piece) objects are supposed to only be allocated for active (downloading or seeding) torrents - then again you do have rather a lot in this state so I guess that could add up.

**Comment by parg** [comment]
B03 has a couple of changes that might speed up the initial load time of BiglyBT with a large library

**Comment by jaymzjulian** [comment]
I'll give B03 a shot.  What's interesting, is i saw the diskmanager objects while most torrents were in initializing.  I actually tried turning off disk cache, which did allow the session to last longer - it's now throwing oom after 8-10 hours, up from around 2-3 hours.   Sadly the JVM wouldn't let me heapdump at that point, because it ironically ran out of ram to generate the dump.  (That's with parallelgc again - G1GC seems to die faster, which kinda makes sense in truth)

**Comment by jaymzjulian** [comment]
My other thought was (and i'm happy to be told "that's not useful, dude!") - does there exist a pre-canned script to "sanitize" downloads.config?  (I can write one otherwise, since I've already got scripts that parse the format to clean up stuff on my disk)  I'm wondering if it would be worth uploading a sanitized version of this, since it might be easier to reproduce the memory leakage that way than attempting to wrangle (and/or sanitize) a 30+gig heapdump...

**Comment by jaymzjulian** [comment]
Confirming B03 hit UI in under 15 minutes, down from 2 hours.  Thanks!

**Comment by parg** [comment]
Nice! To reproduce things the best approach would be for me to auto-generate 100,000 dummy torrents etc but I would need to actually have them running which would challenge my somewhat limited storage :( I'm going to be away for a few days - I'll see if I can find some time when I'm back. cheers!

**Comment by jaymzjulian** [comment]
Update: B03 was actually generally better for a little while, although it's completly locked up now with DEBUG::Fri Aug 10 10:31:21 AEST 2018::com.biglybt.pifimpl.local.download.DownloadManagerImpl::addListener::920:
  java.lang.NullPointerException being the last log.  (thread_*.log haven't been updated since that time either, though I have attached them just in case)

Interestingly, GC _is_ working, and is cycling between 16 and 20gig, so objects are being both allocated and killed, so not everything is spiders!  Also curl of tags works instantly, so that's something.  However, there is no network traffic and/or attempts at opening connections.  Given that, I'm going to restart the whole thing, 


![image](https://user-images.githubusercontent.com/787351/43944739-c9f84a42-9c34-11e8-8c9f-2e689cade19c.png)

[thread_1.log](https://github.com/BiglySoftware/BiglyBT/files/2276979/thread_1.log)
[thread_2.log](https://github.com/BiglySoftware/BiglyBT/files/2276980/thread_2.log)

**Comment by jaymzjulian** [comment]
Enjoy your time away - I really do appreciate the assistance!  I feel like sparse files would be the right approach for that - i imagine a bunch of torrents of zeros with a few random bytes interspersed would go okay.  the active folder is only about 16gig, which becomes more doable.

**Comment by kwloafman** [comment]
I'm getting lockups too, and I have only about 1,500 torrents to deal
with.  B03 does seem to start faster.

...Thanks,
...Ken

Java 1.8.0_171 (64 bit)
  Oracle Corporation
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home

SWT v4528, cocoa
Mac OS X v10.13.6, x86_64 (64 bit)
B1.6.0.1_B03/4 az3

**Comment by jaymzjulian** [comment]
Interestingly, I got out of GC hell - it seems queued but not active torrents take a lot of ram, and I accidentally ended up with a bunch of these - running stopall bought the heap back down to a "reasonable" 10-12gig, however bought us all the way back around to our original issue of the UI not updating - the window pane gets redrawn (eventually), but screens like options and tags overview are just a blank square.  I've attached a new threaddump for this run, since it's finally a useufl run where things are downloading/not dying for "other" reasons

[thread_1.log](https://github.com/BiglySoftware/BiglyBT/files/2279903/thread_1.log)
[thread_2.log](https://github.com/BiglySoftware/BiglyBT/files/2279904/thread_2.log)

(This is on -B02, of course, since B03 just hangs)

**Comment by jaymzjulian** [comment]
Additional clues:  Turning off scraping in options actually seemed to significantly reduce the bottom out point, and make the whole thing way more stable - as you can see in this screenshot, the bottomout point is now 8gig of heap rather than about double that before - it's still generating objects to build up to 26gig at a pretty rapid rate, but this is definitely the best its been so far - in all honestly, an 8gig base rate would be _fine_, if we can work out what's generating constant objects (seems to be around 5gig/minute or so!)


![image](https://user-images.githubusercontent.com/787351/43997763-d33fc95c-9d99-11e8-8a13-976875df348e.png)

**Comment by jaymzjulian** [comment]
I tried the SJK tool to attempt to find the dead objectss, and actually got an interesting - reproducable - result.  Lorg.eclipse.swt.widgets.RunnableLock is always the top user of objects/heap ram, though of course the number changes because I guess they get GC'd quickly

dvd@chuckie:~/sjk$ java -jar sjk.jar  hh --dead --pid 16105
Restarting java with unlocked package access
   #      Instances          Bytes  Type
   1:           906     5970924080  [Lorg.eclipse.swt.widgets.RunnableLock;
   2:        537073       17186336  com.biglybt.core.util.LightHashMap
   3:         53484        2139360  com.biglybt.core.util.StringInterner$WeakStringEntry
   4:         41351        1323232  com.biglybt.core.util.LightHashMap$EntrySet$EntrySetIterator
   5:         41845        1004280  com.biglybt.core.util.LightHashMap$EntrySet$EntrySetIterator$Entry

**Comment by jaymzjulian** [comment]
Based on the above, I did three things, and I'm not really sure yet which one it is - 
1) I updated SWT to 4.8, and 
2) I turned off the "my torrents" display, and
3) I turned off "rememebr progress bar position" option in interface

And by doing this, it seemed to stop the heap constantly growing, and stabilised it at between 4 and 8 gig, whcih seems.... way way better!  Later I'll do the differential to see which of these actually fixed it

**Comment by jaymzjulian** [comment]
(What I ended up doing with that, is turning off table updates entirely - setting "reorder" to never, and update graphical bars to 999 (though i have them turned off), which seems to have stopped the leaking, and has the heap sitting at around 4gig average, occaisonal peaks to 6gig when "new" things happen, which is also fine.

**Comment by jaymzjulian** [comment]
So, after doing all of these things, it ran for 48h with no issues, at which point I opened the "My Torrents" tab, which sent it into SWT event hell again after about two minutes, from which it never recovered and needed a restart

I had an idea that I could potentially implement to deal with this, though I won't have time to spin up a development environment/remember how to java (it's been a while ;)) until the weekend, but I was thinking of implementing a UI queue thread which calls syncExec, which could (in the simple case) ensure that we don't stack timer updates for tables, or (in the complex case) just throw out duplicate updates and/or have some kind of priority system.  

I mean, alternatly if the UI is already its own thread anyhow, just calling syncExec rather than asyncExec _seems_ like it would resolve this, but i'm skittish about locking up other parts of the system!

**Comment by parg** [comment]
Just back and going through things - hopefully B04 will have improved the lockups? Don't suppose you have a full stack trace from the NPE in addListener?

**Comment by parg** [comment]
From your debug it seems that a lot of the SWT thrashing is to do with positions changing in MyTorrents view - I've changed things for the next beta that might improve that - thanks for all the feedback, very useful!

**Comment by jaymzjulian** [comment]
sadly it's not dumping a full stack to debug_*.log - the entirety we get is

[08:12:01] [stderr] DEBUG::Sun Aug 05 08:12:01 AEST 2018::com.biglybt.pifimpl.local.download.DownloadManagerImpl::addListener::920:
[08:12:01] [stderr]   java.lang.NullPointerException
[08:12:01] [stderr]

**Comment by jaymzjulian** [comment]
Confirming B06 doens't lock up, so that's great, however I can't actually open the My Torrents view, since the view menu is empty!

**Comment by jaymzjulian** [comment]
B06 - no hangs after 20 hours, but SWT GC hell, which I guess is because I forgot to close the "My Torrents" screen during startup.  Interestingly, the startup time has gone way up again - unsure if this is expected or not, but i'm an hour into starting and still going, compared to around 15 minutes with b03

**Comment by jaymzjulian** [comment]
Also: In B06 I can't double click items in plugins to show a torrent list anymore, and most (but not all) of the icons seem to have bad scaling?!  - see in this screenshot, where options has a cog, but tags overview has dots, or the iconsat the bottom of the screen are mostly corrupted except the ones which aren't.  If this is just me, it might be that I'm still on GTK2 though - I'll try GTK3 and see later today, but it's def weird.

![image](https://user-images.githubusercontent.com/787351/44378328-b0614280-a4b5-11e8-876f-70de8baad379.png)

**Comment by parg** [comment]
\o/ 

Upload a thread_n.log file that covers the loading period if you get a chance, I'll see if there's anything obvious that could be improved

**Comment by jaymzjulian** [comment]
Will do next restart - so far been running the correct B06 for two days, including with the my-torrents dialog, and it's working well!

**Comment by jaymzjulian** [comment]
Interestingly, this has also fixed the _other_ problem I have had, which was the inability to delete torrents - I was able to delete a few thousand torrents with no problem now, whereas in earlier releases, it would cause an OOM, so I guess that was the same root cause.  Huzzah!

The one thing I _did_ have to do, is turn off magnet recovery accross restarts - it would sometimes push system load up to around 900 on startup with magnet threads, and the die with OOM as nothing could keep up.  This is no problem for me, since I push magnets in through scripts anyhow, but it might be worth backing off those and only queueing some at a time (What I do in my script, is I actually pull one of my RSS feeds to ensure that the java isn't wedged, and don't add magnet if load > 20), but beyond that things are _way way_ better now - thanks so much for your help!

**Comment by jjlimepoint** [comment]
Awesome, thanks for that - things are looking pretty good for me now, and it's much appricated.  Happy for this ticket to be closed out!

**Comment by jaymzjulian** [comment]
(Last comment was me - I have too many github accounts ;)
