### ISSUE TITLE
tags multifiltering do not work

### ISSUE THREAD

**Issue by KonoromiHimaries** [BiglySoftware/BiglyBT#562]
Any posts or screenshots displaying torrent names, search results, subscription names, will be removed without notification, unless they are linux distros.

![2018-08-03-](https://user-images.githubusercontent.com/5884000/43621915-f09fef84-96d9-11e8-8697-1a55141ed911.png)

to reproduct click ctrl and select tags

For bugs, please include the "System" section of the Help->About window, or if you don't have access to the window, include:
* OS and version w10
* BiglyBT Version Number  v1.6.0.0

Erase all this text before submitting the issue :)

**Comment by parg** [comment]
When multiple Tags are selected the logic is an AND operation - i.e. the download displayed have ALL of the selected tags assigned (as opposed to at least one)

What isn't working?

**Comment by KonoromiHimaries** [comment]
multifiltrating instead of subtracting items, adds new to the search list

**Comment by TuxPaper** [comment]
fwiw, Tags Overview has the ability to do both.  It defaults to AND like the Library view, but there's a checkbox in the Torrents tab for "Torrents with any of the selected tags"

**Comment by parg** [comment]
Ah, sorry, my mistake - the default option for the buttons is OR.

**Comment by parg** [comment]
There will be an option to switch to AND in the next beta - Tools->Options->Interface->Tables: Library

**Comment by KonoromiHimaries** [comment]
@parg and deselecting tags do not work. can you add feathure to deselect the specified tags with `ctrl + left click` or only `left click`

**Comment by parg** [comment]
Can you test out the latest beta release B02 please? https://www.tumblr.com/blog/biglybt
