### ISSUE TITLE
Weird behaviour 

### ISSUE THREAD

**Issue by Ynti** [BiglySoftware/BiglyBT#563]
Hi
I have a weird behaviour with BiglyBT. Download starts then stops for some time, then starts again, then stops again and so on. And this for some dozens of minutes (even 45 min ). After this long time the download goes on normally. In all this time I'm connected to the peers, I have the status ,,fully established".
Does anyone know what causes this kind of behavior?
Below is the speed graphic where you can see the behaviour.
[img]https://s15.postimg.cc/my8wppq17/Untitled.png[/img]

**Comment by parg** [comment]
To be honest I wouldn't mess with the cache size much - you could look at the statistics for cache hits (Tools->Statistics: Cache) to see how effective it is being.

When you are downloading multiple sequential blocks from a peer then the cache helps to consolidate the 16kb blocks into bigger writes. 

When a piece is being checked when it completes if the piece is still in cache then this saves some reads from the disk. However, if you have a lot of active pieces then the cache becomes less effective. 

Personally I don't mess with the setting at all.
