### ISSUE TITLE
"NAT / Firewall Test" fails.

### ISSUE THREAD

**Issue by Achaean** [BiglySoftware/BiglyBT#565]
Hi! :-)
Last BBT release on Win 10 (both x64).

```
Java 1.8.0_181 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_181
SWT v4757, win32
Windows 10 v10.0, amd64 (64 bit)
B1.6.0.0/4 az3
```
UDP test is known to be faulty in Azureus too, but now the TCP test, fails as well, with this message:

```
Γίνεται δοκιμή της θύρας  TCP 56560 ... 
Unable to test: Invalid port given, or test service failed.
Another application may already be using this port.. 
(Error: Connection refused: connect).
```

This specific port is normally opened in firewall and forwarded from router.
Either is a real problem, or the TCP test fails.
Dunno! I just installed BBT for testing it.

**Comment by parg** [comment]
BiglyBT uses the same NAT test servers as Vuze - it seems that the servers are down

**Comment by Achaean** [comment]
Oh, I see!

Well...that's strange! :-)
Launching Azureus the TCP NAT test works properly.
Launching Bigly, it displays the above mentioned error message.
Nothing of importance though!

**Comment by parg** [comment]
Please test with B03

**Comment by Achaean** [comment]
Ehm...Where can I find the Beta jar? :-)
Trying the "join Beta Program" option (from inside Bigly), is failing.
![screenshot](https://user-images.githubusercontent.com/3608053/43917212-2bf9bad6-9bff-11e8-9b6f-6e72b4f8902b.png)

**Comment by parg** [comment]
Meh! Something's borked innit! You can manually install the beta by downloading

https://s3.amazonaws.com/biglybt-files/core/BiglyBT1601-B03-signed.jar

and then renaming it to BiglyBT.jar and replace the one in the installation folder.

Wonder what is borking your updates...

**Comment by Achaean** [comment]
Success!!! :-)

Both TCP and UDP tests completed successfully!
