### ISSUE TITLE
"Plugins uninstallation" error.

### ISSUE THREAD

**Issue by Achaean** [BiglySoftware/BiglyBT#566]
Hi! :-)
Last BBT release on Win 10 (both x64).
```
Java 1.8.0_181 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_181
SWT v4757, win32
Windows 10 v10.0, amd64 (64 bit)
B1.6.0.0/4 az3
```
Plugins uninstallation  wizard, seems to be broken.
Fails to uninstall whatever plugin I tried to.
(eg. Ratings, Message Sync, M-Lab etc).

**Comment by parg** [comment]
Do you have any specific error during uninstallation? I just tested with mlab and it worked fine.

**Comment by Achaean** [comment]
No.
The wizards offers restarting Bigly (which I accept), it launches the command prompt updater (asking for  administrator rights, which I accept), starting  again Bigly and all the plugins are still there.

Nothing of importance too.
I maybe was unable to uninstall them, but I was able to disable them (from settings).

PS. Specifically the M-Lab plugins, never worked properly for me.
It prompts me to limit the upload speed to 60-70 kbps, while I'm uploading with 90-110.
