### ISSUE TITLE
Tags not working

### ISSUE THREAD

**Issue by marc0nline** [BiglySoftware/BiglyBT#567]
Windows Server 2016 v10.0, amd64 (64 bit)
B1.6.0.0/4 az3

When using Sonarr or Radarr the grabbed files aren't being tagged or moved per the parameters set for the TAGS. I have to manually move everything.  is there a WIKI to help me set tags so my downloaded content will automatically get tagged and moved to the correct folders?

**Comment by ferdnyc** [comment]
Well, there's https://github.com/BiglySoftware/BiglyBT/wiki/Tags which may be of some help.

Really, though, you'll have to tell us _how_ you're attempting to set up your tag parameters, and what you expect to happen. Tags are a powerful feature (almost too powerful), so it can take some experimentation to achieve the results you want.

I can offer a few insights, though:
1. Automatic and Manual tags are mutually exclusive, a tag can only be one or the other. This one threw me for a loop until I figured it out. 
   If you set a tag up to auto-apply (based on tracker matching, constraints, or whatever other criteria), it will still _show_ "Manual" for its Type, but the tag can no longer be manually applied and unapplied, it will **only** be applied based on the configured rules. Tags which are configured to auto-apply won't even show up in the Tags submenu of the torrent's context menu.
2. Tags _can_ be configured to auto-apply based on the presence of other tags, even manual ones, using a `hasTag()` constraint. So, if you have a manual-apply tag `Software`, and you set up a tag `DownloadDir` to auto-apply on the constraint `hasTag("Software")`, then manually tagging a torrent `Software` will automatically also tag it `DownloadDir`. The rules for both tags will be applied. There may be situations where this is useful, though to be perfectly honest I haven't come up with any. (My auto-apply tags all apply either based on tracker hostnames, or based on `hasTag()` constraints for one of those _other_, tracker-hostname-driven, auto-apply tags.)
3. Setting the Initial Save Location of a torrent via a tag won't work if the torrent is running already. If you want to be able to configure the download dir for your torrents by applying tags, you need to have the torrents add in the stopped state, and apply the tag **before** starting them.

**Comment by ferdnyc** [comment]
Oh, one more:
1. (Actually 4.) The auto-apply considerations I mentioned above are specific to tags that auto-apply _themselves_. You can still have manual tags that are automatically applied by _other_ means (like plugins). For instance, I have RSSFeed Scanner configured to set certain tags on torrents, based on which feeds they come in on. Those tags still count as Manual tags, so I can apply and remove them manually as well.
