### ISSUE TITLE
Help/Check for Updates not working in 1.5

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#577]
![biglybt no update](https://user-images.githubusercontent.com/37715552/44304542-fc917300-a34d-11e8-9081-e624a1900494.png)

Picture says it all. I only found the 1.6 Update from the web page.  The check for Updates is not working in 1.5.0.0. Since I did not see the Check for Updates in the change log for 1.6, thought I would mention it so it can be checked.

**Comment by parg** [comment]
Weird - it is working for most people (as people are upgrading). Can you take a look in the 'debug_1.log' and 'debug_2.log' files in the 'logs' folder in the BiglyBT config data folder (%APPDATA%\BiglyBT\logs) and see if there are any errors relating to update checks?

**Comment by NaPurHab** [comment]
Did a search on the word “update”.  But not sure the line I found is what your asking about.  So see attached logs. Hope they help.

Sent from Mail for Windows 10

**Comment by parg** [comment]
nothing attached - trying attaching them to the issue directly https://github.com/BiglySoftware/BiglyBT/issues/577 ?

**Comment by NaPurHab** [comment]
[debug_1.log](https://github.com/BiglySoftware/BiglyBT/files/2300178/debug_1.log)
[debug_2.log](https://github.com/BiglySoftware/BiglyBT/files/2300181/debug_2.log)

**Comment by NaPurHab** [comment]
Hmm, under logs\save are backups. And I just found some other lines in a search for "update".  Attached are the all the backup versions.
[1534619303421_debug_1.log](https://github.com/BiglySoftware/BiglyBT/files/2300186/1534619303421_debug_1.log)
[1534619303421_debug_2.log](https://github.com/BiglySoftware/BiglyBT/files/2300187/1534619303421_debug_2.log)
[1534643574273_debug_1.log](https://github.com/BiglySoftware/BiglyBT/files/2300188/1534643574273_debug_1.log)
[1534643574273_debug_2.log](https://github.com/BiglySoftware/BiglyBT/files/2300189/1534643574273_debug_2.log)

**Comment by parg** [comment]
You have 'anonymous updates' enabled - for some reason this is borking

**Comment by parg** [comment]
Do you have the 'Tor Helper' plugin installed and working?

**Comment by NaPurHab** [comment]
![biglybt start](https://user-images.githubusercontent.com/37715552/44311924-6b6adc80-a3df-11e8-971b-8f2b9e55a0ff.PNG)
 RE: anonymous updates.    Was there a question in there?

As to Tor Helper.  Installed, and on the Display settings for External Browser, the test on that page works.   But when I click the test on the Tor Helper Plugin page, it opens 2 small windows, that when I try URLs or a search, nothing happens.  Here is the text of the Tor Helper Log (tools/plugins/logviews/tor helper) and the snips of what the Browsers look like and the Config screen for Tor Helper.

Tor Helper Log:
[14:40:00] Plugin enabled=true, server=internal, socks port=29071
[14:40:00] Domain rewrites: {}
[14:40:00] Prompt decisions: Allow Vuze; [^*]
[14:40:01] Intermediate SOCKS proxy started on port 58695 for Filtering for I2P: 58378, filtering=true
[14:40:01] Filtering details: 58695 -> 127.0.0.1:58378
[14:40:04] Starting server
[14:40:04] Server started
[14:40:04] Waiting for server to initialise
[14:40:04] * 'C:\Users\Phillip' is not recognized as an internal or external command,
[14:40:04] * operable program or batch file.
[14:42:04] Server failed to initialise, abandoning

![tor helper](https://user-images.githubusercontent.com/37715552/44312000-e08ae180-a3e0-11e8-8a17-387f09456cbb.PNG)
![tor helper 2](https://user-images.githubusercontent.com/37715552/44312002-e54f9580-a3e0-11e8-8346-c519552cb0f4.PNG)

**Comment by NaPurHab** [comment]
Oh and just thought of this. When the Tor Helper is installed.  The only place I can find to Launch a Tor Browser is on the options screen.  No where in the main interface is a button to launch a Tor Browser.  Perhaps a tick box in the Tor Helper settings regarding "Show Tor Browser Button". And then Have a Button that show/disappears for "Open Tor Browser", where the Add Torrent and Search Buttons are.
