### ISSUE TITLE
Update All Subscriptions Only Partially Functional

### ISSUE THREAD

**Issue by LuvBiglyBT** [BiglySoftware/BiglyBT#578]
All subscriptions do not update when Updsate All is selected on right clicking on subscriptions.  Only about 5% are updated.  When updated individually, they will update or, if left untouched, they will update via Auto Update.  Also changing of URL on right click craetes a new subscription but the (old) one also changes.

One last thing, when downloading new updates to the program, I have to disable PeerBlock because one of the URL's is blacklisted on the government blacklist.  What is up with that?

![capture 3](https://user-images.githubusercontent.com/34841335/44487718-fbe62e80-a624-11e8-9b1c-9f15501c99d6.JPG)

**Comment by parg** [comment]
The same code is used to individually update a subscription and to do them all. They are processed asynchronously though so if you have a lot it might take some time to go through them. Also the UI might not update immediately.

Look at the Subscriptions_1.log and Subscriptions_2.log files in the logs folder in the BiglyBT config folder for info.

I'm not seeing the URL change on the 'old' one - do you have an example to show this?

As for PeerBlock - you would need to ask the list providers why they are blacklisting a particular URL

**Comment by LuvBiglyBT** [comment]
Parg,

Sorry for the slow response.  Wanted to spend time making sure of my experience.

The issue with “changing the url” on right click seems to be resolved after latest updates.  The issue with “Update All” subscriptions seems the same and I am not sure if it is a waiting time issue or not.  My experience while viewing ALL subscriptions after left clicking once on subscriptions and after right clicking to “Update all now” is that almost immediately I receive this message, “Failed to load page” on more than 90% of my subscriptions.  Then if I update the previously failed subscriptions individually and manually, they appropriately update OR I can wait 10-15 minutes and they will all update appropriately via Auto Update.  Having used Vuze for years previously, and Bigly for the last year, I have never before run into this problem, which was only noticed for the first time about 3 months ago.

It might help for you to know that I do have close to 100 subscriptions, usually created with LimeTorrents.

LuvBiglyBT

**Comment by parg** [comment]
Are there any more details with the 'failed to load page' message? It could be that the RSS feed site is enforcing a 'refresh period minimum' and the attempt to refresh all at once is blowing it?

**Comment by LuvBiglyBT** [comment]
This is one example:
Failed to load page, https://www.limetorrents.cc/searchrss/The marvelous Mrs  Maisel 720p/: Error on connect for 'https://www.limetorrents.cc:443/searchrss/The%20marvelous%20Mrs%20%20Maisel%20720p/': 503 Service Temporarily Unavailable: error=<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body bgcolor="white">
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>

This is another:
Failed to load page, https://www.limetorrents.cc/searchrss/Shooter 720p/: Error on connect for 'https://www.limetorrents.cc:443/searchrss/Shooter%20720p/': 503 Service Temporarily Unavailable: error=<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body bgcolor="white">
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>

Your suggestion might very well be the culprit. although I have no info in logs to that effect.  The "Temporary Unavailable" does not appear during individual update, nor is the service unavailable when I go diurectlyu to the website.

**Comment by parg** [comment]
Thanks - the 503 does seem to show throttling occurring - it isn't as if the request to perform the feed update is any different for a refresh-all triggered refresh or a manual one.

You could try going to Tools->Options->Subscriptions: Rate limits:

and setting 

www.limetorrents.cc=1

**Comment by LuvBiglyBT** [comment]
Parg,

 

To follow up, enabling Rate limits simply stopped all updating and I had to disable it again to get needed updates.  I realize this is not6 an issue with BiglyBT, but do you have any other suggestions.

 

Best,

LuvBigltBT
