### ISSUE TITLE
Mac dmg installer is damaged and won't install

### ISSUE THREAD

**Issue by ackerthehacker2** [BiglySoftware/BiglyBT#581]
Downloading the latest .dmg file shows the dmg as damaged ...

**Comment by TuxPaper** [comment]
Are you downloading it from github, or biglybt.com?

**Comment by ackerthehacker2** [comment]
Biglybt.com

**Comment by TuxPaper** [comment]
I've tried both installers and they install correctly on my Mac.  Can you provide any more information?

Does the damaged error show up when you launch the .dmg file, or when you launch the "BiglyBT Installer.app" within the dmg?

Is there any additional information provided in the damaged message, like a mention of certificate errors or nargles?

What macOS version are you running?

**Comment by ackerthehacker2** [comment]
I got it to work by running it from the command line after doing a hdutil attach:   BiglyBT 1.6.0.0 Installer dacker$ BiglyBT\ Installer.app/Contents/MacOS/JavaApplicationStub 

Maybe a Mojava or Java issue?  Weird

**Comment by TuxPaper** [comment]
Thanks!  I haven't found your specific issue yet, but I did find something worrying going forward, from https://www.macrumors.com/2018/06/05/macos-mojave-security-privacy/

> Notarization will let macOS Mojave users know for sure that a third-party non-App Store Mac app has been double checked by Apple and that it's free from malware. Eventually, Apple plans to require all Developer ID apps to be notarized before they can be installed, but Apple says this is not an app review process and is used exclusively to analyze apps for security purposes.

**Comment by ackerthehacker2** [comment]
The installer hung migrating my Vuze installation, but I was able to manually configure
