### ISSUE TITLE
Connection Binding Not Enforced in RSSFeed Scanner 

### ISSUE THREAD

**Issue by Taurean75** [BiglySoftware/BiglyBT#586]
Hello --

I'm using an VPN, which I bound BiglyBT to (TAP-Windows Adapter V9); however, the scanner fetches RSS feeds even when the VPN interface is disabled.  I presume this is the case for other functions as well, such as updates.

Are you guys aware of this?

Thanks!

**Comment by parg** [comment]
Unfortunately the 'enforce bind' option that prevents connection when the VPN is not connected is only really applicable to peer-to-peer traffic and tracker communications.

**Comment by Taurean75** [comment]
Can't you change it?  That would make it much more secure and private.

**Comment by parg** [comment]
Check out version 1.6.9 - there is still a small window between the VPN connection dropping and BiglyBT detecting this but it is the best that can be done given the time available. Please report if it is working OK as I don't have a VPN to test with.

**Comment by Taurean75** [comment]
It still loads through the normal interface.

**Comment by parg** [comment]
I set up a bogus bind address and when I went to refresh a feed in the RSSFeed Scanner it gave the expected error - 'Forced bind address is missing'

![image](https://user-images.githubusercontent.com/395293/44948020-2a76bd00-ae0e-11e8-85a7-8f710d5d2ea1.png)

**Comment by Taurean75** [comment]
I guess there's a difference between disabled and missing interface.

I can lend you my VPN if you want.

**Comment by parg** [comment]
Just checking that you have enabled the 'force bind' option along with the bind address/interface?
