### ISSUE TITLE
Add Seed2PeerRatio to Tags Transfer Settings

### ISSUE THREAD

**Issue by Xemnarth** [BiglySoftware/BiglyBT#588]
A field for Minimum/Target Seed2PeerRatio along with 'When exceeded:' options. This would help identify which torrents require seeding the most based on their health. Thank you!

**Comment by parg** [comment]
There is already a Tag Constraint variable called 'seed_peer_ratio' that you can use to select the torrents assigned to a tag. For example, to select torrents with a seed-to-peer ratio of < 0.5 use a constraint of

isLT( seed_peer_ratio, 0.5 )

**Comment by Xemnarth** [comment]
Where do I set this custom tag rule?

**Comment by Xemnarth** [comment]
Type where?? Under the console?
