### ISSUE TITLE
Can't collapse 'My Torrents'

### ISSUE THREAD

**Issue by Xemnarth** [BiglySoftware/BiglyBT#589]
When I try to collapse 'My Torrents' in the sidebar it force expands. This behavior can also be observed in 'Content Discovery>Subscriptions' sometimes.

**Comment by parg** [comment]
I think this happens when one of the entries within MyTorrents has focus - try selecting something outside of MyTorrents and then collapse it

**Comment by Xemnarth** [comment]
Nope. Tried changing focus to no avail.
