### ISSUE TITLE
Options search-highlighting has contrast issues

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#593]
When you perform a Search in the Options window, any panes with matching entries have their labels bolded, and the entries are highlighted in the window.

At least on Linux / GTK3, that highlighting is done in black... it isn't super pretty, but it mostly works OK when the text is reversed to light gray.

The problem is, checkbox labels _don't_ get reversed, they end up in bold dark gray on black, which is virtually unreadable. (The checkboxes themselves also reverse badly, so that it's hard to tell whether a highlighted box is checked or not.)

Here's Options > Plugins > UPnP after a search for "device":
![image](https://user-images.githubusercontent.com/538020/45057971-3d36ff00-b065-11e8-9d32-fd59c31db0ba.png)

### System details
```
Java 1.8.0_181 (64 bit)
  Oracle Corporation
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181-7.b13.fc28.x86_64/jre

SWT v4757, gtk/3.22.30
Linux v4.17.19-200.fc28.x86_64, amd64 (64 bit)
B1.6.0.1_B08/4 az3
```

**Comment by ferdnyc** [comment]
Huh. Well, that's frustrating. I guess it might be a theme issue?

(Regardless, is there any possibility the highlighting could be done in a color that the gray text would have better contrast with, say a dark green or blue? Or by keeping the text black, and highlighting with a lighter color? ...I suppose it's still possible for a theme to screw that up, of course.)

I'll try and look at the GTK theme LXDE is using, see if there's something there.

**Comment by parg** [comment]
There was a layout issue with those fields that I've fixed - dunno if it'll make any difference to you though. Check the next beta anyway (not built yet), just in case!

**Comment by ferdnyc** [comment]
I... feel sort of guilty, now. :laughing:

**Comment by ferdnyc** [comment]
So what do you think the determining factor is, then? GTK 3.22+? It wouldn't surprise me if they locked the color down to the theme, and took it out of application control. That sounds like them.

**Comment by parg** [comment]
hehe, no idea :) I'll look into an alternative highlight technique for the moment

**Comment by ferdnyc** [comment]
Neato. 1.6.0.1_B09:
![image](https://user-images.githubusercontent.com/538020/45197518-bb470180-b22f-11e8-9b19-9e712a776951.png)
