### ISSUE TITLE
sometimes biglybt disappeared from the tray beam

### ISSUE THREAD

**Issue by KonoromiHimaries** [BiglySoftware/BiglyBT#594]
before
![2018-09-05-window](https://user-images.githubusercontent.com/5884000/45066413-a860ef80-b0be-11e8-9e38-b1aeb93be60b.png)

after
![2018-09-05-2-window](https://user-images.githubusercontent.com/5884000/45066525-173e4880-b0bf-11e8-9825-6e15adb2787a.png)

biglybt is visible on the background bar and by the task manager

if i use the x button located in the upper right corner of the program, biglybt is not visible anywhere except the task manager

only after being closed by the task manager and restarting biglybt appears again in the tray 

to reproduce:

try open and minimalize biglybt to the background bar x10 times or more at different time intervals

* OS and version w10 x64 pro last update
* BiglyBT Version Number 1.6.0.0
* For *nix: Desktop Environment

**Comment by parg** [comment]
When it is in this state what happens if you try and start BiglyBT (while it is showing in the task bar)?

**Comment by parg** [comment]
weird - I assume that the BiglyBT icon isn't visible in the 'hidden' icons section (shown when you hit the 'up arrow'  - 

![image](https://user-images.githubusercontent.com/395293/45149447-7b493580-b1c1-11e8-821b-c80d289924fc.png)

**Comment by KonoromiHimaries** [comment]
no, i have off the 'hidden' icons section

**Comment by Havokdan** [comment]
This happens randomly with me too, very rare, the icon disappears and I can only display the application again when I click on the executable again, which brings the application to the foreground.

**Comment by eurobank** [comment]
The Icon dissapear when Windows Explorer crashes. Windows Explorer crash seems like a screen refresh.

**Comment by googlenews** [comment]
My BiglyBT icon is NOT VISIBLE in dark-mode in macOS and I’ve reported it for about 1 yr how.

**Comment by TimetravelerDD** [comment]
i can confirm this behavior on windows. Once the explorer crashes or is restarted the try icon disappear and does not come back. So there is no apparent way of reopening the application again, however it is still running in the background unaccessibly.

Most of the time I can actually get back into the application by opening it again from the start menu like I would if it would be not running at all. (however this sometimes fails if the application is about to install an update or was recently updated)
