### ISSUE TITLE
[FEATURE REQUEST] Alternative Speed

### ISSUE THREAD

**Issue by eurobank** [BiglySoftware/BiglyBT#595]
Hello.

Sometimes we want to switch (for a while) quickly to an alternative speed settings (usually faster download speeds). 

It would be great if some option existed for an (already set) alternative speed and we could switch it on and off via the bottom bar.

Thank for this great client.

**Comment by parg** [comment]
If you open the 'plugin bar' (View->Plugin bar') and select the 'Quick Config' section you will see an entry for 'temporary rate limits'. Currently this is applied for a specified time - if you want manual control then just enter a large duration and manually de-activate when required

**Comment by eurobank** [comment]
Where is that ? No such thing in my View
![2018-09-11 14_37_53-window](https://user-images.githubusercontent.com/4467158/45357882-5fce9800-b5d0-11e8-80d7-a47b5c09580b.png)

**Comment by parg** [comment]
Ah, you need to set you 'Mode' (Under Tools->Options) to 'Advanced' - forgot about that!

**Comment by eurobank** [comment]
Thanks !!
