### ISSUE TITLE
Plugins→Friends→Decentralized chat window not have a scrollbar and not fit findow

### ISSUE THREAD

**Issue by iav** [BiglySoftware/BiglyBT#596]
Plugins→Friends→Decentralized chat window not have a vertical scrollbar and not fit findow.
Java 1.8.0_181 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_181

SWT v4757, win32
Windows 7 v6.1, amd64 (64 bit)
B1.6.0.0/4 az2

**Comment by parg** [comment]
fixed in B10

**Comment by iav** [comment]
> 
> 
> fixed in B10

I confirm.
Thank you!
