### ISSUE TITLE
zonealarm deletes program when updated

### ISSUE THREAD

**Issue by softwarek** [BiglySoftware/BiglyBT#60]
OS:Windows 10 64
ZoneAlarm Free Antivirus + Firewall version: 15.0.653.17211
Vsmon version: 15.0.653.17211
Driver version: 15.1.29.17237
Antivirus engine version: 8.7.0.69
Antivirus signature DAT file version: 1261376576

ZoneAlarm deleted updated biglybt.exe and biglybt restart.bat say it a trojan.

ZoneAlarm
AV/treatment,2017/09/15,08:19:04 -4:00 GMT,PDM:Trojan.Win32.Generic,c:\program files\biglybt\biglybt.exe,Deleted,Auto
AV/treatment,2017/09/15,08:19:04 -4:00 GMT,PDM:Trojan.Win32.Generic,c:\users\sts\appdata\roaming\biglybt\restart.bat,Deleted,Auto
AV/treatment,2017/09/15,08:19:04 -4:00 GMT,PDM:Trojan.Win32.Generic,c:\program files\biglybt\biglybt.exe,Deleted,Auto

**Comment by parg** [comment]
Hmm, ZoneAlarm support page ( ) suggests uploading the file to

**Comment by softwarek** [comment]
yeah I re-download and installed doesn't give any issue.Only when it used the update.bat for some reason iam not sure what zone alarm is seeing as issues .I know there no actual virus there just something in the update that triggered zonealarm. having delete the program because it thinks something in it malware it a pain

**Comment by HOTinHEELS** [comment]
hmm.  you need to configure ZA to quarantine all detected issues (best policy).  Doing so will enable you to then go to "Quarantine" and restore the item (BiglyBT) which will automatically add it to the exceptions list.
