### ISSUE TITLE
Window "Edit comment" is not resizeable

### ISSUE THREAD

**Issue by iav** [BiglySoftware/BiglyBT#600]
Popup Window "Edit comment" used for torrebt comment edition is not resizeable.
I think there should be availableway to make window much larger to comfortable view and edit large piece of text.

Maybe when wondow opens to edit already eisted text it can take initial size as compromiss of "to display existed text without viewport scrolling" and available screen size.

**Comment by parg** [comment]
Fixed in next beta - made larger and resizeable (but not fit-existing)

**Comment by iav** [comment]
I try, and now everything fine.
Thank you!

**Comment by parg** [comment]
great
