### ISSUE TITLE
Implement http://retracker.local/announce

### ISSUE THREAD

**Issue by token0** [BiglySoftware/BiglyBT#602]
Please implement local retracker compatibility feature. 
Standard address is http://retracker.local/announce

**Comment by parg** [comment]
Any more info on this?

**Comment by token0** [comment]
It is used for local exchange. It's been there for quite long time actually, roughly about 10 years. Some tracker sites add it in .torrent files as tracker source. I haven't found articles on English, only a lot in Russian. You can look in translated wiki though https://translate.google.com/translate?sl=ru&tl=en&js=y&prev=_t&&ie=UTF-8&u=https%3A%2F%2Fru.wikipedia.org%2Fwiki%2F%25D0%25A0%25D0%25B5%25D1%2582%25D1%2580%25D0%25B5%25D0%25BA%25D0%25B5%25D1%2580&edit-text=&act=url

**Comment by parg** [comment]
So basically some greater-being (something that controls your DNS) assigns 'retracker.local' to a tracker optimized for intra-ISP (for example) communication? As far as I can tell this requires no support from BiglyBT - it is up to some other entity to

1) Setup DNS to resolve 'retracker.local' to something concrete (say IP address a.b.c.d)
2) Run their own open tracker on a.b.c.d 

Unless I have misunderstood things?

**Comment by iav** [comment]
@token0 do you mean something like auto-add retracker.local to tracker list of torrent during add? 
Or add retracker.local as additional source to all active torrents, but not changing torrents itself?
Something else?

**Comment by parg** [comment]
Closed due to no user feedback

**Comment by ramazansancar** [comment]
Main Post: https://rutracker.org/forum/viewtopic.php?t=2234744

Source: https://ru.wikipedia.org/wiki/%D0%A0%D0%B5%D1%82%D1%80%D0%B5%D0%BA%D0%B5%D1%80 4. Note
