### ISSUE TITLE
Update anonymously failes due to wrong IP resolution 

### ISSUE THREAD

**Issue by ghost** [BiglySoftware/BiglyBT#603]
when updating anonymously there are errors due to IP resolution ( or some other kind of response rewrite from the server(s) ) that leads bbt to fetch from a 10.x.x.x subnet:

[  Downloading: http://plugins.biglybt.com/update/pluginlist3.php]
[Error: http://10.189.192.155/update/pluginlist3.php?type=&version=1.6.0.1_B11...........

It would be great if this is fixable to have BBT up to date when in anonymous mode only.

Thanx

**Comment by parg** [comment]
That 10.x.y.z subnet is used internally to route requests through Tor - so it looks as if Tor ain't working well - check Tools->Plugins->Log Views->Tor Helper
