### ISSUE TITLE
"Search Library" field of "My torrents" view text does case-sensitive matchung for russian words

### ISSUE THREAD

**Issue by iav** [BiglySoftware/BiglyBT#604]
"Search Library" field of "My torrents" view text does case-sensitive matchung for russian words.

For example, I have some torrents with word "ЛИНУКС" in name. It should match case-insensitive with any string like
линукс
Линукс лИнУкС

but will match only exact "ЛИНУКС"

**Comment by parg** [comment]
fixed next beta, thanks

**Comment by parg** [comment]
B12 is out

**Comment by iav** [comment]
I did a check.
Seems all correct.

Thank you.

**Comment by parg** [comment]
\o/
