### ISSUE TITLE
Android 7.1.2 not visible tools in status bar (at blue line)

### ISSUE THREAD

**Issue by bodanek** [BiglySoftware/BiglyBT#606]
Hi,

I tried to use my favorite BiglyBT on my Android TV BOX (KIII PRO AMLOGIC S912), but I have problem with missing tools at blue line (see picture) 
I tried to reinstall BiglyBT, factory reset TV BOX, use older version, etc but I can not do anything to use or control BiglyBT.
Of course I run on "Torrent using this device" not remote client!

Have anybody idea how to solve that isue?

Thank you, 
![biglybt](https://user-images.githubusercontent.com/43348417/45636365-cd366900-baa7-11e8-9719-4bb29c31367f.jpg)
Petr

**Comment by TuxPaper** [comment]
See Issue in in the BiglyBT-Android project.  I've commented on a potential workaround
