### ISSUE TITLE
"show tag buttons" in mouse context menu does nothing

### ISSUE THREAD

**Issue by iav** [BiglySoftware/BiglyBT#607]
"show tag buttons"  in mouse context menu near "search library" does nothing. Seems it should make buttons with tag names, like it work for "show category buttons", but it didn't.

Java 1.8.0_181 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_181

SWT v4757, win32
Windows 7 v6.1, amd64 (64 bit)
B1.6.0.0/4 az2

**Comment by parg** [comment]
hmm, works fine for me :(

![image](https://user-images.githubusercontent.com/395293/45677098-49be5b80-bb2b-11e8-8d1d-1a7fed860129.png)

Category buttons are on the left, Tag buttons on the right (there's a bit of space separating them)

**Comment by iav** [comment]
I found:
in "tags overview" tab I can choose a tag, and see a property "view in sidebar". It not checked  by default, and it's areason why none of my tagshave it set. 
Now I check it, and tag buttons works as it should.

I propose to change default value "view in sidebar" of a newly added tag to "yes" to avoid problem like mine.

**Comment by parg** [comment]
Yup. You do have some Tags defined I assume? There are no 'All' and 'Untagged' buttons for Tags (by default)

**Comment by iav** [comment]
I have some tags.
But how can i enable 'All' and 'Untagged' buttons for Tags? I think it will be right behaviour.

**Comment by parg** [comment]
They have to be 'manual' tags (green by default)

For 'All' go to TagsOverview, create a Tag and then set its 'Tag Constraint' to 'true'

For 'Untagged' go to TagsOverview, create a Tag, right-click on it, select 'Properties' and then select 'Untagged'

**Comment by parg** [comment]
Ah, 'view in sidebar' - interesting!

**Comment by parg** [comment]
The default for that is supposed to be 'true' :( When I add a new Tag that setting is ticked

**Comment by iav** [comment]
> For 'All' go to TagsOverview, create a Tag and then set its 'Tag Constraint' to 'true'
> 
> For 'Untagged' go to TagsOverview, create a Tag, right-click on it, select 'Properties' and then select 'Untagged'

Seems tricky

**Comment by iav** [comment]
> 
> 
> The default for that is supposed to be 'true' :( When I add a new Tag that setting is ticked

try to add as I did: via new tag in torrent add dialog and via new tag in torrent details form
