### ISSUE TITLE
Sorting in Files doesn't work

### ISSUE THREAD

**Issue by eurobank** [BiglySoftware/BiglyBT#609]
Using latest beta and Windows 10/64 also latest.

It seems that Sorting in columns of Files doesn't work. The Arrows DO change but nothing else.

See the capture.

![2018-09-19 17_48_42-biglybt](https://user-images.githubusercontent.com/4467158/45761309-a8233100-bc34-11e8-9ec8-951fbbc8d0bf.png)

**Comment by parg** [comment]
Sorting never worked in the Tree version of the Files View

**Comment by Xemnarth** [comment]
Will have to live with it I guess
