### ISSUE TITLE
Cannot connect to update server

### ISSUE THREAD

**Issue by mattsigal** [BiglySoftware/BiglyBT#61]
I'm running BiglyBT on OS X and recently got the prompt to update the app to version 1.0.2 from 1.0.0. I clicked update and the download gets added to my queue (so the .torrent download is functioning), but the torrent itself is never able to connect to the server. I've restarted the app and also left it running for over 24 hours - but in neither situation am I able to connect. All the plugin updates have installed successfully.

This is the tracker info from the update torrent:
![screen shot 2017-09-16 at 12 59 43 pm](https://user-images.githubusercontent.com/1421758/30514238-f3887bbe-9ade-11e7-89c5-3c58f87744f0.png)

Any ideas?

**Comment by parg** [comment]
Hmm, it is a decentralised torrent - is your DHT working OK? Look in the status area, bottom right to the left of the up/down speed indicators. It should show around to a million users.

Worst case please edit the torrent's trackers and add

udp://tracker.leechers-paradise.org:6969

as a tracker

**Comment by TuxPaper** [comment]
Closing issue do to age and lack of update. If anyone still has this issue, please file a new one.  Thanks!
