### ISSUE TITLE
Do Not Download is Ignored 

### ISSUE THREAD

**Issue by Taurean75** [BiglySoftware/BiglyBT#610]
Windows 10 x64 1804
Latest BiglyBT

I've tried unchecking the files within the download window and selecting "Do Not Download" priority under the Files tab, but they are being ignored.

Please advise.

**Comment by parg** [comment]
https://wiki.vuze.com/w/Selective_downloading#Note:_about_file_creation_with_Delete_and_DND

**Comment by Taurean75** [comment]
Thanks, However, I believe other clients don't behave this way. Perhaps they "clean up" afterwards?

**Comment by Havokdan** [comment]
It's protocol, everyone does it, what changes is how each customer deals with it. Utorrent the last time I saw it, it created a .dat file with these bits, bitcomet created a folder and leaves those pieces there and so on.
