### ISSUE TITLE
100% disk usage after a new torrent download starts

### ISSUE THREAD

**Issue by ivu86** [BiglySoftware/BiglyBT#612]
Hello,
When i start to download a new torrent (30gb+, haven't tried with smaller ones) the program goes to downloading -> downloads around 10mb and then download speed goes to 0 and disk usage goes to 90/100%. Within resource management i see that bigly is "writing" the file to the HDD with 70+mb/s but actually nothing happens and the torrent doesn't start to actually download anything. When i try to stop it or restart the program then the torrent is at "Stopping" for quite some time and it's quite slow.

Any ideas what settings to check or remove in order to fix this issue?

**Comment by parg** [comment]
Try enabling Tools->Options->File: Append data to files as downloaded and reorder pieces...

**Comment by ivu86** [comment]
Should i change the default 10mb setting or leave it as it is?
