### ISSUE TITLE
ExecuteOnAssign delete

### ISSUE THREAD

**Issue by mppdidi** [BiglySoftware/BiglyBT#616]
Would it be possible to implemente delete when a tag matches ?

**Comment by parg** [comment]
You can achieve that by using 'limits' and setting the max to 999999 (see https://github.com/BiglySoftware/BiglyBT/wiki/Tags)

**Comment by mppdidi** [comment]
Sorry to ask - but I cannot find the limits when right clicking on a tag.

**Comment by parg** [comment]
Go to the Tag Setting view - right click on the Tag and select 'Settings'
