### ISSUE TITLE
Download Rank not working properly

### ISSUE THREAD

**Issue by mppdidi** [BiglySoftware/BiglyBT#619]
The Queue -> Downloading -> Prioritize.... (Reverse Seed Count) is not working properly.
It seems like the sorting algorithm only works partially or it is converging poorly.

**Comment by mppdidi** [comment]
It seems the criterion here is the number of reported seeds and not the actual connected seeds.
So I guess my assumption about how it works is wrong.

**Comment by parg** [comment]
Do you think connected seeds would be a better metric?

**Comment by parg** [comment]
Remember that the ordering controls which downloads start so it would only order downloads within the active ones

**Comment by mppdidi** [comment]
I understand. It would make sense to have ordering by connected peers / seeds e.g. reorder based on reverse availablity in order to prioritize 'weaker' torrents for some of my use cases.
Would it be possible to implement that.
What are your thoughts on this - do you think it would be usefull ?

**Comment by parg** [comment]
Not sure. If you prioritize by connected peers/seeds the you would have the situation where queued torrents would all be at the same rank (0 as they have no connections) - when one download completed the next one to become active would be 'randomly' selected from the queued ones and then stay active until it completed.

So unless you had all incomplete torrents actively downloading you would get this slightly odd behaviour for queued->active transitions (and never active->queued)

**Comment by parg** [comment]
Closed due to no user feedback
