### ISSUE TITLE
Cannot Mount DMG File On MacOs Mojave 10.14

### ISSUE THREAD

**Issue by Dedication91** [BiglySoftware/BiglyBT#621]
Trying to install BiglyBt on brand new MacOs Mojave 10.14 install, when trying to mount the DMG file, I get a message saying the DMG image is damaged and cannot be opened, I get the option to cancel or move the file to the trash. I tried testing with Vuze and get the same symptom. I am able to mount other DMG files such as the Google Chrome installer, the Java installer and Adobe Flash Player Installer.

For bugs, please inclu
![screen shot 2018-09-25 at 12 15 24 am](https://user-images.githubusercontent.com/23633268/45998654-588b9d80-c058-11e8-8383-7382e3fbc979.png)

de the "System" section of the Help->About window, or if you don't have access to the window, include:
* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment

Erase all this text before submitting the issue :)

**Comment by TuxPaper** [comment]
I've built a new installer that should support Mojave and placed it on https://github.com/BiglySoftware/BiglyBT/releases/tag/v1.6.0.0

Please try it and get back to me.  If it works, I'll put it on the main website too (I may put it on the website sooner)

**Comment by Dedication91** [comment]
Worked fine and I was able to install, thanks :)

**Comment by TuxPaper** [comment]
Thanks for testing it :D I've updated the installer on biglybt.com as well.
