### ISSUE TITLE
Rightclick Menu is incredibly slow

### ISSUE THREAD

**Issue by akidburn** [BiglySoftware/BiglyBT#622]
Hi,
since the beginning of version 1.6 the rightclick menu has been slow.

Its building up from top to bottom, sometimes without the black frame around it.
And when switching between riders, the black frame disappears, lets the buttons build and then reappears.

Depending on system load, it takes between 2 and 5 seconds before it becomes usable, 
and the same process happens if i switch between the riders.

and that yellow exclamation mark symbol says among others " 5% SBC_LibraryTableView max 719" <- no idea what that means actually.

akidburn

Java 10.0.2 (64 bit)
  Oracle Corporation
c:\program files\java\jdk-10.0.2

SWT v4757, win32
Windows 10 v10.0, amd64 (64 bit)
B1.6.0.1_B14/4 az3

**Comment by parg** [comment]
Do you have a lot of downloads selected? Previously there have been issues caused by the menu-state computation causing all the selected download's files to be accessed (thought to be fixed...)

**Comment by akidburn** [comment]
I did some more testing, seems like it slows the more torrents are in the program, doesnt matter how many are selected.

**Comment by akidburn** [comment]
@parg B19 is quite a bit faster, though still sometimes noticeable.

That SBC_LibraryTableView line is now "2% max SBC_LibraryTableView max 187"
