### ISSUE TITLE
NAT and download speed issue.

### ISSUE THREAD

**Issue by Escaone** [BiglySoftware/BiglyBT#623]
Hello.
I got some issue with download speed and the NAT test.
Downloads became very very slow, the NAT test now keeps giving me an error no matter what port I choose (49160–65534 range), I made sure the ports I chose are open on my router and are not in use, tried at least 6.

Errors are the following:

TCP- Unable to test: Invalid port given, or test service failed.
Another application may already be using this port.. 
(Error: Connection refused: connect).

UDP- Sending outbound packet and waiting for reply probe (timeout=5000)
    Sending outbound packet and waiting for reply probe (timeout=10000)
    Sending outbound packet and waiting for reply probe (timeout=15000)
    Sending completion event

NAT Error. Inbound test failed, timed out.

This also happens on vuze now.

Torrents still show green status but download speed is very slow, for example a torrent with over 50 seeds and peers and download speed is not even reaching 1MB, before it used to be 4 and even 5 MB for me.

would appreciate your support.

**Comment by parg** [comment]
Please join the Beta Program (See the Help menu) and then test again once updated

**Comment by parg** [comment]
Closed due to no user feedback
