### ISSUE TITLE
First time installing BiglyBT - Stuck on "Initializing Core"

### ISSUE THREAD

**Issue by Doa132** [BiglySoftware/BiglyBT#624]
I've just installed BiglyBT (on MacOS Mojave). First try (while Vuze was still installed) and imediately after opening BiglyBT it was a mostly blank window (sidebar was there and clickable), but nothing in the main window. Trying to resize the window or move it resulted in the app not responding. Tried  uninstalled and reinstalled and now all I'm getting is the window with Initializing Core. I used the default instal settings (except migrate from Vuze) Can't click anywhere on else on the app. 
If anyone knows why this is happening or how to fix it, please help.

[debug_1.log](https://github.com/BiglySoftware/BiglyBT/files/2422995/debug_1.log)
[debug_2.log](https://github.com/BiglySoftware/BiglyBT/files/2422996/debug_2.log)

<img width="1680" alt="screen shot 2018-09-27 at 1 10 07 pm" src="https://user-images.githubusercontent.com/43628930/46121340-aa9a1200-c256-11e8-913b-33855682b230.png">

----
Tried reinstalling it and deselected all the options for installation. No more initializing core box, but now I'm back to this:

<img width="719" alt="screen shot 2018-09-27 at 7 23 21 pm" src="https://user-images.githubusercontent.com/43628930/46136446-f49ceb00-c28a-11e8-8135-df881944ae39.png">

[debug_1.log](https://github.com/BiglySoftware/BiglyBT/files/2423412/debug_1.log)

-----
Now I'm really confused. Reinstalled Vuze to use for now, and it's doing the same as BiglyBT.
Attempting to do anything just results in it not responding.

<img width="701" alt="screen shot 2018-09-27 at 7 46 00 pm" src="https://user-images.githubusercontent.com/43628930/46138020-2d8a8f00-c28e-11e8-9b80-d98cd46d8676.png">

**Comment by parg** [comment]
Take a look in

/Users/<your user name>/Library/Application Support/BiglyBT/logs

for log files named 'debug_1.log' and (possibly) 'debug_2.log'.

Please uploaded them to this issue.

**Comment by parg** [comment]
Closed due to no user feedback
