### ISSUE TITLE
Retrieving Metadata has wrong filename

### ISSUE THREAD

**Issue by mppdidi** [BiglySoftware/BiglyBT#625]
When retrieving magnet / metadata download via i2p only the original filename is not used for subsequent downloading leading to stuck metadata / magnet phase.
Example: magnet:?xt=urn:btih:a5e549f4c35331a25fdd11fafacac9077dc6bf74

**Comment by parg** [comment]
What original filename? if the magnet doesn't have a &dn=.... parameter then there is no filename. Anyway, the dnis irrelevant, it is only used for display purposes and has no impact on metadata download whatseoever

**Comment by mppdidi** [comment]
I wasn't aware of that.
