### ISSUE TITLE
Resize Left Window not available on mac os mojave

### ISSUE THREAD

**Issue by ddbelina** [BiglySoftware/BiglyBT#626]
beta 14
No resize arrow for left window after update to mac mojave

**Comment by parg** [comment]
Do you mean the split between sidebar and the right-side content? If so I can resize that on Mojave

**Comment by ddbelina** [comment]
Sent snapshot - the big up/down fram is what I would like to move to the left to show a larger download frame.

Thanks, 

Dave


On October 1, 2018 at 8:52:12 AM, parg (notifications@github.com) wrote:

Do you mean the split between sidebar and the right-side content? If so I can resize that on Mojave

**Comment by parg** [comment]
Hmm, where did that snapshot end up?

**Comment by ddbelina** [comment]
Oops!

Sorry

Dave
On October 1, 2018 at 9:45:22 AM, parg (notifications@github.com) wrote:

Hmm, where did that snapshot end up?
