### ISSUE TITLE
Pausing and resuming a checking job resets progress

### ISSUE THREAD

**Issue by Xemnarth** [BiglySoftware/BiglyBT#627]
* Windows 10 Pro
* BiglyBT 1.6.0.1_B14
uTorrent 2.2.1 handles this just fine.

**Comment by parg** [comment]
You mean stopping and restarting a checking job resets progress? There is no 'pause' regarding rechecking

**Comment by Xemnarth** [comment]
No, when pausing a checking job (let say at 30%) and resuming it, it will start downloading from 30% instead of completing the checking process to 100% first. This is a weird behavior.
