### ISSUE TITLE
Menu Items Gray-Out. Only for this software

### ISSUE THREAD

**Issue by googlenews** [BiglySoftware/BiglyBT#63]
I have notice my menu items have been grayed out for the longest while…only the Torrent menu is working properly and I can select from the drop down list.
This has been happening since the previous software, this new software, and even this new update.
Any ideas what can be causing this issue? here are some screen shot of the File, View, Community, Tools, Help menus.

![screen shot 2017-09-16 at 3 35 27 pm](https://user-images.githubusercontent.com/31664007/30515789-78a4c31c-9afc-11e7-9da0-7fdf15aee01b.png)
![screen shot 2017-09-16 at 3 35 10 pm](https://user-images.githubusercontent.com/31664007/30515790-78b13dcc-9afc-11e7-8b29-720343cfe481.png)
![screen shot 2017-09-16 at 3 34 57 pm](https://user-images.githubusercontent.com/31664007/30515791-78b26256-9afc-11e7-92f8-fb3735a4ea60.png)
![screen shot 2017-09-16 at 3 34 42 pm](https://user-images.githubusercontent.com/31664007/30515793-78b397f2-9afc-11e7-86d6-9d1191716f0f.png)
![screen shot 2017-09-16 at 3 34 11 pm](https://user-images.githubusercontent.com/31664007/30515792-78b37b6e-9afc-11e7-82a6-a606470b4688.png)

SWT v4528, cocoa
Mac OS X v10.13, x86_64 (64 bit)
B1.0.2.0/4 az3

**Comment by TuxPaper** [comment]
A recent macOS update has been reported to have fixed menu issues.  Check for an update and see if that fixes it for you.  I think the URL is
https://itunes.apple.com/co/app/macos-high-sierra-beta/id1209167288?l=en&mt=12

**Comment by googlenews** [comment]
I have the latest updates for macOS High Sierra  for my system and current beta of this software. The menu issue is only with this Software app, otherwise to that, it seems to run fine.
If I completely remove software, I would like to resume to my current state and setting, would the software backup function be enough or would I have to do some kind of Apple TimeMachine backup restore?

**Comment by TuxPaper** [comment]
Removing the software with the uninstaller usually keeps your config around.  It's in "~/Library/Application Support/BiglyBT" if you want to back up that folder.

I might have a workaround for the menu issue in a day

**Comment by TuxPaper** [comment]
Interesting, committing code auto-closes Issues.  Will re-open until it's been confirmed in next beta (hopefully coming out with in the next 12 hours)

**Comment by TuxPaper** [comment]
Try B02 and see if things have improved :)

**Comment by googlenews** [comment]
I’ve updated software and still no difference showing the gray out menu (none selectable) items. I’ve also ran disk uitility First Aid to repair permissions.

This issue have ongoing for a few months but since the other forum site had died down, I’m only mentioning it now.

**Comment by googlenews** [comment]
Ok… Menu list items have returned from gray-out state. Problem fixed wit Gold Master update of MacOS.  👍

**Comment by parg** [comment]
Gold Master FTW!
