### ISSUE TITLE
Windows 10.64 downloading intermittent: it's either very good or nothing

### ISSUE THREAD

**Issue by danielwfisher** [BiglySoftware/BiglyBT#632]
I am the latest version of BiglyBT on my machine. Sometimes over the last few weeks it'll work fine and be able to download data. Othertimes, like now, it does not download anything despite having a good internet connection (other apps successfully have incoming connections).

I've checked BiglyBT settings, my VPN's settings (BiglyBT is bound to it), added Firewall rules  allowing BiglyBT connections, and disabled Windows Defender. 

What other things should I be troubleshooting? It is otherwise from what's mentioned above an out of the box BiglyBT install other than I configured it to randomize incoming ports up on startup and bound BiglyBT to my VPN and set to enforce that. I have, coincidentally, turned off the binding entirely, and the result is still the same. Thanks in advance. I know enough to be dangerous and just need some general pointers of what else to look for.

**Comment by parg** [comment]
When it isn't downloading do you have peer connections? Check the PeersView of your download. If you don't try checking the Sources view and see if trackers are reporting errors. 

Generally with a VPN you won't get incoming connections unless you do something to arrange for the VPN for forward connections - some VPNs don't even support doing that.

**Comment by danielwfisher** [comment]
Very helpful, thank you. I was getting peer connections and that was the frustrating part, like it would connect but still not work, but when you said look at my VPN's configuration, although it didn't have a forwarding feature, it does enable a choice of different protocols, so I toyed with those until I found one that works, thereby allowing data to come through to BiglyBT. Thanks very much!
