### ISSUE TITLE
NAT status shows OK but fails NAT/Firewall test

### ISSUE THREAD

**Issue by kcalcopi** [BiglySoftware/BiglyBT#633]
Hi, 

The last few days I’ve had trouble connecting to a private tracker. Upon investigation I have found that although NAT status is showing OK, it is actually failing the connection test and coming up with the following error 

Testing port TCP 26121
Unable to test: Invalid port given, or test service failed. 
Another application may already be using this port. 
(Error: Unexpected end of file from server) 

Any advice on how this may be fixed please?

Cheers 

Karen :)

![bb403bcf-5ba8-4d79-aaf4-6730c8230c35](https://user-images.githubusercontent.com/43843245/46461624-7dbf9f00-c802-11e8-8dfc-00eee6638bec.jpeg)
![f0e55444-f5fb-4d5c-8a0a-ee3e1854ef91](https://user-images.githubusercontent.com/43843245/46461625-7dbf9f00-c802-11e8-8e6a-dd1cda30046f.jpeg)

**Comment by parg** [comment]
If you want the NAT tester to work in BiglyBT you will need to join the beta program (See the help menu)
