### ISSUE TITLE
Ability to set Torrent Created

### ISSUE THREAD

**Issue by Xemnarth** [BiglySoftware/BiglyBT#634]
Ability to set Torrent Created date (e.g. for torrents lacking it)
OR
Make adding torrents with identical hash update Created value too (not just merge trackers)
Also, the 'Reset Date' drop-down option of the 'Date Added' column doesn't seem to have any effect.

**Comment by parg** [comment]
'Reset Date' sets the 'date added' value to the modification date of the .torrent file

**Comment by parg** [comment]
Check B17 - there is a right-click menu in the General view to set creation date
