### ISSUE TITLE
no ability to force seeding in controls

### ISSUE THREAD

**Issue by bleoved** [BiglySoftware/BiglyBT#639]
version 1.6.0.0
SWT v4757, win32
Windows 10 v10.0, amd64 (64 bit)
B1.6.0.0/4 az3
green arrow in controls is greyed out, so there is no ability to force seed a torrent.

**Comment by parg** [comment]
Works for me..

![image](https://user-images.githubusercontent.com/395293/46597113-b13a4c00-cad6-11e8-846d-744a1f1ca87a.png)
