### ISSUE TITLE
[Feature Request] Select Image as Thumbnails (Context Menu Option)

### ISSUE THREAD

**Issue by ldgbc** [BiglySoftware/BiglyBT#642]
Java 1.8.0_181 (64 bit)
SWT v4757, win32
Windows 10 v10.0, amd64 (64 bit)
B1.6.0.0/4 az3

Issue: Can only choose Set Thumbnails for Torrent using File Explorer. The file path always reset to the installation folder (at least it is with Portable mode on at startup).

Request feature: Choose current select image as Thumbnails. For example Torrent include MKV video + a Image (cover image). We should be able to right click on "Cover.jpg" and "Set Select Image as Thumbnails.

Thank you.

**Comment by parg** [comment]
Done in B19 :)

![image](https://user-images.githubusercontent.com/395293/46731921-dfa95a00-cc83-11e8-8dab-067b31aa5617.png)
