### ISSUE TITLE
Tray icon unresponsive.

### ISSUE THREAD

**Issue by Achaean** [BiglySoftware/BiglyBT#644]
Tray icon is completely unresponsive.
It doesn't react to right or left clicking or to double clicking.

Version infos:
Java 1.8.0_181 (64 bit)
  Oracle Corporation
/usr/lib/jvm/java-8-openjdk-amd64/jre

SWT v4757, gtk/3.22.11
Linux v4.9.0-8-amd64, amd64 (64 bit)
B1.6.0.0/4 az3

On Devuan ASCII x64 KDE.

**Comment by Achaean** [comment]
PS. I have this problem, with the latest beta too (B1.6.0.1_B20/4 az3).

**Comment by parg** [comment]
Works ok on Kubuntu - hard to keep up with all the distros :(

**Comment by parg** [comment]
Works ok for me on Kubuntu 18.04 with KDE-Plasma 1.12.6 :(

What does it say in the BiglyBT Help->About?

SWT v4919, gtk/3.22.30 ?

**Comment by HieronymusCH** [comment]
BiglyBT - Help - About:
Java 1.8.0_181 (64 bit)
  Oracle Corporation
/usr/lib/jvm/java-8-openjdk-amd64/jre

SWT v4757, gtk/3.22.30
Linux v4.15.0-24-generic, amd64 (64 bit)
B1.6.0.1_B26/4 az3

**Comment by parg** [comment]
hmm, looks like I might have been testing with a newer SWT at some point. Let me update SWT for you

**Comment by parg** [comment]
OK, version 4922 is up for beta Linux GTK 64-bit users - please update to this and see if that helps

**Comment by Achaean** [comment]
Didn't change something here. :-(

**Comment by parg** [comment]
Just double checking that Help->About BiglyBT shows SWTv4922 ?

**Comment by Achaean** [comment]
Java 1.8.0_181 (64 bit)
  Oracle Corporation
/usr/lib/jvm/java-8-openjdk-amd64/jre

SWT v4922, gtk/3.22.11
Linux v4.9.0-8-amd64, amd64 (64 bit)
B1.7.0.1_B01/4 az3

**Comment by TuxPaper** [comment]
Please download https://s3.amazonaws.com/biglybt-files/test/dorkbox.2018.10.24/dorkbox-systemtray.jar 

While BiglyBT isn't running, and copy it to your biglybt app folder (backup the existing file if you desire)

Let me know if anything improves.  If you run biglybt from a shell, the system tray debug should be at the beginning, and usually starts with a "[", similar to this

```
[OS: {}, Linux]
[Arch: {}, amd64]
[{} {} {}, Oracle Corporation, OpenJDK 64-Bit Server VM, 1.8.0_131]
[Is Auto sizing tray/menu? {}, true]
[Is JavaFX detected? {}, false]
[Is SWT detected? {}, false]
[Java Swing L&F: {}, Metal]
[Auto-detecting tray type]
[Force GTK2: {}, false]
[Prefer GTK3: {}, true]
[Currently using the '{}' desktop environment
, Unknown]
[TT=class dorkbox.systemTray.ui.gtk._AppIndicatorNativeTray]
```

**Comment by TuxPaper** [comment]
With 1.8.00, a new plugin `dorkboxupdater` is installed that should give you a new dorkbox-systemtray jar (after a restart of BiglyBT).

Check to see if this improves anything.  There's also a new option in Options->Interface->System Tray that lets you 'force' usage of the DorkBox-SystemTray.  This might also help.

I'll write a wiki page up soon, but there's also a few other things than one can try:

* Your distro might have a package called `appindicator` or similar.  Installing it might help.
* Gnome has a couple of extensions named "Top Icons".  I've had "Top Icons Redux" work on one distro, and "Top Icons Plus" sort work on another.

**Comment by Achaean** [comment]
> 
>     * Your distro might have a package called `appindicator` or similar.  Installing it might help.
> 

Indeed!
Installing libappindicator3-1, solved the problem! :-)
