### ISSUE TITLE
question about biglybt speed

### ISSUE THREAD

**Issue by moham96** [BiglySoftware/BiglyBT#645]
Hi,
This is a question, not a bug.
I've tried many torrent clients (qbittorent, deluge,transmission...etc) and so far biglybt has been the fastest of them all and I was wondering why? what features biglybt has that makes it faster than others?
one of the key points of my specific setup is that I don't have port forwarding (my ISP doesn't allow port forwarding) so this may be the cause why so many clients have slow download speed, but this doesn't seem to affect biglybt as the speed is blazing fast so how does biglybt accomplish this?

PS: it is not ideal to write questions in github issues, the project needs another way of communicating that can be used for quick questions(irc channel, [discord channel](https://discordapp.com/) or [gitter room](https://gitter.im))

Regards

**Comment by parg** [comment]
BiglyBT does have built in chat - Community menu->Community Chat->Public

It is unusual for someone to question why it is so fast, people usually ask why it is slow ;) And the answer is that I don't know - perhaps your ISP is a BiglyBT fan and doesn't throttle it :)
