### ISSUE TITLE
Remember sub-tabs section position

### ISSUE THREAD

**Issue by Xemnarth** [BiglySoftware/BiglyBT#649]
I've noticed that the sub-tabs section always slightly decreases after restarting the client (check the blue line) making me always re-adjust its height. A similar issue also applies to Advanced List view.
![capture](https://user-images.githubusercontent.com/6406869/46902042-4d959180-cecf-11e8-9f60-b748566156c3.PNG)

**Comment by parg** [comment]
Somewhat typically I can't reproduce this. Obviously it does already attempt to remember the positions of these dividers, it seems that for you it isn't quite doing it correctly...

**Comment by parg** [comment]
Actually I did manage to reproduce it in the 'simple list' view. I think it is because the location is stored as a percentage of height (to support proportional resize) and rounding errors can make things a pixel out now and then

**Comment by parg** [comment]
might be improved in next beta

**Comment by Xemnarth** [comment]
well, it's fixed now! many thanks
