### ISSUE TITLE
Remember files view position

### ISSUE THREAD

**Issue by Xemnarth** [BiglySoftware/BiglyBT#650]
Retain highlighted/selected file position (in other words, scroll position) in the Files sub-tab when minimizing and restoring client window.

**Comment by Xemnarth** [comment]
![capture3](https://user-images.githubusercontent.com/6406869/46940475-de0fd580-d079-11e8-92f3-40a87256c9cf.PNG)

**Comment by parg** [comment]
are you saying it collapses or moves down? For me it appears to stay exactly where it was before minimise

**Comment by parg** [comment]
very odd - doesn't do that for me :(

**Comment by Xemnarth** [comment]
I think it has something to do with 'Update GUI every X s' (mine is set to 1 s). I tried changing it to 10 s and the list stopped refreshing in that strange behavior.

**Comment by Xemnarth** [comment]
the issue still happens on a fresh installation on a different system... I don't think you're reproducing the issue correctly

**Comment by Xemnarth** [comment]
I think I was able to pinpoint the issue. If I minimize client window for more than 1 seconds and restore it, the 'Files' tab resets view (deselecting any files and returning to to top of the list). If you minimize and restore the client window in under 1 second, you wont have this reset issue.

**Comment by Xemnarth** [comment]
this issue still not fixed as of 1.7.0.1_B28

**Comment by DeoW** [comment]
I cannot reproduce the error. My Library view is split vertically (not horizontally), and the Upload portion dragged to the left to occupy almost the whole window. The selected file (or more than one, adjacent or separated) remains selected after minimising the BBT window.

**Comment by Xemnarth** [comment]
Can you perhaps include a screenshot to better visualize your example?
Thanks!

**Comment by DeoW** [comment]
As to screenshots, I do not know how to obfuscate the details of my torrents. I know how to use the snipping tool, but graphics is a weakness of mine. As to settings: Options>Interface>Tables Library section, "Advanced View download split mode (Restart Required)". I have "Left Incomplete, Right Complete" which results in DLs left, ULs Right. The two halves are sizeable by dragging on the separator between them. So if I am looking at ULs, I drag the UL window-half to be almost all of the window. That gives me the width I need for the columns I want, and the DL window is empty for most of the time, so being not visible is fine. My DLs are fast, hence over soon, while ULs take much longer.

**Comment by DeoW** [comment]
Type "Split" into the Options "search" input field at the bottom of the "Options" window. It will lead you to the correct place.

**Comment by Xemnarth** [comment]
Do you have 'Show sub-tabs in Library views' enabled?

**Comment by DeoW** [comment]
Yes

**Comment by Xemnarth** [comment]
Strange. The issue is still there in my case.

**Comment by DeoW** [comment]
Very strange!

**Comment by Xemnarth** [comment]
Only when the files list is viewed under torrent details that it behaves
normally

**Comment by DeoW** [comment]
Weird. Mine is fine, behaves exactly as expected in Library View. I do not think I can be of use further. I suspect the problem is within your device/settings interaction, and specific to your device, if your settings are as I have come to see them.

**Comment by Xemnarth** [comment]
Guess I need to grant remote desktop access to a mod to better understand my client behavior... OR try a new installation on a freshly installed OS (I'm thinking to experiment with VMs).

**Comment by DeoW** [comment]
A Screen Snip of the "Split" option is at https://jmp.sh/ExwsBbp  if you want to try it. (the layout is a bit defferent to when I last spoke about it)
I have been summoning up courage to try VMs for a while - I have some legal XP software that will only run on XP. I hope you have success in your endeavours!
