### ISSUE TITLE
if i click "import Vuze settings" with standard update/install biglybt, then removes all my last torrents from biglybt panel : /

### ISSUE THREAD

**Issue by KonoromiHimaries** [BiglySoftware/BiglyBT#659]
https://github.com/BiglySoftware/BiglyBT/releases/tag/v1.7.0.0

* OS and version w10
* BiglyBT Version Number 1.6.0.0 to 1.7.0.0
* For *nix: Desktop Environment

**Comment by TuxPaper** [comment]
Thanks for the report.  Yes, checking the Migrate button will migrate Vuze settings over top of any existing BiglyBT ones.  The checkbox should have been turned off if it detected you had an existing BiglyBT config, but as you notices, you can click it back on again.

I've just added a "Are you sure?" Dialog box for this use case, when you click the checkbox and already have a config.  I've also added a quick backup of the biglybt config files if one presses Yes anyway.

But none of that helps you, unfortunately.  Did you have BiglyBT set up to do autamatic config backups?  If you do, restore those files!
