### ISSUE TITLE
IP connections (IPv4 and IPv6) stay in "Connecting" or "Pending" for a long long time

### ISSUE THREAD

**Issue by david-bakin** [BiglySoftware/BiglyBT#664]
[Windows Server 2012 R2; BiglyBT 1.7.0.1_B01 but it's been happening for quite a few recent (beta) versions.  Server is wired to a Google Wifi hub which is wired to the cable modem.  Google Wifi is implementing the firewall and is in the DMZ of the cable modem to let everything go through.]

I have a lot of torrents which, when started, will _try to_ connect to anywhere from 4 to 15 peers but in fact all the connections stay in Connecting or Pending for a long long time.  Every once in awhile one or two connections will proceed to Fully Established.  I haven't actually timed it but the timeframe on this is several minutes.

Meanwhile other torrents will start, peers connect just fine, transfers happen at top speed, all is well.

I'm suspecting some networking problem on my end (IOW not something with BiglyBt) - either with the cable modem or google wifi or something ... but what could I be looking for?

[BTW, I'm able to get incoming TCP connections but not incoming UDP or uTP, for some reason I haven't yet figured out, even though Google Wifi is set to forward both TCP and UDP ports (same port number) to my server.]

**Comment by parg** [comment]
Pending means that you have hit BiglyBT connection limits and network activity is yet to start - could be that these are queued up behind the 'connecting' ones.

As for what might be causing them to stall, I can't think of anything torrent specific unless there is something weird with the tracker and it is returning fake peers that perhaps stall the TCP connection process?

Have you checked UDP incoming in the NAT test tool? See the help ,menu

**Comment by david-bakin** [comment]
UDP incoming succeeded in the test tool (as did everything else). It might actually be my server/Wifi/modem combination.  I'll investigate that.
