### ISSUE TITLE
Bigly needs to stay closed when you double click a torrent file to start downloading

### ISSUE THREAD

**Issue by psychokilla** [BiglySoftware/BiglyBT#668]
Currently it opens the program. But remember how vuze would keep the program closed? I cannot find the setting in options either.

**Comment by parg** [comment]
How about the options under Tools->Options->Interface->Alerts:

Show main windows when a download is added by another application
etc.

**Comment by psychokilla** [comment]
Thank you Sir, I had not double clicked interface to open the draw down menu.
