### ISSUE TITLE
Multiple tag selection

### ISSUE THREAD

**Issue by Xemnarth** [BiglySoftware/BiglyBT#674]
Ability to select multiple tags from the sidebar to show up in the same window

**Comment by parg** [comment]
Use a Tag Group? Multi-select in the sidebar isn't going to be implemented any day soon...

Of course you can enable Tag buttons in the Library view and multi-select these

**Comment by TuxPaper** [comment]
My favorite way is to make a new tag and have a constraint of `hasTag("foo") && hasTag("bar")` Unfortunately we don't have an `isTagGroup("tar")` (yet? :D)

You can also go to Tags Overview, multi-click there, and chose the Torrents subview

**Comment by parg** [comment]
Added 'hasTagGroup( "tar")' in next beta

**Comment by Xemnarth** [comment]
what does this do?

**Comment by parg** [comment]
It means you can write a Tag Constraint with a value, say, hasTagGroup( "meh" ) and that Tag will automatically have all downloads that are assigned to Tags that had a group of "meh" being assigned to it.
