### ISSUE TITLE
Can't decode character set

### ISSUE THREAD

**Issue by Xemnarth** [BiglySoftware/BiglyBT#677]
Can't decode character set of files in this .torrent: https://mega.nz/#!ewUQ3KaB!KqZHsEy3Ke7XL_40RTtdRNN5E6MD9plFBmMbiZDgiO4
Tip: uTorrent reads it just fine

**Comment by Xemnarth** [comment]
similar to https://github.com/BiglySoftware/BiglyBT/issues/629

**Comment by Xemnarth** [comment]
any update?

**Comment by TuxPaper** [comment]
1.7.0.1 B31 now has a Torrent Encoding entry in the Torrent Information section of the Open Torrent Options window.  Click it and it should ask you for a new encoding.  Torrents with "utf8 keys" encoding aren't changeable.

![image](https://user-images.githubusercontent.com/725353/50542092-aa1c5a80-0b68-11e9-8db7-b54bcb0e9ed0.png)

This is not the full solution, just a workaround, so I won't close the issue.  We should be reading the perfectly valid UTF-8 keys within the .torrent, but instead are reading the non-UTF-8 ones, which have not been encoded to the locale that the .torrent specified (In this case, the .torrent file told us the non-UTF-8 keys were Shift_JIS, when they were really GBK encoded)

**Comment by marcussacana** [comment]
I'm with this problem, this window appears but don't shows the 'utf-8' option that is the right encoding of my torrent.

**Comment by djdv** [comment]
@marcussacana 
I was having a similar issue. The encoding I needed was not 'utf-8', but it was also not in the list of encodings I was prompted with.
When I enabled this option, the encoding I needed appeared and worked fine.
Options>Files>Torrents>Decoding Character Sets> Show less likely encodings
![opt](https://user-images.githubusercontent.com/13862850/70382051-9f934500-1923-11ea-9e22-e4bc66cabecc.png)

(thanks to the devs who worked on settings search feature 🙏)

**Comment by marcussacana** [comment]
@djdv thanks for the advice, I don't remember even what I torrent I had this problem anymore but i'm sure will help in my future downloads.
