### ISSUE TITLE
Un-needed confirmation when manually canceling download.

### ISSUE THREAD

**Issue by Galane** [BiglySoftware/BiglyBT#686]
After deleting a torrent there's a window that pops up to say that it was manually canceled. Well DUH! I know that already because *I* stopped it.

It's like if cars had a message on a heads up display that said "Your vehicle has stopped because you pressed the brake pedal."

**Comment by parg** [comment]
If you can find time between your finishing lessons, please post a screenshot and steps to reproduce this.

**Comment by Galane** [comment]
Close the operation in progress dialog when it stops at no sources found. Right click the metadata download, go to delete, select delete from computer. The operation in progress dialog pops back up to inform the user of what they already know. It failed. It was manually canceled.

![deleted](https://user-images.githubusercontent.com/31779300/47640592-82d5ec80-db29-11e8-88bb-c6ea8a0fc4c8.jpg)

**Comment by parg** [comment]
Select 'Suppress File Download popup dalog' under Tools->Options->Display: Various

**Comment by parg** [comment]
OK, I'll bodge something for the next beta

**Comment by Galane** [comment]
Thanks. :)
