### ISSUE TITLE
Number of seeds not matching availability

### ISSUE THREAD

**Issue by Galane** [BiglySoftware/BiglyBT#687]
Win 10 x64 BiglyBT 1.7.0.0

I'm looking at a torrent where it says there are 3 seeds but in the piece map the blocks all show 1 or 2. 2 are all blue, 1 are all white - and it's working on downloading the white blocks *extremely slowly*.

If there really are 2 other seeds with this file, why isn't BiglyBT downloading from *them*?

mlDHT in Sources says there are *4* seeds. There are 2 trackers with 3 seeds, 7 with 2 seeds, and several more with 1 seed. Given that the 1 seed it's downloading like dialup from could be connected to all the trackers showing seeds, that's still 2 or 3 it's apparently ignoring.

I'm using a VPN and in BiglyBT have it set to require encrypted transport, not allow unencrypted incoming or outgoing, and use the cryptoport tracker extension.

**Comment by parg** [comment]
Trackers report seed/peer potential availability. They can be inaccurate (seed computer went to sleep without de-registering from the tracker) or the seeds may not be connectable (you and the seed are both behind non-traversable NAT), Or your VPN might be in their IP filter block list. So use those numbers as a guide not an absolute.
