### ISSUE TITLE
Beta Version Setup - Link not working

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#690]
![biglybt beta](https://user-images.githubusercontent.com/37715552/47694305-82922b80-dbd3-11e8-90cc-8b6e9ee407eb.png)

Clicking the marked link results in a page not found. Link points at https://www.biglybt.com/beta.  It should probably point at https://github.com/BiglySoftware/BiglyBT

Windows 10 1803
Biglybt 1.6.0.0

**Comment by parg** [comment]
Fixed in latest betas!
