### ISSUE TITLE
Existing folder torrent files on PC rewritten as BiglyBT files (without permisso)

### ISSUE THREAD

**Issue by nothus1** [BiglySoftware/BiglyBT#694]
I just installed BiglyBT yesterday and upon turning on my PC today - discovered that all of my saved folder of torrent files have been converted to BiglyBT files - that will not work on my other programs (uTorrent, et al.) now... what gives?

**Comment by parg** [comment]
Nothing has been 'converted', it is just that the default program for opening a .torrent file has switched to BiglyBT. Simply right-click on the .torrent file and select 'Open With...'
