### ISSUE TITLE
Statistic Country Stats is showing nothing

### ISSUE THREAD

**Issue by PrototypeZero** [BiglySoftware/BiglyBT#698]
The new in 1.7.0.0 feature never shows any statistics, it always shows..

Samples: 0, population: 0, throughput

...and nothing else.

This is on multiple PCs running multiple downloads and seedings, they all fail to show anything.

Also 2 identical "Pop out..." options are shown instead of one when you right click on any of the tabs under statistics.

Running under Windows 10 Pro, x64 in Classic UI/Advanced.

**Comment by parg** [comment]
Works for me - did you disable the DHT?

**Comment by PrototypeZero** [comment]
> 
> 
> Works for me - did you disable the DHT?

Didn't know it needed DHT, but its on anyway (I never turn it off).

**Comment by parg** [comment]
Can you join the beta prog (Help menu option), wait for BiglyBT to update and then check the BiglyBT DDB view to see if things are working?

**Comment by parg** [comment]
If you do manage to join the beta program then check out the 'local' country statistics tab to at least see if that works
