### ISSUE TITLE
Move Data on Tag Change

### ISSUE THREAD

**Issue by Xemnarth** [BiglySoftware/BiglyBT#701]
Is it possible to instruct BiglyBT to actually move data files (if any) on assigning a new tag to its 'Initial Save Location' like how qBittorrent does with automatic torrent management?

Note: the current 'Move data' tag option doesn't work.

**Comment by parg** [comment]
There is an 'Apply To Current' right-click Tag option under the Files menu

**Comment by parg** [comment]
As far as I can remember it re-applies the move-to operation to all the downloads currently assigned to the Tag

**Comment by Xemnarth** [comment]
and that includes actually moving data files or just changing their location?

**Comment by parg** [comment]
well changing their location is moving them isn't it?

**Comment by Xemnarth** [comment]
not really

**Comment by Hetsig** [comment]
i would love this feature as well. the only current feature that qbittorrent have over bigly is just this.
an option in the "execute on assign" list it could be under "move to initial save location".
if that might be too much moving while downloading something the "move on complete" could also be used to move it after it's done and auto assigne the moved location directory to initial saved location.
