### ISSUE TITLE
Disable automatic Uploaded value setting

### ISSUE THREAD

**Issue by Xemnarth** [BiglySoftware/BiglyBT#703]
When you add a partially downloaded torrent to BiglyBT, it'll always assign an uploaded value equal to its calculated downloaded value, which normally should always be 0 uploaded byte for accuracy. Can we specify an option for that or disable it?

**Comment by parg** [comment]
Just reset the upload stats by right-clicking on the download in the 'uploaded' column

**Comment by Xemnarth** [comment]
you mean the 'Set Uploaded' option?

**Comment by parg** [comment]
right - set it to 0 or whatever

**Comment by Xemnarth** [comment]
can we make an option to auto-set 0 byte uploaded for such torrents upon addition? thank you
