### ISSUE TITLE
Provide a way to verify the download

### ISSUE THREAD

**Issue by WPFilmmaker** [BiglySoftware/BiglyBT#706]
First of all thank you for the new release!
I would like to request a way to verify the download from the github page. I am assuming that most of users who already have BBT installed updated through the software, however for new installs there is no way to verify the download. Could you please add a sha256sum or pgp?
Thank you.

**Comment by TuxPaper** [comment]
I've put sha1sum.txt and sha256sum.txt in the current github release.  I'll make a note to generate these on future releases.

As you probably already know, to check, ensure both the installer and the txt file are in the current path, and

```
sha256sum --ignore-missing -c sha256sum.txt
```

**Comment by WPFilmmaker** [comment]
Thank you very much! I would add it to https://www.biglybt.com/download/ as well as I noticed that it is not present there, maybe you could add such instructions on how to verify in the download page as well?It would be useful!
