### ISSUE TITLE
Max # of torrents not respected ?

### ISSUE THREAD

**Issue by eurobank** [BiglySoftware/BiglyBT#709]
Windows 10/64 bit. It seems that while my max simultaneous downloads are set to 2 and max active torrents are set to 3, this is not respected.

Any ideas ?

Thanks

![2018-11-06 11_57_34-window](https://user-images.githubusercontent.com/4467158/48057113-e7451b80-e1bb-11e8-9c5c-68f5d5647457.png)

![2018-11-06 12_02_40-window](https://user-images.githubusercontent.com/4467158/48057125-eca26600-e1bb-11e8-8b86-3a9a043f464f.png)

**Comment by Havokdan** [comment]
Dont count torrent as using a download slot if speed is below 128 kbps?
In your screenshot, only one slot meets this rule. So as long as a second torrent also fulfills, it will activate the others, will not it?

**Comment by eurobank** [comment]
Oops. Never thought it works like that.

Thanks !
