### ISSUE TITLE
PIA VPN Helper is still NOT working

### ISSUE THREAD

**Issue by DeathStalker77** [BiglySoftware/BiglyBT#710]
Current version of BBT.

Message I get is -

VPN HAS WARNINGS
✔ BiglyBT UDP is currently bound to /1XXX.XXX.XXX.XXX aka eth0 (Private Internet Access Network Adapter)
✔ Found bindable address /XXX.XXX.XXX.XXX on eth0 (Private Internet Access Network Adapter) which is likely VPN's local IP
✔ Non-BiglyBT probably routing through /XXX.XXX.XXX.XXX aka eth0 (Private Internet Access Network Adapter). Same as bindable address :)
✔ Excellent, BiglyBT already bound to eth0
⌘ Could not get Forwarding Port.  Set user/pass in plugin config.

I am using the newest PIA client, v0.9.3 Beta (build 01708)

**Comment by TuxPaper** [comment]
Working on a new version.

A possible workaround is to go to the VPN Helper config, and under "PIA", blank out the "Login" value (cut), and re-enter it (paste).  This will solve one bug I found where the value shown isn't being used, but it won't solve any other issues :(

**Comment by TuxPaper** [comment]
Latest plugin version should work with new PIA client
