### ISSUE TITLE
uTorrent RESUME.DAT Import

### ISSUE THREAD

**Issue by DeathStalker77** [BiglySoftware/BiglyBT#711]
I posted this originally when this was still in Beta.

I just ran some tests and have to admit, that the speeds I got, even over VPN, were impressive.  The only problem is the need to be able to successfully import the resume.dat file from uT.  I WAS able to successfully (with a couple exceptions, mostly due to incomplete files and the converter not recognizing the .!ut extension) import ~2100 titles in QBT.  So I'm hoping you can build on their devs' base and do this for BiglyBT.

Thanks!

**Comment by hatewesterncivilization** [comment]
Super must-have thing for years now. Include also Tixati, so on support.

**Comment by TuxPaper** [comment]
There's now a pre-release of a uTorrent migration plugin at https://github.com/BiglySoftware/BiglyBT-plugin-migratetorrentapp

Plugin (.biglybt file) can be downloaded at https://github.com/BiglySoftware/BiglyBT-plugin-migratetorrentapp/releases

I realize that anyone reading this issue probably has already dealt with migration manually, however, if you would like to test it, we'd appreciate the help and feedback.

Any issues, feedback, or feature requests can be made using that GitHub projects Issue Tracker.
