### ISSUE TITLE
Standard Date Format

### ISSUE THREAD

**Issue by DeathStalker77** [BiglySoftware/BiglyBT#712]
Instead of the ex, Nov 07 9:22PM format, could we please get a 11/07/2018 9:22PM format?  (And obviously, 07/11/2018 for European countries - based on the language selected?)

Thanks!

**Comment by parg** [comment]
The column date formats are localis/zable via

column.date.formats=EEEE, MMMM d, yyyy GG; EEEE, MMMM d, yyyy; EEE, MMMM d, yyyy; MMMM d, ''yy; EEE, MMM d, ''yy; MMM d, yyyy; MMM d, ''yy; yyyy/MM/dd; ''yy/MM/dd; MMM dd; MM/dd

The format chosen depends on column width.

You can set a custom date format for all tables under Tools->Options->Interface->Tables: Custom Date Format or on a per-column basis by right-clicking on the column header
