### ISSUE TITLE
Not Clear On TheSimple List vs Advanced List

### ISSUE THREAD

**Issue by DeathStalker77** [BiglySoftware/BiglyBT#713]
I prefer the thin-lined view of the Advanced List, but I do not see any appreciable difference between the 2 - it just seems to be more of a waste of space.  You could collapse the TITLE/Name into one line (limited by the length of the field the user chooses.  I see no reason to waste so much space with 2 lines per title, nor do I see any advantage provided by the "Advanced List".

Thanks.

**Comment by parg** [comment]
The Simple list has different column defaults and also merges downloading/seeding tables into one view for those that have both. Just pick the one you prefer. There is also an option somewhere to remove the simple view type completely.

**Comment by parg** [comment]
You can right-click in the header area:

![image](https://user-images.githubusercontent.com/395293/48306964-df2e0880-e53a-11e8-8d06-d9072a648e01.png)
