### ISSUE TITLE
Auto-speed page showing incorrect values (wrong unit!)

### ISSUE THREAD

**Issue by Kadigan** [BiglySoftware/BiglyBT#714]
The calculations between "Mibit/s" and "KiB/s" are unclear and erroneous. It's not immediately clear why I have to put in 3052 to get "25 Mibit/s" when it should be 3200, or 18310 for "150 Mibit/s" when it should be 19200.

![image](https://user-images.githubusercontent.com/16637976/48299187-e23ce080-e4c9-11e8-8dc2-f849c754acbd.png)

**It becomes clear when you realize the page means "Mbit/s", not "Mibit/s".** The 'i' stands for "binary" in there, so 1 Mibit = 1024 Kibit - meanwhile, to arrive at "3052" I need to treat the "Mibit" value as decimal (1 Mbit = 1000 Kbit), thereby "3052 *8 *1024 /1000 /1000 = 25.00". Similarly, "18310 *8 *1024 /1000 /1000 = 149.99".

**Please fix the units, or better yet - provide a wider explanation on that page.**

The MiB/s calculations higher in that section (2.98 MiB/s and 17.88 MiB/s, respectively) are accurate.

_(For a good second there, I was under the impression that the algo took some overhead into consideration.)_

**Versions:**
* Java 1.8.0_191 (64 bit)
* SWT v4922, win32
* Windows 7 v6.1, amd64 (64 bit)
* B1.7.0.0/4 az2

**Comment by parg** [comment]
Indeed, thanks for reporting (and I'm sure there are more places where such errors exist...)

**Comment by parg** [comment]
For example I know many config values are stored internally as 'K' (e.g. some speed limits, say 5 for example) - so these will render as either 5Kib or 5KB depending on which unit display you select. That is they won't be converted from 1024 <-> 1000 basis. This ain't gonna change any time soon as it would require reworking to internally store them as bytes not 'K'.

**Comment by parg** [comment]
1701_B13 might be better

**Comment by Kadigan** [comment]
I see. Well, as long as you're aware of the issue and plan to fix it at _some_ point... ;)

**Comment by parg** [comment]
Have you tried the beta? Help menu has an option to get it

**Comment by parg** [comment]
Closed due to no user feedback
