### ISSUE TITLE
Hash Checking Of Existing Files

### ISSUE THREAD

**Issue by DeathStalker77** [BiglySoftware/BiglyBT#716]
I just tried adding a torrent that I already have downloaded, and BBT wanted to allocate and re-start the DL from zero.  I Saw no option "Skip Hashcheck".

**Comment by Havokdan** [comment]
I think this applies to BiglyBT yet:https://wiki.vuze.com/w/Seed_an_existing_file

**Comment by DeathStalker77** [comment]
That option still re-hashes the file, it does not skip it like the option in uT does.
