### ISSUE TITLE
can't even launch the app

### ISSUE THREAD

**Issue by exekutive** [BiglySoftware/BiglyBT#721]
OS10.14
this is what I could get out of the console

error	23:54:18.365107 -0800	Dock	Unable to load Info.plist exceptions (eGPUOverrides)
default	23:54:18.378332 -0800	CommCenter	27366555: RECEIVED OUT-OF-SEQUENCE NOTIFICATION: 0 vs 216, 256, <private>
default	23:54:18.378676 -0800	CommCenter	#I handleLSNotitifcation_sync: Application launched: <private>
default	23:54:18.378799 -0800	loginwindow	-[ApplicationManager checkInAppContext:refCon:eventData:] | enter
default	23:54:18.379376 -0800	loginwindow	-[PersistentAppsSupport applicationLaunched:] | enter. clearing logout in progress and last logout time
default	23:54:18.379411 -0800	loginwindow	-[PersistentAppsSupport applicationReady:] | App: BiglyBT, ready, updating active tracking timer
default	23:54:18.379437 -0800	loginwindow	-[PersistentAppsSupport(Internal) updateActiveTrackingTimer] | Creating timer
default	23:54:18.379479 -0800	loginwindow	-[ApplicationManager checkInAppContext:refCon:eventData:] |      checked in app : BiglyBT
default	23:54:18.390419 -0800	mds	directQueryFetchResultsReply 36866 1795162112 35
default	23:54:18.390591 -0800	mds	directQueryFetchResultsReply 36865 1795162112 35
default	23:54:18.490432 -0800	CommCenter	#I handleLSNotitifcation_sync: Application exited: <private>
default	23:54:18.490622 -0800	Dock	27366555: RECEIVED OUT-OF-SEQUENCE NOTIFICATION: 135 vs 201, 258, <private>
error	23:54:18.491060 -0800	contextstored	Death of untracked active application: <private>
default	23:54:18.491404 -0800	loginwindow	27366555: RECEIVED OUT-OF-SEQUENCE NOTIFICATION: 128 vs 259, 258, <private>
default	23:54:18.491867 -0800	loginwindow	-[PersistentAppsSupport applicationQuit:] | for app:BiglyBT, _appTrackingState = 2
default	23:54:18.491903 -0800	loginwindow	-[PersistentAppsSupport applicationQuit:] | App: BiglyBT, quit, updating active tracking timer
default	23:54:18.491929 -0800	loginwindow	-[PersistentAppsSupport(Internal) updateActiveTrackingTimer] | Extending timer
default	23:54:18.505071 -0800	locationd	{"msg":"kCLConnectionMessageWatchdog", "event":"activity", "this":"0x7fa8a0c80030", "registrationRequired":0, "registrationReceived":1}
default	23:54:18.687760 -0800	locationd	{"msg":"kCLConnectionMessageWatchdog", "event":"activity", "this":"0x7fa8a2c06af0", "registrationRequired":0, "registrationReceived":1}
default	23:54:20.504506 -0800	kernel	com.apple.p2p: IO80211AWDLPeerManager::setAwdlOperatingMode Setting the AWDL operation mode from AUTO to SUSPENDED
default	23:54:20.504521 -0800	kernel	com.apple.p2p: AWDL is suspended
default	23:54:20.635027 -0800	kernel	com.apple.p2p: IO80211AWDLPeerManager::setAwdlOperatingMode Setting the AWDL operation mode from SUSPENDED to AUTO
default	23:54:20.635040 -0800	kernel	com.apple.p2p: IO80211AWDLPeerManager::exitAwdlSuspendedMode Resuming AWDL from SUSPEND  mode
default	23:54:20.635340 -0800	kernel	com.apple.p2p: AWDL is off
default	23:54:21.388880 -0800	locationd	{"msg":"kCLConnectionMessageWatchdog", "event":"activity", "this":"0x7fa8a0e0f6c0", "registrationRequired":0, "registrationReceived":1}
default	23:54:22.141540 -0800	UserEventAgent	{"msg":"CLLocationManager", "event":"activity", "_cmd":"appsUsingLocationWithInfo", "self":"0x7fff9c703fd8"}
default	23:54:22.141462 -0800	LocationMenu	{"msg":"CLLocationManager", "event":"activity", "_cmd":"appsUsingLocationWithInfo", "self":"0x7fff9c703fd8"}
default	23:54:22.141717 -0800	UserEventAgent	{"msg":"CLCopyAppsUsingLocation", "event":"activity"}
default	23:54:22.141583 -0800	LocationMenu	{"msg":"CLCopyAppsUsingLocation", "event":"activity"}
default	23:54:22.142916 -0800	LocationMenu	{"msg":"CLLocationManager", "event":"activity", "_cmd":"appsUsingLocationWithInfo", "self":"0x7fff9c703fd8"}
default	23:54:22.142992 -0800	LocationMenu	{"msg":"CLCopyAppsUsingLocation", "event":"activity"}
default	23:54:23.493012 -0800	loginwindow	-[PersistentAppsSupport(Internal) writeCurrentPersistenceState:] | enter. Timer fired, writing a snapshot to disk
default	23:54:23.493199 -0800	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] | entered. isSnapShot:1
default	23:54:23.493248 -0800	loginwindow	-[PersistentAppsSupport(Internal) checkAndSetEarlySaveStateExitCriteria:] |      logout was not already in progress
default	23:54:23.493278 -0800	loginwindow	-[PersistentAppsSupport(Internal) checkAndSetEarlySaveStateExitCriteria:] |      exit: 0
default	23:54:23.493445 -0800	loginwindow	-[PersistentAppsSupport(Internal) shouldSaveState:finalSnapShot:] |      exit: 1
default	23:54:23.493475 -0800	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] | saveState == YES, gathering save state
default	23:54:23.493648 -0800	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |      frontToBackAppArray: (
    "LSASN:{hi=0x0;lo=0x55055}",
    "LSASN:{hi=0x0;lo=0x41041}",
    "LSASN:{hi=0x0;lo=0x11011}",
    "LSASN:{hi=0x0;lo=0x34034}"
)
default	23:54:23.493696 -0800	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |      getting previous list so we don't change the hidden or background state values if they were not resumed
default	23:54:23.494194 -0800	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |      previouslyRunningApps: (
        {
        BackgroundState = 2;
        BundleID = "com.apple.console";
        Hide = 0;
        Path = "/Applications/Utilities/Console.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.azureus.vuze";
        Hide = 0;
        Path = "/Applications/Vuze.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.finder";
        Hide = 0;
        Path = "/System/Library/CoreServices/Finder.app";
    },
        {
        BackgroundState = 2;
        BundleID = "org.mozilla.firefox";
        Hide = 0;
        Path = "/Applications/Firefox.app";
    }
)
default	23:54:23.494290 -0800	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |      frontToBackCount: 4
default	23:54:23.495700 -0800	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |      checkAgainstApp is : Console
default	23:54:23.495748 -0800	loginwindow	-[PersistentAppsSupport appShouldBeRelaunched:] | entered. checking app: Console
default	23:54:23.495777 -0800	loginwindow	-[PersistentAppsSupport appShouldBeRelaunched:] |      returning: 1
default	23:54:23.495805 -0800	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |           Adding to relaunchArray: Console
default	23:54:23.496499 -0800	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |      checkAgainstApp is : Vuze
default	23:54:23.496532 -0800	loginwindow	-[PersistentAppsSupport appShouldBeRelaunched:] | entered. checking app: Vuze
default	23:54:23.496559 -0800	loginwindow	-[PersistentAppsSupport appShouldBeRelaunched:] |      returning: 1
default	23:54:23.496586 -0800	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |           Adding to relaunchArray: Vuze
default	23:54:23.497743 -0800	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |      checkAgainstApp is : Finder
default	23:54:23.497766 -0800	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |           Adding to relaunchArray: Finder
default	23:54:23.498367 -0800	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |      checkAgainstApp is : Firefox
default	23:54:23.498390 -0800	loginwindow	-[PersistentAppsSupport appShouldBeRelaunched:] | entered. checking app: Firefox
default	23:54:23.498409 -0800	loginwindow	-[PersistentAppsSupport appShouldBeRelaunched:] |      returning: 1
default	23:54:23.498430 -0800	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |           Adding to relaunchArray: Firefox
default	23:54:23.498453 -0800	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |      checking for Stopped apps
default	23:54:23.501396 -0800	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |      no stopped apps found
default	23:54:23.501494 -0800	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |      Writing dictionary to prefs
default	23:54:23.501570 -0800	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |           Contents:(
        {
        BackgroundState = 2;
        BundleID = "com.apple.console";
        Hide = 0;
        Path = "/Applications/Utilities/Console.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.azureus.vuze";
        Hide = 0;
        Path = "/Applications/Vuze.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.finder";
        Hide = 0;
        Path = "/System/Library/CoreServices/Finder.app";
    },
        {
        BackgroundState = 2;
        BundleID = "org.mozilla.firefox";
        Hide = 0;
        Path = "/Applications/Firefox.app";
    }
)
default	23:54:23.503033 -0800	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |      setting _stateSaveInProgress to NO and exiting

**Comment by jeolefmo** [comment]
Hi guys,

I have been unable to run Vuze on my MacBook Pro (Mojave 10.14) for a year or two due to installation issues and the app freezing on startup. I have since been using a range of inferior torrent clients trying to find something relatively suitable, but have been left disappointed at every avenue. 

I heard about BiglyBT and got very excited!
However, once installed I have found that it has similar issues to what Vuze was showing.
After installation, BiglyBT does not even start up. As I open the app, its name appears in my toolbar for around 1-2 seconds and then disappears as it fails to boot.

I'm no programmer, but there must be something incompatible with the newer versions of MacOS and the coding within Vuze and BiglyBT.
I would love to get this app working, and I will do anything I can to assist you in providing information to this issue.
Let me know what information you need to get this sorted out, and I'll help you as much as I can.

**Comment by hatewesterncivilization** [comment]
I'm think, if Paul and Tuxpaper interesting, they can do remote conversations with yours PC's and take a look the problems. And then undoubtedly fix and eliminate it.

**Comment by exekutive** [comment]
Newer version worked.
