### ISSUE TITLE
BiglyBT slow startup

### ISSUE THREAD

**Issue by WPFilmmaker** [BiglySoftware/BiglyBT#722]
Every time I run BiglyBT from "cold" it takes roughly 15 seconds to reach the torrent menu (no torrents), roughly 5 to draw the interface and then several seconds of loading stuff.

I have 12gb of ram (not ssd though) and to me it seems a bit too much given it is not a heavy software like photoshop. In comparison Transmission opens instantly wheras Fostwire (written in Java like BiglyBT) takes even longer than 15 seconds.

I assumed it depends on the fact that it is written in Java. I don't want to criticize your software and don't intend to switch to Transmission, but we you make the booting a bit faster?Is there room for optimization?
 
Lubuntu 16.04, LXDE BiglyBT 1.7.0

**Comment by parg** [comment]
Not much that can be done, there's a lot of Java classfile loading, linking, dynamic compilation etc. going on.

**Comment by WPFilmmaker** [comment]
Thanks for your answer;)

**Comment by parg** [comment]
"AppCDS" looks like it might be worth investigating sometime, thanks

**Comment by parg** [comment]
On my system using AppCDS seemed to speed up the time taken to get the UI fully loaded from around 7 seconds to around 6 - not really worth the effort especially as this was for a minimally loaded client. If you have a number of torrents to also load this will increase load time on top of this as each torrent requires loading and setting up.

**Comment by hatewesterncivilization** [comment]
Get an ramdisk app like Gilisoft ramdisk or Primo Ramdisk and place on it whole Bigly's dir, and you will go on.

Mega fast config files writing-reading and jet startup and running. Just do some backuping this Bigly's dir with soft like Ease Todo Backup and so on.
