### ISSUE TITLE
Cannot install BiglyBT

### ISSUE THREAD

**Issue by JBSpigot** [BiglySoftware/BiglyBT#723]
Whenever I attempt to install BiglyBT I get all the way to the end. Then windows states that it cannot create the start file. Pressing "try again" doesn't seem to work.

![image](https://user-images.githubusercontent.com/45129349/48664599-163a7780-ea6f-11e8-94f4-449be19f53e7.png)

* OS and version Windows 7 64
* BiglyBT Version Number 1.7.0.0
* For *nix: Desktop Environment

**Comment by TuxPaper** [comment]
Not sure what to make of that one.  The installer is set to skip making a Start Menu link if it receives an error, but there it is in your screenshot!  Can you check if there's already a BiglyBT.lnk in that path, or if the path exists/is writable?

**Comment by JBSpigot** [comment]
You nailed it... there was an identical path of the same name from a previous install attempt. Changed name of the file in that path during installation and it installed just fine
