### ISSUE TITLE
About auto-stopping torrents...

### ISSUE THREAD

**Issue by Xemnarth** [BiglySoftware/BiglyBT#724]
![tempsnip](https://user-images.githubusercontent.com/6406869/48759707-67d84180-ecbd-11e8-92d2-dffd7c356303.png)
How does this actually work?

**Comment by parg** [comment]
'First Priority' (FP) seeds take preference over non-FP seeds when being scheduled for upload after completing. The main driver is usually to get a decent share-ratio before they get relegated to the non-FP pool that are scheduled only when there is room. 

If you mess around with the FP rules this can cause downloads to drop down to the non-FP pool and become queued (the comment here about being 'stopped' actually means 'stopped from uploading' as opposed to being in an actual 'stopped' state) before having a chance to get a decent ratio.
