### ISSUE TITLE
[Feature Request] Allow "Pause For..." from Stopped state (and Paused!)

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#727]
The new Advanced > Pause For... context menu option for torrents _almost_ completely eliminates any need for the old TimedAutoStart plugin, except for one difference: It's disabled (grayed out) for Stopped torrents.

Maybe it's a bit silly, but I like being able to select a bunch of Stopped torrents, choose "Auto start in ?" from the menu, set a delay, and have them flip smoothly into Paused state until the timer expires. With Pause For..., the torrents have to be _Started_ before the Pause delay can be applied to them, which creates additional churn in terms of network connections opening, trackers and peers being contacted, etc. So I tend to still use TimedAutoStart instead, even though the same functionality is built in. (And works better, since with Pause For... the Progress column displays "Resuming at HH:MM".)

If "Advanced > Pause For..." worked on stopped torrents, I'd be able to uninstall TimedAutoStart completely.

**Comment by ferdnyc** [comment]
(Oh, and include Paused torrents in that as well. Neither feature's timers survive a restart, which is understandable. But since BiglyBT comes back up with the torrents in Paused state, TimedAutoStart's delay can be reapplied directly. With Pause For..., the torrents _again_ have to be started, before they can be re-paused with a timeout.)

**Comment by parg** [comment]
Check the next beta (B17)

**Comment by ferdnyc** [comment]
Woohoo! Sweet — and goodbye forever, TimedAutoStart. :checkered_flag: Many thanks.
