### ISSUE TITLE
add support for auto-update trackers-ip from tracker list

### ISSUE THREAD

**Issue by KonoromiHimaries** [BiglySoftware/BiglyBT#736]
example. i have a tracker list from that repo <https://github.com/ngosang/trackerslist#trackerslist>
I would like biglybt to get auto-updates from this list and customize all my active torrents to that trackers

thanks

**Comment by parg** [comment]
The feature already exists: https://github.com/BiglySoftware/BiglyBT/wiki/Tracker-Templates-and-Lists
