### ISSUE TITLE
torrent download history

### ISSUE THREAD

**Issue by dnellis** [BiglySoftware/BiglyBT#739]
* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment

**Comment by parg** [comment]
wha?

**Comment by dnellis** [comment]
When I restore from a previous backup file, I lose all the torrent entries which were made in the interim in the "download history". Can this be corrected? Or is there a method of saving those torrents in order to be able to re-enter them in the restored History Folder?

**Comment by parg** [comment]
If you have the dlhistorya.config and dlhistoryd.config files from before the restore then just replace the current ones with those (when BiglyBT is stopped)
