### ISSUE TITLE
Remote monitoring on iOS

### ISSUE THREAD

**Issue by googlenews** [BiglySoftware/BiglyBT#74]
I was wondering what’s the best way to monitor BiglyBT computer remotely or remote control from an iOS device.

**Comment by googlenews** [comment]
The darn button got hit by mistake while I was trying to target the body text box. 

Anyway,  I was wondering what’s the best way to monitor BiglyBT computer remotely or remote control from an iOS device.

**Comment by TuxPaper** [comment]
Apple App store doesn't allow any apps related to torrenting at all.  In 2012, they let a Transmission Remote app slip in, but I checked today, and it's gone.

The only way I know of is using a website.  There are two options:

1) (Easiest) Vuze provides one at http://remote.vuze.com/ .  The BiglyBT access code should work there as well.

2) (Hardest) If you know your desktop's IP address, you can open it in your browser on your iOS device with port 9091 (for example `http://127.0.0.1:9091/`), and will be prompted for a username/pw.  The username is 'vuze' and the password is your access code (Tools->Remote Pairing).

**Comment by googlenews** [comment]
It worked. thanks. Loved that it presented a QR code also.

**Comment by googlenews** [comment]
This web remote app is truly unsung. I just discovered the touch controls… awesome! Are any updates coming soon and will it be automatically applied on app launch? Keep up the great work. 👍🏻
