### ISSUE TITLE
Fails to launch on Mac (Mojave) after installation

### ISSUE THREAD

**Issue by jeolefmo** [BiglySoftware/BiglyBT#740]
Hi guys,

I have been unable to run Vuze on my MacBook Pro (Mojave 10.14) for a year or two due to installation issues and the app freezing on startup. I have since been using a range of inferior torrent clients trying to find something relatively suitable, but have been left disappointed at every avenue. 

I heard about BiglyBT and got very excited!
However, once installed I have found that it has similar issues to what Vuze was showing.
After installation, BiglyBT does not even start up. As I open the app, its name appears in my toolbar for around half a second and then disappears as it fails to boot.

I'm no programmer, but there must be something incompatible with the newer versions of MacOS and the coding within Vuze and BiglyBT.
I would love to get this app working, and I will do anything I can to assist you in providing information to this issue.
Let me know what information you need to get this sorted out, and I'll help you as much as I can.

This is what my computer looks like just as it opens and then crashes.
![screen-shot-2018-12-06-at-9 15 26-am](https://user-images.githubusercontent.com/45642387/49549138-c812e880-f937-11e8-9300-c035c0daa68e.gif)

**System Log:**
Dec  6 09:41:45 MacBook-Pro-2 JavaApplicationStub[918]: DEPRECATED USE in libdispatch client: dispatch source activated with no event handler set; set a breakpoint on _dispatch_bug_deprecated to debug

**From Error & Faults while attempting to open the app:**
Unable to load Info.plist exceptions (eGPUOverrides)

error	09:43:35.280944 +1030	JavaApplicationStub	Unable to load Info.plist exceptions (eGPUOverrides)

error	09:43:35.936463 +1030	cfprefsd	rejecting write of key _DKThrottledActivityLast_DKKnowledgeStorageLogging_DKKnowledgeStorageDidInsertEventsNotification:/app/usageActivityDate in { com.apple.contextstored, root, kCFPreferencesAnyHost, no container, managed: 0 } from process 206 because setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access

error	09:43:35.936619 +1030	contextstored	Couldn't write value for key _DKThrottledActivityLast_DKKnowledgeStorageLogging_DKKnowledgeStorageDidInsertEventsNotification:/app/usageActivityDate in CFPrefsPlistSource<0x7ff447206360> (Domain: com.apple.contextstored, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access

error	09:43:35.937328 +1030	cfprefsd	rejecting write of key _DKThrottledActivityLast_DKKnowledgeStorageLogging_DKKnowledgeStorageDidInsertLocalEventsNotification:/app/usageActivityDate in { com.apple.contextstored, root, kCFPreferencesAnyHost, no container, managed: 0 } from process 206 because setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access

error	09:43:35.937473 +1030	contextstored	Couldn't write value for key _DKThrottledActivityLast_DKKnowledgeStorageLogging_DKKnowledgeStorageDidInsertLocalEventsNotification:/app/usageActivityDate in CFPrefsPlistSource<0x7ff447206360> (Domain: com.apple.contextstored, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access

**Comment by parg** [comment]
Can you run BiglyBT as follows:

Locate BiglyBT.app in Finder
Right-click and select 'show package contents'
Open the 'Contents' folder
Open the 'MacOS' folder
Locate JavaApplicationStub and execute that by double-clicking.

This should open a console that logs messages during BiglyBT startup - copy/paste all the messages into this issue.

Thanks!

**Comment by jeolefmo** [comment]
Hi Parg,

Here is what the log has recorded:

Last login: Fri Dec  7 08:34:46 on ttys000
MacBook-Pro-2:~ jeolefmo$ /Applications/BiglyBT/BiglyBT.app/Contents/MacOS/JavaApplicationStub ; exit;
There appears to be another process already listening on socket [127.0.0.1:6880].

Locate and terminate the other program or change the control port - <a href="https://wiki.biglybt.com/w/Commandline_options#Changing_the_Control_Port">see the wiki for details</a>.
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by jeolefmo** [comment]
I figured it out!
My VPN client was using the same socket (127.0.0.1:6880).
I uninstalled it, and now BiglyBT is working!

**Comment by parg** [comment]
whoa, crazy! Good job :)
