### ISSUE TITLE
Select all files

### ISSUE THREAD

**Issue by adrium** [BiglySoftware/BiglyBT#746]
## Situation

When adding a torrent, the "wanted" files can be selected.
Per default, all of the files are selected.
Folders and files can be marked "unwanted".

## Feature Request

Some torrents contain hundreds of files, but you only want to download one or two. It takes a lot of time to uncheck every unwanted file.

There should be a _Select All / Deselect All_ functionality. Either by seperate buttons, or by displaying a "virtual root folder" named like the torrent.

## Info

* Android 8.1
* BiglyBT Version 1.2.1

**Comment by TuxPaper** [comment]
This issue was moved to BiglySoftware/BiglyBT-Android#89
