### ISSUE TITLE
"Firewalled" despite no active firewall

### ISSUE THREAD

**Issue by davidsmoothington** [BiglySoftware/BiglyBT#748]
<!--
Hi, I've been getting the Firewalled status and can't quite figure out how to fix. I turned off Windows firewall although I'm not sure if it's ever really off and made sure BiglBT is allowed for both in and outbound connections, have no other firewall running, opened my ports through my router for this machine, even opened it up in the DMZ in my router, to no avail. When I check the network via BiglyBT, it can access the BiglyBT website, but it says "NAT check failed. Connection attempt to .... (your computer) timed out...." Saw a recent post about NAT failing and tried, following the instructions to download [https://s3.amazonaws.com/biglybt-files/core/BiglyBT1601-B03-signed.jar] renaming it as directed. No luck.

Any advice or recommendations? 

* Windows 10 v10.0
* BiglyBT Version Number: just downloaded latest version to see if it helped (unfortunately not)

**Comment by davidsmoothington** [comment]
Strange, I ended up starting and re-starting BiglyBT about 4-7 times, without doing anything else like re-starting Windows, all resulting in the same "Firewalled" result, but now this time it's working. I get the "NAT OK" message. The inconsistency is the tough part.

**Comment by parg** [comment]
The best test is to go to the Help menu and perform the NAT test. The icon indicator in the status bar shows whether or not here have been incoming TCP connections recently - while the presence of these is a good indicator of your NAT being OK the absence might not be,.

**Comment by davidsmoothington** [comment]
Got it. Fascinating. Sometimes if I just let it go for 10 minutes or so it seems to clear. 

Thanks for all that you do!
