### ISSUE TITLE
FreeBSD swt libc.so.6 error

### ISSUE THREAD

**Issue by GreyAsh** [BiglySoftware/BiglyBT#75]
Hello,
            I installed the application with the .sh installer from https://github.com/BiglySoftware/BiglyBT/releases on FreeBSD 11. I see the following on launch tho. 
```
zsh/2 640 % ~/applications/biglybt/biglybt
Starting BiglyBT...
Suitable java version found [java = openjdk 1.8.0_144]
Using swt/swt-x86_64.jar v4.757
DEBUG::Wed Sep 27 08:57:19 AST 2017  BC Provider 'BC_VUZE' initialised successfully (loaded from jar:file:/usr/home/<username>/applications/biglybt/Azureus2.jar!/org/gudy/bouncycastle/jce/provider/BouncyCastleProvider.class)
SWT check failed with: No GTK3 found. java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
        no swt-gtk-4757 in java.library.path
        no swt-gtk in java.library.path
        /usr/home/<username>/.swt/lib/FreeBSD/x86_64/libswt-gtk-4757.so: Shared object "libc.so.6" not found, required by "libswt-gtk-4757.so"
        Can't load library: /usr/home/<username>/.swt/lib/FreeBSD/x86_64/libswt-gtk.so
```

I tried modifying libmap.conf as per this: https://forums.freebsd.org/threads/43766/ but then i see a message /lib/libc.so.7: version GLIBC_2.2.5 required
Any suggestions? Are misc/compat* ports required for BiglyBT on FreeBSD?

**Comment by TuxPaper** [comment]
Looks like the biglybt script is not detecting you are on FreeBSD, and is trying to use the wrong swt.  It uses the OSTYPE environment variable and checks if it matches "FreeBSD".  Try this first

```
OSTYPE="FreeBSD" ~/applications/biglybt/biglybt
```

If that doesn't work, you can manually override the swt dection with this:

```
cp ~/applications/biglybt/swt/swt-bsd.jar ~/applications/biglybt/swt.jar
mv ~/applications/biglybt/swt ~/applications/biglybt/hideswt
```
Which, as the code says, copies the bsd swt into the biglybt root and renames the swt dir so the script can't find it anymore.

**Comment by GreyAsh** [comment]
Based on TuxPaper's post I checked the environment variables.  No OSTYPE under zsh, but it is present under tcsh. Last month I switched shells from tcsh to zsh. And then began seeing the above behavior. Thanks TuxPaper, the client loaded up like normal.
