### ISSUE TITLE
"Use GTK2 instead of GTK3" does nothing

### ISSUE THREAD

**Issue by axredneck** [BiglySoftware/BiglyBT#753]
Setting "Use GTK2 instead of GTK3" in Options and then restarting BiglyBT doesn't switch it to GTK2, interface remains in GTK3 which is buggy.

System:

Java 11.0.1 (64 bit)
  Oracle Corporation
/usr/lib/jvm/java-11-openjdk

SWT v4922, gtk/3.24.1
Linux v4.19.4-zen1-1-zen, amd64 (64 bit)
B1.7.0.0/4 az3

Arch Linux, KDE, BiglyBT from AUR.

**Comment by CrafterLaughter** [comment]
I'm a newbie and don't know how to discern if GTK2 or GTK3 is running specifically for BiglyBT yet here are my observations when Bigly's UI didn't work quite right for me on first launch.

Specifically the behavior was section headers like MyTorrents, BiglyBT, Content Discovery, Devices can be seen yet the subsections are only readable when illuminated after selected.  The subsections being  Library, New, Active, Inactive etc.

The problem appears to be Linux theme specific and I'm seeing the problem with Blackbird, Greybird, High Contrast, Numix, Raleigh.  The problem does not exist for adwaita white or dark.  Switching Bigly to it's classic interface also proved to work for all Linux themes including those that didn't work under the latest interface.

The UI chooser toggle is just under the GTK toggle in options.

![image](https://user-images.githubusercontent.com/23381273/50254758-97f22d80-03ac-11e9-868a-74bf6dcfd04b.png)

Java 1.8.0_181 (32 bit)
  Oracle Corporation
/usr/lib/jvm/java-8-openjdk-i386/jre

SWT v4757, gtk/2.24.31
Linux v4.15.0-1-686-pae, i386 (32 bit)
B1.7.0.0/4 az2

**Comment by axredneck** [comment]
@CrafterLaughter 
> ... how to discern if GTK2 or GTK3 is running specifically for BiglyBT

I use different themes for GTK 2 and 3 so i can see. Also Your BiglyBT likely uses GTK2:
>SWT v4757, gtk/2.24.31

For me BiglyBT uses GTK3 and some widgets are very large so they don't fit in it's window. Previously "Use GTK2 instead of GTK3" worked and with GTK2 all was right, so this bug is **probably a regression**. Maybe it's a regression of OpenJDK, i'm unsure.
> Switching Bigly to it's classic interface also proved to work ...

Thank You, i'll try, but it's just a workaround, not an actual fix, especially considering Classic Interface is deprecated.

**Comment by axredneck** [comment]
@CrafterLaughter 
> Switching Bigly to it's classic interface also proved to work ...

Doesn't help, interface is still broken.

**Comment by parg** [comment]
You could try the latest beta - there have been some GTK3 improvements - See the Help menu to join the Beta Program (this is for axredneck)

**Comment by axredneck** [comment]
@parg 
Sadly i can't update BiglyBT installed from AUR to beta. Also i can't install BiglyBT downloaded from Github (GitHub_BiglyBT_Installer.sh) but it's separate issue. Vuze had much better way to install on Linux: just download, unzip, run and enjoy, no AUR and no install.sh.

**Comment by axredneck** [comment]
@parg 
Finally i managed to install this beta, and it fixed GTK3 interface 😃, but this checkbox still does nothing.
