### ISSUE TITLE
Left and Right resize bars unresponsive

### ISSUE THREAD

**Issue by eurobank** [BiglySoftware/BiglyBT#759]
Using the latest beta under Windows 10/64 i see that trying to "open up" or shrink the window using the left or right bars, it very-very unresponsive.

Using Top or Bottom option to resize works great.

Thanks.

**Comment by parg** [comment]
When you say 'resize bars' what do you mean? Clicking on the left/right window edge and dragging? I don't see any such issues with my test VM

**Comment by eurobank** [comment]
Sorry, English is not my forte.

Yes, dragging the left and right windows edge response is very hard, takes 5 seconds, seems stuck and actually resizes after a while.

**Comment by parg** [comment]
Claassic UI or regular BiglyBT UI with the sidebar? Anything special about your Win 10 setup?

**Comment by eurobank** [comment]
No nothing strange or special. I use the Advanced list (if you mean that). I have a side bar.

**Comment by eurobank** [comment]
This also seems fixed. Not sure when and how, if it was biglybt or my graphics or windows ...
