### ISSUE TITLE
Update via I2P not possible

### ISSUE THREAD

**Issue by mppdidi** [BiglySoftware/BiglyBT#764]
It would be nice to be able to update via i2p and not S3 - anonymous configuration settings related to updates are not working FWICT.

* Windows 10
* 1.7.0.1_B29

**Comment by parg** [comment]
I've created some anonymous chat channels that contain anonymous updates

chat:anon:?BiglyBT%3A%20Updates%5Bpk%3DARJPXVO5NRE3ZG4OBCWPA5I6ZXF6D2JSPDS23Q4GEPW7LRBVIC7EWLRVM2QS6ZAXR357L2B4ZPWAATQ%26ro%3D1%5D

Doesn't fix the problem but might be vaguely useful

**Comment by parg** [comment]
I've fixed an issue with the anonymous plugin list updating - can you see if that helps with things?

**Comment by parg** [comment]
I started https://github.com/BiglySoftware/BiglyBT/wiki/Updating-BiglyBT to record some things

**Comment by mppdidi** [comment]
Did a quick test and it works :-)
Appreciate the effort !!!

**Comment by mppdidi** [comment]
Would it be possible to run check+update via i2p only - currently tor plugin is required ?

**Comment by parg** [comment]
Maybe one day - I'd need to knock up some I2P 'hidden services', make sure they kept running, hack around with the plugin to proxy things...
