### ISSUE TITLE
Corrupted dat files in  active directory.

### ISSUE THREAD

**Issue by BPDunbar** [BiglySoftware/BiglyBT#775]
A week or so ago something went wrong and most of the torrents in my library started displaying an error like this:
Error: IO Error (Error reading torrent file 'C:\Users\brett\AppData\Roaming\BiglyBT\active\7114B629247DFA51C8E115B7C33A3549D907793A.dat - Error reading torrent: Contents invalid - bad header)

The size of the torrent is shown as 0 bytes

And the hash is shown as 00000000 00000000 00000000 00000000 00000000

Force Re-Check is greyed out.
Attempting to re add the torrent file matches it to the  existing torrent and does not repair.

Removing  the torrent from the library then re adding simply gives a torrent previously downloaded notification and the same error.

On each restart a small number of torrents will spontaneously move to active and have the correct hash and the correct file size is listed on checking the downloaded file they match and move to the library. There seems to be no obvious pattern to which files are repaired in this way. This is taking a very long time as it fixes up to ten files at a time and close to 1400 torrents are still affected.

Other than that the the only solution I have found is manually deleting the *.dat, *.dat._az and *.dat.saving files in the active directory that match the string in the *.dat file in the error message (I do a search on the string and delete all three, it's possible that not all of them need to be deleted). And also deleting the torrent from the library and re adding it. This is effective but is also very laborious. It would be a great deal easier if I could tell the program to ignore the broken dat files and create new ones using the torrent files which are perfectly fine so I didn't have to manually delete them.

Java 1.8.0_162 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4922, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B1.7.0.1_B14/4 az3

**Comment by parg** [comment]
Please update to the latest beta (B33) - some work has been done to aid recovery from this kind of error.

**Comment by BPDunbar** [comment]
That seems to have worked.

The beta and installed plugins weren't updating, so I reinstalled and joined the beta programme. This may have been the same problem that caused the corruption.
