### ISSUE TITLE
add support for multiple socks proxy ip address

### ISSUE THREAD

**Issue by KonoromiHimaries** [BiglySoftware/BiglyBT#778]
if I have a super fast internet, then one ip proxy is not able to handle it.

**Comment by parg** [comment]
Are you talking socks proxies? You can bind BiglyBT to multiple network interfaces already.

**Comment by parg** [comment]
I was talking about network interfaces (Tools->Options->Connection->Advanced Network Settings: Bind to local IP address(es)

Do you really have two (or more) SOCKS proxies? It would be possible to add support for > 1 but only for out-bound connections (via round-robin selection, not load-balanced in any way). However this would be a bit of work...

**Comment by KonoromiHimaries** [comment]
I would like bigly bt to support custom lists with proxy ip

like https://github.com/BiglySoftware/BiglyBT/wiki/Tracker-Templates-and-Lists#tracker-list

**Comment by parg** [comment]
custom lists of what?

**Comment by KonoromiHimaries** [comment]
https://github.com/clarketm/proxy-list/blob/master/proxy-list.txt

**Comment by parg** [comment]
But your original request was to do with SOCKS peer-peer data connections - that proxy list is HTTP/HTTPS.

So, back to the original request, do you have access to > 1 SOCKS proxy that you want BiglyBT to use for peer-peer data connections? 

Most likely you will need to be paying for the SOCKS proxies as you will find it hard to locate open SOCKS proxies that are willing to transfer torrent data.

**Comment by parg** [comment]
Beta version B35 supports up to 3 peer data socks proxies

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
_i was looking for something like this by try using random integer range in proxy hah._ Many Thanks for adding this possibility natively! 

> not load-balanced in any way

BiglyBT uses many connections. So This could be a win. There is a algorithm called "least_con". Like its used in nginx. This makes basically sure to connect you next time to the proxy with the currently lowest peer connections. Which is very nice balancing in torrents. May consider this if not to hard to implement. (tracking peer connections count per outgoing proxy) the routing stats already does track socks and interface connections Counters differently. just my thought.

**Comment by ArtemGr** [comment]
Given it's marked as "completed", was it implemented? Like, can I configure two socks5 proxies, one to a nearby server and another to a different country, in order for a torrent download to find more/better peers?

**Comment by parg** [comment]
Comment above says "Beta version B35 supports up to 3 peer data socks proxies"

**Comment by ArtemGr** [comment]
I mean, there's obviously support for multiple proxy plugins, but the standard UI in https://github.com/BiglySoftware/BiglyBT/blob/7ee84f7310e20ed3563110758b412d7934460373/core/src/com/biglybt/ui/config/ConfigSectionConnectionProxy.java#L69 **can't** have multiple socks proxies, right?

**Comment by parg** [comment]
<img width="1144" height="806" alt="Image" src="https://github.com/user-attachments/assets/c0cf41f1-00fe-4617-b964-4f34a27ffb6d" />

**Comment by ArtemGr** [comment]
Duh, I wondered what _these_ are for 😅. Will test.

p.s. Yes, this works!
I've configured two socks5 proxies, one in-country and one overseas, and added them both to _Options / Connection / Proxy / Peer Communications / Proxy Server 1 & 2_ - and I can see both the in-country and the overseas peers being used, with server-side bandwidth stats matching the respective peers!
