### ISSUE TITLE
i2phelper default settings

### ISSUE THREAD

**Issue by ghost** [BiglySoftware/BiglyBT#784]
* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment

**Comment by mppdidi** [comment]
The i2phelper module has default tunnel lengths ( Inbound- and Outbound hops ) of 1 and 2 - that is unsafe and should be 3 by default.
https://geti2p.net/en/docs/how/tunnel-routing

**Comment by parg** [comment]
The 'mixed' destination is unsafe anyway as it can easily be correlated with public activity (as it is mixed...) The 'I2P only' destination is 3.
