### ISSUE TITLE
Implement BitTorrent Token (BTT)

### ISSUE THREAD

**Issue by TuxPaper** [BiglySoftware/BiglyBT#787]
BTT is a "token-based economy around the usage of networking, bandwidth and storage".  Basically, it allows you to sell your upload bandwidth and buy torrent data from other peers.

BTT White Paper: https://www.bittorrent.com/btt/btt-docs/BitTorrent_Token_Whitepaper.pdf

Spec (BEP) is currently not available.  Assuming there is enough interest in BTT, we'd still have to wait until there's a BEP and assess it from there.

Note: Creation of this issue does not indicate that BiglyBT devs are in favor of BTT.

**Comment by ElDavoo** [comment]
The new white paper can be found here: https://www.bittorrent.com/btt/btt-docs/BitTorrent_(BTT)_White_Paper_v0.8.7_Feb_2019.pdf
I would be very interested in the feature since bittorrent can't handle my huge numbers of seeding torrents

**Comment by EarthBoundX5** [comment]
Bump, as I would like to see this too.  And I refuse to use µTorrent, Azureus is king!

**Comment by ElDavoo** [comment]
(nit: this issue should be closed as "not planned" and not as completed)
