### ISSUE TITLE
Metadata stuck at 0%

### ISSUE THREAD

**Issue by ghost** [BiglySoftware/BiglyBT#790]
Metadata download often gets stuck at 0% allthough the connected peers do have the torrent / metadata available.
Any hint on how I can debug this issue further ?

**Comment by parg** [comment]
I assume that the connected peers have a completion > 0%? You could turn on logging (Tools->Options->Logging) and then check the metadata download's 'Console' sub-tab

**Comment by o0nd7ots** [comment]
@TuxPaper I think we won't get any new info here so I suggest closing this issue.
