### ISSUE TITLE
update the web engine from old internet explorer to last chromium

### ISSUE THREAD

**Issue by KonoromiHimaries** [BiglySoftware/BiglyBT#791]
the `Wiki: Dashboard` was broken

![2019-01-09-](https://user-images.githubusercontent.com/5884000/50930711-f74dd580-1460-11e9-8d91-f316bc81d389.png)

potential fix
https://bitbucket.org/chromiumembedded/java-cef

**Comment by parg** [comment]
We use SWT - something like https://blogs.eclipse.org/post/mika%C3%ABl-barbero/chromium-eclipse-swt-integration would be a preferential fix

**Comment by TuxPaper** [comment]
Interesting that https://github.com/maketechnology/chromium.swt now says "The full SWT Browser API is supported now, including sync and async Javascript support."  Apparently they finished a month ago :)

**Comment by parg** [comment]
Waiting on them to fix a few issues - doesn't seem to be an active project :(

https://github.com/maketechnology/chromium.swt/issues/42
https://github.com/maketechnology/chromium.swt/issues/41

**Comment by parg** [comment]
I take back the comment about the project not being very active - have some fixes in version 8.0 and am testing them!

**Comment by parg** [comment]
If you are running the latest beta then try installing the 'Chromium SWT Browser Plugin' plugin from https://plugins.biglybt.com/

**Comment by Yijare** [comment]
sorry to dig this up again - but couldn't we include that in the main program? Because the Client refuses to install from the webpage
![biglybt_error](https://user-images.githubusercontent.com/5788141/65031875-5cd45900-d942-11e9-9ca3-7be54521dd2a.png)

**Comment by parg** [comment]
64-bit windows?

**Comment by Yijare** [comment]
yes. let me guess. there is only an x86 version

**Comment by parg** [comment]
There's only an x64 version. Are you running BiglyBT 2100? It installs fine for me

**Comment by Yijare** [comment]
yes i'm running the lastest BBT Version. Still no install for me.

**Comment by parg** [comment]
How about if you download

https://files.biglybt.com/plugins/bgchromiumswt_3071.3.biglybt

and then install it via the Help menu's Advanced->Install Update Manually... ?

**Comment by Yijare** [comment]
it installs but does not replace the default SWT Browser.

**Comment by parg** [comment]
how do you know? does it have a right-click menu?

**Comment by Yijare** [comment]
it is there listed as plugin. but even after reboot BBT's dashboard still uses the default browser. I have no menu to configure the plugin as default

**Comment by parg** [comment]
If you right-click on the dashboard's web view do you get a menu with items like 'back' and 'print' ? If yes then the view is using the Chromium browser. If no then it is still using SWT's default one (Internet Explorer)

**Comment by Yijare** [comment]
![biglybt_2](https://user-images.githubusercontent.com/5788141/65206717-aaaaa780-da8f-11e9-861f-5c807609ac21.png)
i'd say 'no'

**Comment by parg** [comment]
Not on the eidebar, on the right-hand-side, the actual webpage

**Comment by Yijare** [comment]
oh, my bad. But nothing at all, when I right-click

**Comment by parg** [comment]
hmm, darn it, Can you look in your Debug_1/2.log files to see if there's anything related to the browser?

**Comment by Yijare** [comment]
I only have one debug/ in %appdata%/biglybt ... I guess i'm doing something terribly wrong here.

**Comment by parg** [comment]
heh, I don't think you're doing anything wrong, must be some bug somewhere. You might only have a single Debug_1.log file if it hasn't filled up yet:

%appdata%\biglybt\logs\debug_1.log

**Comment by Yijare** [comment]
the last entry there is an Stacktrace to networking issues  ([alert] Alert:3:ERROR, unable to bind TCP incoming server socket to 49516 ) - witch is nothing related to this issue

Other than the bind problem there is nothing in my debug_1 file

(and yes I was searching for the directiory 'debug_1' with the file 2.log, so I did something wrong)

**Comment by parg** [comment]
hmmm! Can you general a debug.zip (Help menu, last option) and send it over to paul@biglybt.com please?

**Comment by Yijare** [comment]
Give me a moment, will do.

Thank you for the help
