### ISSUE TITLE
I2P Helper -- Define default open trackers?

### ISSUE THREAD

**Issue by manasb** [BiglySoftware/BiglyBT#800]
* Qubes R4.0
* 1.7.0.1_B37
* KDE

I2Psnark has a set of default open trackers, is it possible to define these in the I2P helper plugin so that they are queried for I2P torrents?

Taken from my `~/.i2p/i2psnark.config.d/i2psnark.config`:
```
i2psnark.opentrackers=http://ri5a27ioqd4vkik72fawbcryglkmwyy4726uu5j3eg6zqh2jswfq.b32.i2p/announce,http://s5ikrdyjwbcgxmqetxb3nyheizftms7euacuub2hic7defkh3xhq.b32.i2p/a,http://uajd4nctepxpac4c4bdyrdw7qvja2a5u3x25otfhkptcjgd53ioq.b32.i2p/announce,http://w7tpbzncbcocrqtwwm3nezhnnsw4ozadvi2hmvzdhrqzfxfum7wa.b32.i2p/a
```

**Comment by parg** [comment]
Use a tag - here's one (unzip it and install into BiglyBT)

[I2POpenTrackers.zip](https://github.com/BiglySoftware/BiglyBT/files/2748909/I2POpenTrackers.zip)

**Comment by parg** [comment]
Added to https://github.com/BiglySoftware/BiglyBT/wiki/Tracker-Templates-and-Lists
