### ISSUE TITLE
Embeded Media Player Plugin Cannot detect VLC

### ISSUE THREAD

**Issue by MagnumGR** [BiglySoftware/BiglyBT#807]
BiglyBT cannot detect installed VLC in Embeded Media Player Plugin.

![biglybt](https://user-images.githubusercontent.com/8311546/51072483-3307bb80-166a-11e9-8578-0c66f09f9cfa.jpg)

![biglybt-vlc](https://user-images.githubusercontent.com/8311546/51072487-3602ac00-166a-11e9-9e5c-226ddafa971c.jpg)

The latest 64bit version of VLC is already installed. BiglyBT show Vlc icon on video files.
On double click get the following message, but with right click and open, VLC play the specific media file !
 

![biglybt-vlcn](https://user-images.githubusercontent.com/8311546/51072559-6ac33300-166b-11e9-9526-5d0a498715e8.png)

* Fedora 29
* BiglyBT 1.7.0.1_B37
* For *nix: Gnome 3.30.2

**Comment by Marvel0us7** [comment]
It would be nice if we could just specify any path to any program or simply use OS settings for standard playback.

**Comment by parg** [comment]
You can - just set the 'Launch Helpers' up in config

**Comment by Marvel0us7** [comment]
I put in mkv,mp4 as extensions but double clicking a torrent that has such a media file in it still playes it with the embedded player

**Comment by parg** [comment]
Did you change the 'double click action' to Launch?

**Comment by parg** [comment]
I've just released version 4.3.2 to beta testers (join the Beta Program to get it) - please tell me if this fixes the VLC detection issue

**Comment by parg** [comment]
VLC is the only option on Linux - that' why it is pre-selected and you can't change it

**Comment by MagnumGR** [comment]
OK, but even now that BiglyLT detect VLC, with double click (action -> Open Play content), it opens and play with embedded player and not with VLC.

![biglybt-vlc6](https://user-images.githubusercontent.com/8311546/51173986-60997280-18bf-11e9-9ab1-8fe2094a4172.png)

**Comment by parg** [comment]
With VLC installed the embedded player uses VLC
