### ISSUE TITLE
Upload speed tab is empty but upload happens

### ISSUE THREAD

**Issue by WPFilmmaker** [BiglySoftware/BiglyBT#808]
The upload speed tab in the torrent menu is empty, it looks like you are not uploading anything. However if you look at the bottom you see that you are uploading so I think there is a glitch, top bar should reflect the fact that you are uploading.

BiglyBT 1.7.0.0
Lubuntu 16.04.3
LXPanel 0.8.2
Java 1.8.0_191 (64 bit)
Oracle Corporation
/usr/lib/jvm/java-8-openjdk-amd64/jre
SWT v4757, gtk/3.18.9
Linux v4.4.0-141-generic, amd64 (64 bit)
B1.7.0.0/4 az2

**Comment by WPFilmmaker** [comment]
@parg thanks for the quick answer!
Forgot to say that the share ratio is stuck to 0.000..I have only one torrent so I thought it would show the speed..pardon my ignorance but is the upload in the bottom is not related to the torrent, what is?

**Comment by parg** [comment]
It is related to the torrent but it isn't data transfer, rather protocol related to making peer connections (or keeping a connection alive)

**Comment by WPFilmmaker** [comment]
Thanks!

**Comment by parg** [comment]
No problem!
