### ISSUE TITLE
Feature Request: Block specific peers

### ISSUE THREAD

**Issue by gshudhanshu** [BiglySoftware/BiglyBT#817]
Hello,
Due to some reason I always get 5-10 same peers. They are always 10.240.252.0 to 10.240.252.255 these peers always takes my all upload speed and never provide me download speed, their upload speed always crosses the limit speed and always start downloading when I start download. I thought it may be due to any virus or malware but this same thing happens to my other two PCs. I have two internet connection this thing happens only with ISP1 not with ISP2.

I want to permantly block 10.240.252.0 to 10.240.252.255 peers. Please add this feature. It will be very helpful to me. Thank you sir!

![image](https://user-images.githubusercontent.com/33764308/51216043-047b3080-1949-11e9-91f4-e7e5c9f90786.png)

* OS- Windows 10 Enterprise and version 1809
* BiglyBT Version Number - B1.7.0.1_B38/4 az3
* For *nix: Desktop Environment

**Comment by parg** [comment]
Use the IP filter and manually add the range:

Tools->Options->IP Filters - hit the 'add' button at the bottom and enter the details

**Comment by gshudhanshu** [comment]
Hello parg,
Still is does not work :(

![image](https://user-images.githubusercontent.com/33764308/51267120-07c2fa80-19e3-11e9-9980-e2c141d08bb1.png)
![image](https://user-images.githubusercontent.com/33764308/51267181-304af480-19e3-11e9-9796-cf9430ad97a7.png)

**Comment by gshudhanshu** [comment]
Hello parg,
Still, it is not working :(

![image](https://user-images.githubusercontent.com/33764308/51268409-119a2d00-19e6-11e9-9e61-da7d5bb32baf.png)

**Comment by parg** [comment]
Odd... Remove those ranges and try

0.0.0.0 -> 255.255.255.255

Are you using a proxy?

**Comment by gshudhanshu** [comment]
Hi parg, Still it is not working... :(
I don't use any proxy. 

![image](https://user-images.githubusercontent.com/33764308/51270662-8b80e500-19eb-11e9-94c5-fc0c1e95773c.png)
![image](https://user-images.githubusercontent.com/33764308/51270632-7b690580-19eb-11e9-9c11-c1efb852ad46.png)

**Comment by parg** [comment]
Also if you right-click in the status area at the bottom there is a 'show' menu that has an option to show 'IPFilter Status'. Enable this and an additional element is added to the status bar showing what addresses have been blocked - double click it to see details.

It is also possible to enable/disable the IPFilter on a per-torrent basis - there is a column that you can enable to see the state of this and also a right-click option in the Library to enable/disable it - check that too.

**Comment by gshudhanshu** [comment]
IP Filter column added. Please check
![image](https://user-images.githubusercontent.com/33764308/51270891-24176500-19ec-11e9-9d9c-d12470d30826.png)

**Comment by parg** [comment]
And another thing - addresses that are 'LAN Local' are not considered for banning. The 10.x range is site-local which is by default treated as LAN local. Go to Tools->Options->Plugins->LAN Peer Finder and deselect the 'Automatically include loopback/link/site local networks'

**Comment by gshudhanshu** [comment]
It is working 👍. Thank you for timely help :)
![image](https://user-images.githubusercontent.com/33764308/51271223-f383fb00-19ec-11e9-9b9f-02b447ed57ce.png)

**Comment by parg** [comment]
No problem :)
