### ISSUE TITLE
fix 20-30% uploading dataless on a slow internet connection

### ISSUE THREAD

**Issue by KonoromiHimaries** [BiglySoftware/BiglyBT#818]
when i have upload ratio on `1.0` , then i have only a `70%` data send to all peers..

* OS and version w10
* BiglyBT Version Number stable latest

**Comment by parg** [comment]
How?

**Comment by parg** [comment]
Can you stop wasting my time? I put a lot of effort into

https://github.com/BiglySoftware/BiglyBT/issues/778

and you didn't have the decency to follow up.
