### ISSUE TITLE
Beta Update Download Failures

### ISSUE THREAD

**Issue by nofnway** [BiglySoftware/BiglyBT#83]
Hi,
Awesome job guys. Long-time Azureus user, so very happy you started this project. Thank you! Over the past month., since switching to BiglyBT, I have encountered frequent failures when attempting to download new betas. I see the blog post that a new beta is available, but then I can't download it. I see the following in the Component/Plugin Installer window:

![image](https://user-images.githubusercontent.com/32655597/31363371-8f284cba-ad23-11e7-9716-3cc9b52f8c8d.png)

I have also tried to directly download via the Amazon link in the browser, but it stalls out and also fails. Hours later, the beta does finally download on its own, and I get the Restart Now/Later popup. Is this a bug or am I doing something wrong? I never had this type of issue with Azureus, or at first with BiglyBT, so thinking bug. Please help if you can. Thanks!

OS Windows 10 build 17004.rs_prerelease.170922-2229
BiglyBT 1.0.2.1_B08

**Comment by parg** [comment]
Thanks for the support!

One or two users have reported problems with the amazon 'S3' CDN - no idea what is causing it :( Ultimately I'd like to distribute updates via torrent, as happens in Vuze, it's just the matter of getting around to setting things up...  I'll see if I can find some time to take a look!

**Comment by parg** [comment]
By the way, can you access

https://s3.amazonaws.com/biglybt-files/core/BiglyBT1021-B09-signed.jar

now or does it still stall?

**Comment by parg** [comment]
Torrent updates are now enabled - hope that helps!

**Comment by nofnway** [comment]
Sorry, just getting back to check on this to see if more info was needed. I see updates are now torrents. Awesome!!! Thanks parg!

**Comment by parg** [comment]
no problem!
