### ISSUE TITLE
How do I get you to stop popping up ads in my Vuze?

### ISSUE THREAD

**Issue by o9573126** [BiglySoftware/BiglyBT#833]
For someone who claims to have removed advertising in their new project you sure are spamming the crud out of existing Vuze users. That is NOT the way to convince me you are any better than what I already have.

* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment

**Comment by Havokdan** [comment]
I dont see ads in BiglyBT

**Comment by parg** [comment]
I believe you can turn off ads in Vuze by disabling the 'azpromo' plugin. You would need to go to 

Tools->Options and click on 'Plugins' - on the right there is a list of installed plugins. Deselecting the checkbox next to 'azpromo' will prevent this plugin from being loaded next time you start.

Hope that helps.

**Comment by TuxPaper** [comment]
Are you still using Vuze, or did you switch to BiglyBT?

I'm not even sure how the azpromo plugin would have gotten migrated to BiglyBT, but BiglyBT doesn't have any re-install logic for it, so you should be safe in just uninstalling that plugin entirely.

If you are still using Vuze (and still want to use it), parg's steps should work.
