### ISSUE TITLE
Program stops responding after a while

### ISSUE THREAD

**Issue by Coruvian** [BiglySoftware/BiglyBT#834]
Had no problems with previous version but after updating to 1.8, program would stop responding after a while, marginally better if downloads were paused but will also stop responding even with minimal downloads started. Could it be too many items in library? Although used to have no problems with about 100 active uploads and >20 active downloads with previous version. Attached debug info generated in Help before it stopped responding...
  Java 1.8.0_181 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4922, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B1.8.0.0/4 az3

* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment

[debug.zip](https://github.com/BiglySoftware/BiglyBT/files/2792392/debug.zip)

**Comment by parg** [comment]
You have a lot of

 java.lang.OutOfMemoryError: GC overhead limit exceeded

Go to Tools->Options->Mode and select "advanced". Then go to Startup & Shutdown and check the Java Options setting towards the bottom. Try increasing the 'Max Heap memory size' by a reasonable amount, say 50MB (can't remember what the default is)

If you have a lot of active torrents, and run the I2P helper plugin, memory usage can get quite high.

**Comment by Coruvian** [comment]
That seemed to have helped... Thanks!

**Comment by as-muncher** [comment]
I've been getting Piece check error: GC overhead limit exceeded
Disk read error: GC overhead limit exceeded
initialisation failed: GC overhead limit exceeded

I will put my Max heap memory size to 251 MB. and hopefully that will help

As a side note, I don't mind looking through the logs to see if there are any entries that say "DEBUG".  If you want, I can upload those.
