### ISSUE TITLE
Scrape Error with utf8 characters in path names

### ISSUE THREAD

**Issue by Scaler22** [BiglySoftware/BiglyBT#837]
Hello,

Since the 1.8.0.0 update, BiglyBT does not recognize utf8 folder names, so all previous torrents with special characters in folder names are marked as "Scrape Error: File Not Found" or "Scrape Error: Scrape System is Offline!".

Forcing to re-download these torrents will create new folders with "?" in there name at the place of specials characters.

System:
Java 1.8.0_181 (64 bit)
  Oracle Corporation
/usr/lib/jvm/java-8-oracle/jre

SWT v4922, gtk/3.22.30, zoom=100, dpi=109
Linux v4.15.0-43-generic, amd64 (64 bit)
B1.8.0.0/4 az2

**Comment by parg** [comment]
Whilst not addressing your file names with "?" in them, the tracker scrapes are based on the torrent hash which is not dependent in any way on the character set selected for file names. A scrape error of 'file not found' reported by a tracker usually corresponds to either the torrent no longer being registered with the tracker or the tracker having some kind of system issue.

**Comment by Scaler22** [comment]
Hmmm, maybe the scrape error is just a side effect.
I just noticed that if I force start of torrent, the error "Error: Data Missing /<path>" is showing in the status column.

**Comment by Scaler22** [comment]
Nevermind, everything is back to normal after rebooting computer…
Sorry for the bother.
