### ISSUE TITLE
add settings for ignoring updates

### ISSUE THREAD

**Issue by sparkysamza** [BiglySoftware/BiglyBT#839]
* OS and version - windows 10 1703
* BiglyBT Version Number 1.6

Can you please stop trying to force 1.7 down my neck it is getting very frustrating, there are no major issues with 1.6 and do not wish to update it at this time as updates with Windows 10 N always cause more issues than they solve. 

Unless there is some super major out of this world security flaw then there is no need all the features i need are in 1.6 :) 

thank you!

**Comment by parg** [comment]
Well, the latest is actually 1.8.

Tools->Options->Interface->Start
