### ISSUE TITLE
I2P Tunnel Lease should have the prefix BiglyBT

### ISSUE THREAD

**Issue by mppdidi** [BiglySoftware/BiglyBT#84]
I2P Tunnel Lease should have the prefix BiglyBT.
When looking at the router leaseset ( I2P Java router) the BiglyBT tunnels have the 'ordinary' trimmed Base64 description - it would be nice and helpfull to have them named with BiglyBT prefix.

**Comment by parg** [comment]
Where do you mean exactly? In the router console I get

![image](https://user-images.githubusercontent.com/395293/31443579-b8af628e-ae91-11e7-8dab-219d04c9ce42.png)

**Comment by mppdidi** [comment]
Go to NetDB LeaseSets

**Comment by mppdidi** [comment]
this is at http://127.0.0.1:7657/netdb?l=1

**Comment by parg** [comment]
Ah - no idea how that could be changed - probably an I2P enhancement rather than something under our control?

**Comment by mppdidi** [comment]
As it is not really relevant to the functionality I'm closing the ticket.
