### ISSUE TITLE
New Idea: Tag Filter Assignment

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#841]
Ok, this idea came from looking at the Options-Files screen. Specifically the Auto-Prioritize and Ignore.  Basically, Once the Ignore has taken care of things you don't want.  What is left could be run through a filter and Add the correct Tag by File Type. This would cause the Download Dialog to have the Tags selected by the new Filter Option. It would only apply when Adding New Torrents.  For Example a Torrent contains both a .MKV and a .MP3 file. It could get Auto Tagged with _'Video'_ and _'Audio'_ Tags.  Torrents with .EPUB files could be Tagged _'Books'_.  Like the auto import from a directory, it would have a ADD to add more Type/Tag entries.  And finally it would have a Default Field to set a Tag for anything that doesn't fit. Oh, and the entire section would be Optional.   Should also consider if the Add Tag in the import from directory section would still apply.

Anyway to help visualise how it would look I have created a rough mockup of the way the screen would look.  Discussion and input is welcome.  Maybe you have an idea for this that I didn't think of.  Lets get a discussion going, before @parg  runs off and codes it.

![biglybt new torrent filter](https://user-images.githubusercontent.com/37715552/51902431-fafdb980-2387-11e9-98d7-ab5017f9654a.png)

**Comment by HOTinHEELS** [comment]
Good idea. I think a bunch more fields would be needed to be really useful and without having to think about it too hard, something in the order of 10-20.  
Please Sir, can I have [more](https://youtu.be/hVZKJt4WzxM)?

**Comment by NaPurHab** [comment]
If you look at my idea, I have a Add, though I forgot to edit the image and it still says 'Add another directory', when it should be something like 'Add another filter'.   But in the end it would allow as many filter to be added as the user desires.

In the end all it will do is pre-tag any downloads.  Then if the user is using the full download dialog, and has not told it to not show up again.  Then the user will have an option to change the Tags, or just check the destination path, the selected files in the torrent, the ignored files (i.e. those useless 'this file downloaded from xyz_site'), etc. Then click OK to start the download.

The main reason I thought of this is that using the download dialog, I know if it is a certain file type, which Tag I want.  So having it Pre-Tag the download with a filter seems the easiest way. You can even get multiple Tags if say a file contains different types. Say you have a Software Tag that includes .EXE as a extension, but also a .PDF containing instructions, you could Tag both 'Software' and 'Books'.

So in the end it would just ensure the right tags for the content. And a lot less clicking to set the tags.

**Comment by DeoW** [comment]
Good idea for a coarse-grade filter. Probably suit people who DL a lot of different stuff.
For people who do mostly just one thing, e.g. video or audio or books, a finer filter will be required. Possibly only a sentient process will be able to figure that one out, i.e. genre of movie. I know naught of .EPUB. That may solve some of the possible issues in granularity of the filter. The system as described would make it quicker to find an item using a tag-based search, as cross-referencing is automatic.

**Comment by HOTinHEELS** [comment]
>  I forgot to edit the image and it still says 'Add another directory', when it should be something like 'Add another filter'. But in the end it would allow as many filter to be added as the user desires.

I wondered about that but then thought it better to clarify it in the form of an opinion

**Comment by NaPurHab** [comment]
I just updated the image.

**Comment by HOTinHEELS** [comment]
Tops!  No doubt about what is meant now!

**Comment by DeoW** [comment]
Seems to cover everything suggested. Pity, as the screen mockup took effort, and was darn good.

**Comment by NaPurHab** [comment]
This is to compliment the Ignore Filter.   For example, I download a torrent that Contains a Video and also files ending in .nfo and .txt.  The Ignore Filter de-selects those files in the torrent in the Download Dialog.  Then I have to manually click on the Tags I want to add.   With the filter I am suggesting, it would automatically add the Tags that match the filters after first applying the Ignore Filter.  Then I would only have to check the directory I want to save to, and if I want the Move on Complete (wish that was relocated to be more visable).  Constrains are more for once you have a Tag and what to do within it.  While this is for when you first add a torrent.

If you download and open a torrent, or download to a path and let it be loaded Automatic Import. In both cases it would apply the Tag(s) based on the content.  Where the current Automatic Import can only do it based on the Path. So with the Automatic Import, I would have to save to Path A for one Tag and Path B for another Tag.  With this idea, you would only need one path to import from, and the Tag(s) would be applied based on Content.  And as you can see in the image, I put a TICK Box, so it would be optional.

But I think this would be better than what the current Automatic Import can do. As well if I just download and open, it can again apply the Tags based on Content.

**Comment by HOTinHEELS** [comment]
@NaPurHab,  you should log in to beta chat and see the shitstorm that's brewing over your idea.

**Comment by NaPurHab** [comment]
No idea where to find that.   But the idea was to open dialog, to achieve a more fully thought out idea.  Good to know it is being discussed.

**Comment by parg** [comment]
I updated the tag constraints to have a variable called 'file_names_selected' which excluded any you have marked as 'do not download'. So you can use

<pre>matches( file_names_selected, "(\.mp4|\.ogg)$")</pre>

Does this satisfy your requirements? I would obviously prefer to avoid any need to add new UI elements to achieve this if Tags with suitable constraints can do the job (and more)

**Comment by NaPurHab** [comment]
Except that a Tag Contraint only applies when the torrent is already in the Tag.   The solutions I suggested above is for Add a brand new torrent via either opening the torrent or import from the auto-import.  At which point it would have no tag.

My idea is to add the new filter fields and remove the Tag entry from the Auto-Import, to make it a pure import.  Then Apply the Ignore Filter, then the New Tag by Type Filters.  In an import it would then start the torrent.  While in a Open it would display the download dialog if the user has it set to be used.  With the tags already selected by the filter. The user would only have to choose the save path.  Or if not using the Download Dialog, and this would be more common, then it would go straight to start the download.

It would streamline the download process.  In my case I click a download link and Open the torrent. So I go to the download dialog.  I have over 20TB and save things to collections on many different drives. Having the Tags By content would mean I only have to set the download path.

**Comment by parg** [comment]
Tag Constraints automatically assign downloads to tags based on their constraint. If you have a constraint of 'true' than ALL of your downloads will automatically be assigned to the tag. If your tag has a constraint of 'isComplete' then all complete downloads will automatically be assigned to it.

If your tag has a constraint like the one in my previous post then all downloads that had at least one file selected for download and ending in .mp4 or .ogg will *automatically* be assigned to that tag when the downlad is added. 

Try it

**Comment by NaPurHab** [comment]
I just did. I will explain what I did, then why it is not suitable for people who can barely use a computer. And there are a lot of them out there. Call them Average Users. I used to do Database Programming, and the biggest problem was dumbing down the input interface for the Average Users.

So, to start I took 2 torrents that contained MP3 and FLAC files. Changed their assigned Tag to Untagged.   Then I applied the following constraint.

matches( file_names_selected, "(\.mp3|\wav|\.ogg|\.flac)$")

It gathered all the torrents that contained these extensions.  The 2 torrents that I mentioned, plus some that I had in other tags, like Keep_Seeding. I use Keep_Seeding a storage area. The music I get in various formats all get converted to mp3/128 and added to 'My Music'.  Then instead of just deleting the torrent like a lot of people would do. I drop into Keep_Seeding and remove the Audio Tag.  Then if I am running out of space at a future point. I go into Keep_Seeding and remove torrents on the drive I need space. 
I also added a random torrent from the Anon:Shares that had Flac and Mp3 files, and in the Download dialog I selected no tags.  And yes it then assigned the Audio Tag.

But the problem is that constraints are very flexable, but as I just described, they apply to all torrents. Both new and existing.  As described above, I Re-Tag things at later times. For example I download a Video that has a high bit-rate, say 15000kbs, but I find that too high for my PLEX streaming, so I transcode to 2500kbs.  But then I Re-Tag it to Keep Seeding because it has Few Seeds.  Using a constraint like:

matches( file_names_selected, "(\.mkv|\mp4|\.avi|\.mpg)$")

would result in Un-Doing all my Re-Tagging.

But lets get back to those Average Users.  Finding the documentation on Constraints and then understanding it, would not be possible for most of them.  Even I, who have a programming background in Databases (never did 'C' or Java), am having problems understanding it.  The Constrains documentation is hidden in the GitHub Wiki Tab, under JavaScript, then a Link inline in the text of the 3rd paragraph. Once the link is followed, then it is half way down the page. And then it is difficult for me with a programming background to understand.  The Average User would be completely lost.

So look at my idea as remove the TAG assignment from the Auto-Import.   Then Add the Form for Tag Assignment to replace it, as in the Mock-Up.  Then on Adding a New Torrent, either via Download or Import, Apply the Ignore Section (perhaps move from 'Files' to 'Files/torrents' page), the Apply the Contents of the Form. Then it only applies to NEW torrents, instead of applying system wide like the constraint example.

Think of the form as a way to make the constraint User Friendly, but also limit it to only New Torrents. For example:

![biglybt new torrent filter 2](https://user-images.githubusercontent.com/37715552/52009032-eca2c100-249f-11e9-967f-0164d199fe62.png)

would become a set of constrains. That only apply to NEW Torrents.

matches( file_names_selected, "(\.mkv|\.mp4|\.avi|\.wmv|\.mpg)$")
matches( file_names_selected, "(\.mp3|\.wav|\.wma|\.flac|\.ogg)$")
matches( file_names_selected, "(\.epub|\.pdf|\.mobi|\.lrf|\.opf)$")

So my idea makes it User Friendly to set these filters, and only applies to New Torrents. And even includes a Default if none of the above apply.  And doesn't undo Tag-Reassignment done at a later time, as the constraint did in my test.

**Comment by parg** [comment]
If you only want to apply it to new torrents then first create a tag, call it 'existing', and manually assign all downloads to it (crtl+a in library view and drag-drop to the tag)

then modify you constraint(s) to read 

!hasTag( "existing" ) && matches(...)

You could create a 'recently_added' tag with a constraint of 'age > 60' and add this to the mix

!( hasTag( "existing" ) || hasTag( "recently_added" ) && matches(...)

Anyway, I understand your points about making it easy for users

**Comment by HOTinHEELS** [comment]
@NaPurHab 
Menu->View->Friends->Decentralized Chat,  andlook for "Test" whre there's a field for Create/join custom channel: key -> **_BiglyBT: Beta: Chat_**  (paste into field)

**Comment by NaPurHab** [comment]
Ok, I see on Tumblr that you have added 'auto-tag based on file extensions  (incomplete)'.  So not working at the moment.

![biglybt new torrent filter 3](https://user-images.githubusercontent.com/37715552/52169447-9c796800-2706-11e9-98f2-570d2646b1b9.png)

In the above the numbered items are:  
1) Adjust length to balance with the subfolder field. I often edit the Subfolder and a bit more room to see the name would help.
2) Remove the More that then show the Move on Complete, then clicking that shows Set/Clear.  Just put them on the next line in the empty space on the right.
3) This is the Incomplete part, as it is clearly not setting the Initial Tags.

I still think the Ignore and Auto Tag should be moved to the Files: Torrents screen.  Here is a mockup:
![biglybt new torrent filter](https://user-images.githubusercontent.com/37715552/52169493-612b6900-2707-11e9-9fba-003c221293b6.png)

1) Remove the Assign Tag on Auto Import, it is redundant.
2) Change this to read:  Default when none of the above match.
    or something like that.

Those 2 changes, combined with the Optional nature of Auto-Tagging means that new torrents Imported or Opened will have no Tag, or the Default if Tagging is ON, Or specific Tagging if extension lists are filled in.  Show work a treat when you finish it.

And why I want to see it all on the Files: Torrents.  It is basically an upgrade of the Assign to Tag on Import, that I recommend removing as it is Redundant.  Always thought it needed more. After all I am not going to have different save paths for every tag type, that would get tedious to always have to change the save path in my browser.  This is going to be much more friendly to Beginner/Average Users, and still flexable for more advanced users.  Besides the Files Screen is getting crowded.

You could even take it further, add an option to say Only One Tag Applies when Turned ON, First Tag that Applies. I.E. if I have a Torrent with 3 files in it, say 'War and Peace', 1 movie, 1 Audio Book, and 1 ePub. The user would then have the option to let it apply all 2 tags, or First that Applies. Which in the above example would be Video.  This one I would just add to the Right of the Enable Auto-tagging, if you decide to do so.

Anyway, looks good. Still would prefer it on Files:Torrents though.

**Comment by parg** [comment]
B10 has an update, might be working

**Comment by parg** [comment]
Regarding (1) there are other uses for the 'assign tag on auto-import'

**Comment by NaPurHab** [comment]
Ok at 2 hours after, still no B10.  See images below.  I included 2, because 1) is the Updater during Startup, 2) is the Updater when the program has been running a while.   2 different styles, perhaps you could harmonise them.  But the point is if you look at the bottom of the first one.

As to the 'assign tag on auto-import', it make the assumption that everything you put in a path is going to get one Tag.  That is what the new section would do, Allow Tag by extension. And the Assumption made with 'assign tag on auto-import' is Redundant as there is the 'When none of the above match' which would be the Assumption.
When I choose to save torrents to the HD, I just use one path. Others might have several, ie  \IE\download  \Chrome\download   \Opera\download.   But assuming that each would be tagged IE Chrome Opera as tags does not make sense.  They are just locations, like looking for your car keys when you misplace them.   The Auto-Tag allows some decision making in Initial-Tagging. And has the catch-all 'When none of the above match'.  But if that is what your going to do, fine.    Just a thought though, perhaps instead of the labels being 'Assign to Tag' they should be 'Initial Tag(s)' [; separated].  An example would be:
.mkv   Video;Convert
.mp4  Video
I convert all MKV to MP4 with Web Optimization.  I also seed to Min 2:1, so the convert would be to tell me what need to be converted.  Once converted I remove the Tag and just wait for Target Share Ratio to take effect.   So allowing Multiple Tags for each Extension Set, might be a good idea too.  But still think the 'assign tag on auto-import' is Redundant.   If you do allow multiple Tags, I suggest moving the Labels 'File Extension [; separated]' & 'Assign Tag [; separated]' to be Headers over the Fields, would look cleaner as Column Headers.  Also  the Enable Auto Tagging with Auto Tagging seems a bit of repeating yourself.  So putting the column headers in place of the 2nd Auto-tagging, would look nice and not use additional space.

Anyway here are the 2 snips of the Updater displays.  Just did a check at 2:15 since your post and B10 Just turned up.  Consider Harmonising the 2 below images.
![biglybt updater 1](https://user-images.githubusercontent.com/37715552/52181268-17ea2080-27be-11e9-9f4f-5477642e5fd4.png)
![biglybt update 2](https://user-images.githubusercontent.com/37715552/52181271-1d476b00-27be-11e9-957a-45e6003c04e8.png)

**Comment by parg** [comment]
Hopefully things are working ok now!

For the assign-tag-on-auto-import - I use it to pick up content from a separate plugin that dumps torrent files from Amazon S3 buckets into various folders. The tag is then used to auto-generate an RSS feed that is then dumped by the RSSToChat plugin into a chat channel for people to download. Voila an automatic distribution system (as evidenced here: https://github.com/BiglySoftware/BiglyBT/wiki/Updating-BiglyBT )

**Comment by NaPurHab** [comment]
For the import from Amazon S3, if the files have specific Masks, then the solution would be to make the auto-tagging use a file mask, instead of just extensions.  For example:
*.mkv;*.mp4    Video
*AMZN*.torrent;*S3*.*  RSSFeed
Doctor Who*.*   DoctorWho

But just a suggestion.

**Comment by parg** [comment]
that would be because you don't need the leading '.' - after all the extension is MKV not .MKV
