### ISSUE TITLE
Option to disable UI refreshing while minimized

### ISSUE THREAD

**Issue by Xemnarth** [BiglySoftware/BiglyBT#842]
Topic.
Related: https://github.com/BiglySoftware/BiglyBT/issues/650

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Or if ui is not in focus. It consumes CPU cycles while in background behind other windows :(

**Comment by parg** [comment]
I'll add an option to disable updates when minimised. Can't do "when not in focus" really.

**Comment by parg** [comment]
in 3501_B19
