### ISSUE TITLE
BiglyBT trying to send emails

### ISSUE THREAD

**Issue by eoinkennedy** [BiglySoftware/BiglyBT#846]
* Windows 10 1809
* BiglyBT Version Number 1.8.0.0

Blocked by port blocking rule 	C:\PROGRAM FILES\BIGLYBT\BIGLYBT.EXE	Anti-virus Standard Protection:Prevent mass mailing worms from sending mail	46.23.61.216:25

What or why is BiglyBT trying to connect to an SMTP server?

**Comment by parg** [comment]
It isn't - you are attempting to connect to a peer that has been configured to listen on port 25.

**Comment by parg** [comment]
There is an option to ignore peers with given ports under Tools->Transfer: Ignore peers with these data ports (at the bottom)
