### ISSUE TITLE
tor / socks failing

### ISSUE THREAD

**Issue by ghost** [BiglySoftware/BiglyBT#853]
since tor release-0.3.5 socks connection is no longer possible

[warn] socks5: parsing failed - invalid user/pass authentication message.
[warn] Fetching socks handshake failed. Closing.

**Comment by parg** [comment]
BiglyBT currently uses Tor 0.3.3.9 - where are you seeing this?

**Comment by mppdidi** [comment]
From the external tor process

**Comment by parg** [comment]
Put in an arbitrary username and password in BiglyBT - Tor uses socks auth for stream isolation (by default) and I guess it has started bitching about having a blank user/password.

Or maybe change the torrc to specify 'NoIsolateSOCKSAuth' (dunno if it will fix things) - https://www.torproject.org/docs/tor-manual.html.en
