### ISSUE TITLE
linux ipv6

### ISSUE THREAD

**Issue by mppdidi** [BiglySoftware/BiglyBT#854]
No ipv6 addresses are detected running on linux - Enable IPv6 support is checked. What am I missing here ?

**Comment by parg** [comment]
Do you have an IPv6 dht running under Statistics ?

**Comment by mppdidi** [comment]
No.

**Comment by parg** [comment]
the you don't have a functioning ipv6 network stack

**Comment by mppdidi** [comment]
I do - every other app works just fine with ipv6.
