### ISSUE TITLE
Meta Search with Jackett timeout exception

### ISSUE THREAD

**Issue by GlavitsBalazs** [BiglySoftware/BiglyBT#857]
Jackett v. 0.10.692.0 is running on my system and I wish to be able to access it directly from BiglyBT. I have followed [this helpful wiki page](https://github.com/BiglySoftware/BiglyBT/wiki/Search-Templates) with success, for setting up Meta Search to use Jackett. However on querying I get the error message: 
`I/O Exception while downloading 'http://127.0.0.1:9117/api/v2.0/indexers/all/results', Read timed out`
This is not very surprising, because my Jackett is configured to search many (25+) indexers, so naturally it takes a long time to go through them all. To confirm this I tried accessing the same query URL that BiglyBT timed out on, in my web browser (Chrome) and indeed after quite a long time (5-10 seconds) Jackett responds with the desired JSON.

**My Question:** How to configure Meta Search to allow more time for my Jackett query to complete?

System information: `Java 1.8.0_191 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_191
SWT v4922, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B1.8.0.0/4 az3`

**Comment by parg** [comment]
Join the beta program - there is an option under Tools->Options->Search to extend the timeout

**Comment by GlavitsBalazs** [comment]
Thank you I definitely will. Though I hope that this feature gets included in the next version.
