### ISSUE TITLE
Uninstalling vuze force a shutdown of BiglyBT

### ISSUE THREAD

**Issue by djack42** [BiglySoftware/BiglyBT#859]
* OS and version
**> Windows 10 1803**
* BiglyBT Version Number
**> Latest vuze and BiglyBT 1.8.0.0**

I just installed BiglyBT in place of Vuze, migration went well (but torrents were not listed fast enough at launch though, i had the time to think something went wrong and was about to reinstall...)
**Anyway, as the new BiglyBT was running well, i went to uninstall Vuze and BiglyBT was shutdown** when Vuze was trying to close all running instance of itself.

Because BiglyBT is a fork of Vuze, maybe the uninstall wizard of Vuze detects BiglyBT as one of his.
I don't mind if you just close the issue as this is just a one time thing not that annoying.

**Comment by bigdgun** [comment]
I have been using BiglyBT for some time and it has been successful. Yesterday, VUZE forced it's way back onto my PC and I am unable to uninstall it. In fact, it isn't even listed in my program files. What happens if I download VUZE again and then uninstall it? Will it interfere with the operation of BiglyBT?

**Comment by parg** [comment]
Just go to 

C:\Program Files

or

C:\Program Files (x86)

and delete the Vuze folder?

**Comment by bigdgun** [comment]
Thank you for responding. I have tried numerous times, but it tells me that the folder is in use. I opened the folder and there is no "uninstall.exe". I have attached a screen print of what my pc is telling me. Can I reinstall Vuze and then hope to delete it or will that just delete BiglyBT?
Thanks again.
    On Monday, May 20, 2019, 10:51:39 AM PDT, parg <notifications@github.com> wrote:  
 
 
Just go to

C:\Program Files

or

C:\Program Files (x86)

and delete the Vuze folder?

**Comment by parg** [comment]
Vuze and BiglyBT are independent installs so you can uninstall one without affecting the other. They do however share one thing, the port they listen on for various commands such as 'shut down' - so uninstalling Vuze may well shut down BiglyBT if it is running. However, that is all it will do.

If the folder is in use perhaps open up TaskManager and see if there is a Vuze.exe or similar running? Some Vuze related process must still be running and locking that folder.

You could install and uninstall Vuze to see if that helps - just make sure that you don't have BiglyBT running at the time to potentially cause any confusion.

**Comment by bigdgun** [comment]
I installed and then uninstalled Vuze. This time it worked including removal of the old uninstall which failed. Thanks for your encouragement.
    On Tuesday, May 21, 2019, 07:22:15 AM PDT, parg <notifications@github.com> wrote:  
 
 
Vuze and BiglyBT are independent installs so you can uninstall one without affecting the other. They do however share one thing, the port they listen on for various commands such as 'shut down' - so uninstalling Vuze may well shut down BiglyBT if it is running. However, that is all it will do.

If the folder is in use perhaps open up TaskManager and see if there is a Vuze.exe or similar running? Some Vuze related process must still be running and locking that folder.

You could install and uninstall Vuze to see if that helps - just make sure that you don't have BiglyBT running at the time to potentially cause any confusion.
