### ISSUE TITLE
mldht does not work

### ISSUE THREAD

**Issue by hexinn** [BiglySoftware/BiglyBT#86]
Java 9 (64 bit)
  Oracle Corporation
/usr/lib/jvm/java-9-oracle

SWT v4757, gtk/3.18.9
Linux v4.10.0-37-generic, amd64 (64 bit)
B1.0.2.1_B10/4 az3

There is log :

> [10:06:32] Starting DHT on port 49001
> [10:06:32] Loaded 0 entries from cache. Cache was 681min old. Reusing old id = true
> [10:06:33] Starting RPC Server
> [10:06:33] DNS lookupg for router.silotis.usfailed: router.silotis.us: 未知的名称或服务
> [10:06:33] DNS lookupg for router.silotis.usfailed: router.silotis.us
> [10:06:34] Starting DHT on port 49001
> [10:06:34] DNS lookupg for router.silotis.usfailed: router.silotis.us
> [10:06:34] Loaded 0 entries from cache. Cache was 145min old. Reusing old id = true
> [10:06:42] Starting RPC Server
> [10:06:44] DNS lookupg for router.silotis.usfailed: router.silotis.us: 未知的名称或服务

**Comment by parg** [comment]
Unlikely to be associated with the Java version (running fine for me on 9). Your error is with your DNS most likely, the bootstrap node is failing to resolve. The code has four to select from (I assume randomly)

	InetSocketAddress.createUnresolved("dht.transmissionbt.com", 6881),
	InetSocketAddress.createUnresolved("router.bittorrent.com", 6881),
	InetSocketAddress.createUnresolved("router.utorrent.com", 6881),
	InetSocketAddress.createUnresolved("router.silotis.us", 6881),

For me:

>nslookup
Default Server:  google-public-dns-a.google.com
Address:  8.8.8.8

> router.silotis.us
Server:  google-public-dns-a.google.com
Address:  8.8.8.8

Name:    router.silotis.us
Address:  2604:180:3:bbb::3e82
