### ISSUE TITLE
Clicking on downloaded torrents in Classic UI consumes up to 40% of CPU.

### ISSUE THREAD

**Issue by Tacis** [BiglySoftware/BiglyBT#866]
Java 1.8.0_201 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_201
SWT v4922, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B1.8.0.0/4 az2

I have 35 downloaded torrents (all seeding). When I click on each torrent, there is a 1-2 seconds delay before the torrent is selected, and also I get up to 40% CPU usage by BiglyBT.exe in Task Manager. Classic UI.

Upgraded to BiglyBT yesterday because my Vuze said I should do it. Slightly disappointed in my decision, BiglyBT seems to use more of my resources doing the same thing.

**Comment by parg** [comment]
Definitely something not right - can you generate a debug.zip (Help menu, last option) and send it to bt@biglybt.com? thanks!

**Comment by Tacis** [comment]
Generated and send. Please check your mail. Thank you.

**Comment by parg** [comment]
Hmm, nothing obvious there - you seem to have enough Java memory allocated. As a test could you stop all of your downloads (pause them all via the File menu Transfers->Pause) and see if that makes any difference to the CPU usage when selecting them?

Also check your antivirus/firewall to ensure that BiglyBT.exe is excluded from any realtime network analysis, some products suck CPU when doing that.

Beyond that you could join the beta program (see the Help menu) and once installed reproduce the problem for a while and send over a new debug.zip - hopefully it will contain more info!

Thanks

**Comment by Tacis** [comment]
I don't have downloads, only 100% downloaded torrents, seeding.

Pausing/stopping them makes BiglyBT somewhat more responsive when I click/select torrents, but still up to 30% CPU usage. Check out the video: https://www.screencast.com/t/RUHFzX0xaQa I click each line, you can see what's happening.

Installed Beta, sent the debug zip.

**Comment by parg** [comment]
You've got me stumped - there's nothing particularly out of the ordinary although the thread_1.log does show CPU usage in the graphics thread in a few places in native 'clipping' code. That being said there isn't a whole lot of difference in this area between Vuze and BiglyBT apart from a GUI library update. What you could try is (if you still have Vuze installed)

grab the swt.jar from C:\Program Files\Vuze (or wherever installed) and replace the swt.jar in the BiglyBT install folder with that one (need to close BiglyBT first). Maybe backup the swt.jar before overwriting!

BiglyBT will try and update the swt.jar but you will at least get one run with the old one in place just to see if it is related to that

**Comment by parg** [comment]
Darn it! Not that I think it will make any difference but you could switch from classic UI to the 'non-classic-UI' under Tools->Options->Display->Start: UI chooser

One thing in general - force-seeding a lot of torrents should be avoided if possible as it does use resources (network, memory, cpu) - if you let BiglyBT schedule the torrents between a queued->seeding state by using a reasonable share-ratio target along with other seeding rule config (Tools->Options->Queue: max active torrents etc. ) then that can help.

**Comment by DeoW** [comment]
Tacis, is there a specific reason you choose to use the Classic UI?
I have just checked my system, running on the Options>Start>UI Chooser default (BiglyBT UI).
Selecting and deselecting cause no major variation of CPU, Memory, Disk or Network stats. I checked via Resource Monitor, and also Memory via Task Manager|Details. 
Clearly your Options>Startup&Shutdown>Java options are good, and I assume that the Options>Files>Torrents>Performance options are reasonable.
It would be very interesting to see if changing the UI made such a dramatic difference, but I am loathe to risk breaking a working horse on my side.

**Comment by parg** [comment]
Both UIs use the same underlying GUI library etc so I don't think it would make a difference. On the other hand I'm not aware of any other users with this problem. 

Are you sure you don't have some antivirus product that could be interfering? There have been many cases of these products causing CPU usage in the Vuze/BiglyBT process as they inject their code into it to snoop on things. Usually though this appears as CPU usage in the networking part of things, not the UI. Or perhaps you have a product that monitors application user interfaces somehow?

BiglyBT and Vuze don't share any common configuration files or runtimes so it is very hard to explain how Vuze on the second PC started displaying the same CPU usage!

**Comment by Tacis** [comment]
BiglyBT interface doesn't make a difference - there's also a delay between a click and selection.

As you can see from the video, not a lot of seeded torrents are downloaded simultaneously. Maybe 2-3 with not a lot of peers. Do all other force seeded but not downloaded (no peers connected) torrents affect system resources that much? And why does BiglyBT uses so much CPU only when I select the torrent in list?

DeoW, yes, there is a reason: I find classic UI much more usable (even despite newly found delays).

parg, I have Windows Defender with default settings. That's all.

After installing BiglyBT on the other machine, I chose to migrate settings from Vuze. Could it be maybe that BiglyBT somehow changed Vuze settings during that process?

**Comment by parg** [comment]
No, the Vuze config is left untouched. I made a minor change that will be in the next beta to remove a double 'selection event' when changing rows but don't think it'll make much difference.

**Comment by parg** [comment]
I've just released beta version B12 - please see if anything has improved (or got worse :)

**Comment by Tacis** [comment]
Huge difference to a better side! Still using a lot of CPU when clicking on the torrents, but the interface is much more responsive! Thank you!
