### ISSUE TITLE
Display Glitch on Show Details: Info

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#868]
This is from 'Show Details' on the 'Info' Tab.

![biglybt - details - info - stalled progress](https://user-images.githubusercontent.com/37715552/52304251-4f90ce00-2960-11e9-9380-7dca9587b377.png)

In the above image, the Status and the Pieces, Agree with each other.  But in the Progress the Checking on the right is Stalled.  If I keep watching, Status and Pieces Update, but the Progress continues to be stalled.

![biglybt - details - info - stalled progress 2](https://user-images.githubusercontent.com/37715552/52304259-54ee1880-2960-11e9-82d9-daf01ef867f4.png)

If I change to something else, then come back, you can see in this Image that the Progress updated on the refreshed view. But continues to not Keep up.  Status is at 39.5% but in the Progress Checking is again stalled at 37.4%.

Minor display glitch, see if you can reproduce.

* Windows 10 1809
* BiglyBT Version 18.0.1_B12
* Java 1.8.0_201 (64 bit)

**Comment by parg** [comment]
fixed next beta, thanks
