### ISSUE TITLE
Dashboard problem.

### ISSUE THREAD

**Issue by Achaean** [BiglySoftware/BiglyBT#869]
Hi! :-)
I'm on Devuan x64 KDE, with Bigly v.1v.8.
Java 1.8.0_181 (64 bit)
  Oracle Corporation
/usr/lib/jvm/java-8-openjdk-amd64/jre

SWT v4922, gtk/3.22.11, zoom=100, dpi=96
Linux v4.9.0-8-amd64, amd64 (64 bit)
B1.8.0.0/4 az3

I don't really know, what Dashboard is, but it seems to have a problem:
No more handles, because no underlying browser available.

![dashboard](https://user-images.githubusercontent.com/3608053/52334760-1eb8a380-2a09-11e9-96b0-6f941a13c66c.png)

**Comment by TuxPaper** [comment]
hmm, is there a webkit package for Devuan that you can install?

What's the default browser on Devuan?  I'm guessing Firefox since the message complains about no webkit :P

**Comment by Achaean** [comment]
1) Well...installing Devuan with KDE as the desktop of your choice, leaves you with Konqueror as your default and actually the only preinstalled browser.
Welcome to the 90s! :-)

I have installed (and defaulted) Waterfox here. I prefer it over Firefox, for a number of reasons (eg. better privacy settings).

2) Now (that you pointed me to the right direction), I can see that WebKit is already installed, but I was lack the GTK bindings.
Installing libwebkitgtk-3.0-0, solved the problem.

THANKS again!!! :-)
