### ISSUE TITLE
1 of 2 ways to "Add Category" .. doesn't

### ISSUE THREAD

**Issue by csylvain** [BiglySoftware/BiglyBT#87]
(currently using B1.0.2.1_B03/4 az3)

single right-click on torrent in lower panel of Library opens a 'short form' menu. Organize -> Assign Category -> Add Category results in a flash of a window appearing and then vanishing. Can't add a category that way

workaround: double right-click on torrent to open a 'long form' menu. Assign Category -> Add Category results in a text entry window opening (and remaining until "OK" is pressed!)

**Comment by parg** [comment]
fixed in next beta, thanks (B11 to come sometime soonish!)
