### ISSUE TITLE
more columns for archived downloads

### ISSUE THREAD

**Issue by hatbrox** [BiglySoftware/BiglyBT#873]
Hello,

The "archived downloads" has too few columns to choose from. I really like the numerous columns available in the library (and the library files).
Please keep the same columns for the archived downloads.
At the very, very least, I would like to have the tracker name and the file location.

* windows 2002 R2
* B1.7.0.0/4 az3
* For *nix: Desktop Environment

**Comment by parg** [comment]
The point of archiving is to reduce the resource requirements for an archived download to a minimum. What would be the point of archiving if it retained all the information? 

Just leave it in your library in a unarchived state.

You can right-click and select 'show in explorer' to see the download location. I suppose this could be added as a column if of use.

**Comment by hatbrox** [comment]
"What would be the point of archiving if it retained all the information?"
that's a strange statement. archiving doesn't imply loosing any information. When I restore an archive I don't lose any information!!!
Archiving is all about freeing some CPU and some RAM. I can't see how showing the tracker name, file location would increase resource requirement. These are static information that you read from a file. They cost nothing. Yet they are very useful. I suggested to have the same columns as in the library for simplicity of the argument, I didn't want to list all columns (there are so many) that I'd like to see.

Also, When I archive I mean it. the torrent data are stored is a USB hard drive that would be stored elsewhere, so my computer doesn't need to have all hard drives connected (that also saves electricity and I don't need a big computer with thens of disks)

I use the (un)archive functionality a lot (back and forth) and with this experience, I often need to know, as a minimum what tracker the torrent belongs too or on what disk where the files are. I do use the right click command to reveal the file location but it only works for 1 torrent at a time but most of the time it doesn't work because my archive are on disconnected disks.
I've been using the tags as a workaround (tracker name, hard drive and more) for years but I sometimes forget to update them or set them.

I only suggest adding more columns because I recently had problems finding the correct archive disks (wrong + missing tags). 

"Just leave it in your library in a unarchived state." I'm not understanding this suggestion. I'll assume you mean to leave the torrent in a stopped state. 
This suggestion seems to defeat the purpose of Archiving.
In any case, it doesn't work well, I tried it in Azureus, then Vuze before Archiving was introduced:

- A stopped torrent still consume more resources than an archived one. 
- I still see the torrent the library
- I also noticed that when Bigly crashes, it sometimes fail to see that a torrent was in stopped state and it would resume all torrents.

most people won't not notice it, but when you have 1400 torrents (about half are archived), you feel the performance tax

But if the Bigly developers don't want to do it, that's fine, I'll still love Bigly.

**Comment by parg** [comment]
My comment regarding 'retaining all the information' was referring to within the archive-view user interface, not the underlying archive. 

Like I said, I can add the save-location as an optional column fairly easily as the information is already denormalized.

**Comment by hatbrox** [comment]
ok, file location would already be great. Appreciate if this feature can be put in your backlog. Thanks

**Comment by parg** [comment]
It is already done and will be in the next beta.

If you think having a tracker there too would be a major benefit then I can consider adding that although the problem there is that torrents in general have multiple trackers and in that case you'd end up with a random one.

If you have a limited set of trackers that you normally engage with then you could set up a Tag for each one and use 'tracker properties' to auto-tag them. Unfortunately at the moment auto-tags aren't archived but I have changed that as I can see they would be generally useful for documentation purposes.

**Comment by hatbrox** [comment]
that's fantastic. My torrents are always "single tracker" so the tag functionality is still a very good alternative.
Thanks.

**Comment by parg** [comment]
I also added 'Main Tracker' to the columns - it will populate for newly archived files but not for existing ones. For multi-tracker downloads you will end up with whatever is currently set to be the announce-url
