### ISSUE TITLE
unable to get correct public IPv6 addr behind router

### ISSUE THREAD

**Issue by SUCM** [BiglySoftware/BiglyBT#880]
Java 1.8.0_181 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_181

SWT v4922, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B1.8.0.0/4 az3

while behind a router with NAT&port forwarding, IPv4 inbound and outbound tests worked just fine when doing Network Status test since BiglyBT correctly detects the IPv4 addr ISP assigned to the router . However, Network status test failed to get the correct public IPv6 addr. BiglyBT thinks the IPv6 addr assign by router to device within LAN is the public IPv6 addr, so IPv6 tests would always fail.

However, I can see the correct public IPv6 addr being listed as one of the IPv6 addrs in Option -> Connection -> Advanced Network Settings

**Comment by parg** [comment]
Works for me - if you can see the address under Advanced Network Settings then that address is assigned to your computer...

Generally there is no NAT with IPv6, all IPv6 addresses (of the right type of course) are 'public' - that's not to say that a firewall won't block them.

**Comment by SUCM** [comment]
google, gmail and http://whatismyv6.com/ shows my public IPv6 as *:283e. Network Status test also listed 283e as one of the Bindable addresses, but Network Status test says my Default public IPv6 address is *:a26c. *:a26c is the IPv6 addr from my route and only visible within the LAN

I get below result when doing IPv6 for just inbound test

IPv6 test
    Default public IPv6 address: *:a26c
    Testing connectivity...
        Connect failed
Test complete

Interestingly, my IPv4 UDP outbound is not working while inbound works just fine even when I disabled firewall on both router and PC during the test

**Comment by parg** [comment]
AFAIK the code attempts to select the 'best' global scope v6 address from those available:

	public static boolean isGlobalAddressV6(InetAddress addr) {
		return addr instanceof Inet6Address && !addr.isAnyLocalAddress() && !addr.isLinkLocalAddress() && !addr.isLoopbackAddress() && !addr.isMulticastAddress() && !addr.isSiteLocalAddress() && !((Inet6Address)addr).isIPv4CompatibleAddress();
	}

**Comment by SUCM** [comment]
perhaps the algorithm needs some improvement. I see that BiglyBT is selecting the very first IPv6 addr in the list of the interface as the public addr. a LAN IPv4 addr was the first in the same list while the selected IPv6 addr being the second in the list. the correct IPv6 addr is the 2nd last one in the list right before the fe80::*:a26c local scoped IPv6 addr

not sure if I can helps to improve the algorithm, but I guess the problem is that there are 4 IPv6 addrs of the same scope with only one being the correct addr. ipconfig /all says that 2 of the 4 IPv6 addrs are expired and BiglyBT's chosen IPv6 addr is the first and only non-leased/dynamic IPv6 addr. the correct IPv6 addr is the only one that's dynamic/leased and not expired

my ISP does change IPv6 addr once every couple days

**Comment by SUCM** [comment]
seems like a regression or some config wasn't imported properly. my BiglyBT configuration was imported from Vuze last week. I existed BiglyBT and launched Vuze today to do the same test. all IPv4/IPv6*TCP/UDP*inbound/outbound combos works with Vuze.

I exit Vuze, then start BiglyBT again to run the same IPv4/IPv6*TCP/UDP*inbound/outbound combos. I get these different results with BiglyBT. haven't touch any config yet, so all ports and connection config should be the same
1. all IPv6 tests failed because wrong IPv6 addr was picked
2. UDP outbound test failed, but inbound tests works

**Comment by SUCM** [comment]
actually, the same IPv6 addr is picked now, I was just unlucky to hit Ipv6 addr refresh while switchign between Vuze and BiglyBT. with the same IPv6 addr picked by both, BiglyBT still failed all IPv6 tests while Vuze worked just fine

**Comment by parg** [comment]
Try the latest beta and see if anything has improved

**Comment by SUCM** [comment]
how do I download beta without joining the beta program? is there a jar file that I can download and replace, then put back original jar file to go back to current stable?

**Comment by parg** [comment]
https://github.com/BiglySoftware/BiglyBT/wiki/Updating-BiglyBT

**Comment by SUCM** [comment]
don't see any difference with core_BiglyBT1801-B18-signed.jar. still fail the same way

this is BiglyBT 1801_B18 result
[code]
Test starting
Default public address is *.*.*.*
Bindable addresses: 127.0.0.1, 0:0:0:0:0:0:0:1, 192.168.*.* *****
No explicit bind address set
Testing HTTP outbound
    Test successful
Testing TCP outbound
    Test successful
Testing UDP outbound
    Test failed: Outbound test failed
Testing TCP port X inbound
    Test successful
Testing UDP port X inbound
    Sending outbound packet and waiting for reply probe (timeout=5000)
    Sending completion event
    Test successful
1 public/external addresses found
    *.*.*.*
    AS details: *****
IPv6 test
    Default public IPv6 address: *:a26c
    Testing connectivity...
        Connect failed
Test complete
[code]

this is Vuze result
[code]
Test starting
Default public address is *.*.*.*
Bindable addresses: 127.0.0.1, 0:0:0:0:0:0:0:1, 192.168.*.* *****
No explicit bind address set
Testing HTTP outbound
    Test successful
Testing TCP outbound
    Test successful
Testing UDP outbound
    Test successful
2 public/external addresses found
     *.*.*.*
    AS details: *****
     *.*.*.*
    AS details: *****
IPv6 test
    Default public IPv6 address: *:a26c
    Testing connectivity...
        Connect succeeded, reported IPv6 address: *:a26c
Test complete
[code]

**Comment by parg** [comment]
Perhaps you can look fog configuration differences - the Help menu has an Advanced->Show Config Changes option

check for anything different between Vuze and BiglyBT

**Comment by SUCM** [comment]
other than the non-common (between the two client) options, everything else is the same except mlDHT and tracker server. I set them to match then restart BiglyBT to redo the test, but still failing the same way. are the test criteria/server different?

**Comment by SUCM** [comment]
the fact that Vuze found 2 external IPv4 addrs (although one is IPv6 tunnel) already suggest both are doing somewhat different detection

**Comment by parg** [comment]
For UDP outbound testing all BiglyBT does is attempt to contact the BiglyBT version server via UDP. Unless you have configured 'anonymous updates' in which case this will fail.

**Comment by parg** [comment]
Also the test for IPv6 connectivity is also performed via a connection to the version server, which again will fail for 'anonymous updates'

**Comment by SUCM** [comment]
ah, that's it. disabling update anonymously fix the issue.

I'm was worried since BiglyBT had a notification saying outbound UDP doesn't work need decentralized distribution needs that to work

**Comment by parg** [comment]
bit of an 'unintended consequence' of that setting :(

**Comment by SUCM** [comment]
got it XD
I guess the other plugin update torrent privacy auto set to anonymous only is due to the same reason?

**Comment by parg** [comment]
yup
