### ISSUE TITLE
[feature request] make per tracker/torrent exception on crypto tracker extension ?

### ISSUE THREAD

**Issue by SUCM** [BiglySoftware/BiglyBT#881]
I have crypto tracker extension enabled globally, but some of the trackers, especially the private trackers, don't not support this and will always fail with invalid port of 0. instead of globally disable crypto tracker extension, would it be possible to configure a list of trackers in option or per torrent to disable crypto tracker extension for these private trackers while keep crypto tracker extension ON for rest of the torrents/trackers?

**Comment by parg** [comment]
There will be an option in the all-trackers view to disable cryptoport on a per-tracker basis in the next beta

**Comment by SUCM** [comment]
thanks

**Comment by SUCM** [comment]
I haven't been able to find this option even in 2.1.0.0. can you let me know what's the text (in torrent adding panel or somewhere?) or show a screenshot of where it is?

**Comment by SUCM** [comment]
ok, found it. thought it never made into any non-beta release

**Comment by parg** [comment]
Been there for almost a year.

**Comment by SUCM** [comment]
just that I had never find it and haven't upgrade Bigly until recently. plus some of the private tracker had banned Bigly+Vuze due to this despite my explanation that this is not for cheating, so I can't use Bigly unless Bigly can tell private tracker it's some other client like qBtorrent, Bittorrent, Deluge. all in all, haven't really test/look for it hard enough until now because it looks like more non-private trackers are starting to return invalid port due to not supporting this and causes problems

**Comment by SUCM** [comment]
also, it looks like I can't select multiple trackers in the search result to set this option. I selected multiple trackers from "invalid port" search result and tick the option from right click, but right click on each individual tracker still shows option not set and torrents updating tracker still says invalid port. I had to configure tracker one by one, then torrents updating tracker would change status to online
