### ISSUE TITLE
unable to download any plugin

### ISSUE THREAD

**Issue by SUCM** [BiglySoftware/BiglyBT#882]
Java 1.8.0_181 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_181

SWT v4922, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B1.8.0.0/4 az3

for unknown reason, I can retrieve list and view plugin details on BiglyBT, but downloading (for installation) through BiglyBT client or plugin update never download anything. the download progress would just stuck at 0% forever. download from web through regular browser works just fine

for example, I have plugins_azneti2phelper-win32_0.9.38.1.1.zip plugin update torrent that BiglyBT automatically added that showed 263 (varies +- a few) seeds since couple hours ago, but I'm never connected to any seed/peer to download it. However, other torrents are working just fine

**Comment by SUCM** [comment]
using BiglyBT, I get the following error for tracker. download finishes in a breeze when loading the same torrent on Vuze
Error: Offline - Network not enabled for url 'http://tracker.amazonaws.com:6969/announce'

**Comment by parg** [comment]
You've disabled the public network - check the Privacy tab

**Comment by SUCM** [comment]
yup, that was the issue. it's a torrent added by BiglyBT itself and I have all 3 networks checked in Options->Connection. I don't know why this plugin update torrent would disable public network. all other torrents I add have public network enabled

also noticed that when configure static potr to bind, the update restart of Bigly usually get unable to bind to port X due to address already in use. I ned to manually exit Bigly, then launch again after waiting for a minute or so to avoid that port binding problem

**Comment by TuxPaper** [comment]
I think it may be the Options->Interface->Start->Update Anonymously checkbox that's overriding it.

**Comment by SUCM** [comment]
yup. it took great effort, but we eventually realized that in #880, which is another side effect of the Update Anonymously option
