### ISSUE TITLE
dark mode for windows possible? 

### ISSUE THREAD

**Issue by sparkysamza** [BiglySoftware/BiglyBT#884]
WIndows 10 N 1809 
Version 1.8.0

question is is it possible to get a dark mode as the white burns!

**Comment by parg** [comment]
There are some settings under Tools->Options->Interface->Color Scheme that might help but won't get you all the way :(

**Comment by sparkysamza** [comment]
damn that's a shame was hoping for a more all-rounded solution :L 
thanks though

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
biglybt is very configurable. Great. is this possible by plugin?

**Comment by parg** [comment]
Version 3.3, about to be released, has a better dark theme - enable it via Tools->Options->Interface->Color Scheme

Note that you will need Java 11 or higher to get the best result.
