### ISSUE TITLE
Force running of specified announcers, maybe mass-work on this & mass-deleting of specific trackers over thousands torrents 

### ISSUE THREAD

**Issue by hatewesterncivilization** [BiglySoftware/BiglyBT#885]
Java 11.0.2 (64 bit)
  Eclipse OpenJ9
q:\jdk-11.0.2+9

SWT v4924, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B1.8.0.1_B07/4 az3

About second suggestion I am not sure, maybe already somehow exists.

Also can I request providing of information how filter specific torrents state by a numbers? Also please filtering in the search field specific trackers messages and states.

**Comment by parg** [comment]
You've checked out the recently added 'All Trackers' view right?

**Comment by hatewesterncivilization** [comment]
Sorry for delay, yes, have checked yesterday after your remark, at the first onset removed interesting trackers. 

First suggestion still not implemented in All trackers view, must-have thing including both global and individual force-starting of trackes, also there are some hanging while listing-scrolling.

Can I hope for implementing of filtering in All trackers by the tracker message?

**Comment by parg** [comment]
I've added search on status.

Trackers have strict rules about how often they should be hit and also the way that multi-trackers are used. They wouldn't be happy with an option that caused an immediate update on potentially hundreds of torrents.
