### ISSUE TITLE
in Library view/tab, downloading torrent jumping between seeding and downloading panels

### ISSUE THREAD

**Issue by SUCM** [BiglySoftware/BiglyBT#887]
not sure what's going on, but when I was staring at BiglyBT downloading 204 files totalling 9MB out of a 100GB+ torrent (only need the txt files, not the other large files), that torrent was constantly jumping between seeding and downloading (incomplete section?) panels every 10-15 seconds. torrent eventually settled at seeding panel after it's done

searched through options, but didn't find any specific setting related to this behaviour

**Comment by SUCM** [comment]
ant to add that while still downloading, its Status shows something like "Downloading..." while it's in Seeding/Completed panel during the jumping phase

**Comment by parg** [comment]
weird one - perhaps there's some rounding error regarding small files completing out of such a large torrent. If I get a chance I'll take a look.

**Comment by parg** [comment]
maybe you could send the .torrent file to parg@users.sf.net - I'll see if I can reproduce it

**Comment by SUCM** [comment]
I selected to download only the ass files and nothing else @ https nyaa.si/view/938032

**Comment by parg** [comment]
Hopefully fixed in next beta, thanks
