### ISSUE TITLE
I2P helper modes

### ISSUE THREAD

**Issue by mppdidi** [BiglySoftware/BiglyBT#89]
Can you explain briefly the i2p helper modes - pure - mixed and bridged ?
When do they kick in - especially the bridged ?

Thank you

**Comment by parg** [comment]
The 'mixed' destination is used for network mixing operations - as clearnet and I2P torrents are being seeded by the client it is possible to correlate the clearnet and I2P identities of the client. The 'pure' destination is used for I2P-only downloads. The 'bridged' destination is used to delegate operations from the I2P network into the clearnet in a way that allows anonymous publication to the clearnet DHT.
