### ISSUE TITLE
Maybe last beta doesn't work properly

### ISSUE THREAD

**Issue by hatewesterncivilization** [BiglySoftware/BiglyBT#890]
parg, hello. Seems with last beta Bigly starts don't sending seeding data to trackers, maybe when there is additional announcers with main. Before that, say, with B07 this problem wasn't exists.

Now I am seeding days and megabytes sending to trackers sites is nothing. Hope, you will fix this thing as fast as possible.

**Comment by DeoW** [comment]
If you select a line in Library view, and look at the sub-tabs for Sources and also Peers, does what you see support non-communication with trackers?
My system is operating normally, with trackers refreshing on time. Looking at the Peers tab, the choking by both my machine and the recipient seems normal.

**Comment by parg** [comment]
Nothing has changed in this area in recent betas - more likely an issue with your tracker?

You can see what is being sent to trackers if you turn on logging (Tools->Options->Logging) and look in the console for lines like

[08:39:54.051] {tracker} Tracker Announcer is Requesting: http://<tracker>/announce?info_hash=%BA%1Eu%D3%F1%A4KAi%1B%CD%B8%C8%97%C0%81c%0A%E6S&peer_id=-AZ5750-7e0e3ZmQcgOo&port=61247&uploaded=0&downloaded=0&left=1908408320&compact=1&event=started&numwant=81'

the uploaded= and downloaded= are the amounts uploaded/downloaded in the last session (session = since the torrent was LAST started (i.e. started BiglyBT or it went from a queued/stopped state into a seeding state)

**Comment by hatewesterncivilization** [comment]
I'm think I'm catching something, it just stopping then announcing. There was 4 min for next announce, then Next field just nothing and empty or is this normal showing?

http://prntscr.com/mlv54n

Another one tracker node, tr4 on kinozal

http://prntscr.com/mlv5yj

Rutracker side same behavior

http://prntscr.com/mlv6hg

In Console with logging literally all 'uploaded=' just nil and rutracker's & kinozal's announcers even doesn't appears. Running time since client start - 1h 23 min

http://prntscr.com/mlv7be

Looks like there are maybe some blocking technique by who? ISP, govs, DPI, so on? Or maybe in Windows something going on, nut I even switched off the built-in Firewall.

What else can cause the problem? SWT library, which I suddenly updated to last? Isn't the announce period of announcers is the thing?

Now I'm going back to last beta, still investigating and fixing, waiting help from parg and guys. Thanks, mates.

**Comment by hatewesterncivilization** [comment]
Isn't OpenJ9 culprit.

**Comment by DeoW** [comment]
My B20 is working fine. Mine are all public trackers, none the same as ones you mentioned. My Refresh times are all around 30 minutes. Maybe try something like udp://9.rarbg.me:2770 or udp://9.rarbg.to:2750 which I believe result in the same tracker, or a widely used one like udp://tracker.coppersurfer.tk:6969

**Comment by hatewesterncivilization** [comment]
Sounds like it's a new strategies of this two trackers, rutracker done updated sended statistics, the problem solved. But kinozal still the same, will see.

**Comment by DeoW** [comment]
I am glad the problem has been solved.

**Comment by hatewesterncivilization** [comment]
> I am glad the problem has been solved.

But in fact it's BiglyBT stop request of announcers, will see what can say parg.

**Comment by hatewesterncivilization** [comment]
Thanks for support. In fact two trackers rutracker and kinozal now wait 2 hours before take an data from my PC. I have looking other users on kinozal, strange they are fine as usual.

**Comment by DeoW** [comment]
30 min is 1/2 hour

**Comment by hatewesterncivilization** [comment]
No, I think it's 30 min announce time itself and 30 min idle time before next announce, in fact it works right that. Rutracker & kinozal is something 1h 00 min (1h 00 min), 2 h! Before next announce!

**Comment by hatewesterncivilization** [comment]
So, it's politics right Bigly's reproted in addition by Rutracker & Kinozal, but I have look to others users, strange they are seems fine. Something is going on with this confusions.

**Comment by DeoW** [comment]
Interesting. On my machine, in Library view, the Sources subtab shows a column headed "Next". This is, for all my trackers, about 30 minutes. It counts down, the tracker engages, and the clock goes back to about 30 minutes. The process repeats indefinitely.
I think you might affect things positively if you change your settings at Options>Tracker>Server  "Tracker client poll interval".
I have Minimum=120, Maximum=3600, Increase by 60 Every 10 clients. That results in what I have described above.

**Comment by DeoW** [comment]
You also need to enable "Show Sub-tabs in Library views" at Options>Interface>Tables "Library section"
As to screenshots, I do not know how to obfuscate the details of my torrents. I know how to use the snipping tool, but graphics is a weakness of mine.

**Comment by hatewesterncivilization** [comment]
> You also need to enable "Show Sub-tabs in Library views" at Options>Interface>Tables "Library section"
> As to screenshots, I do not know how to obfuscate the details of my torrents. I know how to use the snipping tool, but graphics is a weakness of mine.

It's just selective selection while making an screenshots.

**Comment by hatewesterncivilization** [comment]
> You also need to enable "Show Sub-tabs in Library views" at Options>Interface>Tables "Library section"
> As to screenshots, I do not know how to obfuscate the details of my torrents. I know how to use the snipping tool, but graphics is a weakness of mine.

This settings addresses server on user's PC, but I've found other settings at Client tab, this is what a need to drive with like setting Minimum time between tracker announces in seconds. Was though 0 sec, I set it to 6 sec. Scarcely that will help, because this settings is pretty fine.

**Comment by hatewesterncivilization** [comment]
Last client start since uploaded overall 64 GB, but rutracker and kinozal for two persons showing only 4.8 & 1.75 GB at all.

**Comment by DeoW** [comment]
You are correct about setting the Client side, sorry for bad suggestion. My setting is 180 seconds between announces.

**Comment by hatewesterncivilization** [comment]
Maybe Nazarbayev, jewish, herman Merkel's DPI thing? As I know Merkel hardly do not approve and stops bittorrenting in Germany. Why I saying Nazarbayev together with Merkel, it's because they may secretly maintain relations between two nations. There are also Macron, Olland and great french nation which is not welcome bittorrenting.

**Comment by hatewesterncivilization** [comment]
Sorry for boring, but I suspect OpenJ9, yesterday I have used-in Java 12 early access instead of it, and first time kinozal starts quick showing 521 MB uploaded while before it was only >100 MB around. So, it's maybe OpenJ9 cause the problem, today in the evening I will once again finally check this thing. And if it so, I will be very glad.

**Comment by parg** [comment]
It is almost impossible for whatever you are seeing being caused by Java version unless it was something to do with some nuance of SSL - in which case you would be seeing explicit error messages.

**Comment by hatewesterncivilization** [comment]
I'm going to reinstall Windows, coz it looks like Windows was compromized by someone due to certificates vulnerable hole. I don't know, maybe there are bigger compromizing of PC through deepest level of OS and PC.

**Comment by hatewesterncivilization** [comment]
Is the next normal thing? It's calculated and adjusted in min interval and whole announce interval.

8:21:20.681] {tracker} Next tracker announce (unadjusted) will be in 3197s; 	| Torrent: 'SM-Trax [lossless]'
[18:21:20.681] {tracker} MIN INTERVAL CALC: override, perc = 50; 	| Torrent: 'SM-Trax [lossless]'
[18:21:20.681] {tracker} MIN INTERVAL CALC: min_interval=3207, interval=3197, orig=3197, new=3212, added=1614, perc=1.0031279; 	| Torrent: 'SM-Trax [lossless]'
[18:21:20.681] {tracker} Next tracker announce (adjusted) will be in 3212s; 	| Torrent: 'SM-Trax [lossless]'

**Comment by parg** [comment]
yes

**Comment by hatewesterncivilization** [comment]
That is, some other client Tixati just non-problematic works, so, it causes by Bigly. Looks like it is respect model of work to announcers propagandized by Bigly team, but in fact I completely can't work with this at several sites like rutracker and kinozal. 

Maybe, sometime ever it will changing, what a pity.
