### ISSUE TITLE
unable to load IPFilter.zip

### ISSUE THREAD

**Issue by SUCM** [BiglySoftware/BiglyBT#891]
somehow BiglyBT is unable to load this IPFilter when I click on Load Now. However, BiglyBT loads the zip file without issue if I download it to local HDD first, then point BiglyBT to the downloaded ipfilter.zip file

http://upd.emule-security.org/ipfilter.zip

**Comment by parg** [comment]
Loads for me

**Comment by SUCM** [comment]
sorry, now it loads...

clicking Load Now would grey out for less than 1 second and come back clickable when I opened the ticket, but it's working now
