### ISSUE TITLE
Problem spontaneously solved- torrents all stopped for 3 hours...

### ISSUE THREAD

**Issue by mkrier** [BiglySoftware/BiglyBT#898]
Woa! I just typed this is an "problem" post but then it spontaneously started working while I was typing so I guess I'll still post it since it might be helpful for you guys to know.  (And I guess it's an "issue" when something spontaneously starts working and developers don't know why...) 

Here (was) my post would have been:

----------------------------------------------------------------
Hello, I'm running 1.8.00 on:
Java 1.8.0_191 (64 bit)
  Oracle Corporation
/usr/lib/jvm/java-8-openjdk-amd64/jre
SWT v4922, gtk/3.22.30, zoom=100, dpi=94
Linux v4.15.0-45-generic, amd64 (64 bit)
B1.8.0.0/4 az3

Running on Ubuntu 18.04.2, standard Gnome that comes with it by default. 

So; pretty vanilla and up-to-date environment, right.

Everything was working fine and then suddenly no torrents are downloading at all.  It was dwindling down to B/s and then all torrents stopped entirely.  (In the footer I was seeing  a measly 15 B/s now and then up or down.)

So I restarted biglybt a few times.  And then restarted ubuntu entirely, which not surprisingly didn't help. 

I only had 4 torrents started and fyi I'm port randomizing from 40000-50000 and I checked the router to see if it hadn't like spontaneously restarted and forgot, and and I ran ifconfig and checked that it didn't assign my workstations a new ip (which would make the port forwarding meaningless). Nope. All good.  

And yes, all other internet stuff works fine; same speeds.  (about 10 mb/s) 

---------------------------------------------

So the above was what I was about to post and then, spontaneously it started working.  One thing that might have changed is that I deleted all the (non) active torrents on the list and just tried one by itself.  But that was like an hour+ ago.

Anyway there it is. If you want logs lemme know, I'm a developer too (hence I'm running ubuntu), so it's the least I can do! 

It's important to point out that all of my other internet activity was totally unaffected- so if you're thinking the problem is local to my isp having an outage or something; no, that wouldn't make sense.

**Comment by parg** [comment]
Odd one that - if it happens again take a look at the 'all peers' view (Tools menu) to see if you have any active connections or whether they've all dropped out. Not that that would provide an explanation in itself...

**Comment by mkrier** [comment]
Will do, glad to help.  ( Btw if I switch back to java I might become a contributor. )  

thanks
