### ISSUE TITLE
It would be great to be able to toggle networks based on tags 

### ISSUE THREAD

**Issue by mppdidi** [BiglySoftware/BiglyBT#90]
It would be great to be able to toggle networks based on tags !

**Comment by parg** [comment]
You can do it via a script using the 'execute on assign' tag feature (right-click on the tag in sidebar to set this)

For example

javascript( var ta = pi.getTorrentManager().getAttribute( com.biglybt.pif.torrent.TorrentAttribute.TA_NETWORKS); var StringArray = Java.type("java.lang.String[]");	var nets = new StringArray(1); nets[0] = 	com.biglybt.core.util.AENetworkClassifier.AT_I2P; download.setListAttribute( ta, nets ))

sets assigned downloads to just be the I2P network.

Has to be a single line of script if you enter it directly.

**Comment by mppdidi** [comment]
that sounds great - can trackers also be added with javascript ?

**Comment by parg** [comment]
trackers can be added more simply by using 'tracker templates' - https://github.com/BiglySoftware/BiglyBT/wiki/Tags#Tracker_Templates

**Comment by mppdidi** [comment]
Yes i know - but in the stage of metadata download there is no option for this except scripts.
Thanx for the support !

**Comment by parg** [comment]
ah, metadata download... that's a quantum download, exists and doesn't. You could add an &tr=<blah> argument to the magnet link ;)

**Comment by mppdidi** [comment]
so the javascript could at &tr= to the url in the metadata phase ?

**Comment by parg** [comment]
no :( I meant you could manually add it to the magnet before entering it in BiglyBT (obviously not a very good solution)

I can add a 'isMagnet()' method to the Tag Constraints language that would allow you to use Tracker Templates to do this, that work for you?

**Comment by parg** [comment]
it'll be in next beta

**Comment by mppdidi** [comment]
That would be fantastic - thanx for your excellent support !
Do you have a donation link for your project ?

**Comment by parg** [comment]
There's the Donation Help menu option but that won't work with I2P only of course - good point about links in an I2P only setup - many of them allow you to right-click and select the URL which you can then manually paste into a TorBrowser (for example) - if you have the TorBrowser plugin installed then that's one way of getting that.

You can donate btc at 1BiGLYBT38ttJhvZkjGc5mCw5uKoRHcUmr - thanks :)

**Comment by mppdidi** [comment]
The isMeta works like a charm !
Thumbs up - hands down :-)

**Comment by parg** [comment]
excellento!
