### ISSUE TITLE
global sequential downloading or extension based

### ISSUE THREAD

**Issue by moham96** [BiglySoftware/BiglyBT#900]
Hi,
Is it possible to set a global sequential download (i.e all the added torrent will have the sequential download turned on) ?
I know I can set the sequential option for each individual torrent but I want all torrent to be downloaded sequentially.
This is useful if all my downloads are videos.
Another way to implement this is to have a setting in the options to set the sequential property based on file extension( so for example i can add 'mp4 mkv' to the list and biglybt will enable sequential for them automatically.

Regards

**Comment by parg** [comment]
I'll look into your suggesting for extension based auto-sequential, check the next beta (it'll be B25 once built)

**Comment by moham96** [comment]
@parg How can someone know if the sequential download has been enabled for the file successfully ?
would be nice to have some information in the general tab of the selected torrent something like 
auto-sequential:       yes
download in order:     yes

Regards

**Comment by parg** [comment]
you can tell the same way as before ;) go to the piece-map and look for pieces being downloaded in order. Or go to the pieces view and look for pieces that have a priority >= 100000.

That being said, I just spotted a bug that break things - I'll fix in next beta. I'll also add some more info to the header section in the piece-map header, something like

Seq=<n>+   - meaning sequential ascending from piece <n>

You would then be able to hover over piece <n> to see what file it was part of

**Comment by moham96** [comment]
> you can tell the same way as before ;) go to the piece-map and look for pieces being downloaded in order.

This requires the file to be downloaded to see whether a setting is enabled or not, I don't start my torrents immediately, I just add them in paused state and they are scheduled to start downloading at night.
>Or go to the pieces view and look for pieces that have a priority >= 100000.
> 
> That being said, I just spotted a bug that break things - I'll fix in next beta. I'll also add some more info to the header section in the piece-map header, something like
> 
> Seq=+ - meaning sequential ascending from piece
> 
> You would then be able to hover over piece to see what file it was part of

I just figured how to check whether the sequential downloading is enabled which is by simply right clicking on the torrent, but I see that the "Sequential Download" is not checked so things are not working.
Looking forward for your fix since it doesn't work as of now.

Just curious how does sequential downloading works technically ? I  can think of two ways to achieve this:
1- where piece 2 is not downloaded unless piece 1 is downloaded, which is really bad.
2- pieces are assigned descending priority so piece one has the highest priority and the last piece has the lowest priority, similar to how it was implemented in http://patraulea.com/azureus-ordered-download.patch/.

I suspect it's the second method but I wanted to make sure.
also how does sequential downloading play with Options->Transfer->Prioritize first and last piece of file(s)? does biglybt prioritize the first and last pieces the highest priority and then the pieces in-between takes a descending priority ?
If you could provide technical details I would appreciate it.

Reagrds

**Comment by parg** [comment]
The new option is file suffix based - it doesn't set sequential for the entire download (as the right-click on a download does) but only for the files that match the extensions

Technically it works by adding priorities to pieces, that's all - the piece picker then allocates requests based on priorities - as in (2)

As for how it plays with other things, priorities are accumulated.

See https://github.com/BiglySoftware/BiglyBT/blob/master/core/src/com/biglybt/core/peermanager/piecepicker/impl/PiecePickerImpl.java

**Comment by ForbiddenEra** [comment]
Thanks for this feature.
