### ISSUE TITLE
Can you watch movies/series while you download them? if not, how do you enable this?

### ISSUE THREAD

**Issue by melnation-com** [BiglySoftware/BiglyBT#902]
I heard in some torrent clients you can watch the movie/series while you torrent them, it does this by downloading the earliest pieces first so you can watch while it downloads.

**Comment by res1492** [comment]
Hello
if you right click on the Movie or episode you can tick "sequential Download"...this makes it so the file is downloaded from the start to the finish, if you give it like 20 seconds after ticking the option go find the movie file and double click to start watching as normal...if you have a fast enough connection the movie will play and finish downloading as you watch it...this works for me using VLC ... I sometimes run into problems with .avi files but tell VLC to "play without rebuilding the index"

**Comment by parg** [comment]
Or right-click on the file in BiglyBT and select 'copy stream URI to clipboard' and then paste that into VLC. Or use the 'embedded media player'

**Comment by crzsotona** [comment]
Right-click on torrent to open context menu, select Content->Media Server->Play Locally

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
using embedded media player is best practice
