### ISSUE TITLE
Empty swarm discoveries list.

### ISSUE THREAD

**Issue by Achaean** [BiglySoftware/BiglyBT#904]
Java 1.8.0_181 (64 bit)
  Oracle Corporation
/usr/lib/jvm/java-8-openjdk-amd64/jre

SWT v4922, gtk/3.22.11, zoom=100, dpi=96
Linux v4.9.0-8-amd64, amd64 (64 bit)
B1.8.0.0/4 az3 on Devuan ASCII (stable) x64 KDE (based on Debian stable).

Swarm discoveries list remains empty, after several days.

**Comment by parg** [comment]
Maybe you need to select more 'sources' - Tools->Options->Plugins->Swarm Discoveries: Choose Tracker Sources

**Comment by Achaean** [comment]
OK! I added manually, a bunch of trackers.
After a day or so, list is still empty.

**Comment by parg** [comment]
You could try using * to see if it is working at all - I assume you have added a few downloads to BiglyBT in order for swarm discoveries to try and find related content.

You could also experiment by searching for 'linux' (right-click the swarm discoveries entry in the sidebar and select 'discover by search')

**Comment by Achaean** [comment]
Indeed, this way works.
