### ISSUE TITLE
Peers tab not autorefreshes.

### ISSUE THREAD

**Issue by Achaean** [BiglySoftware/BiglyBT#905]
Java 1.8.0_181 (64 bit)
  Oracle Corporation
/usr/lib/jvm/java-8-openjdk-amd64/jre

SWT v4922, gtk/3.22.11, zoom=100, dpi=96
Linux v4.9.0-8-amd64, amd64 (64 bit)
B1.8.0.0/4 az3 on Devuan ASCII (stable) x64 KDE (based on Debian stable).

At Library, when selecting a torrent, the Peers tab, don't automatically start displaying data (the connected peers).
Clicking at another tab (eg. General) at clicking back at Peers one, solves the problem.

**Comment by parg** [comment]
try the latest beta

**Comment by Achaean** [comment]
I did it.
Indeed it's an improvement.
Still happens, but rarely.
