### ISSUE TITLE
Build jar file

### ISSUE THREAD

**Issue by mppdidi** [BiglySoftware/BiglyBT#91]
In order to have the latest build from the github repo - is it enough to rebuild the BiglyBT.jar for an update ?
I am not sure on how to build the windows client from the repo - maybe you could provide a short checklist ?

Cheers

**Comment by mppdidi** [comment]
Maybe as an alternative you could seed the signed update from the beta to open i2p trackers - that would make it easier to have the latest stuff with an i2p only client ?

**Comment by mppdidi** [comment]
On a second thought maybe this would be a good idea to announce all the bbt plugin updates on an open i2p tracker ?

**Comment by parg** [comment]
If you have selected 'anonymous updates' then the download process inserts a tracker I run into the download (jcgok7sfv2ycwdluzjr6s5bdca4ps6beaogilp72dzl6mopp46ya.b32.i2p:6968) - however I currently don't auto-seed things ;(

**Comment by mppdidi** [comment]
Where can I find the 'anonymous updates' ?

**Comment by mppdidi** [comment]
Okay found it .
On the tracker issue - you could add one the well known open i2p trackers - that should solve the problem and the BBT nodes would keep seeding them I think.

**Comment by mppdidi** [comment]
Anonymous update is not working in a mixed mode scenario due to the fact the BBT updates are in the temp directory - it would be a great boost to have beta updates published to an anon tracker also.

**Comment by parg** [comment]
Next beta update should have an I2P tracker (mine) - if you think it would be good to add another open one then post here or email me your selection :) paul@biglybt.com

**Comment by mppdidi** [comment]
tracker.thebland.i2p is a good one

http://s5ikrdyjwbcgxmqetxb3nyheizftms7euacuub2hic7defkh3xhq.b32.i2p/a

Thank you so much - BBT is the goto bt-client !!!

**Comment by mppdidi** [comment]
Allthough quite slow - update it is working now anoymously !

:-)
