### ISSUE TITLE
Peer Tab: Show percentage of file the peer has but you don't?

### ISSUE THREAD

**Issue by david-bakin** [BiglySoftware/BiglyBT#910]
Is there a way, on the Peers Tab, to display the percentage of a file the peer has that you don't?  You can get the peer's percentages - and the visualization of which pieces the peer has - but I can't find an item for the amount of stuff you're missing that the peer can offer you.

**Comment by parg** [comment]
You need to show the detailed view (right-click on the download and select 'show details')

Then select the Peers tab and look at the bottom for a Files sub-tab
