### ISSUE TITLE
Direct Buffer errors with 1977MB of cashe

### ISSUE THREAD

**Issue by t999uk** [BiglySoftware/BiglyBT#913]
when downloading torrents i randomly get Direct Buffer errors seems to occur more with torrents in the size of around 50+GB i currently have 2GB of memory assign via command line after getting prompted of increasing it to 512mb and a cache value of 1977MB 

* OS and version windows 10 Build 1809
* BiglyBT Version Number 1.8.0.0 
* For *nix: Desktop Environment

System Spec if needed:
cpu: AMD Rysen 7 1800X
Ram: 16GB DDR4 kingston
HDD: 2TB HDD
GPU: GTX1070

**Comment by parg** [comment]
See that comment 'more that 32mb cache is probably overkill' ? There really is no point in setting a huge cache size within BiglyBT, try lowering it and see if the errors go away.

**Comment by t999uk** [comment]
ok, 32mb seems to have cleared it up for now so I guess the old adage "less is more" is true in this case. it only ended up at 2GB cache due to the Direct Buffer errors every time it happened I increased the cache and when the program told me to increase java memory I did
