### ISSUE TITLE
User Interface: toggling check boxes

### ISSUE THREAD

**Issue by doctechnical** [BiglySoftware/BiglyBT#915]
When selecting which files to download from a torrent of many files the only way to check or uncheck the checkbox is by clicking it. It would be much faster and easier to use if there were a keyboard shortcut (such as the space bar) that would do this toggle so you could use _only_ the keyboard instead of click-scroll-click-scroll-scroll-click. This is the way pretty much _every_ scrolling list of checkbox items works in Windows.

OS: Windows v7
BiglyBT: v1.8.0.0

**Comment by TuxPaper** [comment]
Not as fast as keyboard, but you can select the ones you (don't) want, and right click.  So, maybe 3 clicks vs one keyboard press.

**Comment by doctechnical** [comment]
Yes, that works, but it's clumsy as all get-out.
