### ISSUE TITLE
[Feature Request]: Prioritize downloads by ETA

### ISSUE THREAD

**Issue by MartiniGM** [BiglySoftware/BiglyBT#918]
Hi,
I see you've added a couple of new sorting methods for download prioritizing. Could it be possible to add a new sorting mechanism "Prioritize downloads by ETA". It would sort the downloading in the same way as if you sorted the active torrents by ETA. It would need some additional logic though, like the "Prioritize downloads by Speed". One way could be to start all or max + a number of downloads every X second, run them for X seconds and pick the once with lowest ETA.

The reason that I would like this feature is when you have a large number of torrents downloading and both the size of the torrents and the speed of the connected peers varies greatly it would be nice to just finish the lowest hanging fruits first (the torrents with lowest ETA) and neither the prioritize by seed count nor the prioritize by speed will make that possible.

**Comment by parg** [comment]
Next beta will have an ETA option.
Note that by default the testing of downloads for speed (rate/ETA) only occurs on ones in a queued state as the option is mainly about kicking potentially better downloads out of a queued state to replace the worse performing active one.

I added a further option that will result in already active ones also being tested (default = off)

**Comment by parg** [comment]
Beta 29 is out if you get a chance to play

**Comment by MartiniGM** [comment]
Yea! Do you know how often one of my suggestions has been fulfilled this fast? Or.. maybe it is because I have made a really, really good suggestion at a lucky time in an applications development? :)

Anyways - I AM using the new feature - and I like it! :)

**Comment by parg** [comment]
Bit of everything :)

**Comment by as-muncher** [comment]
Was this option removed?  I remember seeing an option to prioritise downloads according to pieces remaining, but I can't seem to find it now.  And wow, I noticed all the ways that the queue can be prioritised - right on!!  Thanks for making BiglyBT so feature-rich.

**Comment by parg** [comment]
Features are never removed from BIglyBT, that's why it is so full of crap.

There's never been an option to prioritize by amount remaining although that could be added easily I'd imagine.
