### ISSUE TITLE
Any reports (besides me) of BiglyBT recently messing up internet connection completely?

### ISSUE THREAD

**Issue by david-bakin** [BiglySoftware/BiglyBT#919]
This is a wierd one ... but I haven't changed anything in my networking setup except upgrading BiglyBT beta versions ...and for the last 3 or 4 days:

Running BiglyBT on my server kills my internet connection.  Haven't been able to pin it down the exact bad behavior - its the cable modem, but I have tried it in various configurations w.r.t. my separate router.  The cable modem itself "appears" to work.  I.e., the lights on the front don't change, and Comcast, remotely, says it is working.

But: no DNS gets resolved, and I can't ping remote sites with explicit IP addresses either.

I first noticed this with the following network connection with the _server only_ running BiglyBT:

```
server------\
             google wifi ------ cable modem --- the world
laptop------/
```

After starting BiglyBT _and starting transfers_ both server and laptop would fail DNS, fail to ping, etc.

Changing to the following configuration

```
server--------------------------\
             google wifi ------ cable modem --- the world
laptop------/
```

For awhile: the server internet would stop (same thing, no DNS, no ping) while BiglyBT was running, and start again when BiglyBT exited; meanwhile the laptop would be running fine (with continuous pinging to a named remote server).

So it is almost like the server running BiglyBT kills only the one port on the cable modem it is connected to, not others.

So ... I'm about to call Comcast and complain ... but have you or anyone heard of this happening?  Or can you think of some change in BiglyBT recently that could cause this (though I can't imagine what it would be).

[Always running the latest beta offering, on Windows Server 2016.]

**Comment by hatewesterncivilization** [comment]
It is not something provocatively by someone in global baseness against Bigly? I'm myself just experienced one big issue described in the neighborhood here. Had moving to Tixati.

**Comment by parg** [comment]
Nothing has changed in any recent (or indeed not-so-recent) betas that should have an impact on network traffic. Are you running the I2P plugin? If so try disabling it to see if that improves things. Your symptoms are perhaps that of an overloaded cable-modem.

**Comment by david-bakin** [comment]
I2P is not on.  Well, I've characterized it further as follows:  All it takes is starting BiglyBT and the cable modem immediately stops making new connections - to DNS, to anything.  And BiglyBT isn't transferring anything.  (Except probably trying to log in to DHT.)  When I exit BiglyBT connection start getting made again almost immediately, even before the main UI window vanishes.

So it could be the initiation of DHT, or it could be PNP negotiation or firewall negotiation.

I'm sure what happened is that Comcast pushed a new configuration or firmware or something to the cable modem and broke something badly.  I was just checking with you to eliminate a variable.

**Comment by afberendsen** [comment]
I am having exactly the same problem but I am in Germany. Have you fixed this issue?

**Comment by parg** [comment]
If running BiglyBT causes general internet issues then it is likely that your router can't handle the amount of network traffic that is being generated. Consider

1) making sure your maximum download speed is set to <= 80% of your ISP's max rate 
2) ensuring that you haven't installed the I2P plugin 
3) disabling the DHT (Tools->Options->Plugins->Distributed Database)

**Comment by afberendsen** [comment]
The thing is that it was working until last Thursday...and now, from nowhere, this problem start to happen. I will try your suggestions and let's see what happens. Thanks

**Comment by JamesOlvertone** [comment]
Same here. Reducing connections, transferrates doesnt matter. This behaviour even appears when all seeding/donwloading is stopped. I have to restart my router (disconnect from power, soft restart doesn't work) then its gone until it happens again.
