### ISSUE TITLE
Extra width of Seeds or Peers columns in Library

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#921]
I happened to be on an especially popular torrent recently, which caused the Seeds column to overflow the space I'd allocated for it in the Library. While I was widening it, I noticed that both Seeds and Peers force some whitespace to the left of their contents that can't be removed — if you narrow the column, the contents will ellipsize instead of moving into that blank space.

Specifically, this is how my Seeds column originally appeared, along with the Peers column next to it:
![Screenshot from 2019-02-24 07-24-54](https://user-images.githubusercontent.com/538020/54086120-74d87980-431c-11e9-9d75-975354c196aa.png)

And this is the narrowest I could make either of them without the contents ellipsizing:
![Screenshot from 2019-02-24 07-25-13](https://user-images.githubusercontent.com/538020/54086127-95083880-431c-11e9-8ae5-1e10202442be.png)

This was in the upper half of the Library view, but the same is true for the Seeds/Peers columns in the lower half:
![Screenshot from 2019-02-24 07-25-37](https://user-images.githubusercontent.com/538020/54086131-bb2dd880-431c-11e9-8228-e154fa40479b.png) ![Screenshot from 2019-02-24 07-25-23](https://user-images.githubusercontent.com/538020/54086134-bec15f80-431c-11e9-881a-41d906bcfcc2.png)

Compare that to other columns, like Size or Done, which can be narrowed so that the contents occupy all of their width:
![Screenshot from 2019-02-24 07-27-02](https://user-images.githubusercontent.com/538020/54086143-def11e80-431c-11e9-8548-65793c003168.png)

One thing I do note is that the Seeds and Peers columns have a "Show Network Icons" option. I normally leave that turned _off_, since I don't use any network except the public internet. But if I switch it _on_, the width of the column's contents doesn't change. Perhaps the whitespace to the left of the data is the space for network icons, which is being reserved even when those icons are disabled?

Anyway, it'd be nice to be able to narrow the Seeds/Peers columns to the width of their content, like the other columns in the Library view(s).

### System block
```
Java 1.8.0_201 (64 bit)
  Oracle Corporation
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.201.b09-2.fc29.x86_64/jre

SWT v4922, gtk/3.24.1, zoom=100, dpi=96
Linux v4.20.13-200.fc29.x86_64, amd64 (64 bit)
B1.8.0.1_B28/4 az3
```

**Comment by parg** [comment]
The space is reserved in case you enable the network icons so things line up. I've changed it so that if you disable network icons (and restart) then the space won't be reserved.

**Comment by ferdnyc** [comment]
And indeed, after an update to 1.8.0.1_B29 (and restart):

![image](https://user-images.githubusercontent.com/538020/54203588-e8a78d00-44a8-11e9-8aaa-f57bb12cd453.png)

Sweet! Thanks.
