### ISSUE TITLE
Feature Request: Options to rename

### ISSUE THREAD

**Issue by ms52538** [BiglySoftware/BiglyBT#922]
Would like to have the option to rename (single or in bulk) a file based upon either:

the pre-existing Torrent name
the altered or pre-existing Torrent File Save Path Name
the altered or pre-existing File name contained within Torrent (if different from Torrent or Torrent File Save Path Name)

Example:
Torrent File Name:   aa41124
Torrent File Save Path Name for aa41124:  Drive Letter/Some Folder/Comedy - Joe's Pizza
Included individual files within Torrent:   1) Joe's Pizza (2014).mp4 Joe's Pizza, 2) The Return of Pepperoni (2016).mp4

So I recently restored a bunch of torrent files from a library into the program, and then searched for and created links to those files on my hard drive. The problem is that the torrent names do not match either the Save Path file name or file names contained within the torrent itself (if there are multiples).

I like to have the names all universally match at the Torrent File, and Save File Path File Name levels. But to go through my collection and having to change each name manually is a long road to take. If it can be automated some way would be fantastic. We sort of have that ability now where we can perform a rename function (by selecting which check boxes to include in the task: i.e. Torrent Name, Save File Path Name, etc.) but we can only facilitate that one torrent at a time. And it does not give an option to select from an existing File Name from within the Torrent (if there are multiple files contained within it).

Probably not an easy task accomplish - and maybe not practical either - but it's a situation I face so I thought I'd raise it up as a suggested feature. If there is already a means to facilitate this that I am unaware of please let me know! It's not always easy discovering all the newly added features going into the program.

Thanks, as always!

**Comment by parg** [comment]
The only batch-level rename functional currently available is at the file level - select multiple files (optionally from multiple downloads) in the FilesView window and select the batch retarget/rename menu item.

Not that it helps you but just for info.

**Comment by ms52538** [comment]
> The only batch-level rename functional currently available is at the file level - select multiple files (optionally from multiple downloads) in the FilesView window and select the batch retarget/rename menu item.
> 
> Not that it helps you but just for info.

Roger that - thought I'd at least ask. :)  Thank you.

**Comment by parg** [comment]
If you could sketch out a batch kind of solution I might get a chance to look at it - some kind of similar approach to the batch file rename where an intermediate text based view is generated that you can fiddle with to achieve the desired results? I gravitate to something like that rather than a complex UI because I hate writing UIs :)

**Comment by ms52538** [comment]
> If you could sketch out a batch kind of solution I might get a chance to look at it - some kind of similar approach to the batch file rename where an intermediate text based view is generated that you can fiddle with to achieve the desired results? I gravitate to something like that rather than a complex UI because I hate writing UIs :)

I'd be happy to, give me a day or two if you would.  - Thanks for the consideration. It's appreciated. I know there are priorities, niceties, capabilities, etc...

**Comment by ms52538** [comment]
> If you could sketch out a batch kind of solution I might get a chance to look at it - some kind of similar approach to the batch file rename where an intermediate text-based view is generated that you can fiddle with to achieve the desired results? I gravitate to something like that rather than a complex UI because I hate writing UIs :)

I took a shot at it, hope this is enough if not, please let me know and I'll attempt to further illustrate. Trying to keep communications of the idea as clean/simple as possible, but not always easy when it's a non-coder presently the ideas and vision. lol  :)

At Present, the function for renaming (@ Torrent Level):

Right-click a torrent in the program, a pop-up box appears, select ORGANIZE: 

A. RENAME... 

A1. RENAME | "Rename Download" | Manually enter text into [text field]

Options include:

x Rename Displayed Name 
x Rename Save Path 
x Rename Torrent



ISSUE: The present rename function is limited to renaming the torrent based upon the text that is manually entered into the dialog box [Enter New Name for Download].


PROPOSAL: Provide additional functionality to the rename function at the torrent level, to provide functions that automate the rename BASED UPON any of the following:

B Existing Displayed Name
C Existing Save Path Name
D Existing Torrent Name
 

VISION: Instead of just having the "RENAME..." line item, add the following lines underneath it to the ORGANIZE Pop-up Box:

A. RENAME manually... (leave as is)
B. RENAME from Displayed Name... (ADD) [Note: pulls from the existing Displayed Name] 
C. RENAME from Save Path Name... (ADD) [Note: pulls from the existing Save Path Name (not including path)] 
D. RENAME from Torrent Name... (ADD) [Note: pulls from the existing Torrent Name]

....... These are to be added:

B1. RENAME from Displayed Name...
Options include:
x Rename Save Path
x Rename Torrent

C1. RENAME from Save Path Name...
Options include:
x Rename Displayed Name
x Rename Torrent

D1. RENAME from Torrent Name...
Options include:
x Rename Display Name
x Rename Save Path


For the new items B1-D1; you can either have a similar Text Box field (as you do for the Rename... (manually) feature and auto-populate it so the user can see the auto-populated text, and have it appear in the rename pop-box supporting each, or you can opt not to include the auto-populated text field. I think it would be nice if it could be added (the same size as the present one you use for the manually A. RENAME manually feature presently in use).

All of this listed above, thus far, is a ONE-TO-ONE rename facilitation (renaming manually 1 torrent at a time). At presently, if you are to select multiple single file Torrents (say a group of 5 out of a library of 10 torrents), and attempt to rename them manually using (A) from above, multiple boxes appear stacked on top each other as you complete one the next torrent out of the 5 appear). You could extend the proposed VISION to have that same functionality (thinking that is the easiest means to implement with the least amount of coding). But if you can think of a way apply the proposed functionality from the VISION, and apply it in batch form to multiple torrents simultaneously, that would be even more fantastic (i.e. as above, select 5 ouf 10 torrents, perform a single C1. RENAME from Save Path Name... function and all 5 torrents are renamed all together at one time.

In regards to the Rename functionality at the file level, within the torrent - I'd leave that as it is, honestly, now that I've looked at this - you have more than enough features there to help it.

Thanks for your consideration of this. I've tried to keep this simple in a way that conveys the VISION, but you may have other ideas once seeing this, based upon your experience with code and knowing the capabilities/limitations of which, that I cannot. Hopefully, this will help.

**Comment by parg** [comment]
I fiddled with the dialog a bit in B30 - it now shows the display-name/save-path/torrent-file and has buttons to copy them into the text area. Tell me what you think!

**Comment by ms52538** [comment]
I'm loving it! And nice way to consolidate it and keep it simple. :)  Thank you! Hope others like the new capabilities as well.

**Comment by ms52538** [comment]
I just have to tell you - I'm LOVING this new capability. It's really coming in handy. :)  So again, thank you and great work!

**Comment by parg** [comment]
no problem, thanks for the suggestion!
