### ISSUE TITLE
Feature Request: Global Search of All Files Function

### ISSUE THREAD

**Issue by ms52538** [BiglySoftware/BiglyBT#923]
Would like to have a single function that allows a search of all files globally throughout the library (included files contained within the torrents).

If that's not readily easy to code, then perhaps a 'select all' feature in the library which highlights all torrents, so that I can then use the file search feature at the bottom of the page. This would be a bit easier than having to manually highlight and select all torrents first, which when you have over 1,000 torrents in a library is a tad cumbersome.

As always ... THANKS Much! :)

**Comment by parg** [comment]
You can already do that with ctrl+a (or click the first one, scroll to the last and shift+click that).

To handle both incomplete and complete downloads you can switch to the 'simple list view' (toolbar button) that shows both types of download in a single view.
