### ISSUE TITLE
Feature Request: Stay in background when adding torrents

### ISSUE THREAD

**Issue by doctechnical** [BiglySoftware/BiglyBT#928]
It's annoying when d/l multiple torrents / magnet links from a site to have the app keep popping over the browser ever time one is added. It would be nice if, like other torrent clients, there were an option for the program to stay minimized or in the background while torrents were added.

**Comment by parg** [comment]
Check out Tools->Options->Interface->Display:

Suppress File Download popup dialog

and

Tools->Options->Interface->Alerts:

Show the main window when a download is added by another application
Reduce situations where the main window is automatically shown

**Comment by doctechnical** [comment]
YES! Thank you, I didn't know about that second one. That took care of it!
