### ISSUE TITLE
Swarm discovery with pure i2p

### ISSUE THREAD

**Issue by mppdidi** [BiglySoftware/BiglyBT#93]
Can you elaborate a bit on the swarm discovery - with an I2P only setup it is not discovering anything on it's own ?

**Comment by parg** [comment]
I believe it should work in such a setup with I2P only downloads - however there may not be that many people running I2P only and therefore you might not get any results. You could always try the 'discover by search/popularity' right-click menu options on the swarm discoveries sidebar entry - if you prefix the expression with 'I2P:' then this forces the swarm discoveries operations themselves to run over I2P. HOWEVER, the results themselves will be clearnet and (potentially) I2P together, there is currently no way to prevent that.

**Comment by mppdidi** [comment]
Thank you.

**Comment by mppdidi** [comment]
Would it be possible to activate the swarm discover by default for i2p ?
Afaikt i need to manually setup the search expression after a restart of BBT.

**Comment by parg** [comment]
See https://github.com/BiglySoftware/BiglyBT/issues/97
