### ISSUE TITLE
Not Responding (advanced)

### ISSUE THREAD

**Issue by mattish91** [BiglySoftware/BiglyBT#931]
* Windows 10 PRO 17763.379
* BiglyBT Version Number not sure (latest stable*)

Everytime i start it simply freezes and is not responding, this issue comes after a power outage, i have tried deleting all files in appdata/roaming/BiglyBT with no result, after a new torrent added the same result. Also tried vuze's safemode with same result. (i made a backup of all files in appdata/roaming/BiglyBT) just in case it wasn't the issue, i tried reinstalling biglybt from scratch, same result. Any suggestion is helpful, also if i can provide any kind of logs i will. Thanks!

https://imgur.com/BrhmdQA

[EDIT]
Kind of got it working, imported all relevant files from the torrents folder, now i got some files working and some not.

**Comment by parg** [comment]
Hmm, can you try joining the beta program - see the Help menu for options. See if the latest beta version helps

**Comment by mattish91** [comment]
Yea, i did, thats how i partially got it working now, i can't get any magnets to load in without having to reset the entire data directory, pretty bad, i know. not sure what causes the issue either.

**Comment by mattish91** [comment]
After an update, this issue is now back again -.- (latest beta)
