### ISSUE TITLE
Add ability to whitelist IP ranges in IP block list

### ISSUE THREAD

**Issue by PrototypeZero** [BiglySoftware/BiglyBT#933]
I use an ISP which is mistakenly often listed in block lists because of outdated information.  

The IP range is a huge /8 subnet (51.x.x.x) which is often mistakenly attributed to "UK Government Department of Work and Pensions".  Unfortunately this information has not been the correct for a _**very, very**_ long time and the said subnet is now split between mainly British Telecom and a number of other telecom/ISP companies which use BT's infrastructure here in the UK.

How does this affect BiglyBT?  Their own direct residential and business customers sometimes getting IP address assigned to the said /8 IP range (myself included), that's how.

Ok, you say remove it from the list, fine but.. as the IP block list in BiglyBT is constantly refreshed every time it does it adds this range back to the blocking list even if you removed it

So unless you check if its been updated fairly often (and manually remove incorrect entries), you will find yourself blocking (and being blocked by) possible valuable peers.

So why not add a manual whitelist of IP ranges the user can edit, with ranges that are never blocked even if in a block list?  This will help more than myself I'm sure and allow people to use block list if they want to.

**Comment by parg** [comment]
Given that the block list is so out of date, why even use it? 

Maybe you could add the desired range as a LAN subnet, they aren't blocked.

Tools->Options->Plugins->LAN Peer Finder

You might want to disable separate speed limits for LAN peers (under Transport->LAN) if you do this.

**Comment by PrototypeZero** [comment]
OK, I can see your point.  

I know most blacklists are next to useless and contain multiple holes/blacklisted IPs and other mistakes but doing it the LAN peer way would be a good compromise.

I never thought about using LAN peer option to achieve the same result as AFAIK I see no mention of it anywhere in the program.  Maybe making the point about LAN subnets not being blocked in the LAN peer options could clear this up.

Thanks
