### ISSUE TITLE
[Bug] Friends plugin re-enables itself every 30 seconds

### ISSUE THREAD

**Issue by PrototypeZero** [BiglySoftware/BiglyBT#934]
Using BiglyBT 1.8.0.1_B32 on Windows 10.

If the friends plugin (azbuddy) is loaded (not if its disabled from starting) any attempt to disable it will be in vain as regular as clockwork it will re-enable itself every 30 seconds (not from when you disable it but I'm guessing from when it 1st started).

As I find it (the Friends plugin) of little use myself I just stop it from loading, but I usually prefer to have most plugins loaded so I can experiment with settings.  Hopefully you can fix it.

**Comment by parg** [comment]
Next beta will only auto-enable once so you will see that but no more after you disable it.
