### ISSUE TITLE
Simultaneous downloads and limits

### ISSUE THREAD

**Issue by eurobank** [BiglySoftware/BiglyBT#943]
I'm using the following settings:

Simultaneous downloads 2
Max active torrents 3
Don't count downloads below 192 kbps
Don't count uploads below 5 kbps
Prioritize downloads Order

But as you see from the capture below, all torrents have started.  I have tried to limit them to max 2 downloads, still no luck. 

I don't understand the logic probably. 

Thanks

![2019-03-20 12_15_39-BiglyBT](https://user-images.githubusercontent.com/4467158/54676846-4a4fa300-4b0a-11e9-8309-7ea7a738f9c3.png)

(Windows 10 pro 64bit and latest beta of Biglybt)

**Comment by parg** [comment]
don't count downloads below 192 kbps?

**Comment by eurobank** [comment]
@parg I understand what you say, BUT when i manually STOP the torrents and leave only the 1st in order or the second, the download is maxed out (reaching my limit of adsl line). So the 1 torrent HAS the speed potential. Why the 2nd is started and at the end all of them ? A third torrent should start only if the 1st and 2nd are below 192kbps, right ?

Doesn't seem right to me.

**Comment by eurobank** [comment]
Also changing the max simutanous downloads from 2 to 1, seems to work right.

See for the same torrents/queue, with a max of 1:

![2019-03-20 12_42_46-BiglyBT](https://user-images.githubusercontent.com/4467158/54678440-d1524a80-4b0d-11e9-818b-18e579107694.png)

**Comment by parg** [comment]
Have you played with the download prioritization under Queue->Downloading?

Also, have you changed Transfer: User request throttling/focus download speed settings from their default of enabled?

**Comment by eurobank** [comment]
The Queue->Downloading is Order

The Transfer yes, i have changed several things:

![2019-03-20 12_54_08-Options](https://user-images.githubusercontent.com/4467158/54679162-48d4a980-4b0f-11e9-894c-c550ac691389.png)

**Comment by parg** [comment]
revert the 'focus download speed' setting to enabled

**Comment by eurobank** [comment]
This seems to do the trick, but all the "speed" is given to the 1st in order. Still that way works much-much better.

Thank you.

**Comment by eurobank** [comment]
I spoke too soon. It seems that after a few hours everything is gone crazy.

![2019-03-20 20_09_12-BiglyBT](https://user-images.githubusercontent.com/4467158/54708518-3b89e000-4b4c-11e9-8436-87312f571c18.png)

**Comment by parg** [comment]
Probably because you have a ridiculously high setting for 'ignore downloads with speed lower than'

**Comment by eurobank** [comment]
192kbps is not high. Anyway, this seems to come and go.

**Comment by parg** [comment]
192kbps is high because download speeds fluctuate and, if you get to a point where some of your active downloads drop below 192k then another download will be started (not sure if they subsequently get stopped). Gradually more and more will get started and make it more and more likely that others will drop below 192. The setting is supposed to catch 'stalled' downloads, so if you set it high you are likely to suffer these consequences.
