### ISSUE TITLE
FEATURE REQUEST:  Text/URL field in order to link back to a URL web page

### ISSUE THREAD

**Issue by ms52538** [BiglySoftware/BiglyBT#944]
Pretty simple on this one; trying to use the Comment field with a limitation of 150 characters (which is probably a limitation, not sure), and attempting to populate and save a URL address into the field - only to realize I can't do that for that specific function.

So, would be 'nice to have' a field/box in which the user of the client can paste or type into the field a URL address. For my specific use, I'm looking to do this to associate back to a private-torrent-site web page which is associated to the torrent (but is not referenced IN the torrent itself). This would allow users to click back to the Site/Page in which they downloaded the torrent from initially, or for other uses in general. Considering URL addresses can be rather long, not sure if there is a means to use the Comment field beyond the 150 character limitation, but if there is I still cannot use the Comment field for my own personal use on a private torrent that I'm not sharing with the community. I don't share my torrents. LOL ;)  Thanks Captain!

**Comment by parg** [comment]
There are private comment fields that'll take longer strings - look for the column with the 'text icon'

![image](https://user-images.githubusercontent.com/395293/54780880-d3ea9800-4c12-11e9-8b20-4622fcae0423.png)

It is true that entering a URL doesn't make it clickable although that could be changed if it'd do the job?

**Comment by ms52538** [comment]
Alright - Groovy, found it! Couple of questions: How does this differ from the "Comment" field when I initially download a torrent and the pop-up window appears for me to make some selections before I confirm for it to actually start the download? There is a button there for Comment, but that seems to be related to a 'sharing and rating system'?  Ideally it would be available in that window, as that's the initial moment I'd have my browser open and pulling down the torrent - so I'd want to copy / paste there. But that's in a perfect world. So if it can be only where it is now on the main page/form then that works. Can you make the URL linkable? :)  I just try to make suggestions based on real use of the app, I work with it daily.

**Comment by parg** [comment]
It is already searchable in the library - prefix the search with c:  (see tooltip for search field, also supports regex)

**Comment by parg** [comment]
the initial pop-up window 'comment' thing is all about being able to search the public ratings/comments for the download - the intent is to allow you to check out the download before committing to adding it to your downloads. By the way, the initial torrent download link is automatically captured (where available) under right-click menu:

Control: Tracker/Torrent->Torrent Download Link

**Comment by parg** [comment]
next beta has a little comment icon in the open-torrent dialog and URL click in the comment dialog (detected URL is shown bottom left and clickable)

**Comment by ms52538** [comment]
That was fast! Thank you!! I look forward to trying it out once the beta hits the streets.  🥇

**Comment by parg** [comment]
B36 is out!

**Comment by ms52538** [comment]
B36 looking great thus far! Found the icon for the initial comment in the download pop-up box, nice! And the linkage to the URLs enter looks great as well!  Thank you again - that was fast work and turn around on the request!
