### ISSUE TITLE
Unable to transcode or play

### ISSUE THREAD

**Issue by itsme203** [BiglySoftware/BiglyBT#95]
I just downloaded BiglyBT over my Vuze. I can no longer transcode to iTunes or play directly from BiglyBT...any ideas or fixes?

**Comment by parg** [comment]
Are you getting any error messages when things fail?

**Comment by itsme203** [comment]
No error message

**Comment by parg** [comment]
Please give me a bit more information about what the problem is - why can't you play directly from BiglyBT for example? Is something missing in the interface? etc.

**Comment by mred49** [comment]
I'm having similar issue with XBox360.  When i try to Transcode to Xbox the download appears in the list for the device but the Device Name field is blank and there is no error message.
