### ISSUE TITLE
New Torrent Dialog View Composition Corruption

### ISSUE THREAD

**Issue by brazenvoid** [BiglySoftware/BiglyBT#954]
![Capture](https://user-images.githubusercontent.com/8722533/54837033-488f0680-4ce7-11e9-8a09-8e9551e0151b.JPG)

Noticed this issue today. I can consistently reproduce it. Steps to reproduce:
- Load a torrent with many files and folders 
- Open the tree view and uncheck some folders (Mine appeared on top of the dialog.)
- Close it
- Search files by a keyword in the new torrent dialog
- There must be at least some results, the more the better
- Now start unchecking the results one by one from top to bottom
- The partial view of the tree view will suddenly appear beneath the save location section. The section gets resized to accommodate it even!
- Sometimes it does not happen. So one can try checking them all again and then unchecking them to produce it.
- Checking/unchecking some other files will remove it again

* Windows 10 x64 1803
* BiglyBT B35

**Comment by parg** [comment]
Can't reproduce on Win7 or Win10 :( It would seem that the tree view somehow isn 't being disposed correctly and then somehow coming back to partial life - can't for the life of me think how....

**Comment by parg** [comment]
hmm that isn't a partial view of the tree, it seems to be a number of potential save locations an associated space

**Comment by brazenvoid** [comment]
No the paths are of folders contained inside the torrent or perhaps how will they be afterwards

**Comment by brazenvoid** [comment]
Though those are not from the treeview indeed. My mistake. They are something else...

**Comment by brazenvoid** [comment]
I am closing this as I haven't been able to reliably reproduce it.
