### ISSUE TITLE
Bulgarian messages have some encoding issues

### ISSUE THREAD

**Issue by lislei** [BiglySoftware/BiglyBT#958]
![bilde](https://user-images.githubusercontent.com/13136714/54866499-bc2b2500-4d74-11e9-9c6c-77475deafbcb.png)

In CrowdIn they apprear like this:
![bilde](https://user-images.githubusercontent.com/13136714/54866512-e8df3c80-4d74-11e9-8ab8-99e850b27d3a.png)

**Comment by lislei** [comment]
The actual contents of the property file is:
```
MainWindow.menu.file.export=&\u0415\u043A\u0441\u043F\u043E\u0440\u0442 \u043D\u0430 XML \u0442\u043E\u0440\u0435\u043D\u0442\u0085\u2026
```

The last two characters are looking strange to me.
`\u0085` represents that square symbol
`\u2026` represents the three trailing dots

**Comment by lislei** [comment]
The contet is from the initial commit into into the git repository so it must have been an issue back then.

**Comment by TuxPaper** [comment]
I haven't updated my source in a while, but here's what mine looks like:
![image](https://user-images.githubusercontent.com/725353/54869538-5d0ae780-4d57-11e9-83fd-accb5ca2354c.png)

Note IntelliJ thinks it's UTF-8, while your screenshot thinks it's ISO-8859-1

**Comment by TuxPaper** [comment]
Weird, my Crowd-in shows it ok too!  
![image](https://user-images.githubusercontent.com/725353/54869571-e02c3d80-4d57-11e9-96d1-b550107d006f.png)

I mean, "ok" as in it displays it.. having 6 dots of varying sizes isn't necessarily "ok" :P

**Comment by TuxPaper** [comment]
Interestingly, 0x0085 at https://www.fileformat.info/info/unicode/char/0085/index.htm
says it's a "Next Line" or "Paragraph Separator", which shows up as three dots for me.

0x2026 is definitely the right one

**Comment by TuxPaper** [comment]
I've done a replace of "…" with "…" in Crowdin and that should fix things up once Crowdin makes a pull request.

That an odd bug you found!

**Comment by lislei** [comment]
I will argue that the `\u2026` is a bug as well. It derives from the same encoding problem. Everywhere else then three trailing dots (...) are used in the translation files. In order of consistancy I'll vote for it to be raplaced as well:)

Having that said, I notice that many use that charcter (&hellip; in html) for shortening a paragraph of text.
There's even a tweak in BiglyBT spesific for mac that replaces three dots with `"\u2026"`.

I found this amount of usages in all properties files:
`"\u2026"` : 143 occurances whereof the sequence `"\u0085\u2026"` has 25 occurances.

The string "\u0085\n" has 8 occurances.

![bilde](https://user-images.githubusercontent.com/13136714/54871021-6c694f80-4dae-11e9-9ad0-647926fdad5f.png)

**Comment by lislei** [comment]
Regarding ISO-8859-1 and UTF-8.

Control characters are displayed on windows as a square symbol. I'm assuming you're on mac since it's different.
Encoding in this case doesn't matter as the text is UTF escaped.
![bilde](https://user-images.githubusercontent.com/13136714/54871103-86576200-4daf-11e9-8523-c83d225d11cd.png)

And there's a good reason for escaping it as Java 8 treats properties files as ISO-8859-1 while Java 9 and onwards parses them as UTF-8!

**Comment by TuxPaper** [comment]
I know Android Studio (Which is just Intellij + Google Junk) loves to suggest replacing three actual dots "..." with the unicode equivalent, as it keeps telling me every time I write 3 dots :P  I'll check to see what unicode it keeps suggesting the next time I fire up Android Studio.

**Comment by lislei** [comment]
The fix removed almost all of the squares. It's looking way better, but there are still some left.
Here's what my search looks like on tip of the master brach;
![bilde](https://user-images.githubusercontent.com/13136714/55279882-64655e80-531e-11e9-9403-6779d2aabe0d.png)
