### ISSUE TITLE
[FEATURE REQUEST] Duplicate detection.

### ISSUE THREAD

**Issue by alexandru5500** [BiglySoftware/BiglyBT#969]
Hello Prag, 

Please tell me if it's possible to have implemented a method to detect duplicate names for torrents for cases when we rename them after loading.

I think also that function to auto-rename duplicate names of torrents at loading is not working properly.

Waiting for your feedback.

Best regards,
Alexandru.

* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment

**Comment by parg** [comment]
Hmm, what do you mean? You can't have two torrents with the same hash loaded at the same time in BiglyBT (well you can but only under very strict circumstances that you probably haven't encountered). Maybe an example would help?

**Comment by alexandru5500** [comment]
Hello Prag,

I'm speaking about two torrent files with the same name with different hashes, located in different folders at loading.
In this case, BiglyBT should auto-rename the second torrent to <name>.<something> to make a difference between them. Also to set downloading folder different for each one on default location.

In the second case let's say that we have two torrents already loaded with <name1> and <name 2>.
Now it is possible to rename <name1> to <name2> without any warning.

Waiting for feedback.

Best regards,
Alexandru.

**Comment by alexandru5500** [comment]
Hello Prag,

I'm speaking about two torrent files with the same name with different hashes, located in different folders at loading.
In this case, BiglyBT should auto-rename the second torrent to <name>.<something> to make a difference between them. Also to set downloading folder different for each one on default location.

In the second case let's say that we have two torrents already loaded with <name1> and <name 2>.
Now it is possible to rename <name1> to <name2> without any warning.

Waiting for feedback.

Best regards,
Alexandru.

**Comment by alexandru5500** [comment]
Hello Prag,

I'm speaking about two torrent files with the same name with different hashes, located in different folders at loading.
In this case, BiglyBT should auto-rename the second torrent to <name>.<something> to make a difference between them. Also to set downloading folder different for each one on default location.

In the second case let's say that we have two torrents already loaded with "name1" and "name 2".
Now it is possible to rename "name1" to "name2" without any warning.

Waiting for feedback.

Best regards,
Alexandru.

**Comment by alexandru5500** [comment]
sorry for repeating but ">" and "<" not working in this text box

**Comment by parg** [comment]
Internally it does rename as required (when storing torrent file in the 'torrents' folder in the BiglyBT config folder). 

So BiglyBT doesn't prevent you adding two torrents with the same name. I don't think it should auto-rename the download name shown within BiglyBT, I can't really see how that would help. If you have

MyLovelyPony.mp4
MyLovelyPony.mp4

shown in the library this is no less useful than some renamed

MyLovelyPony.mp4
MyLovelyPony_1.mp4

You still don't know what the difference is.

**Comment by alexandru5500** [comment]
Hello Prag,

I've got your point, was just a remark for the situation when you have a lot of torrents with the same name assigned to different tags, stored in different locations, some of them are completed, some of them are in progress, was useful to have this possibility. But I think I can manage it with a little care.

Best regards,
Alexandru.

**Comment by alexandru5500** [comment]
Hello Prag,

Sorry, I forgot to ask you if is possible to have one option to cancel the warning box when you are trying to add same torrent files (same hash check) multiple times because it's annoying when you try to add a lot of torrents already existing and only a few of them are new.

Best regards,
Alexandru.

**Comment by parg** [comment]
I've added something for the next beta
