### ISSUE TITLE
Swarm discoveries in tor+i2p mode

### ISSUE THREAD

**Issue by mppdidi** [BiglySoftware/BiglyBT#97]
Manual swarm discoveries work okay if I manually discover related - is there a way to automate this ?

Thanx in advance

**Comment by parg** [comment]
If you do a manual discovery on an I2P only download then this should cause the swarm discoveries to run over I2P - I'll look into adding a way to switch the default discoveries to run over I2P

**Comment by parg** [comment]
Just to check, are all your downloads set as 'I2P Only'? If they are then in theory the discoveries stuff should run over I2P. If they are set as mixed (I2P+clearnet) (see Privacy tab) then swarm discoveries will use clearnet and not I2P.

**Comment by mppdidi** [comment]
Yes the privacy tab is the issue - there is no way to set this via action on maybe ?

**Comment by mppdidi** [comment]
Already figured the stuff you mentioned - i'll give it a try as soon as you push a new beta.
Thank you so much !

**Comment by mppdidi** [comment]
Sweet + neat !
Thumbs up - hands down ;-)
