### ISSUE TITLE
Updates to releases for beta channel users?

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#971]
I noticed this back in January with the release of 1.8.0.0 (see #827), but now again with 1.9.0.0 — it _feels_  a bit odd that users opted-in to the beta channel **only** receive beta version updates, and not the actual releases. For example, BiglyBT is currently preparing to update from `1.8.0.1_B36` to `1.9.0.1_B01`, skipping over the actual `1.9.0.0` release entirely.

Now, as I said, that _feels_ a bit odd — but maybe it isn't. If the releases are identical to the last beta prior to release, then there's no point in updating to `1.9.0.0` because I was already running that version (it was just called "`1.8.0.1_B36`"). But if there are any changes between the beta and the release builds (whether it's last-minute additions, removals, what have you), then it seems like it'd be good to have releases included in the beta channel as well, when they're the most current version.

So, I guess that's my question: Are the releases identical to the last beta preceding them? If they are, that's cool and this can be closed as "FOMO Resolved". :wink:

**Comment by TuxPaper** [comment]
Even if B36 and 1.9.0.0 are code identical (or B01 and 1.9.0.0), the beta has a number of things turned on, such as a second DHT, more debug, extra menu options.  In that respect, upgrading beta users to a release version might end up being confusing to beta users.

**Comment by ferdnyc** [comment]
@TuxPaper That makes sense, I hadn't thought about that.

For a moment I was tempted to say, "Why not roll a `_B00` beta-configured build alongside each release, and push that out to the beta users?" but then I realized that's dumb and pointless. Especially since `_B01` typically shows up within a few days of the release, at most.

**#FOMO** is a hell of a drug. Closing!
