### ISSUE TITLE
Documentation Request:  wiki/tags

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#974]
I finally found the Icon setting in the Tags Overview, under the Settings Tab at the bottom of the screen. It is not available from the Right Click on a Tag. And I am not asking for that to be changed.

What I am asking for is the the Wiki/Tags documentation be updated with info on the File Format and Dimensions for the Icon.  i.e. when I click the Icon setting, a file browser opens.  What kind of file am I looking for?  Can it use the DLL Icon libraries from the OS.  For example in windows: %SystemRoot%\System32\SHELL32.dll   And then Pick from the DLL Library.  Or is a standalone ICO or PNG or JPG or BMP, etc needed.  These are the things that beginners will be asking.

I've tries some ICO and PNG Icons from [www.iconarchive.com](http://www.iconarchive.com/)  When SET in Biglybt they look like crap.  Even the simplest b/w Icons do not look good. (See Attached)  Is this perhaps because the Icons I am using are Square, while the Tag Icons visually appear to be rectangular?  I suggest that under the Biglybt install path, that an ICON subdirectory containing a few example Icons might be helpful.

I also found right clicking the Icon Button is where the Reset is located. Not obvious for beginners. So mention in the Wiki.

I would also ask that all Wiki entries have a HELP link in Biglybt where needed.  Lower on the Tags Overview/Settings Tab in the Constraint section there is a Link for Tag Constraints.  But not for [Tags](https://github.com/BiglySoftware/BiglyBT/wiki/Tags).  Might be a good idea to make sure all Wiki entries are linked as Help as a matter of Habit.

![Film-2-icon](https://user-images.githubusercontent.com/37715552/55293599-199f2180-53c6-11e9-9113-5fdf83f02b38.png)  ![Movies-icon](https://user-images.githubusercontent.com/37715552/55293600-1c9a1200-53c6-11e9-95be-556552b595a7.png)

- Windows 10 1809
- Biglybt Beta 1.9.0.1_B01
- Java 1.8.0_201 (64 bit)

**Comment by NaPurHab** [comment]
Still have no idea what the size of icons is.  Adding to the Wiki would really help.

**Comment by parg** [comment]
They are resized based on context - menu items are 16x16,  in tag displays 20x14, other places resized to fit available space.
