### ISSUE TITLE
Renaming files contained within torrent, after being moved, do not reflect change

### ISSUE THREAD

**Issue by ms52538** [BiglySoftware/BiglyBT#976]
Windows X64 client

I've been noticing an issue for about the past full version of the client, it seems to have appeared shortly after initial release of 1800. I kept thinking it would resolve itself in a future beta release, but as of 1902 it has not, so thought I'd report it.

Here is the scenario:

Initial torrent, with multiple files contained within, completes. I move the torrent on a my drive to a different Windows 10 folder. I rename the torrent file, and the files within, giving each file within a unique identifier (i.e. Pic A, Pic B) tagged on as a suffix to the full torrent name:

C:\My Movies\2018\Comedies
\Joe's Pawn Shop (2018) 
...Joe's Pawn Shop (2018) (Joey, David, Lori, Frank).mp4
...Joes Pawn Shop (2018) Pic - A.jpg
...Joes Pawn Shop (2018) Pic - B.jpg

Now if I move the Torrent again to a different folder someplace else on my drive, the files will follow it, as normal. 

D:\New Movies I Like\A-List titles
\Joes Pawn Shop (2018)
\Joe's Pawn Shop (2018) 
...Joe's Pawn Shop (2018) (Joey, David, Lori, Frank).mp4
...Joes Pawn Shop (2018) Pic - A.jpg
...Joes Pawn Shop (2018) Pic - B.jpg

Let's say now I want to move just the .MP4 file to a different sub-directory, but higher than the torrent's location:

D:\New Movies I Like\A-List titles
\Joes Pawn Shop (2018)
**D:\New Movies\Joe's Pawn Shop (2018) (Joey, David, Lori, Frank).mp4**
...Joes Pawn Shop (2018) Pic - A.jpg
...Joes Pawn Shop (2018) Pic - B.jpg

And the file moves as expected.

Here is where then the problem occurs, it seems: If I now attempt to rename the file:
**D:\New Movies\Joe's Pawn Shop (2018) (Joey, David, Lori, Frank).mp4**
to anything, the change occurs on the Windows O/S level (on the hard drive) but the file name does not accurately update in the BiglyBT client.

I get this error a lot, as I move various torrents through 'work flow processes' of cleaning up file names, organizing the files, etc..

Hope you can reproduce. Yet again, you may already be aware.

Thanks as always!
:)

**Comment by parg** [comment]
hmm, I tried to follow your steps accurately but failed to reproduce the problem. Does it happen every time you do that? What if you 'pop out' the Library/FilesView, does the problem resolve itself? How about if you restart BiglyBT?

**Comment by ms52538** [comment]
I’ll do some more recording of steps to determine if there is something more specific to the issue occurring . Yes, the text with the client does update when the client is restarted. Will get back soon.

**Comment by ms52538** [comment]
I'm definitely duplicating the issue.
Here are a few screen shots of the flow I'm using, which shows the issue:
![1 - Starting Point](https://user-images.githubusercontent.com/20614244/55412121-d6af8c00-5534-11e9-8ec2-b6c21dcd070c.png)
![2A - Move video clips up one directory level, outside of torrent folder but in same folder as torrent folder](https://user-images.githubusercontent.com/20614244/55412127-d911e600-5534-11e9-9bf7-6de30937a136.png)
![2B - Now placing Quick Rename focus on one of the video clips moved up one directory level](https://user-images.githubusercontent.com/20614244/55412133-db744000-5534-11e9-9203-24741b70f400.png)
![3 - A completed Quick Rename of one of the moved video clips](https://user-images.githubusercontent.com/20614244/55412139-ddd69a00-5534-11e9-8a3a-728128d6ef1d.png)

These will illustrate the move file issue and impact on the name of the moved file, then a Quick Rename of the same file. 

Also, when I performed this test for you, everything worked as expected. However - there are times when I do this and the client ends up actually deleting the file and placing it in the recycle bin with an odd name, and created a new file (zero file size) in the original file's place - as if it has to re-download the file again within the torrent in order for the torrent to complete. When i perform a Revert File Location function on that file, the client returns it to the torrent folder but the file name still shows a Windows Recycle Bin name (and not the original torrent file name) so I'm guessing there is some tagging/connection the client is still doing with the file and creating the replacement file at zero file size?

Hope this helps.
Thanks as always!

**Comment by parg** [comment]
So, forgetting the weird recycle bin thing, your problem is that after the initial move to the parent folder the file name is shown incorrectly (truncated from "BowWowWow Dog Training Collection - Clip BWW 001.wmv" to " - Clip BWW 001.wmv" for example) ? 

If so then I can reproduce that much. Haven't looked into the caused but I'm guessing there is some logic that doesn't show the absolute file name if it appears to be in the download's folder and the fact that your file name starts with the same characters as the folder is confusing it and causing it to treat

<prefix><suffix> as <prefix>\<suffix> 

just wanted to verify that before diving in!

**Comment by ms52538** [comment]
I will say, the recycle box thing is getting annoying though.
Yes, you summed it up. The renamed DOES take place but it's not reflected in the Torrent middle in the middle of the screen. As you probably already saw, if you highlight any of those that do not appear correctly, the 'files' section at the bottom of the screen DOES SHOW the correct file name after renaming takes place.  :)  It's low priority.

**Comment by parg** [comment]
If you could find a way to reproduce the recycle thing that would be a great help!

**Comment by ms52538** [comment]
I should be able to do that this weekend for you. Also, quick question: the bottom section of the screen where files appear (i.e. I perform a Control "A" to highlight all torrents - let's say there are 1,000), the lower section then reflects, lets say 30,000 files. In that 30,000 files section I perform a search (i.e. "Delta"), and all the files that have "Delta" appear in that view. I'm at a loss of how to associate the file results back to their respective parent torrent files up in the mid section of the screen. I try using the "Torrent" column in the view but I can't link off it in a 'click' to open the torrent. If this makes sense?

**Comment by parg** [comment]
There's a 'Download Name' column that you can enable - unfortunately this doesn't give you a quick way of getting to the download. I could look into, say, a right-click option of 'go to download' - this would most likely result in the selection getting lost though so you'd only be able to do it once for a given search...

**Comment by ms52538** [comment]
It would be a new feature function - so to quote Shakespeare's Hamlet .... "Do it England"  :)

I'll look for the additional column for the time being.  :)

Gracias Senior!

**Comment by parg** [comment]
It'll be in B07

**Comment by ms52538** [comment]
Thank you! I'm still tracking the recycle bin issue; I'm not able to nail down the exact 'trigger' of events which causes it yet but am getting closer. It happened 3 times over the weekend, and I touched roughly 430 torrents and renamed and moved a slew of files contained with those. It has something to do with the sequence of events and creating a state where renaming/moving/renaming and recheck action which moved a good file to the recycle bin and replaces it with a copy of the file in it's place at zero bytes. Don't quote me on it, just trying to give you more general information - so please don't try to duplicate the issue yet. I may be pushing the limitations of the system's logs and tracking. Speaking of logging, is there a transactional log file the system is maintaining, that I could look at, when I see the problem occur? Again, thanks as always. :)

**Comment by parg** [comment]
There's no overall log for file operations within BiglyBT - you could have a look in the debug_1/2.log files to see if there's any clues in there, sometimes unexpected situations spew something there.

**Comment by ms52538** [comment]
Alright! I'm digging it. Not only brings into the focus the primary torrent file, but also scans and isolates the files within the torrent too in the other pane. The count down takes a bit when it has to search through 10,000 files, but I'll take what I can get. :)  Thank you!!
