### ISSUE TITLE
SOCKS proxy setup failed

### ISSUE THREAD

**Issue by saxsymbol1989** [BiglySoftware/BiglyBT#980]
I'm trying to set up a SOCKS proxy. The tests come out ok, but when my trackers try to connect I get the following error:

Error: offline -socks setup failed: SOCKS 5: udp association fails [reply=7]

How can I correct this error?

**Comment by parg** [comment]
Maybe your SOCKS proxy doesn't support UDP Associate - required for interacting with UDP based trackers.
