### ISSUE TITLE
Stop after Allocate, requires Check when Started. Why?

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#983]
I was testing the following setting:
![BiglyBT Allocate then stop](https://user-images.githubusercontent.com/37715552/55585094-df9a8c00-56f3-11e9-88e1-9af0d3e3aa5b.PNG)
My goal was to have a large group of torrents of similar size and seeds, Allocated and Stopped. Then see how quickly they got going and finished, when all started at the same time. Usually I don't use this setting and have to wait for each to allocate before they start.  Hence the Starting line for a Marathon.

Now the problem.  Allocate, Check.  Stop after Allocate, Check.  Start Torrents, Fail.
Why Fail, because it then starts Checking the Newly Allocated Torrents.   If this option is used, it is a Brand New Allocation. Hence should be clean and not need to be checked.

I assume you already have a Flag that tells if a torrent shut down cleanly. That triggers Checks when starting Biglybt after a not clean shutdown.  So perhaps this would be a method to prevent Newly Allocated Torrents using the 'Stop the download after files have been allocated' Option from being Checked when started.

I have replicated this 3 times.  Most of the reason I find this annoying is that Allocating and Checking each cause a significant speed drop due to the level of disk activity introduced when either is happening.  Normal Upload speeds for me is from 120-200 Mbits/s, but that drops to around 20 when Allocating or Checking. And considering I have 8 HDs, Allocating or Checking on 1 HD, should not effect the Upload speed for torrents on other drives so much.

So why does a Brand New Torrent that was Allocated then Stopped, but never used need to be Checked?

- Windows 10 1809
- Biglybt Beta 1.9.0.1_B03
- Java 1.8.0_201 (64 bit)

**Comment by parg** [comment]
Yup, not great that - please check the next beta (B04)

thanks!

**Comment by NaPurHab** [comment]
Seems to fix the problem.   Would it be possible to make it an Option on the 'Open Torrents' Popup Window.  Specifically the 'Add Mode' in the Start Options section.  Currently the options in Add Mode are:

Queued
Stopped
Force Started
Seeding

Since this is a drop down, lots of room for more choices.   So suggest an updated list would look like:

Queued
Allocate then Queue
Stopped
Allocate then Stop
Force Started
Seeding

Forced Start would allocate by default, and Seeding I assume is for importing torrents where the files already exist, so no need to allocate.

This idea would be an alternate to the All or Nothing 'Stop the download after files have been allocated' Option. As it could be chosen on case by case basis.

**Comment by parg** [comment]
Do you really decide on a per-torrent basis whether to 

stop-without-allocation
or
stop-with-allocation

? I'd have thought it was more of a global attitude to managing downloads.

**Comment by NaPurHab** [comment]
I generally would not use the Allocate then stop. As I add torrents at random.   But if I plan to download a batch of related torrents. (say 30 Seasons of the Simpsons)  I might wish to allocate then stop, so they are ready to start when I want them too.  I might be using bandwidth for something else and want to start them before I go to bed.  So allow them to allocate then stop means that when I do start them, they will go as soon as they connect. Great way to bulk load my connection to see how fast I can download.  I have 500/500 Fibre service. Best so far is the rare topping of 200 with peaks to 240. So having the option in the Open Torrents Popup in the Add Mode, means I can choose to ADD that option when I want to.

Another reason, I may have torrents I want to finish first.  Now I could use the add stopped, then pause. But I would have to turn that on Globally.  In fact that is an idea for the 'Add Mode' to be able to Add, Allocate, Stop then Pause.  Ready for a schedule to Resume all paused torrents.  So again, something that could be use when necessary.  So since the list is a drop down and has room, the list could look like:

Queued
Allocate then Queue
Stopped
Allocate then Stop
Paused
Allocate then Pause
Force Started
Seeding

Or you could shorten the list by having a Tick Bob beside the list for Allocate before Action. Like:

[ ] Allocate before:
- Queued
- Stopped
- Paused
- Force Started
- Seeding

Ultimately these are suggestions, up to you to decide if the are good.

**Comment by NaPurHab** [comment]
Beta 6 does the trick. I just tested it and works a charm.

I know this will annoy you but one more related I just found.

![BiglyBT Import Torrents](https://user-images.githubusercontent.com/37715552/55748131-dd923f00-5a0b-11e9-93f4-b6ecf04e9773.jpg)

At the bottom of the above image.  'Begin Stopped'  should be changed to include 'Allocate then Stop' and the pause when stopped option in the middle of the option.

Also, the Pause option in the middle of the image only applies when the 'By default add new torrents in a stopped state' is Set. _So the next line for the Pause should be indented._

Or you can try to make these look similar to the Add Mode you just changed in B06.

Reason for the above suggestions is that that Original idea for the Stop then Pause was part of changes to the Schedule. Here is what I used:

daily limited from 00:00 to 1:59 resume_tag:Paused
daily unlimited from 02:00 to 07:59 resume_tag:Paused
daily limited from 08:00 to 08:01 pause_tag:Downloading
daily limited from 08:00 to 23:59 resume_tag:Paused

That was when I had 25/10 Service with a 350GB Monthly Cap, and Unlimited Downloads from 2-8 am.  So adding a Pause to the 'Begin stopped' will allow those still using a schedule for control to include torrents from disk.  I could see new .torrent files being added this way, by linking a directory on a Desktop to a Laptop via OneDrive or GoogleDrive.  Then the .torrent would be imported and with the addition of a least a Pause option added. It would work with the Schedule to be Paused and ready to dance to the tune of the schedule.

I had forgotten about the import torrents from disk as I don't usually use them. But when I went to test the new Drop Down in Open Torrents. I decided to make sure the 2 related options were off in the Settings.  And I spotted the Import and thought that needs at least a pause option.

**Comment by parg** [comment]
Actually the 'when added in stopped auto-pause' is independent from the option above and shouldn't be indented. There is an obvious question regarding unification of all these various kind of options but I'm not going there at the moment...

**Comment by parg** [comment]
Next beta has same torrent import start options as add-torrent dialog

**Comment by NaPurHab** [comment]
Ok, I thought the Pause when Stopped only applied when stopped by default. So why I suggested it be indented.

One thought, for the Import Torrent. Should it have the Assign Tag, or leave the issue of Tags to the Auto-Tag.  Or perhaps have a Note on the Right under the Assign to Tag for Import that says "Leave Blank for Auto-Tagging".  So if blank, it fails to Auto-Tagging, or just remove the Assign to Tag and leave it to Auto-Tagging?  My thinking is that it should be left to Auto-tagging, so import of .torrents follow the same rules as Open Torrents. Less confusing for beginners if Tags are applied in a standard way.
