### ISSUE TITLE
Excessive White Space - Low Priority - But Annoying

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#984]
![BiglyBT Statistics White Space](https://user-images.githubusercontent.com/37715552/55586790-d3183280-56f7-11e9-9a5e-ee8f2765d87d.PNG)

As you can see in the above clip. There is a lot of wasted space between the columns.  If tidied up the info in the Downloaded and Uploaded columns would not be clipped with '...'.  Also the SOCKS box could be made Optional. Such that if Inactive it would not be shown. This too would create extra space to prevent the truncation of the Downloaded and Uploaded columns.

Likewise at the bottom the the Clip, the **Connection Details** also shows the '...' clipping of the displayed info. When there is clearly a lot of empty space to the right.

Low priority Issue, but annoying when I can't read the full entries in the columns.

- Windows 10 1809
- Biglybt Beta 1.9.0.1_B03
- Java 1.8.0_201 (64 bit)

**Comment by parg** [comment]
I fiddled with it a bit in next beta

**Comment by NaPurHab** [comment]
![BiglyBT Statistics White Space](https://user-images.githubusercontent.com/37715552/55691688-c18c9000-596e-11e9-9d66-14d5033ff4d1.PNG)

Above is what the fiddling achived.  You can still see a bit of truncating on the first line of the Uploaded section.  Below I a photoshopped version that shows a better use of the space.  It will be a good guideline.  There are 5 sections, Labels, Downloaded, Uploaded, Ratio and Up Time.  By making columns 1, 4 & 5 narrow and Fixed, and then using all remaining as a 50/50 split for column 2 & 3. It should solve the truncating.

![BiglyBT Statistics White Space 2](https://user-images.githubusercontent.com/37715552/55691799-f5b48080-596f-11e9-8f4a-5cba3b90773f.png)

Still think that if the Socks Section is Inactive or Disabled that it could be hidden when not needed.  I suspect that VPN has for the most part replaced SOCKS.  It might be time to Retire SOCKS support in Biglybt.  Likewise there are lingering traces of Categories that Tags replaced.  The Beta cycle might be a good time to finally finish purging Categories.

- Windows 10 1809
- Biglybt Beta 1.9.0.1_B05
- Java 1.8.0_201 (64 bit)

**Comment by NaPurHab** [comment]
While we are still in a beta cycle, perhaps you can look at the above and fiddle with it a bit more to get rid of the last of the truncating.
