### ISSUE TITLE
BiglyBT with nordVPN

### ISSUE THREAD

**Issue by cwaynedavis1946** [BiglySoftware/BiglyBT#985]
Java 1.8.0_201 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_201

SWT v4922, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B1.9.0.0/4 az3

I will greatly appreciate any help/advice I can get on this.  I had this problem with Vuze and nordVPN so upgraded to BiglyBT but no improvement.

I am thoroughly confused about configuring BiglyBT for use with nordVPN.  I used vuze many years ago without a vpn and had no problems.  Now I've been going back and forth with this but have no idea if I have it setup right.  Most of the information I found in forums seems to be outdated or doesn't apply.  The nordVPN representatives have been of only limited help.  Basically they've told me that all I have to do is connect nordVPN to one of their p2p servers, which I have.  I've examined logs but can't figure it out.  I've gone through all the Vuze documentation, including the best practices, and ensured that all settings are as recommended.

I think nordVPN is handling port forwarding for BiglyBT but the nord people don't answer my questions about that.  Is it significant that the BiglyBT NAT/Firewall test fails for inbound connections or is this normal when using a vpn?  The network status test also fails for inbound connections.

Transfers are working, uploads are constantly at or near the limit.  Downloads are happening but don't seem to be working properly.  The NAT OK icon in the BiglyBT status bar is usually green, as it is now, but only one of the download health icons is green, the rest are all blue.  Only 3 downloads are active, none are being started automatically.  I have to force start them.  I'm currently downloading at 223.7 kB/s, uploading at 263.9 kB/s.

Results from speedtest, with all torrents paused:
ping 99 ms
download 26063 kbps
upload    2684 kbps

Ran BiglyBT configuration wizard:

M-Lab Network Diagnostic Tool:

Pausing downloads before performing test...................................................
TCP/Web100 Network Diagnostic Tool v3.6.2b
** Starting test 1 of 1 **
Connecting to 'ndt.iupui.mlab2.mia02.measurement-lab.org' [ndt.iupui.mlab2.mia02.measurement-lab.org/38.109.21.24] to run test
Connected to: ndt.iupui.mlab2.mia02.measurement-lab.org--  Using IPv4 address
Checking for Middleboxes  . . . . . . . . . . . . . . . . . .
Done.
Checking for firewalls . . . . . . . . . . . . . . . . . . .
Done.
running 10s outbound test (client-to-server [C2S]) . . . . .
2.71Mb/s
running 10s inbound test (server-to-client [S2C]) . . . . . .
19.57Mb/s
The slowest link in the end-to-end path is a
10 Mbps Ethernet subnet
Information: Other network traffic is congesting the link
Completed: up=331.2 kB/s, down=2.33 MB/s
-----------------------------------------
M-Lab Details Tab:
The theoretical network limit is 18.53 Mbps
The NDT server has a 391.0 KByte buffer which limits the throughput to 141.87 Mbps
Your PC/Workstation has a 1078.0 KByte buffer which limits the throughput to 195.38 Mbps
The network based flow control limits the throughput to 55.83 Mbps
Client Data reports link is 'Ethernet', Client Acks report link is 'Ethernet'
Server Data reports link is 'OC-48', Server Acks report link is 'OC-48'
Information: Network Middlebox is modifying MSS variable
Information: Network Address Translation (NAT) box is modifying the Client's IP address
Server says [38.109.21.24], but Client says [63449]
Information: Network Address Translation (NAT) box is modifying the Client's IP address
Server says [185.245.86.57], but Client says [1528]
Completed: up=331.2 kB/s, down=2.33 MB/s

--------------------------------------------------------
BiglyBT Help->NAT/Firewall test:

Testing TCP port 46237 inbound
  Test failed: NAT test failed: Error connection reset
  check port forwarding for TCP 46237
Testing UDP port 46237 inbound
  Test failed: inbound test failed
  check port forwarding for TCP 46237
----------------------------------------------------------
BiglyBT Help->Network Status test:

outbound tests ok
Testing UDP port 46237 inbound
 Test failed: NAT test failed: Connect attempt to ... failed your port is probably closed.  Check port forwarding ...
Testing UDP port 46237 inbound
 ... test failed ... check port forwarding
indirect connect test result ok
...
Distributed protocol test
  ...
   3 outbound failed, 9 ok
...
No incoming connections received, likely NAT problems.
------------------------------------------------------
I've tried everything I could come up with but gotten nowhere.

Thank you.

**Comment by TuxPaper** [comment]
NordVPN doesn't support Port Forwarding, so BiglyBT will almost always report being (partially) firewalled.

https://support.nordvpn.com/Getting-started/1047408432/Do-you-offer-port-forwarding.htm

Not sure if we can help you with the speed or connections. It could be the server/country you choose, how congested the vpn server is, etc.  For more peers, you can try a more popular torrent from a more popular tracker that has a lot of active peers.  The "Mainline DHT" plugin also can pull in more peers

**Comment by cwaynedavis1946** [comment]
Thank you.  I'm not sure what impact the lack of port forwarding has on torrenting.  Should I switch to a vpn that provides it?

I'm making sure that I select a vpn server near me that supports P2P and has a good load factor.  I don't know enough about torrenting to know how to find more popular torrent/trackers but I'll search for more info.  I'll also try the Mainline DHT plugin, thanks for suggesting it.  Can you recommend any good guides for plugins?  I haven't looked into this before but obviously should.

**Comment by NaPurHab** [comment]
I use Purevpn.  The client supports Split Tunneling.  That creates a PPP1 entry that Biglybt can use.  As to Port Forwarding, you need to use a Fixed entry in Biglybt and Purchase the Portforwarding Addon from Purevpn.  Then you need to portforward  the Biglybt port you choose plus the mlDHT port 49001.
There a lots of VPN services available.  If you need Port Forwarding, I suggest detailed research.
