### ISSUE TITLE
error on start torrents

### ISSUE THREAD

**Issue by alexandru5500** [BiglySoftware/BiglyBT#986]
Hello Parg,

When I'm starting torrents, more often for torrents with a big number of files, they are going in the error state, some of them with the only error message without additional details, some of them with an error that a file is not found. If I stop them and start one by one usually they are starting correctly but there also few that I need to do a hash check before to be possible to start them. This is happening even after a BiglyBT restart when everything was ok.

Waiting for feedback.

Best regards,
Alexandru.

* OS: Debian Stable
* BiglyBT: latest beta
* For *nix: XFCE

**Comment by parg** [comment]
So this is a new problem with B04 that you've never seen before?

**Comment by alexandru5500** [comment]
Hello Parg,

No, I think this is happening in 1.9.0.0 also, maybe in older versions too.

Best regards,
Alexandru.
