### ISSUE TITLE
regression: "do not download" files are fully allocated when download is started

### ISSUE THREAD

**Issue by bughit** [BiglySoftware/BiglyBT#988]
v1.9.0.0, win7, Oracle Java 1.8.0_202 (64 bit)

- torrent is added stopped
- some files are set to not download
- at this point the files don't yet exist (as normal)
- torrent is started
- all files (including "do not download")  are created full size
- in prior versions the "do not download" files were either not created or created 0 size, it may have flipped between not at all and 0 at some point, not sure

file settings
![image](https://user-images.githubusercontent.com/895588/55679548-89883d00-58db-11e9-8e93-c7d983bc03ab.png)

With the above settings, only downloaded and overflow files should be created

**Comment by parg** [comment]
There was a fix in 1900 to make the handling of 'delete' and 'do not download' file 'priorities' work more consistently. In particular, once a download has been added, using the check-box in the FilesView will toggle the file between 'normal' and 'do not download'. The latter will cause the files to be created when started.

You can work around this by using the right-click menu's 'set priority->delete' to cause the files not to be allocated.

I'll look into seeing if the check-box based deselection behaviour can toggle between normal/delete for downloads that haven't been started.

**Comment by bughit** [comment]
- It's not just just the checkbox, I had been setting "do not download" via multi-selection and context menu, and this worked reasonably, as one would expect.
- If a file is set to not download, **before it's created**, it makes no sense to then create and allocate it. Don't understand why you call this a fix, maybe it's cleaner internally, but from the user perspective it's a bug.
- Also choosing "delete" for something that does not exist is not intuitive, one does not "delete" future files, one prevent their creation, so "do not download" is a more intuitive/natural choice.

**Comment by parg** [comment]
Do-not-download does not mean do-not-allocate.

Use 'Delete' if you want the files to not be created.

**Comment by bughit** [comment]
> Do-not-download does not mean do-not-allocate.

For files that had not been created, it did and it should.

If a file is set to not download, before it's created, it makes no sense to then create and allocate it.

You are performing a completely absurd and harmful operation (stealing potentially huge amount of disk-space you know you don't need), in the name of nonsensical "consistency".
