### ISSUE TITLE
PIA Manager, Where is it After PIA Upgrade? ".PIA_Manager.app now considered legacy software"

### ISSUE THREAD

**Issue by Swampgirl** [BiglySoftware/BiglyBT#989]
Hi, I just tried to change from PIA to a new VPN. After frustration with not knowing how to configure the new VPN, I reloaded PIA, and I finally downloaded a new copy of BBT (I am in the beta program, and my BBT software had developed interesting idiosyncrasies). So I went to find the .pia_manager.app, and I cannot find it. Where is it these days? Is it called something else now?

I've pulled out all of my hair.
Warm Regards,
Swampgirl

OS: mac OS Sierra
BBT Version 1.9.0.1_B05
PIA Version 1.1.1 (Build 02545)

* OS and version
* BiglyBT Version Number
* For *nix: Desktop Environment

**Comment by Havokdan** [comment]
https://plugins.biglybt.com

It has some plugins that say it is for such purpose.

**Comment by Swampgirl** [comment]
Thank you Havokdan! However, what the PIA plugin requires is for the BBT user to browse to the .pia_manager.app.  I have been doings this with ease for years, even before the event of BiglyBT. After updating both BBT and PIA, I was unable to find the manager app. I looked everywhere. It is a hidden file that I have never had trouble finding before. PIA, however, have updated their entire interface. And now I cannot find it, and if it called something else, I do not know what that is.

Thank you for your help.
