### ISSUE TITLE
magnet download problem

### ISSUE THREAD

**Issue by szh7379** [BiglySoftware/BiglyBT#99]
* OS win10 
* biglybt all Version 
magnet can work good in qbittorrent, just add it, it will download meta background, but in biglybt, you must wait the meta downloaded, then click start.   several times, same device, same source, qbittorrent can download it, but biglybt suck in the meta downloading  or work tens minutes later.

**Comment by parg** [comment]
send me an example bad magnet (paul@biglybt.com) and I'll take a look

**Comment by szh7379** [comment]
which i get this issue is  a source release in a few time, i can ensure it will appear again after several hours. it download the same soure's meta successfully now.

**Comment by szh7379** [comment]
I get another problem again, it should happen in biglybt, i download the embdded player failed, the second plugin   plugins_vuzexcode-win32_0.9.2.zip, it stay at 5.4% all the days. today i copy the magnet link to qbittorrent, it download successfully,  then biglybt discover it in the local network, and finish it. it is biglybt's plugin, it should be rasy in biglybt, but i success in qbittorrent. i am behind a NAT network, but qbittorrent work fine, so i think network is not a problem. 

as the problem i got. maybe  biglybt can't get meta data from nittorrent's client via mlDHT, but bittorrent client can get data from biglybt's DHT.

**Comment by parg** [comment]
There's something basically wrong with your setup. Can you go to the Help menu, select the last option there to generate a debug.zip file and then send it to me at paul@biglybt.com? thanks

**Comment by mppdidi** [comment]
I verified this against I2P snark - the BBT client does not gather the metadata correctly at all.
The console debug did not reveal a reason as to why this is.
Any ideas / logging that might help ?

**Comment by mppdidi** [comment]
Just to clarify my scenario - downloaded torrent via magent link on mixed node.
Pasted same magnet url on another pure i2p bbt node - metadata never got loaded.
Pasted the same magnet url to i2psnark - download of metadata and torrent succeded.

**Comment by parg** [comment]
Well I just grabbed a magnet for a reasonably well seeded I2P torrent, loaded it in BBT and it downloaded the metadata just fine via connections to I2PSnark peers, so not sure what the problem is. Perhaps you could email me the magnet so I can test: paul@biglybt.com

**Comment by mppdidi** [comment]
This is so strange, some magnet links work perfectly.
The only thing that is different is that the 'problematic' magnet url does not get saved across restarts.

**Comment by mppdidi** [comment]
It seems there was a problem with DDB + DTR plugin, after doing a config from scratch the magnet url's worked just fine.

**Comment by mppdidi** [comment]
Am I getting this right - are the distributed database and tracker necessary for the i2p helper dht ?

**Comment by parg** [comment]
Possibly...

**Comment by hasandiwan** [comment]
I've gotten this a few times, refreshing the magnet link seems to sort the problem -- OSX Catalina.
