### ISSUE TITLE
Drag/drop torrent into a incomplete category view no longer works

### ISSUE THREAD

**Issue by david-bakin** [BiglySoftware/BiglyBT#992]
(Windows Server 2016; BiglyBT Beta (1.9.0.1_B08))

It's been working all along, and I'm sure it was still working in B06.  But now the incomplete category view is no longer a drop target.  (You get the universal circle/slash icon.)  Still works in downloading category view though.

I'm nearly always showing and using the incomplete category view.  That's just the way I roll.

BTW, speaking of B06: I really like the new options on adding a torrent - paused, stopped+alloc, etc..  I prefer to see "active" or "pending" torrents in incomplete as downloading or paused.  Not stopped.  Don't know why, that's just the way I like it.  (Not sure if there's a practical difference between paused and stopped.)

**Comment by david-bakin** [comment]
I have found a workaround: The category label itself "Incomplete" is a drop target.  Needs a bit more accuracy ... but I can manage that ...

**Comment by parg** [comment]
Hmm, can you explain what you mean by 'incomplete category view' - there isn't an automatic incomplete category, there is an 'Incomplete' auto-tag but you can't manually add/remove things from that. I know, I'm sure I'm asking a stupid question but bear with me!

As for the difference between stopped and paused - at one level they are the same (a paused download is a stopped download with a flag set to say 'hey, I'm paused'. The main functional difference is that 'resume-all' will resume paused downloads (but not stopped ones).

**Comment by parg** [comment]
By the way, if you're talking about dragging .torrent files onto the Library views of BiglyBT to add them I found a bug that could causes dropping onto an empty part of the library to stop working if you had previously dragged existing downloads either within the library or from the library to the sidebar.

**Comment by david-bakin** [comment]
Well, even though I've been using BiglyBt for several years I don't have all the names down.  Or features.  So categories, tags, etc: I don't know the difference.

So I think I _am_ talking about dragging .torrent files onto the Library view - that is, I click on the "Incomplete" tab that's on the left sidebar under "My Torrents" and I see a grid - and I drag/drop onto the empty part of the grid.

Anyway, seems to be fixed now in B09 as you said!

And my only other question is: In the B09 release notes you say "remove drag+drop sidebar target _cheese_".  "Cheese"?  Some kind of technical term?

Thanks for your work on BiglyBT, the best of the torrent clients!

**Comment by parg** [comment]
Search https://www.uxmatters.com/mt/archives/2014/05/the-secret-to-making-ux-a-top-priority-in-agile.php for 'cheese' :)
