### ISSUE TITLE
Creation of NEW Tag - does not appear in Tag drop-down list view

### ISSUE THREAD

**Issue by ms52538** [BiglySoftware/BiglyBT#993]
Windows, B08

Click on a torrent file and attempt to create and NEW tag and assign it - and the initial process works correctly as it should. But then attempt to take another torrent file and Tag it from the drop-down list of existing Tags, and the new Tag new just created in the previous step does not appear in the drop-down list. A restart of the client does not resolve the matter. Nor, if downloading a brand new torrent with the download pop-up view enabled for the pre-assigning of information (i.e. you are loading a brand new torrent into the client for download) - the newly created Tag does show, but it is greyed out and is not selectable. 

Workaround for the issue is to simply create a NEW Tag each time you want to tag a torrent file, and it will appear in the Dashboard View of "My Torrent" with the green label along with other torrents that you assign the tag to. i.e. I had to create 4 NEW tags of the same name, individually for 4 torrent files, and they then all appeared correctly in the My Torrents view under the TAG name. :)

FYI, Captain.

**Comment by parg** [comment]
Hmm! I'm not seeing this with a few experiments. 

Tags that you create should only be hidden/not-selectable with they have constraints or other aspects that makes them auto-assign.

Please spell out the exact steps you are using to reproduce the issue. For example, is the first step a 'right-click on the torrent in the Library, select the Organize tab of the menu and then Tags->Add Tag...'?

There are many ways of doing things in BiglyBT, it may just be one path that you are using that leads to the issue.

**Comment by ms52538** [comment]
And here I thought I had done a better job of explaining the issue this time out. LOL  

Here goes:
Dashboard/My Torrents/ Library view: left-click select a torrent file in the library. Right-click that selected torrent name, then in the pop-up box left-click Organize, left click TAGS. You now see existing tags you've created in the past in this TAGS view, but we are going to create a NEW tag, so left-click "Add tag", and a new pop-up window appears and you can create the name for the new tag. Process complete.

Now, go back to the Dashboard/My Torrents/Library view: left-click and select a torrent file (different from the one above). Right-click that selected torrent name, then in the pop-up box left-click Organize, left click TAGS. [Here is where the problem resides - the newly created tag in the step above does NOT appear in the list of possible tag names to select from if you want to assign it in the list in the pop-out box. Normally it appears here for me, and now it's not.]

**Comment by ms52538** [comment]
Whatever you did, B09 has resolved the issue. :)  Thank you, Captain
