### ISSUE TITLE
Stop Restart BiglyBT Dialog From Stealing Focus

### ISSUE THREAD

**Issue by brazenvoid** [BiglySoftware/BiglyBT#994]
Is there an option to disable this behavior? 

It is certainly extremely frustrating to be switched to BiglyBT whenever an update arrives. For beta program participants (like me) this is a constant issue. 

--- Rant Starts ---
Obviously with such a rapid pace of development going on for BiglyBT, this has happened many times now, but highlights include: 
- While doing a screen share to assist my employees, the view gets switched to BiglyBT with all my torrents for all to see... 
- While reveling in a problem solving high, putting out an incredible solution in code and the view gets switched to BiglyBT... 
- While having an intense firefight and an enemy gets up close n personal, you hit the melee key AND the view switches to BIGLYBT... 

--- Rant Ends ---

* Windows 10 x64 1809
* BiglyBT 1901B09

**Comment by parg** [comment]
There's an option under

Tools->Options->Interface->Alerts: Reduce situations where the main window is automatically shown

Don't know if it'll help with the restart prompt but you could try it.

**Comment by brazenvoid** [comment]
I'll let you know in either case. Thanks!

**Comment by brazenvoid** [comment]
It works thanks!
